# S&P 500 Options: NLinear

This notebook snapshots the complete three-model sequence population before fitting its NLinear
member. `09a_lstm` and `09b_patchtst` execute the other declared members against the same
immutable population. Every configured checkpoint remains eligible for model analysis and
backtesting.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit NLinear within the declared S&P 500 options sequence population."""

import polars as pl

from case_studies.research import supersedes_for_run
from case_studies.sp500_options.research_workflow import (
    ALL_LABELS,
    declared_dl_device,
    model_request_catalog,
    open_study,
    published_dl_device,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_subset,
    run_resolved_model_requests,
    snapshot_official_model_catalog,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
PREVIEW_REDUCTIONS: dict = {}
DEVICE: str = ""

SEQUENCE_CONFIGS = ("nlinear", "lstm_h64", "patchtst")
POPULATION_NAME: str = ""
SUPERSEDES_POPULATION: str = "7a9dc8881c9e"

### The device the population was fitted on

A network trained on a GPU and the same network trained on a CPU accumulate their sums in a
different order and reach different weights, so the device is part of what the fitted model is
and sits inside the training identity rather than beside it. The device this population was
fitted on is declared once, in `modeling.dl.device` in `config/setup.yaml`, and read from there
by all four deep-learning notebooks rather than retyped in each. On a machine with no NVIDIA
card the run stops here rather than quietly training something else: set `DEVICE="cpu"` and pass
a `POPULATION_NAME` to fit the same requests there, under a name of their own.

In [3]:
CANONICAL_POPULATION_NAME = "sp500-options-sequence-validation-v1"

published_device = published_dl_device()
device = declared_dl_device(DEVICE)
population_name = POPULATION_NAME or CANONICAL_POPULATION_NAME
if device != published_device and population_name == CANONICAL_POPULATION_NAME:
    raise ValueError(
        f"this run fits on {device!r}, not the published {published_device!r}, so its "
        f"identities are not the ones {CANONICAL_POPULATION_NAME!r} holds; pass "
        f"POPULATION_NAME to give them a population of their own"
    )
print(f"training device: {device} (declared: {published_device})")

training device: cuda (declared: cuda)

## Complete sequence request population

The case-wide table is resolved before the first member executes. Canonical execution snapshots
all configuration-checkpoint identities so a failed member cannot disappear from later analysis.

**A name holds one generation at a time**, and this notebook is the only one that writes this
population - `09a_lstm` and `09b_patchtst` execute members of a snapshot that already exists.
Anything that moves a training identity moves every prediction hash with it, so the members
this run computes are no longer the members an earlier snapshot under the same name declared,
and those two notebooks then refuse their own work as undeclared. `SUPERSEDES_POPULATION`
names the snapshot such a run retires, and the value is part of what the population is hashed
over. The value here names the snapshot this run retires; it is empty only for the first
snapshot under a name.

`create` refuses a changed member list under an existing name unless this names the current
snapshot, so the parameter is what makes refreshing this population possible at all. Without
it the refit stops at the write with the hash it needs, which is the right failure but not
one this notebook could act on.

In [4]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
all_requests = model_request_catalog(
    "deep_learning",
    labels=ALL_LABELS,
    config_names=SEQUENCE_CONFIGS,
)
all_resolved = resolve_model_requests(
    study,
    all_requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": device},
    preview_reductions=PREVIEW_REDUCTIONS,
)
resolved_model_plan(all_resolved)

shape: (3, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 9be44756 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 048d     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ f4874ea1 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 9561     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 10506ca4 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 9b0c     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute NLinear

NLinear shares the gap-safe sequence construction, fold boundaries, fitted-state persistence,
restart, and exact eligible-key checks used by the other sequence configurations.

In [5]:
nlinear_resolved = tuple(
    request for request in all_resolved if request.spec["config_name"] == "nlinear"
)
if len(nlinear_resolved) != 1:
    raise ValueError("the sequence population must contain exactly one NLinear request")

if EXECUTION_TIER == "canonical":
    population = snapshot_official_model_catalog(
        study,
        all_requests,
        population_name=population_name,
        resolved_requests=all_resolved,
        supersedes=supersedes_for_run(
            study,
            population_name=population_name,
            declared=SUPERSEDES_POPULATION or None,
            execution_tier=EXECUTION_TIER,
        ),
    )
    execution, population = run_official_model_subset(
        study,
        nlinear_resolved,
        population=population,
    )
else:
    if not WORKSPACE or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, nlinear_resolved)
    population = None

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=80,175 seq across 532 symbols
    val=56,536 seq across 556 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.801500

      epoch   2/100: train_loss=0.694972

      epoch   3/100: train_loss=0.683949

      epoch   4/100: train_loss=0.678515

      epoch   5/100: train_loss=0.674882, val_loss=0.588932, IC=-0.0096

      epoch   6/100: train_loss=0.677645

      epoch   7/100: train_loss=0.674611

      epoch   8/100: train_loss=0.670630

      epoch   9/100: train_loss=0.668805

      epoch  10/100: train_loss=0.672047, val_loss=0.595842, IC=-0.0136

      epoch  11/100: train_loss=0.669606

      epoch  12/100: train_loss=0.669007

      epoch  13/100: train_loss=0.669517

      epoch  14/100: train_loss=0.666926

      epoch  15/100: train_loss=0.668677, val_loss=0.596094, IC=-0.0176

      epoch  16/100: train_loss=0.666974

      epoch  17/100: train_loss=0.667748

      epoch  18/100: train_loss=0.669532

      epoch  19/100: train_loss=0.667156

      epoch  20/100: train_loss=0.665530, val_loss=0.594821, IC=-0.0160

      epoch  21/100: train_loss=0.667014

      epoch  22/100: train_loss=0.666038

      epoch  23/100: train_loss=0.664955

      epoch  24/100: train_loss=0.663247

      epoch  25/100: train_loss=0.666917, val_loss=0.597249, IC=-0.0175

      epoch  26/100: train_loss=0.663611

      epoch  27/100: train_loss=0.666637

      epoch  28/100: train_loss=0.663932

      epoch  29/100: train_loss=0.663722

      epoch  30/100: train_loss=0.663513, val_loss=0.597363, IC=-0.0155

      epoch  31/100: train_loss=0.668471

      epoch  32/100: train_loss=0.665699

      epoch  33/100: train_loss=0.667025

      epoch  34/100: train_loss=0.662943

      epoch  35/100: train_loss=0.668790, val_loss=0.600626, IC=-0.0159

      epoch  36/100: train_loss=0.664913

      epoch  37/100: train_loss=0.667428

      epoch  38/100: train_loss=0.668474

      epoch  39/100: train_loss=0.663639

      epoch  40/100: train_loss=0.665714, val_loss=0.598618, IC=-0.0175

      epoch  41/100: train_loss=0.665645

      epoch  42/100: train_loss=0.669320

      epoch  43/100: train_loss=0.663937

      epoch  44/100: train_loss=0.665851

      epoch  45/100: train_loss=0.666157, val_loss=0.599591, IC=-0.0169

      epoch  46/100: train_loss=0.664342

      epoch  47/100: train_loss=0.664448

      epoch  48/100: train_loss=0.662481

      epoch  49/100: train_loss=0.665609

      epoch  50/100: train_loss=0.662238, val_loss=0.598693, IC=-0.0179

      epoch  51/100: train_loss=0.662984

      epoch  52/100: train_loss=0.664519

      epoch  53/100: train_loss=0.665643

      epoch  54/100: train_loss=0.666200

      epoch  55/100: train_loss=0.664268, val_loss=0.597940, IC=-0.0173

      epoch  56/100: train_loss=0.662774

      epoch  57/100: train_loss=0.664214

      epoch  58/100: train_loss=0.669537

      epoch  59/100: train_loss=0.666862

      epoch  60/100: train_loss=0.666911, val_loss=0.596728, IC=-0.0183

      epoch  61/100: train_loss=0.664704

      epoch  62/100: train_loss=0.664199

      epoch  63/100: train_loss=0.663338

      epoch  64/100: train_loss=0.666149

      epoch  65/100: train_loss=0.664840, val_loss=0.598728, IC=-0.0165

      epoch  66/100: train_loss=0.664954

      epoch  67/100: train_loss=0.662667

      epoch  68/100: train_loss=0.666653

      epoch  69/100: train_loss=0.666718

      epoch  70/100: train_loss=0.665716, val_loss=0.598588, IC=-0.0176

      epoch  71/100: train_loss=0.664605

      epoch  72/100: train_loss=0.665703

      epoch  73/100: train_loss=0.667372

      epoch  74/100: train_loss=0.663070

      epoch  75/100: train_loss=0.665379, val_loss=0.597917, IC=-0.0174

      epoch  76/100: train_loss=0.664636

      epoch  77/100: train_loss=0.663643

      epoch  78/100: train_loss=0.663975

      epoch  79/100: train_loss=0.663996

      epoch  80/100: train_loss=0.664466, val_loss=0.598795, IC=-0.0174

      epoch  81/100: train_loss=0.665806

      epoch  82/100: train_loss=0.667239

      epoch  83/100: train_loss=0.664051

      epoch  84/100: train_loss=0.665800

      epoch  85/100: train_loss=0.662377, val_loss=0.598331, IC=-0.0176

      epoch  86/100: train_loss=0.664040

      epoch  87/100: train_loss=0.662893

      epoch  88/100: train_loss=0.662494

      epoch  89/100: train_loss=0.663667

      epoch  90/100: train_loss=0.669171, val_loss=0.598368, IC=-0.0170

      epoch  91/100: train_loss=0.665146

      epoch  92/100: train_loss=0.662211

      epoch  93/100: train_loss=0.664351

      epoch  94/100: train_loss=0.666694

      epoch  95/100: train_loss=0.664506, val_loss=0.598470, IC=-0.0172

      epoch  96/100: train_loss=0.664371

      epoch  97/100: train_loss=0.665065

      epoch  98/100: train_loss=0.664656

      epoch  99/100: train_loss=0.665141

      epoch 100/100: train_loss=0.662396, val_loss=0.598397, IC=-0.0171

      best_ep=5, IC=-0.0096 (100.5s, 20 checkpoints)

  Fold 1: creating sequences...

    train=94,348 seq across 522 symbols
    val=28,547 seq across 582 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.683362

      epoch   2/100: train_loss=0.619571

      epoch   3/100: train_loss=0.614904

      epoch   4/100: train_loss=0.608013

      epoch   5/100: train_loss=0.609382, val_loss=2.276906, IC=+0.0142

      epoch   6/100: train_loss=0.604272

      epoch   7/100: train_loss=0.604286

      epoch   8/100: train_loss=0.602416

      epoch   9/100: train_loss=0.604901

      epoch  10/100: train_loss=0.608340, val_loss=2.279229, IC=+0.0100

      epoch  11/100: train_loss=0.603394

      epoch  12/100: train_loss=0.602507

      epoch  13/100: train_loss=0.601308

      epoch  14/100: train_loss=0.600563

      epoch  15/100: train_loss=0.600125, val_loss=2.297883, IC=-0.0175

      epoch  16/100: train_loss=0.601037

      epoch  17/100: train_loss=0.599607

      epoch  18/100: train_loss=0.608863

      epoch  19/100: train_loss=0.600203

      epoch  20/100: train_loss=0.598314, val_loss=2.297216, IC=-0.0165

      epoch  21/100: train_loss=0.601644

      epoch  22/100: train_loss=0.602544

      epoch  23/100: train_loss=0.601593

      epoch  24/100: train_loss=0.604553

      epoch  25/100: train_loss=0.603789, val_loss=2.296379, IC=-0.0229

      epoch  26/100: train_loss=0.597535

      epoch  27/100: train_loss=0.605805

      epoch  28/100: train_loss=0.601337

      epoch  29/100: train_loss=0.601339

      epoch  30/100: train_loss=0.602359, val_loss=2.296982, IC=-0.0212

      epoch  31/100: train_loss=0.601952

      epoch  32/100: train_loss=0.601968

      epoch  33/100: train_loss=0.600108

      epoch  34/100: train_loss=0.600268

      epoch  35/100: train_loss=0.599243, val_loss=2.299467, IC=-0.0209

      epoch  36/100: train_loss=0.600966

      epoch  37/100: train_loss=0.600154

      epoch  38/100: train_loss=0.601126

      epoch  39/100: train_loss=0.599990

      epoch  40/100: train_loss=0.599201, val_loss=2.299873, IC=-0.0236

      epoch  41/100: train_loss=0.602604

      epoch  42/100: train_loss=0.598161

      epoch  43/100: train_loss=0.602416

      epoch  44/100: train_loss=0.602159

      epoch  45/100: train_loss=0.600172, val_loss=2.291115, IC=-0.0206

      epoch  46/100: train_loss=0.599082

      epoch  47/100: train_loss=0.601482

      epoch  48/100: train_loss=0.597922

      epoch  49/100: train_loss=0.601301

      epoch  50/100: train_loss=0.598147, val_loss=2.295913, IC=-0.0164

      epoch  51/100: train_loss=0.603130

      epoch  52/100: train_loss=0.599784

      epoch  53/100: train_loss=0.609143

      epoch  54/100: train_loss=0.597908

      epoch  55/100: train_loss=0.602041, val_loss=2.298421, IC=-0.0242

      epoch  56/100: train_loss=0.599540

      epoch  57/100: train_loss=0.599683

      epoch  58/100: train_loss=0.598063

      epoch  59/100: train_loss=0.602353

      epoch  60/100: train_loss=0.602449, val_loss=2.300734, IC=-0.0250

      epoch  61/100: train_loss=0.601109

      epoch  62/100: train_loss=0.601800

      epoch  63/100: train_loss=0.597804

      epoch  64/100: train_loss=0.600213

      epoch  65/100: train_loss=0.600506, val_loss=2.297628, IC=-0.0262

      epoch  66/100: train_loss=0.602892

      epoch  67/100: train_loss=0.607226

      epoch  68/100: train_loss=0.599380

      epoch  69/100: train_loss=0.598860

      epoch  70/100: train_loss=0.600270, val_loss=2.296923, IC=-0.0239

      epoch  71/100: train_loss=0.598291

      epoch  72/100: train_loss=0.601621

      epoch  73/100: train_loss=0.598304

      epoch  74/100: train_loss=0.602457

      epoch  75/100: train_loss=0.604550, val_loss=2.300185, IC=-0.0249

      epoch  76/100: train_loss=0.601449

      epoch  77/100: train_loss=0.602724

      epoch  78/100: train_loss=0.599997

      epoch  79/100: train_loss=0.597184

      epoch  80/100: train_loss=0.599715, val_loss=2.298988, IC=-0.0262

      epoch  81/100: train_loss=0.600076

      epoch  82/100: train_loss=0.599934

      epoch  83/100: train_loss=0.600523

      epoch  84/100: train_loss=0.599029

      epoch  85/100: train_loss=0.602899, val_loss=2.299806, IC=-0.0244

      epoch  86/100: train_loss=0.600016

      epoch  87/100: train_loss=0.600341

      epoch  88/100: train_loss=0.599419

      epoch  89/100: train_loss=0.601144

      epoch  90/100: train_loss=0.601690, val_loss=2.298624, IC=-0.0247

      epoch  91/100: train_loss=0.600553

      epoch  92/100: train_loss=0.605002

      epoch  93/100: train_loss=0.601654

      epoch  94/100: train_loss=0.601023

      epoch  95/100: train_loss=0.600744, val_loss=2.299327, IC=-0.0249

      epoch  96/100: train_loss=0.602790

      epoch  97/100: train_loss=0.600663

      epoch  98/100: train_loss=0.599701

      epoch  99/100: train_loss=0.597857

      epoch 100/100: train_loss=0.609984, val_loss=2.298889, IC=-0.0247

      best_ep=5, IC=+0.0142 (113.6s, 20 checkpoints)

  nlinear: best_epoch=5, IC=+0.0017 (214.1s)

  Best: nlinear @ epoch 5 (IC=+0.0017)
  Saved to ~/ml4t/public-dl-rerun/case_studies/sp500_options/run_log/training/f4874ea19561/diagnostics

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("NLinear execution returned a partial checkpoint")
catalog

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ 58830242f │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ b5d       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ 180b6fb09 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ b86       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ 26c61a312 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ 01f       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ c0ac0f176 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ 0e9       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ 1657ef963 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ 21a       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ d09852853 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ 658       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ 0f963e745 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ 446       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ fae0f8975 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ 333       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ bbb730631 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ 9ef       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f4874ea19 ┆ 1c5866211 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 561       ┆ 76b       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

The NLinear checkpoint artifacts are complete. The official sequence population remains open
until `09a_lstm` and `09b_patchtst` publish their declared members.