# S&P 500 Options: NLinear

This notebook snapshots the complete three-model sequence population before fitting its NLinear
member. `09a_lstm` and `09b_patchtst` execute the other declared members against the same
immutable population. Every configured checkpoint remains eligible for model analysis and
backtesting.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit NLinear within the declared S&P 500 options sequence population."""

import polars as pl

from case_studies.sp500_options.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_subset,
    run_resolved_model_requests,
    snapshot_official_model_catalog,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
PREVIEW_REDUCTIONS: dict = {}

SEQUENCE_CONFIGS = ("nlinear", "lstm_h64", "patchtst")
POPULATION_NAME = "sp500-options-sequence-validation-v1"

## Complete sequence request population

The case-wide table is resolved before the first member executes. Canonical execution snapshots
all configuration-checkpoint identities so a failed member cannot disappear from later analysis.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
all_requests = model_request_catalog(
    "deep_learning",
    labels=ALL_LABELS,
    config_names=SEQUENCE_CONFIGS,
)
all_resolved = resolve_model_requests(
    study,
    all_requests,
    execution_tier=EXECUTION_TIER,
    preview_reductions=PREVIEW_REDUCTIONS,
)
resolved_model_plan(all_resolved)

shape: (3, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ regressio ┆ … ┆ 2020-11-1 ┆ 20        ┆ canonical ┆ f3f4c079 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 0         ┆           ┆           ┆ 128f     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ regressio ┆ … ┆ 2020-11-1 ┆ 20        ┆ canonical ┆ a0a502ee │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 0         ┆           ┆           ┆ c2bf     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ regressio ┆ … ┆ 2020-11-1 ┆ 20        ┆ canonical ┆ 04915ba9 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 0         ┆           ┆           ┆ cfb2     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute NLinear

NLinear shares the gap-safe sequence construction, fold boundaries, fitted-state persistence,
restart, and exact eligible-key checks used by the other sequence configurations.

In [4]:
nlinear_resolved = tuple(
    request for request in all_resolved if request.spec["config_name"] == "nlinear"
)
if len(nlinear_resolved) != 1:
    raise ValueError("the sequence population must contain exactly one NLinear request")

if EXECUTION_TIER == "canonical":
    population = snapshot_official_model_catalog(
        study,
        all_requests,
        population_name=POPULATION_NAME,
        resolved_requests=all_resolved,
    )
    execution, population = run_official_model_subset(
        study,
        nlinear_resolved,
        population=population,
    )
else:
    if not WORKSPACE or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, nlinear_resolved)
    population = None

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=49,629 seq across 472 symbols
    val=12,326 seq across 473 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.825852

      epoch   2/100: train_loss=0.672026

      epoch   3/100: train_loss=0.632068

      epoch   4/100: train_loss=0.625769

      epoch   5/100: train_loss=0.616664, val_loss=5.079322, IC=-0.0098

      epoch   6/100: train_loss=0.613195

      epoch   7/100: train_loss=0.614960

      epoch   8/100: train_loss=0.612319

      epoch   9/100: train_loss=0.611700

      epoch  10/100: train_loss=0.606654, val_loss=5.045401, IC=-0.0033

      epoch  11/100: train_loss=0.612034

      epoch  12/100: train_loss=0.608202

      epoch  13/100: train_loss=0.608455

      epoch  14/100: train_loss=0.605089

      epoch  15/100: train_loss=0.604382, val_loss=5.062530, IC=-0.0108

      epoch  16/100: train_loss=0.603434

      epoch  17/100: train_loss=0.603131

      epoch  18/100: train_loss=0.601025

      epoch  19/100: train_loss=0.606961

      epoch  20/100: train_loss=0.604732, val_loss=5.079929, IC=-0.0145

      epoch  21/100: train_loss=0.600717

      epoch  22/100: train_loss=0.602669

      epoch  23/100: train_loss=0.601236

      epoch  24/100: train_loss=0.605041

      epoch  25/100: train_loss=0.597300, val_loss=5.106371, IC=-0.0176

      epoch  26/100: train_loss=0.600436

      epoch  27/100: train_loss=0.603280

      epoch  28/100: train_loss=0.597717

      epoch  29/100: train_loss=0.599958

      epoch  30/100: train_loss=0.601477, val_loss=5.076251, IC=-0.0113

      epoch  31/100: train_loss=0.604374

      epoch  32/100: train_loss=0.603183

      epoch  33/100: train_loss=0.597908

      epoch  34/100: train_loss=0.600578

      epoch  35/100: train_loss=0.600773, val_loss=5.097075, IC=-0.0141

      epoch  36/100: train_loss=0.604121

      epoch  37/100: train_loss=0.601272

      epoch  38/100: train_loss=0.599777

      epoch  39/100: train_loss=0.598454

      epoch  40/100: train_loss=0.600915, val_loss=5.088553, IC=-0.0120

      epoch  41/100: train_loss=0.598079

      epoch  42/100: train_loss=0.600105

      epoch  43/100: train_loss=0.601205

      epoch  44/100: train_loss=0.599815

      epoch  45/100: train_loss=0.598853, val_loss=5.085745, IC=-0.0135

      epoch  46/100: train_loss=0.603615

      epoch  47/100: train_loss=0.597004

      epoch  48/100: train_loss=0.600514

      epoch  49/100: train_loss=0.599443

      epoch  50/100: train_loss=0.597163, val_loss=5.090176, IC=-0.0151

      epoch  51/100: train_loss=0.601937

      epoch  52/100: train_loss=0.597241

      epoch  53/100: train_loss=0.599011

      epoch  54/100: train_loss=0.600561

      epoch  55/100: train_loss=0.599599, val_loss=5.076974, IC=-0.0140

      epoch  56/100: train_loss=0.600824

      epoch  57/100: train_loss=0.597935

      epoch  58/100: train_loss=0.598935

      epoch  59/100: train_loss=0.601517

      epoch  60/100: train_loss=0.596895, val_loss=5.091875, IC=-0.0163

      epoch  61/100: train_loss=0.598342

      epoch  62/100: train_loss=0.600788

      epoch  63/100: train_loss=0.603093

      epoch  64/100: train_loss=0.597770

      epoch  65/100: train_loss=0.600852, val_loss=5.077828, IC=-0.0127

      epoch  66/100: train_loss=0.597025

      epoch  67/100: train_loss=0.599554

      epoch  68/100: train_loss=0.596025

      epoch  69/100: train_loss=0.602044

      epoch  70/100: train_loss=0.600546, val_loss=5.091766, IC=-0.0152

      epoch  71/100: train_loss=0.599412

      epoch  72/100: train_loss=0.599258

      epoch  73/100: train_loss=0.596599

      epoch  74/100: train_loss=0.598482

      epoch  75/100: train_loss=0.600736, val_loss=5.086588, IC=-0.0144

      epoch  76/100: train_loss=0.601389

      epoch  77/100: train_loss=0.597797

      epoch  78/100: train_loss=0.600869

      epoch  79/100: train_loss=0.598492

      epoch  80/100: train_loss=0.597108, val_loss=5.089162, IC=-0.0131

      epoch  81/100: train_loss=0.598180

      epoch  82/100: train_loss=0.601668

      epoch  83/100: train_loss=0.597099

      epoch  84/100: train_loss=0.597735

      epoch  85/100: train_loss=0.598138, val_loss=5.086893, IC=-0.0144

      epoch  86/100: train_loss=0.599633

      epoch  87/100: train_loss=0.599799

      epoch  88/100: train_loss=0.597413

      epoch  89/100: train_loss=0.597871

      epoch  90/100: train_loss=0.598821, val_loss=5.088947, IC=-0.0142

      epoch  91/100: train_loss=0.601475

      epoch  92/100: train_loss=0.598054

      epoch  93/100: train_loss=0.604105

      epoch  94/100: train_loss=0.602760

      epoch  95/100: train_loss=0.597230, val_loss=5.087747, IC=-0.0143

      epoch  96/100: train_loss=0.599760

      epoch  97/100: train_loss=0.599056

      epoch  98/100: train_loss=0.599875

      epoch  99/100: train_loss=0.599642

      epoch 100/100: train_loss=0.597750, val_loss=5.087526, IC=-0.0147

      best_ep=10, IC=-0.0033 (73.4s, 20 checkpoints)

  Fold 1: creating sequences...

    train=36,365 seq across 468 symbols
    val=29,860 seq across 480 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.921280

      epoch   2/100: train_loss=0.804584

      epoch   3/100: train_loss=0.776064

      epoch   4/100: train_loss=0.762443

      epoch   5/100: train_loss=0.755342, val_loss=0.582979, IC=+0.0013

      epoch   6/100: train_loss=0.753751

      epoch   7/100: train_loss=0.749374

      epoch   8/100: train_loss=0.748656

      epoch   9/100: train_loss=0.748018

      epoch  10/100: train_loss=0.745766, val_loss=0.585594, IC=-0.0068

      epoch  11/100: train_loss=0.746682

      epoch  12/100: train_loss=0.747671

      epoch  13/100: train_loss=0.744495

      epoch  14/100: train_loss=0.745017

      epoch  15/100: train_loss=0.744837, val_loss=0.590246, IC=-0.0090

      epoch  16/100: train_loss=0.743965

      epoch  17/100: train_loss=0.741859

      epoch  18/100: train_loss=0.745634

      epoch  19/100: train_loss=0.741966

      epoch  20/100: train_loss=0.742528, val_loss=0.593260, IC=-0.0106

      epoch  21/100: train_loss=0.742947

      epoch  22/100: train_loss=0.741375

      epoch  23/100: train_loss=0.743787

      epoch  24/100: train_loss=0.740191

      epoch  25/100: train_loss=0.740773, val_loss=0.594235, IC=-0.0109

      epoch  26/100: train_loss=0.742785

      epoch  27/100: train_loss=0.741329

      epoch  28/100: train_loss=0.740302

      epoch  29/100: train_loss=0.740184

      epoch  30/100: train_loss=0.742186, val_loss=0.594707, IC=-0.0120

      epoch  31/100: train_loss=0.739193

      epoch  32/100: train_loss=0.739058

      epoch  33/100: train_loss=0.740881

      epoch  34/100: train_loss=0.740528

      epoch  35/100: train_loss=0.742729, val_loss=0.596014, IC=-0.0114

      epoch  36/100: train_loss=0.740046

      epoch  37/100: train_loss=0.740892

      epoch  38/100: train_loss=0.738670

      epoch  39/100: train_loss=0.740801

      epoch  40/100: train_loss=0.739190, val_loss=0.597971, IC=-0.0112

      epoch  41/100: train_loss=0.740799

      epoch  42/100: train_loss=0.738133

      epoch  43/100: train_loss=0.737650

      epoch  44/100: train_loss=0.737982

      epoch  45/100: train_loss=0.738556, val_loss=0.599197, IC=-0.0104

      epoch  46/100: train_loss=0.739420

      epoch  47/100: train_loss=0.738615

      epoch  48/100: train_loss=0.740685

      epoch  49/100: train_loss=0.738534

      epoch  50/100: train_loss=0.736990, val_loss=0.599328, IC=-0.0109

      epoch  51/100: train_loss=0.739227

      epoch  52/100: train_loss=0.740273

      epoch  53/100: train_loss=0.738027

      epoch  54/100: train_loss=0.738397

      epoch  55/100: train_loss=0.740174, val_loss=0.599627, IC=-0.0100

      epoch  56/100: train_loss=0.739622

      epoch  57/100: train_loss=0.739534

      epoch  58/100: train_loss=0.737419

      epoch  59/100: train_loss=0.737510

      epoch  60/100: train_loss=0.740604, val_loss=0.600412, IC=-0.0116

      epoch  61/100: train_loss=0.736843

      epoch  62/100: train_loss=0.738161

      epoch  63/100: train_loss=0.736301

      epoch  64/100: train_loss=0.736743

      epoch  65/100: train_loss=0.737771, val_loss=0.600794, IC=-0.0112

      epoch  66/100: train_loss=0.739442

      epoch  67/100: train_loss=0.737603

      epoch  68/100: train_loss=0.740217

      epoch  69/100: train_loss=0.737256

      epoch  70/100: train_loss=0.738624, val_loss=0.601157, IC=-0.0106

      epoch  71/100: train_loss=0.737829

      epoch  72/100: train_loss=0.739171

      epoch  73/100: train_loss=0.737296

      epoch  74/100: train_loss=0.736966

      epoch  75/100: train_loss=0.736833, val_loss=0.601114, IC=-0.0106

      epoch  76/100: train_loss=0.740450

      epoch  77/100: train_loss=0.735230

      epoch  78/100: train_loss=0.737620

      epoch  79/100: train_loss=0.737132

      epoch  80/100: train_loss=0.737204, val_loss=0.601677, IC=-0.0103

      epoch  81/100: train_loss=0.737756

      epoch  82/100: train_loss=0.737941

      epoch  83/100: train_loss=0.741768

      epoch  84/100: train_loss=0.739575

      epoch  85/100: train_loss=0.736416, val_loss=0.601455, IC=-0.0104

      epoch  86/100: train_loss=0.737785

      epoch  87/100: train_loss=0.736552

      epoch  88/100: train_loss=0.736132

      epoch  89/100: train_loss=0.740010

      epoch  90/100: train_loss=0.739693, val_loss=0.601561, IC=-0.0104

      epoch  91/100: train_loss=0.736889

      epoch  92/100: train_loss=0.735074

      epoch  93/100: train_loss=0.735334

      epoch  94/100: train_loss=0.735264

      epoch  95/100: train_loss=0.737408, val_loss=0.601583, IC=-0.0105

      epoch  96/100: train_loss=0.739151

      epoch  97/100: train_loss=0.736555

      epoch  98/100: train_loss=0.735481

      epoch  99/100: train_loss=0.736733

      epoch 100/100: train_loss=0.737412, val_loss=0.601595, IC=-0.0105

      best_ep=5, IC=+0.0013 (58.8s, 20 checkpoints)

  nlinear: best_epoch=5, IC=-0.0038 (132.2s)

  Best: nlinear @ epoch 5 (IC=-0.0038)
  Saved to ~/ml4t/public-s6-sp500_options/case_studies/sp500_options/run_log/training/a0a502eec2bf/diagnostics

In [5]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("NLinear execution returned a partial checkpoint")
catalog

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ 3e3c6fff9 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ ff3       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ 77ff4fd3f │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ 9cc       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ bd19369ef │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ 986       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ dec025b2e │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ 929       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ 5da723979 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ 54f       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ f189ed6a9 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ 28a       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ 1dc80df88 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ 7ea       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ a84d5f281 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ be2       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ 620c1f1b0 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ 360       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a0a502eec ┆ bd20adb68 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2bf       ┆ 5cf       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

The NLinear checkpoint artifacts are complete. The official sequence population remains open
until `09a_lstm` and `09b_patchtst` publish their declared members.