# S&P 500 Options: NLinear

This notebook snapshots the complete three-model sequence population before fitting its NLinear
member. `09a_lstm` and `09b_patchtst` execute the other declared members against the same
immutable population. Every configured checkpoint remains eligible for model analysis and
backtesting.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit NLinear within the declared S&P 500 options sequence population."""

import polars as pl

from case_studies.sp500_options.research_workflow import (
    ALL_LABELS,
    declared_dl_device,
    model_request_catalog,
    open_study,
    published_dl_device,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_subset,
    run_resolved_model_requests,
    snapshot_official_model_catalog,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
PREVIEW_REDUCTIONS: dict = {}
DEVICE: str = ""

SEQUENCE_CONFIGS = ("nlinear", "lstm_h64", "patchtst")
POPULATION_NAME: str = ""
SUPERSEDES_POPULATION: str = "fd45f829a576"

### The device the population was fitted on

A network trained on a GPU and the same network trained on a CPU accumulate their sums in a
different order and reach different weights, so the device is part of what the fitted model is
and sits inside the training identity rather than beside it. The device this population was
fitted on is declared once, in `modeling.dl.device` in `config/setup.yaml`, and read from there
by all four deep-learning notebooks rather than retyped in each. On a machine with no NVIDIA
card the run stops here rather than quietly training something else: set `DEVICE="cpu"` and pass
a `POPULATION_NAME` to fit the same requests there, under a name of their own.

In [3]:
CANONICAL_POPULATION_NAME = "sp500-options-sequence-validation-v1"

published_device = published_dl_device()
device = declared_dl_device(DEVICE)
population_name = POPULATION_NAME or CANONICAL_POPULATION_NAME
if device != published_device and population_name == CANONICAL_POPULATION_NAME:
    raise ValueError(
        f"this run fits on {device!r}, not the published {published_device!r}, so its "
        f"identities are not the ones {CANONICAL_POPULATION_NAME!r} holds; pass "
        f"POPULATION_NAME to give them a population of their own"
    )
print(f"training device: {device} (declared: {published_device})")

training device: cuda (declared: cuda)

## Complete sequence request population

The case-wide table is resolved before the first member executes. Canonical execution snapshots
all configuration-checkpoint identities so a failed member cannot disappear from later analysis.

**A name holds one generation at a time**, and this notebook is the only one that writes this
population - `09a_lstm` and `09b_patchtst` execute members of a snapshot that already exists.
Anything that moves a training identity moves every prediction hash with it, so the members
this run computes are no longer the members an earlier snapshot under the same name declared,
and those two notebooks then refuse their own work as undeclared. `SUPERSEDES_POPULATION`
names the snapshot such a run retires, and the value is part of what the population is hashed
over. The value here names the snapshot this run retires; it is empty only for the first
snapshot under a name.

`create` refuses a changed member list under an existing name unless this names the current
snapshot, so the parameter is what makes refreshing this population possible at all. Without
it the refit stops at the write with the hash it needs, which is the right failure but not
one this notebook could act on.

In [4]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
all_requests = model_request_catalog(
    "deep_learning",
    labels=ALL_LABELS,
    config_names=SEQUENCE_CONFIGS,
)
all_resolved = resolve_model_requests(
    study,
    all_requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": device},
    preview_reductions=PREVIEW_REDUCTIONS,
)
resolved_model_plan(all_resolved)

shape: (3, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ regressio ┆ … ┆ 2020-11-1 ┆ 20        ┆ canonical ┆ 6038372b │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 0         ┆           ┆           ┆ dd4d     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ regressio ┆ … ┆ 2020-11-1 ┆ 20        ┆ canonical ┆ dc76d91d │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 0         ┆           ┆           ┆ 861b     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ regressio ┆ … ┆ 2020-11-1 ┆ 20        ┆ canonical ┆ 472344b7 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 0         ┆           ┆           ┆ 74ad     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute NLinear

NLinear shares the gap-safe sequence construction, fold boundaries, fitted-state persistence,
restart, and exact eligible-key checks used by the other sequence configurations.

In [5]:
nlinear_resolved = tuple(
    request for request in all_resolved if request.spec["config_name"] == "nlinear"
)
if len(nlinear_resolved) != 1:
    raise ValueError("the sequence population must contain exactly one NLinear request")

if EXECUTION_TIER == "canonical":
    population = snapshot_official_model_catalog(
        study,
        all_requests,
        population_name=population_name,
        resolved_requests=all_resolved,
        supersedes=SUPERSEDES_POPULATION or None,
    )
    execution, population = run_official_model_subset(
        study,
        nlinear_resolved,
        population=population,
    )
else:
    if not WORKSPACE or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, nlinear_resolved)
    population = None

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=49,609 seq across 472 symbols
    val=12,146 seq across 473 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.817201

      epoch   2/100: train_loss=0.663327

      epoch   3/100: train_loss=0.626412

      epoch   4/100: train_loss=0.618218

      epoch   5/100: train_loss=0.613224, val_loss=3.015997, IC=-0.0123

      epoch   6/100: train_loss=0.608318

      epoch   7/100: train_loss=0.605476

      epoch   8/100: train_loss=0.605573

      epoch   9/100: train_loss=0.603828

      epoch  10/100: train_loss=0.604271, val_loss=3.022406, IC=-0.0054

      epoch  11/100: train_loss=0.600651

      epoch  12/100: train_loss=0.598810

      epoch  13/100: train_loss=0.595721

      epoch  14/100: train_loss=0.593812

      epoch  15/100: train_loss=0.593434, val_loss=3.062516, IC=-0.0156

      epoch  16/100: train_loss=0.594232

      epoch  17/100: train_loss=0.593043

      epoch  18/100: train_loss=0.594808

      epoch  19/100: train_loss=0.594978

      epoch  20/100: train_loss=0.591391, val_loss=3.054010, IC=-0.0142

      epoch  21/100: train_loss=0.594476

      epoch  22/100: train_loss=0.594057

      epoch  23/100: train_loss=0.596349

      epoch  24/100: train_loss=0.592078

      epoch  25/100: train_loss=0.591109, val_loss=3.059136, IC=-0.0169

      epoch  26/100: train_loss=0.591048

      epoch  27/100: train_loss=0.594236

      epoch  28/100: train_loss=0.594400

      epoch  29/100: train_loss=0.595782

      epoch  30/100: train_loss=0.591837, val_loss=3.056829, IC=-0.0149

      epoch  31/100: train_loss=0.594241

      epoch  32/100: train_loss=0.593225

      epoch  33/100: train_loss=0.590193

      epoch  34/100: train_loss=0.591801

      epoch  35/100: train_loss=0.594526, val_loss=3.053808, IC=-0.0124

      epoch  36/100: train_loss=0.593414

      epoch  37/100: train_loss=0.592265

      epoch  38/100: train_loss=0.590762

      epoch  39/100: train_loss=0.591414

      epoch  40/100: train_loss=0.592389, val_loss=3.048590, IC=-0.0180

      epoch  41/100: train_loss=0.590505

      epoch  42/100: train_loss=0.590250

      epoch  43/100: train_loss=0.599599

      epoch  44/100: train_loss=0.595274

      epoch  45/100: train_loss=0.596603, val_loss=3.058204, IC=-0.0143

      epoch  46/100: train_loss=0.588195

      epoch  47/100: train_loss=0.588928

      epoch  48/100: train_loss=0.589270

      epoch  49/100: train_loss=0.591828

      epoch  50/100: train_loss=0.590302, val_loss=3.054867, IC=-0.0121

      epoch  51/100: train_loss=0.594649

      epoch  52/100: train_loss=0.587498

      epoch  53/100: train_loss=0.591807

      epoch  54/100: train_loss=0.592081

      epoch  55/100: train_loss=0.591384, val_loss=3.053729, IC=-0.0135

      epoch  56/100: train_loss=0.587524

      epoch  57/100: train_loss=0.587376

      epoch  58/100: train_loss=0.589846

      epoch  59/100: train_loss=0.589512

      epoch  60/100: train_loss=0.591138, val_loss=3.058175, IC=-0.0151

      epoch  61/100: train_loss=0.593588

      epoch  62/100: train_loss=0.591016

      epoch  63/100: train_loss=0.590020

      epoch  64/100: train_loss=0.591247

      epoch  65/100: train_loss=0.591171, val_loss=3.051434, IC=-0.0119

      epoch  66/100: train_loss=0.591214

      epoch  67/100: train_loss=0.590825

      epoch  68/100: train_loss=0.593627

      epoch  69/100: train_loss=0.592843

      epoch  70/100: train_loss=0.592080, val_loss=3.054262, IC=-0.0144

      epoch  71/100: train_loss=0.591675

      epoch  72/100: train_loss=0.591080

      epoch  73/100: train_loss=0.596146

      epoch  74/100: train_loss=0.592524

      epoch  75/100: train_loss=0.589437, val_loss=3.054238, IC=-0.0148

      epoch  76/100: train_loss=0.591091

      epoch  77/100: train_loss=0.594308

      epoch  78/100: train_loss=0.592049

      epoch  79/100: train_loss=0.589668

      epoch  80/100: train_loss=0.596284, val_loss=3.052856, IC=-0.0137

      epoch  81/100: train_loss=0.589371

      epoch  82/100: train_loss=0.593355

      epoch  83/100: train_loss=0.591935

      epoch  84/100: train_loss=0.591788

      epoch  85/100: train_loss=0.591042, val_loss=3.056498, IC=-0.0152

      epoch  86/100: train_loss=0.591062

      epoch  87/100: train_loss=0.588459

      epoch  88/100: train_loss=0.590693

      epoch  89/100: train_loss=0.590424

      epoch  90/100: train_loss=0.592166, val_loss=3.054447, IC=-0.0156

      epoch  91/100: train_loss=0.590120

      epoch  92/100: train_loss=0.588795

      epoch  93/100: train_loss=0.590599

      epoch  94/100: train_loss=0.589661

      epoch  95/100: train_loss=0.588578, val_loss=3.054371, IC=-0.0156

      epoch  96/100: train_loss=0.590033

      epoch  97/100: train_loss=0.591617

      epoch  98/100: train_loss=0.592142

      epoch  99/100: train_loss=0.586871

      epoch 100/100: train_loss=0.593197, val_loss=3.054501, IC=-0.0157

      best_ep=10, IC=-0.0054 (56.3s, 20 checkpoints)

  Fold 1: creating sequences...

    train=36,322 seq across 468 symbols
    val=29,860 seq across 480 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.821585

      epoch   2/100: train_loss=0.696919

      epoch   3/100: train_loss=0.670251

      epoch   4/100: train_loss=0.661497

      epoch   5/100: train_loss=0.654967, val_loss=0.582205, IC=-0.0010

      epoch   6/100: train_loss=0.651461

      epoch   7/100: train_loss=0.648907

      epoch   8/100: train_loss=0.648779

      epoch   9/100: train_loss=0.647192

      epoch  10/100: train_loss=0.646307, val_loss=0.583448, IC=-0.0115

      epoch  11/100: train_loss=0.644971

      epoch  12/100: train_loss=0.643938

      epoch  13/100: train_loss=0.644485

      epoch  14/100: train_loss=0.642133

      epoch  15/100: train_loss=0.641715, val_loss=0.586025, IC=-0.0141

      epoch  16/100: train_loss=0.640784

      epoch  17/100: train_loss=0.641138

      epoch  18/100: train_loss=0.641186

      epoch  19/100: train_loss=0.640494

      epoch  20/100: train_loss=0.640819, val_loss=0.587594, IC=-0.0133

      epoch  21/100: train_loss=0.640606

      epoch  22/100: train_loss=0.640320

      epoch  23/100: train_loss=0.639701

      epoch  24/100: train_loss=0.640000

      epoch  25/100: train_loss=0.640269, val_loss=0.589145, IC=-0.0160

      epoch  26/100: train_loss=0.639805

      epoch  27/100: train_loss=0.639196

      epoch  28/100: train_loss=0.638965

      epoch  29/100: train_loss=0.639687

      epoch  30/100: train_loss=0.638531, val_loss=0.588869, IC=-0.0142

      epoch  31/100: train_loss=0.637707

      epoch  32/100: train_loss=0.639982

      epoch  33/100: train_loss=0.638637

      epoch  34/100: train_loss=0.639600

      epoch  35/100: train_loss=0.638382, val_loss=0.591089, IC=-0.0157

      epoch  36/100: train_loss=0.637732

      epoch  37/100: train_loss=0.639574

      epoch  38/100: train_loss=0.638024

      epoch  39/100: train_loss=0.638291

      epoch  40/100: train_loss=0.637158, val_loss=0.591564, IC=-0.0143

      epoch  41/100: train_loss=0.638799

      epoch  42/100: train_loss=0.637662

      epoch  43/100: train_loss=0.637530

      epoch  44/100: train_loss=0.638073

      epoch  45/100: train_loss=0.637257, val_loss=0.592331, IC=-0.0146

      epoch  46/100: train_loss=0.637210

      epoch  47/100: train_loss=0.638508

      epoch  48/100: train_loss=0.638209

      epoch  49/100: train_loss=0.637338

      epoch  50/100: train_loss=0.636772, val_loss=0.592082, IC=-0.0137

      epoch  51/100: train_loss=0.638151

      epoch  52/100: train_loss=0.636944

      epoch  53/100: train_loss=0.635797

      epoch  54/100: train_loss=0.636234

      epoch  55/100: train_loss=0.636125, val_loss=0.593125, IC=-0.0152

      epoch  56/100: train_loss=0.635169

      epoch  57/100: train_loss=0.635571

      epoch  58/100: train_loss=0.635818

      epoch  59/100: train_loss=0.637140

      epoch  60/100: train_loss=0.634995, val_loss=0.593893, IC=-0.0138

      epoch  61/100: train_loss=0.635664

      epoch  62/100: train_loss=0.635956

      epoch  63/100: train_loss=0.637162

      epoch  64/100: train_loss=0.636943

      epoch  65/100: train_loss=0.635578, val_loss=0.594140, IC=-0.0146

      epoch  66/100: train_loss=0.635403

      epoch  67/100: train_loss=0.635648

      epoch  68/100: train_loss=0.635226

      epoch  69/100: train_loss=0.636373

      epoch  70/100: train_loss=0.636484, val_loss=0.594522, IC=-0.0137

      epoch  71/100: train_loss=0.635123

      epoch  72/100: train_loss=0.635561

      epoch  73/100: train_loss=0.635785

      epoch  74/100: train_loss=0.635253

      epoch  75/100: train_loss=0.636308, val_loss=0.594669, IC=-0.0144

      epoch  76/100: train_loss=0.636394

      epoch  77/100: train_loss=0.636386

      epoch  78/100: train_loss=0.635070

      epoch  79/100: train_loss=0.635789

      epoch  80/100: train_loss=0.634540, val_loss=0.594885, IC=-0.0140

      epoch  81/100: train_loss=0.635864

      epoch  82/100: train_loss=0.635794

      epoch  83/100: train_loss=0.634344

      epoch  84/100: train_loss=0.634508

      epoch  85/100: train_loss=0.635121, val_loss=0.595049, IC=-0.0142

      epoch  86/100: train_loss=0.635013

      epoch  87/100: train_loss=0.636303

      epoch  88/100: train_loss=0.636814

      epoch  89/100: train_loss=0.634304

      epoch  90/100: train_loss=0.635174, val_loss=0.595216, IC=-0.0142

      epoch  91/100: train_loss=0.634311

      epoch  92/100: train_loss=0.634739

      epoch  93/100: train_loss=0.635709

      epoch  94/100: train_loss=0.635369

      epoch  95/100: train_loss=0.635712, val_loss=0.595131, IC=-0.0143

      epoch  96/100: train_loss=0.635254

      epoch  97/100: train_loss=0.635766

      epoch  98/100: train_loss=0.634605

      epoch  99/100: train_loss=0.635781

      epoch 100/100: train_loss=0.634989, val_loss=0.595146, IC=-0.0143

      best_ep=5, IC=-0.0010 (44.1s, 20 checkpoints)

  nlinear: best_epoch=5, IC=-0.0062 (100.5s)

  Best: nlinear @ epoch 5 (IC=-0.0062)
  Saved to ~/ml4t/public-s6-sp500_options/case_studies/sp500_options/run_log/training/dc76d91d861b/diagnostics

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("NLinear execution returned a partial checkpoint")
catalog

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ 0f69f89a7 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 0ae       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ 3b7f25dc1 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 93c       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ 585bcf211 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 7e4       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ 0372c9f2f │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 678       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ b845bbf18 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 515       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ de22cc6d4 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 7c6       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ d1102ee90 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 772       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ a1177fb06 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 793       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ 67bbb64ec │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ b2e       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ dc76d91d8 ┆ 19e9fa0e3 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 61b       ┆ 419       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

The NLinear checkpoint artifacts are complete. The official sequence population remains open
until `09a_lstm` and `09b_patchtst` publish their declared members.