# S&P 500 Options: NLinear

This notebook snapshots the complete three-model sequence population before fitting its NLinear
member. `09a_lstm` and `09b_patchtst` execute the other declared members against the same
immutable population. Every configured checkpoint remains eligible for model analysis and
backtesting.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit NLinear within the declared S&P 500 options sequence population."""

import polars as pl

from case_studies.research import supersedes_for_run
from case_studies.sp500_options.research_workflow import (
    ALL_LABELS,
    declared_dl_device,
    model_request_catalog,
    open_study,
    published_dl_device,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_subset,
    run_resolved_model_requests,
    snapshot_official_model_catalog,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
PREVIEW_REDUCTIONS: dict = {}
DEVICE: str = ""

SEQUENCE_CONFIGS = ("nlinear", "lstm_h64", "patchtst")
POPULATION_NAME: str = ""
SUPERSEDES_POPULATION: str = "fd45f829a576"

### The device the population was fitted on

A network trained on a GPU and the same network trained on a CPU accumulate their sums in a
different order and reach different weights, so the device is part of what the fitted model is
and sits inside the training identity rather than beside it. The device this population was
fitted on is declared once, in `modeling.dl.device` in `config/setup.yaml`, and read from there
by all four deep-learning notebooks rather than retyped in each. On a machine with no NVIDIA
card the run stops here rather than quietly training something else: set `DEVICE="cpu"` and pass
a `POPULATION_NAME` to fit the same requests there, under a name of their own.

In [4]:
CANONICAL_POPULATION_NAME = "sp500-options-sequence-validation-v1"

published_device = published_dl_device()
device = declared_dl_device(DEVICE)
population_name = POPULATION_NAME or CANONICAL_POPULATION_NAME
if device != published_device and population_name == CANONICAL_POPULATION_NAME:
    raise ValueError(
        f"this run fits on {device!r}, not the published {published_device!r}, so its "
        f"identities are not the ones {CANONICAL_POPULATION_NAME!r} holds; pass "
        f"POPULATION_NAME to give them a population of their own"
    )
print(f"training device: {device} (declared: {published_device})")

training device: cuda (declared: cuda)

## Complete sequence request population

The case-wide table is resolved before the first member executes. Canonical execution snapshots
all configuration-checkpoint identities so a failed member cannot disappear from later analysis.

**A name holds one generation at a time**, and this notebook is the only one that writes this
population - `09a_lstm` and `09b_patchtst` execute members of a snapshot that already exists.
Anything that moves a training identity moves every prediction hash with it, so the members
this run computes are no longer the members an earlier snapshot under the same name declared,
and those two notebooks then refuse their own work as undeclared. `SUPERSEDES_POPULATION`
names the snapshot such a run retires, and the value is part of what the population is hashed
over. The value here names the snapshot this run retires; it is empty only for the first
snapshot under a name.

`create` refuses a changed member list under an existing name unless this names the current
snapshot, so the parameter is what makes refreshing this population possible at all. Without
it the refit stops at the write with the hash it needs, which is the right failure but not
one this notebook could act on.

In [5]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
all_requests = model_request_catalog(
    "deep_learning",
    labels=ALL_LABELS,
    config_names=SEQUENCE_CONFIGS,
)
all_resolved = resolve_model_requests(
    study,
    all_requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": device},
    preview_reductions=PREVIEW_REDUCTIONS,
)
resolved_model_plan(all_resolved)

shape: (3, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 81d20120 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 78c3     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 749a6005 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 82cc     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 1529ec75 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 918c     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute NLinear

NLinear shares the gap-safe sequence construction, fold boundaries, fitted-state persistence,
restart, and exact eligible-key checks used by the other sequence configurations.

In [6]:
nlinear_resolved = tuple(
    request for request in all_resolved if request.spec["config_name"] == "nlinear"
)
if len(nlinear_resolved) != 1:
    raise ValueError("the sequence population must contain exactly one NLinear request")

if EXECUTION_TIER == "canonical":
    population = snapshot_official_model_catalog(
        study,
        all_requests,
        population_name=population_name,
        resolved_requests=all_resolved,
        supersedes=supersedes_for_run(
            study,
            population_name=population_name,
            declared=SUPERSEDES_POPULATION or None,
            execution_tier=EXECUTION_TIER,
        ),
    )
    execution, population = run_official_model_subset(
        study,
        nlinear_resolved,
        population=population,
    )
else:
    if not WORKSPACE or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, nlinear_resolved)
    population = None

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=51,093 seq across 474 symbols
    val=12,944 seq across 477 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.813597

      epoch   2/100: train_loss=0.654342

      epoch   3/100: train_loss=0.620080

      epoch   4/100: train_loss=0.609169

      epoch   5/100: train_loss=0.603463, val_loss=3.046076, IC=-0.0078

      epoch   6/100: train_loss=0.602232

      epoch   7/100: train_loss=0.599331

      epoch   8/100: train_loss=0.597769

      epoch   9/100: train_loss=0.595614

      epoch  10/100: train_loss=0.595091, val_loss=3.080590, IC=-0.0018

      epoch  11/100: train_loss=0.594080

      epoch  12/100: train_loss=0.592472

      epoch  13/100: train_loss=0.590873

      epoch  14/100: train_loss=0.591245

      epoch  15/100: train_loss=0.590904, val_loss=3.078419, IC=-0.0046

      epoch  16/100: train_loss=0.589874

      epoch  17/100: train_loss=0.589681

      epoch  18/100: train_loss=0.588120

      epoch  19/100: train_loss=0.587874

      epoch  20/100: train_loss=0.588820, val_loss=3.079998, IC=-0.0027

      epoch  21/100: train_loss=0.588292

      epoch  22/100: train_loss=0.587672

      epoch  23/100: train_loss=0.586932

      epoch  24/100: train_loss=0.587058

      epoch  25/100: train_loss=0.587238, val_loss=3.083954, IC=-0.0084

      epoch  26/100: train_loss=0.586303

      epoch  27/100: train_loss=0.587307

      epoch  28/100: train_loss=0.586945

      epoch  29/100: train_loss=0.586405

      epoch  30/100: train_loss=0.586648, val_loss=3.077151, IC=-0.0061

      epoch  31/100: train_loss=0.586778

      epoch  32/100: train_loss=0.585664

      epoch  33/100: train_loss=0.586029

      epoch  34/100: train_loss=0.585529

      epoch  35/100: train_loss=0.586060, val_loss=3.097894, IC=-0.0129

      epoch  36/100: train_loss=0.585584

      epoch  37/100: train_loss=0.585902

      epoch  38/100: train_loss=0.585761

      epoch  39/100: train_loss=0.586061

      epoch  40/100: train_loss=0.586215, val_loss=3.094828, IC=-0.0121

      epoch  41/100: train_loss=0.586158

      epoch  42/100: train_loss=0.585985

      epoch  43/100: train_loss=0.585606

      epoch  44/100: train_loss=0.585547

      epoch  45/100: train_loss=0.585529, val_loss=3.088173, IC=-0.0100

      epoch  46/100: train_loss=0.584940

      epoch  47/100: train_loss=0.585205

      epoch  48/100: train_loss=0.586202

      epoch  49/100: train_loss=0.585161

      epoch  50/100: train_loss=0.585243, val_loss=3.092231, IC=-0.0137

      epoch  51/100: train_loss=0.584970

      epoch  52/100: train_loss=0.584705

      epoch  53/100: train_loss=0.585125

      epoch  54/100: train_loss=0.584773

      epoch  55/100: train_loss=0.585244, val_loss=3.090589, IC=-0.0122

      epoch  56/100: train_loss=0.584856

      epoch  57/100: train_loss=0.585707

      epoch  58/100: train_loss=0.584796

      epoch  59/100: train_loss=0.585298

      epoch  60/100: train_loss=0.585110, val_loss=3.090574, IC=-0.0119

      epoch  61/100: train_loss=0.585009

      epoch  62/100: train_loss=0.585491

      epoch  63/100: train_loss=0.585389

      epoch  64/100: train_loss=0.584593

      epoch  65/100: train_loss=0.585704, val_loss=3.095578, IC=-0.0153

      epoch  66/100: train_loss=0.585123

      epoch  67/100: train_loss=0.585566

      epoch  68/100: train_loss=0.585357

      epoch  69/100: train_loss=0.585241

      epoch  70/100: train_loss=0.585566, val_loss=3.088565, IC=-0.0125

      epoch  71/100: train_loss=0.584914

      epoch  72/100: train_loss=0.585806

      epoch  73/100: train_loss=0.585617

      epoch  74/100: train_loss=0.585547

      epoch  75/100: train_loss=0.585551, val_loss=3.090365, IC=-0.0121

      epoch  76/100: train_loss=0.585411

      epoch  77/100: train_loss=0.585108

      epoch  78/100: train_loss=0.585102

      epoch  79/100: train_loss=0.584737

      epoch  80/100: train_loss=0.585520, val_loss=3.090429, IC=-0.0131

      epoch  81/100: train_loss=0.585541

      epoch  82/100: train_loss=0.584174

      epoch  83/100: train_loss=0.584635

      epoch  84/100: train_loss=0.585327

      epoch  85/100: train_loss=0.585046, val_loss=3.089681, IC=-0.0120

      epoch  86/100: train_loss=0.584767

      epoch  87/100: train_loss=0.584610

      epoch  88/100: train_loss=0.584718

      epoch  89/100: train_loss=0.583980

      epoch  90/100: train_loss=0.584592, val_loss=3.090886, IC=-0.0124

      epoch  91/100: train_loss=0.584953

      epoch  92/100: train_loss=0.585565

      epoch  93/100: train_loss=0.585037

      epoch  94/100: train_loss=0.585385

      epoch  95/100: train_loss=0.585803, val_loss=3.091260, IC=-0.0129

      epoch  96/100: train_loss=0.584996

      epoch  97/100: train_loss=0.584914

      epoch  98/100: train_loss=0.585091

      epoch  99/100: train_loss=0.585304

      epoch 100/100: train_loss=0.584379, val_loss=3.091297, IC=-0.0131

      best_ep=10, IC=-0.0018 (53.4s, 20 checkpoints)

  Fold 1: creating sequences...

    train=38,016 seq across 475 symbols
    val=29,860 seq across 480 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.821422

      epoch   2/100: train_loss=0.707200

      epoch   3/100: train_loss=0.684846

      epoch   4/100: train_loss=0.674738

      epoch   5/100: train_loss=0.669515, val_loss=0.584425, IC=-0.0048

      epoch   6/100: train_loss=0.664555

      epoch   7/100: train_loss=0.663100

      epoch   8/100: train_loss=0.660672

      epoch   9/100: train_loss=0.661320

      epoch  10/100: train_loss=0.659720, val_loss=0.586449, IC=-0.0132

      epoch  11/100: train_loss=0.657812

      epoch  12/100: train_loss=0.656473

      epoch  13/100: train_loss=0.656054

      epoch  14/100: train_loss=0.656376

      epoch  15/100: train_loss=0.653051, val_loss=0.590477, IC=-0.0209

      epoch  16/100: train_loss=0.654002

      epoch  17/100: train_loss=0.652905

      epoch  18/100: train_loss=0.651966

      epoch  19/100: train_loss=0.651494

      epoch  20/100: train_loss=0.652225, val_loss=0.590202, IC=-0.0258

      epoch  21/100: train_loss=0.653271

      epoch  22/100: train_loss=0.651994

      epoch  23/100: train_loss=0.652327

      epoch  24/100: train_loss=0.651232

      epoch  25/100: train_loss=0.650669, val_loss=0.591641, IC=-0.0289

      epoch  26/100: train_loss=0.651230

      epoch  27/100: train_loss=0.649407

      epoch  28/100: train_loss=0.650517

      epoch  29/100: train_loss=0.648423

      epoch  30/100: train_loss=0.648693, val_loss=0.591522, IC=-0.0314

      epoch  31/100: train_loss=0.649233

      epoch  32/100: train_loss=0.649897

      epoch  33/100: train_loss=0.650908

      epoch  34/100: train_loss=0.649390

      epoch  35/100: train_loss=0.649123, val_loss=0.591488, IC=-0.0291

      epoch  36/100: train_loss=0.647642

      epoch  37/100: train_loss=0.649405

      epoch  38/100: train_loss=0.648935

      epoch  39/100: train_loss=0.648188

      epoch  40/100: train_loss=0.648656, val_loss=0.592469, IC=-0.0292

      epoch  41/100: train_loss=0.646622

      epoch  42/100: train_loss=0.647666

      epoch  43/100: train_loss=0.650559

      epoch  44/100: train_loss=0.647987

      epoch  45/100: train_loss=0.648557, val_loss=0.592193, IC=-0.0280

      epoch  46/100: train_loss=0.648660

      epoch  47/100: train_loss=0.647124

      epoch  48/100: train_loss=0.649241

      epoch  49/100: train_loss=0.647586

      epoch  50/100: train_loss=0.648332, val_loss=0.592758, IC=-0.0287

      epoch  51/100: train_loss=0.648842

      epoch  52/100: train_loss=0.646657

      epoch  53/100: train_loss=0.648261

      epoch  54/100: train_loss=0.647684

      epoch  55/100: train_loss=0.648142, val_loss=0.592251, IC=-0.0277

      epoch  56/100: train_loss=0.648717

      epoch  57/100: train_loss=0.647311

      epoch  58/100: train_loss=0.648498

      epoch  59/100: train_loss=0.646826

      epoch  60/100: train_loss=0.648186, val_loss=0.592288, IC=-0.0278

      epoch  61/100: train_loss=0.647935

      epoch  62/100: train_loss=0.647674

      epoch  63/100: train_loss=0.649826

      epoch  64/100: train_loss=0.646635

      epoch  65/100: train_loss=0.647037, val_loss=0.593363, IC=-0.0274

      epoch  66/100: train_loss=0.646897

      epoch  67/100: train_loss=0.648211

      epoch  68/100: train_loss=0.646811

      epoch  69/100: train_loss=0.648328

      epoch  70/100: train_loss=0.648087, val_loss=0.593114, IC=-0.0270

      epoch  71/100: train_loss=0.648667

      epoch  72/100: train_loss=0.645962

      epoch  73/100: train_loss=0.648734

      epoch  74/100: train_loss=0.647220

      epoch  75/100: train_loss=0.648767, val_loss=0.593344, IC=-0.0270

      epoch  76/100: train_loss=0.648535

      epoch  77/100: train_loss=0.648000

      epoch  78/100: train_loss=0.648170

      epoch  79/100: train_loss=0.647113

      epoch  80/100: train_loss=0.646663, val_loss=0.593452, IC=-0.0267

      epoch  81/100: train_loss=0.646950

      epoch  82/100: train_loss=0.648160

      epoch  83/100: train_loss=0.648130

      epoch  84/100: train_loss=0.647844

      epoch  85/100: train_loss=0.647422, val_loss=0.593536, IC=-0.0268

      epoch  86/100: train_loss=0.648159

      epoch  87/100: train_loss=0.647410

      epoch  88/100: train_loss=0.648825

      epoch  89/100: train_loss=0.649065

      epoch  90/100: train_loss=0.646717, val_loss=0.593557, IC=-0.0272

      epoch  91/100: train_loss=0.649190

      epoch  92/100: train_loss=0.648333

      epoch  93/100: train_loss=0.647314

      epoch  94/100: train_loss=0.646830

      epoch  95/100: train_loss=0.646795, val_loss=0.593457, IC=-0.0273

      epoch  96/100: train_loss=0.646558

      epoch  97/100: train_loss=0.648886

      epoch  98/100: train_loss=0.646183

      epoch  99/100: train_loss=0.648205

      epoch 100/100: train_loss=0.645871, val_loss=0.593456, IC=-0.0273

      best_ep=5, IC=-0.0048 (45.1s, 20 checkpoints)

  nlinear: best_epoch=5, IC=-0.0062 (98.5s)

  Best: nlinear @ epoch 5 (IC=-0.0062)
  Saved to ~/ml4t/public-sp500-options-close/case_studies/sp500_options/run_log/training/749a600582cc/diagnostics

In [7]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("NLinear execution returned a partial checkpoint")
catalog

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 24c9fe29d │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 9e9       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ e14f57405 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 641       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 3e9cd972f │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 640       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 6320cea71 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 7e0       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 192c194c6 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 2ee       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 56a7b9806 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 1f3       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 15df3d512 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 5a9       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 4b15c32ca │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 64f       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 6d5148ad8 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ 971       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 749a60058 ┆ 0a77549ce │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 2cc       ┆ f6b       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

The NLinear checkpoint artifacts are complete. The official sequence population remains open
until `09a_lstm` and `09b_patchtst` publish their declared members.