# S&P 500 Options: NLinear

This notebook snapshots the complete three-model sequence population before fitting its NLinear
member. `09a_lstm` and `09b_patchtst` execute the other declared members against the same
immutable population. Every configured checkpoint remains eligible for model analysis and
backtesting.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit NLinear within the declared S&P 500 options sequence population."""

import polars as pl

from case_studies.research import supersedes_for_run
from case_studies.sp500_options.research_workflow import (
    ALL_LABELS,
    declared_dl_device,
    model_request_catalog,
    open_study,
    published_dl_device,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_subset,
    run_resolved_model_requests,
    snapshot_official_model_catalog,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
PREVIEW_REDUCTIONS: dict = {}
DEVICE: str = ""

SEQUENCE_CONFIGS = ("nlinear", "lstm_h64", "patchtst")
POPULATION_NAME: str = ""
SUPERSEDES_POPULATION: str = "0f4b6616b370"

### The device the population was fitted on

A network trained on a GPU and the same network trained on a CPU accumulate their sums in a
different order and reach different weights, so the device is part of what the fitted model is
and sits inside the training identity rather than beside it. The device this population was
fitted on is declared once, in `modeling.dl.device` in `config/setup.yaml`, and read from there
by all four deep-learning notebooks rather than retyped in each. On a machine with no NVIDIA
card the run stops here rather than quietly training something else: set `DEVICE="cpu"` and pass
a `POPULATION_NAME` to fit the same requests there, under a name of their own.

In [3]:
CANONICAL_POPULATION_NAME = "sp500-options-sequence-validation-v1"

published_device = published_dl_device()
device = declared_dl_device(DEVICE)
population_name = POPULATION_NAME or CANONICAL_POPULATION_NAME
if device != published_device and population_name == CANONICAL_POPULATION_NAME:
    raise ValueError(
        f"this run fits on {device!r}, not the published {published_device!r}, so its "
        f"identities are not the ones {CANONICAL_POPULATION_NAME!r} holds; pass "
        f"POPULATION_NAME to give them a population of their own"
    )
print(f"training device: {device} (declared: {published_device})")

training device: cuda (declared: cuda)

## Complete sequence request population

The case-wide table is resolved before the first member executes. Canonical execution snapshots
all configuration-checkpoint identities so a failed member cannot disappear from later analysis.

**A name holds one generation at a time**, and this notebook is the only one that writes this
population - `09a_lstm` and `09b_patchtst` execute members of a snapshot that already exists.
Anything that moves a training identity moves every prediction hash with it, so the members
this run computes are no longer the members an earlier snapshot under the same name declared,
and those two notebooks then refuse their own work as undeclared. `SUPERSEDES_POPULATION`
names the snapshot such a run retires, and the value is part of what the population is hashed
over. The value here names the snapshot this run retires; it is empty only for the first
snapshot under a name.

`create` refuses a changed member list under an existing name unless this names the current
snapshot, so the parameter is what makes refreshing this population possible at all. Without
it the refit stops at the write with the hash it needs, which is the right failure but not
one this notebook could act on.

In [4]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
all_requests = model_request_catalog(
    "deep_learning",
    labels=ALL_LABELS,
    config_names=SEQUENCE_CONFIGS,
)
all_resolved = resolve_model_requests(
    study,
    all_requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": device},
    preview_reductions=PREVIEW_REDUCTIONS,
)
resolved_model_plan(all_resolved)

shape: (3, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 9352ea66 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 2f25     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 8d26c4c0 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ f196     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 7e09aacf │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 8c55     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute NLinear

NLinear shares the gap-safe sequence construction, fold boundaries, fitted-state persistence,
restart, and exact eligible-key checks used by the other sequence configurations.

In [5]:
nlinear_resolved = tuple(
    request for request in all_resolved if request.spec["config_name"] == "nlinear"
)
if len(nlinear_resolved) != 1:
    raise ValueError("the sequence population must contain exactly one NLinear request")

if EXECUTION_TIER == "canonical":
    population = snapshot_official_model_catalog(
        study,
        all_requests,
        population_name=population_name,
        resolved_requests=all_resolved,
        supersedes=supersedes_for_run(
            study,
            population_name=population_name,
            declared=SUPERSEDES_POPULATION or None,
            execution_tier=EXECUTION_TIER,
        ),
    )
    execution, population = run_official_model_subset(
        study,
        nlinear_resolved,
        population=population,
    )
else:
    if not WORKSPACE or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, nlinear_resolved)
    population = None

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=38,016 seq across 475 symbols
    val=29,860 seq across 480 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.849579

      epoch   2/100: train_loss=0.730766

      epoch   3/100: train_loss=0.689695

      epoch   4/100: train_loss=0.676235

      epoch   5/100: train_loss=0.671063, val_loss=0.588712, IC=-0.0148

      epoch   6/100: train_loss=0.666718

      epoch   7/100: train_loss=0.663514

      epoch   8/100: train_loss=0.661992

      epoch   9/100: train_loss=0.660021

      epoch  10/100: train_loss=0.658466, val_loss=0.592469, IC=-0.0251

      epoch  11/100: train_loss=0.659542

      epoch  12/100: train_loss=0.656159

      epoch  13/100: train_loss=0.656463

      epoch  14/100: train_loss=0.655790

      epoch  15/100: train_loss=0.654084, val_loss=0.593941, IC=-0.0255

      epoch  16/100: train_loss=0.653572

      epoch  17/100: train_loss=0.653212

      epoch  18/100: train_loss=0.653358

      epoch  19/100: train_loss=0.651017

      epoch  20/100: train_loss=0.653649, val_loss=0.591863, IC=-0.0179

      epoch  21/100: train_loss=0.652922

      epoch  22/100: train_loss=0.654071

      epoch  23/100: train_loss=0.651106

      epoch  24/100: train_loss=0.652231

      epoch  25/100: train_loss=0.649680, val_loss=0.593519, IC=-0.0247

      epoch  26/100: train_loss=0.651630

      epoch  27/100: train_loss=0.652373

      epoch  28/100: train_loss=0.649387

      epoch  29/100: train_loss=0.649776

      epoch  30/100: train_loss=0.651225, val_loss=0.594192, IC=-0.0235

      epoch  31/100: train_loss=0.650585

      epoch  32/100: train_loss=0.650941

      epoch  33/100: train_loss=0.649236

      epoch  34/100: train_loss=0.649663

      epoch  35/100: train_loss=0.649834, val_loss=0.596205, IC=-0.0251

      epoch  36/100: train_loss=0.647931

      epoch  37/100: train_loss=0.650188

      epoch  38/100: train_loss=0.649105

      epoch  39/100: train_loss=0.648079

      epoch  40/100: train_loss=0.647751, val_loss=0.595076, IC=-0.0238

      epoch  41/100: train_loss=0.647946

      epoch  42/100: train_loss=0.647698

      epoch  43/100: train_loss=0.647676

      epoch  44/100: train_loss=0.650452

      epoch  45/100: train_loss=0.650716, val_loss=0.595794, IC=-0.0255

      epoch  46/100: train_loss=0.648190

      epoch  47/100: train_loss=0.649110

      epoch  48/100: train_loss=0.649624

      epoch  49/100: train_loss=0.648549

      epoch  50/100: train_loss=0.648503, val_loss=0.594845, IC=-0.0232

      epoch  51/100: train_loss=0.650049

      epoch  52/100: train_loss=0.647981

      epoch  53/100: train_loss=0.647692

      epoch  54/100: train_loss=0.649220

      epoch  55/100: train_loss=0.650428, val_loss=0.594632, IC=-0.0219

      epoch  56/100: train_loss=0.648053

      epoch  57/100: train_loss=0.650052

      epoch  58/100: train_loss=0.649366

      epoch  59/100: train_loss=0.648456

      epoch  60/100: train_loss=0.649517, val_loss=0.594745, IC=-0.0234

      epoch  61/100: train_loss=0.647814

      epoch  62/100: train_loss=0.649774

      epoch  63/100: train_loss=0.648283

      epoch  64/100: train_loss=0.650779

      epoch  65/100: train_loss=0.647876, val_loss=0.594018, IC=-0.0215

      epoch  66/100: train_loss=0.649224

      epoch  67/100: train_loss=0.647927

      epoch  68/100: train_loss=0.648572

      epoch  69/100: train_loss=0.647795

      epoch  70/100: train_loss=0.647302, val_loss=0.594934, IC=-0.0225

      epoch  71/100: train_loss=0.650753

      epoch  72/100: train_loss=0.650657

      epoch  73/100: train_loss=0.648427

      epoch  74/100: train_loss=0.647531

      epoch  75/100: train_loss=0.648305, val_loss=0.595187, IC=-0.0243

      epoch  76/100: train_loss=0.648572

      epoch  77/100: train_loss=0.649637

      epoch  78/100: train_loss=0.649233

      epoch  79/100: train_loss=0.649614

      epoch  80/100: train_loss=0.649601, val_loss=0.594999, IC=-0.0229

      epoch  81/100: train_loss=0.648663

      epoch  82/100: train_loss=0.647634

      epoch  83/100: train_loss=0.647365

      epoch  84/100: train_loss=0.648512

      epoch  85/100: train_loss=0.648542, val_loss=0.595281, IC=-0.0233

      epoch  86/100: train_loss=0.646356

      epoch  87/100: train_loss=0.648643

      epoch  88/100: train_loss=0.648977

      epoch  89/100: train_loss=0.649739

      epoch  90/100: train_loss=0.649337, val_loss=0.595154, IC=-0.0233

      epoch  91/100: train_loss=0.648682

      epoch  92/100: train_loss=0.648193

      epoch  93/100: train_loss=0.648108

      epoch  94/100: train_loss=0.648123

      epoch  95/100: train_loss=0.648120, val_loss=0.595127, IC=-0.0231

      epoch  96/100: train_loss=0.647399

      epoch  97/100: train_loss=0.647522

      epoch  98/100: train_loss=0.646839

      epoch  99/100: train_loss=0.648571

      epoch 100/100: train_loss=0.648980, val_loss=0.595158, IC=-0.0232

      best_ep=5, IC=-0.0148 (100.7s, 20 checkpoints)

  Fold 1: creating sequences...

    train=51,093 seq across 474 symbols
    val=12,944 seq across 477 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.722893

      epoch   2/100: train_loss=0.631964

      epoch   3/100: train_loss=0.617467

      epoch   4/100: train_loss=0.609874

      epoch   5/100: train_loss=0.605278, val_loss=3.035968, IC=+0.0223

      epoch   6/100: train_loss=0.603924

      epoch   7/100: train_loss=0.601238

      epoch   8/100: train_loss=0.601402

      epoch   9/100: train_loss=0.600128

      epoch  10/100: train_loss=0.599535, val_loss=3.002142, IC=+0.0169

      epoch  11/100: train_loss=0.599237

      epoch  12/100: train_loss=0.598539

      epoch  13/100: train_loss=0.598633

      epoch  14/100: train_loss=0.598177

      epoch  15/100: train_loss=0.597526, val_loss=3.011291, IC=+0.0246

      epoch  16/100: train_loss=0.596601

      epoch  17/100: train_loss=0.595125

      epoch  18/100: train_loss=0.594707

      epoch  19/100: train_loss=0.593712

      epoch  20/100: train_loss=0.593245, val_loss=3.043282, IC=+0.0071

      epoch  21/100: train_loss=0.592487

      epoch  22/100: train_loss=0.592200

      epoch  23/100: train_loss=0.591587

      epoch  24/100: train_loss=0.591250

      epoch  25/100: train_loss=0.591600, val_loss=3.044929, IC=-0.0003

      epoch  26/100: train_loss=0.592187

      epoch  27/100: train_loss=0.591235

      epoch  28/100: train_loss=0.590910

      epoch  29/100: train_loss=0.591135

      epoch  30/100: train_loss=0.590359, val_loss=3.061912, IC=-0.0078

      epoch  31/100: train_loss=0.590612

      epoch  32/100: train_loss=0.591103

      epoch  33/100: train_loss=0.590726

      epoch  34/100: train_loss=0.590508

      epoch  35/100: train_loss=0.590945, val_loss=3.055688, IC=-0.0142

      epoch  36/100: train_loss=0.590725

      epoch  37/100: train_loss=0.591009

      epoch  38/100: train_loss=0.590759

      epoch  39/100: train_loss=0.590706

      epoch  40/100: train_loss=0.590302, val_loss=3.058559, IC=-0.0120

      epoch  41/100: train_loss=0.590477

      epoch  42/100: train_loss=0.590907

      epoch  43/100: train_loss=0.591024

      epoch  44/100: train_loss=0.590353

      epoch  45/100: train_loss=0.590606, val_loss=3.059805, IC=-0.0264

      epoch  46/100: train_loss=0.590106

      epoch  47/100: train_loss=0.590362

      epoch  48/100: train_loss=0.589886

      epoch  49/100: train_loss=0.590734

      epoch  50/100: train_loss=0.589620, val_loss=3.056851, IC=-0.0210

      epoch  51/100: train_loss=0.590320

      epoch  52/100: train_loss=0.590176

      epoch  53/100: train_loss=0.590815

      epoch  54/100: train_loss=0.589992

      epoch  55/100: train_loss=0.590379, val_loss=3.058452, IC=-0.0246

      epoch  56/100: train_loss=0.590303

      epoch  57/100: train_loss=0.589965

      epoch  58/100: train_loss=0.590407

      epoch  59/100: train_loss=0.590572

      epoch  60/100: train_loss=0.589837, val_loss=3.057826, IC=-0.0230

      epoch  61/100: train_loss=0.590413

      epoch  62/100: train_loss=0.590636

      epoch  63/100: train_loss=0.590432

      epoch  64/100: train_loss=0.589884

      epoch  65/100: train_loss=0.590134, val_loss=3.057145, IC=-0.0220

      epoch  66/100: train_loss=0.589750

      epoch  67/100: train_loss=0.590200

      epoch  68/100: train_loss=0.590137

      epoch  69/100: train_loss=0.589642

      epoch  70/100: train_loss=0.590053, val_loss=3.058058, IC=-0.0237

      epoch  71/100: train_loss=0.590100

      epoch  72/100: train_loss=0.589959

      epoch  73/100: train_loss=0.590637

      epoch  74/100: train_loss=0.590157

      epoch  75/100: train_loss=0.590151, val_loss=3.056019, IC=-0.0267

      epoch  76/100: train_loss=0.590253

      epoch  77/100: train_loss=0.590047

      epoch  78/100: train_loss=0.590200

      epoch  79/100: train_loss=0.589753

      epoch  80/100: train_loss=0.590320, val_loss=3.057484, IC=-0.0261

      epoch  81/100: train_loss=0.590498

      epoch  82/100: train_loss=0.590444

      epoch  83/100: train_loss=0.589755

      epoch  84/100: train_loss=0.589781

      epoch  85/100: train_loss=0.589948, val_loss=3.057452, IC=-0.0263

      epoch  86/100: train_loss=0.590064

      epoch  87/100: train_loss=0.589648

      epoch  88/100: train_loss=0.589793

      epoch  89/100: train_loss=0.590017

      epoch  90/100: train_loss=0.589720, val_loss=3.057761, IC=-0.0256

      epoch  91/100: train_loss=0.589391

      epoch  92/100: train_loss=0.590037

      epoch  93/100: train_loss=0.589943

      epoch  94/100: train_loss=0.589687

      epoch  95/100: train_loss=0.590284, val_loss=3.057543, IC=-0.0257

      epoch  96/100: train_loss=0.590611

      epoch  97/100: train_loss=0.589774

      epoch  98/100: train_loss=0.589871

      epoch  99/100: train_loss=0.589989

      epoch 100/100: train_loss=0.589665, val_loss=3.057388, IC=-0.0255

      best_ep=15, IC=+0.0246 (121.3s, 20 checkpoints)

  nlinear: best_epoch=5, IC=+0.0028 (222.0s)

  Best: nlinear @ epoch 5 (IC=+0.0028)
  Saved to ~/ml4t/public-sp500-standardization/case_studies/sp500_options/run_log/training/8d26c4c0f196/diagnostics

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("NLinear execution returned a partial checkpoint")
catalog

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ 3d08334ce │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ 34b       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ 7b1382f0c │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ fe0       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ e96ed99a5 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ 756       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ 8d780cf60 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ bbc       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ 9b0a0653e │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ aa6       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ c70e37e1e │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ 5d2       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ 44aea544f │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ 944       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ 7b0cdeea6 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ aed       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ 862d77aa2 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ 1c3       │
│ deep_lear ┆ ret_to_ex ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8d26c4c0f ┆ 60a9f3ccc │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 196       ┆ 24e       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

The NLinear checkpoint artifacts are complete. The official sequence population remains open
until `09a_lstm` and `09b_patchtst` publish their declared members.