# S&P 500 Options: LSTM

This notebook fits the declared LSTM member of the sequence population snapshotted by
`09_deep_learning`. Chronological windows, validation gaps, checkpoints, and prediction
eligibility are resolved through the shared sequence boundary.

Prerequisite: `09_deep_learning` must create the complete official sequence population.

**Why the population is declared in one notebook and filled by several.** The set of members is
a claim made once, before any of them is fitted, so that no family can be added or dropped after
its results are visible. This notebook fits one declared member into a population it did not
define and cannot extend; running it alone leaves the population incomplete rather than smaller.

## What this model is, and what it is being asked to do here

An LSTM reads a symbol's history one session at a time and carries a state forward, updating it
at each step through gates that decide how much of the new observation to admit and how much of
the existing state to keep. The gates are what separate it from a plain recurrent network: they
give the model a route by which information from many steps back can reach the output without
being multiplied away at every step, which is what makes a long lookback usable at all.

**What that buys on this data, and what it costs.** The cross-sectional families in this case
study see one row per symbol per decision time: whatever history matters has to have been
compressed into a feature first. This model is handed the window instead and left to decide what
in it matters, so a pattern nobody wrote a feature for is reachable. The cost is that it has far
more freedom to fit noise, and options data on a few hundred names is not abundant, so the
comparison against the cross-sectional families is the point of running it rather than a
formality.

**It is not expected to win, and that is worth saying before the numbers.** A sequence model
earns its keep where the ordering of observations carries information the features do not. If
it does not beat a gradient-boosted model on engineered features here, that is a result about
this data, not a failed run, and the chapter reports it either way.

In [1]:
"""Fit the declared S&P 500 options LSTM request."""

import polars as pl

from case_studies.sp500_options.research_workflow import (
    ALL_LABELS,
    declared_dl_device,
    model_request_catalog,
    open_study,
    published_dl_device,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_subset,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
PREVIEW_REDUCTIONS: dict = {}
DEVICE: str = ""

POPULATION_NAME: str = ""

### The device the population was fitted on

A network trained on a GPU and the same network trained on a CPU accumulate their sums in a
different order and reach different weights, so the device is part of what the fitted model is
and sits inside the training identity rather than beside it. The device this population was
fitted on is declared once, in `modeling.dl.device` in `config/setup.yaml`, and read from there
by all four deep-learning notebooks rather than retyped in each. On a machine with no NVIDIA
card the run stops here rather than quietly training something else: set `DEVICE="cpu"` and pass
a `POPULATION_NAME` to fit the same requests there, under a name of their own.

**Why a second name rather than a second run under the first.** The published population is a
claim about a specific set of fitted models. A CPU fit of the same request is a different set,
close but not identical, and letting it join the published name would make the population mean
"these requests, fitted somewhere" instead of "these models". The check above refuses that
combination outright rather than warning about it, because a warning in a long run is read once
and then not read.

**This is why the gradient-boosted families run on CPU and these run on GPU.** A reader without
a card can reproduce everything the book compares on trees; the sequence families are the part
that needs hardware, and they are separated so that the absence of a GPU costs a chapter's
comparison rather than the whole case study.

In [3]:
CANONICAL_POPULATION_NAME = "sp500-options-sequence-validation-v1"

published_device = published_dl_device()
device = declared_dl_device(DEVICE)
population_name = POPULATION_NAME or CANONICAL_POPULATION_NAME
if device != published_device and population_name == CANONICAL_POPULATION_NAME:
    raise ValueError(
        f"this run fits on {device!r}, not the published {published_device!r}, so its "
        f"identities are not the ones {CANONICAL_POPULATION_NAME!r} holds; pass "
        f"POPULATION_NAME to give them a population of their own"
    )
print(f"training device: {device} (declared: {published_device})")

training device: cuda (declared: cuda)

## Declared request

**What the settings decide.** `lookback: 60` is the window handed to the model: sixty sessions,
about a quarter, so a fitted state can span an earnings cycle without reaching back to a regime
the symbol has left. `hidden_size: 64` and `n_layers: 2` set how much the state can hold and how
many times it is re-read before the output; larger values fit more and generalize less, and on a
panel this size they are the first place overfitting shows. `dropout: 0.1` drops a tenth of the
connections on each training pass, which stops the network leaning on any single one.

`batch_size: 2048` is a throughput choice rather than a modelling one, but it is not neutral:
gradient noise falls as the batch grows, so a large batch trains more smoothly and explores
less. It is declared rather than tuned because tuning it would change what was fitted while
looking like an infrastructure decision.

**The configuration is read from a preset, not written here.** `lstm_h64` names a file under
`case_studies/config/`, so this notebook cannot quietly differ from the same architecture in
another chapter, and a reader comparing the two is comparing declarations rather than code.

**Every label is fitted, not just the primary one.** The request spans `ALL_LABELS`, because
selection downstream ranks across labels as well as across configurations, and a label with no
candidates cannot be chosen or ruled out.

In [4]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
requests = model_request_catalog(
    "deep_learning",
    labels=ALL_LABELS,
    config_names=("lstm_h64",),
)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": device},
    preview_reductions=PREVIEW_REDUCTIONS,
)
resolved_model_plan(resolved)

shape: (1, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ regressio ┆ … ┆ 2020-11-2 ┆ 20        ┆ canonical ┆ 9be44756 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 5         ┆           ┆           ┆ 048d     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

The shared sequence runner owns chronological window construction, fold fitting, fitted-state
reload, checkpoint publication, restart, and exact eligible-key validation.

**A checkpoint is part of a configuration, not a detail of how it was fitted.** Training runs for
100 epochs and publishes every fifth, so this one request becomes twenty scored candidates rather
than one. That is deliberate: a network's validation performance is not monotone in training
time, and the epoch at which it peaks is a property of the fit that a reader is entitled to see
rather than a number chosen after the fact. Each published checkpoint therefore carries its own
identity and competes on its own downstream, and picking the best epoch after seeing the results
is selection, which happens once, downstream, on backtests.

**Restart is a correctness property, not a convenience.** Fold fits are written as they finish
and reloaded rather than refitted, so a run interrupted after eight of ten folds resumes at the
ninth. What matters is not the time saved: it is that the alternative - starting over - invites
quietly reducing the job to make it fit, and a population assembled from a reduced re-run and a
full first attempt is not one population. Reloading a fitted state means the checkpoint that
reaches the registry is the one the schedule asked for, whatever happened to the process.

**Windows are built chronologically and never span a fold boundary.** A sequence handed to the
model has to end before the fold's validation window opens, or the state carries information
from the period being scored. The runner owns that construction for the same reason the fold
geometry is shared: it is the kind of rule that is easy to restate slightly differently in each
notebook and impossible to notice when someone does.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_subset(
        study,
        resolved,
        population=population_name,
    )
else:
    if not WORKSPACE or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=80,175 seq across 532 symbols
    val=56,536 seq across 556 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.665532

      epoch   2/100: train_loss=0.643745

      epoch   3/100: train_loss=0.606749

      epoch   4/100: train_loss=0.569481

      epoch   5/100: train_loss=0.530760, val_loss=0.745485, IC=-0.0006

      epoch   6/100: train_loss=0.489858

      epoch   7/100: train_loss=0.460526

      epoch   8/100: train_loss=0.430758

      epoch   9/100: train_loss=0.407867

      epoch  10/100: train_loss=0.386369, val_loss=0.875688, IC=+0.0013

      epoch  11/100: train_loss=0.365013

      epoch  12/100: train_loss=0.344240

      epoch  13/100: train_loss=0.328606

      epoch  14/100: train_loss=0.313261

      epoch  15/100: train_loss=0.300405, val_loss=0.979190, IC=-0.0129

      epoch  16/100: train_loss=0.287012

      epoch  17/100: train_loss=0.279258

      epoch  18/100: train_loss=0.266748

      epoch  19/100: train_loss=0.258038

      epoch  20/100: train_loss=0.246592, val_loss=0.985915, IC=-0.0113

      epoch  21/100: train_loss=0.238724

      epoch  22/100: train_loss=0.232381

      epoch  23/100: train_loss=0.225148

      epoch  24/100: train_loss=0.219657

      epoch  25/100: train_loss=0.213417, val_loss=1.017252, IC=-0.0143

      epoch  26/100: train_loss=0.208445

      epoch  27/100: train_loss=0.203382

      epoch  28/100: train_loss=0.197380

      epoch  29/100: train_loss=0.194047

      epoch  30/100: train_loss=0.191302, val_loss=1.009663, IC=-0.0112

      epoch  31/100: train_loss=0.188552

      epoch  32/100: train_loss=0.182931

      epoch  33/100: train_loss=0.181360

      epoch  34/100: train_loss=0.175997

      epoch  35/100: train_loss=0.174926, val_loss=1.007529, IC=-0.0156

      epoch  36/100: train_loss=0.173441

      epoch  37/100: train_loss=0.169577

      epoch  38/100: train_loss=0.166754

      epoch  39/100: train_loss=0.163763

      epoch  40/100: train_loss=0.161971, val_loss=1.027099, IC=-0.0086

      epoch  41/100: train_loss=0.158804

      epoch  42/100: train_loss=0.157596

      epoch  43/100: train_loss=0.155980

      epoch  44/100: train_loss=0.153160

      epoch  45/100: train_loss=0.152061, val_loss=1.058712, IC=-0.0049

      epoch  46/100: train_loss=0.151107

      epoch  47/100: train_loss=0.149317

      epoch  48/100: train_loss=0.148080

      epoch  49/100: train_loss=0.146305

      epoch  50/100: train_loss=0.145865, val_loss=1.030192, IC=-0.0079

      epoch  51/100: train_loss=0.143645

      epoch  52/100: train_loss=0.142324

      epoch  53/100: train_loss=0.140641

      epoch  54/100: train_loss=0.139218

      epoch  55/100: train_loss=0.138362, val_loss=1.051620, IC=-0.0089

      epoch  56/100: train_loss=0.137868

      epoch  57/100: train_loss=0.136738

      epoch  58/100: train_loss=0.134774

      epoch  59/100: train_loss=0.134239

      epoch  60/100: train_loss=0.133832, val_loss=1.060414, IC=-0.0099

      epoch  61/100: train_loss=0.132150

      epoch  62/100: train_loss=0.131750

      epoch  63/100: train_loss=0.131276

      epoch  64/100: train_loss=0.130275

      epoch  65/100: train_loss=0.129837, val_loss=1.063780, IC=-0.0077

      epoch  66/100: train_loss=0.127911

      epoch  67/100: train_loss=0.128048

      epoch  68/100: train_loss=0.127482

      epoch  69/100: train_loss=0.126745

      epoch  70/100: train_loss=0.126465, val_loss=1.060925, IC=-0.0069

      epoch  71/100: train_loss=0.125953

      epoch  72/100: train_loss=0.125194

      epoch  73/100: train_loss=0.124177

      epoch  74/100: train_loss=0.124154

      epoch  75/100: train_loss=0.123451, val_loss=1.070503, IC=-0.0087

      epoch  76/100: train_loss=0.122726

      epoch  77/100: train_loss=0.122411

      epoch  78/100: train_loss=0.123257

      epoch  79/100: train_loss=0.121577

      epoch  80/100: train_loss=0.121006, val_loss=1.063908, IC=-0.0085

      epoch  81/100: train_loss=0.121012

      epoch  82/100: train_loss=0.120892

      epoch  83/100: train_loss=0.120708

      epoch  84/100: train_loss=0.120657

      epoch  85/100: train_loss=0.120357, val_loss=1.066237, IC=-0.0078

      epoch  86/100: train_loss=0.119138

      epoch  87/100: train_loss=0.119665

      epoch  88/100: train_loss=0.119015

      epoch  89/100: train_loss=0.119092

      epoch  90/100: train_loss=0.118202, val_loss=1.072469, IC=-0.0084

      epoch  91/100: train_loss=0.118427

      epoch  92/100: train_loss=0.118798

      epoch  93/100: train_loss=0.118040

      epoch  94/100: train_loss=0.118317

      epoch  95/100: train_loss=0.118390, val_loss=1.069900, IC=-0.0086

      epoch  96/100: train_loss=0.117965

      epoch  97/100: train_loss=0.118334

      epoch  98/100: train_loss=0.117801

      epoch  99/100: train_loss=0.118163

      epoch 100/100: train_loss=0.118080, val_loss=1.069667, IC=-0.0085

      best_ep=10, IC=+0.0013 (380.8s, 20 checkpoints)

  Fold 1: creating sequences...

    train=94,348 seq across 522 symbols
    val=28,547 seq across 582 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.599045

      epoch   2/100: train_loss=0.574856

      epoch   3/100: train_loss=0.551855

      epoch   4/100: train_loss=0.515935

      epoch   5/100: train_loss=0.478628, val_loss=2.483858, IC=-0.0039

      epoch   6/100: train_loss=0.444591

      epoch   7/100: train_loss=0.416968

      epoch   8/100: train_loss=0.390833

      epoch   9/100: train_loss=0.366307

      epoch  10/100: train_loss=0.348854, val_loss=2.646206, IC=+0.0387

      epoch  11/100: train_loss=0.332146

      epoch  12/100: train_loss=0.317746

      epoch  13/100: train_loss=0.300649

      epoch  14/100: train_loss=0.287625

      epoch  15/100: train_loss=0.275739, val_loss=2.693006, IC=+0.0330

      epoch  16/100: train_loss=0.265411

      epoch  17/100: train_loss=0.255248

      epoch  18/100: train_loss=0.246108

      epoch  19/100: train_loss=0.238837

      epoch  20/100: train_loss=0.229301, val_loss=2.741297, IC=+0.0315

      epoch  21/100: train_loss=0.223678

      epoch  22/100: train_loss=0.216706

      epoch  23/100: train_loss=0.210750

      epoch  24/100: train_loss=0.205397

      epoch  25/100: train_loss=0.201812, val_loss=2.721679, IC=+0.0496

      epoch  26/100: train_loss=0.195654

      epoch  27/100: train_loss=0.190024

      epoch  28/100: train_loss=0.187991

      epoch  29/100: train_loss=0.182689

      epoch  30/100: train_loss=0.179599, val_loss=2.738237, IC=+0.0619

      epoch  31/100: train_loss=0.176392

      epoch  32/100: train_loss=0.171808

      epoch  33/100: train_loss=0.169426

      epoch  34/100: train_loss=0.164741

      epoch  35/100: train_loss=0.163414, val_loss=2.695035, IC=+0.0639

      epoch  36/100: train_loss=0.159553

      epoch  37/100: train_loss=0.157820

      epoch  38/100: train_loss=0.156693

      epoch  39/100: train_loss=0.153879

      epoch  40/100: train_loss=0.151020, val_loss=2.763018, IC=+0.0610

      epoch  41/100: train_loss=0.149481

      epoch  42/100: train_loss=0.147310

      epoch  43/100: train_loss=0.145304

      epoch  44/100: train_loss=0.144727

      epoch  45/100: train_loss=0.143182, val_loss=2.775836, IC=+0.0612

      epoch  46/100: train_loss=0.140618

      epoch  47/100: train_loss=0.141269

      epoch  48/100: train_loss=0.138185

      epoch  49/100: train_loss=0.137312

      epoch  50/100: train_loss=0.136509, val_loss=2.766154, IC=+0.0495

      epoch  51/100: train_loss=0.134525

      epoch  52/100: train_loss=0.132977

      epoch  53/100: train_loss=0.131958

      epoch  54/100: train_loss=0.130546

      epoch  55/100: train_loss=0.129856, val_loss=2.785276, IC=+0.0460

      epoch  56/100: train_loss=0.128495

      epoch  57/100: train_loss=0.128540

      epoch  58/100: train_loss=0.126626

      epoch  59/100: train_loss=0.126646

      epoch  60/100: train_loss=0.125407, val_loss=2.773143, IC=+0.0464

      epoch  61/100: train_loss=0.124643

      epoch  62/100: train_loss=0.124096

      epoch  63/100: train_loss=0.122934

      epoch  64/100: train_loss=0.123012

      epoch  65/100: train_loss=0.120921, val_loss=2.773672, IC=+0.0512

      epoch  66/100: train_loss=0.121843

      epoch  67/100: train_loss=0.120207

      epoch  68/100: train_loss=0.119052

      epoch  69/100: train_loss=0.119452

      epoch  70/100: train_loss=0.119217, val_loss=2.779350, IC=+0.0540

      epoch  71/100: train_loss=0.117757

      epoch  72/100: train_loss=0.117239

      epoch  73/100: train_loss=0.117427

      epoch  74/100: train_loss=0.116602

      epoch  75/100: train_loss=0.115539, val_loss=2.799899, IC=+0.0516

      epoch  76/100: train_loss=0.115832

      epoch  77/100: train_loss=0.115600

      epoch  78/100: train_loss=0.114978

      epoch  79/100: train_loss=0.114997

      epoch  80/100: train_loss=0.114615, val_loss=2.784022, IC=+0.0514

      epoch  81/100: train_loss=0.113378

      epoch  82/100: train_loss=0.113591

      epoch  83/100: train_loss=0.113702

      epoch  84/100: train_loss=0.112665

      epoch  85/100: train_loss=0.112587, val_loss=2.792537, IC=+0.0512

      epoch  86/100: train_loss=0.112458

      epoch  87/100: train_loss=0.112311

      epoch  88/100: train_loss=0.112000

      epoch  89/100: train_loss=0.112167

      epoch  90/100: train_loss=0.111787, val_loss=2.793654, IC=+0.0509

      epoch  91/100: train_loss=0.111639

      epoch  92/100: train_loss=0.111662

      epoch  93/100: train_loss=0.111771

      epoch  94/100: train_loss=0.112920

      epoch  95/100: train_loss=0.111652, val_loss=2.794960, IC=+0.0506

      epoch  96/100: train_loss=0.111222

      epoch  97/100: train_loss=0.111858

      epoch  98/100: train_loss=0.111956

      epoch  99/100: train_loss=0.111341

      epoch 100/100: train_loss=0.111032, val_loss=2.794389, IC=+0.0508

      best_ep=35, IC=+0.0639 (463.4s, 20 checkpoints)

  lstm_h64: best_epoch=45, IC=+0.0265 (844.3s)

  Best: lstm_h64 @ epoch 45 (IC=+0.0265)
  Saved to ~/ml4t/public-dl-rerun/case_studies/sp500_options/run_log/training/9be44756048d/diagnostics

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("LSTM execution returned a partial checkpoint")
catalog

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ 0f548a210 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ 9cf       │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ f842b4cd9 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ 29f       │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ d92ff679e │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ 5ab       │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ cdd4268a4 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ 46a       │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ eb6405cd5 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ 02c       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ 01e68c8df │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ 7ed       │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ 43321039a │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ c1e       │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ 3d8250327 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ e5f       │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ 84a847229 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ 545       │
│ deep_lear ┆ ret_to_ex ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 9be447560 ┆ f0b3ba50b │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 48d       ┆ ad8       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

The complete LSTM checkpoint population is ready for model analysis and backtesting. This
notebook does not compare it with another family or choose a checkpoint.

**What completeness means here and why it is checked before anything leaves.** Every requested
checkpoint produced predictions on exactly the rows its eligibility contract declared - not
more, and not fewer. A partial checkpoint is refused rather than published, because a downstream
comparison against a model scored on a subset of the panel is not a comparison, and the subset
is invisible by the time anyone reads the result.

**The eligible rows are fewer than the cross-sectional families see, and that is structural.**
A symbol cannot be scored until sixty sessions of it exist, so this family is eligible on
strictly fewer rows than a model reading one row at a time. `11_model_analysis` groups by
eligibility for exactly this reason: comparing an IC from this population against one from a
cross-sectional population mixes the models with the rows they were scored on.