# S&P 500 Options: PatchTST

This notebook fits the declared PatchTST member of the sequence population snapshotted by
`09_deep_learning`. After publishing every PatchTST checkpoint, it verifies that the complete
NLinear, LSTM, and PatchTST population is present.

Prerequisites: `09_deep_learning` and `09a_lstm`.

In [1]:
"""Fit the declared S&P 500 options PatchTST request."""

import polars as pl

from case_studies.sp500_options.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_subset,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
PREVIEW_REDUCTIONS: dict = {}

POPULATION_NAME = "sp500-options-sequence-validation-v1"

## Declared request

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
requests = model_request_catalog(
    "deep_learning",
    labels=ALL_LABELS,
    config_names=("patchtst",),
)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    preview_reductions=PREVIEW_REDUCTIONS,
)
resolved_model_plan(resolved)

shape: (1, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ regressio ┆ … ┆ 2020-11-1 ┆ 20        ┆ canonical ┆ 04915ba9 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 0         ┆           ┆           ┆ cfb2     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

The shared sequence runner owns gap-safe window construction, fold fitting, fitted-state reload,
checkpoint publication, restart, and exact eligible-key validation.

In [4]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_subset(
        study,
        resolved,
        population=POPULATION_NAME,
        require_population_complete=True,
    )
else:
    if not WORKSPACE or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=49,629 seq across 472 symbols
    val=12,326 seq across 473 symbols
    creating datasets...
    datasets ready
    patchtst:

      epoch   1/100: train_loss=0.630326

      epoch   2/100: train_loss=0.610269

      epoch   3/100: train_loss=0.613247

      epoch   4/100: train_loss=0.600285

      epoch   5/100: train_loss=0.594785, val_loss=5.275345, IC=+0.0119

      epoch   6/100: train_loss=0.590918

      epoch   7/100: train_loss=0.586954

      epoch   8/100: train_loss=0.582196

      epoch   9/100: train_loss=0.575226

      epoch  10/100: train_loss=0.573336, val_loss=5.101873, IC=+0.0095

      epoch  11/100: train_loss=0.566365

      epoch  12/100: train_loss=0.562903

      epoch  13/100: train_loss=0.557086

      epoch  14/100: train_loss=0.555624

      epoch  15/100: train_loss=0.547896, val_loss=5.290106, IC=+0.0193

      epoch  16/100: train_loss=0.547405

      epoch  17/100: train_loss=0.545447

      epoch  18/100: train_loss=0.536452

      epoch  19/100: train_loss=0.532438

      epoch  20/100: train_loss=0.532137, val_loss=5.382377, IC=+0.0308

      epoch  21/100: train_loss=0.525181

      epoch  22/100: train_loss=0.521447

      epoch  23/100: train_loss=0.517269

      epoch  24/100: train_loss=0.513853

      epoch  25/100: train_loss=0.509825, val_loss=5.376900, IC=+0.0181

      epoch  26/100: train_loss=0.509749

      epoch  27/100: train_loss=0.501959

      epoch  28/100: train_loss=0.503120

      epoch  29/100: train_loss=0.501349

      epoch  30/100: train_loss=0.494848, val_loss=5.237667, IC=+0.0170

      epoch  31/100: train_loss=0.493839

      epoch  32/100: train_loss=0.487690

      epoch  33/100: train_loss=0.485484

      epoch  34/100: train_loss=0.481515

      epoch  35/100: train_loss=0.481285, val_loss=5.336406, IC=+0.0195

      epoch  36/100: train_loss=0.477780

      epoch  37/100: train_loss=0.475618

      epoch  38/100: train_loss=0.473712

      epoch  39/100: train_loss=0.474260

      epoch  40/100: train_loss=0.468011, val_loss=5.387724, IC=+0.0231

      epoch  41/100: train_loss=0.464624

      epoch  42/100: train_loss=0.463355

      epoch  43/100: train_loss=0.461515

      epoch  44/100: train_loss=0.457185

      epoch  45/100: train_loss=0.455682, val_loss=5.371022, IC=+0.0209

      epoch  46/100: train_loss=0.453045

      epoch  47/100: train_loss=0.450910

      epoch  48/100: train_loss=0.449262

      epoch  49/100: train_loss=0.449646

      epoch  50/100: train_loss=0.447919, val_loss=5.452673, IC=+0.0178

      epoch  51/100: train_loss=0.443040

      epoch  52/100: train_loss=0.444146

      epoch  53/100: train_loss=0.442084

      epoch  54/100: train_loss=0.441186

      epoch  55/100: train_loss=0.435535, val_loss=5.419557, IC=+0.0288

      epoch  56/100: train_loss=0.433482

      epoch  57/100: train_loss=0.435411

      epoch  58/100: train_loss=0.434028

      epoch  59/100: train_loss=0.430806

      epoch  60/100: train_loss=0.431325, val_loss=5.431647, IC=+0.0214

      epoch  61/100: train_loss=0.432836

      epoch  62/100: train_loss=0.425509

      epoch  63/100: train_loss=0.425926

      epoch  64/100: train_loss=0.425704

      epoch  65/100: train_loss=0.423210, val_loss=5.464495, IC=+0.0250

      epoch  66/100: train_loss=0.423546

      epoch  67/100: train_loss=0.425143

      epoch  68/100: train_loss=0.421308

      epoch  69/100: train_loss=0.421062

      epoch  70/100: train_loss=0.418345, val_loss=5.510318, IC=+0.0270

      epoch  71/100: train_loss=0.419754

      epoch  72/100: train_loss=0.417512

      epoch  73/100: train_loss=0.415388

      epoch  74/100: train_loss=0.416666

      epoch  75/100: train_loss=0.418570, val_loss=5.458926, IC=+0.0300

      epoch  76/100: train_loss=0.414745

      epoch  77/100: train_loss=0.417371

      epoch  78/100: train_loss=0.413381

      epoch  79/100: train_loss=0.416956

      epoch  80/100: train_loss=0.415235, val_loss=5.461594, IC=+0.0240

      epoch  81/100: train_loss=0.411245

      epoch  82/100: train_loss=0.410156

      epoch  83/100: train_loss=0.411744

      epoch  84/100: train_loss=0.412051

      epoch  85/100: train_loss=0.410454, val_loss=5.483445, IC=+0.0275

      epoch  86/100: train_loss=0.411836

      epoch  87/100: train_loss=0.408912

      epoch  88/100: train_loss=0.408992

      epoch  89/100: train_loss=0.411328

      epoch  90/100: train_loss=0.410501, val_loss=5.463483, IC=+0.0258

      epoch  91/100: train_loss=0.409744

      epoch  92/100: train_loss=0.407685

      epoch  93/100: train_loss=0.406685

      epoch  94/100: train_loss=0.409534

      epoch  95/100: train_loss=0.408567, val_loss=5.469593, IC=+0.0254

      epoch  96/100: train_loss=0.410087

      epoch  97/100: train_loss=0.410187

      epoch  98/100: train_loss=0.408676

      epoch  99/100: train_loss=0.409666

      epoch 100/100: train_loss=0.406686, val_loss=5.469163, IC=+0.0254

      best_ep=20, IC=+0.0308 (707.2s, 20 checkpoints)

  Fold 1: creating sequences...

    train=36,365 seq across 468 symbols
    val=29,860 seq across 480 symbols
    creating datasets...
    datasets ready
    patchtst:

      epoch   1/100: train_loss=0.836445

      epoch   2/100: train_loss=0.767452

      epoch   3/100: train_loss=0.750512

      epoch   4/100: train_loss=0.740662

      epoch   5/100: train_loss=0.735817, val_loss=0.613515, IC=-0.0203

      epoch   6/100: train_loss=0.729853

      epoch   7/100: train_loss=0.725005

      epoch   8/100: train_loss=0.716740

      epoch   9/100: train_loss=0.709781

      epoch  10/100: train_loss=0.703684, val_loss=0.649928, IC=-0.0074

      epoch  11/100: train_loss=0.700068

      epoch  12/100: train_loss=0.693831

      epoch  13/100: train_loss=0.684206

      epoch  14/100: train_loss=0.680076

      epoch  15/100: train_loss=0.671058, val_loss=0.676777, IC=+0.0005

      epoch  16/100: train_loss=0.663090

      epoch  17/100: train_loss=0.657008

      epoch  18/100: train_loss=0.650480

      epoch  19/100: train_loss=0.648264

      epoch  20/100: train_loss=0.639348, val_loss=0.736960, IC=-0.0019

      epoch  21/100: train_loss=0.633619

      epoch  22/100: train_loss=0.625870

      epoch  23/100: train_loss=0.622526

      epoch  24/100: train_loss=0.612674

      epoch  25/100: train_loss=0.606331, val_loss=0.741873, IC=+0.0035

      epoch  26/100: train_loss=0.601318

      epoch  27/100: train_loss=0.594554

      epoch  28/100: train_loss=0.587527

      epoch  29/100: train_loss=0.580433

      epoch  30/100: train_loss=0.574614, val_loss=0.756260, IC=+0.0099

      epoch  31/100: train_loss=0.572485

      epoch  32/100: train_loss=0.563036

      epoch  33/100: train_loss=0.558616

      epoch  34/100: train_loss=0.552910

      epoch  35/100: train_loss=0.543119, val_loss=0.767631, IC=+0.0120

      epoch  36/100: train_loss=0.540268

      epoch  37/100: train_loss=0.535966

      epoch  38/100: train_loss=0.530575

      epoch  39/100: train_loss=0.526018

      epoch  40/100: train_loss=0.520401, val_loss=0.800272, IC=+0.0146

      epoch  41/100: train_loss=0.513694

      epoch  42/100: train_loss=0.507755

      epoch  43/100: train_loss=0.503675

      epoch  44/100: train_loss=0.500322

      epoch  45/100: train_loss=0.493349, val_loss=0.822415, IC=+0.0124

      epoch  46/100: train_loss=0.491513

      epoch  47/100: train_loss=0.484072

      epoch  48/100: train_loss=0.485622

      epoch  49/100: train_loss=0.478932

      epoch  50/100: train_loss=0.481863, val_loss=0.777229, IC=+0.0158

      epoch  51/100: train_loss=0.475754

      epoch  52/100: train_loss=0.471991

      epoch  53/100: train_loss=0.468481

      epoch  54/100: train_loss=0.470553

      epoch  55/100: train_loss=0.466642, val_loss=0.799273, IC=+0.0159

      epoch  56/100: train_loss=0.461504

      epoch  57/100: train_loss=0.459966

      epoch  58/100: train_loss=0.458102

      epoch  59/100: train_loss=0.454531

      epoch  60/100: train_loss=0.454908, val_loss=0.813282, IC=+0.0136

      epoch  61/100: train_loss=0.453443

      epoch  62/100: train_loss=0.448057

      epoch  63/100: train_loss=0.451805

      epoch  64/100: train_loss=0.446314

      epoch  65/100: train_loss=0.446520, val_loss=0.807731, IC=+0.0156

      epoch  66/100: train_loss=0.441967

      epoch  67/100: train_loss=0.440195

      epoch  68/100: train_loss=0.439023

      epoch  69/100: train_loss=0.436769

      epoch  70/100: train_loss=0.438571, val_loss=0.820408, IC=+0.0135

      epoch  71/100: train_loss=0.435658

      epoch  72/100: train_loss=0.436947

      epoch  73/100: train_loss=0.434417

      epoch  74/100: train_loss=0.430053

      epoch  75/100: train_loss=0.434627, val_loss=0.825730, IC=+0.0152

      epoch  76/100: train_loss=0.429100

      epoch  77/100: train_loss=0.431883

      epoch  78/100: train_loss=0.425373

      epoch  79/100: train_loss=0.427847

      epoch  80/100: train_loss=0.429066, val_loss=0.825102, IC=+0.0155

      epoch  81/100: train_loss=0.424852

      epoch  82/100: train_loss=0.429441

      epoch  83/100: train_loss=0.421089

      epoch  84/100: train_loss=0.424323

      epoch  85/100: train_loss=0.423519, val_loss=0.827788, IC=+0.0146

      epoch  86/100: train_loss=0.425697

      epoch  87/100: train_loss=0.425375

      epoch  88/100: train_loss=0.422972

      epoch  89/100: train_loss=0.423699

      epoch  90/100: train_loss=0.419660, val_loss=0.824002, IC=+0.0145

      epoch  91/100: train_loss=0.422223

      epoch  92/100: train_loss=0.425287

      epoch  93/100: train_loss=0.419980

      epoch  94/100: train_loss=0.423500

      epoch  95/100: train_loss=0.422314, val_loss=0.827579, IC=+0.0144

      epoch  96/100: train_loss=0.419321

      epoch  97/100: train_loss=0.419017

      epoch  98/100: train_loss=0.424065

      epoch  99/100: train_loss=0.421893

      epoch 100/100: train_loss=0.424375, val_loss=0.828537, IC=+0.0143

      best_ep=55, IC=+0.0159 (542.4s, 20 checkpoints)

  patchtst: best_epoch=75, IC=+0.0220 (1249.6s)

  Best: patchtst @ epoch 75 (IC=+0.0220)
  Saved to ~/ml4t/public-s6-sp500_options/case_studies/sp500_options/run_log/training/04915ba9cfb2/diagnostics

In [5]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("PatchTST execution returned a partial checkpoint")
catalog

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ 405d5def3 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ 578       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ 9a69eca3e │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ 2fc       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ f2c2242da │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ 98d       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ 693e6c2ef │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ e60       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ 922fbd410 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ b29       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ d1304ac97 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ f9d       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ 03c93e496 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ 261       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ de859816c │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ bec       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ 9a880447c │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ 579       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 04915ba9c ┆ a3f1c818a │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ fb2       ┆ 801       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

The official sequence population is complete and ready for model analysis and backtesting. This
notebook does not compare configurations or choose a checkpoint.