# S&P 500 Options: PatchTST

This notebook fits the declared PatchTST member of the sequence population snapshotted by
`09_deep_learning`. After publishing every PatchTST checkpoint, it verifies that the complete
NLinear, LSTM, and PatchTST population is present.

Prerequisites: `09_deep_learning` and `09a_lstm`.

In [1]:
"""Fit the declared S&P 500 options PatchTST request."""

import polars as pl

from case_studies.sp500_options.research_workflow import (
    ALL_LABELS,
    declared_dl_device,
    model_request_catalog,
    open_study,
    published_dl_device,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_subset,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
PREVIEW_REDUCTIONS: dict = {}
DEVICE: str = ""

POPULATION_NAME: str = ""

### The device the population was fitted on

A network trained on a GPU and the same network trained on a CPU accumulate their sums in a
different order and reach different weights, so the device is part of what the fitted model is
and sits inside the training identity rather than beside it. The device this population was
fitted on is declared once, in `modeling.dl.device` in `config/setup.yaml`, and read from there
by all four deep-learning notebooks rather than retyped in each. On a machine with no NVIDIA
card the run stops here rather than quietly training something else: set `DEVICE="cpu"` and pass
a `POPULATION_NAME` to fit the same requests there, under a name of their own.

In [3]:
CANONICAL_POPULATION_NAME = "sp500-options-sequence-validation-v1"

published_device = published_dl_device()
device = declared_dl_device(DEVICE)
population_name = POPULATION_NAME or CANONICAL_POPULATION_NAME
if device != published_device and population_name == CANONICAL_POPULATION_NAME:
    raise ValueError(
        f"this run fits on {device!r}, not the published {published_device!r}, so its "
        f"identities are not the ones {CANONICAL_POPULATION_NAME!r} holds; pass "
        f"POPULATION_NAME to give them a population of their own"
    )
print(f"training device: {device} (declared: {published_device})")

training device: cuda (declared: cuda)

## Declared request

In [4]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
requests = model_request_catalog(
    "deep_learning",
    labels=ALL_LABELS,
    config_names=("patchtst",),
)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": device},
    preview_reductions=PREVIEW_REDUCTIONS,
)
resolved_model_plan(resolved)

shape: (1, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ regressio ┆ … ┆ 2020-11-1 ┆ 20        ┆ canonical ┆ 472344b7 │
│ ning      ┆ piry      ┆           ┆ n         ┆   ┆ 0         ┆           ┆           ┆ 74ad     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

The shared sequence runner owns gap-safe window construction, fold fitting, fitted-state reload,
checkpoint publication, restart, and exact eligible-key validation.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_subset(
        study,
        resolved,
        population=population_name,
        require_population_complete=True,
    )
else:
    if not WORKSPACE or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=49,609 seq across 472 symbols
    val=12,146 seq across 473 symbols
    creating datasets...
    datasets ready
    patchtst:

      epoch   1/100: train_loss=0.620928

      epoch   2/100: train_loss=0.601182

      epoch   3/100: train_loss=0.594474

      epoch   4/100: train_loss=0.594739

      epoch   5/100: train_loss=0.589104, val_loss=3.111397, IC=+0.0185

      epoch   6/100: train_loss=0.581556

      epoch   7/100: train_loss=0.576433

      epoch   8/100: train_loss=0.569923

      epoch   9/100: train_loss=0.570058

      epoch  10/100: train_loss=0.565585, val_loss=3.112644, IC=+0.0347

      epoch  11/100: train_loss=0.557589

      epoch  12/100: train_loss=0.555775

      epoch  13/100: train_loss=0.547016

      epoch  14/100: train_loss=0.543790

      epoch  15/100: train_loss=0.538738, val_loss=3.084783, IC=+0.0233

      epoch  16/100: train_loss=0.539036

      epoch  17/100: train_loss=0.529492

      epoch  18/100: train_loss=0.526558

      epoch  19/100: train_loss=0.522623

      epoch  20/100: train_loss=0.520640, val_loss=3.087595, IC=+0.0170

      epoch  21/100: train_loss=0.513503

      epoch  22/100: train_loss=0.512847

      epoch  23/100: train_loss=0.508138

      epoch  24/100: train_loss=0.503613

      epoch  25/100: train_loss=0.503848, val_loss=3.078620, IC=+0.0089

      epoch  26/100: train_loss=0.499660

      epoch  27/100: train_loss=0.494499

      epoch  28/100: train_loss=0.491997

      epoch  29/100: train_loss=0.489367

      epoch  30/100: train_loss=0.487875, val_loss=3.186359, IC=+0.0059

      epoch  31/100: train_loss=0.485710

      epoch  32/100: train_loss=0.482733

      epoch  33/100: train_loss=0.478582

      epoch  34/100: train_loss=0.476078

      epoch  35/100: train_loss=0.469005, val_loss=3.252980, IC=+0.0150

      epoch  36/100: train_loss=0.468388

      epoch  37/100: train_loss=0.466078

      epoch  38/100: train_loss=0.464872

      epoch  39/100: train_loss=0.460277

      epoch  40/100: train_loss=0.461411, val_loss=3.203971, IC=+0.0094

      epoch  41/100: train_loss=0.460940

      epoch  42/100: train_loss=0.456798

      epoch  43/100: train_loss=0.452671

      epoch  44/100: train_loss=0.452925

      epoch  45/100: train_loss=0.447912, val_loss=3.259948, IC=+0.0207

      epoch  46/100: train_loss=0.447008

      epoch  47/100: train_loss=0.448994

      epoch  48/100: train_loss=0.443875

      epoch  49/100: train_loss=0.444917

      epoch  50/100: train_loss=0.441174, val_loss=3.251682, IC=+0.0105

      epoch  51/100: train_loss=0.436442

      epoch  52/100: train_loss=0.437986

      epoch  53/100: train_loss=0.437817

      epoch  54/100: train_loss=0.434379

      epoch  55/100: train_loss=0.429704, val_loss=3.299511, IC=+0.0029

      epoch  56/100: train_loss=0.429203

      epoch  57/100: train_loss=0.432390

      epoch  58/100: train_loss=0.429676

      epoch  59/100: train_loss=0.430080

      epoch  60/100: train_loss=0.427183, val_loss=3.321076, IC=+0.0138

      epoch  61/100: train_loss=0.422224

      epoch  62/100: train_loss=0.423341

      epoch  63/100: train_loss=0.422089

      epoch  64/100: train_loss=0.423364

      epoch  65/100: train_loss=0.422577, val_loss=3.340875, IC=+0.0100

      epoch  66/100: train_loss=0.421813

      epoch  67/100: train_loss=0.419143

      epoch  68/100: train_loss=0.420833

      epoch  69/100: train_loss=0.416699

      epoch  70/100: train_loss=0.418489, val_loss=3.344645, IC=+0.0110

      epoch  71/100: train_loss=0.415397

      epoch  72/100: train_loss=0.417551

      epoch  73/100: train_loss=0.413869

      epoch  74/100: train_loss=0.416223

      epoch  75/100: train_loss=0.412137, val_loss=3.375097, IC=+0.0053

      epoch  76/100: train_loss=0.411119

      epoch  77/100: train_loss=0.412163

      epoch  78/100: train_loss=0.413029

      epoch  79/100: train_loss=0.410396

      epoch  80/100: train_loss=0.413578, val_loss=3.352926, IC=+0.0078

      epoch  81/100: train_loss=0.410207

      epoch  82/100: train_loss=0.413259

      epoch  83/100: train_loss=0.409692

      epoch  84/100: train_loss=0.410072

      epoch  85/100: train_loss=0.411011, val_loss=3.369693, IC=+0.0076

      epoch  86/100: train_loss=0.407271

      epoch  87/100: train_loss=0.407731

      epoch  88/100: train_loss=0.410142

      epoch  89/100: train_loss=0.408229

      epoch  90/100: train_loss=0.407768, val_loss=3.353737, IC=+0.0070

      epoch  91/100: train_loss=0.408354

      epoch  92/100: train_loss=0.408236

      epoch  93/100: train_loss=0.407816

      epoch  94/100: train_loss=0.407465

      epoch  95/100: train_loss=0.408435, val_loss=3.350178, IC=+0.0086

      epoch  96/100: train_loss=0.407890

      epoch  97/100: train_loss=0.405531

      epoch  98/100: train_loss=0.406868

      epoch  99/100: train_loss=0.407441

      epoch 100/100: train_loss=0.405729, val_loss=3.353321, IC=+0.0087

      best_ep=10, IC=+0.0347 (747.0s, 20 checkpoints)

  Fold 1: creating sequences...

    train=36,322 seq across 468 symbols
    val=29,860 seq across 480 symbols
    creating datasets...
    datasets ready
    patchtst:

      epoch   1/100: train_loss=0.722437

      epoch   2/100: train_loss=0.661106

      epoch   3/100: train_loss=0.646860

      epoch   4/100: train_loss=0.641357

      epoch   5/100: train_loss=0.636350, val_loss=0.606270, IC=-0.0200

      epoch   6/100: train_loss=0.630011

      epoch   7/100: train_loss=0.626146

      epoch   8/100: train_loss=0.621561

      epoch   9/100: train_loss=0.615964

      epoch  10/100: train_loss=0.613024, val_loss=0.630885, IC=-0.0059

      epoch  11/100: train_loss=0.604989

      epoch  12/100: train_loss=0.600153

      epoch  13/100: train_loss=0.593133

      epoch  14/100: train_loss=0.588233

      epoch  15/100: train_loss=0.584189, val_loss=0.658494, IC=-0.0025

      epoch  16/100: train_loss=0.580157

      epoch  17/100: train_loss=0.573191

      epoch  18/100: train_loss=0.568293

      epoch  19/100: train_loss=0.564569

      epoch  20/100: train_loss=0.559493, val_loss=0.674662, IC=+0.0045

      epoch  21/100: train_loss=0.552497

      epoch  22/100: train_loss=0.548663

      epoch  23/100: train_loss=0.541647

      epoch  24/100: train_loss=0.536636

      epoch  25/100: train_loss=0.534070, val_loss=0.697495, IC=+0.0036

      epoch  26/100: train_loss=0.528861

      epoch  27/100: train_loss=0.524725

      epoch  28/100: train_loss=0.518024

      epoch  29/100: train_loss=0.516877

      epoch  30/100: train_loss=0.512381, val_loss=0.707198, IC=+0.0092

      epoch  31/100: train_loss=0.504217

      epoch  32/100: train_loss=0.499591

      epoch  33/100: train_loss=0.497340

      epoch  34/100: train_loss=0.493333

      epoch  35/100: train_loss=0.490868, val_loss=0.741787, IC=+0.0062

      epoch  36/100: train_loss=0.484209

      epoch  37/100: train_loss=0.482439

      epoch  38/100: train_loss=0.477203

      epoch  39/100: train_loss=0.473333

      epoch  40/100: train_loss=0.470283, val_loss=0.753467, IC=+0.0095

      epoch  41/100: train_loss=0.468987

      epoch  42/100: train_loss=0.464907

      epoch  43/100: train_loss=0.461970

      epoch  44/100: train_loss=0.457970

      epoch  45/100: train_loss=0.453808, val_loss=0.768029, IC=+0.0098

      epoch  46/100: train_loss=0.452023

      epoch  47/100: train_loss=0.449995

      epoch  48/100: train_loss=0.444378

      epoch  49/100: train_loss=0.443338

      epoch  50/100: train_loss=0.442169, val_loss=0.782667, IC=+0.0098

      epoch  51/100: train_loss=0.440025

      epoch  52/100: train_loss=0.436796

      epoch  53/100: train_loss=0.433095

      epoch  54/100: train_loss=0.429582

      epoch  55/100: train_loss=0.430529, val_loss=0.785716, IC=+0.0118

      epoch  56/100: train_loss=0.425776

      epoch  57/100: train_loss=0.428083

      epoch  58/100: train_loss=0.425799

      epoch  59/100: train_loss=0.423583

      epoch  60/100: train_loss=0.421628, val_loss=0.800647, IC=+0.0092

      epoch  61/100: train_loss=0.420144

      epoch  62/100: train_loss=0.417334

      epoch  63/100: train_loss=0.414680

      epoch  64/100: train_loss=0.414567

      epoch  65/100: train_loss=0.411812, val_loss=0.803449, IC=+0.0116

      epoch  66/100: train_loss=0.410307

      epoch  67/100: train_loss=0.414254

      epoch  68/100: train_loss=0.408163

      epoch  69/100: train_loss=0.406909

      epoch  70/100: train_loss=0.406728, val_loss=0.810011, IC=+0.0105

      epoch  71/100: train_loss=0.405205

      epoch  72/100: train_loss=0.404728

      epoch  73/100: train_loss=0.402330

      epoch  74/100: train_loss=0.402619

      epoch  75/100: train_loss=0.402058, val_loss=0.812110, IC=+0.0091

      epoch  76/100: train_loss=0.401679

      epoch  77/100: train_loss=0.401204

      epoch  78/100: train_loss=0.398672

      epoch  79/100: train_loss=0.399445

      epoch  80/100: train_loss=0.395806, val_loss=0.819543, IC=+0.0094

      epoch  81/100: train_loss=0.396465

      epoch  82/100: train_loss=0.399793

      epoch  83/100: train_loss=0.394969

      epoch  84/100: train_loss=0.395846

      epoch  85/100: train_loss=0.394444, val_loss=0.820127, IC=+0.0089

      epoch  86/100: train_loss=0.394474

      epoch  87/100: train_loss=0.396536

      epoch  88/100: train_loss=0.392990

      epoch  89/100: train_loss=0.397811

      epoch  90/100: train_loss=0.395220, val_loss=0.819959, IC=+0.0090

      epoch  91/100: train_loss=0.394281

      epoch  92/100: train_loss=0.394307

      epoch  93/100: train_loss=0.393137

      epoch  94/100: train_loss=0.394876

      epoch  95/100: train_loss=0.394788, val_loss=0.820051, IC=+0.0087

      epoch  96/100: train_loss=0.393102

      epoch  97/100: train_loss=0.394583

      epoch  98/100: train_loss=0.392493

      epoch  99/100: train_loss=0.392859

      epoch 100/100: train_loss=0.392067, val_loss=0.820266, IC=+0.0088

      best_ep=55, IC=+0.0118 (563.9s, 20 checkpoints)

  patchtst: best_epoch=45, IC=+0.0149 (1311.0s)

  Best: patchtst @ epoch 45 (IC=+0.0149)
  Saved to ~/ml4t/public-s6-sp500_options/case_studies/sp500_options/run_log/training/472344b774ad/diagnostics

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("PatchTST execution returned a partial checkpoint")
catalog

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ 1f858cde3 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ 8c3       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ b9e39e1e8 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ 85a       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ 876420f9d │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ c84       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ a2e8376e7 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ f64       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ 21aaacf53 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ 874       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ 0315d75ad │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ e43       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ 75161112e │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ 34a       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ 3971dc695 │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ a58       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ 072e2e5db │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ 412       │
│ deep_lear ┆ ret_to_ex ┆ patchtst  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 472344b77 ┆ e0e0b623d │
│ ning      ┆ piry      ┆           ┆           ┆   ┆           ┆          ┆ 4ad       ┆ 434       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

The official sequence population is complete and ready for model analysis and backtesting. This
notebook does not compare configurations or choose a checkpoint.