# TabM on the funding panel, and what a network adds that a tree does not

[`06_linear`](06_linear.ipynb) and [`07_gbm`](07_gbm.ipynb) read the same design matrix this
notebook does: one row per perpetual per settlement, one column per feature, with nothing in
the table saying the rows are ordered in time. They differ in what they can represent. A
penalized linear model gives each feature one coefficient and can spread weight across a group
of near-duplicate columns. A tree ensemble can express an interaction - a condition on one
feature evaluated inside a region defined by others - but it reaches one by choosing a single
column at each split, and several columns here carry almost the same information, so which one
is chosen is close to arbitrary.

A neural network on the same table answers the same question a third way. Its first layer is a
weighted sum of every feature, so like the linear model it never has to choose among correlated
columns; the nonlinearity after it lets those sums combine into interactions the linear model
cannot write down. That is the reason to fit one here, rather than a general preference for
neural networks: the two properties that pulled against each other in the previous two
notebooks are not obviously in conflict in this architecture.

**TabM is an ensemble, and the ensemble is the point.** Averaging several independently
initialized networks is a standard way to make a neural fit on a table less erratic, and the
cost is normally that you train several networks. TabM trains most of one. A backbone of two
layers is shared by every member; each member owns only a vector carrying one number per hidden
unit, which scales the backbone's output element by element, and its own final linear layer.
The members' predictions are averaged. So `n_members: 4` at `hidden_dim: 64` costs four small
vectors and four output layers on top of one backbone, not four networks - which is why the
member count can be raised much further than the width can.

**This notebook fits three of the four declared labels, and two of them are not returns.**
`fwd_ret_8h` is a regression target. `fwd_dir_8h` is its sign, a binary classification, and
`fwd_dir_8h_3c` adds a flat class for moves too small to trade - three-way, and deliberately
unbalanced, because most settlements are small. A classification request therefore resolves
more than a regression one: the class weights that correct the imbalance are fitted per fold,
because the balance of a fold is a property of its own training window and not of the panel.
It also resolves a *continuous* evaluation target, so a classifier's ranking can be scored
against the return it was trying to sign rather than against its own discrete labels.

**A neural fit has a meaningful state at every epoch**, in the way a boosted model has one at
every iteration and a linear fit does not. An epoch is one pass over the training rows. These
configurations train for 200 and save the weights every 25, so each produces eight scoreable
models rather than one and each is registered separately. What counts downstream is
configurations times checkpoints, not configurations.

**Learning objectives.** By the end of this notebook you will be able to:

- Say what a weight-sharing ensemble holds in common between its members and what it keeps
  separate, and why that makes *k* members cost far less than *k* networks.
- Tell apart a regression, a binary and a multiclass request, and say what each additionally
  resolves before anything is fitted.
- Explain why class weights are fitted per fold rather than once for the panel, and what would
  go wrong if a single weighting were carried across folds.
- Read the epoch schedule out of a declared configuration and say how many scoreable models a
  run will publish for it.
- Say why a catalog identity has to bind the device policy as well as the model and seed.

**Book reference:** Chapter 18, deep learning for tabular data.

**Prerequisites:** [`03_financial_features`](03_financial_features.ipynb) and
[`04_model_based_features`](04_model_based_features.ipynb) have written the feature matrices, and
[`05_evaluation`](05_evaluation.ipynb) has established the walk-forward folds. The canonical run
uses CUDA; the reduced run in CI does not.

**What it writes:** one training run per configuration and one complete validation prediction set
per checkpoint, grouped under a named population that [`13_backtest`](13_backtest.ipynb) reads
and selects from on validation backtest Sharpe. **Nothing here ranks anything**, and no number
printed below decides which model the case study goes on to use.

In [1]:
import os

import polars as pl

from case_studies.crypto_perps_funding.research_workflow import (
    ALL_LABELS,
    declared_contracts,
    freeze_official_model_population,
    model_request_catalog,
    open_study,
    plan_model_catalog,
    plan_specs,
    run_model_plan,
)

In [2]:
EXECUTION_TIER = "canonical"
SUPERSEDES_POPULATION: str = ""
# The generation of this notebook's own checkpoint population that this run replaces, if any.
# Distinct from SUPERSEDES_POPULATION above, which is the case-wide official model population:
# the two are separate declarations and a refit can move either without moving the other.
SUPERSEDES_MODEL_POPULATION: str = ""
WORKSPACE = os.environ.get("ML4T_OUTPUT_DIR", "")
LABELS = ALL_LABELS
PREVIEW_REDUCTIONS = {}
OVERRIDES = {"class_weight": "balanced", "device": "cuda"}

## 1. Resolve targets, imbalance policy, and checkpoints

Nothing is fitted below. The catalog resolves each declared configuration against each label into
a request with an identity, and the table that follows prints what those requests will actually
do. Three fields on it repay attention.

`task` is where the three labels stop being interchangeable. A regression request minimizes
squared error against `fwd_ret_8h`; a binary request fits the sign; the three-class request fits
a sign with a flat band in the middle. They are different objectives on the same features, and a
comparison across them is a comparison of what each was asked to do, not of which is better.

`class_weights` is empty for the regression request and populated for the other two, and it is
resolved **per fold**. The proportion of flat settlements is a property of a particular training
window, not of the panel: crypto funding regimes are long-lived, and a fold covering a quiet
stretch has a different balance from one covering a volatile stretch. A single weighting computed
once over the whole panel would carry each fold a correction fitted partly on the others.

`checkpoint_schedule` is what turns each configuration into several scoreable models. Read the
epoch count and interval off this table rather than from the configuration file, because it is
the frozen specification that the run will follow.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
official_population = (
    freeze_official_model_population(study, supersedes=SUPERSEDES_POPULATION or None)
    if EXECUTION_TIER == "canonical"
    else None
)
requests = model_request_catalog("tabular_dl", labels=LABELS, config_prefix="tabm")
requests

shape: (12, 3)
┌────────────┬───────────────┬─────────────┐
│ family     ┆ label         ┆ config_name │
│ ---        ┆ ---           ┆ ---         │
│ str        ┆ str           ┆ str         │
╞════════════╪═══════════════╪═════════════╡
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_s      │
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_m      │
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_l      │
│ tabular_dl ┆ fwd_ret_24h   ┆ tabm_s      │
│ tabular_dl ┆ fwd_ret_24h   ┆ tabm_m      │
│ …          ┆ …             ┆ …           │
│ tabular_dl ┆ fwd_dir_8h    ┆ tabm_m      │
│ tabular_dl ┆ fwd_dir_8h    ┆ tabm_l      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_s      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_m      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_l      │
└────────────┴───────────────┴─────────────┘

In [4]:
plan = plan_model_catalog(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides=OVERRIDES,
    preview_reductions=PREVIEW_REDUCTIONS,
)
# Task semantics and imbalance treatment are resolved inputs, so read them from the frozen
# specification rather than restating the configuration file here.
resolved_tasks = [spec["computation"]["task"] for spec in plan_specs(plan)]
resolved_contracts = declared_contracts(plan).with_columns(
    pl.Series("metrics", [task.get("metrics", []) for task in resolved_tasks]),
    pl.Series("imbalance", [task.get("imbalance") for task in resolved_tasks]),
)
resolved_contracts.select(
    "label",
    "config_name",
    "task",
    "continuous_eval_label",
    "imbalance",
    "metrics",
    "checkpoint_value",
    "eligible_rows",
    "training_hash",
)

shape: (96, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ task      ┆ continuou ┆ … ┆ metrics   ┆ checkpoin ┆ eligible_ ┆ training │
│ ---       ┆ me        ┆ ---       ┆ s_eval_la ┆   ┆ ---       ┆ t_value   ┆ rows      ┆ _hash    │
│ str       ┆ ---       ┆ str       ┆ bel       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆ ---       ┆   ┆           ┆ i64       ┆ i64       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 25        ┆ 35280     ┆ 4ba96918 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ 4c07     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 50        ┆ 35280     ┆ 4ba96918 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ 4c07     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 75        ┆ 35280     ┆ 4ba96918 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ 4c07     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 100       ┆ 35280     ┆ 4ba96918 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ 4c07     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 125       ┆ 35280     ┆ 4ba96918 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ 4c07     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 100       ┆ 35280     ┆ 3796e24b │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5032     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 125       ┆ 35280     ┆ 3796e24b │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5032     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 150       ┆ 35280     ┆ 3796e24b │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5032     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 175       ┆ 35280     ┆ 3796e24b │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5032     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 200       ┆ 35280     ┆ 3796e24b │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5032     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

The complete case-wide population is recorded before the first fit, so a member that later
fails to train cannot quietly disappear from the population it was declared in. This notebook
produces one slice of it, and that slice must lie inside the declaration.

In [5]:
if official_population is not None:
    outside = set(plan.expected_prediction_hashes) - set(official_population.members)
    if outside:
        raise RuntimeError(
            f"{len(outside)} declared checkpoints lie outside the official model population"
        )

## 2. Execute and validate the fitted-state population

Each configuration is fitted on each fold; the weights are persisted at every checkpoint epoch
with a digest, and one complete validation prediction set is registered per checkpoint. A cached
fitted state is reused only when its digest matches, so a resumed run cannot silently continue
from weights that a code change has invalidated.

The completeness check is the substantive one. A prediction set is complete when it covers every
validation key its fold declares. A set covering most of them is not a slightly worse result - it
is a different sample, and putting it beside a complete one in the backtest would compare two
models measured on different data. The run raises rather than publishing an incomplete
population, which is the behaviour to want: a loud failure here costs a re-run, and a quiet one
costs a wrong comparison that nothing downstream can detect.

In [6]:
execution = run_model_plan(
    plan,
    supersedes=SUPERSEDES_MODEL_POPULATION or None,
    population_name="crypto-tabm-validation-predictions-v1"
    if EXECUTION_TIER == "canonical"
    else None,
)
catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if (
    catalog.height != len(plan.expected_prediction_hashes)
    or catalog.filter(~pl.col("complete")).height
):
    raise RuntimeError("TabM fitted-state or prediction population is incomplete")
catalog.select(
    "label",
    "config_name",
    "task",
    "checkpoint_kind",
    "checkpoint_value",
    "training_hash",
    "prediction_hash",
    "complete",
)

Preparing and releasing folds...

  Fold 0: train=23,681  val=16,738

      epoch  25/200: loss=0.001743, IC=+0.0084

      epoch  50/200: loss=0.001639, IC=+0.0242

      epoch  75/200: loss=0.001551, IC=+0.0304

      epoch 100/200: loss=0.001520, IC=+0.0275

      epoch 125/200: loss=0.001478, IC=+0.0236

      epoch 150/200: loss=0.001459, IC=+0.0244

      epoch 175/200: loss=0.001476, IC=+0.0241

      epoch 200/200: loss=0.001461, IC=+0.0241

    Fold 0: best_ep=75, IC=+0.0304 (11.1s)

      epoch  25/200: loss=0.001740, IC=+0.0156

      epoch  50/200: loss=0.001577, IC=-0.0047

      epoch  75/200: loss=0.001473, IC=-0.0046

      epoch 100/200: loss=0.001397, IC=-0.0079

      epoch 125/200: loss=0.001347, IC=-0.0089

      epoch 150/200: loss=0.001313, IC=-0.0091

      epoch 175/200: loss=0.001308, IC=-0.0100

      epoch 200/200: loss=0.001293, IC=-0.0100

    Fold 0: best_ep=25, IC=+0.0156 (11.0s)

      epoch  25/200: loss=0.001615, IC=+0.0205

      epoch  50/200: loss=0.001373, IC=+0.0129

      epoch  75/200: loss=0.001183, IC=-0.0103

      epoch 100/200: loss=0.001069, IC=+0.0028

      epoch 125/200: loss=0.000993, IC=-0.0002

      epoch 150/200: loss=0.000946, IC=+0.0035

      epoch 175/200: loss=0.000935, IC=+0.0003

      epoch 200/200: loss=0.000937, IC=-0.0006

    Fold 0: best_ep=25, IC=+0.0205 (16.1s)

  Fold 1: train=31,402  val=18,542

      epoch  25/200: loss=0.001561, IC=+0.0005

      epoch  50/200: loss=0.001535, IC=+0.0046

      epoch  75/200: loss=0.001462, IC=-0.0033

      epoch 100/200: loss=0.001441, IC=-0.0044

      epoch 125/200: loss=0.001402, IC=-0.0078

      epoch 150/200: loss=0.001382, IC=-0.0068

      epoch 175/200: loss=0.001378, IC=-0.0071

      epoch 200/200: loss=0.001386, IC=-0.0085

    Fold 1: best_ep=50, IC=+0.0046 (14.1s)

      epoch  25/200: loss=0.001470, IC=+0.0069

      epoch  50/200: loss=0.001336, IC=+0.0072

      epoch  75/200: loss=0.001254, IC=+0.0045

      epoch 100/200: loss=0.001196, IC=+0.0063

      epoch 125/200: loss=0.001156, IC=+0.0014

      epoch 150/200: loss=0.001133, IC=+0.0031

      epoch 175/200: loss=0.001125, IC=+0.0018

      epoch 200/200: loss=0.001121, IC=+0.0021

    Fold 1: best_ep=50, IC=+0.0072 (19.7s)

      epoch  25/200: loss=0.001397, IC=+0.0035

      epoch  50/200: loss=0.001183, IC=+0.0045

      epoch  75/200: loss=0.001069, IC=+0.0017

      epoch 100/200: loss=0.000967, IC=-0.0019

      epoch 125/200: loss=0.000927, IC=-0.0006

      epoch 150/200: loss=0.000892, IC=+0.0024

      epoch 175/200: loss=0.000884, IC=+0.0003

      epoch 200/200: loss=0.000878, IC=+0.0000

    Fold 1: best_ep=50, IC=+0.0045 (23.8s)

    → best_epoch=50, IC=+0.0144 (25.3s)

    → best_epoch=25, IC=+0.0112 (30.8s)

    → best_epoch=25, IC=+0.0120 (40.0s)

  Best: 4ba969184c07 @ epoch 50 (IC=+0.0144)

Preparing and releasing folds...
  Fold 0: train=23,653  val=16,722

      epoch  25/200: loss=0.006740, IC=+0.0251

      epoch  50/200: loss=0.006172, IC=+0.0448

      epoch  75/200: loss=0.005727, IC=+0.0513

      epoch 100/200: loss=0.005447, IC=+0.0383

      epoch 125/200: loss=0.005319, IC=+0.0327

      epoch 150/200: loss=0.005101, IC=+0.0313

      epoch 175/200: loss=0.005125, IC=+0.0294

      epoch 200/200: loss=0.005071, IC=+0.0281

    Fold 0: best_ep=75, IC=+0.0513 (10.6s)

      epoch  25/200: loss=0.006589, IC=+0.0359

      epoch  50/200: loss=0.005388, IC=+0.0303

      epoch  75/200: loss=0.004698, IC=+0.0173

      epoch 100/200: loss=0.004273, IC=+0.0218

      epoch 125/200: loss=0.004106, IC=+0.0216

      epoch 150/200: loss=0.004061, IC=+0.0223

      epoch 175/200: loss=0.003995, IC=+0.0194

      epoch 200/200: loss=0.004046, IC=+0.0189

    Fold 0: best_ep=25, IC=+0.0359 (11.4s)

      epoch  25/200: loss=0.006149, IC=+0.0567

      epoch  50/200: loss=0.004518, IC=+0.0547

      epoch  75/200: loss=0.003774, IC=+0.0335

      epoch 100/200: loss=0.003452, IC=+0.0279

      epoch 125/200: loss=0.003200, IC=+0.0272

      epoch 150/200: loss=0.003019, IC=+0.0212

      epoch 175/200: loss=0.002960, IC=+0.0219

      epoch 200/200: loss=0.002982, IC=+0.0226

    Fold 0: best_ep=25, IC=+0.0567 (13.1s)

  Fold 1: train=31,350  val=18,504

      epoch  25/200: loss=0.005703, IC=-0.0115

      epoch  50/200: loss=0.005426, IC=-0.0041

      epoch  75/200: loss=0.004873, IC=-0.0108

      epoch 100/200: loss=0.004562, IC=-0.0095

      epoch 125/200: loss=0.004442, IC=-0.0064

      epoch 150/200: loss=0.004312, IC=-0.0082

      epoch 175/200: loss=0.004264, IC=-0.0052

      epoch 200/200: loss=0.004321, IC=-0.0065

    Fold 1: best_ep=50, IC=-0.0041 (11.4s)

      epoch  25/200: loss=0.005377, IC=+0.0007

      epoch  50/200: loss=0.004615, IC=-0.0045

      epoch  75/200: loss=0.004133, IC=+0.0092

      epoch 100/200: loss=0.003811, IC=+0.0090

      epoch 125/200: loss=0.003704, IC=+0.0114

      epoch 150/200: loss=0.003588, IC=+0.0071

      epoch 175/200: loss=0.003562, IC=+0.0080

      epoch 200/200: loss=0.003518, IC=+0.0078

    Fold 1: best_ep=125, IC=+0.0114 (12.3s)

      epoch  25/200: loss=0.004964, IC=-0.0193

      epoch  50/200: loss=0.003977, IC=+0.0051

      epoch  75/200: loss=0.003343, IC=+0.0093

      epoch 100/200: loss=0.003056, IC=+0.0148

      epoch 125/200: loss=0.002865, IC=+0.0123

      epoch 150/200: loss=0.002782, IC=+0.0090

      epoch 175/200: loss=0.002721, IC=+0.0057

      epoch 200/200: loss=0.002723, IC=+0.0069

    Fold 1: best_ep=100, IC=+0.0148 (17.4s)

    → best_epoch=50, IC=+0.0204 (22.1s)

    → best_epoch=25, IC=+0.0183 (23.8s)

    → best_epoch=50, IC=+0.0299 (30.6s)

  Best: 5c77e31d4cb9 @ epoch 50 (IC=+0.0299)

Preparing and releasing folds...
  Fold 0: train=23,681  val=16,738

      epoch  25/200: loss=0.686640, IC=+0.0331

      epoch  50/200: loss=0.678078, IC=+0.0379

      epoch  75/200: loss=0.672236, IC=+0.0367

      epoch 100/200: loss=0.666621, IC=+0.0390

      epoch 125/200: loss=0.664917, IC=+0.0351

      epoch 150/200: loss=0.664486, IC=+0.0362

      epoch 175/200: loss=0.661536, IC=+0.0356

      epoch 200/200: loss=0.661473, IC=+0.0345

    Fold 0: best_ep=100, IC=+0.0390 (5.5s)

      epoch  25/200: loss=0.682243, IC=+0.0295

      epoch  50/200: loss=0.667551, IC=+0.0255

      epoch  75/200: loss=0.654744, IC=+0.0179

      epoch 100/200: loss=0.646274, IC=+0.0231

      epoch 125/200: loss=0.638826, IC=+0.0207

      epoch 150/200: loss=0.636832, IC=+0.0198

      epoch 175/200: loss=0.637518, IC=+0.0205

      epoch 200/200: loss=0.635238, IC=+0.0203

    Fold 0: best_ep=25, IC=+0.0295 (7.4s)

      epoch  25/200: loss=0.672825, IC=+0.0371

      epoch  50/200: loss=0.645061, IC=+0.0254

      epoch  75/200: loss=0.620767, IC=+0.0156

      epoch 100/200: loss=0.605365, IC=+0.0163

      epoch 125/200: loss=0.592957, IC=+0.0195

      epoch 150/200: loss=0.584241, IC=+0.0168

      epoch 175/200: loss=0.580177, IC=+0.0153

      epoch 200/200: loss=0.583055, IC=+0.0153

    Fold 0: best_ep=25, IC=+0.0371 (10.7s)

  Fold 1: train=31,402  val=18,542

      epoch  25/200: loss=0.685374, IC=+0.0135

      epoch  50/200: loss=0.677624, IC=+0.0111

      epoch  75/200: loss=0.672166, IC=+0.0099

      epoch 100/200: loss=0.667368, IC=+0.0070

      epoch 125/200: loss=0.664966, IC=+0.0075

      epoch 150/200: loss=0.662718, IC=+0.0055

      epoch 175/200: loss=0.660637, IC=+0.0047

      epoch 200/200: loss=0.661338, IC=+0.0051

    Fold 1: best_ep=25, IC=+0.0135 (9.2s)

      epoch  25/200: loss=0.680459, IC=+0.0110

      epoch  50/200: loss=0.668259, IC=+0.0056

      epoch  75/200: loss=0.659988, IC=+0.0052

      epoch 100/200: loss=0.650390, IC=+0.0030

      epoch 125/200: loss=0.645354, IC=+0.0027

      epoch 150/200: loss=0.641544, IC=+0.0038

      epoch 175/200: loss=0.640399, IC=+0.0025

      epoch 200/200: loss=0.639254, IC=+0.0023

    Fold 1: best_ep=25, IC=+0.0110 (14.3s)

      epoch  25/200: loss=0.672603, IC=+0.0020

      epoch  50/200: loss=0.648712, IC=+0.0016

      epoch  75/200: loss=0.627443, IC=-0.0003

      epoch 100/200: loss=0.612917, IC=+0.0003

      epoch 125/200: loss=0.602729, IC=+0.0022

      epoch 150/200: loss=0.595231, IC=+0.0027

      epoch 175/200: loss=0.592339, IC=+0.0022

      epoch 200/200: loss=0.590453, IC=+0.0024

    Fold 1: best_ep=150, IC=+0.0027 (24.7s)

    → best_epoch=50, IC=+0.0245 (14.7s)

    → best_epoch=25, IC=+0.0203 (21.8s)

    → best_epoch=25, IC=+0.0196 (35.4s)

  Best: cc088f93eff8 @ epoch 50 (IC=+0.0245)

Preparing and releasing folds...
  Fold 0: train=23,681  val=16,738

      epoch  25/200: loss=1.052944, IC=+0.0472

      epoch  50/200: loss=1.045395, IC=+0.0416

      epoch  75/200: loss=1.039587, IC=+0.0422

      epoch 100/200: loss=1.036810, IC=+0.0425

      epoch 125/200: loss=1.033324, IC=+0.0396

      epoch 150/200: loss=1.031295, IC=+0.0405

      epoch 175/200: loss=1.030179, IC=+0.0410

      epoch 200/200: loss=1.031400, IC=+0.0410

    Fold 0: best_ep=25, IC=+0.0472 (10.5s)

      epoch  25/200: loss=1.048434, IC=+0.0480

      epoch  50/200: loss=1.036934, IC=+0.0457

      epoch  75/200: loss=1.023500, IC=+0.0322

      epoch 100/200: loss=1.014238, IC=+0.0346

      epoch 125/200: loss=1.009712, IC=+0.0308

      epoch 150/200: loss=1.006826, IC=+0.0307

      epoch 175/200: loss=1.005004, IC=+0.0305

      epoch 200/200: loss=1.003822, IC=+0.0307

    Fold 0: best_ep=25, IC=+0.0480 (13.3s)

      epoch  25/200: loss=1.043671, IC=+0.0421

      epoch  50/200: loss=1.021270, IC=+0.0353

      epoch  75/200: loss=0.997524, IC=+0.0228

      epoch 100/200: loss=0.980080, IC=+0.0205

      epoch 125/200: loss=0.969116, IC=+0.0182

      epoch 150/200: loss=0.962796, IC=+0.0159

      epoch 175/200: loss=0.961171, IC=+0.0167

      epoch 200/200: loss=0.960565, IC=+0.0165

    Fold 0: best_ep=25, IC=+0.0421 (16.9s)

  Fold 1: train=31,402  val=18,542

      epoch  25/200: loss=1.059344, IC=+0.0141

      epoch  50/200: loss=1.051505, IC=+0.0130

      epoch  75/200: loss=1.046410, IC=+0.0075

      epoch 100/200: loss=1.044019, IC=+0.0089

      epoch 125/200: loss=1.040886, IC=+0.0100

      epoch 150/200: loss=1.039948, IC=+0.0096

      epoch 175/200: loss=1.038910, IC=+0.0093

      epoch 200/200: loss=1.038643, IC=+0.0092

    Fold 1: best_ep=25, IC=+0.0141 (15.2s)

      epoch  25/200: loss=1.054891, IC=+0.0140

      epoch  50/200: loss=1.043080, IC=+0.0179

      epoch  75/200: loss=1.033789, IC=+0.0161

      epoch 100/200: loss=1.027534, IC=+0.0178

      epoch 125/200: loss=1.023585, IC=+0.0176

      epoch 150/200: loss=1.022201, IC=+0.0143

      epoch 175/200: loss=1.019894, IC=+0.0154

      epoch 200/200: loss=1.019216, IC=+0.0138

    Fold 1: best_ep=50, IC=+0.0179 (20.2s)

      epoch  25/200: loss=1.048449, IC=+0.0217

      epoch  50/200: loss=1.027095, IC=+0.0159

      epoch  75/200: loss=1.010144, IC=+0.0112

      epoch 100/200: loss=0.996006, IC=+0.0126

      epoch 125/200: loss=0.985356, IC=+0.0135

      epoch 150/200: loss=0.980896, IC=+0.0120

      epoch 175/200: loss=0.978015, IC=+0.0106

      epoch 200/200: loss=0.974779, IC=+0.0105

    Fold 1: best_ep=25, IC=+0.0217 (26.2s)

    → best_epoch=25, IC=+0.0307 (25.7s)

    → best_epoch=50, IC=+0.0318 (33.6s)

    → best_epoch=25, IC=+0.0319 (43.2s)

  Best: 3796e24b5032 @ epoch 25 (IC=+0.0319)

shape: (96, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬──────────┐
│ label      ┆ config_nam ┆ task       ┆ checkpoint ┆ checkpoin ┆ training_ ┆ predictio ┆ complete │
│ ---        ┆ e          ┆ ---        ┆ _kind      ┆ t_value   ┆ hash      ┆ n_hash    ┆ ---      │
│ str        ┆ ---        ┆ str        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ bool     │
│            ┆ str        ┆            ┆ str        ┆ i64       ┆ str       ┆ str       ┆          │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 25        ┆ 31b3c81b7 ┆ a5f54070d ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ f40       ┆ 5a3       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 50        ┆ 31b3c81b7 ┆ 9f2494fde ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ f40       ┆ 198       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 75        ┆ 31b3c81b7 ┆ ef2b40ed8 ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ f40       ┆ 3c3       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 100       ┆ 31b3c81b7 ┆ 8956ddf17 ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ f40       ┆ de4       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 125       ┆ 31b3c81b7 ┆ 2849de88f ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ f40       ┆ 86a       ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 100       ┆ 4ba969184 ┆ 1e4b587ae ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ c07       ┆ 3f7       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 125       ┆ 4ba969184 ┆ 3700b2926 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ c07       ┆ 606       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 150       ┆ 4ba969184 ┆ 90a47d7db ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ c07       ┆ fd6       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 175       ┆ 4ba969184 ┆ e1d9bec74 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ c07       ┆ cfc       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 200       ┆ 4ba969184 ┆ bf002edb9 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ c07       ┆ 3d3       ┆          │
└────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴──────────┘

## Key takeaways and limitations

- **The ensemble is nearly free, and that is the design.** Four members share one two-layer
  backbone and own only a per-unit scaling vector and a final linear layer each. The averaging
  that steadies a neural fit on a table costs four small tensors here rather than four networks,
  which is why the member count is the cheap dial and the hidden width is not.
- **Task semantics and imbalance treatment are resolved inputs, not notebook conventions.** What
  objective is minimized, and how a fold's class imbalance is corrected, are read back out of the
  frozen specification. If they were decided in notebook code, two runs of the same declared
  configuration could differ without their identities differing.
- **Class weights belong to a fold, not to the panel.** Fitting them once over the whole history
  would carry every fold a correction estimated partly on windows it must not see.
- **Configurations times checkpoints is the count that matters.** Eight scoreable models per
  configuration, each registered separately. Reporting the best of them as a single model's score
  would be reporting a maximum over eight draws, and the selection that handles this correctly
  happens in [`13_backtest`](13_backtest.ipynb), not here.
- **The identity binds the device policy, not only the model and seed.** GPU kernels reorder
  floating-point reductions, so the same weights and the same data can produce slightly different
  numbers on a different device. Binding the device policy into the identity means a result is
  never compared against one produced under a different arithmetic.
- **Two folds is the binding constraint, not the architecture.** As with every model family in
  this case study, the usable perpetual funding history is short, and no amount of capacity
  compensates for that.