# TabM on the funding panel, and what a network adds that a tree does not

[`06_linear`](06_linear.ipynb) and [`07_gbm`](07_gbm.ipynb) read the same design matrix this
notebook does: one row per perpetual per settlement, one column per feature, with nothing in
the table saying the rows are ordered in time. They differ in what they can represent. A
penalized linear model gives each feature one coefficient and can spread weight across a group
of near-duplicate columns. A tree ensemble can express an interaction - a condition on one
feature evaluated inside a region defined by others - but it reaches one by choosing a single
column at each split, and several columns here carry almost the same information, so which one
is chosen is close to arbitrary.

A neural network on the same table answers the same question a third way. Its first layer is a
weighted sum of every feature, so like the linear model it never has to choose among correlated
columns; the nonlinearity after it lets those sums combine into interactions the linear model
cannot write down. That is the reason to fit one here, rather than a general preference for
neural networks: the two properties that pulled against each other in the previous two
notebooks are not obviously in conflict in this architecture.

**TabM is an ensemble, and the ensemble is the point.** Averaging several independently
initialized networks is a standard way to make a neural fit on a table less erratic, and the
cost is normally that you train several networks. TabM trains most of one. A backbone of two
layers is shared by every member; each member owns only a vector carrying one number per hidden
unit, which scales the backbone's output element by element, and its own final linear layer.
The members' predictions are averaged. So `n_members: 4` at `hidden_dim: 64` costs four small
vectors and four output layers on top of one backbone, not four networks - which is why the
member count can be raised much further than the width can.

**This notebook fits three of the four declared labels, and two of them are not returns.**
`fwd_ret_8h` is a regression target. `fwd_dir_8h` is its sign, a binary classification, and
`fwd_dir_8h_3c` adds a flat class for moves too small to trade - three-way, and deliberately
unbalanced, because most settlements are small. A classification request therefore resolves
more than a regression one: the class weights that correct the imbalance are fitted per fold,
because the balance of a fold is a property of its own training window and not of the panel.
It also resolves a *continuous* evaluation target, so a classifier's ranking can be scored
against the return it was trying to sign rather than against its own discrete labels.

**A neural fit has a meaningful state at every epoch**, in the way a boosted model has one at
every iteration and a linear fit does not. An epoch is one pass over the training rows. These
configurations train for 200 and save the weights every 25, so each produces eight scoreable
models rather than one and each is registered separately. What counts downstream is
configurations times checkpoints, not configurations.

**Learning objectives.** By the end of this notebook you will be able to:

- Say what a weight-sharing ensemble holds in common between its members and what it keeps
  separate, and why that makes *k* members cost far less than *k* networks.
- Tell apart a regression, a binary and a multiclass request, and say what each additionally
  resolves before anything is fitted.
- Explain why class weights are fitted per fold rather than once for the panel, and what would
  go wrong if a single weighting were carried across folds.
- Read the epoch schedule out of a declared configuration and say how many scoreable models a
  run will publish for it.
- Say why a catalog identity has to bind the device policy as well as the model and seed.

**Book reference:** Chapter 18, deep learning for tabular data.

**Prerequisites:** [`03_financial_features`](03_financial_features.ipynb) and
[`04_model_based_features`](04_model_based_features.ipynb) have written the feature matrices, and
[`05_evaluation`](05_evaluation.ipynb) has established the walk-forward folds. The canonical run
uses CUDA; the reduced run in CI does not.

**What it writes:** one training run per configuration and one complete validation prediction set
per checkpoint, grouped under a named population that [`13_backtest`](13_backtest.ipynb) reads
and selects from on validation backtest Sharpe. **Nothing here ranks anything**, and no number
printed below decides which model the case study goes on to use.

In [1]:
import os

import polars as pl

from case_studies.crypto_perps_funding.research_workflow import (
    ALL_LABELS,
    OFFICIAL_POPULATION,
    declared_contracts,
    freeze_official_model_population,
    model_request_catalog,
    open_study,
    plan_model_catalog,
    plan_specs,
    run_model_plan,
)
from case_studies.research import SUPERSEDES_LIVE, supersedes_for_run

In [2]:
EXECUTION_TIER = "canonical"
# That this run intends to extend the lineage published under the case-wide official model
# population's name. `SUPERSEDES_LIVE` says so without quoting a hash, which would have to equal
# a value the registry moves on every publish; `supersedes_for_run` resolves it against the
# registry and withholds it on a clean clone or under a preview.
SUPERSEDES_POPULATION: str = SUPERSEDES_LIVE
# The same declaration for this notebook's own checkpoint population, which is a separate
# lineage: a refit can move either without moving the other.
SUPERSEDES_MODEL_POPULATION: str = SUPERSEDES_LIVE
WORKSPACE = os.environ.get("ML4T_OUTPUT_DIR", "")
LABELS = ALL_LABELS
PREVIEW_REDUCTIONS = {}
OVERRIDES = {"class_weight": "balanced", "device": "cuda"}

## 1. Resolve targets, imbalance policy, and checkpoints

Nothing is fitted below. The catalog resolves each declared configuration against each label into
a request with an identity, and the table that follows prints what those requests will actually
do. Three fields on it repay attention.

`task` is where the three labels stop being interchangeable. A regression request minimizes
squared error against `fwd_ret_8h`; a binary request fits the sign; the three-class request fits
a sign with a flat band in the middle. They are different objectives on the same features, and a
comparison across them is a comparison of what each was asked to do, not of which is better.

`class_weights` is empty for the regression request and populated for the other two, and it is
resolved **per fold**. The proportion of flat settlements is a property of a particular training
window, not of the panel: crypto funding regimes are long-lived, and a fold covering a quiet
stretch has a different balance from one covering a volatile stretch. A single weighting computed
once over the whole panel would carry each fold a correction fitted partly on the others.

`checkpoint_schedule` is what turns each configuration into several scoreable models. Read the
epoch count and interval off this table rather than from the configuration file, because it is
the frozen specification that the run will follow.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
official_population = (
    freeze_official_model_population(
        study,
        supersedes=supersedes_for_run(
            study,
            population_name=OFFICIAL_POPULATION,
            declared=SUPERSEDES_POPULATION or None,
            execution_tier=EXECUTION_TIER,
        ),
    )
    if EXECUTION_TIER == "canonical"
    else None
)
requests = model_request_catalog("tabular_dl", labels=LABELS, config_prefix="tabm")
requests

shape: (12, 3)
┌────────────┬───────────────┬─────────────┐
│ family     ┆ label         ┆ config_name │
│ ---        ┆ ---           ┆ ---         │
│ str        ┆ str           ┆ str         │
╞════════════╪═══════════════╪═════════════╡
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_s      │
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_m      │
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_l      │
│ tabular_dl ┆ fwd_ret_24h   ┆ tabm_s      │
│ tabular_dl ┆ fwd_ret_24h   ┆ tabm_m      │
│ …          ┆ …             ┆ …           │
│ tabular_dl ┆ fwd_dir_8h    ┆ tabm_m      │
│ tabular_dl ┆ fwd_dir_8h    ┆ tabm_l      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_s      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_m      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_l      │
└────────────┴───────────────┴─────────────┘

In [4]:
plan = plan_model_catalog(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides=OVERRIDES,
    preview_reductions=PREVIEW_REDUCTIONS,
)
# Task semantics and imbalance treatment are resolved inputs, so read them from the frozen
# specification rather than restating the configuration file here.
resolved_tasks = [spec["computation"]["task"] for spec in plan_specs(plan)]
resolved_contracts = declared_contracts(plan).with_columns(
    pl.Series("metrics", [task.get("metrics", []) for task in resolved_tasks]),
    pl.Series("imbalance", [task.get("imbalance") for task in resolved_tasks]),
)
resolved_contracts.select(
    "label",
    "config_name",
    "task",
    "continuous_eval_label",
    "imbalance",
    "metrics",
    "checkpoint_value",
    "eligible_rows",
    "training_hash",
)

shape: (96, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ task      ┆ continuou ┆ … ┆ metrics   ┆ checkpoin ┆ eligible_ ┆ training │
│ ---       ┆ me        ┆ ---       ┆ s_eval_la ┆   ┆ ---       ┆ t_value   ┆ rows      ┆ _hash    │
│ str       ┆ ---       ┆ str       ┆ bel       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆ ---       ┆   ┆           ┆ i64       ┆ i64       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 25        ┆ 35280     ┆ e15ee733 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ b2e3     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 50        ┆ 35280     ┆ e15ee733 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ b2e3     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 75        ┆ 35280     ┆ e15ee733 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ b2e3     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 100       ┆ 35280     ┆ e15ee733 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ b2e3     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 125       ┆ 35280     ┆ e15ee733 │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ b2e3     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 100       ┆ 35280     ┆ 3b6cafb6 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 0fbd     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 125       ┆ 35280     ┆ 3b6cafb6 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 0fbd     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 150       ┆ 35280     ┆ 3b6cafb6 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 0fbd     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 175       ┆ 35280     ┆ 3b6cafb6 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 0fbd     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 200       ┆ 35280     ┆ 3b6cafb6 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 0fbd     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

The complete case-wide population is recorded before the first fit, so a member that later
fails to train cannot quietly disappear from the population it was declared in. This notebook
produces one slice of it, and that slice must lie inside the declaration.

In [5]:
if official_population is not None:
    outside = set(plan.expected_prediction_hashes) - set(official_population.members)
    if outside:
        raise RuntimeError(
            f"{len(outside)} declared checkpoints lie outside the official model population"
        )

## 2. Execute and validate the fitted-state population

Each configuration is fitted on each fold; the weights are persisted at every checkpoint epoch
with a digest, and one complete validation prediction set is registered per checkpoint. A cached
fitted state is reused only when its digest matches, so a resumed run cannot silently continue
from weights that a code change has invalidated.

The completeness check is the substantive one. A prediction set is complete when it covers every
validation key its fold declares. A set covering most of them is not a slightly worse result - it
is a different sample, and putting it beside a complete one in the backtest would compare two
models measured on different data. The run raises rather than publishing an incomplete
population, which is the behaviour to want: a loud failure here costs a re-run, and a quiet one
costs a wrong comparison that nothing downstream can detect.

In [6]:
execution = run_model_plan(
    plan,
    supersedes=supersedes_for_run(
        study,
        population_name="crypto-tabm-validation-predictions-v1",
        declared=SUPERSEDES_MODEL_POPULATION or None,
        execution_tier=EXECUTION_TIER,
    ),
    population_name="crypto-tabm-validation-predictions-v1"
    if EXECUTION_TIER == "canonical"
    else None,
)
catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if (
    catalog.height != len(plan.expected_prediction_hashes)
    or catalog.filter(~pl.col("complete")).height
):
    raise RuntimeError("TabM fitted-state or prediction population is incomplete")
catalog.select(
    "label",
    "config_name",
    "task",
    "checkpoint_kind",
    "checkpoint_value",
    "training_hash",
    "prediction_hash",
    "complete",
)

Preparing and releasing folds...
  Fold 0: train=23,681  val=16,738

      epoch  25/200: loss=0.001901, IC=-0.0005

      epoch  50/200: loss=0.001790, IC=+0.0127

      epoch  75/200: loss=0.001767, IC=+0.0179

      epoch 100/200: loss=0.001760, IC=+0.0188

      epoch 125/200: loss=0.001740, IC=+0.0209

      epoch 150/200: loss=0.001734, IC=+0.0201

      epoch 175/200: loss=0.001733, IC=+0.0202

      epoch 200/200: loss=0.001741, IC=+0.0198

    Fold 0: best_ep=125, IC=+0.0209 (4.5s)

      epoch  25/200: loss=0.001868, IC=+0.0119

      epoch  50/200: loss=0.001775, IC=+0.0114

      epoch  75/200: loss=0.001758, IC=+0.0133

      epoch 100/200: loss=0.001742, IC=+0.0168

      epoch 125/200: loss=0.001731, IC=+0.0199

      epoch 150/200: loss=0.001721, IC=+0.0201

      epoch 175/200: loss=0.001722, IC=+0.0210

      epoch 200/200: loss=0.001727, IC=+0.0213

    Fold 0: best_ep=200, IC=+0.0213 (4.3s)

      epoch  25/200: loss=0.001821, IC=+0.0058

      epoch  50/200: loss=0.001761, IC=+0.0060

      epoch  75/200: loss=0.001751, IC=+0.0138

      epoch 100/200: loss=0.001738, IC=+0.0223

      epoch 125/200: loss=0.001721, IC=+0.0204

      epoch 150/200: loss=0.001713, IC=+0.0212

      epoch 175/200: loss=0.001713, IC=+0.0205

      epoch 200/200: loss=0.001716, IC=+0.0212

    Fold 0: best_ep=100, IC=+0.0223 (12.3s)

  Fold 1: train=31,402  val=18,542

      epoch  25/200: loss=0.001744, IC=-0.0012

      epoch  50/200: loss=0.001631, IC=+0.0008

      epoch  75/200: loss=0.001583, IC=-0.0050

      epoch 100/200: loss=0.001572, IC=-0.0047

      epoch 125/200: loss=0.001572, IC=-0.0094

      epoch 150/200: loss=0.001551, IC=-0.0088

      epoch 175/200: loss=0.001558, IC=-0.0095

      epoch 200/200: loss=0.001561, IC=-0.0097

    Fold 1: best_ep=50, IC=+0.0008 (4.9s)

      epoch  25/200: loss=0.001705, IC=-0.0061

      epoch  50/200: loss=0.001605, IC=-0.0034

      epoch  75/200: loss=0.001565, IC=+0.0014

      epoch 100/200: loss=0.001559, IC=+0.0086

      epoch 125/200: loss=0.001561, IC=+0.0072

      epoch 150/200: loss=0.001546, IC=+0.0080

      epoch 175/200: loss=0.001552, IC=+0.0079

      epoch 200/200: loss=0.001549, IC=+0.0080

    Fold 1: best_ep=100, IC=+0.0086 (10.9s)

      epoch  25/200: loss=0.001644, IC=-0.0004

      epoch  50/200: loss=0.001586, IC=-0.0032

      epoch  75/200: loss=0.001563, IC=-0.0043

      epoch 100/200: loss=0.001559, IC=+0.0005

      epoch 125/200: loss=0.001558, IC=+0.0023

      epoch 150/200: loss=0.001542, IC=+0.0037

      epoch 175/200: loss=0.001546, IC=+0.0040

      epoch 200/200: loss=0.001543, IC=+0.0039

    Fold 1: best_ep=175, IC=+0.0040 (16.8s)

    → best_epoch=100, IC=+0.0071 (9.4s)

    → best_epoch=200, IC=+0.0146 (15.2s)

    → best_epoch=200, IC=+0.0126 (29.1s)

  Best: 480b67b19d0f @ epoch 200 (IC=+0.0146)

Preparing and releasing folds...
  Fold 0: train=23,653  val=16,722

      epoch  25/200: loss=0.007026, IC=-0.0143

      epoch  50/200: loss=0.006860, IC=+0.0101

      epoch  75/200: loss=0.006774, IC=+0.0205

      epoch 100/200: loss=0.006690, IC=+0.0227

      epoch 125/200: loss=0.006597, IC=+0.0203

      epoch 150/200: loss=0.006505, IC=+0.0190

      epoch 175/200: loss=0.006607, IC=+0.0157

      epoch 200/200: loss=0.006526, IC=+0.0156

    Fold 0: best_ep=100, IC=+0.0227 (7.6s)

      epoch  25/200: loss=0.007012, IC=+0.0177

      epoch  50/200: loss=0.006826, IC=+0.0322

      epoch  75/200: loss=0.006705, IC=+0.0346

      epoch 100/200: loss=0.006605, IC=+0.0397

      epoch 125/200: loss=0.006475, IC=+0.0362

      epoch 150/200: loss=0.006420, IC=+0.0414

      epoch 175/200: loss=0.006456, IC=+0.0419

      epoch 200/200: loss=0.006408, IC=+0.0417

    Fold 0: best_ep=175, IC=+0.0419 (4.9s)

      epoch  25/200: loss=0.006937, IC=+0.0060

      epoch  50/200: loss=0.006759, IC=+0.0267

      epoch  75/200: loss=0.006586, IC=+0.0285

      epoch 100/200: loss=0.006398, IC=+0.0343

      epoch 125/200: loss=0.006310, IC=+0.0321

      epoch 150/200: loss=0.006213, IC=+0.0379

      epoch 175/200: loss=0.006227, IC=+0.0382

      epoch 200/200: loss=0.006190, IC=+0.0379

    Fold 0: best_ep=175, IC=+0.0382 (11.7s)

  Fold 1: train=31,350  val=18,504

      epoch  25/200: loss=0.005995, IC=+0.0009

      epoch  50/200: loss=0.005842, IC=+0.0005

      epoch  75/200: loss=0.005776, IC=+0.0026

      epoch 100/200: loss=0.005735, IC=+0.0046

      epoch 125/200: loss=0.005644, IC=+0.0037

      epoch 150/200: loss=0.005619, IC=+0.0013

      epoch 175/200: loss=0.005675, IC=+0.0014

      epoch 200/200: loss=0.005644, IC=+0.0016

    Fold 1: best_ep=100, IC=+0.0046 (6.7s)

      epoch  25/200: loss=0.005887, IC=-0.0023

      epoch  50/200: loss=0.005787, IC=+0.0020

      epoch  75/200: loss=0.005749, IC=-0.0011

      epoch 100/200: loss=0.005697, IC=+0.0021

      epoch 125/200: loss=0.005626, IC=-0.0016

      epoch 150/200: loss=0.005608, IC=-0.0004

      epoch 175/200: loss=0.005637, IC=-0.0029

      epoch 200/200: loss=0.005586, IC=-0.0033

    Fold 1: best_ep=100, IC=+0.0021 (7.7s)

      epoch  25/200: loss=0.005884, IC=-0.0041

      epoch  50/200: loss=0.005791, IC=-0.0005

      epoch  75/200: loss=0.005724, IC=+0.0045

      epoch 100/200: loss=0.005656, IC=+0.0042

      epoch 125/200: loss=0.005579, IC=+0.0030

      epoch 150/200: loss=0.005544, IC=+0.0022

      epoch 175/200: loss=0.005586, IC=+0.0025

      epoch 200/200: loss=0.005542, IC=+0.0025

    Fold 1: best_ep=75, IC=+0.0045 (17.1s)

    → best_epoch=100, IC=+0.0137 (14.4s)

    → best_epoch=100, IC=+0.0209 (12.7s)

    → best_epoch=175, IC=+0.0204 (28.9s)

  Best: 1ad6eb0a400a @ epoch 100 (IC=+0.0209)

Preparing and releasing folds...
  Fold 0: train=23,681  val=16,738

      epoch  25/200: loss=0.686788, IC=+0.0342

      epoch  50/200: loss=0.681001, IC=+0.0364

      epoch  75/200: loss=0.677044, IC=+0.0391

      epoch 100/200: loss=0.674931, IC=+0.0392

      epoch 125/200: loss=0.673086, IC=+0.0420

      epoch 150/200: loss=0.672195, IC=+0.0441

      epoch 175/200: loss=0.671752, IC=+0.0430

      epoch 200/200: loss=0.671628, IC=+0.0429

    Fold 0: best_ep=150, IC=+0.0441 (4.8s)

      epoch  25/200: loss=0.684103, IC=+0.0389

      epoch  50/200: loss=0.675986, IC=+0.0386

      epoch  75/200: loss=0.670381, IC=+0.0430

      epoch 100/200: loss=0.666417, IC=+0.0439

      epoch 125/200: loss=0.664293, IC=+0.0429

      epoch 150/200: loss=0.662878, IC=+0.0441

      epoch 175/200: loss=0.662737, IC=+0.0456

      epoch 200/200: loss=0.662400, IC=+0.0461

    Fold 0: best_ep=200, IC=+0.0461 (4.7s)

      epoch  25/200: loss=0.679677, IC=+0.0441

      epoch  50/200: loss=0.667681, IC=+0.0408

      epoch  75/200: loss=0.659389, IC=+0.0398

      epoch 100/200: loss=0.653559, IC=+0.0369

      epoch 125/200: loss=0.649595, IC=+0.0319

      epoch 150/200: loss=0.647803, IC=+0.0323

      epoch 175/200: loss=0.646593, IC=+0.0331

      epoch 200/200: loss=0.647396, IC=+0.0330

    Fold 0: best_ep=25, IC=+0.0441 (12.2s)

  Fold 1: train=31,402  val=18,542

      epoch  25/200: loss=0.686434, IC=+0.0134

      epoch  50/200: loss=0.681762, IC=+0.0128

      epoch  75/200: loss=0.678660, IC=+0.0080

      epoch 100/200: loss=0.675883, IC=+0.0074

      epoch 125/200: loss=0.674925, IC=+0.0061

      epoch 150/200: loss=0.674051, IC=+0.0055

      epoch 175/200: loss=0.673661, IC=+0.0035

      epoch 200/200: loss=0.673172, IC=+0.0037

    Fold 1: best_ep=25, IC=+0.0134 (12.2s)

      epoch  25/200: loss=0.684707, IC=+0.0215

      epoch  50/200: loss=0.678325, IC=+0.0136

      epoch  75/200: loss=0.673770, IC=+0.0094

      epoch 100/200: loss=0.670874, IC=+0.0076

      epoch 125/200: loss=0.669022, IC=+0.0057

      epoch 150/200: loss=0.667758, IC=+0.0050

      epoch 175/200: loss=0.667572, IC=+0.0055

      epoch 200/200: loss=0.667324, IC=+0.0055

    Fold 1: best_ep=25, IC=+0.0215 (6.7s)

      epoch  25/200: loss=0.681842, IC=+0.0170

      epoch  50/200: loss=0.672018, IC=+0.0103

      epoch  75/200: loss=0.665215, IC=+0.0067

      epoch 100/200: loss=0.661400, IC=+0.0031

      epoch 125/200: loss=0.658034, IC=+0.0043

      epoch 150/200: loss=0.656131, IC=+0.0029

      epoch 175/200: loss=0.655244, IC=+0.0026

      epoch 200/200: loss=0.655364, IC=+0.0028

    Fold 1: best_ep=25, IC=+0.0170 (16.1s)

    → best_epoch=150, IC=+0.0248 (17.1s)

    → best_epoch=25, IC=+0.0302 (11.5s)

    → best_epoch=25, IC=+0.0306 (28.3s)

  Best: cf8e1d374c66 @ epoch 25 (IC=+0.0306)

Preparing and releasing folds...
  Fold 0: train=23,681  val=16,738

      epoch  25/200: loss=1.053297, IC=+0.0520

      epoch  50/200: loss=1.047611, IC=+0.0515

      epoch  75/200: loss=1.043097, IC=+0.0511

      epoch 100/200: loss=1.039386, IC=+0.0468

      epoch 125/200: loss=1.036688, IC=+0.0433

      epoch 150/200: loss=1.036155, IC=+0.0435

      epoch 175/200: loss=1.035635, IC=+0.0440

      epoch 200/200: loss=1.035182, IC=+0.0436

    Fold 0: best_ep=25, IC=+0.0520 (5.9s)

      epoch  25/200: loss=1.050396, IC=+0.0514

      epoch  50/200: loss=1.041446, IC=+0.0468

      epoch  75/200: loss=1.033756, IC=+0.0482

      epoch 100/200: loss=1.029033, IC=+0.0446

      epoch 125/200: loss=1.026139, IC=+0.0426

      epoch 150/200: loss=1.024575, IC=+0.0405

      epoch 175/200: loss=1.023972, IC=+0.0384

      epoch 200/200: loss=1.023680, IC=+0.0386

    Fold 0: best_ep=25, IC=+0.0514 (5.7s)

      epoch  25/200: loss=1.044764, IC=+0.0414

      epoch  50/200: loss=1.029877, IC=+0.0395

      epoch  75/200: loss=1.018878, IC=+0.0383

      epoch 100/200: loss=1.010935, IC=+0.0365

      epoch 125/200: loss=1.007169, IC=+0.0350

      epoch 150/200: loss=1.004461, IC=+0.0354

      epoch 175/200: loss=1.003579, IC=+0.0347

      epoch 200/200: loss=1.003405, IC=+0.0343

    Fold 0: best_ep=25, IC=+0.0414 (12.6s)

  Fold 1: train=31,402  val=18,542

      epoch  25/200: loss=1.059495, IC=+0.0043

      epoch  50/200: loss=1.054876, IC=+0.0118

      epoch  75/200: loss=1.051200, IC=+0.0109

      epoch 100/200: loss=1.048219, IC=+0.0117

      epoch 125/200: loss=1.047233, IC=+0.0116

      epoch 150/200: loss=1.046235, IC=+0.0100

      epoch 175/200: loss=1.045711, IC=+0.0100

      epoch 200/200: loss=1.045529, IC=+0.0100

    Fold 1: best_ep=50, IC=+0.0118 (15.2s)

      epoch  25/200: loss=1.056571, IC=+0.0123

      epoch  50/200: loss=1.049501, IC=+0.0188

      epoch  75/200: loss=1.044096, IC=+0.0175

      epoch 100/200: loss=1.040258, IC=+0.0179

      epoch 125/200: loss=1.037781, IC=+0.0170

      epoch 150/200: loss=1.036821, IC=+0.0157

      epoch 175/200: loss=1.036887, IC=+0.0165

      epoch 200/200: loss=1.035393, IC=+0.0158

    Fold 1: best_ep=50, IC=+0.0188 (9.7s)

      epoch  25/200: loss=1.051867, IC=+0.0213

      epoch  50/200: loss=1.040656, IC=+0.0168

      epoch  75/200: loss=1.032450, IC=+0.0190

      epoch 100/200: loss=1.026970, IC=+0.0168

      epoch 125/200: loss=1.023672, IC=+0.0164

      epoch 150/200: loss=1.020655, IC=+0.0163

      epoch 175/200: loss=1.021564, IC=+0.0161

      epoch 200/200: loss=1.020118, IC=+0.0165

    Fold 1: best_ep=25, IC=+0.0213 (20.3s)

    → best_epoch=50, IC=+0.0316 (21.1s)

    → best_epoch=75, IC=+0.0328 (15.5s)

    → best_epoch=25, IC=+0.0313 (32.9s)

  Best: cd943aa613be @ epoch 75 (IC=+0.0328)

shape: (96, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬──────────┐
│ label      ┆ config_nam ┆ task       ┆ checkpoint ┆ checkpoin ┆ training_ ┆ predictio ┆ complete │
│ ---        ┆ e          ┆ ---        ┆ _kind      ┆ t_value   ┆ hash      ┆ n_hash    ┆ ---      │
│ str        ┆ ---        ┆ str        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ bool     │
│            ┆ str        ┆            ┆ str        ┆ i64       ┆ str       ┆ str       ┆          │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 25        ┆ cf8e1d374 ┆ a72bb59da ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ c66       ┆ 07e       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 50        ┆ cf8e1d374 ┆ e09b295d3 ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ c66       ┆ 816       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 75        ┆ cf8e1d374 ┆ 4d864353c ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ c66       ┆ 7dc       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 100       ┆ cf8e1d374 ┆ 199b71b6f ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ c66       ┆ 6eb       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 125       ┆ cf8e1d374 ┆ b65193bda ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ c66       ┆ 646       ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 100       ┆ e15ee733b ┆ 570438b54 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 2e3       ┆ 3a1       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 125       ┆ e15ee733b ┆ 402b0307a ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 2e3       ┆ 5f5       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 150       ┆ e15ee733b ┆ 592bd7886 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 2e3       ┆ 8aa       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 175       ┆ e15ee733b ┆ a976158f6 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 2e3       ┆ c42       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 200       ┆ e15ee733b ┆ 851c607b9 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 2e3       ┆ 67c       ┆          │
└────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴──────────┘

## Key takeaways and limitations

- **The ensemble is nearly free, and that is the design.** Four members share one two-layer
  backbone and own only a per-unit scaling vector and a final linear layer each. The averaging
  that steadies a neural fit on a table costs four small tensors here rather than four networks,
  which is why the member count is the cheap dial and the hidden width is not.
- **Task semantics and imbalance treatment are resolved inputs, not notebook conventions.** What
  objective is minimized, and how a fold's class imbalance is corrected, are read back out of the
  frozen specification. If they were decided in notebook code, two runs of the same declared
  configuration could differ without their identities differing.
- **Class weights belong to a fold, not to the panel.** Fitting them once over the whole history
  would carry every fold a correction estimated partly on windows it must not see.
- **Configurations times checkpoints is the count that matters.** Eight scoreable models per
  configuration, each registered separately. Reporting the best of them as a single model's score
  would be reporting a maximum over eight draws, and the selection that handles this correctly
  happens in [`13_backtest`](13_backtest.ipynb), not here.
- **The identity binds the device policy, not only the model and seed.** GPU kernels reorder
  floating-point reductions, so the same weights and the same data can produce slightly different
  numbers on a different device. Binding the device policy into the identity means a result is
  never compared against one produced under a different arithmetic.
- **Two folds is the binding constraint, not the architecture.** As with every model family in
  this case study, the usable perpetual funding history is short, and no amount of capacity
  compensates for that.