# TabM models for an unbalanced perpetual-futures panel

The shared TabM request resolves regression or classification explicitly. Classification requests
also resolve their continuous return target, task metrics, fold-specific class weights, and every
epoch checkpoint before fitting. The complete checkpoint catalog is the notebook output.

**Learning objectives**

- distinguish regression, binary classification, and multiclass requests;
- inspect the continuous return target and fold-specific imbalance treatment; and
- verify fitted-state and checkpoint lineage after GPU execution.

**Book reference:** Chapter 18, deep learning for tabular data.

**Prerequisites:** finalized crypto labels, features, and purged walk-forward folds; CUDA for the
canonical run.

In [1]:
import os

import polars as pl

from case_studies.crypto_perps_funding.research_workflow import (
    ALL_LABELS,
    declared_contracts,
    freeze_official_model_population,
    model_request_catalog,
    open_study,
    plan_model_catalog,
    plan_specs,
    run_model_plan,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE = os.environ.get("ML4T_OUTPUT_DIR", "")
LABELS = ALL_LABELS
PREVIEW_REDUCTIONS = {}
OVERRIDES = {"class_weight": "balanced", "device": "cuda"}

## Resolve targets, imbalance policy, and checkpoints

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
official_population = (
    freeze_official_model_population(study) if EXECUTION_TIER == "canonical" else None
)
requests = model_request_catalog("tabular_dl", labels=LABELS, config_prefix="tabm")
requests

shape: (12, 3)
┌────────────┬───────────────┬─────────────┐
│ family     ┆ label         ┆ config_name │
│ ---        ┆ ---           ┆ ---         │
│ str        ┆ str           ┆ str         │
╞════════════╪═══════════════╪═════════════╡
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_s      │
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_m      │
│ tabular_dl ┆ fwd_ret_8h    ┆ tabm_l      │
│ tabular_dl ┆ fwd_ret_24h   ┆ tabm_s      │
│ tabular_dl ┆ fwd_ret_24h   ┆ tabm_m      │
│ …          ┆ …             ┆ …           │
│ tabular_dl ┆ fwd_dir_8h    ┆ tabm_m      │
│ tabular_dl ┆ fwd_dir_8h    ┆ tabm_l      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_s      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_m      │
│ tabular_dl ┆ fwd_dir_8h_3c ┆ tabm_l      │
└────────────┴───────────────┴─────────────┘

In [4]:
plan = plan_model_catalog(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides=OVERRIDES,
    preview_reductions=PREVIEW_REDUCTIONS,
)
# Task semantics and imbalance treatment are resolved inputs, so read them from the frozen
# specification rather than restating the configuration file here.
resolved_tasks = [spec.get("computation", spec)["task"] for spec in plan_specs(plan)]
resolved_contracts = declared_contracts(plan).with_columns(
    pl.Series("metrics", [task.get("metrics", []) for task in resolved_tasks]),
    pl.Series("imbalance", [task.get("imbalance") for task in resolved_tasks]),
)
resolved_contracts.select(
    "label",
    "config_name",
    "task",
    "continuous_eval_label",
    "imbalance",
    "metrics",
    "checkpoint_value",
    "eligible_rows",
    "training_hash",
)

shape: (96, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ task      ┆ continuou ┆ … ┆ metrics   ┆ checkpoin ┆ eligible_ ┆ training │
│ ---       ┆ me        ┆ ---       ┆ s_eval_la ┆   ┆ ---       ┆ t_value   ┆ rows      ┆ _hash    │
│ str       ┆ ---       ┆ str       ┆ bel       ┆   ┆ list[str] ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆ ---       ┆   ┆           ┆ i64       ┆ i64       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 25        ┆ 35280     ┆ b3a627bd │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ c0b5     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 50        ┆ 35280     ┆ b3a627bd │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ c0b5     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 75        ┆ 35280     ┆ b3a627bd │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ c0b5     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 100       ┆ 35280     ┆ b3a627bd │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ c0b5     │
│ fwd_ret_8 ┆ tabm_s    ┆ regressio ┆ null      ┆ … ┆ []        ┆ 125       ┆ 35280     ┆ b3a627bd │
│ h         ┆           ┆ n         ┆           ┆   ┆           ┆           ┆           ┆ c0b5     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 100       ┆ 35280     ┆ 3259e504 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5b00     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 125       ┆ 35280     ┆ 3259e504 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5b00     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 150       ┆ 35280     ┆ 3259e504 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5b00     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 175       ┆ 35280     ┆ 3259e504 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5b00     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
│ fwd_dir_8 ┆ tabm_l    ┆ classific ┆ fwd_ret_8 ┆ … ┆ ["ic",    ┆ 200       ┆ 35280     ┆ 3259e504 │
│ h_3c      ┆           ┆ ation     ┆ h         ┆   ┆ "accuracy ┆           ┆           ┆ 5b00     │
│           ┆           ┆           ┆           ┆   ┆ ", "balan ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ced_a…    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

The complete case-wide population is recorded before the first fit, so a member that later
fails to train cannot quietly disappear from the population it was declared in. This notebook
produces one slice of it, and that slice must lie inside the declaration.

In [5]:
if official_population is not None:
    outside = set(plan.expected_prediction_hashes) - set(official_population.members)
    if outside:
        raise RuntimeError(
            f"{len(outside)} declared checkpoints lie outside the official model population"
        )

## Execute and validate the fitted-state population

In [6]:
execution = run_model_plan(
    plan,
    population_name="crypto-tabm-validation-predictions-v1"
    if EXECUTION_TIER == "canonical"
    else None,
)
catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if (
    catalog.height != len(plan.expected_prediction_hashes)
    or catalog.filter(~pl.col("complete")).height
):
    raise RuntimeError("TabM fitted-state or prediction population is incomplete")
catalog.select(
    "label",
    "config_name",
    "task",
    "checkpoint_kind",
    "checkpoint_value",
    "training_hash",
    "prediction_hash",
    "complete",
)

Preparing and releasing folds...
  Fold 0: train=31,402  val=18,542

      epoch  25/200: loss=0.001528, IC=+0.0148

      epoch  50/200: loss=0.001452, IC=+0.0030

      epoch  75/200: loss=0.001396, IC=-0.0029

      epoch 100/200: loss=0.001353, IC=-0.0027

      epoch 125/200: loss=0.001327, IC=-0.0055

      epoch 150/200: loss=0.001310, IC=-0.0056

      epoch 175/200: loss=0.001311, IC=-0.0052

      epoch 200/200: loss=0.001307, IC=-0.0053

    Fold 0: best_ep=25, IC=+0.0148 (7.3s)

      epoch  25/200: loss=0.001499, IC=-0.0140

      epoch  50/200: loss=0.001375, IC=-0.0083

      epoch  75/200: loss=0.001283, IC=-0.0085

      epoch 100/200: loss=0.001242, IC=-0.0002

      epoch 125/200: loss=0.001191, IC=-0.0030

      epoch 150/200: loss=0.001168, IC=-0.0037

      epoch 175/200: loss=0.001177, IC=-0.0029

      epoch 200/200: loss=0.001169, IC=-0.0028

    Fold 0: best_ep=100, IC=-0.0002 (8.3s)

      epoch  25/200: loss=0.001413, IC=-0.0019

      epoch  50/200: loss=0.001207, IC=+0.0061

      epoch  75/200: loss=0.001070, IC=+0.0176

      epoch 100/200: loss=0.000977, IC=+0.0207

      epoch 125/200: loss=0.000935, IC=+0.0167

      epoch 150/200: loss=0.000905, IC=+0.0146

      epoch 175/200: loss=0.000887, IC=+0.0143

      epoch 200/200: loss=0.000884, IC=+0.0139

    Fold 0: best_ep=100, IC=+0.0207 (11.2s)

  Fold 1: train=23,681  val=16,738

      epoch  25/200: loss=0.001775, IC=+0.0059

      epoch  50/200: loss=0.001707, IC=+0.0090

      epoch  75/200: loss=0.001648, IC=+0.0007

      epoch 100/200: loss=0.001591, IC=-0.0026

      epoch 125/200: loss=0.001592, IC=+0.0014

      epoch 150/200: loss=0.001542, IC=-0.0019

      epoch 175/200: loss=0.001545, IC=-0.0028

      epoch 200/200: loss=0.001552, IC=-0.0038

    Fold 1: best_ep=50, IC=+0.0090 (4.8s)

      epoch  25/200: loss=0.001620, IC=+0.0194

      epoch  50/200: loss=0.001459, IC=+0.0126

      epoch  75/200: loss=0.001369, IC=+0.0271

      epoch 100/200: loss=0.001305, IC=+0.0213

      epoch 125/200: loss=0.001265, IC=+0.0243

      epoch 150/200: loss=0.001227, IC=+0.0222

      epoch 175/200: loss=0.001221, IC=+0.0216

      epoch 200/200: loss=0.001228, IC=+0.0210

    Fold 1: best_ep=75, IC=+0.0271 (6.0s)

      epoch  25/200: loss=0.001518, IC=-0.0008

      epoch  50/200: loss=0.001255, IC=-0.0100

      epoch  75/200: loss=0.001103, IC=+0.0150

      epoch 100/200: loss=0.001004, IC=+0.0174

      epoch 125/200: loss=0.000948, IC=+0.0194

      epoch 150/200: loss=0.000910, IC=+0.0201

      epoch 175/200: loss=0.000893, IC=+0.0187

      epoch 200/200: loss=0.000887, IC=+0.0189

    Fold 1: best_ep=150, IC=+0.0201 (8.5s)

    → best_epoch=25, IC=+0.0103 (12.1s)

    → best_epoch=125, IC=+0.0107 (14.4s)

    → best_epoch=100, IC=+0.0190 (19.8s)

  Best: fec4bbb847a9 @ epoch 100 (IC=+0.0190)

Preparing and releasing folds...

  Fold 0: train=31,350  val=18,504

      epoch  25/200: loss=0.005640, IC=-0.0173

      epoch  50/200: loss=0.004997, IC=-0.0144

      epoch  75/200: loss=0.004552, IC=+0.0020

      epoch 100/200: loss=0.004480, IC=+0.0014

      epoch 125/200: loss=0.004314, IC=+0.0026

      epoch 150/200: loss=0.004237, IC=+0.0015

      epoch 175/200: loss=0.004253, IC=+0.0008

      epoch 200/200: loss=0.004190, IC=+0.0011

    Fold 0: best_ep=125, IC=+0.0026 (6.0s)

      epoch  25/200: loss=0.005418, IC=-0.0243

      epoch  50/200: loss=0.004456, IC=-0.0037

      epoch  75/200: loss=0.004082, IC=+0.0033

      epoch 100/200: loss=0.003821, IC=+0.0022

      epoch 125/200: loss=0.003705, IC=+0.0045

      epoch 150/200: loss=0.003614, IC=+0.0074

      epoch 175/200: loss=0.003588, IC=+0.0062

      epoch 200/200: loss=0.003560, IC=+0.0058

    Fold 0: best_ep=150, IC=+0.0074 (7.9s)

      epoch  25/200: loss=0.004923, IC=+0.0047

      epoch  50/200: loss=0.003860, IC=+0.0145

      epoch  75/200: loss=0.003388, IC=+0.0180

      epoch 100/200: loss=0.003071, IC=+0.0127

      epoch 125/200: loss=0.002914, IC=+0.0089

      epoch 150/200: loss=0.002813, IC=+0.0115

      epoch 175/200: loss=0.002751, IC=+0.0096

      epoch 200/200: loss=0.002748, IC=+0.0088

    Fold 0: best_ep=75, IC=+0.0180 (11.1s)

  Fold 1: train=23,653  val=16,722

      epoch  25/200: loss=0.006855, IC=+0.0182

      epoch  50/200: loss=0.006430, IC=+0.0244

      epoch  75/200: loss=0.006037, IC=+0.0276

      epoch 100/200: loss=0.005738, IC=+0.0171

      epoch 125/200: loss=0.005388, IC=+0.0131

      epoch 150/200: loss=0.005510, IC=+0.0136

      epoch 175/200: loss=0.005285, IC=+0.0128

      epoch 200/200: loss=0.005251, IC=+0.0123

    Fold 1: best_ep=75, IC=+0.0276 (4.3s)

      epoch  25/200: loss=0.006353, IC=+0.0237

      epoch  50/200: loss=0.005378, IC=+0.0135

      epoch  75/200: loss=0.004668, IC=+0.0191

      epoch 100/200: loss=0.004236, IC=+0.0158

      epoch 125/200: loss=0.004064, IC=+0.0243

      epoch 150/200: loss=0.003971, IC=+0.0215

      epoch 175/200: loss=0.003957, IC=+0.0187

      epoch 200/200: loss=0.003971, IC=+0.0191

    Fold 1: best_ep=125, IC=+0.0243 (5.7s)

      epoch  25/200: loss=0.005903, IC=+0.0380

      epoch  50/200: loss=0.004533, IC=+0.0155

      epoch  75/200: loss=0.003705, IC=+0.0153

      epoch 100/200: loss=0.003375, IC=+0.0050

      epoch 125/200: loss=0.003155, IC=+0.0026

      epoch 150/200: loss=0.002975, IC=+0.0040

      epoch 175/200: loss=0.002945, IC=+0.0033

      epoch 200/200: loss=0.002920, IC=+0.0035

    Fold 1: best_ep=25, IC=+0.0380 (8.3s)

    → best_epoch=75, IC=+0.0148 (10.4s)

    → best_epoch=150, IC=+0.0144 (13.7s)

    → best_epoch=25, IC=+0.0214 (19.5s)

  Best: aad7cd55546a @ epoch 25 (IC=+0.0214)

Preparing and releasing folds...

  Fold 0: train=31,402  val=18,542

      epoch  25/200: loss=0.686056, IC=+0.0117

      epoch  50/200: loss=0.676964, IC=+0.0054

      epoch  75/200: loss=0.671698, IC=+0.0040

      epoch 100/200: loss=0.666745, IC=+0.0046

      epoch 125/200: loss=0.664674, IC=+0.0052

      epoch 150/200: loss=0.663533, IC=+0.0075

      epoch 175/200: loss=0.663017, IC=+0.0073

      epoch 200/200: loss=0.661370, IC=+0.0072

    Fold 0: best_ep=25, IC=+0.0117 (6.4s)

      epoch  25/200: loss=0.681391, IC=+0.0221

      epoch  50/200: loss=0.668561, IC=+0.0054

      epoch  75/200: loss=0.658307, IC=+0.0100

      epoch 100/200: loss=0.647187, IC=+0.0050

      epoch 125/200: loss=0.643143, IC=+0.0041

      epoch 150/200: loss=0.641778, IC=+0.0019

      epoch 175/200: loss=0.641109, IC=+0.0020

      epoch 200/200: loss=0.640626, IC=+0.0017

    Fold 0: best_ep=25, IC=+0.0221 (8.3s)

      epoch  25/200: loss=0.673718, IC=+0.0126

      epoch  50/200: loss=0.647941, IC=+0.0038

      epoch  75/200: loss=0.628670, IC=+0.0029

      epoch 100/200: loss=0.613858, IC=+0.0056

      epoch 125/200: loss=0.601448, IC=+0.0080

      epoch 150/200: loss=0.597569, IC=+0.0078

      epoch 175/200: loss=0.594276, IC=+0.0084

      epoch 200/200: loss=0.593435, IC=+0.0081

    Fold 0: best_ep=25, IC=+0.0126 (12.0s)

  Fold 1: train=23,681  val=16,738

      epoch  25/200: loss=0.685515, IC=+0.0373

      epoch  50/200: loss=0.675909, IC=+0.0366

      epoch  75/200: loss=0.670051, IC=+0.0407

      epoch 100/200: loss=0.666744, IC=+0.0388

      epoch 125/200: loss=0.662892, IC=+0.0400

      epoch 150/200: loss=0.661911, IC=+0.0396

      epoch 175/200: loss=0.659521, IC=+0.0405

      epoch 200/200: loss=0.660299, IC=+0.0405

    Fold 1: best_ep=75, IC=+0.0407 (4.7s)

      epoch  25/200: loss=0.679344, IC=+0.0288

      epoch  50/200: loss=0.666409, IC=+0.0219

      epoch  75/200: loss=0.653001, IC=+0.0243

      epoch 100/200: loss=0.646512, IC=+0.0169

      epoch 125/200: loss=0.639396, IC=+0.0143

      epoch 150/200: loss=0.636603, IC=+0.0182

      epoch 175/200: loss=0.635027, IC=+0.0175

      epoch 200/200: loss=0.633338, IC=+0.0183

    Fold 1: best_ep=25, IC=+0.0288 (6.4s)

      epoch  25/200: loss=0.672451, IC=+0.0209

      epoch  50/200: loss=0.641681, IC=+0.0195

      epoch  75/200: loss=0.617651, IC=+0.0210

      epoch 100/200: loss=0.601231, IC=+0.0203

      epoch 125/200: loss=0.590486, IC=+0.0236

      epoch 150/200: loss=0.580511, IC=+0.0226

      epoch 175/200: loss=0.573291, IC=+0.0210

      epoch 200/200: loss=0.579145, IC=+0.0213

    Fold 1: best_ep=125, IC=+0.0236 (9.0s)

    → best_epoch=25, IC=+0.0245 (11.1s)

    → best_epoch=25, IC=+0.0254 (14.7s)

    → best_epoch=25, IC=+0.0167 (21.0s)

  Best: 5212a9cfd48c @ epoch 25 (IC=+0.0254)

Preparing and releasing folds...

  Fold 0: train=31,402  val=18,542

      epoch  25/200: loss=1.057751, IC=+0.0138

      epoch  50/200: loss=1.051640, IC=+0.0221

      epoch  75/200: loss=1.046881, IC=+0.0236

      epoch 100/200: loss=1.042389, IC=+0.0234

      epoch 125/200: loss=1.041594, IC=+0.0207

      epoch 150/200: loss=1.040208, IC=+0.0186

      epoch 175/200: loss=1.039299, IC=+0.0192

      epoch 200/200: loss=1.037417, IC=+0.0196

    Fold 0: best_ep=75, IC=+0.0236 (9.3s)

      epoch  25/200: loss=1.054476, IC=+0.0179

      epoch  50/200: loss=1.044080, IC=+0.0207

      epoch  75/200: loss=1.037387, IC=+0.0148

      epoch 100/200: loss=1.028586, IC=+0.0127

      epoch 125/200: loss=1.026104, IC=+0.0093

      epoch 150/200: loss=1.022523, IC=+0.0093

      epoch 175/200: loss=1.020314, IC=+0.0083

      epoch 200/200: loss=1.018877, IC=+0.0077

    Fold 0: best_ep=50, IC=+0.0207 (11.1s)

      epoch  25/200: loss=1.048703, IC=+0.0199

      epoch  50/200: loss=1.026888, IC=+0.0135

      epoch  75/200: loss=1.011141, IC=+0.0089

      epoch 100/200: loss=0.997214, IC=+0.0097

      epoch 125/200: loss=0.985519, IC=+0.0066

      epoch 150/200: loss=0.981941, IC=+0.0082

      epoch 175/200: loss=0.980324, IC=+0.0071

      epoch 200/200: loss=0.977483, IC=+0.0073

    Fold 0: best_ep=25, IC=+0.0199 (17.3s)

  Fold 1: train=23,681  val=16,738

      epoch  25/200: loss=1.050924, IC=+0.0490

      epoch  50/200: loss=1.044237, IC=+0.0538

      epoch  75/200: loss=1.038354, IC=+0.0519

      epoch 100/200: loss=1.032554, IC=+0.0402

      epoch 125/200: loss=1.029297, IC=+0.0344

      epoch 150/200: loss=1.026527, IC=+0.0326

      epoch 175/200: loss=1.025741, IC=+0.0311

      epoch 200/200: loss=1.027025, IC=+0.0308

    Fold 1: best_ep=50, IC=+0.0538 (7.2s)

      epoch  25/200: loss=1.045681, IC=+0.0533

      epoch  50/200: loss=1.032363, IC=+0.0354

      epoch  75/200: loss=1.020137, IC=+0.0274

      epoch 100/200: loss=1.015274, IC=+0.0208

      epoch 125/200: loss=1.009660, IC=+0.0220

      epoch 150/200: loss=1.008486, IC=+0.0225

      epoch 175/200: loss=1.006882, IC=+0.0227

      epoch 200/200: loss=1.002911, IC=+0.0227

    Fold 1: best_ep=25, IC=+0.0533 (9.1s)

      epoch  25/200: loss=1.038222, IC=+0.0422

      epoch  50/200: loss=1.011100, IC=+0.0304

      epoch  75/200: loss=0.992351, IC=+0.0274

      epoch 100/200: loss=0.974465, IC=+0.0239

      epoch 125/200: loss=0.964953, IC=+0.0222

      epoch 150/200: loss=0.957912, IC=+0.0222

      epoch 175/200: loss=0.952917, IC=+0.0204

      epoch 200/200: loss=0.955519, IC=+0.0214

    Fold 1: best_ep=25, IC=+0.0422 (12.8s)

    → best_epoch=50, IC=+0.0379 (16.5s)

    → best_epoch=25, IC=+0.0356 (20.3s)

    → best_epoch=25, IC=+0.0311 (30.2s)

  Best: 56613697f4f1 @ epoch 50 (IC=+0.0379)

shape: (96, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬──────────┐
│ label      ┆ config_nam ┆ task       ┆ checkpoint ┆ checkpoin ┆ training_ ┆ predictio ┆ complete │
│ ---        ┆ e          ┆ ---        ┆ _kind      ┆ t_value   ┆ hash      ┆ n_hash    ┆ ---      │
│ str        ┆ ---        ┆ str        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ bool     │
│            ┆ str        ┆            ┆ str        ┆ i64       ┆ str       ┆ str       ┆          │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 25        ┆ 320ca8909 ┆ da82f4597 ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ e63       ┆ ff4       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 50        ┆ 320ca8909 ┆ b73e005be ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ e63       ┆ 45a       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 75        ┆ 320ca8909 ┆ c0243640b ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ e63       ┆ 671       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 100       ┆ 320ca8909 ┆ d6bc890a9 ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ e63       ┆ 59e       ┆          │
│ fwd_dir_8h ┆ tabm_l     ┆ classifica ┆ epoch      ┆ 125       ┆ 320ca8909 ┆ 8a8eff7df ┆ true     │
│            ┆            ┆ tion       ┆            ┆           ┆ e63       ┆ 9fe       ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 100       ┆ b3a627bdc ┆ bdd596f5a ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 0b5       ┆ 37f       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 125       ┆ b3a627bdc ┆ 6f078b819 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 0b5       ┆ 9b3       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 150       ┆ b3a627bdc ┆ 55e22f9a8 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 0b5       ┆ 288       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 175       ┆ b3a627bdc ┆ f71c6eb7c ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 0b5       ┆ ba6       ┆          │
│ fwd_ret_8h ┆ tabm_s     ┆ regression ┆ epoch      ┆ 200       ┆ b3a627bdc ┆ dda739968 ┆ true     │
│            ┆            ┆            ┆            ┆           ┆ 0b5       ┆ 29e       ┆          │
└────────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴──────────┘

## Key takeaways and limitations

- Task semantics and imbalance treatment are resolved inputs, not notebook-side conventions.
- Every reported checkpoint has a persisted fitted state and exact prediction coverage.
- GPU kernels can introduce small numerical differences; catalog identity still binds the model,
  seed, device policy, and checkpoint schedule used by the run.