# Does the premium's path carry more than its summaries?

[`06_linear`](06_linear.ipynb) fitted a design matrix that is mostly one economic quantity - the
**premium**, the gap between the perpetual price and spot that the funding payment is computed
from - measured many ways. Among those ways are hand-built summaries of the premium's recent
*path*: its change over six horizons, its volatility over four, its z-score over two windows, its
quantile position over three. Each of those columns compresses a stretch of history into one
number, and a human chose the compression.

A sequence model does not take that compression as given. It reads the last 60 settlements of
every feature as an ordered window and learns its own summary. So the question this notebook and
[`10_dl_tcn`](10_dl_tcn.ipynb) put to the data is narrow and answerable: **on this case study,
does a learned representation of the path beat the hand-built one?** Not "are neural networks
useful" - the design matrix already contains a considerable amount of path information, and the
sequence family has to earn its keep against that, not against a naive baseline.

Two architectures are fitted here against the same request:

- **NLinear** is the baseline, and it is deliberately almost nothing. It subtracts the last value
  of each window from the window, applies a single linear map to what remains, and adds the
  subtracted value back. It has no recurrence, no gating and no nonlinearity. It exists so that
  "the LSTM did better" has to mean better than the simplest thing that reads the same window in
  the same order - which, on financial series, is a bar a great many published architectures do
  not clear.
- **LSTM** is the recurrent model: two layers, a hidden state of 64, dropout 0.1. It processes
  the window one settlement at a time and carries a state forward, so unlike NLinear it can in
  principle represent an interaction between what happened early in the window and what happened
  late.

Both go through the same request contract - the same feature order, the same folds, the same
missing-observation policy, the same checkpoint schedule. **That is the point of running them
from one notebook.** When the two differ in a later backtest, the difference is the architecture,
because nothing else was allowed to vary.

## The grid is 8-hourly, and gaps in it are real

A perpetual's funding is settled every 8 hours, and this case study's observation grid is that
settlement cadence. A lookback of 60 is therefore **60 settlements, about 20 days** - not 60 days
and not 60 rows of whatever happened to be adjacent in the file.

That distinction has teeth here. A perpetual can be delisted, halted, or newly listed, and the
exchange's history has holes. If a 60-bar window were built by taking 60 adjacent *rows*, a
window spanning a two-day outage would silently splice across it and present the model with a
discontinuity as though it were a normal step. The resolved policy on every request below is
`exclude_windows_crossing_missing_expected_periods`: a window that would cross a settlement the
grid expects and the data does not have is **dropped, not imputed**. The eligible-row count in
the contracts table is what survives that rule, and it is smaller than the row count of the
panel.

## A checkpoint is a model, not a progress marker

Each configuration trains for 100 epochs and persists its state every 5, so each produces 20
checkpoints, and **each checkpoint is a distinct prediction identity** that a later backtest can
select. Early stopping is not implemented as a rule that halts training; it is implemented as a
population of checkpoints from which selection picks. That is why the population is frozen before
the first fit: a checkpoint that trains and then turns out to be poor stays in the population it
was declared in, and cannot quietly disappear from the count it is judged against.

**Learning objectives.** By the end of this notebook you will be able to:

- Explain why a sequence model on an irregular observation grid needs a declared cadence, and
  what goes wrong when window construction uses row adjacency instead.
- Read a resolved sequence request and say what lookback, gap policy and eligible row count the
  run will actually use, before anything is fitted.
- Say what a checkpoint schedule buys, and why every checkpoint is registered as its own
  prediction set rather than only the last or the best.
- Recognise that a linear baseline sharing the sequence contract is the correct comparison for a
  recurrent model, and that beating a cross-sectional model is not the same claim.

**Book reference:** Chapter 19, recurrent neural networks for time series.

**Prerequisites:** [`03_financial_features`](03_financial_features.ipynb) and
[`04_model_based_features`](04_model_based_features.ipynb) have written the feature matrices, and
[`05_evaluation`](05_evaluation.ipynb) has established the walk-forward folds. The canonical run
uses CUDA; the reduced run in CI does not.

**What it writes:** one training run per configuration and one complete validation prediction set
per checkpoint, in `run_log/registry.db` and under `run_log/training/` and
`run_log/predictions/`, grouped under a named population.
[`13_backtest`](13_backtest.ipynb) reads that population and selects on validation backtest
Sharpe. **Selection happens there, not here.** Nothing in this notebook ranks anything.

In [1]:
import os

import polars as pl

from case_studies.crypto_perps_funding.research_workflow import (
    REGRESSION_LABELS,
    declared_contracts,
    freeze_official_model_population,
    model_request_catalog,
    open_study,
    plan_model_catalog,
    plan_specs,
    run_model_plan,
)
from case_studies.research import population_supersedes

In [2]:
EXECUTION_TIER = "canonical"
SUPERSEDES_POPULATION: str = "1b444ce334d4"
# The generation of this notebook's own checkpoint population that this run replaces, if any.
# Distinct from SUPERSEDES_POPULATION above, which is the case-wide official model population:
# the two are separate declarations and a refit can move either without moving the other.
SUPERSEDES_MODEL_POPULATION: str = "f3168d150e27"
WORKSPACE = os.environ.get("ML4T_OUTPUT_DIR", "")
LABELS = REGRESSION_LABELS
PREVIEW_REDUCTIONS = {}
OVERRIDES = {"device": "cuda"}

## 1. Resolve the sequence and checkpoint identities

Nothing is fitted in this cell. `model_request_catalog` reads the configurations this case study
declares for the regression labels and returns the requests they resolve to; the plan that
follows binds those requests to the data on disk and computes an identity for each. Reading the
resolved plan before training is what makes the run auditable: if the lookback, the gap policy or
the eligible row count is not what you expected, you find out here rather than after the fits.

`config_prefix=("nlinear", "lstm")` is what restricts this notebook to the two architectures
discussed above. The TCN declared alongside them in `config/training/fwd_ret_8h.yaml` is fitted
by [`10_dl_tcn`](10_dl_tcn.ipynb) against the same contract.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
official_population = (
    freeze_official_model_population(
        study,
        supersedes=population_supersedes(
            study,
            name="crypto-validation-predictions-v1",
            declared=SUPERSEDES_POPULATION,
        ),
    )
    if EXECUTION_TIER == "canonical"
    else None
)
requests = model_request_catalog("deep_learning", labels=LABELS, config_prefix=("nlinear", "lstm"))
requests

shape: (4, 3)
┌───────────────┬─────────────┬─────────────┐
│ family        ┆ label       ┆ config_name │
│ ---           ┆ ---         ┆ ---         │
│ str           ┆ str         ┆ str         │
╞═══════════════╪═════════════╪═════════════╡
│ deep_learning ┆ fwd_ret_8h  ┆ nlinear     │
│ deep_learning ┆ fwd_ret_8h  ┆ lstm_h64    │
│ deep_learning ┆ fwd_ret_24h ┆ nlinear     │
│ deep_learning ┆ fwd_ret_24h ┆ lstm_h64    │
└───────────────┴─────────────┴─────────────┘

The table below is the run's declaration of what it is about to do. `gap_policy` and `lookback`
are read back out of the frozen specification rather than restated from the configuration file,
so the table cannot drift from what the fit will use. `eligible_rows` is the count of window
end-points that survive the gap rule - the effective sample the model is fitted on, which is
always smaller than the panel and is the number to quote when describing how much data a
sequence model here actually saw.

In [4]:
plan = plan_model_catalog(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides=OVERRIDES,
    preview_reductions=PREVIEW_REDUCTIONS,
)
# Sequence eligibility follows from the resolved gap policy and lookback, so read both from the
# frozen specification instead of restating the configuration file here.
resolved_preprocessing = [spec["computation"]["preprocessing"] for spec in plan_specs(plan)]
contracts = declared_contracts(plan).with_columns(
    pl.Series("gap_policy", [step["gap_policy"] for step in resolved_preprocessing]),
    pl.Series("lookback", [step["lookback"] for step in resolved_preprocessing]),
)
contracts.select(
    "label",
    "config_name",
    "gap_policy",
    "lookback",
    "checkpoint_value",
    "eligible_rows",
    "training_hash",
)

shape: (80, 7)
┌─────────────┬─────────────┬──────────────┬──────────┬──────────────┬──────────────┬──────────────┐
│ label       ┆ config_name ┆ gap_policy   ┆ lookback ┆ checkpoint_v ┆ eligible_row ┆ training_has │
│ ---         ┆ ---         ┆ ---          ┆ ---      ┆ alue         ┆ s            ┆ h            │
│ str         ┆ str         ┆ str          ┆ i64      ┆ ---          ┆ ---          ┆ ---          │
│             ┆             ┆              ┆          ┆ i64          ┆ i64          ┆ str          │
╞═════════════╪═════════════╪══════════════╪══════════╪══════════════╪══════════════╪══════════════╡
│ fwd_ret_8h  ┆ nlinear     ┆ calendar_gri ┆ 60       ┆ 5            ┆ 32320        ┆ 1314218b099a │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ fwd_ret_8h  ┆ nlinear     ┆ calendar_gri ┆ 60       ┆ 10           ┆ 32320        ┆ 1314218b099a │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ fwd_ret_8h  ┆ nlinear     ┆ calendar_gri ┆ 60       ┆ 15           ┆ 32320        ┆ 1314218b099a │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ fwd_ret_8h  ┆ nlinear     ┆ calendar_gri ┆ 60       ┆ 20           ┆ 32320        ┆ 1314218b099a │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ fwd_ret_8h  ┆ nlinear     ┆ calendar_gri ┆ 60       ┆ 25           ┆ 32320        ┆ 1314218b099a │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ …           ┆ …           ┆ …            ┆ …        ┆ …            ┆ …            ┆ …            │
│ fwd_ret_24h ┆ lstm_h64    ┆ calendar_gri ┆ 60       ┆ 80           ┆ 32266        ┆ 748cd563b047 │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ fwd_ret_24h ┆ lstm_h64    ┆ calendar_gri ┆ 60       ┆ 85           ┆ 32266        ┆ 748cd563b047 │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ fwd_ret_24h ┆ lstm_h64    ┆ calendar_gri ┆ 60       ┆ 90           ┆ 32266        ┆ 748cd563b047 │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ fwd_ret_24h ┆ lstm_h64    ┆ calendar_gri ┆ 60       ┆ 95           ┆ 32266        ┆ 748cd563b047 │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
│ fwd_ret_24h ┆ lstm_h64    ┆ calendar_gri ┆ 60       ┆ 100          ┆ 32266        ┆ 748cd563b047 │
│             ┆             ┆ d_observatio ┆          ┆              ┆              ┆              │
│             ┆             ┆ n_mask…      ┆          ┆              ┆              ┆              │
└─────────────┴─────────────┴──────────────┴──────────┴──────────────┴──────────────┴──────────────┘

The complete case-wide population is recorded before the first fit, so a member that later
fails to train cannot quietly disappear from the population it was declared in. This notebook
produces one slice of it, and that slice must lie inside the declaration.

In [5]:
if official_population is not None:
    outside = set(plan.expected_prediction_hashes) - set(official_population.members)
    if outside:
        raise RuntimeError(
            f"{len(outside)} declared checkpoints lie outside the official model population"
        )

## 2. Execute the declared population

The adapter fits each configuration on each fold, writes a checkpoint every fifth epoch, and
registers one complete validation prediction set per checkpoint. A fitted state is persisted with
a digest, and a cached state is reused only when the digest matches, so a resumed run cannot
quietly continue from a state that a code change has invalidated.

The completeness check below is the one that matters. A prediction set is `complete` when it
covers every eligible validation key for its fold; a set that covers most of them is not a
slightly worse result, it is a different sample, and comparing it against a full one would be
comparing two things measured on different data. The run raises rather than publishing a
population containing one.

In [6]:
execution = run_model_plan(
    plan,
    supersedes=population_supersedes(
        study,
        name="crypto-lstm-validation-predictions-v1",
        declared=SUPERSEDES_MODEL_POPULATION,
    ),
    population_name="crypto-lstm-validation-predictions-v1"
    if EXECUTION_TIER == "canonical"
    else None,
)
catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if (
    catalog.height != len(plan.expected_prediction_hashes)
    or catalog.filter(~pl.col("complete")).height
):
    raise RuntimeError("sequence baseline and LSTM checkpoint population is incomplete")
catalog.select(
    "label",
    "config_name",
    "checkpoint_value",
    "training_hash",
    "prediction_hash",
    "complete",
)

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=21,457 seq across 16 symbols
    val=15,323 seq across 18 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.137056

      epoch   2/100: train_loss=0.088834

      epoch   3/100: train_loss=0.062069

      epoch   4/100: train_loss=0.044717

      epoch   5/100: train_loss=0.033162, val_loss=0.090846, IC=+0.0243

      epoch   6/100: train_loss=0.024877

      epoch   7/100: train_loss=0.019383

      epoch   8/100: train_loss=0.015914

      epoch   9/100: train_loss=0.013010

      epoch  10/100: train_loss=0.011158, val_loss=0.023279, IC=+0.0253

      epoch  11/100: train_loss=0.009423

      epoch  12/100: train_loss=0.008154

      epoch  13/100: train_loss=0.007120

      epoch  14/100: train_loss=0.006567

      epoch  15/100: train_loss=0.005703, val_loss=0.008199, IC=+0.0200

      epoch  16/100: train_loss=0.005276

      epoch  17/100: train_loss=0.004898

      epoch  18/100: train_loss=0.004646

      epoch  19/100: train_loss=0.004124

      epoch  20/100: train_loss=0.004009, val_loss=0.003679, IC=+0.0100

      epoch  21/100: train_loss=0.003636

      epoch  22/100: train_loss=0.003510

      epoch  23/100: train_loss=0.003281

      epoch  24/100: train_loss=0.003214

      epoch  25/100: train_loss=0.003002, val_loss=0.002060, IC=+0.0050

      epoch  26/100: train_loss=0.002980

      epoch  27/100: train_loss=0.002948

      epoch  28/100: train_loss=0.002904

      epoch  29/100: train_loss=0.002788

      epoch  30/100: train_loss=0.002597, val_loss=0.001448, IC=+0.0061

      epoch  31/100: train_loss=0.002601

      epoch  32/100: train_loss=0.002551

      epoch  33/100: train_loss=0.002443

      epoch  34/100: train_loss=0.002400

      epoch  35/100: train_loss=0.002404, val_loss=0.001217, IC=+0.0074

      epoch  36/100: train_loss=0.002345

      epoch  37/100: train_loss=0.002365

      epoch  38/100: train_loss=0.002266

      epoch  39/100: train_loss=0.002243

      epoch  40/100: train_loss=0.002194, val_loss=0.001099, IC=+0.0047

      epoch  41/100: train_loss=0.002203

      epoch  42/100: train_loss=0.002170

      epoch  43/100: train_loss=0.002179

      epoch  44/100: train_loss=0.002171

      epoch  45/100: train_loss=0.002116, val_loss=0.001050, IC=+0.0010

      epoch  46/100: train_loss=0.002169

      epoch  47/100: train_loss=0.002072

      epoch  48/100: train_loss=0.002077

      epoch  49/100: train_loss=0.002050

      epoch  50/100: train_loss=0.002032, val_loss=0.001017, IC=+0.0011

      epoch  51/100: train_loss=0.002009

      epoch  52/100: train_loss=0.002025

      epoch  53/100: train_loss=0.002021

      epoch  54/100: train_loss=0.002042

      epoch  55/100: train_loss=0.001991, val_loss=0.001002, IC=-0.0039

      epoch  56/100: train_loss=0.001992

      epoch  57/100: train_loss=0.002026

      epoch  58/100: train_loss=0.001992

      epoch  59/100: train_loss=0.001983

      epoch  60/100: train_loss=0.001995, val_loss=0.000986, IC=-0.0050

      epoch  61/100: train_loss=0.002041

      epoch  62/100: train_loss=0.001972

      epoch  63/100: train_loss=0.001984

      epoch  64/100: train_loss=0.001961

      epoch  65/100: train_loss=0.001959, val_loss=0.000980, IC=-0.0006

      epoch  66/100: train_loss=0.001928

      epoch  67/100: train_loss=0.001960

      epoch  68/100: train_loss=0.001945

      epoch  69/100: train_loss=0.001966

      epoch  70/100: train_loss=0.001913, val_loss=0.000975, IC=-0.0014

      epoch  71/100: train_loss=0.001939

      epoch  72/100: train_loss=0.001944

      epoch  73/100: train_loss=0.001904

      epoch  74/100: train_loss=0.001995

      epoch  75/100: train_loss=0.001917, val_loss=0.000972, IC=-0.0051

      epoch  76/100: train_loss=0.001923

      epoch  77/100: train_loss=0.001918

      epoch  78/100: train_loss=0.001927

      epoch  79/100: train_loss=0.001916

      epoch  80/100: train_loss=0.001922, val_loss=0.000970, IC=-0.0013

      epoch  81/100: train_loss=0.001905

      epoch  82/100: train_loss=0.001915

      epoch  83/100: train_loss=0.001905

      epoch  84/100: train_loss=0.001920

      epoch  85/100: train_loss=0.001907, val_loss=0.000969, IC=-0.0027

      epoch  86/100: train_loss=0.001928

      epoch  87/100: train_loss=0.001902

      epoch  88/100: train_loss=0.001919

      epoch  89/100: train_loss=0.001908

      epoch  90/100: train_loss=0.001920, val_loss=0.000968, IC=-0.0030

      epoch  91/100: train_loss=0.001919

      epoch  92/100: train_loss=0.001907

      epoch  93/100: train_loss=0.001904

      epoch  94/100: train_loss=0.001907

      epoch  95/100: train_loss=0.001914, val_loss=0.000968, IC=-0.0030

      epoch  96/100: train_loss=0.001910

      epoch  97/100: train_loss=0.001906

      epoch  98/100: train_loss=0.001887

      epoch  99/100: train_loss=0.001914

      epoch 100/100: train_loss=0.001916, val_loss=0.000968, IC=-0.0033

      best_ep=10, IC=+0.0253 (61.4s, 20 checkpoints)

  Fold 1: creating sequences...

    train=27,969 seq across 18 symbols
    val=16,997 seq across 19 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.230803

      epoch   2/100: train_loss=0.099681

      epoch   3/100: train_loss=0.060722

      epoch   4/100: train_loss=0.036743

      epoch   5/100: train_loss=0.025985, val_loss=0.008525, IC=-0.0034

      epoch   6/100: train_loss=0.019600

      epoch   7/100: train_loss=0.015153

      epoch   8/100: train_loss=0.013272

      epoch   9/100: train_loss=0.011231

      epoch  10/100: train_loss=0.010115, val_loss=0.002776, IC=+0.0114

      epoch  11/100: train_loss=0.008495

      epoch  12/100: train_loss=0.007397

      epoch  13/100: train_loss=0.006962

      epoch  14/100: train_loss=0.006399

      epoch  15/100: train_loss=0.005842, val_loss=0.001440, IC=+0.0123

      epoch  16/100: train_loss=0.005361

      epoch  17/100: train_loss=0.005070

      epoch  18/100: train_loss=0.004828

      epoch  19/100: train_loss=0.004517

      epoch  20/100: train_loss=0.004266, val_loss=0.001025, IC=+0.0066

      epoch  21/100: train_loss=0.004074

      epoch  22/100: train_loss=0.003815

      epoch  23/100: train_loss=0.003584

      epoch  24/100: train_loss=0.003503

      epoch  25/100: train_loss=0.003362, val_loss=0.000855, IC=+0.0027

      epoch  26/100: train_loss=0.003246

      epoch  27/100: train_loss=0.003197

      epoch  28/100: train_loss=0.003038

      epoch  29/100: train_loss=0.002914

      epoch  30/100: train_loss=0.002798, val_loss=0.000764, IC=+0.0016

      epoch  31/100: train_loss=0.002750

      epoch  32/100: train_loss=0.002602

      epoch  33/100: train_loss=0.002582

      epoch  34/100: train_loss=0.002594

      epoch  35/100: train_loss=0.002459, val_loss=0.000723, IC=+0.0009

      epoch  36/100: train_loss=0.002460

      epoch  37/100: train_loss=0.002325

      epoch  38/100: train_loss=0.002349

      epoch  39/100: train_loss=0.002260

      epoch  40/100: train_loss=0.002206, val_loss=0.000692, IC=+0.0008

      epoch  41/100: train_loss=0.002157

      epoch  42/100: train_loss=0.002140

      epoch  43/100: train_loss=0.002134

      epoch  44/100: train_loss=0.002072

      epoch  45/100: train_loss=0.002045, val_loss=0.000672, IC=+0.0015

      epoch  46/100: train_loss=0.002004

      epoch  47/100: train_loss=0.001987

      epoch  48/100: train_loss=0.001986

      epoch  49/100: train_loss=0.001951

      epoch  50/100: train_loss=0.001929, val_loss=0.000660, IC=+0.0001

      epoch  51/100: train_loss=0.001903

      epoch  52/100: train_loss=0.001896

      epoch  53/100: train_loss=0.001866

      epoch  54/100: train_loss=0.001876

      epoch  55/100: train_loss=0.001865, val_loss=0.000647, IC=+0.0049

      epoch  56/100: train_loss=0.001871

      epoch  57/100: train_loss=0.001817

      epoch  58/100: train_loss=0.001807

      epoch  59/100: train_loss=0.001795

      epoch  60/100: train_loss=0.001796, val_loss=0.000642, IC=+0.0035

      epoch  61/100: train_loss=0.001818

      epoch  62/100: train_loss=0.001763

      epoch  63/100: train_loss=0.001776

      epoch  64/100: train_loss=0.001755

      epoch  65/100: train_loss=0.001762, val_loss=0.000637, IC=+0.0041

      epoch  66/100: train_loss=0.001749

      epoch  67/100: train_loss=0.001738

      epoch  68/100: train_loss=0.001742

      epoch  69/100: train_loss=0.001753

      epoch  70/100: train_loss=0.001732, val_loss=0.000634, IC=+0.0032

      epoch  71/100: train_loss=0.001720

      epoch  72/100: train_loss=0.001741

      epoch  73/100: train_loss=0.001725

      epoch  74/100: train_loss=0.001725

      epoch  75/100: train_loss=0.001709, val_loss=0.000633, IC=-0.0008

      epoch  76/100: train_loss=0.001710

      epoch  77/100: train_loss=0.001703

      epoch  78/100: train_loss=0.001690

      epoch  79/100: train_loss=0.001682

      epoch  80/100: train_loss=0.001690, val_loss=0.000631, IC=-0.0006

      epoch  81/100: train_loss=0.001683

      epoch  82/100: train_loss=0.001703

      epoch  83/100: train_loss=0.001701

      epoch  84/100: train_loss=0.001695

      epoch  85/100: train_loss=0.001676, val_loss=0.000631, IC=+0.0001

      epoch  86/100: train_loss=0.001683

      epoch  87/100: train_loss=0.001683

      epoch  88/100: train_loss=0.001687

      epoch  89/100: train_loss=0.001680

      epoch  90/100: train_loss=0.001696, val_loss=0.000630, IC=+0.0017

      epoch  91/100: train_loss=0.001678

      epoch  92/100: train_loss=0.001672

      epoch  93/100: train_loss=0.001684

      epoch  94/100: train_loss=0.001662

      epoch  95/100: train_loss=0.001682, val_loss=0.000630, IC=+0.0013

      epoch  96/100: train_loss=0.001674

      epoch  97/100: train_loss=0.001666

      epoch  98/100: train_loss=0.001661

      epoch  99/100: train_loss=0.001680

      epoch 100/100: train_loss=0.001690, val_loss=0.000630, IC=+0.0013

      best_ep=15, IC=+0.0123 (78.2s, 20 checkpoints)

  nlinear: best_epoch=10, IC=+0.0184 (139.6s)

  Best: nlinear @ epoch 10 (IC=+0.0184)
  Saved to ~/ml4t/public-dl-rerun/case_studies/crypto_perps_funding/run_log/training/1314218b099a/diagnostics

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=21,457 seq across 16 symbols
    val=15,323 seq across 18 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002424

      epoch   2/100: train_loss=0.001928

      epoch   3/100: train_loss=0.001826

      epoch   4/100: train_loss=0.001796

      epoch   5/100: train_loss=0.001788, val_loss=0.000947, IC=+0.0049

      epoch   6/100: train_loss=0.001787

      epoch   7/100: train_loss=0.001791

      epoch   8/100: train_loss=0.001784

      epoch   9/100: train_loss=0.001763

      epoch  10/100: train_loss=0.001765, val_loss=0.000955, IC=+0.0173

      epoch  11/100: train_loss=0.001756

      epoch  12/100: train_loss=0.001754

      epoch  13/100: train_loss=0.001745

      epoch  14/100: train_loss=0.001747

      epoch  15/100: train_loss=0.001741, val_loss=0.000961, IC=+0.0093

      epoch  16/100: train_loss=0.001738

      epoch  17/100: train_loss=0.001739

      epoch  18/100: train_loss=0.001706

      epoch  19/100: train_loss=0.001697

      epoch  20/100: train_loss=0.001695, val_loss=0.000978, IC=+0.0183

      epoch  21/100: train_loss=0.001696

      epoch  22/100: train_loss=0.001683

      epoch  23/100: train_loss=0.001675

      epoch  24/100: train_loss=0.001644

      epoch  25/100: train_loss=0.001666, val_loss=0.000975, IC=+0.0019

      epoch  26/100: train_loss=0.001648

      epoch  27/100: train_loss=0.001631

      epoch  28/100: train_loss=0.001617

      epoch  29/100: train_loss=0.001601

      epoch  30/100: train_loss=0.001584, val_loss=0.000978, IC=+0.0017

      epoch  31/100: train_loss=0.001597

      epoch  32/100: train_loss=0.001577

      epoch  33/100: train_loss=0.001592

      epoch  34/100: train_loss=0.001552

      epoch  35/100: train_loss=0.001543, val_loss=0.000986, IC=-0.0070

      epoch  36/100: train_loss=0.001535

      epoch  37/100: train_loss=0.001535

      epoch  38/100: train_loss=0.001523

      epoch  39/100: train_loss=0.001498

      epoch  40/100: train_loss=0.001496, val_loss=0.000981, IC=+0.0027

      epoch  41/100: train_loss=0.001481

      epoch  42/100: train_loss=0.001481

      epoch  43/100: train_loss=0.001461

      epoch  44/100: train_loss=0.001441

      epoch  45/100: train_loss=0.001458, val_loss=0.000986, IC=+0.0072

      epoch  46/100: train_loss=0.001428

      epoch  47/100: train_loss=0.001425

      epoch  48/100: train_loss=0.001420

      epoch  49/100: train_loss=0.001421

      epoch  50/100: train_loss=0.001409, val_loss=0.000988, IC=+0.0099

      epoch  51/100: train_loss=0.001394

      epoch  52/100: train_loss=0.001374

      epoch  53/100: train_loss=0.001375

      epoch  54/100: train_loss=0.001368

      epoch  55/100: train_loss=0.001350, val_loss=0.000984, IC=+0.0135

      epoch  56/100: train_loss=0.001339

      epoch  57/100: train_loss=0.001338

      epoch  58/100: train_loss=0.001353

      epoch  59/100: train_loss=0.001343

      epoch  60/100: train_loss=0.001326, val_loss=0.000986, IC=+0.0069

      epoch  61/100: train_loss=0.001312

      epoch  62/100: train_loss=0.001313

      epoch  63/100: train_loss=0.001313

      epoch  64/100: train_loss=0.001313

      epoch  65/100: train_loss=0.001311, val_loss=0.000999, IC=+0.0117

      epoch  66/100: train_loss=0.001297

      epoch  67/100: train_loss=0.001290

      epoch  68/100: train_loss=0.001293

      epoch  69/100: train_loss=0.001305

      epoch  70/100: train_loss=0.001286, val_loss=0.000991, IC=+0.0079

      epoch  71/100: train_loss=0.001273

      epoch  72/100: train_loss=0.001283

      epoch  73/100: train_loss=0.001289

      epoch  74/100: train_loss=0.001267

      epoch  75/100: train_loss=0.001275, val_loss=0.000992, IC=+0.0057

      epoch  76/100: train_loss=0.001278

      epoch  77/100: train_loss=0.001262

      epoch  78/100: train_loss=0.001268

      epoch  79/100: train_loss=0.001280

      epoch  80/100: train_loss=0.001278, val_loss=0.000991, IC=+0.0066

      epoch  81/100: train_loss=0.001255

      epoch  82/100: train_loss=0.001267

      epoch  83/100: train_loss=0.001264

      epoch  84/100: train_loss=0.001266

      epoch  85/100: train_loss=0.001278, val_loss=0.000991, IC=+0.0073

      epoch  86/100: train_loss=0.001263

      epoch  87/100: train_loss=0.001255

      epoch  88/100: train_loss=0.001256

      epoch  89/100: train_loss=0.001260

      epoch  90/100: train_loss=0.001262, val_loss=0.000991, IC=+0.0053

      epoch  91/100: train_loss=0.001266

      epoch  92/100: train_loss=0.001252

      epoch  93/100: train_loss=0.001260

      epoch  94/100: train_loss=0.001257

      epoch  95/100: train_loss=0.001255, val_loss=0.000991, IC=+0.0055

      epoch  96/100: train_loss=0.001253

      epoch  97/100: train_loss=0.001252

      epoch  98/100: train_loss=0.001250

      epoch  99/100: train_loss=0.001252

      epoch 100/100: train_loss=0.001252, val_loss=0.000991, IC=+0.0054

      best_ep=20, IC=+0.0183 (87.0s, 20 checkpoints)

  Fold 1: creating sequences...

    train=27,969 seq across 18 symbols
    val=16,997 seq across 19 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002103

      epoch   2/100: train_loss=0.001591

      epoch   3/100: train_loss=0.001542

      epoch   4/100: train_loss=0.001512

      epoch   5/100: train_loss=0.001503, val_loss=0.000631, IC=+0.0030

      epoch   6/100: train_loss=0.001502

      epoch   7/100: train_loss=0.001504

      epoch   8/100: train_loss=0.001491

      epoch   9/100: train_loss=0.001481

      epoch  10/100: train_loss=0.001488, val_loss=0.000633, IC=-0.0014

      epoch  11/100: train_loss=0.001472

      epoch  12/100: train_loss=0.001485

      epoch  13/100: train_loss=0.001459

      epoch  14/100: train_loss=0.001460

      epoch  15/100: train_loss=0.001449, val_loss=0.000631, IC=+0.0135

      epoch  16/100: train_loss=0.001437

      epoch  17/100: train_loss=0.001440

      epoch  18/100: train_loss=0.001433

      epoch  19/100: train_loss=0.001428

      epoch  20/100: train_loss=0.001413, val_loss=0.000637, IC=+0.0020

      epoch  21/100: train_loss=0.001404

      epoch  22/100: train_loss=0.001394

      epoch  23/100: train_loss=0.001385

      epoch  24/100: train_loss=0.001374

      epoch  25/100: train_loss=0.001369, val_loss=0.000662, IC=+0.0077

      epoch  26/100: train_loss=0.001366

      epoch  27/100: train_loss=0.001355

      epoch  28/100: train_loss=0.001342

      epoch  29/100: train_loss=0.001335

      epoch  30/100: train_loss=0.001322, val_loss=0.000673, IC=+0.0063

      epoch  31/100: train_loss=0.001328

      epoch  32/100: train_loss=0.001327

      epoch  33/100: train_loss=0.001309

      epoch  34/100: train_loss=0.001300

      epoch  35/100: train_loss=0.001290, val_loss=0.000684, IC=+0.0051

      epoch  36/100: train_loss=0.001276

      epoch  37/100: train_loss=0.001276

      epoch  38/100: train_loss=0.001264

      epoch  39/100: train_loss=0.001250

      epoch  40/100: train_loss=0.001243, val_loss=0.000672, IC=+0.0042

      epoch  41/100: train_loss=0.001234

      epoch  42/100: train_loss=0.001232

      epoch  43/100: train_loss=0.001213

      epoch  44/100: train_loss=0.001217

      epoch  45/100: train_loss=0.001214, val_loss=0.000686, IC=+0.0003

      epoch  46/100: train_loss=0.001203

      epoch  47/100: train_loss=0.001197

      epoch  48/100: train_loss=0.001189

      epoch  49/100: train_loss=0.001186

      epoch  50/100: train_loss=0.001183, val_loss=0.000689, IC=+0.0005

      epoch  51/100: train_loss=0.001172

      epoch  52/100: train_loss=0.001172

      epoch  53/100: train_loss=0.001172

      epoch  54/100: train_loss=0.001167

      epoch  55/100: train_loss=0.001161, val_loss=0.000686, IC=+0.0011

      epoch  56/100: train_loss=0.001151

      epoch  57/100: train_loss=0.001147

      epoch  58/100: train_loss=0.001149

      epoch  59/100: train_loss=0.001145

      epoch  60/100: train_loss=0.001135, val_loss=0.000687, IC=-0.0011

      epoch  61/100: train_loss=0.001134

      epoch  62/100: train_loss=0.001130

      epoch  63/100: train_loss=0.001121

      epoch  64/100: train_loss=0.001129

      epoch  65/100: train_loss=0.001121, val_loss=0.000698, IC=-0.0013

      epoch  66/100: train_loss=0.001116

      epoch  67/100: train_loss=0.001119

      epoch  68/100: train_loss=0.001112

      epoch  69/100: train_loss=0.001109

      epoch  70/100: train_loss=0.001112, val_loss=0.000700, IC=-0.0007

      epoch  71/100: train_loss=0.001108

      epoch  72/100: train_loss=0.001105

      epoch  73/100: train_loss=0.001101

      epoch  74/100: train_loss=0.001099

      epoch  75/100: train_loss=0.001100, val_loss=0.000695, IC=-0.0016

      epoch  76/100: train_loss=0.001092

      epoch  77/100: train_loss=0.001097

      epoch  78/100: train_loss=0.001088

      epoch  79/100: train_loss=0.001094

      epoch  80/100: train_loss=0.001094, val_loss=0.000698, IC=-0.0015

      epoch  81/100: train_loss=0.001090

      epoch  82/100: train_loss=0.001094

      epoch  83/100: train_loss=0.001092

      epoch  84/100: train_loss=0.001091

      epoch  85/100: train_loss=0.001094, val_loss=0.000698, IC=-0.0029

      epoch  86/100: train_loss=0.001083

      epoch  87/100: train_loss=0.001084

      epoch  88/100: train_loss=0.001087

      epoch  89/100: train_loss=0.001091

      epoch  90/100: train_loss=0.001087, val_loss=0.000698, IC=-0.0020

      epoch  91/100: train_loss=0.001090

      epoch  92/100: train_loss=0.001087

      epoch  93/100: train_loss=0.001079

      epoch  94/100: train_loss=0.001089

      epoch  95/100: train_loss=0.001085, val_loss=0.000698, IC=-0.0031

      epoch  96/100: train_loss=0.001082

      epoch  97/100: train_loss=0.001080

      epoch  98/100: train_loss=0.001092

      epoch  99/100: train_loss=0.001085

      epoch 100/100: train_loss=0.001080, val_loss=0.000698, IC=-0.0027

      best_ep=15, IC=+0.0135 (122.0s, 20 checkpoints)

  lstm_h64: best_epoch=15, IC=+0.0114 (209.1s)

  Best: lstm_h64 @ epoch 15 (IC=+0.0114)
  Saved to ~/ml4t/public-dl-rerun/case_studies/crypto_perps_funding/run_log/training/6ce62c6e810b/diagnostics

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=21,431 seq across 16 symbols
    val=15,307 seq across 18 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.142670

      epoch   2/100: train_loss=0.097760

      epoch   3/100: train_loss=0.070312

      epoch   4/100: train_loss=0.052589

      epoch   5/100: train_loss=0.040304, val_loss=0.093778, IC=+0.0478

      epoch   6/100: train_loss=0.031840

      epoch   7/100: train_loss=0.026148

      epoch   8/100: train_loss=0.021865

      epoch   9/100: train_loss=0.018850

      epoch  10/100: train_loss=0.016797, val_loss=0.025831, IC=+0.0449

      epoch  11/100: train_loss=0.015288

      epoch  12/100: train_loss=0.013656

      epoch  13/100: train_loss=0.012729

      epoch  14/100: train_loss=0.012145

      epoch  15/100: train_loss=0.011326, val_loss=0.009836, IC=+0.0391

      epoch  16/100: train_loss=0.010861

      epoch  17/100: train_loss=0.010367

      epoch  18/100: train_loss=0.010094

      epoch  19/100: train_loss=0.010319

      epoch  20/100: train_loss=0.009448, val_loss=0.005039, IC=+0.0301

      epoch  21/100: train_loss=0.009333

      epoch  22/100: train_loss=0.008990

      epoch  23/100: train_loss=0.008839

      epoch  24/100: train_loss=0.008586

      epoch  25/100: train_loss=0.008526, val_loss=0.003608, IC=+0.0217

      epoch  26/100: train_loss=0.008490

      epoch  27/100: train_loss=0.008367

      epoch  28/100: train_loss=0.008102

      epoch  29/100: train_loss=0.008130

      epoch  30/100: train_loss=0.008067, val_loss=0.003129, IC=+0.0242

      epoch  31/100: train_loss=0.008161

      epoch  32/100: train_loss=0.007929

      epoch  33/100: train_loss=0.008002

      epoch  34/100: train_loss=0.007927

      epoch  35/100: train_loss=0.008591, val_loss=0.002953, IC=+0.0157

      epoch  36/100: train_loss=0.007736

      epoch  37/100: train_loss=0.007737

      epoch  38/100: train_loss=0.007711

      epoch  39/100: train_loss=0.007642

      epoch  40/100: train_loss=0.007575, val_loss=0.002890, IC=+0.0117

      epoch  41/100: train_loss=0.007603

      epoch  42/100: train_loss=0.007544

      epoch  43/100: train_loss=0.007577

      epoch  44/100: train_loss=0.007502

      epoch  45/100: train_loss=0.007502, val_loss=0.002868, IC=+0.0094

      epoch  46/100: train_loss=0.007511

      epoch  47/100: train_loss=0.007471

      epoch  48/100: train_loss=0.007470

      epoch  49/100: train_loss=0.007551

      epoch  50/100: train_loss=0.007438, val_loss=0.002856, IC=+0.0079

      epoch  51/100: train_loss=0.007374

      epoch  52/100: train_loss=0.007633

      epoch  53/100: train_loss=0.007515

      epoch  54/100: train_loss=0.008147

      epoch  55/100: train_loss=0.007392, val_loss=0.002855, IC=+0.0014

      epoch  56/100: train_loss=0.007404

      epoch  57/100: train_loss=0.007423

      epoch  58/100: train_loss=0.007418

      epoch  59/100: train_loss=0.007375

      epoch  60/100: train_loss=0.007415, val_loss=0.002854, IC=-0.0024

      epoch  61/100: train_loss=0.007359

      epoch  62/100: train_loss=0.007384

      epoch  63/100: train_loss=0.007437

      epoch  64/100: train_loss=0.007312

      epoch  65/100: train_loss=0.007362, val_loss=0.002858, IC=+0.0022

      epoch  66/100: train_loss=0.007366

      epoch  67/100: train_loss=0.007321

      epoch  68/100: train_loss=0.007988

      epoch  69/100: train_loss=0.007483

      epoch  70/100: train_loss=0.007994, val_loss=0.002858, IC=-0.0040

      epoch  71/100: train_loss=0.007299

      epoch  72/100: train_loss=0.007497

      epoch  73/100: train_loss=0.007293

      epoch  74/100: train_loss=0.007335

      epoch  75/100: train_loss=0.007266, val_loss=0.002857, IC=-0.0071

      epoch  76/100: train_loss=0.007274

      epoch  77/100: train_loss=0.007266

      epoch  78/100: train_loss=0.007344

      epoch  79/100: train_loss=0.007320

      epoch  80/100: train_loss=0.007328, val_loss=0.002858, IC=-0.0046

      epoch  81/100: train_loss=0.007257

      epoch  82/100: train_loss=0.007255

      epoch  83/100: train_loss=0.007479

      epoch  84/100: train_loss=0.007329

      epoch  85/100: train_loss=0.007291, val_loss=0.002859, IC=-0.0055

      epoch  86/100: train_loss=0.007282

      epoch  87/100: train_loss=0.007293

      epoch  88/100: train_loss=0.007296

      epoch  89/100: train_loss=0.007303

      epoch  90/100: train_loss=0.007251, val_loss=0.002859, IC=-0.0047

      epoch  91/100: train_loss=0.007303

      epoch  92/100: train_loss=0.007297

      epoch  93/100: train_loss=0.007255

      epoch  94/100: train_loss=0.007328

      epoch  95/100: train_loss=0.007389, val_loss=0.002860, IC=-0.0050

      epoch  96/100: train_loss=0.008055

      epoch  97/100: train_loss=0.007310

      epoch  98/100: train_loss=0.008016

      epoch  99/100: train_loss=0.007470

      epoch 100/100: train_loss=0.007220, val_loss=0.002860, IC=-0.0047

      best_ep=5, IC=+0.0478 (77.1s, 20 checkpoints)

  Fold 1: creating sequences...

    train=27,917 seq across 18 symbols
    val=16,959 seq across 19 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.253508

      epoch   2/100: train_loss=0.109818

      epoch   3/100: train_loss=0.065829

      epoch   4/100: train_loss=0.041911

      epoch   5/100: train_loss=0.030507, val_loss=0.010245, IC=-0.0086

      epoch   6/100: train_loss=0.023920

      epoch   7/100: train_loss=0.020679

      epoch   8/100: train_loss=0.017727

      epoch   9/100: train_loss=0.015203

      epoch  10/100: train_loss=0.014262, val_loss=0.004093, IC=+0.0065

      epoch  11/100: train_loss=0.012872

      epoch  12/100: train_loss=0.011900

      epoch  13/100: train_loss=0.011230

      epoch  14/100: train_loss=0.010942

      epoch  15/100: train_loss=0.010349, val_loss=0.002856, IC=+0.0113

      epoch  16/100: train_loss=0.009785

      epoch  17/100: train_loss=0.009635

      epoch  18/100: train_loss=0.008946

      epoch  19/100: train_loss=0.008755

      epoch  20/100: train_loss=0.008578, val_loss=0.002325, IC=+0.0053

      epoch  21/100: train_loss=0.008247

      epoch  22/100: train_loss=0.008172

      epoch  23/100: train_loss=0.007878

      epoch  24/100: train_loss=0.007771

      epoch  25/100: train_loss=0.007639, val_loss=0.002165, IC=-0.0047

      epoch  26/100: train_loss=0.007484

      epoch  27/100: train_loss=0.007368

      epoch  28/100: train_loss=0.007317

      epoch  29/100: train_loss=0.007137

      epoch  30/100: train_loss=0.007221, val_loss=0.002073, IC=-0.0066

      epoch  31/100: train_loss=0.007004

      epoch  32/100: train_loss=0.006907

      epoch  33/100: train_loss=0.007194

      epoch  34/100: train_loss=0.006817

      epoch  35/100: train_loss=0.006800, val_loss=0.002012, IC=-0.0074

      epoch  36/100: train_loss=0.006647

      epoch  37/100: train_loss=0.006520

      epoch  38/100: train_loss=0.006621

      epoch  39/100: train_loss=0.006567

      epoch  40/100: train_loss=0.006476, val_loss=0.001975, IC=-0.0071

      epoch  41/100: train_loss=0.006390

      epoch  42/100: train_loss=0.006668

      epoch  43/100: train_loss=0.006414

      epoch  44/100: train_loss=0.006316

      epoch  45/100: train_loss=0.006278, val_loss=0.001946, IC=-0.0070

      epoch  46/100: train_loss=0.006283

      epoch  47/100: train_loss=0.006223

      epoch  48/100: train_loss=0.006543

      epoch  49/100: train_loss=0.006202

      epoch  50/100: train_loss=0.006449, val_loss=0.001937, IC=-0.0033

      epoch  51/100: train_loss=0.006169

      epoch  52/100: train_loss=0.006143

      epoch  53/100: train_loss=0.006124

      epoch  54/100: train_loss=0.006396

      epoch  55/100: train_loss=0.006113, val_loss=0.001934, IC=-0.0048

      epoch  56/100: train_loss=0.006052

      epoch  57/100: train_loss=0.006053

      epoch  58/100: train_loss=0.006436

      epoch  59/100: train_loss=0.006052

      epoch  60/100: train_loss=0.006035, val_loss=0.001917, IC=-0.0052

      epoch  61/100: train_loss=0.005973

      epoch  62/100: train_loss=0.006014

      epoch  63/100: train_loss=0.005988

      epoch  64/100: train_loss=0.006018

      epoch  65/100: train_loss=0.005998, val_loss=0.001916, IC=-0.0041

      epoch  66/100: train_loss=0.005944

      epoch  67/100: train_loss=0.005986

      epoch  68/100: train_loss=0.006103

      epoch  69/100: train_loss=0.005936

      epoch  70/100: train_loss=0.005936, val_loss=0.001916, IC=-0.0069

      epoch  71/100: train_loss=0.006026

      epoch  72/100: train_loss=0.005976

      epoch  73/100: train_loss=0.005956

      epoch  74/100: train_loss=0.005926

      epoch  75/100: train_loss=0.006070, val_loss=0.001913, IC=-0.0063

      epoch  76/100: train_loss=0.005993

      epoch  77/100: train_loss=0.005937

      epoch  78/100: train_loss=0.005963

      epoch  79/100: train_loss=0.005934

      epoch  80/100: train_loss=0.005915, val_loss=0.001912, IC=-0.0055

      epoch  81/100: train_loss=0.005913

      epoch  82/100: train_loss=0.005943

      epoch  83/100: train_loss=0.005909

      epoch  84/100: train_loss=0.005915

      epoch  85/100: train_loss=0.006286, val_loss=0.001909, IC=-0.0050

      epoch  86/100: train_loss=0.005938

      epoch  87/100: train_loss=0.005890

      epoch  88/100: train_loss=0.005920

      epoch  89/100: train_loss=0.005911

      epoch  90/100: train_loss=0.005955, val_loss=0.001909, IC=-0.0049

      epoch  91/100: train_loss=0.005896

      epoch  92/100: train_loss=0.005931

      epoch  93/100: train_loss=0.005922

      epoch  94/100: train_loss=0.005921

      epoch  95/100: train_loss=0.005918, val_loss=0.001909, IC=-0.0058

      epoch  96/100: train_loss=0.005886

      epoch  97/100: train_loss=0.005872

      epoch  98/100: train_loss=0.005928

      epoch  99/100: train_loss=0.005919

      epoch 100/100: train_loss=0.005916, val_loss=0.001909, IC=-0.0059

      best_ep=15, IC=+0.0113 (102.5s, 20 checkpoints)

  nlinear: best_epoch=10, IC=+0.0259 (179.6s)

  Best: nlinear @ epoch 10 (IC=+0.0259)
  Saved to ~/ml4t/public-dl-rerun/case_studies/crypto_perps_funding/run_log/training/230a6cc348ec/diagnostics

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=21,431 seq across 16 symbols
    val=15,307 seq across 18 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.008003

      epoch   2/100: train_loss=0.007308

      epoch   3/100: train_loss=0.007175

      epoch   4/100: train_loss=0.007110

      epoch   5/100: train_loss=0.007086, val_loss=0.002789, IC=-0.0263

      epoch   6/100: train_loss=0.007064

      epoch   7/100: train_loss=0.006939

      epoch   8/100: train_loss=0.006898

      epoch   9/100: train_loss=0.007033

      epoch  10/100: train_loss=0.006700, val_loss=0.002878, IC=-0.0122

      epoch  11/100: train_loss=0.006683

      epoch  12/100: train_loss=0.006465

      epoch  13/100: train_loss=0.006299

      epoch  14/100: train_loss=0.006184

      epoch  15/100: train_loss=0.005986, val_loss=0.002975, IC=+0.0054

      epoch  16/100: train_loss=0.005838

      epoch  17/100: train_loss=0.005476

      epoch  18/100: train_loss=0.005077

      epoch  19/100: train_loss=0.004884

      epoch  20/100: train_loss=0.004700, val_loss=0.003047, IC=+0.0055

      epoch  21/100: train_loss=0.004487

      epoch  22/100: train_loss=0.004243

      epoch  23/100: train_loss=0.004100

      epoch  24/100: train_loss=0.003964

      epoch  25/100: train_loss=0.003917, val_loss=0.003042, IC=+0.0131

      epoch  26/100: train_loss=0.003827

      epoch  27/100: train_loss=0.003721

      epoch  28/100: train_loss=0.003674

      epoch  29/100: train_loss=0.003586

      epoch  30/100: train_loss=0.003585, val_loss=0.003059, IC=+0.0188

      epoch  31/100: train_loss=0.003493

      epoch  32/100: train_loss=0.003442

      epoch  33/100: train_loss=0.003432

      epoch  34/100: train_loss=0.003338

      epoch  35/100: train_loss=0.003338, val_loss=0.003092, IC=+0.0237

      epoch  36/100: train_loss=0.003295

      epoch  37/100: train_loss=0.003245

      epoch  38/100: train_loss=0.003263

      epoch  39/100: train_loss=0.003222

      epoch  40/100: train_loss=0.003151, val_loss=0.003059, IC=+0.0224

      epoch  41/100: train_loss=0.003176

      epoch  42/100: train_loss=0.003138

      epoch  43/100: train_loss=0.003180

      epoch  44/100: train_loss=0.003083

      epoch  45/100: train_loss=0.003018, val_loss=0.003124, IC=+0.0277

      epoch  46/100: train_loss=0.003036

      epoch  47/100: train_loss=0.003001

      epoch  48/100: train_loss=0.002964

      epoch  49/100: train_loss=0.002976

      epoch  50/100: train_loss=0.002926, val_loss=0.003104, IC=+0.0274

      epoch  51/100: train_loss=0.002916

      epoch  52/100: train_loss=0.002881

      epoch  53/100: train_loss=0.002886

      epoch  54/100: train_loss=0.002855

      epoch  55/100: train_loss=0.002870, val_loss=0.003125, IC=+0.0262

      epoch  56/100: train_loss=0.002813

      epoch  57/100: train_loss=0.002793

      epoch  58/100: train_loss=0.002790

      epoch  59/100: train_loss=0.002789

      epoch  60/100: train_loss=0.002793, val_loss=0.003154, IC=+0.0322

      epoch  61/100: train_loss=0.002779

      epoch  62/100: train_loss=0.002741

      epoch  63/100: train_loss=0.002773

      epoch  64/100: train_loss=0.002728

      epoch  65/100: train_loss=0.002732, val_loss=0.003129, IC=+0.0321

      epoch  66/100: train_loss=0.002694

      epoch  67/100: train_loss=0.002715

      epoch  68/100: train_loss=0.002704

      epoch  69/100: train_loss=0.002643

      epoch  70/100: train_loss=0.002678, val_loss=0.003136, IC=+0.0328

      epoch  71/100: train_loss=0.002689

      epoch  72/100: train_loss=0.002663

      epoch  73/100: train_loss=0.002661

      epoch  74/100: train_loss=0.002645

      epoch  75/100: train_loss=0.002654, val_loss=0.003141, IC=+0.0327

      epoch  76/100: train_loss=0.002639

      epoch  77/100: train_loss=0.002634

      epoch  78/100: train_loss=0.002635

      epoch  79/100: train_loss=0.002626

      epoch  80/100: train_loss=0.002598, val_loss=0.003154, IC=+0.0323

      epoch  81/100: train_loss=0.002638

      epoch  82/100: train_loss=0.002632

      epoch  83/100: train_loss=0.002620

      epoch  84/100: train_loss=0.002626

      epoch  85/100: train_loss=0.002596, val_loss=0.003149, IC=+0.0324

      epoch  86/100: train_loss=0.002600

      epoch  87/100: train_loss=0.002598

      epoch  88/100: train_loss=0.002587

      epoch  89/100: train_loss=0.002611

      epoch  90/100: train_loss=0.002596, val_loss=0.003153, IC=+0.0334

      epoch  91/100: train_loss=0.002619

      epoch  92/100: train_loss=0.002596

      epoch  93/100: train_loss=0.002563

      epoch  94/100: train_loss=0.002584

      epoch  95/100: train_loss=0.002588, val_loss=0.003150, IC=+0.0329

      epoch  96/100: train_loss=0.002587

      epoch  97/100: train_loss=0.002608

      epoch  98/100: train_loss=0.002569

      epoch  99/100: train_loss=0.002605

      epoch 100/100: train_loss=0.002561, val_loss=0.003149, IC=+0.0329

      best_ep=90, IC=+0.0334 (100.9s, 20 checkpoints)

  Fold 1: creating sequences...

    train=27,917 seq across 18 symbols
    val=16,959 seq across 19 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.006336

      epoch   2/100: train_loss=0.005784

      epoch   3/100: train_loss=0.005688

      epoch   4/100: train_loss=0.005631

      epoch   5/100: train_loss=0.005585, val_loss=0.001978, IC=+0.0066

      epoch   6/100: train_loss=0.005535

      epoch   7/100: train_loss=0.005727

      epoch   8/100: train_loss=0.005404

      epoch   9/100: train_loss=0.005230

      epoch  10/100: train_loss=0.005161, val_loss=0.002169, IC=-0.0197

      epoch  11/100: train_loss=0.005295

      epoch  12/100: train_loss=0.004829

      epoch  13/100: train_loss=0.004625

      epoch  14/100: train_loss=0.004434

      epoch  15/100: train_loss=0.004220, val_loss=0.002378, IC=-0.0064

      epoch  16/100: train_loss=0.004078

      epoch  17/100: train_loss=0.003902

      epoch  18/100: train_loss=0.003768

      epoch  19/100: train_loss=0.003673

      epoch  20/100: train_loss=0.003609, val_loss=0.002311, IC=-0.0077

      epoch  21/100: train_loss=0.003523

      epoch  22/100: train_loss=0.003446

      epoch  23/100: train_loss=0.003404

      epoch  24/100: train_loss=0.003335

      epoch  25/100: train_loss=0.003300, val_loss=0.002367, IC=-0.0088

      epoch  26/100: train_loss=0.003258

      epoch  27/100: train_loss=0.003202

      epoch  28/100: train_loss=0.003168

      epoch  29/100: train_loss=0.003150

      epoch  30/100: train_loss=0.003046, val_loss=0.002438, IC=-0.0246

      epoch  31/100: train_loss=0.003086

      epoch  32/100: train_loss=0.002995

      epoch  33/100: train_loss=0.002929

      epoch  34/100: train_loss=0.002945

      epoch  35/100: train_loss=0.002906, val_loss=0.002465, IC=-0.0130

      epoch  36/100: train_loss=0.002911

      epoch  37/100: train_loss=0.002874

      epoch  38/100: train_loss=0.002836

      epoch  39/100: train_loss=0.002804

      epoch  40/100: train_loss=0.002805, val_loss=0.002472, IC=-0.0082

      epoch  41/100: train_loss=0.002736

      epoch  42/100: train_loss=0.002763

      epoch  43/100: train_loss=0.002718

      epoch  44/100: train_loss=0.002721

      epoch  45/100: train_loss=0.002714, val_loss=0.002442, IC=-0.0067

      epoch  46/100: train_loss=0.002706

      epoch  47/100: train_loss=0.002659

      epoch  48/100: train_loss=0.002666

      epoch  49/100: train_loss=0.002623

      epoch  50/100: train_loss=0.002629, val_loss=0.002495, IC=-0.0096

      epoch  51/100: train_loss=0.002612

      epoch  52/100: train_loss=0.002608

      epoch  53/100: train_loss=0.002589

      epoch  54/100: train_loss=0.002567

      epoch  55/100: train_loss=0.002539, val_loss=0.002572, IC=-0.0115

      epoch  56/100: train_loss=0.002542

      epoch  57/100: train_loss=0.002528

      epoch  58/100: train_loss=0.002534

      epoch  59/100: train_loss=0.002509

      epoch  60/100: train_loss=0.002529, val_loss=0.002537, IC=-0.0070

      epoch  61/100: train_loss=0.002492

      epoch  62/100: train_loss=0.002487

      epoch  63/100: train_loss=0.002442

      epoch  64/100: train_loss=0.002448

      epoch  65/100: train_loss=0.002479, val_loss=0.002559, IC=-0.0111

      epoch  66/100: train_loss=0.002444

      epoch  67/100: train_loss=0.002434

      epoch  68/100: train_loss=0.002426

      epoch  69/100: train_loss=0.002409

      epoch  70/100: train_loss=0.002423, val_loss=0.002579, IC=-0.0101

      epoch  71/100: train_loss=0.002414

      epoch  72/100: train_loss=0.002392

      epoch  73/100: train_loss=0.002378

      epoch  74/100: train_loss=0.002384

      epoch  75/100: train_loss=0.002394, val_loss=0.002541, IC=-0.0117

      epoch  76/100: train_loss=0.002368

      epoch  77/100: train_loss=0.002372

      epoch  78/100: train_loss=0.002371

      epoch  79/100: train_loss=0.002365

      epoch  80/100: train_loss=0.002369, val_loss=0.002542, IC=-0.0109

      epoch  81/100: train_loss=0.002364

      epoch  82/100: train_loss=0.002370

      epoch  83/100: train_loss=0.002360

      epoch  84/100: train_loss=0.002349

      epoch  85/100: train_loss=0.002362, val_loss=0.002570, IC=-0.0104

      epoch  86/100: train_loss=0.002352

      epoch  87/100: train_loss=0.002349

      epoch  88/100: train_loss=0.002345

      epoch  89/100: train_loss=0.002347

      epoch  90/100: train_loss=0.002340, val_loss=0.002564, IC=-0.0108

      epoch  91/100: train_loss=0.002334

      epoch  92/100: train_loss=0.002341

      epoch  93/100: train_loss=0.002351

      epoch  94/100: train_loss=0.002336

      epoch  95/100: train_loss=0.002342, val_loss=0.002566, IC=-0.0121

      epoch  96/100: train_loss=0.002333

      epoch  97/100: train_loss=0.002328

      epoch  98/100: train_loss=0.002350

      epoch  99/100: train_loss=0.002341

      epoch 100/100: train_loss=0.002347, val_loss=0.002569, IC=-0.0122

      best_ep=5, IC=+0.0066 (113.0s, 20 checkpoints)

  lstm_h64: best_epoch=60, IC=+0.0128 (213.8s)

  Best: lstm_h64 @ epoch 60 (IC=+0.0128)
  Saved to ~/ml4t/public-dl-rerun/case_studies/crypto_perps_funding/run_log/training/748cd563b047/diagnostics

shape: (80, 6)
┌─────────────┬─────────────┬──────────────────┬───────────────┬─────────────────┬──────────┐
│ label       ┆ config_name ┆ checkpoint_value ┆ training_hash ┆ prediction_hash ┆ complete │
│ ---         ┆ ---         ┆ ---              ┆ ---           ┆ ---             ┆ ---      │
│ str         ┆ str         ┆ i64              ┆ str           ┆ str             ┆ bool     │
╞═════════════╪═════════════╪══════════════════╪═══════════════╪═════════════════╪══════════╡
│ fwd_ret_24h ┆ lstm_h64    ┆ 5                ┆ 748cd563b047  ┆ 8e3df100fa5f    ┆ true     │
│ fwd_ret_24h ┆ lstm_h64    ┆ 10               ┆ 748cd563b047  ┆ bb61022ce8d6    ┆ true     │
│ fwd_ret_24h ┆ lstm_h64    ┆ 15               ┆ 748cd563b047  ┆ ba74d9c5e069    ┆ true     │
│ fwd_ret_24h ┆ lstm_h64    ┆ 20               ┆ 748cd563b047  ┆ 99f5f5e2abd4    ┆ true     │
│ fwd_ret_24h ┆ lstm_h64    ┆ 25               ┆ 748cd563b047  ┆ 1e4e3045df05    ┆ true     │
│ …           ┆ …           ┆ …                ┆ …             ┆ …               ┆ …        │
│ fwd_ret_8h  ┆ nlinear     ┆ 80               ┆ 1314218b099a  ┆ 793688c67b92    ┆ true     │
│ fwd_ret_8h  ┆ nlinear     ┆ 85               ┆ 1314218b099a  ┆ c30f300770a6    ┆ true     │
│ fwd_ret_8h  ┆ nlinear     ┆ 90               ┆ 1314218b099a  ┆ 9f96779aeacc    ┆ true     │
│ fwd_ret_8h  ┆ nlinear     ┆ 95               ┆ 1314218b099a  ┆ 017a271dd7be    ┆ true     │
│ fwd_ret_8h  ┆ nlinear     ┆ 100              ┆ 1314218b099a  ┆ c7414c0d09b5    ┆ true     │
└─────────────┴─────────────┴──────────────────┴───────────────┴─────────────────┴──────────┘

## Key takeaways and limitations

- **Eligibility follows the declared cadence, not row adjacency.** A 60-bar window is 60 expected
  8-hour settlements. A window that would cross a settlement missing from the data is dropped,
  which is why `eligible_rows` is smaller than the panel and why that count, not the panel
  height, is the sample size to quote.
- **The linear baseline is the comparison that means something.** NLinear reads the same window,
  in the same order, under the same contract, and has no recurrence at all. An LSTM that does not
  beat it has not shown that recurrence bought anything on this data.
- **Every checkpoint is a model.** Twenty per configuration, each registered as its own
  prediction identity, and selection among them happens in [`13_backtest`](13_backtest.ipynb) on
  validation backtest Sharpe. Reporting the best checkpoint's score as though one model had
  achieved it would be reporting a maximum over twenty draws as a single measurement.
- **The history is short and the folds are few.** This case study's usable perpetual funding
  history supports two validation folds, and a two-layer LSTM with a 64-unit hidden state has far
  more capacity than two folds of an 8-hourly panel can identify. Dropout and the checkpoint
  population are doing the regularization that a longer history would not need as badly.
- **A fixed lookback is a modelling assumption, not a neutral default.** Sixty settlements is
  about twenty days. Any dependence on something that happened before that window is invisible to
  these models by construction, however long the funding cycle they are meant to capture.