# Does the premium's path carry more than its summaries?

[`06_linear`](06_linear.ipynb) fitted a design matrix that is mostly one economic quantity - the
**premium**, the gap between the perpetual price and spot that the funding payment is computed
from - measured many ways. Among those ways are hand-built summaries of the premium's recent
*path*: its change over six horizons, its volatility over four, its z-score over two windows, its
quantile position over three. Each of those columns compresses a stretch of history into one
number, and a human chose the compression.

A sequence model does not take that compression as given. It reads the last 60 settlements of
every feature as an ordered window and learns its own summary. So the question this notebook and
[`10_dl_tcn`](10_dl_tcn.ipynb) put to the data is narrow and answerable: **on this case study,
does a learned representation of the path beat the hand-built one?** Not "are neural networks
useful" - the design matrix already contains a considerable amount of path information, and the
sequence family has to earn its keep against that, not against a naive baseline.

Two architectures are fitted here against the same request:

- **NLinear** is the baseline, and it is deliberately almost nothing. It subtracts the last value
  of each window from the window, applies a single linear map to what remains, and adds the
  subtracted value back. It has no recurrence, no gating and no nonlinearity. It exists so that
  "the LSTM did better" has to mean better than the simplest thing that reads the same window in
  the same order - which, on financial series, is a bar a great many published architectures do
  not clear.
- **LSTM** is the recurrent model: two layers, a hidden state of 64, dropout 0.1. It processes
  the window one settlement at a time and carries a state forward, so unlike NLinear it can in
  principle represent an interaction between what happened early in the window and what happened
  late.

Both go through the same request contract - the same feature order, the same folds, the same
missing-observation policy, the same checkpoint schedule. **That is the point of running them
from one notebook.** When the two differ in a later backtest, the difference is the architecture,
because nothing else was allowed to vary.

## The grid is 8-hourly, and gaps in it are real

A perpetual's funding is settled every 8 hours, and this case study's observation grid is that
settlement cadence. A lookback of 60 is therefore **60 settlements, about 20 days** - not 60 days
and not 60 rows of whatever happened to be adjacent in the file.

That distinction has teeth here. A perpetual can be delisted, halted, or newly listed, and the
exchange's history has holes. If a 60-bar window were built by taking 60 adjacent *rows*, a
window spanning a two-day outage would silently splice across it and present the model with a
discontinuity as though it were a normal step. The resolved policy on every request below is
`exclude_windows_crossing_missing_expected_periods`: a window that would cross a settlement the
grid expects and the data does not have is **dropped, not imputed**. The eligible-row count in
the contracts table is what survives that rule, and it is smaller than the row count of the
panel.

## A checkpoint is a model, not a progress marker

Each configuration trains for 100 epochs and persists its state every 5, so each produces 20
checkpoints, and **each checkpoint is a distinct prediction identity** that a later backtest can
select. Early stopping is not implemented as a rule that halts training; it is implemented as a
population of checkpoints from which selection picks. That is why the population is frozen before
the first fit: a checkpoint that trains and then turns out to be poor stays in the population it
was declared in, and cannot quietly disappear from the count it is judged against.

**Learning objectives.** By the end of this notebook you will be able to:

- Explain why a sequence model on an irregular observation grid needs a declared cadence, and
  what goes wrong when window construction uses row adjacency instead.
- Read a resolved sequence request and say what lookback, gap policy and eligible row count the
  run will actually use, before anything is fitted.
- Say what a checkpoint schedule buys, and why every checkpoint is registered as its own
  prediction set rather than only the last or the best.
- Recognise that a linear baseline sharing the sequence contract is the correct comparison for a
  recurrent model, and that beating a cross-sectional model is not the same claim.

**Book reference:** Chapter 19, recurrent neural networks for time series.

**Prerequisites:** [`03_financial_features`](03_financial_features.ipynb) and
[`04_model_based_features`](04_model_based_features.ipynb) have written the feature matrices, and
[`05_evaluation`](05_evaluation.ipynb) has established the walk-forward folds. The canonical run
uses CUDA; the reduced run in CI does not.

**What it writes:** one training run per configuration and one complete validation prediction set
per checkpoint, in `run_log/registry.db` and under `run_log/training/` and
`run_log/predictions/`, grouped under a named population.
[`13_backtest`](13_backtest.ipynb) reads that population and selects on validation backtest
Sharpe. **Selection happens there, not here.** Nothing in this notebook ranks anything.

In [1]:
import os

import polars as pl

from case_studies.crypto_perps_funding.research_workflow import (
    REGRESSION_LABELS,
    declared_contracts,
    freeze_official_model_population,
    model_request_catalog,
    open_study,
    plan_model_catalog,
    plan_specs,
    run_model_plan,
)

In [2]:
EXECUTION_TIER = "canonical"
SUPERSEDES_POPULATION: str = ""
# The generation of this notebook's own checkpoint population that this run replaces, if any.
# Distinct from SUPERSEDES_POPULATION above, which is the case-wide official model population:
# the two are separate declarations and a refit can move either without moving the other.
SUPERSEDES_MODEL_POPULATION: str = ""
WORKSPACE = os.environ.get("ML4T_OUTPUT_DIR", "")
LABELS = REGRESSION_LABELS
PREVIEW_REDUCTIONS = {}
OVERRIDES = {"device": "cuda"}

## 1. Resolve the sequence and checkpoint identities

Nothing is fitted in this cell. `model_request_catalog` reads the configurations this case study
declares for the regression labels and returns the requests they resolve to; the plan that
follows binds those requests to the data on disk and computes an identity for each. Reading the
resolved plan before training is what makes the run auditable: if the lookback, the gap policy or
the eligible row count is not what you expected, you find out here rather than after the fits.

`config_prefix=("nlinear", "lstm")` is what restricts this notebook to the two architectures
discussed above. The TCN declared alongside them in `config/training/fwd_ret_8h.yaml` is fitted
by [`10_dl_tcn`](10_dl_tcn.ipynb) against the same contract.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
official_population = (
    freeze_official_model_population(study, supersedes=SUPERSEDES_POPULATION or None)
    if EXECUTION_TIER == "canonical"
    else None
)
requests = model_request_catalog("deep_learning", labels=LABELS, config_prefix=("nlinear", "lstm"))
requests

shape: (4, 3)
┌───────────────┬─────────────┬─────────────┐
│ family        ┆ label       ┆ config_name │
│ ---           ┆ ---         ┆ ---         │
│ str           ┆ str         ┆ str         │
╞═══════════════╪═════════════╪═════════════╡
│ deep_learning ┆ fwd_ret_8h  ┆ nlinear     │
│ deep_learning ┆ fwd_ret_8h  ┆ lstm_h64    │
│ deep_learning ┆ fwd_ret_24h ┆ nlinear     │
│ deep_learning ┆ fwd_ret_24h ┆ lstm_h64    │
└───────────────┴─────────────┴─────────────┘

The table below is the run's declaration of what it is about to do. `gap_policy` and `lookback`
are read back out of the frozen specification rather than restated from the configuration file,
so the table cannot drift from what the fit will use. `eligible_rows` is the count of window
end-points that survive the gap rule - the effective sample the model is fitted on, which is
always smaller than the panel and is the number to quote when describing how much data a
sequence model here actually saw.

In [4]:
plan = plan_model_catalog(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides=OVERRIDES,
    preview_reductions=PREVIEW_REDUCTIONS,
)
# Sequence eligibility follows from the resolved gap policy and lookback, so read both from the
# frozen specification instead of restating the configuration file here.
resolved_preprocessing = [spec["computation"]["preprocessing"] for spec in plan_specs(plan)]
contracts = declared_contracts(plan).with_columns(
    pl.Series("gap_policy", [step["gap_policy"] for step in resolved_preprocessing]),
    pl.Series("lookback", [step["lookback"] for step in resolved_preprocessing]),
)
contracts.select(
    "label",
    "config_name",
    "gap_policy",
    "lookback",
    "checkpoint_value",
    "eligible_rows",
    "training_hash",
)

shape: (80, 7)
┌─────────────┬─────────────┬──────────────┬──────────┬──────────────┬──────────────┬──────────────┐
│ label       ┆ config_name ┆ gap_policy   ┆ lookback ┆ checkpoint_v ┆ eligible_row ┆ training_has │
│ ---         ┆ ---         ┆ ---          ┆ ---      ┆ alue         ┆ s            ┆ h            │
│ str         ┆ str         ┆ str          ┆ i64      ┆ ---          ┆ ---          ┆ ---          │
│             ┆             ┆              ┆          ┆ i64          ┆ i64          ┆ str          │
╞═════════════╪═════════════╪══════════════╪══════════╪══════════════╪══════════════╪══════════════╡
│ fwd_ret_8h  ┆ nlinear     ┆ exclude_wind ┆ 60       ┆ 5            ┆ 31885        ┆ 615931c83f63 │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ fwd_ret_8h  ┆ nlinear     ┆ exclude_wind ┆ 60       ┆ 10           ┆ 31885        ┆ 615931c83f63 │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ fwd_ret_8h  ┆ nlinear     ┆ exclude_wind ┆ 60       ┆ 15           ┆ 31885        ┆ 615931c83f63 │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ fwd_ret_8h  ┆ nlinear     ┆ exclude_wind ┆ 60       ┆ 20           ┆ 31885        ┆ 615931c83f63 │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ fwd_ret_8h  ┆ nlinear     ┆ exclude_wind ┆ 60       ┆ 25           ┆ 31885        ┆ 615931c83f63 │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ …           ┆ …           ┆ …            ┆ …        ┆ …            ┆ …            ┆ …            │
│ fwd_ret_24h ┆ lstm_h64    ┆ exclude_wind ┆ 60       ┆ 80           ┆ 31831        ┆ b6f229eb00dc │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ fwd_ret_24h ┆ lstm_h64    ┆ exclude_wind ┆ 60       ┆ 85           ┆ 31831        ┆ b6f229eb00dc │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ fwd_ret_24h ┆ lstm_h64    ┆ exclude_wind ┆ 60       ┆ 90           ┆ 31831        ┆ b6f229eb00dc │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ fwd_ret_24h ┆ lstm_h64    ┆ exclude_wind ┆ 60       ┆ 95           ┆ 31831        ┆ b6f229eb00dc │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
│ fwd_ret_24h ┆ lstm_h64    ┆ exclude_wind ┆ 60       ┆ 100          ┆ 31831        ┆ b6f229eb00dc │
│             ┆             ┆ ows_crossing ┆          ┆              ┆              ┆              │
│             ┆             ┆ _missi…      ┆          ┆              ┆              ┆              │
└─────────────┴─────────────┴──────────────┴──────────┴──────────────┴──────────────┴──────────────┘

The complete case-wide population is recorded before the first fit, so a member that later
fails to train cannot quietly disappear from the population it was declared in. This notebook
produces one slice of it, and that slice must lie inside the declaration.

In [5]:
if official_population is not None:
    outside = set(plan.expected_prediction_hashes) - set(official_population.members)
    if outside:
        raise RuntimeError(
            f"{len(outside)} declared checkpoints lie outside the official model population"
        )

## 2. Execute the declared population

The adapter fits each configuration on each fold, writes a checkpoint every fifth epoch, and
registers one complete validation prediction set per checkpoint. A fitted state is persisted with
a digest, and a cached state is reused only when the digest matches, so a resumed run cannot
quietly continue from a state that a code change has invalidated.

The completeness check below is the one that matters. A prediction set is `complete` when it
covers every eligible validation key for its fold; a set that covers most of them is not a
slightly worse result, it is a different sample, and comparing it against a full one would be
comparing two things measured on different data. The run raises rather than publishing a
population containing one.

In [6]:
execution = run_model_plan(
    plan,
    supersedes=SUPERSEDES_MODEL_POPULATION or None,
    population_name="crypto-lstm-validation-predictions-v1"
    if EXECUTION_TIER == "canonical"
    else None,
)
catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if (
    catalog.height != len(plan.expected_prediction_hashes)
    or catalog.filter(~pl.col("complete")).height
):
    raise RuntimeError("sequence baseline and LSTM checkpoint population is incomplete")
catalog.select(
    "label",
    "config_name",
    "checkpoint_value",
    "training_hash",
    "prediction_hash",
    "complete",
)

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=27,756 seq across 18 symbols
    val=16,682 seq across 19 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.155731

      epoch   2/100: train_loss=0.092476

      epoch   3/100: train_loss=0.057305

      epoch   4/100: train_loss=0.038425

      epoch   5/100: train_loss=0.027808, val_loss=0.018540, IC=-0.0117

      epoch   6/100: train_loss=0.019175

      epoch   7/100: train_loss=0.015092

      epoch   8/100: train_loss=0.011389

      epoch   9/100: train_loss=0.009820

      epoch  10/100: train_loss=0.007465, val_loss=0.005478, IC=-0.0143

      epoch  11/100: train_loss=0.006455

      epoch  12/100: train_loss=0.005462

      epoch  13/100: train_loss=0.004789

      epoch  14/100: train_loss=0.004568

      epoch  15/100: train_loss=0.004082, val_loss=0.002394, IC=-0.0188

      epoch  16/100: train_loss=0.003591

      epoch  17/100: train_loss=0.003408

      epoch  18/100: train_loss=0.003331

      epoch  19/100: train_loss=0.003118

      epoch  20/100: train_loss=0.002873, val_loss=0.001424, IC=-0.0219

      epoch  21/100: train_loss=0.002781

      epoch  22/100: train_loss=0.002644

      epoch  23/100: train_loss=0.002583

      epoch  24/100: train_loss=0.002543

      epoch  25/100: train_loss=0.002404, val_loss=0.001060, IC=-0.0231

      epoch  26/100: train_loss=0.002329

      epoch  27/100: train_loss=0.002312

      epoch  28/100: train_loss=0.002298

      epoch  29/100: train_loss=0.002275

      epoch  30/100: train_loss=0.002232, val_loss=0.000897, IC=-0.0157

      epoch  31/100: train_loss=0.002129

      epoch  32/100: train_loss=0.002047

      epoch  33/100: train_loss=0.002008

      epoch  34/100: train_loss=0.002003

      epoch  35/100: train_loss=0.001999, val_loss=0.000789, IC=-0.0153

      epoch  36/100: train_loss=0.001936

      epoch  37/100: train_loss=0.002110

      epoch  38/100: train_loss=0.001882

      epoch  39/100: train_loss=0.001944

      epoch  40/100: train_loss=0.001978, val_loss=0.000731, IC=-0.0154

      epoch  41/100: train_loss=0.001928

      epoch  42/100: train_loss=0.001840

      epoch  43/100: train_loss=0.001921

      epoch  44/100: train_loss=0.001944

      epoch  45/100: train_loss=0.001807, val_loss=0.000687, IC=-0.0182

      epoch  46/100: train_loss=0.001874

      epoch  47/100: train_loss=0.001823

      epoch  48/100: train_loss=0.001847

      epoch  49/100: train_loss=0.001808

      epoch  50/100: train_loss=0.001737, val_loss=0.000664, IC=-0.0169

      epoch  51/100: train_loss=0.001746

      epoch  52/100: train_loss=0.001795

      epoch  53/100: train_loss=0.001763

      epoch  54/100: train_loss=0.001734

      epoch  55/100: train_loss=0.001734, val_loss=0.000640, IC=-0.0159

      epoch  56/100: train_loss=0.001694

      epoch  57/100: train_loss=0.001729

      epoch  58/100: train_loss=0.001742

      epoch  59/100: train_loss=0.001760

      epoch  60/100: train_loss=0.001741, val_loss=0.000627, IC=-0.0161

      epoch  61/100: train_loss=0.001731

      epoch  62/100: train_loss=0.001725

      epoch  63/100: train_loss=0.001674

      epoch  64/100: train_loss=0.001700

      epoch  65/100: train_loss=0.001681, val_loss=0.000621, IC=-0.0141

      epoch  66/100: train_loss=0.001685

      epoch  67/100: train_loss=0.001651

      epoch  68/100: train_loss=0.001710

      epoch  69/100: train_loss=0.001690

      epoch  70/100: train_loss=0.001670, val_loss=0.000613, IC=-0.0140

      epoch  71/100: train_loss=0.001674

      epoch  72/100: train_loss=0.001690

      epoch  73/100: train_loss=0.001670

      epoch  74/100: train_loss=0.001683

      epoch  75/100: train_loss=0.001652, val_loss=0.000608, IC=-0.0118

      epoch  76/100: train_loss=0.001663

      epoch  77/100: train_loss=0.001631

      epoch  78/100: train_loss=0.001631

      epoch  79/100: train_loss=0.001666

      epoch  80/100: train_loss=0.001685, val_loss=0.000606, IC=-0.0127

      epoch  81/100: train_loss=0.001687

      epoch  82/100: train_loss=0.001690

      epoch  83/100: train_loss=0.001655

      epoch  84/100: train_loss=0.001677

      epoch  85/100: train_loss=0.001660, val_loss=0.000603, IC=-0.0098

      epoch  86/100: train_loss=0.001659

      epoch  87/100: train_loss=0.001662

      epoch  88/100: train_loss=0.001664

      epoch  89/100: train_loss=0.001662

      epoch  90/100: train_loss=0.001645, val_loss=0.000604, IC=-0.0118

      epoch  91/100: train_loss=0.001655

      epoch  92/100: train_loss=0.001614

      epoch  93/100: train_loss=0.001642

      epoch  94/100: train_loss=0.001672

      epoch  95/100: train_loss=0.001647, val_loss=0.000603, IC=-0.0111

      epoch  96/100: train_loss=0.001663

      epoch  97/100: train_loss=0.001630

      epoch  98/100: train_loss=0.001677

      epoch  99/100: train_loss=0.001640

      epoch 100/100: train_loss=0.001644, val_loss=0.000603, IC=-0.0111

      best_ep=85, IC=-0.0098 (74.3s, 20 checkpoints)

  Fold 1: creating sequences...

    train=21,349 seq across 16 symbols
    val=15,203 seq across 18 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.302634

      epoch   2/100: train_loss=0.131533

      epoch   3/100: train_loss=0.087718

      epoch   4/100: train_loss=0.057752

      epoch   5/100: train_loss=0.040797, val_loss=0.031730, IC=-0.0088

      epoch   6/100: train_loss=0.030764

      epoch   7/100: train_loss=0.024884

      epoch   8/100: train_loss=0.020438

      epoch   9/100: train_loss=0.017264

      epoch  10/100: train_loss=0.014440, val_loss=0.008896, IC=+0.0079

      epoch  11/100: train_loss=0.012677

      epoch  12/100: train_loss=0.011111

      epoch  13/100: train_loss=0.010011

      epoch  14/100: train_loss=0.009207

      epoch  15/100: train_loss=0.008340, val_loss=0.004492, IC=+0.0182

      epoch  16/100: train_loss=0.007655

      epoch  17/100: train_loss=0.007189

      epoch  18/100: train_loss=0.006413

      epoch  19/100: train_loss=0.006168

      epoch  20/100: train_loss=0.005779, val_loss=0.002900, IC=+0.0265

      epoch  21/100: train_loss=0.005344

      epoch  22/100: train_loss=0.005201

      epoch  23/100: train_loss=0.004938

      epoch  24/100: train_loss=0.004554

      epoch  25/100: train_loss=0.004442, val_loss=0.002115, IC=+0.0223

      epoch  26/100: train_loss=0.004255

      epoch  27/100: train_loss=0.004018

      epoch  28/100: train_loss=0.003872

      epoch  29/100: train_loss=0.003748

      epoch  30/100: train_loss=0.003682, val_loss=0.001731, IC=+0.0176

      epoch  31/100: train_loss=0.003537

      epoch  32/100: train_loss=0.003423

      epoch  33/100: train_loss=0.003343

      epoch  34/100: train_loss=0.003225

      epoch  35/100: train_loss=0.003086, val_loss=0.001488, IC=+0.0103

      epoch  36/100: train_loss=0.003105

      epoch  37/100: train_loss=0.002965

      epoch  38/100: train_loss=0.002923

      epoch  39/100: train_loss=0.002873

      epoch  40/100: train_loss=0.002791, val_loss=0.001339, IC=+0.0045

      epoch  41/100: train_loss=0.002742

      epoch  42/100: train_loss=0.002727

      epoch  43/100: train_loss=0.002663

      epoch  44/100: train_loss=0.002613

      epoch  45/100: train_loss=0.002607, val_loss=0.001212, IC=-0.0010

      epoch  46/100: train_loss=0.002572

      epoch  47/100: train_loss=0.002521

      epoch  48/100: train_loss=0.002480

      epoch  49/100: train_loss=0.002487

      epoch  50/100: train_loss=0.002461, val_loss=0.001158, IC=-0.0033

      epoch  51/100: train_loss=0.002394

      epoch  52/100: train_loss=0.002403

      epoch  53/100: train_loss=0.002388

      epoch  54/100: train_loss=0.002413

      epoch  55/100: train_loss=0.002297, val_loss=0.001117, IC=-0.0043

      epoch  56/100: train_loss=0.002313

      epoch  57/100: train_loss=0.002313

      epoch  58/100: train_loss=0.002284

      epoch  59/100: train_loss=0.002252

      epoch  60/100: train_loss=0.002285, val_loss=0.001089, IC=-0.0084

      epoch  61/100: train_loss=0.002247

      epoch  62/100: train_loss=0.002259

      epoch  63/100: train_loss=0.002242

      epoch  64/100: train_loss=0.002249

      epoch  65/100: train_loss=0.002206, val_loss=0.001064, IC=-0.0103

      epoch  66/100: train_loss=0.002186

      epoch  67/100: train_loss=0.002239

      epoch  68/100: train_loss=0.002216

      epoch  69/100: train_loss=0.002227

      epoch  70/100: train_loss=0.002138, val_loss=0.001056, IC=-0.0081

      epoch  71/100: train_loss=0.002165

      epoch  72/100: train_loss=0.002170

      epoch  73/100: train_loss=0.002143

      epoch  74/100: train_loss=0.002117

      epoch  75/100: train_loss=0.002145, val_loss=0.001049, IC=-0.0082

      epoch  76/100: train_loss=0.002143

      epoch  77/100: train_loss=0.002163

      epoch  78/100: train_loss=0.002122

      epoch  79/100: train_loss=0.002147

      epoch  80/100: train_loss=0.002124, val_loss=0.001042, IC=-0.0092

      epoch  81/100: train_loss=0.002131

      epoch  82/100: train_loss=0.002110

      epoch  83/100: train_loss=0.002092

      epoch  84/100: train_loss=0.002124

      epoch  85/100: train_loss=0.002130, val_loss=0.001038, IC=-0.0103

      epoch  86/100: train_loss=0.002114

      epoch  87/100: train_loss=0.002130

      epoch  88/100: train_loss=0.002095

      epoch  89/100: train_loss=0.002098

      epoch  90/100: train_loss=0.002101, val_loss=0.001037, IC=-0.0099

      epoch  91/100: train_loss=0.002099

      epoch  92/100: train_loss=0.002115

      epoch  93/100: train_loss=0.002093

      epoch  94/100: train_loss=0.002118

      epoch  95/100: train_loss=0.002114, val_loss=0.001036, IC=-0.0106

      epoch  96/100: train_loss=0.002107

      epoch  97/100: train_loss=0.002122

      epoch  98/100: train_loss=0.002105

      epoch  99/100: train_loss=0.002123

      epoch 100/100: train_loss=0.002105, val_loss=0.001036, IC=-0.0107

      best_ep=20, IC=+0.0265 (53.1s, 20 checkpoints)

  nlinear: best_epoch=20, IC=+0.0026 (127.3s)

  Best: nlinear @ epoch 20 (IC=+0.0026)
  Saved to ~/ml4t/public-s6-crypto_perps_funding-bt/case_studies/crypto_perps_funding/run_log/training/615931c83f63/diagnostics

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=27,756 seq across 18 symbols
    val=16,682 seq across 19 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001814

      epoch   2/100: train_loss=0.001554

      epoch   3/100: train_loss=0.001521

      epoch   4/100: train_loss=0.001511

      epoch   5/100: train_loss=0.001509, val_loss=0.000594, IC=+0.0293

      epoch   6/100: train_loss=0.001506

      epoch   7/100: train_loss=0.001484

      epoch   8/100: train_loss=0.001486

      epoch   9/100: train_loss=0.001477

      epoch  10/100: train_loss=0.001487, val_loss=0.000598, IC=+0.0036

      epoch  11/100: train_loss=0.001471

      epoch  12/100: train_loss=0.001455

      epoch  13/100: train_loss=0.001448

      epoch  14/100: train_loss=0.001442

      epoch  15/100: train_loss=0.001430, val_loss=0.000629, IC=-0.0023

      epoch  16/100: train_loss=0.001418

      epoch  17/100: train_loss=0.001409

      epoch  18/100: train_loss=0.001411

      epoch  19/100: train_loss=0.001419

      epoch  20/100: train_loss=0.001390, val_loss=0.000623, IC=+0.0082

      epoch  21/100: train_loss=0.001372

      epoch  22/100: train_loss=0.001364

      epoch  23/100: train_loss=0.001348

      epoch  24/100: train_loss=0.001348

      epoch  25/100: train_loss=0.001332, val_loss=0.000656, IC=+0.0037

      epoch  26/100: train_loss=0.001324

      epoch  27/100: train_loss=0.001311

      epoch  28/100: train_loss=0.001307

      epoch  29/100: train_loss=0.001292

      epoch  30/100: train_loss=0.001279, val_loss=0.000657, IC=+0.0017

      epoch  31/100: train_loss=0.001279

      epoch  32/100: train_loss=0.001259

      epoch  33/100: train_loss=0.001250

      epoch  34/100: train_loss=0.001230

      epoch  35/100: train_loss=0.001236, val_loss=0.000642, IC=+0.0020

      epoch  36/100: train_loss=0.001226

      epoch  37/100: train_loss=0.001224

      epoch  38/100: train_loss=0.001184

      epoch  39/100: train_loss=0.001186

      epoch  40/100: train_loss=0.001178, val_loss=0.000676, IC=+0.0013

      epoch  41/100: train_loss=0.001183

      epoch  42/100: train_loss=0.001168

      epoch  43/100: train_loss=0.001149

      epoch  44/100: train_loss=0.001154

      epoch  45/100: train_loss=0.001146, val_loss=0.000674, IC=-0.0002

      epoch  46/100: train_loss=0.001131

      epoch  47/100: train_loss=0.001125

      epoch  48/100: train_loss=0.001118

      epoch  49/100: train_loss=0.001116

      epoch  50/100: train_loss=0.001103, val_loss=0.000672, IC=-0.0022

      epoch  51/100: train_loss=0.001101

      epoch  52/100: train_loss=0.001090

      epoch  53/100: train_loss=0.001092

      epoch  54/100: train_loss=0.001083

      epoch  55/100: train_loss=0.001086, val_loss=0.000696, IC=-0.0017

      epoch  56/100: train_loss=0.001071

      epoch  57/100: train_loss=0.001067

      epoch  58/100: train_loss=0.001063

      epoch  59/100: train_loss=0.001060

      epoch  60/100: train_loss=0.001055, val_loss=0.000697, IC=+0.0032

      epoch  61/100: train_loss=0.001051

      epoch  62/100: train_loss=0.001051

      epoch  63/100: train_loss=0.001044

      epoch  64/100: train_loss=0.001046

      epoch  65/100: train_loss=0.001037, val_loss=0.000684, IC=-0.0009

      epoch  66/100: train_loss=0.001037

      epoch  67/100: train_loss=0.001034

      epoch  68/100: train_loss=0.001030

      epoch  69/100: train_loss=0.001027

      epoch  70/100: train_loss=0.001038, val_loss=0.000686, IC=-0.0021

      epoch  71/100: train_loss=0.001028

      epoch  72/100: train_loss=0.001028

      epoch  73/100: train_loss=0.001029

      epoch  74/100: train_loss=0.001020

      epoch  75/100: train_loss=0.001020, val_loss=0.000685, IC=-0.0026

      epoch  76/100: train_loss=0.001017

      epoch  77/100: train_loss=0.001017

      epoch  78/100: train_loss=0.001010

      epoch  79/100: train_loss=0.001021

      epoch  80/100: train_loss=0.001014, val_loss=0.000686, IC=-0.0014

      epoch  81/100: train_loss=0.001013

      epoch  82/100: train_loss=0.001013

      epoch  83/100: train_loss=0.001005

      epoch  84/100: train_loss=0.001010

      epoch  85/100: train_loss=0.001004, val_loss=0.000690, IC=-0.0027

      epoch  86/100: train_loss=0.001002

      epoch  87/100: train_loss=0.001005

      epoch  88/100: train_loss=0.001011

      epoch  89/100: train_loss=0.001004

      epoch  90/100: train_loss=0.001001, val_loss=0.000690, IC=-0.0009

      epoch  91/100: train_loss=0.000999

      epoch  92/100: train_loss=0.001008

      epoch  93/100: train_loss=0.000999

      epoch  94/100: train_loss=0.001000

      epoch  95/100: train_loss=0.001001, val_loss=0.000690, IC=-0.0015

      epoch  96/100: train_loss=0.001007

      epoch  97/100: train_loss=0.001011

      epoch  98/100: train_loss=0.001007

      epoch  99/100: train_loss=0.001010

      epoch 100/100: train_loss=0.000999, val_loss=0.000690, IC=-0.0016

      best_ep=5, IC=+0.0293 (70.9s, 20 checkpoints)

  Fold 1: creating sequences...

    train=21,349 seq across 16 symbols
    val=15,203 seq across 18 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002129

      epoch   2/100: train_loss=0.001852

      epoch   3/100: train_loss=0.001829

      epoch   4/100: train_loss=0.001811

      epoch   5/100: train_loss=0.001777, val_loss=0.000947, IC=+0.0092

      epoch   6/100: train_loss=0.001780

      epoch   7/100: train_loss=0.001761

      epoch   8/100: train_loss=0.001765

      epoch   9/100: train_loss=0.001746

      epoch  10/100: train_loss=0.001745, val_loss=0.000955, IC=+0.0138

      epoch  11/100: train_loss=0.001713

      epoch  12/100: train_loss=0.001726

      epoch  13/100: train_loss=0.001701

      epoch  14/100: train_loss=0.001711

      epoch  15/100: train_loss=0.001703, val_loss=0.000967, IC=+0.0290

      epoch  16/100: train_loss=0.001690

      epoch  17/100: train_loss=0.001662

      epoch  18/100: train_loss=0.001652

      epoch  19/100: train_loss=0.001630

      epoch  20/100: train_loss=0.001623, val_loss=0.000981, IC=+0.0294

      epoch  21/100: train_loss=0.001605

      epoch  22/100: train_loss=0.001597

      epoch  23/100: train_loss=0.001590

      epoch  24/100: train_loss=0.001573

      epoch  25/100: train_loss=0.001564, val_loss=0.000969, IC=+0.0208

      epoch  26/100: train_loss=0.001558

      epoch  27/100: train_loss=0.001542

      epoch  28/100: train_loss=0.001539

      epoch  29/100: train_loss=0.001535

      epoch  30/100: train_loss=0.001493, val_loss=0.000971, IC=+0.0187

      epoch  31/100: train_loss=0.001497

      epoch  32/100: train_loss=0.001497

      epoch  33/100: train_loss=0.001482

      epoch  34/100: train_loss=0.001487

      epoch  35/100: train_loss=0.001445, val_loss=0.000975, IC=+0.0190

      epoch  36/100: train_loss=0.001452

      epoch  37/100: train_loss=0.001474

      epoch  38/100: train_loss=0.001436

      epoch  39/100: train_loss=0.001399

      epoch  40/100: train_loss=0.001404, val_loss=0.000973, IC=+0.0264

      epoch  41/100: train_loss=0.001427

      epoch  42/100: train_loss=0.001387

      epoch  43/100: train_loss=0.001386

      epoch  44/100: train_loss=0.001378

      epoch  45/100: train_loss=0.001373, val_loss=0.000973, IC=+0.0256

      epoch  46/100: train_loss=0.001355

      epoch  47/100: train_loss=0.001352

      epoch  48/100: train_loss=0.001357

      epoch  49/100: train_loss=0.001344

      epoch  50/100: train_loss=0.001322, val_loss=0.000977, IC=+0.0220

      epoch  51/100: train_loss=0.001341

      epoch  52/100: train_loss=0.001314

      epoch  53/100: train_loss=0.001304

      epoch  54/100: train_loss=0.001308

      epoch  55/100: train_loss=0.001300, val_loss=0.000985, IC=+0.0200

      epoch  56/100: train_loss=0.001288

      epoch  57/100: train_loss=0.001306

      epoch  58/100: train_loss=0.001284

      epoch  59/100: train_loss=0.001293

      epoch  60/100: train_loss=0.001270, val_loss=0.000983, IC=+0.0227

      epoch  61/100: train_loss=0.001284

      epoch  62/100: train_loss=0.001261

      epoch  63/100: train_loss=0.001257

      epoch  64/100: train_loss=0.001264

      epoch  65/100: train_loss=0.001233, val_loss=0.000985, IC=+0.0217

      epoch  66/100: train_loss=0.001256

      epoch  67/100: train_loss=0.001254

      epoch  68/100: train_loss=0.001226

      epoch  69/100: train_loss=0.001239

      epoch  70/100: train_loss=0.001240, val_loss=0.000984, IC=+0.0176

      epoch  71/100: train_loss=0.001232

      epoch  72/100: train_loss=0.001236

      epoch  73/100: train_loss=0.001245

      epoch  74/100: train_loss=0.001221

      epoch  75/100: train_loss=0.001220, val_loss=0.000989, IC=+0.0170

      epoch  76/100: train_loss=0.001221

      epoch  77/100: train_loss=0.001224

      epoch  78/100: train_loss=0.001216

      epoch  79/100: train_loss=0.001223

      epoch  80/100: train_loss=0.001219, val_loss=0.000986, IC=+0.0152

      epoch  81/100: train_loss=0.001221

      epoch  82/100: train_loss=0.001214

      epoch  83/100: train_loss=0.001205

      epoch  84/100: train_loss=0.001218

      epoch  85/100: train_loss=0.001197, val_loss=0.000987, IC=+0.0166

      epoch  86/100: train_loss=0.001208

      epoch  87/100: train_loss=0.001209

      epoch  88/100: train_loss=0.001212

      epoch  89/100: train_loss=0.001214

      epoch  90/100: train_loss=0.001195, val_loss=0.000989, IC=+0.0165

      epoch  91/100: train_loss=0.001188

      epoch  92/100: train_loss=0.001205

      epoch  93/100: train_loss=0.001188

      epoch  94/100: train_loss=0.001198

      epoch  95/100: train_loss=0.001194, val_loss=0.000989, IC=+0.0165

      epoch  96/100: train_loss=0.001202

      epoch  97/100: train_loss=0.001191

      epoch  98/100: train_loss=0.001201

      epoch  99/100: train_loss=0.001198

      epoch 100/100: train_loss=0.001203, val_loss=0.000988, IC=+0.0170

      best_ep=20, IC=+0.0294 (52.6s, 20 checkpoints)

  lstm_h64: best_epoch=5, IC=+0.0192 (123.6s)

  Best: lstm_h64 @ epoch 5 (IC=+0.0192)
  Saved to ~/ml4t/public-s6-crypto_perps_funding-bt/case_studies/crypto_perps_funding/run_log/training/a581e3d53ebe/diagnostics

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone=None), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=27,704 seq across 18 symbols
    val=16,644 seq across 19 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.158931

      epoch   2/100: train_loss=0.096119

      epoch   3/100: train_loss=0.062443

      epoch   4/100: train_loss=0.042312

      epoch   5/100: train_loss=0.031447, val_loss=0.019736, IC=-0.0114

      epoch   6/100: train_loss=0.023669

      epoch   7/100: train_loss=0.020044

      epoch   8/100: train_loss=0.016263

      epoch   9/100: train_loss=0.013763

      epoch  10/100: train_loss=0.011876, val_loss=0.006312, IC=-0.0220

      epoch  11/100: train_loss=0.011627

      epoch  12/100: train_loss=0.010186

      epoch  13/100: train_loss=0.009387

      epoch  14/100: train_loss=0.008532

      epoch  15/100: train_loss=0.009292, val_loss=0.003327, IC=-0.0323

      epoch  16/100: train_loss=0.008232

      epoch  17/100: train_loss=0.007696

      epoch  18/100: train_loss=0.007485

      epoch  19/100: train_loss=0.007085

      epoch  20/100: train_loss=0.007348, val_loss=0.002396, IC=-0.0347

      epoch  21/100: train_loss=0.007106

      epoch  22/100: train_loss=0.007080

      epoch  23/100: train_loss=0.006845

      epoch  24/100: train_loss=0.006734

      epoch  25/100: train_loss=0.006726, val_loss=0.002068, IC=-0.0301

      epoch  26/100: train_loss=0.006869

      epoch  27/100: train_loss=0.006626

      epoch  28/100: train_loss=0.006577

      epoch  29/100: train_loss=0.006514

      epoch  30/100: train_loss=0.006430, val_loss=0.001940, IC=-0.0291

      epoch  31/100: train_loss=0.006319

      epoch  32/100: train_loss=0.006466

      epoch  33/100: train_loss=0.006346

      epoch  34/100: train_loss=0.006344

      epoch  35/100: train_loss=0.006255, val_loss=0.001864, IC=-0.0168

      epoch  36/100: train_loss=0.006233

      epoch  37/100: train_loss=0.006688

      epoch  38/100: train_loss=0.006202

      epoch  39/100: train_loss=0.006378

      epoch  40/100: train_loss=0.006188, val_loss=0.001825, IC=-0.0203

      epoch  41/100: train_loss=0.006153

      epoch  42/100: train_loss=0.006484

      epoch  43/100: train_loss=0.006042

      epoch  44/100: train_loss=0.006061

      epoch  45/100: train_loss=0.006030, val_loss=0.001790, IC=-0.0203

      epoch  46/100: train_loss=0.006091

      epoch  47/100: train_loss=0.006026

      epoch  48/100: train_loss=0.006038

      epoch  49/100: train_loss=0.005989

      epoch  50/100: train_loss=0.006015, val_loss=0.001789, IC=-0.0169

      epoch  51/100: train_loss=0.005992

      epoch  52/100: train_loss=0.005970

      epoch  53/100: train_loss=0.006022

      epoch  54/100: train_loss=0.005995

      epoch  55/100: train_loss=0.006005, val_loss=0.001773, IC=-0.0111

      epoch  56/100: train_loss=0.005978

      epoch  57/100: train_loss=0.006072

      epoch  58/100: train_loss=0.005959

      epoch  59/100: train_loss=0.005976

      epoch  60/100: train_loss=0.005935, val_loss=0.001759, IC=-0.0107

      epoch  61/100: train_loss=0.005959

      epoch  62/100: train_loss=0.005942

      epoch  63/100: train_loss=0.005919

      epoch  64/100: train_loss=0.005913

      epoch  65/100: train_loss=0.005946, val_loss=0.001757, IC=-0.0112

      epoch  66/100: train_loss=0.005928

      epoch  67/100: train_loss=0.005886

      epoch  68/100: train_loss=0.005900

      epoch  69/100: train_loss=0.005917

      epoch  70/100: train_loss=0.006028, val_loss=0.001748, IC=-0.0070

      epoch  71/100: train_loss=0.006339

      epoch  72/100: train_loss=0.005923

      epoch  73/100: train_loss=0.005872

      epoch  74/100: train_loss=0.005878

      epoch  75/100: train_loss=0.006016, val_loss=0.001753, IC=-0.0091

      epoch  76/100: train_loss=0.005888

      epoch  77/100: train_loss=0.005868

      epoch  78/100: train_loss=0.005924

      epoch  79/100: train_loss=0.005883

      epoch  80/100: train_loss=0.005906, val_loss=0.001746, IC=-0.0072

      epoch  81/100: train_loss=0.005939

      epoch  82/100: train_loss=0.005865

      epoch  83/100: train_loss=0.005985

      epoch  84/100: train_loss=0.005871

      epoch  85/100: train_loss=0.005927, val_loss=0.001751, IC=-0.0069

      epoch  86/100: train_loss=0.006356

      epoch  87/100: train_loss=0.005987

      epoch  88/100: train_loss=0.005842

      epoch  89/100: train_loss=0.005930

      epoch  90/100: train_loss=0.005884, val_loss=0.001750, IC=-0.0056

      epoch  91/100: train_loss=0.006033

      epoch  92/100: train_loss=0.005870

      epoch  93/100: train_loss=0.006033

      epoch  94/100: train_loss=0.005984

      epoch  95/100: train_loss=0.005974, val_loss=0.001749, IC=-0.0073

      epoch  96/100: train_loss=0.006014

      epoch  97/100: train_loss=0.005923

      epoch  98/100: train_loss=0.005911

      epoch  99/100: train_loss=0.005914

      epoch 100/100: train_loss=0.005879, val_loss=0.001749, IC=-0.0072

      best_ep=90, IC=-0.0056 (38.7s, 20 checkpoints)

  Fold 1: creating sequences...

    train=21,323 seq across 16 symbols
    val=15,187 seq across 18 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.307718

      epoch   2/100: train_loss=0.135060

      epoch   3/100: train_loss=0.094519

      epoch   4/100: train_loss=0.062858

      epoch   5/100: train_loss=0.046378, val_loss=0.034616, IC=-0.0113

      epoch   6/100: train_loss=0.036229

      epoch   7/100: train_loss=0.029375

      epoch   8/100: train_loss=0.025309

      epoch   9/100: train_loss=0.022223

      epoch  10/100: train_loss=0.020169, val_loss=0.011042, IC=+0.0069

      epoch  11/100: train_loss=0.017729

      epoch  12/100: train_loss=0.016833

      epoch  13/100: train_loss=0.015302

      epoch  14/100: train_loss=0.014358

      epoch  15/100: train_loss=0.013791, val_loss=0.006253, IC=+0.0310

      epoch  16/100: train_loss=0.013008

      epoch  17/100: train_loss=0.012470

      epoch  18/100: train_loss=0.012106

      epoch  19/100: train_loss=0.011564

      epoch  20/100: train_loss=0.010978, val_loss=0.004665, IC=+0.0412

      epoch  21/100: train_loss=0.010654

      epoch  22/100: train_loss=0.010524

      epoch  23/100: train_loss=0.010418

      epoch  24/100: train_loss=0.009897

      epoch  25/100: train_loss=0.009869, val_loss=0.003863, IC=+0.0379

      epoch  26/100: train_loss=0.009656

      epoch  27/100: train_loss=0.009517

      epoch  28/100: train_loss=0.009350

      epoch  29/100: train_loss=0.009123

      epoch  30/100: train_loss=0.008990, val_loss=0.003485, IC=+0.0317

      epoch  31/100: train_loss=0.008993

      epoch  32/100: train_loss=0.008859

      epoch  33/100: train_loss=0.008750

      epoch  34/100: train_loss=0.008647

      epoch  35/100: train_loss=0.008627, val_loss=0.003255, IC=+0.0324

      epoch  36/100: train_loss=0.008476

      epoch  37/100: train_loss=0.008439

      epoch  38/100: train_loss=0.008353

      epoch  39/100: train_loss=0.008695

      epoch  40/100: train_loss=0.008126, val_loss=0.003126, IC=+0.0215

      epoch  41/100: train_loss=0.008076

      epoch  42/100: train_loss=0.008159

      epoch  43/100: train_loss=0.008274

      epoch  44/100: train_loss=0.008063

      epoch  45/100: train_loss=0.008000, val_loss=0.003059, IC=+0.0182

      epoch  46/100: train_loss=0.007991

      epoch  47/100: train_loss=0.007915

      epoch  48/100: train_loss=0.008029

      epoch  49/100: train_loss=0.007852

      epoch  50/100: train_loss=0.007869, val_loss=0.002998, IC=+0.0084

      epoch  51/100: train_loss=0.007791

      epoch  52/100: train_loss=0.007835

      epoch  53/100: train_loss=0.007728

      epoch  54/100: train_loss=0.007738

      epoch  55/100: train_loss=0.008017, val_loss=0.002957, IC=+0.0068

      epoch  56/100: train_loss=0.007715

      epoch  57/100: train_loss=0.007764

      epoch  58/100: train_loss=0.007762

      epoch  59/100: train_loss=0.007634

      epoch  60/100: train_loss=0.007720, val_loss=0.002936, IC=+0.0046

      epoch  61/100: train_loss=0.007748

      epoch  62/100: train_loss=0.007652

      epoch  63/100: train_loss=0.007758

      epoch  64/100: train_loss=0.007624

      epoch  65/100: train_loss=0.007659, val_loss=0.002929, IC=+0.0043

      epoch  66/100: train_loss=0.008473

      epoch  67/100: train_loss=0.007607

      epoch  68/100: train_loss=0.008445

      epoch  69/100: train_loss=0.007572

      epoch  70/100: train_loss=0.007717, val_loss=0.002914, IC=+0.0019

      epoch  71/100: train_loss=0.007636

      epoch  72/100: train_loss=0.007549

      epoch  73/100: train_loss=0.008482

      epoch  74/100: train_loss=0.007576

      epoch  75/100: train_loss=0.007666, val_loss=0.002908, IC=+0.0014

      epoch  76/100: train_loss=0.007455

      epoch  77/100: train_loss=0.007574

      epoch  78/100: train_loss=0.007568

      epoch  79/100: train_loss=0.007542

      epoch  80/100: train_loss=0.007553, val_loss=0.002901, IC=+0.0040

      epoch  81/100: train_loss=0.007536

      epoch  82/100: train_loss=0.007763

      epoch  83/100: train_loss=0.007581

      epoch  84/100: train_loss=0.007464

      epoch  85/100: train_loss=0.007481, val_loss=0.002900, IC=+0.0047

      epoch  86/100: train_loss=0.007535

      epoch  87/100: train_loss=0.007479

      epoch  88/100: train_loss=0.007460

      epoch  89/100: train_loss=0.007745

      epoch  90/100: train_loss=0.008502, val_loss=0.002903, IC=+0.0039

      epoch  91/100: train_loss=0.007495

      epoch  92/100: train_loss=0.007466

      epoch  93/100: train_loss=0.007469

      epoch  94/100: train_loss=0.008416

      epoch  95/100: train_loss=0.007481, val_loss=0.002903, IC=+0.0042

      epoch  96/100: train_loss=0.007421

      epoch  97/100: train_loss=0.007450

      epoch  98/100: train_loss=0.007600

      epoch  99/100: train_loss=0.008555

      epoch 100/100: train_loss=0.007527, val_loss=0.002903, IC=+0.0043

      best_ep=20, IC=+0.0412 (26.7s, 20 checkpoints)

  nlinear: best_epoch=35, IC=+0.0080 (65.3s)

  Best: nlinear @ epoch 35 (IC=+0.0080)
  Saved to ~/ml4t/public-s6-crypto_perps_funding-bt/case_studies/crypto_perps_funding/run_log/training/c15eaaeebcb3/diagnostics

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=27,704 seq across 18 symbols
    val=16,644 seq across 19 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.006079

      epoch   2/100: train_loss=0.005754

      epoch   3/100: train_loss=0.005689

      epoch   4/100: train_loss=0.005632

      epoch   5/100: train_loss=0.005983, val_loss=0.001861, IC=+0.0015

      epoch   6/100: train_loss=0.005498

      epoch   7/100: train_loss=0.005819

      epoch   8/100: train_loss=0.005400

      epoch   9/100: train_loss=0.005729

      epoch  10/100: train_loss=0.005161, val_loss=0.002040, IC=+0.0099

      epoch  11/100: train_loss=0.005000

      epoch  12/100: train_loss=0.005174

      epoch  13/100: train_loss=0.004554

      epoch  14/100: train_loss=0.004321

      epoch  15/100: train_loss=0.004336, val_loss=0.003097, IC=+0.0107

      epoch  16/100: train_loss=0.004022

      epoch  17/100: train_loss=0.003834

      epoch  18/100: train_loss=0.003875

      epoch  19/100: train_loss=0.003943

      epoch  20/100: train_loss=0.003767, val_loss=0.002250, IC=+0.0167

      epoch  21/100: train_loss=0.003565

      epoch  22/100: train_loss=0.003448

      epoch  23/100: train_loss=0.003361

      epoch  24/100: train_loss=0.003294

      epoch  25/100: train_loss=0.003279, val_loss=0.002367, IC=+0.0087

      epoch  26/100: train_loss=0.003216

      epoch  27/100: train_loss=0.003135

      epoch  28/100: train_loss=0.003113

      epoch  29/100: train_loss=0.003113

      epoch  30/100: train_loss=0.003091, val_loss=0.002315, IC=+0.0117

      epoch  31/100: train_loss=0.003040

      epoch  32/100: train_loss=0.003020

      epoch  33/100: train_loss=0.002981

      epoch  34/100: train_loss=0.002924

      epoch  35/100: train_loss=0.002862, val_loss=0.002387, IC=+0.0042

      epoch  36/100: train_loss=0.002832

      epoch  37/100: train_loss=0.002828

      epoch  38/100: train_loss=0.002770

      epoch  39/100: train_loss=0.002786

      epoch  40/100: train_loss=0.002749, val_loss=0.002385, IC=-0.0006

      epoch  41/100: train_loss=0.002747

      epoch  42/100: train_loss=0.002702

      epoch  43/100: train_loss=0.002701

      epoch  44/100: train_loss=0.002702

      epoch  45/100: train_loss=0.002675, val_loss=0.002358, IC=+0.0003

      epoch  46/100: train_loss=0.002625

      epoch  47/100: train_loss=0.002624

      epoch  48/100: train_loss=0.002587

      epoch  49/100: train_loss=0.002604

      epoch  50/100: train_loss=0.002568, val_loss=0.002364, IC=-0.0015

      epoch  51/100: train_loss=0.002519

      epoch  52/100: train_loss=0.002553

      epoch  53/100: train_loss=0.002528

      epoch  54/100: train_loss=0.002530

      epoch  55/100: train_loss=0.002498, val_loss=0.002403, IC=-0.0076

      epoch  56/100: train_loss=0.002550

      epoch  57/100: train_loss=0.002488

      epoch  58/100: train_loss=0.002490

      epoch  59/100: train_loss=0.002459

      epoch  60/100: train_loss=0.002455, val_loss=0.002399, IC=-0.0107

      epoch  61/100: train_loss=0.002432

      epoch  62/100: train_loss=0.002436

      epoch  63/100: train_loss=0.002412

      epoch  64/100: train_loss=0.002412

      epoch  65/100: train_loss=0.002395, val_loss=0.002446, IC=-0.0076

      epoch  66/100: train_loss=0.002387

      epoch  67/100: train_loss=0.002363

      epoch  68/100: train_loss=0.002367

      epoch  69/100: train_loss=0.002383

      epoch  70/100: train_loss=0.002372, val_loss=0.002424, IC=-0.0056

      epoch  71/100: train_loss=0.002357

      epoch  72/100: train_loss=0.002370

      epoch  73/100: train_loss=0.002356

      epoch  74/100: train_loss=0.002329

      epoch  75/100: train_loss=0.002348, val_loss=0.002400, IC=-0.0069

      epoch  76/100: train_loss=0.002334

      epoch  77/100: train_loss=0.002324

      epoch  78/100: train_loss=0.002320

      epoch  79/100: train_loss=0.002325

      epoch  80/100: train_loss=0.002321, val_loss=0.002421, IC=-0.0048

      epoch  81/100: train_loss=0.002306

      epoch  82/100: train_loss=0.002313

      epoch  83/100: train_loss=0.002304

      epoch  84/100: train_loss=0.002302

      epoch  85/100: train_loss=0.002301, val_loss=0.002422, IC=-0.0052

      epoch  86/100: train_loss=0.002302

      epoch  87/100: train_loss=0.002291

      epoch  88/100: train_loss=0.002284

      epoch  89/100: train_loss=0.002290

      epoch  90/100: train_loss=0.002280, val_loss=0.002416, IC=-0.0067

      epoch  91/100: train_loss=0.002298

      epoch  92/100: train_loss=0.002262

      epoch  93/100: train_loss=0.002301

      epoch  94/100: train_loss=0.002283

      epoch  95/100: train_loss=0.002298, val_loss=0.002421, IC=-0.0064

      epoch  96/100: train_loss=0.002285

      epoch  97/100: train_loss=0.002290

      epoch  98/100: train_loss=0.002275

      epoch  99/100: train_loss=0.002284

      epoch 100/100: train_loss=0.002291, val_loss=0.002421, IC=-0.0064

      best_ep=20, IC=+0.0167 (51.4s, 20 checkpoints)

  Fold 1: creating sequences...
    train=21,323 seq across 16 symbols
    val=15,187 seq across 18 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.007588

      epoch   2/100: train_loss=0.007201

      epoch   3/100: train_loss=0.007080

      epoch   4/100: train_loss=0.007338

      epoch   5/100: train_loss=0.006975, val_loss=0.002806, IC=+0.0363

      epoch   6/100: train_loss=0.006972

      epoch   7/100: train_loss=0.006782

      epoch   8/100: train_loss=0.007532

      epoch   9/100: train_loss=0.006538

      epoch  10/100: train_loss=0.006418, val_loss=0.002944, IC=+0.0115

      epoch  11/100: train_loss=0.006297

      epoch  12/100: train_loss=0.006163

      epoch  13/100: train_loss=0.006026

      epoch  14/100: train_loss=0.005845

      epoch  15/100: train_loss=0.005696, val_loss=0.003022, IC=+0.0083

      epoch  16/100: train_loss=0.005587

      epoch  17/100: train_loss=0.006234

      epoch  18/100: train_loss=0.005477

      epoch  19/100: train_loss=0.004790

      epoch  20/100: train_loss=0.004793, val_loss=0.003013, IC=+0.0178

      epoch  21/100: train_loss=0.004431

      epoch  22/100: train_loss=0.004153

      epoch  23/100: train_loss=0.004012

      epoch  24/100: train_loss=0.003973

      epoch  25/100: train_loss=0.003852, val_loss=0.003054, IC=+0.0196

      epoch  26/100: train_loss=0.003775

      epoch  27/100: train_loss=0.003763

      epoch  28/100: train_loss=0.003673

      epoch  29/100: train_loss=0.003644

      epoch  30/100: train_loss=0.003646, val_loss=0.003044, IC=+0.0172

      epoch  31/100: train_loss=0.003576

      epoch  32/100: train_loss=0.003584

      epoch  33/100: train_loss=0.003470

      epoch  34/100: train_loss=0.003348

      epoch  35/100: train_loss=0.003326, val_loss=0.003026, IC=+0.0237

      epoch  36/100: train_loss=0.003274

      epoch  37/100: train_loss=0.003255

      epoch  38/100: train_loss=0.003261

      epoch  39/100: train_loss=0.003224

      epoch  40/100: train_loss=0.003189, val_loss=0.003062, IC=+0.0173

      epoch  41/100: train_loss=0.003120

      epoch  42/100: train_loss=0.003109

      epoch  43/100: train_loss=0.003079

      epoch  44/100: train_loss=0.003059

      epoch  45/100: train_loss=0.003027, val_loss=0.003085, IC=+0.0163

      epoch  46/100: train_loss=0.003047

      epoch  47/100: train_loss=0.002987

      epoch  48/100: train_loss=0.002946

      epoch  49/100: train_loss=0.002939

      epoch  50/100: train_loss=0.002900, val_loss=0.003048, IC=+0.0109

      epoch  51/100: train_loss=0.002872

      epoch  52/100: train_loss=0.002832

      epoch  53/100: train_loss=0.002867

      epoch  54/100: train_loss=0.002799

      epoch  55/100: train_loss=0.002830, val_loss=0.003088, IC=+0.0136

      epoch  56/100: train_loss=0.002808

      epoch  57/100: train_loss=0.002832

      epoch  58/100: train_loss=0.002778

      epoch  59/100: train_loss=0.002703

      epoch  60/100: train_loss=0.002714, val_loss=0.003116, IC=+0.0136

      epoch  61/100: train_loss=0.002726

      epoch  62/100: train_loss=0.002690

      epoch  63/100: train_loss=0.002709

      epoch  64/100: train_loss=0.002717

      epoch  65/100: train_loss=0.002699, val_loss=0.003096, IC=+0.0208

      epoch  66/100: train_loss=0.002700

      epoch  67/100: train_loss=0.002628

      epoch  68/100: train_loss=0.002636

      epoch  69/100: train_loss=0.002626

      epoch  70/100: train_loss=0.002628, val_loss=0.003101, IC=+0.0192

      epoch  71/100: train_loss=0.002643

      epoch  72/100: train_loss=0.002607

      epoch  73/100: train_loss=0.002624

      epoch  74/100: train_loss=0.002612

      epoch  75/100: train_loss=0.002611, val_loss=0.003131, IC=+0.0157

      epoch  76/100: train_loss=0.002565

      epoch  77/100: train_loss=0.002602

      epoch  78/100: train_loss=0.002574

      epoch  79/100: train_loss=0.002597

      epoch  80/100: train_loss=0.002554, val_loss=0.003115, IC=+0.0168

      epoch  81/100: train_loss=0.002601

      epoch  82/100: train_loss=0.002558

      epoch  83/100: train_loss=0.002551

      epoch  84/100: train_loss=0.002557

      epoch  85/100: train_loss=0.002561, val_loss=0.003114, IC=+0.0154

      epoch  86/100: train_loss=0.002557

      epoch  87/100: train_loss=0.002545

      epoch  88/100: train_loss=0.002551

      epoch  89/100: train_loss=0.002550

      epoch  90/100: train_loss=0.002540, val_loss=0.003117, IC=+0.0158

      epoch  91/100: train_loss=0.002528

      epoch  92/100: train_loss=0.002533

      epoch  93/100: train_loss=0.002545

      epoch  94/100: train_loss=0.002538

      epoch  95/100: train_loss=0.002553, val_loss=0.003124, IC=+0.0155

      epoch  96/100: train_loss=0.002535

      epoch  97/100: train_loss=0.002515

      epoch  98/100: train_loss=0.002520

      epoch  99/100: train_loss=0.002551

      epoch 100/100: train_loss=0.002533, val_loss=0.003123, IC=+0.0153

      best_ep=5, IC=+0.0363 (52.1s, 20 checkpoints)

  lstm_h64: best_epoch=5, IC=+0.0191 (103.5s)

  Best: lstm_h64 @ epoch 5 (IC=+0.0191)
  Saved to ~/ml4t/public-s6-crypto_perps_funding-bt/case_studies/crypto_perps_funding/run_log/training/b6f229eb00dc/diagnostics

shape: (80, 6)
┌─────────────┬─────────────┬──────────────────┬───────────────┬─────────────────┬──────────┐
│ label       ┆ config_name ┆ checkpoint_value ┆ training_hash ┆ prediction_hash ┆ complete │
│ ---         ┆ ---         ┆ ---              ┆ ---           ┆ ---             ┆ ---      │
│ str         ┆ str         ┆ i64              ┆ str           ┆ str             ┆ bool     │
╞═════════════╪═════════════╪══════════════════╪═══════════════╪═════════════════╪══════════╡
│ fwd_ret_24h ┆ lstm_h64    ┆ 5                ┆ b6f229eb00dc  ┆ 0b7f49de3527    ┆ true     │
│ fwd_ret_24h ┆ lstm_h64    ┆ 10               ┆ b6f229eb00dc  ┆ 9eb04e1283ce    ┆ true     │
│ fwd_ret_24h ┆ lstm_h64    ┆ 15               ┆ b6f229eb00dc  ┆ 7c5fbb6f7264    ┆ true     │
│ fwd_ret_24h ┆ lstm_h64    ┆ 20               ┆ b6f229eb00dc  ┆ 88b83f7ad6f5    ┆ true     │
│ fwd_ret_24h ┆ lstm_h64    ┆ 25               ┆ b6f229eb00dc  ┆ 497028cabcd7    ┆ true     │
│ …           ┆ …           ┆ …                ┆ …             ┆ …               ┆ …        │
│ fwd_ret_8h  ┆ nlinear     ┆ 80               ┆ 615931c83f63  ┆ c9e57ee94928    ┆ true     │
│ fwd_ret_8h  ┆ nlinear     ┆ 85               ┆ 615931c83f63  ┆ d67e5ca1e6ad    ┆ true     │
│ fwd_ret_8h  ┆ nlinear     ┆ 90               ┆ 615931c83f63  ┆ 05e3b467ec7c    ┆ true     │
│ fwd_ret_8h  ┆ nlinear     ┆ 95               ┆ 615931c83f63  ┆ b29f2d8be8fb    ┆ true     │
│ fwd_ret_8h  ┆ nlinear     ┆ 100              ┆ 615931c83f63  ┆ 0d96f8b3c498    ┆ true     │
└─────────────┴─────────────┴──────────────────┴───────────────┴─────────────────┴──────────┘

## Key takeaways and limitations

- **Eligibility follows the declared cadence, not row adjacency.** A 60-bar window is 60 expected
  8-hour settlements. A window that would cross a settlement missing from the data is dropped,
  which is why `eligible_rows` is smaller than the panel and why that count, not the panel
  height, is the sample size to quote.
- **The linear baseline is the comparison that means something.** NLinear reads the same window,
  in the same order, under the same contract, and has no recurrence at all. An LSTM that does not
  beat it has not shown that recurrence bought anything on this data.
- **Every checkpoint is a model.** Twenty per configuration, each registered as its own
  prediction identity, and selection among them happens in [`13_backtest`](13_backtest.ipynb) on
  validation backtest Sharpe. Reporting the best checkpoint's score as though one model had
  achieved it would be reporting a maximum over twenty draws as a single measurement.
- **The history is short and the folds are few.** This case study's usable perpetual funding
  history supports two validation folds, and a two-layer LSTM with a 64-unit hidden state has far
  more capacity than two folds of an 8-hourly panel can identify. Dropout and the checkpoint
  population are doing the regularization that a longer history would not need as badly.
- **A fixed lookback is a modelling assumption, not a neutral default.** Sixty settlements is
  about twenty days. Any dependence on something that happened before that window is invisible to
  these models by construction, however long the funding cycle they are meant to capture.