# A third way to read the same window

[`09_dl_lstm`](09_dl_lstm.ipynb) put two readings of the 60-settlement window against each other:
NLinear, which applies one linear map to the whole window at once, and an LSTM, which walks the
window one settlement at a time and carries a state. This notebook adds a third, fitted against
the identical request contract so that the comparison is architecture and nothing else.

A **temporal convolutional network** slides a small filter along the window instead of stepping
through it. The filter here is `kernel_size: 3`, so one convolution sees three consecutive
settlements. Stacking convolutions with growing **dilations** - `1, 2, 4, 8`, meaning each
successive block skips one, three, then seven settlements between the positions it combines -
lets a shallow stack reach far back without one filter per lag. Every convolution is **causal**:
it is padded on the left and the padding is trimmed from the right, so the value at a position is
computed only from that position and earlier ones. A model that reads its own future within the
window would score well and mean nothing.

The arithmetic is worth doing once, because it is what the dilation schedule is chosen for. Each
of the four blocks applies two convolutions at its dilation, so a block extends the reach by
`2 x (3 - 1) x d`. Summed over `d` in `1, 2, 4, 8`, the receptive field is
`1 + 4 x (1 + 2 + 4 + 8) = 61` settlements against a declared lookback of 60. **The stack is
sized so the last position sees the entire window**, with one settlement to spare - and a
shorter dilation schedule would leave the earliest part of the window unreachable no matter how
long the lookback said it was.

## Where this differs from the LSTM, and why it might matter here

The two architectures aggregate over time in genuinely different ways, and on this data that is
not a detail.

- The LSTM's prediction is read off the state after the **last** settlement, so information from
  early in the window has to survive being carried through sixty updates to be used.
- This TCN pools its representation by **averaging over all positions** before the output layer.
  Nothing has to survive a recurrence, and a pattern that occurred early in the window
  contributes on the same footing as one that occurred late.

For a premium that mean-reverts on a timescale of days, the two are different hypotheses about
where the signal sits: at the end of the window, or spread across it. Neither is obviously right,
which is the reason to fit both rather than to pick one.

## Same contract, same gaps, same checkpoints

Everything [`09_dl_lstm`](09_dl_lstm.ipynb) establishes about the observation grid applies here
unchanged, because it is the same request contract. The grid is the 8-hour funding settlement
cadence, so a lookback of 60 is about 20 days. A window that would cross a settlement the grid
expects and the data does not have is dropped rather than imputed
(`exclude_windows_crossing_missing_expected_periods`), so `eligible_rows` in the contracts table
below, not the panel height, is the sample the model is fitted on. Training runs 100 epochs with
a checkpoint every 5, and each of the resulting 20 checkpoints is registered as its own
prediction identity.

**Learning objectives.** By the end of this notebook you will be able to:

- Explain what causal padding is for, and what a convolutional sequence model would be measuring
  without it.
- Compute the receptive field of a dilated stack and check it against the declared lookback,
  rather than assuming the two agree.
- State how a convolutional model's time aggregation differs from a recurrent model's, and why
  that is a hypothesis about the data rather than an implementation choice.
- Read a resolved request and say what will be fitted, on how many eligible rows, before any
  fitting happens.

**Book reference:** Chapter 19, convolutional sequence models.

**Prerequisites:** [`03_financial_features`](03_financial_features.ipynb) and
[`04_model_based_features`](04_model_based_features.ipynb) have written the feature matrices, and
[`05_evaluation`](05_evaluation.ipynb) has established the walk-forward folds. The canonical run
uses CUDA; the reduced run in CI does not.

**What it writes:** one training run per configuration and one complete validation prediction set
per checkpoint, grouped under a named population that [`13_backtest`](13_backtest.ipynb) reads.
**Selection happens there, on validation backtest Sharpe.** Nothing here ranks anything.

In [1]:
import os

import polars as pl

from case_studies.crypto_perps_funding.research_workflow import (
    REGRESSION_LABELS,
    declared_contracts,
    freeze_official_model_population,
    model_request_catalog,
    open_study,
    plan_model_catalog,
    plan_specs,
    run_model_plan,
)

In [2]:
EXECUTION_TIER = "canonical"
SUPERSEDES_POPULATION: str = ""
# The generation of this notebook's own checkpoint population that this run replaces, if any.
# Distinct from SUPERSEDES_POPULATION above, which is the case-wide official model population:
# the two are separate declarations and a refit can move either without moving the other.
SUPERSEDES_MODEL_POPULATION: str = ""
WORKSPACE = os.environ.get("ML4T_OUTPUT_DIR", "")
LABELS = REGRESSION_LABELS
PREVIEW_REDUCTIONS = {}
OVERRIDES = {"device": "cuda"}

## 1. Resolve the sequence and checkpoint identities

Nothing is fitted below. The catalog is filtered to `config_prefix="tcn"`, which is what confines
this notebook to the convolutional configurations declared in
`config/training/fwd_ret_8h.yaml` alongside the two that
[`09_dl_lstm`](09_dl_lstm.ipynb) fits.

The contracts table reads `gap_policy` and `lookback` back out of the frozen specification rather
than restating the configuration file, so it cannot describe something other than what the fit
will use. Check the lookback against the receptive field computed in the header before running
anything: if a future edit shortens the dilation schedule, the two stop agreeing and the window
grows a region the model cannot see.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)
official_population = (
    freeze_official_model_population(study, supersedes=SUPERSEDES_POPULATION or None)
    if EXECUTION_TIER == "canonical"
    else None
)
requests = model_request_catalog("deep_learning", labels=LABELS, config_prefix="tcn")
requests

shape: (1, 3)
┌───────────────┬────────────┬─────────────┐
│ family        ┆ label      ┆ config_name │
│ ---           ┆ ---        ┆ ---         │
│ str           ┆ str        ┆ str         │
╞═══════════════╪════════════╪═════════════╡
│ deep_learning ┆ fwd_ret_8h ┆ tcn         │
└───────────────┴────────────┴─────────────┘

In [4]:
plan = plan_model_catalog(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides=OVERRIDES,
    preview_reductions=PREVIEW_REDUCTIONS,
)
# Sequence eligibility follows from the resolved gap policy and lookback, so read both from the
# frozen specification instead of restating the configuration file here.
resolved_preprocessing = [spec["computation"]["preprocessing"] for spec in plan_specs(plan)]
contracts = declared_contracts(plan).with_columns(
    pl.Series("gap_policy", [step["gap_policy"] for step in resolved_preprocessing]),
    pl.Series("lookback", [step["lookback"] for step in resolved_preprocessing]),
)
contracts.select(
    "label",
    "config_name",
    "gap_policy",
    "lookback",
    "checkpoint_value",
    "eligible_rows",
    "training_hash",
)

shape: (20, 7)
┌────────────┬─────────────┬───────────────┬──────────┬──────────────┬──────────────┬──────────────┐
│ label      ┆ config_name ┆ gap_policy    ┆ lookback ┆ checkpoint_v ┆ eligible_row ┆ training_has │
│ ---        ┆ ---         ┆ ---           ┆ ---      ┆ alue         ┆ s            ┆ h            │
│ str        ┆ str         ┆ str           ┆ i64      ┆ ---          ┆ ---          ┆ ---          │
│            ┆             ┆               ┆          ┆ i64          ┆ i64          ┆ str          │
╞════════════╪═════════════╪═══════════════╪══════════╪══════════════╪══════════════╪══════════════╡
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 5            ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 10           ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 15           ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 20           ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 25           ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ …          ┆ …           ┆ …             ┆ …        ┆ …            ┆ …            ┆ …            │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 80           ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 85           ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 90           ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 95           ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
│ fwd_ret_8h ┆ tcn         ┆ exclude_windo ┆ 60       ┆ 100          ┆ 31885        ┆ 87c30dba216a │
│            ┆             ┆ ws_crossing_m ┆          ┆              ┆              ┆              │
│            ┆             ┆ issi…         ┆          ┆              ┆              ┆              │
└────────────┴─────────────┴───────────────┴──────────┴──────────────┴──────────────┴──────────────┘

The complete case-wide population is recorded before the first fit, so a member that later
fails to train cannot quietly disappear from the population it was declared in. This notebook
produces one slice of it, and that slice must lie inside the declaration.

In [5]:
if official_population is not None:
    outside = set(plan.expected_prediction_hashes) - set(official_population.members)
    if outside:
        raise RuntimeError(
            f"{len(outside)} declared checkpoints lie outside the official model population"
        )

## 2. Execute the declared population

Each configuration is fitted on each fold, a checkpoint is persisted every fifth epoch, and one
complete validation prediction set is registered per checkpoint. The completeness check is not a
formality: a prediction set covering most of its fold's eligible keys is a different sample, not
a slightly worse result, and comparing it against a complete one in the backtest would be
comparing two models measured on different data. The run raises rather than publishing one.

In [6]:
execution = run_model_plan(
    plan,
    supersedes=SUPERSEDES_MODEL_POPULATION or None,
    population_name="crypto-tcn-validation-predictions-v1"
    if EXECUTION_TIER == "canonical"
    else None,
)
catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if (
    catalog.height != len(plan.expected_prediction_hashes)
    or catalog.filter(~pl.col("complete")).height
):
    raise RuntimeError("TCN checkpoint population is incomplete")
catalog.select(
    "label",
    "config_name",
    "checkpoint_value",
    "training_hash",
    "prediction_hash",
    "complete",
)

Fold-major CV: 2 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=21,349 seq across 16 symbols
    val=15,203 seq across 18 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.095258

      epoch   2/100: train_loss=0.008796

      epoch   3/100: train_loss=0.005192

      epoch   4/100: train_loss=0.003526

      epoch   5/100: train_loss=0.003566, val_loss=0.002045, IC=+0.0211

      epoch   6/100: train_loss=0.003297

      epoch   7/100: train_loss=0.003332

      epoch   8/100: train_loss=0.003076

      epoch   9/100: train_loss=0.002962

      epoch  10/100: train_loss=0.003096, val_loss=0.001675, IC=+0.0069

      epoch  11/100: train_loss=0.003076

      epoch  12/100: train_loss=0.002965

      epoch  13/100: train_loss=0.002613

      epoch  14/100: train_loss=0.002522

      epoch  15/100: train_loss=0.002555, val_loss=0.001256, IC=+0.0097

      epoch  16/100: train_loss=0.002544

      epoch  17/100: train_loss=0.002484

      epoch  18/100: train_loss=0.002615

      epoch  19/100: train_loss=0.002886

      epoch  20/100: train_loss=0.002600, val_loss=0.001480, IC=-0.0086

      epoch  21/100: train_loss=0.002365

      epoch  22/100: train_loss=0.002392

      epoch  23/100: train_loss=0.002460

      epoch  24/100: train_loss=0.002447

      epoch  25/100: train_loss=0.002301, val_loss=0.003596, IC=-0.0131

      epoch  26/100: train_loss=0.002598

      epoch  27/100: train_loss=0.002811

      epoch  28/100: train_loss=0.002612

      epoch  29/100: train_loss=0.002300

      epoch  30/100: train_loss=0.002208, val_loss=0.001851, IC=-0.0073

      epoch  31/100: train_loss=0.002270

      epoch  32/100: train_loss=0.002194

      epoch  33/100: train_loss=0.002261

      epoch  34/100: train_loss=0.002361

      epoch  35/100: train_loss=0.002235, val_loss=0.001332, IC=-0.0008

      epoch  36/100: train_loss=0.002203

      epoch  37/100: train_loss=0.002196

      epoch  38/100: train_loss=0.002224

      epoch  39/100: train_loss=0.002270

      epoch  40/100: train_loss=0.002152, val_loss=0.001135, IC=-0.0048

      epoch  41/100: train_loss=0.002359

      epoch  42/100: train_loss=0.002215

      epoch  43/100: train_loss=0.002228

      epoch  44/100: train_loss=0.002184

      epoch  45/100: train_loss=0.002234, val_loss=0.001640, IC=-0.0048

      epoch  46/100: train_loss=0.002140

      epoch  47/100: train_loss=0.002093

      epoch  48/100: train_loss=0.002207

      epoch  49/100: train_loss=0.002094

      epoch  50/100: train_loss=0.002089, val_loss=0.001363, IC=+0.0030

      epoch  51/100: train_loss=0.002130

      epoch  52/100: train_loss=0.002133

      epoch  53/100: train_loss=0.002097

      epoch  54/100: train_loss=0.002075

      epoch  55/100: train_loss=0.002080, val_loss=0.001089, IC=+0.0005

      epoch  56/100: train_loss=0.002074

      epoch  57/100: train_loss=0.002104

      epoch  58/100: train_loss=0.002111

      epoch  59/100: train_loss=0.002056

      epoch  60/100: train_loss=0.002084, val_loss=0.001297, IC=-0.0040

      epoch  61/100: train_loss=0.002100

      epoch  62/100: train_loss=0.002069

      epoch  63/100: train_loss=0.002127

      epoch  64/100: train_loss=0.002044

      epoch  65/100: train_loss=0.002093, val_loss=0.001289, IC=-0.0010

      epoch  66/100: train_loss=0.001977

      epoch  67/100: train_loss=0.002075

      epoch  68/100: train_loss=0.002056

      epoch  69/100: train_loss=0.002048

      epoch  70/100: train_loss=0.002067, val_loss=0.001101, IC=+0.0053

      epoch  71/100: train_loss=0.002142

      epoch  72/100: train_loss=0.002060

      epoch  73/100: train_loss=0.002008

      epoch  74/100: train_loss=0.002035

      epoch  75/100: train_loss=0.002057, val_loss=0.001079, IC=+0.0049

      epoch  76/100: train_loss=0.002001

      epoch  77/100: train_loss=0.002111

      epoch  78/100: train_loss=0.002093

      epoch  79/100: train_loss=0.002061

      epoch  80/100: train_loss=0.002061, val_loss=0.001388, IC=-0.0057

      epoch  81/100: train_loss=0.002093

      epoch  82/100: train_loss=0.002050

      epoch  83/100: train_loss=0.002022

      epoch  84/100: train_loss=0.001985

      epoch  85/100: train_loss=0.002016, val_loss=0.001253, IC=-0.0027

      epoch  86/100: train_loss=0.002004

      epoch  87/100: train_loss=0.002034

      epoch  88/100: train_loss=0.002020

      epoch  89/100: train_loss=0.002014

      epoch  90/100: train_loss=0.002014, val_loss=0.001131, IC=+0.0013

      epoch  91/100: train_loss=0.002035

      epoch  92/100: train_loss=0.001993

      epoch  93/100: train_loss=0.001966

      epoch  94/100: train_loss=0.002023

      epoch  95/100: train_loss=0.002041, val_loss=0.001219, IC=-0.0025

      epoch  96/100: train_loss=0.002007

      epoch  97/100: train_loss=0.002022

      epoch  98/100: train_loss=0.002002

      epoch  99/100: train_loss=0.001986

      epoch 100/100: train_loss=0.002059, val_loss=0.001268, IC=-0.0057

      best_ep=5, IC=+0.0211 (125.1s, 20 checkpoints)

  Fold 1: creating sequences...

    train=27,756 seq across 18 symbols
    val=16,682 seq across 19 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.021552

      epoch   2/100: train_loss=0.005580

      epoch   3/100: train_loss=0.005023

      epoch   4/100: train_loss=0.004576

      epoch   5/100: train_loss=0.005693, val_loss=0.003963, IC=-0.0076

      epoch   6/100: train_loss=0.004154

      epoch   7/100: train_loss=0.004379

      epoch   8/100: train_loss=0.004091

      epoch   9/100: train_loss=0.003516

      epoch  10/100: train_loss=0.003940, val_loss=0.001058, IC=-0.0037

      epoch  11/100: train_loss=0.003531

      epoch  12/100: train_loss=0.003730

      epoch  13/100: train_loss=0.003157

      epoch  14/100: train_loss=0.003116

      epoch  15/100: train_loss=0.002926, val_loss=0.001144, IC=-0.0054

      epoch  16/100: train_loss=0.002881

      epoch  17/100: train_loss=0.003090

      epoch  18/100: train_loss=0.003247

      epoch  19/100: train_loss=0.002757

      epoch  20/100: train_loss=0.002702, val_loss=0.001026, IC=-0.0065

      epoch  21/100: train_loss=0.002669

      epoch  22/100: train_loss=0.002745

      epoch  23/100: train_loss=0.002497

      epoch  24/100: train_loss=0.002859

      epoch  25/100: train_loss=0.002521, val_loss=0.000994, IC=-0.0012

      epoch  26/100: train_loss=0.002545

      epoch  27/100: train_loss=0.002488

      epoch  28/100: train_loss=0.002464

      epoch  29/100: train_loss=0.002714

      epoch  30/100: train_loss=0.002884, val_loss=0.000850, IC=-0.0015

      epoch  31/100: train_loss=0.002558

      epoch  32/100: train_loss=0.002559

      epoch  33/100: train_loss=0.002676

      epoch  34/100: train_loss=0.002429

      epoch  35/100: train_loss=0.002561, val_loss=0.000785, IC=-0.0067

      epoch  36/100: train_loss=0.002510

      epoch  37/100: train_loss=0.002343

      epoch  38/100: train_loss=0.002343

      epoch  39/100: train_loss=0.002331

      epoch  40/100: train_loss=0.002271, val_loss=0.000868, IC=-0.0060

      epoch  41/100: train_loss=0.002258

      epoch  42/100: train_loss=0.002261

      epoch  43/100: train_loss=0.002280

      epoch  44/100: train_loss=0.002179

      epoch  45/100: train_loss=0.002138, val_loss=0.001022, IC=-0.0042

      epoch  46/100: train_loss=0.002353

      epoch  47/100: train_loss=0.002201

      epoch  48/100: train_loss=0.002152

      epoch  49/100: train_loss=0.002262

      epoch  50/100: train_loss=0.002245, val_loss=0.001325, IC=-0.0114

      epoch  51/100: train_loss=0.002242

      epoch  52/100: train_loss=0.002140

      epoch  53/100: train_loss=0.002194

      epoch  54/100: train_loss=0.002086

      epoch  55/100: train_loss=0.002093, val_loss=0.000830, IC=-0.0096

      epoch  56/100: train_loss=0.002308

      epoch  57/100: train_loss=0.002065

      epoch  58/100: train_loss=0.002150

      epoch  59/100: train_loss=0.002152

      epoch  60/100: train_loss=0.002184, val_loss=0.000721, IC=-0.0085

      epoch  61/100: train_loss=0.002068

      epoch  62/100: train_loss=0.002160

      epoch  63/100: train_loss=0.002176

      epoch  64/100: train_loss=0.002130

      epoch  65/100: train_loss=0.002148, val_loss=0.000838, IC=-0.0114

      epoch  66/100: train_loss=0.002114

      epoch  67/100: train_loss=0.002164

      epoch  68/100: train_loss=0.002120

      epoch  69/100: train_loss=0.002077

      epoch  70/100: train_loss=0.002088, val_loss=0.000727, IC=-0.0079

      epoch  71/100: train_loss=0.002106

      epoch  72/100: train_loss=0.002077

      epoch  73/100: train_loss=0.002042

      epoch  74/100: train_loss=0.002050

      epoch  75/100: train_loss=0.002076, val_loss=0.000699, IC=-0.0094

      epoch  76/100: train_loss=0.002057

      epoch  77/100: train_loss=0.001982

      epoch  78/100: train_loss=0.002065

      epoch  79/100: train_loss=0.002041

      epoch  80/100: train_loss=0.002038, val_loss=0.000698, IC=-0.0094

      epoch  81/100: train_loss=0.002081

      epoch  82/100: train_loss=0.002085

      epoch  83/100: train_loss=0.002011

      epoch  84/100: train_loss=0.002030

      epoch  85/100: train_loss=0.002020, val_loss=0.000699, IC=-0.0094

      epoch  86/100: train_loss=0.001952

      epoch  87/100: train_loss=0.002000

      epoch  88/100: train_loss=0.002007

      epoch  89/100: train_loss=0.002017

      epoch  90/100: train_loss=0.002055, val_loss=0.000715, IC=-0.0093

      epoch  91/100: train_loss=0.002002

      epoch  92/100: train_loss=0.002070

      epoch  93/100: train_loss=0.001956

      epoch  94/100: train_loss=0.001991

      epoch  95/100: train_loss=0.002022, val_loss=0.000698, IC=-0.0095

      epoch  96/100: train_loss=0.001990

      epoch  97/100: train_loss=0.002006

      epoch  98/100: train_loss=0.001975

      epoch  99/100: train_loss=0.002032

      epoch 100/100: train_loss=0.001985, val_loss=0.000692, IC=-0.0090

      best_ep=25, IC=-0.0012 (168.7s, 20 checkpoints)

  tcn: best_epoch=5, IC=+0.0069 (293.8s)

  Best: tcn @ epoch 5 (IC=+0.0069)
  Saved to ~/ml4t/public/case_studies/crypto_perps_funding/run_log/training/87c30dba216a/diagnostics

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

direction AUC against fwd_dir_8h not computed: cannot align join key 'timestamp': predictions are Datetime(time_unit='us', time_zone='UTC'), direction label 'fwd_dir_8h' is Datetime(time_unit='ms', time_zone='UTC')

shape: (20, 6)
┌────────────┬─────────────┬──────────────────┬───────────────┬─────────────────┬──────────┐
│ label      ┆ config_name ┆ checkpoint_value ┆ training_hash ┆ prediction_hash ┆ complete │
│ ---        ┆ ---         ┆ ---              ┆ ---           ┆ ---             ┆ ---      │
│ str        ┆ str         ┆ i64              ┆ str           ┆ str             ┆ bool     │
╞════════════╪═════════════╪══════════════════╪═══════════════╪═════════════════╪══════════╡
│ fwd_ret_8h ┆ tcn         ┆ 5                ┆ 87c30dba216a  ┆ ffb2ff58b757    ┆ true     │
│ fwd_ret_8h ┆ tcn         ┆ 10               ┆ 87c30dba216a  ┆ 160150924514    ┆ true     │
│ fwd_ret_8h ┆ tcn         ┆ 15               ┆ 87c30dba216a  ┆ a685cb22fd9e    ┆ true     │
│ fwd_ret_8h ┆ tcn         ┆ 20               ┆ 87c30dba216a  ┆ a0ab2aa0f43c    ┆ true     │
│ fwd_ret_8h ┆ tcn         ┆ 25               ┆ 87c30dba216a  ┆ 89b6bda1c63a    ┆ true     │
│ …          ┆ …           ┆ …                ┆ …             ┆ …               ┆ …        │
│ fwd_ret_8h ┆ tcn         ┆ 80               ┆ 87c30dba216a  ┆ 8b7051a7e6f1    ┆ true     │
│ fwd_ret_8h ┆ tcn         ┆ 85               ┆ 87c30dba216a  ┆ a7119eb2a40b    ┆ true     │
│ fwd_ret_8h ┆ tcn         ┆ 90               ┆ 87c30dba216a  ┆ c640bf944d15    ┆ true     │
│ fwd_ret_8h ┆ tcn         ┆ 95               ┆ 87c30dba216a  ┆ a72622c5b43b    ┆ true     │
│ fwd_ret_8h ┆ tcn         ┆ 100              ┆ 87c30dba216a  ┆ f13c3a0f0fbe    ┆ true     │
└────────────┴─────────────┴──────────────────┴───────────────┴─────────────────┴──────────┘

## Key takeaways and limitations

- **The receptive field is a property of the architecture, not of the lookback.** Four blocks at
  dilations 1, 2, 4, 8 with kernel 3 reach 61 settlements; the lookback is 60. Change either
  without checking the other and the model quietly stops seeing part of the window it is handed.
- **Causal padding is what makes the number honest.** Without trimming the right-hand padding,
  each position would be computed partly from later ones, and the validation score would be
  measuring a model that had seen the answer.
- **Averaging over positions is a hypothesis.** This TCN pools its representation across the whole
  window, so it treats a pattern early in the window as no less usable than one at the end. The
  LSTM in [`09_dl_lstm`](09_dl_lstm.ipynb) does the opposite. Which is right is an empirical
  question about where in the window the premium's information sits, and the backtest is where it
  gets answered.
- **Batch normalization pools across windows, not across time within one.** The statistics used to
  normalize a training window come from the other windows in its batch, which may be
  chronologically later within the same fold. Fold boundaries are respected, so no validation
  information reaches training - but the training objective is not a pure per-window causal
  function, and that is worth knowing before attributing a result entirely to the convolutions.
- **Two folds is what the history supports.** The reach of the dilation schedule is not the
  binding constraint on what this model can learn here; the length of the usable perpetual
  funding record is.