# Multi-Agent Research

**Docker image**: `ml4t`

One research agent gives one answer with no way to tell a considered probability from a
lucky search. Running several is the cheapest available check, and it only works if they
disagree: three agents returning the same number are one agent charged for three times.

This notebook runs three copies of the agent from
[`04_research_agent`](04_research_agent.ipynb) on one question, in parallel, and looks at
what came back. Nothing distinguishes the three except their identifiers, which is the point:
no roles, no settings, nothing assigned to make them differ. Two things can still make them
differ anyway - the model samples its replies, and each agent's searches return different
documents - and this run separates neither.

**What this run establishes, and what it does not.** The numbers below are one live capture
(`claude-sonnet-4`, Tavily search) taken on 2026-06-09 and replayed by default, so the
figures are the same whenever the notebook runs. One capture on one question is a
demonstration that a panel of identical agents is not degenerate. It is not an experiment:
nothing here varies temperature, retrieval, or question wording independently, so the spread
cannot be attributed to any of them. And the market's own probability was in every prompt,
which rules out reading the agents' closeness to the market as skill.

**Learning Objectives**:
- Run several agents concurrently and keep each one's conversation separately attributable
- Read a panel's timelines to tell genuine disagreement from one agent run three times
- Exclude agents that never produced a forecast before aggregating
- Show how far the assumed correlation moves an aggregate, relative to how far the agents
  are apart
- Say what a single dated capture of a multi-agent run does and does not establish

**Book Reference**: Chapter 24, Section 24.7 (Multi-Agent Forecasting Systems -
Agent Ensemble)

**Prerequisites**: [`04_research_agent`](04_research_agent.ipynb) (the agent),
[`05_aggregation_math`](05_aggregation_math.ipynb) (the aggregation rules).

In [2]:
"""Multi-Agent Research - parallel agents on one shared question."""

import sys

from utils.paths import get_chapter_dir

sys.path.insert(0, str(get_chapter_dir(24)))

from concurrent.futures import ThreadPoolExecutor, as_completed

import polars as pl
from agent_fixtures import get_chapter_clear_question
from agent_observability import (
    TRACES_DIR,
    RunTrace,
    merge_calls,
    replay_llm_calls,
    show_agents,
    trace_llm,
)
from agent_pipeline import neyman_extremize, neyman_extremize_weighted
from agent_providers import TokenUsage, create_llm_client
from agent_research import ResearchAgent, format_agent_summary
from agent_schemas import AgentForecastArtifact
from agent_tools import create_search_client

In [3]:
# RUN_LIVE=False (the default) replays the pinned trace named in PINNED_TRACE:
# the notebook reloads that saved run and makes no API calls, so the outputs are
# stable and match the chapter. Set RUN_LIVE=True to forecast a current question
# live; that path needs API keys and produces different numbers.
RUN_LIVE = False
PINNED_TRACE = "06_multi_agent_research_20260609T141413Z_9fc4a2655471.json"

# Live-run settings (ignored when RUN_LIVE=False). Blank reads the provider from
# your .env (LLM_PROVIDER + LLM_API_KEY); the captured run used claude-sonnet-4.
# Set LLM_PROVIDER="openrouter" with LLM_MODEL="deepseek/deepseek-chat-v3.1" to
# drive an open model instead (raise MAX_STEPS for open models, which tend to
# issue more searches before forecasting). LLM_PROVIDER="mock" is a deterministic
# CI smoke-test only and does not reproduce the captured forecasts.
LLM_PROVIDER = ""
N_AGENTS = 3
MAX_STEPS = 5
MAX_SEARCH_RESULTS = 5

## Setup

All three agents share one model client and one search client. Each gets a distinct
`agent_id` and nothing else: the same prompt, the same tools, the same sampling temperature.
Nothing is built in to make them disagree. Two channels remain open: the model's own
sampling, and the different documents each agent's searches return. The timelines below show
the second; nothing here separates the two.

The question is `CHAPTER_CLEAR_QUESTION` from `agent_fixtures.py`, *"Will the US enter a
recession by the end of 2026?"*, carrying the prediction-market probability recorded on
2026-06-09.

**That market probability was included in every prompt.** It is passed to `agent.run` as
`market_price` below, so each agent saw the market's answer before it searched. That makes
the comparison between the agents and the market circular, and it is why the market line in
the chart further down is labelled as context rather than as a benchmark. A run designed to
test the agents against the market would withhold it, as
[`04_research_agent`](04_research_agent.ipynb) does.

In [4]:
if RUN_LIVE:
    llm = create_llm_client(LLM_PROVIDER)
    search = create_search_client()
    question = get_chapter_clear_question()
    provider_name = llm.model_name
    n_agents = N_AGENTS
else:
    # Replay: load the pinned trace and rebuild the question it forecast.
    pinned_run = RunTrace.load(TRACES_DIR / PINNED_TRACE)
    question = pinned_run.question_obj()
    provider_name = pinned_run.provider
    n_agents = len(pinned_run.agents)

print(f"Mode:         {'LIVE' if RUN_LIVE else 'REPLAY (pinned 2026-06-09 trace)'}")
print(f"Provider:     {provider_name}")
print(f"Question:     {question.question}")
print(f"Market p_yes: {question.current_market_price}")
print(f"Agents:       {n_agents}")

Mode:         REPLAY (pinned 2026-06-09 trace)
Provider:     claude-sonnet-4-20250514
Question:     Will the US enter a recession by the end of 2026?
Market p_yes: 0.175
Agents:       3

## Running Agents in Parallel

`ThreadPoolExecutor` runs agents concurrently. Each agent independently
decides what to search and when to forecast.

In [5]:
def run_agent(agent_id: str):
    """Run a single research agent under its own tracer.

    The pool shares one `llm` and one `search` client across worker threads,
    so thread safety here depends on those providers being safe under
    concurrent calls. Anthropic and Tavily clients are; if you swap in a
    provider that is not, construct the client inside this function.

    Each agent wraps the shared client in its own `TracingLLMClient` labeled
    with the `agent_id`. That records every prompt the agent sent and every
    raw response it received - the full conversation, not just the parsed
    forecast - and a per-agent tracer keeps the capture thread-safe and
    correctly attributed. We merge the call logs afterward.
    """
    tracer = trace_llm(llm, label=agent_id)
    agent = ResearchAgent(
        llm=tracer,
        search=search,
        agent_id=agent_id,
        max_steps=MAX_STEPS,
        max_search_results=MAX_SEARCH_RESULTS,
    )
    return agent.run(question, market_price=None), tracer


artifacts: list[AgentForecastArtifact] = []

if RUN_LIVE:
    tracers = []
    with ThreadPoolExecutor(max_workers=N_AGENTS) as pool:
        futures = {pool.submit(run_agent, f"agent_{i}"): i for i in range(N_AGENTS)}
        for future in as_completed(futures):
            artifact, tracer = future.result()
            artifacts.append(artifact)
            tracers.append(tracer)
    llm_calls = merge_calls(*tracers)
else:
    # Replay: rehydrate the saved artifacts and the raw model conversation. The
    # display cells below cannot tell these apart from a live run's outputs.
    artifacts = pinned_run.agent_artifacts()
    llm_calls = pinned_run.call_log()

# Sort by agent_id for consistent display
artifacts.sort(key=lambda a: a.agent_id)

## What Each Agent Returned

Probability, confidence, sentiment, and how much evidence each one gathered getting there.
The last two columns are worth as much as the first: two agents landing on the same
probability after two searches and after six searches did not do the same thing.

In [6]:
total_tokens = TokenUsage()
for a in artifacts:
    total_tokens = total_tokens + a.token_usage

panel_df = pl.DataFrame(
    [
        {
            "agent_id": a.agent_id,
            "status": a.status,
            "p_yes": round(a.p_yes, 3) if a.p_yes is not None else None,
            "confidence": round(a.confidence, 3),
            "sentiment": a.sentiment.value,
            "queries": a.search_queries_made,
            "sources": a.sources_consulted,
        }
        for a in artifacts
    ]
)
print(f"Market p_yes (Polymarket):  {question.current_market_price:.2f}")
print(f"Total agent tokens:         {total_tokens.total_tokens:,}\n")
panel_df

Market p_yes (Polymarket):  0.17
Total agent tokens:         57,908

shape: (3, 7)
┌──────────┬────────────────┬───────┬────────────┬──────────────────┬─────────┬─────────┐
│ agent_id ┆ status         ┆ p_yes ┆ confidence ┆ sentiment        ┆ queries ┆ sources │
│ ---      ┆ ---            ┆ ---   ┆ ---        ┆ ---              ┆ ---     ┆ ---     │
│ str      ┆ str            ┆ f64   ┆ f64        ┆ str              ┆ i64     ┆ i64     │
╞══════════╪════════════════╪═══════╪════════════╪══════════════════╪═════════╪═════════╡
│ agent_0  ┆ legacy_capture ┆ 0.12  ┆ 0.76       ┆ strongly_bearish ┆ 3       ┆ 15      │
│ agent_1  ┆ legacy_capture ┆ 0.22  ┆ 0.56       ┆ bearish          ┆ 3       ┆ 15      │
│ agent_2  ┆ legacy_capture ┆ 0.22  ┆ 0.56       ┆ bearish          ┆ 3       ┆ 15      │
└──────────┴────────────────┴───────┴────────────┴──────────────────┴─────────┴─────────┘

## Reading the Agents, Not the Aggregate

The table gives each agent's answer and none of its reasoning. `show_agents` renders the full
captured timeline for all three: every query, the documents it returned with title, date, URL
and a snippet, and the untruncated rationale, key findings and uncertainties. Each artifact
carries this in its `traces`, the `AgentTrace` records built in
[`04_research_agent`](04_research_agent.ipynb).

Read side by side, the timelines answer the question the bar chart cannot. Three agents
reaching similar numbers by different search paths is three observations. Three agents
pulling the same documents and reasoning in step is one observation printed three times, and
aggregating it produces confidence that nothing earned. The second case is what a panel of
identical agents drifts toward, and it is worth checking before any aggregation is trusted.

In [7]:
print(show_agents(artifacts))

==============================================================================
  AGENT_0  ·  p_yes=0.12  status=legacy_capture  confidence=0.76  sentiment=strongly_bearish  evidence=high
  searches=3  sources=15  tokens=12,662
==============================================================================
  Step 1 · SEARCH  "US GDP growth forecast 2025 2026 recession indicators economic outlook"
      1. [?] U.S. outlook for 2026 - Indiana Business Research Center
         https://www.ibrc.indiana.edu/ibr/2025/outlook/national.html
         The IBR is a publication of the Indiana Business Research Center at
         IU's Kelley School of Business. *Recent developments in the U.S. and
         global economy present a complex and evolving picture for
         policymakers and business leaders. While our current readings of
         headline growth rema…
      2. [?] Economic Outlook U.S. Q2 2026: Curb Your Enthusia
         https://www.spglobal.com/ratings/en/regulatory/article/economic-outlook-us-q2-2026-curb-your-enthusiasm-s101676533
         [Current Oil Price Surge To Weigh On Growth](https://www.spglobal.com
         /ratings/en/regulatory/article/economic-outlook-us-q2-2026-curb-your-
         enthusiasm-s101676533). Before the war broke out, we were expecting
         to increase our growth forecast for this year closer to 2.5% on
         higher-tha…
      3. [?] US Economic Forecast Q1 2026 | Deloitte Insights
         https://www.deloitte.com/us/en/insights/topics/economy/us-economic-forecast/united-states-outlook-analysis.html
         This reflects the sizable capital expenditure plans that AI
         “hyperscalers” have announced for this
         year.[4](https://www.deloitte.com/us/en/insights/topics/economy/us-
         economic-forecast/united-states-outlook-analysis.html#endnote-4)We
         now expect real business investment to grow by…
      4. [?] The Budget and Economic Outlook: 2026 to 2036
         https://www.cbo.gov/publication/62105
         Real GDP growth in 2026 is projected to be stronger in the current
         projections, partly because of the effects of the 2025 reconciliation
         act. In
      5. [?] United States GDP Growth Rate - Trading Economics
         https://tradingeconomics.com/united-states/gdp-growth
         [](https://tradingeconomics.com/united-states/gdp-growth).
         [](https://tradingeconomics.com/united-states/gdp-growth).
         [Markets](https://tradingeconomics.com/united-states/gdp-growth#).
         [Forecasts](https://tradingeconomics.com/united-states/gdp-growth#).
         [](https://tradingeconomic…
  Step 2 · SEARCH  "US recession probability 2025 2026 NBER recession indicators economic risks"
      1. [?] [PDF] Probability of US Recession Predicted by Treasury Spread
         https://www.newyorkfed.org/medialibrary/media/research/capital_markets/prob_rec.pdf
         Probability of US Recession Predicted by Treasury Spread* Treasury
         Spread: 10 yr bond rate-3 month bill rate Monthly Average (Percent)
         1959 1961 1963 1965 1967 1969 1971 1973 1975 1977 1979 1981 1983 1985
         1987 1989 1991 1993 1995 1997 1999 2001 2003 2005 2007 2009 2011 2013
         2015…
      2. [?] US Recession Probability 2025 – Sahm Rule, Yield Curve & NBER ...
         https://www.jvinvest.ai/economics
         Track US recession risk in real-time: Sahm Rule at 0.5%, yield curve
         analysis, NBER probability models. Free charts & data updated daily.
      3. [?] U.S. Recession Probabilities (1967-2026) - Macrotrends
         https://www.macrotrends.net/3084/us-recession-probabilities
         ## U.S. Recession Probabilities (1967-2026). Markets Metals Energy
         Commodities Interest Rates Exchange Rates Economy. Inflation Rate
         Unemployment National Debt Debt/GDP Housing Starts Initial Claims
         Retail Sales Industrial Prod Durable Goods. # **U.S. Recession
         Probabilities:** 0…
      4. [?] 6 Key Recession Indicators To Watch for in 2025 - Chase Bank
         https://www.chase.com/personal/investments/learning-and-insights/article/what-are-recession-indicators
         The NBER doesn't have a set formula to determine if the US is in a
         recession, but it does use the following six key economic indicators
         to help identify
      5. [?] The Big Four Recession Indicators - dshort - Advisor Perspectives
         https://www.advisorperspectives.com/dshort/updates/2026/06/05/the-big-four-recession-indicators
         The chart and table below illustrate the performance of the generic
         big four since the end of the most recent recession (2020). The NBER
  Step 3 · SEARCH  "Federal Reserve interest rates 2025 2026 monetary policy inflation unemployment current economic conditions"
      1. [?] Fed Outlook 2026: Rate Forecasts and Fixed Income Strategies
         https://www.ishares.com/us/insights/fed-outlook-2026-interest-rate-forecast
         We believe the most likely path for Fed policy in 2026 is for the
         central bank to bring rates down from the current range of 3.50% to
         3.75%
      2. [?] Minutes of the Federal Open Market Committee
         https://www.federalreserve.gov/monetarypolicy/fomcminutes20250917.htm
         In their consideration of monetary policy at this meeting,
         participants noted that inflation had risen recently and remained
         somewhat elevated,
      3. [?] The Economic Outlook and Monetary Policy – April 1, 2026
         https://www.stlouisfed.org/from-the-president/remarks/2026/economic-outlook-monetary-policy-aei
         A baseline scenario for 2026 has real GDP growing close to potential,
         the unemployment rate holding around its current level, and core
         inflation
      4. [?] Minutes of the Federal Open Market Committee
         https://www.federalreserve.gov/monetarypolicy/fomcminutes20260429.htm
         With regard to the outlook for monetary policy, participants
         generally judged that the continued elevated inflation readings
         together with
      5. [?] The Outlook for Fed Rate Cuts in 2026 | Goldman Sachs
         https://www.goldmansachs.com/insights/articles/the-outlook-for-fed-rate-cuts-in-2026
         Goldman Sachs Research forecasts two more cuts from the Fed next
         year, leaving interest rates at 3-3.25%.
  Step 4 · FORECAST → p_yes=0.12

  Rationale:
    Multiple forecasts show positive GDP growth for 2025-2026: Indiana
    Business Research Center forecasts 1.8% real GDP growth in 2026, Deloitte
    expects 4% business investment growth, and Fed officials project growth
    near potential. Current recession probability models show low risk (0.44%
    as of April 2026, NY Fed treasury spread model at ~15% for 12-months
    ahead). While some economic headwinds exist (softening labor market,
    elevated deficits), the consensus forecasts positive growth through 2026.
    The market implied probability of 17.5% appears slightly elevated given
    current economic indicators and forecasts.
  Uncertainties:
    - Current recession probability models show low risk (0

==============================================================================
  AGENT_1  ·  p_yes=0.22  status=legacy_capture  confidence=0.56  sentiment=bearish  evidence=high
  searches=3  sources=15  tokens=18,161
==============================================================================
  Step 1 · SEARCH  "US economic indicators 2024 2025 GDP growth inflation unemployment Federal Reserve interest rates"
      1. [?] The 2024 Economy and 2025 Preview
         https://blog.uwsp.edu/cps/2024/12/06/the-2024-economy-and-2025-preview
         As 2024 comes to an end, overall, the U.S. economy is in great shape.
         In 2024 economic growth was strong with more Americans working than
         ever as job gains continued and real wages were increasing. The U.S.
         stock market hit several record highs and was a global leader in
         providin…
      2. [?] An Update to the Economic Outlook: 2023 to 2025
         https://www.cbo.gov/publication/59258
         Real GDP increases by 1.5 percent in 2024 and by 2.4 percent in 2025.
         That initial slowdown in economic growth drives up unemployment. The
      3. [?] First Quarter 2025 Survey of Professional Forecasters
         https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/spf-q1-2025
         *   [Survey of Professional
         Forecasters](https://www.philadelphiafed.org/surveys-and-data/real-
         time-data-research/survey-of-professional-forecasters).
         [](https://www.philadelphiafed.org/-/media/FRBP/Assets/Surveys-And-
         Data/survey-of-professional-forecasters/2025/spfQ125.pdf "Down…
      4. [?] U.S. outlook for 2025 - Indiana Business Research Center
         https://www.ibrc.indiana.edu/ibr/2024/outlook/national.html
         ![Image 8: Line graph showing quarterly real personal consumption
         growth in the U.S. from 2023 Q4 to 2024 Q3, forecasted real personal
         consumption growth from 2024 Q4 to 2026 Q4 and last year's forecast
         for real personal consumption growth from 2023 Q4 to 2026
         Q4.'](https://www.i…
      5. [?] December 10, 2025: FOMC Projections materials, accessible version
         https://www.federalreserve.gov/monetarypolicy/fomcprojtabl20251210.htm
         *   [Federal Reserve
         Act](https://www.federalreserve.gov/aboutthefed/fract.htm). *
         [Notes](https://www.federalreserve.gov/monetarypolicy/monetary-
         policy-principles-and-practice.htm). *   [Federal Reserve
         Act](https://www.federalreserve.gov/aboutthefed/fract.htm). *
         [Federal R…
  Step 2 · SEARCH  "US recession probability 2025 2026 economic forecasts professional economists NBER recession indicators"
      1. [?] US Issues Recession Alert: Higher Chances In 2026 | WION
         https://www.youtube.com/watch?v=-HL5JFweunk
         The United States faces rising recession risks in 2026, with experts
         warning of economic slowdown ahead. Factors like inflation, interest
      2. [?] U.S. Recession Probabilities (1967-2026) - Macrotrends
         https://www.macrotrends.net/3084/us-recession-probabilities
         ## U.S. Recession Probabilities (1967-2026). Markets Metals Energy
         Commodities Interest Rates Exchange Rates Economy. Inflation Rate
         Unemployment National Debt Debt/GDP Housing Starts Initial Claims
         Retail Sales Industrial Prod Durable Goods. # **U.S. Recession
         Probabilities:** 0…
      3. [?] [PDF] Probability of US Recession Predicted by Treasury Spread
         https://www.newyorkfed.org/medialibrary/media/research/capital_markets/prob_rec.pdf
         Probability of US Recession Predicted by Treasury Spread* Treasury
         Spread: 10 yr bond rate-3 month bill rate Monthly Average (Percent)
         1959 1961 1963 1965 1967 1969 1971 1973 1975 1977 1979 1981 1983 1985
         1987 1989 1991 1993 1995 1997 1999 2001 2003 2005 2007 2009 2011 2013
         2015…
      4. [?] NBER based Recession Indicators for the United States from ... - FRED
         https://fred.stlouisfed.org/series/USREC
         # NBER based Recession Indicators for the United States from the
         Period following the Peak through the Trough (USREC). This time
         series is an interpretation of US Business Cycle Expansions and
         Contractions data provided by The National Bureau of Economic
         Research (NBER). For this…
      5. [?] What Is the Probability of a Recession? | J.P. Morgan Research
         https://www.jpmorgan.com/insights/global-research/economy/recession-probability
         [Skip to main content](https://www.jpmorgan.com/insights/global-
         research/economy/recession-probability#main). *   [Global
         Research](https://www.jpmorgan.com/insights/research). *   [Global
         Research](https://www.jpmorgan.com/insights/global-research). *
         [Markets and Economy](htt…
  Step 3 · SEARCH  "US economic base rates recession frequency historical data since 1950 average recession probability"
      1. [?] [PDF] History Suggests a High Chance of Recession over the Next 24 ...
         https://www.hks.harvard.edu/sites/default/files/centers/mrcbg/files/Recession_blog.pdf
         To examine the plausibility of these forecasts, we look at quarterly
         data going back to the 1950s and calculate the probability that the
         economy goes into a recession within the next 12 and 24 months,
         conditioning on alternative measures of inflation and unemployment.
         Table 1 sho…
      2. [?] [PDF] Probability of US Recession Predicted by Treasury Spread
         https://www.newyorkfed.org/medialibrary/media/research/capital_markets/prob_rec.pdf
         Probability of US Recession Predicted by Treasury Spread* Treasury
         Spread: 10 yr bond rate-3 month bill rate Monthly Average (Percent)
         1959 1961 1963 1965 1967 1969 1971 1973 1975 1977 1979 1981 1983 1985
         1987 1989 1991 1993 1995 1997 1999 2001 2003 2005 2007 2009 2011 2013
         2015…
      3. [?] List of recessions in the United States - Wikipedia
         https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States
         # List of recessions in the United States. There have been as many as
         48 recessions in the United States dating back to the Articles of
         Confederation, and although economists and historians dispute certain
         19th-century recessions, the consensus view among economists and
         historian…
      4. [?] [PDF] Has the Recession Started? - University of California, Berkeley
         https://eml.berkeley.edu/~saez/michaillat-saezOBES25.pdf
         The indicator is larger when the unem-ployment rate increases more
         rapidly.2 1960 1970 1980 1990 2000 2010 2020 0 0.5 1 2 3 4 Recession
         indicators (pp) Unemployment Vacancy FIGURE 2 | Construction of the
         Michez rule: unemployment and vacancy indicators, January
         1960–December 2024…
      5. [?] Dates of U.S. recessions as inferred by GDP-based recession indicator (JHDUSRGDPBR) | FRED | St. Louis Fed
         https://fred.stlouisfed.org/series/JHDUSRGDPBR
         # Dates of U.S. recessions as inferred by GDP-based recession
         indicator (JHDUSRGDPBR). **Release:** GDP-Based Recession Indicator
         Index. The series assigns dates to U.S. recessions based on a
         mathematical model of the way that recessions differ from expansions.
         Whenever the GDP-b…
  Step 4 · FORECAST → p_yes=0.22

  Rationale:
    Based on current economic conditions and historical base rates, the US
    economy shows resilience with strong 2024 performance (2.5-2.9% GDP
    growth), low unemployment near 4%, and inflation approaching the Fed's 2%
    target. Professional forecasters project continued positive growth through
    2025-2026. However, historical data shows recessions occur roughly every
    6-8 years on average, with the last recession ending in 2020. The NY Fed
    yield curve model shows only 14.98% recession probability by May 2027,
    while other indicators remain relatively low. Given the 24-month forecast
    window and typical recession frequency, assigning 22% probability accounts
    for both the currently favorable conditions and the base rate risk of
    economic cycles, slightly above the market-implied 17.5%.
  Uncertainties:
    - However, historical data shows recessions occur roughly every 6-8 years
    on average, with the last recession ending in 2020
    - Given the 24-month forecast window and typical recession frequency,
    assigning 22% probability accounts for both the currently favorable
    conditions and the base rate risk of economic cycles, slightly above the
    market-implied 17

==============================================================================
  AGENT_2  ·  p_yes=0.22  status=legacy_capture  confidence=0.56  sentiment=bearish  evidence=high
  searches=3  sources=15  tokens=27,085
==============================================================================
  Step 1 · SEARCH  "US economic indicators 2024 2025 GDP growth inflation unemployment Federal Reserve interest rates"
      1. [?] An Update to the Economic Outlook: 2023 to 2025
         https://www.cbo.gov/publication/59258
         Real GDP increases by 1.5 percent in 2024 and by 2.4 percent in 2025.
         That initial slowdown in economic growth drives up unemployment. The
      2. [?] First Quarter 2025 Survey of Professional Forecasters
         https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/spf-q1-2025
         *   [Survey of Professional
         Forecasters](https://www.philadelphiafed.org/surveys-and-data/real-
         time-data-research/survey-of-professional-forecasters).
         [](https://www.philadelphiafed.org/-/media/FRBP/Assets/Surveys-And-
         Data/survey-of-professional-forecasters/2025/spfQ125.pdf "Down…
      3. [?] U.S. outlook for 2025 - Indiana Business Research Center
         https://www.ibrc.indiana.edu/ibr/2024/outlook/national.html
         ![Image 8: Line graph showing quarterly real personal consumption
         growth in the U.S. from 2023 Q4 to 2024 Q3, forecasted real personal
         consumption growth from 2024 Q4 to 2026 Q4 and last year's forecast
         for real personal consumption growth from 2023 Q4 to 2026
         Q4.'](https://www.i…
      4. [?] December 10, 2025: FOMC Projections materials, accessible version
         https://www.federalreserve.gov/monetarypolicy/fomcprojtabl20251210.htm
         *   [Federal Reserve
         Act](https://www.federalreserve.gov/aboutthefed/fract.htm). *
         [Notes](https://www.federalreserve.gov/monetarypolicy/monetary-
         policy-principles-and-practice.htm). *   [Federal Reserve
         Act](https://www.federalreserve.gov/aboutthefed/fract.htm). *
         [Federal R…
      5. [?] United States Fed Funds Interest Rate - Trading Economics
         https://tradingeconomics.com/united-states/interest-rate
         [](https://tradingeconomics.com/united-states/interest-rate).
         [](https://tradingeconomics.com/united-states/interest-rate).
         [Markets](https://tradingeconomics.com/united-states/interest-rate#).
         [Forecasts](https://tradingeconomics.com/united-states/interest-
         rate#). [](https://tra…
  Step 2 · SEARCH  "US recession probability 2025 2026 professional forecasters economists surveys"
      1. [?] First Quarter 2026 Survey of Professional Forecasters
         https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/spf-q1-2026
         *   [Survey of Professional
         Forecasters](https://www.philadelphiafed.org/surveys-and-data/real-
         time-data-research/survey-of-professional-forecasters).
         [](https://www.philadelphiafed.org/-/media/FRBP/Assets/Surveys-And-
         Data/survey-of-professional-forecasters/2026/spfQ126.pdf "Down…
      2. [?] Survey of Professional Forecasters
         https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/survey-of-professional-forecasters
         *   [Second Quarter 2026 Survey of Professional Forecasters / May
         2026](https://www.philadelphiafed.org/surveys-and-data/real-time-
         data-research/spf-q2-2026). *   [First Quarter 2026 Survey of
         Professional Forecasters / March
         2026](https://www.philadelphiafed.org/surveys-and-data…
      3. [?] US Economic Forecast Q1 2026 | Deloitte Insights
         https://www.deloitte.com/us/en/insights/topics/economy/us-economic-forecast/united-states-outlook-analysis.html
         This reflects the sizable capital expenditure plans that AI
         “hyperscalers” have announced for this
         year.[4](https://www.deloitte.com/us/en/insights/topics/economy/us-

## Aggregating the Panel

Three ways to turn three probabilities into one, from
[`05_aggregation_math`](05_aggregation_math.ipynb):

| Method | What it assumes |
|---|---|
| Simple mean | Nothing beyond the forecasts themselves |
| Neyman | A pairwise correlation, supplied rather than estimated |
| Weighted Neyman | That correlation, plus that the confidence values mean something |

Only artifacts that actually produced a forecast may enter any of the three. An agent that
exhausted its step budget carries the loop's fallback probability, and averaging that in
would pull the panel toward even odds on the strength of an agent that never answered.

In [8]:
forecast_artifacts = [a for a in artifacts if a.p_yes is not None]
if not forecast_artifacts:
    run = RunTrace.capture(
        notebook="06_multi_agent_research",
        provider=provider_name,
        question=question,
        agents=artifacts,
        llm_calls=llm_calls,
        status="abstained",
    )
    raise RuntimeError(f"All researchers abstained. Diagnostic trace: {run.save()}")
probs = [a.p_yes for a in forecast_artifacts]
weights = [a.confidence for a in forecast_artifacts]

simple_mean = sum(probs) / len(probs)
result_neyman = neyman_extremize(probs, base=0.5, correlation=0.3)
result_weighted = neyman_extremize_weighted(probs, weights, base=0.5, correlation=0.3)

agg_df = pl.DataFrame(
    [
        {
            "method": "Simple mean",
            "aggregate": round(simple_mean, 3),
            "d": None,
            "n_eff": None,
        },
        {
            "method": "Neyman (ρ=0.3)",
            "aggregate": round(result_neyman.extremized_probability, 3),
            "d": round(result_neyman.extremization_factor, 3),
            "n_eff": round(result_neyman.effective_n, 2),
        },
        {
            "method": "Weighted Neyman",
            "aggregate": round(result_weighted.extremized_probability, 3),
            "d": round(result_weighted.extremization_factor, 3),
            "n_eff": round(result_weighted.effective_n, 2),
        },
    ]
)
agg_df

shape: (3, 4)
┌─────────────────┬───────────┬───────┬───────┐
│ method          ┆ aggregate ┆ d     ┆ n_eff │
│ ---             ┆ ---       ┆ ---   ┆ ---   │
│ str             ┆ f64       ┆ f64   ┆ f64   │
╞═════════════════╪═══════════╪═══════╪═══════╡
│ Simple mean     ┆ 0.187     ┆ null  ┆ null  │
│ Neyman (ρ=0.3)  ┆ 0.071     ┆ 1.369 ┆ 1.88  │
│ Weighted Neyman ┆ 0.063     ┆ 1.363 ┆ 1.86  │
└─────────────────┴───────────┴───────┴───────┘

Both Neyman variants sit further from the base rate than the mean, which is what
extremization does. The gap between them is the whole contribution of the confidence
weights, and those weights are a function of how far each probability sits from even odds
rather than of anything measured, so the two lines being close is not reassurance.

## How Much the Correlation Assumption Decides

$\rho$ is the one input to Neyman extremization that nothing in this run measures, and it is
the input the answer is most sensitive to. Sweeping it over the same three forecasts shows
how much of the aggregate is evidence and how much is assumption.

In [9]:
correlation_rows = []
for rho in [0.0, 0.1, 0.3, 0.5, 0.7, 0.9]:
    r = neyman_extremize(probs, base=0.5, correlation=rho)
    rw = neyman_extremize_weighted(probs, weights, base=0.5, correlation=rho)
    correlation_rows.append(
        {
            "correlation": rho,
            "neyman": round(r.extremized_probability, 3),
            "weighted_neyman": round(rw.extremized_probability, 3),
            "shift_from_mean": round((r.extremized_probability or 0) - simple_mean, 3),
        }
    )
correlation_df = pl.DataFrame(correlation_rows)
correlation_df

shape: (6, 4)
┌─────────────┬────────┬─────────────────┬─────────────────┐
│ correlation ┆ neyman ┆ weighted_neyman ┆ shift_from_mean │
│ ---         ┆ ---    ┆ ---             ┆ ---             │
│ f64         ┆ f64    ┆ f64             ┆ f64             │
╞═════════════╪════════╪═════════════════╪═════════════════╡
│ 0.0         ┆ 0.01   ┆ 0.01            ┆ -0.177          │
│ 0.1         ┆ 0.01   ┆ 0.01            ┆ -0.177          │
│ 0.3         ┆ 0.071  ┆ 0.063           ┆ -0.116          │
│ 0.5         ┆ 0.116  ┆ 0.109           ┆ -0.07           │
│ 0.7         ┆ 0.15   ┆ 0.142           ┆ -0.037          │
│ 0.9         ┆ 0.176  ┆ 0.169           ┆ -0.011          │
└─────────────┴────────┴─────────────────┴─────────────────┘

At the dependent end the panel is credited with barely more than one observation and the
aggregate settles onto the mean. At the independent end it is credited with three, the
formula pushes so far below the base rate that it leaves the unit interval, and what the
chart shows there is the floor. The agents' own forecasts never move along any of these
curves. Everything that does move is the assumption.

A clamp that carries the answer is worth naming rather than tolerating. It is not part of
the theory: it exists so the function always returns something a downstream consumer can
treat as a probability, and where it binds, the method has failed on this panel rather than
answered it. The reading to take from the left of this chart is that a three-agent panel this
far from even odds, under an independence assumption, is mapped outside the unit interval by
this formula, which therefore has no answer to give: not that the aggregate is whatever the
floor happens to be set to, and not that these three agents are in fact correlated.

Nothing in this run estimates $\rho$, and the confidence values feeding the weighted variant
are the extremity heuristic from [`04_research_agent`](04_research_agent.ipynb) rather than
measured skill. So the mean is the number to report, and the curve is what says how much
would be at stake in estimating the correlation properly.

## What the Next Stages Receive

Debate and supervisor reconciliation do not read the artifacts directly. They read this
summary: the agent's id, its probability and confidence, the opening of its rationale, and,
where the model enumerated any, its first few key findings. None of these three rationales
enumerates anything - all three are continuous prose - so no findings block appears below,
which is what [`04_research_agent`](04_research_agent.ipynb) means when it says the field
records how the model chose to present its reasons. Everything else - the full search trail,
the evidence, the uncertainties - stays in the record and out of the next prompt, which is a
context budget decision as much as a design one.

The correlation values are illustrative assumptions, not measured dependence
among these models. Confidence weights are model-reported or heuristic and are
not calibrated reliability estimates. Use the sensitivity sweep to see how those
assumptions change the arithmetic, not to establish a performance advantage.

In [10]:
all_summaries = "\n\n---\n\n".join(format_agent_summary(a) for a in forecast_artifacts)
print(all_summaries)

Agent: agent_0
Probability (p_yes): 0.12
Status: legacy_capture
Confidence: 0.76
Rationale: Multiple forecasts show positive GDP growth for 2025-2026: Indiana Business Research Center forecasts 1.8% real GDP growth in 2026, Deloitte expects 4% business investment growth, and Fed officials project growth near potential. Current recession probability models show low risk (0.44% as of April 2026, NY Fed treasury spread model at ~15% for 12-months ahead). While some economic headwinds exist (softening labor market, elevated deficits), the consensus forecasts positive growth through 2026. The market implied probability of 17.5% appears slightly elevated given current economic indicators and forecasts.
Source: U.S. outlook for 2026 - Indiana Business Research Center | https://www.ibrc.indiana.edu/ibr/2025/outlook/national.html
Excerpt: The IBR is a publication of the Indiana Business Research Center at IU's Kelley School of Business. *Recent developments in the U.S. and global economy present a complex and evolving picture for policymakers and business leaders. While our current readings of headline growth rema…
Source: Economic Outlook U.S. Q2 2026: Curb Your Enthusia | https://www.spglobal.com/ratings/en/regulatory/article/economic-outlook-us-q2-2026-curb-your-enthusiasm-s101676533
Excerpt: [Current Oil Price Surge To Weigh On Growth](https://www.spglobal.com/ratings/en/regulatory/article/economic-outlook-us-q2-2026-curb-your-enthusiasm-s101676533). Before the war broke out, we were expecting to increase our growth forecast for this year closer to 2.5% on higher-tha…
Source: US Economic Forecast Q1 2026 | Deloitte Insights | https://www.deloitte.com/us/en/insights/topics/economy/us-economic-forecast/united-states-outlook-analysis.html
Excerpt: This reflects the sizable capital expenditure plans that AI “hyperscalers” have announced for this year.[4](https://www.deloitte.com/us/en/insights/topics/economy/us-economic-forecast/united-states-outlook-analysis.html#endnote-4)We now expect real business investment to grow by…
Source: The Budget and Economic Outlook: 2026 to 2036 | https://www.cbo.gov/publication/62105
Excerpt: Real GDP growth in 2026 is projected to be stronger in the current projections, partly because of the effects of the 2025 reconciliation act. In
Source: United States GDP Growth Rate - Trading Economics | https://tradingeconomics.com/united-states/gdp-growth
Excerpt: [](https://tradingeconomics.com/united-states/gdp-growth). [](https://tradingeconomics.com/united-states/gdp-growth). [Markets](https://tradingeconomics.com/united-states/gdp-growth#). [Forecasts](https://tradingeconomics.com/united-states/gdp-growth#). [](https://tradingeconomic…
Source: [PDF] Probability of US Recession Predicted by Treasury Spread | https://www.newyorkfed.org/medialibrary/media/research/capital_markets/prob_rec.pdf
Excerpt: Probability of US Recession Predicted by Treasury Spread* Treasury Spread: 10 yr bond rate-3 month bill rate Monthly Average (Percent) 1959 1961 1963 1965 1967 1969 1971 1973 1975 1977 1979 1981 1983 1985 1987 1989 1991 1993 1995 1997 1999 2001 2003 2005 2007 2009 2011 2013 2015…
Source: US Recession Probability 2025 – Sahm Rule, Yield Curve & NBER ... | https://www.jvinvest.ai/economics
Excerpt: Track US recession risk in real-time: Sahm Rule at 0.5%, yield curve analysis, NBER probability models. Free charts & data updated daily.
Source: U.S. Recession Probabilities (1967-2026) - Macrotrends | https://www.macrotrends.net/3084/us-recession-probabilities
Excerpt: ## U.S. Recession Probabilities (1967-2026). Markets Metals Energy Commodities Interest Rates Exchange Rates Economy. Inflation Rate Unemployment National Debt Debt/GDP Housing Starts Initial Claims Retail Sales Industrial Prod Durable Goods. # **U.S. Recession Probabilities:** 0…
Source: 6 Key Recession Indicators To Watch for in 2025 - Chase Bank | https://www.chase.com/personal/investments/learning-and-insights/article/what-are-recession-indicators
Excerpt: The NBER doesn't have a set formula to determine if the US is in a recession, but it does use the following six key economic indicators to help identify
Source: The Big Four Recession Indicators - dshort - Advisor Perspectives | https://www.advisorperspectives.com/dshort/updates/2026/06/05/the-big-four-recession-indicators
Excerpt: The chart and table below illustrate the performance of the generic big four since the end of the most recent recession (2020). The NBER
Source: Fed Outlook 2026: Rate Forecasts and Fixed Income Strategies | https://www.ishares.com/us/insights/fed-outlook-2026-interest-rate-forecast
Excerpt: We believe the most likely path for Fed policy in 2026 is for the central bank to bring rates down from the current range of 3.50% to 3.75%
Source: Minutes of the Federal Open Market Committee | https://www.federalreserve.gov/monetarypolicy/fomcminutes20250917.htm
Excerpt: In their consideration of monetary policy at this meeting, participants noted that inflation had risen recently and remained somewhat elevated,
Source: The Economic Outlook and Monetary Policy – April 1, 2026 | https://www.stlouisfed.org/from-the-president/remarks/2026/economic-outlook-monetary-policy-aei
Excerpt: A baseline scenario for 2026 has real GDP growing close to potential, the unemployment rate holding around its current level, and core inflation
Source: Minutes of the Federal Open Market Committee | https://www.federalreserve.gov/monetarypolicy/fomcminutes20260429.htm
Excerpt: With regard to the outlook for monetary policy, participants generally judged that the continued elevated inflation readings together with
Source: The Outlook for Fed Rate Cuts in 2026 | Goldman Sachs | https://www.goldmansachs.com/insights/articles/the-outlook-for-fed-rate-cuts-in-2026
Excerpt: Goldman Sachs Research forecasts two more cuts from the Fed next year, leaving interest rates at 3-3.25%.

---

Agent: agent_1
Probability (p_yes): 0.22
Status: legacy_capture
Confidence: 0.56
Rationale: Based on current economic conditions and historical base rates, the US economy shows resilience with strong 2024 performance (2.5-2.9% GDP growth), low unemployment near 4%, and inflation approaching the Fed's 2% target. Professional forecasters project continued positive growth through 2025-2026. However, historical data shows recessions occur roughly every 6-8 years on average, with the last recession ending in 2020. The NY Fed yield curve model shows only 14.98% recession probability by May 2027, while other indicators remain relatively low. Given the 24-month forecast window and typical recession frequency, assigning 22% probability accounts for both the currently favorable conditions and the base rate risk of economic cycles, slightly above the market-implied 17.5%.
Source: The 2024 Economy and 2025 Preview | https://blog.uwsp.edu/cps/2024/12/06/the-2024-economy-and-2025-preview
Excerpt: As 2024 comes to an end, overall, the U.S. economy is in great shape. In 2024 economic growth was strong with more Americans working than ever as job gains continued and real wages were increasing. The U.S. stock market hit several record highs and was a global leader in providin…
Source: An Update to the Economic Outlook: 2023 to 2025 | https://www.cbo.gov/publication/59258
Excerpt: Real GDP increases by 1.5 percent in 2024 and by 2.4 percent in 2025. That initial slowdown in economic growth drives up unemployment. The
Source: First Quarter 2025 Survey of Professional Forecasters | https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/spf-q1-2025
Excerpt: *   [Survey of Professional Forecasters](https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/survey-of-professional-forecasters). [](https://www.philadelphiafed.org/-/media/FRBP/Assets/Surveys-And-Data/survey-of-professional-forecasters/2025/spfQ125.pdf "Down…
Source: U.S. outlook for 2025 - Indiana Business Research Center | https://www.ibrc.indiana.edu/ibr/2024/outlook/national.html
Excerpt: ![Image 8: Line graph showing quarterly real personal consumption growth in the U.S. from 2023 Q4 to 2024 Q3, forecasted real personal consumption growth from 2024 Q4 to 2026 Q4 and last year's forecast for real personal consumption growth from 2023 Q4 to 2026 Q4.'](https://www.i…
Source: December 10, 2025: FOMC Projections materials, accessible version | https://www.federalreserve.gov/monetarypolicy/fomcprojtabl20251210.htm
Excerpt: *   [Federal Reserve Act](https://www.federalreserve.gov/aboutthefed/fract.htm). *   [Notes](https://www.federalreserve.gov/monetarypolicy/monetary-policy-principles-and-practice.htm). *   [Federal Reserve Act](https://www.federalreserve.gov/aboutthefed/fract.htm). *   [Federal R…
Source: US Issues Recession Alert: Higher Chances In 2026 | WION | https://www.youtube.com/watch?v=-HL5JFweunk
Excerpt: The United States faces rising recession risks in 2026, with experts warning of economic slowdown ahead. Factors like inflation, interest
Source: U.S. Recession Probabilities (1967-2026) - Macrotrends | https://www.macrotrends.net/3084/us-recession-probabilities
Excerpt: ## U.S. Recession Probabilities (1967-2026). Markets Metals Energy Commodities Interest Rates Exchange Rates Economy. Inflation Rate Unemployment National Debt Debt/GDP Housing Starts Initial Claims Retail Sales Industrial Prod Durable Goods. # **U.S. Recession Probabilities:** 0…
Source: [PDF] Probability of US Recession Predicted by Treasury Spread | https://www.newyorkfed.org/medialibrary/media/research/capital_markets/prob_rec.pdf
Excerpt: Probability of US Recession Predicted by Treasury Spread* Treasury Spread: 10 yr bond rate-3 month bill rate Monthly Average (Percent) 1959 1961 1963 1965 1967 1969 1971 1973 1975 1977 1979 1981 1983 1985 1987 1989 1991 1993 1995 1997 1999 2001 2003 2005 2007 2009 2011 2013 2015…
Source: NBER based Recession Indicators for the United States from ... - FRED | https://fred.stlouisfed.org/series/USREC
Excerpt: # NBER based Recession Indicators for the United States from the Period following the Peak through the Trough (USREC). This time series is an interpretation of US Business Cycle Expansions and Contractions data provided by The National Bureau of Economic Research (NBER). For this…
Source: What Is the Probability of a Recession? | J.P. Morgan Research | https://www.jpmorgan.com/insights/global-research/economy/recession-probability
Excerpt: [Skip to main content](https://www.jpmorgan.com/insights/global-research/economy/recession-probability#main). *   [Global Research](https://www.jpmorgan.com/insights/research). *   [Global Research](https://www.jpmorgan.com/insights/global-research). *   [Markets and Economy](htt…
Source: [PDF] History Suggests a High Chance of Recession over the Next 24 ... | https://www.hks.harvard.edu/sites/default/files/centers/mrcbg/files/Recession_blog.pdf
Excerpt: To examine the plausibility of these forecasts, we look at quarterly data going back to the 1950s and calculate the probability that the economy goes into a recession within the next 12 and 24 months, conditioning on alternative measures of inflation and unemployment. Table 1 sho…
Source: [PDF] Probability of US Recession Predicted by Treasury Spread | https://www.newyorkfed.org/medialibrary/media/research/capital_markets/prob_rec.pdf
Excerpt: Probability of US Recession Predicted by Treasury Spread* Treasury Spread: 10 yr bond rate-3 month bill rate Monthly Average (Percent) 1959 1961 1963 1965 1967 1969 1971 1973 1975 1977 1979 1981 1983 1985 1987 1989 1991 1993 1995 1997 1999 2001 2003 2005 2007 2009 2011 2013 2015…
Source: List of recessions in the United States - Wikipedia | https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States
Excerpt: # List of recessions in the United States. There have been as many as 48 recessions in the United States dating back to the Articles of Confederation, and although economists and historians dispute certain 19th-century recessions, the consensus view among economists and historian…
Source: [PDF] Has the Recession Started? - University of California, Berkeley | https://eml.berkeley.edu/~saez/michaillat-saezOBES25.pdf
Excerpt: The indicator is larger when the unem-ployment rate increases more rapidly.2 1960 1970 1980 1990 2000 2010 2020 0 0.5 1 2 3 4 Recession indicators (pp) Unemployment Vacancy FIGURE 2 | Construction of the Michez rule: unemployment and vacancy indicators, January 1960–December 2024…
Source: Dates of U.S. recessions as inferred by GDP-based recession indicator (JHDUSRGDPBR) | FRED | St. Louis Fed | https://fred.stlouisfed.org/series/JHDUSRGDPBR
Excerpt: # Dates of U.S. recessions as inferred by GDP-based recession indicator (JHDUSRGDPBR). **Release:** GDP-Based Recession Indicator Index. The series assigns dates to U.S. recessions based on a mathematical model of the way that recessions differ from expansions. Whenever the GDP-b…

---

Agent: agent_2
Probability (p_yes): 0.22
Status: legacy_capture
Confidence: 0.56
Rationale: Based on professional forecaster surveys showing continued GDP growth expectations for 2025-2026, Fed projections indicating gradual economic expansion, and historical base rates showing US recessions occur roughly every 6-8 years on average (with the last recession in 2020). Current economic indicators suggest a 'soft landing' scenario with unemployment remaining relatively low and inflation moderating. The market implied probability of 17.5% appears slightly underpriced given typical recession frequency and current economic uncertainties, but professional consensus forecasts lean toward continued growth through 2026.
Source: An Update to the Economic Outlook: 2023 to 2025 | https://www.cbo.gov/publication/59258
Excerpt: Real GDP increases by 1.5 percent in 2024 and by 2.4 percent in 2025. That initial slowdown in economic growth drives up unemployment. The
Source: First Quarter 2025 Survey of Professional Forecasters | https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/spf-q1-2025
Excerpt: *   [Survey of Professional Forecasters](https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/survey-of-professional-forecasters). [](https://www.philadelphiafed.org/-/media/FRBP/Assets/Surveys-And-Data/survey-of-professional-forecasters/2025/spfQ125.pdf "Down…
Source: U.S. outlook for 2025 - Indiana Business Research Center | https://www.ibrc.indiana.edu/ibr/2024/outlook/national.html
Excerpt: ![Image 8: Line graph showing quarterly real personal consumption growth in the U.S. from 2023 Q4 to 2024 Q3, forecasted real personal consumption growth from 2024 Q4 to 2026 Q4 and last year's forecast for real personal consumption growth from 2023 Q4 to 2026 Q4.'](https://www.i…
Source: December 10, 2025: FOMC Projections materials, accessible version | https://www.federalreserve.gov/monetarypolicy/fomcprojtabl20251210.htm
Excerpt: *   [Federal Reserve Act](https://www.federalreserve.gov/aboutthefed/fract.htm). *   [Notes](https://www.federalreserve.gov/monetarypolicy/monetary-policy-principles-and-practice.htm). *   [Federal Reserve Act](https://www.federalreserve.gov/aboutthefed/fract.htm). *   [Federal R…
Source: United States Fed Funds Interest Rate - Trading Economics | https://tradingeconomics.com/united-states/interest-rate
Excerpt: [](https://tradingeconomics.com/united-states/interest-rate). [](https://tradingeconomics.com/united-states/interest-rate). [Markets](https://tradingeconomics.com/united-states/interest-rate#). [Forecasts](https://tradingeconomics.com/united-states/interest-rate#). [](https://tra…
Source: First Quarter 2026 Survey of Professional Forecasters | https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/spf-q1-2026
Excerpt: *   [Survey of Professional Forecasters](https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/survey-of-professional-forecasters). [](https://www.philadelphiafed.org/-/media/FRBP/Assets/Surveys-And-Data/survey-of-professional-forecasters/2026/spfQ126.pdf "Down…
Source: Survey of Professional Forecasters | https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/survey-of-professional-forecasters
Excerpt: *   [Second Quarter 2026 Survey of Professional Forecasters / May 2026](https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/spf-q2-2026). *   [First Quarter 2026 Survey of Professional Forecasters / March 2026](https://www.philadelphiafed.org/surveys-and-data…
Source: US Economic Forecast Q1 2026 | Deloitte Insights | https://www.deloitte.com/us/en/insights/topics/economy/us-economic-forecast/united-states-outlook-analysis.html
Excerpt: This reflects the sizable capital expenditure plans that AI “hyperscalers” have announced for this year.[4](https://www.deloitte.com/us/en/insights/topics/economy/us-economic-forecast/united-states-outlook-analysis.html#endnote-4)We now expect real business investment to grow by…
Source: Professional Forecasters' Past Performance and the 2026 Economic ... | https://www.stlouisfed.org/on-the-economy/2025/dec/professional-forecasters-past-performance-outlook-2026
Excerpt: # Professional Forecasters’ Past Performance and the 2026 Economic Outlook. Image 2: Federal Reserve Bank of St. Louis. Image 3 FRED Tools and resources to find and use economic data worldwide. Image 4 FRASER U.S. Financial, economic, and banking history. Image 5 ALFRED Vintages…
Source: U.S. Economy Forecast: Blue Chip Economic Indicators outlook for ... | https://www.wolterskluwer.com/en/expert-insights/us-economy-forecast-blue-chip-economic-indicators-outlook-for-the-year-ahead
Excerpt: All content is available on the global site. # U.S. Economy Forecast: Blue Chip Economic Indicators outlook for the year ahead. ### Every month, Wolters Kluwer provides corporate and government decision-makers with an outlook on the performance of the U.S. economy for the year ah…
Source: [PDF] NBER Recession Dates: Strengths, Weaknesses, and a Modern ... | https://eml.berkeley.edu/~dromer/papers/NBER%20Recession%20Dates.pdf
Excerpt: This is the second key result of the model.3 In other words, if a modern time-series econometrician with no knowledge of the history of business cycle dating or the concept of a recession were handed the time series for postwar U.S. GDP growth, they would conclude that the data p…
Source: NBER based Recession Indicators for the United States from ... - FRED | https://fred.stlouisfed.org/series/USREC
Excerpt: # NBER based Recession Indicators for the United States from the Period following the Peak through the Trough (USREC). This time series is an interpretation of US Business Cycle Expansions and Contractions data provided by The National Bureau of Economic Research (NBER). For this…
Source: Recession Dating and Real-Time Data | https://www.philadelphiafed.org/the-economy/macroeconomics/recession-dating-and-real-time-data
Excerpt: The NBER is the accepted dater of the start and end of recessions in the U.S. The NBER is the accepted dater of the start and end of recessions in the U.S. When recessions are called by the NBER, they are generally marked by a downward trend in the following variables: real sales…
Source: [PDF] Business Cycles and Low-Frequency Fluctuations in the US ... | https://www.clevelandfed.org/-/media/project/clevelandfedtenant/clevelandfedsite/publications/working-papers/2023/wp2319.pdf
Excerpt: I refer to these recessions as “NBER recessions.” For my second type of recession, I follow in the spirit of previous macro-labor research.
Source: List of recessions in the United States - Wikipedia | https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States
Excerpt: # List of recessions in the United States. There have been as many as 48 recessions in the United States dating back to the Articles of Confederation, and although economists and historians dispute certain 19th-century recessions, the consensus view among economists and historian…

## Search Execution Audit

Rolling every agent's search steps into one table shows the panel's evidence-gathering at a
glance: who asked what, and how much came back. Queries appearing in more than one agent's
rows are shared retrieval, which is one of the two things that could explain agreement; the
table shows the overlap and does not, on its own, attribute the spread to it.

In [11]:
audit_df = pl.DataFrame(
    [
        {
            "agent_id": a.agent_id,
            "step": t.step,
            "query": t.query,
            "results": len(t.results),
        }
        for a in artifacts
        for t in a.traces
        if t.action == "search"
    ]
)
audit_df

shape: (9, 4)
┌──────────┬──────┬─────────────────────────────────┬─────────┐
│ agent_id ┆ step ┆ query                           ┆ results │
│ ---      ┆ ---  ┆ ---                             ┆ ---     │
│ str      ┆ i64  ┆ str                             ┆ i64     │
╞══════════╪══════╪═════════════════════════════════╪═════════╡
│ agent_0  ┆ 1    ┆ US GDP growth forecast 2025 20… ┆ 5       │
│ agent_0  ┆ 2    ┆ US recession probability 2025 … ┆ 5       │
│ agent_0  ┆ 3    ┆ Federal Reserve interest rates… ┆ 5       │
│ agent_1  ┆ 1    ┆ US economic indicators 2024 20… ┆ 5       │
│ agent_1  ┆ 2    ┆ US recession probability 2025 … ┆ 5       │
│ agent_1  ┆ 3    ┆ US economic base rates recessi… ┆ 5       │
│ agent_2  ┆ 1    ┆ US economic indicators 2024 20… ┆ 5       │
│ agent_2  ┆ 2    ┆ US recession probability 2025 … ┆ 5       │
│ agent_2  ┆ 3    ┆ historical US recession freque… ┆ 5       │
└──────────┴──────┴─────────────────────────────────┴─────────┘

Both counts bound what this run can be used for. Every prompt carried the market price, so
the agents were told the answer the market had reached before they searched, and their
closeness to it says nothing about their skill. No result carries a publication date, so
nothing establishes that a document was available before the question was asked; the trace
reproduces what the agents saw and cannot date it.

## Persisting the Full Run Trace

Auditing an agent means being able to reconstruct exactly what it saw and
said. `RunTrace.capture` bundles the question, the parameters, every agent's
structured artifact, the aggregation result, and the complete raw model
conversation (`llm_calls` - every prompt sent and every response received,
captured by the per-agent `TracingLLMClient`s above) into one object, and
`save()` writes it to `forecast_traces/` as JSON. That saved file is exactly
what the replay path above reloads: it is the durable record of this
point-in-time run, which a reviewer can reopen long after the live market and
web evidence have moved on. A live run (`RUN_LIVE = True`) writes a fresh trace
here; the default replay run reports the pinned trace it loaded instead of
overwriting it.

In [12]:
if RUN_LIVE:
    run = RunTrace.capture(
        notebook="06_multi_agent_research",
        provider=provider_name,
        question=question,
        params={
            "n_agents": N_AGENTS,
            "max_steps": MAX_STEPS,
            "max_search_results": MAX_SEARCH_RESULTS,
        },
        agents=artifacts,
        aggregation=result_neyman,
        final_probability=result_neyman.extremized_probability,
        notes="Parallel research agents on the pinned one-directional question.",
        llm_calls=llm_calls,
    )
    trace_path = run.save()
    print(
        f"Saved {len(run.llm_calls)} model calls "
        f"({run.total_tokens():,} tokens) → {trace_path.relative_to(trace_path.parents[1])}"
    )
else:
    # Replay: report the pinned trace we loaded rather than writing a new file.
    run = pinned_run
    trace_path = TRACES_DIR / PINNED_TRACE
    print(
        f"Replayed {len(run.llm_calls)} model calls "
        f"({run.total_tokens():,} tokens) from {trace_path.name}"
    )

Replayed 12 model calls (57,908 tokens) from 06_multi_agent_research_20260609T141413Z_9fc4a2655471.json

## The Raw Conversation

The timeline above is the parsed trace. This is what the model actually received and sent.
For the first agent, `replay_llm_calls` prints each message in order - the system prompt, the
question, and every tool result fed back in - beside the untruncated JSON returned at each
step.

This is where an audit ends up when a forecast looks wrong. The parsed rationale, the search
queries and the probability are all derived from these responses, so a disagreement between
the summary and the source is settled here. Pass `content_chars=None` for the complete
payloads.

In [13]:
agent_0_calls = [c for c in llm_calls if c.label == "agent_0"]
print(replay_llm_calls(agent_0_calls, content_chars=600))

==============================================================================
  CALL #0 [agent_0]  ·  claude-sonnet-4-20250514  ·  json_mode=True  ·  tokens in/out=254/26
------------------------------------------------------------------------------
  ▸ SYSTEM:
      You are a forecasting agent in a multi-agent forecasting system.
      Your job:
      1) Gather evidence by issuing web/news search queries when needed.
      2) Then produce a binary probability forecast for the question.
      You must follow the action schema exactly and output valid JSON only.
      You must not browse prediction market prices unless they are explicitly
      provided.
  ▸ USER:
      QUESTION:
      Will the US enter a recession by the end of 2026?
      MARKET CONTEXT:
      Resolves YES if US real GDP (seasonally adjusted annualized) contracts
      for two consecutive quarters between Q2 2025 and Q4 2026, or the NBER
      declares a recession dated within that window.
      MARKET IMPLIED PROBABILITY (p_yes):
      0.175
      NEXT ACTION SCHEMA (output JSON only):
      If you need more info:
      {"action":"search","query":"..."}
      If you are ready to forecast:
      {"action":"forecast","p_yes":0.XX,"rationale":"short explanation
      grounded in evidence and base rates"}
      Pick exactly one action.
  ◂ RESPONSE:
      {"action":"search","query":"US GDP growth forecast 2025 2026 recession
      indicators economic outlook"}

==============================================================================
  CALL #3 [agent_0]  ·  claude-sonnet-4-20250514  ·  json_mode=True  ·  tokens in/out=3206/28
------------------------------------------------------------------------------
  ▸ SYSTEM:
      You are a forecasting agent in a multi-agent forecasting system.
      Your job:
      1) Gather evidence by issuing web/news search queries when needed.
      2) Then produce a binary probability forecast for the question.
      You must follow the action schema exactly and output valid JSON only.
      You must not browse prediction market prices unless they are explicitly
      provided.
  ▸ USER:
      QUESTION:
      Will the US enter a recession by the end of 2026?
      MARKET CONTEXT:
      Resolves YES if US real GDP (seasonally adjusted annualized) contracts
      for two consecutive quarters between Q2 2025 and Q4 2026, or the NBER
      declares a recession dated within that window.
      MARKET IMPLIED PROBABILITY (p_yes):
      0.175
      NEXT ACTION SCHEMA (output JSON only):
      If you need more info:
      {"action":"search","query":"..."}
      If you are ready to forecast:
      {"action":"forecast","p_yes":0.XX,"rationale":"short explanation
      grounded in evidence and base rates"}
      Pick exactly one action.
  ▸ ASSISTANT:
      {"action":"search","query":"US GDP growth forecast 2025 2026 recession
      indicators economic outlook"}
  ▸ TOOL:
      SEARCH RESULTS:
      1. U.S. outlook for 2026 - Indiana Business Research Center
      URL: https://www.ibrc.indiana.edu/ibr/2025/outlook/national.html
      The IBR is a publication of the Indiana Business Research Center at IU's
      Kelley School of Business. *Recent developments in the U.S. and global
      economy present a complex and evolving picture for policymakers and
      business leaders. While our current readings of headline growth remain
      resilient — buoyed by strong investment in artificial intelligence, a
      resilient consumer and robust financial markets — underlying indicators
      suggest a more nuanced reali…
  ◂ RESPONSE:
      {"action":"search","query":"US recession probability 2025 2026 NBER
      recession indicators economic risks"}

==============================================================================
  CALL #6 [agent_0]  ·  claude-sonnet-4-20250514  ·  json_mode=True  ·  tokens in/out=4267/29
------------------------------------------------------------------------------
  ▸ SYSTEM:
      You are a forecasting agent in a multi-agent forecasting system.
      Your job:
      1) Gather evidence by issuing web/news search queries when needed.
      2) Then produce a binary probability forecast for the question.
      You must follow the action schema exactly and output valid JSON only.
      You must not browse prediction market prices unless they are explicitly
      provided.
  ▸ USER:
      QUESTION:
      Will the US enter a recession by the end of 2026?
      MARKET CONTEXT:
      Resolves YES if US real GDP (seasonally adjusted annualized) contracts
      for two consecutive quarters between Q2 2025 and Q4 2026, or the NBER
      declares a recession dated within that window.
      MARKET IMPLIED PROBABILITY (p_yes):
      0.175
      NEXT ACTION SCHEMA (output JSON only):
      If you need more info:
      {"action":"search","query":"..."}
      If you are ready to forecast:
      {"action":"forecast","p_yes":0.XX,"rationale":"short explanation
      grounded in evidence and base rates"}
      Pick exactly one action.
  ▸ ASSISTANT:
      {"action":"search","query":"US GDP growth forecast 2025 2026 recession
      indicators economic outlook"}
  ▸ TOOL:
      SEARCH RESULTS:
      1. U.S. outlook for 2026 - Indiana Business Research Center
      URL: https://www.ibrc.indiana.edu/ibr/2025/outlook/national.html
      The IBR is a publication of the Indiana Business Research Center at IU's
      Kelley School of Business. *Recent developments in the U.S. and global
      economy present a complex and evolving picture for policymakers and
      business leaders. While our current readings of headline growth remain
      resilient — buoyed by strong investment in artificial intelligence, a
      resilient consumer and robust financial markets — underlying indicators
      suggest a more nuanced reali…
  ▸ ASSISTANT:
      {"action":"search","query":"US recession probability 2025 2026 NBER
      recession indicators economic risks"}
  ▸ TOOL:
      SEARCH RESULTS:
      1. [PDF] Probability of US Recession Predicted by Treasury Spread
      URL: https://www.newyorkfed.org/medialibrary/media/research/capital_mark
      ets/prob_rec.pdf
      Probability of US Recession Predicted by Treasury Spread* Treasury
      Spread: 10 yr bond rate-3 month bill rate Monthly Average (Percent) 1959
      1961 1963 1965 1967 1969 1971 1973 1975 1977 1979 1981 1983 1985 1987
      1989 1991 1993 1995 1997 1999 2001 2003 2005 2007 2009 2011 2013 2015
      2017 2019 2021 2023 2025 May 2026 = 0.79648 -4 -3 -2 -1 0 1 2 3 4 5
      Twelve Months Ahead (month averages) 1961 1963 1965 1967 1969 1971 1973
      197…
  ◂ RESPONSE:
      {"action":"search","query":"Federal Reserve interest rates 2025 2026
      monetary policy inflation unemployment current economic conditions"}

==============================================================================
  CALL #9 [agent_0]  ·  claude-sonnet-4-20250514  ·  json_mode=True  ·  tokens in/out=4693/159
------------------------------------------------------------------------------
  ▸ SYSTEM:
      You are a forecasting agent in a multi-agent forecasting system.
      Your job:
      1) Gather evidence by issuing web/news search queries when needed.
      2) Then produce a binary probability forecast for the question.
      You must follow the action schema exactly and output valid JSON only.
      You must not browse prediction market prices unless they are explicitly
      provided.
  ▸ USER:
      QUESTION:
      Will the US enter a recession by the end of 2026?
      MARKET CONTEXT:
      Resolves YES if US real GDP (seasonally adjusted annualized) contracts
      for two consecutive quarters between Q2 2025 and Q4 2026, or the NBER
      declares a recession dated within that window.
      MARKET IMPLIED PROBABILITY (p_yes):
      0.175
      NEXT ACTION SCHEMA (output JSON only):
      If you need more info:
      {"action":"search","query":"..."}
      If you are ready to forecast:
      {"action":"forecast","p_yes":0.XX,"rationale":"short explanation
      grounded in evidence and base rates"}
      Pick exactly one action.
  ▸ ASSISTANT:
      {"action":"search","query":"US GDP growth forecast 2025 2026 recession
      indicators economic outlook"}
  ▸ TOOL:
      SEARCH RESULTS:
      1. U.S. outlook for 2026 - Indiana Business Research Center
      URL: https://www.ibrc.indiana.edu/ibr/2025/outlook/national.html
      The IBR is a publication of the Indiana Business Research Center at IU's
      Kelley School of Business. *Recent developments in the U.S. and global
      economy present a complex and evolving picture for policymakers and
      business leaders. While our current readings of headline growth remain
      resilient — buoyed by strong investment in artificial intelligence, a
      resilient consumer and robust financial markets — underlying indicators
      suggest a more nuanced reali…
  ▸ ASSISTANT:
      {"action":"search","query":"US recession probability 2025 2026 NBER
      recession indicators economic risks"}
  ▸ TOOL:
      SEARCH RESULTS:
      1. [PDF] Probability of US Recession Predicted by Treasury Spread
      URL: https://www.newyorkfed.org/medialibrary/media/research/capital_mark
      ets/prob_rec.pdf
      Probability of US Recession Predicted by Treasury Spread* Treasury
      Spread: 10 yr bond rate-3 month bill rate Monthly Average (Percent) 1959
      1961 1963 1965 1967 1969 1971 1973 1975 1977 1979 1981 1983 1985 1987
      1989 1991 1993 1995 1997 1999 2001 2003 2005 2007 2009 2011 2013 2015
      2017 2019 2021 2023 2025 May 2026 = 0.79648 -4 -3 -2 -1 0 1 2 3 4 5
      Twelve Months Ahead (month averages) 1961 1963 1965 1967 1969 1971 1973
      197…
  ▸ ASSISTANT:
      {"action":"search","query":"Federal Reserve interest rates 2025 2026
      monetary policy inflation unemployment current economic conditions"}
  ▸ TOOL:
      SEARCH RESULTS:
      1. Fed Outlook 2026: Rate Forecasts and Fixed Income Strategies
      URL: https://www.ishares.com/us/insights/fed-outlook-2026-interest-rate-
      forecast
      We believe the most likely path for Fed policy in 2026 is for the
      central bank to bring rates down from the current range of 3.50% to
      3.75%
      2. Minutes of the Federal Open Market Committee
      URL:
      https://www.federalreserve.gov/monetarypolicy/fomcminutes20250917.htm
      In their consideration of monetary policy at this meeting, participants
      noted that inflation had risen recently and remained somewhat elevated,
      3. The Economic Ou…
  ◂ RESPONSE:
      {"action":"forecast","p_yes":0.12,"rationale":"Multiple forecasts show
      positive GDP growth for 2025-2026: Indiana Business Research Center
      forecasts 1.8% real GDP growth in 2026, Deloitte expects 4% business
      investment growth, and Fed officials project growth near potential.
      Current recession probability models show low risk (0.44% as of April
      2026, NY Fed treasury spread model at ~15% for 12-months ahead). While
      some economic headwinds exist (softening labor market, elevated
      deficits), the consensus forecasts positive growth through 2026. The
      market implied probability of 17.5% appears slight…

## Key Takeaways

1. **Identical agents diverge, and that is the panel's entire value.** Nothing distinguishes
   these three: same prompt, same tools, same client, same sampling temperature. Three
   different answers come out anyway, from the model's sampling and from what each agent's
   searches returned, in proportions this run does not separate.
2. **A panel is only worth aggregating if its members are worth aggregating separately.**
   Read the timelines before the aggregate. Agents converging by different routes is evidence;
   agents pulling identical documents and reasoning in step is one agent run three times, and
   the aggregate will report false confidence.
3. **Extremization moves the answer more than the panel does.** Sweeping the correlation
   assumption over the same three forecasts moves the aggregate further than the forecasts
   themselves are apart. With no estimate of that correlation, the mean is the number to
   report and the Neyman values are a sensitivity analysis around it.
4. **An agent handed the market's own probability is not an independent check on it.** This
   capture put the market price in every prompt, so the agents' proximity to it is not
   evidence about their skill.
5. **Parallelism is a thread pool and a per-agent tracer.** Agents share the model client and
   the search client, so both have to be safe under concurrent calls; each gets its own
   tracer, which is what keeps the captured conversations correctly attributed.

**Known limitations of what is built here.** One capture, one question, three agents: the
spread has no error bar and nothing establishes it would recur. The confidence values feeding
the weighted aggregate are the extremity heuristic from
[`04_research_agent`](04_research_agent.ipynb), not measured skill. No retrieved result
carries a publication date, so nothing here can be scored as a point-in-time forecast. And
the agents differ only by sampling: a panel built to be diverse would vary the model, the
search index, or the framing of the question.

**Next**: [`07_adversarial_debate`](07_adversarial_debate.ipynb) takes a panel that disagrees
and makes the disagreement do work, by having the agents argue the two sides.

**Book**: Section 24.7 presents multi-agent forecasting systems.