# Tabular Deep Learning - FX Pairs

TabM applies a small neural network to each decision row without turning the history into a
sequence. This notebook submits the published capacity choices to the shared TabM runner. The
runner fits preprocessing inside each training fold, saves every declared weight checkpoint, and
publishes a separate complete validation prediction set for every checkpoint.

**Learning objectives**

- Express neural-network capacity and checkpoint schedules as visible requests.
- Verify that every fold and epoch checkpoint has reloadable fitted state.
- Continue from complete prediction rows without selecting a checkpoint by rank correlation.

**Book reference**: Chapter 12, Section 12.3

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published TabM FX configurations."""

import polars as pl
import yaml

from case_studies.research import ExecutionTier, Study, plan_models
from utils.modeling import load_configs
from utils.paths import get_case_study_dir
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
BATCH_SIZE = 0
DEVICE = "cuda"
SEED = 42

## Select the task and execution tier

Canonical execution uses every configured fold, symbol, epoch, and batch setting. Supplying a
reduction creates a preview identity in an isolated registry. A preview proves the path but cannot
join the official model population.

In [3]:
set_global_seeds(SEED)
case_dir = get_case_study_dir(CASE_STUDY_ID)
setup = yaml.safe_load((case_dir / "config" / "setup.yaml").read_text())
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [setup["labels"]["primary"], *setup["labels"].get("variants", [])]
)

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

reductions = {
    **({"folds": list(range(MAX_FOLDS))} if MAX_FOLDS else {}),
    **({"max_symbols": MAX_SYMBOLS} if MAX_SYMBOLS else {}),
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
}
tier = ExecutionTier.PREVIEW if reductions else ExecutionTier.CANONICAL
study = Study.regenerate(CASE_STUDY_ID)

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {DEVICE}")

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda

## Build the published requests

The YAML menu supplies the architecture settings and production checkpoint schedules. The
parameter cell can reduce epochs or change batch size for a preview without changing the menu.

In [4]:
overrides = {
    "device": DEVICE,
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
}
menu = [
    (label, config)
    for label in labels
    for config in load_configs(CASE_STUDY_ID, label, family="tabular_dl")
]
requests = [
    study.model(
        family="tabular_dl",
        label=label,
        config_name=config["config_name"],
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label, config in menu
]

pl.DataFrame(
    {
        "config_name": [request.config_name for request in requests],
        "label": [request.label for request in requests],
        "device": [DEVICE] * len(requests),
        "execution_tier": [request.execution_tier.value for request in requests],
    }
)

shape: (9, 4)
┌─────────────┬─────────────┬────────┬────────────────┐
│ config_name ┆ label       ┆ device ┆ execution_tier │
│ ---         ┆ ---         ┆ ---    ┆ ---            │
│ str         ┆ str         ┆ str    ┆ str            │
╞═════════════╪═════════════╪════════╪════════════════╡
│ tabm_s      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_s      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_s      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
└─────────────┴─────────────┴────────┴────────────────┘

## Declare every epoch checkpoint before training

The declared epoch schedule, not the run that follows, decides how many downstream configurations
this notebook owes. Planning resolves each one without training, so a failed member is visible as
a gap in the population rather than a shorter catalog.

In [5]:
plan = plan_models(study, requests=requests)
if len(plan.expected_training_hashes) != len(requests):
    raise RuntimeError("each TabM configuration must plan exactly one training identity")

configured = {(label, config["config_name"]) for label, config in menu}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        "the plan does not match the configured TabM menu; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )

pl.DataFrame(
    {
        "label": [member.label for member in plan.members],
        "config_name": [member.config_name for member in plan.members],
        "checkpoint_kind": [member.checkpoint_kind for member in plan.members],
        "checkpoint_value": [member.checkpoint_value for member in plan.members],
        "prediction_hash": [member.prediction_hash for member in plan.members],
    }
)

shape: (72, 5)
┌─────────────┬─────────────┬─────────────────┬──────────────────┬─────────────────┐
│ label       ┆ config_name ┆ checkpoint_kind ┆ checkpoint_value ┆ prediction_hash │
│ ---         ┆ ---         ┆ ---             ┆ ---              ┆ ---             │
│ str         ┆ str         ┆ str             ┆ i64              ┆ str             │
╞═════════════╪═════════════╪═════════════════╪══════════════════╪═════════════════╡
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 25               ┆ 243c981790e5    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 50               ┆ fce2b00758da    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 75               ┆ 91868fa741e6    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 100              ┆ 7bfe5132ffdf    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 125              ┆ 18cee173f0dc    │
│ …           ┆ …           ┆ …               ┆ …                ┆ …               │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 100              ┆ dc71fa146a3d    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 125              ┆ 03e9540dbeb8    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 150              ┆ 615228463a26    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 175              ┆ 0e43990927ac    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 200              ┆ ebda68c5bb3c    │
└─────────────┴─────────────┴─────────────────┴──────────────────┴─────────────────┘

## Record the official population, then fit or reload every capacity choice

Compatible TabM requests share base-fold materialization. Candidate-specific scaling, random
state, weights, and prediction identities remain separate. Any failed member stops the cell.

In [6]:
population = (
    plan.create_population(name=f"{CASE_STUDY_ID}:{'+'.join(labels)}:tabular_dl")
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
if len(execution.runs) != len(requests):
    raise RuntimeError("the TabM runner did not return every requested configuration")

catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial TabM checkpoints cannot pass to backtesting")
if catalog.select("label", "config_name", "checkpoint_value").n_unique() != catalog.height:
    raise RuntimeError("each configuration and epoch checkpoint must identify one prediction set")
if catalog.get_column("checkpoint_value").null_count():
    raise RuntimeError("every TabM prediction must name its epoch checkpoint")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Preparing and releasing folds...

  Fold 0: train=25,780  val=5,140

      epoch  25/200: loss=0.000029, IC=-0.0069

      epoch  50/200: loss=0.000028, IC=+0.0007

      epoch  75/200: loss=0.000027, IC=+0.0056

      epoch 100/200: loss=0.000027, IC=+0.0204

      epoch 125/200: loss=0.000027, IC=+0.0235

      epoch 150/200: loss=0.000026, IC=+0.0236

      epoch 175/200: loss=0.000026, IC=+0.0233

      epoch 200/200: loss=0.000026, IC=+0.0246

    Fold 0: best_ep=200, IC=+0.0246 (4.8s)

      epoch  25/200: loss=0.000027, IC=+0.0028

      epoch  50/200: loss=0.000024, IC=+0.0116

      epoch  75/200: loss=0.000023, IC=+0.0056

      epoch 100/200: loss=0.000022, IC=-0.0031

      epoch 125/200: loss=0.000021, IC=-0.0065

      epoch 150/200: loss=0.000021, IC=-0.0114

      epoch 175/200: loss=0.000020, IC=-0.0131

      epoch 200/200: loss=0.000020, IC=-0.0125

    Fold 0: best_ep=50, IC=+0.0116 (5.6s)

      epoch  25/200: loss=0.000026, IC=+0.0125

      epoch  50/200: loss=0.000022, IC=+0.0231

      epoch  75/200: loss=0.000020, IC=+0.0161

      epoch 100/200: loss=0.000018, IC=+0.0300

      epoch 125/200: loss=0.000017, IC=+0.0254

      epoch 150/200: loss=0.000016, IC=+0.0230

      epoch 175/200: loss=0.000016, IC=+0.0249

      epoch 200/200: loss=0.000016, IC=+0.0249

    Fold 0: best_ep=100, IC=+0.0300 (7.8s)

  Fold 1: train=25,780  val=5,160

      epoch  25/200: loss=0.000026, IC=-0.0062

      epoch  50/200: loss=0.000025, IC=-0.0436

      epoch  75/200: loss=0.000024, IC=-0.0559

      epoch 100/200: loss=0.000023, IC=-0.0640

      epoch 125/200: loss=0.000023, IC=-0.0616

      epoch 150/200: loss=0.000023, IC=-0.0603

      epoch 175/200: loss=0.000023, IC=-0.0587

      epoch 200/200: loss=0.000023, IC=-0.0589

    Fold 1: best_ep=25, IC=-0.0062 (3.9s)

      epoch  25/200: loss=0.000022, IC=-0.0289

      epoch  50/200: loss=0.000021, IC=-0.0156

      epoch  75/200: loss=0.000019, IC=-0.0252

      epoch 100/200: loss=0.000018, IC=-0.0273

      epoch 125/200: loss=0.000018, IC=-0.0309

      epoch 150/200: loss=0.000017, IC=-0.0280

      epoch 175/200: loss=0.000017, IC=-0.0290

      epoch 200/200: loss=0.000017, IC=-0.0274

    Fold 1: best_ep=50, IC=-0.0156 (5.0s)

      epoch  25/200: loss=0.000022, IC=-0.0383

      epoch  50/200: loss=0.000020, IC=-0.0225

      epoch  75/200: loss=0.000018, IC=-0.0300

      epoch 100/200: loss=0.000017, IC=-0.0295

      epoch 125/200: loss=0.000016, IC=-0.0346

      epoch 150/200: loss=0.000015, IC=-0.0314

      epoch 175/200: loss=0.000015, IC=-0.0325

      epoch 200/200: loss=0.000015, IC=-0.0322

    Fold 1: best_ep=50, IC=-0.0225 (7.0s)

  Fold 2: train=25,780  val=5,160

      epoch  25/200: loss=0.000032, IC=-0.0223

      epoch  50/200: loss=0.000030, IC=-0.0055

      epoch  75/200: loss=0.000028, IC=-0.0208

      epoch 100/200: loss=0.000027, IC=-0.0120

      epoch 125/200: loss=0.000027, IC=-0.0131

      epoch 150/200: loss=0.000027, IC=-0.0095

      epoch 175/200: loss=0.000026, IC=-0.0094

      epoch 200/200: loss=0.000026, IC=-0.0080

    Fold 2: best_ep=50, IC=-0.0055 (4.0s)

      epoch  25/200: loss=0.000030, IC=-0.0287

      epoch  50/200: loss=0.000026, IC=-0.0137

      epoch  75/200: loss=0.000024, IC=-0.0124

      epoch 100/200: loss=0.000023, IC=-0.0082

      epoch 125/200: loss=0.000022, IC=-0.0125

      epoch 150/200: loss=0.000022, IC=-0.0081

      epoch 175/200: loss=0.000022, IC=-0.0126

      epoch 200/200: loss=0.000022, IC=-0.0114

    Fold 2: best_ep=150, IC=-0.0081 (5.0s)

      epoch  25/200: loss=0.000030, IC=-0.0321

      epoch  50/200: loss=0.000025, IC=+0.0028

      epoch  75/200: loss=0.000022, IC=+0.0008

      epoch 100/200: loss=0.000020, IC=+0.0034

      epoch 125/200: loss=0.000019, IC=+0.0051

      epoch 150/200: loss=0.000018, IC=-0.0006

      epoch 175/200: loss=0.000018, IC=+0.0064

      epoch 200/200: loss=0.000018, IC=+0.0068

    Fold 2: best_ep=200, IC=+0.0068 (7.4s)

  Fold 3: train=25,780  val=5,160

      epoch  25/200: loss=0.000049, IC=-0.0331

      epoch  50/200: loss=0.000042, IC=-0.0360

      epoch  75/200: loss=0.000041, IC=-0.0429

      epoch 100/200: loss=0.000042, IC=-0.0524

      epoch 125/200: loss=0.000041, IC=-0.0571

      epoch 150/200: loss=0.000038, IC=-0.0522

      epoch 175/200: loss=0.000041, IC=-0.0543

      epoch 200/200: loss=0.000039, IC=-0.0543

    Fold 3: best_ep=25, IC=-0.0331 (4.0s)

      epoch  25/200: loss=0.000037, IC=-0.0272

      epoch  50/200: loss=0.000033, IC=-0.0038

      epoch  75/200: loss=0.000030, IC=-0.0087

      epoch 100/200: loss=0.000029, IC=-0.0040

      epoch 125/200: loss=0.000027, IC=-0.0019

      epoch 150/200: loss=0.000027, IC=-0.0011

      epoch 175/200: loss=0.000026, IC=-0.0004

      epoch 200/200: loss=0.000026, IC=-0.0005

    Fold 3: best_ep=175, IC=-0.0004 (5.0s)

      epoch  25/200: loss=0.000037, IC=-0.0165

      epoch  50/200: loss=0.000031, IC=-0.0275

      epoch  75/200: loss=0.000027, IC=-0.0048

      epoch 100/200: loss=0.000024, IC=-0.0093

      epoch 125/200: loss=0.000022, IC=-0.0056

      epoch 150/200: loss=0.000021, IC=-0.0086

      epoch 175/200: loss=0.000022, IC=-0.0098

      epoch 200/200: loss=0.000020, IC=-0.0105

    Fold 3: best_ep=75, IC=-0.0048 (7.1s)

  Fold 4: train=25,780  val=5,160

      epoch  25/200: loss=0.000058, IC=-0.0138

      epoch  50/200: loss=0.000049, IC=+0.0001

      epoch  75/200: loss=0.000043, IC=+0.0149

      epoch 100/200: loss=0.000043, IC=+0.0189

      epoch 125/200: loss=0.000044, IC=+0.0256

      epoch 150/200: loss=0.000042, IC=+0.0247

      epoch 175/200: loss=0.000041, IC=+0.0255

      epoch 200/200: loss=0.000041, IC=+0.0250

    Fold 4: best_ep=125, IC=+0.0256 (3.9s)

      epoch  25/200: loss=0.000045, IC=+0.0196

      epoch  50/200: loss=0.000043, IC=+0.0279

      epoch  75/200: loss=0.000039, IC=+0.0264

      epoch 100/200: loss=0.000039, IC=+0.0244

      epoch 125/200: loss=0.000041, IC=+0.0184

      epoch 150/200: loss=0.000038, IC=+0.0241

      epoch 175/200: loss=0.000037, IC=+0.0205

      epoch 200/200: loss=0.000038, IC=+0.0201

    Fold 4: best_ep=50, IC=+0.0279 (5.1s)

      epoch  25/200: loss=0.000037, IC=+0.0067

      epoch  50/200: loss=0.000034, IC=+0.0245

      epoch  75/200: loss=0.000028, IC=+0.0267

      epoch 100/200: loss=0.000025, IC=+0.0269

      epoch 125/200: loss=0.000025, IC=+0.0284

      epoch 150/200: loss=0.000021, IC=+0.0290

      epoch 175/200: loss=0.000021, IC=+0.0310

      epoch 200/200: loss=0.000022, IC=+0.0299

    Fold 4: best_ep=175, IC=+0.0310 (8.1s)

  Fold 5: train=25,780  val=5,160

      epoch  25/200: loss=0.000042, IC=+0.0151

      epoch  50/200: loss=0.000039, IC=+0.0096

      epoch  75/200: loss=0.000037, IC=+0.0101

      epoch 100/200: loss=0.000037, IC=+0.0084

      epoch 125/200: loss=0.000035, IC=+0.0106

      epoch 150/200: loss=0.000036, IC=+0.0079

      epoch 175/200: loss=0.000035, IC=+0.0073

      epoch 200/200: loss=0.000035, IC=+0.0064

    Fold 5: best_ep=25, IC=+0.0151 (4.6s)

      epoch  25/200: loss=0.000042, IC=+0.0256

      epoch  50/200: loss=0.000040, IC=+0.0386

      epoch  75/200: loss=0.000037, IC=+0.0474

      epoch 100/200: loss=0.000035, IC=+0.0395

      epoch 125/200: loss=0.000034, IC=+0.0500

      epoch 150/200: loss=0.000035, IC=+0.0430

      epoch 175/200: loss=0.000033, IC=+0.0429

      epoch 200/200: loss=0.000033, IC=+0.0421

    Fold 5: best_ep=125, IC=+0.0500 (5.6s)

      epoch  25/200: loss=0.000040, IC=-0.0002

      epoch  50/200: loss=0.000035, IC=+0.0167

      epoch  75/200: loss=0.000031, IC=+0.0104

      epoch 100/200: loss=0.000028, IC=+0.0180

      epoch 125/200: loss=0.000026, IC=+0.0276

      epoch 150/200: loss=0.000024, IC=+0.0314

      epoch 175/200: loss=0.000023, IC=+0.0309

      epoch 200/200: loss=0.000024, IC=+0.0300

    Fold 5: best_ep=150, IC=+0.0314 (8.1s)

  Fold 6: train=23,420  val=5,160

      epoch  25/200: loss=0.000048, IC=-0.0104

      epoch  50/200: loss=0.000045, IC=-0.0139

      epoch  75/200: loss=0.000045, IC=-0.0093

      epoch 100/200: loss=0.000043, IC=-0.0103

      epoch 125/200: loss=0.000043, IC=-0.0095

      epoch 150/200: loss=0.000043, IC=-0.0080

      epoch 175/200: loss=0.000042, IC=-0.0067

      epoch 200/200: loss=0.000042, IC=-0.0055

    Fold 6: best_ep=200, IC=-0.0055 (3.9s)

      epoch  25/200: loss=0.000045, IC=-0.0213

      epoch  50/200: loss=0.000043, IC=-0.0129

      epoch  75/200: loss=0.000041, IC=-0.0029

      epoch 100/200: loss=0.000038, IC=-0.0031

      epoch 125/200: loss=0.000037, IC=+0.0006

      epoch 150/200: loss=0.000037, IC=+0.0015

      epoch 175/200: loss=0.000036, IC=+0.0037

      epoch 200/200: loss=0.000036, IC=+0.0035

    Fold 6: best_ep=175, IC=+0.0037 (4.8s)

      epoch  25/200: loss=0.000041, IC=+0.0297

      epoch  50/200: loss=0.000036, IC=+0.0135

      epoch  75/200: loss=0.000031, IC=-0.0006

      epoch 100/200: loss=0.000026, IC=-0.0188

      epoch 125/200: loss=0.000024, IC=-0.0148

      epoch 150/200: loss=0.000023, IC=-0.0194

      epoch 175/200: loss=0.000023, IC=-0.0208

      epoch 200/200: loss=0.000022, IC=-0.0190

    Fold 6: best_ep=25, IC=+0.0297 (6.8s)

  Fold 7: train=18,260  val=5,160

      epoch  25/200: loss=0.000052, IC=-0.0044

      epoch  50/200: loss=0.000045, IC=-0.0051

      epoch  75/200: loss=0.000043, IC=-0.0070

      epoch 100/200: loss=0.000041, IC=-0.0087

      epoch 125/200: loss=0.000044, IC=-0.0137

      epoch 150/200: loss=0.000040, IC=-0.0174

      epoch 175/200: loss=0.000044, IC=-0.0195

      epoch 200/200: loss=0.000040, IC=-0.0200

    Fold 7: best_ep=25, IC=-0.0044 (3.0s)

      epoch  25/200: loss=0.000046, IC=+0.0066

      epoch  50/200: loss=0.000042, IC=+0.0085

      epoch  75/200: loss=0.000040, IC=+0.0175

      epoch 100/200: loss=0.000038, IC=+0.0229

      epoch 125/200: loss=0.000040, IC=+0.0169

      epoch 150/200: loss=0.000036, IC=+0.0114

      epoch 175/200: loss=0.000039, IC=+0.0129

      epoch 200/200: loss=0.000036, IC=+0.0114

    Fold 7: best_ep=100, IC=+0.0229 (4.1s)

      epoch  25/200: loss=0.000042, IC=+0.0058

      epoch  50/200: loss=0.000034, IC=+0.0196

      epoch  75/200: loss=0.000029, IC=+0.0048

      epoch 100/200: loss=0.000024, IC=+0.0129

      epoch 125/200: loss=0.000024, IC=+0.0049

      epoch 150/200: loss=0.000021, IC=+0.0074

      epoch 175/200: loss=0.000022, IC=+0.0055

      epoch 200/200: loss=0.000021, IC=+0.0063

    Fold 7: best_ep=50, IC=+0.0196 (5.7s)

    → best_epoch=25, IC=-0.0103 (32.2s)

    → best_epoch=75, IC=+0.0060 (40.4s)

    → best_epoch=50, IC=+0.0063 (58.0s)

  Best: 2b929abc9475 @ epoch 50 (IC=+0.0063)

Preparing and releasing folds...
  Fold 0: train=25,700  val=5,060

      epoch  25/200: loss=0.000131, IC=-0.0387

      epoch  50/200: loss=0.000115, IC=-0.0391

      epoch  75/200: loss=0.000105, IC=-0.0299

      epoch 100/200: loss=0.000098, IC=-0.0395

      epoch 125/200: loss=0.000095, IC=-0.0333

      epoch 150/200: loss=0.000092, IC=-0.0357

      epoch 175/200: loss=0.000090, IC=-0.0379

      epoch 200/200: loss=0.000091, IC=-0.0393

    Fold 0: best_ep=75, IC=-0.0299 (4.4s)

      epoch  25/200: loss=0.000102, IC=-0.0544

      epoch  50/200: loss=0.000080, IC=-0.0556

      epoch  75/200: loss=0.000069, IC=-0.0426

      epoch 100/200: loss=0.000063, IC=-0.0364

      epoch 125/200: loss=0.000060, IC=-0.0346

      epoch 150/200: loss=0.000058, IC=-0.0334

      epoch 175/200: loss=0.000056, IC=-0.0337

      epoch 200/200: loss=0.000056, IC=-0.0335

    Fold 0: best_ep=150, IC=-0.0334 (5.6s)

      epoch  25/200: loss=0.000087, IC=-0.0538

      epoch  50/200: loss=0.000063, IC=-0.0560

      epoch  75/200: loss=0.000050, IC=-0.0498

      epoch 100/200: loss=0.000044, IC=-0.0442

      epoch 125/200: loss=0.000040, IC=-0.0407

      epoch 150/200: loss=0.000038, IC=-0.0394

      epoch 175/200: loss=0.000037, IC=-0.0414

      epoch 200/200: loss=0.000037, IC=-0.0413

    Fold 0: best_ep=150, IC=-0.0394 (8.9s)

  Fold 1: train=25,700  val=5,160

      epoch  25/200: loss=0.000113, IC=-0.0634

      epoch  50/200: loss=0.000101, IC=-0.0645

      epoch  75/200: loss=0.000095, IC=-0.0327

      epoch 100/200: loss=0.000091, IC=-0.0395

      epoch 125/200: loss=0.000088, IC=-0.0466

      epoch 150/200: loss=0.000085, IC=-0.0485

      epoch 175/200: loss=0.000085, IC=-0.0516

      epoch 200/200: loss=0.000085, IC=-0.0508

    Fold 1: best_ep=75, IC=-0.0327 (4.4s)

      epoch  25/200: loss=0.000085, IC=-0.0319

      epoch  50/200: loss=0.000069, IC=-0.0472

      epoch  75/200: loss=0.000059, IC=-0.0574

      epoch 100/200: loss=0.000055, IC=-0.0665

      epoch 125/200: loss=0.000052, IC=-0.0662

      epoch 150/200: loss=0.000050, IC=-0.0643

      epoch 175/200: loss=0.000050, IC=-0.0658

      epoch 200/200: loss=0.000050, IC=-0.0657

    Fold 1: best_ep=25, IC=-0.0319 (5.6s)

      epoch  25/200: loss=0.000077, IC=-0.0368

      epoch  50/200: loss=0.000055, IC=-0.0434

      epoch  75/200: loss=0.000045, IC=-0.0550

      epoch 100/200: loss=0.000039, IC=-0.0455

      epoch 125/200: loss=0.000036, IC=-0.0492

      epoch 150/200: loss=0.000033, IC=-0.0434

      epoch 175/200: loss=0.000032, IC=-0.0462

      epoch 200/200: loss=0.000033, IC=-0.0476

    Fold 1: best_ep=25, IC=-0.0368 (7.7s)

  Fold 2: train=25,700  val=5,160

      epoch  25/200: loss=0.000134, IC=+0.0038

      epoch  50/200: loss=0.000114, IC=+0.0151

      epoch  75/200: loss=0.000101, IC=+0.0185

      epoch 100/200: loss=0.000096, IC=+0.0206

      epoch 125/200: loss=0.000093, IC=+0.0149

      epoch 150/200: loss=0.000091, IC=+0.0160

      epoch 175/200: loss=0.000091, IC=+0.0147

      epoch 200/200: loss=0.000091, IC=+0.0145

    Fold 2: best_ep=100, IC=+0.0206 (4.4s)

      epoch  25/200: loss=0.000117, IC=+0.0216

      epoch  50/200: loss=0.000093, IC=+0.0285

      epoch  75/200: loss=0.000080, IC=+0.0284

      epoch 100/200: loss=0.000073, IC=+0.0155

      epoch 125/200: loss=0.000069, IC=+0.0132

      epoch 150/200: loss=0.000067, IC=+0.0103

      epoch 175/200: loss=0.000066, IC=+0.0067

      epoch 200/200: loss=0.000065, IC=+0.0060

    Fold 2: best_ep=50, IC=+0.0285 (6.1s)

      epoch  25/200: loss=0.000103, IC=+0.0189

      epoch  50/200: loss=0.000071, IC=+0.0099

      epoch  75/200: loss=0.000057, IC=+0.0039

      epoch 100/200: loss=0.000050, IC=-0.0057

      epoch 125/200: loss=0.000044, IC=+0.0076

      epoch 150/200: loss=0.000043, IC=+0.0045

      epoch 175/200: loss=0.000041, IC=+0.0037

      epoch 200/200: loss=0.000041, IC=+0.0037

    Fold 2: best_ep=25, IC=+0.0189 (7.8s)

  Fold 3: train=25,700  val=5,160

      epoch  25/200: loss=0.000184, IC=-0.0773

      epoch  50/200: loss=0.000168, IC=-0.0694

      epoch  75/200: loss=0.000161, IC=-0.0621

      epoch 100/200: loss=0.000156, IC=-0.0580

      epoch 125/200: loss=0.000148, IC=-0.0650

      epoch 150/200: loss=0.000147, IC=-0.0661

      epoch 175/200: loss=0.000143, IC=-0.0679

      epoch 200/200: loss=0.000143, IC=-0.0683

    Fold 3: best_ep=100, IC=-0.0580 (4.5s)

      epoch  25/200: loss=0.000133, IC=-0.0299

      epoch  50/200: loss=0.000105, IC=-0.0393

      epoch  75/200: loss=0.000091, IC=-0.0268

      epoch 100/200: loss=0.000085, IC=-0.0325

      epoch 125/200: loss=0.000078, IC=-0.0297

      epoch 150/200: loss=0.000074, IC=-0.0303

      epoch 175/200: loss=0.000074, IC=-0.0294

      epoch 200/200: loss=0.000073, IC=-0.0293

    Fold 3: best_ep=75, IC=-0.0268 (5.7s)

      epoch  25/200: loss=0.000115, IC=-0.0430

      epoch  50/200: loss=0.000080, IC=-0.0164

      epoch  75/200: loss=0.000063, IC=-0.0219

      epoch 100/200: loss=0.000055, IC=-0.0118

      epoch 125/200: loss=0.000050, IC=-0.0134

      epoch 150/200: loss=0.000047, IC=-0.0084

      epoch 175/200: loss=0.000046, IC=-0.0076

      epoch 200/200: loss=0.000046, IC=-0.0078

    Fold 3: best_ep=175, IC=-0.0076 (7.2s)

  Fold 4: train=25,700  val=5,160

      epoch  25/200: loss=0.000198, IC=-0.0490

      epoch  50/200: loss=0.000184, IC=-0.0327

      epoch  75/200: loss=0.000170, IC=-0.0081

      epoch 100/200: loss=0.000164, IC=-0.0027

      epoch 125/200: loss=0.000159, IC=-0.0006

      epoch 150/200: loss=0.000159, IC=+0.0028

      epoch 175/200: loss=0.000158, IC=-0.0015

      epoch 200/200: loss=0.000155, IC=-0.0018

    Fold 4: best_ep=150, IC=+0.0028 (4.1s)

      epoch  25/200: loss=0.000178, IC=-0.0211

      epoch  50/200: loss=0.000162, IC=-0.0138

      epoch  75/200: loss=0.000142, IC=+0.0047

      epoch 100/200: loss=0.000130, IC=+0.0138

      epoch 125/200: loss=0.000125, IC=+0.0140

      epoch 150/200: loss=0.000122, IC=+0.0151

      epoch 175/200: loss=0.000118, IC=+0.0177

      epoch 200/200: loss=0.000117, IC=+0.0141

    Fold 4: best_ep=175, IC=+0.0177 (5.6s)

      epoch  25/200: loss=0.000125, IC=-0.0049

      epoch  50/200: loss=0.000087, IC=-0.0015

      epoch  75/200: loss=0.000070, IC=+0.0137

      epoch 100/200: loss=0.000060, IC=+0.0166

      epoch 125/200: loss=0.000055, IC=-0.0000

      epoch 150/200: loss=0.000052, IC=+0.0021

      epoch 175/200: loss=0.000051, IC=+0.0083

      epoch 200/200: loss=0.000053, IC=+0.0061

    Fold 4: best_ep=100, IC=+0.0166 (7.6s)

  Fold 5: train=25,700  val=5,160

      epoch  25/200: loss=0.000171, IC=+0.0182

      epoch  50/200: loss=0.000152, IC=+0.0030

      epoch  75/200: loss=0.000136, IC=+0.0051

      epoch 100/200: loss=0.000128, IC=+0.0133

      epoch 125/200: loss=0.000124, IC=+0.0238

      epoch 150/200: loss=0.000118, IC=+0.0184

      epoch 175/200: loss=0.000117, IC=+0.0164

      epoch 200/200: loss=0.000120, IC=+0.0159

    Fold 5: best_ep=125, IC=+0.0238 (4.0s)

      epoch  25/200: loss=0.000167, IC=+0.0266

      epoch  50/200: loss=0.000130, IC=+0.0294

      epoch  75/200: loss=0.000108, IC=+0.0523

      epoch 100/200: loss=0.000098, IC=+0.0599

      epoch 125/200: loss=0.000091, IC=+0.0535

      epoch 150/200: loss=0.000087, IC=+0.0546

      epoch 175/200: loss=0.000085, IC=+0.0545

      epoch 200/200: loss=0.000088, IC=+0.0533

    Fold 5: best_ep=100, IC=+0.0599 (5.1s)

      epoch  25/200: loss=0.000134, IC=+0.0247

      epoch  50/200: loss=0.000094, IC=+0.0401

      epoch  75/200: loss=0.000076, IC=+0.0549

      epoch 100/200: loss=0.000064, IC=+0.0503

      epoch 125/200: loss=0.000059, IC=+0.0472

      epoch 150/200: loss=0.000055, IC=+0.0457

      epoch 175/200: loss=0.000053, IC=+0.0454

      epoch 200/200: loss=0.000055, IC=+0.0442

    Fold 5: best_ep=75, IC=+0.0549 (7.9s)

  Fold 6: train=23,340  val=5,160

      epoch  25/200: loss=0.000204, IC=-0.0385

      epoch  50/200: loss=0.000184, IC=+0.0132

      epoch  75/200: loss=0.000166, IC=+0.0064

      epoch 100/200: loss=0.000154, IC=-0.0148

      epoch 125/200: loss=0.000145, IC=-0.0263

      epoch 150/200: loss=0.000142, IC=-0.0265

      epoch 175/200: loss=0.000140, IC=-0.0268

      epoch 200/200: loss=0.000141, IC=-0.0255

    Fold 6: best_ep=50, IC=+0.0132 (3.5s)

      epoch  25/200: loss=0.000183, IC=+0.0038

      epoch  50/200: loss=0.000141, IC=-0.0315

      epoch  75/200: loss=0.000117, IC=-0.0324

      epoch 100/200: loss=0.000103, IC=-0.0394

      epoch 125/200: loss=0.000098, IC=-0.0457

      epoch 150/200: loss=0.000092, IC=-0.0433

      epoch 175/200: loss=0.000091, IC=-0.0426

      epoch 200/200: loss=0.000091, IC=-0.0420

    Fold 6: best_ep=25, IC=+0.0038 (4.4s)

      epoch  25/200: loss=0.000136, IC=-0.0296

      epoch  50/200: loss=0.000091, IC=-0.0476

      epoch  75/200: loss=0.000073, IC=-0.0374

      epoch 100/200: loss=0.000063, IC=-0.0261

      epoch 125/200: loss=0.000058, IC=-0.0247

      epoch 150/200: loss=0.000054, IC=-0.0241

      epoch 175/200: loss=0.000053, IC=-0.0277

      epoch 200/200: loss=0.000053, IC=-0.0274

    Fold 6: best_ep=150, IC=-0.0241 (6.2s)

  Fold 7: train=18,180  val=5,160

      epoch  25/200: loss=0.000196, IC=+0.0114

      epoch  50/200: loss=0.000180, IC=+0.0299

      epoch  75/200: loss=0.000166, IC=+0.0254

      epoch 100/200: loss=0.000156, IC=+0.0251

      epoch 125/200: loss=0.000149, IC=+0.0382

      epoch 150/200: loss=0.000147, IC=+0.0376

      epoch 175/200: loss=0.000145, IC=+0.0374

      epoch 200/200: loss=0.000139, IC=+0.0368

    Fold 7: best_ep=125, IC=+0.0382 (2.8s)

      epoch  25/200: loss=0.000179, IC=+0.0633

      epoch  50/200: loss=0.000138, IC=-0.0033

      epoch  75/200: loss=0.000115, IC=+0.0062

      epoch 100/200: loss=0.000106, IC=+0.0161

      epoch 125/200: loss=0.000096, IC=+0.0213

      epoch 150/200: loss=0.000093, IC=+0.0233

      epoch 175/200: loss=0.000092, IC=+0.0226

      epoch 200/200: loss=0.000091, IC=+0.0229

    Fold 7: best_ep=25, IC=+0.0633 (3.6s)

      epoch  25/200: loss=0.000128, IC=+0.0055

      epoch  50/200: loss=0.000082, IC=+0.0306

      epoch  75/200: loss=0.000064, IC=+0.0313

      epoch 100/200: loss=0.000059, IC=+0.0224

      epoch 125/200: loss=0.000053, IC=+0.0303

      epoch 150/200: loss=0.000049, IC=+0.0247

      epoch 175/200: loss=0.000047, IC=+0.0253

      epoch 200/200: loss=0.000046, IC=+0.0251

    Fold 7: best_ep=75, IC=+0.0313 (4.9s)

    → best_epoch=75, IC=-0.0096 (32.2s)

    → best_epoch=25, IC=-0.0026 (41.7s)

    → best_epoch=150, IC=-0.0047 (58.4s)

  Best: 2afb0a9b07e8 @ epoch 25 (IC=-0.0026)

Preparing and releasing folds...
  Fold 0: train=25,380  val=4,740

      epoch  25/200: loss=0.000398, IC=-0.0854

      epoch  50/200: loss=0.000295, IC=-0.1327

      epoch  75/200: loss=0.000247, IC=-0.1357

      epoch 100/200: loss=0.000223, IC=-0.1419

      epoch 125/200: loss=0.000209, IC=-0.1402

      epoch 150/200: loss=0.000201, IC=-0.1441

      epoch 175/200: loss=0.000194, IC=-0.1431

      epoch 200/200: loss=0.000200, IC=-0.1437

    Fold 0: best_ep=25, IC=-0.0854 (3.5s)

      epoch  25/200: loss=0.000266, IC=-0.1139

      epoch  50/200: loss=0.000184, IC=-0.1207

      epoch  75/200: loss=0.000148, IC=-0.1040

      epoch 100/200: loss=0.000128, IC=-0.0940

      epoch 125/200: loss=0.000120, IC=-0.0971

      epoch 150/200: loss=0.000115, IC=-0.0966

      epoch 175/200: loss=0.000112, IC=-0.0976

      epoch 200/200: loss=0.000109, IC=-0.0951

    Fold 0: best_ep=100, IC=-0.0940 (4.7s)

      epoch  25/200: loss=0.000199, IC=-0.1180

      epoch  50/200: loss=0.000123, IC=-0.1120

      epoch  75/200: loss=0.000093, IC=-0.0922

      epoch 100/200: loss=0.000080, IC=-0.0911

      epoch 125/200: loss=0.000074, IC=-0.0801

      epoch 150/200: loss=0.000070, IC=-0.0839

      epoch 175/200: loss=0.000067, IC=-0.0823

      epoch 200/200: loss=0.000068, IC=-0.0811

    Fold 0: best_ep=125, IC=-0.0801 (7.3s)

  Fold 1: train=25,380  val=5,160

      epoch  25/200: loss=0.000350, IC=-0.0183

      epoch  50/200: loss=0.000283, IC=-0.0375

      epoch  75/200: loss=0.000236, IC=-0.0312

      epoch 100/200: loss=0.000212, IC=-0.0307

      epoch 125/200: loss=0.000200, IC=-0.0263

      epoch 150/200: loss=0.000193, IC=-0.0181

      epoch 175/200: loss=0.000192, IC=-0.0193

      epoch 200/200: loss=0.000190, IC=-0.0197

    Fold 1: best_ep=150, IC=-0.0181 (3.7s)

      epoch  25/200: loss=0.000229, IC=+0.0323

      epoch  50/200: loss=0.000164, IC=+0.0207

      epoch  75/200: loss=0.000131, IC=+0.0297

      epoch 100/200: loss=0.000115, IC=+0.0378

      epoch 125/200: loss=0.000106, IC=+0.0458

      epoch 150/200: loss=0.000100, IC=+0.0499

      epoch 175/200: loss=0.000098, IC=+0.0477

      epoch 200/200: loss=0.000097, IC=+0.0476

    Fold 1: best_ep=150, IC=+0.0499 (4.6s)

      epoch  25/200: loss=0.000178, IC=+0.0115

      epoch  50/200: loss=0.000108, IC=+0.0368

      epoch  75/200: loss=0.000084, IC=+0.0287

      epoch 100/200: loss=0.000071, IC=+0.0353

      epoch 125/200: loss=0.000065, IC=+0.0327

      epoch 150/200: loss=0.000061, IC=+0.0410

      epoch 175/200: loss=0.000060, IC=+0.0404

      epoch 200/200: loss=0.000059, IC=+0.0403

    Fold 1: best_ep=150, IC=+0.0410 (6.9s)

  Fold 2: train=25,380  val=5,160

      epoch  25/200: loss=0.000360, IC=+0.0482

      epoch  50/200: loss=0.000274, IC=+0.0781

      epoch  75/200: loss=0.000241, IC=+0.0533

      epoch 100/200: loss=0.000220, IC=+0.0417

      epoch 125/200: loss=0.000210, IC=+0.0291

      epoch 150/200: loss=0.000199, IC=+0.0289

      epoch 175/200: loss=0.000201, IC=+0.0282

      epoch 200/200: loss=0.000197, IC=+0.0295

    Fold 2: best_ep=50, IC=+0.0781 (3.7s)

      epoch  25/200: loss=0.000283, IC=+0.0446

      epoch  50/200: loss=0.000204, IC=+0.0315

      epoch  75/200: loss=0.000169, IC=+0.0018

      epoch 100/200: loss=0.000146, IC=+0.0021

      epoch 125/200: loss=0.000137, IC=-0.0130

      epoch 150/200: loss=0.000128, IC=-0.0058

      epoch 175/200: loss=0.000126, IC=-0.0072

      epoch 200/200: loss=0.000124, IC=-0.0091

    Fold 2: best_ep=25, IC=+0.0446 (4.9s)

      epoch  25/200: loss=0.000206, IC=+0.1013

      epoch  50/200: loss=0.000126, IC=+0.0500

      epoch  75/200: loss=0.000100, IC=+0.0257

      epoch 100/200: loss=0.000085, IC=+0.0377

      epoch 125/200: loss=0.000078, IC=+0.0352

      epoch 150/200: loss=0.000073, IC=+0.0317

      epoch 175/200: loss=0.000073, IC=+0.0293

      epoch 200/200: loss=0.000071, IC=+0.0297

    Fold 2: best_ep=25, IC=+0.1013 (6.8s)

  Fold 3: train=25,380  val=5,160

      epoch  25/200: loss=0.000538, IC=-0.1795

      epoch  50/200: loss=0.000415, IC=-0.1523

      epoch  75/200: loss=0.000359, IC=-0.1384

      epoch 100/200: loss=0.000325, IC=-0.1402

      epoch 125/200: loss=0.000304, IC=-0.1412

      epoch 150/200: loss=0.000295, IC=-0.1507

      epoch 175/200: loss=0.000290, IC=-0.1476

      epoch 200/200: loss=0.000290, IC=-0.1486

    Fold 3: best_ep=75, IC=-0.1384 (3.5s)

      epoch  25/200: loss=0.000314, IC=-0.1280

      epoch  50/200: loss=0.000223, IC=-0.1026

      epoch  75/200: loss=0.000185, IC=-0.1029

      epoch 100/200: loss=0.000165, IC=-0.0952

      epoch 125/200: loss=0.000148, IC=-0.0996

      epoch 150/200: loss=0.000143, IC=-0.0971

      epoch 175/200: loss=0.000141, IC=-0.0924

      epoch 200/200: loss=0.000142, IC=-0.0946

    Fold 3: best_ep=175, IC=-0.0924 (4.6s)

      epoch  25/200: loss=0.000235, IC=-0.1658

      epoch  50/200: loss=0.000149, IC=-0.1430

      epoch  75/200: loss=0.000118, IC=-0.1393

      epoch 100/200: loss=0.000102, IC=-0.1493

      epoch 125/200: loss=0.000090, IC=-0.1426

      epoch 150/200: loss=0.000087, IC=-0.1453

      epoch 175/200: loss=0.000085, IC=-0.1448

      epoch 200/200: loss=0.000084, IC=-0.1435

    Fold 3: best_ep=75, IC=-0.1393 (6.5s)

  Fold 4: train=25,380  val=5,160

      epoch  25/200: loss=0.000607, IC=+0.0079

      epoch  50/200: loss=0.000472, IC=+0.0348

      epoch  75/200: loss=0.000402, IC=+0.0411

      epoch 100/200: loss=0.000366, IC=+0.0545

      epoch 125/200: loss=0.000350, IC=+0.0649

      epoch 150/200: loss=0.000333, IC=+0.0598

      epoch 175/200: loss=0.000334, IC=+0.0610

      epoch 200/200: loss=0.000333, IC=+0.0621

    Fold 4: best_ep=125, IC=+0.0649 (3.5s)

      epoch  25/200: loss=0.000505, IC=-0.0302

      epoch  50/200: loss=0.000355, IC=+0.0106

      epoch  75/200: loss=0.000274, IC=+0.0322

      epoch 100/200: loss=0.000235, IC=+0.0302

      epoch 125/200: loss=0.000216, IC=+0.0363

      epoch 150/200: loss=0.000210, IC=+0.0396

      epoch 175/200: loss=0.000199, IC=+0.0355

      epoch 200/200: loss=0.000198, IC=+0.0348

    Fold 4: best_ep=150, IC=+0.0396 (4.5s)

      epoch  25/200: loss=0.000264, IC=+0.0350

      epoch  50/200: loss=0.000168, IC=+0.0379

      epoch  75/200: loss=0.000128, IC=+0.0349

      epoch 100/200: loss=0.000107, IC=+0.0334

      epoch 125/200: loss=0.000097, IC=+0.0266

      epoch 150/200: loss=0.000095, IC=+0.0265

      epoch 175/200: loss=0.000091, IC=+0.0249

      epoch 200/200: loss=0.000089, IC=+0.0272

    Fold 4: best_ep=50, IC=+0.0379 (7.4s)

  Fold 5: train=25,380  val=5,160

      epoch  25/200: loss=0.000499, IC=+0.1678

      epoch  50/200: loss=0.000379, IC=+0.1804

      epoch  75/200: loss=0.000323, IC=+0.1557

      epoch 100/200: loss=0.000301, IC=+0.1720

      epoch 125/200: loss=0.000278, IC=+0.1746

      epoch 150/200: loss=0.000268, IC=+0.1712

      epoch 175/200: loss=0.000273, IC=+0.1742

      epoch 200/200: loss=0.000266, IC=+0.1743

    Fold 5: best_ep=50, IC=+0.1804 (3.8s)

      epoch  25/200: loss=0.000414, IC=+0.1637

      epoch  50/200: loss=0.000275, IC=+0.1632

      epoch  75/200: loss=0.000218, IC=+0.1691

      epoch 100/200: loss=0.000193, IC=+0.1680

      epoch 125/200: loss=0.000180, IC=+0.1756

      epoch 150/200: loss=0.000169, IC=+0.1718

      epoch 175/200: loss=0.000168, IC=+0.1802

      epoch 200/200: loss=0.000167, IC=+0.1803

    Fold 5: best_ep=200, IC=+0.1803 (4.9s)

      epoch  25/200: loss=0.000310, IC=+0.1651

      epoch  50/200: loss=0.000195, IC=+0.1718

      epoch  75/200: loss=0.000147, IC=+0.1714

      epoch 100/200: loss=0.000125, IC=+0.1771

      epoch 125/200: loss=0.000110, IC=+0.1682

      epoch 150/200: loss=0.000106, IC=+0.1727

      epoch 175/200: loss=0.000101, IC=+0.1728

      epoch 200/200: loss=0.000102, IC=+0.1747

    Fold 5: best_ep=100, IC=+0.1771 (7.8s)

  Fold 6: train=23,020  val=5,160

      epoch  25/200: loss=0.000611, IC=-0.0505

      epoch  50/200: loss=0.000430, IC=-0.0477

      epoch  75/200: loss=0.000354, IC=-0.0517

      epoch 100/200: loss=0.000318, IC=-0.0569

      epoch 125/200: loss=0.000293, IC=-0.0676

      epoch 150/200: loss=0.000278, IC=-0.0737

      epoch 175/200: loss=0.000280, IC=-0.0727

      epoch 200/200: loss=0.000275, IC=-0.0727

    Fold 6: best_ep=50, IC=-0.0477 (3.1s)

      epoch  25/200: loss=0.000448, IC=-0.0151

      epoch  50/200: loss=0.000285, IC=-0.0462

      epoch  75/200: loss=0.000217, IC=-0.0820

      epoch 100/200: loss=0.000189, IC=-0.0901

      epoch 125/200: loss=0.000171, IC=-0.0839

      epoch 150/200: loss=0.000166, IC=-0.0876

      epoch 175/200: loss=0.000161, IC=-0.0842

      epoch 200/200: loss=0.000159, IC=-0.0858

    Fold 6: best_ep=25, IC=-0.0151 (4.9s)

      epoch  25/200: loss=0.000298, IC=-0.0704

      epoch  50/200: loss=0.000174, IC=-0.1000

      epoch  75/200: loss=0.000131, IC=-0.0952

      epoch 100/200: loss=0.000112, IC=-0.0992

      epoch 125/200: loss=0.000102, IC=-0.1084

      epoch 150/200: loss=0.000097, IC=-0.1038

      epoch 175/200: loss=0.000095, IC=-0.1045

      epoch 200/200: loss=0.000094, IC=-0.1029

    Fold 6: best_ep=25, IC=-0.0704 (5.8s)

  Fold 7: train=17,860  val=5,160

      epoch  25/200: loss=0.000595, IC=+0.0182

      epoch  50/200: loss=0.000421, IC=+0.0025

      epoch  75/200: loss=0.000349, IC=+0.0181

      epoch 100/200: loss=0.000302, IC=+0.0283

      epoch 125/200: loss=0.000279, IC=+0.0333

      epoch 150/200: loss=0.000266, IC=+0.0340

      epoch 175/200: loss=0.000261, IC=+0.0337

      epoch 200/200: loss=0.000262, IC=+0.0326

    Fold 7: best_ep=150, IC=+0.0340 (2.8s)

      epoch  25/200: loss=0.000456, IC=+0.0056

      epoch  50/200: loss=0.000281, IC=+0.0191

      epoch  75/200: loss=0.000218, IC=+0.0236

      epoch 100/200: loss=0.000181, IC=+0.0292

      epoch 125/200: loss=0.000169, IC=+0.0388

      epoch 150/200: loss=0.000158, IC=+0.0503

      epoch 175/200: loss=0.000154, IC=+0.0482

      epoch 200/200: loss=0.000152, IC=+0.0495

    Fold 7: best_ep=150, IC=+0.0503 (3.5s)

      epoch  25/200: loss=0.000255, IC=+0.0754

      epoch  50/200: loss=0.000150, IC=+0.0548

      epoch  75/200: loss=0.000118, IC=+0.0482

      epoch 100/200: loss=0.000098, IC=+0.0452

      epoch 125/200: loss=0.000090, IC=+0.0508

      epoch 150/200: loss=0.000084, IC=+0.0457

      epoch 175/200: loss=0.000082, IC=+0.0466

      epoch 200/200: loss=0.000083, IC=+0.0454

    Fold 7: best_ep=25, IC=+0.0754 (5.4s)

    → best_epoch=100, IC=-0.0078 (27.6s)

    → best_epoch=175, IC=+0.0048 (36.7s)

    → best_epoch=25, IC=+0.0055 (54.0s)

  Best: 710a71c76a2e @ epoch 25 (IC=+0.0055)

shape: (72, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean   ┆ ic_t      ┆ training_ ┆ predicti │
│ ---       ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---       ┆ ---       ┆ hash      ┆ on_hash  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ i64       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 25        ┆ … ┆ -0.004033 ┆ -0.526438 ┆ 2b929abc9 ┆ f9155c11 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 475       ┆ faba     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 50        ┆ … ┆ 0.006267  ┆ 0.924793  ┆ 2b929abc9 ┆ d937c16f │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 475       ┆ 7118     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 75        ┆ … ┆ 0.002941  ┆ 0.531829  ┆ 2b929abc9 ┆ e1e57ac8 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 475       ┆ 7164     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 100       ┆ … ┆ 0.004194  ┆ 0.584408  ┆ 2b929abc9 ┆ 83b706ea │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 475       ┆ 3f17     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 125       ┆ … ┆ 0.004526  ┆ 0.607901  ┆ 2b929abc9 ┆ 9deaf63b │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 475       ┆ 1d24     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 100       ┆ … ┆ -0.011937 ┆ -1.15802  ┆ f960af626 ┆ 7d0f251f │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 672       ┆ 9e43     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 125       ┆ … ┆ -0.01185  ┆ -0.981717 ┆ f960af626 ┆ 190a7323 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 672       ┆ d12d     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 150       ┆ … ┆ -0.012756 ┆ -1.051666 ┆ f960af626 ┆ a7dd3a9e │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 672       ┆ eabd     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 175       ┆ … ┆ -0.014651 ┆ -1.195963 ┆ f960af626 ┆ 81b2bf5b │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 672       ┆ 42b3     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 200       ┆ … ┆ -0.014805 ┆ -1.214979 ┆ f960af626 ┆ 039c5670 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 672       ┆ 2e88     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Reload the checkpoint population

Repeating the same request validates the saved checkpoint manifests and returns the same catalog
identities. No empty cached summary or single IC-chosen checkpoint is substituted.

In [7]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("TabM checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview checkpoints remain outside official comparison and holdout selection.")

Official prediction population: 0044e1f31b9c

## Key takeaways

- Train-only preprocessing and checkpoint persistence belong to the shared TabM computation.
- Every declared epoch remains available to the backtest stage.
- Rank correlation is a diagnostic field in the catalog, not a checkpoint-selection rule.