# Tabular Deep Learning - FX Pairs

TabM applies a small neural network to each decision row without turning the history into a
sequence. This notebook submits the published capacity choices to the shared TabM runner. The
runner fits preprocessing inside each training fold, saves every declared weight checkpoint, and
publishes a separate complete validation prediction set for every checkpoint.

**Learning objectives**

- Express neural-network capacity and checkpoint schedules as visible requests.
- Verify that every fold and epoch checkpoint has reloadable fitted state.
- Continue from complete prediction rows without selecting a checkpoint by rank correlation.

**Book reference**: Chapter 12, Section 12.3

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published TabM FX configurations."""

import polars as pl
import torch

from case_studies.research import (
    ExecutionTier,
    declared_labels,
    narrows_declared_catalog,
    open_study,
    plan_models,
    population_supersedes,
    sweep_labels,
)
from utils.modeling import load_configs
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
BATCH_SIZE = 0
DEVICE = ""
SEED = 42
POPULATION_NAME = ""
SUPERSEDES_POPULATION: str = "7896f6bcaf7e"
# The tier is a parameter, not something inferred from whether a reduction happens to be set.
# Inferring it meant a run could be reduced and still open the case study's own artifacts in
# place, which is the production path; a reader under test then wrote where the published run
# writes. WORKSPACE is the other half: a preview has nowhere else to put its results.
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None

## Select the task and execution tier

Canonical execution uses every configured fold, symbol, epoch, and batch setting. A preview
declares its reductions, takes an isolated workspace, and creates a preview identity there. A
preview proves the path but cannot join the official model population.

The reductions are read before the study is opened, because which study to open is decided by
the tier and the two have to agree: a preview that reduces nothing is a canonical run wearing
the wrong tier, and a canonical run carrying reductions would publish a narrowed population
under the canonical name.

In [3]:
set_global_seeds(SEED)
REDUCTION_PARAMETERS = {
    "folds": list(range(MAX_FOLDS)) if MAX_FOLDS else None,
    "max_symbols": MAX_SYMBOLS or None,
    "n_epochs": N_EPOCHS or None,
}
reductions = {key: value for key, value in REDUCTION_PARAMETERS.items() if value is not None}
tier = ExecutionTier(EXECUTION_TIER)
if tier is ExecutionTier.PREVIEW and not reductions:
    raise ValueError("preview execution must declare at least one reduction")
if tier is ExecutionTier.CANONICAL and reductions:
    raise ValueError(f"canonical execution cannot carry reductions: {sorted(reductions)}")
study = open_study(CASE_STUDY_ID, execution_tier=tier, workspace=WORKSPACE or None)

# Which labels this notebook fits is a question for the training menus, not for the sweep list:
# `setup.yaml` says which labels the case study carries, a menu says what to fit for one of them,
# and a label in the sweep whose menu declares no `tabular_dl:` section owes nothing here. The two
# agree in this case study today, so restating the sweep list produced the right answer by
# coincidence and would have kept producing it silently after a menu changed. The order stays
# `setup.yaml`'s rather than `declared_labels`' menu-file order because the population is named
# after its labels and hashed over its members as an ordered list, so re-ordering would give the
# published population a new identity and demand a supersedes for a run that fits the same models.
fits_tabm = set(declared_labels(study, "tabular_dl"))
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [label for label in sweep_labels(study) if label in fits_tabm]
)

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")


print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
# An empty DEVICE resolves to what the machine has. The runners refuse "cuda" on a host without
# it rather than falling back silently - which is the right contract for a run whose results get
# registered - so a hardcoded "cuda" default made the notebook unrunnable for any reader without
# an NVIDIA card, and unrunnable on a CPU CI runner. Resolving here keeps the refusal for anyone
# who asks for "cuda" explicitly, and prints what was chosen so a run never leaves it implicit.
device = DEVICE or ("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda

## Build the published requests

The YAML menu supplies the architecture settings and production checkpoint schedules. The
parameter cell can reduce epochs or change batch size for a preview without changing the menu.

In [4]:
overrides = {
    "device": device,
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
}
menu = [
    (label, config)
    for label in labels
    for config in load_configs(CASE_STUDY_ID, label, family="tabular_dl")
]

# `PRIMARY_LABEL` narrows what is fitted, and a narrowed run declares a different set of members
# than the canonical population does. A population is immutable once written, so such a run must
# publish under its own name. The comparison is over `(label, config_name)` pairs rather than a
# row count, and it says so here rather than several cells later in a message about hashes.
if (
    narrows_declared_catalog(
        study,
        "tabular_dl",
        pl.DataFrame(
            {
                "label": [label for label, _ in menu],
                "config_name": [config["config_name"] for _, config in menu],
            }
        ),
    )
    and not POPULATION_NAME
):
    raise ValueError(
        f"this run declares {len(menu)} label-configuration pairs, which is not the complete "
        "declared catalog, so it cannot publish the canonical population; pass POPULATION_NAME "
        "to give it its own"
    )
requests = [
    study.model(
        family="tabular_dl",
        label=label,
        config_name=config["config_name"],
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label, config in menu
]

pl.DataFrame(
    {
        "config_name": [request.config_name for request in requests],
        "label": [request.label for request in requests],
        "device": [device] * len(requests),
        "execution_tier": [request.execution_tier.value for request in requests],
    }
)

shape: (9, 4)
┌─────────────┬─────────────┬────────┬────────────────┐
│ config_name ┆ label       ┆ device ┆ execution_tier │
│ ---         ┆ ---         ┆ ---    ┆ ---            │
│ str         ┆ str         ┆ str    ┆ str            │
╞═════════════╪═════════════╪════════╪════════════════╡
│ tabm_s      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_s      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_s      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
└─────────────┴─────────────┴────────┴────────────────┘

## Declare every epoch checkpoint before training

The declared epoch schedule, not the run that follows, decides how many downstream configurations
this notebook owes. Planning resolves each one without training, so a failed member is visible as
a gap in the population rather than a shorter catalog.

In [5]:
plan = plan_models(study, requests=requests)
if len(plan.expected_training_hashes) != len(requests):
    raise RuntimeError("each TabM configuration must plan exactly one training identity")

configured = {(label, config["config_name"]) for label, config in menu}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        "the plan does not match the configured TabM menu; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )

pl.DataFrame(
    {
        "label": [member.label for member in plan.members],
        "config_name": [member.config_name for member in plan.members],
        "checkpoint_kind": [member.checkpoint_kind for member in plan.members],
        "checkpoint_value": [member.checkpoint_value for member in plan.members],
        "prediction_hash": [member.prediction_hash for member in plan.members],
    }
)

shape: (72, 5)
┌─────────────┬─────────────┬─────────────────┬──────────────────┬─────────────────┐
│ label       ┆ config_name ┆ checkpoint_kind ┆ checkpoint_value ┆ prediction_hash │
│ ---         ┆ ---         ┆ ---             ┆ ---              ┆ ---             │
│ str         ┆ str         ┆ str             ┆ i64              ┆ str             │
╞═════════════╪═════════════╪═════════════════╪══════════════════╪═════════════════╡
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 25               ┆ a4410d8ac3dd    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 50               ┆ ecf5298efdb7    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 75               ┆ c8d420861865    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 100              ┆ 3c1799cea565    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 125              ┆ 2225b4315102    │
│ …           ┆ …           ┆ …               ┆ …                ┆ …               │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 100              ┆ 0be5b2e0d016    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 125              ┆ e7642a0979bc    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 150              ┆ 89cda36761bd    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 175              ┆ 1d4c9e4df99b    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 200              ┆ 6461a37d1fd2    │
└─────────────┴─────────────┴─────────────────┴──────────────────┴─────────────────┘

## Record the official population, then fit or reload every capacity choice

Compatible TabM requests share base-fold materialization. Candidate-specific scaling, random
state, weights, and prediction identities remain separate. Any failed member stops the cell.

`SUPERSEDES_POPULATION` names the population hash this run replaces. A population is the set of
prediction identities it publishes, so anything that moves a training identity produces a
different population under the same name, and the registry refuses to write it without being
told which snapshot it supersedes. That lineage is the only record of which generation is which,
and what moved the identities here was a change to the family's own source file rather than to
anything the notebook declares.

`population_supersedes` decides whether the declared hash may be offered. It is offered when the
name already carries the generation this declaration produced, so a re-run resolves to the
population it published, and when the declaration names the generation in force, so a refit
publishes the next one. It is withheld everywhere else - on a reader's clean clone, where
`run_log/` is gitignored and the registry has no generation at all; under a caller's own
`POPULATION_NAME`; and in a preview, whose isolated registry holds nothing under this name.

In [6]:
population_name = POPULATION_NAME or f"{CASE_STUDY_ID}:{'+'.join(labels)}:tabular_dl"
population = (
    plan.create_population(
        name=population_name,
        supersedes=population_supersedes(
            study, name=population_name, declared=SUPERSEDES_POPULATION
        ),
    )
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
if len(execution.runs) != len(requests):
    raise RuntimeError("the TabM runner did not return every requested configuration")

catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial TabM checkpoints cannot pass to backtesting")
if catalog.select("label", "config_name", "checkpoint_value").n_unique() != catalog.height:
    raise RuntimeError("each configuration and epoch checkpoint must identify one prediction set")
if catalog.get_column("checkpoint_value").null_count():
    raise RuntimeError("every TabM prediction must name its epoch checkpoint")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Preparing and releasing folds...
  Fold 0: train=18,260  val=5,160

      epoch  25/200: loss=0.000042, IC=+0.0380

      epoch  50/200: loss=0.000043, IC=+0.0357

      epoch  75/200: loss=0.000042, IC=+0.0269

      epoch 100/200: loss=0.000039, IC=+0.0241

      epoch 125/200: loss=0.000039, IC=+0.0217

      epoch 150/200: loss=0.000038, IC=+0.0234

      epoch 175/200: loss=0.000038, IC=+0.0218

      epoch 200/200: loss=0.000039, IC=+0.0217

    Fold 0: best_ep=25, IC=+0.0380 (6.5s)

      epoch  25/200: loss=0.000039, IC=-0.0252

      epoch  50/200: loss=0.000039, IC=-0.0040

      epoch  75/200: loss=0.000035, IC=-0.0012

      epoch 100/200: loss=0.000031, IC=-0.0041

      epoch 125/200: loss=0.000029, IC=-0.0079

      epoch 150/200: loss=0.000029, IC=-0.0011

      epoch 175/200: loss=0.000029, IC=-0.0015

      epoch 200/200: loss=0.000028, IC=-0.0012

    Fold 0: best_ep=150, IC=-0.0011 (7.4s)

      epoch  25/200: loss=0.000038, IC=-0.0010

      epoch  50/200: loss=0.000036, IC=+0.0159

      epoch  75/200: loss=0.000032, IC=+0.0223

      epoch 100/200: loss=0.000025, IC=+0.0234

      epoch 125/200: loss=0.000023, IC=+0.0165

      epoch 150/200: loss=0.000022, IC=+0.0180

      epoch 175/200: loss=0.000022, IC=+0.0218

      epoch 200/200: loss=0.000021, IC=+0.0213

    Fold 0: best_ep=100, IC=+0.0234 (10.6s)

  Fold 1: train=23,420  val=5,160

      epoch  25/200: loss=0.000048, IC=-0.0176

      epoch  50/200: loss=0.000045, IC=-0.0261

      epoch  75/200: loss=0.000044, IC=-0.0282

      epoch 100/200: loss=0.000044, IC=-0.0319

      epoch 125/200: loss=0.000044, IC=-0.0326

      epoch 150/200: loss=0.000043, IC=-0.0330

      epoch 175/200: loss=0.000043, IC=-0.0310

      epoch 200/200: loss=0.000043, IC=-0.0310

    Fold 1: best_ep=25, IC=-0.0176 (6.8s)

      epoch  25/200: loss=0.000042, IC=-0.0185

      epoch  50/200: loss=0.000038, IC=-0.0188

      epoch  75/200: loss=0.000034, IC=-0.0091

      epoch 100/200: loss=0.000031, IC=-0.0073

      epoch 125/200: loss=0.000030, IC=-0.0058

      epoch 150/200: loss=0.000029, IC=-0.0094

      epoch 175/200: loss=0.000028, IC=-0.0116

      epoch 200/200: loss=0.000028, IC=-0.0129

    Fold 1: best_ep=125, IC=-0.0058 (6.7s)

      epoch  25/200: loss=0.000042, IC=-0.0022

      epoch  50/200: loss=0.000035, IC=+0.0053

      epoch  75/200: loss=0.000030, IC=-0.0141

      epoch 100/200: loss=0.000025, IC=-0.0115

      epoch 125/200: loss=0.000024, IC=-0.0141

      epoch 150/200: loss=0.000024, IC=-0.0163

      epoch 175/200: loss=0.000024, IC=-0.0159

      epoch 200/200: loss=0.000023, IC=-0.0144

    Fold 1: best_ep=50, IC=+0.0053 (12.3s)

  Fold 2: train=25,780  val=5,160

      epoch  25/200: loss=0.000042, IC=+0.0012

      epoch  50/200: loss=0.000040, IC=+0.0380

      epoch  75/200: loss=0.000039, IC=+0.0308

      epoch 100/200: loss=0.000038, IC=+0.0182

      epoch 125/200: loss=0.000037, IC=+0.0192

      epoch 150/200: loss=0.000036, IC=+0.0221

      epoch 175/200: loss=0.000035, IC=+0.0191

      epoch 200/200: loss=0.000036, IC=+0.0206

    Fold 2: best_ep=50, IC=+0.0380 (9.4s)

      epoch  25/200: loss=0.000040, IC=+0.0231

      epoch  50/200: loss=0.000037, IC=+0.0407

      epoch  75/200: loss=0.000034, IC=+0.0398

      epoch 100/200: loss=0.000031, IC=+0.0341

      epoch 125/200: loss=0.000029, IC=+0.0309

      epoch 150/200: loss=0.000028, IC=+0.0247

      epoch 175/200: loss=0.000028, IC=+0.0261

      epoch 200/200: loss=0.000029, IC=+0.0252

    Fold 2: best_ep=50, IC=+0.0407 (9.1s)

      epoch  25/200: loss=0.000040, IC=+0.0020

      epoch  50/200: loss=0.000035, IC=+0.0200

      epoch  75/200: loss=0.000031, IC=+0.0179

      epoch 100/200: loss=0.000028, IC=+0.0253

      epoch 125/200: loss=0.000026, IC=+0.0255

      epoch 150/200: loss=0.000023, IC=+0.0258

      epoch 175/200: loss=0.000023, IC=+0.0264

      epoch 200/200: loss=0.000023, IC=+0.0259

    Fold 2: best_ep=175, IC=+0.0264 (13.7s)

  Fold 3: train=25,780  val=5,160

      epoch  25/200: loss=0.000050, IC=+0.0107

      epoch  50/200: loss=0.000042, IC=+0.0151

      epoch  75/200: loss=0.000041, IC=+0.0087

      epoch 100/200: loss=0.000040, IC=+0.0093

      epoch 125/200: loss=0.000040, IC=+0.0123

      epoch 150/200: loss=0.000039, IC=+0.0121

      epoch 175/200: loss=0.000039, IC=+0.0117

      epoch 200/200: loss=0.000039, IC=+0.0111

    Fold 3: best_ep=50, IC=+0.0151 (9.1s)

      epoch  25/200: loss=0.000037, IC=+0.0067

      epoch  50/200: loss=0.000034, IC=+0.0109

      epoch  75/200: loss=0.000031, IC=+0.0129

      epoch 100/200: loss=0.000029, IC=+0.0188

      epoch 125/200: loss=0.000028, IC=+0.0085

      epoch 150/200: loss=0.000027, IC=+0.0189

      epoch 175/200: loss=0.000026, IC=+0.0193

      epoch 200/200: loss=0.000027, IC=+0.0200

    Fold 3: best_ep=200, IC=+0.0200 (10.7s)

      epoch  25/200: loss=0.000037, IC=+0.0067

      epoch  50/200: loss=0.000033, IC=+0.0194

      epoch  75/200: loss=0.000029, IC=+0.0024

      epoch 100/200: loss=0.000026, IC=+0.0195

      epoch 125/200: loss=0.000023, IC=+0.0182

      epoch 150/200: loss=0.000022, IC=+0.0246

      epoch 175/200: loss=0.000022, IC=+0.0197

      epoch 200/200: loss=0.000022, IC=+0.0218

    Fold 3: best_ep=150, IC=+0.0246 (12.2s)

  Fold 4: train=25,780  val=5,160

      epoch  25/200: loss=0.000058, IC=-0.0353

      epoch  50/200: loss=0.000049, IC=-0.0161

      epoch  75/200: loss=0.000043, IC=-0.0117

      epoch 100/200: loss=0.000040, IC=-0.0168

      epoch 125/200: loss=0.000042, IC=-0.0106

      epoch 150/200: loss=0.000039, IC=-0.0125

      epoch 175/200: loss=0.000039, IC=-0.0104

      epoch 200/200: loss=0.000040, IC=-0.0095

    Fold 4: best_ep=200, IC=-0.0095 (8.7s)

      epoch  25/200: loss=0.000044, IC=-0.0185

      epoch  50/200: loss=0.000043, IC=-0.0111

      epoch  75/200: loss=0.000039, IC=-0.0092

      epoch 100/200: loss=0.000037, IC=-0.0203

      epoch 125/200: loss=0.000039, IC=-0.0201

      epoch 150/200: loss=0.000036, IC=-0.0216

      epoch 175/200: loss=0.000036, IC=-0.0187

      epoch 200/200: loss=0.000036, IC=-0.0197

    Fold 4: best_ep=75, IC=-0.0092 (10.7s)

      epoch  25/200: loss=0.000036, IC=-0.0242

      epoch  50/200: loss=0.000035, IC=-0.0243

      epoch  75/200: loss=0.000028, IC=-0.0132

      epoch 100/200: loss=0.000024, IC=-0.0116

      epoch 125/200: loss=0.000022, IC=-0.0182

      epoch 150/200: loss=0.000021, IC=-0.0179

      epoch 175/200: loss=0.000021, IC=-0.0158

      epoch 200/200: loss=0.000021, IC=-0.0179

    Fold 4: best_ep=100, IC=-0.0116 (13.6s)

  Fold 5: train=25,780  val=5,160

      epoch  25/200: loss=0.000031, IC=-0.0031

      epoch  50/200: loss=0.000029, IC=-0.0073

      epoch  75/200: loss=0.000028, IC=+0.0037

      epoch 100/200: loss=0.000027, IC=+0.0072

      epoch 125/200: loss=0.000026, IC=+0.0072

      epoch 150/200: loss=0.000026, IC=+0.0094

      epoch 175/200: loss=0.000026, IC=+0.0091

      epoch 200/200: loss=0.000026, IC=+0.0089

    Fold 5: best_ep=150, IC=+0.0094 (7.9s)

      epoch  25/200: loss=0.000032, IC=+0.0132

      epoch  50/200: loss=0.000029, IC=+0.0131

      epoch  75/200: loss=0.000027, IC=+0.0011

      epoch 100/200: loss=0.000026, IC=+0.0194

      epoch 125/200: loss=0.000024, IC=+0.0191

      epoch 150/200: loss=0.000024, IC=+0.0188

      epoch 175/200: loss=0.000024, IC=+0.0186

      epoch 200/200: loss=0.000024, IC=+0.0196

    Fold 5: best_ep=200, IC=+0.0196 (11.5s)

      epoch  25/200: loss=0.000029, IC=-0.0059

      epoch  50/200: loss=0.000025, IC=+0.0032

      epoch  75/200: loss=0.000022, IC=-0.0099

      epoch 100/200: loss=0.000020, IC=-0.0174

      epoch 125/200: loss=0.000018, IC=-0.0130

      epoch 150/200: loss=0.000018, IC=-0.0121

      epoch 175/200: loss=0.000018, IC=-0.0107

      epoch 200/200: loss=0.000017, IC=-0.0114

    Fold 5: best_ep=50, IC=+0.0032 (12.1s)

  Fold 6: train=25,780  val=5,160

      epoch  25/200: loss=0.000027, IC=-0.0115

      epoch  50/200: loss=0.000025, IC=+0.0017

      epoch  75/200: loss=0.000024, IC=+0.0032

      epoch 100/200: loss=0.000023, IC=-0.0047

      epoch 125/200: loss=0.000023, IC=-0.0093

      epoch 150/200: loss=0.000023, IC=-0.0148

      epoch 175/200: loss=0.000023, IC=-0.0157

      epoch 200/200: loss=0.000023, IC=-0.0161

    Fold 6: best_ep=75, IC=+0.0032 (7.6s)

      epoch  25/200: loss=0.000025, IC=-0.0566

      epoch  50/200: loss=0.000023, IC=-0.0493

      epoch  75/200: loss=0.000022, IC=-0.0428

      epoch 100/200: loss=0.000021, IC=-0.0370

      epoch 125/200: loss=0.000021, IC=-0.0338

      epoch 150/200: loss=0.000021, IC=-0.0331

      epoch 175/200: loss=0.000020, IC=-0.0299

      epoch 200/200: loss=0.000020, IC=-0.0305

    Fold 6: best_ep=175, IC=-0.0299 (9.6s)

      epoch  25/200: loss=0.000023, IC=-0.0433

      epoch  50/200: loss=0.000020, IC=-0.0401

      epoch  75/200: loss=0.000018, IC=-0.0373

      epoch 100/200: loss=0.000016, IC=-0.0375

      epoch 125/200: loss=0.000015, IC=-0.0426

      epoch 150/200: loss=0.000015, IC=-0.0366

      epoch 175/200: loss=0.000014, IC=-0.0389

      epoch 200/200: loss=0.000014, IC=-0.0392

    Fold 6: best_ep=150, IC=-0.0366 (16.2s)

  Fold 7: train=25,780  val=5,140

      epoch  25/200: loss=0.000033, IC=+0.0030

      epoch  50/200: loss=0.000029, IC=+0.0033

      epoch  75/200: loss=0.000028, IC=+0.0020

      epoch 100/200: loss=0.000027, IC=+0.0037

      epoch 125/200: loss=0.000027, IC=+0.0008

      epoch 150/200: loss=0.000028, IC=-0.0004

      epoch 175/200: loss=0.000027, IC=-0.0012

      epoch 200/200: loss=0.000027, IC=-0.0013

    Fold 7: best_ep=100, IC=+0.0037 (7.2s)

      epoch  25/200: loss=0.000029, IC=-0.0237

      epoch  50/200: loss=0.000027, IC=+0.0001

      epoch  75/200: loss=0.000026, IC=+0.0215

      epoch 100/200: loss=0.000025, IC=+0.0253

      epoch 125/200: loss=0.000024, IC=+0.0252

      epoch 150/200: loss=0.000024, IC=+0.0234

      epoch 175/200: loss=0.000024, IC=+0.0237

      epoch 200/200: loss=0.000023, IC=+0.0250

    Fold 7: best_ep=100, IC=+0.0253 (10.4s)

      epoch  25/200: loss=0.000026, IC=+0.0392

      epoch  50/200: loss=0.000022, IC=+0.0166

      epoch  75/200: loss=0.000020, IC=+0.0146

      epoch 100/200: loss=0.000018, IC=+0.0042

      epoch 125/200: loss=0.000017, IC=+0.0021

      epoch 150/200: loss=0.000016, IC=+0.0019

      epoch 175/200: loss=0.000016, IC=+0.0056

      epoch 200/200: loss=0.000016, IC=+0.0045

    Fold 7: best_ep=25, IC=+0.0392 (14.0s)

    → best_epoch=50, IC=+0.0055 (63.4s)

    → best_epoch=100, IC=+0.0036 (76.3s)

    → best_epoch=50, IC=+0.0020 (104.9s)

  Best: 4e8fe017e765 @ epoch 50 (IC=+0.0055)

Preparing and releasing folds...
  Fold 0: train=18,180  val=5,160

      epoch  25/200: loss=0.000187, IC=+0.0535

      epoch  50/200: loss=0.000169, IC=+0.0197

      epoch  75/200: loss=0.000153, IC=+0.0210

      epoch 100/200: loss=0.000143, IC=+0.0240

      epoch 125/200: loss=0.000137, IC=+0.0238

      epoch 150/200: loss=0.000138, IC=+0.0252

      epoch 175/200: loss=0.000133, IC=+0.0235

      epoch 200/200: loss=0.000137, IC=+0.0244

    Fold 0: best_ep=25, IC=+0.0535 (5.4s)

      epoch  25/200: loss=0.000146, IC=-0.0011

      epoch  50/200: loss=0.000113, IC=-0.0094

      epoch  75/200: loss=0.000094, IC=-0.0049

      epoch 100/200: loss=0.000086, IC=+0.0050

      epoch 125/200: loss=0.000078, IC=+0.0096

      epoch 150/200: loss=0.000077, IC=+0.0105

      epoch 175/200: loss=0.000076, IC=+0.0101

      epoch 200/200: loss=0.000075, IC=+0.0120

    Fold 0: best_ep=200, IC=+0.0120 (6.9s)

      epoch  25/200: loss=0.000129, IC=+0.0515

      epoch  50/200: loss=0.000086, IC=+0.0582

      epoch  75/200: loss=0.000068, IC=+0.0385

      epoch 100/200: loss=0.000058, IC=+0.0412

      epoch 125/200: loss=0.000052, IC=+0.0374

      epoch 150/200: loss=0.000052, IC=+0.0374

      epoch 175/200: loss=0.000049, IC=+0.0340

      epoch 200/200: loss=0.000049, IC=+0.0345

    Fold 0: best_ep=50, IC=+0.0582 (10.8s)

  Fold 1: train=23,340  val=5,160

      epoch  25/200: loss=0.000210, IC=-0.0236

      epoch  50/200: loss=0.000191, IC=+0.0118

      epoch  75/200: loss=0.000174, IC=+0.0197

      epoch 100/200: loss=0.000166, IC=+0.0139

      epoch 125/200: loss=0.000158, IC=+0.0220

      epoch 150/200: loss=0.000155, IC=+0.0217

      epoch 175/200: loss=0.000155, IC=+0.0183

      epoch 200/200: loss=0.000152, IC=+0.0179

    Fold 1: best_ep=125, IC=+0.0220 (7.1s)

      epoch  25/200: loss=0.000156, IC=-0.0326

      epoch  50/200: loss=0.000117, IC=-0.0389

      epoch  75/200: loss=0.000103, IC=-0.0442

      epoch 100/200: loss=0.000092, IC=-0.0443

      epoch 125/200: loss=0.000087, IC=-0.0381

      epoch 150/200: loss=0.000084, IC=-0.0455

      epoch 175/200: loss=0.000083, IC=-0.0477

      epoch 200/200: loss=0.000083, IC=-0.0487

    Fold 1: best_ep=25, IC=-0.0326 (8.3s)

      epoch  25/200: loss=0.000137, IC=-0.0354

      epoch  50/200: loss=0.000094, IC=-0.0274

      epoch  75/200: loss=0.000075, IC=-0.0294

      epoch 100/200: loss=0.000066, IC=-0.0531

      epoch 125/200: loss=0.000058, IC=-0.0547

      epoch 150/200: loss=0.000057, IC=-0.0563

      epoch 175/200: loss=0.000054, IC=-0.0541

      epoch 200/200: loss=0.000053, IC=-0.0544

    Fold 1: best_ep=50, IC=-0.0274 (11.2s)

  Fold 2: train=25,700  val=5,160

      epoch  25/200: loss=0.000181, IC=+0.0373

      epoch  50/200: loss=0.000154, IC=+0.0576

      epoch  75/200: loss=0.000141, IC=+0.0649

      epoch 100/200: loss=0.000130, IC=+0.0571

      epoch 125/200: loss=0.000124, IC=+0.0602

      epoch 150/200: loss=0.000122, IC=+0.0593

      epoch 175/200: loss=0.000121, IC=+0.0589

      epoch 200/200: loss=0.000121, IC=+0.0566

    Fold 2: best_ep=75, IC=+0.0649 (8.7s)

      epoch  25/200: loss=0.000156, IC=+0.0399

      epoch  50/200: loss=0.000121, IC=+0.0560

      epoch  75/200: loss=0.000107, IC=+0.0400

      epoch 100/200: loss=0.000095, IC=+0.0476

      epoch 125/200: loss=0.000090, IC=+0.0483

      epoch 150/200: loss=0.000089, IC=+0.0366

      epoch 175/200: loss=0.000086, IC=+0.0350

      epoch 200/200: loss=0.000085, IC=+0.0371

    Fold 2: best_ep=50, IC=+0.0560 (10.8s)

      epoch  25/200: loss=0.000140, IC=+0.0461

      epoch  50/200: loss=0.000097, IC=+0.0586

      epoch  75/200: loss=0.000078, IC=+0.0601

      epoch 100/200: loss=0.000066, IC=+0.0681

      epoch 125/200: loss=0.000059, IC=+0.0639

      epoch 150/200: loss=0.000055, IC=+0.0638

      epoch 175/200: loss=0.000055, IC=+0.0673

      epoch 200/200: loss=0.000054, IC=+0.0676

    Fold 2: best_ep=100, IC=+0.0681 (15.1s)

  Fold 3: train=25,700  val=5,160

      epoch  25/200: loss=0.000187, IC=-0.0274

      epoch  50/200: loss=0.000177, IC=-0.0270

      epoch  75/200: loss=0.000169, IC=-0.0169

      epoch 100/200: loss=0.000158, IC=-0.0055

      epoch 125/200: loss=0.000154, IC=+0.0163

      epoch 150/200: loss=0.000153, IC=+0.0146

      epoch 175/200: loss=0.000151, IC=+0.0142

      epoch 200/200: loss=0.000152, IC=+0.0142

    Fold 3: best_ep=125, IC=+0.0163 (7.4s)

      epoch  25/200: loss=0.000142, IC=+0.0017

      epoch  50/200: loss=0.000114, IC=+0.0125

      epoch  75/200: loss=0.000097, IC=+0.0035

      epoch 100/200: loss=0.000090, IC=+0.0084

      epoch 125/200: loss=0.000084, IC=+0.0079

      epoch 150/200: loss=0.000081, IC=+0.0148

      epoch 175/200: loss=0.000081, IC=+0.0115

      epoch 200/200: loss=0.000080, IC=+0.0114

    Fold 3: best_ep=150, IC=+0.0148 (9.9s)

      epoch  25/200: loss=0.000128, IC=+0.0048

      epoch  50/200: loss=0.000091, IC=+0.0301

      epoch  75/200: loss=0.000072, IC=+0.0197

      epoch 100/200: loss=0.000061, IC=+0.0247

      epoch 125/200: loss=0.000055, IC=+0.0156

      epoch 150/200: loss=0.000052, IC=+0.0166

      epoch 175/200: loss=0.000050, IC=+0.0169

      epoch 200/200: loss=0.000050, IC=+0.0164

    Fold 3: best_ep=50, IC=+0.0301 (14.2s)

  Fold 4: train=25,700  val=5,160

      epoch  25/200: loss=0.000192, IC=-0.0634

      epoch  50/200: loss=0.000175, IC=-0.0533

      epoch  75/200: loss=0.000166, IC=-0.0498

      epoch 100/200: loss=0.000162, IC=-0.0512

      epoch 125/200: loss=0.000154, IC=-0.0431

      epoch 150/200: loss=0.000149, IC=-0.0443

      epoch 175/200: loss=0.000147, IC=-0.0473

      epoch 200/200: loss=0.000149, IC=-0.0461

    Fold 4: best_ep=125, IC=-0.0431 (8.9s)

      epoch  25/200: loss=0.000173, IC=-0.0418

      epoch  50/200: loss=0.000157, IC=-0.0308

      epoch  75/200: loss=0.000140, IC=-0.0251

      epoch 100/200: loss=0.000128, IC=-0.0307

      epoch 125/200: loss=0.000121, IC=-0.0290

      epoch 150/200: loss=0.000119, IC=-0.0293

      epoch 175/200: loss=0.000113, IC=-0.0287

      epoch 200/200: loss=0.000114, IC=-0.0272

    Fold 4: best_ep=75, IC=-0.0251 (10.5s)

      epoch  25/200: loss=0.000122, IC=-0.0252

      epoch  50/200: loss=0.000087, IC=-0.0402

      epoch  75/200: loss=0.000070, IC=-0.0285

      epoch 100/200: loss=0.000060, IC=-0.0310

      epoch 125/200: loss=0.000055, IC=-0.0303

      epoch 150/200: loss=0.000052, IC=-0.0231

      epoch 175/200: loss=0.000050, IC=-0.0266

      epoch 200/200: loss=0.000049, IC=-0.0240

    Fold 4: best_ep=150, IC=-0.0231 (15.7s)

  Fold 5: train=25,700  val=5,160

      epoch  25/200: loss=0.000126, IC=+0.0130

      epoch  50/200: loss=0.000108, IC=+0.0178

      epoch  75/200: loss=0.000099, IC=+0.0132

      epoch 100/200: loss=0.000094, IC=+0.0216

      epoch 125/200: loss=0.000089, IC=+0.0164

      epoch 150/200: loss=0.000088, IC=+0.0200

      epoch 175/200: loss=0.000087, IC=+0.0187

      epoch 200/200: loss=0.000089, IC=+0.0198

    Fold 5: best_ep=100, IC=+0.0216 (8.3s)

      epoch  25/200: loss=0.000121, IC=-0.0151

      epoch  50/200: loss=0.000095, IC=-0.0034

      epoch  75/200: loss=0.000081, IC=+0.0030

      epoch 100/200: loss=0.000074, IC=+0.0025

      epoch 125/200: loss=0.000069, IC=+0.0023

      epoch 150/200: loss=0.000067, IC=+0.0053

      epoch 175/200: loss=0.000066, IC=+0.0073

      epoch 200/200: loss=0.000067, IC=+0.0075

    Fold 5: best_ep=200, IC=+0.0075 (8.9s)

      epoch  25/200: loss=0.000100, IC=+0.0376

      epoch  50/200: loss=0.000068, IC=+0.0636

      epoch  75/200: loss=0.000055, IC=+0.0537

      epoch 100/200: loss=0.000048, IC=+0.0541

      epoch 125/200: loss=0.000043, IC=+0.0645

      epoch 150/200: loss=0.000041, IC=+0.0656

      epoch 175/200: loss=0.000040, IC=+0.0584

      epoch 200/200: loss=0.000041, IC=+0.0581

    Fold 5: best_ep=150, IC=+0.0656 (14.1s)

  Fold 6: train=25,700  val=5,160

      epoch  25/200: loss=0.000114, IC=-0.0713

      epoch  50/200: loss=0.000102, IC=-0.0540

      epoch  75/200: loss=0.000093, IC=-0.0625

      epoch 100/200: loss=0.000088, IC=-0.0616

      epoch 125/200: loss=0.000084, IC=-0.0544

      epoch 150/200: loss=0.000083, IC=-0.0520

      epoch 175/200: loss=0.000082, IC=-0.0492

      epoch 200/200: loss=0.000081, IC=-0.0489

    Fold 6: best_ep=200, IC=-0.0489 (7.6s)

      epoch  25/200: loss=0.000101, IC=-0.0512

      epoch  50/200: loss=0.000082, IC=-0.0153

      epoch  75/200: loss=0.000069, IC=-0.0211

      epoch 100/200: loss=0.000061, IC=-0.0269

      epoch 125/200: loss=0.000059, IC=-0.0359

      epoch 150/200: loss=0.000056, IC=-0.0397

      epoch 175/200: loss=0.000056, IC=-0.0377

      epoch 200/200: loss=0.000055, IC=-0.0369

    Fold 6: best_ep=50, IC=-0.0153 (9.5s)

      epoch  25/200: loss=0.000076, IC=-0.0282

      epoch  50/200: loss=0.000053, IC=-0.0352

      epoch  75/200: loss=0.000043, IC=-0.0235

      epoch 100/200: loss=0.000037, IC=-0.0323

      epoch 125/200: loss=0.000034, IC=-0.0287

      epoch 150/200: loss=0.000032, IC=-0.0255

      epoch 175/200: loss=0.000031, IC=-0.0271

      epoch 200/200: loss=0.000031, IC=-0.0276

    Fold 6: best_ep=75, IC=-0.0235 (14.3s)

  Fold 7: train=25,700  val=5,060

      epoch  25/200: loss=0.000137, IC=+0.0032

      epoch  50/200: loss=0.000123, IC=-0.0101

      epoch  75/200: loss=0.000114, IC=-0.0125

      epoch 100/200: loss=0.000109, IC=-0.0350

      epoch 125/200: loss=0.000106, IC=-0.0422

      epoch 150/200: loss=0.000102, IC=-0.0484

      epoch 175/200: loss=0.000102, IC=-0.0503

      epoch 200/200: loss=0.000102, IC=-0.0502

    Fold 7: best_ep=25, IC=+0.0032 (7.9s)

      epoch  25/200: loss=0.000120, IC=-0.0262

      epoch  50/200: loss=0.000094, IC=-0.0256

      epoch  75/200: loss=0.000081, IC=-0.0427

      epoch 100/200: loss=0.000073, IC=-0.0291

      epoch 125/200: loss=0.000069, IC=-0.0312

      epoch 150/200: loss=0.000067, IC=-0.0260

      epoch 175/200: loss=0.000067, IC=-0.0292

      epoch 200/200: loss=0.000064, IC=-0.0276

    Fold 7: best_ep=50, IC=-0.0256 (11.4s)

      epoch  25/200: loss=0.000083, IC=-0.0305

      epoch  50/200: loss=0.000058, IC=-0.0294

      epoch  75/200: loss=0.000047, IC=-0.0323

      epoch 100/200: loss=0.000040, IC=-0.0355

      epoch 125/200: loss=0.000037, IC=-0.0486

      epoch 150/200: loss=0.000035, IC=-0.0395

      epoch 175/200: loss=0.000035, IC=-0.0423

      epoch 200/200: loss=0.000034, IC=-0.0395

    Fold 7: best_ep=50, IC=-0.0294 (16.2s)

    → best_epoch=125, IC=-0.0000 (61.4s)

    → best_epoch=50, IC=-0.0068 (76.3s)

    → best_epoch=50, IC=+0.0099 (111.8s)

  Best: ba4916d1b246 @ epoch 50 (IC=+0.0099)

Preparing and releasing folds...
  Fold 0: train=17,860  val=5,160

      epoch  25/200: loss=0.000582, IC=+0.0308

      epoch  50/200: loss=0.000412, IC=+0.0529

      epoch  75/200: loss=0.000334, IC=+0.0612

      epoch 100/200: loss=0.000288, IC=+0.0534

      epoch 125/200: loss=0.000264, IC=+0.0382

      epoch 150/200: loss=0.000262, IC=+0.0344

      epoch 175/200: loss=0.000257, IC=+0.0309

      epoch 200/200: loss=0.000251, IC=+0.0312

    Fold 0: best_ep=75, IC=+0.0612 (5.2s)

      epoch  25/200: loss=0.000345, IC=+0.0050

      epoch  50/200: loss=0.000233, IC=+0.0170

      epoch  75/200: loss=0.000187, IC=+0.0134

      epoch 100/200: loss=0.000160, IC=+0.0175

      epoch 125/200: loss=0.000150, IC=+0.0161

      epoch 150/200: loss=0.000144, IC=+0.0185

      epoch 175/200: loss=0.000141, IC=+0.0160

      epoch 200/200: loss=0.000139, IC=+0.0175

    Fold 0: best_ep=150, IC=+0.0185 (6.9s)

      epoch  25/200: loss=0.000273, IC=+0.0641

      epoch  50/200: loss=0.000157, IC=+0.0388

      epoch  75/200: loss=0.000122, IC=+0.0278

      epoch 100/200: loss=0.000105, IC=+0.0253

      epoch 125/200: loss=0.000093, IC=+0.0178

      epoch 150/200: loss=0.000088, IC=+0.0212

      epoch 175/200: loss=0.000086, IC=+0.0145

      epoch 200/200: loss=0.000083, IC=+0.0166

    Fold 0: best_ep=25, IC=+0.0641 (11.4s)

  Fold 1: train=23,020  val=5,160

      epoch  25/200: loss=0.000661, IC=+0.0118

      epoch  50/200: loss=0.000468, IC=-0.0317

      epoch  75/200: loss=0.000382, IC=-0.0389

      epoch 100/200: loss=0.000339, IC=-0.0380

      epoch 125/200: loss=0.000318, IC=-0.0362

      epoch 150/200: loss=0.000307, IC=-0.0352

      epoch 175/200: loss=0.000304, IC=-0.0327

      epoch 200/200: loss=0.000306, IC=-0.0303

    Fold 1: best_ep=25, IC=+0.0118 (8.2s)

      epoch  25/200: loss=0.000381, IC=-0.0343

      epoch  50/200: loss=0.000257, IC=-0.0308

      epoch  75/200: loss=0.000206, IC=-0.0341

      epoch 100/200: loss=0.000184, IC=-0.0559

      epoch 125/200: loss=0.000170, IC=-0.0629

      epoch 150/200: loss=0.000163, IC=-0.0616

      epoch 175/200: loss=0.000160, IC=-0.0603

      epoch 200/200: loss=0.000162, IC=-0.0614

    Fold 1: best_ep=50, IC=-0.0308 (10.2s)

      epoch  25/200: loss=0.000298, IC=-0.0655

      epoch  50/200: loss=0.000180, IC=-0.0916

      epoch  75/200: loss=0.000140, IC=-0.0928

      epoch 100/200: loss=0.000119, IC=-0.0775

      epoch 125/200: loss=0.000108, IC=-0.0820

      epoch 150/200: loss=0.000101, IC=-0.0825

      epoch 175/200: loss=0.000101, IC=-0.0796

      epoch 200/200: loss=0.000099, IC=-0.0814

    Fold 1: best_ep=25, IC=-0.0655 (12.4s)

  Fold 2: train=25,380  val=5,160

      epoch  25/200: loss=0.000523, IC=+0.1538

      epoch  50/200: loss=0.000395, IC=+0.1941

      epoch  75/200: loss=0.000330, IC=+0.1957

      epoch 100/200: loss=0.000302, IC=+0.1850

      epoch 125/200: loss=0.000291, IC=+0.1740

      epoch 150/200: loss=0.000274, IC=+0.1659

      epoch 175/200: loss=0.000270, IC=+0.1694

      epoch 200/200: loss=0.000274, IC=+0.1680

    Fold 2: best_ep=75, IC=+0.1957 (9.1s)

      epoch  25/200: loss=0.000412, IC=+0.1823

      epoch  50/200: loss=0.000290, IC=+0.1825

      epoch  75/200: loss=0.000227, IC=+0.1769

      epoch 100/200: loss=0.000203, IC=+0.1751

      epoch 125/200: loss=0.000190, IC=+0.1781

      epoch 150/200: loss=0.000174, IC=+0.1722

      epoch 175/200: loss=0.000173, IC=+0.1740

      epoch 200/200: loss=0.000175, IC=+0.1710

    Fold 2: best_ep=50, IC=+0.1825 (10.6s)

      epoch  25/200: loss=0.000315, IC=+0.1183

      epoch  50/200: loss=0.000184, IC=+0.1083

      epoch  75/200: loss=0.000144, IC=+0.1105

      epoch 100/200: loss=0.000125, IC=+0.0995

      epoch 125/200: loss=0.000111, IC=+0.1048

      epoch 150/200: loss=0.000104, IC=+0.0985

      epoch 175/200: loss=0.000103, IC=+0.1002

      epoch 200/200: loss=0.000103, IC=+0.1003

    Fold 2: best_ep=25, IC=+0.1183 (15.1s)

  Fold 3: train=25,380  val=5,160

      epoch  25/200: loss=0.000600, IC=-0.0017

      epoch  50/200: loss=0.000474, IC=+0.0569

      epoch  75/200: loss=0.000403, IC=+0.0543

      epoch 100/200: loss=0.000370, IC=+0.0489

      epoch 125/200: loss=0.000344, IC=+0.0502

      epoch 150/200: loss=0.000331, IC=+0.0490

      epoch 175/200: loss=0.000330, IC=+0.0495

      epoch 200/200: loss=0.000336, IC=+0.0498

    Fold 3: best_ep=50, IC=+0.0569 (9.5s)

      epoch  25/200: loss=0.000361, IC=+0.0269

      epoch  50/200: loss=0.000250, IC=+0.0339

      epoch  75/200: loss=0.000204, IC=+0.0026

      epoch 100/200: loss=0.000178, IC=+0.0046

      epoch 125/200: loss=0.000164, IC=+0.0061

      epoch 150/200: loss=0.000158, IC=-0.0046

      epoch 175/200: loss=0.000159, IC=-0.0075

      epoch 200/200: loss=0.000159, IC=-0.0069

    Fold 3: best_ep=50, IC=+0.0339 (10.4s)

      epoch  25/200: loss=0.000265, IC=+0.0177

      epoch  50/200: loss=0.000163, IC=+0.0427

      epoch  75/200: loss=0.000130, IC=+0.0323

      epoch 100/200: loss=0.000110, IC=+0.0343

      epoch 125/200: loss=0.000099, IC=+0.0191

      epoch 150/200: loss=0.000094, IC=+0.0155

      epoch 175/200: loss=0.000092, IC=+0.0188

      epoch 200/200: loss=0.000093, IC=+0.0212

    Fold 3: best_ep=50, IC=+0.0427 (16.3s)

  Fold 4: train=25,380  val=5,160

      epoch  25/200: loss=0.000549, IC=-0.1758

      epoch  50/200: loss=0.000426, IC=-0.1471

      epoch  75/200: loss=0.000363, IC=-0.1504

      epoch 100/200: loss=0.000339, IC=-0.1556

      epoch 125/200: loss=0.000319, IC=-0.1536

      epoch 150/200: loss=0.000309, IC=-0.1548

      epoch 175/200: loss=0.000303, IC=-0.1593

      epoch 200/200: loss=0.000299, IC=-0.1587

    Fold 4: best_ep=50, IC=-0.1471 (8.6s)

      epoch  25/200: loss=0.000467, IC=-0.1863

      epoch  50/200: loss=0.000322, IC=-0.1572

      epoch  75/200: loss=0.000254, IC=-0.1844

      epoch 100/200: loss=0.000215, IC=-0.1964

      epoch 125/200: loss=0.000201, IC=-0.1945

      epoch 150/200: loss=0.000190, IC=-0.1916

      epoch 175/200: loss=0.000183, IC=-0.1993

      epoch 200/200: loss=0.000181, IC=-0.1954

    Fold 4: best_ep=50, IC=-0.1572 (10.4s)

      epoch  25/200: loss=0.000228, IC=-0.1279

      epoch  50/200: loss=0.000139, IC=-0.1435

      epoch  75/200: loss=0.000109, IC=-0.1464

      epoch 100/200: loss=0.000095, IC=-0.1380

      epoch 125/200: loss=0.000088, IC=-0.1321

      epoch 150/200: loss=0.000081, IC=-0.1349

      epoch 175/200: loss=0.000080, IC=-0.1384

      epoch 200/200: loss=0.000080, IC=-0.1382

    Fold 4: best_ep=25, IC=-0.1279 (16.1s)

  Fold 5: train=25,380  val=5,160

      epoch  25/200: loss=0.000357, IC=+0.0817

      epoch  50/200: loss=0.000276, IC=+0.0717

      epoch  75/200: loss=0.000238, IC=+0.0690

      epoch 100/200: loss=0.000216, IC=+0.0629

      epoch 125/200: loss=0.000208, IC=+0.0620

      epoch 150/200: loss=0.000196, IC=+0.0572

      epoch 175/200: loss=0.000198, IC=+0.0553

      epoch 200/200: loss=0.000195, IC=+0.0571

    Fold 5: best_ep=25, IC=+0.0817 (8.4s)

      epoch  25/200: loss=0.000303, IC=+0.0412

      epoch  50/200: loss=0.000199, IC=+0.0580

      epoch  75/200: loss=0.000163, IC=+0.0496

      epoch 100/200: loss=0.000139, IC=+0.0457

      epoch 125/200: loss=0.000129, IC=+0.0318

      epoch 150/200: loss=0.000123, IC=+0.0354

      epoch 175/200: loss=0.000121, IC=+0.0321

      epoch 200/200: loss=0.000121, IC=+0.0329

    Fold 5: best_ep=50, IC=+0.0580 (12.6s)

      epoch  25/200: loss=0.000214, IC=+0.0645

      epoch  50/200: loss=0.000132, IC=+0.0713

      epoch  75/200: loss=0.000103, IC=+0.0523

      epoch 100/200: loss=0.000086, IC=+0.0438

      epoch 125/200: loss=0.000081, IC=+0.0370

      epoch 150/200: loss=0.000075, IC=+0.0334

      epoch 175/200: loss=0.000075, IC=+0.0324

      epoch 200/200: loss=0.000074, IC=+0.0323

    Fold 5: best_ep=50, IC=+0.0713 (15.9s)

  Fold 6: train=25,380  val=5,160

      epoch  25/200: loss=0.000341, IC=-0.0179

      epoch  50/200: loss=0.000258, IC=+0.0028

      epoch  75/200: loss=0.000216, IC=-0.0170

      epoch 100/200: loss=0.000194, IC=-0.0214

      epoch 125/200: loss=0.000181, IC=-0.0211

      epoch 150/200: loss=0.000174, IC=-0.0209

      epoch 175/200: loss=0.000171, IC=-0.0192

      epoch 200/200: loss=0.000169, IC=-0.0214

    Fold 6: best_ep=50, IC=+0.0028 (8.8s)

      epoch  25/200: loss=0.000256, IC=+0.0125

      epoch  50/200: loss=0.000165, IC=-0.0062

      epoch  75/200: loss=0.000128, IC=-0.0100

      epoch 100/200: loss=0.000113, IC=-0.0048

      epoch 125/200: loss=0.000101, IC=-0.0083

      epoch 150/200: loss=0.000098, IC=-0.0084

      epoch 175/200: loss=0.000095, IC=-0.0091

      epoch 200/200: loss=0.000095, IC=-0.0104

    Fold 6: best_ep=25, IC=+0.0125 (9.2s)

      epoch  25/200: loss=0.000161, IC=+0.0405

      epoch  50/200: loss=0.000097, IC=+0.0202

      epoch  75/200: loss=0.000073, IC=+0.0255

      epoch 100/200: loss=0.000063, IC=+0.0354

      epoch 125/200: loss=0.000057, IC=+0.0265

      epoch 150/200: loss=0.000055, IC=+0.0351

      epoch 175/200: loss=0.000054, IC=+0.0338

      epoch 200/200: loss=0.000053, IC=+0.0329

    Fold 6: best_ep=25, IC=+0.0405 (15.7s)

  Fold 7: train=25,380  val=4,740

      epoch  25/200: loss=0.000436, IC=-0.1308

      epoch  50/200: loss=0.000324, IC=-0.0973

      epoch  75/200: loss=0.000272, IC=-0.1229

      epoch 100/200: loss=0.000248, IC=-0.1342

      epoch 125/200: loss=0.000232, IC=-0.1275

      epoch 150/200: loss=0.000222, IC=-0.1239

      epoch 175/200: loss=0.000220, IC=-0.1200

      epoch 200/200: loss=0.000216, IC=-0.1196

    Fold 7: best_ep=50, IC=-0.0973 (9.1s)

      epoch  25/200: loss=0.000324, IC=-0.0980

      epoch  50/200: loss=0.000206, IC=-0.1306

      epoch  75/200: loss=0.000164, IC=-0.0950

      epoch 100/200: loss=0.000147, IC=-0.0966

      epoch 125/200: loss=0.000132, IC=-0.0878

      epoch 150/200: loss=0.000123, IC=-0.0925

      epoch 175/200: loss=0.000121, IC=-0.0896

      epoch 200/200: loss=0.000120, IC=-0.0903

    Fold 7: best_ep=125, IC=-0.0878 (11.0s)

      epoch  25/200: loss=0.000194, IC=-0.1253

      epoch  50/200: loss=0.000118, IC=-0.1451

      epoch  75/200: loss=0.000092, IC=-0.1520

      epoch 100/200: loss=0.000079, IC=-0.1465

      epoch 125/200: loss=0.000073, IC=-0.1497

      epoch 150/200: loss=0.000068, IC=-0.1479

      epoch 175/200: loss=0.000067, IC=-0.1472

      epoch 200/200: loss=0.000065, IC=-0.1470

    Fold 7: best_ep=25, IC=-0.1253 (13.0s)

    → best_epoch=50, IC=+0.0139 (67.1s)

    → best_epoch=50, IC=-0.0029 (81.4s)

    → best_epoch=25, IC=-0.0004 (116.1s)

  Best: d642e0e22691 @ epoch 50 (IC=+0.0139)

shape: (72, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean   ┆ ic_t      ┆ training_ ┆ predicti │
│ ---       ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---       ┆ ---       ┆ hash      ┆ on_hash  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ i64       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 25        ┆ … ┆ -0.003591 ┆ -0.454919 ┆ bcd0dc793 ┆ ef6b06c7 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ a8c       ┆ 97bd     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 50        ┆ … ┆ 0.002004  ┆ 0.270878  ┆ bcd0dc793 ┆ d2e4dd2d │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ a8c       ┆ 1cf5     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 75        ┆ … ┆ -0.00215  ┆ -0.321538 ┆ bcd0dc793 ┆ 3504fb8b │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ a8c       ┆ c466     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 100       ┆ … ┆ -0.000704 ┆ -0.094443 ┆ bcd0dc793 ┆ d7ff7678 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ a8c       ┆ 67bb     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 125       ┆ … ┆ -0.003191 ┆ -0.420699 ┆ bcd0dc793 ┆ e34ff415 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ a8c       ┆ 25a5     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 100       ┆ … ┆ -0.004602 ┆ -0.33604  ┆ f76f07473 ┆ dda1dee2 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5d9       ┆ 10b1     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 125       ┆ … ┆ -0.000123 ┆ -0.009084 ┆ f76f07473 ┆ 84fc0eb0 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5d9       ┆ 94b2     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 150       ┆ … ┆ -0.000485 ┆ -0.035068 ┆ f76f07473 ┆ 15a0cbde │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5d9       ┆ b7f8     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 175       ┆ … ┆ -0.001647 ┆ -0.119958 ┆ f76f07473 ┆ 6fb2f7b9 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5d9       ┆ 9567     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 200       ┆ … ┆ -0.001538 ┆ -0.113616 ┆ f76f07473 ┆ 0962c68b │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5d9       ┆ 1451     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Reload the checkpoint population

Repeating the same request validates the saved checkpoint manifests and returns the same catalog
identities. No empty cached summary or single IC-chosen checkpoint is substituted.

In [7]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("TabM checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview checkpoints remain outside official comparison and holdout selection.")

Official prediction population: 33cefe348c67

## Key takeaways

- Train-only preprocessing and checkpoint persistence belong to the shared TabM computation.
- Every declared epoch remains available to the backtest stage.
- Rank correlation is a diagnostic field in the catalog, not a checkpoint-selection rule.