# Tabular Deep Learning - FX Pairs

TabM applies a small neural network to each decision row without turning the history into a
sequence. This notebook submits the published capacity choices to the shared TabM runner. The
runner fits preprocessing inside each training fold, saves every declared weight checkpoint, and
publishes a separate complete validation prediction set for every checkpoint.

**Learning objectives**

- Express neural-network capacity and checkpoint schedules as visible requests.
- Verify that every fold and epoch checkpoint has reloadable fitted state.
- Continue from complete prediction rows without selecting a checkpoint by rank correlation.

**Book reference**: Chapter 12, Section 12.3

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published TabM FX configurations."""

import polars as pl
import torch

from case_studies.research import (
    ExecutionTier,
    declared_labels,
    narrows_declared_catalog,
    open_study,
    plan_models,
    population_supersedes,
    sweep_labels,
)
from utils.modeling import load_configs
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
BATCH_SIZE = 0
DEVICE = ""
SEED = 42
POPULATION_NAME = ""
SUPERSEDES_POPULATION: str = "33cefe348c67"
# The tier is a parameter, not something inferred from whether a reduction happens to be set.
# Inferring it meant a run could be reduced and still open the case study's own artifacts in
# place, which is the production path; a reader under test then wrote where the published run
# writes. WORKSPACE is the other half: a preview has nowhere else to put its results.
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None

## Select the task and execution tier

Canonical execution uses every configured fold, symbol, epoch, and batch setting. A preview
declares its reductions, takes an isolated workspace, and creates a preview identity there. A
preview proves the path but cannot join the official model population.

The reductions are read before the study is opened, because which study to open is decided by
the tier and the two have to agree: a preview that reduces nothing is a canonical run wearing
the wrong tier, and a canonical run carrying reductions would publish a narrowed population
under the canonical name.

In [3]:
set_global_seeds(SEED)
REDUCTION_PARAMETERS = {
    "folds": list(range(MAX_FOLDS)) if MAX_FOLDS else None,
    "max_symbols": MAX_SYMBOLS or None,
    "n_epochs": N_EPOCHS or None,
}
reductions = {key: value for key, value in REDUCTION_PARAMETERS.items() if value is not None}
tier = ExecutionTier(EXECUTION_TIER)
if tier is ExecutionTier.PREVIEW and not reductions:
    raise ValueError("preview execution must declare at least one reduction")
if tier is ExecutionTier.CANONICAL and reductions:
    raise ValueError(f"canonical execution cannot carry reductions: {sorted(reductions)}")
study = open_study(CASE_STUDY_ID, execution_tier=tier, workspace=WORKSPACE or None)

# Which labels this notebook fits is a question for the training menus, not for the sweep list:
# `setup.yaml` says which labels the case study carries, a menu says what to fit for one of them,
# and a label in the sweep whose menu declares no `tabular_dl:` section owes nothing here. The two
# agree in this case study today, so restating the sweep list produced the right answer by
# coincidence and would have kept producing it silently after a menu changed. The order stays
# `setup.yaml`'s rather than `declared_labels`' menu-file order because the population is named
# after its labels and hashed over its members as an ordered list, so re-ordering would give the
# published population a new identity and demand a supersedes for a run that fits the same models.
fits_tabm = set(declared_labels(study, "tabular_dl"))
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [label for label in sweep_labels(study) if label in fits_tabm]
)

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")


print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
# An empty DEVICE resolves to what the machine has. The runners refuse "cuda" on a host without
# it rather than falling back silently - which is the right contract for a run whose results get
# registered - so a hardcoded "cuda" default made the notebook unrunnable for any reader without
# an NVIDIA card, and unrunnable on a CPU CI runner. Resolving here keeps the refusal for anyone
# who asks for "cuda" explicitly, and prints what was chosen so a run never leaves it implicit.
device = DEVICE or ("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda

## Build the published requests

The YAML menu supplies the architecture settings and production checkpoint schedules. The
parameter cell can reduce epochs or change batch size for a preview without changing the menu.

In [4]:
overrides = {
    "device": device,
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
}
menu = [
    (label, config)
    for label in labels
    for config in load_configs(CASE_STUDY_ID, label, family="tabular_dl")
]

# `PRIMARY_LABEL` narrows what is fitted, and a narrowed run declares a different set of members
# than the canonical population does. A population is immutable once written, so such a run must
# publish under its own name. The comparison is over `(label, config_name)` pairs rather than a
# row count, and it says so here rather than several cells later in a message about hashes.
if (
    narrows_declared_catalog(
        study,
        "tabular_dl",
        pl.DataFrame(
            {
                "label": [label for label, _ in menu],
                "config_name": [config["config_name"] for _, config in menu],
            }
        ),
    )
    and not POPULATION_NAME
):
    raise ValueError(
        f"this run declares {len(menu)} label-configuration pairs, which is not the complete "
        "declared catalog, so it cannot publish the canonical population; pass POPULATION_NAME "
        "to give it its own"
    )
requests = [
    study.model(
        family="tabular_dl",
        label=label,
        config_name=config["config_name"],
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label, config in menu
]

pl.DataFrame(
    {
        "config_name": [request.config_name for request in requests],
        "label": [request.label for request in requests],
        "device": [device] * len(requests),
        "execution_tier": [request.execution_tier.value for request in requests],
    }
)

shape: (9, 4)
┌─────────────┬─────────────┬────────┬────────────────┐
│ config_name ┆ label       ┆ device ┆ execution_tier │
│ ---         ┆ ---         ┆ ---    ┆ ---            │
│ str         ┆ str         ┆ str    ┆ str            │
╞═════════════╪═════════════╪════════╪════════════════╡
│ tabm_s      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_1d  ┆ cuda   ┆ canonical      │
│ tabm_s      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_5d  ┆ cuda   ┆ canonical      │
│ tabm_s      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
│ tabm_m      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
│ tabm_l      ┆ fwd_ret_21d ┆ cuda   ┆ canonical      │
└─────────────┴─────────────┴────────┴────────────────┘

## Declare every epoch checkpoint before training

The declared epoch schedule, not the run that follows, decides how many downstream configurations
this notebook owes. Planning resolves each one without training, so a failed member is visible as
a gap in the population rather than a shorter catalog.

In [5]:
plan = plan_models(study, requests=requests)
if len(plan.expected_training_hashes) != len(requests):
    raise RuntimeError("each TabM configuration must plan exactly one training identity")

configured = {(label, config["config_name"]) for label, config in menu}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        "the plan does not match the configured TabM menu; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )

pl.DataFrame(
    {
        "label": [member.label for member in plan.members],
        "config_name": [member.config_name for member in plan.members],
        "checkpoint_kind": [member.checkpoint_kind for member in plan.members],
        "checkpoint_value": [member.checkpoint_value for member in plan.members],
        "prediction_hash": [member.prediction_hash for member in plan.members],
    }
)

shape: (72, 5)
┌─────────────┬─────────────┬─────────────────┬──────────────────┬─────────────────┐
│ label       ┆ config_name ┆ checkpoint_kind ┆ checkpoint_value ┆ prediction_hash │
│ ---         ┆ ---         ┆ ---             ┆ ---              ┆ ---             │
│ str         ┆ str         ┆ str             ┆ i64              ┆ str             │
╞═════════════╪═════════════╪═════════════════╪══════════════════╪═════════════════╡
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 25               ┆ 3b2d47609156    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 50               ┆ b444387c0009    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 75               ┆ 65c55a03e86f    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 100              ┆ b921c0e06f14    │
│ fwd_ret_1d  ┆ tabm_s      ┆ epoch           ┆ 125              ┆ 8b4f2229208d    │
│ …           ┆ …           ┆ …               ┆ …                ┆ …               │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 100              ┆ f10c663fb117    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 125              ┆ 999771014d8f    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 150              ┆ 8ed05637f42a    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 175              ┆ d3a51ca305cc    │
│ fwd_ret_21d ┆ tabm_l      ┆ epoch           ┆ 200              ┆ abda6927a2da    │
└─────────────┴─────────────┴─────────────────┴──────────────────┴─────────────────┘

## Record the official population, then fit or reload every capacity choice

Compatible TabM requests share base-fold materialization. Candidate-specific scaling, random
state, weights, and prediction identities remain separate. Any failed member stops the cell.

`SUPERSEDES_POPULATION` names the population hash this run replaces. A population is the set of
prediction identities it publishes, so anything that moves a training identity produces a
different population under the same name, and the registry refuses to write it without being
told which snapshot it supersedes. That lineage is the only record of which generation is which,
and what moved the identities here was a change to the family's own source file rather than to
anything the notebook declares.

`population_supersedes` decides whether the declared hash may be offered. It is offered when the
name already carries the generation this declaration produced, so a re-run resolves to the
population it published, and when the declaration names the generation in force, so a refit
publishes the next one. It is withheld everywhere else - on a reader's clean clone, where
`run_log/` is gitignored and the registry has no generation at all; under a caller's own
`POPULATION_NAME`; and in a preview, whose isolated registry holds nothing under this name.

In [6]:
population_name = POPULATION_NAME or f"{CASE_STUDY_ID}:{'+'.join(labels)}:tabular_dl"
population = (
    plan.create_population(
        name=population_name,
        supersedes=population_supersedes(
            study, name=population_name, declared=SUPERSEDES_POPULATION
        ),
    )
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
if len(execution.runs) != len(requests):
    raise RuntimeError("the TabM runner did not return every requested configuration")

catalog = execution.catalog_rows.sort("label", "config_name", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial TabM checkpoints cannot pass to backtesting")
if catalog.select("label", "config_name", "checkpoint_value").n_unique() != catalog.height:
    raise RuntimeError("each configuration and epoch checkpoint must identify one prediction set")
if catalog.get_column("checkpoint_value").null_count():
    raise RuntimeError("every TabM prediction must name its epoch checkpoint")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Preparing and releasing folds...
  Fold 0: train=18,260  val=5,160

      epoch  25/200: loss=0.000315, IC=-0.0140

      epoch  50/200: loss=0.000155, IC=-0.0185

      epoch  75/200: loss=0.000108, IC=-0.0117

      epoch 100/200: loss=0.000086, IC=-0.0031

      epoch 125/200: loss=0.000077, IC=+0.0036

      epoch 150/200: loss=0.000074, IC=+0.0059

      epoch 175/200: loss=0.000071, IC=+0.0082

      epoch 200/200: loss=0.000071, IC=+0.0087

    Fold 0: best_ep=200, IC=+0.0087 (6.9s)

      epoch  25/200: loss=0.000168, IC=-0.0136

      epoch  50/200: loss=0.000085, IC=-0.0320

      epoch  75/200: loss=0.000063, IC=-0.0262

      epoch 100/200: loss=0.000053, IC=-0.0273

      epoch 125/200: loss=0.000050, IC=-0.0259

      epoch 150/200: loss=0.000048, IC=-0.0249

      epoch 175/200: loss=0.000048, IC=-0.0262

      epoch 200/200: loss=0.000047, IC=-0.0258

    Fold 0: best_ep=25, IC=-0.0136 (6.1s)

      epoch  25/200: loss=0.000131, IC=-0.0190

      epoch  50/200: loss=0.000066, IC=-0.0154

      epoch  75/200: loss=0.000052, IC=-0.0194

      epoch 100/200: loss=0.000045, IC=-0.0200

      epoch 125/200: loss=0.000044, IC=-0.0210

      epoch 150/200: loss=0.000043, IC=-0.0201

      epoch 175/200: loss=0.000043, IC=-0.0216

      epoch 200/200: loss=0.000043, IC=-0.0215

    Fold 0: best_ep=50, IC=-0.0154 (10.7s)

  Fold 1: train=23,420  val=5,160

      epoch  25/200: loss=0.000201, IC=-0.0080

      epoch  50/200: loss=0.000105, IC=-0.0099

      epoch  75/200: loss=0.000078, IC=-0.0150

      epoch 100/200: loss=0.000068, IC=-0.0191

      epoch 125/200: loss=0.000063, IC=-0.0236

      epoch 150/200: loss=0.000060, IC=-0.0250

      epoch 175/200: loss=0.000059, IC=-0.0252

      epoch 200/200: loss=0.000058, IC=-0.0254

    Fold 1: best_ep=25, IC=-0.0080 (9.7s)

      epoch  25/200: loss=0.000118, IC=+0.0059

      epoch  50/200: loss=0.000066, IC=+0.0052

      epoch  75/200: loss=0.000054, IC=+0.0089

      epoch 100/200: loss=0.000051, IC=+0.0067

      epoch 125/200: loss=0.000049, IC=+0.0093

      epoch 150/200: loss=0.000048, IC=+0.0119

      epoch 175/200: loss=0.000048, IC=+0.0112

      epoch 200/200: loss=0.000047, IC=+0.0106

    Fold 1: best_ep=150, IC=+0.0119 (10.4s)

      epoch  25/200: loss=0.000130, IC=-0.0100

      epoch  50/200: loss=0.000068, IC=-0.0129

      epoch  75/200: loss=0.000054, IC=-0.0171

      epoch 100/200: loss=0.000050, IC=-0.0223

      epoch 125/200: loss=0.000049, IC=-0.0249

      epoch 150/200: loss=0.000047, IC=-0.0263

      epoch 175/200: loss=0.000047, IC=-0.0269

      epoch 200/200: loss=0.000047, IC=-0.0268

    Fold 1: best_ep=25, IC=-0.0100 (15.0s)

  Fold 2: train=25,780  val=5,160

      epoch  25/200: loss=0.000258, IC=+0.0042

      epoch  50/200: loss=0.000123, IC=-0.0113

      epoch  75/200: loss=0.000085, IC=-0.0059

      epoch 100/200: loss=0.000072, IC=-0.0100

      epoch 125/200: loss=0.000065, IC=-0.0091

      epoch 150/200: loss=0.000061, IC=-0.0101

      epoch 175/200: loss=0.000061, IC=-0.0088

      epoch 200/200: loss=0.000061, IC=-0.0093

    Fold 2: best_ep=25, IC=+0.0042 (11.5s)

      epoch  25/200: loss=0.000163, IC=+0.0133

      epoch  50/200: loss=0.000081, IC=+0.0217

      epoch  75/200: loss=0.000062, IC=+0.0196

      epoch 100/200: loss=0.000054, IC=+0.0187

      epoch 125/200: loss=0.000051, IC=+0.0162

      epoch 150/200: loss=0.000049, IC=+0.0148

      epoch 175/200: loss=0.000049, IC=+0.0147

      epoch 200/200: loss=0.000049, IC=+0.0146

    Fold 2: best_ep=50, IC=+0.0217 (11.6s)

      epoch  25/200: loss=0.000104, IC=+0.0371

      epoch  50/200: loss=0.000057, IC=+0.0352

      epoch  75/200: loss=0.000048, IC=+0.0331

      epoch 100/200: loss=0.000045, IC=+0.0272

      epoch 125/200: loss=0.000045, IC=+0.0280

      epoch 150/200: loss=0.000044, IC=+0.0220

      epoch 175/200: loss=0.000044, IC=+0.0258

      epoch 200/200: loss=0.000044, IC=+0.0258

    Fold 2: best_ep=25, IC=+0.0371 (17.0s)

  Fold 3: train=25,780  val=5,160

      epoch  25/200: loss=0.000124, IC=+0.0445

      epoch  50/200: loss=0.000064, IC=+0.0399

      epoch  75/200: loss=0.000051, IC=+0.0385

      epoch 100/200: loss=0.000046, IC=+0.0391

      epoch 125/200: loss=0.000044, IC=+0.0366

      epoch 150/200: loss=0.000043, IC=+0.0392

      epoch 175/200: loss=0.000043, IC=+0.0364

      epoch 200/200: loss=0.000043, IC=+0.0364

    Fold 3: best_ep=25, IC=+0.0445 (12.3s)

      epoch  25/200: loss=0.000160, IC=-0.0118

      epoch  50/200: loss=0.000078, IC=-0.0090

      epoch  75/200: loss=0.000058, IC=-0.0101

      epoch 100/200: loss=0.000050, IC=-0.0090

      epoch 125/200: loss=0.000047, IC=-0.0107

      epoch 150/200: loss=0.000046, IC=-0.0134

      epoch 175/200: loss=0.000045, IC=-0.0136

      epoch 200/200: loss=0.000045, IC=-0.0126

    Fold 3: best_ep=100, IC=-0.0090 (13.4s)

      epoch  25/200: loss=0.000096, IC=+0.0054

      epoch  50/200: loss=0.000052, IC=+0.0089

      epoch  75/200: loss=0.000045, IC=+0.0077

      epoch 100/200: loss=0.000042, IC=+0.0086

      epoch 125/200: loss=0.000041, IC=+0.0093

      epoch 150/200: loss=0.000041, IC=+0.0103

      epoch 175/200: loss=0.000041, IC=+0.0107

      epoch 200/200: loss=0.000041, IC=+0.0108

    Fold 3: best_ep=200, IC=+0.0108 (16.9s)

  Fold 4: train=25,780  val=5,160

      epoch  25/200: loss=0.000179, IC=-0.0217

      epoch  50/200: loss=0.000092, IC=-0.0156

      epoch  75/200: loss=0.000066, IC=-0.0150

      epoch 100/200: loss=0.000056, IC=-0.0142

      epoch 125/200: loss=0.000054, IC=-0.0102

      epoch 150/200: loss=0.000049, IC=-0.0128

      epoch 175/200: loss=0.000049, IC=-0.0143

      epoch 200/200: loss=0.000050, IC=-0.0144

    Fold 4: best_ep=125, IC=-0.0102 (8.8s)

      epoch  25/200: loss=0.000150, IC=-0.0016

      epoch  50/200: loss=0.000078, IC=+0.0048

      epoch  75/200: loss=0.000056, IC=+0.0101

      epoch 100/200: loss=0.000048, IC=+0.0081

      epoch 125/200: loss=0.000048, IC=+0.0084

      epoch 150/200: loss=0.000044, IC=+0.0054

      epoch 175/200: loss=0.000044, IC=+0.0076

      epoch 200/200: loss=0.000045, IC=+0.0071

    Fold 4: best_ep=75, IC=+0.0101 (10.0s)

      epoch  25/200: loss=0.000103, IC=-0.0068

      epoch  50/200: loss=0.000056, IC=-0.0249

      epoch  75/200: loss=0.000044, IC=-0.0231

      epoch 100/200: loss=0.000041, IC=-0.0236

      epoch 125/200: loss=0.000043, IC=-0.0263

      epoch 150/200: loss=0.000040, IC=-0.0266

      epoch 175/200: loss=0.000040, IC=-0.0244

      epoch 200/200: loss=0.000041, IC=-0.0247

    Fold 4: best_ep=25, IC=-0.0068 (17.2s)

  Fold 5: train=25,780  val=5,160

      epoch  25/200: loss=0.000165, IC=+0.0086

      epoch  50/200: loss=0.000076, IC=+0.0082

      epoch  75/200: loss=0.000054, IC=-0.0012

      epoch 100/200: loss=0.000046, IC=-0.0041

      epoch 125/200: loss=0.000042, IC=-0.0034

      epoch 150/200: loss=0.000041, IC=-0.0036

      epoch 175/200: loss=0.000040, IC=-0.0040

      epoch 200/200: loss=0.000040, IC=-0.0034

    Fold 5: best_ep=25, IC=+0.0086 (12.4s)

      epoch  25/200: loss=0.000101, IC=+0.0152

      epoch  50/200: loss=0.000052, IC=+0.0148

      epoch  75/200: loss=0.000042, IC=+0.0174

      epoch 100/200: loss=0.000038, IC=+0.0203

      epoch 125/200: loss=0.000036, IC=+0.0228

      epoch 150/200: loss=0.000036, IC=+0.0226

      epoch 175/200: loss=0.000035, IC=+0.0235

      epoch 200/200: loss=0.000035, IC=+0.0241

    Fold 5: best_ep=200, IC=+0.0241 (11.3s)

      epoch  25/200: loss=0.000088, IC=+0.0050

      epoch  50/200: loss=0.000044, IC=-0.0013

      epoch  75/200: loss=0.000036, IC=-0.0013

      epoch 100/200: loss=0.000034, IC=-0.0035

      epoch 125/200: loss=0.000033, IC=-0.0079

      epoch 150/200: loss=0.000033, IC=-0.0089

      epoch 175/200: loss=0.000033, IC=-0.0102

      epoch 200/200: loss=0.000033, IC=-0.0106

    Fold 5: best_ep=25, IC=+0.0050 (17.5s)

  Fold 6: train=25,780  val=5,160

      epoch  25/200: loss=0.000130, IC=-0.0231

      epoch  50/200: loss=0.000060, IC=-0.0273

      epoch  75/200: loss=0.000042, IC=-0.0257

      epoch 100/200: loss=0.000035, IC=-0.0297

      epoch 125/200: loss=0.000032, IC=-0.0311

      epoch 150/200: loss=0.000030, IC=-0.0301

      epoch 175/200: loss=0.000030, IC=-0.0297

      epoch 200/200: loss=0.000030, IC=-0.0304

    Fold 6: best_ep=25, IC=-0.0231 (14.0s)

      epoch  25/200: loss=0.000106, IC=-0.0411

      epoch  50/200: loss=0.000047, IC=-0.0471

      epoch  75/200: loss=0.000035, IC=-0.0472

      epoch 100/200: loss=0.000030, IC=-0.0424

      epoch 125/200: loss=0.000028, IC=-0.0424

      epoch 150/200: loss=0.000028, IC=-0.0418

      epoch 175/200: loss=0.000027, IC=-0.0420

      epoch 200/200: loss=0.000027, IC=-0.0426

    Fold 6: best_ep=25, IC=-0.0411 (11.6s)

      epoch  25/200: loss=0.000095, IC=-0.0188

      epoch  50/200: loss=0.000043, IC=-0.0376

      epoch  75/200: loss=0.000031, IC=-0.0447

      epoch 100/200: loss=0.000028, IC=-0.0511

      epoch 125/200: loss=0.000027, IC=-0.0518

      epoch 150/200: loss=0.000026, IC=-0.0540

      epoch 175/200: loss=0.000026, IC=-0.0532

      epoch 200/200: loss=0.000026, IC=-0.0535

    Fold 6: best_ep=25, IC=-0.0188 (16.6s)

  Fold 7: train=25,780  val=5,140

      epoch  25/200: loss=0.000248, IC=+0.0185

      epoch  50/200: loss=0.000108, IC=-0.0048

      epoch  75/200: loss=0.000071, IC=-0.0163

      epoch 100/200: loss=0.000056, IC=-0.0158

      epoch 125/200: loss=0.000049, IC=-0.0108

      epoch 150/200: loss=0.000047, IC=-0.0089

      epoch 175/200: loss=0.000045, IC=-0.0074

      epoch 200/200: loss=0.000045, IC=-0.0069

    Fold 7: best_ep=25, IC=+0.0185 (13.0s)

      epoch  25/200: loss=0.000119, IC=-0.0014

      epoch  50/200: loss=0.000054, IC=-0.0025

      epoch  75/200: loss=0.000039, IC=+0.0041

      epoch 100/200: loss=0.000034, IC=+0.0111

      epoch 125/200: loss=0.000032, IC=+0.0149

      epoch 150/200: loss=0.000032, IC=+0.0146

      epoch 175/200: loss=0.000031, IC=+0.0165

      epoch 200/200: loss=0.000031, IC=+0.0160

    Fold 7: best_ep=175, IC=+0.0165 (11.2s)

      epoch  25/200: loss=0.000097, IC=+0.0167

      epoch  50/200: loss=0.000045, IC=+0.0222

      epoch  75/200: loss=0.000035, IC=+0.0138

      epoch 100/200: loss=0.000031, IC=+0.0128

      epoch 125/200: loss=0.000030, IC=+0.0132

      epoch 150/200: loss=0.000030, IC=+0.0132

      epoch 175/200: loss=0.000029, IC=+0.0114

      epoch 200/200: loss=0.000029, IC=+0.0115

    Fold 7: best_ep=50, IC=+0.0222 (17.0s)

    → best_epoch=25, IC=+0.0011 (88.7s)

    → best_epoch=125, IC=-0.0010 (85.9s)

    → best_epoch=25, IC=+0.0012 (128.2s)

  Best: d925320dc90c @ epoch 25 (IC=+0.0012)

Preparing and releasing folds...

  Fold 0: train=18,180  val=5,160

      epoch  25/200: loss=0.000465, IC=+0.0023

      epoch  50/200: loss=0.000298, IC=+0.0093

      epoch  75/200: loss=0.000249, IC=+0.0314

      epoch 100/200: loss=0.000227, IC=+0.0339

      epoch 125/200: loss=0.000219, IC=+0.0363

      epoch 150/200: loss=0.000216, IC=+0.0385

      epoch 175/200: loss=0.000212, IC=+0.0375

      epoch 200/200: loss=0.000217, IC=+0.0376

    Fold 0: best_ep=150, IC=+0.0385 (18.0s)

      epoch  25/200: loss=0.000311, IC=+0.0100

      epoch  50/200: loss=0.000229, IC=+0.0135

      epoch  75/200: loss=0.000204, IC=+0.0220

      epoch 100/200: loss=0.000195, IC=+0.0233

      epoch 125/200: loss=0.000191, IC=+0.0234

      epoch 150/200: loss=0.000191, IC=+0.0203

      epoch 175/200: loss=0.000189, IC=+0.0215

      epoch 200/200: loss=0.000192, IC=+0.0219

    Fold 0: best_ep=125, IC=+0.0234 (17.0s)

      epoch  25/200: loss=0.000274, IC=+0.0306

      epoch  50/200: loss=0.000210, IC=+0.0229

      epoch  75/200: loss=0.000193, IC=+0.0233

      epoch 100/200: loss=0.000187, IC=+0.0210

      epoch 125/200: loss=0.000184, IC=+0.0245

      epoch 150/200: loss=0.000185, IC=+0.0260

      epoch 175/200: loss=0.000182, IC=+0.0264

      epoch 200/200: loss=0.000186, IC=+0.0277

    Fold 0: best_ep=25, IC=+0.0306 (19.3s)

  Fold 1: train=23,340  val=5,160

      epoch  25/200: loss=0.000366, IC=-0.0348

      epoch  50/200: loss=0.000266, IC=-0.0522

      epoch  75/200: loss=0.000241, IC=-0.0562

      epoch 100/200: loss=0.000230, IC=-0.0613

      epoch 125/200: loss=0.000224, IC=-0.0626

      epoch 150/200: loss=0.000221, IC=-0.0622

      epoch 175/200: loss=0.000220, IC=-0.0607

      epoch 200/200: loss=0.000220, IC=-0.0606

    Fold 1: best_ep=25, IC=-0.0348 (27.8s)

      epoch  25/200: loss=0.000281, IC=-0.0170

      epoch  50/200: loss=0.000225, IC=-0.0272

      epoch  75/200: loss=0.000216, IC=-0.0299

      epoch 100/200: loss=0.000211, IC=-0.0330

      epoch 125/200: loss=0.000208, IC=-0.0321

      epoch 150/200: loss=0.000207, IC=-0.0315

      epoch 175/200: loss=0.000206, IC=-0.0317

      epoch 200/200: loss=0.000206, IC=-0.0311

    Fold 1: best_ep=25, IC=-0.0170 (30.3s)

      epoch  25/200: loss=0.000293, IC=-0.0460

      epoch  50/200: loss=0.000229, IC=-0.0529

      epoch  75/200: loss=0.000217, IC=-0.0535

      epoch 100/200: loss=0.000212, IC=-0.0492

      epoch 125/200: loss=0.000208, IC=-0.0478

      epoch 150/200: loss=0.000208, IC=-0.0461

      epoch 175/200: loss=0.000207, IC=-0.0452

      epoch 200/200: loss=0.000206, IC=-0.0451

    Fold 1: best_ep=200, IC=-0.0451 (21.1s)

  Fold 2: train=25,700  val=5,160

      epoch  25/200: loss=0.000416, IC=+0.0022

      epoch  50/200: loss=0.000280, IC=-0.0078

      epoch  75/200: loss=0.000247, IC=-0.0145

      epoch 100/200: loss=0.000230, IC=-0.0154

      epoch 125/200: loss=0.000221, IC=-0.0186

      epoch 150/200: loss=0.000218, IC=-0.0195

      epoch 175/200: loss=0.000216, IC=-0.0178

      epoch 200/200: loss=0.000216, IC=-0.0170

    Fold 2: best_ep=25, IC=+0.0022 (38.0s)

      epoch  25/200: loss=0.000320, IC=-0.0066

      epoch  50/200: loss=0.000237, IC=-0.0020

      epoch  75/200: loss=0.000223, IC=+0.0063

      epoch 100/200: loss=0.000211, IC=+0.0075

      epoch 125/200: loss=0.000206, IC=+0.0116

      epoch 150/200: loss=0.000205, IC=+0.0115

      epoch 175/200: loss=0.000202, IC=+0.0129

      epoch 200/200: loss=0.000203, IC=+0.0132

    Fold 2: best_ep=200, IC=+0.0132 (36.4s)

      epoch  25/200: loss=0.000263, IC=+0.0395

      epoch  50/200: loss=0.000214, IC=+0.0172

      epoch  75/200: loss=0.000211, IC=+0.0209

      epoch 100/200: loss=0.000203, IC=+0.0161

      epoch 125/200: loss=0.000200, IC=+0.0173

      epoch 150/200: loss=0.000200, IC=+0.0187

      epoch 175/200: loss=0.000198, IC=+0.0191

      epoch 200/200: loss=0.000198, IC=+0.0193

    Fold 2: best_ep=25, IC=+0.0395 (36.4s)

  Fold 3: train=25,700  val=5,160

      epoch  25/200: loss=0.000267, IC=+0.0513

      epoch  50/200: loss=0.000208, IC=+0.0466

      epoch  75/200: loss=0.000197, IC=+0.0381

      epoch 100/200: loss=0.000187, IC=+0.0287

      epoch 125/200: loss=0.000187, IC=+0.0220

      epoch 150/200: loss=0.000185, IC=+0.0221

      epoch 175/200: loss=0.000184, IC=+0.0249

      epoch 200/200: loss=0.000188, IC=+0.0244

    Fold 3: best_ep=25, IC=+0.0513 (18.5s)

      epoch  25/200: loss=0.000302, IC=-0.0598

      epoch  50/200: loss=0.000221, IC=-0.0573

      epoch  75/200: loss=0.000203, IC=-0.0534

      epoch 100/200: loss=0.000191, IC=-0.0528

      epoch 125/200: loss=0.000190, IC=-0.0534

      epoch 150/200: loss=0.000188, IC=-0.0542

      epoch 175/200: loss=0.000187, IC=-0.0552

      epoch 200/200: loss=0.000192, IC=-0.0543

    Fold 3: best_ep=100, IC=-0.0528 (22.3s)

      epoch  25/200: loss=0.000238, IC=-0.0149

      epoch  50/200: loss=0.000198, IC=-0.0345

      epoch  75/200: loss=0.000191, IC=-0.0438

      epoch 100/200: loss=0.000184, IC=-0.0490

      epoch 125/200: loss=0.000185, IC=-0.0458

      epoch 150/200: loss=0.000184, IC=-0.0427

      epoch 175/200: loss=0.000183, IC=-0.0409

      epoch 200/200: loss=0.000187, IC=-0.0420

    Fold 3: best_ep=25, IC=-0.0149 (18.1s)

  Fold 4: train=25,700  val=5,160

      epoch  25/200: loss=0.000313, IC=-0.0408

      epoch  50/200: loss=0.000227, IC=-0.0426

      epoch  75/200: loss=0.000203, IC=-0.0391

      epoch 100/200: loss=0.000197, IC=-0.0394

      epoch 125/200: loss=0.000193, IC=-0.0395

      epoch 150/200: loss=0.000188, IC=-0.0428

      epoch 175/200: loss=0.000185, IC=-0.0413

      epoch 200/200: loss=0.000190, IC=-0.0411

    Fold 4: best_ep=75, IC=-0.0391 (14.3s)

      epoch  25/200: loss=0.000285, IC=-0.0443

      epoch  50/200: loss=0.000210, IC=-0.0572

      epoch  75/200: loss=0.000192, IC=-0.0623

      epoch 100/200: loss=0.000189, IC=-0.0619

      epoch 125/200: loss=0.000186, IC=-0.0640

      epoch 150/200: loss=0.000182, IC=-0.0654

      epoch 175/200: loss=0.000179, IC=-0.0646

      epoch 200/200: loss=0.000184, IC=-0.0646

    Fold 4: best_ep=25, IC=-0.0443 (16.2s)

      epoch  25/200: loss=0.000240, IC=-0.0370

      epoch  50/200: loss=0.000191, IC=-0.0555

      epoch  75/200: loss=0.000183, IC=-0.0645

      epoch 100/200: loss=0.000185, IC=-0.0635

      epoch 125/200: loss=0.000183, IC=-0.0660

      epoch 150/200: loss=0.000179, IC=-0.0695

      epoch 175/200: loss=0.000176, IC=-0.0698

      epoch 200/200: loss=0.000181, IC=-0.0701

    Fold 4: best_ep=25, IC=-0.0370 (21.7s)

  Fold 5: train=25,700  val=5,160

      epoch  25/200: loss=0.000285, IC=+0.0280

      epoch  50/200: loss=0.000196, IC=+0.0356

      epoch  75/200: loss=0.000177, IC=+0.0365

      epoch 100/200: loss=0.000167, IC=+0.0356

      epoch 125/200: loss=0.000161, IC=+0.0380

      epoch 150/200: loss=0.000161, IC=+0.0419

      epoch 175/200: loss=0.000159, IC=+0.0417

      epoch 200/200: loss=0.000159, IC=+0.0410

    Fold 5: best_ep=150, IC=+0.0419 (9.6s)

      epoch  25/200: loss=0.000220, IC=+0.0089

      epoch  50/200: loss=0.000171, IC=+0.0137

      epoch  75/200: loss=0.000162, IC=+0.0192

      epoch 100/200: loss=0.000156, IC=+0.0193

      epoch 125/200: loss=0.000152, IC=+0.0209

      epoch 150/200: loss=0.000152, IC=+0.0206

      epoch 175/200: loss=0.000150, IC=+0.0234

      epoch 200/200: loss=0.000152, IC=+0.0225

    Fold 5: best_ep=175, IC=+0.0234 (15.1s)

      epoch  25/200: loss=0.000207, IC=+0.0095

      epoch  50/200: loss=0.000165, IC=+0.0106

      epoch  75/200: loss=0.000160, IC=+0.0072

      epoch 100/200: loss=0.000155, IC=+0.0107

      epoch 125/200: loss=0.000151, IC=+0.0073

      epoch 150/200: loss=0.000151, IC=+0.0075

      epoch 175/200: loss=0.000150, IC=+0.0077

      epoch 200/200: loss=0.000151, IC=+0.0083

    Fold 5: best_ep=100, IC=+0.0107 (16.6s)

  Fold 6: train=25,700  val=5,160

      epoch  25/200: loss=0.000221, IC=-0.0499

      epoch  50/200: loss=0.000151, IC=-0.0552

      epoch  75/200: loss=0.000131, IC=-0.0567

      epoch 100/200: loss=0.000125, IC=-0.0596

      epoch 125/200: loss=0.000120, IC=-0.0624

      epoch 150/200: loss=0.000120, IC=-0.0660

      epoch 175/200: loss=0.000118, IC=-0.0674

      epoch 200/200: loss=0.000117, IC=-0.0679

    Fold 6: best_ep=25, IC=-0.0499 (12.4s)

      epoch  25/200: loss=0.000195, IC=-0.0384

      epoch  50/200: loss=0.000138, IC=-0.0394

      epoch  75/200: loss=0.000124, IC=-0.0458

      epoch 100/200: loss=0.000121, IC=-0.0468

      epoch 125/200: loss=0.000118, IC=-0.0496

      epoch 150/200: loss=0.000118, IC=-0.0528

      epoch 175/200: loss=0.000116, IC=-0.0512

      epoch 200/200: loss=0.000115, IC=-0.0514

    Fold 6: best_ep=25, IC=-0.0384 (18.2s)

      epoch  25/200: loss=0.000184, IC=-0.0565

      epoch  50/200: loss=0.000133, IC=-0.0520

      epoch  75/200: loss=0.000121, IC=-0.0554

      epoch 100/200: loss=0.000118, IC=-0.0577

      epoch 125/200: loss=0.000115, IC=-0.0595

      epoch 150/200: loss=0.000116, IC=-0.0590

      epoch 175/200: loss=0.000114, IC=-0.0593

      epoch 200/200: loss=0.000113, IC=-0.0594

    Fold 6: best_ep=50, IC=-0.0520 (17.1s)

  Fold 7: train=25,700  val=5,060

      epoch  25/200: loss=0.000352, IC=+0.0528

      epoch  50/200: loss=0.000210, IC=+0.0247

      epoch  75/200: loss=0.000174, IC=+0.0240

      epoch 100/200: loss=0.000159, IC=+0.0277

      epoch 125/200: loss=0.000153, IC=+0.0336

      epoch 150/200: loss=0.000150, IC=+0.0361

      epoch 175/200: loss=0.000148, IC=+0.0371

      epoch 200/200: loss=0.000150, IC=+0.0385

    Fold 7: best_ep=25, IC=+0.0528 (7.4s)

      epoch  25/200: loss=0.000222, IC=+0.0187

      epoch  50/200: loss=0.000156, IC=+0.0137

      epoch  75/200: loss=0.000143, IC=+0.0121

      epoch 100/200: loss=0.000138, IC=+0.0104

      epoch 125/200: loss=0.000137, IC=+0.0123

      epoch 150/200: loss=0.000135, IC=+0.0139

      epoch 175/200: loss=0.000135, IC=+0.0127

      epoch 200/200: loss=0.000136, IC=+0.0130

    Fold 7: best_ep=25, IC=+0.0187 (8.1s)

      epoch  25/200: loss=0.000200, IC=+0.0261

      epoch  50/200: loss=0.000147, IC=+0.0234

      epoch  75/200: loss=0.000138, IC=+0.0236

      epoch 100/200: loss=0.000134, IC=+0.0147

      epoch 125/200: loss=0.000134, IC=+0.0107

      epoch 150/200: loss=0.000132, IC=+0.0100

      epoch 175/200: loss=0.000132, IC=+0.0082

      epoch 200/200: loss=0.000134, IC=+0.0090

    Fold 7: best_ep=25, IC=+0.0261 (17.1s)

    → best_epoch=25, IC=+0.0013 (146.6s)

    → best_epoch=25, IC=-0.0162 (164.0s)

    → best_epoch=25, IC=-0.0062 (167.7s)

  Best: f1dd90908386 @ epoch 25 (IC=+0.0013)

Preparing and releasing folds...
  Fold 0: train=17,860  val=5,160

      epoch  25/200: loss=0.000936, IC=-0.0013

      epoch  50/200: loss=0.000753, IC=+0.0206

      epoch  75/200: loss=0.000684, IC=+0.0311

      epoch 100/200: loss=0.000643, IC=+0.0296

      epoch 125/200: loss=0.000618, IC=+0.0251

      epoch 150/200: loss=0.000615, IC=+0.0280

      epoch 175/200: loss=0.000605, IC=+0.0253

      epoch 200/200: loss=0.000603, IC=+0.0248

    Fold 0: best_ep=75, IC=+0.0311 (5.0s)

      epoch  25/200: loss=0.000765, IC=+0.0002

      epoch  50/200: loss=0.000656, IC=+0.0065

      epoch  75/200: loss=0.000602, IC=+0.0125

      epoch 100/200: loss=0.000565, IC=+0.0171

      epoch 125/200: loss=0.000541, IC=+0.0201

      epoch 150/200: loss=0.000530, IC=+0.0239

      epoch 175/200: loss=0.000525, IC=+0.0238

      epoch 200/200: loss=0.000522, IC=+0.0240

    Fold 0: best_ep=200, IC=+0.0240 (7.2s)

      epoch  25/200: loss=0.000717, IC=+0.0171

      epoch  50/200: loss=0.000611, IC=+0.0209

      epoch  75/200: loss=0.000551, IC=+0.0375

      epoch 100/200: loss=0.000509, IC=+0.0427

      epoch 125/200: loss=0.000484, IC=+0.0445

      epoch 150/200: loss=0.000476, IC=+0.0472

      epoch 175/200: loss=0.000471, IC=+0.0455

      epoch 200/200: loss=0.000465, IC=+0.0462

    Fold 0: best_ep=150, IC=+0.0472 (13.1s)

  Fold 1: train=23,020  val=5,160

      epoch  25/200: loss=0.000901, IC=-0.0638

      epoch  50/200: loss=0.000770, IC=-0.0504

      epoch  75/200: loss=0.000709, IC=-0.0530

      epoch 100/200: loss=0.000673, IC=-0.0582

      epoch 125/200: loss=0.000652, IC=-0.0551

      epoch 150/200: loss=0.000640, IC=-0.0516

      epoch 175/200: loss=0.000635, IC=-0.0506

      epoch 200/200: loss=0.000630, IC=-0.0509

    Fold 1: best_ep=50, IC=-0.0504 (9.4s)

      epoch  25/200: loss=0.000786, IC=-0.0509

      epoch  50/200: loss=0.000689, IC=-0.0573

      epoch  75/200: loss=0.000626, IC=-0.0691

      epoch 100/200: loss=0.000589, IC=-0.0747

      epoch 125/200: loss=0.000564, IC=-0.0800

      epoch 150/200: loss=0.000549, IC=-0.0824

      epoch 175/200: loss=0.000543, IC=-0.0834

      epoch 200/200: loss=0.000543, IC=-0.0837

    Fold 1: best_ep=25, IC=-0.0509 (7.2s)

      epoch  25/200: loss=0.000799, IC=-0.0538

      epoch  50/200: loss=0.000692, IC=-0.0435

      epoch  75/200: loss=0.000629, IC=-0.0417

      epoch 100/200: loss=0.000588, IC=-0.0391

      epoch 125/200: loss=0.000563, IC=-0.0361

      epoch 150/200: loss=0.000548, IC=-0.0343

      epoch 175/200: loss=0.000543, IC=-0.0356

      epoch 200/200: loss=0.000540, IC=-0.0356

    Fold 1: best_ep=150, IC=-0.0343 (17.9s)

  Fold 2: train=25,380  val=5,160

      epoch  25/200: loss=0.000935, IC=-0.0002

      epoch  50/200: loss=0.000775, IC=+0.0177

      epoch  75/200: loss=0.000718, IC=+0.0400

      epoch 100/200: loss=0.000678, IC=+0.0643

      epoch 125/200: loss=0.000666, IC=+0.0776

      epoch 150/200: loss=0.000650, IC=+0.0829

      epoch 175/200: loss=0.000644, IC=+0.0874

      epoch 200/200: loss=0.000647, IC=+0.0885

    Fold 2: best_ep=200, IC=+0.0885 (11.5s)

      epoch  25/200: loss=0.000822, IC=+0.0215

      epoch  50/200: loss=0.000711, IC=+0.0297

      epoch  75/200: loss=0.000662, IC=+0.0455

      epoch 100/200: loss=0.000620, IC=+0.0657

      epoch 125/200: loss=0.000603, IC=+0.0785

      epoch 150/200: loss=0.000590, IC=+0.0827

      epoch 175/200: loss=0.000584, IC=+0.0858

      epoch 200/200: loss=0.000583, IC=+0.0873

    Fold 2: best_ep=200, IC=+0.0873 (6.5s)

      epoch  25/200: loss=0.000765, IC=+0.0844

      epoch  50/200: loss=0.000675, IC=+0.0944

      epoch  75/200: loss=0.000620, IC=+0.0996

      epoch 100/200: loss=0.000575, IC=+0.1075

      epoch 125/200: loss=0.000554, IC=+0.1169

      epoch 150/200: loss=0.000536, IC=+0.1131

      epoch 175/200: loss=0.000531, IC=+0.1189

      epoch 200/200: loss=0.000531, IC=+0.1193

    Fold 2: best_ep=200, IC=+0.1193 (13.2s)

  Fold 3: train=25,380  val=5,160

      epoch  25/200: loss=0.000738, IC=+0.0531

      epoch  50/200: loss=0.000643, IC=+0.0534

      epoch  75/200: loss=0.000590, IC=+0.0818

      epoch 100/200: loss=0.000564, IC=+0.0953

      epoch 125/200: loss=0.000546, IC=+0.1067

      epoch 150/200: loss=0.000533, IC=+0.1020

      epoch 175/200: loss=0.000531, IC=+0.1022

      epoch 200/200: loss=0.000535, IC=+0.1026

    Fold 3: best_ep=125, IC=+0.1067 (8.9s)

      epoch  25/200: loss=0.000772, IC=-0.0136

      epoch  50/200: loss=0.000662, IC=+0.0014

      epoch  75/200: loss=0.000612, IC=+0.0019

      epoch 100/200: loss=0.000586, IC=+0.0038

      epoch 125/200: loss=0.000567, IC=+0.0104

      epoch 150/200: loss=0.000554, IC=+0.0030

      epoch 175/200: loss=0.000555, IC=+0.0061

      epoch 200/200: loss=0.000559, IC=+0.0054

    Fold 3: best_ep=125, IC=+0.0104 (18.1s)

      epoch  25/200: loss=0.000695, IC=-0.0049

      epoch  50/200: loss=0.000616, IC=+0.0042

      epoch  75/200: loss=0.000560, IC=+0.0051

      epoch 100/200: loss=0.000531, IC=+0.0088

      epoch 125/200: loss=0.000508, IC=+0.0131

      epoch 150/200: loss=0.000494, IC=+0.0094

      epoch 175/200: loss=0.000492, IC=+0.0116

      epoch 200/200: loss=0.000495, IC=+0.0111

    Fold 3: best_ep=125, IC=+0.0131 (31.5s)

  Fold 4: train=25,380  val=5,160

      epoch  25/200: loss=0.000718, IC=-0.1849

      epoch  50/200: loss=0.000610, IC=-0.1863

      epoch  75/200: loss=0.000557, IC=-0.1812

      epoch 100/200: loss=0.000537, IC=-0.1767

      epoch 125/200: loss=0.000536, IC=-0.1736

      epoch 150/200: loss=0.000515, IC=-0.1714

      epoch 175/200: loss=0.000505, IC=-0.1710

      epoch 200/200: loss=0.000507, IC=-0.1701

    Fold 4: best_ep=200, IC=-0.1701 (24.2s)

      epoch  25/200: loss=0.000673, IC=-0.1489

      epoch  50/200: loss=0.000569, IC=-0.1510

      epoch  75/200: loss=0.000523, IC=-0.1476

      epoch 100/200: loss=0.000500, IC=-0.1458

      epoch 125/200: loss=0.000496, IC=-0.1445

      epoch 150/200: loss=0.000479, IC=-0.1428

      epoch 175/200: loss=0.000469, IC=-0.1424

      epoch 200/200: loss=0.000470, IC=-0.1422

    Fold 4: best_ep=200, IC=-0.1422 (12.6s)

      epoch  25/200: loss=0.000627, IC=-0.1426

      epoch  50/200: loss=0.000549, IC=-0.1604

      epoch  75/200: loss=0.000504, IC=-0.1567

      epoch 100/200: loss=0.000477, IC=-0.1569

      epoch 125/200: loss=0.000473, IC=-0.1545

      epoch 150/200: loss=0.000454, IC=-0.1507

      epoch 175/200: loss=0.000444, IC=-0.1509

      epoch 200/200: loss=0.000445, IC=-0.1507

    Fold 4: best_ep=25, IC=-0.1426 (15.6s)

  Fold 5: train=25,380  val=5,160

      epoch  25/200: loss=0.000672, IC=+0.0478

      epoch  50/200: loss=0.000555, IC=+0.0773

      epoch  75/200: loss=0.000521, IC=+0.0769

      epoch 100/200: loss=0.000492, IC=+0.0828

      epoch 125/200: loss=0.000475, IC=+0.0898

      epoch 150/200: loss=0.000470, IC=+0.0960

      epoch 175/200: loss=0.000466, IC=+0.0963

      epoch 200/200: loss=0.000461, IC=+0.0958

    Fold 5: best_ep=175, IC=+0.0963 (9.5s)

      epoch  25/200: loss=0.000594, IC=+0.0578

      epoch  50/200: loss=0.000511, IC=+0.0906

      epoch  75/200: loss=0.000476, IC=+0.0993

      epoch 100/200: loss=0.000446, IC=+0.1000

      epoch 125/200: loss=0.000427, IC=+0.1021

      epoch 150/200: loss=0.000418, IC=+0.1031

      epoch 175/200: loss=0.000417, IC=+0.1037

      epoch 200/200: loss=0.000410, IC=+0.1041

    Fold 5: best_ep=200, IC=+0.1041 (10.4s)

      epoch  25/200: loss=0.000582, IC=+0.0711

      epoch  50/200: loss=0.000504, IC=+0.0993

      epoch  75/200: loss=0.000468, IC=+0.1106

      epoch 100/200: loss=0.000435, IC=+0.1171

      epoch 125/200: loss=0.000417, IC=+0.1172

      epoch 150/200: loss=0.000407, IC=+0.1216

      epoch 175/200: loss=0.000406, IC=+0.1185

      epoch 200/200: loss=0.000400, IC=+0.1175

    Fold 5: best_ep=150, IC=+0.1216 (14.0s)

  Fold 6: train=25,380  val=5,160

      epoch  25/200: loss=0.000512, IC=-0.0242

      epoch  50/200: loss=0.000431, IC=-0.0139

      epoch  75/200: loss=0.000390, IC=-0.0003

      epoch 100/200: loss=0.000373, IC=+0.0060

      epoch 125/200: loss=0.000357, IC=+0.0060

      epoch 150/200: loss=0.000354, IC=+0.0076

      epoch 175/200: loss=0.000349, IC=+0.0080

      epoch 200/200: loss=0.000347, IC=+0.0081

    Fold 6: best_ep=200, IC=+0.0081 (6.3s)

      epoch  25/200: loss=0.000480, IC=-0.0492

      epoch  50/200: loss=0.000418, IC=-0.0330

      epoch  75/200: loss=0.000383, IC=-0.0222

      epoch 100/200: loss=0.000367, IC=-0.0051

      epoch 125/200: loss=0.000353, IC=+0.0020

      epoch 150/200: loss=0.000351, IC=+0.0068

      epoch 175/200: loss=0.000347, IC=+0.0094

      epoch 200/200: loss=0.000343, IC=+0.0093

    Fold 6: best_ep=175, IC=+0.0094 (13.7s)

      epoch  25/200: loss=0.000464, IC=-0.0171

      epoch  50/200: loss=0.000402, IC=-0.0159

      epoch  75/200: loss=0.000367, IC=-0.0106

      epoch 100/200: loss=0.000350, IC=-0.0037

      epoch 125/200: loss=0.000335, IC=+0.0019

      epoch 150/200: loss=0.000331, IC=+0.0020

      epoch 175/200: loss=0.000328, IC=+0.0031

      epoch 200/200: loss=0.000324, IC=+0.0037

    Fold 6: best_ep=200, IC=+0.0037 (13.7s)

  Fold 7: train=25,380  val=4,740

      epoch  25/200: loss=0.000702, IC=+0.1143

      epoch  50/200: loss=0.000545, IC=+0.0201

      epoch  75/200: loss=0.000499, IC=-0.0100

      epoch 100/200: loss=0.000487, IC=-0.0300

      epoch 125/200: loss=0.000467, IC=-0.0431

      epoch 150/200: loss=0.000459, IC=-0.0488

      epoch 175/200: loss=0.000459, IC=-0.0511

      epoch 200/200: loss=0.000454, IC=-0.0510

    Fold 7: best_ep=25, IC=+0.1143 (9.8s)

      epoch  25/200: loss=0.000570, IC=+0.0130

      epoch  50/200: loss=0.000483, IC=-0.0357

      epoch  75/200: loss=0.000449, IC=-0.0754

      epoch 100/200: loss=0.000437, IC=-0.0901

      epoch 125/200: loss=0.000418, IC=-0.1003

      epoch 150/200: loss=0.000408, IC=-0.1084

      epoch 175/200: loss=0.000404, IC=-0.1104

      epoch 200/200: loss=0.000406, IC=-0.1108

    Fold 7: best_ep=25, IC=+0.0130 (5.6s)

      epoch  25/200: loss=0.000539, IC=-0.0362

      epoch  50/200: loss=0.000463, IC=-0.0622

      epoch  75/200: loss=0.000427, IC=-0.0805

      epoch 100/200: loss=0.000413, IC=-0.0915

      epoch 125/200: loss=0.000392, IC=-0.0951

      epoch 150/200: loss=0.000382, IC=-0.0963

      epoch 175/200: loss=0.000379, IC=-0.0998

      epoch 200/200: loss=0.000380, IC=-0.0987

    Fold 7: best_ep=25, IC=-0.0362 (13.6s)

    → best_epoch=200, IC=+0.0066 (85.0s)

    → best_epoch=200, IC=-0.0123 (81.5s)

    → best_epoch=200, IC=+0.0026 (133.0s)

  Best: 3a05e09d91cc @ epoch 200 (IC=+0.0066)

shape: (72, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean   ┆ ic_t      ┆ training_ ┆ predicti │
│ ---       ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---       ┆ ---       ┆ hash      ┆ on_hash  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ i64       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 25        ┆ … ┆ 0.0012    ┆ 0.189795  ┆ d925320dc ┆ 0a408b91 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 90c       ┆ 358c     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 50        ┆ … ┆ -0.00324  ┆ -0.401288 ┆ d925320dc ┆ 1b1984b6 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 90c       ┆ 993e     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 75        ┆ … ┆ -0.006373 ┆ -0.784582 ┆ d925320dc ┆ c6670b78 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 90c       ┆ aedf     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 100       ┆ … ┆ -0.009006 ┆ -1.084608 ┆ d925320dc ┆ 9a4bf134 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 90c       ┆ c48f     │
│ fwd_ret_1 ┆ tabm_l    ┆ epoch     ┆ 125       ┆ … ┆ -0.010182 ┆ -1.187066 ┆ d925320dc ┆ 37b3d279 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 90c       ┆ 7476     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 100       ┆ … ┆ -0.006223 ┆ -0.440066 ┆ f1dd90908 ┆ fd057d7d │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 386       ┆ ae75     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 125       ┆ … ┆ -0.006659 ┆ -0.454403 ┆ f1dd90908 ┆ c8756fee │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 386       ┆ 5d30     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 150       ┆ … ┆ -0.006491 ┆ -0.422159 ┆ f1dd90908 ┆ 906e08e8 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 386       ┆ f5d2     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 175       ┆ … ┆ -0.005768 ┆ -0.375176 ┆ f1dd90908 ┆ e9058da2 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 386       ┆ fb5b     │
│ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ 200       ┆ … ┆ -0.005629 ┆ -0.365434 ┆ f1dd90908 ┆ d4052221 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 386       ┆ 1064     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Reload the checkpoint population

Repeating the same request validates the saved checkpoint manifests and returns the same catalog
identities. No empty cached summary or single IC-chosen checkpoint is substituted.

In [7]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("TabM checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview checkpoints remain outside official comparison and holdout selection.")

Official prediction population: c410ee21bfd1

## Key takeaways

- Train-only preprocessing and checkpoint persistence belong to the shared TabM computation.
- Every declared epoch remains available to the backtest stage.
- Rank correlation is a diagnostic field in the catalog, not a checkpoint-selection rule.