# Temporal Convolutional Network - FX Pairs

A temporal convolutional network reads a fixed number of consecutive daily observations for each
currency pair. A missing daily observation invalidates every lookback window that crosses it. The
shared sequence runner derives that eligible endpoint grid, primes each validation fold only with
observable earlier rows, saves epoch checkpoints, and publishes predictions against the same grid.

**Learning objectives**

- Define one sequence-model request without rebuilding windows in the notebook.
- Inspect the cadence-aware eligibility and checkpoint identities recorded by the runner.
- Reload fitted weights and pass complete predictions through the shared catalog.

**Book reference**: Chapter 13, Sections 13.2 and 13.4

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published TCN FX configuration."""

import json

import polars as pl
import torch

from case_studies.research import (
    ExecutionTier,
    declared_labels,
    open_study,
    plan_models,
    population_supersedes,
    sweep_labels,
)
from utils.modeling import load_configs
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
LOOKBACK = 0
BATCH_SIZE = 0
DEVICE = ""
SEED = 42
POPULATION_NAME = ""
SUPERSEDES_POPULATION: str = "5415fd1d8d0f"
# The tier is a parameter, not something inferred from whether a reduction happens to be set.
# Inferring it meant a run could be reduced and still open the case study's own artifacts in
# place, which is the production path; a reader under test then wrote where the published run
# writes. WORKSPACE is the other half: a preview has nowhere else to put its results.
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None

## Plan the sequence request

Fold and symbol reductions create a preview. Epochs, lookback length, and batch size are visible
model overrides: changing any of them creates a different training identity. Planning resolves
that identity, the eligible validation keys, and every declared epoch checkpoint before any
training starts.

In [3]:
set_global_seeds(SEED)
# The reductions are read before the study is opened, because which study to open is decided by
# the tier and the two have to agree: a preview that reduces nothing is a canonical run wearing
# the wrong tier, and a canonical run carrying reductions would publish a narrowed population
# under the canonical name.
REDUCTION_PARAMETERS = {
    "folds": list(range(MAX_FOLDS)) if MAX_FOLDS else None,
    "max_symbols": MAX_SYMBOLS or None,
}
reductions = {key: value for key, value in REDUCTION_PARAMETERS.items() if value is not None}
tier = ExecutionTier(EXECUTION_TIER)
if tier is ExecutionTier.PREVIEW and not reductions:
    raise ValueError("preview execution must declare at least one reduction")
if tier is ExecutionTier.CANONICAL and reductions:
    raise ValueError(f"canonical execution cannot carry reductions: {sorted(reductions)}")
study = open_study(CASE_STUDY_ID, execution_tier=tier, workspace=WORKSPACE or None)

# Which labels this notebook fits is a question for the training menus, not for the sweep list:
# `setup.yaml` says which labels the case study carries, a menu says what to fit for one of them,
# and a sweep label whose menu declares no `deep_learning:` section owes nothing here. The two
# agree in this case study today, so restating the sweep list produced the right answer by
# coincidence and would have kept producing it silently after a menu changed. The order stays
# `setup.yaml`'s rather than `declared_labels`' menu-file order because the population is named
# after its labels and hashed over its members as an ordered list, so re-ordering would give the
# published population a new identity and demand a supersedes for a run that fits the same models.
declared = declared_labels(study, "deep_learning")
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [label for label in sweep_labels(study) if label in set(declared)]
)

# A run that fits fewer labels than the menus declare is not the canonical population, and the
# architecture is fixed below, so the label set is the only knob that narrows it. Such a run must
# publish under its own name rather than register a partial snapshot under the canonical one.
if set(labels) != set(declared) and not POPULATION_NAME:
    raise ValueError(
        f"this run fits {len(labels)} of the {len(declared)} declared labels, so it cannot "
        "publish the canonical population; pass POPULATION_NAME to give it its own"
    )

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

# An empty DEVICE resolves to what the machine has. The runners refuse "cuda" on a host without
# it rather than falling back silently - which is the right contract for a run whose results get
# registered - so a hardcoded "cuda" default made the notebook unrunnable for any reader without
# an NVIDIA card, and unrunnable on a CPU CI runner. Resolving here keeps the refusal for anyone
# who asks for "cuda" explicitly; the resolved value is printed with the rest of the numerics
# below, so a run never leaves it implicit.
device = DEVICE or ("cuda" if torch.cuda.is_available() else "cpu")
overrides = {
    "device": device,
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
    **({"lookback": LOOKBACK} if LOOKBACK else {}),
}
ARCHITECTURE = "tcn"
menu = {
    label: [
        config["config_name"]
        for config in load_configs(CASE_STUDY_ID, label, family="deep_learning")
    ]
    for label in labels
}
uncovered = {label: sorted(set(names) - {ARCHITECTURE}) for label, names in menu.items()}
for label, names in menu.items():
    if ARCHITECTURE not in names:
        raise RuntimeError(
            f"{ARCHITECTURE} is not in the configured deep_learning menu for {label}: {names}"
        )

requests = [
    study.model(
        family="deep_learning",
        label=label,
        config_name=ARCHITECTURE,
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label in labels
]
plan = plan_models(study, requests=requests)

# This notebook owes one architecture on every configured label. The rest of the family menu is
# named here rather than left implicit, because a population that is short a configured model is
# otherwise indistinguishable from a complete one.
configured = {(label, ARCHITECTURE) for label in labels}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        f"the plan does not match this notebook's declared coverage; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )
specs = {member.label: json.loads(member.spec_json) for member in plan.members}
computations = {label: spec.get("computation", spec) for label, spec in specs.items()}
computation = computations[labels[0]]

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {computation['numerics']['device']}")
print(f"Lookback: {computation['preprocessing']['lookback']} consecutive daily observations")
for horizon, values in computations.items():
    print(f"Eligible validation rows, {horizon}: {values['expected_prediction_keys']['n_rows']:,}")
for horizon, names in uncovered.items():
    print(
        f"Configured deep_learning models this notebook does not run, {horizon}: {names or 'none'}"
    )

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda
Lookback: 60 consecutive daily observations
Eligible validation rows, fwd_ret_1d: 41,260
Eligible validation rows, fwd_ret_5d: 41,180
Eligible validation rows, fwd_ret_21d: 40,860
Configured deep_learning models this notebook does not run, fwd_ret_1d: ['lstm_h64', 'nlinear']
Configured deep_learning models this notebook does not run, fwd_ret_5d: ['lstm_h64', 'nlinear']
Configured deep_learning models this notebook does not run, fwd_ret_21d: ['lstm_h64', 'nlinear']

## Inspect the declared checkpoints and gap policy

The resolved request records exact validation keys and the rule that excludes windows crossing a
missing expected day. Checkpoint values below are training epochs, not IC-selected summaries.

In [4]:
checkpoint_schedule = pl.DataFrame(computation["checkpoint_schedule"])
input_summary = pl.DataFrame(
    {
        "label": list(computations),
        "gap_policy": [c["preprocessing"]["gap_policy"] for c in computations.values()],
        "validation_folds": [
            c["expected_prediction_keys"]["n_folds"] for c in computations.values()
        ],
        "validation_rows": [c["expected_prediction_keys"]["n_rows"] for c in computations.values()],
        "key_digest": [c["expected_prediction_keys"]["digest"] for c in computations.values()],
    }
)
input_summary
checkpoint_schedule

shape: (20, 2)
┌───────┬───────┐
│ kind  ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ epoch ┆ 5     │
│ epoch ┆ 10    │
│ epoch ┆ 15    │
│ epoch ┆ 20    │
│ epoch ┆ 25    │
│ …     ┆ …     │
│ epoch ┆ 80    │
│ epoch ┆ 85    │
│ epoch ┆ 90    │
│ epoch ┆ 95    │
│ epoch ┆ 100   │
└───────┴───────┘

## Record the official population, then fit or reload the TCN

The same resolved request is used by the notebook and direct Python callers. Publication fails if
any fold is missing, any prediction is non-finite, or the prediction keys differ from eligibility.

`SUPERSEDES_POPULATION` names the population hash this run replaces. A population is the set of
prediction identities it publishes, so anything that moves a training identity produces a
different population under the same name, and the registry refuses to write it without being
told which snapshot it supersedes. That lineage is the only record of which generation is which,
and what moved the identities here was a change to the family's own source file rather than to
anything the notebook declares.

`population_supersedes` decides whether the declared hash may be offered. It is offered when the
name already carries the generation this declaration produced, so a re-run resolves to the
population it published, and when the declaration names the generation in force, so a refit
publishes the next one. It is withheld everywhere else - on a reader's clean clone, where
`run_log/` is gitignored and the registry has no generation at all; under a caller's own
`POPULATION_NAME`; and in a preview, whose isolated registry holds nothing under this name.

In [5]:
if len(plan.expected_prediction_hashes) != checkpoint_schedule.height * len(labels):
    raise RuntimeError("the plan does not cover every declared epoch checkpoint on every label")
population_name = POPULATION_NAME or f"{CASE_STUDY_ID}:{'+'.join(labels)}:tcn"
population = (
    plan.create_population(
        name=population_name,
        supersedes=population_supersedes(
            study, name=population_name, declared=SUPERSEDES_POPULATION
        ),
    )
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
catalog = execution.catalog_rows.sort("label", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial TCN checkpoints cannot pass to backtesting")
for label in labels:
    published = catalog.filter(pl.col("label") == label).get_column("checkpoint_value").to_list()
    if published != checkpoint_schedule["value"].to_list():
        raise RuntimeError(f"catalog checkpoints for {label} differ from the resolved request")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=17,060 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.479888

      epoch   2/100: train_loss=0.037479

      epoch   3/100: train_loss=0.006746

      epoch   4/100: train_loss=0.003565

      epoch   5/100: train_loss=0.002840, val_loss=0.003319, IC=+0.0340

      epoch   6/100: train_loss=0.002839

      epoch   7/100: train_loss=0.001956

      epoch   8/100: train_loss=0.001912

      epoch   9/100: train_loss=0.001546

      epoch  10/100: train_loss=0.001307, val_loss=0.006122, IC=+0.0064

      epoch  11/100: train_loss=0.001378

      epoch  12/100: train_loss=0.001131

      epoch  13/100: train_loss=0.001111

      epoch  14/100: train_loss=0.001042

      epoch  15/100: train_loss=0.001413, val_loss=0.004432, IC=+0.0016

      epoch  16/100: train_loss=0.001235

      epoch  17/100: train_loss=0.001863

      epoch  18/100: train_loss=0.001087

      epoch  19/100: train_loss=0.001024

      epoch  20/100: train_loss=0.001176, val_loss=0.002555, IC=+0.0031

      epoch  21/100: train_loss=0.001488

      epoch  22/100: train_loss=0.001029

      epoch  23/100: train_loss=0.000866

      epoch  24/100: train_loss=0.001026

      epoch  25/100: train_loss=0.000890, val_loss=0.000649, IC=+0.0014

      epoch  26/100: train_loss=0.000959

      epoch  27/100: train_loss=0.000696

      epoch  28/100: train_loss=0.001132

      epoch  29/100: train_loss=0.000914

      epoch  30/100: train_loss=0.000847, val_loss=0.001146, IC=+0.0000

      epoch  31/100: train_loss=0.000848

      epoch  32/100: train_loss=0.000795

      epoch  33/100: train_loss=0.000827

      epoch  34/100: train_loss=0.001533

      epoch  35/100: train_loss=0.001271, val_loss=0.004743, IC=+0.0158

      epoch  36/100: train_loss=0.000906

      epoch  37/100: train_loss=0.000800

      epoch  38/100: train_loss=0.000688

      epoch  39/100: train_loss=0.000654

      epoch  40/100: train_loss=0.000681, val_loss=0.000628, IC=+0.0035

      epoch  41/100: train_loss=0.000722

      epoch  42/100: train_loss=0.000671

      epoch  43/100: train_loss=0.000666

      epoch  44/100: train_loss=0.000726

      epoch  45/100: train_loss=0.000706, val_loss=0.000399, IC=+0.0078

      epoch  46/100: train_loss=0.000711

      epoch  47/100: train_loss=0.000838

      epoch  48/100: train_loss=0.000596

      epoch  49/100: train_loss=0.001136

      epoch  50/100: train_loss=0.000976, val_loss=0.000353, IC=+0.0074

      epoch  51/100: train_loss=0.000783

      epoch  52/100: train_loss=0.000949

      epoch  53/100: train_loss=0.000786

      epoch  54/100: train_loss=0.000635

      epoch  55/100: train_loss=0.000507, val_loss=0.000357, IC=+0.0103

      epoch  56/100: train_loss=0.000566

      epoch  57/100: train_loss=0.000598

      epoch  58/100: train_loss=0.000573

      epoch  59/100: train_loss=0.000647

      epoch  60/100: train_loss=0.000573, val_loss=0.000417, IC=+0.0085

      epoch  61/100: train_loss=0.000488

      epoch  62/100: train_loss=0.000561

      epoch  63/100: train_loss=0.000466

      epoch  64/100: train_loss=0.000497

      epoch  65/100: train_loss=0.000522, val_loss=0.000357, IC=+0.0058

      epoch  66/100: train_loss=0.000530

      epoch  67/100: train_loss=0.000501

      epoch  68/100: train_loss=0.000543

      epoch  69/100: train_loss=0.000515

      epoch  70/100: train_loss=0.000553, val_loss=0.000336, IC=+0.0103

      epoch  71/100: train_loss=0.000533

      epoch  72/100: train_loss=0.000539

      epoch  73/100: train_loss=0.000537

      epoch  74/100: train_loss=0.000440

      epoch  75/100: train_loss=0.000472, val_loss=0.000399, IC=+0.0030

      epoch  76/100: train_loss=0.000434

      epoch  77/100: train_loss=0.000473

      epoch  78/100: train_loss=0.000499

      epoch  79/100: train_loss=0.000511

      epoch  80/100: train_loss=0.000603, val_loss=0.000331, IC=+0.0067

      epoch  81/100: train_loss=0.000506

      epoch  82/100: train_loss=0.000518

      epoch  83/100: train_loss=0.000572

      epoch  84/100: train_loss=0.000459

      epoch  85/100: train_loss=0.000473, val_loss=0.000327, IC=+0.0089

      epoch  86/100: train_loss=0.000457

      epoch  87/100: train_loss=0.000490

      epoch  88/100: train_loss=0.000490

      epoch  89/100: train_loss=0.000488

      epoch  90/100: train_loss=0.000520, val_loss=0.000370, IC=+0.0053

      epoch  91/100: train_loss=0.000441

      epoch  92/100: train_loss=0.000484

      epoch  93/100: train_loss=0.000471

      epoch  94/100: train_loss=0.000470

      epoch  95/100: train_loss=0.000403, val_loss=0.000323, IC=+0.0066

      epoch  96/100: train_loss=0.000516

      epoch  97/100: train_loss=0.000496

      epoch  98/100: train_loss=0.000553

      epoch  99/100: train_loss=0.000456

      epoch 100/100: train_loss=0.000478, val_loss=0.000312, IC=+0.0088

      best_ep=5, IC=+0.0340 (54.4s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,220 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.023562

      epoch   2/100: train_loss=0.004725

      epoch   3/100: train_loss=0.002563

      epoch   4/100: train_loss=0.001938

      epoch   5/100: train_loss=0.001641, val_loss=0.001842, IC=+0.0142

      epoch   6/100: train_loss=0.001520

      epoch   7/100: train_loss=0.001404

      epoch   8/100: train_loss=0.001299

      epoch   9/100: train_loss=0.001308

      epoch  10/100: train_loss=0.001311, val_loss=0.000771, IC=+0.0068

      epoch  11/100: train_loss=0.001275

      epoch  12/100: train_loss=0.001210

      epoch  13/100: train_loss=0.001183

      epoch  14/100: train_loss=0.001055

      epoch  15/100: train_loss=0.001039, val_loss=0.000554, IC=+0.0022

      epoch  16/100: train_loss=0.001046

      epoch  17/100: train_loss=0.001027

      epoch  18/100: train_loss=0.000977

      epoch  19/100: train_loss=0.000973

      epoch  20/100: train_loss=0.000871, val_loss=0.000592, IC=-0.0048

      epoch  21/100: train_loss=0.000846

      epoch  22/100: train_loss=0.000820

      epoch  23/100: train_loss=0.000880

      epoch  24/100: train_loss=0.000816

      epoch  25/100: train_loss=0.000823, val_loss=0.000442, IC=-0.0084

      epoch  26/100: train_loss=0.000736

      epoch  27/100: train_loss=0.000717

      epoch  28/100: train_loss=0.000700

      epoch  29/100: train_loss=0.000709

      epoch  30/100: train_loss=0.000749, val_loss=0.000276, IC=-0.0082

      epoch  31/100: train_loss=0.000751

      epoch  32/100: train_loss=0.000678

      epoch  33/100: train_loss=0.000659

      epoch  34/100: train_loss=0.000585

      epoch  35/100: train_loss=0.000665, val_loss=0.000373, IC=-0.0148

      epoch  36/100: train_loss=0.000631

      epoch  37/100: train_loss=0.000606

      epoch  38/100: train_loss=0.000678

      epoch  39/100: train_loss=0.000559

      epoch  40/100: train_loss=0.000547, val_loss=0.000199, IC=-0.0144

      epoch  41/100: train_loss=0.000576

      epoch  42/100: train_loss=0.000550

      epoch  43/100: train_loss=0.000563

      epoch  44/100: train_loss=0.000517

      epoch  45/100: train_loss=0.000513, val_loss=0.000302, IC=-0.0121

      epoch  46/100: train_loss=0.000546

      epoch  47/100: train_loss=0.000550

      epoch  48/100: train_loss=0.000501

      epoch  49/100: train_loss=0.000510

      epoch  50/100: train_loss=0.000521, val_loss=0.000213, IC=-0.0166

      epoch  51/100: train_loss=0.000519

      epoch  52/100: train_loss=0.000478

      epoch  53/100: train_loss=0.000503

      epoch  54/100: train_loss=0.000511

      epoch  55/100: train_loss=0.000475, val_loss=0.000160, IC=-0.0205

      epoch  56/100: train_loss=0.000453

      epoch  57/100: train_loss=0.000446

      epoch  58/100: train_loss=0.000431

      epoch  59/100: train_loss=0.000422

      epoch  60/100: train_loss=0.000429, val_loss=0.000150, IC=-0.0210

      epoch  61/100: train_loss=0.000445

      epoch  62/100: train_loss=0.000440

      epoch  63/100: train_loss=0.000447

      epoch  64/100: train_loss=0.000419

      epoch  65/100: train_loss=0.000428, val_loss=0.000148, IC=-0.0205

      epoch  66/100: train_loss=0.000403

      epoch  67/100: train_loss=0.000429

      epoch  68/100: train_loss=0.000444

      epoch  69/100: train_loss=0.000424

      epoch  70/100: train_loss=0.000411, val_loss=0.000145, IC=-0.0235

      epoch  71/100: train_loss=0.000414

      epoch  72/100: train_loss=0.000403

      epoch  73/100: train_loss=0.000400

      epoch  74/100: train_loss=0.000429

      epoch  75/100: train_loss=0.000385, val_loss=0.000155, IC=-0.0245

      epoch  76/100: train_loss=0.000396

      epoch  77/100: train_loss=0.000400

      epoch  78/100: train_loss=0.000406

      epoch  79/100: train_loss=0.000412

      epoch  80/100: train_loss=0.000402, val_loss=0.000145, IC=-0.0212

      epoch  81/100: train_loss=0.000387

      epoch  82/100: train_loss=0.000388

      epoch  83/100: train_loss=0.000390

      epoch  84/100: train_loss=0.000406

      epoch  85/100: train_loss=0.000401, val_loss=0.000133, IC=-0.0220

      epoch  86/100: train_loss=0.000388

      epoch  87/100: train_loss=0.000378

      epoch  88/100: train_loss=0.000397

      epoch  89/100: train_loss=0.000393

      epoch  90/100: train_loss=0.000389, val_loss=0.000138, IC=-0.0243

      epoch  91/100: train_loss=0.000382

      epoch  92/100: train_loss=0.000391

      epoch  93/100: train_loss=0.000382

      epoch  94/100: train_loss=0.000391

      epoch  95/100: train_loss=0.000412, val_loss=0.000133, IC=-0.0236

      epoch  96/100: train_loss=0.000412

      epoch  97/100: train_loss=0.000387

      epoch  98/100: train_loss=0.000383

      epoch  99/100: train_loss=0.000389

      epoch 100/100: train_loss=0.000393, val_loss=0.000136, IC=-0.0232

      best_ep=5, IC=+0.0142 (73.0s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.433920

      epoch   2/100: train_loss=0.026347

      epoch   3/100: train_loss=0.005884

      epoch   4/100: train_loss=0.003196

      epoch   5/100: train_loss=0.005343, val_loss=0.000998, IC=+0.0059

      epoch   6/100: train_loss=0.004921

      epoch   7/100: train_loss=0.002578

      epoch   8/100: train_loss=0.003020

      epoch   9/100: train_loss=0.004857

      epoch  10/100: train_loss=0.002993, val_loss=0.000378, IC=-0.0138

      epoch  11/100: train_loss=0.001732

      epoch  12/100: train_loss=0.004164

      epoch  13/100: train_loss=0.004396

      epoch  14/100: train_loss=0.001737

      epoch  15/100: train_loss=0.001303, val_loss=0.000418, IC=-0.0134

      epoch  16/100: train_loss=0.001696

      epoch  17/100: train_loss=0.001679

      epoch  18/100: train_loss=0.003141

      epoch  19/100: train_loss=0.001656

      epoch  20/100: train_loss=0.001904, val_loss=0.000718, IC=-0.0002

      epoch  21/100: train_loss=0.002072

      epoch  22/100: train_loss=0.001869

      epoch  23/100: train_loss=0.001382

      epoch  24/100: train_loss=0.001966

      epoch  25/100: train_loss=0.001946, val_loss=0.000425, IC=-0.0061

      epoch  26/100: train_loss=0.001011

      epoch  27/100: train_loss=0.001321

      epoch  28/100: train_loss=0.001387

      epoch  29/100: train_loss=0.001140

      epoch  30/100: train_loss=0.001749, val_loss=0.000275, IC=+0.0100

      epoch  31/100: train_loss=0.001176

      epoch  32/100: train_loss=0.001027

      epoch  33/100: train_loss=0.001342

      epoch  34/100: train_loss=0.000863

      epoch  35/100: train_loss=0.000699, val_loss=0.000274, IC=+0.0104

      epoch  36/100: train_loss=0.000781

      epoch  37/100: train_loss=0.002714

      epoch  38/100: train_loss=0.000907

      epoch  39/100: train_loss=0.001178

      epoch  40/100: train_loss=0.001020, val_loss=0.000340, IC=+0.0070

      epoch  41/100: train_loss=0.001748

      epoch  42/100: train_loss=0.000838

      epoch  43/100: train_loss=0.001163

      epoch  44/100: train_loss=0.000655

      epoch  45/100: train_loss=0.000982, val_loss=0.000508, IC=-0.0125

      epoch  46/100: train_loss=0.000773

      epoch  47/100: train_loss=0.000890

      epoch  48/100: train_loss=0.001514

      epoch  49/100: train_loss=0.001091

      epoch  50/100: train_loss=0.000740, val_loss=0.000247, IC=-0.0093

      epoch  51/100: train_loss=0.000901

      epoch  52/100: train_loss=0.000729

      epoch  53/100: train_loss=0.000570

      epoch  54/100: train_loss=0.001169

      epoch  55/100: train_loss=0.000758, val_loss=0.000110, IC=+0.0218

      epoch  56/100: train_loss=0.001020

      epoch  57/100: train_loss=0.000697

      epoch  58/100: train_loss=0.000596

      epoch  59/100: train_loss=0.000965

      epoch  60/100: train_loss=0.000973, val_loss=0.000358, IC=-0.0140

      epoch  61/100: train_loss=0.001020

      epoch  62/100: train_loss=0.001000

      epoch  63/100: train_loss=0.000751

      epoch  64/100: train_loss=0.000625

      epoch  65/100: train_loss=0.000589, val_loss=0.000194, IC=+0.0018

      epoch  66/100: train_loss=0.000595

      epoch  67/100: train_loss=0.000526

      epoch  68/100: train_loss=0.000811

      epoch  69/100: train_loss=0.000554

      epoch  70/100: train_loss=0.000545, val_loss=0.000141, IC=-0.0002

      epoch  71/100: train_loss=0.000600

      epoch  72/100: train_loss=0.000493

      epoch  73/100: train_loss=0.000557

      epoch  74/100: train_loss=0.000813

      epoch  75/100: train_loss=0.000522, val_loss=0.000110, IC=+0.0056

      epoch  76/100: train_loss=0.000491

      epoch  77/100: train_loss=0.000479

      epoch  78/100: train_loss=0.000515

      epoch  79/100: train_loss=0.000693

      epoch  80/100: train_loss=0.000900, val_loss=0.000176, IC=-0.0000

      epoch  81/100: train_loss=0.000457

      epoch  82/100: train_loss=0.000617

      epoch  83/100: train_loss=0.000500

      epoch  84/100: train_loss=0.000680

      epoch  85/100: train_loss=0.000496, val_loss=0.000181, IC=-0.0147

      epoch  86/100: train_loss=0.000478

      epoch  87/100: train_loss=0.000662

      epoch  88/100: train_loss=0.000622

      epoch  89/100: train_loss=0.000434

      epoch  90/100: train_loss=0.000611, val_loss=0.000165, IC=-0.0067

      epoch  91/100: train_loss=0.000490

      epoch  92/100: train_loss=0.000789

      epoch  93/100: train_loss=0.000431

      epoch  94/100: train_loss=0.000527

      epoch  95/100: train_loss=0.000427, val_loss=0.000174, IC=-0.0188

      epoch  96/100: train_loss=0.000697

      epoch  97/100: train_loss=0.000448

      epoch  98/100: train_loss=0.000731

      epoch  99/100: train_loss=0.000493

      epoch 100/100: train_loss=0.000442, val_loss=0.000135, IC=-0.0069

      best_ep=55, IC=+0.0218 (84.4s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.032179

      epoch   2/100: train_loss=0.005166

      epoch   3/100: train_loss=0.003716

      epoch   4/100: train_loss=0.002967

      epoch   5/100: train_loss=0.003146, val_loss=0.002223, IC=+0.0064

      epoch   6/100: train_loss=0.002996

      epoch   7/100: train_loss=0.004102

      epoch   8/100: train_loss=0.002202

      epoch   9/100: train_loss=0.002438

      epoch  10/100: train_loss=0.002973, val_loss=0.002158, IC=+0.0074

      epoch  11/100: train_loss=0.002713

      epoch  12/100: train_loss=0.002435

      epoch  13/100: train_loss=0.002005

      epoch  14/100: train_loss=0.002853

      epoch  15/100: train_loss=0.001736, val_loss=0.000685, IC=+0.0149

      epoch  16/100: train_loss=0.001701

      epoch  17/100: train_loss=0.001599

      epoch  18/100: train_loss=0.002265

      epoch  19/100: train_loss=0.001918

      epoch  20/100: train_loss=0.001668, val_loss=0.001807, IC=-0.0032

      epoch  21/100: train_loss=0.002477

      epoch  22/100: train_loss=0.001779

      epoch  23/100: train_loss=0.001969

      epoch  24/100: train_loss=0.001856

      epoch  25/100: train_loss=0.001806, val_loss=0.001967, IC=+0.0011

      epoch  26/100: train_loss=0.001601

      epoch  27/100: train_loss=0.002315

      epoch  28/100: train_loss=0.001987

      epoch  29/100: train_loss=0.001804

      epoch  30/100: train_loss=0.001279, val_loss=0.000532, IC=+0.0090

      epoch  31/100: train_loss=0.001063

      epoch  32/100: train_loss=0.001014

      epoch  33/100: train_loss=0.001060

      epoch  34/100: train_loss=0.001024

      epoch  35/100: train_loss=0.001142, val_loss=0.000328, IC=-0.0201

      epoch  36/100: train_loss=0.001558

      epoch  37/100: train_loss=0.001211

      epoch  38/100: train_loss=0.000948

      epoch  39/100: train_loss=0.000919

      epoch  40/100: train_loss=0.001133, val_loss=0.000581, IC=-0.0326

      epoch  41/100: train_loss=0.001162

      epoch  42/100: train_loss=0.000914

      epoch  43/100: train_loss=0.001489

      epoch  44/100: train_loss=0.001698

      epoch  45/100: train_loss=0.001127, val_loss=0.000320, IC=-0.0131

      epoch  46/100: train_loss=0.001192

      epoch  47/100: train_loss=0.001572

      epoch  48/100: train_loss=0.000921

      epoch  49/100: train_loss=0.001156

      epoch  50/100: train_loss=0.000855, val_loss=0.000253, IC=-0.0167

      epoch  51/100: train_loss=0.000993

      epoch  52/100: train_loss=0.001873

      epoch  53/100: train_loss=0.001228

      epoch  54/100: train_loss=0.000829

      epoch  55/100: train_loss=0.000823, val_loss=0.000229, IC=-0.0126

      epoch  56/100: train_loss=0.000739

      epoch  57/100: train_loss=0.000776

      epoch  58/100: train_loss=0.001277

      epoch  59/100: train_loss=0.002306

      epoch  60/100: train_loss=0.000836, val_loss=0.000288, IC=-0.0136

      epoch  61/100: train_loss=0.000862

      epoch  62/100: train_loss=0.000763

      epoch  63/100: train_loss=0.000798

      epoch  64/100: train_loss=0.001635

      epoch  65/100: train_loss=0.000805, val_loss=0.000248, IC=-0.0153

      epoch  66/100: train_loss=0.000984

      epoch  67/100: train_loss=0.001278

      epoch  68/100: train_loss=0.000972

      epoch  69/100: train_loss=0.000782

      epoch  70/100: train_loss=0.000768, val_loss=0.000204, IC=-0.0123

      epoch  71/100: train_loss=0.000729

      epoch  72/100: train_loss=0.000684

      epoch  73/100: train_loss=0.000633

      epoch  74/100: train_loss=0.000687

      epoch  75/100: train_loss=0.000676, val_loss=0.000189, IC=-0.0122

      epoch  76/100: train_loss=0.000721

      epoch  77/100: train_loss=0.001105

      epoch  78/100: train_loss=0.001175

      epoch  79/100: train_loss=0.000899

      epoch  80/100: train_loss=0.000852, val_loss=0.000176, IC=-0.0172

      epoch  81/100: train_loss=0.001102

      epoch  82/100: train_loss=0.000945

      epoch  83/100: train_loss=0.000693

      epoch  84/100: train_loss=0.000666

      epoch  85/100: train_loss=0.000729, val_loss=0.000172, IC=-0.0204

      epoch  86/100: train_loss=0.000781

      epoch  87/100: train_loss=0.000666

      epoch  88/100: train_loss=0.000662

      epoch  89/100: train_loss=0.000593

      epoch  90/100: train_loss=0.000756, val_loss=0.000189, IC=-0.0166

      epoch  91/100: train_loss=0.000671

      epoch  92/100: train_loss=0.000981

      epoch  93/100: train_loss=0.000629

      epoch  94/100: train_loss=0.000802

      epoch  95/100: train_loss=0.000756, val_loss=0.000176, IC=-0.0137

      epoch  96/100: train_loss=0.000619

      epoch  97/100: train_loss=0.000713

      epoch  98/100: train_loss=0.000626

      epoch  99/100: train_loss=0.000641

      epoch 100/100: train_loss=0.000707, val_loss=0.000177, IC=-0.0135

      best_ep=15, IC=+0.0149 (90.6s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.023622

      epoch   2/100: train_loss=0.005273

      epoch   3/100: train_loss=0.003288

      epoch   4/100: train_loss=0.002683

      epoch   5/100: train_loss=0.002869, val_loss=0.002073, IC=+0.0330

      epoch   6/100: train_loss=0.002970

      epoch   7/100: train_loss=0.002641

      epoch   8/100: train_loss=0.003003

      epoch   9/100: train_loss=0.002343

      epoch  10/100: train_loss=0.002309, val_loss=0.002137, IC=+0.0217

      epoch  11/100: train_loss=0.003014

      epoch  12/100: train_loss=0.002023

      epoch  13/100: train_loss=0.002100

      epoch  14/100: train_loss=0.001517

      epoch  15/100: train_loss=0.001285, val_loss=0.001228, IC=-0.0023

      epoch  16/100: train_loss=0.001573

      epoch  17/100: train_loss=0.001911

      epoch  18/100: train_loss=0.002163

      epoch  19/100: train_loss=0.001446

      epoch  20/100: train_loss=0.001384, val_loss=0.000865, IC=+0.0012

      epoch  21/100: train_loss=0.001204

      epoch  22/100: train_loss=0.001312

      epoch  23/100: train_loss=0.001289

      epoch  24/100: train_loss=0.001624

      epoch  25/100: train_loss=0.001985, val_loss=0.001597, IC=-0.0156

      epoch  26/100: train_loss=0.001483

      epoch  27/100: train_loss=0.001193

      epoch  28/100: train_loss=0.002069

      epoch  29/100: train_loss=0.001232

      epoch  30/100: train_loss=0.001611, val_loss=0.000879, IC=-0.0255

      epoch  31/100: train_loss=0.001618

      epoch  32/100: train_loss=0.001209

      epoch  33/100: train_loss=0.001373

      epoch  34/100: train_loss=0.001426

      epoch  35/100: train_loss=0.001217, val_loss=0.000858, IC=-0.0048

      epoch  36/100: train_loss=0.001040

      epoch  37/100: train_loss=0.001102

      epoch  38/100: train_loss=0.001274

      epoch  39/100: train_loss=0.001301

      epoch  40/100: train_loss=0.001461, val_loss=0.000605, IC=-0.0184

      epoch  41/100: train_loss=0.001290

      epoch  42/100: train_loss=0.000934

      epoch  43/100: train_loss=0.000824

      epoch  44/100: train_loss=0.001701

      epoch  45/100: train_loss=0.001201, val_loss=0.000759, IC=+0.0089

      epoch  46/100: train_loss=0.002259

      epoch  47/100: train_loss=0.000994

      epoch  48/100: train_loss=0.000998

      epoch  49/100: train_loss=0.000944

      epoch  50/100: train_loss=0.001038, val_loss=0.000374, IC=-0.0266

      epoch  51/100: train_loss=0.000737

      epoch  52/100: train_loss=0.000838

      epoch  53/100: train_loss=0.000644

      epoch  54/100: train_loss=0.000725

      epoch  55/100: train_loss=0.000790, val_loss=0.000374, IC=-0.0348

      epoch  56/100: train_loss=0.001104

      epoch  57/100: train_loss=0.000733

      epoch  58/100: train_loss=0.000924

      epoch  59/100: train_loss=0.000961

      epoch  60/100: train_loss=0.000808, val_loss=0.000376, IC=-0.0153

      epoch  61/100: train_loss=0.000771

      epoch  62/100: train_loss=0.001182

      epoch  63/100: train_loss=0.000818

      epoch  64/100: train_loss=0.000628

      epoch  65/100: train_loss=0.000808, val_loss=0.000322, IC=-0.0221

      epoch  66/100: train_loss=0.000764

      epoch  67/100: train_loss=0.001060

      epoch  68/100: train_loss=0.000789

      epoch  69/100: train_loss=0.000899

      epoch  70/100: train_loss=0.000708, val_loss=0.000376, IC=-0.0264

      epoch  71/100: train_loss=0.000650

      epoch  72/100: train_loss=0.000597

      epoch  73/100: train_loss=0.000541

      epoch  74/100: train_loss=0.000681

      epoch  75/100: train_loss=0.000539, val_loss=0.000344, IC=-0.0221

      epoch  76/100: train_loss=0.000622

      epoch  77/100: train_loss=0.000647

      epoch  78/100: train_loss=0.000537

      epoch  79/100: train_loss=0.000863

      epoch  80/100: train_loss=0.000543, val_loss=0.000324, IC=-0.0289

      epoch  81/100: train_loss=0.000554

      epoch  82/100: train_loss=0.000579

      epoch  83/100: train_loss=0.000532

      epoch  84/100: train_loss=0.000547

      epoch  85/100: train_loss=0.000509, val_loss=0.000331, IC=-0.0329

      epoch  86/100: train_loss=0.000758

      epoch  87/100: train_loss=0.000546

      epoch  88/100: train_loss=0.000659

      epoch  89/100: train_loss=0.000665

      epoch  90/100: train_loss=0.000564, val_loss=0.000324, IC=-0.0283

      epoch  91/100: train_loss=0.000578

      epoch  92/100: train_loss=0.000525

      epoch  93/100: train_loss=0.000677

      epoch  94/100: train_loss=0.000531

      epoch  95/100: train_loss=0.001048, val_loss=0.000351, IC=-0.0276

      epoch  96/100: train_loss=0.000571

      epoch  97/100: train_loss=0.000557

      epoch  98/100: train_loss=0.000513

      epoch  99/100: train_loss=0.000712

      epoch 100/100: train_loss=0.000513, val_loss=0.000307, IC=-0.0254

      best_ep=5, IC=+0.0330 (89.4s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.016022

      epoch   2/100: train_loss=0.003322

      epoch   3/100: train_loss=0.002388

      epoch   4/100: train_loss=0.001338

      epoch   5/100: train_loss=0.001468, val_loss=0.002897, IC=+0.0180

      epoch   6/100: train_loss=0.001820

      epoch   7/100: train_loss=0.001350

      epoch   8/100: train_loss=0.001091

      epoch   9/100: train_loss=0.000951

      epoch  10/100: train_loss=0.000850, val_loss=0.000844, IC=+0.0044

      epoch  11/100: train_loss=0.000996

      epoch  12/100: train_loss=0.001261

      epoch  13/100: train_loss=0.001334

      epoch  14/100: train_loss=0.001242

      epoch  15/100: train_loss=0.000824, val_loss=0.000503, IC=+0.0036

      epoch  16/100: train_loss=0.000786

      epoch  17/100: train_loss=0.001191

      epoch  18/100: train_loss=0.001068

      epoch  19/100: train_loss=0.000953

      epoch  20/100: train_loss=0.001173, val_loss=0.000628, IC=+0.0100

      epoch  21/100: train_loss=0.001011

      epoch  22/100: train_loss=0.000973

      epoch  23/100: train_loss=0.001117

      epoch  24/100: train_loss=0.000829

      epoch  25/100: train_loss=0.000693, val_loss=0.000342, IC=+0.0123

      epoch  26/100: train_loss=0.000621

      epoch  27/100: train_loss=0.000733

      epoch  28/100: train_loss=0.001055

      epoch  29/100: train_loss=0.000959

      epoch  30/100: train_loss=0.000748, val_loss=0.000458, IC=+0.0044

      epoch  31/100: train_loss=0.001401

      epoch  32/100: train_loss=0.000839

      epoch  33/100: train_loss=0.000794

      epoch  34/100: train_loss=0.001483

      epoch  35/100: train_loss=0.000809, val_loss=0.000315, IC=-0.0108

      epoch  36/100: train_loss=0.000577

      epoch  37/100: train_loss=0.000770

      epoch  38/100: train_loss=0.000678

      epoch  39/100: train_loss=0.000468

      epoch  40/100: train_loss=0.000546, val_loss=0.000250, IC=-0.0115

      epoch  41/100: train_loss=0.000643

      epoch  42/100: train_loss=0.000562

      epoch  43/100: train_loss=0.000748

      epoch  44/100: train_loss=0.000755

      epoch  45/100: train_loss=0.000565, val_loss=0.000289, IC=-0.0109

      epoch  46/100: train_loss=0.000438

      epoch  47/100: train_loss=0.000417

      epoch  48/100: train_loss=0.000387

      epoch  49/100: train_loss=0.000422

      epoch  50/100: train_loss=0.000522, val_loss=0.000204, IC=+0.0072

      epoch  51/100: train_loss=0.000457

      epoch  52/100: train_loss=0.000434

      epoch  53/100: train_loss=0.000522

      epoch  54/100: train_loss=0.000489

      epoch  55/100: train_loss=0.000538, val_loss=0.000441, IC=+0.0177

      epoch  56/100: train_loss=0.000622

      epoch  57/100: train_loss=0.000537

      epoch  58/100: train_loss=0.000489

      epoch  59/100: train_loss=0.000486

      epoch  60/100: train_loss=0.000491, val_loss=0.000239, IC=+0.0114

      epoch  61/100: train_loss=0.000420

      epoch  62/100: train_loss=0.000448

      epoch  63/100: train_loss=0.000374

      epoch  64/100: train_loss=0.000737

      epoch  65/100: train_loss=0.000474, val_loss=0.000500, IC=+0.0090

      epoch  66/100: train_loss=0.000428

      epoch  67/100: train_loss=0.000389

      epoch  68/100: train_loss=0.000356

      epoch  69/100: train_loss=0.000434

      epoch  70/100: train_loss=0.000394, val_loss=0.000288, IC=-0.0008

      epoch  71/100: train_loss=0.000375

      epoch  72/100: train_loss=0.000343

      epoch  73/100: train_loss=0.000351

      epoch  74/100: train_loss=0.000414

      epoch  75/100: train_loss=0.000359, val_loss=0.000241, IC=-0.0073

      epoch  76/100: train_loss=0.000351

      epoch  77/100: train_loss=0.000397

      epoch  78/100: train_loss=0.000382

      epoch  79/100: train_loss=0.000336

      epoch  80/100: train_loss=0.000364, val_loss=0.000195, IC=+0.0040

      epoch  81/100: train_loss=0.000335

      epoch  82/100: train_loss=0.000317

      epoch  83/100: train_loss=0.000420

      epoch  84/100: train_loss=0.000452

      epoch  85/100: train_loss=0.000322, val_loss=0.000152, IC=-0.0091

      epoch  86/100: train_loss=0.000358

      epoch  87/100: train_loss=0.000337

      epoch  88/100: train_loss=0.000387

      epoch  89/100: train_loss=0.000322

      epoch  90/100: train_loss=0.000311, val_loss=0.000129, IC=-0.0052

      epoch  91/100: train_loss=0.000430

      epoch  92/100: train_loss=0.000314

      epoch  93/100: train_loss=0.000355

      epoch  94/100: train_loss=0.000322

      epoch  95/100: train_loss=0.000309, val_loss=0.000141, IC=-0.0080

      epoch  96/100: train_loss=0.000316

      epoch  97/100: train_loss=0.000342

      epoch  98/100: train_loss=0.000326

      epoch  99/100: train_loss=0.000347

      epoch 100/100: train_loss=0.000375, val_loss=0.000117, IC=-0.0077

      best_ep=5, IC=+0.0180 (90.0s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.045961

      epoch   2/100: train_loss=0.003818

      epoch   3/100: train_loss=0.002584

      epoch   4/100: train_loss=0.002072

      epoch   5/100: train_loss=0.002026, val_loss=0.005649, IC=+0.0135

      epoch   6/100: train_loss=0.003262

      epoch   7/100: train_loss=0.002537

      epoch   8/100: train_loss=0.001716

      epoch   9/100: train_loss=0.001734

      epoch  10/100: train_loss=0.001305, val_loss=0.001488, IC=+0.0174

      epoch  11/100: train_loss=0.001271

      epoch  12/100: train_loss=0.001713

      epoch  13/100: train_loss=0.001624

      epoch  14/100: train_loss=0.001564

      epoch  15/100: train_loss=0.001206, val_loss=0.002817, IC=-0.0258

      epoch  16/100: train_loss=0.001268

      epoch  17/100: train_loss=0.002109

      epoch  18/100: train_loss=0.001298

      epoch  19/100: train_loss=0.001541

      epoch  20/100: train_loss=0.002317, val_loss=0.001088, IC=-0.0036

      epoch  21/100: train_loss=0.001247

      epoch  22/100: train_loss=0.001313

      epoch  23/100: train_loss=0.000902

      epoch  24/100: train_loss=0.000916

      epoch  25/100: train_loss=0.000932, val_loss=0.000735, IC=+0.0072

      epoch  26/100: train_loss=0.001419

      epoch  27/100: train_loss=0.000899

      epoch  28/100: train_loss=0.000995

      epoch  29/100: train_loss=0.001229

      epoch  30/100: train_loss=0.001137, val_loss=0.000547, IC=+0.0013

      epoch  31/100: train_loss=0.001433

      epoch  32/100: train_loss=0.000903

      epoch  33/100: train_loss=0.000723

      epoch  34/100: train_loss=0.000624

      epoch  35/100: train_loss=0.000892, val_loss=0.001293, IC=-0.0004

      epoch  36/100: train_loss=0.001536

      epoch  37/100: train_loss=0.000800

      epoch  38/100: train_loss=0.000729

      epoch  39/100: train_loss=0.000963

      epoch  40/100: train_loss=0.000819, val_loss=0.000465, IC=+0.0157

      epoch  41/100: train_loss=0.000708

      epoch  42/100: train_loss=0.000677

      epoch  43/100: train_loss=0.000546

      epoch  44/100: train_loss=0.000658

      epoch  45/100: train_loss=0.000664, val_loss=0.000657, IC=-0.0116

      epoch  46/100: train_loss=0.000617

      epoch  47/100: train_loss=0.001214

      epoch  48/100: train_loss=0.000678

      epoch  49/100: train_loss=0.001753

      epoch  50/100: train_loss=0.000630, val_loss=0.000681, IC=-0.0239

      epoch  51/100: train_loss=0.000523

      epoch  52/100: train_loss=0.000911

      epoch  53/100: train_loss=0.000716

      epoch  54/100: train_loss=0.000554

      epoch  55/100: train_loss=0.000615, val_loss=0.001135, IC=-0.0103

      epoch  56/100: train_loss=0.000469

      epoch  57/100: train_loss=0.000867

      epoch  58/100: train_loss=0.000545

      epoch  59/100: train_loss=0.000455

      epoch  60/100: train_loss=0.000554, val_loss=0.000855, IC=-0.0236

      epoch  61/100: train_loss=0.001420

      epoch  62/100: train_loss=0.000637

      epoch  63/100: train_loss=0.000705

      epoch  64/100: train_loss=0.000582

      epoch  65/100: train_loss=0.000492, val_loss=0.000601, IC=+0.0162

      epoch  66/100: train_loss=0.000420

      epoch  67/100: train_loss=0.000770

      epoch  68/100: train_loss=0.000702

      epoch  69/100: train_loss=0.000680

      epoch  70/100: train_loss=0.000854, val_loss=0.000335, IC=+0.0011

      epoch  71/100: train_loss=0.000564

      epoch  72/100: train_loss=0.000783

      epoch  73/100: train_loss=0.000474

      epoch  74/100: train_loss=0.000540

      epoch  75/100: train_loss=0.000427, val_loss=0.000349, IC=-0.0060

      epoch  76/100: train_loss=0.000435

      epoch  77/100: train_loss=0.000477

      epoch  78/100: train_loss=0.000418

      epoch  79/100: train_loss=0.000572

      epoch  80/100: train_loss=0.000730, val_loss=0.000370, IC=-0.0016

      epoch  81/100: train_loss=0.000450

      epoch  82/100: train_loss=0.000423

      epoch  83/100: train_loss=0.000387

      epoch  84/100: train_loss=0.000385

      epoch  85/100: train_loss=0.000554, val_loss=0.000405, IC=-0.0092

      epoch  86/100: train_loss=0.000391

      epoch  87/100: train_loss=0.000428

      epoch  88/100: train_loss=0.000352

      epoch  89/100: train_loss=0.000691

      epoch  90/100: train_loss=0.000404, val_loss=0.000408, IC=-0.0023

      epoch  91/100: train_loss=0.000386

      epoch  92/100: train_loss=0.000397

      epoch  93/100: train_loss=0.000496

      epoch  94/100: train_loss=0.000498

      epoch  95/100: train_loss=0.000400, val_loss=0.000378, IC=-0.0035

      epoch  96/100: train_loss=0.000632

      epoch  97/100: train_loss=0.000402

      epoch  98/100: train_loss=0.000364

      epoch  99/100: train_loss=0.000465

      epoch 100/100: train_loss=0.000428, val_loss=0.000364, IC=-0.0003

      best_ep=10, IC=+0.0174 (91.6s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,140 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.149347

      epoch   2/100: train_loss=0.024217

      epoch   3/100: train_loss=0.007176

      epoch   4/100: train_loss=0.006767

      epoch   5/100: train_loss=0.004981, val_loss=0.001764, IC=-0.0046

      epoch   6/100: train_loss=0.003147

      epoch   7/100: train_loss=0.002774

      epoch   8/100: train_loss=0.002135

      epoch   9/100: train_loss=0.004018

      epoch  10/100: train_loss=0.002185, val_loss=0.007355, IC=+0.0255

      epoch  11/100: train_loss=0.004380

      epoch  12/100: train_loss=0.002792

      epoch  13/100: train_loss=0.001762

      epoch  14/100: train_loss=0.001611

      epoch  15/100: train_loss=0.001523, val_loss=0.000733, IC=+0.0072

      epoch  16/100: train_loss=0.001687

      epoch  17/100: train_loss=0.001220

      epoch  18/100: train_loss=0.001210

      epoch  19/100: train_loss=0.001037

      epoch  20/100: train_loss=0.002764, val_loss=0.000827, IC=+0.0146

      epoch  21/100: train_loss=0.000938

      epoch  22/100: train_loss=0.001191

      epoch  23/100: train_loss=0.001014

      epoch  24/100: train_loss=0.001273

      epoch  25/100: train_loss=0.001797, val_loss=0.000851, IC=+0.0109

      epoch  26/100: train_loss=0.001178

      epoch  27/100: train_loss=0.001027

      epoch  28/100: train_loss=0.000879

      epoch  29/100: train_loss=0.000943

      epoch  30/100: train_loss=0.000882, val_loss=0.000555, IC=+0.0350

      epoch  31/100: train_loss=0.000980

      epoch  32/100: train_loss=0.000990

      epoch  33/100: train_loss=0.000983

      epoch  34/100: train_loss=0.001374

      epoch  35/100: train_loss=0.001480, val_loss=0.001124, IC=+0.0242

      epoch  36/100: train_loss=0.001047

      epoch  37/100: train_loss=0.001140

      epoch  38/100: train_loss=0.000935

      epoch  39/100: train_loss=0.000855

      epoch  40/100: train_loss=0.000646, val_loss=0.000622, IC=+0.0287

      epoch  41/100: train_loss=0.000541

      epoch  42/100: train_loss=0.000766

      epoch  43/100: train_loss=0.000734

      epoch  44/100: train_loss=0.000828

      epoch  45/100: train_loss=0.000832, val_loss=0.000648, IC=+0.0165

      epoch  46/100: train_loss=0.000785

      epoch  47/100: train_loss=0.001055

      epoch  48/100: train_loss=0.000865

      epoch  49/100: train_loss=0.000756

      epoch  50/100: train_loss=0.000744, val_loss=0.000855, IC=+0.0445

      epoch  51/100: train_loss=0.000593

      epoch  52/100: train_loss=0.000952

      epoch  53/100: train_loss=0.000656

      epoch  54/100: train_loss=0.000614

      epoch  55/100: train_loss=0.000677, val_loss=0.000295, IC=+0.0098

      epoch  56/100: train_loss=0.000777

      epoch  57/100: train_loss=0.000550

      epoch  58/100: train_loss=0.000709

      epoch  59/100: train_loss=0.000619

      epoch  60/100: train_loss=0.000655, val_loss=0.000269, IC=+0.0363

      epoch  61/100: train_loss=0.000637

      epoch  62/100: train_loss=0.000573

      epoch  63/100: train_loss=0.000568

      epoch  64/100: train_loss=0.000583

      epoch  65/100: train_loss=0.000676, val_loss=0.000220, IC=+0.0117

      epoch  66/100: train_loss=0.000679

      epoch  67/100: train_loss=0.000554

      epoch  68/100: train_loss=0.000593

      epoch  69/100: train_loss=0.000470

      epoch  70/100: train_loss=0.000445, val_loss=0.000178, IC=+0.0112

      epoch  71/100: train_loss=0.000753

      epoch  72/100: train_loss=0.000563

      epoch  73/100: train_loss=0.000534

      epoch  74/100: train_loss=0.000422

      epoch  75/100: train_loss=0.000441, val_loss=0.000180, IC=+0.0138

      epoch  76/100: train_loss=0.000567

      epoch  77/100: train_loss=0.000498

      epoch  78/100: train_loss=0.000513

      epoch  79/100: train_loss=0.000461

      epoch  80/100: train_loss=0.000694, val_loss=0.000162, IC=+0.0081

      epoch  81/100: train_loss=0.000512

      epoch  82/100: train_loss=0.000745

      epoch  83/100: train_loss=0.000468

      epoch  84/100: train_loss=0.000580

      epoch  85/100: train_loss=0.000473, val_loss=0.000219, IC=+0.0202

      epoch  86/100: train_loss=0.000506

      epoch  87/100: train_loss=0.000436

      epoch  88/100: train_loss=0.000453

      epoch  89/100: train_loss=0.000482

      epoch  90/100: train_loss=0.000428, val_loss=0.000196, IC=+0.0194

      epoch  91/100: train_loss=0.000425

      epoch  92/100: train_loss=0.000444

      epoch  93/100: train_loss=0.000555

      epoch  94/100: train_loss=0.000548

      epoch  95/100: train_loss=0.000377, val_loss=0.000159, IC=+0.0137

      epoch  96/100: train_loss=0.000627

      epoch  97/100: train_loss=0.000647

      epoch  98/100: train_loss=0.000394

      epoch  99/100: train_loss=0.000383

      epoch 100/100: train_loss=0.000400, val_loss=0.000148, IC=+0.0187

      best_ep=50, IC=+0.0445 (100.1s, 20 checkpoints)

  tcn: best_epoch=5, IC=+0.0150 (673.5s)

  Best: tcn @ epoch 5 (IC=+0.0150)
  Saved to ~/ml4t/public/case_studies/fx_pairs/run_log/training/3e68afa47f92/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=16,980 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.478626

      epoch   2/100: train_loss=0.035793

      epoch   3/100: train_loss=0.007901

      epoch   4/100: train_loss=0.004657

      epoch   5/100: train_loss=0.003255, val_loss=0.006197, IC=+0.0709

      epoch   6/100: train_loss=0.002345

      epoch   7/100: train_loss=0.001931

      epoch   8/100: train_loss=0.001679

      epoch   9/100: train_loss=0.001691

      epoch  10/100: train_loss=0.001978, val_loss=0.001777, IC=+0.0190

      epoch  11/100: train_loss=0.002206

      epoch  12/100: train_loss=0.002961

      epoch  13/100: train_loss=0.001961

      epoch  14/100: train_loss=0.002270

      epoch  15/100: train_loss=0.001634, val_loss=0.004186, IC=+0.0388

      epoch  16/100: train_loss=0.001478

      epoch  17/100: train_loss=0.001151

      epoch  18/100: train_loss=0.001362

      epoch  19/100: train_loss=0.001405

      epoch  20/100: train_loss=0.001171, val_loss=0.002534, IC=+0.0548

      epoch  21/100: train_loss=0.001344

      epoch  22/100: train_loss=0.001475

      epoch  23/100: train_loss=0.001294

      epoch  24/100: train_loss=0.001140

      epoch  25/100: train_loss=0.000995, val_loss=0.001513, IC=+0.0026

      epoch  26/100: train_loss=0.001105

      epoch  27/100: train_loss=0.001233

      epoch  28/100: train_loss=0.000976

      epoch  29/100: train_loss=0.001075

      epoch  30/100: train_loss=0.000960, val_loss=0.002872, IC=+0.0058

      epoch  31/100: train_loss=0.000965

      epoch  32/100: train_loss=0.000998

      epoch  33/100: train_loss=0.000951

      epoch  34/100: train_loss=0.001018

      epoch  35/100: train_loss=0.000997, val_loss=0.002096, IC=-0.0074

      epoch  36/100: train_loss=0.001113

      epoch  37/100: train_loss=0.000942

      epoch  38/100: train_loss=0.000895

      epoch  39/100: train_loss=0.000816

      epoch  40/100: train_loss=0.000905, val_loss=0.000666, IC=+0.0777

      epoch  41/100: train_loss=0.000883

      epoch  42/100: train_loss=0.001059

      epoch  43/100: train_loss=0.000952

      epoch  44/100: train_loss=0.000999

      epoch  45/100: train_loss=0.000891, val_loss=0.000668, IC=+0.0536

      epoch  46/100: train_loss=0.000785

      epoch  47/100: train_loss=0.000815

      epoch  48/100: train_loss=0.000783

      epoch  49/100: train_loss=0.000790

      epoch  50/100: train_loss=0.000851, val_loss=0.001210, IC=+0.0165

      epoch  51/100: train_loss=0.000763

      epoch  52/100: train_loss=0.000663

      epoch  53/100: train_loss=0.000764

      epoch  54/100: train_loss=0.000764

      epoch  55/100: train_loss=0.000706, val_loss=0.000562, IC=+0.0658

      epoch  56/100: train_loss=0.000802

      epoch  57/100: train_loss=0.000731

      epoch  58/100: train_loss=0.000741

      epoch  59/100: train_loss=0.000733

      epoch  60/100: train_loss=0.000775, val_loss=0.000565, IC=+0.0535

      epoch  61/100: train_loss=0.000776

      epoch  62/100: train_loss=0.000668

      epoch  63/100: train_loss=0.000697

      epoch  64/100: train_loss=0.000696

      epoch  65/100: train_loss=0.000765, val_loss=0.000919, IC=+0.0339

      epoch  66/100: train_loss=0.000664

      epoch  67/100: train_loss=0.000667

      epoch  68/100: train_loss=0.000656

      epoch  69/100: train_loss=0.000674

      epoch  70/100: train_loss=0.000627, val_loss=0.000894, IC=+0.0236

      epoch  71/100: train_loss=0.000719

      epoch  72/100: train_loss=0.000727

      epoch  73/100: train_loss=0.000771

      epoch  74/100: train_loss=0.000719

      epoch  75/100: train_loss=0.000713, val_loss=0.000590, IC=+0.0539

      epoch  76/100: train_loss=0.000658

      epoch  77/100: train_loss=0.000618

      epoch  78/100: train_loss=0.000593

      epoch  79/100: train_loss=0.000697

      epoch  80/100: train_loss=0.000717, val_loss=0.001023, IC=+0.0248

      epoch  81/100: train_loss=0.000629

      epoch  82/100: train_loss=0.000713

      epoch  83/100: train_loss=0.000640

      epoch  84/100: train_loss=0.000662

      epoch  85/100: train_loss=0.000767, val_loss=0.000734, IC=+0.0342

      epoch  86/100: train_loss=0.000657

      epoch  87/100: train_loss=0.000641

      epoch  88/100: train_loss=0.000706

      epoch  89/100: train_loss=0.000653

      epoch  90/100: train_loss=0.000649, val_loss=0.000664, IC=+0.0421

      epoch  91/100: train_loss=0.000679

      epoch  92/100: train_loss=0.000624

      epoch  93/100: train_loss=0.000613

      epoch  94/100: train_loss=0.000683

      epoch  95/100: train_loss=0.000667, val_loss=0.000625, IC=+0.0449

      epoch  96/100: train_loss=0.000664

      epoch  97/100: train_loss=0.000632

      epoch  98/100: train_loss=0.000696

      epoch  99/100: train_loss=0.000632

      epoch 100/100: train_loss=0.000622, val_loss=0.000665, IC=+0.0424

      best_ep=40, IC=+0.0777 (60.5s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,140 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.023650

      epoch   2/100: train_loss=0.004505

      epoch   3/100: train_loss=0.002718

      epoch   4/100: train_loss=0.002095

      epoch   5/100: train_loss=0.001831, val_loss=0.001214, IC=+0.0360

      epoch   6/100: train_loss=0.001651

      epoch   7/100: train_loss=0.001556

      epoch   8/100: train_loss=0.001500

      epoch   9/100: train_loss=0.001425

      epoch  10/100: train_loss=0.001358, val_loss=0.001014, IC=+0.0233

      epoch  11/100: train_loss=0.001306

      epoch  12/100: train_loss=0.001220

      epoch  13/100: train_loss=0.001385

      epoch  14/100: train_loss=0.001414

      epoch  15/100: train_loss=0.001240, val_loss=0.000837, IC=-0.0023

      epoch  16/100: train_loss=0.001224

      epoch  17/100: train_loss=0.001111

      epoch  18/100: train_loss=0.001053

      epoch  19/100: train_loss=0.001048

      epoch  20/100: train_loss=0.001035, val_loss=0.000631, IC=-0.0039

      epoch  21/100: train_loss=0.000971

      epoch  22/100: train_loss=0.000959

      epoch  23/100: train_loss=0.000924

      epoch  24/100: train_loss=0.000927

      epoch  25/100: train_loss=0.000883, val_loss=0.000514, IC=+0.0050

      epoch  26/100: train_loss=0.000828

      epoch  27/100: train_loss=0.000831

      epoch  28/100: train_loss=0.000862

      epoch  29/100: train_loss=0.000890

      epoch  30/100: train_loss=0.000773, val_loss=0.000474, IC=-0.0007

      epoch  31/100: train_loss=0.000783

      epoch  32/100: train_loss=0.000789

      epoch  33/100: train_loss=0.000796

      epoch  34/100: train_loss=0.000794

      epoch  35/100: train_loss=0.000786, val_loss=0.000385, IC=+0.0107

      epoch  36/100: train_loss=0.000789

      epoch  37/100: train_loss=0.000697

      epoch  38/100: train_loss=0.000730

      epoch  39/100: train_loss=0.000672

      epoch  40/100: train_loss=0.000691, val_loss=0.000312, IC=+0.0070

      epoch  41/100: train_loss=0.000651

      epoch  42/100: train_loss=0.000664

      epoch  43/100: train_loss=0.000669

      epoch  44/100: train_loss=0.000640

      epoch  45/100: train_loss=0.000634, val_loss=0.000294, IC=+0.0010

      epoch  46/100: train_loss=0.000623

      epoch  47/100: train_loss=0.000650

      epoch  48/100: train_loss=0.000614

      epoch  49/100: train_loss=0.000596

      epoch  50/100: train_loss=0.000607, val_loss=0.000312, IC=+0.0118

      epoch  51/100: train_loss=0.000596

      epoch  52/100: train_loss=0.000560

      epoch  53/100: train_loss=0.000598

      epoch  54/100: train_loss=0.000587

      epoch  55/100: train_loss=0.000589, val_loss=0.000274, IC=+0.0150

      epoch  56/100: train_loss=0.000574

      epoch  57/100: train_loss=0.000584

      epoch  58/100: train_loss=0.000561

      epoch  59/100: train_loss=0.000595

      epoch  60/100: train_loss=0.000563, val_loss=0.000256, IC=+0.0034

      epoch  61/100: train_loss=0.000555

      epoch  62/100: train_loss=0.000546

      epoch  63/100: train_loss=0.000542

      epoch  64/100: train_loss=0.000547

      epoch  65/100: train_loss=0.000556, val_loss=0.000298, IC=+0.0006

      epoch  66/100: train_loss=0.000548

      epoch  67/100: train_loss=0.000535

      epoch  68/100: train_loss=0.000566

      epoch  69/100: train_loss=0.000532

      epoch  70/100: train_loss=0.000530, val_loss=0.000274, IC=+0.0024

      epoch  71/100: train_loss=0.000522

      epoch  72/100: train_loss=0.000527

      epoch  73/100: train_loss=0.000546

      epoch  74/100: train_loss=0.000522

      epoch  75/100: train_loss=0.000508, val_loss=0.000257, IC=+0.0034

      epoch  76/100: train_loss=0.000513

      epoch  77/100: train_loss=0.000536

      epoch  78/100: train_loss=0.000503

      epoch  79/100: train_loss=0.000517

      epoch  80/100: train_loss=0.000497, val_loss=0.000251, IC=+0.0025

      epoch  81/100: train_loss=0.000509

      epoch  82/100: train_loss=0.000530

      epoch  83/100: train_loss=0.000512

      epoch  84/100: train_loss=0.000516

      epoch  85/100: train_loss=0.000489, val_loss=0.000245, IC=+0.0019

      epoch  86/100: train_loss=0.000499

      epoch  87/100: train_loss=0.000489

      epoch  88/100: train_loss=0.000509

      epoch  89/100: train_loss=0.000505

      epoch  90/100: train_loss=0.000500, val_loss=0.000264, IC=+0.0010

      epoch  91/100: train_loss=0.000511

      epoch  92/100: train_loss=0.000486

      epoch  93/100: train_loss=0.000505

      epoch  94/100: train_loss=0.000493

      epoch  95/100: train_loss=0.000488, val_loss=0.000251, IC=+0.0039

      epoch  96/100: train_loss=0.000527

      epoch  97/100: train_loss=0.000510

      epoch  98/100: train_loss=0.000500

      epoch  99/100: train_loss=0.000501

      epoch 100/100: train_loss=0.000516, val_loss=0.000252, IC=+0.0024

      best_ep=5, IC=+0.0360 (78.4s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.517963

      epoch   2/100: train_loss=0.028553

      epoch   3/100: train_loss=0.006396

      epoch   4/100: train_loss=0.002725

      epoch   5/100: train_loss=0.001851, val_loss=0.000597, IC=-0.0528

      epoch   6/100: train_loss=0.001668

      epoch   7/100: train_loss=0.001422

      epoch   8/100: train_loss=0.001605

      epoch   9/100: train_loss=0.001412

      epoch  10/100: train_loss=0.001284, val_loss=0.000446, IC=-0.0481

      epoch  11/100: train_loss=0.001173

      epoch  12/100: train_loss=0.001100

      epoch  13/100: train_loss=0.000986

      epoch  14/100: train_loss=0.001075

      epoch  15/100: train_loss=0.001179, val_loss=0.000300, IC=-0.0373

      epoch  16/100: train_loss=0.000986

      epoch  17/100: train_loss=0.001116

      epoch  18/100: train_loss=0.000875

      epoch  19/100: train_loss=0.000898

      epoch  20/100: train_loss=0.000989, val_loss=0.000374, IC=-0.0500

      epoch  21/100: train_loss=0.000805

      epoch  22/100: train_loss=0.000917

      epoch  23/100: train_loss=0.000980

      epoch  24/100: train_loss=0.000954

      epoch  25/100: train_loss=0.000735, val_loss=0.000231, IC=-0.0628

      epoch  26/100: train_loss=0.000746

      epoch  27/100: train_loss=0.000860

      epoch  28/100: train_loss=0.000878

      epoch  29/100: train_loss=0.000872

      epoch  30/100: train_loss=0.000935, val_loss=0.000213, IC=-0.0504

      epoch  31/100: train_loss=0.000802

      epoch  32/100: train_loss=0.000769

      epoch  33/100: train_loss=0.000728

      epoch  34/100: train_loss=0.000732

      epoch  35/100: train_loss=0.000726, val_loss=0.000228, IC=-0.0681

      epoch  36/100: train_loss=0.000658

      epoch  37/100: train_loss=0.000698

      epoch  38/100: train_loss=0.000770

      epoch  39/100: train_loss=0.000636

      epoch  40/100: train_loss=0.000869, val_loss=0.000181, IC=-0.0492

      epoch  41/100: train_loss=0.000684

      epoch  42/100: train_loss=0.000732

      epoch  43/100: train_loss=0.000736

      epoch  44/100: train_loss=0.000694

      epoch  45/100: train_loss=0.000662, val_loss=0.000181, IC=-0.0577

      epoch  46/100: train_loss=0.000664

      epoch  47/100: train_loss=0.000749

      epoch  48/100: train_loss=0.000623

      epoch  49/100: train_loss=0.000649

      epoch  50/100: train_loss=0.000612, val_loss=0.000185, IC=-0.0513

      epoch  51/100: train_loss=0.000639

      epoch  52/100: train_loss=0.000565

      epoch  53/100: train_loss=0.000591

      epoch  54/100: train_loss=0.000602

      epoch  55/100: train_loss=0.000662, val_loss=0.000262, IC=-0.0624

      epoch  56/100: train_loss=0.000594

      epoch  57/100: train_loss=0.000547

      epoch  58/100: train_loss=0.000580

      epoch  59/100: train_loss=0.000724

      epoch  60/100: train_loss=0.000709, val_loss=0.000175, IC=-0.0574

      epoch  61/100: train_loss=0.000661

      epoch  62/100: train_loss=0.000618

      epoch  63/100: train_loss=0.000598

      epoch  64/100: train_loss=0.000551

      epoch  65/100: train_loss=0.000601, val_loss=0.000174, IC=-0.0474

      epoch  66/100: train_loss=0.000546

      epoch  67/100: train_loss=0.000603

      epoch  68/100: train_loss=0.000525

      epoch  69/100: train_loss=0.000591

      epoch  70/100: train_loss=0.000522, val_loss=0.000189, IC=-0.0435

      epoch  71/100: train_loss=0.000540

      epoch  72/100: train_loss=0.000539

      epoch  73/100: train_loss=0.000506

      epoch  74/100: train_loss=0.000515

      epoch  75/100: train_loss=0.000524, val_loss=0.000184, IC=-0.0464

      epoch  76/100: train_loss=0.000579

      epoch  77/100: train_loss=0.000560

      epoch  78/100: train_loss=0.000551

      epoch  79/100: train_loss=0.000495

      epoch  80/100: train_loss=0.000508, val_loss=0.000178, IC=-0.0500

      epoch  81/100: train_loss=0.000532

      epoch  82/100: train_loss=0.000485

      epoch  83/100: train_loss=0.000537

      epoch  84/100: train_loss=0.000515

      epoch  85/100: train_loss=0.000520, val_loss=0.000173, IC=-0.0440

      epoch  86/100: train_loss=0.000516

      epoch  87/100: train_loss=0.000472

      epoch  88/100: train_loss=0.000506

      epoch  89/100: train_loss=0.000497

      epoch  90/100: train_loss=0.000516, val_loss=0.000191, IC=-0.0461

      epoch  91/100: train_loss=0.000519

      epoch  92/100: train_loss=0.000529

      epoch  93/100: train_loss=0.000508

      epoch  94/100: train_loss=0.000526

      epoch  95/100: train_loss=0.000511, val_loss=0.000173, IC=-0.0453

      epoch  96/100: train_loss=0.000482

      epoch  97/100: train_loss=0.000512

      epoch  98/100: train_loss=0.000506

      epoch  99/100: train_loss=0.000475

      epoch 100/100: train_loss=0.000482, val_loss=0.000168, IC=-0.0457

      best_ep=15, IC=-0.0373 (93.3s, 20 checkpoints)

  Fold 3: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.032989

      epoch   2/100: train_loss=0.005305

      epoch   3/100: train_loss=0.003462

      epoch   4/100: train_loss=0.002761

      epoch   5/100: train_loss=0.002434, val_loss=0.001309, IC=+0.0113

      epoch   6/100: train_loss=0.002167

      epoch   7/100: train_loss=0.002040

      epoch   8/100: train_loss=0.001933

      epoch   9/100: train_loss=0.001864

      epoch  10/100: train_loss=0.001780, val_loss=0.000903, IC=-0.0112

      epoch  11/100: train_loss=0.001734

      epoch  12/100: train_loss=0.001697

      epoch  13/100: train_loss=0.001611

      epoch  14/100: train_loss=0.001472

      epoch  15/100: train_loss=0.001461, val_loss=0.000717, IC=-0.0170

      epoch  16/100: train_loss=0.001364

      epoch  17/100: train_loss=0.001316

      epoch  18/100: train_loss=0.001271

      epoch  19/100: train_loss=0.001240

      epoch  20/100: train_loss=0.001335, val_loss=0.000609, IC=-0.0230

      epoch  21/100: train_loss=0.001189

      epoch  22/100: train_loss=0.001170

      epoch  23/100: train_loss=0.001222

      epoch  24/100: train_loss=0.001274

      epoch  25/100: train_loss=0.001158, val_loss=0.000489, IC=-0.0219

      epoch  26/100: train_loss=0.001047

      epoch  27/100: train_loss=0.001030

      epoch  28/100: train_loss=0.001002

      epoch  29/100: train_loss=0.001017

      epoch  30/100: train_loss=0.000989, val_loss=0.000480, IC=-0.0308

      epoch  31/100: train_loss=0.000947

      epoch  32/100: train_loss=0.000913

      epoch  33/100: train_loss=0.000892

      epoch  34/100: train_loss=0.000921

      epoch  35/100: train_loss=0.000873, val_loss=0.000519, IC=-0.0522

      epoch  36/100: train_loss=0.000841

      epoch  37/100: train_loss=0.000856

      epoch  38/100: train_loss=0.000817

      epoch  39/100: train_loss=0.000832

      epoch  40/100: train_loss=0.000820, val_loss=0.000329, IC=-0.0550

      epoch  41/100: train_loss=0.000814

      epoch  42/100: train_loss=0.000754

      epoch  43/100: train_loss=0.000781

      epoch  44/100: train_loss=0.000781

      epoch  45/100: train_loss=0.000749, val_loss=0.000298, IC=-0.0470

      epoch  46/100: train_loss=0.000716

      epoch  47/100: train_loss=0.000732

      epoch  48/100: train_loss=0.000715

      epoch  49/100: train_loss=0.000727

      epoch  50/100: train_loss=0.000706, val_loss=0.000314, IC=-0.0439

      epoch  51/100: train_loss=0.000696

      epoch  52/100: train_loss=0.000691

      epoch  53/100: train_loss=0.000684

      epoch  54/100: train_loss=0.000692

      epoch  55/100: train_loss=0.000691, val_loss=0.000277, IC=-0.0427

      epoch  56/100: train_loss=0.000640

      epoch  57/100: train_loss=0.000663

      epoch  58/100: train_loss=0.000652

      epoch  59/100: train_loss=0.000631

      epoch  60/100: train_loss=0.000631, val_loss=0.000278, IC=-0.0324

      epoch  61/100: train_loss=0.000620

      epoch  62/100: train_loss=0.000635

      epoch  63/100: train_loss=0.000608

      epoch  64/100: train_loss=0.000621

      epoch  65/100: train_loss=0.000640, val_loss=0.000243, IC=-0.0298

      epoch  66/100: train_loss=0.000611

      epoch  67/100: train_loss=0.000600

      epoch  68/100: train_loss=0.000606

      epoch  69/100: train_loss=0.000607

      epoch  70/100: train_loss=0.000597, val_loss=0.000258, IC=-0.0270

      epoch  71/100: train_loss=0.000595

      epoch  72/100: train_loss=0.000596

      epoch  73/100: train_loss=0.000584

      epoch  74/100: train_loss=0.000593

      epoch  75/100: train_loss=0.000592, val_loss=0.000250, IC=-0.0280

      epoch  76/100: train_loss=0.000573

      epoch  77/100: train_loss=0.000590

      epoch  78/100: train_loss=0.000571

      epoch  79/100: train_loss=0.000573

      epoch  80/100: train_loss=0.000558, val_loss=0.000268, IC=-0.0282

      epoch  81/100: train_loss=0.000574

      epoch  82/100: train_loss=0.000585

      epoch  83/100: train_loss=0.000590

      epoch  84/100: train_loss=0.000576

      epoch  85/100: train_loss=0.000569, val_loss=0.000244, IC=-0.0266

      epoch  86/100: train_loss=0.000570

      epoch  87/100: train_loss=0.000577

      epoch  88/100: train_loss=0.000561

      epoch  89/100: train_loss=0.000559

      epoch  90/100: train_loss=0.000569, val_loss=0.000242, IC=-0.0241

      epoch  91/100: train_loss=0.000556

      epoch  92/100: train_loss=0.000560

      epoch  93/100: train_loss=0.000561

      epoch  94/100: train_loss=0.000569

      epoch  95/100: train_loss=0.000569, val_loss=0.000242, IC=-0.0240

      epoch  96/100: train_loss=0.000551

      epoch  97/100: train_loss=0.000559

      epoch  98/100: train_loss=0.000551

      epoch  99/100: train_loss=0.000560

      epoch 100/100: train_loss=0.000559, val_loss=0.000247, IC=-0.0255

      best_ep=5, IC=+0.0113 (78.8s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.024740

      epoch   2/100: train_loss=0.004755

      epoch   3/100: train_loss=0.002994

      epoch   4/100: train_loss=0.002362

      epoch   5/100: train_loss=0.002135, val_loss=0.002905, IC=-0.0117

      epoch   6/100: train_loss=0.001899

      epoch   7/100: train_loss=0.001745

      epoch   8/100: train_loss=0.001679

      epoch   9/100: train_loss=0.001595

      epoch  10/100: train_loss=0.001519, val_loss=0.001382, IC=-0.0296

      epoch  11/100: train_loss=0.001472

      epoch  12/100: train_loss=0.001454

      epoch  13/100: train_loss=0.001363

      epoch  14/100: train_loss=0.001302

      epoch  15/100: train_loss=0.001282, val_loss=0.001017, IC=-0.0321

      epoch  16/100: train_loss=0.001197

      epoch  17/100: train_loss=0.001140

      epoch  18/100: train_loss=0.001156

      epoch  19/100: train_loss=0.001128

      epoch  20/100: train_loss=0.001096, val_loss=0.000960, IC=-0.0516

      epoch  21/100: train_loss=0.001016

      epoch  22/100: train_loss=0.001004

      epoch  23/100: train_loss=0.001019

      epoch  24/100: train_loss=0.001023

      epoch  25/100: train_loss=0.001081, val_loss=0.001486, IC=-0.0157

      epoch  26/100: train_loss=0.000986

      epoch  27/100: train_loss=0.000918

      epoch  28/100: train_loss=0.000904

      epoch  29/100: train_loss=0.000883

      epoch  30/100: train_loss=0.000885, val_loss=0.000730, IC=-0.0372

      epoch  31/100: train_loss=0.000833

      epoch  32/100: train_loss=0.000772

      epoch  33/100: train_loss=0.000783

      epoch  34/100: train_loss=0.000749

      epoch  35/100: train_loss=0.000762, val_loss=0.000754, IC=-0.0146

      epoch  36/100: train_loss=0.000749

      epoch  37/100: train_loss=0.000720

      epoch  38/100: train_loss=0.000735

      epoch  39/100: train_loss=0.000727

      epoch  40/100: train_loss=0.000675, val_loss=0.000718, IC=-0.0157

      epoch  41/100: train_loss=0.000704

      epoch  42/100: train_loss=0.000683

      epoch  43/100: train_loss=0.000648

      epoch  44/100: train_loss=0.000636

      epoch  45/100: train_loss=0.000642, val_loss=0.000832, IC=+0.0010

      epoch  46/100: train_loss=0.000633

      epoch  47/100: train_loss=0.000639

      epoch  48/100: train_loss=0.000614

      epoch  49/100: train_loss=0.000608

      epoch  50/100: train_loss=0.000595, val_loss=0.000528, IC=-0.0193

      epoch  51/100: train_loss=0.000596

      epoch  52/100: train_loss=0.000597

      epoch  53/100: train_loss=0.000580

      epoch  54/100: train_loss=0.000574

      epoch  55/100: train_loss=0.000562, val_loss=0.000516, IC=-0.0117

      epoch  56/100: train_loss=0.000585

      epoch  57/100: train_loss=0.000568

      epoch  58/100: train_loss=0.000553

      epoch  59/100: train_loss=0.000538

      epoch  60/100: train_loss=0.000549, val_loss=0.000549, IC=-0.0160

      epoch  61/100: train_loss=0.000534

      epoch  62/100: train_loss=0.000525

      epoch  63/100: train_loss=0.000553

      epoch  64/100: train_loss=0.000534

      epoch  65/100: train_loss=0.000522, val_loss=0.000490, IC=-0.0128

      epoch  66/100: train_loss=0.000530

      epoch  67/100: train_loss=0.000526

      epoch  68/100: train_loss=0.000526

      epoch  69/100: train_loss=0.000526

      epoch  70/100: train_loss=0.000524, val_loss=0.000506, IC=-0.0096

      epoch  71/100: train_loss=0.000518

      epoch  72/100: train_loss=0.000512

      epoch  73/100: train_loss=0.000491

      epoch  74/100: train_loss=0.000502

      epoch  75/100: train_loss=0.000512, val_loss=0.000476, IC=-0.0113

      epoch  76/100: train_loss=0.000492

      epoch  77/100: train_loss=0.000492

      epoch  78/100: train_loss=0.000499

      epoch  79/100: train_loss=0.000494

      epoch  80/100: train_loss=0.000494, val_loss=0.000491, IC=-0.0111

      epoch  81/100: train_loss=0.000494

      epoch  82/100: train_loss=0.000487

      epoch  83/100: train_loss=0.000496

      epoch  84/100: train_loss=0.000481

      epoch  85/100: train_loss=0.000463, val_loss=0.000450, IC=-0.0170

      epoch  86/100: train_loss=0.000482

      epoch  87/100: train_loss=0.000493

      epoch  88/100: train_loss=0.000491

      epoch  89/100: train_loss=0.000480

      epoch  90/100: train_loss=0.000481, val_loss=0.000476, IC=-0.0084

      epoch  91/100: train_loss=0.000468

      epoch  92/100: train_loss=0.000485

      epoch  93/100: train_loss=0.000477

      epoch  94/100: train_loss=0.000471

      epoch  95/100: train_loss=0.000476, val_loss=0.000467, IC=-0.0093

      epoch  96/100: train_loss=0.000469

      epoch  97/100: train_loss=0.000473

      epoch  98/100: train_loss=0.000479

      epoch  99/100: train_loss=0.000490

      epoch 100/100: train_loss=0.000471, val_loss=0.000476, IC=-0.0091

      best_ep=45, IC=+0.0010 (80.5s, 20 checkpoints)

  Fold 5: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.016474

      epoch   2/100: train_loss=0.002832

      epoch   3/100: train_loss=0.001650

      epoch   4/100: train_loss=0.001264

      epoch   5/100: train_loss=0.001138, val_loss=0.001219, IC=+0.0268

      epoch   6/100: train_loss=0.001063

      epoch   7/100: train_loss=0.000984

      epoch   8/100: train_loss=0.000955

      epoch   9/100: train_loss=0.000900

      epoch  10/100: train_loss=0.000841, val_loss=0.000505, IC=+0.0494

      epoch  11/100: train_loss=0.000845

      epoch  12/100: train_loss=0.000802

      epoch  13/100: train_loss=0.000762

      epoch  14/100: train_loss=0.000765

      epoch  15/100: train_loss=0.000752, val_loss=0.000645, IC=+0.0630

      epoch  16/100: train_loss=0.000724

      epoch  17/100: train_loss=0.000727

      epoch  18/100: train_loss=0.000684

      epoch  19/100: train_loss=0.000653

      epoch  20/100: train_loss=0.000696, val_loss=0.000768, IC=+0.0554

      epoch  21/100: train_loss=0.000716

      epoch  22/100: train_loss=0.000652

      epoch  23/100: train_loss=0.000583

      epoch  24/100: train_loss=0.000576

      epoch  25/100: train_loss=0.000573, val_loss=0.000446, IC=+0.0745

      epoch  26/100: train_loss=0.000588

      epoch  27/100: train_loss=0.000552

      epoch  28/100: train_loss=0.000536

      epoch  29/100: train_loss=0.000533

      epoch  30/100: train_loss=0.000525, val_loss=0.000404, IC=+0.0572

      epoch  31/100: train_loss=0.000548

      epoch  32/100: train_loss=0.000541

      epoch  33/100: train_loss=0.000523

      epoch  34/100: train_loss=0.000498

      epoch  35/100: train_loss=0.000495, val_loss=0.000351, IC=+0.0661

      epoch  36/100: train_loss=0.000498

      epoch  37/100: train_loss=0.000533

      epoch  38/100: train_loss=0.000490

      epoch  39/100: train_loss=0.000464

      epoch  40/100: train_loss=0.000451, val_loss=0.000396, IC=+0.0547

      epoch  41/100: train_loss=0.000458

      epoch  42/100: train_loss=0.000464

      epoch  43/100: train_loss=0.000444

      epoch  44/100: train_loss=0.000419

      epoch  45/100: train_loss=0.000449, val_loss=0.000272, IC=+0.0540

      epoch  46/100: train_loss=0.000439

      epoch  47/100: train_loss=0.000419

      epoch  48/100: train_loss=0.000420

      epoch  49/100: train_loss=0.000411

      epoch  50/100: train_loss=0.000407, val_loss=0.000431, IC=+0.0595

      epoch  51/100: train_loss=0.000406

      epoch  52/100: train_loss=0.000412

      epoch  53/100: train_loss=0.000410

      epoch  54/100: train_loss=0.000401

      epoch  55/100: train_loss=0.000407, val_loss=0.000340, IC=+0.0640

      epoch  56/100: train_loss=0.000386

      epoch  57/100: train_loss=0.000397

      epoch  58/100: train_loss=0.000387

      epoch  59/100: train_loss=0.000384

      epoch  60/100: train_loss=0.000391, val_loss=0.000251, IC=+0.0473

      epoch  61/100: train_loss=0.000380

      epoch  62/100: train_loss=0.000378

      epoch  63/100: train_loss=0.000375

      epoch  64/100: train_loss=0.000364

      epoch  65/100: train_loss=0.000370, val_loss=0.000268, IC=+0.0521

      epoch  66/100: train_loss=0.000366

      epoch  67/100: train_loss=0.000371

      epoch  68/100: train_loss=0.000364

      epoch  69/100: train_loss=0.000371

      epoch  70/100: train_loss=0.000366, val_loss=0.000250, IC=+0.0558

      epoch  71/100: train_loss=0.000363

      epoch  72/100: train_loss=0.000366

      epoch  73/100: train_loss=0.000358

      epoch  74/100: train_loss=0.000360

      epoch  75/100: train_loss=0.000359, val_loss=0.000249, IC=+0.0498

      epoch  76/100: train_loss=0.000351

      epoch  77/100: train_loss=0.000345

      epoch  78/100: train_loss=0.000349

      epoch  79/100: train_loss=0.000348

      epoch  80/100: train_loss=0.000349, val_loss=0.000293, IC=+0.0481

      epoch  81/100: train_loss=0.000355

      epoch  82/100: train_loss=0.000350

      epoch  83/100: train_loss=0.000349

      epoch  84/100: train_loss=0.000351

      epoch  85/100: train_loss=0.000349, val_loss=0.000281, IC=+0.0492

      epoch  86/100: train_loss=0.000346

      epoch  87/100: train_loss=0.000350

      epoch  88/100: train_loss=0.000345

      epoch  89/100: train_loss=0.000346

      epoch  90/100: train_loss=0.000334, val_loss=0.000255, IC=+0.0501

      epoch  91/100: train_loss=0.000350

      epoch  92/100: train_loss=0.000353

      epoch  93/100: train_loss=0.000339

      epoch  94/100: train_loss=0.000347

      epoch  95/100: train_loss=0.000341, val_loss=0.000250, IC=+0.0480

      epoch  96/100: train_loss=0.000346

      epoch  97/100: train_loss=0.000336

      epoch  98/100: train_loss=0.000360

      epoch  99/100: train_loss=0.000347

      epoch 100/100: train_loss=0.000340, val_loss=0.000256, IC=+0.0482

      best_ep=25, IC=+0.0745 (86.6s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.046180

      epoch   2/100: train_loss=0.003383

      epoch   3/100: train_loss=0.002152

      epoch   4/100: train_loss=0.001724

      epoch   5/100: train_loss=0.001577, val_loss=0.002884, IC=+0.0172

      epoch   6/100: train_loss=0.001421

      epoch   7/100: train_loss=0.001329

      epoch   8/100: train_loss=0.001220

      epoch   9/100: train_loss=0.001160

      epoch  10/100: train_loss=0.001113, val_loss=0.001148, IC=+0.0269

      epoch  11/100: train_loss=0.001071

      epoch  12/100: train_loss=0.000989

      epoch  13/100: train_loss=0.000978

      epoch  14/100: train_loss=0.000898

      epoch  15/100: train_loss=0.000890, val_loss=0.001082, IC=+0.0222

      epoch  16/100: train_loss=0.000830

      epoch  17/100: train_loss=0.000795

      epoch  18/100: train_loss=0.000783

      epoch  19/100: train_loss=0.000856

      epoch  20/100: train_loss=0.000724, val_loss=0.000597, IC=+0.0362

      epoch  21/100: train_loss=0.000689

      epoch  22/100: train_loss=0.000642

      epoch  23/100: train_loss=0.000631

      epoch  24/100: train_loss=0.000622

      epoch  25/100: train_loss=0.000612, val_loss=0.000623, IC=+0.0192

      epoch  26/100: train_loss=0.000590

      epoch  27/100: train_loss=0.000565

      epoch  28/100: train_loss=0.000576

      epoch  29/100: train_loss=0.000537

      epoch  30/100: train_loss=0.000530, val_loss=0.000596, IC=+0.0207

      epoch  31/100: train_loss=0.000546

      epoch  32/100: train_loss=0.000543

      epoch  33/100: train_loss=0.000548

      epoch  34/100: train_loss=0.000494

      epoch  35/100: train_loss=0.000489, val_loss=0.000475, IC=+0.0294

      epoch  36/100: train_loss=0.000466

      epoch  37/100: train_loss=0.000560

      epoch  38/100: train_loss=0.000529

      epoch  39/100: train_loss=0.000479

      epoch  40/100: train_loss=0.000456, val_loss=0.000451, IC=+0.0347

      epoch  41/100: train_loss=0.000429

      epoch  42/100: train_loss=0.000447

      epoch  43/100: train_loss=0.000410

      epoch  44/100: train_loss=0.000404

      epoch  45/100: train_loss=0.000456, val_loss=0.000441, IC=+0.0397

      epoch  46/100: train_loss=0.000425

      epoch  47/100: train_loss=0.000414

      epoch  48/100: train_loss=0.000385

      epoch  49/100: train_loss=0.000363

      epoch  50/100: train_loss=0.000359, val_loss=0.000415, IC=+0.0302

      epoch  51/100: train_loss=0.000385

      epoch  52/100: train_loss=0.000372

      epoch  53/100: train_loss=0.000382

      epoch  54/100: train_loss=0.000404

      epoch  55/100: train_loss=0.000380, val_loss=0.000359, IC=+0.0324

      epoch  56/100: train_loss=0.000386

      epoch  57/100: train_loss=0.000339

      epoch  58/100: train_loss=0.000364

      epoch  59/100: train_loss=0.000357

      epoch  60/100: train_loss=0.000345, val_loss=0.000424, IC=+0.0244

      epoch  61/100: train_loss=0.000335

      epoch  62/100: train_loss=0.000335

      epoch  63/100: train_loss=0.000361

      epoch  64/100: train_loss=0.000369

      epoch  65/100: train_loss=0.000359, val_loss=0.000368, IC=+0.0337

      epoch  66/100: train_loss=0.000324

      epoch  67/100: train_loss=0.000333

      epoch  68/100: train_loss=0.000338

      epoch  69/100: train_loss=0.000338

      epoch  70/100: train_loss=0.000368, val_loss=0.000352, IC=+0.0169

      epoch  71/100: train_loss=0.000349

      epoch  72/100: train_loss=0.000333

      epoch  73/100: train_loss=0.000333

      epoch  74/100: train_loss=0.000327

      epoch  75/100: train_loss=0.000326, val_loss=0.000366, IC=+0.0185

      epoch  76/100: train_loss=0.000306

      epoch  77/100: train_loss=0.000316

      epoch  78/100: train_loss=0.000322

      epoch  79/100: train_loss=0.000320

      epoch  80/100: train_loss=0.000307, val_loss=0.000359, IC=+0.0239

      epoch  81/100: train_loss=0.000314

      epoch  82/100: train_loss=0.000313

      epoch  83/100: train_loss=0.000306

      epoch  84/100: train_loss=0.000311

      epoch  85/100: train_loss=0.000310, val_loss=0.000339, IC=+0.0244

      epoch  86/100: train_loss=0.000308

      epoch  87/100: train_loss=0.000318

      epoch  88/100: train_loss=0.000307

      epoch  89/100: train_loss=0.000300

      epoch  90/100: train_loss=0.000301, val_loss=0.000353, IC=+0.0205

      epoch  91/100: train_loss=0.000298

      epoch  92/100: train_loss=0.000306

      epoch  93/100: train_loss=0.000300

      epoch  94/100: train_loss=0.000313

      epoch  95/100: train_loss=0.000300, val_loss=0.000341, IC=+0.0182

      epoch  96/100: train_loss=0.000304

      epoch  97/100: train_loss=0.000297

      epoch  98/100: train_loss=0.000312

      epoch  99/100: train_loss=0.000307

      epoch 100/100: train_loss=0.000301, val_loss=0.000343, IC=+0.0186

      best_ep=45, IC=+0.0397 (88.0s, 20 checkpoints)

  Fold 7: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,060 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.208229

      epoch   2/100: train_loss=0.019211

      epoch   3/100: train_loss=0.004595

      epoch   4/100: train_loss=0.002082

      epoch   5/100: train_loss=0.001514, val_loss=0.000933, IC=-0.0471

      epoch   6/100: train_loss=0.001533

      epoch   7/100: train_loss=0.001420

      epoch   8/100: train_loss=0.001325

      epoch   9/100: train_loss=0.001351

      epoch  10/100: train_loss=0.001066, val_loss=0.000594, IC=-0.0855

      epoch  11/100: train_loss=0.000995

      epoch  12/100: train_loss=0.000997

      epoch  13/100: train_loss=0.001011

      epoch  14/100: train_loss=0.000842

      epoch  15/100: train_loss=0.000955, val_loss=0.000463, IC=-0.0809

      epoch  16/100: train_loss=0.001046

      epoch  17/100: train_loss=0.000909

      epoch  18/100: train_loss=0.001150

      epoch  19/100: train_loss=0.000986

      epoch  20/100: train_loss=0.000740, val_loss=0.000543, IC=-0.0479

      epoch  21/100: train_loss=0.000835

      epoch  22/100: train_loss=0.000854

      epoch  23/100: train_loss=0.000784

      epoch  24/100: train_loss=0.000683

      epoch  25/100: train_loss=0.000586, val_loss=0.000624, IC=-0.0229

      epoch  26/100: train_loss=0.000610

      epoch  27/100: train_loss=0.000572

      epoch  28/100: train_loss=0.000634

      epoch  29/100: train_loss=0.000605

      epoch  30/100: train_loss=0.000648, val_loss=0.000609, IC=-0.0102

      epoch  31/100: train_loss=0.000647

      epoch  32/100: train_loss=0.000748

      epoch  33/100: train_loss=0.000690

      epoch  34/100: train_loss=0.000577

      epoch  35/100: train_loss=0.000579, val_loss=0.000308, IC=-0.0165

      epoch  36/100: train_loss=0.000593

      epoch  37/100: train_loss=0.000515

      epoch  38/100: train_loss=0.000538

      epoch  39/100: train_loss=0.000668

      epoch  40/100: train_loss=0.000543, val_loss=0.000412, IC=-0.0144

      epoch  41/100: train_loss=0.000547

      epoch  42/100: train_loss=0.000519

      epoch  43/100: train_loss=0.000532

      epoch  44/100: train_loss=0.000489

      epoch  45/100: train_loss=0.000485, val_loss=0.000267, IC=-0.0192

      epoch  46/100: train_loss=0.000469

      epoch  47/100: train_loss=0.000460

      epoch  48/100: train_loss=0.000465

      epoch  49/100: train_loss=0.000487

      epoch  50/100: train_loss=0.000424, val_loss=0.000335, IC=-0.0087

      epoch  51/100: train_loss=0.000434

      epoch  52/100: train_loss=0.000468

      epoch  53/100: train_loss=0.000431

      epoch  54/100: train_loss=0.000435

      epoch  55/100: train_loss=0.000455, val_loss=0.000315, IC=-0.0036

      epoch  56/100: train_loss=0.000423

      epoch  57/100: train_loss=0.000433

      epoch  58/100: train_loss=0.000466

      epoch  59/100: train_loss=0.000453

      epoch  60/100: train_loss=0.000441, val_loss=0.000294, IC=+0.0019

      epoch  61/100: train_loss=0.000423

      epoch  62/100: train_loss=0.000435

      epoch  63/100: train_loss=0.000403

      epoch  64/100: train_loss=0.000440

      epoch  65/100: train_loss=0.000405, val_loss=0.000350, IC=+0.0078

      epoch  66/100: train_loss=0.000431

      epoch  67/100: train_loss=0.000416

      epoch  68/100: train_loss=0.000413

      epoch  69/100: train_loss=0.000435

      epoch  70/100: train_loss=0.000446, val_loss=0.000240, IC=-0.0151

      epoch  71/100: train_loss=0.000401

      epoch  72/100: train_loss=0.000410

      epoch  73/100: train_loss=0.000415

      epoch  74/100: train_loss=0.000409

      epoch  75/100: train_loss=0.000410, val_loss=0.000276, IC=+0.0017

      epoch  76/100: train_loss=0.000383

      epoch  77/100: train_loss=0.000384

      epoch  78/100: train_loss=0.000400

      epoch  79/100: train_loss=0.000368

      epoch  80/100: train_loss=0.000410, val_loss=0.000323, IC=+0.0115

      epoch  81/100: train_loss=0.000384

      epoch  82/100: train_loss=0.000417

      epoch  83/100: train_loss=0.000376

      epoch  84/100: train_loss=0.000405

      epoch  85/100: train_loss=0.000402, val_loss=0.000265, IC=+0.0044

      epoch  86/100: train_loss=0.000406

      epoch  87/100: train_loss=0.000379

      epoch  88/100: train_loss=0.000376

      epoch  89/100: train_loss=0.000364

      epoch  90/100: train_loss=0.000389, val_loss=0.000265, IC=-0.0032

      epoch  91/100: train_loss=0.000393

      epoch  92/100: train_loss=0.000417

      epoch  93/100: train_loss=0.000417

      epoch  94/100: train_loss=0.000391

      epoch  95/100: train_loss=0.000388, val_loss=0.000255, IC=+0.0003

      epoch  96/100: train_loss=0.000379

      epoch  97/100: train_loss=0.000370

      epoch  98/100: train_loss=0.000387

      epoch  99/100: train_loss=0.000390

      epoch 100/100: train_loss=0.000404, val_loss=0.000261, IC=+0.0010

      best_ep=80, IC=+0.0115 (89.3s, 20 checkpoints)

  tcn: best_epoch=55, IC=+0.0071 (655.5s)

  Best: tcn @ epoch 55 (IC=+0.0071)
  Saved to ~/ml4t/public/case_studies/fx_pairs/run_log/training/c22b88518fc2/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=16,660 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.494122

      epoch   2/100: train_loss=0.038416

      epoch   3/100: train_loss=0.006894

      epoch   4/100: train_loss=0.003716

      epoch   5/100: train_loss=0.003969, val_loss=0.016036, IC=+0.0084

      epoch   6/100: train_loss=0.002863

      epoch   7/100: train_loss=0.003874

      epoch   8/100: train_loss=0.002198

      epoch   9/100: train_loss=0.002701

      epoch  10/100: train_loss=0.002403, val_loss=0.019164, IC=+0.0022

      epoch  11/100: train_loss=0.003653

      epoch  12/100: train_loss=0.002107

      epoch  13/100: train_loss=0.002989

      epoch  14/100: train_loss=0.001939

      epoch  15/100: train_loss=0.001882, val_loss=0.002662, IC=+0.0088

      epoch  16/100: train_loss=0.002266

      epoch  17/100: train_loss=0.001661

      epoch  18/100: train_loss=0.001594

      epoch  19/100: train_loss=0.002012

      epoch  20/100: train_loss=0.001484, val_loss=0.002670, IC=-0.0010

      epoch  21/100: train_loss=0.001685

      epoch  22/100: train_loss=0.001260

      epoch  23/100: train_loss=0.001564

      epoch  24/100: train_loss=0.001452

      epoch  25/100: train_loss=0.001792, val_loss=0.010421, IC=-0.0482

      epoch  26/100: train_loss=0.001677

      epoch  27/100: train_loss=0.001274

      epoch  28/100: train_loss=0.001488

      epoch  29/100: train_loss=0.001319

      epoch  30/100: train_loss=0.001610, val_loss=0.009597, IC=-0.0461

      epoch  31/100: train_loss=0.001548

      epoch  32/100: train_loss=0.001364

      epoch  33/100: train_loss=0.001221

      epoch  34/100: train_loss=0.001148

      epoch  35/100: train_loss=0.001244, val_loss=0.001608, IC=+0.0964

      epoch  36/100: train_loss=0.001109

      epoch  37/100: train_loss=0.001235

      epoch  38/100: train_loss=0.001312

      epoch  39/100: train_loss=0.001121

      epoch  40/100: train_loss=0.001044, val_loss=0.001944, IC=-0.0486

      epoch  41/100: train_loss=0.001013

      epoch  42/100: train_loss=0.001040

      epoch  43/100: train_loss=0.001134

      epoch  44/100: train_loss=0.000987

      epoch  45/100: train_loss=0.000911, val_loss=0.001487, IC=+0.0275

      epoch  46/100: train_loss=0.000917

      epoch  47/100: train_loss=0.000957

      epoch  48/100: train_loss=0.000990

      epoch  49/100: train_loss=0.001036

      epoch  50/100: train_loss=0.001266, val_loss=0.001541, IC=+0.0072

      epoch  51/100: train_loss=0.001222

      epoch  52/100: train_loss=0.001144

      epoch  53/100: train_loss=0.000941

      epoch  54/100: train_loss=0.000823

      epoch  55/100: train_loss=0.000852, val_loss=0.001513, IC=+0.0074

      epoch  56/100: train_loss=0.000884

      epoch  57/100: train_loss=0.001052

      epoch  58/100: train_loss=0.000965

      epoch  59/100: train_loss=0.000925

      epoch  60/100: train_loss=0.000868, val_loss=0.002001, IC=+0.0785

      epoch  61/100: train_loss=0.001000

      epoch  62/100: train_loss=0.000927

      epoch  63/100: train_loss=0.000774

      epoch  64/100: train_loss=0.000784

      epoch  65/100: train_loss=0.000838, val_loss=0.002659, IC=-0.0740

      epoch  66/100: train_loss=0.000866

      epoch  67/100: train_loss=0.000809

      epoch  68/100: train_loss=0.000813

      epoch  69/100: train_loss=0.000912

      epoch  70/100: train_loss=0.000820, val_loss=0.001771, IC=-0.0435

      epoch  71/100: train_loss=0.000849

      epoch  72/100: train_loss=0.000811

      epoch  73/100: train_loss=0.000929

      epoch  74/100: train_loss=0.000804

      epoch  75/100: train_loss=0.000794, val_loss=0.001978, IC=-0.0527

      epoch  76/100: train_loss=0.000759

      epoch  77/100: train_loss=0.000806

      epoch  78/100: train_loss=0.000789

      epoch  79/100: train_loss=0.000770

      epoch  80/100: train_loss=0.000731, val_loss=0.001515, IC=+0.0235

      epoch  81/100: train_loss=0.000799

      epoch  82/100: train_loss=0.000787

      epoch  83/100: train_loss=0.000866

      epoch  84/100: train_loss=0.000794

      epoch  85/100: train_loss=0.000774, val_loss=0.001765, IC=-0.0315

      epoch  86/100: train_loss=0.000953

      epoch  87/100: train_loss=0.000804

      epoch  88/100: train_loss=0.000779

      epoch  89/100: train_loss=0.000838

      epoch  90/100: train_loss=0.000808, val_loss=0.001724, IC=-0.0298

      epoch  91/100: train_loss=0.000865

      epoch  92/100: train_loss=0.000751

      epoch  93/100: train_loss=0.000777

      epoch  94/100: train_loss=0.000789

      epoch  95/100: train_loss=0.000815, val_loss=0.001660, IC=-0.0152

      epoch  96/100: train_loss=0.000761

      epoch  97/100: train_loss=0.000674

      epoch  98/100: train_loss=0.000782

      epoch  99/100: train_loss=0.000862

      epoch 100/100: train_loss=0.000774, val_loss=0.001725, IC=-0.0235

      best_ep=35, IC=+0.0964 (61.1s, 20 checkpoints)

  Fold 1: creating sequences...
    train=21,820 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.023926

      epoch   2/100: train_loss=0.005420

      epoch   3/100: train_loss=0.003367

      epoch   4/100: train_loss=0.002649

      epoch   5/100: train_loss=0.002293, val_loss=0.001961, IC=+0.0541

      epoch   6/100: train_loss=0.002056

      epoch   7/100: train_loss=0.001931

      epoch   8/100: train_loss=0.001792

      epoch   9/100: train_loss=0.001746

      epoch  10/100: train_loss=0.001701, val_loss=0.001769, IC=+0.0046

      epoch  11/100: train_loss=0.001625

      epoch  12/100: train_loss=0.001581

      epoch  13/100: train_loss=0.001491

      epoch  14/100: train_loss=0.001598

      epoch  15/100: train_loss=0.001448, val_loss=0.001355, IC=+0.0259

      epoch  16/100: train_loss=0.001361

      epoch  17/100: train_loss=0.001533

      epoch  18/100: train_loss=0.001289

      epoch  19/100: train_loss=0.001275

      epoch  20/100: train_loss=0.001237, val_loss=0.001321, IC=+0.0410

      epoch  21/100: train_loss=0.001235

      epoch  22/100: train_loss=0.001179

      epoch  23/100: train_loss=0.001206

      epoch  24/100: train_loss=0.001121

      epoch  25/100: train_loss=0.001123, val_loss=0.001330, IC=+0.0322

      epoch  26/100: train_loss=0.001054

      epoch  27/100: train_loss=0.001031

      epoch  28/100: train_loss=0.001013

      epoch  29/100: train_loss=0.000979

      epoch  30/100: train_loss=0.001030, val_loss=0.001370, IC=+0.0367

      epoch  31/100: train_loss=0.000996

      epoch  32/100: train_loss=0.001013

      epoch  33/100: train_loss=0.000967

      epoch  34/100: train_loss=0.001010

      epoch  35/100: train_loss=0.000983, val_loss=0.001260, IC=+0.0317

      epoch  36/100: train_loss=0.000916

      epoch  37/100: train_loss=0.000932

      epoch  38/100: train_loss=0.000917

      epoch  39/100: train_loss=0.000887

      epoch  40/100: train_loss=0.000833, val_loss=0.001319, IC=+0.0286

      epoch  41/100: train_loss=0.000832

      epoch  42/100: train_loss=0.000866

      epoch  43/100: train_loss=0.000852

      epoch  44/100: train_loss=0.000843

      epoch  45/100: train_loss=0.000787, val_loss=0.001140, IC=+0.0238

      epoch  46/100: train_loss=0.000848

      epoch  47/100: train_loss=0.000826

      epoch  48/100: train_loss=0.000854

      epoch  49/100: train_loss=0.000853

      epoch  50/100: train_loss=0.000818, val_loss=0.001207, IC=+0.0258

      epoch  51/100: train_loss=0.000791

      epoch  52/100: train_loss=0.000764

      epoch  53/100: train_loss=0.000762

      epoch  54/100: train_loss=0.000757

      epoch  55/100: train_loss=0.000719, val_loss=0.001228, IC=+0.0254

      epoch  56/100: train_loss=0.000743

      epoch  57/100: train_loss=0.000750

      epoch  58/100: train_loss=0.000758

      epoch  59/100: train_loss=0.000701

      epoch  60/100: train_loss=0.000713, val_loss=0.001209, IC=+0.0290

      epoch  61/100: train_loss=0.000732

      epoch  62/100: train_loss=0.000795

      epoch  63/100: train_loss=0.000741

      epoch  64/100: train_loss=0.000715

      epoch  65/100: train_loss=0.000693, val_loss=0.001254, IC=+0.0189

      epoch  66/100: train_loss=0.000714

      epoch  67/100: train_loss=0.000698

      epoch  68/100: train_loss=0.000725

      epoch  69/100: train_loss=0.000655

      epoch  70/100: train_loss=0.000670, val_loss=0.001184, IC=+0.0253

      epoch  71/100: train_loss=0.000671

      epoch  72/100: train_loss=0.000673

      epoch  73/100: train_loss=0.000669

      epoch  74/100: train_loss=0.000675

      epoch  75/100: train_loss=0.000673, val_loss=0.001181, IC=+0.0327

      epoch  76/100: train_loss=0.000671

      epoch  77/100: train_loss=0.000657

      epoch  78/100: train_loss=0.000650

      epoch  79/100: train_loss=0.000674

      epoch  80/100: train_loss=0.000663, val_loss=0.001196, IC=+0.0328

      epoch  81/100: train_loss=0.000674

      epoch  82/100: train_loss=0.000670

      epoch  83/100: train_loss=0.000646

      epoch  84/100: train_loss=0.000650

      epoch  85/100: train_loss=0.000651, val_loss=0.001212, IC=+0.0357

      epoch  86/100: train_loss=0.000651

      epoch  87/100: train_loss=0.000648

      epoch  88/100: train_loss=0.000659

      epoch  89/100: train_loss=0.000644

      epoch  90/100: train_loss=0.000665, val_loss=0.001177, IC=+0.0384

      epoch  91/100: train_loss=0.000652

      epoch  92/100: train_loss=0.000624

      epoch  93/100: train_loss=0.000642

      epoch  94/100: train_loss=0.000642

      epoch  95/100: train_loss=0.000626, val_loss=0.001162, IC=+0.0367

      epoch  96/100: train_loss=0.000654

      epoch  97/100: train_loss=0.000656

      epoch  98/100: train_loss=0.000670

      epoch  99/100: train_loss=0.000640

      epoch 100/100: train_loss=0.000667, val_loss=0.001173, IC=+0.0367

      best_ep=5, IC=+0.0541 (79.9s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.535167

      epoch   2/100: train_loss=0.030984

      epoch   3/100: train_loss=0.006304

      epoch   4/100: train_loss=0.003381

      epoch   5/100: train_loss=0.002563, val_loss=0.001058, IC=-0.0089

      epoch   6/100: train_loss=0.002171

      epoch   7/100: train_loss=0.001892

      epoch   8/100: train_loss=0.001790

      epoch   9/100: train_loss=0.001683

      epoch  10/100: train_loss=0.001855, val_loss=0.000829, IC=-0.0210

      epoch  11/100: train_loss=0.001583

      epoch  12/100: train_loss=0.001758

      epoch  13/100: train_loss=0.001495

      epoch  14/100: train_loss=0.001436

      epoch  15/100: train_loss=0.001471, val_loss=0.000757, IC=-0.0246

      epoch  16/100: train_loss=0.001336

      epoch  17/100: train_loss=0.001288

      epoch  18/100: train_loss=0.001398

      epoch  19/100: train_loss=0.001306

      epoch  20/100: train_loss=0.001223, val_loss=0.000771, IC=-0.0410

      epoch  21/100: train_loss=0.001128

      epoch  22/100: train_loss=0.001159

      epoch  23/100: train_loss=0.001253

      epoch  24/100: train_loss=0.001465

      epoch  25/100: train_loss=0.001315, val_loss=0.000807, IC=-0.0491

      epoch  26/100: train_loss=0.001248

      epoch  27/100: train_loss=0.001070

      epoch  28/100: train_loss=0.001071

      epoch  29/100: train_loss=0.001152

      epoch  30/100: train_loss=0.001230, val_loss=0.000776, IC=-0.0606

      epoch  31/100: train_loss=0.001042

      epoch  32/100: train_loss=0.001073

      epoch  33/100: train_loss=0.000983

      epoch  34/100: train_loss=0.000971

      epoch  35/100: train_loss=0.000971, val_loss=0.000809, IC=-0.0581

      epoch  36/100: train_loss=0.001049

      epoch  37/100: train_loss=0.000960

      epoch  38/100: train_loss=0.000950

      epoch  39/100: train_loss=0.000893

      epoch  40/100: train_loss=0.000933, val_loss=0.000821, IC=-0.0483

      epoch  41/100: train_loss=0.000922

      epoch  42/100: train_loss=0.000991

      epoch  43/100: train_loss=0.000938

      epoch  44/100: train_loss=0.000915

      epoch  45/100: train_loss=0.000999, val_loss=0.001000, IC=-0.0591

      epoch  46/100: train_loss=0.000945

      epoch  47/100: train_loss=0.000883

      epoch  48/100: train_loss=0.000942

      epoch  49/100: train_loss=0.000902

      epoch  50/100: train_loss=0.001013, val_loss=0.000852, IC=-0.0534

      epoch  51/100: train_loss=0.000897

      epoch  52/100: train_loss=0.000904

      epoch  53/100: train_loss=0.000845

      epoch  54/100: train_loss=0.000758

      epoch  55/100: train_loss=0.000778, val_loss=0.000860, IC=-0.0509

      epoch  56/100: train_loss=0.000772

      epoch  57/100: train_loss=0.000875

      epoch  58/100: train_loss=0.000842

      epoch  59/100: train_loss=0.000843

      epoch  60/100: train_loss=0.000773, val_loss=0.000850, IC=-0.0415

      epoch  61/100: train_loss=0.000725

      epoch  62/100: train_loss=0.000746

      epoch  63/100: train_loss=0.000722

      epoch  64/100: train_loss=0.000714

      epoch  65/100: train_loss=0.000742, val_loss=0.000980, IC=-0.0448

      epoch  66/100: train_loss=0.000723

      epoch  67/100: train_loss=0.000707

      epoch  68/100: train_loss=0.000736

      epoch  69/100: train_loss=0.000706

      epoch  70/100: train_loss=0.000715, val_loss=0.000960, IC=-0.0420

      epoch  71/100: train_loss=0.000707

      epoch  72/100: train_loss=0.000715

      epoch  73/100: train_loss=0.000669

      epoch  74/100: train_loss=0.000678

      epoch  75/100: train_loss=0.000704, val_loss=0.000930, IC=-0.0418

      epoch  76/100: train_loss=0.000716

      epoch  77/100: train_loss=0.000668

      epoch  78/100: train_loss=0.000683

      epoch  79/100: train_loss=0.000713

      epoch  80/100: train_loss=0.000686, val_loss=0.000935, IC=-0.0342

      epoch  81/100: train_loss=0.000753

      epoch  82/100: train_loss=0.000683

      epoch  83/100: train_loss=0.000685

      epoch  84/100: train_loss=0.000649

      epoch  85/100: train_loss=0.000694, val_loss=0.000932, IC=-0.0342

      epoch  86/100: train_loss=0.000672

      epoch  87/100: train_loss=0.000670

      epoch  88/100: train_loss=0.000660

      epoch  89/100: train_loss=0.000626

      epoch  90/100: train_loss=0.000643, val_loss=0.000945, IC=-0.0356

      epoch  91/100: train_loss=0.000653

      epoch  92/100: train_loss=0.000657

      epoch  93/100: train_loss=0.000637

      epoch  94/100: train_loss=0.000690

      epoch  95/100: train_loss=0.000685, val_loss=0.000940, IC=-0.0355

      epoch  96/100: train_loss=0.000632

      epoch  97/100: train_loss=0.000709

      epoch  98/100: train_loss=0.000647

      epoch  99/100: train_loss=0.000644

      epoch 100/100: train_loss=0.000688, val_loss=0.000966, IC=-0.0351

      best_ep=5, IC=-0.0089 (82.7s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.035931

      epoch   2/100: train_loss=0.006035

      epoch   3/100: train_loss=0.003793

      epoch   4/100: train_loss=0.002977

      epoch   5/100: train_loss=0.002623, val_loss=0.001637, IC=+0.0374

      epoch   6/100: train_loss=0.002494

      epoch   7/100: train_loss=0.002307

      epoch   8/100: train_loss=0.002169

      epoch   9/100: train_loss=0.002095

      epoch  10/100: train_loss=0.002013, val_loss=0.001249, IC=+0.0371

      epoch  11/100: train_loss=0.001943

      epoch  12/100: train_loss=0.001819

      epoch  13/100: train_loss=0.001770

      epoch  14/100: train_loss=0.001767

      epoch  15/100: train_loss=0.001730, val_loss=0.000974, IC=+0.0050

      epoch  16/100: train_loss=0.001660

      epoch  17/100: train_loss=0.001563

      epoch  18/100: train_loss=0.001566

      epoch  19/100: train_loss=0.001518

      epoch  20/100: train_loss=0.001464, val_loss=0.001161, IC=+0.0092

      epoch  21/100: train_loss=0.001379

      epoch  22/100: train_loss=0.001373

      epoch  23/100: train_loss=0.001382

      epoch  24/100: train_loss=0.001304

      epoch  25/100: train_loss=0.001287, val_loss=0.000965, IC=+0.0195

      epoch  26/100: train_loss=0.001267

      epoch  27/100: train_loss=0.001241

      epoch  28/100: train_loss=0.001209

      epoch  29/100: train_loss=0.001161

      epoch  30/100: train_loss=0.001197, val_loss=0.000954, IC=+0.0104

      epoch  31/100: train_loss=0.001231

      epoch  32/100: train_loss=0.001168

      epoch  33/100: train_loss=0.001092

      epoch  34/100: train_loss=0.001091

      epoch  35/100: train_loss=0.001068, val_loss=0.000806, IC=+0.0528

      epoch  36/100: train_loss=0.001091

      epoch  37/100: train_loss=0.001052

      epoch  38/100: train_loss=0.001047

      epoch  39/100: train_loss=0.000985

      epoch  40/100: train_loss=0.001003, val_loss=0.000741, IC=+0.0318

      epoch  41/100: train_loss=0.001015

      epoch  42/100: train_loss=0.000991

      epoch  43/100: train_loss=0.000993

      epoch  44/100: train_loss=0.000993

      epoch  45/100: train_loss=0.000997, val_loss=0.000684, IC=+0.0456

      epoch  46/100: train_loss=0.000971

      epoch  47/100: train_loss=0.000947

      epoch  48/100: train_loss=0.000935

      epoch  49/100: train_loss=0.000927

      epoch  50/100: train_loss=0.000922, val_loss=0.000745, IC=+0.0261

      epoch  51/100: train_loss=0.000890

      epoch  52/100: train_loss=0.000892

      epoch  53/100: train_loss=0.000859

      epoch  54/100: train_loss=0.000865

      epoch  55/100: train_loss=0.000875, val_loss=0.000639, IC=+0.0568

      epoch  56/100: train_loss=0.000880

      epoch  57/100: train_loss=0.000866

      epoch  58/100: train_loss=0.000852

      epoch  59/100: train_loss=0.000850

      epoch  60/100: train_loss=0.000863, val_loss=0.000647, IC=+0.0443

      epoch  61/100: train_loss=0.000829

      epoch  62/100: train_loss=0.000821

      epoch  63/100: train_loss=0.000801

      epoch  64/100: train_loss=0.000829

      epoch  65/100: train_loss=0.000797, val_loss=0.000690, IC=+0.0536

      epoch  66/100: train_loss=0.000801

      epoch  67/100: train_loss=0.000839

      epoch  68/100: train_loss=0.000805

      epoch  69/100: train_loss=0.000793

      epoch  70/100: train_loss=0.000784, val_loss=0.000699, IC=+0.0490

      epoch  71/100: train_loss=0.000791

      epoch  72/100: train_loss=0.000767

      epoch  73/100: train_loss=0.000782

      epoch  74/100: train_loss=0.000778

      epoch  75/100: train_loss=0.000763, val_loss=0.000644, IC=+0.0542

      epoch  76/100: train_loss=0.000772

      epoch  77/100: train_loss=0.000776

      epoch  78/100: train_loss=0.000777

      epoch  79/100: train_loss=0.000748

      epoch  80/100: train_loss=0.000746, val_loss=0.000663, IC=+0.0516

      epoch  81/100: train_loss=0.000754

      epoch  82/100: train_loss=0.000746

      epoch  83/100: train_loss=0.000754

      epoch  84/100: train_loss=0.000744

      epoch  85/100: train_loss=0.000748, val_loss=0.000651, IC=+0.0493

      epoch  86/100: train_loss=0.000759

      epoch  87/100: train_loss=0.000742

      epoch  88/100: train_loss=0.000747

      epoch  89/100: train_loss=0.000750

      epoch  90/100: train_loss=0.000743, val_loss=0.000689, IC=+0.0509

      epoch  91/100: train_loss=0.000744

      epoch  92/100: train_loss=0.000752

      epoch  93/100: train_loss=0.000751

      epoch  94/100: train_loss=0.000743

      epoch  95/100: train_loss=0.000757, val_loss=0.000664, IC=+0.0521

      epoch  96/100: train_loss=0.000737

      epoch  97/100: train_loss=0.000743

      epoch  98/100: train_loss=0.000754

      epoch  99/100: train_loss=0.000731

      epoch 100/100: train_loss=0.000736, val_loss=0.000660, IC=+0.0523

      best_ep=55, IC=+0.0568 (94.4s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.025481

      epoch   2/100: train_loss=0.004925

      epoch   3/100: train_loss=0.003060

      epoch   4/100: train_loss=0.002504

      epoch   5/100: train_loss=0.002220, val_loss=0.002593, IC=-0.1343

      epoch   6/100: train_loss=0.002052

      epoch   7/100: train_loss=0.001975

      epoch   8/100: train_loss=0.001845

      epoch   9/100: train_loss=0.001716

      epoch  10/100: train_loss=0.001647, val_loss=0.002143, IC=-0.1243

      epoch  11/100: train_loss=0.001578

      epoch  12/100: train_loss=0.001527

      epoch  13/100: train_loss=0.001448

      epoch  14/100: train_loss=0.001463

      epoch  15/100: train_loss=0.001438, val_loss=0.002918, IC=-0.0899

      epoch  16/100: train_loss=0.001360

      epoch  17/100: train_loss=0.001301

      epoch  18/100: train_loss=0.001238

      epoch  19/100: train_loss=0.001204

      epoch  20/100: train_loss=0.001177, val_loss=0.001898, IC=-0.1106

      epoch  21/100: train_loss=0.001130

      epoch  22/100: train_loss=0.001116

      epoch  23/100: train_loss=0.001105

      epoch  24/100: train_loss=0.001046

      epoch  25/100: train_loss=0.001044, val_loss=0.001681, IC=-0.0833

      epoch  26/100: train_loss=0.001066

      epoch  27/100: train_loss=0.001070

      epoch  28/100: train_loss=0.000996

      epoch  29/100: train_loss=0.001019

      epoch  30/100: train_loss=0.000995, val_loss=0.001796, IC=-0.0996

      epoch  31/100: train_loss=0.000895

      epoch  32/100: train_loss=0.000918

      epoch  33/100: train_loss=0.000943

      epoch  34/100: train_loss=0.000935

      epoch  35/100: train_loss=0.000853, val_loss=0.001805, IC=-0.0819

      epoch  36/100: train_loss=0.000878

      epoch  37/100: train_loss=0.000841

      epoch  38/100: train_loss=0.000883

      epoch  39/100: train_loss=0.000828

      epoch  40/100: train_loss=0.000841, val_loss=0.001688, IC=-0.0881

      epoch  41/100: train_loss=0.000865

      epoch  42/100: train_loss=0.000815

      epoch  43/100: train_loss=0.000773

      epoch  44/100: train_loss=0.000769

      epoch  45/100: train_loss=0.000751, val_loss=0.001660, IC=-0.0823

      epoch  46/100: train_loss=0.000776

      epoch  47/100: train_loss=0.000785

      epoch  48/100: train_loss=0.000731

      epoch  49/100: train_loss=0.000721

      epoch  50/100: train_loss=0.000719, val_loss=0.001578, IC=-0.0584

      epoch  51/100: train_loss=0.000716

      epoch  52/100: train_loss=0.000695

      epoch  53/100: train_loss=0.000684

      epoch  54/100: train_loss=0.000694

      epoch  55/100: train_loss=0.000662, val_loss=0.001582, IC=-0.0637

      epoch  56/100: train_loss=0.000660

      epoch  57/100: train_loss=0.000678

      epoch  58/100: train_loss=0.000684

      epoch  59/100: train_loss=0.000659

      epoch  60/100: train_loss=0.000705, val_loss=0.001550, IC=-0.0602

      epoch  61/100: train_loss=0.000644

      epoch  62/100: train_loss=0.000655

      epoch  63/100: train_loss=0.000659

      epoch  64/100: train_loss=0.000631

      epoch  65/100: train_loss=0.000667, val_loss=0.001614, IC=-0.0471

      epoch  66/100: train_loss=0.000682

      epoch  67/100: train_loss=0.000640

      epoch  68/100: train_loss=0.000636

      epoch  69/100: train_loss=0.000634

      epoch  70/100: train_loss=0.000628, val_loss=0.001574, IC=-0.0540

      epoch  71/100: train_loss=0.000613

      epoch  72/100: train_loss=0.000607

      epoch  73/100: train_loss=0.000625

      epoch  74/100: train_loss=0.000608

      epoch  75/100: train_loss=0.000616, val_loss=0.001520, IC=-0.0400

      epoch  76/100: train_loss=0.000612

      epoch  77/100: train_loss=0.000586

      epoch  78/100: train_loss=0.000608

      epoch  79/100: train_loss=0.000600

      epoch  80/100: train_loss=0.000605, val_loss=0.001570, IC=-0.0495

      epoch  81/100: train_loss=0.000612

      epoch  82/100: train_loss=0.000601

      epoch  83/100: train_loss=0.000590

      epoch  84/100: train_loss=0.000591

      epoch  85/100: train_loss=0.000586, val_loss=0.001539, IC=-0.0488

      epoch  86/100: train_loss=0.000575

      epoch  87/100: train_loss=0.000600

      epoch  88/100: train_loss=0.000598

      epoch  89/100: train_loss=0.000586

      epoch  90/100: train_loss=0.000598, val_loss=0.001545, IC=-0.0443

      epoch  91/100: train_loss=0.000567

      epoch  92/100: train_loss=0.000567

      epoch  93/100: train_loss=0.000563

      epoch  94/100: train_loss=0.000582

      epoch  95/100: train_loss=0.000576, val_loss=0.001526, IC=-0.0436

      epoch  96/100: train_loss=0.000596

      epoch  97/100: train_loss=0.000584

      epoch  98/100: train_loss=0.000585

      epoch  99/100: train_loss=0.000582

      epoch 100/100: train_loss=0.000591, val_loss=0.001536, IC=-0.0432

      best_ep=75, IC=-0.0400 (86.4s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.017299

      epoch   2/100: train_loss=0.003322

      epoch   3/100: train_loss=0.001980

      epoch   4/100: train_loss=0.001571

      epoch   5/100: train_loss=0.001430, val_loss=0.001565, IC=+0.0846

      epoch   6/100: train_loss=0.001283

      epoch   7/100: train_loss=0.001251

      epoch   8/100: train_loss=0.001168

      epoch   9/100: train_loss=0.001129

      epoch  10/100: train_loss=0.001071, val_loss=0.001584, IC=+0.1091

      epoch  11/100: train_loss=0.001053

      epoch  12/100: train_loss=0.001032

      epoch  13/100: train_loss=0.000988

      epoch  14/100: train_loss=0.000929

      epoch  15/100: train_loss=0.000924, val_loss=0.001187, IC=+0.0966

      epoch  16/100: train_loss=0.000883

      epoch  17/100: train_loss=0.000867

      epoch  18/100: train_loss=0.000824

      epoch  19/100: train_loss=0.000814

      epoch  20/100: train_loss=0.000808, val_loss=0.001215, IC=+0.0439

      epoch  21/100: train_loss=0.000797

      epoch  22/100: train_loss=0.000803

      epoch  23/100: train_loss=0.000770

      epoch  24/100: train_loss=0.000760

      epoch  25/100: train_loss=0.000727, val_loss=0.001273, IC=+0.0485

      epoch  26/100: train_loss=0.000714

      epoch  27/100: train_loss=0.000703

      epoch  28/100: train_loss=0.000718

      epoch  29/100: train_loss=0.000675

      epoch  30/100: train_loss=0.000659, val_loss=0.000943, IC=+0.0607

      epoch  31/100: train_loss=0.000677

      epoch  32/100: train_loss=0.000682

      epoch  33/100: train_loss=0.000623

      epoch  34/100: train_loss=0.000646

      epoch  35/100: train_loss=0.000614, val_loss=0.001134, IC=+0.0680

      epoch  36/100: train_loss=0.000614

      epoch  37/100: train_loss=0.000636

      epoch  38/100: train_loss=0.000612

      epoch  39/100: train_loss=0.000603

      epoch  40/100: train_loss=0.000603, val_loss=0.001103, IC=+0.0779

      epoch  41/100: train_loss=0.000587

      epoch  42/100: train_loss=0.000588

      epoch  43/100: train_loss=0.000557

      epoch  44/100: train_loss=0.000566

      epoch  45/100: train_loss=0.000572, val_loss=0.001315, IC=+0.0764

      epoch  46/100: train_loss=0.000536

      epoch  47/100: train_loss=0.000525

      epoch  48/100: train_loss=0.000528

      epoch  49/100: train_loss=0.000522

      epoch  50/100: train_loss=0.000520, val_loss=0.001140, IC=+0.0779

      epoch  51/100: train_loss=0.000524

      epoch  52/100: train_loss=0.000509

      epoch  53/100: train_loss=0.000524

      epoch  54/100: train_loss=0.000507

      epoch  55/100: train_loss=0.000505, val_loss=0.000908, IC=+0.0812

      epoch  56/100: train_loss=0.000516

      epoch  57/100: train_loss=0.000501

      epoch  58/100: train_loss=0.000482

      epoch  59/100: train_loss=0.000481

      epoch  60/100: train_loss=0.000481, val_loss=0.001108, IC=+0.0900

      epoch  61/100: train_loss=0.000485

      epoch  62/100: train_loss=0.000481

      epoch  63/100: train_loss=0.000463

      epoch  64/100: train_loss=0.000470

      epoch  65/100: train_loss=0.000469, val_loss=0.000914, IC=+0.0918

      epoch  66/100: train_loss=0.000467

      epoch  67/100: train_loss=0.000467

      epoch  68/100: train_loss=0.000460

      epoch  69/100: train_loss=0.000449

      epoch  70/100: train_loss=0.000468, val_loss=0.000931, IC=+0.0879

      epoch  71/100: train_loss=0.000459

      epoch  72/100: train_loss=0.000458

      epoch  73/100: train_loss=0.000451

      epoch  74/100: train_loss=0.000456

      epoch  75/100: train_loss=0.000457, val_loss=0.000879, IC=+0.0850

      epoch  76/100: train_loss=0.000448

      epoch  77/100: train_loss=0.000445

      epoch  78/100: train_loss=0.000450

      epoch  79/100: train_loss=0.000447

      epoch  80/100: train_loss=0.000450, val_loss=0.000915, IC=+0.0926

      epoch  81/100: train_loss=0.000441

      epoch  82/100: train_loss=0.000438

      epoch  83/100: train_loss=0.000445

      epoch  84/100: train_loss=0.000441

      epoch  85/100: train_loss=0.000442, val_loss=0.000846, IC=+0.0882

      epoch  86/100: train_loss=0.000440

      epoch  87/100: train_loss=0.000437

      epoch  88/100: train_loss=0.000444

      epoch  89/100: train_loss=0.000441

      epoch  90/100: train_loss=0.000444, val_loss=0.000874, IC=+0.0909

      epoch  91/100: train_loss=0.000432

      epoch  92/100: train_loss=0.000436

      epoch  93/100: train_loss=0.000435

      epoch  94/100: train_loss=0.000436

      epoch  95/100: train_loss=0.000438, val_loss=0.000860, IC=+0.0917

      epoch  96/100: train_loss=0.000440

      epoch  97/100: train_loss=0.000440

      epoch  98/100: train_loss=0.000439

      epoch  99/100: train_loss=0.000431

      epoch 100/100: train_loss=0.000435, val_loss=0.000871, IC=+0.0917

      best_ep=10, IC=+0.1091 (78.4s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.046198

      epoch   2/100: train_loss=0.003922

      epoch   3/100: train_loss=0.002348

      epoch   4/100: train_loss=0.001841

      epoch   5/100: train_loss=0.001639, val_loss=0.002317, IC=+0.0618

      epoch   6/100: train_loss=0.001517

      epoch   7/100: train_loss=0.001492

      epoch   8/100: train_loss=0.001428

      epoch   9/100: train_loss=0.001252

      epoch  10/100: train_loss=0.001271, val_loss=0.003369, IC=+0.0774

      epoch  11/100: train_loss=0.001212

      epoch  12/100: train_loss=0.001094

      epoch  13/100: train_loss=0.001085

      epoch  14/100: train_loss=0.001090

      epoch  15/100: train_loss=0.000984, val_loss=0.001794, IC=+0.1293

      epoch  16/100: train_loss=0.000927

      epoch  17/100: train_loss=0.000916

      epoch  18/100: train_loss=0.000879

      epoch  19/100: train_loss=0.000833

      epoch  20/100: train_loss=0.000864, val_loss=0.002089, IC=+0.1309

      epoch  21/100: train_loss=0.000834

      epoch  22/100: train_loss=0.000745

      epoch  23/100: train_loss=0.000792

      epoch  24/100: train_loss=0.000756

      epoch  25/100: train_loss=0.000700, val_loss=0.001737, IC=+0.1122

      epoch  26/100: train_loss=0.000764

      epoch  27/100: train_loss=0.000733

      epoch  28/100: train_loss=0.000652

      epoch  29/100: train_loss=0.000682

      epoch  30/100: train_loss=0.000680, val_loss=0.001640, IC=+0.1107

      epoch  31/100: train_loss=0.000631

      epoch  32/100: train_loss=0.000624

      epoch  33/100: train_loss=0.000626

      epoch  34/100: train_loss=0.000617

      epoch  35/100: train_loss=0.000582, val_loss=0.001542, IC=+0.0745

      epoch  36/100: train_loss=0.000564

      epoch  37/100: train_loss=0.000541

      epoch  38/100: train_loss=0.000563

      epoch  39/100: train_loss=0.000556

      epoch  40/100: train_loss=0.000559, val_loss=0.001475, IC=+0.0881

      epoch  41/100: train_loss=0.000527

      epoch  42/100: train_loss=0.000528

      epoch  43/100: train_loss=0.000505

      epoch  44/100: train_loss=0.000496

      epoch  45/100: train_loss=0.000479, val_loss=0.001558, IC=+0.0849

      epoch  46/100: train_loss=0.000511

      epoch  47/100: train_loss=0.000468

      epoch  48/100: train_loss=0.000469

      epoch  49/100: train_loss=0.000499

      epoch  50/100: train_loss=0.000466, val_loss=0.001731, IC=+0.0771

      epoch  51/100: train_loss=0.000499

      epoch  52/100: train_loss=0.000500

      epoch  53/100: train_loss=0.000470

      epoch  54/100: train_loss=0.000490

      epoch  55/100: train_loss=0.000483, val_loss=0.001584, IC=+0.0798

      epoch  56/100: train_loss=0.000452

      epoch  57/100: train_loss=0.000440

      epoch  58/100: train_loss=0.000426

      epoch  59/100: train_loss=0.000426

      epoch  60/100: train_loss=0.000431, val_loss=0.001509, IC=+0.0857

      epoch  61/100: train_loss=0.000436

      epoch  62/100: train_loss=0.000432

      epoch  63/100: train_loss=0.000428

      epoch  64/100: train_loss=0.000451

      epoch  65/100: train_loss=0.000455, val_loss=0.001508, IC=+0.0878

      epoch  66/100: train_loss=0.000408

      epoch  67/100: train_loss=0.000416

      epoch  68/100: train_loss=0.000433

      epoch  69/100: train_loss=0.000417

      epoch  70/100: train_loss=0.000416, val_loss=0.001530, IC=+0.0948

      epoch  71/100: train_loss=0.000433

      epoch  72/100: train_loss=0.000401

      epoch  73/100: train_loss=0.000395

      epoch  74/100: train_loss=0.000422

      epoch  75/100: train_loss=0.000402, val_loss=0.001543, IC=+0.0935

      epoch  76/100: train_loss=0.000404

      epoch  77/100: train_loss=0.000417

      epoch  78/100: train_loss=0.000414

      epoch  79/100: train_loss=0.000396

      epoch  80/100: train_loss=0.000414, val_loss=0.001522, IC=+0.0887

      epoch  81/100: train_loss=0.000400

      epoch  82/100: train_loss=0.000396

      epoch  83/100: train_loss=0.000386

      epoch  84/100: train_loss=0.000390

      epoch  85/100: train_loss=0.000386, val_loss=0.001519, IC=+0.0854

      epoch  86/100: train_loss=0.000390

      epoch  87/100: train_loss=0.000391

      epoch  88/100: train_loss=0.000390

      epoch  89/100: train_loss=0.000383

      epoch  90/100: train_loss=0.000395, val_loss=0.001544, IC=+0.0792

      epoch  91/100: train_loss=0.000386

      epoch  92/100: train_loss=0.000378

      epoch  93/100: train_loss=0.000388

      epoch  94/100: train_loss=0.000380

      epoch  95/100: train_loss=0.000386, val_loss=0.001531, IC=+0.0847

      epoch  96/100: train_loss=0.000389

      epoch  97/100: train_loss=0.000386

      epoch  98/100: train_loss=0.000398

      epoch  99/100: train_loss=0.000388

      epoch 100/100: train_loss=0.000378, val_loss=0.001530, IC=+0.0842

      best_ep=20, IC=+0.1309 (102.7s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,180 seq across 20 symbols
    val=4,740 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.219137

      epoch   2/100: train_loss=0.020676

      epoch   3/100: train_loss=0.005567

      epoch   4/100: train_loss=0.002580

      epoch   5/100: train_loss=0.002236, val_loss=0.001375, IC=-0.0374

      epoch   6/100: train_loss=0.001820

      epoch   7/100: train_loss=0.001523

      epoch   8/100: train_loss=0.001640

      epoch   9/100: train_loss=0.001457

      epoch  10/100: train_loss=0.001223, val_loss=0.001380, IC=-0.1338

      epoch  11/100: train_loss=0.001272

      epoch  12/100: train_loss=0.001233

      epoch  13/100: train_loss=0.001141

      epoch  14/100: train_loss=0.001203

      epoch  15/100: train_loss=0.001273, val_loss=0.001262, IC=-0.1358

      epoch  16/100: train_loss=0.001083

      epoch  17/100: train_loss=0.001030

      epoch  18/100: train_loss=0.000945

      epoch  19/100: train_loss=0.000921

      epoch  20/100: train_loss=0.000896, val_loss=0.001341, IC=-0.1424

      epoch  21/100: train_loss=0.000895

      epoch  22/100: train_loss=0.000981

      epoch  23/100: train_loss=0.000894

      epoch  24/100: train_loss=0.000905

      epoch  25/100: train_loss=0.000876, val_loss=0.001352, IC=-0.1388

      epoch  26/100: train_loss=0.000931

      epoch  27/100: train_loss=0.000844

      epoch  28/100: train_loss=0.000825

      epoch  29/100: train_loss=0.000891

      epoch  30/100: train_loss=0.000864, val_loss=0.001403, IC=-0.1480

      epoch  31/100: train_loss=0.000857

      epoch  32/100: train_loss=0.000850

      epoch  33/100: train_loss=0.000771

      epoch  34/100: train_loss=0.000738

      epoch  35/100: train_loss=0.000701, val_loss=0.001240, IC=-0.1774

      epoch  36/100: train_loss=0.000693

      epoch  37/100: train_loss=0.000729

      epoch  38/100: train_loss=0.000686

      epoch  39/100: train_loss=0.000648

      epoch  40/100: train_loss=0.000682, val_loss=0.001168, IC=-0.1783

      epoch  41/100: train_loss=0.000690

      epoch  42/100: train_loss=0.000648

      epoch  43/100: train_loss=0.000648

      epoch  44/100: train_loss=0.000722

      epoch  45/100: train_loss=0.000656, val_loss=0.001238, IC=-0.1779

      epoch  46/100: train_loss=0.000705

      epoch  47/100: train_loss=0.000696

      epoch  48/100: train_loss=0.000638

      epoch  49/100: train_loss=0.000609

      epoch  50/100: train_loss=0.000595, val_loss=0.001182, IC=-0.1993

      epoch  51/100: train_loss=0.000576

      epoch  52/100: train_loss=0.000613

      epoch  53/100: train_loss=0.000596

      epoch  54/100: train_loss=0.000604

      epoch  55/100: train_loss=0.000617, val_loss=0.001223, IC=-0.1821

      epoch  56/100: train_loss=0.000602

      epoch  57/100: train_loss=0.000591

      epoch  58/100: train_loss=0.000606

      epoch  59/100: train_loss=0.000590

      epoch  60/100: train_loss=0.000572, val_loss=0.001266, IC=-0.1835

      epoch  61/100: train_loss=0.000668

      epoch  62/100: train_loss=0.000705

      epoch  63/100: train_loss=0.000572

      epoch  64/100: train_loss=0.000596

      epoch  65/100: train_loss=0.000645, val_loss=0.001233, IC=-0.1740

      epoch  66/100: train_loss=0.000633

      epoch  67/100: train_loss=0.000544

      epoch  68/100: train_loss=0.000555

      epoch  69/100: train_loss=0.000575

      epoch  70/100: train_loss=0.000554, val_loss=0.001249, IC=-0.2070

      epoch  71/100: train_loss=0.000565

      epoch  72/100: train_loss=0.000553

      epoch  73/100: train_loss=0.000555

      epoch  74/100: train_loss=0.000538

      epoch  75/100: train_loss=0.000550, val_loss=0.001247, IC=-0.2002

      epoch  76/100: train_loss=0.000536

      epoch  77/100: train_loss=0.000533

      epoch  78/100: train_loss=0.000514

      epoch  79/100: train_loss=0.000525

      epoch  80/100: train_loss=0.000525, val_loss=0.001244, IC=-0.1966

      epoch  81/100: train_loss=0.000527

      epoch  82/100: train_loss=0.000503

      epoch  83/100: train_loss=0.000522

      epoch  84/100: train_loss=0.000517

      epoch  85/100: train_loss=0.000525, val_loss=0.001242, IC=-0.1950

      epoch  86/100: train_loss=0.000505

      epoch  87/100: train_loss=0.000496

      epoch  88/100: train_loss=0.000515

      epoch  89/100: train_loss=0.000517

      epoch  90/100: train_loss=0.000515, val_loss=0.001249, IC=-0.1986

      epoch  91/100: train_loss=0.000507

      epoch  92/100: train_loss=0.000494

      epoch  93/100: train_loss=0.000493

      epoch  94/100: train_loss=0.000499

      epoch  95/100: train_loss=0.000489, val_loss=0.001246, IC=-0.1982

      epoch  96/100: train_loss=0.000513

      epoch  97/100: train_loss=0.000494

      epoch  98/100: train_loss=0.000494

      epoch  99/100: train_loss=0.000485

      epoch 100/100: train_loss=0.000507, val_loss=0.001247, IC=-0.1976

      best_ep=5, IC=-0.0374 (90.9s, 20 checkpoints)

  tcn: best_epoch=5, IC=+0.0087 (676.6s)

  Best: tcn @ epoch 5 (IC=+0.0087)
  Saved to ~/ml4t/public/case_studies/fx_pairs/run_log/training/47fc728b2ef4/diagnostics

shape: (60, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean   ┆ ic_t      ┆ training_ ┆ predicti │
│ ---       ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---       ┆ ---       ┆ hash      ┆ on_hash  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ i64       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_1 ┆ tcn       ┆ epoch     ┆ 5         ┆ … ┆ 0.01504   ┆ 3.421703  ┆ 3e68afa47 ┆ 72b492b9 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ f92       ┆ 5612     │
│ fwd_ret_1 ┆ tcn       ┆ epoch     ┆ 10        ┆ … ┆ 0.009478  ┆ 2.329351  ┆ 3e68afa47 ┆ 39935cab │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ f92       ┆ af61     │
│ fwd_ret_1 ┆ tcn       ┆ epoch     ┆ 15        ┆ … ┆ -0.001512 ┆ -0.360233 ┆ 3e68afa47 ┆ f54719af │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ f92       ┆ 3f19     │
│ fwd_ret_1 ┆ tcn       ┆ epoch     ┆ 20        ┆ … ┆ 0.002143  ┆ 0.94085   ┆ 3e68afa47 ┆ ffca70f1 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ f92       ┆ e049     │
│ fwd_ret_1 ┆ tcn       ┆ epoch     ┆ 25        ┆ … ┆ 0.000335  ┆ 0.103149  ┆ 3e68afa47 ┆ 6fbe013b │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ f92       ┆ 2949     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_5 ┆ tcn       ┆ epoch     ┆ 80        ┆ … ┆ 0.002697  ┆ 0.257788  ┆ c22b88518 ┆ 3512b9f5 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ fc2       ┆ c49d     │
│ fwd_ret_5 ┆ tcn       ┆ epoch     ┆ 85        ┆ … ┆ 0.003322  ┆ 0.316306  ┆ c22b88518 ┆ 8140957d │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ fc2       ┆ 6005     │
│ fwd_ret_5 ┆ tcn       ┆ epoch     ┆ 90        ┆ … ┆ 0.003987  ┆ 0.371486  ┆ c22b88518 ┆ 9ce2f7f6 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ fc2       ┆ 96ee     │
│ fwd_ret_5 ┆ tcn       ┆ epoch     ┆ 95        ┆ … ┆ 0.004585  ┆ 0.432176  ┆ c22b88518 ┆ f2b03e3b │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ fc2       ┆ aa1a     │
│ fwd_ret_5 ┆ tcn       ┆ epoch     ┆ 100       ┆ … ┆ 0.00404   ┆ 0.381882  ┆ c22b88518 ┆ 7011e02c │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ fc2       ┆ d0ee     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Reload the fitted state

An identical call validates the saved weights and returns the same prediction identities. The
comparison with other model families belongs in `12_model_analysis` after every family completes.

In [6]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("TCN checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview sequence checkpoints remain outside official comparisons.")

Official prediction population: 3cf95f3b150d

## Key takeaways

- Eligibility is defined by consecutive observations at the declared daily cadence.
- Validation priming uses earlier observable rows without admitting training targets.
- Every saved epoch checkpoint remains available to the backtest stage.