# Temporal Convolutional Network - FX Pairs

A temporal convolutional network reads a fixed number of consecutive daily observations for each
currency pair. A missing daily observation invalidates every lookback window that crosses it. The
shared sequence runner derives that eligible endpoint grid, primes each validation fold only with
observable earlier rows, saves epoch checkpoints, and publishes predictions against the same grid.

**Learning objectives**

- Define one sequence-model request without rebuilding windows in the notebook.
- Inspect the cadence-aware eligibility and checkpoint identities recorded by the runner.
- Reload fitted weights and pass complete predictions through the shared catalog.

**Book reference**: Chapter 13, Sections 13.2 and 13.4

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published TCN FX configuration."""

import json

import polars as pl
import torch

from case_studies.research import (
    ExecutionTier,
    declared_labels,
    open_study,
    plan_models,
    population_supersedes,
    sweep_labels,
)
from utils.modeling import load_configs
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
LOOKBACK = 0
BATCH_SIZE = 0
DEVICE = ""
SEED = 42
POPULATION_NAME = ""
SUPERSEDES_POPULATION: str = "3cf95f3b150d"
# The tier is a parameter, not something inferred from whether a reduction happens to be set.
# Inferring it meant a run could be reduced and still open the case study's own artifacts in
# place, which is the production path; a reader under test then wrote where the published run
# writes. WORKSPACE is the other half: a preview has nowhere else to put its results.
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None

## Plan the sequence request

Fold and symbol reductions create a preview. Epochs, lookback length, and batch size are visible
model overrides: changing any of them creates a different training identity. Planning resolves
that identity, the eligible validation keys, and every declared epoch checkpoint before any
training starts.

In [3]:
set_global_seeds(SEED)
# The reductions are read before the study is opened, because which study to open is decided by
# the tier and the two have to agree: a preview that reduces nothing is a canonical run wearing
# the wrong tier, and a canonical run carrying reductions would publish a narrowed population
# under the canonical name.
REDUCTION_PARAMETERS = {
    "folds": list(range(MAX_FOLDS)) if MAX_FOLDS else None,
    "max_symbols": MAX_SYMBOLS or None,
}
reductions = {key: value for key, value in REDUCTION_PARAMETERS.items() if value is not None}
tier = ExecutionTier(EXECUTION_TIER)
if tier is ExecutionTier.PREVIEW and not reductions:
    raise ValueError("preview execution must declare at least one reduction")
if tier is ExecutionTier.CANONICAL and reductions:
    raise ValueError(f"canonical execution cannot carry reductions: {sorted(reductions)}")
study = open_study(CASE_STUDY_ID, execution_tier=tier, workspace=WORKSPACE or None)

# Which labels this notebook fits is a question for the training menus, not for the sweep list:
# `setup.yaml` says which labels the case study carries, a menu says what to fit for one of them,
# and a sweep label whose menu declares no `deep_learning:` section owes nothing here. The two
# agree in this case study today, so restating the sweep list produced the right answer by
# coincidence and would have kept producing it silently after a menu changed. The order stays
# `setup.yaml`'s rather than `declared_labels`' menu-file order because the population is named
# after its labels and hashed over its members as an ordered list, so re-ordering would give the
# published population a new identity and demand a supersedes for a run that fits the same models.
declared = declared_labels(study, "deep_learning")
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [label for label in sweep_labels(study) if label in set(declared)]
)

# A run that fits fewer labels than the menus declare is not the canonical population, and the
# architecture is fixed below, so the label set is the only knob that narrows it. Such a run must
# publish under its own name rather than register a partial snapshot under the canonical one.
if set(labels) != set(declared) and not POPULATION_NAME:
    raise ValueError(
        f"this run fits {len(labels)} of the {len(declared)} declared labels, so it cannot "
        "publish the canonical population; pass POPULATION_NAME to give it its own"
    )

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

# An empty DEVICE resolves to what the machine has. The runners refuse "cuda" on a host without
# it rather than falling back silently - which is the right contract for a run whose results get
# registered - so a hardcoded "cuda" default made the notebook unrunnable for any reader without
# an NVIDIA card, and unrunnable on a CPU CI runner. Resolving here keeps the refusal for anyone
# who asks for "cuda" explicitly; the resolved value is printed with the rest of the numerics
# below, so a run never leaves it implicit.
device = DEVICE or ("cuda" if torch.cuda.is_available() else "cpu")
overrides = {
    "device": device,
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
    **({"lookback": LOOKBACK} if LOOKBACK else {}),
}
ARCHITECTURE = "tcn"
menu = {
    label: [
        config["config_name"]
        for config in load_configs(CASE_STUDY_ID, label, family="deep_learning")
    ]
    for label in labels
}
uncovered = {label: sorted(set(names) - {ARCHITECTURE}) for label, names in menu.items()}
for label, names in menu.items():
    if ARCHITECTURE not in names:
        raise RuntimeError(
            f"{ARCHITECTURE} is not in the configured deep_learning menu for {label}: {names}"
        )

requests = [
    study.model(
        family="deep_learning",
        label=label,
        config_name=ARCHITECTURE,
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label in labels
]
plan = plan_models(study, requests=requests)

# This notebook owes one architecture on every configured label. The rest of the family menu is
# named here rather than left implicit, because a population that is short a configured model is
# otherwise indistinguishable from a complete one.
configured = {(label, ARCHITECTURE) for label in labels}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        f"the plan does not match this notebook's declared coverage; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )
specs = {member.label: json.loads(member.spec_json) for member in plan.members}
computations = {label: spec.get("computation", spec) for label, spec in specs.items()}
computation = computations[labels[0]]

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {computation['numerics']['device']}")
print(f"Lookback: {computation['preprocessing']['lookback']} consecutive daily observations")
for horizon, values in computations.items():
    print(f"Eligible validation rows, {horizon}: {values['expected_prediction_keys']['n_rows']:,}")
for horizon, names in uncovered.items():
    print(
        f"Configured deep_learning models this notebook does not run, {horizon}: {names or 'none'}"
    )

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda
Lookback: 60 consecutive daily observations
Eligible validation rows, fwd_ret_1d: 41,260
Eligible validation rows, fwd_ret_5d: 41,180
Eligible validation rows, fwd_ret_21d: 40,860
Configured deep_learning models this notebook does not run, fwd_ret_1d: ['lstm_h64', 'nlinear']
Configured deep_learning models this notebook does not run, fwd_ret_5d: ['lstm_h64', 'nlinear']
Configured deep_learning models this notebook does not run, fwd_ret_21d: ['lstm_h64', 'nlinear']

## Inspect the declared checkpoints and gap policy

The resolved request records exact validation keys and the rule that excludes windows crossing a
missing expected day. Checkpoint values below are training epochs, not IC-selected summaries.

In [4]:
checkpoint_schedule = pl.DataFrame(computation["checkpoint_schedule"])
input_summary = pl.DataFrame(
    {
        "label": list(computations),
        "gap_policy": [c["preprocessing"]["gap_policy"] for c in computations.values()],
        "validation_folds": [
            c["expected_prediction_keys"]["n_folds"] for c in computations.values()
        ],
        "validation_rows": [c["expected_prediction_keys"]["n_rows"] for c in computations.values()],
        "key_digest": [c["expected_prediction_keys"]["digest"] for c in computations.values()],
    }
)
input_summary
checkpoint_schedule

shape: (20, 2)
┌───────┬───────┐
│ kind  ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ epoch ┆ 5     │
│ epoch ┆ 10    │
│ epoch ┆ 15    │
│ epoch ┆ 20    │
│ epoch ┆ 25    │
│ …     ┆ …     │
│ epoch ┆ 80    │
│ epoch ┆ 85    │
│ epoch ┆ 90    │
│ epoch ┆ 95    │
│ epoch ┆ 100   │
└───────┴───────┘

## Record the official population, then fit or reload the TCN

The same resolved request is used by the notebook and direct Python callers. Publication fails if
any fold is missing, any prediction is non-finite, or the prediction keys differ from eligibility.

`SUPERSEDES_POPULATION` names the population hash this run replaces. A population is the set of
prediction identities it publishes, so anything that moves a training identity produces a
different population under the same name, and the registry refuses to write it without being
told which snapshot it supersedes. That lineage is the only record of which generation is which,
and what moved the identities here was a change to the family's own source file rather than to
anything the notebook declares.

`population_supersedes` decides whether the declared hash may be offered. It is offered when the
name already carries the generation this declaration produced, so a re-run resolves to the
population it published, and when the declaration names the generation in force, so a refit
publishes the next one. It is withheld everywhere else - on a reader's clean clone, where
`run_log/` is gitignored and the registry has no generation at all; under a caller's own
`POPULATION_NAME`; and in a preview, whose isolated registry holds nothing under this name.

In [5]:
if len(plan.expected_prediction_hashes) != checkpoint_schedule.height * len(labels):
    raise RuntimeError("the plan does not cover every declared epoch checkpoint on every label")
population_name = POPULATION_NAME or f"{CASE_STUDY_ID}:{'+'.join(labels)}:tcn"
population = (
    plan.create_population(
        name=population_name,
        supersedes=population_supersedes(
            study, name=population_name, declared=SUPERSEDES_POPULATION
        ),
    )
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
catalog = execution.catalog_rows.sort("label", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial TCN checkpoints cannot pass to backtesting")
for label in labels:
    published = catalog.filter(pl.col("label") == label).get_column("checkpoint_value").to_list()
    if published != checkpoint_schedule["value"].to_list():
        raise RuntimeError(f"catalog checkpoints for {label} differ from the resolved request")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=17,060 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.047384

      epoch   2/100: train_loss=0.005767

      epoch   3/100: train_loss=0.002923

      epoch   4/100: train_loss=0.002182

      epoch   5/100: train_loss=0.001709, val_loss=0.002139, IC=-0.0009

      epoch   6/100: train_loss=0.001533

      epoch   7/100: train_loss=0.001427

      epoch   8/100: train_loss=0.001343

      epoch   9/100: train_loss=0.001299

      epoch  10/100: train_loss=0.001243, val_loss=0.002093, IC=+0.0051

      epoch  11/100: train_loss=0.001221

      epoch  12/100: train_loss=0.001177

      epoch  13/100: train_loss=0.001111

      epoch  14/100: train_loss=0.001102

      epoch  15/100: train_loss=0.001068, val_loss=0.001971, IC=+0.0103

      epoch  16/100: train_loss=0.001043

      epoch  17/100: train_loss=0.000983

      epoch  18/100: train_loss=0.000930

      epoch  19/100: train_loss=0.000932

      epoch  20/100: train_loss=0.000913, val_loss=0.000884, IC=+0.0135

      epoch  21/100: train_loss=0.000867

      epoch  22/100: train_loss=0.000839

      epoch  23/100: train_loss=0.000812

      epoch  24/100: train_loss=0.000842

      epoch  25/100: train_loss=0.000771, val_loss=0.001011, IC=+0.0127

      epoch  26/100: train_loss=0.000807

      epoch  27/100: train_loss=0.000781

      epoch  28/100: train_loss=0.000752

      epoch  29/100: train_loss=0.000781

      epoch  30/100: train_loss=0.000714, val_loss=0.000646, IC=+0.0183

      epoch  31/100: train_loss=0.000740

      epoch  32/100: train_loss=0.000666

      epoch  33/100: train_loss=0.000670

      epoch  34/100: train_loss=0.000683

      epoch  35/100: train_loss=0.000673, val_loss=0.000468, IC=+0.0090

      epoch  36/100: train_loss=0.000671

      epoch  37/100: train_loss=0.000651

      epoch  38/100: train_loss=0.000632

      epoch  39/100: train_loss=0.000640

      epoch  40/100: train_loss=0.000615, val_loss=0.000448, IC=+0.0200

      epoch  41/100: train_loss=0.000589

      epoch  42/100: train_loss=0.000570

      epoch  43/100: train_loss=0.000582

      epoch  44/100: train_loss=0.000594

      epoch  45/100: train_loss=0.000586, val_loss=0.000469, IC=+0.0193

      epoch  46/100: train_loss=0.000564

      epoch  47/100: train_loss=0.000559

      epoch  48/100: train_loss=0.000537

      epoch  49/100: train_loss=0.000546

      epoch  50/100: train_loss=0.000539, val_loss=0.000562, IC=+0.0219

      epoch  51/100: train_loss=0.000511

      epoch  52/100: train_loss=0.000502

      epoch  53/100: train_loss=0.000512

      epoch  54/100: train_loss=0.000517

      epoch  55/100: train_loss=0.000537, val_loss=0.000820, IC=+0.0156

      epoch  56/100: train_loss=0.000520

      epoch  57/100: train_loss=0.000500

      epoch  58/100: train_loss=0.000455

      epoch  59/100: train_loss=0.000452

      epoch  60/100: train_loss=0.000509, val_loss=0.000709, IC=+0.0158

      epoch  61/100: train_loss=0.000460

      epoch  62/100: train_loss=0.000468

      epoch  63/100: train_loss=0.000472

      epoch  64/100: train_loss=0.000487

      epoch  65/100: train_loss=0.000459, val_loss=0.000439, IC=+0.0205

      epoch  66/100: train_loss=0.000443

      epoch  67/100: train_loss=0.000452

      epoch  68/100: train_loss=0.000434

      epoch  69/100: train_loss=0.000436

      epoch  70/100: train_loss=0.000436, val_loss=0.000441, IC=+0.0246

      epoch  71/100: train_loss=0.000441

      epoch  72/100: train_loss=0.000455

      epoch  73/100: train_loss=0.000437

      epoch  74/100: train_loss=0.000431

      epoch  75/100: train_loss=0.000457, val_loss=0.000480, IC=+0.0271

      epoch  76/100: train_loss=0.000429

      epoch  77/100: train_loss=0.000422

      epoch  78/100: train_loss=0.000422

      epoch  79/100: train_loss=0.000434

      epoch  80/100: train_loss=0.000417, val_loss=0.000458, IC=+0.0214

      epoch  81/100: train_loss=0.000420

      epoch  82/100: train_loss=0.000407

      epoch  83/100: train_loss=0.000427

      epoch  84/100: train_loss=0.000422

      epoch  85/100: train_loss=0.000433, val_loss=0.000636, IC=+0.0213

      epoch  86/100: train_loss=0.000433

      epoch  87/100: train_loss=0.000405

      epoch  88/100: train_loss=0.000412

      epoch  89/100: train_loss=0.000400

      epoch  90/100: train_loss=0.000409, val_loss=0.000454, IC=+0.0241

      epoch  91/100: train_loss=0.000402

      epoch  92/100: train_loss=0.000403

      epoch  93/100: train_loss=0.000409

      epoch  94/100: train_loss=0.000410

      epoch  95/100: train_loss=0.000398, val_loss=0.000438, IC=+0.0266

      epoch  96/100: train_loss=0.000409

      epoch  97/100: train_loss=0.000414

      epoch  98/100: train_loss=0.000410

      epoch  99/100: train_loss=0.000397

      epoch 100/100: train_loss=0.000422, val_loss=0.000435, IC=+0.0265

      best_ep=75, IC=+0.0271 (57.0s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,220 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.034882

      epoch   2/100: train_loss=0.004426

      epoch   3/100: train_loss=0.002662

      epoch   4/100: train_loss=0.002199

      epoch   5/100: train_loss=0.001879, val_loss=0.001408, IC=+0.0560

      epoch   6/100: train_loss=0.001678

      epoch   7/100: train_loss=0.001559

      epoch   8/100: train_loss=0.001559

      epoch   9/100: train_loss=0.001432

      epoch  10/100: train_loss=0.001402, val_loss=0.000677, IC=+0.0460

      epoch  11/100: train_loss=0.001287

      epoch  12/100: train_loss=0.001314

      epoch  13/100: train_loss=0.001218

      epoch  14/100: train_loss=0.001235

      epoch  15/100: train_loss=0.001131, val_loss=0.000485, IC=+0.0310

      epoch  16/100: train_loss=0.001116

      epoch  17/100: train_loss=0.001095

      epoch  18/100: train_loss=0.001086

      epoch  19/100: train_loss=0.001160

      epoch  20/100: train_loss=0.001156, val_loss=0.000486, IC=+0.0336

      epoch  21/100: train_loss=0.000917

      epoch  22/100: train_loss=0.000904

      epoch  23/100: train_loss=0.000939

      epoch  24/100: train_loss=0.000895

      epoch  25/100: train_loss=0.000898, val_loss=0.000379, IC=+0.0228

      epoch  26/100: train_loss=0.000833

      epoch  27/100: train_loss=0.000852

      epoch  28/100: train_loss=0.000799

      epoch  29/100: train_loss=0.000752

      epoch  30/100: train_loss=0.000790, val_loss=0.000393, IC=+0.0256

      epoch  31/100: train_loss=0.000883

      epoch  32/100: train_loss=0.000750

      epoch  33/100: train_loss=0.000721

      epoch  34/100: train_loss=0.000750

      epoch  35/100: train_loss=0.000751, val_loss=0.000264, IC=+0.0236

      epoch  36/100: train_loss=0.000717

      epoch  37/100: train_loss=0.000733

      epoch  38/100: train_loss=0.000794

      epoch  39/100: train_loss=0.000789

      epoch  40/100: train_loss=0.000707, val_loss=0.000211, IC=+0.0227

      epoch  41/100: train_loss=0.000697

      epoch  42/100: train_loss=0.000709

      epoch  43/100: train_loss=0.000662

      epoch  44/100: train_loss=0.000639

      epoch  45/100: train_loss=0.000631, val_loss=0.000209, IC=+0.0191

      epoch  46/100: train_loss=0.000648

      epoch  47/100: train_loss=0.000626

      epoch  48/100: train_loss=0.000621

      epoch  49/100: train_loss=0.000595

      epoch  50/100: train_loss=0.000574, val_loss=0.000203, IC=+0.0245

      epoch  51/100: train_loss=0.000580

      epoch  52/100: train_loss=0.000590

      epoch  53/100: train_loss=0.000556

      epoch  54/100: train_loss=0.000583

      epoch  55/100: train_loss=0.000588, val_loss=0.000170, IC=+0.0171

      epoch  56/100: train_loss=0.000587

      epoch  57/100: train_loss=0.000563

      epoch  58/100: train_loss=0.000572

      epoch  59/100: train_loss=0.000594

      epoch  60/100: train_loss=0.000540, val_loss=0.000237, IC=+0.0239

      epoch  61/100: train_loss=0.000539

      epoch  62/100: train_loss=0.000539

      epoch  63/100: train_loss=0.000547

      epoch  64/100: train_loss=0.000508

      epoch  65/100: train_loss=0.000522, val_loss=0.000164, IC=+0.0222

      epoch  66/100: train_loss=0.000519

      epoch  67/100: train_loss=0.000518

      epoch  68/100: train_loss=0.000494

      epoch  69/100: train_loss=0.000515

      epoch  70/100: train_loss=0.000535, val_loss=0.000162, IC=+0.0229

      epoch  71/100: train_loss=0.000520

      epoch  72/100: train_loss=0.000511

      epoch  73/100: train_loss=0.000492

      epoch  74/100: train_loss=0.000509

      epoch  75/100: train_loss=0.000493, val_loss=0.000181, IC=+0.0203

      epoch  76/100: train_loss=0.000494

      epoch  77/100: train_loss=0.000493

      epoch  78/100: train_loss=0.000515

      epoch  79/100: train_loss=0.000486

      epoch  80/100: train_loss=0.000494, val_loss=0.000174, IC=+0.0210

      epoch  81/100: train_loss=0.000484

      epoch  82/100: train_loss=0.000488

      epoch  83/100: train_loss=0.000492

      epoch  84/100: train_loss=0.000498

      epoch  85/100: train_loss=0.000496, val_loss=0.000175, IC=+0.0193

      epoch  86/100: train_loss=0.000488

      epoch  87/100: train_loss=0.000481

      epoch  88/100: train_loss=0.000507

      epoch  89/100: train_loss=0.000469

      epoch  90/100: train_loss=0.000488, val_loss=0.000156, IC=+0.0180

      epoch  91/100: train_loss=0.000476

      epoch  92/100: train_loss=0.000473

      epoch  93/100: train_loss=0.000472

      epoch  94/100: train_loss=0.000479

      epoch  95/100: train_loss=0.000473, val_loss=0.000149, IC=+0.0202

      epoch  96/100: train_loss=0.000478

      epoch  97/100: train_loss=0.000473

      epoch  98/100: train_loss=0.000468

      epoch  99/100: train_loss=0.000465

      epoch 100/100: train_loss=0.000462, val_loss=0.000146, IC=+0.0191

      best_ep=5, IC=+0.0560 (70.6s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.021726

      epoch   2/100: train_loss=0.004122

      epoch   3/100: train_loss=0.002579

      epoch   4/100: train_loss=0.002389

      epoch   5/100: train_loss=0.002831, val_loss=0.002656, IC=-0.0255

      epoch   6/100: train_loss=0.002351

      epoch   7/100: train_loss=0.002489

      epoch   8/100: train_loss=0.001846

      epoch   9/100: train_loss=0.001402

      epoch  10/100: train_loss=0.001318, val_loss=0.001481, IC=+0.0007

      epoch  11/100: train_loss=0.001510

      epoch  12/100: train_loss=0.001507

      epoch  13/100: train_loss=0.001137

      epoch  14/100: train_loss=0.001046

      epoch  15/100: train_loss=0.000926, val_loss=0.000671, IC=-0.0287

      epoch  16/100: train_loss=0.000933

      epoch  17/100: train_loss=0.000996

      epoch  18/100: train_loss=0.001260

      epoch  19/100: train_loss=0.001040

      epoch  20/100: train_loss=0.001031, val_loss=0.000432, IC=-0.0175

      epoch  21/100: train_loss=0.001164

      epoch  22/100: train_loss=0.000992

      epoch  23/100: train_loss=0.000985

      epoch  24/100: train_loss=0.000985

      epoch  25/100: train_loss=0.000843, val_loss=0.000439, IC=-0.0261

      epoch  26/100: train_loss=0.001036

      epoch  27/100: train_loss=0.001254

      epoch  28/100: train_loss=0.001279

      epoch  29/100: train_loss=0.001841

      epoch  30/100: train_loss=0.001387, val_loss=0.000543, IC=-0.0085

      epoch  31/100: train_loss=0.000970

      epoch  32/100: train_loss=0.000760

      epoch  33/100: train_loss=0.000719

      epoch  34/100: train_loss=0.000658

      epoch  35/100: train_loss=0.000785, val_loss=0.000281, IC=-0.0228

      epoch  36/100: train_loss=0.000862

      epoch  37/100: train_loss=0.000849

      epoch  38/100: train_loss=0.002535

      epoch  39/100: train_loss=0.000790

      epoch  40/100: train_loss=0.000999, val_loss=0.000668, IC=-0.0339

      epoch  41/100: train_loss=0.001056

      epoch  42/100: train_loss=0.001193

      epoch  43/100: train_loss=0.000840

      epoch  44/100: train_loss=0.000898

      epoch  45/100: train_loss=0.000610, val_loss=0.000240, IC=-0.0344

      epoch  46/100: train_loss=0.000728

      epoch  47/100: train_loss=0.000708

      epoch  48/100: train_loss=0.000568

      epoch  49/100: train_loss=0.000558

      epoch  50/100: train_loss=0.000500, val_loss=0.000190, IC=-0.0218

      epoch  51/100: train_loss=0.000499

      epoch  52/100: train_loss=0.000700

      epoch  53/100: train_loss=0.000811

      epoch  54/100: train_loss=0.000746

      epoch  55/100: train_loss=0.001259, val_loss=0.000194, IC=-0.0207

      epoch  56/100: train_loss=0.000704

      epoch  57/100: train_loss=0.000519

      epoch  58/100: train_loss=0.000523

      epoch  59/100: train_loss=0.000702

      epoch  60/100: train_loss=0.000594, val_loss=0.000177, IC=-0.0005

      epoch  61/100: train_loss=0.000796

      epoch  62/100: train_loss=0.000615

      epoch  63/100: train_loss=0.000498

      epoch  64/100: train_loss=0.000582

      epoch  65/100: train_loss=0.000631, val_loss=0.000187, IC=-0.0209

      epoch  66/100: train_loss=0.000590

      epoch  67/100: train_loss=0.000486

      epoch  68/100: train_loss=0.001021

      epoch  69/100: train_loss=0.000941

      epoch  70/100: train_loss=0.000530, val_loss=0.000207, IC=-0.0177

      epoch  71/100: train_loss=0.000480

      epoch  72/100: train_loss=0.000480

      epoch  73/100: train_loss=0.000468

      epoch  74/100: train_loss=0.000510

      epoch  75/100: train_loss=0.000490, val_loss=0.000148, IC=-0.0239

      epoch  76/100: train_loss=0.000433

      epoch  77/100: train_loss=0.000451

      epoch  78/100: train_loss=0.000508

      epoch  79/100: train_loss=0.001047

      epoch  80/100: train_loss=0.000496, val_loss=0.000168, IC=-0.0078

      epoch  81/100: train_loss=0.000849

      epoch  82/100: train_loss=0.000453

      epoch  83/100: train_loss=0.000430

      epoch  84/100: train_loss=0.000453

      epoch  85/100: train_loss=0.000580, val_loss=0.000150, IC=-0.0133

      epoch  86/100: train_loss=0.000484

      epoch  87/100: train_loss=0.000484

      epoch  88/100: train_loss=0.000505

      epoch  89/100: train_loss=0.000505

      epoch  90/100: train_loss=0.000468, val_loss=0.000165, IC=-0.0174

      epoch  91/100: train_loss=0.000403

      epoch  92/100: train_loss=0.000488

      epoch  93/100: train_loss=0.000695

      epoch  94/100: train_loss=0.000599

      epoch  95/100: train_loss=0.000708, val_loss=0.000165, IC=-0.0122

      epoch  96/100: train_loss=0.000488

      epoch  97/100: train_loss=0.000393

      epoch  98/100: train_loss=0.000419

      epoch  99/100: train_loss=0.000593

      epoch 100/100: train_loss=0.000410, val_loss=0.000139, IC=-0.0126

      best_ep=10, IC=+0.0007 (76.7s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.076981

      epoch   2/100: train_loss=0.005584

      epoch   3/100: train_loss=0.003774

      epoch   4/100: train_loss=0.002634

      epoch   5/100: train_loss=0.002240, val_loss=0.001462, IC=-0.0006

      epoch   6/100: train_loss=0.002084

      epoch   7/100: train_loss=0.002515

      epoch   8/100: train_loss=0.002340

      epoch   9/100: train_loss=0.003822

      epoch  10/100: train_loss=0.002831, val_loss=0.000982, IC=+0.0245

      epoch  11/100: train_loss=0.002092

      epoch  12/100: train_loss=0.002047

      epoch  13/100: train_loss=0.002220

      epoch  14/100: train_loss=0.002350

      epoch  15/100: train_loss=0.001793, val_loss=0.000832, IC=+0.0362

      epoch  16/100: train_loss=0.001483

      epoch  17/100: train_loss=0.001560

      epoch  18/100: train_loss=0.002271

      epoch  19/100: train_loss=0.001424

      epoch  20/100: train_loss=0.001485, val_loss=0.000529, IC=+0.0327

      epoch  21/100: train_loss=0.002298

      epoch  22/100: train_loss=0.001943

      epoch  23/100: train_loss=0.002335

      epoch  24/100: train_loss=0.002154

      epoch  25/100: train_loss=0.001430, val_loss=0.001762, IC=+0.0095

      epoch  26/100: train_loss=0.001461

      epoch  27/100: train_loss=0.001237

      epoch  28/100: train_loss=0.001732

      epoch  29/100: train_loss=0.001409

      epoch  30/100: train_loss=0.001081, val_loss=0.000618, IC=-0.0073

      epoch  31/100: train_loss=0.000961

      epoch  32/100: train_loss=0.000922

      epoch  33/100: train_loss=0.000924

      epoch  34/100: train_loss=0.000937

      epoch  35/100: train_loss=0.001456, val_loss=0.000377, IC=+0.0253

      epoch  36/100: train_loss=0.001346

      epoch  37/100: train_loss=0.001185

      epoch  38/100: train_loss=0.001197

      epoch  39/100: train_loss=0.002348

      epoch  40/100: train_loss=0.001253, val_loss=0.000469, IC=+0.0137

      epoch  41/100: train_loss=0.001005

      epoch  42/100: train_loss=0.001274

      epoch  43/100: train_loss=0.000962

      epoch  44/100: train_loss=0.001231

      epoch  45/100: train_loss=0.002283, val_loss=0.000258, IC=+0.0087

      epoch  46/100: train_loss=0.001223

      epoch  47/100: train_loss=0.001135

      epoch  48/100: train_loss=0.001034

      epoch  49/100: train_loss=0.001345

      epoch  50/100: train_loss=0.000991, val_loss=0.000398, IC=-0.0002

      epoch  51/100: train_loss=0.001213

      epoch  52/100: train_loss=0.002896

      epoch  53/100: train_loss=0.000976

      epoch  54/100: train_loss=0.001154

      epoch  55/100: train_loss=0.000911, val_loss=0.000185, IC=-0.0110

      epoch  56/100: train_loss=0.001047

      epoch  57/100: train_loss=0.001266

      epoch  58/100: train_loss=0.002702

      epoch  59/100: train_loss=0.001059

      epoch  60/100: train_loss=0.000819, val_loss=0.000284, IC=-0.0035

      epoch  61/100: train_loss=0.001672

      epoch  62/100: train_loss=0.000759

      epoch  63/100: train_loss=0.000795

      epoch  64/100: train_loss=0.001000

      epoch  65/100: train_loss=0.001167, val_loss=0.000175, IC=-0.0059

      epoch  66/100: train_loss=0.000699

      epoch  67/100: train_loss=0.000851

      epoch  68/100: train_loss=0.000828

      epoch  69/100: train_loss=0.000853

      epoch  70/100: train_loss=0.000705, val_loss=0.000464, IC=+0.0009

      epoch  71/100: train_loss=0.000591

      epoch  72/100: train_loss=0.000807

      epoch  73/100: train_loss=0.000742

      epoch  74/100: train_loss=0.000846

      epoch  75/100: train_loss=0.000658, val_loss=0.000221, IC=+0.0010

      epoch  76/100: train_loss=0.000587

      epoch  77/100: train_loss=0.000898

      epoch  78/100: train_loss=0.000772

      epoch  79/100: train_loss=0.000656

      epoch  80/100: train_loss=0.000657, val_loss=0.000184, IC=-0.0081

      epoch  81/100: train_loss=0.001674

      epoch  82/100: train_loss=0.000830

      epoch  83/100: train_loss=0.000985

      epoch  84/100: train_loss=0.000632

      epoch  85/100: train_loss=0.000560, val_loss=0.000339, IC=-0.0044

      epoch  86/100: train_loss=0.000586

      epoch  87/100: train_loss=0.000551

      epoch  88/100: train_loss=0.000551

      epoch  89/100: train_loss=0.000658

      epoch  90/100: train_loss=0.000752, val_loss=0.000147, IC=-0.0050

      epoch  91/100: train_loss=0.000581

      epoch  92/100: train_loss=0.000654

      epoch  93/100: train_loss=0.001148

      epoch  94/100: train_loss=0.000569

      epoch  95/100: train_loss=0.000564, val_loss=0.000139, IC=-0.0070

      epoch  96/100: train_loss=0.000888

      epoch  97/100: train_loss=0.000664

      epoch  98/100: train_loss=0.000589

      epoch  99/100: train_loss=0.000659

      epoch 100/100: train_loss=0.000653, val_loss=0.000138, IC=-0.0062

      best_ep=15, IC=+0.0362 (80.9s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.186689

      epoch   2/100: train_loss=0.006591

      epoch   3/100: train_loss=0.002756

      epoch   4/100: train_loss=0.002537

      epoch   5/100: train_loss=0.002680, val_loss=0.002722, IC=+0.0175

      epoch   6/100: train_loss=0.002191

      epoch   7/100: train_loss=0.002077

      epoch   8/100: train_loss=0.002101

      epoch   9/100: train_loss=0.003221

      epoch  10/100: train_loss=0.001603, val_loss=0.002101, IC=+0.0231

      epoch  11/100: train_loss=0.001380

      epoch  12/100: train_loss=0.001619

      epoch  13/100: train_loss=0.001844

      epoch  14/100: train_loss=0.001970

      epoch  15/100: train_loss=0.001489, val_loss=0.005476, IC=-0.0451

      epoch  16/100: train_loss=0.002867

      epoch  17/100: train_loss=0.002092

      epoch  18/100: train_loss=0.001199

      epoch  19/100: train_loss=0.000972

      epoch  20/100: train_loss=0.001625, val_loss=0.001013, IC=+0.0226

      epoch  21/100: train_loss=0.001145

      epoch  22/100: train_loss=0.001225

      epoch  23/100: train_loss=0.001106

      epoch  24/100: train_loss=0.001352

      epoch  25/100: train_loss=0.001105, val_loss=0.000892, IC=-0.0210

      epoch  26/100: train_loss=0.000874

      epoch  27/100: train_loss=0.000767

      epoch  28/100: train_loss=0.001294

      epoch  29/100: train_loss=0.001096

      epoch  30/100: train_loss=0.001213, val_loss=0.000634, IC=-0.0101

      epoch  31/100: train_loss=0.001499

      epoch  32/100: train_loss=0.000977

      epoch  33/100: train_loss=0.000773

      epoch  34/100: train_loss=0.000578

      epoch  35/100: train_loss=0.001150, val_loss=0.000485, IC=+0.0214

      epoch  36/100: train_loss=0.001216

      epoch  37/100: train_loss=0.000994

      epoch  38/100: train_loss=0.000749

      epoch  39/100: train_loss=0.001728

      epoch  40/100: train_loss=0.000878, val_loss=0.000957, IC=+0.0133

      epoch  41/100: train_loss=0.001102

      epoch  42/100: train_loss=0.000677

      epoch  43/100: train_loss=0.000609

      epoch  44/100: train_loss=0.000535

      epoch  45/100: train_loss=0.000731, val_loss=0.000446, IC=-0.0050

      epoch  46/100: train_loss=0.000724

      epoch  47/100: train_loss=0.000634

      epoch  48/100: train_loss=0.000712

      epoch  49/100: train_loss=0.000840

      epoch  50/100: train_loss=0.000635, val_loss=0.001281, IC=+0.0039

      epoch  51/100: train_loss=0.000583

      epoch  52/100: train_loss=0.000502

      epoch  53/100: train_loss=0.000792

      epoch  54/100: train_loss=0.000699

      epoch  55/100: train_loss=0.000785, val_loss=0.000971, IC=+0.0240

      epoch  56/100: train_loss=0.000934

      epoch  57/100: train_loss=0.000786

      epoch  58/100: train_loss=0.000673

      epoch  59/100: train_loss=0.000629

      epoch  60/100: train_loss=0.000746, val_loss=0.000586, IC=+0.0160

      epoch  61/100: train_loss=0.000630

      epoch  62/100: train_loss=0.000530

      epoch  63/100: train_loss=0.000442

      epoch  64/100: train_loss=0.000516

      epoch  65/100: train_loss=0.000561, val_loss=0.000405, IC=+0.0141

      epoch  66/100: train_loss=0.000500

      epoch  67/100: train_loss=0.000446

      epoch  68/100: train_loss=0.000579

      epoch  69/100: train_loss=0.000584

      epoch  70/100: train_loss=0.000619, val_loss=0.000395, IC=+0.0291

      epoch  71/100: train_loss=0.000466

      epoch  72/100: train_loss=0.000422

      epoch  73/100: train_loss=0.000398

      epoch  74/100: train_loss=0.000430

      epoch  75/100: train_loss=0.000428, val_loss=0.000334, IC=+0.0347

      epoch  76/100: train_loss=0.000568

      epoch  77/100: train_loss=0.000496

      epoch  78/100: train_loss=0.000526

      epoch  79/100: train_loss=0.000461

      epoch  80/100: train_loss=0.000449, val_loss=0.000296, IC=+0.0316

      epoch  81/100: train_loss=0.000402

      epoch  82/100: train_loss=0.000630

      epoch  83/100: train_loss=0.000872

      epoch  84/100: train_loss=0.000418

      epoch  85/100: train_loss=0.000413, val_loss=0.000438, IC=+0.0273

      epoch  86/100: train_loss=0.000390

      epoch  87/100: train_loss=0.000420

      epoch  88/100: train_loss=0.000405

      epoch  89/100: train_loss=0.000421

      epoch  90/100: train_loss=0.000401, val_loss=0.000324, IC=+0.0287

      epoch  91/100: train_loss=0.000476

      epoch  92/100: train_loss=0.000413

      epoch  93/100: train_loss=0.000450

      epoch  94/100: train_loss=0.000371

      epoch  95/100: train_loss=0.000918, val_loss=0.000365, IC=+0.0342

      epoch  96/100: train_loss=0.000624

      epoch  97/100: train_loss=0.000420

      epoch  98/100: train_loss=0.000386

      epoch  99/100: train_loss=0.000464

      epoch 100/100: train_loss=0.000438, val_loss=0.000269, IC=+0.0301

      best_ep=75, IC=+0.0347 (81.6s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.496207

      epoch   2/100: train_loss=0.014786

      epoch   3/100: train_loss=0.005512

      epoch   4/100: train_loss=0.004649

      epoch   5/100: train_loss=0.003167, val_loss=0.001313, IC=+0.0079

      epoch   6/100: train_loss=0.001479

      epoch   7/100: train_loss=0.001461

      epoch   8/100: train_loss=0.002504

      epoch   9/100: train_loss=0.002254

      epoch  10/100: train_loss=0.001339, val_loss=0.000818, IC=+0.0211

      epoch  11/100: train_loss=0.003658

      epoch  12/100: train_loss=0.001942

      epoch  13/100: train_loss=0.001211

      epoch  14/100: train_loss=0.001257

      epoch  15/100: train_loss=0.002428, val_loss=0.000665, IC=+0.0117

      epoch  16/100: train_loss=0.001218

      epoch  17/100: train_loss=0.001402

      epoch  18/100: train_loss=0.001293

      epoch  19/100: train_loss=0.001114

      epoch  20/100: train_loss=0.001219, val_loss=0.000617, IC=+0.0052

      epoch  21/100: train_loss=0.002562

      epoch  22/100: train_loss=0.002083

      epoch  23/100: train_loss=0.001864

      epoch  24/100: train_loss=0.001859

      epoch  25/100: train_loss=0.001337, val_loss=0.000313, IC=+0.0196

      epoch  26/100: train_loss=0.001063

      epoch  27/100: train_loss=0.000777

      epoch  28/100: train_loss=0.000921

      epoch  29/100: train_loss=0.001167

      epoch  30/100: train_loss=0.001560, val_loss=0.000295, IC=+0.0112

      epoch  31/100: train_loss=0.001342

      epoch  32/100: train_loss=0.000971

      epoch  33/100: train_loss=0.001059

      epoch  34/100: train_loss=0.001427

      epoch  35/100: train_loss=0.000842, val_loss=0.000231, IC=+0.0196

      epoch  36/100: train_loss=0.001068

      epoch  37/100: train_loss=0.000892

      epoch  38/100: train_loss=0.001014

      epoch  39/100: train_loss=0.001215

      epoch  40/100: train_loss=0.001130, val_loss=0.000211, IC=+0.0127

      epoch  41/100: train_loss=0.001454

      epoch  42/100: train_loss=0.000836

      epoch  43/100: train_loss=0.001586

      epoch  44/100: train_loss=0.000638

      epoch  45/100: train_loss=0.000818, val_loss=0.000194, IC=+0.0153

      epoch  46/100: train_loss=0.000904

      epoch  47/100: train_loss=0.000865

      epoch  48/100: train_loss=0.000812

      epoch  49/100: train_loss=0.000686

      epoch  50/100: train_loss=0.000871, val_loss=0.000222, IC=+0.0240

      epoch  51/100: train_loss=0.001111

      epoch  52/100: train_loss=0.000944

      epoch  53/100: train_loss=0.000587

      epoch  54/100: train_loss=0.000575

      epoch  55/100: train_loss=0.000546, val_loss=0.000143, IC=+0.0184

      epoch  56/100: train_loss=0.000569

      epoch  57/100: train_loss=0.000540

      epoch  58/100: train_loss=0.000534

      epoch  59/100: train_loss=0.000616

      epoch  60/100: train_loss=0.000655, val_loss=0.000212, IC=+0.0146

      epoch  61/100: train_loss=0.000621

      epoch  62/100: train_loss=0.000601

      epoch  63/100: train_loss=0.000862

      epoch  64/100: train_loss=0.000565

      epoch  65/100: train_loss=0.000522, val_loss=0.000153, IC=+0.0168

      epoch  66/100: train_loss=0.000455

      epoch  67/100: train_loss=0.000655

      epoch  68/100: train_loss=0.000714

      epoch  69/100: train_loss=0.000522

      epoch  70/100: train_loss=0.000654, val_loss=0.000151, IC=+0.0189

      epoch  71/100: train_loss=0.000550

      epoch  72/100: train_loss=0.000533

      epoch  73/100: train_loss=0.000438

      epoch  74/100: train_loss=0.000591

      epoch  75/100: train_loss=0.000537, val_loss=0.000141, IC=+0.0297

      epoch  76/100: train_loss=0.000496

      epoch  77/100: train_loss=0.000466

      epoch  78/100: train_loss=0.000505

      epoch  79/100: train_loss=0.000571

      epoch  80/100: train_loss=0.000918, val_loss=0.000164, IC=+0.0319

      epoch  81/100: train_loss=0.000535

      epoch  82/100: train_loss=0.000555

      epoch  83/100: train_loss=0.000494

      epoch  84/100: train_loss=0.000495

      epoch  85/100: train_loss=0.000474, val_loss=0.000150, IC=+0.0291

      epoch  86/100: train_loss=0.000458

      epoch  87/100: train_loss=0.000881

      epoch  88/100: train_loss=0.000436

      epoch  89/100: train_loss=0.000400

      epoch  90/100: train_loss=0.000506, val_loss=0.000140, IC=+0.0318

      epoch  91/100: train_loss=0.000585

      epoch  92/100: train_loss=0.000456

      epoch  93/100: train_loss=0.000402

      epoch  94/100: train_loss=0.000995

      epoch  95/100: train_loss=0.000467, val_loss=0.000138, IC=+0.0279

      epoch  96/100: train_loss=0.000462

      epoch  97/100: train_loss=0.000629

      epoch  98/100: train_loss=0.000446

      epoch  99/100: train_loss=0.000432

      epoch 100/100: train_loss=0.000587, val_loss=0.000139, IC=+0.0311

      best_ep=80, IC=+0.0319 (78.7s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.040427

      epoch   2/100: train_loss=0.004937

      epoch   3/100: train_loss=0.003759

      epoch   4/100: train_loss=0.002181

      epoch   5/100: train_loss=0.002304, val_loss=0.002673, IC=+0.0096

      epoch   6/100: train_loss=0.004888

      epoch   7/100: train_loss=0.002642

      epoch   8/100: train_loss=0.001946

      epoch   9/100: train_loss=0.001641

      epoch  10/100: train_loss=0.001885, val_loss=0.003576, IC=-0.0275

      epoch  11/100: train_loss=0.001740

      epoch  12/100: train_loss=0.001504

      epoch  13/100: train_loss=0.001383

      epoch  14/100: train_loss=0.002376

      epoch  15/100: train_loss=0.001704, val_loss=0.004522, IC=-0.0245

      epoch  16/100: train_loss=0.001747

      epoch  17/100: train_loss=0.001758

      epoch  18/100: train_loss=0.001591

      epoch  19/100: train_loss=0.001639

      epoch  20/100: train_loss=0.002127, val_loss=0.001354, IC=-0.0350

      epoch  21/100: train_loss=0.002705

      epoch  22/100: train_loss=0.001199

      epoch  23/100: train_loss=0.001079

      epoch  24/100: train_loss=0.001282

      epoch  25/100: train_loss=0.001709, val_loss=0.001871, IC=-0.0175

      epoch  26/100: train_loss=0.001306

      epoch  27/100: train_loss=0.001155

      epoch  28/100: train_loss=0.000995

      epoch  29/100: train_loss=0.000948

      epoch  30/100: train_loss=0.000910, val_loss=0.002998, IC=-0.0213

      epoch  31/100: train_loss=0.001766

      epoch  32/100: train_loss=0.000913

      epoch  33/100: train_loss=0.000728

      epoch  34/100: train_loss=0.000774

      epoch  35/100: train_loss=0.000782, val_loss=0.000850, IC=-0.0309

      epoch  36/100: train_loss=0.002883

      epoch  37/100: train_loss=0.001107

      epoch  38/100: train_loss=0.001205

      epoch  39/100: train_loss=0.001266

      epoch  40/100: train_loss=0.002096, val_loss=0.000625, IC=-0.0343

      epoch  41/100: train_loss=0.001410

      epoch  42/100: train_loss=0.001604

      epoch  43/100: train_loss=0.001304

      epoch  44/100: train_loss=0.000745

      epoch  45/100: train_loss=0.000662, val_loss=0.000637, IC=-0.0112

      epoch  46/100: train_loss=0.001260

      epoch  47/100: train_loss=0.001044

      epoch  48/100: train_loss=0.001296

      epoch  49/100: train_loss=0.001338

      epoch  50/100: train_loss=0.001246, val_loss=0.000486, IC=-0.0084

      epoch  51/100: train_loss=0.000935

      epoch  52/100: train_loss=0.000767

      epoch  53/100: train_loss=0.000701

      epoch  54/100: train_loss=0.000630

      epoch  55/100: train_loss=0.001120, val_loss=0.001146, IC=-0.0196

      epoch  56/100: train_loss=0.000661

      epoch  57/100: train_loss=0.000578

      epoch  58/100: train_loss=0.000642

      epoch  59/100: train_loss=0.000576

      epoch  60/100: train_loss=0.000565, val_loss=0.000422, IC=-0.0204

      epoch  61/100: train_loss=0.000931

      epoch  62/100: train_loss=0.000621

      epoch  63/100: train_loss=0.000530

      epoch  64/100: train_loss=0.000500

      epoch  65/100: train_loss=0.000623, val_loss=0.000615, IC=-0.0281

      epoch  66/100: train_loss=0.000560

      epoch  67/100: train_loss=0.000545

      epoch  68/100: train_loss=0.000511

      epoch  69/100: train_loss=0.000544

      epoch  70/100: train_loss=0.000762, val_loss=0.000380, IC=-0.0245

      epoch  71/100: train_loss=0.000704

      epoch  72/100: train_loss=0.000581

      epoch  73/100: train_loss=0.000577

      epoch  74/100: train_loss=0.000542

      epoch  75/100: train_loss=0.000502, val_loss=0.000412, IC=-0.0236

      epoch  76/100: train_loss=0.000850

      epoch  77/100: train_loss=0.000721

      epoch  78/100: train_loss=0.000519

      epoch  79/100: train_loss=0.000506

      epoch  80/100: train_loss=0.000506, val_loss=0.000451, IC=-0.0209

      epoch  81/100: train_loss=0.000500

      epoch  82/100: train_loss=0.000468

      epoch  83/100: train_loss=0.000679

      epoch  84/100: train_loss=0.000593

      epoch  85/100: train_loss=0.000476, val_loss=0.000306, IC=-0.0274

      epoch  86/100: train_loss=0.000545

      epoch  87/100: train_loss=0.000492

      epoch  88/100: train_loss=0.000479

      epoch  89/100: train_loss=0.000509

      epoch  90/100: train_loss=0.000497, val_loss=0.000442, IC=-0.0259

      epoch  91/100: train_loss=0.000452

      epoch  92/100: train_loss=0.000586

      epoch  93/100: train_loss=0.000497

      epoch  94/100: train_loss=0.000518

      epoch  95/100: train_loss=0.000602, val_loss=0.000326, IC=-0.0275

      epoch  96/100: train_loss=0.000622

      epoch  97/100: train_loss=0.000534

      epoch  98/100: train_loss=0.000643

      epoch  99/100: train_loss=0.000471

      epoch 100/100: train_loss=0.000449, val_loss=0.000401, IC=-0.0272

      best_ep=5, IC=+0.0096 (75.0s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,140 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.052800

      epoch   2/100: train_loss=0.005512

      epoch   3/100: train_loss=0.004153

      epoch   4/100: train_loss=0.003073

      epoch   5/100: train_loss=0.002477, val_loss=0.002490, IC=+0.0228

      epoch   6/100: train_loss=0.002455

      epoch   7/100: train_loss=0.002243

      epoch   8/100: train_loss=0.002654

      epoch   9/100: train_loss=0.002218

      epoch  10/100: train_loss=0.003535, val_loss=0.001488, IC=+0.0266

      epoch  11/100: train_loss=0.001790

      epoch  12/100: train_loss=0.001642

      epoch  13/100: train_loss=0.001716

      epoch  14/100: train_loss=0.001536

      epoch  15/100: train_loss=0.001543, val_loss=0.000794, IC=+0.0268

      epoch  16/100: train_loss=0.001353

      epoch  17/100: train_loss=0.001271

      epoch  18/100: train_loss=0.001301

      epoch  19/100: train_loss=0.001603

      epoch  20/100: train_loss=0.002021, val_loss=0.002559, IC=+0.0227

      epoch  21/100: train_loss=0.001912

      epoch  22/100: train_loss=0.001716

      epoch  23/100: train_loss=0.002508

      epoch  24/100: train_loss=0.001540

      epoch  25/100: train_loss=0.001547, val_loss=0.000755, IC=+0.0326

      epoch  26/100: train_loss=0.002826

      epoch  27/100: train_loss=0.001352

      epoch  28/100: train_loss=0.001684

      epoch  29/100: train_loss=0.001737

      epoch  30/100: train_loss=0.001412, val_loss=0.001535, IC=+0.0188

      epoch  31/100: train_loss=0.001266

      epoch  32/100: train_loss=0.001469

      epoch  33/100: train_loss=0.001461

      epoch  34/100: train_loss=0.001310

      epoch  35/100: train_loss=0.001725, val_loss=0.000626, IC=+0.0332

      epoch  36/100: train_loss=0.000977

      epoch  37/100: train_loss=0.001094

      epoch  38/100: train_loss=0.002242

      epoch  39/100: train_loss=0.001119

      epoch  40/100: train_loss=0.001081, val_loss=0.000387, IC=+0.0295

      epoch  41/100: train_loss=0.000982

      epoch  42/100: train_loss=0.001227

      epoch  43/100: train_loss=0.000785

      epoch  44/100: train_loss=0.000878

      epoch  45/100: train_loss=0.001028, val_loss=0.000500, IC=+0.0189

      epoch  46/100: train_loss=0.001471

      epoch  47/100: train_loss=0.000799

      epoch  48/100: train_loss=0.000756

      epoch  49/100: train_loss=0.000658

      epoch  50/100: train_loss=0.000628, val_loss=0.000328, IC=+0.0244

      epoch  51/100: train_loss=0.000740

      epoch  52/100: train_loss=0.000693

      epoch  53/100: train_loss=0.000705

      epoch  54/100: train_loss=0.001152

      epoch  55/100: train_loss=0.000694, val_loss=0.000364, IC=+0.0155

      epoch  56/100: train_loss=0.000829

      epoch  57/100: train_loss=0.000777

      epoch  58/100: train_loss=0.000867

      epoch  59/100: train_loss=0.001378

      epoch  60/100: train_loss=0.000669, val_loss=0.000333, IC=+0.0307

      epoch  61/100: train_loss=0.000742

      epoch  62/100: train_loss=0.000728

      epoch  63/100: train_loss=0.001075

      epoch  64/100: train_loss=0.001388

      epoch  65/100: train_loss=0.000899, val_loss=0.000676, IC=+0.0275

      epoch  66/100: train_loss=0.000973

      epoch  67/100: train_loss=0.000736

      epoch  68/100: train_loss=0.000580

      epoch  69/100: train_loss=0.000576

      epoch  70/100: train_loss=0.000625, val_loss=0.000366, IC=+0.0186

      epoch  71/100: train_loss=0.000702

      epoch  72/100: train_loss=0.000707

      epoch  73/100: train_loss=0.000663

      epoch  74/100: train_loss=0.000580

      epoch  75/100: train_loss=0.000591, val_loss=0.000273, IC=+0.0186

      epoch  76/100: train_loss=0.000594

      epoch  77/100: train_loss=0.000541

      epoch  78/100: train_loss=0.000551

      epoch  79/100: train_loss=0.000626

      epoch  80/100: train_loss=0.000617, val_loss=0.000289, IC=+0.0093

      epoch  81/100: train_loss=0.000613

      epoch  82/100: train_loss=0.000700

      epoch  83/100: train_loss=0.000671

      epoch  84/100: train_loss=0.000746

      epoch  85/100: train_loss=0.000642, val_loss=0.000262, IC=+0.0086

      epoch  86/100: train_loss=0.000662

      epoch  87/100: train_loss=0.000633

      epoch  88/100: train_loss=0.000876

      epoch  89/100: train_loss=0.000748

      epoch  90/100: train_loss=0.000560, val_loss=0.000271, IC=+0.0073

      epoch  91/100: train_loss=0.000617

      epoch  92/100: train_loss=0.000515

      epoch  93/100: train_loss=0.000543

      epoch  94/100: train_loss=0.000580

      epoch  95/100: train_loss=0.001033, val_loss=0.000285, IC=+0.0131

      epoch  96/100: train_loss=0.000581

      epoch  97/100: train_loss=0.000516

      epoch  98/100: train_loss=0.000553

      epoch  99/100: train_loss=0.000626

      epoch 100/100: train_loss=0.000550, val_loss=0.000255, IC=+0.0077

      best_ep=35, IC=+0.0332 (83.8s, 20 checkpoints)

  tcn: best_epoch=10, IC=+0.0149 (604.3s)

  Best: tcn @ epoch 10 (IC=+0.0149)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/8caab3d93247/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=16,980 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.047914

      epoch   2/100: train_loss=0.005463

      epoch   3/100: train_loss=0.003091

      epoch   4/100: train_loss=0.002349

      epoch   5/100: train_loss=0.001834, val_loss=0.003809, IC=-0.0254

      epoch   6/100: train_loss=0.001712

      epoch   7/100: train_loss=0.001579

      epoch   8/100: train_loss=0.001464

      epoch   9/100: train_loss=0.001446

      epoch  10/100: train_loss=0.001348, val_loss=0.002268, IC=-0.0102

      epoch  11/100: train_loss=0.001354

      epoch  12/100: train_loss=0.001294

      epoch  13/100: train_loss=0.001282

      epoch  14/100: train_loss=0.001383

      epoch  15/100: train_loss=0.001303, val_loss=0.002650, IC=-0.0033

      epoch  16/100: train_loss=0.001210

      epoch  17/100: train_loss=0.001107

      epoch  18/100: train_loss=0.001095

      epoch  19/100: train_loss=0.001040

      epoch  20/100: train_loss=0.000990, val_loss=0.001847, IC=+0.0013

      epoch  21/100: train_loss=0.001020

      epoch  22/100: train_loss=0.001019

      epoch  23/100: train_loss=0.001016

      epoch  24/100: train_loss=0.000980

      epoch  25/100: train_loss=0.000933, val_loss=0.001915, IC=-0.0140

      epoch  26/100: train_loss=0.000942

      epoch  27/100: train_loss=0.000877

      epoch  28/100: train_loss=0.000855

      epoch  29/100: train_loss=0.000853

      epoch  30/100: train_loss=0.000860, val_loss=0.002132, IC=-0.0130

      epoch  31/100: train_loss=0.000903

      epoch  32/100: train_loss=0.000796

      epoch  33/100: train_loss=0.000869

      epoch  34/100: train_loss=0.000788

      epoch  35/100: train_loss=0.000781, val_loss=0.001248, IC=-0.0137

      epoch  36/100: train_loss=0.000774

      epoch  37/100: train_loss=0.000760

      epoch  38/100: train_loss=0.000774

      epoch  39/100: train_loss=0.000736

      epoch  40/100: train_loss=0.000737, val_loss=0.001245, IC=-0.0172

      epoch  41/100: train_loss=0.000702

      epoch  42/100: train_loss=0.000706

      epoch  43/100: train_loss=0.000691

      epoch  44/100: train_loss=0.000701

      epoch  45/100: train_loss=0.000690, val_loss=0.001208, IC=-0.0248

      epoch  46/100: train_loss=0.000689

      epoch  47/100: train_loss=0.000686

      epoch  48/100: train_loss=0.000655

      epoch  49/100: train_loss=0.000682

      epoch  50/100: train_loss=0.000737, val_loss=0.001161, IC=-0.0273

      epoch  51/100: train_loss=0.000690

      epoch  52/100: train_loss=0.000679

      epoch  53/100: train_loss=0.000636

      epoch  54/100: train_loss=0.000607

      epoch  55/100: train_loss=0.000614, val_loss=0.000902, IC=-0.0164

      epoch  56/100: train_loss=0.000620

      epoch  57/100: train_loss=0.000596

      epoch  58/100: train_loss=0.000615

      epoch  59/100: train_loss=0.000634

      epoch  60/100: train_loss=0.000649, val_loss=0.001079, IC=-0.0188

      epoch  61/100: train_loss=0.000611

      epoch  62/100: train_loss=0.000593

      epoch  63/100: train_loss=0.000583

      epoch  64/100: train_loss=0.000578

      epoch  65/100: train_loss=0.000607, val_loss=0.001195, IC=-0.0275

      epoch  66/100: train_loss=0.000572

      epoch  67/100: train_loss=0.000566

      epoch  68/100: train_loss=0.000577

      epoch  69/100: train_loss=0.000544

      epoch  70/100: train_loss=0.000564, val_loss=0.000858, IC=-0.0236

      epoch  71/100: train_loss=0.000563

      epoch  72/100: train_loss=0.000555

      epoch  73/100: train_loss=0.000578

      epoch  74/100: train_loss=0.000558

      epoch  75/100: train_loss=0.000540, val_loss=0.001026, IC=-0.0276

      epoch  76/100: train_loss=0.000547

      epoch  77/100: train_loss=0.000541

      epoch  78/100: train_loss=0.000544

      epoch  79/100: train_loss=0.000546

      epoch  80/100: train_loss=0.000545, val_loss=0.000921, IC=-0.0240

      epoch  81/100: train_loss=0.000532

      epoch  82/100: train_loss=0.000547

      epoch  83/100: train_loss=0.000538

      epoch  84/100: train_loss=0.000533

      epoch  85/100: train_loss=0.000531, val_loss=0.000884, IC=-0.0244

      epoch  86/100: train_loss=0.000535

      epoch  87/100: train_loss=0.000535

      epoch  88/100: train_loss=0.000540

      epoch  89/100: train_loss=0.000525

      epoch  90/100: train_loss=0.000538, val_loss=0.000837, IC=-0.0235

      epoch  91/100: train_loss=0.000524

      epoch  92/100: train_loss=0.000523

      epoch  93/100: train_loss=0.000522

      epoch  94/100: train_loss=0.000527

      epoch  95/100: train_loss=0.000532, val_loss=0.000906, IC=-0.0260

      epoch  96/100: train_loss=0.000506

      epoch  97/100: train_loss=0.000541

      epoch  98/100: train_loss=0.000523

      epoch  99/100: train_loss=0.000531

      epoch 100/100: train_loss=0.000527, val_loss=0.000874, IC=-0.0248

      best_ep=20, IC=+0.0013 (62.0s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,140 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.033914

      epoch   2/100: train_loss=0.005051

      epoch   3/100: train_loss=0.003011

      epoch   4/100: train_loss=0.002463

      epoch   5/100: train_loss=0.002120, val_loss=0.002826, IC=+0.1062

      epoch   6/100: train_loss=0.001871

      epoch   7/100: train_loss=0.001857

      epoch   8/100: train_loss=0.001699

      epoch   9/100: train_loss=0.001566

      epoch  10/100: train_loss=0.001548, val_loss=0.000814, IC=+0.0561

      epoch  11/100: train_loss=0.001504

      epoch  12/100: train_loss=0.001412

      epoch  13/100: train_loss=0.001349

      epoch  14/100: train_loss=0.001321

      epoch  15/100: train_loss=0.001312, val_loss=0.000611, IC=+0.0702

      epoch  16/100: train_loss=0.001280

      epoch  17/100: train_loss=0.001309

      epoch  18/100: train_loss=0.001212

      epoch  19/100: train_loss=0.001249

      epoch  20/100: train_loss=0.001216, val_loss=0.000814, IC=+0.0721

      epoch  21/100: train_loss=0.001187

      epoch  22/100: train_loss=0.001097

      epoch  23/100: train_loss=0.001049

      epoch  24/100: train_loss=0.001014

      epoch  25/100: train_loss=0.001035, val_loss=0.000560, IC=+0.0071

      epoch  26/100: train_loss=0.001104

      epoch  27/100: train_loss=0.000996

      epoch  28/100: train_loss=0.000957

      epoch  29/100: train_loss=0.000954

      epoch  30/100: train_loss=0.000972, val_loss=0.000415, IC=+0.0304

      epoch  31/100: train_loss=0.000965

      epoch  32/100: train_loss=0.000946

      epoch  33/100: train_loss=0.000856

      epoch  34/100: train_loss=0.000879

      epoch  35/100: train_loss=0.000845, val_loss=0.000505, IC=+0.0545

      epoch  36/100: train_loss=0.000840

      epoch  37/100: train_loss=0.000861

      epoch  38/100: train_loss=0.000876

      epoch  39/100: train_loss=0.000803

      epoch  40/100: train_loss=0.000789, val_loss=0.000365, IC=+0.0446

      epoch  41/100: train_loss=0.000777

      epoch  42/100: train_loss=0.000814

      epoch  43/100: train_loss=0.000785

      epoch  44/100: train_loss=0.000729

      epoch  45/100: train_loss=0.000747, val_loss=0.000331, IC=+0.0343

      epoch  46/100: train_loss=0.000775

      epoch  47/100: train_loss=0.000780

      epoch  48/100: train_loss=0.000767

      epoch  49/100: train_loss=0.000772

      epoch  50/100: train_loss=0.000709, val_loss=0.000383, IC=+0.0519

      epoch  51/100: train_loss=0.000704

      epoch  52/100: train_loss=0.000700

      epoch  53/100: train_loss=0.000735

      epoch  54/100: train_loss=0.000696

      epoch  55/100: train_loss=0.000686, val_loss=0.000314, IC=+0.0279

      epoch  56/100: train_loss=0.000697

      epoch  57/100: train_loss=0.000676

      epoch  58/100: train_loss=0.000686

      epoch  59/100: train_loss=0.000689

      epoch  60/100: train_loss=0.000685, val_loss=0.000297, IC=+0.0194

      epoch  61/100: train_loss=0.000692

      epoch  62/100: train_loss=0.000681

      epoch  63/100: train_loss=0.000652

      epoch  64/100: train_loss=0.000651

      epoch  65/100: train_loss=0.000667, val_loss=0.000335, IC=+0.0371

      epoch  66/100: train_loss=0.000653

      epoch  67/100: train_loss=0.000678

      epoch  68/100: train_loss=0.000645

      epoch  69/100: train_loss=0.000633

      epoch  70/100: train_loss=0.000617, val_loss=0.000303, IC=+0.0454

      epoch  71/100: train_loss=0.000638

      epoch  72/100: train_loss=0.000604

      epoch  73/100: train_loss=0.000653

      epoch  74/100: train_loss=0.000630

      epoch  75/100: train_loss=0.000619, val_loss=0.000309, IC=+0.0423

      epoch  76/100: train_loss=0.000611

      epoch  77/100: train_loss=0.000609

      epoch  78/100: train_loss=0.000617

      epoch  79/100: train_loss=0.000608

      epoch  80/100: train_loss=0.000598, val_loss=0.000308, IC=+0.0386

      epoch  81/100: train_loss=0.000607

      epoch  82/100: train_loss=0.000599

      epoch  83/100: train_loss=0.000596

      epoch  84/100: train_loss=0.000605

      epoch  85/100: train_loss=0.000598, val_loss=0.000303, IC=+0.0454

      epoch  86/100: train_loss=0.000605

      epoch  87/100: train_loss=0.000599

      epoch  88/100: train_loss=0.000604

      epoch  89/100: train_loss=0.000607

      epoch  90/100: train_loss=0.000599, val_loss=0.000299, IC=+0.0436

      epoch  91/100: train_loss=0.000601

      epoch  92/100: train_loss=0.000605

      epoch  93/100: train_loss=0.000595

      epoch  94/100: train_loss=0.000620

      epoch  95/100: train_loss=0.000585, val_loss=0.000292, IC=+0.0395

      epoch  96/100: train_loss=0.000605

      epoch  97/100: train_loss=0.000615

      epoch  98/100: train_loss=0.000609

      epoch  99/100: train_loss=0.000602

      epoch 100/100: train_loss=0.000597, val_loss=0.000283, IC=+0.0436

      best_ep=5, IC=+0.1062 (87.2s, 20 checkpoints)

  Fold 2: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.022956

      epoch   2/100: train_loss=0.003899

      epoch   3/100: train_loss=0.002356

      epoch   4/100: train_loss=0.001806

      epoch   5/100: train_loss=0.001619, val_loss=0.001239, IC=-0.0332

      epoch   6/100: train_loss=0.001453

      epoch   7/100: train_loss=0.001315

      epoch   8/100: train_loss=0.001281

      epoch   9/100: train_loss=0.001198

      epoch  10/100: train_loss=0.001153, val_loss=0.000960, IC=-0.0351

      epoch  11/100: train_loss=0.001086

      epoch  12/100: train_loss=0.001022

      epoch  13/100: train_loss=0.001000

      epoch  14/100: train_loss=0.000973

      epoch  15/100: train_loss=0.000927, val_loss=0.000594, IC=+0.0113

      epoch  16/100: train_loss=0.000927

      epoch  17/100: train_loss=0.000868

      epoch  18/100: train_loss=0.000847

      epoch  19/100: train_loss=0.000819

      epoch  20/100: train_loss=0.000809, val_loss=0.000454, IC=-0.0097

      epoch  21/100: train_loss=0.000780

      epoch  22/100: train_loss=0.000753

      epoch  23/100: train_loss=0.000747

      epoch  24/100: train_loss=0.000744

      epoch  25/100: train_loss=0.000692, val_loss=0.000370, IC=-0.0171

      epoch  26/100: train_loss=0.000668

      epoch  27/100: train_loss=0.000667

      epoch  28/100: train_loss=0.000673

      epoch  29/100: train_loss=0.000639

      epoch  30/100: train_loss=0.000636, val_loss=0.000400, IC=-0.0284

      epoch  31/100: train_loss=0.000644

      epoch  32/100: train_loss=0.000601

      epoch  33/100: train_loss=0.000601

      epoch  34/100: train_loss=0.000630

      epoch  35/100: train_loss=0.000601, val_loss=0.000336, IC=-0.0355

      epoch  36/100: train_loss=0.000581

      epoch  37/100: train_loss=0.000574

      epoch  38/100: train_loss=0.000563

      epoch  39/100: train_loss=0.000572

      epoch  40/100: train_loss=0.000566, val_loss=0.000270, IC=-0.0185

      epoch  41/100: train_loss=0.000537

      epoch  42/100: train_loss=0.000534

      epoch  43/100: train_loss=0.000550

      epoch  44/100: train_loss=0.000519

      epoch  45/100: train_loss=0.000545, val_loss=0.000338, IC=-0.0308

      epoch  46/100: train_loss=0.000514

      epoch  47/100: train_loss=0.000502

      epoch  48/100: train_loss=0.000511

      epoch  49/100: train_loss=0.000505

      epoch  50/100: train_loss=0.000498, val_loss=0.000439, IC=-0.0237

      epoch  51/100: train_loss=0.000504

      epoch  52/100: train_loss=0.000478

      epoch  53/100: train_loss=0.000478

      epoch  54/100: train_loss=0.000481

      epoch  55/100: train_loss=0.000473, val_loss=0.000275, IC=-0.0120

      epoch  56/100: train_loss=0.000473

      epoch  57/100: train_loss=0.000465

      epoch  58/100: train_loss=0.000463

      epoch  59/100: train_loss=0.000469

      epoch  60/100: train_loss=0.000474, val_loss=0.000263, IC=-0.0154

      epoch  61/100: train_loss=0.000468

      epoch  62/100: train_loss=0.000469

      epoch  63/100: train_loss=0.000453

      epoch  64/100: train_loss=0.000462

      epoch  65/100: train_loss=0.000457, val_loss=0.000288, IC=-0.0204

      epoch  66/100: train_loss=0.000450

      epoch  67/100: train_loss=0.000442

      epoch  68/100: train_loss=0.000447

      epoch  69/100: train_loss=0.000436

      epoch  70/100: train_loss=0.000429, val_loss=0.000246, IC=-0.0102

      epoch  71/100: train_loss=0.000442

      epoch  72/100: train_loss=0.000433

      epoch  73/100: train_loss=0.000434

      epoch  74/100: train_loss=0.000431

      epoch  75/100: train_loss=0.000428, val_loss=0.000268, IC=-0.0123

      epoch  76/100: train_loss=0.000434

      epoch  77/100: train_loss=0.000437

      epoch  78/100: train_loss=0.000433

      epoch  79/100: train_loss=0.000427

      epoch  80/100: train_loss=0.000424, val_loss=0.000267, IC=-0.0150

      epoch  81/100: train_loss=0.000433

      epoch  82/100: train_loss=0.000432

      epoch  83/100: train_loss=0.000422

      epoch  84/100: train_loss=0.000424

      epoch  85/100: train_loss=0.000423, val_loss=0.000263, IC=-0.0101

      epoch  86/100: train_loss=0.000424

      epoch  87/100: train_loss=0.000425

      epoch  88/100: train_loss=0.000415

      epoch  89/100: train_loss=0.000423

      epoch  90/100: train_loss=0.000428, val_loss=0.000248, IC=-0.0105

      epoch  91/100: train_loss=0.000430

      epoch  92/100: train_loss=0.000425

      epoch  93/100: train_loss=0.000414

      epoch  94/100: train_loss=0.000427

      epoch  95/100: train_loss=0.000426, val_loss=0.000260, IC=-0.0145

      epoch  96/100: train_loss=0.000413

      epoch  97/100: train_loss=0.000419

      epoch  98/100: train_loss=0.000416

      epoch  99/100: train_loss=0.000420

      epoch 100/100: train_loss=0.000429, val_loss=0.000247, IC=-0.0107

      best_ep=15, IC=+0.0113 (130.6s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.077565

      epoch   2/100: train_loss=0.005787

      epoch   3/100: train_loss=0.003329

      epoch   4/100: train_loss=0.002407

      epoch   5/100: train_loss=0.002053, val_loss=0.001231, IC=+0.0113

      epoch   6/100: train_loss=0.001891

      epoch   7/100: train_loss=0.001718

      epoch   8/100: train_loss=0.001640

      epoch   9/100: train_loss=0.001536

      epoch  10/100: train_loss=0.001456, val_loss=0.000665, IC=+0.0296

      epoch  11/100: train_loss=0.001418

      epoch  12/100: train_loss=0.001376

      epoch  13/100: train_loss=0.001323

      epoch  14/100: train_loss=0.001302

      epoch  15/100: train_loss=0.001193, val_loss=0.000551, IC=+0.0240

      epoch  16/100: train_loss=0.001205

      epoch  17/100: train_loss=0.001213

      epoch  18/100: train_loss=0.001118

      epoch  19/100: train_loss=0.001088

      epoch  20/100: train_loss=0.001041, val_loss=0.000371, IC=+0.0386

      epoch  21/100: train_loss=0.001030

      epoch  22/100: train_loss=0.001035

      epoch  23/100: train_loss=0.001012

      epoch  24/100: train_loss=0.000986

      epoch  25/100: train_loss=0.000988, val_loss=0.000453, IC=+0.0382

      epoch  26/100: train_loss=0.000971

      epoch  27/100: train_loss=0.000889

      epoch  28/100: train_loss=0.000918

      epoch  29/100: train_loss=0.000880

      epoch  30/100: train_loss=0.000886, val_loss=0.000358, IC=+0.0155

      epoch  31/100: train_loss=0.000855

      epoch  32/100: train_loss=0.000799

      epoch  33/100: train_loss=0.000833

      epoch  34/100: train_loss=0.000828

      epoch  35/100: train_loss=0.000766, val_loss=0.000240, IC=+0.0257

      epoch  36/100: train_loss=0.000775

      epoch  37/100: train_loss=0.000807

      epoch  38/100: train_loss=0.000763

      epoch  39/100: train_loss=0.000765

      epoch  40/100: train_loss=0.000768, val_loss=0.000272, IC=+0.0157

      epoch  41/100: train_loss=0.000791

      epoch  42/100: train_loss=0.000745

      epoch  43/100: train_loss=0.000743

      epoch  44/100: train_loss=0.000717

      epoch  45/100: train_loss=0.000710, val_loss=0.000206, IC=+0.0087

      epoch  46/100: train_loss=0.000683

      epoch  47/100: train_loss=0.000663

      epoch  48/100: train_loss=0.000697

      epoch  49/100: train_loss=0.000705

      epoch  50/100: train_loss=0.000683, val_loss=0.000210, IC=+0.0135

      epoch  51/100: train_loss=0.000662

      epoch  52/100: train_loss=0.000654

      epoch  53/100: train_loss=0.000640

      epoch  54/100: train_loss=0.000655

      epoch  55/100: train_loss=0.000664, val_loss=0.000301, IC=+0.0106

      epoch  56/100: train_loss=0.000675

      epoch  57/100: train_loss=0.000656

      epoch  58/100: train_loss=0.000629

      epoch  59/100: train_loss=0.000632

      epoch  60/100: train_loss=0.000623, val_loss=0.000216, IC=+0.0040

      epoch  61/100: train_loss=0.000614

      epoch  62/100: train_loss=0.000607

      epoch  63/100: train_loss=0.000614

      epoch  64/100: train_loss=0.000592

      epoch  65/100: train_loss=0.000600, val_loss=0.000196, IC=-0.0004

      epoch  66/100: train_loss=0.000577

      epoch  67/100: train_loss=0.000584

      epoch  68/100: train_loss=0.000590

      epoch  69/100: train_loss=0.000573

      epoch  70/100: train_loss=0.000585, val_loss=0.000194, IC=+0.0030

      epoch  71/100: train_loss=0.000597

      epoch  72/100: train_loss=0.000601

      epoch  73/100: train_loss=0.000583

      epoch  74/100: train_loss=0.000586

      epoch  75/100: train_loss=0.000588, val_loss=0.000191, IC=+0.0139

      epoch  76/100: train_loss=0.000557

      epoch  77/100: train_loss=0.000563

      epoch  78/100: train_loss=0.000577

      epoch  79/100: train_loss=0.000549

      epoch  80/100: train_loss=0.000564, val_loss=0.000191, IC=+0.0058

      epoch  81/100: train_loss=0.000579

      epoch  82/100: train_loss=0.000557

      epoch  83/100: train_loss=0.000568

      epoch  84/100: train_loss=0.000543

      epoch  85/100: train_loss=0.000573, val_loss=0.000188, IC=+0.0093

      epoch  86/100: train_loss=0.000546

      epoch  87/100: train_loss=0.000556

      epoch  88/100: train_loss=0.000558

      epoch  89/100: train_loss=0.000572

      epoch  90/100: train_loss=0.000552, val_loss=0.000190, IC=+0.0114

      epoch  91/100: train_loss=0.000538

      epoch  92/100: train_loss=0.000560

      epoch  93/100: train_loss=0.000546

      epoch  94/100: train_loss=0.000557

      epoch  95/100: train_loss=0.000547, val_loss=0.000187, IC=+0.0095

      epoch  96/100: train_loss=0.000557

      epoch  97/100: train_loss=0.000545

      epoch  98/100: train_loss=0.000543

      epoch  99/100: train_loss=0.000568

      epoch 100/100: train_loss=0.000550, val_loss=0.000188, IC=+0.0103

      best_ep=20, IC=+0.0386 (162.6s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.201309

      epoch   2/100: train_loss=0.008264

      epoch   3/100: train_loss=0.002569

      epoch   4/100: train_loss=0.001813

      epoch   5/100: train_loss=0.001399, val_loss=0.001605, IC=+0.0393

      epoch   6/100: train_loss=0.001235

      epoch   7/100: train_loss=0.001140

      epoch   8/100: train_loss=0.001124

      epoch   9/100: train_loss=0.001056

      epoch  10/100: train_loss=0.000992, val_loss=0.000781, IC=+0.0615

      epoch  11/100: train_loss=0.001073

      epoch  12/100: train_loss=0.001269

      epoch  13/100: train_loss=0.001450

      epoch  14/100: train_loss=0.000844

      epoch  15/100: train_loss=0.000853, val_loss=0.000924, IC=+0.0218

      epoch  16/100: train_loss=0.000782

      epoch  17/100: train_loss=0.000869

      epoch  18/100: train_loss=0.000724

      epoch  19/100: train_loss=0.000789

      epoch  20/100: train_loss=0.000876, val_loss=0.000716, IC=+0.0377

      epoch  21/100: train_loss=0.000743

      epoch  22/100: train_loss=0.000756

      epoch  23/100: train_loss=0.000758

      epoch  24/100: train_loss=0.000731

      epoch  25/100: train_loss=0.000684, val_loss=0.000686, IC=+0.0242

      epoch  26/100: train_loss=0.000613

      epoch  27/100: train_loss=0.000763

      epoch  28/100: train_loss=0.000673

      epoch  29/100: train_loss=0.000721

      epoch  30/100: train_loss=0.000681, val_loss=0.000718, IC=+0.0106

      epoch  31/100: train_loss=0.000655

      epoch  32/100: train_loss=0.000599

      epoch  33/100: train_loss=0.000669

      epoch  34/100: train_loss=0.000663

      epoch  35/100: train_loss=0.000727, val_loss=0.000891, IC=-0.0031

      epoch  36/100: train_loss=0.000544

      epoch  37/100: train_loss=0.000568

      epoch  38/100: train_loss=0.000594

      epoch  39/100: train_loss=0.000590

      epoch  40/100: train_loss=0.000640, val_loss=0.000926, IC=+0.0275

      epoch  41/100: train_loss=0.000653

      epoch  42/100: train_loss=0.000546

      epoch  43/100: train_loss=0.000552

      epoch  44/100: train_loss=0.000578

      epoch  45/100: train_loss=0.000542, val_loss=0.000699, IC=-0.0169

      epoch  46/100: train_loss=0.000516

      epoch  47/100: train_loss=0.000492

      epoch  48/100: train_loss=0.000467

      epoch  49/100: train_loss=0.000515

      epoch  50/100: train_loss=0.000558, val_loss=0.000620, IC=+0.0194

      epoch  51/100: train_loss=0.000500

      epoch  52/100: train_loss=0.000594

      epoch  53/100: train_loss=0.000512

      epoch  54/100: train_loss=0.000531

      epoch  55/100: train_loss=0.000494, val_loss=0.000653, IC=-0.0039

      epoch  56/100: train_loss=0.000503

      epoch  57/100: train_loss=0.000479

      epoch  58/100: train_loss=0.000505

      epoch  59/100: train_loss=0.000504

      epoch  60/100: train_loss=0.000436, val_loss=0.000414, IC=+0.0206

      epoch  61/100: train_loss=0.000458

      epoch  62/100: train_loss=0.000506

      epoch  63/100: train_loss=0.000465

      epoch  64/100: train_loss=0.000459

      epoch  65/100: train_loss=0.000485, val_loss=0.000676, IC=-0.0198

      epoch  66/100: train_loss=0.000503

      epoch  67/100: train_loss=0.000472

      epoch  68/100: train_loss=0.000458

      epoch  69/100: train_loss=0.000476

      epoch  70/100: train_loss=0.000471, val_loss=0.000650, IC=+0.0156

      epoch  71/100: train_loss=0.000480

      epoch  72/100: train_loss=0.000419

      epoch  73/100: train_loss=0.000448

      epoch  74/100: train_loss=0.000444

      epoch  75/100: train_loss=0.000469, val_loss=0.000399, IC=+0.0260

      epoch  76/100: train_loss=0.000459

      epoch  77/100: train_loss=0.000478

      epoch  78/100: train_loss=0.000470

      epoch  79/100: train_loss=0.000466

      epoch  80/100: train_loss=0.000472, val_loss=0.000386, IC=+0.0245

      epoch  81/100: train_loss=0.000438

      epoch  82/100: train_loss=0.000452

      epoch  83/100: train_loss=0.000445

      epoch  84/100: train_loss=0.000426

      epoch  85/100: train_loss=0.000438, val_loss=0.000436, IC=+0.0188

      epoch  86/100: train_loss=0.000429

      epoch  87/100: train_loss=0.000441

      epoch  88/100: train_loss=0.000407

      epoch  89/100: train_loss=0.000462

      epoch  90/100: train_loss=0.000433, val_loss=0.000396, IC=+0.0222

      epoch  91/100: train_loss=0.000444

      epoch  92/100: train_loss=0.000444

      epoch  93/100: train_loss=0.000419

      epoch  94/100: train_loss=0.000423

      epoch  95/100: train_loss=0.000420, val_loss=0.000384, IC=+0.0228

      epoch  96/100: train_loss=0.000442

      epoch  97/100: train_loss=0.000405

      epoch  98/100: train_loss=0.000430

      epoch  99/100: train_loss=0.000407

      epoch 100/100: train_loss=0.000429, val_loss=0.000391, IC=+0.0221

      best_ep=10, IC=+0.0615 (167.2s, 20 checkpoints)

  Fold 5: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.522947

      epoch   2/100: train_loss=0.010656

      epoch   3/100: train_loss=0.003692

      epoch   4/100: train_loss=0.002223

      epoch   5/100: train_loss=0.001572, val_loss=0.000927, IC=+0.0487

      epoch   6/100: train_loss=0.001474

      epoch   7/100: train_loss=0.001311

      epoch   8/100: train_loss=0.001468

      epoch   9/100: train_loss=0.001200

      epoch  10/100: train_loss=0.001111, val_loss=0.000510, IC=+0.0430

      epoch  11/100: train_loss=0.001178

      epoch  12/100: train_loss=0.001322

      epoch  13/100: train_loss=0.001000

      epoch  14/100: train_loss=0.001015

      epoch  15/100: train_loss=0.001082, val_loss=0.000447, IC=+0.0452

      epoch  16/100: train_loss=0.001032

      epoch  17/100: train_loss=0.000954

      epoch  18/100: train_loss=0.000854

      epoch  19/100: train_loss=0.000803

      epoch  20/100: train_loss=0.000975, val_loss=0.000325, IC=+0.0413

      epoch  21/100: train_loss=0.000924

      epoch  22/100: train_loss=0.001010

      epoch  23/100: train_loss=0.000824

      epoch  24/100: train_loss=0.000781

      epoch  25/100: train_loss=0.000765, val_loss=0.000297, IC=+0.0422

      epoch  26/100: train_loss=0.000767

      epoch  27/100: train_loss=0.000713

      epoch  28/100: train_loss=0.000662

      epoch  29/100: train_loss=0.000659

      epoch  30/100: train_loss=0.000627, val_loss=0.000327, IC=+0.0314

      epoch  31/100: train_loss=0.000663

      epoch  32/100: train_loss=0.000729

      epoch  33/100: train_loss=0.000811

      epoch  34/100: train_loss=0.000828

      epoch  35/100: train_loss=0.000622, val_loss=0.000253, IC=+0.0406

      epoch  36/100: train_loss=0.000687

      epoch  37/100: train_loss=0.000643

      epoch  38/100: train_loss=0.000599

      epoch  39/100: train_loss=0.000580

      epoch  40/100: train_loss=0.000563, val_loss=0.000242, IC=+0.0365

      epoch  41/100: train_loss=0.000541

      epoch  42/100: train_loss=0.000538

      epoch  43/100: train_loss=0.000572

      epoch  44/100: train_loss=0.000545

      epoch  45/100: train_loss=0.000530, val_loss=0.000254, IC=+0.0362

      epoch  46/100: train_loss=0.000532

      epoch  47/100: train_loss=0.000551

      epoch  48/100: train_loss=0.000533

      epoch  49/100: train_loss=0.000536

      epoch  50/100: train_loss=0.000529, val_loss=0.000220, IC=+0.0355

      epoch  51/100: train_loss=0.000525

      epoch  52/100: train_loss=0.000549

      epoch  53/100: train_loss=0.000487

      epoch  54/100: train_loss=0.000471

      epoch  55/100: train_loss=0.000501, val_loss=0.000230, IC=+0.0204

      epoch  56/100: train_loss=0.000550

      epoch  57/100: train_loss=0.000493

      epoch  58/100: train_loss=0.000514

      epoch  59/100: train_loss=0.000568

      epoch  60/100: train_loss=0.000466, val_loss=0.000240, IC=+0.0234

      epoch  61/100: train_loss=0.000485

      epoch  62/100: train_loss=0.000485

      epoch  63/100: train_loss=0.000483

      epoch  64/100: train_loss=0.000486

      epoch  65/100: train_loss=0.000515, val_loss=0.000219, IC=+0.0269

      epoch  66/100: train_loss=0.000475

      epoch  67/100: train_loss=0.000464

      epoch  68/100: train_loss=0.000460

      epoch  69/100: train_loss=0.000455

      epoch  70/100: train_loss=0.000490, val_loss=0.000211, IC=+0.0263

      epoch  71/100: train_loss=0.000510

      epoch  72/100: train_loss=0.000449

      epoch  73/100: train_loss=0.000427

      epoch  74/100: train_loss=0.000488

      epoch  75/100: train_loss=0.000471, val_loss=0.000201, IC=+0.0274

      epoch  76/100: train_loss=0.000463

      epoch  77/100: train_loss=0.000441

      epoch  78/100: train_loss=0.000436

      epoch  79/100: train_loss=0.000435

      epoch  80/100: train_loss=0.000491, val_loss=0.000209, IC=+0.0252

      epoch  81/100: train_loss=0.000441

      epoch  82/100: train_loss=0.000438

      epoch  83/100: train_loss=0.000427

      epoch  84/100: train_loss=0.000466

      epoch  85/100: train_loss=0.000424, val_loss=0.000195, IC=+0.0243

      epoch  86/100: train_loss=0.000447

      epoch  87/100: train_loss=0.000446

      epoch  88/100: train_loss=0.000457

      epoch  89/100: train_loss=0.000446

      epoch  90/100: train_loss=0.000437, val_loss=0.000196, IC=+0.0238

      epoch  91/100: train_loss=0.000439

      epoch  92/100: train_loss=0.000449

      epoch  93/100: train_loss=0.000428

      epoch  94/100: train_loss=0.000420

      epoch  95/100: train_loss=0.000447, val_loss=0.000198, IC=+0.0239

      epoch  96/100: train_loss=0.000426

      epoch  97/100: train_loss=0.000422

      epoch  98/100: train_loss=0.000438

      epoch  99/100: train_loss=0.000459

      epoch 100/100: train_loss=0.000423, val_loss=0.000198, IC=+0.0232

      best_ep=5, IC=+0.0487 (154.3s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.041783

      epoch   2/100: train_loss=0.004949

      epoch   3/100: train_loss=0.002752

      epoch   4/100: train_loss=0.002060

      epoch   5/100: train_loss=0.001907, val_loss=0.005380, IC=+0.0049

      epoch   6/100: train_loss=0.001691

      epoch   7/100: train_loss=0.001632

      epoch   8/100: train_loss=0.001489

      epoch   9/100: train_loss=0.001414

      epoch  10/100: train_loss=0.001375, val_loss=0.002372, IC=-0.0080

      epoch  11/100: train_loss=0.001317

      epoch  12/100: train_loss=0.001234

      epoch  13/100: train_loss=0.001166

      epoch  14/100: train_loss=0.001222

      epoch  15/100: train_loss=0.001141, val_loss=0.003196, IC=+0.0054

      epoch  16/100: train_loss=0.001173

      epoch  17/100: train_loss=0.001070

      epoch  18/100: train_loss=0.001006

      epoch  19/100: train_loss=0.001031

      epoch  20/100: train_loss=0.000962, val_loss=0.001716, IC=-0.0067

      epoch  21/100: train_loss=0.000936

      epoch  22/100: train_loss=0.000943

      epoch  23/100: train_loss=0.000893

      epoch  24/100: train_loss=0.000858

      epoch  25/100: train_loss=0.000849, val_loss=0.001860, IC=+0.0218

      epoch  26/100: train_loss=0.000818

      epoch  27/100: train_loss=0.000789

      epoch  28/100: train_loss=0.000793

      epoch  29/100: train_loss=0.000809

      epoch  30/100: train_loss=0.000743, val_loss=0.001385, IC=+0.0149

      epoch  31/100: train_loss=0.000762

      epoch  32/100: train_loss=0.000781

      epoch  33/100: train_loss=0.000696

      epoch  34/100: train_loss=0.000700

      epoch  35/100: train_loss=0.000667, val_loss=0.001016, IC=+0.0335

      epoch  36/100: train_loss=0.000666

      epoch  37/100: train_loss=0.000643

      epoch  38/100: train_loss=0.000634

      epoch  39/100: train_loss=0.000627

      epoch  40/100: train_loss=0.000625, val_loss=0.000743, IC=+0.0463

      epoch  41/100: train_loss=0.000597

      epoch  42/100: train_loss=0.000609

      epoch  43/100: train_loss=0.000625

      epoch  44/100: train_loss=0.000580

      epoch  45/100: train_loss=0.000567, val_loss=0.000975, IC=+0.0318

      epoch  46/100: train_loss=0.000580

      epoch  47/100: train_loss=0.000566

      epoch  48/100: train_loss=0.000555

      epoch  49/100: train_loss=0.000543

      epoch  50/100: train_loss=0.000546, val_loss=0.000843, IC=+0.0386

      epoch  51/100: train_loss=0.000541

      epoch  52/100: train_loss=0.000530

      epoch  53/100: train_loss=0.000537

      epoch  54/100: train_loss=0.000533

      epoch  55/100: train_loss=0.000532, val_loss=0.000654, IC=+0.0356

      epoch  56/100: train_loss=0.000525

      epoch  57/100: train_loss=0.000512

      epoch  58/100: train_loss=0.000516

      epoch  59/100: train_loss=0.000514

      epoch  60/100: train_loss=0.000514, val_loss=0.000677, IC=+0.0348

      epoch  61/100: train_loss=0.000494

      epoch  62/100: train_loss=0.000497

      epoch  63/100: train_loss=0.000475

      epoch  64/100: train_loss=0.000484

      epoch  65/100: train_loss=0.000472, val_loss=0.000492, IC=+0.0302

      epoch  66/100: train_loss=0.000487

      epoch  67/100: train_loss=0.000476

      epoch  68/100: train_loss=0.000478

      epoch  69/100: train_loss=0.000474

      epoch  70/100: train_loss=0.000464, val_loss=0.000546, IC=+0.0384

      epoch  71/100: train_loss=0.000464

      epoch  72/100: train_loss=0.000470

      epoch  73/100: train_loss=0.000463

      epoch  74/100: train_loss=0.000470

      epoch  75/100: train_loss=0.000443, val_loss=0.000543, IC=+0.0277

      epoch  76/100: train_loss=0.000447

      epoch  77/100: train_loss=0.000457

      epoch  78/100: train_loss=0.000450

      epoch  79/100: train_loss=0.000454

      epoch  80/100: train_loss=0.000451, val_loss=0.000492, IC=+0.0254

      epoch  81/100: train_loss=0.000447

      epoch  82/100: train_loss=0.000443

      epoch  83/100: train_loss=0.000437

      epoch  84/100: train_loss=0.000443

      epoch  85/100: train_loss=0.000445, val_loss=0.000516, IC=+0.0314

      epoch  86/100: train_loss=0.000444

      epoch  87/100: train_loss=0.000443

      epoch  88/100: train_loss=0.000451

      epoch  89/100: train_loss=0.000437

      epoch  90/100: train_loss=0.000457, val_loss=0.000481, IC=+0.0294

      epoch  91/100: train_loss=0.000440

      epoch  92/100: train_loss=0.000440

      epoch  93/100: train_loss=0.000442

      epoch  94/100: train_loss=0.000431

      epoch  95/100: train_loss=0.000444, val_loss=0.000516, IC=+0.0307

      epoch  96/100: train_loss=0.000437

      epoch  97/100: train_loss=0.000435

      epoch  98/100: train_loss=0.000438

      epoch  99/100: train_loss=0.000432

      epoch 100/100: train_loss=0.000441, val_loss=0.000516, IC=+0.0295

      best_ep=40, IC=+0.0463 (168.9s, 20 checkpoints)

  Fold 7: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,060 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.055894

      epoch   2/100: train_loss=0.005980

      epoch   3/100: train_loss=0.003205

      epoch   4/100: train_loss=0.002345

      epoch   5/100: train_loss=0.002054, val_loss=0.001667, IC=-0.0211

      epoch   6/100: train_loss=0.001893

      epoch   7/100: train_loss=0.001818

      epoch   8/100: train_loss=0.001749

      epoch   9/100: train_loss=0.001637

      epoch  10/100: train_loss=0.001567, val_loss=0.001031, IC=-0.0229

      epoch  11/100: train_loss=0.001484

      epoch  12/100: train_loss=0.001448

      epoch  13/100: train_loss=0.001348

      epoch  14/100: train_loss=0.001294

      epoch  15/100: train_loss=0.001280, val_loss=0.000859, IC=+0.0082

      epoch  16/100: train_loss=0.001193

      epoch  17/100: train_loss=0.001234

      epoch  18/100: train_loss=0.001261

      epoch  19/100: train_loss=0.001246

      epoch  20/100: train_loss=0.001119, val_loss=0.000907, IC=-0.0177

      epoch  21/100: train_loss=0.001020

      epoch  22/100: train_loss=0.001011

      epoch  23/100: train_loss=0.000989

      epoch  24/100: train_loss=0.001012

      epoch  25/100: train_loss=0.000946, val_loss=0.000593, IC=-0.0006

      epoch  26/100: train_loss=0.000937

      epoch  27/100: train_loss=0.000910

      epoch  28/100: train_loss=0.000864

      epoch  29/100: train_loss=0.000839

      epoch  30/100: train_loss=0.000844, val_loss=0.000540, IC=-0.0141

      epoch  31/100: train_loss=0.000857

      epoch  32/100: train_loss=0.000809

      epoch  33/100: train_loss=0.000806

      epoch  34/100: train_loss=0.000845

      epoch  35/100: train_loss=0.000838, val_loss=0.000742, IC=-0.0179

      epoch  36/100: train_loss=0.000805

      epoch  37/100: train_loss=0.000729

      epoch  38/100: train_loss=0.000715

      epoch  39/100: train_loss=0.000712

      epoch  40/100: train_loss=0.000710, val_loss=0.000429, IC=-0.0214

      epoch  41/100: train_loss=0.000677

      epoch  42/100: train_loss=0.000642

      epoch  43/100: train_loss=0.000657

      epoch  44/100: train_loss=0.000644

      epoch  45/100: train_loss=0.000639, val_loss=0.000383, IC=-0.0204

      epoch  46/100: train_loss=0.000655

      epoch  47/100: train_loss=0.000624

      epoch  48/100: train_loss=0.000603

      epoch  49/100: train_loss=0.000600

      epoch  50/100: train_loss=0.000639, val_loss=0.000372, IC=-0.0319

      epoch  51/100: train_loss=0.000586

      epoch  52/100: train_loss=0.000604

      epoch  53/100: train_loss=0.000567

      epoch  54/100: train_loss=0.000568

      epoch  55/100: train_loss=0.000573, val_loss=0.000340, IC=-0.0177

      epoch  56/100: train_loss=0.000565

      epoch  57/100: train_loss=0.000557

      epoch  58/100: train_loss=0.000542

      epoch  59/100: train_loss=0.000584

      epoch  60/100: train_loss=0.000581, val_loss=0.000343, IC=-0.0230

      epoch  61/100: train_loss=0.000575

      epoch  62/100: train_loss=0.000577

      epoch  63/100: train_loss=0.000561

      epoch  64/100: train_loss=0.000514

      epoch  65/100: train_loss=0.000526, val_loss=0.000321, IC=-0.0238

      epoch  66/100: train_loss=0.000518

      epoch  67/100: train_loss=0.000502

      epoch  68/100: train_loss=0.000508

      epoch  69/100: train_loss=0.000505

      epoch  70/100: train_loss=0.000501, val_loss=0.000324, IC=-0.0229

      epoch  71/100: train_loss=0.000501

      epoch  72/100: train_loss=0.000501

      epoch  73/100: train_loss=0.000513

      epoch  74/100: train_loss=0.000489

      epoch  75/100: train_loss=0.000490, val_loss=0.000294, IC=-0.0239

      epoch  76/100: train_loss=0.000496

      epoch  77/100: train_loss=0.000490

      epoch  78/100: train_loss=0.000508

      epoch  79/100: train_loss=0.000495

      epoch  80/100: train_loss=0.000494, val_loss=0.000290, IC=-0.0187

      epoch  81/100: train_loss=0.000478

      epoch  82/100: train_loss=0.000489

      epoch  83/100: train_loss=0.000483

      epoch  84/100: train_loss=0.000486

      epoch  85/100: train_loss=0.000496, val_loss=0.000280, IC=-0.0214

      epoch  86/100: train_loss=0.000479

      epoch  87/100: train_loss=0.000474

      epoch  88/100: train_loss=0.000468

      epoch  89/100: train_loss=0.000464

      epoch  90/100: train_loss=0.000467, val_loss=0.000282, IC=-0.0229

      epoch  91/100: train_loss=0.000474

      epoch  92/100: train_loss=0.000465

      epoch  93/100: train_loss=0.000477

      epoch  94/100: train_loss=0.000461

      epoch  95/100: train_loss=0.000470, val_loss=0.000279, IC=-0.0227

      epoch  96/100: train_loss=0.000483

      epoch  97/100: train_loss=0.000460

      epoch  98/100: train_loss=0.000467

      epoch  99/100: train_loss=0.000457

      epoch 100/100: train_loss=0.000458, val_loss=0.000280, IC=-0.0237

      best_ep=15, IC=+0.0082 (178.3s, 20 checkpoints)

  tcn: best_epoch=15, IC=+0.0229 (1111.1s)

  Best: tcn @ epoch 15 (IC=+0.0229)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/1978f50dd33b/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=16,660 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.048296

      epoch   2/100: train_loss=0.006707

      epoch   3/100: train_loss=0.003459

      epoch   4/100: train_loss=0.002641

      epoch   5/100: train_loss=0.002191, val_loss=0.004286, IC=-0.0521

      epoch   6/100: train_loss=0.001918

      epoch   7/100: train_loss=0.001781

      epoch   8/100: train_loss=0.001776

      epoch   9/100: train_loss=0.001643

      epoch  10/100: train_loss=0.001551, val_loss=0.004873, IC=-0.0650

      epoch  11/100: train_loss=0.001533

      epoch  12/100: train_loss=0.001565

      epoch  13/100: train_loss=0.001484

      epoch  14/100: train_loss=0.001483

      epoch  15/100: train_loss=0.001345, val_loss=0.003914, IC=-0.0564

      epoch  16/100: train_loss=0.001282

      epoch  17/100: train_loss=0.001246

      epoch  18/100: train_loss=0.001211

      epoch  19/100: train_loss=0.001283

      epoch  20/100: train_loss=0.001387, val_loss=0.002930, IC=-0.0773

      epoch  21/100: train_loss=0.001319

      epoch  22/100: train_loss=0.001229

      epoch  23/100: train_loss=0.001131

      epoch  24/100: train_loss=0.001102

      epoch  25/100: train_loss=0.001051, val_loss=0.003614, IC=-0.0594

      epoch  26/100: train_loss=0.001033

      epoch  27/100: train_loss=0.001046

      epoch  28/100: train_loss=0.001020

      epoch  29/100: train_loss=0.001001

      epoch  30/100: train_loss=0.000977, val_loss=0.003197, IC=-0.0553

      epoch  31/100: train_loss=0.000975

      epoch  32/100: train_loss=0.000946

      epoch  33/100: train_loss=0.000965

      epoch  34/100: train_loss=0.000928

      epoch  35/100: train_loss=0.000995, val_loss=0.003629, IC=-0.0614

      epoch  36/100: train_loss=0.000916

      epoch  37/100: train_loss=0.001017

      epoch  38/100: train_loss=0.001013

      epoch  39/100: train_loss=0.000926

      epoch  40/100: train_loss=0.000921, val_loss=0.003774, IC=-0.0533

      epoch  41/100: train_loss=0.000852

      epoch  42/100: train_loss=0.000849

      epoch  43/100: train_loss=0.000857

      epoch  44/100: train_loss=0.000820

      epoch  45/100: train_loss=0.000840, val_loss=0.002063, IC=-0.0180

      epoch  46/100: train_loss=0.000811

      epoch  47/100: train_loss=0.000795

      epoch  48/100: train_loss=0.000795

      epoch  49/100: train_loss=0.000771

      epoch  50/100: train_loss=0.000772, val_loss=0.002728, IC=-0.0409

      epoch  51/100: train_loss=0.000783

      epoch  52/100: train_loss=0.000740

      epoch  53/100: train_loss=0.000774

      epoch  54/100: train_loss=0.000765

      epoch  55/100: train_loss=0.000723, val_loss=0.002491, IC=-0.0307

      epoch  56/100: train_loss=0.000756

      epoch  57/100: train_loss=0.000729

      epoch  58/100: train_loss=0.000720

      epoch  59/100: train_loss=0.000732

      epoch  60/100: train_loss=0.000716, val_loss=0.002824, IC=-0.0386

      epoch  61/100: train_loss=0.000708

      epoch  62/100: train_loss=0.000703

      epoch  63/100: train_loss=0.000684

      epoch  64/100: train_loss=0.000700

      epoch  65/100: train_loss=0.000669, val_loss=0.002331, IC=-0.0520

      epoch  66/100: train_loss=0.000683

      epoch  67/100: train_loss=0.000667

      epoch  68/100: train_loss=0.000672

      epoch  69/100: train_loss=0.000696

      epoch  70/100: train_loss=0.000707, val_loss=0.002161, IC=-0.0272

      epoch  71/100: train_loss=0.000683

      epoch  72/100: train_loss=0.000674

      epoch  73/100: train_loss=0.000655

      epoch  74/100: train_loss=0.000665

      epoch  75/100: train_loss=0.000669, val_loss=0.002392, IC=-0.0405

      epoch  76/100: train_loss=0.000669

      epoch  77/100: train_loss=0.000655

      epoch  78/100: train_loss=0.000656

      epoch  79/100: train_loss=0.000667

      epoch  80/100: train_loss=0.000662, val_loss=0.002324, IC=-0.0346

      epoch  81/100: train_loss=0.000652

      epoch  82/100: train_loss=0.000631

      epoch  83/100: train_loss=0.000628

      epoch  84/100: train_loss=0.000637

      epoch  85/100: train_loss=0.000638, val_loss=0.002335, IC=-0.0351

      epoch  86/100: train_loss=0.000649

      epoch  87/100: train_loss=0.000652

      epoch  88/100: train_loss=0.000672

      epoch  89/100: train_loss=0.000680

      epoch  90/100: train_loss=0.000648, val_loss=0.002201, IC=-0.0298

      epoch  91/100: train_loss=0.000648

      epoch  92/100: train_loss=0.000640

      epoch  93/100: train_loss=0.000648

      epoch  94/100: train_loss=0.000630

      epoch  95/100: train_loss=0.000642, val_loss=0.002368, IC=-0.0380

      epoch  96/100: train_loss=0.000621

      epoch  97/100: train_loss=0.000642

      epoch  98/100: train_loss=0.000646

      epoch  99/100: train_loss=0.000636

      epoch 100/100: train_loss=0.000628, val_loss=0.002318, IC=-0.0376

      best_ep=45, IC=-0.0180 (120.8s, 20 checkpoints)

  Fold 1: creating sequences...
    train=21,820 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.035568

      epoch   2/100: train_loss=0.005240

      epoch   3/100: train_loss=0.003416

      epoch   4/100: train_loss=0.002647

      epoch   5/100: train_loss=0.002364, val_loss=0.002066, IC=+0.1194

      epoch   6/100: train_loss=0.002277

      epoch   7/100: train_loss=0.002202

      epoch   8/100: train_loss=0.002101

      epoch   9/100: train_loss=0.001942

      epoch  10/100: train_loss=0.001904, val_loss=0.001530, IC=+0.0913

      epoch  11/100: train_loss=0.001982

      epoch  12/100: train_loss=0.001765

      epoch  13/100: train_loss=0.001707

      epoch  14/100: train_loss=0.001594

      epoch  15/100: train_loss=0.001555, val_loss=0.001312, IC=+0.0987

      epoch  16/100: train_loss=0.001537

      epoch  17/100: train_loss=0.001469

      epoch  18/100: train_loss=0.001432

      epoch  19/100: train_loss=0.001371

      epoch  20/100: train_loss=0.001336, val_loss=0.001262, IC=+0.0401

      epoch  21/100: train_loss=0.001355

      epoch  22/100: train_loss=0.001307

      epoch  23/100: train_loss=0.001395

      epoch  24/100: train_loss=0.001300

      epoch  25/100: train_loss=0.001253, val_loss=0.001413, IC=+0.0345

      epoch  26/100: train_loss=0.001234

      epoch  27/100: train_loss=0.001178

      epoch  28/100: train_loss=0.001160

      epoch  29/100: train_loss=0.001172

      epoch  30/100: train_loss=0.001120, val_loss=0.001299, IC=+0.0660

      epoch  31/100: train_loss=0.001171

      epoch  32/100: train_loss=0.001121

      epoch  33/100: train_loss=0.001066

      epoch  34/100: train_loss=0.001061

      epoch  35/100: train_loss=0.001057, val_loss=0.001254, IC=+0.0447

      epoch  36/100: train_loss=0.001057

      epoch  37/100: train_loss=0.001027

      epoch  38/100: train_loss=0.001010

      epoch  39/100: train_loss=0.000957

      epoch  40/100: train_loss=0.000970, val_loss=0.001194, IC=+0.0608

      epoch  41/100: train_loss=0.000984

      epoch  42/100: train_loss=0.000963

      epoch  43/100: train_loss=0.000927

      epoch  44/100: train_loss=0.000917

      epoch  45/100: train_loss=0.000935, val_loss=0.001259, IC=+0.0389

      epoch  46/100: train_loss=0.000953

      epoch  47/100: train_loss=0.000972

      epoch  48/100: train_loss=0.000920

      epoch  49/100: train_loss=0.000906

      epoch  50/100: train_loss=0.000904, val_loss=0.001205, IC=+0.0419

      epoch  51/100: train_loss=0.000892

      epoch  52/100: train_loss=0.000858

      epoch  53/100: train_loss=0.000840

      epoch  54/100: train_loss=0.000826

      epoch  55/100: train_loss=0.000852, val_loss=0.001119, IC=+0.0567

      epoch  56/100: train_loss=0.000905

      epoch  57/100: train_loss=0.000822

      epoch  58/100: train_loss=0.000801

      epoch  59/100: train_loss=0.000854

      epoch  60/100: train_loss=0.000825, val_loss=0.001227, IC=+0.0548

      epoch  61/100: train_loss=0.000813

      epoch  62/100: train_loss=0.000827

      epoch  63/100: train_loss=0.000820

      epoch  64/100: train_loss=0.000842

      epoch  65/100: train_loss=0.000815, val_loss=0.001140, IC=+0.0696

      epoch  66/100: train_loss=0.000819

      epoch  67/100: train_loss=0.000782

      epoch  68/100: train_loss=0.000764

      epoch  69/100: train_loss=0.000767

      epoch  70/100: train_loss=0.000778, val_loss=0.001122, IC=+0.0708

      epoch  71/100: train_loss=0.000751

      epoch  72/100: train_loss=0.000797

      epoch  73/100: train_loss=0.000811

      epoch  74/100: train_loss=0.000794

      epoch  75/100: train_loss=0.000762, val_loss=0.001123, IC=+0.0608

      epoch  76/100: train_loss=0.000768

      epoch  77/100: train_loss=0.000784

      epoch  78/100: train_loss=0.000733

      epoch  79/100: train_loss=0.000740

      epoch  80/100: train_loss=0.000749, val_loss=0.001105, IC=+0.0814

      epoch  81/100: train_loss=0.000746

      epoch  82/100: train_loss=0.000743

      epoch  83/100: train_loss=0.000739

      epoch  84/100: train_loss=0.000754

      epoch  85/100: train_loss=0.000737, val_loss=0.001106, IC=+0.0721

      epoch  86/100: train_loss=0.000755

      epoch  87/100: train_loss=0.000732

      epoch  88/100: train_loss=0.000740

      epoch  89/100: train_loss=0.000724

      epoch  90/100: train_loss=0.000732, val_loss=0.001092, IC=+0.0652

      epoch  91/100: train_loss=0.000738

      epoch  92/100: train_loss=0.000730

      epoch  93/100: train_loss=0.000749

      epoch  94/100: train_loss=0.000736

      epoch  95/100: train_loss=0.000725, val_loss=0.001097, IC=+0.0711

      epoch  96/100: train_loss=0.000728

      epoch  97/100: train_loss=0.000728

      epoch  98/100: train_loss=0.000705

      epoch  99/100: train_loss=0.000720

      epoch 100/100: train_loss=0.000734, val_loss=0.001090, IC=+0.0701

      best_ep=5, IC=+0.1194 (155.6s, 20 checkpoints)

  Fold 2: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.023439

      epoch   2/100: train_loss=0.004206

      epoch   3/100: train_loss=0.002743

      epoch   4/100: train_loss=0.002161

      epoch   5/100: train_loss=0.001901, val_loss=0.001589, IC=-0.0871

      epoch   6/100: train_loss=0.001801

      epoch   7/100: train_loss=0.001671

      epoch   8/100: train_loss=0.001600

      epoch   9/100: train_loss=0.001542

      epoch  10/100: train_loss=0.001398, val_loss=0.001108, IC=-0.0593

      epoch  11/100: train_loss=0.001379

      epoch  12/100: train_loss=0.001339

      epoch  13/100: train_loss=0.001243

      epoch  14/100: train_loss=0.001209

      epoch  15/100: train_loss=0.001181, val_loss=0.001073, IC=-0.0739

      epoch  16/100: train_loss=0.001181

      epoch  17/100: train_loss=0.001104

      epoch  18/100: train_loss=0.001101

      epoch  19/100: train_loss=0.001048

      epoch  20/100: train_loss=0.001022, val_loss=0.001026, IC=-0.0659

      epoch  21/100: train_loss=0.000988

      epoch  22/100: train_loss=0.001030

      epoch  23/100: train_loss=0.001008

      epoch  24/100: train_loss=0.000956

      epoch  25/100: train_loss=0.000950, val_loss=0.000908, IC=-0.0136

      epoch  26/100: train_loss=0.000950

      epoch  27/100: train_loss=0.000920

      epoch  28/100: train_loss=0.000890

      epoch  29/100: train_loss=0.000864

      epoch  30/100: train_loss=0.000860, val_loss=0.000915, IC=-0.0247

      epoch  31/100: train_loss=0.000818

      epoch  32/100: train_loss=0.000813

      epoch  33/100: train_loss=0.000805

      epoch  34/100: train_loss=0.000795

      epoch  35/100: train_loss=0.000766, val_loss=0.000866, IC=-0.0341

      epoch  36/100: train_loss=0.000761

      epoch  37/100: train_loss=0.000753

      epoch  38/100: train_loss=0.000753

      epoch  39/100: train_loss=0.000744

      epoch  40/100: train_loss=0.000738, val_loss=0.000840, IC=-0.0084

      epoch  41/100: train_loss=0.000731

      epoch  42/100: train_loss=0.000754

      epoch  43/100: train_loss=0.000718

      epoch  44/100: train_loss=0.000721

      epoch  45/100: train_loss=0.000742, val_loss=0.000826, IC=-0.0082

      epoch  46/100: train_loss=0.000709

      epoch  47/100: train_loss=0.000681

      epoch  48/100: train_loss=0.000714

      epoch  49/100: train_loss=0.000672

      epoch  50/100: train_loss=0.000703, val_loss=0.000932, IC=-0.0474

      epoch  51/100: train_loss=0.000676

      epoch  52/100: train_loss=0.000674

      epoch  53/100: train_loss=0.000659

      epoch  54/100: train_loss=0.000704

      epoch  55/100: train_loss=0.000689, val_loss=0.000865, IC=-0.0473

      epoch  56/100: train_loss=0.000652

      epoch  57/100: train_loss=0.000641

      epoch  58/100: train_loss=0.000627

      epoch  59/100: train_loss=0.000619

      epoch  60/100: train_loss=0.000627, val_loss=0.000806, IC=+0.0031

      epoch  61/100: train_loss=0.000629

      epoch  62/100: train_loss=0.000621

      epoch  63/100: train_loss=0.000603

      epoch  64/100: train_loss=0.000606

      epoch  65/100: train_loss=0.000600, val_loss=0.000853, IC=-0.0424

      epoch  66/100: train_loss=0.000599

      epoch  67/100: train_loss=0.000606

      epoch  68/100: train_loss=0.000587

      epoch  69/100: train_loss=0.000600

      epoch  70/100: train_loss=0.000592, val_loss=0.000896, IC=-0.0412

      epoch  71/100: train_loss=0.000590

      epoch  72/100: train_loss=0.000598

      epoch  73/100: train_loss=0.000592

      epoch  74/100: train_loss=0.000595

      epoch  75/100: train_loss=0.000577, val_loss=0.000968, IC=-0.0543

      epoch  76/100: train_loss=0.000579

      epoch  77/100: train_loss=0.000571

      epoch  78/100: train_loss=0.000586

      epoch  79/100: train_loss=0.000575

      epoch  80/100: train_loss=0.000573, val_loss=0.000874, IC=-0.0424

      epoch  81/100: train_loss=0.000576

      epoch  82/100: train_loss=0.000570

      epoch  83/100: train_loss=0.000570

      epoch  84/100: train_loss=0.000569

      epoch  85/100: train_loss=0.000561, val_loss=0.000904, IC=-0.0493

      epoch  86/100: train_loss=0.000578

      epoch  87/100: train_loss=0.000568

      epoch  88/100: train_loss=0.000563

      epoch  89/100: train_loss=0.000559

      epoch  90/100: train_loss=0.000564, val_loss=0.000911, IC=-0.0513

      epoch  91/100: train_loss=0.000568

      epoch  92/100: train_loss=0.000562

      epoch  93/100: train_loss=0.000559

      epoch  94/100: train_loss=0.000558

      epoch  95/100: train_loss=0.000560, val_loss=0.000906, IC=-0.0508

      epoch  96/100: train_loss=0.000555

      epoch  97/100: train_loss=0.000563

      epoch  98/100: train_loss=0.000559

      epoch  99/100: train_loss=0.000571

      epoch 100/100: train_loss=0.000573, val_loss=0.000907, IC=-0.0520

      best_ep=60, IC=+0.0031 (143.5s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.079321

      epoch   2/100: train_loss=0.006599

      epoch   3/100: train_loss=0.003866

      epoch   4/100: train_loss=0.002878

      epoch   5/100: train_loss=0.002438, val_loss=0.001502, IC=+0.0626

      epoch   6/100: train_loss=0.002207

      epoch   7/100: train_loss=0.002133

      epoch   8/100: train_loss=0.001983

      epoch   9/100: train_loss=0.001866

      epoch  10/100: train_loss=0.001835, val_loss=0.000992, IC=+0.0885

      epoch  11/100: train_loss=0.001814

      epoch  12/100: train_loss=0.001726

      epoch  13/100: train_loss=0.001707

      epoch  14/100: train_loss=0.001630

      epoch  15/100: train_loss=0.001562, val_loss=0.000869, IC=+0.0710

      epoch  16/100: train_loss=0.001596

      epoch  17/100: train_loss=0.001439

      epoch  18/100: train_loss=0.001362

      epoch  19/100: train_loss=0.001323

      epoch  20/100: train_loss=0.001319, val_loss=0.000756, IC=+0.0538

      epoch  21/100: train_loss=0.001265

      epoch  22/100: train_loss=0.001273

      epoch  23/100: train_loss=0.001297

      epoch  24/100: train_loss=0.001238

      epoch  25/100: train_loss=0.001159, val_loss=0.000717, IC=+0.0689

      epoch  26/100: train_loss=0.001199

      epoch  27/100: train_loss=0.001149

      epoch  28/100: train_loss=0.001074

      epoch  29/100: train_loss=0.001066

      epoch  30/100: train_loss=0.001078, val_loss=0.000638, IC=+0.0490

      epoch  31/100: train_loss=0.001019

      epoch  32/100: train_loss=0.001027

      epoch  33/100: train_loss=0.001018

      epoch  34/100: train_loss=0.001002

      epoch  35/100: train_loss=0.001018, val_loss=0.000620, IC=+0.0371

      epoch  36/100: train_loss=0.000968

      epoch  37/100: train_loss=0.000947

      epoch  38/100: train_loss=0.000944

      epoch  39/100: train_loss=0.000979

      epoch  40/100: train_loss=0.000938, val_loss=0.000604, IC=+0.0546

      epoch  41/100: train_loss=0.000930

      epoch  42/100: train_loss=0.000912

      epoch  43/100: train_loss=0.000890

      epoch  44/100: train_loss=0.000893

      epoch  45/100: train_loss=0.000870, val_loss=0.000615, IC=+0.0260

      epoch  46/100: train_loss=0.000877

      epoch  47/100: train_loss=0.000952

      epoch  48/100: train_loss=0.000888

      epoch  49/100: train_loss=0.000834

      epoch  50/100: train_loss=0.000820, val_loss=0.000614, IC=+0.0071

      epoch  51/100: train_loss=0.000852

      epoch  52/100: train_loss=0.000815

      epoch  53/100: train_loss=0.000822

      epoch  54/100: train_loss=0.000859

      epoch  55/100: train_loss=0.000852, val_loss=0.000619, IC=+0.0157

      epoch  56/100: train_loss=0.000822

      epoch  57/100: train_loss=0.000803

      epoch  58/100: train_loss=0.000781

      epoch  59/100: train_loss=0.000811

      epoch  60/100: train_loss=0.000802, val_loss=0.000613, IC=+0.0269

      epoch  61/100: train_loss=0.000789

      epoch  62/100: train_loss=0.000768

      epoch  63/100: train_loss=0.000756

      epoch  64/100: train_loss=0.000749

      epoch  65/100: train_loss=0.000771, val_loss=0.000626, IC=+0.0385

      epoch  66/100: train_loss=0.000761

      epoch  67/100: train_loss=0.000790

      epoch  68/100: train_loss=0.000749

      epoch  69/100: train_loss=0.000774

      epoch  70/100: train_loss=0.000731, val_loss=0.000644, IC=+0.0323

      epoch  71/100: train_loss=0.000728

      epoch  72/100: train_loss=0.000741

      epoch  73/100: train_loss=0.000711

      epoch  74/100: train_loss=0.000718

      epoch  75/100: train_loss=0.000735, val_loss=0.000638, IC=+0.0184

      epoch  76/100: train_loss=0.000711

      epoch  77/100: train_loss=0.000718

      epoch  78/100: train_loss=0.000733

      epoch  79/100: train_loss=0.000706

      epoch  80/100: train_loss=0.000704, val_loss=0.000634, IC=+0.0200

      epoch  81/100: train_loss=0.000710

      epoch  82/100: train_loss=0.000706

      epoch  83/100: train_loss=0.000702

      epoch  84/100: train_loss=0.000688

      epoch  85/100: train_loss=0.000694, val_loss=0.000633, IC=+0.0247

      epoch  86/100: train_loss=0.000709

      epoch  87/100: train_loss=0.000687

      epoch  88/100: train_loss=0.000699

      epoch  89/100: train_loss=0.000702

      epoch  90/100: train_loss=0.000681, val_loss=0.000629, IC=+0.0190

      epoch  91/100: train_loss=0.000692

      epoch  92/100: train_loss=0.000676

      epoch  93/100: train_loss=0.000697

      epoch  94/100: train_loss=0.000709

      epoch  95/100: train_loss=0.000699, val_loss=0.000646, IC=+0.0216

      epoch  96/100: train_loss=0.000696

      epoch  97/100: train_loss=0.000700

      epoch  98/100: train_loss=0.000674

      epoch  99/100: train_loss=0.000691

      epoch 100/100: train_loss=0.000694, val_loss=0.000641, IC=+0.0211

      best_ep=10, IC=+0.0885 (134.7s, 20 checkpoints)

  Fold 4: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.203939

      epoch   2/100: train_loss=0.009013

      epoch   3/100: train_loss=0.003222

      epoch   4/100: train_loss=0.002043

      epoch   5/100: train_loss=0.001701, val_loss=0.002126, IC=+0.1800

      epoch   6/100: train_loss=0.001574

      epoch   7/100: train_loss=0.001367

      epoch   8/100: train_loss=0.001453

      epoch   9/100: train_loss=0.001308

      epoch  10/100: train_loss=0.001278, val_loss=0.002116, IC=+0.1115

      epoch  11/100: train_loss=0.001236

      epoch  12/100: train_loss=0.001109

      epoch  13/100: train_loss=0.001184

      epoch  14/100: train_loss=0.001081

      epoch  15/100: train_loss=0.001067, val_loss=0.001784, IC=+0.1258

      epoch  16/100: train_loss=0.000968

      epoch  17/100: train_loss=0.001124

      epoch  18/100: train_loss=0.001087

      epoch  19/100: train_loss=0.000909

      epoch  20/100: train_loss=0.000929, val_loss=0.002744, IC=+0.1324

      epoch  21/100: train_loss=0.001040

      epoch  22/100: train_loss=0.000894

      epoch  23/100: train_loss=0.000895

      epoch  24/100: train_loss=0.000849

      epoch  25/100: train_loss=0.000864, val_loss=0.001611, IC=-0.0179

      epoch  26/100: train_loss=0.000897

      epoch  27/100: train_loss=0.000860

      epoch  28/100: train_loss=0.000754

      epoch  29/100: train_loss=0.000765

      epoch  30/100: train_loss=0.000946, val_loss=0.001464, IC=+0.0128

      epoch  31/100: train_loss=0.000762

      epoch  32/100: train_loss=0.000744

      epoch  33/100: train_loss=0.000747

      epoch  34/100: train_loss=0.000762

      epoch  35/100: train_loss=0.000721, val_loss=0.001586, IC=-0.0417

      epoch  36/100: train_loss=0.000750

      epoch  37/100: train_loss=0.000838

      epoch  38/100: train_loss=0.000812

      epoch  39/100: train_loss=0.000799

      epoch  40/100: train_loss=0.000706, val_loss=0.001915, IC=+0.0286

      epoch  41/100: train_loss=0.000756

      epoch  42/100: train_loss=0.000653

      epoch  43/100: train_loss=0.000677

      epoch  44/100: train_loss=0.000667

      epoch  45/100: train_loss=0.000679, val_loss=0.001991, IC=+0.0082

      epoch  46/100: train_loss=0.000718

      epoch  47/100: train_loss=0.000621

      epoch  48/100: train_loss=0.000643

      epoch  49/100: train_loss=0.000674

      epoch  50/100: train_loss=0.000616, val_loss=0.001686, IC=-0.0132

      epoch  51/100: train_loss=0.000652

      epoch  52/100: train_loss=0.000668

      epoch  53/100: train_loss=0.000580

      epoch  54/100: train_loss=0.000567

      epoch  55/100: train_loss=0.000608, val_loss=0.001460, IC=-0.0473

      epoch  56/100: train_loss=0.000569

      epoch  57/100: train_loss=0.000552

      epoch  58/100: train_loss=0.000579

      epoch  59/100: train_loss=0.000602

      epoch  60/100: train_loss=0.000609, val_loss=0.001477, IC=-0.0606

      epoch  61/100: train_loss=0.000587

      epoch  62/100: train_loss=0.000589

      epoch  63/100: train_loss=0.000587

      epoch  64/100: train_loss=0.000564

      epoch  65/100: train_loss=0.000567, val_loss=0.001529, IC=-0.0250

      epoch  66/100: train_loss=0.000536

      epoch  67/100: train_loss=0.000553

      epoch  68/100: train_loss=0.000580

      epoch  69/100: train_loss=0.000629

      epoch  70/100: train_loss=0.000596, val_loss=0.001529, IC=-0.0593

      epoch  71/100: train_loss=0.000546

      epoch  72/100: train_loss=0.000536

      epoch  73/100: train_loss=0.000520

      epoch  74/100: train_loss=0.000521

      epoch  75/100: train_loss=0.000571, val_loss=0.001550, IC=-0.0339

      epoch  76/100: train_loss=0.000521

      epoch  77/100: train_loss=0.000558

      epoch  78/100: train_loss=0.000570

      epoch  79/100: train_loss=0.000535

      epoch  80/100: train_loss=0.000541, val_loss=0.001568, IC=-0.0753

      epoch  81/100: train_loss=0.000529

      epoch  82/100: train_loss=0.000526

      epoch  83/100: train_loss=0.000543

      epoch  84/100: train_loss=0.000530

      epoch  85/100: train_loss=0.000510, val_loss=0.001510, IC=-0.0448

      epoch  86/100: train_loss=0.000506

      epoch  87/100: train_loss=0.000520

      epoch  88/100: train_loss=0.000548

      epoch  89/100: train_loss=0.000536

      epoch  90/100: train_loss=0.000525, val_loss=0.001537, IC=-0.0395

      epoch  91/100: train_loss=0.000543

      epoch  92/100: train_loss=0.000510

      epoch  93/100: train_loss=0.000511

      epoch  94/100: train_loss=0.000523

      epoch  95/100: train_loss=0.000507, val_loss=0.001510, IC=-0.0466

      epoch  96/100: train_loss=0.000525

      epoch  97/100: train_loss=0.000481

      epoch  98/100: train_loss=0.000511

      epoch  99/100: train_loss=0.000496

      epoch 100/100: train_loss=0.000514, val_loss=0.001500, IC=-0.0472

      best_ep=5, IC=+0.1800 (136.1s, 20 checkpoints)

  Fold 5: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.528971

      epoch   2/100: train_loss=0.013143

      epoch   3/100: train_loss=0.004788

      epoch   4/100: train_loss=0.002873

      epoch   5/100: train_loss=0.002253, val_loss=0.001043, IC=+0.0721

      epoch   6/100: train_loss=0.001856

      epoch   7/100: train_loss=0.001736

      epoch   8/100: train_loss=0.001761

      epoch   9/100: train_loss=0.001549

      epoch  10/100: train_loss=0.001477, val_loss=0.000805, IC=+0.0659

      epoch  11/100: train_loss=0.001430

      epoch  12/100: train_loss=0.001482

      epoch  13/100: train_loss=0.001410

      epoch  14/100: train_loss=0.001166

      epoch  15/100: train_loss=0.001213, val_loss=0.000674, IC=+0.0900

      epoch  16/100: train_loss=0.001316

      epoch  17/100: train_loss=0.001178

      epoch  18/100: train_loss=0.001310

      epoch  19/100: train_loss=0.001138

      epoch  20/100: train_loss=0.001135, val_loss=0.000744, IC=+0.0592

      epoch  21/100: train_loss=0.001078

      epoch  22/100: train_loss=0.001091

      epoch  23/100: train_loss=0.000984

      epoch  24/100: train_loss=0.000998

      epoch  25/100: train_loss=0.000915, val_loss=0.000662, IC=+0.0571

      epoch  26/100: train_loss=0.000962

      epoch  27/100: train_loss=0.001002

      epoch  28/100: train_loss=0.001067

      epoch  29/100: train_loss=0.001070

      epoch  30/100: train_loss=0.000975, val_loss=0.000665, IC=+0.0633

      epoch  31/100: train_loss=0.000891

      epoch  32/100: train_loss=0.000875

      epoch  33/100: train_loss=0.000854

      epoch  34/100: train_loss=0.000848

      epoch  35/100: train_loss=0.000847, val_loss=0.000675, IC=+0.0801

      epoch  36/100: train_loss=0.000860

      epoch  37/100: train_loss=0.000805

      epoch  38/100: train_loss=0.000837

      epoch  39/100: train_loss=0.000807

      epoch  40/100: train_loss=0.000745, val_loss=0.000691, IC=+0.0764

      epoch  41/100: train_loss=0.000743

      epoch  42/100: train_loss=0.000719

      epoch  43/100: train_loss=0.000768

      epoch  44/100: train_loss=0.000725

      epoch  45/100: train_loss=0.000801, val_loss=0.000701, IC=+0.0835

      epoch  46/100: train_loss=0.000737

      epoch  47/100: train_loss=0.000697

      epoch  48/100: train_loss=0.000713

      epoch  49/100: train_loss=0.000762

      epoch  50/100: train_loss=0.000749, val_loss=0.000668, IC=+0.0870

      epoch  51/100: train_loss=0.000716

      epoch  52/100: train_loss=0.000694

      epoch  53/100: train_loss=0.000755

      epoch  54/100: train_loss=0.000752

      epoch  55/100: train_loss=0.000689, val_loss=0.000664, IC=+0.0981

      epoch  56/100: train_loss=0.000702

      epoch  57/100: train_loss=0.000637

      epoch  58/100: train_loss=0.000640

      epoch  59/100: train_loss=0.000616

      epoch  60/100: train_loss=0.000631, val_loss=0.000716, IC=+0.0957

      epoch  61/100: train_loss=0.000628

      epoch  62/100: train_loss=0.000643

      epoch  63/100: train_loss=0.000634

      epoch  64/100: train_loss=0.000643

      epoch  65/100: train_loss=0.000625, val_loss=0.000686, IC=+0.0944

      epoch  66/100: train_loss=0.000598

      epoch  67/100: train_loss=0.000621

      epoch  68/100: train_loss=0.000575

      epoch  69/100: train_loss=0.000595

      epoch  70/100: train_loss=0.000578, val_loss=0.000668, IC=+0.0951

      epoch  71/100: train_loss=0.000592

      epoch  72/100: train_loss=0.000612

      epoch  73/100: train_loss=0.000596

      epoch  74/100: train_loss=0.000593

      epoch  75/100: train_loss=0.000588, val_loss=0.000726, IC=+0.0884

      epoch  76/100: train_loss=0.000621

      epoch  77/100: train_loss=0.000581

      epoch  78/100: train_loss=0.000593

      epoch  79/100: train_loss=0.000596

      epoch  80/100: train_loss=0.000576, val_loss=0.000705, IC=+0.0917

      epoch  81/100: train_loss=0.000597

      epoch  82/100: train_loss=0.000570

      epoch  83/100: train_loss=0.000596

      epoch  84/100: train_loss=0.000601

      epoch  85/100: train_loss=0.000595, val_loss=0.000725, IC=+0.0878

      epoch  86/100: train_loss=0.000608

      epoch  87/100: train_loss=0.000573

      epoch  88/100: train_loss=0.000576

      epoch  89/100: train_loss=0.000564

      epoch  90/100: train_loss=0.000557, val_loss=0.000698, IC=+0.0894

      epoch  91/100: train_loss=0.000562

      epoch  92/100: train_loss=0.000562

      epoch  93/100: train_loss=0.000576

      epoch  94/100: train_loss=0.000566

      epoch  95/100: train_loss=0.000578, val_loss=0.000699, IC=+0.0892

      epoch  96/100: train_loss=0.000558

      epoch  97/100: train_loss=0.000570

      epoch  98/100: train_loss=0.000573

      epoch  99/100: train_loss=0.000547

      epoch 100/100: train_loss=0.000567, val_loss=0.000696, IC=+0.0906

      best_ep=55, IC=+0.0981 (150.8s, 20 checkpoints)

  Fold 6: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.043205

      epoch   2/100: train_loss=0.005510

      epoch   3/100: train_loss=0.002966

      epoch   4/100: train_loss=0.002341

      epoch   5/100: train_loss=0.002029, val_loss=0.010446, IC=-0.0646

      epoch   6/100: train_loss=0.001895

      epoch   7/100: train_loss=0.001762

      epoch   8/100: train_loss=0.001639

      epoch   9/100: train_loss=0.001530

      epoch  10/100: train_loss=0.001497, val_loss=0.004844, IC=-0.0509

      epoch  11/100: train_loss=0.001428

      epoch  12/100: train_loss=0.001453

      epoch  13/100: train_loss=0.001366

      epoch  14/100: train_loss=0.001396

      epoch  15/100: train_loss=0.001273, val_loss=0.003389, IC=-0.0365

      epoch  16/100: train_loss=0.001230

      epoch  17/100: train_loss=0.001177

      epoch  18/100: train_loss=0.001167

      epoch  19/100: train_loss=0.001125

      epoch  20/100: train_loss=0.001080, val_loss=0.003190, IC=-0.0195

      epoch  21/100: train_loss=0.001098

      epoch  22/100: train_loss=0.001028

      epoch  23/100: train_loss=0.001034

      epoch  24/100: train_loss=0.001009

      epoch  25/100: train_loss=0.000980, val_loss=0.002697, IC=+0.0223

      epoch  26/100: train_loss=0.000947

      epoch  27/100: train_loss=0.000918

      epoch  28/100: train_loss=0.000957

      epoch  29/100: train_loss=0.000979

      epoch  30/100: train_loss=0.000876, val_loss=0.002599, IC=+0.0183

      epoch  31/100: train_loss=0.000855

      epoch  32/100: train_loss=0.000853

      epoch  33/100: train_loss=0.000880

      epoch  34/100: train_loss=0.000808

      epoch  35/100: train_loss=0.000813, val_loss=0.002767, IC=+0.0334

      epoch  36/100: train_loss=0.000817

      epoch  37/100: train_loss=0.000794

      epoch  38/100: train_loss=0.000781

      epoch  39/100: train_loss=0.000776

      epoch  40/100: train_loss=0.000822, val_loss=0.002288, IC=+0.0234

      epoch  41/100: train_loss=0.000775

      epoch  42/100: train_loss=0.000781

      epoch  43/100: train_loss=0.000727

      epoch  44/100: train_loss=0.000694

      epoch  45/100: train_loss=0.000717, val_loss=0.002005, IC=+0.0337

      epoch  46/100: train_loss=0.000709

      epoch  47/100: train_loss=0.000739

      epoch  48/100: train_loss=0.000707

      epoch  49/100: train_loss=0.000674

      epoch  50/100: train_loss=0.000677, val_loss=0.002238, IC=+0.0170

      epoch  51/100: train_loss=0.000655

      epoch  52/100: train_loss=0.000648

      epoch  53/100: train_loss=0.000664

      epoch  54/100: train_loss=0.000651

      epoch  55/100: train_loss=0.000653, val_loss=0.001947, IC=+0.0254

      epoch  56/100: train_loss=0.000617

      epoch  57/100: train_loss=0.000619

      epoch  58/100: train_loss=0.000617

      epoch  59/100: train_loss=0.000613

      epoch  60/100: train_loss=0.000627, val_loss=0.002147, IC=+0.0066

      epoch  61/100: train_loss=0.000625

      epoch  62/100: train_loss=0.000615

      epoch  63/100: train_loss=0.000604

      epoch  64/100: train_loss=0.000611

      epoch  65/100: train_loss=0.000600, val_loss=0.002186, IC=+0.0240

      epoch  66/100: train_loss=0.000596

      epoch  67/100: train_loss=0.000586

      epoch  68/100: train_loss=0.000600

      epoch  69/100: train_loss=0.000585

      epoch  70/100: train_loss=0.000580, val_loss=0.002063, IC=+0.0238

      epoch  71/100: train_loss=0.000602

      epoch  72/100: train_loss=0.000574

      epoch  73/100: train_loss=0.000570

      epoch  74/100: train_loss=0.000573

      epoch  75/100: train_loss=0.000574, val_loss=0.001857, IC=+0.0266

      epoch  76/100: train_loss=0.000569

      epoch  77/100: train_loss=0.000572

      epoch  78/100: train_loss=0.000571

      epoch  79/100: train_loss=0.000573

      epoch  80/100: train_loss=0.000564, val_loss=0.001864, IC=+0.0281

      epoch  81/100: train_loss=0.000562

      epoch  82/100: train_loss=0.000551

      epoch  83/100: train_loss=0.000557

      epoch  84/100: train_loss=0.000553

      epoch  85/100: train_loss=0.000552, val_loss=0.001905, IC=+0.0233

      epoch  86/100: train_loss=0.000558

      epoch  87/100: train_loss=0.000555

      epoch  88/100: train_loss=0.000557

      epoch  89/100: train_loss=0.000561

      epoch  90/100: train_loss=0.000554, val_loss=0.001930, IC=+0.0226

      epoch  91/100: train_loss=0.000537

      epoch  92/100: train_loss=0.000554

      epoch  93/100: train_loss=0.000546

      epoch  94/100: train_loss=0.000556

      epoch  95/100: train_loss=0.000549, val_loss=0.001890, IC=+0.0233

      epoch  96/100: train_loss=0.000553

      epoch  97/100: train_loss=0.000556

      epoch  98/100: train_loss=0.000542

      epoch  99/100: train_loss=0.000551

      epoch 100/100: train_loss=0.000547, val_loss=0.001890, IC=+0.0231

      best_ep=45, IC=+0.0337 (147.0s, 20 checkpoints)

  Fold 7: creating sequences...

    train=24,180 seq across 20 symbols
    val=4,740 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.056005

      epoch   2/100: train_loss=0.006707

      epoch   3/100: train_loss=0.003806

      epoch   4/100: train_loss=0.002795

      epoch   5/100: train_loss=0.002432, val_loss=0.002133, IC=+0.0459

      epoch   6/100: train_loss=0.002211

      epoch   7/100: train_loss=0.002102

      epoch   8/100: train_loss=0.001936

      epoch   9/100: train_loss=0.001807

      epoch  10/100: train_loss=0.001734, val_loss=0.001898, IC=+0.0473

      epoch  11/100: train_loss=0.001649

      epoch  12/100: train_loss=0.001568

      epoch  13/100: train_loss=0.001565

      epoch  14/100: train_loss=0.001511

      epoch  15/100: train_loss=0.001407, val_loss=0.001544, IC=+0.0220

      epoch  16/100: train_loss=0.001388

      epoch  17/100: train_loss=0.001352

      epoch  18/100: train_loss=0.001375

      epoch  19/100: train_loss=0.001315

      epoch  20/100: train_loss=0.001280, val_loss=0.001810, IC=+0.0122

      epoch  21/100: train_loss=0.001294

      epoch  22/100: train_loss=0.001195

      epoch  23/100: train_loss=0.001133

      epoch  24/100: train_loss=0.001122

      epoch  25/100: train_loss=0.001110, val_loss=0.001546, IC=-0.0085

      epoch  26/100: train_loss=0.001120

      epoch  27/100: train_loss=0.001053

      epoch  28/100: train_loss=0.000986

      epoch  29/100: train_loss=0.000987

      epoch  30/100: train_loss=0.001011, val_loss=0.001255, IC=-0.0273

      epoch  31/100: train_loss=0.000972

      epoch  32/100: train_loss=0.000952

      epoch  33/100: train_loss=0.000958

      epoch  34/100: train_loss=0.000887

      epoch  35/100: train_loss=0.000887, val_loss=0.001247, IC=-0.0387

      epoch  36/100: train_loss=0.000899

      epoch  37/100: train_loss=0.000857

      epoch  38/100: train_loss=0.000822

      epoch  39/100: train_loss=0.000816

      epoch  40/100: train_loss=0.000832, val_loss=0.001234, IC=-0.0581

      epoch  41/100: train_loss=0.000806

      epoch  42/100: train_loss=0.000816

      epoch  43/100: train_loss=0.000792

      epoch  44/100: train_loss=0.000777

      epoch  45/100: train_loss=0.000814, val_loss=0.001164, IC=-0.0253

      epoch  46/100: train_loss=0.000801

      epoch  47/100: train_loss=0.000762

      epoch  48/100: train_loss=0.000742

      epoch  49/100: train_loss=0.000758

      epoch  50/100: train_loss=0.000733, val_loss=0.001087, IC=-0.0089

      epoch  51/100: train_loss=0.000744

      epoch  52/100: train_loss=0.000724

      epoch  53/100: train_loss=0.000683

      epoch  54/100: train_loss=0.000684

      epoch  55/100: train_loss=0.000677, val_loss=0.001039, IC=-0.0176

      epoch  56/100: train_loss=0.000664

      epoch  57/100: train_loss=0.000669

      epoch  58/100: train_loss=0.000662

      epoch  59/100: train_loss=0.000649

      epoch  60/100: train_loss=0.000649, val_loss=0.001009, IC=-0.0018

      epoch  61/100: train_loss=0.000655

      epoch  62/100: train_loss=0.000645

      epoch  63/100: train_loss=0.000641

      epoch  64/100: train_loss=0.000664

      epoch  65/100: train_loss=0.000628, val_loss=0.000990, IC=+0.0015

      epoch  66/100: train_loss=0.000623

      epoch  67/100: train_loss=0.000629

      epoch  68/100: train_loss=0.000622

      epoch  69/100: train_loss=0.000639

      epoch  70/100: train_loss=0.000621, val_loss=0.001011, IC=+0.0153

      epoch  71/100: train_loss=0.000641

      epoch  72/100: train_loss=0.000610

      epoch  73/100: train_loss=0.000607

      epoch  74/100: train_loss=0.000572

      epoch  75/100: train_loss=0.000582, val_loss=0.000961, IC=-0.0004

      epoch  76/100: train_loss=0.000590

      epoch  77/100: train_loss=0.000609

      epoch  78/100: train_loss=0.000594

      epoch  79/100: train_loss=0.000602

      epoch  80/100: train_loss=0.000607, val_loss=0.000978, IC=+0.0083

      epoch  81/100: train_loss=0.000590

      epoch  82/100: train_loss=0.000578

      epoch  83/100: train_loss=0.000578

      epoch  84/100: train_loss=0.000590

      epoch  85/100: train_loss=0.000607, val_loss=0.000976, IC=+0.0094

      epoch  86/100: train_loss=0.000596

      epoch  87/100: train_loss=0.000572

      epoch  88/100: train_loss=0.000593

      epoch  89/100: train_loss=0.000573

      epoch  90/100: train_loss=0.000593, val_loss=0.000973, IC=+0.0023

      epoch  91/100: train_loss=0.000586

      epoch  92/100: train_loss=0.000583

      epoch  93/100: train_loss=0.000584

      epoch  94/100: train_loss=0.000568

      epoch  95/100: train_loss=0.000574, val_loss=0.000976, IC=+0.0056

      epoch  96/100: train_loss=0.000587

      epoch  97/100: train_loss=0.000574

      epoch  98/100: train_loss=0.000571

      epoch  99/100: train_loss=0.000578

      epoch 100/100: train_loss=0.000584, val_loss=0.000972, IC=+0.0040

      best_ep=10, IC=+0.0473 (139.6s, 20 checkpoints)

  tcn: best_epoch=5, IC=+0.0344 (1128.0s)

  Best: tcn @ epoch 5 (IC=+0.0344)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/1c1ca12dc9b6/diagnostics

shape: (60, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ label      ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean  ┆ ic_t     ┆ training_ ┆ predictio │
│ ---        ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---      ┆ ---      ┆ hash      ┆ n_hash    │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64      ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆ i64       ┆   ┆          ┆          ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 5         ┆ … ┆ 0.010851 ┆ 1.403768 ┆ 8caab3d93 ┆ 7119a476d │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 247       ┆ d86       │
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 10        ┆ … ┆ 0.01495  ┆ 2.052329 ┆ 8caab3d93 ┆ 0eb73fea6 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 247       ┆ afa       │
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 15        ┆ … ┆ 0.002199 ┆ 0.215816 ┆ 8caab3d93 ┆ 6c76e9b23 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 247       ┆ 070       │
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 20        ┆ … ┆ 0.009732 ┆ 1.200962 ┆ 8caab3d93 ┆ 8a3d62b26 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 247       ┆ ac1       │
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 25        ┆ … ┆ 0.004078 ┆ 0.550297 ┆ 8caab3d93 ┆ 24a463685 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 247       ┆ 007       │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 80        ┆ … ┆ 0.007721 ┆ 0.967637 ┆ 1978f50dd ┆ c8150226d │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 33b       ┆ 3a3       │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 85        ┆ … ┆ 0.009165 ┆ 1.085807 ┆ 1978f50dd ┆ 2628a9369 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 33b       ┆ fae       │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 90        ┆ … ┆ 0.009174 ┆ 1.098892 ┆ 1978f50dd ┆ fc57f2fa7 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 33b       ┆ 969       │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 95        ┆ … ┆ 0.007888 ┆ 0.932406 ┆ 1978f50dd ┆ 8d42416b4 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 33b       ┆ 24a       │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 100       ┆ … ┆ 0.008676 ┆ 1.02419  ┆ 1978f50dd ┆ e2b818b7e │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 33b       ┆ 60d       │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

## Reload the fitted state

An identical call validates the saved weights and returns the same prediction identities. The
comparison with other model families belongs in `12_model_analysis` after every family completes.

In [6]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("TCN checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview sequence checkpoints remain outside official comparisons.")

Official prediction population: c7951a3956bb

## Key takeaways

- Eligibility is defined by consecutive observations at the declared daily cadence.
- Validation priming uses earlier observable rows without admitting training targets.
- Every saved epoch checkpoint remains available to the backtest stage.