# Temporal Convolutional Network - FX Pairs

A temporal convolutional network reads a fixed number of consecutive daily observations for each
currency pair. A missing daily observation invalidates every lookback window that crosses it. The
shared sequence runner derives that eligible endpoint grid, primes each validation fold only with
observable earlier rows, saves epoch checkpoints, and publishes predictions against the same grid.

**Learning objectives**

- Define one sequence-model request without rebuilding windows in the notebook.
- Inspect the cadence-aware eligibility and checkpoint identities recorded by the runner.
- Reload fitted weights and pass complete predictions through the shared catalog.

**Book reference**: Chapter 13, Sections 13.2 and 13.4

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published TCN FX configuration."""

import json

import polars as pl
import yaml

from case_studies.research import ExecutionTier, Study, plan_models
from utils.modeling import load_configs
from utils.paths import get_case_study_dir
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
LOOKBACK = 0
BATCH_SIZE = 0
DEVICE = "cuda"
SEED = 42

## Plan the sequence request

Fold and symbol reductions create a preview. Epochs, lookback length, and batch size are visible
model overrides: changing any of them creates a different training identity. Planning resolves
that identity, the eligible validation keys, and every declared epoch checkpoint before any
training starts.

In [3]:
set_global_seeds(SEED)
case_dir = get_case_study_dir(CASE_STUDY_ID)
setup = yaml.safe_load((case_dir / "config" / "setup.yaml").read_text())
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [setup["labels"]["primary"], *setup["labels"].get("variants", [])]
)

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

reductions = {
    **({"folds": list(range(MAX_FOLDS))} if MAX_FOLDS else {}),
    **({"max_symbols": MAX_SYMBOLS} if MAX_SYMBOLS else {}),
}
tier = ExecutionTier.PREVIEW if reductions else ExecutionTier.CANONICAL
overrides = {
    "device": DEVICE,
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
    **({"lookback": LOOKBACK} if LOOKBACK else {}),
}
study = Study.regenerate(CASE_STUDY_ID)
ARCHITECTURE = "tcn"
menu = {
    label: [
        config["config_name"]
        for config in load_configs(CASE_STUDY_ID, label, family="deep_learning")
    ]
    for label in labels
}
uncovered = {label: sorted(set(names) - {ARCHITECTURE}) for label, names in menu.items()}
for label, names in menu.items():
    if ARCHITECTURE not in names:
        raise RuntimeError(
            f"{ARCHITECTURE} is not in the configured deep_learning menu for {label}: {names}"
        )

requests = [
    study.model(
        family="deep_learning",
        label=label,
        config_name=ARCHITECTURE,
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label in labels
]
plan = plan_models(study, requests=requests)

# This notebook owes one architecture on every configured label. The rest of the family menu is
# named here rather than left implicit, because a population that is short a configured model is
# otherwise indistinguishable from a complete one.
configured = {(label, ARCHITECTURE) for label in labels}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        f"the plan does not match this notebook's declared coverage; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )
specs = {member.label: json.loads(member.spec_json) for member in plan.members}
computations = {label: spec.get("computation", spec) for label, spec in specs.items()}
computation = computations[labels[0]]

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {computation['numerics']['device']}")
print(f"Lookback: {computation['preprocessing']['lookback']} consecutive daily observations")
for horizon, values in computations.items():
    print(f"Eligible validation rows, {horizon}: {values['expected_prediction_keys']['n_rows']:,}")
for horizon, names in uncovered.items():
    print(
        f"Configured deep_learning models this notebook does not run, {horizon}: {names or 'none'}"
    )

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda
Lookback: 60 consecutive daily observations
Eligible validation rows, fwd_ret_1d: 41,260
Eligible validation rows, fwd_ret_5d: 41,180
Eligible validation rows, fwd_ret_21d: 40,860
Configured deep_learning models this notebook does not run, fwd_ret_1d: ['lstm_h64', 'nlinear']
Configured deep_learning models this notebook does not run, fwd_ret_5d: ['lstm_h64', 'nlinear']
Configured deep_learning models this notebook does not run, fwd_ret_21d: ['lstm_h64', 'nlinear']

## Inspect the declared checkpoints and gap policy

The resolved request records exact validation keys and the rule that excludes windows crossing a
missing expected day. Checkpoint values below are training epochs, not IC-selected summaries.

In [4]:
checkpoint_schedule = pl.DataFrame(computation["checkpoint_schedule"])
input_summary = pl.DataFrame(
    {
        "label": list(computations),
        "gap_policy": [c["preprocessing"]["gap_policy"] for c in computations.values()],
        "validation_folds": [
            c["expected_prediction_keys"]["n_folds"] for c in computations.values()
        ],
        "validation_rows": [c["expected_prediction_keys"]["n_rows"] for c in computations.values()],
        "key_digest": [c["expected_prediction_keys"]["digest"] for c in computations.values()],
    }
)
input_summary
checkpoint_schedule

shape: (20, 2)
┌───────┬───────┐
│ kind  ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ epoch ┆ 5     │
│ epoch ┆ 10    │
│ epoch ┆ 15    │
│ epoch ┆ 20    │
│ epoch ┆ 25    │
│ …     ┆ …     │
│ epoch ┆ 80    │
│ epoch ┆ 85    │
│ epoch ┆ 90    │
│ epoch ┆ 95    │
│ epoch ┆ 100   │
└───────┴───────┘

## Record the official population, then fit or reload the TCN

The same resolved request is used by the notebook and direct Python callers. Publication fails if
any fold is missing, any prediction is non-finite, or the prediction keys differ from eligibility.

In [5]:
if len(plan.expected_prediction_hashes) != checkpoint_schedule.height * len(labels):
    raise RuntimeError("the plan does not cover every declared epoch checkpoint on every label")
population = (
    plan.create_population(name=f"{CASE_STUDY_ID}:{'+'.join(labels)}:tcn")
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
catalog = execution.catalog_rows.sort("label", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial TCN checkpoints cannot pass to backtesting")
for label in labels:
    published = catalog.filter(pl.col("label") == label).get_column("checkpoint_value").to_list()
    if published != checkpoint_schedule["value"].to_list():
        raise RuntimeError(f"catalog checkpoints for {label} differ from the resolved request")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,140 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.192589

      epoch   2/100: train_loss=0.023120

      epoch   3/100: train_loss=0.009977

      epoch   4/100: train_loss=0.005560

      epoch   5/100: train_loss=0.003351, val_loss=0.004063, IC=+0.0283

      epoch   6/100: train_loss=0.009202

      epoch   7/100: train_loss=0.003734

      epoch   8/100: train_loss=0.006432

      epoch   9/100: train_loss=0.002196

      epoch  10/100: train_loss=0.003681, val_loss=0.001328, IC=+0.0087

      epoch  11/100: train_loss=0.007423

      epoch  12/100: train_loss=0.002731

      epoch  13/100: train_loss=0.002492

      epoch  14/100: train_loss=0.002462

      epoch  15/100: train_loss=0.003177, val_loss=0.002984, IC=-0.0127

      epoch  16/100: train_loss=0.002147

      epoch  17/100: train_loss=0.001596

      epoch  18/100: train_loss=0.008189

      epoch  19/100: train_loss=0.001733

      epoch  20/100: train_loss=0.001788, val_loss=0.004559, IC=-0.0297

      epoch  21/100: train_loss=0.001453

      epoch  22/100: train_loss=0.001414

      epoch  23/100: train_loss=0.001982

      epoch  24/100: train_loss=0.002124

      epoch  25/100: train_loss=0.001694, val_loss=0.000550, IC=-0.0080

      epoch  26/100: train_loss=0.003249

      epoch  27/100: train_loss=0.001353

      epoch  28/100: train_loss=0.001074

      epoch  29/100: train_loss=0.002138

      epoch  30/100: train_loss=0.000875, val_loss=0.000553, IC=-0.0217

      epoch  31/100: train_loss=0.000931

      epoch  32/100: train_loss=0.001033

      epoch  33/100: train_loss=0.001351

      epoch  34/100: train_loss=0.001844

      epoch  35/100: train_loss=0.000984, val_loss=0.000495, IC=-0.0069

      epoch  36/100: train_loss=0.001071

      epoch  37/100: train_loss=0.001232

      epoch  38/100: train_loss=0.001181

      epoch  39/100: train_loss=0.001042

      epoch  40/100: train_loss=0.001258, val_loss=0.000698, IC=-0.0272

      epoch  41/100: train_loss=0.000992

      epoch  42/100: train_loss=0.000859

      epoch  43/100: train_loss=0.001007

      epoch  44/100: train_loss=0.001705

      epoch  45/100: train_loss=0.001341, val_loss=0.000897, IC=-0.0235

      epoch  46/100: train_loss=0.000823

      epoch  47/100: train_loss=0.000684

      epoch  48/100: train_loss=0.000900

      epoch  49/100: train_loss=0.000893

      epoch  50/100: train_loss=0.000796, val_loss=0.000342, IC=-0.0522

      epoch  51/100: train_loss=0.000726

      epoch  52/100: train_loss=0.000646

      epoch  53/100: train_loss=0.000651

      epoch  54/100: train_loss=0.000635

      epoch  55/100: train_loss=0.001351, val_loss=0.000407, IC=-0.0419

      epoch  56/100: train_loss=0.001547

      epoch  57/100: train_loss=0.000746

      epoch  58/100: train_loss=0.001363

      epoch  59/100: train_loss=0.000742

      epoch  60/100: train_loss=0.000891, val_loss=0.000525, IC=-0.0466

      epoch  61/100: train_loss=0.000901

      epoch  62/100: train_loss=0.000597

      epoch  63/100: train_loss=0.000762

      epoch  64/100: train_loss=0.000649

      epoch  65/100: train_loss=0.000525, val_loss=0.000790, IC=-0.0316

      epoch  66/100: train_loss=0.000690

      epoch  67/100: train_loss=0.001040

      epoch  68/100: train_loss=0.000814

      epoch  69/100: train_loss=0.000644

      epoch  70/100: train_loss=0.000781, val_loss=0.000623, IC=-0.0367

      epoch  71/100: train_loss=0.000782

      epoch  72/100: train_loss=0.000648

      epoch  73/100: train_loss=0.000475

      epoch  74/100: train_loss=0.001052

      epoch  75/100: train_loss=0.000629, val_loss=0.000570, IC=-0.0352

      epoch  76/100: train_loss=0.000490

      epoch  77/100: train_loss=0.000672

      epoch  78/100: train_loss=0.000561

      epoch  79/100: train_loss=0.000500

      epoch  80/100: train_loss=0.000689, val_loss=0.000358, IC=-0.0392

      epoch  81/100: train_loss=0.000512

      epoch  82/100: train_loss=0.000564

      epoch  83/100: train_loss=0.000649

      epoch  84/100: train_loss=0.000516

      epoch  85/100: train_loss=0.000722, val_loss=0.000364, IC=-0.0416

      epoch  86/100: train_loss=0.000494

      epoch  87/100: train_loss=0.000454

      epoch  88/100: train_loss=0.000545

      epoch  89/100: train_loss=0.000533

      epoch  90/100: train_loss=0.000554, val_loss=0.000327, IC=-0.0414

      epoch  91/100: train_loss=0.000629

      epoch  92/100: train_loss=0.000508

      epoch  93/100: train_loss=0.000748

      epoch  94/100: train_loss=0.000496

      epoch  95/100: train_loss=0.000510, val_loss=0.000323, IC=-0.0408

      epoch  96/100: train_loss=0.000623

      epoch  97/100: train_loss=0.000541

      epoch  98/100: train_loss=0.000458

      epoch  99/100: train_loss=0.000687

      epoch 100/100: train_loss=0.000484, val_loss=0.000366, IC=-0.0417

      best_ep=5, IC=+0.0283 (68.7s, 20 checkpoints)

  Fold 1: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.021100

      epoch   2/100: train_loss=0.004367

      epoch   3/100: train_loss=0.003003

      epoch   4/100: train_loss=0.002627

      epoch   5/100: train_loss=0.002543, val_loss=0.006694, IC=+0.0375

      epoch   6/100: train_loss=0.002066

      epoch   7/100: train_loss=0.002343

      epoch   8/100: train_loss=0.001626

      epoch   9/100: train_loss=0.001577

      epoch  10/100: train_loss=0.001750, val_loss=0.002563, IC=+0.0492

      epoch  11/100: train_loss=0.002213

      epoch  12/100: train_loss=0.002018

      epoch  13/100: train_loss=0.001609

      epoch  14/100: train_loss=0.001596

      epoch  15/100: train_loss=0.001427, val_loss=0.001236, IC=+0.0258

      epoch  16/100: train_loss=0.002589

      epoch  17/100: train_loss=0.001901

      epoch  18/100: train_loss=0.001495

      epoch  19/100: train_loss=0.001287

      epoch  20/100: train_loss=0.001036, val_loss=0.001163, IC=+0.0243

      epoch  21/100: train_loss=0.001039

      epoch  22/100: train_loss=0.000996

      epoch  23/100: train_loss=0.000855

      epoch  24/100: train_loss=0.000881

      epoch  25/100: train_loss=0.001089, val_loss=0.001028, IC=+0.0395

      epoch  26/100: train_loss=0.001111

      epoch  27/100: train_loss=0.001300

      epoch  28/100: train_loss=0.001626

      epoch  29/100: train_loss=0.001914

      epoch  30/100: train_loss=0.001151, val_loss=0.000589, IC=+0.0318

      epoch  31/100: train_loss=0.000862

      epoch  32/100: train_loss=0.000745

      epoch  33/100: train_loss=0.000735

      epoch  34/100: train_loss=0.000709

      epoch  35/100: train_loss=0.000715, val_loss=0.000666, IC=+0.0180

      epoch  36/100: train_loss=0.000667

      epoch  37/100: train_loss=0.000674

      epoch  38/100: train_loss=0.000647

      epoch  39/100: train_loss=0.000640

      epoch  40/100: train_loss=0.000667, val_loss=0.000562, IC=+0.0116

      epoch  41/100: train_loss=0.000711

      epoch  42/100: train_loss=0.000708

      epoch  43/100: train_loss=0.000677

      epoch  44/100: train_loss=0.000857

      epoch  45/100: train_loss=0.000998, val_loss=0.000398, IC=+0.0084

      epoch  46/100: train_loss=0.000712

      epoch  47/100: train_loss=0.000697

      epoch  48/100: train_loss=0.000677

      epoch  49/100: train_loss=0.000928

      epoch  50/100: train_loss=0.000750, val_loss=0.000324, IC=+0.0060

      epoch  51/100: train_loss=0.000747

      epoch  52/100: train_loss=0.000635

      epoch  53/100: train_loss=0.000597

      epoch  54/100: train_loss=0.000605

      epoch  55/100: train_loss=0.000618, val_loss=0.000368, IC=+0.0045

      epoch  56/100: train_loss=0.000696

      epoch  57/100: train_loss=0.000644

      epoch  58/100: train_loss=0.000739

      epoch  59/100: train_loss=0.001247

      epoch  60/100: train_loss=0.000542, val_loss=0.000475, IC=+0.0095

      epoch  61/100: train_loss=0.000595

      epoch  62/100: train_loss=0.000470

      epoch  63/100: train_loss=0.000626

      epoch  64/100: train_loss=0.000527

      epoch  65/100: train_loss=0.000525, val_loss=0.000350, IC=+0.0198

      epoch  66/100: train_loss=0.000672

      epoch  67/100: train_loss=0.000638

      epoch  68/100: train_loss=0.000558

      epoch  69/100: train_loss=0.000462

      epoch  70/100: train_loss=0.000464, val_loss=0.000301, IC=+0.0272

      epoch  71/100: train_loss=0.000884

      epoch  72/100: train_loss=0.000450

      epoch  73/100: train_loss=0.000565

      epoch  74/100: train_loss=0.000501

      epoch  75/100: train_loss=0.000441, val_loss=0.000420, IC=+0.0265

      epoch  76/100: train_loss=0.000727

      epoch  77/100: train_loss=0.000967

      epoch  78/100: train_loss=0.000615

      epoch  79/100: train_loss=0.000743

      epoch  80/100: train_loss=0.000517, val_loss=0.000402, IC=+0.0306

      epoch  81/100: train_loss=0.000565

      epoch  82/100: train_loss=0.000676

      epoch  83/100: train_loss=0.000580

      epoch  84/100: train_loss=0.000505

      epoch  85/100: train_loss=0.000497, val_loss=0.000321, IC=+0.0242

      epoch  86/100: train_loss=0.000851

      epoch  87/100: train_loss=0.000577

      epoch  88/100: train_loss=0.000402

      epoch  89/100: train_loss=0.000527

      epoch  90/100: train_loss=0.000946, val_loss=0.000571, IC=+0.0122

      epoch  91/100: train_loss=0.000463

      epoch  92/100: train_loss=0.000518

      epoch  93/100: train_loss=0.000526

      epoch  94/100: train_loss=0.000437

      epoch  95/100: train_loss=0.000493, val_loss=0.000283, IC=+0.0229

      epoch  96/100: train_loss=0.000506

      epoch  97/100: train_loss=0.000788

      epoch  98/100: train_loss=0.000446

      epoch  99/100: train_loss=0.000507

      epoch 100/100: train_loss=0.000571, val_loss=0.000353, IC=+0.0223

      best_ep=10, IC=+0.0492 (68.4s, 20 checkpoints)

  Fold 2: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.342431

      epoch   2/100: train_loss=0.025959

      epoch   3/100: train_loss=0.007431

      epoch   4/100: train_loss=0.006101

      epoch   5/100: train_loss=0.005992, val_loss=0.000602, IC=-0.0140

      epoch   6/100: train_loss=0.005476

      epoch   7/100: train_loss=0.003912

      epoch   8/100: train_loss=0.001851

      epoch   9/100: train_loss=0.003478

      epoch  10/100: train_loss=0.006087, val_loss=0.000325, IC=-0.0294

      epoch  11/100: train_loss=0.005558

      epoch  12/100: train_loss=0.003028

      epoch  13/100: train_loss=0.001894

      epoch  14/100: train_loss=0.002974

      epoch  15/100: train_loss=0.002056, val_loss=0.000481, IC=-0.0271

      epoch  16/100: train_loss=0.004213

      epoch  17/100: train_loss=0.001391

      epoch  18/100: train_loss=0.002987

      epoch  19/100: train_loss=0.003814

      epoch  20/100: train_loss=0.001285, val_loss=0.000340, IC=-0.0049

      epoch  21/100: train_loss=0.002108

      epoch  22/100: train_loss=0.001746

      epoch  23/100: train_loss=0.001319

      epoch  24/100: train_loss=0.001268

      epoch  25/100: train_loss=0.001392, val_loss=0.000448, IC=-0.0064

      epoch  26/100: train_loss=0.001388

      epoch  27/100: train_loss=0.001771

      epoch  28/100: train_loss=0.002726

      epoch  29/100: train_loss=0.001025

      epoch  30/100: train_loss=0.001312, val_loss=0.000184, IC=-0.0086

      epoch  31/100: train_loss=0.001987

      epoch  32/100: train_loss=0.002745

      epoch  33/100: train_loss=0.001889

      epoch  34/100: train_loss=0.001596

      epoch  35/100: train_loss=0.002182, val_loss=0.000169, IC=+0.0000

      epoch  36/100: train_loss=0.001482

      epoch  37/100: train_loss=0.003488

      epoch  38/100: train_loss=0.001847

      epoch  39/100: train_loss=0.000652

      epoch  40/100: train_loss=0.000683, val_loss=0.000397, IC=-0.0008

      epoch  41/100: train_loss=0.001245

      epoch  42/100: train_loss=0.001549

      epoch  43/100: train_loss=0.001265

      epoch  44/100: train_loss=0.000992

      epoch  45/100: train_loss=0.000602, val_loss=0.000160, IC=-0.0116

      epoch  46/100: train_loss=0.000652

      epoch  47/100: train_loss=0.000925

      epoch  48/100: train_loss=0.001041

      epoch  49/100: train_loss=0.000775

      epoch  50/100: train_loss=0.000692, val_loss=0.000336, IC=+0.0143

      epoch  51/100: train_loss=0.000671

      epoch  52/100: train_loss=0.000649

      epoch  53/100: train_loss=0.002038

      epoch  54/100: train_loss=0.001017

      epoch  55/100: train_loss=0.000740, val_loss=0.000191, IC=+0.0102

      epoch  56/100: train_loss=0.000849

      epoch  57/100: train_loss=0.000810

      epoch  58/100: train_loss=0.000813

      epoch  59/100: train_loss=0.000991

      epoch  60/100: train_loss=0.000881, val_loss=0.000135, IC=+0.0122

      epoch  61/100: train_loss=0.000878

      epoch  62/100: train_loss=0.000905

      epoch  63/100: train_loss=0.000798

      epoch  64/100: train_loss=0.000900

      epoch  65/100: train_loss=0.000619, val_loss=0.000166, IC=+0.0101

      epoch  66/100: train_loss=0.000736

      epoch  67/100: train_loss=0.000749

      epoch  68/100: train_loss=0.001301

      epoch  69/100: train_loss=0.000614

      epoch  70/100: train_loss=0.000666, val_loss=0.000145, IC=+0.0039

      epoch  71/100: train_loss=0.000528

      epoch  72/100: train_loss=0.000916

      epoch  73/100: train_loss=0.000770

      epoch  74/100: train_loss=0.000621

      epoch  75/100: train_loss=0.000546, val_loss=0.000116, IC=+0.0061

      epoch  76/100: train_loss=0.000492

      epoch  77/100: train_loss=0.000522

      epoch  78/100: train_loss=0.000740

      epoch  79/100: train_loss=0.000554

      epoch  80/100: train_loss=0.000984, val_loss=0.000103, IC=+0.0073

      epoch  81/100: train_loss=0.000815

      epoch  82/100: train_loss=0.000512

      epoch  83/100: train_loss=0.000478

      epoch  84/100: train_loss=0.000472

      epoch  85/100: train_loss=0.000566, val_loss=0.000094, IC=+0.0084

      epoch  86/100: train_loss=0.000500

      epoch  87/100: train_loss=0.000700

      epoch  88/100: train_loss=0.000523

      epoch  89/100: train_loss=0.000640

      epoch  90/100: train_loss=0.000472, val_loss=0.000109, IC=+0.0076

      epoch  91/100: train_loss=0.000477

      epoch  92/100: train_loss=0.000503

      epoch  93/100: train_loss=0.000497

      epoch  94/100: train_loss=0.000518

      epoch  95/100: train_loss=0.000475, val_loss=0.000100, IC=+0.0027

      epoch  96/100: train_loss=0.000469

      epoch  97/100: train_loss=0.000527

      epoch  98/100: train_loss=0.000547

      epoch  99/100: train_loss=0.000685

      epoch 100/100: train_loss=0.000476, val_loss=0.000135, IC=+0.0012

      best_ep=50, IC=+0.0143 (68.0s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.030493

      epoch   2/100: train_loss=0.005909

      epoch   3/100: train_loss=0.004046

      epoch   4/100: train_loss=0.003669

      epoch   5/100: train_loss=0.002515, val_loss=0.002357, IC=+0.0378

      epoch   6/100: train_loss=0.002403

      epoch   7/100: train_loss=0.002751

      epoch   8/100: train_loss=0.002354

      epoch   9/100: train_loss=0.002086

      epoch  10/100: train_loss=0.001837, val_loss=0.001444, IC=+0.0147

      epoch  11/100: train_loss=0.002866

      epoch  12/100: train_loss=0.001991

      epoch  13/100: train_loss=0.002880

      epoch  14/100: train_loss=0.002305

      epoch  15/100: train_loss=0.001749, val_loss=0.001292, IC=+0.0347

      epoch  16/100: train_loss=0.002349

      epoch  17/100: train_loss=0.001914

      epoch  18/100: train_loss=0.003184

      epoch  19/100: train_loss=0.002088

      epoch  20/100: train_loss=0.001880, val_loss=0.001733, IC=-0.0232

      epoch  21/100: train_loss=0.002348

      epoch  22/100: train_loss=0.001378

      epoch  23/100: train_loss=0.001320

      epoch  24/100: train_loss=0.001139

      epoch  25/100: train_loss=0.001107, val_loss=0.001114, IC=+0.0322

      epoch  26/100: train_loss=0.001509

      epoch  27/100: train_loss=0.001432

      epoch  28/100: train_loss=0.001270

      epoch  29/100: train_loss=0.001212

      epoch  30/100: train_loss=0.002661, val_loss=0.001467, IC=+0.0249

      epoch  31/100: train_loss=0.001418

      epoch  32/100: train_loss=0.001523

      epoch  33/100: train_loss=0.001160

      epoch  34/100: train_loss=0.001762

      epoch  35/100: train_loss=0.001950, val_loss=0.000626, IC=+0.0171

      epoch  36/100: train_loss=0.001193

      epoch  37/100: train_loss=0.000838

      epoch  38/100: train_loss=0.000951

      epoch  39/100: train_loss=0.001192

      epoch  40/100: train_loss=0.001053, val_loss=0.000571, IC=+0.0215

      epoch  41/100: train_loss=0.001264

      epoch  42/100: train_loss=0.000965

      epoch  43/100: train_loss=0.001583

      epoch  44/100: train_loss=0.001100

      epoch  45/100: train_loss=0.001001, val_loss=0.000506, IC=+0.0137

      epoch  46/100: train_loss=0.001221

      epoch  47/100: train_loss=0.001178

      epoch  48/100: train_loss=0.001657

      epoch  49/100: train_loss=0.001172

      epoch  50/100: train_loss=0.001925, val_loss=0.000904, IC=+0.0160

      epoch  51/100: train_loss=0.001090

      epoch  52/100: train_loss=0.001511

      epoch  53/100: train_loss=0.000974

      epoch  54/100: train_loss=0.000788

      epoch  55/100: train_loss=0.000863, val_loss=0.000469, IC=+0.0125

      epoch  56/100: train_loss=0.000771

      epoch  57/100: train_loss=0.000862

      epoch  58/100: train_loss=0.001025

      epoch  59/100: train_loss=0.000850

      epoch  60/100: train_loss=0.001234, val_loss=0.000340, IC=+0.0142

      epoch  61/100: train_loss=0.000867

      epoch  62/100: train_loss=0.000683

      epoch  63/100: train_loss=0.000685

      epoch  64/100: train_loss=0.000690

      epoch  65/100: train_loss=0.001111, val_loss=0.000423, IC=+0.0014

      epoch  66/100: train_loss=0.000844

      epoch  67/100: train_loss=0.000844

      epoch  68/100: train_loss=0.000899

      epoch  69/100: train_loss=0.000827

      epoch  70/100: train_loss=0.000691, val_loss=0.000343, IC=+0.0218

      epoch  71/100: train_loss=0.001120

      epoch  72/100: train_loss=0.000695

      epoch  73/100: train_loss=0.000662

      epoch  74/100: train_loss=0.000625

      epoch  75/100: train_loss=0.000799, val_loss=0.000283, IC=+0.0294

      epoch  76/100: train_loss=0.001229

      epoch  77/100: train_loss=0.000867

      epoch  78/100: train_loss=0.000679

      epoch  79/100: train_loss=0.000625

      epoch  80/100: train_loss=0.000736, val_loss=0.000314, IC=+0.0110

      epoch  81/100: train_loss=0.000651

      epoch  82/100: train_loss=0.000673

      epoch  83/100: train_loss=0.000645

      epoch  84/100: train_loss=0.000821

      epoch  85/100: train_loss=0.000778, val_loss=0.000291, IC=+0.0084

      epoch  86/100: train_loss=0.000831

      epoch  87/100: train_loss=0.000643

      epoch  88/100: train_loss=0.000615

      epoch  89/100: train_loss=0.000637

      epoch  90/100: train_loss=0.000619, val_loss=0.000291, IC=+0.0118

      epoch  91/100: train_loss=0.000631

      epoch  92/100: train_loss=0.000743

      epoch  93/100: train_loss=0.000652

      epoch  94/100: train_loss=0.000679

      epoch  95/100: train_loss=0.000847, val_loss=0.000322, IC=+0.0098

      epoch  96/100: train_loss=0.000780

      epoch  97/100: train_loss=0.000616

      epoch  98/100: train_loss=0.001238

      epoch  99/100: train_loss=0.000645

      epoch 100/100: train_loss=0.000785, val_loss=0.000325, IC=+0.0090

      best_ep=5, IC=+0.0378 (68.7s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.020153

      epoch   2/100: train_loss=0.004597

      epoch   3/100: train_loss=0.003077

      epoch   4/100: train_loss=0.003825

      epoch   5/100: train_loss=0.002367, val_loss=0.001366, IC=-0.0086

      epoch   6/100: train_loss=0.002352

      epoch   7/100: train_loss=0.002034

      epoch   8/100: train_loss=0.002072

      epoch   9/100: train_loss=0.002384

      epoch  10/100: train_loss=0.002712, val_loss=0.000931, IC=-0.0006

      epoch  11/100: train_loss=0.001879

      epoch  12/100: train_loss=0.001732

      epoch  13/100: train_loss=0.002432

      epoch  14/100: train_loss=0.001906

      epoch  15/100: train_loss=0.001718, val_loss=0.000725, IC=+0.0204

      epoch  16/100: train_loss=0.001426

      epoch  17/100: train_loss=0.001251

      epoch  18/100: train_loss=0.002303

      epoch  19/100: train_loss=0.001927

      epoch  20/100: train_loss=0.001808, val_loss=0.000620, IC=+0.0132

      epoch  21/100: train_loss=0.001904

      epoch  22/100: train_loss=0.001414

      epoch  23/100: train_loss=0.001160

      epoch  24/100: train_loss=0.001547

      epoch  25/100: train_loss=0.001811, val_loss=0.000494, IC=+0.0037

      epoch  26/100: train_loss=0.001124

      epoch  27/100: train_loss=0.001111

      epoch  28/100: train_loss=0.001211

      epoch  29/100: train_loss=0.001134

      epoch  30/100: train_loss=0.001015, val_loss=0.000502, IC=+0.0004

      epoch  31/100: train_loss=0.001036

      epoch  32/100: train_loss=0.001026

      epoch  33/100: train_loss=0.001021

      epoch  34/100: train_loss=0.000926

      epoch  35/100: train_loss=0.000868, val_loss=0.000355, IC=+0.0203

      epoch  36/100: train_loss=0.000773

      epoch  37/100: train_loss=0.001068

      epoch  38/100: train_loss=0.001519

      epoch  39/100: train_loss=0.001271

      epoch  40/100: train_loss=0.001538, val_loss=0.000529, IC=+0.0152

      epoch  41/100: train_loss=0.000917

      epoch  42/100: train_loss=0.000860

      epoch  43/100: train_loss=0.000740

      epoch  44/100: train_loss=0.000824

      epoch  45/100: train_loss=0.001665, val_loss=0.000211, IC=+0.0260

      epoch  46/100: train_loss=0.001063

      epoch  47/100: train_loss=0.000921

      epoch  48/100: train_loss=0.001604

      epoch  49/100: train_loss=0.000792

      epoch  50/100: train_loss=0.001480, val_loss=0.000230, IC=+0.0130

      epoch  51/100: train_loss=0.001072

      epoch  52/100: train_loss=0.000893

      epoch  53/100: train_loss=0.000710

      epoch  54/100: train_loss=0.000701

      epoch  55/100: train_loss=0.000728, val_loss=0.000303, IC=+0.0238

      epoch  56/100: train_loss=0.000648

      epoch  57/100: train_loss=0.000621

      epoch  58/100: train_loss=0.000738

      epoch  59/100: train_loss=0.000854

      epoch  60/100: train_loss=0.000754, val_loss=0.000224, IC=+0.0301

      epoch  61/100: train_loss=0.000584

      epoch  62/100: train_loss=0.000608

      epoch  63/100: train_loss=0.000591

      epoch  64/100: train_loss=0.000649

      epoch  65/100: train_loss=0.001036, val_loss=0.000190, IC=+0.0170

      epoch  66/100: train_loss=0.001148

      epoch  67/100: train_loss=0.000846

      epoch  68/100: train_loss=0.000881

      epoch  69/100: train_loss=0.000617

      epoch  70/100: train_loss=0.000656, val_loss=0.000435, IC=+0.0203

      epoch  71/100: train_loss=0.000699

      epoch  72/100: train_loss=0.000544

      epoch  73/100: train_loss=0.000526

      epoch  74/100: train_loss=0.000899

      epoch  75/100: train_loss=0.000580, val_loss=0.000426, IC=+0.0195

      epoch  76/100: train_loss=0.000651

      epoch  77/100: train_loss=0.000587

      epoch  78/100: train_loss=0.000514

      epoch  79/100: train_loss=0.000872

      epoch  80/100: train_loss=0.000573, val_loss=0.000188, IC=+0.0251

      epoch  81/100: train_loss=0.000961

      epoch  82/100: train_loss=0.000629

      epoch  83/100: train_loss=0.000868

      epoch  84/100: train_loss=0.000763

      epoch  85/100: train_loss=0.000593, val_loss=0.000214, IC=+0.0109

      epoch  86/100: train_loss=0.000560

      epoch  87/100: train_loss=0.000597

      epoch  88/100: train_loss=0.000503

      epoch  89/100: train_loss=0.000611

      epoch  90/100: train_loss=0.001241, val_loss=0.000236, IC=+0.0133

      epoch  91/100: train_loss=0.000618

      epoch  92/100: train_loss=0.000509

      epoch  93/100: train_loss=0.000574

      epoch  94/100: train_loss=0.000631

      epoch  95/100: train_loss=0.000555, val_loss=0.000277, IC=+0.0151

      epoch  96/100: train_loss=0.000572

      epoch  97/100: train_loss=0.000567

      epoch  98/100: train_loss=0.000500

      epoch  99/100: train_loss=0.000695

      epoch 100/100: train_loss=0.000540, val_loss=0.000154, IC=+0.0178

      best_ep=60, IC=+0.0301 (68.5s, 20 checkpoints)

  Fold 5: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.014318

      epoch   2/100: train_loss=0.002447

      epoch   3/100: train_loss=0.002707

      epoch   4/100: train_loss=0.001622

      epoch   5/100: train_loss=0.001565, val_loss=0.000921, IC=+0.0286

      epoch   6/100: train_loss=0.001204

      epoch   7/100: train_loss=0.001236

      epoch   8/100: train_loss=0.001188

      epoch   9/100: train_loss=0.001495

      epoch  10/100: train_loss=0.001300, val_loss=0.000520, IC=+0.0320

      epoch  11/100: train_loss=0.000910

      epoch  12/100: train_loss=0.000965

      epoch  13/100: train_loss=0.001306

      epoch  14/100: train_loss=0.001142

      epoch  15/100: train_loss=0.000758, val_loss=0.000517, IC=+0.0140

      epoch  16/100: train_loss=0.000712

      epoch  17/100: train_loss=0.000718

      epoch  18/100: train_loss=0.000873

      epoch  19/100: train_loss=0.001364

      epoch  20/100: train_loss=0.001333, val_loss=0.000336, IC=+0.0376

      epoch  21/100: train_loss=0.001190

      epoch  22/100: train_loss=0.001071

      epoch  23/100: train_loss=0.000793

      epoch  24/100: train_loss=0.000684

      epoch  25/100: train_loss=0.000752, val_loss=0.000542, IC=-0.0002

      epoch  26/100: train_loss=0.000794

      epoch  27/100: train_loss=0.000699

      epoch  28/100: train_loss=0.000630

      epoch  29/100: train_loss=0.000568

      epoch  30/100: train_loss=0.000814, val_loss=0.000298, IC=+0.0163

      epoch  31/100: train_loss=0.000781

      epoch  32/100: train_loss=0.000593

      epoch  33/100: train_loss=0.000765

      epoch  34/100: train_loss=0.001052

      epoch  35/100: train_loss=0.000881, val_loss=0.001373, IC=+0.0252

      epoch  36/100: train_loss=0.001021

      epoch  37/100: train_loss=0.000589

      epoch  38/100: train_loss=0.000659

      epoch  39/100: train_loss=0.000736

      epoch  40/100: train_loss=0.000586, val_loss=0.000275, IC=+0.0251

      epoch  41/100: train_loss=0.000471

      epoch  42/100: train_loss=0.000436

      epoch  43/100: train_loss=0.000539

      epoch  44/100: train_loss=0.000618

      epoch  45/100: train_loss=0.000488, val_loss=0.000336, IC=+0.0123

      epoch  46/100: train_loss=0.000393

      epoch  47/100: train_loss=0.000747

      epoch  48/100: train_loss=0.000701

      epoch  49/100: train_loss=0.000801

      epoch  50/100: train_loss=0.000702, val_loss=0.000339, IC=+0.0220

      epoch  51/100: train_loss=0.000421

      epoch  52/100: train_loss=0.000388

      epoch  53/100: train_loss=0.000382

      epoch  54/100: train_loss=0.000386

      epoch  55/100: train_loss=0.000407, val_loss=0.000193, IC=+0.0027

      epoch  56/100: train_loss=0.000394

      epoch  57/100: train_loss=0.000357

      epoch  58/100: train_loss=0.000366

      epoch  59/100: train_loss=0.000412

      epoch  60/100: train_loss=0.000363, val_loss=0.000204, IC=+0.0062

      epoch  61/100: train_loss=0.000464

      epoch  62/100: train_loss=0.000412

      epoch  63/100: train_loss=0.000372

      epoch  64/100: train_loss=0.000387

      epoch  65/100: train_loss=0.000388, val_loss=0.000149, IC=-0.0143

      epoch  66/100: train_loss=0.000698

      epoch  67/100: train_loss=0.000530

      epoch  68/100: train_loss=0.000372

      epoch  69/100: train_loss=0.000403

      epoch  70/100: train_loss=0.000334, val_loss=0.000360, IC=-0.0104

      epoch  71/100: train_loss=0.000339

      epoch  72/100: train_loss=0.000370

      epoch  73/100: train_loss=0.000349

      epoch  74/100: train_loss=0.000313

      epoch  75/100: train_loss=0.000399, val_loss=0.000119, IC=-0.0160

      epoch  76/100: train_loss=0.000345

      epoch  77/100: train_loss=0.000508

      epoch  78/100: train_loss=0.000460

      epoch  79/100: train_loss=0.000402

      epoch  80/100: train_loss=0.000373, val_loss=0.000261, IC=-0.0082

      epoch  81/100: train_loss=0.000451

      epoch  82/100: train_loss=0.000315

      epoch  83/100: train_loss=0.000344

      epoch  84/100: train_loss=0.000309

      epoch  85/100: train_loss=0.000368, val_loss=0.000180, IC=-0.0139

      epoch  86/100: train_loss=0.000297

      epoch  87/100: train_loss=0.000331

      epoch  88/100: train_loss=0.000329

      epoch  89/100: train_loss=0.000316

      epoch  90/100: train_loss=0.000333, val_loss=0.000136, IC=-0.0060

      epoch  91/100: train_loss=0.000306

      epoch  92/100: train_loss=0.000323

      epoch  93/100: train_loss=0.000313

      epoch  94/100: train_loss=0.000305

      epoch  95/100: train_loss=0.000331, val_loss=0.000141, IC=-0.0088

      epoch  96/100: train_loss=0.000350

      epoch  97/100: train_loss=0.000310

      epoch  98/100: train_loss=0.000303

      epoch  99/100: train_loss=0.000324

      epoch 100/100: train_loss=0.000298, val_loss=0.000120, IC=-0.0074

      best_ep=20, IC=+0.0376 (67.8s, 20 checkpoints)

  Fold 6: creating sequences...
    train=22,220 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.054612

      epoch   2/100: train_loss=0.004684

      epoch   3/100: train_loss=0.002478

      epoch   4/100: train_loss=0.001794

      epoch   5/100: train_loss=0.001567, val_loss=0.002174, IC=+0.0113

      epoch   6/100: train_loss=0.001409

      epoch   7/100: train_loss=0.001330

      epoch   8/100: train_loss=0.001216

      epoch   9/100: train_loss=0.001178

      epoch  10/100: train_loss=0.001075, val_loss=0.001360, IC=+0.0218

      epoch  11/100: train_loss=0.001033

      epoch  12/100: train_loss=0.000989

      epoch  13/100: train_loss=0.000926

      epoch  14/100: train_loss=0.001001

      epoch  15/100: train_loss=0.000994, val_loss=0.000592, IC=+0.0455

      epoch  16/100: train_loss=0.000903

      epoch  17/100: train_loss=0.000824

      epoch  18/100: train_loss=0.000809

      epoch  19/100: train_loss=0.000753

      epoch  20/100: train_loss=0.000780, val_loss=0.000628, IC=+0.0293

      epoch  21/100: train_loss=0.000728

      epoch  22/100: train_loss=0.000633

      epoch  23/100: train_loss=0.000598

      epoch  24/100: train_loss=0.000595

      epoch  25/100: train_loss=0.000584, val_loss=0.000305, IC=+0.0318

      epoch  26/100: train_loss=0.000590

      epoch  27/100: train_loss=0.000582

      epoch  28/100: train_loss=0.000598

      epoch  29/100: train_loss=0.000565

      epoch  30/100: train_loss=0.000553, val_loss=0.000292, IC=+0.0029

      epoch  31/100: train_loss=0.000516

      epoch  32/100: train_loss=0.000532

      epoch  33/100: train_loss=0.000534

      epoch  34/100: train_loss=0.000545

      epoch  35/100: train_loss=0.000464, val_loss=0.000181, IC=-0.0006

      epoch  36/100: train_loss=0.000446

      epoch  37/100: train_loss=0.000453

      epoch  38/100: train_loss=0.000453

      epoch  39/100: train_loss=0.000446

      epoch  40/100: train_loss=0.000466, val_loss=0.000164, IC=+0.0059

      epoch  41/100: train_loss=0.000467

      epoch  42/100: train_loss=0.000444

      epoch  43/100: train_loss=0.000425

      epoch  44/100: train_loss=0.000402

      epoch  45/100: train_loss=0.000382, val_loss=0.000144, IC=-0.0053

      epoch  46/100: train_loss=0.000378

      epoch  47/100: train_loss=0.000397

      epoch  48/100: train_loss=0.000384

      epoch  49/100: train_loss=0.000373

      epoch  50/100: train_loss=0.000367, val_loss=0.000193, IC=+0.0025

      epoch  51/100: train_loss=0.000353

      epoch  52/100: train_loss=0.000346

      epoch  53/100: train_loss=0.000345

      epoch  54/100: train_loss=0.000360

      epoch  55/100: train_loss=0.000363, val_loss=0.000133, IC=-0.0056

      epoch  56/100: train_loss=0.000367

      epoch  57/100: train_loss=0.000367

      epoch  58/100: train_loss=0.000358

      epoch  59/100: train_loss=0.000345

      epoch  60/100: train_loss=0.000343, val_loss=0.000119, IC=-0.0028

      epoch  61/100: train_loss=0.000323

      epoch  62/100: train_loss=0.000332

      epoch  63/100: train_loss=0.000325

      epoch  64/100: train_loss=0.000311

      epoch  65/100: train_loss=0.000320, val_loss=0.000105, IC=-0.0038

      epoch  66/100: train_loss=0.000332

      epoch  67/100: train_loss=0.000348

      epoch  68/100: train_loss=0.000396

      epoch  69/100: train_loss=0.000335

      epoch  70/100: train_loss=0.000320, val_loss=0.000129, IC=-0.0040

      epoch  71/100: train_loss=0.000309

      epoch  72/100: train_loss=0.000308

      epoch  73/100: train_loss=0.000312

      epoch  74/100: train_loss=0.000307

      epoch  75/100: train_loss=0.000313, val_loss=0.000105, IC=+0.0008

      epoch  76/100: train_loss=0.000303

      epoch  77/100: train_loss=0.000291

      epoch  78/100: train_loss=0.000310

      epoch  79/100: train_loss=0.000292

      epoch  80/100: train_loss=0.000296, val_loss=0.000101, IC=-0.0005

      epoch  81/100: train_loss=0.000302

      epoch  82/100: train_loss=0.000305

      epoch  83/100: train_loss=0.000308

      epoch  84/100: train_loss=0.000292

      epoch  85/100: train_loss=0.000284, val_loss=0.000107, IC=-0.0034

      epoch  86/100: train_loss=0.000288

      epoch  87/100: train_loss=0.000288

      epoch  88/100: train_loss=0.000293

      epoch  89/100: train_loss=0.000300

      epoch  90/100: train_loss=0.000293, val_loss=0.000117, IC=-0.0050

      epoch  91/100: train_loss=0.000298

      epoch  92/100: train_loss=0.000292

      epoch  93/100: train_loss=0.000299

      epoch  94/100: train_loss=0.000284

      epoch  95/100: train_loss=0.000285, val_loss=0.000107, IC=-0.0026

      epoch  96/100: train_loss=0.000287

      epoch  97/100: train_loss=0.000294

      epoch  98/100: train_loss=0.000294

      epoch  99/100: train_loss=0.000289

      epoch 100/100: train_loss=0.000291, val_loss=0.000106, IC=-0.0029

      best_ep=15, IC=+0.0455 (61.3s, 20 checkpoints)

  Fold 7: creating sequences...
    train=17,060 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.455623

      epoch   2/100: train_loss=0.048760

      epoch   3/100: train_loss=0.007735

      epoch   4/100: train_loss=0.003073

      epoch   5/100: train_loss=0.002066, val_loss=0.002425, IC=+0.0426

      epoch   6/100: train_loss=0.001416

      epoch   7/100: train_loss=0.001441

      epoch   8/100: train_loss=0.001300

      epoch   9/100: train_loss=0.001140

      epoch  10/100: train_loss=0.001248, val_loss=0.000921, IC=+0.0239

      epoch  11/100: train_loss=0.001073

      epoch  12/100: train_loss=0.000995

      epoch  13/100: train_loss=0.000999

      epoch  14/100: train_loss=0.000929

      epoch  15/100: train_loss=0.000929, val_loss=0.000875, IC=+0.0228

      epoch  16/100: train_loss=0.000832

      epoch  17/100: train_loss=0.000814

      epoch  18/100: train_loss=0.000953

      epoch  19/100: train_loss=0.000639

      epoch  20/100: train_loss=0.000609, val_loss=0.000708, IC=+0.0159

      epoch  21/100: train_loss=0.000814

      epoch  22/100: train_loss=0.000554

      epoch  23/100: train_loss=0.000794

      epoch  24/100: train_loss=0.000955

      epoch  25/100: train_loss=0.000841, val_loss=0.000647, IC=+0.0110

      epoch  26/100: train_loss=0.000670

      epoch  27/100: train_loss=0.000601

      epoch  28/100: train_loss=0.000567

      epoch  29/100: train_loss=0.000510

      epoch  30/100: train_loss=0.000541, val_loss=0.002211, IC=+0.0159

      epoch  31/100: train_loss=0.000584

      epoch  32/100: train_loss=0.000542

      epoch  33/100: train_loss=0.000569

      epoch  34/100: train_loss=0.000528

      epoch  35/100: train_loss=0.000510, val_loss=0.000536, IC=+0.0118

      epoch  36/100: train_loss=0.000508

      epoch  37/100: train_loss=0.000551

      epoch  38/100: train_loss=0.000455

      epoch  39/100: train_loss=0.000508

      epoch  40/100: train_loss=0.000555, val_loss=0.001452, IC=+0.0110

      epoch  41/100: train_loss=0.000438

      epoch  42/100: train_loss=0.000461

      epoch  43/100: train_loss=0.000485

      epoch  44/100: train_loss=0.000581

      epoch  45/100: train_loss=0.000451, val_loss=0.000977, IC=+0.0100

      epoch  46/100: train_loss=0.000532

      epoch  47/100: train_loss=0.000669

      epoch  48/100: train_loss=0.001025

      epoch  49/100: train_loss=0.000783

      epoch  50/100: train_loss=0.000563, val_loss=0.002295, IC=+0.0190

      epoch  51/100: train_loss=0.000476

      epoch  52/100: train_loss=0.000440

      epoch  53/100: train_loss=0.000587

      epoch  54/100: train_loss=0.000407

      epoch  55/100: train_loss=0.000561, val_loss=0.001173, IC=+0.0205

      epoch  56/100: train_loss=0.000460

      epoch  57/100: train_loss=0.000371

      epoch  58/100: train_loss=0.000427

      epoch  59/100: train_loss=0.000443

      epoch  60/100: train_loss=0.000358, val_loss=0.000309, IC=+0.0093

      epoch  61/100: train_loss=0.000416

      epoch  62/100: train_loss=0.000353

      epoch  63/100: train_loss=0.000383

      epoch  64/100: train_loss=0.000387

      epoch  65/100: train_loss=0.000419, val_loss=0.000573, IC=+0.0098

      epoch  66/100: train_loss=0.000358

      epoch  67/100: train_loss=0.000370

      epoch  68/100: train_loss=0.000345

      epoch  69/100: train_loss=0.000325

      epoch  70/100: train_loss=0.000362, val_loss=0.000445, IC=+0.0044

      epoch  71/100: train_loss=0.000375

      epoch  72/100: train_loss=0.000372

      epoch  73/100: train_loss=0.000349

      epoch  74/100: train_loss=0.000317

      epoch  75/100: train_loss=0.000348, val_loss=0.000791, IC=+0.0127

      epoch  76/100: train_loss=0.000284

      epoch  77/100: train_loss=0.000344

      epoch  78/100: train_loss=0.000328

      epoch  79/100: train_loss=0.000333

      epoch  80/100: train_loss=0.000311, val_loss=0.000472, IC=+0.0092

      epoch  81/100: train_loss=0.000343

      epoch  82/100: train_loss=0.000346

      epoch  83/100: train_loss=0.000331

      epoch  84/100: train_loss=0.000300

      epoch  85/100: train_loss=0.000313, val_loss=0.000799, IC=+0.0144

      epoch  86/100: train_loss=0.000303

      epoch  87/100: train_loss=0.000362

      epoch  88/100: train_loss=0.000321

      epoch  89/100: train_loss=0.000350

      epoch  90/100: train_loss=0.000309, val_loss=0.000428, IC=+0.0058

      epoch  91/100: train_loss=0.000316

      epoch  92/100: train_loss=0.000300

      epoch  93/100: train_loss=0.000329

      epoch  94/100: train_loss=0.000329

      epoch  95/100: train_loss=0.000353, val_loss=0.000631, IC=+0.0108

      epoch  96/100: train_loss=0.000372

      epoch  97/100: train_loss=0.000341

      epoch  98/100: train_loss=0.000321

      epoch  99/100: train_loss=0.000283

      epoch 100/100: train_loss=0.000324, val_loss=0.000604, IC=+0.0110

      best_ep=5, IC=+0.0426 (47.4s, 20 checkpoints)

  tcn: best_epoch=5, IC=+0.0204 (518.7s)

  Best: tcn @ epoch 5 (IC=+0.0204)
  Saved to ~/ml4t/public-s6-fx_pairs/case_studies/fx_pairs/run_log/training/4b7bb9e55bbf/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,060 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.248975

      epoch   2/100: train_loss=0.020390

      epoch   3/100: train_loss=0.004678

      epoch   4/100: train_loss=0.002387

      epoch   5/100: train_loss=0.002294, val_loss=0.001481, IC=+0.0150

      epoch   6/100: train_loss=0.001596

      epoch   7/100: train_loss=0.001531

      epoch   8/100: train_loss=0.001555

      epoch   9/100: train_loss=0.001405

      epoch  10/100: train_loss=0.001331, val_loss=0.000701, IC=+0.0027

      epoch  11/100: train_loss=0.001265

      epoch  12/100: train_loss=0.001192

      epoch  13/100: train_loss=0.001226

      epoch  14/100: train_loss=0.001145

      epoch  15/100: train_loss=0.000981, val_loss=0.000551, IC=-0.0283

      epoch  16/100: train_loss=0.001103

      epoch  17/100: train_loss=0.000883

      epoch  18/100: train_loss=0.000921

      epoch  19/100: train_loss=0.000975

      epoch  20/100: train_loss=0.001019, val_loss=0.001060, IC=-0.0324

      epoch  21/100: train_loss=0.000998

      epoch  22/100: train_loss=0.000842

      epoch  23/100: train_loss=0.000919

      epoch  24/100: train_loss=0.000781

      epoch  25/100: train_loss=0.000825, val_loss=0.000533, IC=-0.0203

      epoch  26/100: train_loss=0.000939

      epoch  27/100: train_loss=0.000888

      epoch  28/100: train_loss=0.000891

      epoch  29/100: train_loss=0.000767

      epoch  30/100: train_loss=0.000796, val_loss=0.000437, IC=-0.0191

      epoch  31/100: train_loss=0.000726

      epoch  32/100: train_loss=0.000722

      epoch  33/100: train_loss=0.000738

      epoch  34/100: train_loss=0.000731

      epoch  35/100: train_loss=0.000725, val_loss=0.000639, IC=+0.0035

      epoch  36/100: train_loss=0.000892

      epoch  37/100: train_loss=0.000697

      epoch  38/100: train_loss=0.000667

      epoch  39/100: train_loss=0.000652

      epoch  40/100: train_loss=0.000769, val_loss=0.000415, IC=-0.0194

      epoch  41/100: train_loss=0.000653

      epoch  42/100: train_loss=0.000687

      epoch  43/100: train_loss=0.000627

      epoch  44/100: train_loss=0.000612

      epoch  45/100: train_loss=0.000651, val_loss=0.000383, IC=-0.0296

      epoch  46/100: train_loss=0.000608

      epoch  47/100: train_loss=0.000630

      epoch  48/100: train_loss=0.000588

      epoch  49/100: train_loss=0.000652

      epoch  50/100: train_loss=0.000577, val_loss=0.000331, IC=-0.0271

      epoch  51/100: train_loss=0.000628

      epoch  52/100: train_loss=0.000617

      epoch  53/100: train_loss=0.000586

      epoch  54/100: train_loss=0.000616

      epoch  55/100: train_loss=0.000576, val_loss=0.000327, IC=-0.0250

      epoch  56/100: train_loss=0.000573

      epoch  57/100: train_loss=0.000602

      epoch  58/100: train_loss=0.000572

      epoch  59/100: train_loss=0.000552

      epoch  60/100: train_loss=0.000574, val_loss=0.000352, IC=-0.0180

      epoch  61/100: train_loss=0.000585

      epoch  62/100: train_loss=0.000553

      epoch  63/100: train_loss=0.000546

      epoch  64/100: train_loss=0.000600

      epoch  65/100: train_loss=0.000591, val_loss=0.000378, IC=-0.0219

      epoch  66/100: train_loss=0.000529

      epoch  67/100: train_loss=0.000535

      epoch  68/100: train_loss=0.000539

      epoch  69/100: train_loss=0.000555

      epoch  70/100: train_loss=0.000537, val_loss=0.000399, IC=-0.0313

      epoch  71/100: train_loss=0.000498

      epoch  72/100: train_loss=0.000528

      epoch  73/100: train_loss=0.000552

      epoch  74/100: train_loss=0.000530

      epoch  75/100: train_loss=0.000567, val_loss=0.000311, IC=-0.0181

      epoch  76/100: train_loss=0.000480

      epoch  77/100: train_loss=0.000550

      epoch  78/100: train_loss=0.000546

      epoch  79/100: train_loss=0.000489

      epoch  80/100: train_loss=0.000510, val_loss=0.000327, IC=-0.0195

      epoch  81/100: train_loss=0.000509

      epoch  82/100: train_loss=0.000490

      epoch  83/100: train_loss=0.000503

      epoch  84/100: train_loss=0.000510

      epoch  85/100: train_loss=0.000524, val_loss=0.000306, IC=-0.0187

      epoch  86/100: train_loss=0.000490

      epoch  87/100: train_loss=0.000503

      epoch  88/100: train_loss=0.000502

      epoch  89/100: train_loss=0.000511

      epoch  90/100: train_loss=0.000481, val_loss=0.000344, IC=-0.0251

      epoch  91/100: train_loss=0.000515

      epoch  92/100: train_loss=0.000481

      epoch  93/100: train_loss=0.000486

      epoch  94/100: train_loss=0.000492

      epoch  95/100: train_loss=0.000504, val_loss=0.000325, IC=-0.0237

      epoch  96/100: train_loss=0.000484

      epoch  97/100: train_loss=0.000489

      epoch  98/100: train_loss=0.000482

      epoch  99/100: train_loss=0.000485

      epoch 100/100: train_loss=0.000502, val_loss=0.000321, IC=-0.0233

      best_ep=5, IC=+0.0150 (56.1s, 20 checkpoints)

  Fold 1: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.019705

      epoch   2/100: train_loss=0.003817

      epoch   3/100: train_loss=0.002303

      epoch   4/100: train_loss=0.001898

      epoch   5/100: train_loss=0.001653, val_loss=0.002862, IC=+0.1055

      epoch   6/100: train_loss=0.001516

      epoch   7/100: train_loss=0.001366

      epoch   8/100: train_loss=0.001302

      epoch   9/100: train_loss=0.001289

      epoch  10/100: train_loss=0.001205, val_loss=0.001163, IC=+0.0746

      epoch  11/100: train_loss=0.001213

      epoch  12/100: train_loss=0.001165

      epoch  13/100: train_loss=0.001090

      epoch  14/100: train_loss=0.001019

      epoch  15/100: train_loss=0.001036, val_loss=0.000897, IC=+0.0561

      epoch  16/100: train_loss=0.000950

      epoch  17/100: train_loss=0.000972

      epoch  18/100: train_loss=0.000955

      epoch  19/100: train_loss=0.000865

      epoch  20/100: train_loss=0.000841, val_loss=0.001328, IC=+0.0707

      epoch  21/100: train_loss=0.000821

      epoch  22/100: train_loss=0.000775

      epoch  23/100: train_loss=0.000749

      epoch  24/100: train_loss=0.000727

      epoch  25/100: train_loss=0.000739, val_loss=0.001225, IC=+0.0846

      epoch  26/100: train_loss=0.000713

      epoch  27/100: train_loss=0.000691

      epoch  28/100: train_loss=0.000661

      epoch  29/100: train_loss=0.000657

      epoch  30/100: train_loss=0.000631, val_loss=0.000865, IC=+0.0706

      epoch  31/100: train_loss=0.000631

      epoch  32/100: train_loss=0.000601

      epoch  33/100: train_loss=0.000626

      epoch  34/100: train_loss=0.000631

      epoch  35/100: train_loss=0.000727, val_loss=0.001184, IC=+0.0472

      epoch  36/100: train_loss=0.000665

      epoch  37/100: train_loss=0.000563

      epoch  38/100: train_loss=0.000598

      epoch  39/100: train_loss=0.000548

      epoch  40/100: train_loss=0.000553, val_loss=0.000468, IC=+0.0636

      epoch  41/100: train_loss=0.000539

      epoch  42/100: train_loss=0.000544

      epoch  43/100: train_loss=0.000569

      epoch  44/100: train_loss=0.000525

      epoch  45/100: train_loss=0.000542, val_loss=0.001188, IC=+0.0190

      epoch  46/100: train_loss=0.000492

      epoch  47/100: train_loss=0.000533

      epoch  48/100: train_loss=0.000489

      epoch  49/100: train_loss=0.000481

      epoch  50/100: train_loss=0.000500, val_loss=0.001153, IC=+0.0279

      epoch  51/100: train_loss=0.000474

      epoch  52/100: train_loss=0.000468

      epoch  53/100: train_loss=0.000459

      epoch  54/100: train_loss=0.000468

      epoch  55/100: train_loss=0.000445, val_loss=0.000624, IC=+0.0241

      epoch  56/100: train_loss=0.000461

      epoch  57/100: train_loss=0.000439

      epoch  58/100: train_loss=0.000445

      epoch  59/100: train_loss=0.000442

      epoch  60/100: train_loss=0.000431, val_loss=0.000532, IC=+0.0472

      epoch  61/100: train_loss=0.000422

      epoch  62/100: train_loss=0.000418

      epoch  63/100: train_loss=0.000431

      epoch  64/100: train_loss=0.000426

      epoch  65/100: train_loss=0.000429, val_loss=0.000419, IC=+0.0275

      epoch  66/100: train_loss=0.000442

      epoch  67/100: train_loss=0.000448

      epoch  68/100: train_loss=0.000410

      epoch  69/100: train_loss=0.000397

      epoch  70/100: train_loss=0.000412, val_loss=0.000467, IC=+0.0313

      epoch  71/100: train_loss=0.000411

      epoch  72/100: train_loss=0.000400

      epoch  73/100: train_loss=0.000381

      epoch  74/100: train_loss=0.000391

      epoch  75/100: train_loss=0.000373, val_loss=0.000448, IC=+0.0247

      epoch  76/100: train_loss=0.000395

      epoch  77/100: train_loss=0.000406

      epoch  78/100: train_loss=0.000391

      epoch  79/100: train_loss=0.000385

      epoch  80/100: train_loss=0.000409, val_loss=0.000534, IC=+0.0268

      epoch  81/100: train_loss=0.000393

      epoch  82/100: train_loss=0.000390

      epoch  83/100: train_loss=0.000396

      epoch  84/100: train_loss=0.000398

      epoch  85/100: train_loss=0.000386, val_loss=0.000618, IC=+0.0301

      epoch  86/100: train_loss=0.000395

      epoch  87/100: train_loss=0.000383

      epoch  88/100: train_loss=0.000390

      epoch  89/100: train_loss=0.000380

      epoch  90/100: train_loss=0.000388, val_loss=0.000490, IC=+0.0323

      epoch  91/100: train_loss=0.000377

      epoch  92/100: train_loss=0.000368

      epoch  93/100: train_loss=0.000373

      epoch  94/100: train_loss=0.000376

      epoch  95/100: train_loss=0.000390, val_loss=0.000485, IC=+0.0330

      epoch  96/100: train_loss=0.000377

      epoch  97/100: train_loss=0.000388

      epoch  98/100: train_loss=0.000385

      epoch  99/100: train_loss=0.000388

      epoch 100/100: train_loss=0.000388, val_loss=0.000474, IC=+0.0317

      best_ep=5, IC=+0.1055 (56.4s, 20 checkpoints)

  Fold 2: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.416736

      epoch   2/100: train_loss=0.025992

      epoch   3/100: train_loss=0.006307

      epoch   4/100: train_loss=0.002757

      epoch   5/100: train_loss=0.001926, val_loss=0.000561, IC=-0.0129

      epoch   6/100: train_loss=0.001662

      epoch   7/100: train_loss=0.001849

      epoch   8/100: train_loss=0.001408

      epoch   9/100: train_loss=0.001354

      epoch  10/100: train_loss=0.001630, val_loss=0.000466, IC=-0.0294

      epoch  11/100: train_loss=0.001387

      epoch  12/100: train_loss=0.001212

      epoch  13/100: train_loss=0.001203

      epoch  14/100: train_loss=0.001255

      epoch  15/100: train_loss=0.001086, val_loss=0.000244, IC=-0.0273

      epoch  16/100: train_loss=0.000954

      epoch  17/100: train_loss=0.000922

      epoch  18/100: train_loss=0.001041

      epoch  19/100: train_loss=0.000954

      epoch  20/100: train_loss=0.000836, val_loss=0.000239, IC=-0.0506

      epoch  21/100: train_loss=0.000811

      epoch  22/100: train_loss=0.000814

      epoch  23/100: train_loss=0.000833

      epoch  24/100: train_loss=0.000866

      epoch  25/100: train_loss=0.000829, val_loss=0.000236, IC=-0.0473

      epoch  26/100: train_loss=0.000736

      epoch  27/100: train_loss=0.000647

      epoch  28/100: train_loss=0.000689

      epoch  29/100: train_loss=0.000813

      epoch  30/100: train_loss=0.000826, val_loss=0.000201, IC=-0.0375

      epoch  31/100: train_loss=0.000707

      epoch  32/100: train_loss=0.000633

      epoch  33/100: train_loss=0.000642

      epoch  34/100: train_loss=0.000663

      epoch  35/100: train_loss=0.000696, val_loss=0.000190, IC=-0.0463

      epoch  36/100: train_loss=0.000678

      epoch  37/100: train_loss=0.000681

      epoch  38/100: train_loss=0.000627

      epoch  39/100: train_loss=0.000596

      epoch  40/100: train_loss=0.000553, val_loss=0.000187, IC=-0.0423

      epoch  41/100: train_loss=0.000585

      epoch  42/100: train_loss=0.000572

      epoch  43/100: train_loss=0.000557

      epoch  44/100: train_loss=0.000678

      epoch  45/100: train_loss=0.000658, val_loss=0.000170, IC=-0.0376

      epoch  46/100: train_loss=0.000632

      epoch  47/100: train_loss=0.000624

      epoch  48/100: train_loss=0.000598

      epoch  49/100: train_loss=0.000541

      epoch  50/100: train_loss=0.000524, val_loss=0.000176, IC=-0.0433

      epoch  51/100: train_loss=0.000560

      epoch  52/100: train_loss=0.000532

      epoch  53/100: train_loss=0.000535

      epoch  54/100: train_loss=0.000496

      epoch  55/100: train_loss=0.000516, val_loss=0.000160, IC=-0.0343

      epoch  56/100: train_loss=0.000589

      epoch  57/100: train_loss=0.000498

      epoch  58/100: train_loss=0.000505

      epoch  59/100: train_loss=0.000548

      epoch  60/100: train_loss=0.000537, val_loss=0.000155, IC=-0.0352

      epoch  61/100: train_loss=0.000517

      epoch  62/100: train_loss=0.000512

      epoch  63/100: train_loss=0.000475

      epoch  64/100: train_loss=0.000466

      epoch  65/100: train_loss=0.000451, val_loss=0.000159, IC=-0.0398

      epoch  66/100: train_loss=0.000449

      epoch  67/100: train_loss=0.000459

      epoch  68/100: train_loss=0.000462

      epoch  69/100: train_loss=0.000482

      epoch  70/100: train_loss=0.000458, val_loss=0.000166, IC=-0.0419

      epoch  71/100: train_loss=0.000490

      epoch  72/100: train_loss=0.000487

      epoch  73/100: train_loss=0.000497

      epoch  74/100: train_loss=0.000485

      epoch  75/100: train_loss=0.000469, val_loss=0.000154, IC=-0.0376

      epoch  76/100: train_loss=0.000434

      epoch  77/100: train_loss=0.000458

      epoch  78/100: train_loss=0.000467

      epoch  79/100: train_loss=0.000438

      epoch  80/100: train_loss=0.000446, val_loss=0.000162, IC=-0.0382

      epoch  81/100: train_loss=0.000463

      epoch  82/100: train_loss=0.000457

      epoch  83/100: train_loss=0.000476

      epoch  84/100: train_loss=0.000462

      epoch  85/100: train_loss=0.000438, val_loss=0.000163, IC=-0.0376

      epoch  86/100: train_loss=0.000466

      epoch  87/100: train_loss=0.000442

      epoch  88/100: train_loss=0.000495

      epoch  89/100: train_loss=0.000436

      epoch  90/100: train_loss=0.000432, val_loss=0.000161, IC=-0.0378

      epoch  91/100: train_loss=0.000429

      epoch  92/100: train_loss=0.000436

      epoch  93/100: train_loss=0.000434

      epoch  94/100: train_loss=0.000458

      epoch  95/100: train_loss=0.000447, val_loss=0.000157, IC=-0.0380

      epoch  96/100: train_loss=0.000480

      epoch  97/100: train_loss=0.000428

      epoch  98/100: train_loss=0.000421

      epoch  99/100: train_loss=0.000428

      epoch 100/100: train_loss=0.000443, val_loss=0.000155, IC=-0.0382

      best_ep=5, IC=-0.0129 (55.9s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.030084

      epoch   2/100: train_loss=0.005221

      epoch   3/100: train_loss=0.003223

      epoch   4/100: train_loss=0.002560

      epoch   5/100: train_loss=0.002304, val_loss=0.002887, IC=-0.0373

      epoch   6/100: train_loss=0.002100

      epoch   7/100: train_loss=0.002018

      epoch   8/100: train_loss=0.001871

      epoch   9/100: train_loss=0.001803

      epoch  10/100: train_loss=0.001706, val_loss=0.001685, IC=-0.0585

      epoch  11/100: train_loss=0.001693

      epoch  12/100: train_loss=0.001583

      epoch  13/100: train_loss=0.001561

      epoch  14/100: train_loss=0.001422

      epoch  15/100: train_loss=0.001418, val_loss=0.001590, IC=-0.0970

      epoch  16/100: train_loss=0.001326

      epoch  17/100: train_loss=0.001312

      epoch  18/100: train_loss=0.001266

      epoch  19/100: train_loss=0.001231

      epoch  20/100: train_loss=0.001191, val_loss=0.001101, IC=-0.0956

      epoch  21/100: train_loss=0.001187

      epoch  22/100: train_loss=0.001191

      epoch  23/100: train_loss=0.001096

      epoch  24/100: train_loss=0.001072

      epoch  25/100: train_loss=0.001013, val_loss=0.000922, IC=-0.0939

      epoch  26/100: train_loss=0.001008

      epoch  27/100: train_loss=0.001005

      epoch  28/100: train_loss=0.000997

      epoch  29/100: train_loss=0.000983

      epoch  30/100: train_loss=0.000947, val_loss=0.001006, IC=-0.1024

      epoch  31/100: train_loss=0.000920

      epoch  32/100: train_loss=0.000869

      epoch  33/100: train_loss=0.000867

      epoch  34/100: train_loss=0.000849

      epoch  35/100: train_loss=0.000854, val_loss=0.000844, IC=-0.0970

      epoch  36/100: train_loss=0.000862

      epoch  37/100: train_loss=0.000806

      epoch  38/100: train_loss=0.000812

      epoch  39/100: train_loss=0.000782

      epoch  40/100: train_loss=0.000778, val_loss=0.000725, IC=-0.0963

      epoch  41/100: train_loss=0.000757

      epoch  42/100: train_loss=0.000760

      epoch  43/100: train_loss=0.000774

      epoch  44/100: train_loss=0.000728

      epoch  45/100: train_loss=0.000750, val_loss=0.000654, IC=-0.0880

      epoch  46/100: train_loss=0.000746

      epoch  47/100: train_loss=0.000711

      epoch  48/100: train_loss=0.000679

      epoch  49/100: train_loss=0.000684

      epoch  50/100: train_loss=0.000683, val_loss=0.000622, IC=-0.0911

      epoch  51/100: train_loss=0.000680

      epoch  52/100: train_loss=0.000667

      epoch  53/100: train_loss=0.000663

      epoch  54/100: train_loss=0.000630

      epoch  55/100: train_loss=0.000635, val_loss=0.000664, IC=-0.0868

      epoch  56/100: train_loss=0.000650

      epoch  57/100: train_loss=0.000653

      epoch  58/100: train_loss=0.000618

      epoch  59/100: train_loss=0.000634

      epoch  60/100: train_loss=0.000638, val_loss=0.000590, IC=-0.0900

      epoch  61/100: train_loss=0.000624

      epoch  62/100: train_loss=0.000619

      epoch  63/100: train_loss=0.000608

      epoch  64/100: train_loss=0.000611

      epoch  65/100: train_loss=0.000594, val_loss=0.000609, IC=-0.0943

      epoch  66/100: train_loss=0.000589

      epoch  67/100: train_loss=0.000589

      epoch  68/100: train_loss=0.000593

      epoch  69/100: train_loss=0.000589

      epoch  70/100: train_loss=0.000597, val_loss=0.000552, IC=-0.0830

      epoch  71/100: train_loss=0.000579

      epoch  72/100: train_loss=0.000591

      epoch  73/100: train_loss=0.000581

      epoch  74/100: train_loss=0.000578

      epoch  75/100: train_loss=0.000588, val_loss=0.000610, IC=-0.0817

      epoch  76/100: train_loss=0.000585

      epoch  77/100: train_loss=0.000565

      epoch  78/100: train_loss=0.000559

      epoch  79/100: train_loss=0.000554

      epoch  80/100: train_loss=0.000559, val_loss=0.000531, IC=-0.0808

      epoch  81/100: train_loss=0.000553

      epoch  82/100: train_loss=0.000540

      epoch  83/100: train_loss=0.000546

      epoch  84/100: train_loss=0.000541

      epoch  85/100: train_loss=0.000552, val_loss=0.000513, IC=-0.0839

      epoch  86/100: train_loss=0.000557

      epoch  87/100: train_loss=0.000543

      epoch  88/100: train_loss=0.000548

      epoch  89/100: train_loss=0.000543

      epoch  90/100: train_loss=0.000550, val_loss=0.000510, IC=-0.0779

      epoch  91/100: train_loss=0.000544

      epoch  92/100: train_loss=0.000546

      epoch  93/100: train_loss=0.000544

      epoch  94/100: train_loss=0.000541

      epoch  95/100: train_loss=0.000565, val_loss=0.000526, IC=-0.0797

      epoch  96/100: train_loss=0.000541

      epoch  97/100: train_loss=0.000550

      epoch  98/100: train_loss=0.000537

      epoch  99/100: train_loss=0.000555

      epoch 100/100: train_loss=0.000544, val_loss=0.000517, IC=-0.0800

      best_ep=5, IC=-0.0373 (56.1s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.021526

      epoch   2/100: train_loss=0.004394

      epoch   3/100: train_loss=0.002814

      epoch   4/100: train_loss=0.002208

      epoch   5/100: train_loss=0.001936, val_loss=0.000941, IC=+0.0089

      epoch   6/100: train_loss=0.001785

      epoch   7/100: train_loss=0.001694

      epoch   8/100: train_loss=0.001626

      epoch   9/100: train_loss=0.001500

      epoch  10/100: train_loss=0.001453, val_loss=0.000594, IC=+0.0293

      epoch  11/100: train_loss=0.001333

      epoch  12/100: train_loss=0.001314

      epoch  13/100: train_loss=0.001325

      epoch  14/100: train_loss=0.001244

      epoch  15/100: train_loss=0.001161, val_loss=0.000415, IC=+0.0399

      epoch  16/100: train_loss=0.001110

      epoch  17/100: train_loss=0.001045

      epoch  18/100: train_loss=0.001042

      epoch  19/100: train_loss=0.001059

      epoch  20/100: train_loss=0.000989, val_loss=0.000479, IC=+0.0443

      epoch  21/100: train_loss=0.000963

      epoch  22/100: train_loss=0.000959

      epoch  23/100: train_loss=0.000999

      epoch  24/100: train_loss=0.001052

      epoch  25/100: train_loss=0.000912, val_loss=0.000328, IC=+0.0523

      epoch  26/100: train_loss=0.000850

      epoch  27/100: train_loss=0.000800

      epoch  28/100: train_loss=0.000806

      epoch  29/100: train_loss=0.000795

      epoch  30/100: train_loss=0.000804, val_loss=0.000265, IC=+0.0432

      epoch  31/100: train_loss=0.000813

      epoch  32/100: train_loss=0.000763

      epoch  33/100: train_loss=0.000796

      epoch  34/100: train_loss=0.000799

      epoch  35/100: train_loss=0.000719, val_loss=0.000250, IC=+0.0544

      epoch  36/100: train_loss=0.000705

      epoch  37/100: train_loss=0.000683

      epoch  38/100: train_loss=0.000672

      epoch  39/100: train_loss=0.000687

      epoch  40/100: train_loss=0.000702, val_loss=0.000237, IC=+0.0553

      epoch  41/100: train_loss=0.000675

      epoch  42/100: train_loss=0.000672

      epoch  43/100: train_loss=0.000669

      epoch  44/100: train_loss=0.000633

      epoch  45/100: train_loss=0.000616, val_loss=0.000238, IC=+0.0626

      epoch  46/100: train_loss=0.000577

      epoch  47/100: train_loss=0.000599

      epoch  48/100: train_loss=0.000612

      epoch  49/100: train_loss=0.000616

      epoch  50/100: train_loss=0.000599, val_loss=0.000258, IC=+0.0664

      epoch  51/100: train_loss=0.000593

      epoch  52/100: train_loss=0.000610

      epoch  53/100: train_loss=0.000610

      epoch  54/100: train_loss=0.000574

      epoch  55/100: train_loss=0.000582, val_loss=0.000261, IC=+0.0613

      epoch  56/100: train_loss=0.000583

      epoch  57/100: train_loss=0.000565

      epoch  58/100: train_loss=0.000543

      epoch  59/100: train_loss=0.000541

      epoch  60/100: train_loss=0.000605, val_loss=0.000225, IC=+0.0687

      epoch  61/100: train_loss=0.000563

      epoch  62/100: train_loss=0.000517

      epoch  63/100: train_loss=0.000513

      epoch  64/100: train_loss=0.000494

      epoch  65/100: train_loss=0.000557, val_loss=0.000185, IC=+0.0746

      epoch  66/100: train_loss=0.000563

      epoch  67/100: train_loss=0.000553

      epoch  68/100: train_loss=0.000552

      epoch  69/100: train_loss=0.000542

      epoch  70/100: train_loss=0.000508, val_loss=0.000188, IC=+0.0677

      epoch  71/100: train_loss=0.000549

      epoch  72/100: train_loss=0.000504

      epoch  73/100: train_loss=0.000494

      epoch  74/100: train_loss=0.000486

      epoch  75/100: train_loss=0.000504, val_loss=0.000225, IC=+0.0728

      epoch  76/100: train_loss=0.000521

      epoch  77/100: train_loss=0.000497

      epoch  78/100: train_loss=0.000512

      epoch  79/100: train_loss=0.000494

      epoch  80/100: train_loss=0.000481, val_loss=0.000206, IC=+0.0751

      epoch  81/100: train_loss=0.000495

      epoch  82/100: train_loss=0.000512

      epoch  83/100: train_loss=0.000510

      epoch  84/100: train_loss=0.000478

      epoch  85/100: train_loss=0.000480, val_loss=0.000200, IC=+0.0680

      epoch  86/100: train_loss=0.000465

      epoch  87/100: train_loss=0.000481

      epoch  88/100: train_loss=0.000472

      epoch  89/100: train_loss=0.000503

      epoch  90/100: train_loss=0.000491, val_loss=0.000193, IC=+0.0709

      epoch  91/100: train_loss=0.000481

      epoch  92/100: train_loss=0.000464

      epoch  93/100: train_loss=0.000478

      epoch  94/100: train_loss=0.000493

      epoch  95/100: train_loss=0.000465, val_loss=0.000190, IC=+0.0721

      epoch  96/100: train_loss=0.000469

      epoch  97/100: train_loss=0.000488

      epoch  98/100: train_loss=0.000476

      epoch  99/100: train_loss=0.000477

      epoch 100/100: train_loss=0.000480, val_loss=0.000197, IC=+0.0699

      best_ep=80, IC=+0.0751 (56.6s, 20 checkpoints)

  Fold 5: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.016431

      epoch   2/100: train_loss=0.002781

      epoch   3/100: train_loss=0.001647

      epoch   4/100: train_loss=0.001309

      epoch   5/100: train_loss=0.001193, val_loss=0.001000, IC=-0.0345

      epoch   6/100: train_loss=0.001115

      epoch   7/100: train_loss=0.001067

      epoch   8/100: train_loss=0.000992

      epoch   9/100: train_loss=0.000971

      epoch  10/100: train_loss=0.000947, val_loss=0.000705, IC=-0.0231

      epoch  11/100: train_loss=0.000896

      epoch  12/100: train_loss=0.000864

      epoch  13/100: train_loss=0.000840

      epoch  14/100: train_loss=0.000819

      epoch  15/100: train_loss=0.000791, val_loss=0.000611, IC=-0.0120

      epoch  16/100: train_loss=0.000763

      epoch  17/100: train_loss=0.000741

      epoch  18/100: train_loss=0.000687

      epoch  19/100: train_loss=0.000716

      epoch  20/100: train_loss=0.000686, val_loss=0.000370, IC=+0.0004

      epoch  21/100: train_loss=0.000666

      epoch  22/100: train_loss=0.000676

      epoch  23/100: train_loss=0.000656

      epoch  24/100: train_loss=0.000696

      epoch  25/100: train_loss=0.000625, val_loss=0.000502, IC=-0.0152

      epoch  26/100: train_loss=0.000617

      epoch  27/100: train_loss=0.000598

      epoch  28/100: train_loss=0.000623

      epoch  29/100: train_loss=0.000600

      epoch  30/100: train_loss=0.000582, val_loss=0.000330, IC=+0.0122

      epoch  31/100: train_loss=0.000565

      epoch  32/100: train_loss=0.000550

      epoch  33/100: train_loss=0.000533

      epoch  34/100: train_loss=0.000543

      epoch  35/100: train_loss=0.000544, val_loss=0.000248, IC=+0.0113

      epoch  36/100: train_loss=0.000525

      epoch  37/100: train_loss=0.000519

      epoch  38/100: train_loss=0.000502

      epoch  39/100: train_loss=0.000510

      epoch  40/100: train_loss=0.000489, val_loss=0.000235, IC=+0.0085

      epoch  41/100: train_loss=0.000488

      epoch  42/100: train_loss=0.000465

      epoch  43/100: train_loss=0.000459

      epoch  44/100: train_loss=0.000457

      epoch  45/100: train_loss=0.000456, val_loss=0.000277, IC=+0.0074

      epoch  46/100: train_loss=0.000460

      epoch  47/100: train_loss=0.000453

      epoch  48/100: train_loss=0.000466

      epoch  49/100: train_loss=0.000452

      epoch  50/100: train_loss=0.000448, val_loss=0.000212, IC=+0.0164

      epoch  51/100: train_loss=0.000432

      epoch  52/100: train_loss=0.000435

      epoch  53/100: train_loss=0.000427

      epoch  54/100: train_loss=0.000430

      epoch  55/100: train_loss=0.000443, val_loss=0.000245, IC=+0.0071

      epoch  56/100: train_loss=0.000426

      epoch  57/100: train_loss=0.000423

      epoch  58/100: train_loss=0.000422

      epoch  59/100: train_loss=0.000420

      epoch  60/100: train_loss=0.000414, val_loss=0.000219, IC=+0.0184

      epoch  61/100: train_loss=0.000410

      epoch  62/100: train_loss=0.000408

      epoch  63/100: train_loss=0.000407

      epoch  64/100: train_loss=0.000405

      epoch  65/100: train_loss=0.000398, val_loss=0.000205, IC=+0.0207

      epoch  66/100: train_loss=0.000406

      epoch  67/100: train_loss=0.000402

      epoch  68/100: train_loss=0.000393

      epoch  69/100: train_loss=0.000388

      epoch  70/100: train_loss=0.000386, val_loss=0.000224, IC=+0.0205

      epoch  71/100: train_loss=0.000394

      epoch  72/100: train_loss=0.000401

      epoch  73/100: train_loss=0.000397

      epoch  74/100: train_loss=0.000378

      epoch  75/100: train_loss=0.000390, val_loss=0.000254, IC=+0.0175

      epoch  76/100: train_loss=0.000385

      epoch  77/100: train_loss=0.000389

      epoch  78/100: train_loss=0.000382

      epoch  79/100: train_loss=0.000382

      epoch  80/100: train_loss=0.000390, val_loss=0.000199, IC=+0.0226

      epoch  81/100: train_loss=0.000387

      epoch  82/100: train_loss=0.000388

      epoch  83/100: train_loss=0.000381

      epoch  84/100: train_loss=0.000383

      epoch  85/100: train_loss=0.000387, val_loss=0.000198, IC=+0.0215

      epoch  86/100: train_loss=0.000383

      epoch  87/100: train_loss=0.000386

      epoch  88/100: train_loss=0.000375

      epoch  89/100: train_loss=0.000387

      epoch  90/100: train_loss=0.000380, val_loss=0.000202, IC=+0.0220

      epoch  91/100: train_loss=0.000385

      epoch  92/100: train_loss=0.000380

      epoch  93/100: train_loss=0.000376

      epoch  94/100: train_loss=0.000379

      epoch  95/100: train_loss=0.000373, val_loss=0.000205, IC=+0.0232

      epoch  96/100: train_loss=0.000369

      epoch  97/100: train_loss=0.000375

      epoch  98/100: train_loss=0.000383

      epoch  99/100: train_loss=0.000390

      epoch 100/100: train_loss=0.000370, val_loss=0.000209, IC=+0.0219

      best_ep=95, IC=+0.0232 (56.2s, 20 checkpoints)

  Fold 6: creating sequences...
    train=22,140 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.052855

      epoch   2/100: train_loss=0.005431

      epoch   3/100: train_loss=0.002894

      epoch   4/100: train_loss=0.002069

      epoch   5/100: train_loss=0.001826, val_loss=0.001633, IC=-0.0171

      epoch   6/100: train_loss=0.001652

      epoch   7/100: train_loss=0.001413

      epoch   8/100: train_loss=0.001394

      epoch   9/100: train_loss=0.001373

      epoch  10/100: train_loss=0.001296, val_loss=0.001467, IC=-0.0095

      epoch  11/100: train_loss=0.001266

      epoch  12/100: train_loss=0.001137

      epoch  13/100: train_loss=0.001061

      epoch  14/100: train_loss=0.001045

      epoch  15/100: train_loss=0.001038, val_loss=0.001501, IC=-0.0041

      epoch  16/100: train_loss=0.001015

      epoch  17/100: train_loss=0.000973

      epoch  18/100: train_loss=0.000880

      epoch  19/100: train_loss=0.000852

      epoch  20/100: train_loss=0.000841, val_loss=0.000641, IC=+0.0050

      epoch  21/100: train_loss=0.000823

      epoch  22/100: train_loss=0.000786

      epoch  23/100: train_loss=0.000783

      epoch  24/100: train_loss=0.000772

      epoch  25/100: train_loss=0.000827, val_loss=0.000366, IC=+0.0714

      epoch  26/100: train_loss=0.000786

      epoch  27/100: train_loss=0.000757

      epoch  28/100: train_loss=0.000710

      epoch  29/100: train_loss=0.000667

      epoch  30/100: train_loss=0.000690, val_loss=0.000436, IC=+0.0282

      epoch  31/100: train_loss=0.000724

      epoch  32/100: train_loss=0.000694

      epoch  33/100: train_loss=0.000697

      epoch  34/100: train_loss=0.000659

      epoch  35/100: train_loss=0.000679, val_loss=0.000375, IC=+0.0151

      epoch  36/100: train_loss=0.000623

      epoch  37/100: train_loss=0.000592

      epoch  38/100: train_loss=0.000567

      epoch  39/100: train_loss=0.000567

      epoch  40/100: train_loss=0.000566, val_loss=0.000349, IC=+0.0460

      epoch  41/100: train_loss=0.000556

      epoch  42/100: train_loss=0.000538

      epoch  43/100: train_loss=0.000547

      epoch  44/100: train_loss=0.000551

      epoch  45/100: train_loss=0.000558, val_loss=0.000248, IC=+0.0504

      epoch  46/100: train_loss=0.000594

      epoch  47/100: train_loss=0.000604

      epoch  48/100: train_loss=0.000517

      epoch  49/100: train_loss=0.000528

      epoch  50/100: train_loss=0.000510, val_loss=0.000304, IC=+0.0177

      epoch  51/100: train_loss=0.000512

      epoch  52/100: train_loss=0.000507

      epoch  53/100: train_loss=0.000514

      epoch  54/100: train_loss=0.000507

      epoch  55/100: train_loss=0.000544, val_loss=0.000284, IC=+0.0435

      epoch  56/100: train_loss=0.000492

      epoch  57/100: train_loss=0.000518

      epoch  58/100: train_loss=0.000521

      epoch  59/100: train_loss=0.000477

      epoch  60/100: train_loss=0.000481, val_loss=0.000282, IC=+0.0057

      epoch  61/100: train_loss=0.000485

      epoch  62/100: train_loss=0.000507

      epoch  63/100: train_loss=0.000511

      epoch  64/100: train_loss=0.000481

      epoch  65/100: train_loss=0.000472, val_loss=0.000235, IC=+0.0279

      epoch  66/100: train_loss=0.000484

      epoch  67/100: train_loss=0.000444

      epoch  68/100: train_loss=0.000455

      epoch  69/100: train_loss=0.000456

      epoch  70/100: train_loss=0.000450, val_loss=0.000263, IC=+0.0069

      epoch  71/100: train_loss=0.000445

      epoch  72/100: train_loss=0.000436

      epoch  73/100: train_loss=0.000442

      epoch  74/100: train_loss=0.000442

      epoch  75/100: train_loss=0.000443, val_loss=0.000237, IC=+0.0241

      epoch  76/100: train_loss=0.000460

      epoch  77/100: train_loss=0.000446

      epoch  78/100: train_loss=0.000451

      epoch  79/100: train_loss=0.000443

      epoch  80/100: train_loss=0.000438, val_loss=0.000242, IC=+0.0175

      epoch  81/100: train_loss=0.000424

      epoch  82/100: train_loss=0.000442

      epoch  83/100: train_loss=0.000442

      epoch  84/100: train_loss=0.000432

      epoch  85/100: train_loss=0.000420, val_loss=0.000248, IC=+0.0146

      epoch  86/100: train_loss=0.000434

      epoch  87/100: train_loss=0.000426

      epoch  88/100: train_loss=0.000437

      epoch  89/100: train_loss=0.000429

      epoch  90/100: train_loss=0.000429, val_loss=0.000230, IC=+0.0286

      epoch  91/100: train_loss=0.000438

      epoch  92/100: train_loss=0.000439

      epoch  93/100: train_loss=0.000431

      epoch  94/100: train_loss=0.000417

      epoch  95/100: train_loss=0.000452, val_loss=0.000251, IC=+0.0142

      epoch  96/100: train_loss=0.000440

      epoch  97/100: train_loss=0.000426

      epoch  98/100: train_loss=0.000422

      epoch  99/100: train_loss=0.000439

      epoch 100/100: train_loss=0.000428, val_loss=0.000239, IC=+0.0146

      best_ep=25, IC=+0.0714 (50.9s, 20 checkpoints)

  Fold 7: creating sequences...
    train=16,980 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.455514

      epoch   2/100: train_loss=0.048444

      epoch   3/100: train_loss=0.006435

      epoch   4/100: train_loss=0.003022

      epoch   5/100: train_loss=0.002218, val_loss=0.004442, IC=+0.0609

      epoch   6/100: train_loss=0.001786

      epoch   7/100: train_loss=0.001710

      epoch   8/100: train_loss=0.001508

      epoch   9/100: train_loss=0.001408

      epoch  10/100: train_loss=0.001553, val_loss=0.004826, IC=+0.0460

      epoch  11/100: train_loss=0.001361

      epoch  12/100: train_loss=0.001640

      epoch  13/100: train_loss=0.001065

      epoch  14/100: train_loss=0.001007

      epoch  15/100: train_loss=0.001104, val_loss=0.000721, IC=+0.0382

      epoch  16/100: train_loss=0.001094

      epoch  17/100: train_loss=0.001399

      epoch  18/100: train_loss=0.001623

      epoch  19/100: train_loss=0.001719

      epoch  20/100: train_loss=0.001226, val_loss=0.001625, IC=+0.0596

      epoch  21/100: train_loss=0.001062

      epoch  22/100: train_loss=0.000832

      epoch  23/100: train_loss=0.000756

      epoch  24/100: train_loss=0.000760

      epoch  25/100: train_loss=0.000692, val_loss=0.001132, IC=+0.0586

      epoch  26/100: train_loss=0.000800

      epoch  27/100: train_loss=0.000731

      epoch  28/100: train_loss=0.000721

      epoch  29/100: train_loss=0.000789

      epoch  30/100: train_loss=0.000779, val_loss=0.002350, IC=+0.0512

      epoch  31/100: train_loss=0.000662

      epoch  32/100: train_loss=0.000625

      epoch  33/100: train_loss=0.000674

      epoch  34/100: train_loss=0.000609

      epoch  35/100: train_loss=0.000716, val_loss=0.001728, IC=+0.0533

      epoch  36/100: train_loss=0.000637

      epoch  37/100: train_loss=0.000519

      epoch  38/100: train_loss=0.000818

      epoch  39/100: train_loss=0.000697

      epoch  40/100: train_loss=0.000704, val_loss=0.002210, IC=+0.0250

      epoch  41/100: train_loss=0.000577

      epoch  42/100: train_loss=0.000744

      epoch  43/100: train_loss=0.000556

      epoch  44/100: train_loss=0.000565

      epoch  45/100: train_loss=0.000630, val_loss=0.001156, IC=+0.0387

      epoch  46/100: train_loss=0.000556

      epoch  47/100: train_loss=0.000487

      epoch  48/100: train_loss=0.000507

      epoch  49/100: train_loss=0.000697

      epoch  50/100: train_loss=0.000596, val_loss=0.002434, IC=+0.0292

      epoch  51/100: train_loss=0.000626

      epoch  52/100: train_loss=0.000681

      epoch  53/100: train_loss=0.000591

      epoch  54/100: train_loss=0.000578

      epoch  55/100: train_loss=0.000503, val_loss=0.000596, IC=+0.0162

      epoch  56/100: train_loss=0.000576

      epoch  57/100: train_loss=0.000554

      epoch  58/100: train_loss=0.000467

      epoch  59/100: train_loss=0.000454

      epoch  60/100: train_loss=0.000464, val_loss=0.001233, IC=+0.0222

      epoch  61/100: train_loss=0.000474

      epoch  62/100: train_loss=0.000520

      epoch  63/100: train_loss=0.000462

      epoch  64/100: train_loss=0.000468

      epoch  65/100: train_loss=0.000455, val_loss=0.000672, IC=+0.0197

      epoch  66/100: train_loss=0.000490

      epoch  67/100: train_loss=0.000469

      epoch  68/100: train_loss=0.000446

      epoch  69/100: train_loss=0.000429

      epoch  70/100: train_loss=0.000460, val_loss=0.001184, IC=+0.0244

      epoch  71/100: train_loss=0.000495

      epoch  72/100: train_loss=0.000460

      epoch  73/100: train_loss=0.000466

      epoch  74/100: train_loss=0.000425

      epoch  75/100: train_loss=0.000458, val_loss=0.000558, IC=+0.0204

      epoch  76/100: train_loss=0.000463

      epoch  77/100: train_loss=0.000475

      epoch  78/100: train_loss=0.000472

      epoch  79/100: train_loss=0.000448

      epoch  80/100: train_loss=0.000441, val_loss=0.000841, IC=+0.0237

      epoch  81/100: train_loss=0.000454

      epoch  82/100: train_loss=0.000445

      epoch  83/100: train_loss=0.000471

      epoch  84/100: train_loss=0.000434

      epoch  85/100: train_loss=0.000477, val_loss=0.001314, IC=+0.0214

      epoch  86/100: train_loss=0.000475

      epoch  87/100: train_loss=0.000421

      epoch  88/100: train_loss=0.000472

      epoch  89/100: train_loss=0.000429

      epoch  90/100: train_loss=0.000413, val_loss=0.000868, IC=+0.0219

      epoch  91/100: train_loss=0.000415

      epoch  92/100: train_loss=0.000404

      epoch  93/100: train_loss=0.000477

      epoch  94/100: train_loss=0.000459

      epoch  95/100: train_loss=0.000460, val_loss=0.000928, IC=+0.0222

      epoch  96/100: train_loss=0.000416

      epoch  97/100: train_loss=0.000418

      epoch  98/100: train_loss=0.000489

      epoch  99/100: train_loss=0.000413

      epoch 100/100: train_loss=0.000421, val_loss=0.000831, IC=+0.0238

      best_ep=5, IC=+0.0609 (39.9s, 20 checkpoints)

  tcn: best_epoch=25, IC=+0.0114 (428.0s)

  Best: tcn @ epoch 25 (IC=+0.0114)
  Saved to ~/ml4t/public-s6-fx_pairs/case_studies/fx_pairs/run_log/training/90b5f579f125/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=24,180 seq across 20 symbols
    val=4,740 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.242756

      epoch   2/100: train_loss=0.019294

      epoch   3/100: train_loss=0.005540

      epoch   4/100: train_loss=0.003131

      epoch   5/100: train_loss=0.002173, val_loss=0.001939, IC=-0.0324

      epoch   6/100: train_loss=0.002082

      epoch   7/100: train_loss=0.001858

      epoch   8/100: train_loss=0.001648

      epoch   9/100: train_loss=0.001587

      epoch  10/100: train_loss=0.001603, val_loss=0.001494, IC=-0.0994

      epoch  11/100: train_loss=0.001530

      epoch  12/100: train_loss=0.001462

      epoch  13/100: train_loss=0.001575

      epoch  14/100: train_loss=0.001519

      epoch  15/100: train_loss=0.001528, val_loss=0.001639, IC=-0.1421

      epoch  16/100: train_loss=0.001362

      epoch  17/100: train_loss=0.001229

      epoch  18/100: train_loss=0.001503

      epoch  19/100: train_loss=0.001360

      epoch  20/100: train_loss=0.001293, val_loss=0.001618, IC=-0.0682

      epoch  21/100: train_loss=0.001262

      epoch  22/100: train_loss=0.001185

      epoch  23/100: train_loss=0.001139

      epoch  24/100: train_loss=0.001255

      epoch  25/100: train_loss=0.001111, val_loss=0.001132, IC=-0.0332

      epoch  26/100: train_loss=0.000995

      epoch  27/100: train_loss=0.000982

      epoch  28/100: train_loss=0.000936

      epoch  29/100: train_loss=0.001044

      epoch  30/100: train_loss=0.001070, val_loss=0.001129, IC=-0.0467

      epoch  31/100: train_loss=0.000954

      epoch  32/100: train_loss=0.001010

      epoch  33/100: train_loss=0.000997

      epoch  34/100: train_loss=0.000823

      epoch  35/100: train_loss=0.000890, val_loss=0.001159, IC=-0.0674

      epoch  36/100: train_loss=0.000811

      epoch  37/100: train_loss=0.000845

      epoch  38/100: train_loss=0.000884

      epoch  39/100: train_loss=0.000901

      epoch  40/100: train_loss=0.000924, val_loss=0.001398, IC=-0.0771

      epoch  41/100: train_loss=0.000805

      epoch  42/100: train_loss=0.000812

      epoch  43/100: train_loss=0.000783

      epoch  44/100: train_loss=0.000784

      epoch  45/100: train_loss=0.000769, val_loss=0.001270, IC=-0.0513

      epoch  46/100: train_loss=0.000830

      epoch  47/100: train_loss=0.000831

      epoch  48/100: train_loss=0.000827

      epoch  49/100: train_loss=0.000737

      epoch  50/100: train_loss=0.000733, val_loss=0.001048, IC=-0.0459

      epoch  51/100: train_loss=0.000733

      epoch  52/100: train_loss=0.000760

      epoch  53/100: train_loss=0.000828

      epoch  54/100: train_loss=0.000779

      epoch  55/100: train_loss=0.000768, val_loss=0.001112, IC=-0.0402

      epoch  56/100: train_loss=0.000728

      epoch  57/100: train_loss=0.000659

      epoch  58/100: train_loss=0.000684

      epoch  59/100: train_loss=0.000673

      epoch  60/100: train_loss=0.000684, val_loss=0.001129, IC=-0.0496

      epoch  61/100: train_loss=0.000697

      epoch  62/100: train_loss=0.000731

      epoch  63/100: train_loss=0.000760

      epoch  64/100: train_loss=0.000673

      epoch  65/100: train_loss=0.000694, val_loss=0.001137, IC=-0.0581

      epoch  66/100: train_loss=0.000726

      epoch  67/100: train_loss=0.000649

      epoch  68/100: train_loss=0.000656

      epoch  69/100: train_loss=0.000645

      epoch  70/100: train_loss=0.000648, val_loss=0.001114, IC=-0.0506

      epoch  71/100: train_loss=0.000649

      epoch  72/100: train_loss=0.000680

      epoch  73/100: train_loss=0.000619

      epoch  74/100: train_loss=0.000629

      epoch  75/100: train_loss=0.000646, val_loss=0.001091, IC=-0.0436

      epoch  76/100: train_loss=0.000612

      epoch  77/100: train_loss=0.000628

      epoch  78/100: train_loss=0.000635

      epoch  79/100: train_loss=0.000647

      epoch  80/100: train_loss=0.000652, val_loss=0.001067, IC=-0.0428

      epoch  81/100: train_loss=0.000665

      epoch  82/100: train_loss=0.000638

      epoch  83/100: train_loss=0.000650

      epoch  84/100: train_loss=0.000647

      epoch  85/100: train_loss=0.000660, val_loss=0.001084, IC=-0.0485

      epoch  86/100: train_loss=0.000606

      epoch  87/100: train_loss=0.000622

      epoch  88/100: train_loss=0.000624

      epoch  89/100: train_loss=0.000637

      epoch  90/100: train_loss=0.000622, val_loss=0.001073, IC=-0.0462

      epoch  91/100: train_loss=0.000612

      epoch  92/100: train_loss=0.000556

      epoch  93/100: train_loss=0.000621

      epoch  94/100: train_loss=0.000613

      epoch  95/100: train_loss=0.000612, val_loss=0.001079, IC=-0.0481

      epoch  96/100: train_loss=0.000601

      epoch  97/100: train_loss=0.000608

      epoch  98/100: train_loss=0.000619

      epoch  99/100: train_loss=0.000593

      epoch 100/100: train_loss=0.000600, val_loss=0.001075, IC=-0.0493

      best_ep=5, IC=-0.0324 (55.2s, 20 checkpoints)

  Fold 1: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.020017

      epoch   2/100: train_loss=0.004283

      epoch   3/100: train_loss=0.002625

      epoch   4/100: train_loss=0.002177

      epoch   5/100: train_loss=0.001987, val_loss=0.002477, IC=+0.0851

      epoch   6/100: train_loss=0.001833

      epoch   7/100: train_loss=0.001646

      epoch   8/100: train_loss=0.001518

      epoch   9/100: train_loss=0.001482

      epoch  10/100: train_loss=0.001451, val_loss=0.002367, IC=+0.0483

      epoch  11/100: train_loss=0.001373

      epoch  12/100: train_loss=0.001288

      epoch  13/100: train_loss=0.001225

      epoch  14/100: train_loss=0.001204

      epoch  15/100: train_loss=0.001138, val_loss=0.002560, IC=+0.0383

      epoch  16/100: train_loss=0.001106

      epoch  17/100: train_loss=0.001118

      epoch  18/100: train_loss=0.001052

      epoch  19/100: train_loss=0.001028

      epoch  20/100: train_loss=0.001020, val_loss=0.002121, IC=+0.0495

      epoch  21/100: train_loss=0.001018

      epoch  22/100: train_loss=0.000953

      epoch  23/100: train_loss=0.000943

      epoch  24/100: train_loss=0.000963

      epoch  25/100: train_loss=0.000856, val_loss=0.003050, IC=+0.0658

      epoch  26/100: train_loss=0.000891

      epoch  27/100: train_loss=0.000823

      epoch  28/100: train_loss=0.000830

      epoch  29/100: train_loss=0.000808

      epoch  30/100: train_loss=0.000762, val_loss=0.002040, IC=+0.0564

      epoch  31/100: train_loss=0.000818

      epoch  32/100: train_loss=0.000791

      epoch  33/100: train_loss=0.000806

      epoch  34/100: train_loss=0.000756

      epoch  35/100: train_loss=0.000704, val_loss=0.002314, IC=+0.0579

      epoch  36/100: train_loss=0.000743

      epoch  37/100: train_loss=0.000777

      epoch  38/100: train_loss=0.000768

      epoch  39/100: train_loss=0.000837

      epoch  40/100: train_loss=0.000696, val_loss=0.002117, IC=+0.0550

      epoch  41/100: train_loss=0.000660

      epoch  42/100: train_loss=0.000678

      epoch  43/100: train_loss=0.000636

      epoch  44/100: train_loss=0.000630

      epoch  45/100: train_loss=0.000635, val_loss=0.002048, IC=+0.0769

      epoch  46/100: train_loss=0.000601

      epoch  47/100: train_loss=0.000625

      epoch  48/100: train_loss=0.000599

      epoch  49/100: train_loss=0.000606

      epoch  50/100: train_loss=0.000602, val_loss=0.001837, IC=+0.0728

      epoch  51/100: train_loss=0.000622

      epoch  52/100: train_loss=0.000598

      epoch  53/100: train_loss=0.000599

      epoch  54/100: train_loss=0.000571

      epoch  55/100: train_loss=0.000590, val_loss=0.002560, IC=+0.0857

      epoch  56/100: train_loss=0.000585

      epoch  57/100: train_loss=0.000568

      epoch  58/100: train_loss=0.000551

      epoch  59/100: train_loss=0.000582

      epoch  60/100: train_loss=0.000569, val_loss=0.002311, IC=+0.0741

      epoch  61/100: train_loss=0.000549

      epoch  62/100: train_loss=0.000556

      epoch  63/100: train_loss=0.000555

      epoch  64/100: train_loss=0.000528

      epoch  65/100: train_loss=0.000537, val_loss=0.002163, IC=+0.0674

      epoch  66/100: train_loss=0.000545

      epoch  67/100: train_loss=0.000523

      epoch  68/100: train_loss=0.000541

      epoch  69/100: train_loss=0.000530

      epoch  70/100: train_loss=0.000548, val_loss=0.001738, IC=+0.0827

      epoch  71/100: train_loss=0.000528

      epoch  72/100: train_loss=0.000541

      epoch  73/100: train_loss=0.000546

      epoch  74/100: train_loss=0.000524

      epoch  75/100: train_loss=0.000537, val_loss=0.001920, IC=+0.0788

      epoch  76/100: train_loss=0.000502

      epoch  77/100: train_loss=0.000510

      epoch  78/100: train_loss=0.000503

      epoch  79/100: train_loss=0.000511

      epoch  80/100: train_loss=0.000489, val_loss=0.001906, IC=+0.0790

      epoch  81/100: train_loss=0.000517

      epoch  82/100: train_loss=0.000497

      epoch  83/100: train_loss=0.000491

      epoch  84/100: train_loss=0.000512

      epoch  85/100: train_loss=0.000499, val_loss=0.001821, IC=+0.0750

      epoch  86/100: train_loss=0.000513

      epoch  87/100: train_loss=0.000517

      epoch  88/100: train_loss=0.000492

      epoch  89/100: train_loss=0.000489

      epoch  90/100: train_loss=0.000491, val_loss=0.001905, IC=+0.0776

      epoch  91/100: train_loss=0.000482

      epoch  92/100: train_loss=0.000490

      epoch  93/100: train_loss=0.000487

      epoch  94/100: train_loss=0.000485

      epoch  95/100: train_loss=0.000491, val_loss=0.001987, IC=+0.0800

      epoch  96/100: train_loss=0.000497

      epoch  97/100: train_loss=0.000497

      epoch  98/100: train_loss=0.000485

      epoch  99/100: train_loss=0.000478

      epoch 100/100: train_loss=0.000491, val_loss=0.001986, IC=+0.0793

      best_ep=55, IC=+0.0857 (55.0s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.425339

      epoch   2/100: train_loss=0.027083

      epoch   3/100: train_loss=0.007317

      epoch   4/100: train_loss=0.003514

      epoch   5/100: train_loss=0.002340, val_loss=0.000863, IC=+0.0049

      epoch   6/100: train_loss=0.002203

      epoch   7/100: train_loss=0.001912

      epoch   8/100: train_loss=0.001637

      epoch   9/100: train_loss=0.001639

      epoch  10/100: train_loss=0.001438, val_loss=0.000992, IC=+0.0283

      epoch  11/100: train_loss=0.001433

      epoch  12/100: train_loss=0.001628

      epoch  13/100: train_loss=0.001331

      epoch  14/100: train_loss=0.001359

      epoch  15/100: train_loss=0.001278, val_loss=0.000872, IC=-0.0060

      epoch  16/100: train_loss=0.001208

      epoch  17/100: train_loss=0.001133

      epoch  18/100: train_loss=0.001329

      epoch  19/100: train_loss=0.001091

      epoch  20/100: train_loss=0.001075, val_loss=0.000804, IC=-0.0198

      epoch  21/100: train_loss=0.001001

      epoch  22/100: train_loss=0.001149

      epoch  23/100: train_loss=0.000973

      epoch  24/100: train_loss=0.001050

      epoch  25/100: train_loss=0.000975, val_loss=0.000743, IC=-0.0239

      epoch  26/100: train_loss=0.000958

      epoch  27/100: train_loss=0.001011

      epoch  28/100: train_loss=0.000946

      epoch  29/100: train_loss=0.000964

      epoch  30/100: train_loss=0.000886, val_loss=0.000778, IC=-0.0164

      epoch  31/100: train_loss=0.001010

      epoch  32/100: train_loss=0.000980

      epoch  33/100: train_loss=0.000968

      epoch  34/100: train_loss=0.000887

      epoch  35/100: train_loss=0.000849, val_loss=0.000777, IC=-0.0230

      epoch  36/100: train_loss=0.000871

      epoch  37/100: train_loss=0.000975

      epoch  38/100: train_loss=0.001220

      epoch  39/100: train_loss=0.000999

      epoch  40/100: train_loss=0.000818, val_loss=0.000724, IC=-0.0285

      epoch  41/100: train_loss=0.000840

      epoch  42/100: train_loss=0.000792

      epoch  43/100: train_loss=0.000966

      epoch  44/100: train_loss=0.000798

      epoch  45/100: train_loss=0.000881, val_loss=0.000838, IC=-0.0284

      epoch  46/100: train_loss=0.000837

      epoch  47/100: train_loss=0.000832

      epoch  48/100: train_loss=0.000743

      epoch  49/100: train_loss=0.000823

      epoch  50/100: train_loss=0.000823, val_loss=0.000828, IC=-0.0392

      epoch  51/100: train_loss=0.000862

      epoch  52/100: train_loss=0.000771

      epoch  53/100: train_loss=0.000757

      epoch  54/100: train_loss=0.000765

      epoch  55/100: train_loss=0.000963, val_loss=0.000750, IC=-0.0231

      epoch  56/100: train_loss=0.000968

      epoch  57/100: train_loss=0.000755

      epoch  58/100: train_loss=0.000719

      epoch  59/100: train_loss=0.000713

      epoch  60/100: train_loss=0.000694, val_loss=0.000775, IC=-0.0311

      epoch  61/100: train_loss=0.000739

      epoch  62/100: train_loss=0.000686

      epoch  63/100: train_loss=0.000690

      epoch  64/100: train_loss=0.000700

      epoch  65/100: train_loss=0.000693, val_loss=0.000802, IC=-0.0311

      epoch  66/100: train_loss=0.000646

      epoch  67/100: train_loss=0.000691

      epoch  68/100: train_loss=0.000626

      epoch  69/100: train_loss=0.000673

      epoch  70/100: train_loss=0.000717, val_loss=0.000786, IC=-0.0309

      epoch  71/100: train_loss=0.000668

      epoch  72/100: train_loss=0.000666

      epoch  73/100: train_loss=0.000691

      epoch  74/100: train_loss=0.000670

      epoch  75/100: train_loss=0.000656, val_loss=0.000823, IC=-0.0249

      epoch  76/100: train_loss=0.000712

      epoch  77/100: train_loss=0.000671

      epoch  78/100: train_loss=0.000632

      epoch  79/100: train_loss=0.000634

      epoch  80/100: train_loss=0.000664, val_loss=0.000833, IC=-0.0284

      epoch  81/100: train_loss=0.000654

      epoch  82/100: train_loss=0.000614

      epoch  83/100: train_loss=0.000636

      epoch  84/100: train_loss=0.000658

      epoch  85/100: train_loss=0.000606, val_loss=0.000800, IC=-0.0287

      epoch  86/100: train_loss=0.000626

      epoch  87/100: train_loss=0.000615

      epoch  88/100: train_loss=0.000604

      epoch  89/100: train_loss=0.000624

      epoch  90/100: train_loss=0.000627, val_loss=0.000808, IC=-0.0266

      epoch  91/100: train_loss=0.000636

      epoch  92/100: train_loss=0.000627

      epoch  93/100: train_loss=0.000621

      epoch  94/100: train_loss=0.000642

      epoch  95/100: train_loss=0.000611, val_loss=0.000810, IC=-0.0286

      epoch  96/100: train_loss=0.000637

      epoch  97/100: train_loss=0.000670

      epoch  98/100: train_loss=0.000621

      epoch  99/100: train_loss=0.000614

      epoch 100/100: train_loss=0.000607, val_loss=0.000831, IC=-0.0283

      best_ep=10, IC=+0.0283 (55.1s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.031209

      epoch   2/100: train_loss=0.005642

      epoch   3/100: train_loss=0.003668

      epoch   4/100: train_loss=0.002987

      epoch   5/100: train_loss=0.002659, val_loss=0.003368, IC=-0.0789

      epoch   6/100: train_loss=0.002405

      epoch   7/100: train_loss=0.002333

      epoch   8/100: train_loss=0.002158

      epoch   9/100: train_loss=0.002023

      epoch  10/100: train_loss=0.001967, val_loss=0.002510, IC=-0.0069

      epoch  11/100: train_loss=0.001892

      epoch  12/100: train_loss=0.001789

      epoch  13/100: train_loss=0.001732

      epoch  14/100: train_loss=0.001641

      epoch  15/100: train_loss=0.001570, val_loss=0.002234, IC=-0.0130

      epoch  16/100: train_loss=0.001594

      epoch  17/100: train_loss=0.001559

      epoch  18/100: train_loss=0.001469

      epoch  19/100: train_loss=0.001434

      epoch  20/100: train_loss=0.001364, val_loss=0.001785, IC=-0.0037

      epoch  21/100: train_loss=0.001328

      epoch  22/100: train_loss=0.001315

      epoch  23/100: train_loss=0.001299

      epoch  24/100: train_loss=0.001226

      epoch  25/100: train_loss=0.001257, val_loss=0.001859, IC=-0.0354

      epoch  26/100: train_loss=0.001208

      epoch  27/100: train_loss=0.001160

      epoch  28/100: train_loss=0.001150

      epoch  29/100: train_loss=0.001272

      epoch  30/100: train_loss=0.001163, val_loss=0.001594, IC=-0.0283

      epoch  31/100: train_loss=0.001104

      epoch  32/100: train_loss=0.001129

      epoch  33/100: train_loss=0.001115

      epoch  34/100: train_loss=0.001046

      epoch  35/100: train_loss=0.001046, val_loss=0.001625, IC=-0.0491

      epoch  36/100: train_loss=0.001021

      epoch  37/100: train_loss=0.001012

      epoch  38/100: train_loss=0.000994

      epoch  39/100: train_loss=0.000966

      epoch  40/100: train_loss=0.000966, val_loss=0.001561, IC=-0.0627

      epoch  41/100: train_loss=0.000959

      epoch  42/100: train_loss=0.000998

      epoch  43/100: train_loss=0.000946

      epoch  44/100: train_loss=0.000967

      epoch  45/100: train_loss=0.000911, val_loss=0.001549, IC=-0.0579

      epoch  46/100: train_loss=0.000917

      epoch  47/100: train_loss=0.000896

      epoch  48/100: train_loss=0.000868

      epoch  49/100: train_loss=0.000875

      epoch  50/100: train_loss=0.000841, val_loss=0.001688, IC=-0.0698

      epoch  51/100: train_loss=0.000840

      epoch  52/100: train_loss=0.000831

      epoch  53/100: train_loss=0.000826

      epoch  54/100: train_loss=0.000806

      epoch  55/100: train_loss=0.000804, val_loss=0.001511, IC=-0.0499

      epoch  56/100: train_loss=0.000799

      epoch  57/100: train_loss=0.000804

      epoch  58/100: train_loss=0.000815

      epoch  59/100: train_loss=0.000786

      epoch  60/100: train_loss=0.000806, val_loss=0.001513, IC=-0.0543

      epoch  61/100: train_loss=0.000833

      epoch  62/100: train_loss=0.000830

      epoch  63/100: train_loss=0.000831

      epoch  64/100: train_loss=0.000757

      epoch  65/100: train_loss=0.000757, val_loss=0.001814, IC=-0.0640

      epoch  66/100: train_loss=0.000758

      epoch  67/100: train_loss=0.000748

      epoch  68/100: train_loss=0.000740

      epoch  69/100: train_loss=0.000745

      epoch  70/100: train_loss=0.000737, val_loss=0.001529, IC=-0.0420

      epoch  71/100: train_loss=0.000745

      epoch  72/100: train_loss=0.000749

      epoch  73/100: train_loss=0.000736

      epoch  74/100: train_loss=0.000731

      epoch  75/100: train_loss=0.000736, val_loss=0.001569, IC=-0.0494

      epoch  76/100: train_loss=0.000711

      epoch  77/100: train_loss=0.000733

      epoch  78/100: train_loss=0.000731

      epoch  79/100: train_loss=0.000716

      epoch  80/100: train_loss=0.000717, val_loss=0.001587, IC=-0.0434

      epoch  81/100: train_loss=0.000730

      epoch  82/100: train_loss=0.000706

      epoch  83/100: train_loss=0.000736

      epoch  84/100: train_loss=0.000726

      epoch  85/100: train_loss=0.000707, val_loss=0.001554, IC=-0.0415

      epoch  86/100: train_loss=0.000715

      epoch  87/100: train_loss=0.000719

      epoch  88/100: train_loss=0.000715

      epoch  89/100: train_loss=0.000715

      epoch  90/100: train_loss=0.000693, val_loss=0.001582, IC=-0.0463

      epoch  91/100: train_loss=0.000693

      epoch  92/100: train_loss=0.000705

      epoch  93/100: train_loss=0.000703

      epoch  94/100: train_loss=0.000701

      epoch  95/100: train_loss=0.000697, val_loss=0.001601, IC=-0.0475

      epoch  96/100: train_loss=0.000703

      epoch  97/100: train_loss=0.000699

      epoch  98/100: train_loss=0.000708

      epoch  99/100: train_loss=0.000707

      epoch 100/100: train_loss=0.000689, val_loss=0.001605, IC=-0.0464

      best_ep=20, IC=-0.0037 (55.1s, 20 checkpoints)

  Fold 4: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.022078

      epoch   2/100: train_loss=0.004483

      epoch   3/100: train_loss=0.003057

      epoch   4/100: train_loss=0.002553

      epoch   5/100: train_loss=0.002306, val_loss=0.001157, IC=-0.0146

      epoch   6/100: train_loss=0.002070

      epoch   7/100: train_loss=0.001943

      epoch   8/100: train_loss=0.001826

      epoch   9/100: train_loss=0.001757

      epoch  10/100: train_loss=0.001721, val_loss=0.000873, IC=+0.0387

      epoch  11/100: train_loss=0.001588

      epoch  12/100: train_loss=0.001613

      epoch  13/100: train_loss=0.001496

      epoch  14/100: train_loss=0.001398

      epoch  15/100: train_loss=0.001431, val_loss=0.000777, IC=+0.0576

      epoch  16/100: train_loss=0.001340

      epoch  17/100: train_loss=0.001320

      epoch  18/100: train_loss=0.001351

      epoch  19/100: train_loss=0.001491

      epoch  20/100: train_loss=0.001320, val_loss=0.000752, IC=+0.0842

      epoch  21/100: train_loss=0.001184

      epoch  22/100: train_loss=0.001111

      epoch  23/100: train_loss=0.001099

      epoch  24/100: train_loss=0.001084

      epoch  25/100: train_loss=0.001070, val_loss=0.000633, IC=+0.0718

      epoch  26/100: train_loss=0.001136

      epoch  27/100: train_loss=0.001114

      epoch  28/100: train_loss=0.001062

      epoch  29/100: train_loss=0.000998

      epoch  30/100: train_loss=0.000972, val_loss=0.000693, IC=+0.0872

      epoch  31/100: train_loss=0.000990

      epoch  32/100: train_loss=0.001091

      epoch  33/100: train_loss=0.001035

      epoch  34/100: train_loss=0.000950

      epoch  35/100: train_loss=0.000984, val_loss=0.000735, IC=+0.0479

      epoch  36/100: train_loss=0.001092

      epoch  37/100: train_loss=0.000964

      epoch  38/100: train_loss=0.000941

      epoch  39/100: train_loss=0.000857

      epoch  40/100: train_loss=0.000875, val_loss=0.000674, IC=+0.0710

      epoch  41/100: train_loss=0.000843

      epoch  42/100: train_loss=0.000819

      epoch  43/100: train_loss=0.000816

      epoch  44/100: train_loss=0.000858

      epoch  45/100: train_loss=0.000813, val_loss=0.000633, IC=+0.0678

      epoch  46/100: train_loss=0.000783

      epoch  47/100: train_loss=0.000764

      epoch  48/100: train_loss=0.000778

      epoch  49/100: train_loss=0.000753

      epoch  50/100: train_loss=0.000765, val_loss=0.000624, IC=+0.0708

      epoch  51/100: train_loss=0.000746

      epoch  52/100: train_loss=0.000762

      epoch  53/100: train_loss=0.000797

      epoch  54/100: train_loss=0.000770

      epoch  55/100: train_loss=0.000744, val_loss=0.000621, IC=+0.0791

      epoch  56/100: train_loss=0.000766

      epoch  57/100: train_loss=0.000751

      epoch  58/100: train_loss=0.000747

      epoch  59/100: train_loss=0.000771

      epoch  60/100: train_loss=0.000749, val_loss=0.000824, IC=+0.0982

      epoch  61/100: train_loss=0.000726

      epoch  62/100: train_loss=0.000710

      epoch  63/100: train_loss=0.000689

      epoch  64/100: train_loss=0.000713

      epoch  65/100: train_loss=0.000702, val_loss=0.000617, IC=+0.0920

      epoch  66/100: train_loss=0.000698

      epoch  67/100: train_loss=0.000678

      epoch  68/100: train_loss=0.000673

      epoch  69/100: train_loss=0.000682

      epoch  70/100: train_loss=0.000647, val_loss=0.000619, IC=+0.0837

      epoch  71/100: train_loss=0.000669

      epoch  72/100: train_loss=0.000662

      epoch  73/100: train_loss=0.000686

      epoch  74/100: train_loss=0.000660

      epoch  75/100: train_loss=0.000642, val_loss=0.000619, IC=+0.0982

      epoch  76/100: train_loss=0.000657

      epoch  77/100: train_loss=0.000676

      epoch  78/100: train_loss=0.000657

      epoch  79/100: train_loss=0.000652

      epoch  80/100: train_loss=0.000633, val_loss=0.000619, IC=+0.0978

      epoch  81/100: train_loss=0.000647

      epoch  82/100: train_loss=0.000652

      epoch  83/100: train_loss=0.000624

      epoch  84/100: train_loss=0.000633

      epoch  85/100: train_loss=0.000641, val_loss=0.000615, IC=+0.0976

      epoch  86/100: train_loss=0.000654

      epoch  87/100: train_loss=0.000638

      epoch  88/100: train_loss=0.000631

      epoch  89/100: train_loss=0.000636

      epoch  90/100: train_loss=0.000615, val_loss=0.000613, IC=+0.0998

      epoch  91/100: train_loss=0.000630

      epoch  92/100: train_loss=0.000632

      epoch  93/100: train_loss=0.000626

      epoch  94/100: train_loss=0.000637

      epoch  95/100: train_loss=0.000605, val_loss=0.000617, IC=+0.0979

      epoch  96/100: train_loss=0.000646

      epoch  97/100: train_loss=0.000620

      epoch  98/100: train_loss=0.000637

      epoch  99/100: train_loss=0.000658

      epoch 100/100: train_loss=0.000616, val_loss=0.000622, IC=+0.0979

      best_ep=90, IC=+0.0998 (55.4s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.016825

      epoch   2/100: train_loss=0.003441

      epoch   3/100: train_loss=0.002206

      epoch   4/100: train_loss=0.001803

      epoch   5/100: train_loss=0.001576, val_loss=0.001418, IC=-0.0189

      epoch   6/100: train_loss=0.001465

      epoch   7/100: train_loss=0.001418

      epoch   8/100: train_loss=0.001327

      epoch   9/100: train_loss=0.001280

      epoch  10/100: train_loss=0.001250, val_loss=0.001311, IC=-0.0037

      epoch  11/100: train_loss=0.001200

      epoch  12/100: train_loss=0.001149

      epoch  13/100: train_loss=0.001125

      epoch  14/100: train_loss=0.001081

      epoch  15/100: train_loss=0.001049, val_loss=0.001002, IC=+0.0177

      epoch  16/100: train_loss=0.000994

      epoch  17/100: train_loss=0.001024

      epoch  18/100: train_loss=0.000973

      epoch  19/100: train_loss=0.000950

      epoch  20/100: train_loss=0.000919, val_loss=0.001122, IC=+0.0793

      epoch  21/100: train_loss=0.000922

      epoch  22/100: train_loss=0.000901

      epoch  23/100: train_loss=0.000873

      epoch  24/100: train_loss=0.000871

      epoch  25/100: train_loss=0.000843, val_loss=0.001142, IC=+0.0585

      epoch  26/100: train_loss=0.000822

      epoch  27/100: train_loss=0.000784

      epoch  28/100: train_loss=0.000788

      epoch  29/100: train_loss=0.000807

      epoch  30/100: train_loss=0.000774, val_loss=0.001219, IC=+0.0302

      epoch  31/100: train_loss=0.000761

      epoch  32/100: train_loss=0.000773

      epoch  33/100: train_loss=0.000728

      epoch  34/100: train_loss=0.000729

      epoch  35/100: train_loss=0.000705, val_loss=0.001038, IC=+0.0423

      epoch  36/100: train_loss=0.000726

      epoch  37/100: train_loss=0.000715

      epoch  38/100: train_loss=0.000683

      epoch  39/100: train_loss=0.000672

      epoch  40/100: train_loss=0.000665, val_loss=0.000934, IC=+0.0578

      epoch  41/100: train_loss=0.000668

      epoch  42/100: train_loss=0.000648

      epoch  43/100: train_loss=0.000657

      epoch  44/100: train_loss=0.000646

      epoch  45/100: train_loss=0.000648, val_loss=0.000986, IC=+0.0518

      epoch  46/100: train_loss=0.000637

      epoch  47/100: train_loss=0.000625

      epoch  48/100: train_loss=0.000627

      epoch  49/100: train_loss=0.000614

      epoch  50/100: train_loss=0.000603, val_loss=0.001141, IC=+0.0247

      epoch  51/100: train_loss=0.000606

      epoch  52/100: train_loss=0.000584

      epoch  53/100: train_loss=0.000602

      epoch  54/100: train_loss=0.000590

      epoch  55/100: train_loss=0.000586, val_loss=0.000932, IC=+0.0616

      epoch  56/100: train_loss=0.000595

      epoch  57/100: train_loss=0.000580

      epoch  58/100: train_loss=0.000569

      epoch  59/100: train_loss=0.000575

      epoch  60/100: train_loss=0.000578, val_loss=0.000878, IC=+0.0666

      epoch  61/100: train_loss=0.000572

      epoch  62/100: train_loss=0.000562

      epoch  63/100: train_loss=0.000561

      epoch  64/100: train_loss=0.000551

      epoch  65/100: train_loss=0.000551, val_loss=0.000907, IC=+0.0605

      epoch  66/100: train_loss=0.000547

      epoch  67/100: train_loss=0.000549

      epoch  68/100: train_loss=0.000541

      epoch  69/100: train_loss=0.000533

      epoch  70/100: train_loss=0.000532, val_loss=0.001022, IC=+0.0510

      epoch  71/100: train_loss=0.000532

      epoch  72/100: train_loss=0.000546

      epoch  73/100: train_loss=0.000539

      epoch  74/100: train_loss=0.000536

      epoch  75/100: train_loss=0.000526, val_loss=0.000923, IC=+0.0472

      epoch  76/100: train_loss=0.000535

      epoch  77/100: train_loss=0.000529

      epoch  78/100: train_loss=0.000524

      epoch  79/100: train_loss=0.000525

      epoch  80/100: train_loss=0.000514, val_loss=0.000931, IC=+0.0505

      epoch  81/100: train_loss=0.000526

      epoch  82/100: train_loss=0.000523

      epoch  83/100: train_loss=0.000514

      epoch  84/100: train_loss=0.000520

      epoch  85/100: train_loss=0.000527, val_loss=0.001006, IC=+0.0432

      epoch  86/100: train_loss=0.000523

      epoch  87/100: train_loss=0.000514

      epoch  88/100: train_loss=0.000511

      epoch  89/100: train_loss=0.000517

      epoch  90/100: train_loss=0.000517, val_loss=0.000948, IC=+0.0451

      epoch  91/100: train_loss=0.000517

      epoch  92/100: train_loss=0.000522

      epoch  93/100: train_loss=0.000519

      epoch  94/100: train_loss=0.000507

      epoch  95/100: train_loss=0.000519, val_loss=0.000971, IC=+0.0453

      epoch  96/100: train_loss=0.000516

      epoch  97/100: train_loss=0.000518

      epoch  98/100: train_loss=0.000515

      epoch  99/100: train_loss=0.000512

      epoch 100/100: train_loss=0.000514, val_loss=0.000957, IC=+0.0444

      best_ep=20, IC=+0.0793 (55.2s, 20 checkpoints)

  Fold 6: creating sequences...
    train=21,820 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=0.053044

      epoch   2/100: train_loss=0.005641

      epoch   3/100: train_loss=0.003357

      epoch   4/100: train_loss=0.002355

      epoch   5/100: train_loss=0.001983, val_loss=0.002780, IC=-0.0980

      epoch   6/100: train_loss=0.001933

      epoch   7/100: train_loss=0.001801

      epoch   8/100: train_loss=0.001590

      epoch   9/100: train_loss=0.001573

      epoch  10/100: train_loss=0.001462, val_loss=0.002490, IC=-0.1289

      epoch  11/100: train_loss=0.001425

      epoch  12/100: train_loss=0.001375

      epoch  13/100: train_loss=0.001292

      epoch  14/100: train_loss=0.001270

      epoch  15/100: train_loss=0.001229, val_loss=0.001489, IC=-0.1148

      epoch  16/100: train_loss=0.001206

      epoch  17/100: train_loss=0.001110

      epoch  18/100: train_loss=0.001171

      epoch  19/100: train_loss=0.001113

      epoch  20/100: train_loss=0.001094, val_loss=0.001331, IC=-0.0778

      epoch  21/100: train_loss=0.001070

      epoch  22/100: train_loss=0.001009

      epoch  23/100: train_loss=0.000985

      epoch  24/100: train_loss=0.001007

      epoch  25/100: train_loss=0.001126, val_loss=0.001338, IC=-0.0491

      epoch  26/100: train_loss=0.001062

      epoch  27/100: train_loss=0.000909

      epoch  28/100: train_loss=0.000974

      epoch  29/100: train_loss=0.000989

      epoch  30/100: train_loss=0.000830, val_loss=0.001204, IC=-0.0849

      epoch  31/100: train_loss=0.000808

      epoch  32/100: train_loss=0.000883

      epoch  33/100: train_loss=0.000816

      epoch  34/100: train_loss=0.000763

      epoch  35/100: train_loss=0.000797, val_loss=0.001175, IC=-0.1101

      epoch  36/100: train_loss=0.000751

      epoch  37/100: train_loss=0.000752

      epoch  38/100: train_loss=0.000753

      epoch  39/100: train_loss=0.000731

      epoch  40/100: train_loss=0.000734, val_loss=0.001198, IC=-0.1150

      epoch  41/100: train_loss=0.000730

      epoch  42/100: train_loss=0.000710

      epoch  43/100: train_loss=0.000691

      epoch  44/100: train_loss=0.000735

      epoch  45/100: train_loss=0.000670, val_loss=0.001312, IC=-0.1311

      epoch  46/100: train_loss=0.000658

      epoch  47/100: train_loss=0.000661

      epoch  48/100: train_loss=0.000667

      epoch  49/100: train_loss=0.000653

      epoch  50/100: train_loss=0.000633, val_loss=0.001215, IC=-0.1299

      epoch  51/100: train_loss=0.000666

      epoch  52/100: train_loss=0.000675

      epoch  53/100: train_loss=0.000627

      epoch  54/100: train_loss=0.000616

      epoch  55/100: train_loss=0.000600, val_loss=0.001211, IC=-0.1156

      epoch  56/100: train_loss=0.000599

      epoch  57/100: train_loss=0.000624

      epoch  58/100: train_loss=0.000604

      epoch  59/100: train_loss=0.000606

      epoch  60/100: train_loss=0.000603, val_loss=0.001236, IC=-0.1249

      epoch  61/100: train_loss=0.000602

      epoch  62/100: train_loss=0.000603

      epoch  63/100: train_loss=0.000634

      epoch  64/100: train_loss=0.000614

      epoch  65/100: train_loss=0.000614, val_loss=0.001171, IC=-0.1004

      epoch  66/100: train_loss=0.000652

      epoch  67/100: train_loss=0.000605

      epoch  68/100: train_loss=0.000587

      epoch  69/100: train_loss=0.000586

      epoch  70/100: train_loss=0.000589, val_loss=0.001178, IC=-0.0970

      epoch  71/100: train_loss=0.000587

      epoch  72/100: train_loss=0.000564

      epoch  73/100: train_loss=0.000567

      epoch  74/100: train_loss=0.000546

      epoch  75/100: train_loss=0.000586, val_loss=0.001228, IC=-0.1098

      epoch  76/100: train_loss=0.000592

      epoch  77/100: train_loss=0.000581

      epoch  78/100: train_loss=0.000557

      epoch  79/100: train_loss=0.000561

      epoch  80/100: train_loss=0.000544, val_loss=0.001206, IC=-0.1009

      epoch  81/100: train_loss=0.000553

      epoch  82/100: train_loss=0.000544

      epoch  83/100: train_loss=0.000562

      epoch  84/100: train_loss=0.000552

      epoch  85/100: train_loss=0.000550, val_loss=0.001212, IC=-0.1062

      epoch  86/100: train_loss=0.000549

      epoch  87/100: train_loss=0.000542

      epoch  88/100: train_loss=0.000553

      epoch  89/100: train_loss=0.000538

      epoch  90/100: train_loss=0.000544, val_loss=0.001222, IC=-0.1099

      epoch  91/100: train_loss=0.000541

      epoch  92/100: train_loss=0.000552

      epoch  93/100: train_loss=0.000545

      epoch  94/100: train_loss=0.000544

      epoch  95/100: train_loss=0.000555, val_loss=0.001206, IC=-0.1056

      epoch  96/100: train_loss=0.000556

      epoch  97/100: train_loss=0.000533

      epoch  98/100: train_loss=0.000544

      epoch  99/100: train_loss=0.000534

      epoch 100/100: train_loss=0.000538, val_loss=0.001212, IC=-0.1029

      best_ep=25, IC=-0.0491 (50.1s, 20 checkpoints)

  Fold 7: creating sequences...
    train=16,660 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    tcn:

      epoch   1/100: train_loss=1.445276

      epoch   2/100: train_loss=0.056288

      epoch   3/100: train_loss=0.009636

      epoch   4/100: train_loss=0.005044

      epoch   5/100: train_loss=0.002988, val_loss=0.003384, IC=+0.1367

      epoch   6/100: train_loss=0.002173

      epoch   7/100: train_loss=0.002139

      epoch   8/100: train_loss=0.001988

      epoch   9/100: train_loss=0.001683

      epoch  10/100: train_loss=0.001707, val_loss=0.004080, IC=+0.0627

      epoch  11/100: train_loss=0.001589

      epoch  12/100: train_loss=0.001347

      epoch  13/100: train_loss=0.001316

      epoch  14/100: train_loss=0.001307

      epoch  15/100: train_loss=0.001581, val_loss=0.004311, IC=+0.0585

      epoch  16/100: train_loss=0.001304

      epoch  17/100: train_loss=0.001297

      epoch  18/100: train_loss=0.001189

      epoch  19/100: train_loss=0.001332

      epoch  20/100: train_loss=0.001348, val_loss=0.001854, IC=+0.0668

      epoch  21/100: train_loss=0.001649

      epoch  22/100: train_loss=0.001765

      epoch  23/100: train_loss=0.001636

      epoch  24/100: train_loss=0.001198

      epoch  25/100: train_loss=0.001303, val_loss=0.001483, IC=+0.1097

      epoch  26/100: train_loss=0.001345

      epoch  27/100: train_loss=0.001299

      epoch  28/100: train_loss=0.000922

      epoch  29/100: train_loss=0.000937

      epoch  30/100: train_loss=0.000865, val_loss=0.003132, IC=+0.0311

      epoch  31/100: train_loss=0.000900

      epoch  32/100: train_loss=0.001115

      epoch  33/100: train_loss=0.000952

      epoch  34/100: train_loss=0.000930

      epoch  35/100: train_loss=0.000810, val_loss=0.001925, IC=+0.0556

      epoch  36/100: train_loss=0.000825

      epoch  37/100: train_loss=0.000823

      epoch  38/100: train_loss=0.000940

      epoch  39/100: train_loss=0.000933

      epoch  40/100: train_loss=0.000804, val_loss=0.004341, IC=+0.0268

      epoch  41/100: train_loss=0.001154

      epoch  42/100: train_loss=0.000928

      epoch  43/100: train_loss=0.001038

      epoch  44/100: train_loss=0.000931

      epoch  45/100: train_loss=0.000951, val_loss=0.001492, IC=+0.0978

      epoch  46/100: train_loss=0.000818

      epoch  47/100: train_loss=0.000826

      epoch  48/100: train_loss=0.000770

      epoch  49/100: train_loss=0.001146

      epoch  50/100: train_loss=0.000917, val_loss=0.002916, IC=+0.0290

      epoch  51/100: train_loss=0.000732

      epoch  52/100: train_loss=0.000870

      epoch  53/100: train_loss=0.001046

      epoch  54/100: train_loss=0.000883

      epoch  55/100: train_loss=0.000765, val_loss=0.001919, IC=+0.0364

      epoch  56/100: train_loss=0.000704

      epoch  57/100: train_loss=0.000696

      epoch  58/100: train_loss=0.000736

      epoch  59/100: train_loss=0.000720

      epoch  60/100: train_loss=0.000688, val_loss=0.002680, IC=+0.0311

      epoch  61/100: train_loss=0.000715

      epoch  62/100: train_loss=0.000658

      epoch  63/100: train_loss=0.000707

      epoch  64/100: train_loss=0.000650

      epoch  65/100: train_loss=0.000654, val_loss=0.002050, IC=+0.0437

      epoch  66/100: train_loss=0.000632

      epoch  67/100: train_loss=0.000660

      epoch  68/100: train_loss=0.000680

      epoch  69/100: train_loss=0.000656

      epoch  70/100: train_loss=0.000637, val_loss=0.002225, IC=+0.0352

      epoch  71/100: train_loss=0.000635

      epoch  72/100: train_loss=0.000700

      epoch  73/100: train_loss=0.000693

      epoch  74/100: train_loss=0.000810

      epoch  75/100: train_loss=0.000747, val_loss=0.002897, IC=+0.0240

      epoch  76/100: train_loss=0.000669

      epoch  77/100: train_loss=0.000638

      epoch  78/100: train_loss=0.000693

      epoch  79/100: train_loss=0.000707

      epoch  80/100: train_loss=0.000676, val_loss=0.002646, IC=+0.0256

      epoch  81/100: train_loss=0.000652

      epoch  82/100: train_loss=0.000672

      epoch  83/100: train_loss=0.000652

      epoch  84/100: train_loss=0.000657

      epoch  85/100: train_loss=0.000650, val_loss=0.002518, IC=+0.0264

      epoch  86/100: train_loss=0.000714

      epoch  87/100: train_loss=0.000643

      epoch  88/100: train_loss=0.000666

      epoch  89/100: train_loss=0.000653

      epoch  90/100: train_loss=0.000654, val_loss=0.002409, IC=+0.0339

      epoch  91/100: train_loss=0.000637

      epoch  92/100: train_loss=0.000617

      epoch  93/100: train_loss=0.000625

      epoch  94/100: train_loss=0.000644

      epoch  95/100: train_loss=0.000642, val_loss=0.002349, IC=+0.0323

      epoch  96/100: train_loss=0.000670

      epoch  97/100: train_loss=0.000679

      epoch  98/100: train_loss=0.000644

      epoch  99/100: train_loss=0.000591

      epoch 100/100: train_loss=0.000691, val_loss=0.002499, IC=+0.0306

      best_ep=5, IC=+0.1367 (38.9s, 20 checkpoints)

  tcn: best_epoch=25, IC=+0.0211 (419.9s)

  Best: tcn @ epoch 25 (IC=+0.0211)
  Saved to ~/ml4t/public-s6-fx_pairs/case_studies/fx_pairs/run_log/training/2a999dd55cf4/diagnostics

shape: (60, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ label      ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean  ┆ ic_t     ┆ training_ ┆ predictio │
│ ---        ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---      ┆ ---      ┆ hash      ┆ n_hash    │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64      ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆ i64       ┆   ┆          ┆          ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 5         ┆ … ┆ 0.020448 ┆ 2.837143 ┆ 4b7bb9e55 ┆ 689e938f3 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ bbf       ┆ 2ee       │
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 10        ┆ … ┆ 0.015043 ┆ 1.942521 ┆ 4b7bb9e55 ┆ 830739601 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ bbf       ┆ 40a       │
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 15        ┆ … ┆ 0.015427 ┆ 1.936974 ┆ 4b7bb9e55 ┆ 226aa3b6d │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ bbf       ┆ 511       │
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 20        ┆ … ┆ 0.007798 ┆ 0.957975 ┆ 4b7bb9e55 ┆ e76bc5774 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ bbf       ┆ 817       │
│ fwd_ret_1d ┆ tcn       ┆ epoch     ┆ 25        ┆ … ┆ 0.012964 ┆ 2.072192 ┆ 4b7bb9e55 ┆ cfb01a246 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ bbf       ┆ e7a       │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 80        ┆ … ┆ 0.003405 ┆ 0.215277 ┆ 90b5f579f ┆ 84267c7c7 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 125       ┆ ae8       │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 85        ┆ … ┆ 0.001936 ┆ 0.124639 ┆ 90b5f579f ┆ fe894845d │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 125       ┆ fc6       │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 90        ┆ … ┆ 0.004348 ┆ 0.276471 ┆ 90b5f579f ┆ d27dee2c9 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 125       ┆ 2ee       │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 95        ┆ … ┆ 0.002898 ┆ 0.184393 ┆ 90b5f579f ┆ 459bfa146 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 125       ┆ 1c1       │
│ fwd_ret_5d ┆ tcn       ┆ epoch     ┆ 100       ┆ … ┆ 0.002538 ┆ 0.163052 ┆ 90b5f579f ┆ dc1d60719 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 125       ┆ 9d4       │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

## Reload the fitted state

An identical call validates the saved weights and returns the same prediction identities. The
comparison with other model families belongs in `12_model_analysis` after every family completes.

In [6]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("TCN checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview sequence checkpoints remain outside official comparisons.")

Official prediction population: e241afc9c172

## Key takeaways

- Eligibility is defined by consecutive observations at the declared daily cadence.
- Validation priming uses earlier observable rows without admitting training targets.
- Every saved epoch checkpoint remains available to the backtest stage.