# NLinear - FX Pairs

NLinear forecasts from a fixed consecutive history after subtracting the last observed level. The
transformation focuses the model on changes over the lookback window. This notebook constructs
only the NLinear request; comparisons with TCN, TabM, trees, and linear models are deferred to
`12_model_analysis`, where the complete registered population is available.

**Learning objectives**

- Resolve NLinear's lookback, normalization, and checkpoint schedule before fitting.
- Use the shared gap-safe sequence eligibility instead of positional row windows.
- Prove weight reload and catalog handoff for every declared epoch.

**Book reference**: Chapter 13, Section 13.4

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published NLinear FX configuration."""

import json

import polars as pl
import torch

from case_studies.research import (
    ExecutionTier,
    declared_labels,
    open_study,
    plan_models,
    population_supersedes,
    sweep_labels,
)
from utils.modeling import load_configs
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
LOOKBACK = 0
BATCH_SIZE = 0
DEVICE = ""
SEED = 42
POPULATION_NAME = ""
SUPERSEDES_POPULATION: str = "20f46e6a5645"
# The tier is a parameter, not something inferred from whether a reduction happens to be set.
# Inferring it meant a run could be reduced and still open the case study's own artifacts in
# place, which is the production path; a reader under test then wrote where the published run
# writes. WORKSPACE is the other half: a preview has nowhere else to put its results.
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None

## Resolve one forecasting request

The shared runner derives fold boundaries from the finalized label timeline. A missing daily
observation invalidates every lookback window that crosses it, so validation coverage can be
smaller than the raw validation panel while still being exact.

In [3]:
set_global_seeds(SEED)
# The reductions are read before the study is opened, because which study to open is decided by
# the tier and the two have to agree: a preview that reduces nothing is a canonical run wearing
# the wrong tier, and a canonical run carrying reductions would publish a narrowed population
# under the canonical name.
REDUCTION_PARAMETERS = {
    "folds": list(range(MAX_FOLDS)) if MAX_FOLDS else None,
    "max_symbols": MAX_SYMBOLS or None,
}
reductions = {key: value for key, value in REDUCTION_PARAMETERS.items() if value is not None}
tier = ExecutionTier(EXECUTION_TIER)
if tier is ExecutionTier.PREVIEW and not reductions:
    raise ValueError("preview execution must declare at least one reduction")
if tier is ExecutionTier.CANONICAL and reductions:
    raise ValueError(f"canonical execution cannot carry reductions: {sorted(reductions)}")
study = open_study(CASE_STUDY_ID, execution_tier=tier, workspace=WORKSPACE or None)

# Which labels this notebook fits is a question for the training menus, not for the sweep list:
# `setup.yaml` says which labels the case study carries, a menu says what to fit for one of them,
# and a sweep label whose menu declares no `deep_learning:` section owes nothing here. The two
# agree in this case study today, so restating the sweep list produced the right answer by
# coincidence and would have kept producing it silently after a menu changed. The order stays
# `setup.yaml`'s rather than `declared_labels`' menu-file order because the population is named
# after its labels and hashed over its members as an ordered list, so re-ordering would give the
# published population a new identity and demand a supersedes for a run that fits the same models.
declared = declared_labels(study, "deep_learning")
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [label for label in sweep_labels(study) if label in set(declared)]
)

# A run that fits fewer labels than the menus declare is not the canonical population, and the
# architecture is fixed below, so the label set is the only knob that narrows it. Such a run must
# publish under its own name rather than register a partial snapshot under the canonical one.
if set(labels) != set(declared) and not POPULATION_NAME:
    raise ValueError(
        f"this run fits {len(labels)} of the {len(declared)} declared labels, so it cannot "
        "publish the canonical population; pass POPULATION_NAME to give it its own"
    )

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

# An empty DEVICE resolves to what the machine has. The runners refuse "cuda" on a host without
# it rather than falling back silently - which is the right contract for a run whose results get
# registered - so a hardcoded "cuda" default made the notebook unrunnable for any reader without
# an NVIDIA card, and unrunnable on a CPU CI runner. Resolving here keeps the refusal for anyone
# who asks for "cuda" explicitly; the resolved value is printed with the rest of the numerics
# below, so a run never leaves it implicit.
device = DEVICE or ("cuda" if torch.cuda.is_available() else "cpu")
overrides = {
    "device": device,
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
    **({"lookback": LOOKBACK} if LOOKBACK else {}),
}
ARCHITECTURE = "nlinear"
menu = {
    label: [
        config["config_name"]
        for config in load_configs(CASE_STUDY_ID, label, family="deep_learning")
    ]
    for label in labels
}
uncovered = {label: sorted(set(names) - {ARCHITECTURE}) for label, names in menu.items()}
for label, names in menu.items():
    if ARCHITECTURE not in names:
        raise RuntimeError(
            f"{ARCHITECTURE} is not in the configured deep_learning menu for {label}: {names}"
        )

requests = [
    study.model(
        family="deep_learning",
        label=label,
        config_name=ARCHITECTURE,
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label in labels
]
plan = plan_models(study, requests=requests)

# This notebook owes one architecture on every configured label. The rest of the family menu is
# named here rather than left implicit, because a population that is short a configured model is
# otherwise indistinguishable from a complete one.
configured = {(label, ARCHITECTURE) for label in labels}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        f"the plan does not match this notebook's declared coverage; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )
specs = {member.label: json.loads(member.spec_json) for member in plan.members}
computations = {label: spec.get("computation", spec) for label, spec in specs.items()}
computation = computations[labels[0]]

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {computation['numerics']['device']}")
print(f"Lookback: {computation['preprocessing']['lookback']} consecutive daily observations")
for horizon, values in computations.items():
    print(f"Eligible validation rows, {horizon}: {values['expected_prediction_keys']['n_rows']:,}")
for horizon, names in uncovered.items():
    print(
        f"Configured deep_learning models this notebook does not run, {horizon}: {names or 'none'}"
    )

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda
Lookback: 60 consecutive daily observations
Eligible validation rows, fwd_ret_1d: 41,260
Eligible validation rows, fwd_ret_5d: 41,180
Eligible validation rows, fwd_ret_21d: 40,860
Configured deep_learning models this notebook does not run, fwd_ret_1d: ['lstm_h64', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_5d: ['lstm_h64', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_21d: ['lstm_h64', 'tcn']

## Inspect identity-bearing settings

The model request records its architecture parameters, exact folds, expected prediction-key
digest, and every epoch that must remain reproducible from stored weights.

In [4]:
checkpoint_schedule = pl.DataFrame(computation["checkpoint_schedule"])
pl.DataFrame(
    {
        "label": list(computations),
        "architecture": [c["model"]["class"] for c in computations.values()],
        "gap_policy": [c["preprocessing"]["gap_policy"] for c in computations.values()],
        "validation_folds": [
            c["expected_prediction_keys"]["n_folds"] for c in computations.values()
        ],
        "key_digest": [c["expected_prediction_keys"]["digest"] for c in computations.values()],
    }
)
checkpoint_schedule

shape: (20, 2)
┌───────┬───────┐
│ kind  ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ epoch ┆ 5     │
│ epoch ┆ 10    │
│ epoch ┆ 15    │
│ epoch ┆ 20    │
│ epoch ┆ 25    │
│ …     ┆ …     │
│ epoch ┆ 80    │
│ epoch ┆ 85    │
│ epoch ┆ 90    │
│ epoch ┆ 95    │
│ epoch ┆ 100   │
└───────┴───────┘

## Record the official population, then fit or reload NLinear

The runner validates every fold separately before any checkpoint becomes downstream-selectable.
Checkpoint rank correlation is retained as a diagnostic and does not remove other epochs.

`SUPERSEDES_POPULATION` names the population hash this run replaces. A population is the set of
prediction identities it publishes, so anything that moves a training identity produces a
different population under the same name, and the registry refuses to write it without being
told which snapshot it supersedes. That lineage is the only record of which generation is which,
and what moved the identities here was a change to the family's own source file rather than to
anything the notebook declares.

`population_supersedes` decides whether the declared hash may be offered. It is offered when the
name already carries the generation this declaration produced, so a re-run resolves to the
population it published, and when the declaration names the generation in force, so a refit
publishes the next one. It is withheld everywhere else - on a reader's clean clone, where
`run_log/` is gitignored and the registry has no generation at all; under a caller's own
`POPULATION_NAME`; and in a preview, whose isolated registry holds nothing under this name.

In [5]:
if len(plan.expected_prediction_hashes) != checkpoint_schedule.height * len(labels):
    raise RuntimeError("the plan does not cover every declared epoch checkpoint on every label")
population_name = POPULATION_NAME or f"{CASE_STUDY_ID}:{'+'.join(labels)}:nlinear"
population = (
    plan.create_population(
        name=population_name,
        supersedes=population_supersedes(
            study, name=population_name, declared=SUPERSEDES_POPULATION
        ),
    )
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
catalog = execution.catalog_rows.sort("label", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial NLinear checkpoints cannot pass to backtesting")
for label in labels:
    published = catalog.filter(pl.col("label") == label).get_column("checkpoint_value").to_list()
    if published != checkpoint_schedule["value"].to_list():
        raise RuntimeError(f"catalog checkpoints for {label} differ from the resolved request")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=17,060 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.682900

      epoch   2/100: train_loss=0.414133

      epoch   3/100: train_loss=0.234120

      epoch   4/100: train_loss=0.120356

      epoch   5/100: train_loss=0.066860, val_loss=0.062578, IC=-0.0422

      epoch   6/100: train_loss=0.045078

      epoch   7/100: train_loss=0.034051

      epoch   8/100: train_loss=0.026766

      epoch   9/100: train_loss=0.022038

      epoch  10/100: train_loss=0.019133, val_loss=0.017543, IC=-0.0369

      epoch  11/100: train_loss=0.017132

      epoch  12/100: train_loss=0.015619

      epoch  13/100: train_loss=0.014699

      epoch  14/100: train_loss=0.013471

      epoch  15/100: train_loss=0.012893, val_loss=0.006044, IC=-0.0220

      epoch  16/100: train_loss=0.011708

      epoch  17/100: train_loss=0.011014

      epoch  18/100: train_loss=0.010222

      epoch  19/100: train_loss=0.009819

      epoch  20/100: train_loss=0.009275, val_loss=0.002874, IC=-0.0110

      epoch  21/100: train_loss=0.008487

      epoch  22/100: train_loss=0.008136

      epoch  23/100: train_loss=0.007649

      epoch  24/100: train_loss=0.007492

      epoch  25/100: train_loss=0.006911, val_loss=0.001565, IC=-0.0081

      epoch  26/100: train_loss=0.006523

      epoch  27/100: train_loss=0.006256

      epoch  28/100: train_loss=0.005574

      epoch  29/100: train_loss=0.005563

      epoch  30/100: train_loss=0.005122, val_loss=0.000949, IC=-0.0029

      epoch  31/100: train_loss=0.004750

      epoch  32/100: train_loss=0.004622

      epoch  33/100: train_loss=0.004351

      epoch  34/100: train_loss=0.004207

      epoch  35/100: train_loss=0.003896, val_loss=0.000649, IC=-0.0034

      epoch  36/100: train_loss=0.003752

      epoch  37/100: train_loss=0.003479

      epoch  38/100: train_loss=0.003294

      epoch  39/100: train_loss=0.003160

      epoch  40/100: train_loss=0.003072, val_loss=0.000480, IC=+0.0002

      epoch  41/100: train_loss=0.002935

      epoch  42/100: train_loss=0.002704

      epoch  43/100: train_loss=0.002578

      epoch  44/100: train_loss=0.002532

      epoch  45/100: train_loss=0.002370, val_loss=0.000352, IC=+0.0034

      epoch  46/100: train_loss=0.002282

      epoch  47/100: train_loss=0.002199

      epoch  48/100: train_loss=0.002112

      epoch  49/100: train_loss=0.001977

      epoch  50/100: train_loss=0.001945, val_loss=0.000283, IC=+0.0057

      epoch  51/100: train_loss=0.001895

      epoch  52/100: train_loss=0.001755

      epoch  53/100: train_loss=0.001779

      epoch  54/100: train_loss=0.001632

      epoch  55/100: train_loss=0.001566, val_loss=0.000238, IC=+0.0041

      epoch  56/100: train_loss=0.001518

      epoch  57/100: train_loss=0.001426

      epoch  58/100: train_loss=0.001468

      epoch  59/100: train_loss=0.001362

      epoch  60/100: train_loss=0.001351, val_loss=0.000200, IC=+0.0062

      epoch  61/100: train_loss=0.001275

      epoch  62/100: train_loss=0.001271

      epoch  63/100: train_loss=0.001239

      epoch  64/100: train_loss=0.001216

      epoch  65/100: train_loss=0.001198, val_loss=0.000178, IC=+0.0093

      epoch  66/100: train_loss=0.001142

      epoch  67/100: train_loss=0.001141

      epoch  68/100: train_loss=0.001120

      epoch  69/100: train_loss=0.001040

      epoch  70/100: train_loss=0.001064, val_loss=0.000161, IC=+0.0098

      epoch  71/100: train_loss=0.001047

      epoch  72/100: train_loss=0.001048

      epoch  73/100: train_loss=0.001012

      epoch  74/100: train_loss=0.000997

      epoch  75/100: train_loss=0.000946, val_loss=0.000151, IC=+0.0098

      epoch  76/100: train_loss=0.001005

      epoch  77/100: train_loss=0.000952

      epoch  78/100: train_loss=0.000950

      epoch  79/100: train_loss=0.000901

      epoch  80/100: train_loss=0.000933, val_loss=0.000145, IC=+0.0089

      epoch  81/100: train_loss=0.000888

      epoch  82/100: train_loss=0.000909

      epoch  83/100: train_loss=0.000850

      epoch  84/100: train_loss=0.000853

      epoch  85/100: train_loss=0.000861, val_loss=0.000141, IC=+0.0100

      epoch  86/100: train_loss=0.000875

      epoch  87/100: train_loss=0.000888

      epoch  88/100: train_loss=0.000832

      epoch  89/100: train_loss=0.000825

      epoch  90/100: train_loss=0.000846, val_loss=0.000138, IC=+0.0101

      epoch  91/100: train_loss=0.000834

      epoch  92/100: train_loss=0.000853

      epoch  93/100: train_loss=0.000826

      epoch  94/100: train_loss=0.000824

      epoch  95/100: train_loss=0.000825, val_loss=0.000138, IC=+0.0101

      epoch  96/100: train_loss=0.000841

      epoch  97/100: train_loss=0.000842

      epoch  98/100: train_loss=0.000854

      epoch  99/100: train_loss=0.000844

      epoch 100/100: train_loss=0.000818, val_loss=0.000137, IC=+0.0101

      best_ep=95, IC=+0.0101 (37.5s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,220 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.277897

      epoch   2/100: train_loss=0.138702

      epoch   3/100: train_loss=0.088697

      epoch   4/100: train_loss=0.058168

      epoch   5/100: train_loss=0.041756, val_loss=0.016408, IC=+0.0129

      epoch   6/100: train_loss=0.030669

      epoch   7/100: train_loss=0.023945

      epoch   8/100: train_loss=0.019340

      epoch   9/100: train_loss=0.016166

      epoch  10/100: train_loss=0.013914, val_loss=0.004497, IC=-0.0069

      epoch  11/100: train_loss=0.012400

      epoch  12/100: train_loss=0.010820

      epoch  13/100: train_loss=0.009536

      epoch  14/100: train_loss=0.008551

      epoch  15/100: train_loss=0.007661, val_loss=0.002128, IC=-0.0134

      epoch  16/100: train_loss=0.006929

      epoch  17/100: train_loss=0.006055

      epoch  18/100: train_loss=0.005440

      epoch  19/100: train_loss=0.004905

      epoch  20/100: train_loss=0.004404, val_loss=0.001054, IC=-0.0187

      epoch  21/100: train_loss=0.003954

      epoch  22/100: train_loss=0.003462

      epoch  23/100: train_loss=0.003142

      epoch  24/100: train_loss=0.002905

      epoch  25/100: train_loss=0.002660, val_loss=0.000568, IC=-0.0167

      epoch  26/100: train_loss=0.002282

      epoch  27/100: train_loss=0.002105

      epoch  28/100: train_loss=0.001918

      epoch  29/100: train_loss=0.001723

      epoch  30/100: train_loss=0.001588, val_loss=0.000328, IC=-0.0114

      epoch  31/100: train_loss=0.001422

      epoch  32/100: train_loss=0.001303

      epoch  33/100: train_loss=0.001189

      epoch  34/100: train_loss=0.001103

      epoch  35/100: train_loss=0.000999, val_loss=0.000196, IC=-0.0154

      epoch  36/100: train_loss=0.000911

      epoch  37/100: train_loss=0.000843

      epoch  38/100: train_loss=0.000778

      epoch  39/100: train_loss=0.000726

      epoch  40/100: train_loss=0.000675, val_loss=0.000126, IC=-0.0135

      epoch  41/100: train_loss=0.000609

      epoch  42/100: train_loss=0.000575

      epoch  43/100: train_loss=0.000520

      epoch  44/100: train_loss=0.000510

      epoch  45/100: train_loss=0.000471, val_loss=0.000090, IC=-0.0033

      epoch  46/100: train_loss=0.000435

      epoch  47/100: train_loss=0.000406

      epoch  48/100: train_loss=0.000381

      epoch  49/100: train_loss=0.000355

      epoch  50/100: train_loss=0.000341, val_loss=0.000068, IC=-0.0102

      epoch  51/100: train_loss=0.000318

      epoch  52/100: train_loss=0.000305

      epoch  53/100: train_loss=0.000298

      epoch  54/100: train_loss=0.000272

      epoch  55/100: train_loss=0.000265, val_loss=0.000055, IC=-0.0077

      epoch  56/100: train_loss=0.000252

      epoch  57/100: train_loss=0.000247

      epoch  58/100: train_loss=0.000238

      epoch  59/100: train_loss=0.000219

      epoch  60/100: train_loss=0.000219, val_loss=0.000048, IC=-0.0106

      epoch  61/100: train_loss=0.000213

      epoch  62/100: train_loss=0.000201

      epoch  63/100: train_loss=0.000195

      epoch  64/100: train_loss=0.000192

      epoch  65/100: train_loss=0.000186, val_loss=0.000044, IC=-0.0160

      epoch  66/100: train_loss=0.000180

      epoch  67/100: train_loss=0.000177

      epoch  68/100: train_loss=0.000169

      epoch  69/100: train_loss=0.000163

      epoch  70/100: train_loss=0.000161, val_loss=0.000041, IC=-0.0104

      epoch  71/100: train_loss=0.000158

      epoch  72/100: train_loss=0.000150

      epoch  73/100: train_loss=0.000151

      epoch  74/100: train_loss=0.000149

      epoch  75/100: train_loss=0.000148, val_loss=0.000038, IC=-0.0147

      epoch  76/100: train_loss=0.000147

      epoch  77/100: train_loss=0.000144

      epoch  78/100: train_loss=0.000139

      epoch  79/100: train_loss=0.000140

      epoch  80/100: train_loss=0.000138, val_loss=0.000037, IC=-0.0136

      epoch  81/100: train_loss=0.000139

      epoch  82/100: train_loss=0.000134

      epoch  83/100: train_loss=0.000137

      epoch  84/100: train_loss=0.000134

      epoch  85/100: train_loss=0.000134, val_loss=0.000037, IC=-0.0145

      epoch  86/100: train_loss=0.000134

      epoch  87/100: train_loss=0.000130

      epoch  88/100: train_loss=0.000130

      epoch  89/100: train_loss=0.000131

      epoch  90/100: train_loss=0.000131, val_loss=0.000036, IC=-0.0120

      epoch  91/100: train_loss=0.000131

      epoch  92/100: train_loss=0.000130

      epoch  93/100: train_loss=0.000128

      epoch  94/100: train_loss=0.000129

      epoch  95/100: train_loss=0.000129, val_loss=0.000036, IC=-0.0116

      epoch  96/100: train_loss=0.000128

      epoch  97/100: train_loss=0.000131

      epoch  98/100: train_loss=0.000133

      epoch  99/100: train_loss=0.000128

      epoch 100/100: train_loss=0.000131, val_loss=0.000036, IC=-0.0112

      best_ep=5, IC=+0.0129 (44.0s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.185426

      epoch   2/100: train_loss=0.072993

      epoch   3/100: train_loss=0.045521

      epoch   4/100: train_loss=0.030309

      epoch   5/100: train_loss=0.025537, val_loss=0.005550, IC=-0.0240

      epoch   6/100: train_loss=0.020423

      epoch   7/100: train_loss=0.022508

      epoch   8/100: train_loss=0.015842

      epoch   9/100: train_loss=0.013858

      epoch  10/100: train_loss=0.011980, val_loss=0.002956, IC=-0.0261

      epoch  11/100: train_loss=0.011643

      epoch  12/100: train_loss=0.010390

      epoch  13/100: train_loss=0.009523

      epoch  14/100: train_loss=0.008146

      epoch  15/100: train_loss=0.007458, val_loss=0.001659, IC=-0.0365

      epoch  16/100: train_loss=0.007233

      epoch  17/100: train_loss=0.005961

      epoch  18/100: train_loss=0.005472

      epoch  19/100: train_loss=0.005697

      epoch  20/100: train_loss=0.004595, val_loss=0.000867, IC=-0.0343

      epoch  21/100: train_loss=0.004083

      epoch  22/100: train_loss=0.003938

      epoch  23/100: train_loss=0.003627

      epoch  24/100: train_loss=0.003720

      epoch  25/100: train_loss=0.003091, val_loss=0.000661, IC=-0.0340

      epoch  26/100: train_loss=0.002653

      epoch  27/100: train_loss=0.002425

      epoch  28/100: train_loss=0.002163

      epoch  29/100: train_loss=0.002090

      epoch  30/100: train_loss=0.001894, val_loss=0.000332, IC=-0.0422

      epoch  31/100: train_loss=0.001723

      epoch  32/100: train_loss=0.001842

      epoch  33/100: train_loss=0.001526

      epoch  34/100: train_loss=0.001332

      epoch  35/100: train_loss=0.001379, val_loss=0.000204, IC=-0.0513

      epoch  36/100: train_loss=0.001336

      epoch  37/100: train_loss=0.001181

      epoch  38/100: train_loss=0.000998

      epoch  39/100: train_loss=0.001031

      epoch  40/100: train_loss=0.000873, val_loss=0.000139, IC=-0.0403

      epoch  41/100: train_loss=0.000821

      epoch  42/100: train_loss=0.000757

      epoch  43/100: train_loss=0.000835

      epoch  44/100: train_loss=0.000918

      epoch  45/100: train_loss=0.000680, val_loss=0.000135, IC=-0.0391

      epoch  46/100: train_loss=0.000607

      epoch  47/100: train_loss=0.000560

      epoch  48/100: train_loss=0.000520

      epoch  49/100: train_loss=0.000528

      epoch  50/100: train_loss=0.000493, val_loss=0.000078, IC=-0.0377

      epoch  51/100: train_loss=0.000548

      epoch  52/100: train_loss=0.000619

      epoch  53/100: train_loss=0.000446

      epoch  54/100: train_loss=0.000379

      epoch  55/100: train_loss=0.000426, val_loss=0.000073, IC=-0.0186

      epoch  56/100: train_loss=0.000402

      epoch  57/100: train_loss=0.000358

      epoch  58/100: train_loss=0.000308

      epoch  59/100: train_loss=0.000301

      epoch  60/100: train_loss=0.000292, val_loss=0.000053, IC=-0.0337

      epoch  61/100: train_loss=0.000283

      epoch  62/100: train_loss=0.000262

      epoch  63/100: train_loss=0.000267

      epoch  64/100: train_loss=0.000253

      epoch  65/100: train_loss=0.000243, val_loss=0.000047, IC=-0.0357

      epoch  66/100: train_loss=0.000250

      epoch  67/100: train_loss=0.000292

      epoch  68/100: train_loss=0.000240

      epoch  69/100: train_loss=0.000217

      epoch  70/100: train_loss=0.000227, val_loss=0.000040, IC=-0.0391

      epoch  71/100: train_loss=0.000236

      epoch  72/100: train_loss=0.000207

      epoch  73/100: train_loss=0.000216

      epoch  74/100: train_loss=0.000192

      epoch  75/100: train_loss=0.000190, val_loss=0.000039, IC=-0.0395

      epoch  76/100: train_loss=0.000192

      epoch  77/100: train_loss=0.000177

      epoch  78/100: train_loss=0.000284

      epoch  79/100: train_loss=0.000184

      epoch  80/100: train_loss=0.000176, val_loss=0.000038, IC=-0.0227

      epoch  81/100: train_loss=0.000171

      epoch  82/100: train_loss=0.000169

      epoch  83/100: train_loss=0.000184

      epoch  84/100: train_loss=0.000166

      epoch  85/100: train_loss=0.000177, val_loss=0.000037, IC=-0.0250

      epoch  86/100: train_loss=0.000186

      epoch  87/100: train_loss=0.000171

      epoch  88/100: train_loss=0.000185

      epoch  89/100: train_loss=0.000167

      epoch  90/100: train_loss=0.000169, val_loss=0.000037, IC=-0.0306

      epoch  91/100: train_loss=0.000161

      epoch  92/100: train_loss=0.000177

      epoch  93/100: train_loss=0.000166

      epoch  94/100: train_loss=0.000159

      epoch  95/100: train_loss=0.000171, val_loss=0.000036, IC=-0.0376

      epoch  96/100: train_loss=0.000164

      epoch  97/100: train_loss=0.000164

      epoch  98/100: train_loss=0.000162

      epoch  99/100: train_loss=0.000168

      epoch 100/100: train_loss=0.000196, val_loss=0.000036, IC=-0.0360

      best_ep=55, IC=-0.0186 (50.6s, 20 checkpoints)

  Fold 3: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.389400

      epoch   2/100: train_loss=0.093297

      epoch   3/100: train_loss=0.056019

      epoch   4/100: train_loss=0.044291

      epoch   5/100: train_loss=0.034490, val_loss=0.011206, IC=-0.0083

      epoch   6/100: train_loss=0.021793

      epoch   7/100: train_loss=0.018090

      epoch   8/100: train_loss=0.016055

      epoch   9/100: train_loss=0.012329

      epoch  10/100: train_loss=0.011021, val_loss=0.003134, IC=+0.0006

      epoch  11/100: train_loss=0.009701

      epoch  12/100: train_loss=0.009111

      epoch  13/100: train_loss=0.008134

      epoch  14/100: train_loss=0.006849

      epoch  15/100: train_loss=0.006569, val_loss=0.001435, IC=-0.0101

      epoch  16/100: train_loss=0.005590

      epoch  17/100: train_loss=0.005479

      epoch  18/100: train_loss=0.004892

      epoch  19/100: train_loss=0.004488

      epoch  20/100: train_loss=0.003709, val_loss=0.000878, IC=-0.0080

      epoch  21/100: train_loss=0.003637

      epoch  22/100: train_loss=0.003326

      epoch  23/100: train_loss=0.003077

      epoch  24/100: train_loss=0.003389

      epoch  25/100: train_loss=0.002685, val_loss=0.000555, IC=-0.0062

      epoch  26/100: train_loss=0.002278

      epoch  27/100: train_loss=0.002438

      epoch  28/100: train_loss=0.002026

      epoch  29/100: train_loss=0.001924

      epoch  30/100: train_loss=0.001860, val_loss=0.000336, IC=-0.0177

      epoch  31/100: train_loss=0.001746

      epoch  32/100: train_loss=0.001743

      epoch  33/100: train_loss=0.001378

      epoch  34/100: train_loss=0.001250

      epoch  35/100: train_loss=0.001272, val_loss=0.000235, IC=-0.0125

      epoch  36/100: train_loss=0.001120

      epoch  37/100: train_loss=0.001040

      epoch  38/100: train_loss=0.001001

      epoch  39/100: train_loss=0.000965

      epoch  40/100: train_loss=0.000921, val_loss=0.000174, IC=-0.0181

      epoch  41/100: train_loss=0.000847

      epoch  42/100: train_loss=0.001156

      epoch  43/100: train_loss=0.000754

      epoch  44/100: train_loss=0.000691

      epoch  45/100: train_loss=0.000697, val_loss=0.000133, IC=-0.0209

      epoch  46/100: train_loss=0.000652

      epoch  47/100: train_loss=0.000644

      epoch  48/100: train_loss=0.000624

      epoch  49/100: train_loss=0.000550

      epoch  50/100: train_loss=0.000565, val_loss=0.000099, IC=-0.0304

      epoch  51/100: train_loss=0.000492

      epoch  52/100: train_loss=0.000471

      epoch  53/100: train_loss=0.000477

      epoch  54/100: train_loss=0.000449

      epoch  55/100: train_loss=0.000447, val_loss=0.000084, IC=-0.0289

      epoch  56/100: train_loss=0.000447

      epoch  57/100: train_loss=0.000399

      epoch  58/100: train_loss=0.000374

      epoch  59/100: train_loss=0.000393

      epoch  60/100: train_loss=0.000374, val_loss=0.000070, IC=-0.0251

      epoch  61/100: train_loss=0.000363

      epoch  62/100: train_loss=0.000353

      epoch  63/100: train_loss=0.000318

      epoch  64/100: train_loss=0.000316

      epoch  65/100: train_loss=0.000318, val_loss=0.000063, IC=-0.0282

      epoch  66/100: train_loss=0.000315

      epoch  67/100: train_loss=0.000292

      epoch  68/100: train_loss=0.000340

      epoch  69/100: train_loss=0.000301

      epoch  70/100: train_loss=0.000278, val_loss=0.000059, IC=-0.0314

      epoch  71/100: train_loss=0.000286

      epoch  72/100: train_loss=0.000278

      epoch  73/100: train_loss=0.000268

      epoch  74/100: train_loss=0.000256

      epoch  75/100: train_loss=0.000297, val_loss=0.000053, IC=-0.0301

      epoch  76/100: train_loss=0.000307

      epoch  77/100: train_loss=0.000276

      epoch  78/100: train_loss=0.000255

      epoch  79/100: train_loss=0.000248

      epoch  80/100: train_loss=0.000241, val_loss=0.000051, IC=-0.0349

      epoch  81/100: train_loss=0.000241

      epoch  82/100: train_loss=0.000236

      epoch  83/100: train_loss=0.000248

      epoch  84/100: train_loss=0.000251

      epoch  85/100: train_loss=0.000280, val_loss=0.000049, IC=-0.0326

      epoch  86/100: train_loss=0.000241

      epoch  87/100: train_loss=0.000232

      epoch  88/100: train_loss=0.000261

      epoch  89/100: train_loss=0.000237

      epoch  90/100: train_loss=0.000221, val_loss=0.000047, IC=-0.0318

      epoch  91/100: train_loss=0.000230

      epoch  92/100: train_loss=0.000231

      epoch  93/100: train_loss=0.000248

      epoch  94/100: train_loss=0.000230

      epoch  95/100: train_loss=0.000238, val_loss=0.000047, IC=-0.0332

      epoch  96/100: train_loss=0.000253

      epoch  97/100: train_loss=0.000256

      epoch  98/100: train_loss=0.000234

      epoch  99/100: train_loss=0.000257

      epoch 100/100: train_loss=0.000267, val_loss=0.000047, IC=-0.0322

      best_ep=10, IC=+0.0006 (54.4s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.251929

      epoch   2/100: train_loss=0.119639

      epoch   3/100: train_loss=0.076676

      epoch   4/100: train_loss=0.050808

      epoch   5/100: train_loss=0.036070, val_loss=0.019224, IC=-0.0191

      epoch   6/100: train_loss=0.030134

      epoch   7/100: train_loss=0.024430

      epoch   8/100: train_loss=0.020670

      epoch   9/100: train_loss=0.022206

      epoch  10/100: train_loss=0.016519, val_loss=0.007878, IC=-0.0073

      epoch  11/100: train_loss=0.014755

      epoch  12/100: train_loss=0.010765

      epoch  13/100: train_loss=0.009901

      epoch  14/100: train_loss=0.008804

      epoch  15/100: train_loss=0.009127, val_loss=0.003035, IC=-0.0051

      epoch  16/100: train_loss=0.006941

      epoch  17/100: train_loss=0.006064

      epoch  18/100: train_loss=0.005455

      epoch  19/100: train_loss=0.004861

      epoch  20/100: train_loss=0.005008, val_loss=0.001443, IC=-0.0002

      epoch  21/100: train_loss=0.004048

      epoch  22/100: train_loss=0.003501

      epoch  23/100: train_loss=0.003556

      epoch  24/100: train_loss=0.002999

      epoch  25/100: train_loss=0.002671, val_loss=0.000658, IC=-0.0028

      epoch  26/100: train_loss=0.002427

      epoch  27/100: train_loss=0.002262

      epoch  28/100: train_loss=0.002021

      epoch  29/100: train_loss=0.002292

      epoch  30/100: train_loss=0.001754, val_loss=0.000480, IC=+0.0125

      epoch  31/100: train_loss=0.001648

      epoch  32/100: train_loss=0.001697

      epoch  33/100: train_loss=0.001448

      epoch  34/100: train_loss=0.001189

      epoch  35/100: train_loss=0.001077, val_loss=0.000271, IC=-0.0060

      epoch  36/100: train_loss=0.000972

      epoch  37/100: train_loss=0.000881

      epoch  38/100: train_loss=0.000817

      epoch  39/100: train_loss=0.000801

      epoch  40/100: train_loss=0.000731, val_loss=0.000228, IC=+0.0034

      epoch  41/100: train_loss=0.000652

      epoch  42/100: train_loss=0.000613

      epoch  43/100: train_loss=0.000554

      epoch  44/100: train_loss=0.000514

      epoch  45/100: train_loss=0.000493, val_loss=0.000140, IC=+0.0009

      epoch  46/100: train_loss=0.000477

      epoch  47/100: train_loss=0.000491

      epoch  48/100: train_loss=0.000401

      epoch  49/100: train_loss=0.000403

      epoch  50/100: train_loss=0.000372, val_loss=0.000119, IC=+0.0152

      epoch  51/100: train_loss=0.000343

      epoch  52/100: train_loss=0.000349

      epoch  53/100: train_loss=0.000313

      epoch  54/100: train_loss=0.000296

      epoch  55/100: train_loss=0.000261, val_loss=0.000105, IC=+0.0027

      epoch  56/100: train_loss=0.000250

      epoch  57/100: train_loss=0.000606

      epoch  58/100: train_loss=0.000325

      epoch  59/100: train_loss=0.000262

      epoch  60/100: train_loss=0.000232, val_loss=0.000096, IC=+0.0064

      epoch  61/100: train_loss=0.000198

      epoch  62/100: train_loss=0.000184

      epoch  63/100: train_loss=0.000185

      epoch  64/100: train_loss=0.000170

      epoch  65/100: train_loss=0.000171, val_loss=0.000077, IC=+0.0165

      epoch  66/100: train_loss=0.000161

      epoch  67/100: train_loss=0.000160

      epoch  68/100: train_loss=0.000151

      epoch  69/100: train_loss=0.000149

      epoch  70/100: train_loss=0.000145, val_loss=0.000070, IC=+0.0064

      epoch  71/100: train_loss=0.000142

      epoch  72/100: train_loss=0.000144

      epoch  73/100: train_loss=0.000143

      epoch  74/100: train_loss=0.000138

      epoch  75/100: train_loss=0.000141, val_loss=0.000063, IC=+0.0083

      epoch  76/100: train_loss=0.000129

      epoch  77/100: train_loss=0.000130

      epoch  78/100: train_loss=0.000128

      epoch  79/100: train_loss=0.000124

      epoch  80/100: train_loss=0.000120, val_loss=0.000062, IC=+0.0085

      epoch  81/100: train_loss=0.000147

      epoch  82/100: train_loss=0.000116

      epoch  83/100: train_loss=0.000137

      epoch  84/100: train_loss=0.000123

      epoch  85/100: train_loss=0.000114, val_loss=0.000060, IC=+0.0149

      epoch  86/100: train_loss=0.000119

      epoch  87/100: train_loss=0.000124

      epoch  88/100: train_loss=0.000118

      epoch  89/100: train_loss=0.000115

      epoch  90/100: train_loss=0.000108, val_loss=0.000058, IC=+0.0122

      epoch  91/100: train_loss=0.000112

      epoch  92/100: train_loss=0.000110

      epoch  93/100: train_loss=0.000129

      epoch  94/100: train_loss=0.000114

      epoch  95/100: train_loss=0.000111, val_loss=0.000059, IC=+0.0086

      epoch  96/100: train_loss=0.000114

      epoch  97/100: train_loss=0.000129

      epoch  98/100: train_loss=0.000111

      epoch  99/100: train_loss=0.000109

      epoch 100/100: train_loss=0.000109, val_loss=0.000058, IC=+0.0110

      best_ep=65, IC=+0.0165 (42.3s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.262863

      epoch   2/100: train_loss=0.299800

      epoch   3/100: train_loss=0.079492

      epoch   4/100: train_loss=0.045394

      epoch   5/100: train_loss=0.037433, val_loss=0.012485, IC=-0.0200

      epoch   6/100: train_loss=0.025206

      epoch   7/100: train_loss=0.020509

      epoch   8/100: train_loss=0.019018

      epoch   9/100: train_loss=0.014927

      epoch  10/100: train_loss=0.013602, val_loss=0.004153, IC=-0.0342

      epoch  11/100: train_loss=0.011876

      epoch  12/100: train_loss=0.010544

      epoch  13/100: train_loss=0.009249

      epoch  14/100: train_loss=0.008372

      epoch  15/100: train_loss=0.007405, val_loss=0.001801, IC=-0.0350

      epoch  16/100: train_loss=0.007086

      epoch  17/100: train_loss=0.006200

      epoch  18/100: train_loss=0.005474

      epoch  19/100: train_loss=0.005424

      epoch  20/100: train_loss=0.004620, val_loss=0.001101, IC=-0.0191

      epoch  21/100: train_loss=0.004243

      epoch  22/100: train_loss=0.003662

      epoch  23/100: train_loss=0.003414

      epoch  24/100: train_loss=0.003149

      epoch  25/100: train_loss=0.003984, val_loss=0.000515, IC=-0.0202

      epoch  26/100: train_loss=0.002929

      epoch  27/100: train_loss=0.002404

      epoch  28/100: train_loss=0.003231

      epoch  29/100: train_loss=0.002137

      epoch  30/100: train_loss=0.001799, val_loss=0.000300, IC=-0.0183

      epoch  31/100: train_loss=0.001827

      epoch  32/100: train_loss=0.001507

      epoch  33/100: train_loss=0.001375

      epoch  34/100: train_loss=0.001261

      epoch  35/100: train_loss=0.001219, val_loss=0.000240, IC=-0.0179

      epoch  36/100: train_loss=0.001111

      epoch  37/100: train_loss=0.000998

      epoch  38/100: train_loss=0.001023

      epoch  39/100: train_loss=0.001011

      epoch  40/100: train_loss=0.000894, val_loss=0.000201, IC=+0.0010

      epoch  41/100: train_loss=0.000835

      epoch  42/100: train_loss=0.000750

      epoch  43/100: train_loss=0.000647

      epoch  44/100: train_loss=0.000681

      epoch  45/100: train_loss=0.000547, val_loss=0.000107, IC=+0.0005

      epoch  46/100: train_loss=0.000551

      epoch  47/100: train_loss=0.000552

      epoch  48/100: train_loss=0.000510

      epoch  49/100: train_loss=0.000443

      epoch  50/100: train_loss=0.000433, val_loss=0.000083, IC=-0.0194

      epoch  51/100: train_loss=0.000420

      epoch  52/100: train_loss=0.000379

      epoch  53/100: train_loss=0.000403

      epoch  54/100: train_loss=0.000346

      epoch  55/100: train_loss=0.000315, val_loss=0.000065, IC=-0.0103

      epoch  56/100: train_loss=0.000304

      epoch  57/100: train_loss=0.000293

      epoch  58/100: train_loss=0.000267

      epoch  59/100: train_loss=0.000264

      epoch  60/100: train_loss=0.000245, val_loss=0.000056, IC=-0.0030

      epoch  61/100: train_loss=0.000235

      epoch  62/100: train_loss=0.000239

      epoch  63/100: train_loss=0.000242

      epoch  64/100: train_loss=0.000237

      epoch  65/100: train_loss=0.000208, val_loss=0.000047, IC=+0.0058

      epoch  66/100: train_loss=0.000204

      epoch  67/100: train_loss=0.000202

      epoch  68/100: train_loss=0.000188

      epoch  69/100: train_loss=0.000177

      epoch  70/100: train_loss=0.000191, val_loss=0.000039, IC=-0.0130

      epoch  71/100: train_loss=0.000179

      epoch  72/100: train_loss=0.000170

      epoch  73/100: train_loss=0.000169

      epoch  74/100: train_loss=0.000167

      epoch  75/100: train_loss=0.000179, val_loss=0.000038, IC=-0.0099

      epoch  76/100: train_loss=0.000162

      epoch  77/100: train_loss=0.000169

      epoch  78/100: train_loss=0.000155

      epoch  79/100: train_loss=0.000176

      epoch  80/100: train_loss=0.000154, val_loss=0.000039, IC=-0.0100

      epoch  81/100: train_loss=0.000147

      epoch  82/100: train_loss=0.000155

      epoch  83/100: train_loss=0.000143

      epoch  84/100: train_loss=0.000154

      epoch  85/100: train_loss=0.000147, val_loss=0.000035, IC=-0.0033

      epoch  86/100: train_loss=0.000143

      epoch  87/100: train_loss=0.000141

      epoch  88/100: train_loss=0.000142

      epoch  89/100: train_loss=0.000146

      epoch  90/100: train_loss=0.000136, val_loss=0.000035, IC=-0.0052

      epoch  91/100: train_loss=0.000140

      epoch  92/100: train_loss=0.000142

      epoch  93/100: train_loss=0.000149

      epoch  94/100: train_loss=0.000136

      epoch  95/100: train_loss=0.000142, val_loss=0.000034, IC=-0.0076

      epoch  96/100: train_loss=0.000146

      epoch  97/100: train_loss=0.000136

      epoch  98/100: train_loss=0.000139

      epoch  99/100: train_loss=0.000137

      epoch 100/100: train_loss=0.000179, val_loss=0.000034, IC=-0.0074

      best_ep=65, IC=+0.0058 (39.4s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.157362

      epoch   2/100: train_loss=0.083117

      epoch   3/100: train_loss=0.063350

      epoch   4/100: train_loss=0.041004

      epoch   5/100: train_loss=0.029894, val_loss=0.013533, IC=+0.0212

      epoch   6/100: train_loss=0.022389

      epoch   7/100: train_loss=0.017964

      epoch   8/100: train_loss=0.016266

      epoch   9/100: train_loss=0.012407

      epoch  10/100: train_loss=0.010581, val_loss=0.005864, IC=+0.0350

      epoch  11/100: train_loss=0.008558

      epoch  12/100: train_loss=0.007624

      epoch  13/100: train_loss=0.006321

      epoch  14/100: train_loss=0.006466

      epoch  15/100: train_loss=0.005217, val_loss=0.002367, IC=+0.0142

      epoch  16/100: train_loss=0.004350

      epoch  17/100: train_loss=0.003792

      epoch  18/100: train_loss=0.003723

      epoch  19/100: train_loss=0.003315

      epoch  20/100: train_loss=0.002657, val_loss=0.001121, IC=+0.0207

      epoch  21/100: train_loss=0.002357

      epoch  22/100: train_loss=0.002064

      epoch  23/100: train_loss=0.001942

      epoch  24/100: train_loss=0.001803

      epoch  25/100: train_loss=0.001541, val_loss=0.000595, IC=-0.0003

      epoch  26/100: train_loss=0.001468

      epoch  27/100: train_loss=0.001302

      epoch  28/100: train_loss=0.001166

      epoch  29/100: train_loss=0.001045

      epoch  30/100: train_loss=0.000916, val_loss=0.000381, IC=+0.0300

      epoch  31/100: train_loss=0.000829

      epoch  32/100: train_loss=0.000763

      epoch  33/100: train_loss=0.000651

      epoch  34/100: train_loss=0.000652

      epoch  35/100: train_loss=0.000547, val_loss=0.000224, IC=+0.0082

      epoch  36/100: train_loss=0.000542

      epoch  37/100: train_loss=0.000459

      epoch  38/100: train_loss=0.000434

      epoch  39/100: train_loss=0.000394

      epoch  40/100: train_loss=0.000425, val_loss=0.000158, IC=+0.0152

      epoch  41/100: train_loss=0.000329

      epoch  42/100: train_loss=0.000289

      epoch  43/100: train_loss=0.000290

      epoch  44/100: train_loss=0.000281

      epoch  45/100: train_loss=0.000229, val_loss=0.000120, IC=+0.0011

      epoch  46/100: train_loss=0.000226

      epoch  47/100: train_loss=0.000258

      epoch  48/100: train_loss=0.000250

      epoch  49/100: train_loss=0.000180

      epoch  50/100: train_loss=0.000259, val_loss=0.000093, IC=+0.0388

      epoch  51/100: train_loss=0.000176

      epoch  52/100: train_loss=0.000150

      epoch  53/100: train_loss=0.000138

      epoch  54/100: train_loss=0.000120

      epoch  55/100: train_loss=0.000125, val_loss=0.000068, IC=+0.0091

      epoch  56/100: train_loss=0.000113

      epoch  57/100: train_loss=0.000113

      epoch  58/100: train_loss=0.000100

      epoch  59/100: train_loss=0.000101

      epoch  60/100: train_loss=0.000093, val_loss=0.000067, IC=+0.0122

      epoch  61/100: train_loss=0.000092

      epoch  62/100: train_loss=0.000089

      epoch  63/100: train_loss=0.000080

      epoch  64/100: train_loss=0.000080

      epoch  65/100: train_loss=0.000074, val_loss=0.000057, IC=+0.0022

      epoch  66/100: train_loss=0.000072

      epoch  67/100: train_loss=0.000076

      epoch  68/100: train_loss=0.000066

      epoch  69/100: train_loss=0.000081

      epoch  70/100: train_loss=0.000067, val_loss=0.000054, IC=+0.0148

      epoch  71/100: train_loss=0.000064

      epoch  72/100: train_loss=0.000060

      epoch  73/100: train_loss=0.000063

      epoch  74/100: train_loss=0.000060

      epoch  75/100: train_loss=0.000061, val_loss=0.000053, IC=-0.0004

      epoch  76/100: train_loss=0.000062

      epoch  77/100: train_loss=0.000057

      epoch  78/100: train_loss=0.000071

      epoch  79/100: train_loss=0.000057

      epoch  80/100: train_loss=0.000067, val_loss=0.000051, IC=-0.0110

      epoch  81/100: train_loss=0.000070

      epoch  82/100: train_loss=0.000067

      epoch  83/100: train_loss=0.000055

      epoch  84/100: train_loss=0.000061

      epoch  85/100: train_loss=0.000055, val_loss=0.000053, IC=+0.0288

      epoch  86/100: train_loss=0.000054

      epoch  87/100: train_loss=0.000051

      epoch  88/100: train_loss=0.000050

      epoch  89/100: train_loss=0.000049

      epoch  90/100: train_loss=0.000052, val_loss=0.000051, IC=-0.0177

      epoch  91/100: train_loss=0.000051

      epoch  92/100: train_loss=0.000053

      epoch  93/100: train_loss=0.000051

      epoch  94/100: train_loss=0.000055

      epoch  95/100: train_loss=0.000055, val_loss=0.000051, IC=-0.0137

      epoch  96/100: train_loss=0.000052

      epoch  97/100: train_loss=0.000051

      epoch  98/100: train_loss=0.000049

      epoch  99/100: train_loss=0.000049

      epoch 100/100: train_loss=0.000053, val_loss=0.000051, IC=-0.0121

      best_ep=50, IC=+0.0388 (46.6s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,140 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.246532

      epoch   2/100: train_loss=0.070215

      epoch   3/100: train_loss=0.075157

      epoch   4/100: train_loss=0.032087

      epoch   5/100: train_loss=0.023181, val_loss=0.007566, IC=+0.0259

      epoch   6/100: train_loss=0.018470

      epoch   7/100: train_loss=0.015455

      epoch   8/100: train_loss=0.012907

      epoch   9/100: train_loss=0.012154

      epoch  10/100: train_loss=0.009681, val_loss=0.002224, IC=+0.0105

      epoch  11/100: train_loss=0.008747

      epoch  12/100: train_loss=0.007724

      epoch  13/100: train_loss=0.006522

      epoch  14/100: train_loss=0.005551

      epoch  15/100: train_loss=0.004864, val_loss=0.000978, IC=+0.0062

      epoch  16/100: train_loss=0.004298

      epoch  17/100: train_loss=0.004097

      epoch  18/100: train_loss=0.004070

      epoch  19/100: train_loss=0.003323

      epoch  20/100: train_loss=0.002981, val_loss=0.000659, IC=-0.0115

      epoch  21/100: train_loss=0.002490

      epoch  22/100: train_loss=0.002263

      epoch  23/100: train_loss=0.002039

      epoch  24/100: train_loss=0.001804

      epoch  25/100: train_loss=0.001680, val_loss=0.000265, IC=+0.0034

      epoch  26/100: train_loss=0.001906

      epoch  27/100: train_loss=0.001882

      epoch  28/100: train_loss=0.001576

      epoch  29/100: train_loss=0.001151

      epoch  30/100: train_loss=0.000961, val_loss=0.000153, IC=+0.0231

      epoch  31/100: train_loss=0.000899

      epoch  32/100: train_loss=0.000769

      epoch  33/100: train_loss=0.000714

      epoch  34/100: train_loss=0.000657

      epoch  35/100: train_loss=0.000593, val_loss=0.000100, IC=+0.0079

      epoch  36/100: train_loss=0.000535

      epoch  37/100: train_loss=0.000544

      epoch  38/100: train_loss=0.000470

      epoch  39/100: train_loss=0.000444

      epoch  40/100: train_loss=0.000406, val_loss=0.000078, IC=+0.0017

      epoch  41/100: train_loss=0.000367

      epoch  42/100: train_loss=0.000366

      epoch  43/100: train_loss=0.000313

      epoch  44/100: train_loss=0.000283

      epoch  45/100: train_loss=0.000263, val_loss=0.000061, IC=-0.0068

      epoch  46/100: train_loss=0.000239

      epoch  47/100: train_loss=0.000244

      epoch  48/100: train_loss=0.000228

      epoch  49/100: train_loss=0.000272

      epoch  50/100: train_loss=0.000216, val_loss=0.000059, IC=-0.0110

      epoch  51/100: train_loss=0.000190

      epoch  52/100: train_loss=0.000170

      epoch  53/100: train_loss=0.000157

      epoch  54/100: train_loss=0.000146

      epoch  55/100: train_loss=0.000136, val_loss=0.000042, IC=+0.0164

      epoch  56/100: train_loss=0.000125

      epoch  57/100: train_loss=0.000136

      epoch  58/100: train_loss=0.000126

      epoch  59/100: train_loss=0.000111

      epoch  60/100: train_loss=0.000113, val_loss=0.000039, IC=+0.0216

      epoch  61/100: train_loss=0.000102

      epoch  62/100: train_loss=0.000102

      epoch  63/100: train_loss=0.000097

      epoch  64/100: train_loss=0.000100

      epoch  65/100: train_loss=0.000090, val_loss=0.000036, IC=+0.0111

      epoch  66/100: train_loss=0.000083

      epoch  67/100: train_loss=0.000112

      epoch  68/100: train_loss=0.000093

      epoch  69/100: train_loss=0.000092

      epoch  70/100: train_loss=0.000114, val_loss=0.000039, IC=-0.0216

      epoch  71/100: train_loss=0.000083

      epoch  72/100: train_loss=0.000089

      epoch  73/100: train_loss=0.000091

      epoch  74/100: train_loss=0.000077

      epoch  75/100: train_loss=0.000069, val_loss=0.000034, IC=-0.0048

      epoch  76/100: train_loss=0.000075

      epoch  77/100: train_loss=0.000068

      epoch  78/100: train_loss=0.000065

      epoch  79/100: train_loss=0.000072

      epoch  80/100: train_loss=0.000063, val_loss=0.000034, IC=+0.0001

      epoch  81/100: train_loss=0.000068

      epoch  82/100: train_loss=0.000062

      epoch  83/100: train_loss=0.000061

      epoch  84/100: train_loss=0.000063

      epoch  85/100: train_loss=0.000063, val_loss=0.000033, IC=+0.0037

      epoch  86/100: train_loss=0.000059

      epoch  87/100: train_loss=0.000058

      epoch  88/100: train_loss=0.000057

      epoch  89/100: train_loss=0.000062

      epoch  90/100: train_loss=0.000060, val_loss=0.000033, IC=+0.0083

      epoch  91/100: train_loss=0.000057

      epoch  92/100: train_loss=0.000059

      epoch  93/100: train_loss=0.000062

      epoch  94/100: train_loss=0.000058

      epoch  95/100: train_loss=0.000063, val_loss=0.000033, IC=+0.0070

      epoch  96/100: train_loss=0.000069

      epoch  97/100: train_loss=0.000067

      epoch  98/100: train_loss=0.000059

      epoch  99/100: train_loss=0.000059

      epoch 100/100: train_loss=0.000058, val_loss=0.000033, IC=+0.0094

      best_ep=5, IC=+0.0259 (48.6s, 20 checkpoints)

  nlinear: best_epoch=85, IC=-0.0023 (363.4s)

  Best: nlinear @ epoch 85 (IC=-0.0023)
  Saved to ~/ml4t/public/case_studies/fx_pairs/run_log/training/9dd216506168/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=16,980 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.687785

      epoch   2/100: train_loss=0.414155

      epoch   3/100: train_loss=0.231762

      epoch   4/100: train_loss=0.122085

      epoch   5/100: train_loss=0.068087, val_loss=0.063343, IC=-0.0484

      epoch   6/100: train_loss=0.044585

      epoch   7/100: train_loss=0.033789

      epoch   8/100: train_loss=0.027514

      epoch   9/100: train_loss=0.022199

      epoch  10/100: train_loss=0.019383, val_loss=0.017786, IC=-0.0386

      epoch  11/100: train_loss=0.017607

      epoch  12/100: train_loss=0.016016

      epoch  13/100: train_loss=0.015009

      epoch  14/100: train_loss=0.013914

      epoch  15/100: train_loss=0.012834, val_loss=0.006259, IC=-0.0062

      epoch  16/100: train_loss=0.012175

      epoch  17/100: train_loss=0.010920

      epoch  18/100: train_loss=0.010622

      epoch  19/100: train_loss=0.010046

      epoch  20/100: train_loss=0.009323, val_loss=0.002874, IC=+0.0159

      epoch  21/100: train_loss=0.008786

      epoch  22/100: train_loss=0.008155

      epoch  23/100: train_loss=0.007899

      epoch  24/100: train_loss=0.007402

      epoch  25/100: train_loss=0.007084, val_loss=0.001720, IC=+0.0256

      epoch  26/100: train_loss=0.006815

      epoch  27/100: train_loss=0.006285

      epoch  28/100: train_loss=0.005998

      epoch  29/100: train_loss=0.005645

      epoch  30/100: train_loss=0.005335, val_loss=0.001140, IC=+0.0377

      epoch  31/100: train_loss=0.004878

      epoch  32/100: train_loss=0.004681

      epoch  33/100: train_loss=0.004463

      epoch  34/100: train_loss=0.004349

      epoch  35/100: train_loss=0.004098, val_loss=0.000894, IC=+0.0400

      epoch  36/100: train_loss=0.003869

      epoch  37/100: train_loss=0.003589

      epoch  38/100: train_loss=0.003462

      epoch  39/100: train_loss=0.003360

      epoch  40/100: train_loss=0.003272, val_loss=0.000703, IC=+0.0527

      epoch  41/100: train_loss=0.003087

      epoch  42/100: train_loss=0.003010

      epoch  43/100: train_loss=0.002771

      epoch  44/100: train_loss=0.002657

      epoch  45/100: train_loss=0.002492, val_loss=0.000592, IC=+0.0542

      epoch  46/100: train_loss=0.002481

      epoch  47/100: train_loss=0.002327

      epoch  48/100: train_loss=0.002302

      epoch  49/100: train_loss=0.002189

      epoch  50/100: train_loss=0.002122, val_loss=0.000518, IC=+0.0623

      epoch  51/100: train_loss=0.002102

      epoch  52/100: train_loss=0.001990

      epoch  53/100: train_loss=0.001900

      epoch  54/100: train_loss=0.001814

      epoch  55/100: train_loss=0.001741, val_loss=0.000472, IC=+0.0644

      epoch  56/100: train_loss=0.001677

      epoch  57/100: train_loss=0.001654

      epoch  58/100: train_loss=0.001584

      epoch  59/100: train_loss=0.001505

      epoch  60/100: train_loss=0.001597, val_loss=0.000437, IC=+0.0673

      epoch  61/100: train_loss=0.001489

      epoch  62/100: train_loss=0.001465

      epoch  63/100: train_loss=0.001424

      epoch  64/100: train_loss=0.001408

      epoch  65/100: train_loss=0.001341, val_loss=0.000419, IC=+0.0716

      epoch  66/100: train_loss=0.001267

      epoch  67/100: train_loss=0.001354

      epoch  68/100: train_loss=0.001303

      epoch  69/100: train_loss=0.001222

      epoch  70/100: train_loss=0.001216, val_loss=0.000404, IC=+0.0740

      epoch  71/100: train_loss=0.001219

      epoch  72/100: train_loss=0.001178

      epoch  73/100: train_loss=0.001151

      epoch  74/100: train_loss=0.001146

      epoch  75/100: train_loss=0.001169, val_loss=0.000391, IC=+0.0778

      epoch  76/100: train_loss=0.001186

      epoch  77/100: train_loss=0.001135

      epoch  78/100: train_loss=0.001121

      epoch  79/100: train_loss=0.001070

      epoch  80/100: train_loss=0.001097, val_loss=0.000385, IC=+0.0765

      epoch  81/100: train_loss=0.001090

      epoch  82/100: train_loss=0.001053

      epoch  83/100: train_loss=0.001048

      epoch  84/100: train_loss=0.001028

      epoch  85/100: train_loss=0.001030, val_loss=0.000382, IC=+0.0770

      epoch  86/100: train_loss=0.001021

      epoch  87/100: train_loss=0.001061

      epoch  88/100: train_loss=0.001032

      epoch  89/100: train_loss=0.001004

      epoch  90/100: train_loss=0.000989, val_loss=0.000378, IC=+0.0773

      epoch  91/100: train_loss=0.001011

      epoch  92/100: train_loss=0.000988

      epoch  93/100: train_loss=0.001007

      epoch  94/100: train_loss=0.001033

      epoch  95/100: train_loss=0.001009, val_loss=0.000377, IC=+0.0774

      epoch  96/100: train_loss=0.001017

      epoch  97/100: train_loss=0.001041

      epoch  98/100: train_loss=0.001023

      epoch  99/100: train_loss=0.000990

      epoch 100/100: train_loss=0.001032, val_loss=0.000377, IC=+0.0778

      best_ep=100, IC=+0.0778 (35.0s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,140 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.275648

      epoch   2/100: train_loss=0.139183

      epoch   3/100: train_loss=0.087852

      epoch   4/100: train_loss=0.059491

      epoch   5/100: train_loss=0.042001, val_loss=0.016566, IC=+0.0278

      epoch   6/100: train_loss=0.030460

      epoch   7/100: train_loss=0.024106

      epoch   8/100: train_loss=0.019355

      epoch   9/100: train_loss=0.016483

      epoch  10/100: train_loss=0.014237, val_loss=0.004569, IC=-0.0257

      epoch  11/100: train_loss=0.012601

      epoch  12/100: train_loss=0.011104

      epoch  13/100: train_loss=0.009987

      epoch  14/100: train_loss=0.008683

      epoch  15/100: train_loss=0.007693, val_loss=0.002241, IC=-0.0411

      epoch  16/100: train_loss=0.006986

      epoch  17/100: train_loss=0.006220

      epoch  18/100: train_loss=0.005680

      epoch  19/100: train_loss=0.005015

      epoch  20/100: train_loss=0.004538, val_loss=0.001187, IC=-0.0437

      epoch  21/100: train_loss=0.004110

      epoch  22/100: train_loss=0.003715

      epoch  23/100: train_loss=0.003303

      epoch  24/100: train_loss=0.002996

      epoch  25/100: train_loss=0.002838, val_loss=0.000700, IC=-0.0348

      epoch  26/100: train_loss=0.002470

      epoch  27/100: train_loss=0.002318

      epoch  28/100: train_loss=0.002079

      epoch  29/100: train_loss=0.001893

      epoch  30/100: train_loss=0.001750, val_loss=0.000432, IC=-0.0460

      epoch  31/100: train_loss=0.001572

      epoch  32/100: train_loss=0.001496

      epoch  33/100: train_loss=0.001341

      epoch  34/100: train_loss=0.001253

      epoch  35/100: train_loss=0.001208, val_loss=0.000305, IC=-0.0685

      epoch  36/100: train_loss=0.001090

      epoch  37/100: train_loss=0.001016

      epoch  38/100: train_loss=0.000944

      epoch  39/100: train_loss=0.000892

      epoch  40/100: train_loss=0.000837, val_loss=0.000228, IC=-0.0399

      epoch  41/100: train_loss=0.000789

      epoch  42/100: train_loss=0.000732

      epoch  43/100: train_loss=0.000703

      epoch  44/100: train_loss=0.000671

      epoch  45/100: train_loss=0.000638, val_loss=0.000191, IC=-0.0195

      epoch  46/100: train_loss=0.000606

      epoch  47/100: train_loss=0.000589

      epoch  48/100: train_loss=0.000574

      epoch  49/100: train_loss=0.000532

      epoch  50/100: train_loss=0.000525, val_loss=0.000167, IC=-0.0237

      epoch  51/100: train_loss=0.000491

      epoch  52/100: train_loss=0.000477

      epoch  53/100: train_loss=0.000470

      epoch  54/100: train_loss=0.000444

      epoch  55/100: train_loss=0.000444, val_loss=0.000156, IC=-0.0594

      epoch  56/100: train_loss=0.000436

      epoch  57/100: train_loss=0.000416

      epoch  58/100: train_loss=0.000415

      epoch  59/100: train_loss=0.000391

      epoch  60/100: train_loss=0.000395, val_loss=0.000148, IC=-0.0512

      epoch  61/100: train_loss=0.000386

      epoch  62/100: train_loss=0.000376

      epoch  63/100: train_loss=0.000374

      epoch  64/100: train_loss=0.000364

      epoch  65/100: train_loss=0.000355, val_loss=0.000143, IC=-0.0688

      epoch  66/100: train_loss=0.000352

      epoch  67/100: train_loss=0.000349

      epoch  68/100: train_loss=0.000344

      epoch  69/100: train_loss=0.000338

      epoch  70/100: train_loss=0.000337, val_loss=0.000141, IC=-0.0795

      epoch  71/100: train_loss=0.000331

      epoch  72/100: train_loss=0.000329

      epoch  73/100: train_loss=0.000324

      epoch  74/100: train_loss=0.000324

      epoch  75/100: train_loss=0.000327, val_loss=0.000138, IC=-0.0758

      epoch  76/100: train_loss=0.000324

      epoch  77/100: train_loss=0.000314

      epoch  78/100: train_loss=0.000315

      epoch  79/100: train_loss=0.000312

      epoch  80/100: train_loss=0.000319, val_loss=0.000136, IC=-0.0706

      epoch  81/100: train_loss=0.000315

      epoch  82/100: train_loss=0.000310

      epoch  83/100: train_loss=0.000311

      epoch  84/100: train_loss=0.000312

      epoch  85/100: train_loss=0.000303, val_loss=0.000136, IC=-0.0769

      epoch  86/100: train_loss=0.000312

      epoch  87/100: train_loss=0.000303

      epoch  88/100: train_loss=0.000304

      epoch  89/100: train_loss=0.000304

      epoch  90/100: train_loss=0.000305, val_loss=0.000136, IC=-0.0797

      epoch  91/100: train_loss=0.000302

      epoch  92/100: train_loss=0.000308

      epoch  93/100: train_loss=0.000306

      epoch  94/100: train_loss=0.000305

      epoch  95/100: train_loss=0.000306, val_loss=0.000136, IC=-0.0824

      epoch  96/100: train_loss=0.000300

      epoch  97/100: train_loss=0.000301

      epoch  98/100: train_loss=0.000311

      epoch  99/100: train_loss=0.000303

      epoch 100/100: train_loss=0.000306, val_loss=0.000136, IC=-0.0828

      best_ep=5, IC=+0.0278 (44.4s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.195475

      epoch   2/100: train_loss=0.078080

      epoch   3/100: train_loss=0.048811

      epoch   4/100: train_loss=0.033390

      epoch   5/100: train_loss=0.026235, val_loss=0.005916, IC=-0.0422

      epoch   6/100: train_loss=0.021817

      epoch   7/100: train_loss=0.018961

      epoch   8/100: train_loss=0.016343

      epoch   9/100: train_loss=0.014656

      epoch  10/100: train_loss=0.013381, val_loss=0.002839, IC=-0.0566

      epoch  11/100: train_loss=0.011896

      epoch  12/100: train_loss=0.010212

      epoch  13/100: train_loss=0.009401

      epoch  14/100: train_loss=0.008513

      epoch  15/100: train_loss=0.007636, val_loss=0.001544, IC=-0.0649

      epoch  16/100: train_loss=0.007064

      epoch  17/100: train_loss=0.006484

      epoch  18/100: train_loss=0.005828

      epoch  19/100: train_loss=0.005263

      epoch  20/100: train_loss=0.004823, val_loss=0.000889, IC=-0.0741

      epoch  21/100: train_loss=0.004353

      epoch  22/100: train_loss=0.003985

      epoch  23/100: train_loss=0.003599

      epoch  24/100: train_loss=0.003401

      epoch  25/100: train_loss=0.003079, val_loss=0.000591, IC=-0.0774

      epoch  26/100: train_loss=0.002869

      epoch  27/100: train_loss=0.002645

      epoch  28/100: train_loss=0.002467

      epoch  29/100: train_loss=0.002247

      epoch  30/100: train_loss=0.002052, val_loss=0.000421, IC=-0.0732

      epoch  31/100: train_loss=0.001947

      epoch  32/100: train_loss=0.001800

      epoch  33/100: train_loss=0.001720

      epoch  34/100: train_loss=0.001549

      epoch  35/100: train_loss=0.001432, val_loss=0.000309, IC=-0.0802

      epoch  36/100: train_loss=0.001351

      epoch  37/100: train_loss=0.001273

      epoch  38/100: train_loss=0.001225

      epoch  39/100: train_loss=0.001139

      epoch  40/100: train_loss=0.001072, val_loss=0.000252, IC=-0.0620

      epoch  41/100: train_loss=0.001010

      epoch  42/100: train_loss=0.000946

      epoch  43/100: train_loss=0.000908

      epoch  44/100: train_loss=0.000852

      epoch  45/100: train_loss=0.000816, val_loss=0.000205, IC=-0.0699

      epoch  46/100: train_loss=0.000771

      epoch  47/100: train_loss=0.000735

      epoch  48/100: train_loss=0.000710

      epoch  49/100: train_loss=0.000653

      epoch  50/100: train_loss=0.000651, val_loss=0.000179, IC=-0.0700

      epoch  51/100: train_loss=0.000619

      epoch  52/100: train_loss=0.000603

      epoch  53/100: train_loss=0.000569

      epoch  54/100: train_loss=0.000562

      epoch  55/100: train_loss=0.000538, val_loss=0.000163, IC=-0.0663

      epoch  56/100: train_loss=0.000518

      epoch  57/100: train_loss=0.000506

      epoch  58/100: train_loss=0.000494

      epoch  59/100: train_loss=0.000489

      epoch  60/100: train_loss=0.000475, val_loss=0.000152, IC=-0.0613

      epoch  61/100: train_loss=0.000450

      epoch  62/100: train_loss=0.000445

      epoch  63/100: train_loss=0.000429

      epoch  64/100: train_loss=0.000435

      epoch  65/100: train_loss=0.000415, val_loss=0.000144, IC=-0.0547

      epoch  66/100: train_loss=0.000416

      epoch  67/100: train_loss=0.000407

      epoch  68/100: train_loss=0.000396

      epoch  69/100: train_loss=0.000388

      epoch  70/100: train_loss=0.000389, val_loss=0.000140, IC=-0.0626

      epoch  71/100: train_loss=0.000391

      epoch  72/100: train_loss=0.000375

      epoch  73/100: train_loss=0.000373

      epoch  74/100: train_loss=0.000373

      epoch  75/100: train_loss=0.000369, val_loss=0.000136, IC=-0.0507

      epoch  76/100: train_loss=0.000364

      epoch  77/100: train_loss=0.000363

      epoch  78/100: train_loss=0.000354

      epoch  79/100: train_loss=0.000363

      epoch  80/100: train_loss=0.000356, val_loss=0.000135, IC=-0.0431

      epoch  81/100: train_loss=0.000353

      epoch  82/100: train_loss=0.000355

      epoch  83/100: train_loss=0.000351

      epoch  84/100: train_loss=0.000348

      epoch  85/100: train_loss=0.000354, val_loss=0.000133, IC=-0.0439

      epoch  86/100: train_loss=0.000348

      epoch  87/100: train_loss=0.000341

      epoch  88/100: train_loss=0.000344

      epoch  89/100: train_loss=0.000338

      epoch  90/100: train_loss=0.000346, val_loss=0.000132, IC=-0.0480

      epoch  91/100: train_loss=0.000342

      epoch  92/100: train_loss=0.000345

      epoch  93/100: train_loss=0.000334

      epoch  94/100: train_loss=0.000336

      epoch  95/100: train_loss=0.000342, val_loss=0.000132, IC=-0.0481

      epoch  96/100: train_loss=0.000335

      epoch  97/100: train_loss=0.000342

      epoch  98/100: train_loss=0.000337

      epoch  99/100: train_loss=0.000338

      epoch 100/100: train_loss=0.000342, val_loss=0.000132, IC=-0.0479

      best_ep=5, IC=-0.0422 (49.7s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.386481

      epoch   2/100: train_loss=0.095770

      epoch   3/100: train_loss=0.063141

      epoch   4/100: train_loss=0.041146

      epoch   5/100: train_loss=0.030786, val_loss=0.012039, IC=-0.0052

      epoch   6/100: train_loss=0.023834

      epoch   7/100: train_loss=0.018711

      epoch   8/100: train_loss=0.015425

      epoch   9/100: train_loss=0.013357

      epoch  10/100: train_loss=0.011275, val_loss=0.003638, IC=+0.0103

      epoch  11/100: train_loss=0.009847

      epoch  12/100: train_loss=0.008580

      epoch  13/100: train_loss=0.008000

      epoch  14/100: train_loss=0.007054

      epoch  15/100: train_loss=0.006234, val_loss=0.001571, IC=+0.0233

      epoch  16/100: train_loss=0.005565

      epoch  17/100: train_loss=0.005174

      epoch  18/100: train_loss=0.004695

      epoch  19/100: train_loss=0.004261

      epoch  20/100: train_loss=0.003885, val_loss=0.000892, IC=+0.0134

      epoch  21/100: train_loss=0.003489

      epoch  22/100: train_loss=0.003206

      epoch  23/100: train_loss=0.002968

      epoch  24/100: train_loss=0.002728

      epoch  25/100: train_loss=0.002526, val_loss=0.000570, IC=+0.0072

      epoch  26/100: train_loss=0.002327

      epoch  27/100: train_loss=0.002236

      epoch  28/100: train_loss=0.001988

      epoch  29/100: train_loss=0.001859

      epoch  30/100: train_loss=0.001767, val_loss=0.000401, IC=+0.0020

      epoch  31/100: train_loss=0.001599

      epoch  32/100: train_loss=0.001540

      epoch  33/100: train_loss=0.001453

      epoch  34/100: train_loss=0.001359

      epoch  35/100: train_loss=0.001291, val_loss=0.000293, IC=-0.0043

      epoch  36/100: train_loss=0.001214

      epoch  37/100: train_loss=0.001147

      epoch  38/100: train_loss=0.001068

      epoch  39/100: train_loss=0.001017

      epoch  40/100: train_loss=0.000975, val_loss=0.000230, IC=-0.0134

      epoch  41/100: train_loss=0.000944

      epoch  42/100: train_loss=0.000888

      epoch  43/100: train_loss=0.000863

      epoch  44/100: train_loss=0.000816

      epoch  45/100: train_loss=0.000782, val_loss=0.000190, IC=-0.0056

      epoch  46/100: train_loss=0.000741

      epoch  47/100: train_loss=0.000720

      epoch  48/100: train_loss=0.000701

      epoch  49/100: train_loss=0.000670

      epoch  50/100: train_loss=0.000658, val_loss=0.000166, IC=-0.0123

      epoch  51/100: train_loss=0.000623

      epoch  52/100: train_loss=0.000610

      epoch  53/100: train_loss=0.000588

      epoch  54/100: train_loss=0.000575

      epoch  55/100: train_loss=0.000553, val_loss=0.000150, IC=-0.0142

      epoch  56/100: train_loss=0.000549

      epoch  57/100: train_loss=0.000527

      epoch  58/100: train_loss=0.000526

      epoch  59/100: train_loss=0.000506

      epoch  60/100: train_loss=0.000501, val_loss=0.000138, IC=-0.0166

      epoch  61/100: train_loss=0.000499

      epoch  62/100: train_loss=0.000477

      epoch  63/100: train_loss=0.000467

      epoch  64/100: train_loss=0.000465

      epoch  65/100: train_loss=0.000452, val_loss=0.000131, IC=-0.0171

      epoch  66/100: train_loss=0.000447

      epoch  67/100: train_loss=0.000445

      epoch  68/100: train_loss=0.000437

      epoch  69/100: train_loss=0.000427

      epoch  70/100: train_loss=0.000417, val_loss=0.000126, IC=-0.0192

      epoch  71/100: train_loss=0.000423

      epoch  72/100: train_loss=0.000409

      epoch  73/100: train_loss=0.000399

      epoch  74/100: train_loss=0.000413

      epoch  75/100: train_loss=0.000404, val_loss=0.000122, IC=-0.0177

      epoch  76/100: train_loss=0.000398

      epoch  77/100: train_loss=0.000393

      epoch  78/100: train_loss=0.000393

      epoch  79/100: train_loss=0.000386

      epoch  80/100: train_loss=0.000382, val_loss=0.000120, IC=-0.0208

      epoch  81/100: train_loss=0.000387

      epoch  82/100: train_loss=0.000387

      epoch  83/100: train_loss=0.000387

      epoch  84/100: train_loss=0.000380

      epoch  85/100: train_loss=0.000387, val_loss=0.000119, IC=-0.0206

      epoch  86/100: train_loss=0.000376

      epoch  87/100: train_loss=0.000377

      epoch  88/100: train_loss=0.000376

      epoch  89/100: train_loss=0.000374

      epoch  90/100: train_loss=0.000372, val_loss=0.000118, IC=-0.0199

      epoch  91/100: train_loss=0.000372

      epoch  92/100: train_loss=0.000375

      epoch  93/100: train_loss=0.000373

      epoch  94/100: train_loss=0.000369

      epoch  95/100: train_loss=0.000369, val_loss=0.000118, IC=-0.0202

      epoch  96/100: train_loss=0.000376

      epoch  97/100: train_loss=0.000371

      epoch  98/100: train_loss=0.000371

      epoch  99/100: train_loss=0.000374

      epoch 100/100: train_loss=0.000371, val_loss=0.000118, IC=-0.0209

      best_ep=15, IC=+0.0233 (51.7s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.271797

      epoch   2/100: train_loss=0.130869

      epoch   3/100: train_loss=0.076405

      epoch   4/100: train_loss=0.052582

      epoch   5/100: train_loss=0.040175, val_loss=0.021815, IC=-0.0327

      epoch   6/100: train_loss=0.032266

      epoch   7/100: train_loss=0.026824

      epoch   8/100: train_loss=0.022523

      epoch   9/100: train_loss=0.019323

      epoch  10/100: train_loss=0.016342, val_loss=0.008436, IC=+0.0055

      epoch  11/100: train_loss=0.013938

      epoch  12/100: train_loss=0.012160

      epoch  13/100: train_loss=0.010722

      epoch  14/100: train_loss=0.009417

      epoch  15/100: train_loss=0.008297, val_loss=0.003351, IC=+0.0061

      epoch  16/100: train_loss=0.007222

      epoch  17/100: train_loss=0.006461

      epoch  18/100: train_loss=0.005776

      epoch  19/100: train_loss=0.005231

      epoch  20/100: train_loss=0.004526, val_loss=0.001452, IC=+0.0000

      epoch  21/100: train_loss=0.004190

      epoch  22/100: train_loss=0.003734

      epoch  23/100: train_loss=0.003323

      epoch  24/100: train_loss=0.003033

      epoch  25/100: train_loss=0.002727, val_loss=0.000809, IC=-0.0065

      epoch  26/100: train_loss=0.002477

      epoch  27/100: train_loss=0.002214

      epoch  28/100: train_loss=0.002033

      epoch  29/100: train_loss=0.001839

      epoch  30/100: train_loss=0.001630, val_loss=0.000530, IC=-0.0105

      epoch  31/100: train_loss=0.001521

      epoch  32/100: train_loss=0.001389

      epoch  33/100: train_loss=0.001296

      epoch  34/100: train_loss=0.001193

      epoch  35/100: train_loss=0.001100, val_loss=0.000415, IC=-0.0190

      epoch  36/100: train_loss=0.001003

      epoch  37/100: train_loss=0.000936

      epoch  38/100: train_loss=0.000863

      epoch  39/100: train_loss=0.000826

      epoch  40/100: train_loss=0.000751, val_loss=0.000345, IC=-0.0154

      epoch  41/100: train_loss=0.000696

      epoch  42/100: train_loss=0.000656

      epoch  43/100: train_loss=0.000633

      epoch  44/100: train_loss=0.000594

      epoch  45/100: train_loss=0.000557, val_loss=0.000299, IC=-0.0156

      epoch  46/100: train_loss=0.000526

      epoch  47/100: train_loss=0.000497

      epoch  48/100: train_loss=0.000481

      epoch  49/100: train_loss=0.000446

      epoch  50/100: train_loss=0.000439, val_loss=0.000277, IC=-0.0168

      epoch  51/100: train_loss=0.000426

      epoch  52/100: train_loss=0.000405

      epoch  53/100: train_loss=0.000389

      epoch  54/100: train_loss=0.000378

      epoch  55/100: train_loss=0.000361, val_loss=0.000258, IC=-0.0171

      epoch  56/100: train_loss=0.000353

      epoch  57/100: train_loss=0.000343

      epoch  58/100: train_loss=0.000330

      epoch  59/100: train_loss=0.000324

      epoch  60/100: train_loss=0.000316, val_loss=0.000248, IC=-0.0164

      epoch  61/100: train_loss=0.000309

      epoch  62/100: train_loss=0.000300

      epoch  63/100: train_loss=0.000298

      epoch  64/100: train_loss=0.000289

      epoch  65/100: train_loss=0.000286, val_loss=0.000238, IC=-0.0181

      epoch  66/100: train_loss=0.000280

      epoch  67/100: train_loss=0.000273

      epoch  68/100: train_loss=0.000270

      epoch  69/100: train_loss=0.000270

      epoch  70/100: train_loss=0.000265, val_loss=0.000232, IC=-0.0182

      epoch  71/100: train_loss=0.000264

      epoch  72/100: train_loss=0.000259

      epoch  73/100: train_loss=0.000260

      epoch  74/100: train_loss=0.000259

      epoch  75/100: train_loss=0.000250, val_loss=0.000230, IC=-0.0186

      epoch  76/100: train_loss=0.000249

      epoch  77/100: train_loss=0.000249

      epoch  78/100: train_loss=0.000244

      epoch  79/100: train_loss=0.000250

      epoch  80/100: train_loss=0.000241, val_loss=0.000228, IC=-0.0188

      epoch  81/100: train_loss=0.000243

      epoch  82/100: train_loss=0.000243

      epoch  83/100: train_loss=0.000240

      epoch  84/100: train_loss=0.000239

      epoch  85/100: train_loss=0.000242, val_loss=0.000227, IC=-0.0204

      epoch  86/100: train_loss=0.000237

      epoch  87/100: train_loss=0.000239

      epoch  88/100: train_loss=0.000237

      epoch  89/100: train_loss=0.000235

      epoch  90/100: train_loss=0.000238, val_loss=0.000226, IC=-0.0213

      epoch  91/100: train_loss=0.000236

      epoch  92/100: train_loss=0.000240

      epoch  93/100: train_loss=0.000237

      epoch  94/100: train_loss=0.000236

      epoch  95/100: train_loss=0.000235, val_loss=0.000225, IC=-0.0210

      epoch  96/100: train_loss=0.000236

      epoch  97/100: train_loss=0.000237

      epoch  98/100: train_loss=0.000238

      epoch  99/100: train_loss=0.000236

      epoch 100/100: train_loss=0.000234, val_loss=0.000225, IC=-0.0210

      best_ep=15, IC=+0.0061 (50.9s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.363070

      epoch   2/100: train_loss=0.343455

      epoch   3/100: train_loss=0.096920

      epoch   4/100: train_loss=0.046582

      epoch   5/100: train_loss=0.036367, val_loss=0.014935, IC=-0.0085

      epoch   6/100: train_loss=0.027080

      epoch   7/100: train_loss=0.022837

      epoch   8/100: train_loss=0.019028

      epoch   9/100: train_loss=0.016457

      epoch  10/100: train_loss=0.013880, val_loss=0.004323, IC=-0.0619

      epoch  11/100: train_loss=0.012814

      epoch  12/100: train_loss=0.011176

      epoch  13/100: train_loss=0.010059

      epoch  14/100: train_loss=0.008759

      epoch  15/100: train_loss=0.008057, val_loss=0.002211, IC=-0.0643

      epoch  16/100: train_loss=0.007292

      epoch  17/100: train_loss=0.006523

      epoch  18/100: train_loss=0.005826

      epoch  19/100: train_loss=0.005316

      epoch  20/100: train_loss=0.004754, val_loss=0.001132, IC=-0.0619

      epoch  21/100: train_loss=0.004418

      epoch  22/100: train_loss=0.003939

      epoch  23/100: train_loss=0.003587

      epoch  24/100: train_loss=0.003339

      epoch  25/100: train_loss=0.003038, val_loss=0.000606, IC=-0.0654

      epoch  26/100: train_loss=0.002744

      epoch  27/100: train_loss=0.002554

      epoch  28/100: train_loss=0.002320

      epoch  29/100: train_loss=0.002174

      epoch  30/100: train_loss=0.001985, val_loss=0.000413, IC=-0.0577

      epoch  31/100: train_loss=0.001843

      epoch  32/100: train_loss=0.001675

      epoch  33/100: train_loss=0.001564

      epoch  34/100: train_loss=0.001450

      epoch  35/100: train_loss=0.001337, val_loss=0.000275, IC=-0.0535

      epoch  36/100: train_loss=0.001243

      epoch  37/100: train_loss=0.001159

      epoch  38/100: train_loss=0.001072

      epoch  39/100: train_loss=0.000996

      epoch  40/100: train_loss=0.000946, val_loss=0.000204, IC=-0.0524

      epoch  41/100: train_loss=0.000883

      epoch  42/100: train_loss=0.000831

      epoch  43/100: train_loss=0.000797

      epoch  44/100: train_loss=0.000760

      epoch  45/100: train_loss=0.000695, val_loss=0.000164, IC=-0.0490

      epoch  46/100: train_loss=0.000665

      epoch  47/100: train_loss=0.000640

      epoch  48/100: train_loss=0.000611

      epoch  49/100: train_loss=0.000582

      epoch  50/100: train_loss=0.000545, val_loss=0.000143, IC=-0.0431

      epoch  51/100: train_loss=0.000517

      epoch  52/100: train_loss=0.000500

      epoch  53/100: train_loss=0.000474

      epoch  54/100: train_loss=0.000465

      epoch  55/100: train_loss=0.000456, val_loss=0.000125, IC=-0.0449

      epoch  56/100: train_loss=0.000438

      epoch  57/100: train_loss=0.000425

      epoch  58/100: train_loss=0.000410

      epoch  59/100: train_loss=0.000395

      epoch  60/100: train_loss=0.000384, val_loss=0.000120, IC=-0.0424

      epoch  61/100: train_loss=0.000376

      epoch  62/100: train_loss=0.000371

      epoch  63/100: train_loss=0.000352

      epoch  64/100: train_loss=0.000351

      epoch  65/100: train_loss=0.000342, val_loss=0.000112, IC=-0.0400

      epoch  66/100: train_loss=0.000338

      epoch  67/100: train_loss=0.000329

      epoch  68/100: train_loss=0.000325

      epoch  69/100: train_loss=0.000321

      epoch  70/100: train_loss=0.000313, val_loss=0.000109, IC=-0.0391

      epoch  71/100: train_loss=0.000308

      epoch  72/100: train_loss=0.000302

      epoch  73/100: train_loss=0.000298

      epoch  74/100: train_loss=0.000292

      epoch  75/100: train_loss=0.000301, val_loss=0.000107, IC=-0.0381

      epoch  76/100: train_loss=0.000290

      epoch  77/100: train_loss=0.000289

      epoch  78/100: train_loss=0.000286

      epoch  79/100: train_loss=0.000284

      epoch  80/100: train_loss=0.000285, val_loss=0.000104, IC=-0.0419

      epoch  81/100: train_loss=0.000285

      epoch  82/100: train_loss=0.000277

      epoch  83/100: train_loss=0.000283

      epoch  84/100: train_loss=0.000276

      epoch  85/100: train_loss=0.000279, val_loss=0.000104, IC=-0.0396

      epoch  86/100: train_loss=0.000273

      epoch  87/100: train_loss=0.000275

      epoch  88/100: train_loss=0.000273

      epoch  89/100: train_loss=0.000272

      epoch  90/100: train_loss=0.000274, val_loss=0.000103, IC=-0.0393

      epoch  91/100: train_loss=0.000269

      epoch  92/100: train_loss=0.000267

      epoch  93/100: train_loss=0.000270

      epoch  94/100: train_loss=0.000274

      epoch  95/100: train_loss=0.000271, val_loss=0.000103, IC=-0.0398

      epoch  96/100: train_loss=0.000275

      epoch  97/100: train_loss=0.000271

      epoch  98/100: train_loss=0.000270

      epoch  99/100: train_loss=0.000270

      epoch 100/100: train_loss=0.000270, val_loss=0.000103, IC=-0.0397

      best_ep=5, IC=-0.0085 (53.1s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.156917

      epoch   2/100: train_loss=0.090149

      epoch   3/100: train_loss=0.060702

      epoch   4/100: train_loss=0.043506

      epoch   5/100: train_loss=0.032073, val_loss=0.015104, IC=+0.0501

      epoch   6/100: train_loss=0.024055

      epoch   7/100: train_loss=0.018829

      epoch   8/100: train_loss=0.015061

      epoch   9/100: train_loss=0.012215

      epoch  10/100: train_loss=0.010137, val_loss=0.004385, IC=+0.0412

      epoch  11/100: train_loss=0.008650

      epoch  12/100: train_loss=0.007188

      epoch  13/100: train_loss=0.005986

      epoch  14/100: train_loss=0.005184

      epoch  15/100: train_loss=0.004423, val_loss=0.001856, IC=+0.0360

      epoch  16/100: train_loss=0.003842

      epoch  17/100: train_loss=0.003295

      epoch  18/100: train_loss=0.002885

      epoch  19/100: train_loss=0.002520

      epoch  20/100: train_loss=0.002195, val_loss=0.000964, IC=+0.0120

      epoch  21/100: train_loss=0.001905

      epoch  22/100: train_loss=0.001714

      epoch  23/100: train_loss=0.001472

      epoch  24/100: train_loss=0.001303

      epoch  25/100: train_loss=0.001174, val_loss=0.000626, IC=+0.0080

      epoch  26/100: train_loss=0.001049

      epoch  27/100: train_loss=0.000925

      epoch  28/100: train_loss=0.000837

      epoch  29/100: train_loss=0.000744

      epoch  30/100: train_loss=0.000672, val_loss=0.000445, IC=-0.0086

      epoch  31/100: train_loss=0.000604

      epoch  32/100: train_loss=0.000556

      epoch  33/100: train_loss=0.000496

      epoch  34/100: train_loss=0.000461

      epoch  35/100: train_loss=0.000419, val_loss=0.000345, IC=-0.0210

      epoch  36/100: train_loss=0.000384

      epoch  37/100: train_loss=0.000360

      epoch  38/100: train_loss=0.000331

      epoch  39/100: train_loss=0.000315

      epoch  40/100: train_loss=0.000290, val_loss=0.000293, IC=-0.0330

      epoch  41/100: train_loss=0.000273

      epoch  42/100: train_loss=0.000258

      epoch  43/100: train_loss=0.000247

      epoch  44/100: train_loss=0.000232

      epoch  45/100: train_loss=0.000225, val_loss=0.000267, IC=-0.0409

      epoch  46/100: train_loss=0.000216

      epoch  47/100: train_loss=0.000206

      epoch  48/100: train_loss=0.000201

      epoch  49/100: train_loss=0.000194

      epoch  50/100: train_loss=0.000186, val_loss=0.000250, IC=-0.0423

      epoch  51/100: train_loss=0.000181

      epoch  52/100: train_loss=0.000178

      epoch  53/100: train_loss=0.000172

      epoch  54/100: train_loss=0.000169

      epoch  55/100: train_loss=0.000167, val_loss=0.000244, IC=-0.0425

      epoch  56/100: train_loss=0.000163

      epoch  57/100: train_loss=0.000161

      epoch  58/100: train_loss=0.000158

      epoch  59/100: train_loss=0.000155

      epoch  60/100: train_loss=0.000152, val_loss=0.000238, IC=-0.0380

      epoch  61/100: train_loss=0.000152

      epoch  62/100: train_loss=0.000150

      epoch  63/100: train_loss=0.000148

      epoch  64/100: train_loss=0.000148

      epoch  65/100: train_loss=0.000145, val_loss=0.000234, IC=-0.0332

      epoch  66/100: train_loss=0.000144

      epoch  67/100: train_loss=0.000144

      epoch  68/100: train_loss=0.000142

      epoch  69/100: train_loss=0.000141

      epoch  70/100: train_loss=0.000139, val_loss=0.000233, IC=-0.0301

      epoch  71/100: train_loss=0.000141

      epoch  72/100: train_loss=0.000138

      epoch  73/100: train_loss=0.000138

      epoch  74/100: train_loss=0.000139

      epoch  75/100: train_loss=0.000137, val_loss=0.000232, IC=-0.0287

      epoch  76/100: train_loss=0.000136

      epoch  77/100: train_loss=0.000137

      epoch  78/100: train_loss=0.000136

      epoch  79/100: train_loss=0.000136

      epoch  80/100: train_loss=0.000136, val_loss=0.000231, IC=-0.0286

      epoch  81/100: train_loss=0.000136

      epoch  82/100: train_loss=0.000136

      epoch  83/100: train_loss=0.000135

      epoch  84/100: train_loss=0.000135

      epoch  85/100: train_loss=0.000134, val_loss=0.000231, IC=-0.0285

      epoch  86/100: train_loss=0.000134

      epoch  87/100: train_loss=0.000135

      epoch  88/100: train_loss=0.000134

      epoch  89/100: train_loss=0.000133

      epoch  90/100: train_loss=0.000134, val_loss=0.000230, IC=-0.0281

      epoch  91/100: train_loss=0.000134

      epoch  92/100: train_loss=0.000134

      epoch  93/100: train_loss=0.000135

      epoch  94/100: train_loss=0.000134

      epoch  95/100: train_loss=0.000134, val_loss=0.000230, IC=-0.0275

      epoch  96/100: train_loss=0.000133

      epoch  97/100: train_loss=0.000133

      epoch  98/100: train_loss=0.000134

      epoch  99/100: train_loss=0.000134

      epoch 100/100: train_loss=0.000133, val_loss=0.000230, IC=-0.0279

      best_ep=5, IC=+0.0501 (52.8s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,060 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.249962

      epoch   2/100: train_loss=0.078550

      epoch   3/100: train_loss=0.046375

      epoch   4/100: train_loss=0.033088

      epoch   5/100: train_loss=0.024411, val_loss=0.007257, IC=+0.0445

      epoch   6/100: train_loss=0.019212

      epoch   7/100: train_loss=0.015373

      epoch   8/100: train_loss=0.012897

      epoch   9/100: train_loss=0.011038

      epoch  10/100: train_loss=0.009368, val_loss=0.002265, IC=+0.0059

      epoch  11/100: train_loss=0.007930

      epoch  12/100: train_loss=0.006900

      epoch  13/100: train_loss=0.005740

      epoch  14/100: train_loss=0.004995

      epoch  15/100: train_loss=0.004322, val_loss=0.000973, IC=+0.0026

      epoch  16/100: train_loss=0.003709

      epoch  17/100: train_loss=0.003179

      epoch  18/100: train_loss=0.002700

      epoch  19/100: train_loss=0.002384

      epoch  20/100: train_loss=0.002117, val_loss=0.000491, IC=-0.0067

      epoch  21/100: train_loss=0.001817

      epoch  22/100: train_loss=0.001616

      epoch  23/100: train_loss=0.001405

      epoch  24/100: train_loss=0.001250

      epoch  25/100: train_loss=0.001114, val_loss=0.000293, IC=-0.0052

      epoch  26/100: train_loss=0.000995

      epoch  27/100: train_loss=0.000872

      epoch  28/100: train_loss=0.000794

      epoch  29/100: train_loss=0.000716

      epoch  30/100: train_loss=0.000642, val_loss=0.000199, IC=-0.0029

      epoch  31/100: train_loss=0.000575

      epoch  32/100: train_loss=0.000517

      epoch  33/100: train_loss=0.000476

      epoch  34/100: train_loss=0.000450

      epoch  35/100: train_loss=0.000414, val_loss=0.000159, IC=-0.0015

      epoch  36/100: train_loss=0.000376

      epoch  37/100: train_loss=0.000351

      epoch  38/100: train_loss=0.000325

      epoch  39/100: train_loss=0.000309

      epoch  40/100: train_loss=0.000287, val_loss=0.000143, IC=-0.0062

      epoch  41/100: train_loss=0.000275

      epoch  42/100: train_loss=0.000262

      epoch  43/100: train_loss=0.000249

      epoch  44/100: train_loss=0.000236

      epoch  45/100: train_loss=0.000229, val_loss=0.000133, IC=+0.0000

      epoch  46/100: train_loss=0.000216

      epoch  47/100: train_loss=0.000211

      epoch  48/100: train_loss=0.000204

      epoch  49/100: train_loss=0.000199

      epoch  50/100: train_loss=0.000191, val_loss=0.000129, IC=-0.0025

      epoch  51/100: train_loss=0.000188

      epoch  52/100: train_loss=0.000185

      epoch  53/100: train_loss=0.000182

      epoch  54/100: train_loss=0.000177

      epoch  55/100: train_loss=0.000174, val_loss=0.000127, IC=-0.0230

      epoch  56/100: train_loss=0.000173

      epoch  57/100: train_loss=0.000171

      epoch  58/100: train_loss=0.000166

      epoch  59/100: train_loss=0.000166

      epoch  60/100: train_loss=0.000164, val_loss=0.000125, IC=-0.0019

      epoch  61/100: train_loss=0.000163

      epoch  62/100: train_loss=0.000162

      epoch  63/100: train_loss=0.000160

      epoch  64/100: train_loss=0.000158

      epoch  65/100: train_loss=0.000157, val_loss=0.000124, IC=-0.0043

      epoch  66/100: train_loss=0.000156

      epoch  67/100: train_loss=0.000157

      epoch  68/100: train_loss=0.000154

      epoch  69/100: train_loss=0.000154

      epoch  70/100: train_loss=0.000155, val_loss=0.000124, IC=-0.0036

      epoch  71/100: train_loss=0.000154

      epoch  72/100: train_loss=0.000152

      epoch  73/100: train_loss=0.000152

      epoch  74/100: train_loss=0.000153

      epoch  75/100: train_loss=0.000151, val_loss=0.000123, IC=-0.0056

      epoch  76/100: train_loss=0.000151

      epoch  77/100: train_loss=0.000151

      epoch  78/100: train_loss=0.000150

      epoch  79/100: train_loss=0.000150

      epoch  80/100: train_loss=0.000149, val_loss=0.000123, IC=-0.0044

      epoch  81/100: train_loss=0.000149

      epoch  82/100: train_loss=0.000149

      epoch  83/100: train_loss=0.000149

      epoch  84/100: train_loss=0.000149

      epoch  85/100: train_loss=0.000149, val_loss=0.000123, IC=-0.0120

      epoch  86/100: train_loss=0.000148

      epoch  87/100: train_loss=0.000148

      epoch  88/100: train_loss=0.000149

      epoch  89/100: train_loss=0.000148

      epoch  90/100: train_loss=0.000148, val_loss=0.000123, IC=-0.0107

      epoch  91/100: train_loss=0.000148

      epoch  92/100: train_loss=0.000148

      epoch  93/100: train_loss=0.000149

      epoch  94/100: train_loss=0.000148

      epoch  95/100: train_loss=0.000148, val_loss=0.000123, IC=-0.0103

      epoch  96/100: train_loss=0.000148

      epoch  97/100: train_loss=0.000148

      epoch  98/100: train_loss=0.000149

      epoch  99/100: train_loss=0.000148

      epoch 100/100: train_loss=0.000148, val_loss=0.000123, IC=-0.0089

      best_ep=5, IC=+0.0445 (74.4s, 20 checkpoints)

  nlinear: best_epoch=5, IC=-0.0019 (411.9s)

  Best: nlinear @ epoch 5 (IC=-0.0019)
  Saved to ~/ml4t/public/case_studies/fx_pairs/run_log/training/fd7fd46291ee/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=16,660 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.688119

      epoch   2/100: train_loss=0.414423

      epoch   3/100: train_loss=0.234340

      epoch   4/100: train_loss=0.123633

      epoch   5/100: train_loss=0.069476, val_loss=0.065754, IC=-0.1047

      epoch   6/100: train_loss=0.045664

      epoch   7/100: train_loss=0.034981

      epoch   8/100: train_loss=0.027674

      epoch   9/100: train_loss=0.023027

      epoch  10/100: train_loss=0.020169, val_loss=0.019288, IC=-0.0973

      epoch  11/100: train_loss=0.018086

      epoch  12/100: train_loss=0.016599

      epoch  13/100: train_loss=0.015268

      epoch  14/100: train_loss=0.014520

      epoch  15/100: train_loss=0.013586, val_loss=0.007450, IC=-0.0406

      epoch  16/100: train_loss=0.012800

      epoch  17/100: train_loss=0.012272

      epoch  18/100: train_loss=0.011200

      epoch  19/100: train_loss=0.010637

      epoch  20/100: train_loss=0.009951, val_loss=0.003990, IC=-0.0130

      epoch  21/100: train_loss=0.009625

      epoch  22/100: train_loss=0.008504

      epoch  23/100: train_loss=0.008340

      epoch  24/100: train_loss=0.008020

      epoch  25/100: train_loss=0.007655, val_loss=0.002625, IC=-0.0113

      epoch  26/100: train_loss=0.007074

      epoch  27/100: train_loss=0.006715

      epoch  28/100: train_loss=0.006574

      epoch  29/100: train_loss=0.006401

      epoch  30/100: train_loss=0.006082, val_loss=0.002020, IC=+0.0075

      epoch  31/100: train_loss=0.005756

      epoch  32/100: train_loss=0.005348

      epoch  33/100: train_loss=0.004987

      epoch  34/100: train_loss=0.004885

      epoch  35/100: train_loss=0.004717, val_loss=0.001748, IC=+0.0152

      epoch  36/100: train_loss=0.004288

      epoch  37/100: train_loss=0.004303

      epoch  38/100: train_loss=0.004091

      epoch  39/100: train_loss=0.004069

      epoch  40/100: train_loss=0.003757, val_loss=0.001593, IC=+0.0172

      epoch  41/100: train_loss=0.003588

      epoch  42/100: train_loss=0.003461

      epoch  43/100: train_loss=0.003373

      epoch  44/100: train_loss=0.003179

      epoch  45/100: train_loss=0.003069, val_loss=0.001513, IC=-0.0017

      epoch  46/100: train_loss=0.003055

      epoch  47/100: train_loss=0.002967

      epoch  48/100: train_loss=0.002772

      epoch  49/100: train_loss=0.002675

      epoch  50/100: train_loss=0.002731, val_loss=0.001429, IC=+0.0101

      epoch  51/100: train_loss=0.002556

      epoch  52/100: train_loss=0.002500

      epoch  53/100: train_loss=0.002447

      epoch  54/100: train_loss=0.002331

      epoch  55/100: train_loss=0.002276, val_loss=0.001376, IC=+0.0195

      epoch  56/100: train_loss=0.002170

      epoch  57/100: train_loss=0.002207

      epoch  58/100: train_loss=0.002140

      epoch  59/100: train_loss=0.002061

      epoch  60/100: train_loss=0.002066, val_loss=0.001346, IC=+0.0230

      epoch  61/100: train_loss=0.002095

      epoch  62/100: train_loss=0.002003

      epoch  63/100: train_loss=0.001957

      epoch  64/100: train_loss=0.001904

      epoch  65/100: train_loss=0.001889, val_loss=0.001327, IC=+0.0370

      epoch  66/100: train_loss=0.001854

      epoch  67/100: train_loss=0.001800

      epoch  68/100: train_loss=0.001773

      epoch  69/100: train_loss=0.001759

      epoch  70/100: train_loss=0.001733, val_loss=0.001310, IC=+0.0229

      epoch  71/100: train_loss=0.001780

      epoch  72/100: train_loss=0.001728

      epoch  73/100: train_loss=0.001697

      epoch  74/100: train_loss=0.001673

      epoch  75/100: train_loss=0.001703, val_loss=0.001314, IC=+0.0133

      epoch  76/100: train_loss=0.001696

      epoch  77/100: train_loss=0.001628

      epoch  78/100: train_loss=0.001653

      epoch  79/100: train_loss=0.001632

      epoch  80/100: train_loss=0.001595, val_loss=0.001307, IC=+0.0223

      epoch  81/100: train_loss=0.001617

      epoch  82/100: train_loss=0.001565

      epoch  83/100: train_loss=0.001560

      epoch  84/100: train_loss=0.001584

      epoch  85/100: train_loss=0.001558, val_loss=0.001303, IC=+0.0208

      epoch  86/100: train_loss=0.001555

      epoch  87/100: train_loss=0.001604

      epoch  88/100: train_loss=0.001563

      epoch  89/100: train_loss=0.001554

      epoch  90/100: train_loss=0.001527, val_loss=0.001293, IC=+0.0229

      epoch  91/100: train_loss=0.001534

      epoch  92/100: train_loss=0.001523

      epoch  93/100: train_loss=0.001565

      epoch  94/100: train_loss=0.001501

      epoch  95/100: train_loss=0.001575, val_loss=0.001292, IC=+0.0233

      epoch  96/100: train_loss=0.001533

      epoch  97/100: train_loss=0.001525

      epoch  98/100: train_loss=0.001542

      epoch  99/100: train_loss=0.001544

      epoch 100/100: train_loss=0.001531, val_loss=0.001291, IC=+0.0243

      best_ep=65, IC=+0.0370 (31.2s, 20 checkpoints)

  Fold 1: creating sequences...
    train=21,820 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.277556

      epoch   2/100: train_loss=0.140585

      epoch   3/100: train_loss=0.090834

      epoch   4/100: train_loss=0.060169

      epoch   5/100: train_loss=0.042653, val_loss=0.016874, IC=+0.0668

      epoch   6/100: train_loss=0.031930

      epoch   7/100: train_loss=0.025197

      epoch   8/100: train_loss=0.020158

      epoch   9/100: train_loss=0.017425

      epoch  10/100: train_loss=0.014901, val_loss=0.004971, IC=-0.0080

      epoch  11/100: train_loss=0.013138

      epoch  12/100: train_loss=0.011483

      epoch  13/100: train_loss=0.010244

      epoch  14/100: train_loss=0.009229

      epoch  15/100: train_loss=0.008395, val_loss=0.002695, IC=-0.0255

      epoch  16/100: train_loss=0.007556

      epoch  17/100: train_loss=0.006768

      epoch  18/100: train_loss=0.006273

      epoch  19/100: train_loss=0.005770

      epoch  20/100: train_loss=0.005087, val_loss=0.001673, IC=-0.0782

      epoch  21/100: train_loss=0.004740

      epoch  22/100: train_loss=0.004369

      epoch  23/100: train_loss=0.004034

      epoch  24/100: train_loss=0.003644

      epoch  25/100: train_loss=0.003418, val_loss=0.001131, IC=-0.0381

      epoch  26/100: train_loss=0.003139

      epoch  27/100: train_loss=0.002896

      epoch  28/100: train_loss=0.002722

      epoch  29/100: train_loss=0.002465

      epoch  30/100: train_loss=0.002361, val_loss=0.000899, IC=-0.1020

      epoch  31/100: train_loss=0.002210

      epoch  32/100: train_loss=0.002123

      epoch  33/100: train_loss=0.001968

      epoch  34/100: train_loss=0.001888

      epoch  35/100: train_loss=0.001806, val_loss=0.000768, IC=-0.1104

      epoch  36/100: train_loss=0.001703

      epoch  37/100: train_loss=0.001654

      epoch  38/100: train_loss=0.001567

      epoch  39/100: train_loss=0.001510

      epoch  40/100: train_loss=0.001461, val_loss=0.000664, IC=-0.0491

      epoch  41/100: train_loss=0.001410

      epoch  42/100: train_loss=0.001379

      epoch  43/100: train_loss=0.001328

      epoch  44/100: train_loss=0.001289

      epoch  45/100: train_loss=0.001259, val_loss=0.000646, IC=-0.1010

      epoch  46/100: train_loss=0.001209

      epoch  47/100: train_loss=0.001200

      epoch  48/100: train_loss=0.001167

      epoch  49/100: train_loss=0.001148

      epoch  50/100: train_loss=0.001136, val_loss=0.000607, IC=-0.0704

      epoch  51/100: train_loss=0.001109

      epoch  52/100: train_loss=0.001094

      epoch  53/100: train_loss=0.001075

      epoch  54/100: train_loss=0.001067

      epoch  55/100: train_loss=0.001055, val_loss=0.000606, IC=-0.0964

      epoch  56/100: train_loss=0.001041

      epoch  57/100: train_loss=0.001029

      epoch  58/100: train_loss=0.001033

      epoch  59/100: train_loss=0.000997

      epoch  60/100: train_loss=0.000996, val_loss=0.000592, IC=-0.0931

      epoch  61/100: train_loss=0.000986

      epoch  62/100: train_loss=0.000993

      epoch  63/100: train_loss=0.000983

      epoch  64/100: train_loss=0.000982

      epoch  65/100: train_loss=0.000963, val_loss=0.000585, IC=-0.0926

      epoch  66/100: train_loss=0.000962

      epoch  67/100: train_loss=0.000963

      epoch  68/100: train_loss=0.000953

      epoch  69/100: train_loss=0.000945

      epoch  70/100: train_loss=0.000943, val_loss=0.000587, IC=-0.0964

      epoch  71/100: train_loss=0.000939

      epoch  72/100: train_loss=0.000933

      epoch  73/100: train_loss=0.000929

      epoch  74/100: train_loss=0.000931

      epoch  75/100: train_loss=0.000929, val_loss=0.000575, IC=-0.0733

      epoch  76/100: train_loss=0.000924

      epoch  77/100: train_loss=0.000935

      epoch  78/100: train_loss=0.000933

      epoch  79/100: train_loss=0.000914

      epoch  80/100: train_loss=0.000915, val_loss=0.000581, IC=-0.0909

      epoch  81/100: train_loss=0.000919

      epoch  82/100: train_loss=0.000916

      epoch  83/100: train_loss=0.000922

      epoch  84/100: train_loss=0.000917

      epoch  85/100: train_loss=0.000920, val_loss=0.000580, IC=-0.0894

      epoch  86/100: train_loss=0.000909

      epoch  87/100: train_loss=0.000919

      epoch  88/100: train_loss=0.000913

      epoch  89/100: train_loss=0.000920

      epoch  90/100: train_loss=0.000917, val_loss=0.000581, IC=-0.0939

      epoch  91/100: train_loss=0.000908

      epoch  92/100: train_loss=0.000917

      epoch  93/100: train_loss=0.000905

      epoch  94/100: train_loss=0.000909

      epoch  95/100: train_loss=0.000919, val_loss=0.000580, IC=-0.0917

      epoch  96/100: train_loss=0.000909

      epoch  97/100: train_loss=0.000908

      epoch  98/100: train_loss=0.000909

      epoch  99/100: train_loss=0.000917

      epoch 100/100: train_loss=0.000915, val_loss=0.000580, IC=-0.0904

      best_ep=5, IC=+0.0668 (41.6s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.191942

      epoch   2/100: train_loss=0.078590

      epoch   3/100: train_loss=0.049353

      epoch   4/100: train_loss=0.034236

      epoch   5/100: train_loss=0.027431, val_loss=0.006286, IC=-0.0583

      epoch   6/100: train_loss=0.022626

      epoch   7/100: train_loss=0.019476

      epoch   8/100: train_loss=0.017093

      epoch   9/100: train_loss=0.015479

      epoch  10/100: train_loss=0.013791, val_loss=0.003083, IC=-0.0952

      epoch  11/100: train_loss=0.012407

      epoch  12/100: train_loss=0.011079

      epoch  13/100: train_loss=0.010091

      epoch  14/100: train_loss=0.009103

      epoch  15/100: train_loss=0.008098, val_loss=0.001811, IC=-0.1184

      epoch  16/100: train_loss=0.007619

      epoch  17/100: train_loss=0.006863

      epoch  18/100: train_loss=0.006226

      epoch  19/100: train_loss=0.005709

      epoch  20/100: train_loss=0.005316, val_loss=0.001167, IC=-0.1213

      epoch  21/100: train_loss=0.004955

      epoch  22/100: train_loss=0.004538

      epoch  23/100: train_loss=0.004240

      epoch  24/100: train_loss=0.003906

      epoch  25/100: train_loss=0.003625, val_loss=0.000896, IC=-0.1151

      epoch  26/100: train_loss=0.003414

      epoch  27/100: train_loss=0.003232

      epoch  28/100: train_loss=0.002979

      epoch  29/100: train_loss=0.002812

      epoch  30/100: train_loss=0.002666, val_loss=0.000732, IC=-0.0905

      epoch  31/100: train_loss=0.002495

      epoch  32/100: train_loss=0.002318

      epoch  33/100: train_loss=0.002204

      epoch  34/100: train_loss=0.002095

      epoch  35/100: train_loss=0.001998, val_loss=0.000633, IC=-0.0867

      epoch  36/100: train_loss=0.001944

      epoch  37/100: train_loss=0.001827

      epoch  38/100: train_loss=0.001791

      epoch  39/100: train_loss=0.001691

      epoch  40/100: train_loss=0.001617, val_loss=0.000568, IC=-0.0652

      epoch  41/100: train_loss=0.001569

      epoch  42/100: train_loss=0.001487

      epoch  43/100: train_loss=0.001442

      epoch  44/100: train_loss=0.001396

      epoch  45/100: train_loss=0.001368, val_loss=0.000532, IC=-0.0621

      epoch  46/100: train_loss=0.001311

      epoch  47/100: train_loss=0.001283

      epoch  48/100: train_loss=0.001253

      epoch  49/100: train_loss=0.001230

      epoch  50/100: train_loss=0.001200, val_loss=0.000510, IC=-0.0453

      epoch  51/100: train_loss=0.001189

      epoch  52/100: train_loss=0.001152

      epoch  53/100: train_loss=0.001140

      epoch  54/100: train_loss=0.001123

      epoch  55/100: train_loss=0.001097, val_loss=0.000493, IC=-0.0290

      epoch  56/100: train_loss=0.001070

      epoch  57/100: train_loss=0.001065

      epoch  58/100: train_loss=0.001055

      epoch  59/100: train_loss=0.001045

      epoch  60/100: train_loss=0.001016, val_loss=0.000481, IC=-0.0252

      epoch  61/100: train_loss=0.001011

      epoch  62/100: train_loss=0.001002

      epoch  63/100: train_loss=0.000993

      epoch  64/100: train_loss=0.000982

      epoch  65/100: train_loss=0.000969, val_loss=0.000473, IC=-0.0178

      epoch  66/100: train_loss=0.000972

      epoch  67/100: train_loss=0.000955

      epoch  68/100: train_loss=0.000946

      epoch  69/100: train_loss=0.000963

      epoch  70/100: train_loss=0.000947, val_loss=0.000470, IC=-0.0013

      epoch  71/100: train_loss=0.000938

      epoch  72/100: train_loss=0.000932

      epoch  73/100: train_loss=0.000930

      epoch  74/100: train_loss=0.000926

      epoch  75/100: train_loss=0.000925, val_loss=0.000469, IC=-0.0019

      epoch  76/100: train_loss=0.000928

      epoch  77/100: train_loss=0.000917

      epoch  78/100: train_loss=0.000916

      epoch  79/100: train_loss=0.000914

      epoch  80/100: train_loss=0.000908, val_loss=0.000467, IC=-0.0048

      epoch  81/100: train_loss=0.000910

      epoch  82/100: train_loss=0.000916

      epoch  83/100: train_loss=0.000917

      epoch  84/100: train_loss=0.000902

      epoch  85/100: train_loss=0.000904, val_loss=0.000465, IC=+0.0005

      epoch  86/100: train_loss=0.000906

      epoch  87/100: train_loss=0.000904

      epoch  88/100: train_loss=0.000900

      epoch  89/100: train_loss=0.000900

      epoch  90/100: train_loss=0.000895, val_loss=0.000464, IC=+0.0005

      epoch  91/100: train_loss=0.000900

      epoch  92/100: train_loss=0.000905

      epoch  93/100: train_loss=0.000900

      epoch  94/100: train_loss=0.000894

      epoch  95/100: train_loss=0.000904, val_loss=0.000463, IC=+0.0013

      epoch  96/100: train_loss=0.000894

      epoch  97/100: train_loss=0.000898

      epoch  98/100: train_loss=0.000897

      epoch  99/100: train_loss=0.000895

      epoch 100/100: train_loss=0.000897, val_loss=0.000464, IC=+0.0011

      best_ep=95, IC=+0.0013 (48.7s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.390424

      epoch   2/100: train_loss=0.095465

      epoch   3/100: train_loss=0.062746

      epoch   4/100: train_loss=0.041873

      epoch   5/100: train_loss=0.031307, val_loss=0.012661, IC=-0.0214

      epoch   6/100: train_loss=0.024153

      epoch   7/100: train_loss=0.019566

      epoch   8/100: train_loss=0.015931

      epoch   9/100: train_loss=0.013831

      epoch  10/100: train_loss=0.011738, val_loss=0.003812, IC=+0.0032

      epoch  11/100: train_loss=0.010365

      epoch  12/100: train_loss=0.009362

      epoch  13/100: train_loss=0.008309

      epoch  14/100: train_loss=0.007411

      epoch  15/100: train_loss=0.006633, val_loss=0.001729, IC=+0.0106

      epoch  16/100: train_loss=0.006087

      epoch  17/100: train_loss=0.005619

      epoch  18/100: train_loss=0.005180

      epoch  19/100: train_loss=0.004661

      epoch  20/100: train_loss=0.004288, val_loss=0.001051, IC=-0.0021

      epoch  21/100: train_loss=0.004014

      epoch  22/100: train_loss=0.003723

      epoch  23/100: train_loss=0.003387

      epoch  24/100: train_loss=0.003241

      epoch  25/100: train_loss=0.002992, val_loss=0.000753, IC=-0.0278

      epoch  26/100: train_loss=0.002785

      epoch  27/100: train_loss=0.002660

      epoch  28/100: train_loss=0.002479

      epoch  29/100: train_loss=0.002352

      epoch  30/100: train_loss=0.002235, val_loss=0.000596, IC=-0.0361

      epoch  31/100: train_loss=0.002084

      epoch  32/100: train_loss=0.002010

      epoch  33/100: train_loss=0.001935

      epoch  34/100: train_loss=0.001854

      epoch  35/100: train_loss=0.001779, val_loss=0.000499, IC=-0.0334

      epoch  36/100: train_loss=0.001725

      epoch  37/100: train_loss=0.001638

      epoch  38/100: train_loss=0.001566

      epoch  39/100: train_loss=0.001512

      epoch  40/100: train_loss=0.001487, val_loss=0.000455, IC=-0.0590

      epoch  41/100: train_loss=0.001444

      epoch  42/100: train_loss=0.001407

      epoch  43/100: train_loss=0.001362

      epoch  44/100: train_loss=0.001318

      epoch  45/100: train_loss=0.001312, val_loss=0.000418, IC=-0.0470

      epoch  46/100: train_loss=0.001268

      epoch  47/100: train_loss=0.001235

      epoch  48/100: train_loss=0.001210

      epoch  49/100: train_loss=0.001183

      epoch  50/100: train_loss=0.001166, val_loss=0.000399, IC=-0.0637

      epoch  51/100: train_loss=0.001141

      epoch  52/100: train_loss=0.001120

      epoch  53/100: train_loss=0.001109

      epoch  54/100: train_loss=0.001091

      epoch  55/100: train_loss=0.001064, val_loss=0.000387, IC=-0.0566

      epoch  56/100: train_loss=0.001055

      epoch  57/100: train_loss=0.001057

      epoch  58/100: train_loss=0.001039

      epoch  59/100: train_loss=0.001024

      epoch  60/100: train_loss=0.001022, val_loss=0.000379, IC=-0.0594

      epoch  61/100: train_loss=0.001006

      epoch  62/100: train_loss=0.001006

      epoch  63/100: train_loss=0.000990

      epoch  64/100: train_loss=0.000982

      epoch  65/100: train_loss=0.000967, val_loss=0.000370, IC=-0.0516

      epoch  66/100: train_loss=0.000971

      epoch  67/100: train_loss=0.000957

      epoch  68/100: train_loss=0.000961

      epoch  69/100: train_loss=0.000943

      epoch  70/100: train_loss=0.000944, val_loss=0.000366, IC=-0.0511

      epoch  71/100: train_loss=0.000938

      epoch  72/100: train_loss=0.000929

      epoch  73/100: train_loss=0.000930

      epoch  74/100: train_loss=0.000917

      epoch  75/100: train_loss=0.000925, val_loss=0.000364, IC=-0.0546

      epoch  76/100: train_loss=0.000920

      epoch  77/100: train_loss=0.000917

      epoch  78/100: train_loss=0.000914

      epoch  79/100: train_loss=0.000912

      epoch  80/100: train_loss=0.000912, val_loss=0.000362, IC=-0.0573

      epoch  81/100: train_loss=0.000904

      epoch  82/100: train_loss=0.000911

      epoch  83/100: train_loss=0.000910

      epoch  84/100: train_loss=0.000900

      epoch  85/100: train_loss=0.000907, val_loss=0.000360, IC=-0.0540

      epoch  86/100: train_loss=0.000897

      epoch  87/100: train_loss=0.000895

      epoch  88/100: train_loss=0.000891

      epoch  89/100: train_loss=0.000891

      epoch  90/100: train_loss=0.000880, val_loss=0.000359, IC=-0.0530

      epoch  91/100: train_loss=0.000905

      epoch  92/100: train_loss=0.000888

      epoch  93/100: train_loss=0.000898

      epoch  94/100: train_loss=0.000886

      epoch  95/100: train_loss=0.000891, val_loss=0.000359, IC=-0.0542

      epoch  96/100: train_loss=0.000887

      epoch  97/100: train_loss=0.000889

      epoch  98/100: train_loss=0.000898

      epoch  99/100: train_loss=0.000901

      epoch 100/100: train_loss=0.000895, val_loss=0.000359, IC=-0.0548

      best_ep=15, IC=+0.0106 (55.7s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.267980

      epoch   2/100: train_loss=0.131400

      epoch   3/100: train_loss=0.077131

      epoch   4/100: train_loss=0.052718

      epoch   5/100: train_loss=0.040324, val_loss=0.022111, IC=-0.0454

      epoch   6/100: train_loss=0.032649

      epoch   7/100: train_loss=0.027240

      epoch   8/100: train_loss=0.023087

      epoch   9/100: train_loss=0.020009

      epoch  10/100: train_loss=0.016962, val_loss=0.009034, IC=+0.0206

      epoch  11/100: train_loss=0.014857

      epoch  12/100: train_loss=0.012789

      epoch  13/100: train_loss=0.011619

      epoch  14/100: train_loss=0.010106

      epoch  15/100: train_loss=0.008917, val_loss=0.004072, IC=+0.0141

      epoch  16/100: train_loss=0.007898

      epoch  17/100: train_loss=0.007028

      epoch  18/100: train_loss=0.006267

      epoch  19/100: train_loss=0.005558

      epoch  20/100: train_loss=0.004947, val_loss=0.002071, IC=+0.0151

      epoch  21/100: train_loss=0.004529

      epoch  22/100: train_loss=0.004137

      epoch  23/100: train_loss=0.003740

      epoch  24/100: train_loss=0.003416

      epoch  25/100: train_loss=0.003179, val_loss=0.001397, IC=-0.0043

      epoch  26/100: train_loss=0.002998

      epoch  27/100: train_loss=0.002677

      epoch  28/100: train_loss=0.002449

      epoch  29/100: train_loss=0.002262

      epoch  30/100: train_loss=0.002133, val_loss=0.001110, IC=-0.0141

      epoch  31/100: train_loss=0.001998

      epoch  32/100: train_loss=0.001849

      epoch  33/100: train_loss=0.001718

      epoch  34/100: train_loss=0.001624

      epoch  35/100: train_loss=0.001553, val_loss=0.000962, IC=-0.0171

      epoch  36/100: train_loss=0.001431

      epoch  37/100: train_loss=0.001408

      epoch  38/100: train_loss=0.001322

      epoch  39/100: train_loss=0.001266

      epoch  40/100: train_loss=0.001219, val_loss=0.000893, IC=-0.0141

      epoch  41/100: train_loss=0.001148

      epoch  42/100: train_loss=0.001098

      epoch  43/100: train_loss=0.001087

      epoch  44/100: train_loss=0.001039

      epoch  45/100: train_loss=0.000995, val_loss=0.000830, IC=-0.0159

      epoch  46/100: train_loss=0.000966

      epoch  47/100: train_loss=0.000946

      epoch  48/100: train_loss=0.000918

      epoch  49/100: train_loss=0.000903

      epoch  50/100: train_loss=0.000887, val_loss=0.000810, IC=-0.0114

      epoch  51/100: train_loss=0.000871

      epoch  52/100: train_loss=0.000848

      epoch  53/100: train_loss=0.000828

      epoch  54/100: train_loss=0.000819

      epoch  55/100: train_loss=0.000793, val_loss=0.000790, IC=-0.0127

      epoch  56/100: train_loss=0.000791

      epoch  57/100: train_loss=0.000787

      epoch  58/100: train_loss=0.000773

      epoch  59/100: train_loss=0.000760

      epoch  60/100: train_loss=0.000758, val_loss=0.000778, IC=-0.0183

      epoch  61/100: train_loss=0.000747

      epoch  62/100: train_loss=0.000742

      epoch  63/100: train_loss=0.000739

      epoch  64/100: train_loss=0.000730

      epoch  65/100: train_loss=0.000727, val_loss=0.000773, IC=-0.0174

      epoch  66/100: train_loss=0.000723

      epoch  67/100: train_loss=0.000721

      epoch  68/100: train_loss=0.000710

      epoch  69/100: train_loss=0.000711

      epoch  70/100: train_loss=0.000710, val_loss=0.000770, IC=-0.0227

      epoch  71/100: train_loss=0.000707

      epoch  72/100: train_loss=0.000698

      epoch  73/100: train_loss=0.000696

      epoch  74/100: train_loss=0.000689

      epoch  75/100: train_loss=0.000686, val_loss=0.000764, IC=-0.0197

      epoch  76/100: train_loss=0.000690

      epoch  77/100: train_loss=0.000686

      epoch  78/100: train_loss=0.000690

      epoch  79/100: train_loss=0.000690

      epoch  80/100: train_loss=0.000691, val_loss=0.000761, IC=-0.0232

      epoch  81/100: train_loss=0.000683

      epoch  82/100: train_loss=0.000680

      epoch  83/100: train_loss=0.000680

      epoch  84/100: train_loss=0.000679

      epoch  85/100: train_loss=0.000683, val_loss=0.000761, IC=-0.0239

      epoch  86/100: train_loss=0.000670

      epoch  87/100: train_loss=0.000679

      epoch  88/100: train_loss=0.000676

      epoch  89/100: train_loss=0.000684

      epoch  90/100: train_loss=0.000685, val_loss=0.000761, IC=-0.0220

      epoch  91/100: train_loss=0.000679

      epoch  92/100: train_loss=0.000680

      epoch  93/100: train_loss=0.000680

      epoch  94/100: train_loss=0.000681

      epoch  95/100: train_loss=0.000674, val_loss=0.000760, IC=-0.0230

      epoch  96/100: train_loss=0.000677

      epoch  97/100: train_loss=0.000674

      epoch  98/100: train_loss=0.000667

      epoch  99/100: train_loss=0.000680

      epoch 100/100: train_loss=0.000672, val_loss=0.000760, IC=-0.0231

      best_ep=10, IC=+0.0206 (52.7s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.375469

      epoch   2/100: train_loss=0.327496

      epoch   3/100: train_loss=0.096345

      epoch   4/100: train_loss=0.047576

      epoch   5/100: train_loss=0.035882, val_loss=0.015265, IC=+0.0044

      epoch   6/100: train_loss=0.027337

      epoch   7/100: train_loss=0.023059

      epoch   8/100: train_loss=0.019210

      epoch   9/100: train_loss=0.016867

      epoch  10/100: train_loss=0.014944, val_loss=0.004326, IC=-0.0536

      epoch  11/100: train_loss=0.013321

      epoch  12/100: train_loss=0.011598

      epoch  13/100: train_loss=0.010446

      epoch  14/100: train_loss=0.009464

      epoch  15/100: train_loss=0.008561, val_loss=0.002272, IC=-0.0545

      epoch  16/100: train_loss=0.007495

      epoch  17/100: train_loss=0.006819

      epoch  18/100: train_loss=0.006171

      epoch  19/100: train_loss=0.005664

      epoch  20/100: train_loss=0.005247, val_loss=0.001319, IC=-0.0518

      epoch  21/100: train_loss=0.004714

      epoch  22/100: train_loss=0.004314

      epoch  23/100: train_loss=0.003987

      epoch  24/100: train_loss=0.003673

      epoch  25/100: train_loss=0.003443, val_loss=0.000825, IC=-0.0392

      epoch  26/100: train_loss=0.003156

      epoch  27/100: train_loss=0.002862

      epoch  28/100: train_loss=0.002745

      epoch  29/100: train_loss=0.002556

      epoch  30/100: train_loss=0.002367, val_loss=0.000630, IC=-0.0390

      epoch  31/100: train_loss=0.002198

      epoch  32/100: train_loss=0.002096

      epoch  33/100: train_loss=0.001922

      epoch  34/100: train_loss=0.001857

      epoch  35/100: train_loss=0.001731, val_loss=0.000508, IC=-0.0357

      epoch  36/100: train_loss=0.001631

      epoch  37/100: train_loss=0.001560

      epoch  38/100: train_loss=0.001483

      epoch  39/100: train_loss=0.001416

      epoch  40/100: train_loss=0.001350, val_loss=0.000450, IC=-0.0379

      epoch  41/100: train_loss=0.001308

      epoch  42/100: train_loss=0.001261

      epoch  43/100: train_loss=0.001204

      epoch  44/100: train_loss=0.001150

      epoch  45/100: train_loss=0.001118, val_loss=0.000419, IC=-0.0319

      epoch  46/100: train_loss=0.001056

      epoch  47/100: train_loss=0.001043

      epoch  48/100: train_loss=0.001005

      epoch  49/100: train_loss=0.000969

      epoch  50/100: train_loss=0.000960, val_loss=0.000400, IC=-0.0321

      epoch  51/100: train_loss=0.000938

      epoch  52/100: train_loss=0.000921

      epoch  53/100: train_loss=0.000889

      epoch  54/100: train_loss=0.000879

      epoch  55/100: train_loss=0.000852, val_loss=0.000391, IC=-0.0306

      epoch  56/100: train_loss=0.000854

      epoch  57/100: train_loss=0.000838

      epoch  58/100: train_loss=0.000822

      epoch  59/100: train_loss=0.000821

      epoch  60/100: train_loss=0.000800, val_loss=0.000385, IC=-0.0408

      epoch  61/100: train_loss=0.000782

      epoch  62/100: train_loss=0.000784

      epoch  63/100: train_loss=0.000767

      epoch  64/100: train_loss=0.000764

      epoch  65/100: train_loss=0.000754, val_loss=0.000383, IC=-0.0413

      epoch  66/100: train_loss=0.000747

      epoch  67/100: train_loss=0.000749

      epoch  68/100: train_loss=0.000735

      epoch  69/100: train_loss=0.000735

      epoch  70/100: train_loss=0.000724, val_loss=0.000379, IC=-0.0459

      epoch  71/100: train_loss=0.000725

      epoch  72/100: train_loss=0.000723

      epoch  73/100: train_loss=0.000722

      epoch  74/100: train_loss=0.000716

      epoch  75/100: train_loss=0.000718, val_loss=0.000376, IC=-0.0416

      epoch  76/100: train_loss=0.000716

      epoch  77/100: train_loss=0.000710

      epoch  78/100: train_loss=0.000696

      epoch  79/100: train_loss=0.000696

      epoch  80/100: train_loss=0.000705, val_loss=0.000375, IC=-0.0387

      epoch  81/100: train_loss=0.000701

      epoch  82/100: train_loss=0.000699

      epoch  83/100: train_loss=0.000698

      epoch  84/100: train_loss=0.000695

      epoch  85/100: train_loss=0.000695, val_loss=0.000374, IC=-0.0377

      epoch  86/100: train_loss=0.000698

      epoch  87/100: train_loss=0.000694

      epoch  88/100: train_loss=0.000689

      epoch  89/100: train_loss=0.000691

      epoch  90/100: train_loss=0.000696, val_loss=0.000375, IC=-0.0430

      epoch  91/100: train_loss=0.000684

      epoch  92/100: train_loss=0.000691

      epoch  93/100: train_loss=0.000688

      epoch  94/100: train_loss=0.000681

      epoch  95/100: train_loss=0.000682, val_loss=0.000375, IC=-0.0419

      epoch  96/100: train_loss=0.000696

      epoch  97/100: train_loss=0.000692

      epoch  98/100: train_loss=0.000690

      epoch  99/100: train_loss=0.000685

      epoch 100/100: train_loss=0.000685, val_loss=0.000375, IC=-0.0418

      best_ep=5, IC=+0.0044 (51.0s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.156117

      epoch   2/100: train_loss=0.090500

      epoch   3/100: train_loss=0.062660

      epoch   4/100: train_loss=0.043634

      epoch   5/100: train_loss=0.033005, val_loss=0.015432, IC=+0.0319

      epoch   6/100: train_loss=0.024867

      epoch   7/100: train_loss=0.019404

      epoch   8/100: train_loss=0.015868

      epoch   9/100: train_loss=0.013125

      epoch  10/100: train_loss=0.010599, val_loss=0.005206, IC=+0.0109

      epoch  11/100: train_loss=0.008924

      epoch  12/100: train_loss=0.007563

      epoch  13/100: train_loss=0.006583

      epoch  14/100: train_loss=0.005617

      epoch  15/100: train_loss=0.004873, val_loss=0.002649, IC=-0.0141

      epoch  16/100: train_loss=0.004241

      epoch  17/100: train_loss=0.003696

      epoch  18/100: train_loss=0.003271

      epoch  19/100: train_loss=0.002926

      epoch  20/100: train_loss=0.002564, val_loss=0.001805, IC=-0.0587

      epoch  21/100: train_loss=0.002306

      epoch  22/100: train_loss=0.002054

      epoch  23/100: train_loss=0.001838

      epoch  24/100: train_loss=0.001687

      epoch  25/100: train_loss=0.001551, val_loss=0.001434, IC=-0.0743

      epoch  26/100: train_loss=0.001395

      epoch  27/100: train_loss=0.001285

      epoch  28/100: train_loss=0.001165

      epoch  29/100: train_loss=0.001100

      epoch  30/100: train_loss=0.001002, val_loss=0.001264, IC=-0.0937

      epoch  31/100: train_loss=0.000946

      epoch  32/100: train_loss=0.000887

      epoch  33/100: train_loss=0.000852

      epoch  34/100: train_loss=0.000779

      epoch  35/100: train_loss=0.000762, val_loss=0.001181, IC=-0.1021

      epoch  36/100: train_loss=0.000721

      epoch  37/100: train_loss=0.000700

      epoch  38/100: train_loss=0.000663

      epoch  39/100: train_loss=0.000640

      epoch  40/100: train_loss=0.000618, val_loss=0.001141, IC=-0.0719

      epoch  41/100: train_loss=0.000605

      epoch  42/100: train_loss=0.000593

      epoch  43/100: train_loss=0.000574

      epoch  44/100: train_loss=0.000562

      epoch  45/100: train_loss=0.000550, val_loss=0.001123, IC=-0.0387

      epoch  46/100: train_loss=0.000542

      epoch  47/100: train_loss=0.000532

      epoch  48/100: train_loss=0.000530

      epoch  49/100: train_loss=0.000518

      epoch  50/100: train_loss=0.000511, val_loss=0.001093, IC=-0.0272

      epoch  51/100: train_loss=0.000504

      epoch  52/100: train_loss=0.000503

      epoch  53/100: train_loss=0.000500

      epoch  54/100: train_loss=0.000493

      epoch  55/100: train_loss=0.000489, val_loss=0.001088, IC=-0.0291

      epoch  56/100: train_loss=0.000487

      epoch  57/100: train_loss=0.000484

      epoch  58/100: train_loss=0.000482

      epoch  59/100: train_loss=0.000478

      epoch  60/100: train_loss=0.000477, val_loss=0.001082, IC=-0.0256

      epoch  61/100: train_loss=0.000475

      epoch  62/100: train_loss=0.000473

      epoch  63/100: train_loss=0.000469

      epoch  64/100: train_loss=0.000472

      epoch  65/100: train_loss=0.000471, val_loss=0.001083, IC=-0.0291

      epoch  66/100: train_loss=0.000468

      epoch  67/100: train_loss=0.000467

      epoch  68/100: train_loss=0.000466

      epoch  69/100: train_loss=0.000466

      epoch  70/100: train_loss=0.000464, val_loss=0.001080, IC=-0.0271

      epoch  71/100: train_loss=0.000462

      epoch  72/100: train_loss=0.000465

      epoch  73/100: train_loss=0.000461

      epoch  74/100: train_loss=0.000463

      epoch  75/100: train_loss=0.000463, val_loss=0.001077, IC=-0.0319

      epoch  76/100: train_loss=0.000461

      epoch  77/100: train_loss=0.000459

      epoch  78/100: train_loss=0.000460

      epoch  79/100: train_loss=0.000461

      epoch  80/100: train_loss=0.000459, val_loss=0.001078, IC=-0.0305

      epoch  81/100: train_loss=0.000459

      epoch  82/100: train_loss=0.000458

      epoch  83/100: train_loss=0.000458

      epoch  84/100: train_loss=0.000455

      epoch  85/100: train_loss=0.000459, val_loss=0.001075, IC=-0.0314

      epoch  86/100: train_loss=0.000461

      epoch  87/100: train_loss=0.000458

      epoch  88/100: train_loss=0.000456

      epoch  89/100: train_loss=0.000457

      epoch  90/100: train_loss=0.000458, val_loss=0.001076, IC=-0.0311

      epoch  91/100: train_loss=0.000458

      epoch  92/100: train_loss=0.000456

      epoch  93/100: train_loss=0.000453

      epoch  94/100: train_loss=0.000456

      epoch  95/100: train_loss=0.000455, val_loss=0.001076, IC=-0.0323

      epoch  96/100: train_loss=0.000455

      epoch  97/100: train_loss=0.000458

      epoch  98/100: train_loss=0.000458

      epoch  99/100: train_loss=0.000456

      epoch 100/100: train_loss=0.000457, val_loss=0.001076, IC=-0.0321

      best_ep=5, IC=+0.0319 (51.2s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,180 seq across 20 symbols
    val=4,740 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.249235

      epoch   2/100: train_loss=0.078862

      epoch   3/100: train_loss=0.047118

      epoch   4/100: train_loss=0.032976

      epoch   5/100: train_loss=0.024174, val_loss=0.007104, IC=+0.1338

      epoch   6/100: train_loss=0.019518

      epoch   7/100: train_loss=0.016142

      epoch   8/100: train_loss=0.013218

      epoch   9/100: train_loss=0.011352

      epoch  10/100: train_loss=0.009722, val_loss=0.002383, IC=+0.0786

      epoch  11/100: train_loss=0.008253

      epoch  12/100: train_loss=0.007273

      epoch  13/100: train_loss=0.006132

      epoch  14/100: train_loss=0.005267

      epoch  15/100: train_loss=0.004714, val_loss=0.001180, IC=+0.0677

      epoch  16/100: train_loss=0.004109

      epoch  17/100: train_loss=0.003631

      epoch  18/100: train_loss=0.003189

      epoch  19/100: train_loss=0.002803

      epoch  20/100: train_loss=0.002535, val_loss=0.000771, IC=+0.0373

      epoch  21/100: train_loss=0.002258

      epoch  22/100: train_loss=0.001975

      epoch  23/100: train_loss=0.001874

      epoch  24/100: train_loss=0.001682

      epoch  25/100: train_loss=0.001508, val_loss=0.000560, IC=+0.0543

      epoch  26/100: train_loss=0.001405

      epoch  27/100: train_loss=0.001311

      epoch  28/100: train_loss=0.001186

      epoch  29/100: train_loss=0.001125

      epoch  30/100: train_loss=0.001025, val_loss=0.000485, IC=+0.0662

      epoch  31/100: train_loss=0.000978

      epoch  32/100: train_loss=0.000932

      epoch  33/100: train_loss=0.000896

      epoch  34/100: train_loss=0.000863

      epoch  35/100: train_loss=0.000808, val_loss=0.000457, IC=+0.0808

      epoch  36/100: train_loss=0.000787

      epoch  37/100: train_loss=0.000756

      epoch  38/100: train_loss=0.000740

      epoch  39/100: train_loss=0.000712

      epoch  40/100: train_loss=0.000684, val_loss=0.000450, IC=+0.0670

      epoch  41/100: train_loss=0.000681

      epoch  42/100: train_loss=0.000657

      epoch  43/100: train_loss=0.000650

      epoch  44/100: train_loss=0.000639

      epoch  45/100: train_loss=0.000630, val_loss=0.000444, IC=+0.0881

      epoch  46/100: train_loss=0.000616

      epoch  47/100: train_loss=0.000609

      epoch  48/100: train_loss=0.000599

      epoch  49/100: train_loss=0.000594

      epoch  50/100: train_loss=0.000593, val_loss=0.000442, IC=+0.1010

      epoch  51/100: train_loss=0.000590

      epoch  52/100: train_loss=0.000586

      epoch  53/100: train_loss=0.000580

      epoch  54/100: train_loss=0.000578

      epoch  55/100: train_loss=0.000574, val_loss=0.000440, IC=+0.1104

      epoch  56/100: train_loss=0.000569

      epoch  57/100: train_loss=0.000568

      epoch  58/100: train_loss=0.000562

      epoch  59/100: train_loss=0.000565

      epoch  60/100: train_loss=0.000560, val_loss=0.000442, IC=+0.0903

      epoch  61/100: train_loss=0.000559

      epoch  62/100: train_loss=0.000559

      epoch  63/100: train_loss=0.000554

      epoch  64/100: train_loss=0.000555

      epoch  65/100: train_loss=0.000553, val_loss=0.000444, IC=+0.0869

      epoch  66/100: train_loss=0.000553

      epoch  67/100: train_loss=0.000553

      epoch  68/100: train_loss=0.000551

      epoch  69/100: train_loss=0.000551

      epoch  70/100: train_loss=0.000550, val_loss=0.000445, IC=+0.0746

      epoch  71/100: train_loss=0.000551

      epoch  72/100: train_loss=0.000550

      epoch  73/100: train_loss=0.000547

      epoch  74/100: train_loss=0.000548

      epoch  75/100: train_loss=0.000550, val_loss=0.000445, IC=+0.0822

      epoch  76/100: train_loss=0.000549

      epoch  77/100: train_loss=0.000546

      epoch  78/100: train_loss=0.000548

      epoch  79/100: train_loss=0.000548

      epoch  80/100: train_loss=0.000547, val_loss=0.000444, IC=+0.0823

      epoch  81/100: train_loss=0.000547

      epoch  82/100: train_loss=0.000546

      epoch  83/100: train_loss=0.000547

      epoch  84/100: train_loss=0.000546

      epoch  85/100: train_loss=0.000548, val_loss=0.000444, IC=+0.0846

      epoch  86/100: train_loss=0.000545

      epoch  87/100: train_loss=0.000547

      epoch  88/100: train_loss=0.000545

      epoch  89/100: train_loss=0.000547

      epoch  90/100: train_loss=0.000544, val_loss=0.000444, IC=+0.0848

      epoch  91/100: train_loss=0.000547

      epoch  92/100: train_loss=0.000548

      epoch  93/100: train_loss=0.000546

      epoch  94/100: train_loss=0.000546

      epoch  95/100: train_loss=0.000546, val_loss=0.000444, IC=+0.0854

      epoch  96/100: train_loss=0.000545

      epoch  97/100: train_loss=0.000547

      epoch  98/100: train_loss=0.000544

      epoch  99/100: train_loss=0.000544

      epoch 100/100: train_loss=0.000545, val_loss=0.000444, IC=+0.0852

      best_ep=5, IC=+0.1338 (48.4s, 20 checkpoints)

  nlinear: best_epoch=5, IC=-0.0005 (380.5s)

  Best: nlinear @ epoch 5 (IC=-0.0005)
  Saved to ~/ml4t/public/case_studies/fx_pairs/run_log/training/c5d9f287e0f9/diagnostics

shape: (60, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean   ┆ ic_t      ┆ training_ ┆ predicti │
│ ---       ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---       ┆ ---       ┆ hash      ┆ on_hash  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ i64       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 5         ┆ … ┆ -0.006692 ┆ -0.833563 ┆ 9dd216506 ┆ 635f436d │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 168       ┆ 3d57     │
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 10        ┆ … ┆ -0.00816  ┆ -1.017873 ┆ 9dd216506 ┆ 59efa701 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 168       ┆ 03ed     │
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 15        ┆ … ┆ -0.012718 ┆ -2.123128 ┆ 9dd216506 ┆ b9d74252 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 168       ┆ 4fbd     │
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 20        ┆ … ┆ -0.01027  ┆ -1.942116 ┆ 9dd216506 ┆ 51c644cf │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 168       ┆ 1f5f     │
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 25        ┆ … ┆ -0.010609 ┆ -2.603047 ┆ 9dd216506 ┆ 465c4a65 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 168       ┆ 8a95     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 80        ┆ … ┆ -0.018975 ┆ -1.320787 ┆ fd7fd4629 ┆ d9c3a212 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1ee       ┆ a6a9     │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 85        ┆ … ┆ -0.020613 ┆ -1.40647  ┆ fd7fd4629 ┆ 59d43700 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1ee       ┆ b5f5     │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 90        ┆ … ┆ -0.021232 ┆ -1.418588 ┆ fd7fd4629 ┆ e3e00a21 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1ee       ┆ 0a2b     │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 95        ┆ … ┆ -0.021478 ┆ -1.417316 ┆ fd7fd4629 ┆ df156e0e │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1ee       ┆ afa2     │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 100       ┆ … ┆ -0.021396 ┆ -1.404691 ┆ fd7fd4629 ┆ 08684f7a │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 1ee       ┆ 1ed1     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Verify checkpoint reload

Repeating the request validates the fitted-state digests and returns the same prediction
identities. The notebook never reconstructs another family from an empty cache path.

In [6]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("NLinear checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview sequence checkpoints remain outside official comparisons.")

Official prediction population: ddf6c474f3d8

## Key takeaways

- NLinear and TCN use the same sequence eligibility contract but keep separate model identities.
- Gaps remove affected windows instead of being hidden by positional indexing.
- Stored weights reproduce every declared checkpoint without retraining.