# NLinear - FX Pairs

NLinear forecasts from a fixed consecutive history after subtracting the last observed level. The
transformation focuses the model on changes over the lookback window. This notebook constructs
only the NLinear request; comparisons with TCN, TabM, trees, and linear models are deferred to
`12_model_analysis`, where the complete registered population is available.

**Learning objectives**

- Resolve NLinear's lookback, normalization, and checkpoint schedule before fitting.
- Use the shared gap-safe sequence eligibility instead of positional row windows.
- Prove weight reload and catalog handoff for every declared epoch.

**Book reference**: Chapter 13, Section 13.4

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published NLinear FX configuration."""

import json

import polars as pl
import torch

from case_studies.research import (
    ExecutionTier,
    declared_labels,
    open_study,
    plan_models,
    population_supersedes,
    sweep_labels,
)
from utils.modeling import load_configs
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
LOOKBACK = 0
BATCH_SIZE = 0
DEVICE = ""
SEED = 42
POPULATION_NAME = ""
SUPERSEDES_POPULATION: str = "ddf6c474f3d8"
# The tier is a parameter, not something inferred from whether a reduction happens to be set.
# Inferring it meant a run could be reduced and still open the case study's own artifacts in
# place, which is the production path; a reader under test then wrote where the published run
# writes. WORKSPACE is the other half: a preview has nowhere else to put its results.
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None

## Resolve one forecasting request

The shared runner derives fold boundaries from the finalized label timeline. A missing daily
observation invalidates every lookback window that crosses it, so validation coverage can be
smaller than the raw validation panel while still being exact.

In [3]:
set_global_seeds(SEED)
# The reductions are read before the study is opened, because which study to open is decided by
# the tier and the two have to agree: a preview that reduces nothing is a canonical run wearing
# the wrong tier, and a canonical run carrying reductions would publish a narrowed population
# under the canonical name.
REDUCTION_PARAMETERS = {
    "folds": list(range(MAX_FOLDS)) if MAX_FOLDS else None,
    "max_symbols": MAX_SYMBOLS or None,
}
reductions = {key: value for key, value in REDUCTION_PARAMETERS.items() if value is not None}
tier = ExecutionTier(EXECUTION_TIER)
if tier is ExecutionTier.PREVIEW and not reductions:
    raise ValueError("preview execution must declare at least one reduction")
if tier is ExecutionTier.CANONICAL and reductions:
    raise ValueError(f"canonical execution cannot carry reductions: {sorted(reductions)}")
study = open_study(CASE_STUDY_ID, execution_tier=tier, workspace=WORKSPACE or None)

# Which labels this notebook fits is a question for the training menus, not for the sweep list:
# `setup.yaml` says which labels the case study carries, a menu says what to fit for one of them,
# and a sweep label whose menu declares no `deep_learning:` section owes nothing here. The two
# agree in this case study today, so restating the sweep list produced the right answer by
# coincidence and would have kept producing it silently after a menu changed. The order stays
# `setup.yaml`'s rather than `declared_labels`' menu-file order because the population is named
# after its labels and hashed over its members as an ordered list, so re-ordering would give the
# published population a new identity and demand a supersedes for a run that fits the same models.
declared = declared_labels(study, "deep_learning")
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [label for label in sweep_labels(study) if label in set(declared)]
)

# A run that fits fewer labels than the menus declare is not the canonical population, and the
# architecture is fixed below, so the label set is the only knob that narrows it. Such a run must
# publish under its own name rather than register a partial snapshot under the canonical one.
if set(labels) != set(declared) and not POPULATION_NAME:
    raise ValueError(
        f"this run fits {len(labels)} of the {len(declared)} declared labels, so it cannot "
        "publish the canonical population; pass POPULATION_NAME to give it its own"
    )

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

# An empty DEVICE resolves to what the machine has. The runners refuse "cuda" on a host without
# it rather than falling back silently - which is the right contract for a run whose results get
# registered - so a hardcoded "cuda" default made the notebook unrunnable for any reader without
# an NVIDIA card, and unrunnable on a CPU CI runner. Resolving here keeps the refusal for anyone
# who asks for "cuda" explicitly; the resolved value is printed with the rest of the numerics
# below, so a run never leaves it implicit.
device = DEVICE or ("cuda" if torch.cuda.is_available() else "cpu")
overrides = {
    "device": device,
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
    **({"lookback": LOOKBACK} if LOOKBACK else {}),
}
ARCHITECTURE = "nlinear"
menu = {
    label: [
        config["config_name"]
        for config in load_configs(CASE_STUDY_ID, label, family="deep_learning")
    ]
    for label in labels
}
uncovered = {label: sorted(set(names) - {ARCHITECTURE}) for label, names in menu.items()}
for label, names in menu.items():
    if ARCHITECTURE not in names:
        raise RuntimeError(
            f"{ARCHITECTURE} is not in the configured deep_learning menu for {label}: {names}"
        )

requests = [
    study.model(
        family="deep_learning",
        label=label,
        config_name=ARCHITECTURE,
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label in labels
]
plan = plan_models(study, requests=requests)

# This notebook owes one architecture on every configured label. The rest of the family menu is
# named here rather than left implicit, because a population that is short a configured model is
# otherwise indistinguishable from a complete one.
configured = {(label, ARCHITECTURE) for label in labels}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        f"the plan does not match this notebook's declared coverage; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )
specs = {member.label: json.loads(member.spec_json) for member in plan.members}
computations = {label: spec.get("computation", spec) for label, spec in specs.items()}
computation = computations[labels[0]]

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {computation['numerics']['device']}")
print(f"Lookback: {computation['preprocessing']['lookback']} consecutive daily observations")
for horizon, values in computations.items():
    print(f"Eligible validation rows, {horizon}: {values['expected_prediction_keys']['n_rows']:,}")
for horizon, names in uncovered.items():
    print(
        f"Configured deep_learning models this notebook does not run, {horizon}: {names or 'none'}"
    )

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda
Lookback: 60 consecutive daily observations
Eligible validation rows, fwd_ret_1d: 41,260
Eligible validation rows, fwd_ret_5d: 41,180
Eligible validation rows, fwd_ret_21d: 40,860
Configured deep_learning models this notebook does not run, fwd_ret_1d: ['lstm_h64', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_5d: ['lstm_h64', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_21d: ['lstm_h64', 'tcn']

## Inspect identity-bearing settings

The model request records its architecture parameters, exact folds, expected prediction-key
digest, and every epoch that must remain reproducible from stored weights.

In [4]:
checkpoint_schedule = pl.DataFrame(computation["checkpoint_schedule"])
pl.DataFrame(
    {
        "label": list(computations),
        "architecture": [c["model"]["class"] for c in computations.values()],
        "gap_policy": [c["preprocessing"]["gap_policy"] for c in computations.values()],
        "validation_folds": [
            c["expected_prediction_keys"]["n_folds"] for c in computations.values()
        ],
        "key_digest": [c["expected_prediction_keys"]["digest"] for c in computations.values()],
    }
)
checkpoint_schedule

shape: (20, 2)
┌───────┬───────┐
│ kind  ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ epoch ┆ 5     │
│ epoch ┆ 10    │
│ epoch ┆ 15    │
│ epoch ┆ 20    │
│ epoch ┆ 25    │
│ …     ┆ …     │
│ epoch ┆ 80    │
│ epoch ┆ 85    │
│ epoch ┆ 90    │
│ epoch ┆ 95    │
│ epoch ┆ 100   │
└───────┴───────┘

## Record the official population, then fit or reload NLinear

The runner validates every fold separately before any checkpoint becomes downstream-selectable.
Checkpoint rank correlation is retained as a diagnostic and does not remove other epochs.

`SUPERSEDES_POPULATION` names the population hash this run replaces. A population is the set of
prediction identities it publishes, so anything that moves a training identity produces a
different population under the same name, and the registry refuses to write it without being
told which snapshot it supersedes. That lineage is the only record of which generation is which,
and what moved the identities here was a change to the family's own source file rather than to
anything the notebook declares.

`population_supersedes` decides whether the declared hash may be offered. It is offered when the
name already carries the generation this declaration produced, so a re-run resolves to the
population it published, and when the declaration names the generation in force, so a refit
publishes the next one. It is withheld everywhere else - on a reader's clean clone, where
`run_log/` is gitignored and the registry has no generation at all; under a caller's own
`POPULATION_NAME`; and in a preview, whose isolated registry holds nothing under this name.

In [5]:
if len(plan.expected_prediction_hashes) != checkpoint_schedule.height * len(labels):
    raise RuntimeError("the plan does not cover every declared epoch checkpoint on every label")
population_name = POPULATION_NAME or f"{CASE_STUDY_ID}:{'+'.join(labels)}:nlinear"
population = (
    plan.create_population(
        name=population_name,
        supersedes=population_supersedes(
            study, name=population_name, declared=SUPERSEDES_POPULATION
        ),
    )
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
catalog = execution.catalog_rows.sort("label", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial NLinear checkpoints cannot pass to backtesting")
for label in labels:
    published = catalog.filter(pl.col("label") == label).get_column("checkpoint_value").to_list()
    if published != checkpoint_schedule["value"].to_list():
        raise RuntimeError(f"catalog checkpoints for {label} differ from the resolved request")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=17,060 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.675710

      epoch   2/100: train_loss=0.398101

      epoch   3/100: train_loss=0.219773

      epoch   4/100: train_loss=0.116065

      epoch   5/100: train_loss=0.063307, val_loss=0.057894, IC=-0.0446

      epoch   6/100: train_loss=0.042299

      epoch   7/100: train_loss=0.032569

      epoch   8/100: train_loss=0.025580

      epoch   9/100: train_loss=0.021609

      epoch  10/100: train_loss=0.018858, val_loss=0.014801, IC=-0.0373

      epoch  11/100: train_loss=0.017079

      epoch  12/100: train_loss=0.015423

      epoch  13/100: train_loss=0.013980

      epoch  14/100: train_loss=0.012643

      epoch  15/100: train_loss=0.011916, val_loss=0.005674, IC=-0.0229

      epoch  16/100: train_loss=0.011142

      epoch  17/100: train_loss=0.011264

      epoch  18/100: train_loss=0.009851

      epoch  19/100: train_loss=0.009528

      epoch  20/100: train_loss=0.008772, val_loss=0.002700, IC=-0.0178

      epoch  21/100: train_loss=0.008476

      epoch  22/100: train_loss=0.007934

      epoch  23/100: train_loss=0.007363

      epoch  24/100: train_loss=0.006890

      epoch  25/100: train_loss=0.006563, val_loss=0.001495, IC=-0.0106

      epoch  26/100: train_loss=0.006238

      epoch  27/100: train_loss=0.005989

      epoch  28/100: train_loss=0.005667

      epoch  29/100: train_loss=0.005134

      epoch  30/100: train_loss=0.004888, val_loss=0.000939, IC=-0.0084

      epoch  31/100: train_loss=0.004630

      epoch  32/100: train_loss=0.004452

      epoch  33/100: train_loss=0.004176

      epoch  34/100: train_loss=0.004014

      epoch  35/100: train_loss=0.003828, val_loss=0.000653, IC=-0.0042

      epoch  36/100: train_loss=0.003577

      epoch  37/100: train_loss=0.003322

      epoch  38/100: train_loss=0.003168

      epoch  39/100: train_loss=0.003149

      epoch  40/100: train_loss=0.002949, val_loss=0.000474, IC=+0.0015

      epoch  41/100: train_loss=0.002778

      epoch  42/100: train_loss=0.002671

      epoch  43/100: train_loss=0.002549

      epoch  44/100: train_loss=0.002424

      epoch  45/100: train_loss=0.002290, val_loss=0.000362, IC=+0.0006

      epoch  46/100: train_loss=0.002207

      epoch  47/100: train_loss=0.002140

      epoch  48/100: train_loss=0.002021

      epoch  49/100: train_loss=0.001945

      epoch  50/100: train_loss=0.001893, val_loss=0.000281, IC=+0.0048

      epoch  51/100: train_loss=0.001820

      epoch  52/100: train_loss=0.001699

      epoch  53/100: train_loss=0.001683

      epoch  54/100: train_loss=0.001601

      epoch  55/100: train_loss=0.001484, val_loss=0.000231, IC=+0.0081

      epoch  56/100: train_loss=0.001523

      epoch  57/100: train_loss=0.001405

      epoch  58/100: train_loss=0.001412

      epoch  59/100: train_loss=0.001347

      epoch  60/100: train_loss=0.001327, val_loss=0.000202, IC=+0.0057

      epoch  61/100: train_loss=0.001248

      epoch  62/100: train_loss=0.001214

      epoch  63/100: train_loss=0.001187

      epoch  64/100: train_loss=0.001148

      epoch  65/100: train_loss=0.001115, val_loss=0.000176, IC=+0.0096

      epoch  66/100: train_loss=0.001132

      epoch  67/100: train_loss=0.001100

      epoch  68/100: train_loss=0.001068

      epoch  69/100: train_loss=0.001026

      epoch  70/100: train_loss=0.001014, val_loss=0.000159, IC=+0.0091

      epoch  71/100: train_loss=0.000955

      epoch  72/100: train_loss=0.000950

      epoch  73/100: train_loss=0.000961

      epoch  74/100: train_loss=0.000947

      epoch  75/100: train_loss=0.000925, val_loss=0.000150, IC=+0.0110

      epoch  76/100: train_loss=0.000924

      epoch  77/100: train_loss=0.000873

      epoch  78/100: train_loss=0.000875

      epoch  79/100: train_loss=0.000894

      epoch  80/100: train_loss=0.000900, val_loss=0.000143, IC=+0.0120

      epoch  81/100: train_loss=0.000857

      epoch  82/100: train_loss=0.000845

      epoch  83/100: train_loss=0.000842

      epoch  84/100: train_loss=0.000848

      epoch  85/100: train_loss=0.000860, val_loss=0.000139, IC=+0.0111

      epoch  86/100: train_loss=0.000851

      epoch  87/100: train_loss=0.000845

      epoch  88/100: train_loss=0.000838

      epoch  89/100: train_loss=0.000845

      epoch  90/100: train_loss=0.000840, val_loss=0.000137, IC=+0.0121

      epoch  91/100: train_loss=0.000848

      epoch  92/100: train_loss=0.000820

      epoch  93/100: train_loss=0.000836

      epoch  94/100: train_loss=0.000828

      epoch  95/100: train_loss=0.000828, val_loss=0.000136, IC=+0.0114

      epoch  96/100: train_loss=0.000823

      epoch  97/100: train_loss=0.000816

      epoch  98/100: train_loss=0.000808

      epoch  99/100: train_loss=0.000801

      epoch 100/100: train_loss=0.000790, val_loss=0.000136, IC=+0.0114

      best_ep=90, IC=+0.0121 (68.6s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,220 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.266553

      epoch   2/100: train_loss=0.131352

      epoch   3/100: train_loss=0.086441

      epoch   4/100: train_loss=0.056803

      epoch   5/100: train_loss=0.039583, val_loss=0.016091, IC=+0.0127

      epoch   6/100: train_loss=0.029825

      epoch   7/100: train_loss=0.023095

      epoch   8/100: train_loss=0.018883

      epoch   9/100: train_loss=0.015926

      epoch  10/100: train_loss=0.013511, val_loss=0.004345, IC=-0.0093

      epoch  11/100: train_loss=0.011811

      epoch  12/100: train_loss=0.010706

      epoch  13/100: train_loss=0.009514

      epoch  14/100: train_loss=0.008357

      epoch  15/100: train_loss=0.007416, val_loss=0.001993, IC=-0.0169

      epoch  16/100: train_loss=0.006690

      epoch  17/100: train_loss=0.005708

      epoch  18/100: train_loss=0.005195

      epoch  19/100: train_loss=0.004752

      epoch  20/100: train_loss=0.004154, val_loss=0.001058, IC=-0.0151

      epoch  21/100: train_loss=0.003807

      epoch  22/100: train_loss=0.003365

      epoch  23/100: train_loss=0.003061

      epoch  24/100: train_loss=0.002767

      epoch  25/100: train_loss=0.002432, val_loss=0.000556, IC=-0.0187

      epoch  26/100: train_loss=0.002222

      epoch  27/100: train_loss=0.001982

      epoch  28/100: train_loss=0.001825

      epoch  29/100: train_loss=0.001639

      epoch  30/100: train_loss=0.001497, val_loss=0.000315, IC=-0.0190

      epoch  31/100: train_loss=0.001356

      epoch  32/100: train_loss=0.001255

      epoch  33/100: train_loss=0.001140

      epoch  34/100: train_loss=0.001050

      epoch  35/100: train_loss=0.000954, val_loss=0.000194, IC=-0.0129

      epoch  36/100: train_loss=0.000861

      epoch  37/100: train_loss=0.000793

      epoch  38/100: train_loss=0.000751

      epoch  39/100: train_loss=0.000685

      epoch  40/100: train_loss=0.000638, val_loss=0.000127, IC=-0.0082

      epoch  41/100: train_loss=0.000594

      epoch  42/100: train_loss=0.000538

      epoch  43/100: train_loss=0.000507

      epoch  44/100: train_loss=0.000479

      epoch  45/100: train_loss=0.000429, val_loss=0.000085, IC=-0.0145

      epoch  46/100: train_loss=0.000415

      epoch  47/100: train_loss=0.000381

      epoch  48/100: train_loss=0.000363

      epoch  49/100: train_loss=0.000350

      epoch  50/100: train_loss=0.000332, val_loss=0.000065, IC=-0.0080

      epoch  51/100: train_loss=0.000317

      epoch  52/100: train_loss=0.000295

      epoch  53/100: train_loss=0.000274

      epoch  54/100: train_loss=0.000273

      epoch  55/100: train_loss=0.000253, val_loss=0.000054, IC=-0.0175

      epoch  56/100: train_loss=0.000248

      epoch  57/100: train_loss=0.000234

      epoch  58/100: train_loss=0.000223

      epoch  59/100: train_loss=0.000212

      epoch  60/100: train_loss=0.000203, val_loss=0.000048, IC=-0.0085

      epoch  61/100: train_loss=0.000198

      epoch  62/100: train_loss=0.000194

      epoch  63/100: train_loss=0.000190

      epoch  64/100: train_loss=0.000181

      epoch  65/100: train_loss=0.000176, val_loss=0.000043, IC=-0.0176

      epoch  66/100: train_loss=0.000171

      epoch  67/100: train_loss=0.000167

      epoch  68/100: train_loss=0.000164

      epoch  69/100: train_loss=0.000159

      epoch  70/100: train_loss=0.000153, val_loss=0.000040, IC=-0.0097

      epoch  71/100: train_loss=0.000153

      epoch  72/100: train_loss=0.000152

      epoch  73/100: train_loss=0.000149

      epoch  74/100: train_loss=0.000144

      epoch  75/100: train_loss=0.000142, val_loss=0.000038, IC=-0.0098

      epoch  76/100: train_loss=0.000142

      epoch  77/100: train_loss=0.000137

      epoch  78/100: train_loss=0.000136

      epoch  79/100: train_loss=0.000137

      epoch  80/100: train_loss=0.000134, val_loss=0.000037, IC=-0.0158

      epoch  81/100: train_loss=0.000134

      epoch  82/100: train_loss=0.000133

      epoch  83/100: train_loss=0.000130

      epoch  84/100: train_loss=0.000130

      epoch  85/100: train_loss=0.000128, val_loss=0.000036, IC=-0.0137

      epoch  86/100: train_loss=0.000128

      epoch  87/100: train_loss=0.000126

      epoch  88/100: train_loss=0.000126

      epoch  89/100: train_loss=0.000128

      epoch  90/100: train_loss=0.000127, val_loss=0.000036, IC=-0.0129

      epoch  91/100: train_loss=0.000126

      epoch  92/100: train_loss=0.000128

      epoch  93/100: train_loss=0.000126

      epoch  94/100: train_loss=0.000125

      epoch  95/100: train_loss=0.000123, val_loss=0.000036, IC=-0.0125

      epoch  96/100: train_loss=0.000126

      epoch  97/100: train_loss=0.000126

      epoch  98/100: train_loss=0.000127

      epoch  99/100: train_loss=0.000125

      epoch 100/100: train_loss=0.000125, val_loss=0.000036, IC=-0.0123

      best_ep=5, IC=+0.0127 (82.8s, 20 checkpoints)

  Fold 2: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.173764

      epoch   2/100: train_loss=0.069958

      epoch   3/100: train_loss=0.046083

      epoch   4/100: train_loss=0.031253

      epoch   5/100: train_loss=0.024487, val_loss=0.005690, IC=-0.0191

      epoch   6/100: train_loss=0.023948

      epoch   7/100: train_loss=0.017822

      epoch   8/100: train_loss=0.016247

      epoch   9/100: train_loss=0.015060

      epoch  10/100: train_loss=0.013354, val_loss=0.003114, IC=-0.0181

      epoch  11/100: train_loss=0.011992

      epoch  12/100: train_loss=0.011422

      epoch  13/100: train_loss=0.010062

      epoch  14/100: train_loss=0.008876

      epoch  15/100: train_loss=0.007906, val_loss=0.001835, IC=-0.0295

      epoch  16/100: train_loss=0.007035

      epoch  17/100: train_loss=0.007102

      epoch  18/100: train_loss=0.006452

      epoch  19/100: train_loss=0.005679

      epoch  20/100: train_loss=0.004663, val_loss=0.000892, IC=-0.0362

      epoch  21/100: train_loss=0.004603

      epoch  22/100: train_loss=0.004361

      epoch  23/100: train_loss=0.004066

      epoch  24/100: train_loss=0.003788

      epoch  25/100: train_loss=0.003187, val_loss=0.000689, IC=-0.0197

      epoch  26/100: train_loss=0.002761

      epoch  27/100: train_loss=0.002670

      epoch  28/100: train_loss=0.002417

      epoch  29/100: train_loss=0.002159

      epoch  30/100: train_loss=0.002212, val_loss=0.000366, IC=-0.0365

      epoch  31/100: train_loss=0.001994

      epoch  32/100: train_loss=0.001809

      epoch  33/100: train_loss=0.001657

      epoch  34/100: train_loss=0.001735

      epoch  35/100: train_loss=0.001424, val_loss=0.000237, IC=-0.0339

      epoch  36/100: train_loss=0.001254

      epoch  37/100: train_loss=0.001119

      epoch  38/100: train_loss=0.001059

      epoch  39/100: train_loss=0.000998

      epoch  40/100: train_loss=0.000924, val_loss=0.000146, IC=-0.0384

      epoch  41/100: train_loss=0.001217

      epoch  42/100: train_loss=0.000908

      epoch  43/100: train_loss=0.000878

      epoch  44/100: train_loss=0.000702

      epoch  45/100: train_loss=0.000654, val_loss=0.000113, IC=-0.0329

      epoch  46/100: train_loss=0.000638

      epoch  47/100: train_loss=0.000581

      epoch  48/100: train_loss=0.000592

      epoch  49/100: train_loss=0.000542

      epoch  50/100: train_loss=0.000502, val_loss=0.000094, IC=-0.0341

      epoch  51/100: train_loss=0.000503

      epoch  52/100: train_loss=0.000482

      epoch  53/100: train_loss=0.000424

      epoch  54/100: train_loss=0.000408

      epoch  55/100: train_loss=0.000391, val_loss=0.000065, IC=-0.0375

      epoch  56/100: train_loss=0.000466

      epoch  57/100: train_loss=0.000414

      epoch  58/100: train_loss=0.000346

      epoch  59/100: train_loss=0.000341

      epoch  60/100: train_loss=0.000326, val_loss=0.000055, IC=-0.0443

      epoch  61/100: train_loss=0.000323

      epoch  62/100: train_loss=0.000298

      epoch  63/100: train_loss=0.000293

      epoch  64/100: train_loss=0.000267

      epoch  65/100: train_loss=0.000260, val_loss=0.000050, IC=-0.0373

      epoch  66/100: train_loss=0.000256

      epoch  67/100: train_loss=0.000250

      epoch  68/100: train_loss=0.000252

      epoch  69/100: train_loss=0.000240

      epoch  70/100: train_loss=0.000259, val_loss=0.000047, IC=-0.0315

      epoch  71/100: train_loss=0.000229

      epoch  72/100: train_loss=0.000224

      epoch  73/100: train_loss=0.000250

      epoch  74/100: train_loss=0.000229

      epoch  75/100: train_loss=0.000216, val_loss=0.000043, IC=-0.0303

      epoch  76/100: train_loss=0.000207

      epoch  77/100: train_loss=0.000205

      epoch  78/100: train_loss=0.000197

      epoch  79/100: train_loss=0.000206

      epoch  80/100: train_loss=0.000196, val_loss=0.000041, IC=-0.0360

      epoch  81/100: train_loss=0.000193

      epoch  82/100: train_loss=0.000189

      epoch  83/100: train_loss=0.000196

      epoch  84/100: train_loss=0.000226

      epoch  85/100: train_loss=0.000190, val_loss=0.000039, IC=-0.0367

      epoch  86/100: train_loss=0.000199

      epoch  87/100: train_loss=0.000188

      epoch  88/100: train_loss=0.000179

      epoch  89/100: train_loss=0.000185

      epoch  90/100: train_loss=0.000223, val_loss=0.000039, IC=-0.0329

      epoch  91/100: train_loss=0.000182

      epoch  92/100: train_loss=0.000190

      epoch  93/100: train_loss=0.000182

      epoch  94/100: train_loss=0.000179

      epoch  95/100: train_loss=0.000186, val_loss=0.000038, IC=-0.0366

      epoch  96/100: train_loss=0.000172

      epoch  97/100: train_loss=0.000222

      epoch  98/100: train_loss=0.000203

      epoch  99/100: train_loss=0.000198

      epoch 100/100: train_loss=0.000174, val_loss=0.000038, IC=-0.0339

      best_ep=10, IC=-0.0181 (95.2s, 20 checkpoints)

  Fold 3: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.353841

      epoch   2/100: train_loss=0.086210

      epoch   3/100: train_loss=0.054831

      epoch   4/100: train_loss=0.038826

      epoch   5/100: train_loss=0.027429, val_loss=0.010556, IC=-0.0034

      epoch   6/100: train_loss=0.020367

      epoch   7/100: train_loss=0.021273

      epoch   8/100: train_loss=0.017651

      epoch   9/100: train_loss=0.012156

      epoch  10/100: train_loss=0.010274, val_loss=0.003054, IC=-0.0058

      epoch  11/100: train_loss=0.008968

      epoch  12/100: train_loss=0.007855

      epoch  13/100: train_loss=0.007835

      epoch  14/100: train_loss=0.006481

      epoch  15/100: train_loss=0.006375, val_loss=0.001848, IC=-0.0090

      epoch  16/100: train_loss=0.005645

      epoch  17/100: train_loss=0.005224

      epoch  18/100: train_loss=0.004349

      epoch  19/100: train_loss=0.003980

      epoch  20/100: train_loss=0.003798, val_loss=0.000941, IC=-0.0085

      epoch  21/100: train_loss=0.003496

      epoch  22/100: train_loss=0.003365

      epoch  23/100: train_loss=0.002942

      epoch  24/100: train_loss=0.002578

      epoch  25/100: train_loss=0.002273, val_loss=0.000574, IC=-0.0165

      epoch  26/100: train_loss=0.002254

      epoch  27/100: train_loss=0.002061

      epoch  28/100: train_loss=0.001912

      epoch  29/100: train_loss=0.001730

      epoch  30/100: train_loss=0.001488, val_loss=0.000363, IC=-0.0135

      epoch  31/100: train_loss=0.001391

      epoch  32/100: train_loss=0.001320

      epoch  33/100: train_loss=0.001185

      epoch  34/100: train_loss=0.001176

      epoch  35/100: train_loss=0.001082, val_loss=0.000242, IC=-0.0239

      epoch  36/100: train_loss=0.001051

      epoch  37/100: train_loss=0.001039

      epoch  38/100: train_loss=0.001052

      epoch  39/100: train_loss=0.000864

      epoch  40/100: train_loss=0.000765, val_loss=0.000152, IC=-0.0267

      epoch  41/100: train_loss=0.000720

      epoch  42/100: train_loss=0.000677

      epoch  43/100: train_loss=0.000652

      epoch  44/100: train_loss=0.000635

      epoch  45/100: train_loss=0.000567, val_loss=0.000114, IC=-0.0250

      epoch  46/100: train_loss=0.000550

      epoch  47/100: train_loss=0.000576

      epoch  48/100: train_loss=0.000510

      epoch  49/100: train_loss=0.000475

      epoch  50/100: train_loss=0.000458, val_loss=0.000090, IC=-0.0300

      epoch  51/100: train_loss=0.000433

      epoch  52/100: train_loss=0.000489

      epoch  53/100: train_loss=0.000494

      epoch  54/100: train_loss=0.000389

      epoch  55/100: train_loss=0.000373, val_loss=0.000077, IC=-0.0356

      epoch  56/100: train_loss=0.000357

      epoch  57/100: train_loss=0.000343

      epoch  58/100: train_loss=0.000359

      epoch  59/100: train_loss=0.000308

      epoch  60/100: train_loss=0.000343, val_loss=0.000063, IC=-0.0357

      epoch  61/100: train_loss=0.000335

      epoch  62/100: train_loss=0.000289

      epoch  63/100: train_loss=0.000276

      epoch  64/100: train_loss=0.000277

      epoch  65/100: train_loss=0.000307, val_loss=0.000055, IC=-0.0422

      epoch  66/100: train_loss=0.000253

      epoch  67/100: train_loss=0.000260

      epoch  68/100: train_loss=0.000292

      epoch  69/100: train_loss=0.000241

      epoch  70/100: train_loss=0.000233, val_loss=0.000052, IC=-0.0357

      epoch  71/100: train_loss=0.000240

      epoch  72/100: train_loss=0.000243

      epoch  73/100: train_loss=0.000231

      epoch  74/100: train_loss=0.000220

      epoch  75/100: train_loss=0.000234, val_loss=0.000047, IC=-0.0339

      epoch  76/100: train_loss=0.000242

      epoch  77/100: train_loss=0.000240

      epoch  78/100: train_loss=0.000214

      epoch  79/100: train_loss=0.000217

      epoch  80/100: train_loss=0.000210, val_loss=0.000047, IC=-0.0423

      epoch  81/100: train_loss=0.000203

      epoch  82/100: train_loss=0.000193

      epoch  83/100: train_loss=0.000208

      epoch  84/100: train_loss=0.000198

      epoch  85/100: train_loss=0.000200, val_loss=0.000044, IC=-0.0361

      epoch  86/100: train_loss=0.000202

      epoch  87/100: train_loss=0.000198

      epoch  88/100: train_loss=0.000197

      epoch  89/100: train_loss=0.000199

      epoch  90/100: train_loss=0.000192, val_loss=0.000043, IC=-0.0361

      epoch  91/100: train_loss=0.000204

      epoch  92/100: train_loss=0.000184

      epoch  93/100: train_loss=0.000185

      epoch  94/100: train_loss=0.000197

      epoch  95/100: train_loss=0.000187, val_loss=0.000043, IC=-0.0357

      epoch  96/100: train_loss=0.000194

      epoch  97/100: train_loss=0.000194

      epoch  98/100: train_loss=0.000189

      epoch  99/100: train_loss=0.000196

      epoch 100/100: train_loss=0.000191, val_loss=0.000043, IC=-0.0368

      best_ep=5, IC=-0.0034 (98.1s, 20 checkpoints)

  Fold 4: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.256817

      epoch   2/100: train_loss=0.116786

      epoch   3/100: train_loss=0.068386

      epoch   4/100: train_loss=0.046247

      epoch   5/100: train_loss=0.037071, val_loss=0.017971, IC=-0.0244

      epoch   6/100: train_loss=0.028014

      epoch   7/100: train_loss=0.026377

      epoch   8/100: train_loss=0.025769

      epoch   9/100: train_loss=0.016670

      epoch  10/100: train_loss=0.014355, val_loss=0.006776, IC=-0.0123

      epoch  11/100: train_loss=0.012382

      epoch  12/100: train_loss=0.010438

      epoch  13/100: train_loss=0.011672

      epoch  14/100: train_loss=0.008412

      epoch  15/100: train_loss=0.007575, val_loss=0.003148, IC=-0.0104

      epoch  16/100: train_loss=0.006606

      epoch  17/100: train_loss=0.006138

      epoch  18/100: train_loss=0.005115

      epoch  19/100: train_loss=0.004898

      epoch  20/100: train_loss=0.004413, val_loss=0.001351, IC=-0.0073

      epoch  21/100: train_loss=0.003821

      epoch  22/100: train_loss=0.003841

      epoch  23/100: train_loss=0.003260

      epoch  24/100: train_loss=0.003367

      epoch  25/100: train_loss=0.002589, val_loss=0.000754, IC=+0.0026

      epoch  26/100: train_loss=0.002429

      epoch  27/100: train_loss=0.002109

      epoch  28/100: train_loss=0.002003

      epoch  29/100: train_loss=0.001812

      epoch  30/100: train_loss=0.001653, val_loss=0.000400, IC=-0.0109

      epoch  31/100: train_loss=0.001439

      epoch  32/100: train_loss=0.001311

      epoch  33/100: train_loss=0.001190

      epoch  34/100: train_loss=0.001077

      epoch  35/100: train_loss=0.001045, val_loss=0.000240, IC=-0.0053

      epoch  36/100: train_loss=0.000910

      epoch  37/100: train_loss=0.000882

      epoch  38/100: train_loss=0.000781

      epoch  39/100: train_loss=0.000820

      epoch  40/100: train_loss=0.000704, val_loss=0.000204, IC=+0.0031

      epoch  41/100: train_loss=0.000642

      epoch  42/100: train_loss=0.000601

      epoch  43/100: train_loss=0.000562

      epoch  44/100: train_loss=0.000507

      epoch  45/100: train_loss=0.000489, val_loss=0.000136, IC=+0.0012

      epoch  46/100: train_loss=0.000450

      epoch  47/100: train_loss=0.000429

      epoch  48/100: train_loss=0.000399

      epoch  49/100: train_loss=0.000435

      epoch  50/100: train_loss=0.000408, val_loss=0.000126, IC=+0.0107

      epoch  51/100: train_loss=0.000338

      epoch  52/100: train_loss=0.000303

      epoch  53/100: train_loss=0.000283

      epoch  54/100: train_loss=0.000282

      epoch  55/100: train_loss=0.000266, val_loss=0.000094, IC=+0.0071

      epoch  56/100: train_loss=0.000243

      epoch  57/100: train_loss=0.000257

      epoch  58/100: train_loss=0.000241

      epoch  59/100: train_loss=0.000224

      epoch  60/100: train_loss=0.000205, val_loss=0.000081, IC=+0.0059

      epoch  61/100: train_loss=0.000224

      epoch  62/100: train_loss=0.000193

      epoch  63/100: train_loss=0.000190

      epoch  64/100: train_loss=0.000176

      epoch  65/100: train_loss=0.000173, val_loss=0.000075, IC=+0.0037

      epoch  66/100: train_loss=0.000165

      epoch  67/100: train_loss=0.000167

      epoch  68/100: train_loss=0.000160

      epoch  69/100: train_loss=0.000163

      epoch  70/100: train_loss=0.000192, val_loss=0.000068, IC=-0.0015

      epoch  71/100: train_loss=0.000156

      epoch  72/100: train_loss=0.000153

      epoch  73/100: train_loss=0.000140

      epoch  74/100: train_loss=0.000216

      epoch  75/100: train_loss=0.000163, val_loss=0.000062, IC=-0.0015

      epoch  76/100: train_loss=0.000143

      epoch  77/100: train_loss=0.000139

      epoch  78/100: train_loss=0.000134

      epoch  79/100: train_loss=0.000132

      epoch  80/100: train_loss=0.000137, val_loss=0.000065, IC=-0.0024

      epoch  81/100: train_loss=0.000123

      epoch  82/100: train_loss=0.000136

      epoch  83/100: train_loss=0.000124

      epoch  84/100: train_loss=0.000126

      epoch  85/100: train_loss=0.000123, val_loss=0.000062, IC=+0.0038

      epoch  86/100: train_loss=0.000133

      epoch  87/100: train_loss=0.000125

      epoch  88/100: train_loss=0.000124

      epoch  89/100: train_loss=0.000118

      epoch  90/100: train_loss=0.000118, val_loss=0.000060, IC=+0.0017

      epoch  91/100: train_loss=0.000122

      epoch  92/100: train_loss=0.000121

      epoch  93/100: train_loss=0.000119

      epoch  94/100: train_loss=0.000117

      epoch  95/100: train_loss=0.000120, val_loss=0.000060, IC=+0.0017

      epoch  96/100: train_loss=0.000124

      epoch  97/100: train_loss=0.000117

      epoch  98/100: train_loss=0.000140

      epoch  99/100: train_loss=0.000118

      epoch 100/100: train_loss=0.000153, val_loss=0.000060, IC=+0.0023

      best_ep=50, IC=+0.0107 (110.8s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.252457

      epoch   2/100: train_loss=0.287148

      epoch   3/100: train_loss=0.080949

      epoch   4/100: train_loss=0.044161

      epoch   5/100: train_loss=0.031530, val_loss=0.011992, IC=-0.0179

      epoch   6/100: train_loss=0.023670

      epoch   7/100: train_loss=0.021339

      epoch   8/100: train_loss=0.017844

      epoch   9/100: train_loss=0.016033

      epoch  10/100: train_loss=0.012300, val_loss=0.003046, IC=-0.0389

      epoch  11/100: train_loss=0.011275

      epoch  12/100: train_loss=0.010198

      epoch  13/100: train_loss=0.014136

      epoch  14/100: train_loss=0.007768

      epoch  15/100: train_loss=0.006876, val_loss=0.001846, IC=-0.0395

      epoch  16/100: train_loss=0.006990

      epoch  17/100: train_loss=0.005359

      epoch  18/100: train_loss=0.005186

      epoch  19/100: train_loss=0.004494

      epoch  20/100: train_loss=0.003980, val_loss=0.000858, IC=-0.0271

      epoch  21/100: train_loss=0.003511

      epoch  22/100: train_loss=0.003487

      epoch  23/100: train_loss=0.004175

      epoch  24/100: train_loss=0.003034

      epoch  25/100: train_loss=0.002417, val_loss=0.000469, IC=-0.0311

      epoch  26/100: train_loss=0.002343

      epoch  27/100: train_loss=0.002189

      epoch  28/100: train_loss=0.004853

      epoch  29/100: train_loss=0.001894

      epoch  30/100: train_loss=0.001670, val_loss=0.000237, IC=-0.0139

      epoch  31/100: train_loss=0.001810

      epoch  32/100: train_loss=0.001541

      epoch  33/100: train_loss=0.001550

      epoch  34/100: train_loss=0.001114

      epoch  35/100: train_loss=0.001034, val_loss=0.000181, IC=-0.0244

      epoch  36/100: train_loss=0.000955

      epoch  37/100: train_loss=0.000871

      epoch  38/100: train_loss=0.000930

      epoch  39/100: train_loss=0.000844

      epoch  40/100: train_loss=0.000744, val_loss=0.000102, IC=-0.0361

      epoch  41/100: train_loss=0.000688

      epoch  42/100: train_loss=0.000607

      epoch  43/100: train_loss=0.000596

      epoch  44/100: train_loss=0.000535

      epoch  45/100: train_loss=0.000618, val_loss=0.000098, IC=-0.0202

      epoch  46/100: train_loss=0.000582

      epoch  47/100: train_loss=0.000471

      epoch  48/100: train_loss=0.000439

      epoch  49/100: train_loss=0.000403

      epoch  50/100: train_loss=0.000387, val_loss=0.000064, IC=-0.0202

      epoch  51/100: train_loss=0.000371

      epoch  52/100: train_loss=0.000350

      epoch  53/100: train_loss=0.000317

      epoch  54/100: train_loss=0.000307

      epoch  55/100: train_loss=0.000352, val_loss=0.000049, IC=-0.0178

      epoch  56/100: train_loss=0.000300

      epoch  57/100: train_loss=0.000282

      epoch  58/100: train_loss=0.000256

      epoch  59/100: train_loss=0.000268

      epoch  60/100: train_loss=0.000241, val_loss=0.000046, IC=-0.0270

      epoch  61/100: train_loss=0.000269

      epoch  62/100: train_loss=0.000234

      epoch  63/100: train_loss=0.000242

      epoch  64/100: train_loss=0.000214

      epoch  65/100: train_loss=0.000210, val_loss=0.000042, IC=-0.0126

      epoch  66/100: train_loss=0.000204

      epoch  67/100: train_loss=0.000192

      epoch  68/100: train_loss=0.000203

      epoch  69/100: train_loss=0.000175

      epoch  70/100: train_loss=0.000186, val_loss=0.000038, IC=-0.0083

      epoch  71/100: train_loss=0.000169

      epoch  72/100: train_loss=0.000176

      epoch  73/100: train_loss=0.000164

      epoch  74/100: train_loss=0.000164

      epoch  75/100: train_loss=0.000155, val_loss=0.000035, IC=-0.0109

      epoch  76/100: train_loss=0.000188

      epoch  77/100: train_loss=0.000159

      epoch  78/100: train_loss=0.000154

      epoch  79/100: train_loss=0.000157

      epoch  80/100: train_loss=0.000153, val_loss=0.000035, IC=-0.0067

      epoch  81/100: train_loss=0.000140

      epoch  82/100: train_loss=0.000153

      epoch  83/100: train_loss=0.000144

      epoch  84/100: train_loss=0.000155

      epoch  85/100: train_loss=0.000154, val_loss=0.000032, IC=-0.0170

      epoch  86/100: train_loss=0.000153

      epoch  87/100: train_loss=0.000151

      epoch  88/100: train_loss=0.000134

      epoch  89/100: train_loss=0.000176

      epoch  90/100: train_loss=0.000136, val_loss=0.000032, IC=-0.0164

      epoch  91/100: train_loss=0.000138

      epoch  92/100: train_loss=0.000146

      epoch  93/100: train_loss=0.000139

      epoch  94/100: train_loss=0.000207

      epoch  95/100: train_loss=0.000146, val_loss=0.000032, IC=-0.0099

      epoch  96/100: train_loss=0.000133

      epoch  97/100: train_loss=0.000137

      epoch  98/100: train_loss=0.000148

      epoch  99/100: train_loss=0.000144

      epoch 100/100: train_loss=0.000142, val_loss=0.000032, IC=-0.0091

      best_ep=80, IC=-0.0067 (106.6s, 20 checkpoints)

  Fold 6: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.139661

      epoch   2/100: train_loss=0.077519

      epoch   3/100: train_loss=0.054252

      epoch   4/100: train_loss=0.038425

      epoch   5/100: train_loss=0.028292, val_loss=0.012392, IC=+0.0260

      epoch   6/100: train_loss=0.023597

      epoch   7/100: train_loss=0.017332

      epoch   8/100: train_loss=0.014753

      epoch   9/100: train_loss=0.011544

      epoch  10/100: train_loss=0.009565, val_loss=0.004969, IC=+0.0336

      epoch  11/100: train_loss=0.008635

      epoch  12/100: train_loss=0.006802

      epoch  13/100: train_loss=0.006059

      epoch  14/100: train_loss=0.005269

      epoch  15/100: train_loss=0.004840, val_loss=0.001920, IC=+0.0260

      epoch  16/100: train_loss=0.004046

      epoch  17/100: train_loss=0.003559

      epoch  18/100: train_loss=0.003153

      epoch  19/100: train_loss=0.002819

      epoch  20/100: train_loss=0.002483, val_loss=0.001051, IC=+0.0190

      epoch  21/100: train_loss=0.002344

      epoch  22/100: train_loss=0.002057

      epoch  23/100: train_loss=0.001822

      epoch  24/100: train_loss=0.001645

      epoch  25/100: train_loss=0.001691, val_loss=0.000589, IC=+0.0417

      epoch  26/100: train_loss=0.001532

      epoch  27/100: train_loss=0.001276

      epoch  28/100: train_loss=0.001013

      epoch  29/100: train_loss=0.001189

      epoch  30/100: train_loss=0.000967, val_loss=0.000502, IC=-0.0330

      epoch  31/100: train_loss=0.000802

      epoch  32/100: train_loss=0.000618

      epoch  33/100: train_loss=0.000560

      epoch  34/100: train_loss=0.000493

      epoch  35/100: train_loss=0.000438, val_loss=0.000220, IC=+0.0354

      epoch  36/100: train_loss=0.000398

      epoch  37/100: train_loss=0.000381

      epoch  38/100: train_loss=0.000333

      epoch  39/100: train_loss=0.000307

      epoch  40/100: train_loss=0.000275, val_loss=0.000124, IC=+0.0035

      epoch  41/100: train_loss=0.000270

      epoch  42/100: train_loss=0.000232

      epoch  43/100: train_loss=0.000276

      epoch  44/100: train_loss=0.000217

      epoch  45/100: train_loss=0.000187, val_loss=0.000080, IC=-0.0012

      epoch  46/100: train_loss=0.000165

      epoch  47/100: train_loss=0.000162

      epoch  48/100: train_loss=0.000149

      epoch  49/100: train_loss=0.000137

      epoch  50/100: train_loss=0.000147, val_loss=0.000073, IC=-0.0236

      epoch  51/100: train_loss=0.000158

      epoch  52/100: train_loss=0.000128

      epoch  53/100: train_loss=0.000103

      epoch  54/100: train_loss=0.000112

      epoch  55/100: train_loss=0.000090, val_loss=0.000065, IC=+0.0182

      epoch  56/100: train_loss=0.000087

      epoch  57/100: train_loss=0.000080

      epoch  58/100: train_loss=0.000085

      epoch  59/100: train_loss=0.000075

      epoch  60/100: train_loss=0.000073, val_loss=0.000055, IC=+0.0088

      epoch  61/100: train_loss=0.000085

      epoch  62/100: train_loss=0.000065

      epoch  63/100: train_loss=0.000064

      epoch  64/100: train_loss=0.000061

      epoch  65/100: train_loss=0.000064, val_loss=0.000053, IC=+0.0095

      epoch  66/100: train_loss=0.000059

      epoch  67/100: train_loss=0.000056

      epoch  68/100: train_loss=0.000056

      epoch  69/100: train_loss=0.000053

      epoch  70/100: train_loss=0.000051, val_loss=0.000053, IC=+0.0060

      epoch  71/100: train_loss=0.000050

      epoch  72/100: train_loss=0.000051

      epoch  73/100: train_loss=0.000048

      epoch  74/100: train_loss=0.000052

      epoch  75/100: train_loss=0.000049, val_loss=0.000052, IC=-0.0204

      epoch  76/100: train_loss=0.000052

      epoch  77/100: train_loss=0.000048

      epoch  78/100: train_loss=0.000047

      epoch  79/100: train_loss=0.000047

      epoch  80/100: train_loss=0.000045, val_loss=0.000050, IC=+0.0049

      epoch  81/100: train_loss=0.000052

      epoch  82/100: train_loss=0.000045

      epoch  83/100: train_loss=0.000051

      epoch  84/100: train_loss=0.000047

      epoch  85/100: train_loss=0.000049, val_loss=0.000049, IC=+0.0006

      epoch  86/100: train_loss=0.000043

      epoch  87/100: train_loss=0.000048

      epoch  88/100: train_loss=0.000044

      epoch  89/100: train_loss=0.000049

      epoch  90/100: train_loss=0.000043, val_loss=0.000050, IC=-0.0055

      epoch  91/100: train_loss=0.000046

      epoch  92/100: train_loss=0.000045

      epoch  93/100: train_loss=0.000046

      epoch  94/100: train_loss=0.000042

      epoch  95/100: train_loss=0.000042, val_loss=0.000050, IC=-0.0107

      epoch  96/100: train_loss=0.000044

      epoch  97/100: train_loss=0.000044

      epoch  98/100: train_loss=0.000042

      epoch  99/100: train_loss=0.000041

      epoch 100/100: train_loss=0.000042, val_loss=0.000050, IC=-0.0078

      best_ep=25, IC=+0.0417 (105.8s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,140 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.232360

      epoch   2/100: train_loss=0.071876

      epoch   3/100: train_loss=0.043311

      epoch   4/100: train_loss=0.030538

      epoch   5/100: train_loss=0.023540, val_loss=0.006512, IC=+0.0281

      epoch   6/100: train_loss=0.019197

      epoch   7/100: train_loss=0.015799

      epoch   8/100: train_loss=0.013568

      epoch   9/100: train_loss=0.012010

      epoch  10/100: train_loss=0.013077, val_loss=0.002202, IC=+0.0150

      epoch  11/100: train_loss=0.008863

      epoch  12/100: train_loss=0.010483

      epoch  13/100: train_loss=0.006965

      epoch  14/100: train_loss=0.006195

      epoch  15/100: train_loss=0.005531, val_loss=0.001170, IC=-0.0047

      epoch  16/100: train_loss=0.005198

      epoch  17/100: train_loss=0.004400

      epoch  18/100: train_loss=0.004506

      epoch  19/100: train_loss=0.003668

      epoch  20/100: train_loss=0.003374, val_loss=0.000584, IC=+0.0058

      epoch  21/100: train_loss=0.003002

      epoch  22/100: train_loss=0.002975

      epoch  23/100: train_loss=0.002833

      epoch  24/100: train_loss=0.002354

      epoch  25/100: train_loss=0.001936, val_loss=0.000496, IC=-0.0241

      epoch  26/100: train_loss=0.001814

      epoch  27/100: train_loss=0.001715

      epoch  28/100: train_loss=0.001457

      epoch  29/100: train_loss=0.001463

      epoch  30/100: train_loss=0.001336, val_loss=0.000271, IC=-0.0143

      epoch  31/100: train_loss=0.001049

      epoch  32/100: train_loss=0.000980

      epoch  33/100: train_loss=0.000923

      epoch  34/100: train_loss=0.000813

      epoch  35/100: train_loss=0.000842, val_loss=0.000122, IC=-0.0065

      epoch  36/100: train_loss=0.000694

      epoch  37/100: train_loss=0.000638

      epoch  38/100: train_loss=0.000540

      epoch  39/100: train_loss=0.000605

      epoch  40/100: train_loss=0.000508, val_loss=0.000083, IC=-0.0150

      epoch  41/100: train_loss=0.000409

      epoch  42/100: train_loss=0.000384

      epoch  43/100: train_loss=0.000412

      epoch  44/100: train_loss=0.000386

      epoch  45/100: train_loss=0.000319, val_loss=0.000067, IC=+0.0043

      epoch  46/100: train_loss=0.000304

      epoch  47/100: train_loss=0.000297

      epoch  48/100: train_loss=0.000249

      epoch  49/100: train_loss=0.000233

      epoch  50/100: train_loss=0.000254, val_loss=0.000048, IC=+0.0056

      epoch  51/100: train_loss=0.000206

      epoch  52/100: train_loss=0.000203

      epoch  53/100: train_loss=0.000205

      epoch  54/100: train_loss=0.000178

      epoch  55/100: train_loss=0.000171, val_loss=0.000045, IC=-0.0147

      epoch  56/100: train_loss=0.000172

      epoch  57/100: train_loss=0.000153

      epoch  58/100: train_loss=0.000143

      epoch  59/100: train_loss=0.000155

      epoch  60/100: train_loss=0.000134, val_loss=0.000042, IC=+0.0055

      epoch  61/100: train_loss=0.000130

      epoch  62/100: train_loss=0.000128

      epoch  63/100: train_loss=0.000118

      epoch  64/100: train_loss=0.000108

      epoch  65/100: train_loss=0.000107, val_loss=0.000037, IC=-0.0032

      epoch  66/100: train_loss=0.000101

      epoch  67/100: train_loss=0.000099

      epoch  68/100: train_loss=0.000096

      epoch  69/100: train_loss=0.000100

      epoch  70/100: train_loss=0.000094, val_loss=0.000038, IC=+0.0024

      epoch  71/100: train_loss=0.000093

      epoch  72/100: train_loss=0.000091

      epoch  73/100: train_loss=0.000094

      epoch  74/100: train_loss=0.000083

      epoch  75/100: train_loss=0.000088, val_loss=0.000034, IC=+0.0031

      epoch  76/100: train_loss=0.000079

      epoch  77/100: train_loss=0.000096

      epoch  78/100: train_loss=0.000094

      epoch  79/100: train_loss=0.000077

      epoch  80/100: train_loss=0.000080, val_loss=0.000034, IC=+0.0106

      epoch  81/100: train_loss=0.000072

      epoch  82/100: train_loss=0.000080

      epoch  83/100: train_loss=0.000074

      epoch  84/100: train_loss=0.000073

      epoch  85/100: train_loss=0.000072, val_loss=0.000033, IC=+0.0026

      epoch  86/100: train_loss=0.000072

      epoch  87/100: train_loss=0.000072

      epoch  88/100: train_loss=0.000069

      epoch  89/100: train_loss=0.000073

      epoch  90/100: train_loss=0.000074, val_loss=0.000033, IC=-0.0009

      epoch  91/100: train_loss=0.000077

      epoch  92/100: train_loss=0.000071

      epoch  93/100: train_loss=0.000069

      epoch  94/100: train_loss=0.000076

      epoch  95/100: train_loss=0.000073, val_loss=0.000033, IC=-0.0005

      epoch  96/100: train_loss=0.000073

      epoch  97/100: train_loss=0.000075

      epoch  98/100: train_loss=0.000072

      epoch  99/100: train_loss=0.000073

      epoch 100/100: train_loss=0.000071, val_loss=0.000033, IC=+0.0004

      best_ep=5, IC=+0.0281 (93.0s, 20 checkpoints)

  nlinear: best_epoch=5, IC=-0.0053 (761.0s)

  Best: nlinear @ epoch 5 (IC=-0.0053)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/e819153914a7/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=16,980 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.670242

      epoch   2/100: train_loss=0.402774

      epoch   3/100: train_loss=0.222682

      epoch   4/100: train_loss=0.117101

      epoch   5/100: train_loss=0.064095, val_loss=0.058121, IC=-0.0506

      epoch   6/100: train_loss=0.043050

      epoch   7/100: train_loss=0.032670

      epoch   8/100: train_loss=0.025911

      epoch   9/100: train_loss=0.021539

      epoch  10/100: train_loss=0.018619, val_loss=0.015846, IC=-0.0388

      epoch  11/100: train_loss=0.016927

      epoch  12/100: train_loss=0.015464

      epoch  13/100: train_loss=0.014411

      epoch  14/100: train_loss=0.013037

      epoch  15/100: train_loss=0.012034, val_loss=0.005812, IC=-0.0045

      epoch  16/100: train_loss=0.011335

      epoch  17/100: train_loss=0.011049

      epoch  18/100: train_loss=0.010104

      epoch  19/100: train_loss=0.009791

      epoch  20/100: train_loss=0.009148, val_loss=0.002890, IC=+0.0170

      epoch  21/100: train_loss=0.008532

      epoch  22/100: train_loss=0.008000

      epoch  23/100: train_loss=0.007687

      epoch  24/100: train_loss=0.007144

      epoch  25/100: train_loss=0.006812, val_loss=0.001535, IC=+0.0305

      epoch  26/100: train_loss=0.006358

      epoch  27/100: train_loss=0.005988

      epoch  28/100: train_loss=0.005639

      epoch  29/100: train_loss=0.005504

      epoch  30/100: train_loss=0.005043, val_loss=0.001083, IC=+0.0372

      epoch  31/100: train_loss=0.004661

      epoch  32/100: train_loss=0.004744

      epoch  33/100: train_loss=0.004261

      epoch  34/100: train_loss=0.003930

      epoch  35/100: train_loss=0.003974, val_loss=0.000844, IC=+0.0407

      epoch  36/100: train_loss=0.003734

      epoch  37/100: train_loss=0.003537

      epoch  38/100: train_loss=0.003330

      epoch  39/100: train_loss=0.003227

      epoch  40/100: train_loss=0.002963, val_loss=0.000687, IC=+0.0433

      epoch  41/100: train_loss=0.002866

      epoch  42/100: train_loss=0.002733

      epoch  43/100: train_loss=0.002636

      epoch  44/100: train_loss=0.002494

      epoch  45/100: train_loss=0.002498, val_loss=0.000588, IC=+0.0539

      epoch  46/100: train_loss=0.002286

      epoch  47/100: train_loss=0.002237

      epoch  48/100: train_loss=0.002161

      epoch  49/100: train_loss=0.002049

      epoch  50/100: train_loss=0.001971, val_loss=0.000517, IC=+0.0591

      epoch  51/100: train_loss=0.001939

      epoch  52/100: train_loss=0.001870

      epoch  53/100: train_loss=0.001766

      epoch  54/100: train_loss=0.001739

      epoch  55/100: train_loss=0.001633, val_loss=0.000480, IC=+0.0647

      epoch  56/100: train_loss=0.001664

      epoch  57/100: train_loss=0.001612

      epoch  58/100: train_loss=0.001542

      epoch  59/100: train_loss=0.001494

      epoch  60/100: train_loss=0.001418, val_loss=0.000437, IC=+0.0671

      epoch  61/100: train_loss=0.001402

      epoch  62/100: train_loss=0.001364

      epoch  63/100: train_loss=0.001340

      epoch  64/100: train_loss=0.001308

      epoch  65/100: train_loss=0.001272, val_loss=0.000419, IC=+0.0694

      epoch  66/100: train_loss=0.001273

      epoch  67/100: train_loss=0.001251

      epoch  68/100: train_loss=0.001219

      epoch  69/100: train_loss=0.001159

      epoch  70/100: train_loss=0.001156, val_loss=0.000402, IC=+0.0714

      epoch  71/100: train_loss=0.001122

      epoch  72/100: train_loss=0.001118

      epoch  73/100: train_loss=0.001096

      epoch  74/100: train_loss=0.001078

      epoch  75/100: train_loss=0.001092, val_loss=0.000394, IC=+0.0709

      epoch  76/100: train_loss=0.001091

      epoch  77/100: train_loss=0.001035

      epoch  78/100: train_loss=0.001060

      epoch  79/100: train_loss=0.001035

      epoch  80/100: train_loss=0.001012, val_loss=0.000390, IC=+0.0744

      epoch  81/100: train_loss=0.000981

      epoch  82/100: train_loss=0.001016

      epoch  83/100: train_loss=0.000977

      epoch  84/100: train_loss=0.000970

      epoch  85/100: train_loss=0.000973, val_loss=0.000383, IC=+0.0714

      epoch  86/100: train_loss=0.000981

      epoch  87/100: train_loss=0.000962

      epoch  88/100: train_loss=0.001016

      epoch  89/100: train_loss=0.001009

      epoch  90/100: train_loss=0.001001, val_loss=0.000381, IC=+0.0717

      epoch  91/100: train_loss=0.000976

      epoch  92/100: train_loss=0.001002

      epoch  93/100: train_loss=0.000948

      epoch  94/100: train_loss=0.000978

      epoch  95/100: train_loss=0.000941, val_loss=0.000379, IC=+0.0720

      epoch  96/100: train_loss=0.000976

      epoch  97/100: train_loss=0.000983

      epoch  98/100: train_loss=0.001005

      epoch  99/100: train_loss=0.000973

      epoch 100/100: train_loss=0.000936, val_loss=0.000378, IC=+0.0724

      best_ep=80, IC=+0.0744 (64.8s, 20 checkpoints)

  Fold 1: creating sequences...

    train=22,140 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.269037

      epoch   2/100: train_loss=0.131241

      epoch   3/100: train_loss=0.085516

      epoch   4/100: train_loss=0.056724

      epoch   5/100: train_loss=0.039661, val_loss=0.016811, IC=+0.0286

      epoch   6/100: train_loss=0.029444

      epoch   7/100: train_loss=0.023321

      epoch   8/100: train_loss=0.018653

      epoch   9/100: train_loss=0.015819

      epoch  10/100: train_loss=0.013801, val_loss=0.004536, IC=-0.0222

      epoch  11/100: train_loss=0.012021

      epoch  12/100: train_loss=0.010619

      epoch  13/100: train_loss=0.009523

      epoch  14/100: train_loss=0.008203

      epoch  15/100: train_loss=0.007616, val_loss=0.002154, IC=-0.0489

      epoch  16/100: train_loss=0.006919

      epoch  17/100: train_loss=0.006098

      epoch  18/100: train_loss=0.005410

      epoch  19/100: train_loss=0.004960

      epoch  20/100: train_loss=0.004461, val_loss=0.001134, IC=-0.0448

      epoch  21/100: train_loss=0.004077

      epoch  22/100: train_loss=0.003607

      epoch  23/100: train_loss=0.003278

      epoch  24/100: train_loss=0.002931

      epoch  25/100: train_loss=0.002703, val_loss=0.000672, IC=-0.0374

      epoch  26/100: train_loss=0.002429

      epoch  27/100: train_loss=0.002196

      epoch  28/100: train_loss=0.002033

      epoch  29/100: train_loss=0.001831

      epoch  30/100: train_loss=0.001717, val_loss=0.000422, IC=-0.0405

      epoch  31/100: train_loss=0.001588

      epoch  32/100: train_loss=0.001447

      epoch  33/100: train_loss=0.001312

      epoch  34/100: train_loss=0.001238

      epoch  35/100: train_loss=0.001132, val_loss=0.000295, IC=-0.0612

      epoch  36/100: train_loss=0.001037

      epoch  37/100: train_loss=0.000986

      epoch  38/100: train_loss=0.000932

      epoch  39/100: train_loss=0.000877

      epoch  40/100: train_loss=0.000812, val_loss=0.000224, IC=-0.0591

      epoch  41/100: train_loss=0.000753

      epoch  42/100: train_loss=0.000728

      epoch  43/100: train_loss=0.000686

      epoch  44/100: train_loss=0.000641

      epoch  45/100: train_loss=0.000636, val_loss=0.000189, IC=-0.0460

      epoch  46/100: train_loss=0.000605

      epoch  47/100: train_loss=0.000576

      epoch  48/100: train_loss=0.000546

      epoch  49/100: train_loss=0.000528

      epoch  50/100: train_loss=0.000505, val_loss=0.000168, IC=-0.0501

      epoch  51/100: train_loss=0.000492

      epoch  52/100: train_loss=0.000473

      epoch  53/100: train_loss=0.000457

      epoch  54/100: train_loss=0.000446

      epoch  55/100: train_loss=0.000430, val_loss=0.000154, IC=-0.0554

      epoch  56/100: train_loss=0.000426

      epoch  57/100: train_loss=0.000405

      epoch  58/100: train_loss=0.000404

      epoch  59/100: train_loss=0.000393

      epoch  60/100: train_loss=0.000381, val_loss=0.000147, IC=-0.0673

      epoch  61/100: train_loss=0.000374

      epoch  62/100: train_loss=0.000373

      epoch  63/100: train_loss=0.000364

      epoch  64/100: train_loss=0.000356

      epoch  65/100: train_loss=0.000350, val_loss=0.000144, IC=-0.0803

      epoch  66/100: train_loss=0.000351

      epoch  67/100: train_loss=0.000347

      epoch  68/100: train_loss=0.000343

      epoch  69/100: train_loss=0.000338

      epoch  70/100: train_loss=0.000334, val_loss=0.000139, IC=-0.0758

      epoch  71/100: train_loss=0.000329

      epoch  72/100: train_loss=0.000329

      epoch  73/100: train_loss=0.000324

      epoch  74/100: train_loss=0.000320

      epoch  75/100: train_loss=0.000320, val_loss=0.000137, IC=-0.0745

      epoch  76/100: train_loss=0.000319

      epoch  77/100: train_loss=0.000317

      epoch  78/100: train_loss=0.000314

      epoch  79/100: train_loss=0.000312

      epoch  80/100: train_loss=0.000311, val_loss=0.000136, IC=-0.0783

      epoch  81/100: train_loss=0.000312

      epoch  82/100: train_loss=0.000307

      epoch  83/100: train_loss=0.000306

      epoch  84/100: train_loss=0.000309

      epoch  85/100: train_loss=0.000304, val_loss=0.000136, IC=-0.0845

      epoch  86/100: train_loss=0.000304

      epoch  87/100: train_loss=0.000300

      epoch  88/100: train_loss=0.000303

      epoch  89/100: train_loss=0.000306

      epoch  90/100: train_loss=0.000305, val_loss=0.000135, IC=-0.0787

      epoch  91/100: train_loss=0.000300

      epoch  92/100: train_loss=0.000302

      epoch  93/100: train_loss=0.000299

      epoch  94/100: train_loss=0.000308

      epoch  95/100: train_loss=0.000306, val_loss=0.000135, IC=-0.0830

      epoch  96/100: train_loss=0.000303

      epoch  97/100: train_loss=0.000300

      epoch  98/100: train_loss=0.000300

      epoch  99/100: train_loss=0.000302

      epoch 100/100: train_loss=0.000301, val_loss=0.000135, IC=-0.0831

      best_ep=5, IC=+0.0286 (89.6s, 20 checkpoints)

  Fold 2: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.186495

      epoch   2/100: train_loss=0.074689

      epoch   3/100: train_loss=0.046120

      epoch   4/100: train_loss=0.031770

      epoch   5/100: train_loss=0.025224, val_loss=0.006064, IC=-0.0408

      epoch   6/100: train_loss=0.021235

      epoch   7/100: train_loss=0.018166

      epoch   8/100: train_loss=0.015777

      epoch   9/100: train_loss=0.014677

      epoch  10/100: train_loss=0.012608, val_loss=0.002788, IC=-0.0607

      epoch  11/100: train_loss=0.011492

      epoch  12/100: train_loss=0.010146

      epoch  13/100: train_loss=0.009117

      epoch  14/100: train_loss=0.008241

      epoch  15/100: train_loss=0.007451, val_loss=0.001484, IC=-0.0633

      epoch  16/100: train_loss=0.006754

      epoch  17/100: train_loss=0.006186

      epoch  18/100: train_loss=0.005610

      epoch  19/100: train_loss=0.005062

      epoch  20/100: train_loss=0.004589, val_loss=0.000867, IC=-0.0744

      epoch  21/100: train_loss=0.004161

      epoch  22/100: train_loss=0.003726

      epoch  23/100: train_loss=0.003450

      epoch  24/100: train_loss=0.003266

      epoch  25/100: train_loss=0.002990, val_loss=0.000569, IC=-0.0765

      epoch  26/100: train_loss=0.002760

      epoch  27/100: train_loss=0.002525

      epoch  28/100: train_loss=0.002354

      epoch  29/100: train_loss=0.002133

      epoch  30/100: train_loss=0.002009, val_loss=0.000406, IC=-0.0719

      epoch  31/100: train_loss=0.001847

      epoch  32/100: train_loss=0.001728

      epoch  33/100: train_loss=0.001579

      epoch  34/100: train_loss=0.001504

      epoch  35/100: train_loss=0.001428, val_loss=0.000297, IC=-0.0795

      epoch  36/100: train_loss=0.001318

      epoch  37/100: train_loss=0.001197

      epoch  38/100: train_loss=0.001149

      epoch  39/100: train_loss=0.001076

      epoch  40/100: train_loss=0.001009, val_loss=0.000240, IC=-0.0669

      epoch  41/100: train_loss=0.000968

      epoch  42/100: train_loss=0.000914

      epoch  43/100: train_loss=0.000864

      epoch  44/100: train_loss=0.000809

      epoch  45/100: train_loss=0.000768, val_loss=0.000201, IC=-0.0801

      epoch  46/100: train_loss=0.000735

      epoch  47/100: train_loss=0.000719

      epoch  48/100: train_loss=0.000691

      epoch  49/100: train_loss=0.000642

      epoch  50/100: train_loss=0.000616, val_loss=0.000176, IC=-0.0639

      epoch  51/100: train_loss=0.000598

      epoch  52/100: train_loss=0.000581

      epoch  53/100: train_loss=0.000556

      epoch  54/100: train_loss=0.000549

      epoch  55/100: train_loss=0.000524, val_loss=0.000160, IC=-0.0708

      epoch  56/100: train_loss=0.000515

      epoch  57/100: train_loss=0.000489

      epoch  58/100: train_loss=0.000484

      epoch  59/100: train_loss=0.000460

      epoch  60/100: train_loss=0.000455, val_loss=0.000149, IC=-0.0636

      epoch  61/100: train_loss=0.000443

      epoch  62/100: train_loss=0.000438

      epoch  63/100: train_loss=0.000420

      epoch  64/100: train_loss=0.000420

      epoch  65/100: train_loss=0.000406, val_loss=0.000141, IC=-0.0566

      epoch  66/100: train_loss=0.000405

      epoch  67/100: train_loss=0.000399

      epoch  68/100: train_loss=0.000384

      epoch  69/100: train_loss=0.000388

      epoch  70/100: train_loss=0.000380, val_loss=0.000137, IC=-0.0598

      epoch  71/100: train_loss=0.000374

      epoch  72/100: train_loss=0.000366

      epoch  73/100: train_loss=0.000368

      epoch  74/100: train_loss=0.000360

      epoch  75/100: train_loss=0.000361, val_loss=0.000134, IC=-0.0578

      epoch  76/100: train_loss=0.000357

      epoch  77/100: train_loss=0.000353

      epoch  78/100: train_loss=0.000342

      epoch  79/100: train_loss=0.000349

      epoch  80/100: train_loss=0.000344, val_loss=0.000133, IC=-0.0519

      epoch  81/100: train_loss=0.000342

      epoch  82/100: train_loss=0.000337

      epoch  83/100: train_loss=0.000342

      epoch  84/100: train_loss=0.000340

      epoch  85/100: train_loss=0.000337, val_loss=0.000132, IC=-0.0478

      epoch  86/100: train_loss=0.000335

      epoch  87/100: train_loss=0.000334

      epoch  88/100: train_loss=0.000337

      epoch  89/100: train_loss=0.000330

      epoch  90/100: train_loss=0.000333, val_loss=0.000131, IC=-0.0474

      epoch  91/100: train_loss=0.000338

      epoch  92/100: train_loss=0.000334

      epoch  93/100: train_loss=0.000332

      epoch  94/100: train_loss=0.000331

      epoch  95/100: train_loss=0.000331, val_loss=0.000131, IC=-0.0457

      epoch  96/100: train_loss=0.000328

      epoch  97/100: train_loss=0.000328

      epoch  98/100: train_loss=0.000332

      epoch  99/100: train_loss=0.000332

      epoch 100/100: train_loss=0.000330, val_loss=0.000131, IC=-0.0457

      best_ep=5, IC=-0.0408 (107.7s, 20 checkpoints)

  Fold 3: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.379635

      epoch   2/100: train_loss=0.091643

      epoch   3/100: train_loss=0.060502

      epoch   4/100: train_loss=0.039991

      epoch   5/100: train_loss=0.029220, val_loss=0.011671, IC=-0.0061

      epoch   6/100: train_loss=0.022347

      epoch   7/100: train_loss=0.017895

      epoch   8/100: train_loss=0.014862

      epoch   9/100: train_loss=0.012578

      epoch  10/100: train_loss=0.010704, val_loss=0.003322, IC=+0.0096

      epoch  11/100: train_loss=0.009463

      epoch  12/100: train_loss=0.008468

      epoch  13/100: train_loss=0.007384

      epoch  14/100: train_loss=0.006739

      epoch  15/100: train_loss=0.006000, val_loss=0.001466, IC=+0.0159

      epoch  16/100: train_loss=0.005443

      epoch  17/100: train_loss=0.004954

      epoch  18/100: train_loss=0.004399

      epoch  19/100: train_loss=0.004036

      epoch  20/100: train_loss=0.003715, val_loss=0.000874, IC=+0.0107

      epoch  21/100: train_loss=0.003359

      epoch  22/100: train_loss=0.003135

      epoch  23/100: train_loss=0.002891

      epoch  24/100: train_loss=0.002620

      epoch  25/100: train_loss=0.002493, val_loss=0.000572, IC=+0.0072

      epoch  26/100: train_loss=0.002285

      epoch  27/100: train_loss=0.002069

      epoch  28/100: train_loss=0.001963

      epoch  29/100: train_loss=0.001845

      epoch  30/100: train_loss=0.001702, val_loss=0.000379, IC=-0.0014

      epoch  31/100: train_loss=0.001585

      epoch  32/100: train_loss=0.001483

      epoch  33/100: train_loss=0.001405

      epoch  34/100: train_loss=0.001294

      epoch  35/100: train_loss=0.001219, val_loss=0.000286, IC=-0.0065

      epoch  36/100: train_loss=0.001167

      epoch  37/100: train_loss=0.001107

      epoch  38/100: train_loss=0.001062

      epoch  39/100: train_loss=0.001022

      epoch  40/100: train_loss=0.000958, val_loss=0.000224, IC=-0.0060

      epoch  41/100: train_loss=0.000900

      epoch  42/100: train_loss=0.000856

      epoch  43/100: train_loss=0.000813

      epoch  44/100: train_loss=0.000794

      epoch  45/100: train_loss=0.000763, val_loss=0.000186, IC=-0.0101

      epoch  46/100: train_loss=0.000736

      epoch  47/100: train_loss=0.000697

      epoch  48/100: train_loss=0.000675

      epoch  49/100: train_loss=0.000661

      epoch  50/100: train_loss=0.000636, val_loss=0.000165, IC=-0.0155

      epoch  51/100: train_loss=0.000615

      epoch  52/100: train_loss=0.000593

      epoch  53/100: train_loss=0.000576

      epoch  54/100: train_loss=0.000566

      epoch  55/100: train_loss=0.000548, val_loss=0.000148, IC=-0.0192

      epoch  56/100: train_loss=0.000543

      epoch  57/100: train_loss=0.000526

      epoch  58/100: train_loss=0.000515

      epoch  59/100: train_loss=0.000495

      epoch  60/100: train_loss=0.000487, val_loss=0.000137, IC=-0.0172

      epoch  61/100: train_loss=0.000473

      epoch  62/100: train_loss=0.000481

      epoch  63/100: train_loss=0.000462

      epoch  64/100: train_loss=0.000456

      epoch  65/100: train_loss=0.000460, val_loss=0.000130, IC=-0.0122

      epoch  66/100: train_loss=0.000438

      epoch  67/100: train_loss=0.000432

      epoch  68/100: train_loss=0.000420

      epoch  69/100: train_loss=0.000419

      epoch  70/100: train_loss=0.000418, val_loss=0.000126, IC=-0.0203

      epoch  71/100: train_loss=0.000419

      epoch  72/100: train_loss=0.000416

      epoch  73/100: train_loss=0.000401

      epoch  74/100: train_loss=0.000395

      epoch  75/100: train_loss=0.000394, val_loss=0.000121, IC=-0.0187

      epoch  76/100: train_loss=0.000400

      epoch  77/100: train_loss=0.000396

      epoch  78/100: train_loss=0.000391

      epoch  79/100: train_loss=0.000391

      epoch  80/100: train_loss=0.000386, val_loss=0.000119, IC=-0.0193

      epoch  81/100: train_loss=0.000388

      epoch  82/100: train_loss=0.000385

      epoch  83/100: train_loss=0.000374

      epoch  84/100: train_loss=0.000376

      epoch  85/100: train_loss=0.000378, val_loss=0.000118, IC=-0.0201

      epoch  86/100: train_loss=0.000373

      epoch  87/100: train_loss=0.000377

      epoch  88/100: train_loss=0.000371

      epoch  89/100: train_loss=0.000370

      epoch  90/100: train_loss=0.000373, val_loss=0.000117, IC=-0.0193

      epoch  91/100: train_loss=0.000364

      epoch  92/100: train_loss=0.000367

      epoch  93/100: train_loss=0.000370

      epoch  94/100: train_loss=0.000367

      epoch  95/100: train_loss=0.000369, val_loss=0.000117, IC=-0.0206

      epoch  96/100: train_loss=0.000370

      epoch  97/100: train_loss=0.000372

      epoch  98/100: train_loss=0.000370

      epoch  99/100: train_loss=0.000369

      epoch 100/100: train_loss=0.000365, val_loss=0.000117, IC=-0.0206

      best_ep=15, IC=+0.0159 (116.8s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.267219

      epoch   2/100: train_loss=0.129828

      epoch   3/100: train_loss=0.072933

      epoch   4/100: train_loss=0.050735

      epoch   5/100: train_loss=0.038175, val_loss=0.020156, IC=-0.0322

      epoch   6/100: train_loss=0.030400

      epoch   7/100: train_loss=0.025729

      epoch   8/100: train_loss=0.021278

      epoch   9/100: train_loss=0.018238

      epoch  10/100: train_loss=0.015556, val_loss=0.007918, IC=+0.0069

      epoch  11/100: train_loss=0.013494

      epoch  12/100: train_loss=0.011639

      epoch  13/100: train_loss=0.010160

      epoch  14/100: train_loss=0.008823

      epoch  15/100: train_loss=0.007815, val_loss=0.003105, IC=+0.0066

      epoch  16/100: train_loss=0.007022

      epoch  17/100: train_loss=0.006084

      epoch  18/100: train_loss=0.005580

      epoch  19/100: train_loss=0.004941

      epoch  20/100: train_loss=0.004337, val_loss=0.001398, IC=+0.0027

      epoch  21/100: train_loss=0.003899

      epoch  22/100: train_loss=0.003563

      epoch  23/100: train_loss=0.003092

      epoch  24/100: train_loss=0.002818

      epoch  25/100: train_loss=0.002625, val_loss=0.000720, IC=-0.0090

      epoch  26/100: train_loss=0.002325

      epoch  27/100: train_loss=0.002081

      epoch  28/100: train_loss=0.001901

      epoch  29/100: train_loss=0.001754

      epoch  30/100: train_loss=0.001590, val_loss=0.000502, IC=-0.0177

      epoch  31/100: train_loss=0.001442

      epoch  32/100: train_loss=0.001354

      epoch  33/100: train_loss=0.001225

      epoch  34/100: train_loss=0.001141

      epoch  35/100: train_loss=0.001052, val_loss=0.000401, IC=-0.0167

      epoch  36/100: train_loss=0.000957

      epoch  37/100: train_loss=0.000900

      epoch  38/100: train_loss=0.000834

      epoch  39/100: train_loss=0.000795

      epoch  40/100: train_loss=0.000725, val_loss=0.000336, IC=-0.0150

      epoch  41/100: train_loss=0.000690

      epoch  42/100: train_loss=0.000642

      epoch  43/100: train_loss=0.000604

      epoch  44/100: train_loss=0.000581

      epoch  45/100: train_loss=0.000553, val_loss=0.000299, IC=-0.0110

      epoch  46/100: train_loss=0.000518

      epoch  47/100: train_loss=0.000493

      epoch  48/100: train_loss=0.000479

      epoch  49/100: train_loss=0.000436

      epoch  50/100: train_loss=0.000429, val_loss=0.000273, IC=-0.0170

      epoch  51/100: train_loss=0.000418

      epoch  52/100: train_loss=0.000400

      epoch  53/100: train_loss=0.000391

      epoch  54/100: train_loss=0.000368

      epoch  55/100: train_loss=0.000351, val_loss=0.000254, IC=-0.0181

      epoch  56/100: train_loss=0.000349

      epoch  57/100: train_loss=0.000333

      epoch  58/100: train_loss=0.000320

      epoch  59/100: train_loss=0.000313

      epoch  60/100: train_loss=0.000309, val_loss=0.000243, IC=-0.0185

      epoch  61/100: train_loss=0.000304

      epoch  62/100: train_loss=0.000295

      epoch  63/100: train_loss=0.000286

      epoch  64/100: train_loss=0.000292

      epoch  65/100: train_loss=0.000282, val_loss=0.000235, IC=-0.0183

      epoch  66/100: train_loss=0.000273

      epoch  67/100: train_loss=0.000271

      epoch  68/100: train_loss=0.000267

      epoch  69/100: train_loss=0.000260

      epoch  70/100: train_loss=0.000262, val_loss=0.000231, IC=-0.0172

      epoch  71/100: train_loss=0.000260

      epoch  72/100: train_loss=0.000259

      epoch  73/100: train_loss=0.000254

      epoch  74/100: train_loss=0.000247

      epoch  75/100: train_loss=0.000254, val_loss=0.000227, IC=-0.0161

      epoch  76/100: train_loss=0.000248

      epoch  77/100: train_loss=0.000245

      epoch  78/100: train_loss=0.000245

      epoch  79/100: train_loss=0.000240

      epoch  80/100: train_loss=0.000241, val_loss=0.000225, IC=-0.0179

      epoch  81/100: train_loss=0.000240

      epoch  82/100: train_loss=0.000242

      epoch  83/100: train_loss=0.000236

      epoch  84/100: train_loss=0.000235

      epoch  85/100: train_loss=0.000239, val_loss=0.000224, IC=-0.0201

      epoch  86/100: train_loss=0.000238

      epoch  87/100: train_loss=0.000236

      epoch  88/100: train_loss=0.000238

      epoch  89/100: train_loss=0.000238

      epoch  90/100: train_loss=0.000235, val_loss=0.000223, IC=-0.0192

      epoch  91/100: train_loss=0.000236

      epoch  92/100: train_loss=0.000237

      epoch  93/100: train_loss=0.000231

      epoch  94/100: train_loss=0.000233

      epoch  95/100: train_loss=0.000234, val_loss=0.000223, IC=-0.0195

      epoch  96/100: train_loss=0.000231

      epoch  97/100: train_loss=0.000236

      epoch  98/100: train_loss=0.000230

      epoch  99/100: train_loss=0.000234

      epoch 100/100: train_loss=0.000233, val_loss=0.000223, IC=-0.0192

      best_ep=10, IC=+0.0069 (101.5s, 20 checkpoints)

  Fold 5: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.322059

      epoch   2/100: train_loss=0.328853

      epoch   3/100: train_loss=0.096994

      epoch   4/100: train_loss=0.047369

      epoch   5/100: train_loss=0.034596, val_loss=0.014298, IC=-0.0133

      epoch   6/100: train_loss=0.026425

      epoch   7/100: train_loss=0.021895

      epoch   8/100: train_loss=0.018339

      epoch   9/100: train_loss=0.015436

      epoch  10/100: train_loss=0.013438, val_loss=0.003822, IC=-0.0607

      epoch  11/100: train_loss=0.012138

      epoch  12/100: train_loss=0.010761

      epoch  13/100: train_loss=0.009462

      epoch  14/100: train_loss=0.008524

      epoch  15/100: train_loss=0.007509, val_loss=0.001816, IC=-0.0675

      epoch  16/100: train_loss=0.006811

      epoch  17/100: train_loss=0.006116

      epoch  18/100: train_loss=0.005581

      epoch  19/100: train_loss=0.004954

      epoch  20/100: train_loss=0.004563, val_loss=0.001045, IC=-0.0623

      epoch  21/100: train_loss=0.004209

      epoch  22/100: train_loss=0.003731

      epoch  23/100: train_loss=0.003410

      epoch  24/100: train_loss=0.003181

      epoch  25/100: train_loss=0.002824, val_loss=0.000560, IC=-0.0693

      epoch  26/100: train_loss=0.002510

      epoch  27/100: train_loss=0.002361

      epoch  28/100: train_loss=0.002121

      epoch  29/100: train_loss=0.001954

      epoch  30/100: train_loss=0.001805, val_loss=0.000351, IC=-0.0639

      epoch  31/100: train_loss=0.001688

      epoch  32/100: train_loss=0.001531

      epoch  33/100: train_loss=0.001444

      epoch  34/100: train_loss=0.001335

      epoch  35/100: train_loss=0.001251, val_loss=0.000255, IC=-0.0507

      epoch  36/100: train_loss=0.001146

      epoch  37/100: train_loss=0.001078

      epoch  38/100: train_loss=0.001004

      epoch  39/100: train_loss=0.000930

      epoch  40/100: train_loss=0.000872, val_loss=0.000196, IC=-0.0519

      epoch  41/100: train_loss=0.000841

      epoch  42/100: train_loss=0.000795

      epoch  43/100: train_loss=0.000747

      epoch  44/100: train_loss=0.000705

      epoch  45/100: train_loss=0.000669, val_loss=0.000154, IC=-0.0498

      epoch  46/100: train_loss=0.000631

      epoch  47/100: train_loss=0.000583

      epoch  48/100: train_loss=0.000583

      epoch  49/100: train_loss=0.000529

      epoch  50/100: train_loss=0.000512, val_loss=0.000137, IC=-0.0481

      epoch  51/100: train_loss=0.000497

      epoch  52/100: train_loss=0.000474

      epoch  53/100: train_loss=0.000454

      epoch  54/100: train_loss=0.000440

      epoch  55/100: train_loss=0.000423, val_loss=0.000124, IC=-0.0477

      epoch  56/100: train_loss=0.000410

      epoch  57/100: train_loss=0.000404

      epoch  58/100: train_loss=0.000390

      epoch  59/100: train_loss=0.000381

      epoch  60/100: train_loss=0.000370, val_loss=0.000115, IC=-0.0423

      epoch  61/100: train_loss=0.000358

      epoch  62/100: train_loss=0.000349

      epoch  63/100: train_loss=0.000353

      epoch  64/100: train_loss=0.000329

      epoch  65/100: train_loss=0.000326, val_loss=0.000109, IC=-0.0447

      epoch  66/100: train_loss=0.000322

      epoch  67/100: train_loss=0.000315

      epoch  68/100: train_loss=0.000312

      epoch  69/100: train_loss=0.000309

      epoch  70/100: train_loss=0.000302, val_loss=0.000106, IC=-0.0420

      epoch  71/100: train_loss=0.000300

      epoch  72/100: train_loss=0.000294

      epoch  73/100: train_loss=0.000295

      epoch  74/100: train_loss=0.000289

      epoch  75/100: train_loss=0.000286, val_loss=0.000103, IC=-0.0420

      epoch  76/100: train_loss=0.000281

      epoch  77/100: train_loss=0.000280

      epoch  78/100: train_loss=0.000279

      epoch  79/100: train_loss=0.000273

      epoch  80/100: train_loss=0.000271, val_loss=0.000102, IC=-0.0461

      epoch  81/100: train_loss=0.000270

      epoch  82/100: train_loss=0.000271

      epoch  83/100: train_loss=0.000270

      epoch  84/100: train_loss=0.000268

      epoch  85/100: train_loss=0.000265, val_loss=0.000102, IC=-0.0443

      epoch  86/100: train_loss=0.000270

      epoch  87/100: train_loss=0.000264

      epoch  88/100: train_loss=0.000261

      epoch  89/100: train_loss=0.000263

      epoch  90/100: train_loss=0.000266, val_loss=0.000101, IC=-0.0429

      epoch  91/100: train_loss=0.000263

      epoch  92/100: train_loss=0.000262

      epoch  93/100: train_loss=0.000260

      epoch  94/100: train_loss=0.000260

      epoch  95/100: train_loss=0.000259, val_loss=0.000101, IC=-0.0426

      epoch  96/100: train_loss=0.000261

      epoch  97/100: train_loss=0.000259

      epoch  98/100: train_loss=0.000261

      epoch  99/100: train_loss=0.000262

      epoch 100/100: train_loss=0.000260, val_loss=0.000101, IC=-0.0428

      best_ep=5, IC=-0.0133 (90.4s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.150940

      epoch   2/100: train_loss=0.086218

      epoch   3/100: train_loss=0.058861

      epoch   4/100: train_loss=0.041239

      epoch   5/100: train_loss=0.030552, val_loss=0.013391, IC=+0.0471

      epoch   6/100: train_loss=0.023169

      epoch   7/100: train_loss=0.018337

      epoch   8/100: train_loss=0.014728

      epoch   9/100: train_loss=0.012074

      epoch  10/100: train_loss=0.009908, val_loss=0.004028, IC=+0.0410

      epoch  11/100: train_loss=0.008115

      epoch  12/100: train_loss=0.006949

      epoch  13/100: train_loss=0.005933

      epoch  14/100: train_loss=0.005009

      epoch  15/100: train_loss=0.004296, val_loss=0.001784, IC=+0.0395

      epoch  16/100: train_loss=0.003740

      epoch  17/100: train_loss=0.003192

      epoch  18/100: train_loss=0.002784

      epoch  19/100: train_loss=0.002436

      epoch  20/100: train_loss=0.002122, val_loss=0.001008, IC=+0.0312

      epoch  21/100: train_loss=0.001882

      epoch  22/100: train_loss=0.001645

      epoch  23/100: train_loss=0.001474

      epoch  24/100: train_loss=0.001272

      epoch  25/100: train_loss=0.001118, val_loss=0.000603, IC=+0.0090

      epoch  26/100: train_loss=0.001010

      epoch  27/100: train_loss=0.000891

      epoch  28/100: train_loss=0.000801

      epoch  29/100: train_loss=0.000708

      epoch  30/100: train_loss=0.000648, val_loss=0.000421, IC=-0.0047

      epoch  31/100: train_loss=0.000593

      epoch  32/100: train_loss=0.000535

      epoch  33/100: train_loss=0.000487

      epoch  34/100: train_loss=0.000445

      epoch  35/100: train_loss=0.000402, val_loss=0.000337, IC=-0.0235

      epoch  36/100: train_loss=0.000376

      epoch  37/100: train_loss=0.000347

      epoch  38/100: train_loss=0.000323

      epoch  39/100: train_loss=0.000302

      epoch  40/100: train_loss=0.000285, val_loss=0.000290, IC=-0.0392

      epoch  41/100: train_loss=0.000272

      epoch  42/100: train_loss=0.000255

      epoch  43/100: train_loss=0.000242

      epoch  44/100: train_loss=0.000230

      epoch  45/100: train_loss=0.000220, val_loss=0.000261, IC=-0.0322

      epoch  46/100: train_loss=0.000210

      epoch  47/100: train_loss=0.000203

      epoch  48/100: train_loss=0.000198

      epoch  49/100: train_loss=0.000192

      epoch  50/100: train_loss=0.000188, val_loss=0.000249, IC=-0.0391

      epoch  51/100: train_loss=0.000179

      epoch  52/100: train_loss=0.000176

      epoch  53/100: train_loss=0.000171

      epoch  54/100: train_loss=0.000168

      epoch  55/100: train_loss=0.000164, val_loss=0.000242, IC=-0.0374

      epoch  56/100: train_loss=0.000162

      epoch  57/100: train_loss=0.000159

      epoch  58/100: train_loss=0.000156

      epoch  59/100: train_loss=0.000154

      epoch  60/100: train_loss=0.000152, val_loss=0.000236, IC=-0.0351

      epoch  61/100: train_loss=0.000151

      epoch  62/100: train_loss=0.000150

      epoch  63/100: train_loss=0.000147

      epoch  64/100: train_loss=0.000147

      epoch  65/100: train_loss=0.000146, val_loss=0.000235, IC=-0.0328

      epoch  66/100: train_loss=0.000143

      epoch  67/100: train_loss=0.000144

      epoch  68/100: train_loss=0.000142

      epoch  69/100: train_loss=0.000142

      epoch  70/100: train_loss=0.000141, val_loss=0.000233, IC=-0.0288

      epoch  71/100: train_loss=0.000139

      epoch  72/100: train_loss=0.000139

      epoch  73/100: train_loss=0.000140

      epoch  74/100: train_loss=0.000138

      epoch  75/100: train_loss=0.000137, val_loss=0.000232, IC=-0.0290

      epoch  76/100: train_loss=0.000136

      epoch  77/100: train_loss=0.000137

      epoch  78/100: train_loss=0.000136

      epoch  79/100: train_loss=0.000135

      epoch  80/100: train_loss=0.000136, val_loss=0.000231, IC=-0.0274

      epoch  81/100: train_loss=0.000135

      epoch  82/100: train_loss=0.000135

      epoch  83/100: train_loss=0.000134

      epoch  84/100: train_loss=0.000136

      epoch  85/100: train_loss=0.000134, val_loss=0.000230, IC=-0.0273

      epoch  86/100: train_loss=0.000134

      epoch  87/100: train_loss=0.000134

      epoch  88/100: train_loss=0.000134

      epoch  89/100: train_loss=0.000134

      epoch  90/100: train_loss=0.000135, val_loss=0.000230, IC=-0.0287

      epoch  91/100: train_loss=0.000133

      epoch  92/100: train_loss=0.000134

      epoch  93/100: train_loss=0.000134

      epoch  94/100: train_loss=0.000133

      epoch  95/100: train_loss=0.000134, val_loss=0.000230, IC=-0.0285

      epoch  96/100: train_loss=0.000133

      epoch  97/100: train_loss=0.000134

      epoch  98/100: train_loss=0.000132

      epoch  99/100: train_loss=0.000134

      epoch 100/100: train_loss=0.000133, val_loss=0.000230, IC=-0.0288

      best_ep=5, IC=+0.0471 (91.7s, 20 checkpoints)

  Fold 7: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,060 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.243717

      epoch   2/100: train_loss=0.078227

      epoch   3/100: train_loss=0.045688

      epoch   4/100: train_loss=0.031296

      epoch   5/100: train_loss=0.022784, val_loss=0.006629, IC=+0.0472

      epoch   6/100: train_loss=0.018117

      epoch   7/100: train_loss=0.014961

      epoch   8/100: train_loss=0.012639

      epoch   9/100: train_loss=0.010521

      epoch  10/100: train_loss=0.008743, val_loss=0.002077, IC=+0.0132

      epoch  11/100: train_loss=0.007646

      epoch  12/100: train_loss=0.006309

      epoch  13/100: train_loss=0.005548

      epoch  14/100: train_loss=0.004796

      epoch  15/100: train_loss=0.004043, val_loss=0.000959, IC=-0.0190

      epoch  16/100: train_loss=0.003513

      epoch  17/100: train_loss=0.003007

      epoch  18/100: train_loss=0.002652

      epoch  19/100: train_loss=0.002279

      epoch  20/100: train_loss=0.002001, val_loss=0.000460, IC=-0.0129

      epoch  21/100: train_loss=0.001733

      epoch  22/100: train_loss=0.001547

      epoch  23/100: train_loss=0.001363

      epoch  24/100: train_loss=0.001207

      epoch  25/100: train_loss=0.001039, val_loss=0.000274, IC=-0.0182

      epoch  26/100: train_loss=0.000939

      epoch  27/100: train_loss=0.000848

      epoch  28/100: train_loss=0.000751

      epoch  29/100: train_loss=0.000692

      epoch  30/100: train_loss=0.000616, val_loss=0.000191, IC=-0.0155

      epoch  31/100: train_loss=0.000550

      epoch  32/100: train_loss=0.000505

      epoch  33/100: train_loss=0.000462

      epoch  34/100: train_loss=0.000425

      epoch  35/100: train_loss=0.000399, val_loss=0.000156, IC=-0.0110

      epoch  36/100: train_loss=0.000363

      epoch  37/100: train_loss=0.000342

      epoch  38/100: train_loss=0.000322

      epoch  39/100: train_loss=0.000308

      epoch  40/100: train_loss=0.000284, val_loss=0.000140, IC=-0.0018

      epoch  41/100: train_loss=0.000271

      epoch  42/100: train_loss=0.000257

      epoch  43/100: train_loss=0.000246

      epoch  44/100: train_loss=0.000236

      epoch  45/100: train_loss=0.000227, val_loss=0.000134, IC=-0.0199

      epoch  46/100: train_loss=0.000220

      epoch  47/100: train_loss=0.000211

      epoch  48/100: train_loss=0.000205

      epoch  49/100: train_loss=0.000198

      epoch  50/100: train_loss=0.000193, val_loss=0.000128, IC=+0.0110

      epoch  51/100: train_loss=0.000189

      epoch  52/100: train_loss=0.000186

      epoch  53/100: train_loss=0.000181

      epoch  54/100: train_loss=0.000176

      epoch  55/100: train_loss=0.000174, val_loss=0.000126, IC=-0.0046

      epoch  56/100: train_loss=0.000172

      epoch  57/100: train_loss=0.000170

      epoch  58/100: train_loss=0.000168

      epoch  59/100: train_loss=0.000167

      epoch  60/100: train_loss=0.000166, val_loss=0.000125, IC=-0.0086

      epoch  61/100: train_loss=0.000165

      epoch  62/100: train_loss=0.000162

      epoch  63/100: train_loss=0.000162

      epoch  64/100: train_loss=0.000159

      epoch  65/100: train_loss=0.000159, val_loss=0.000124, IC=+0.0055

      epoch  66/100: train_loss=0.000158

      epoch  67/100: train_loss=0.000157

      epoch  68/100: train_loss=0.000156

      epoch  69/100: train_loss=0.000156

      epoch  70/100: train_loss=0.000155, val_loss=0.000124, IC=-0.0036

      epoch  71/100: train_loss=0.000154

      epoch  72/100: train_loss=0.000153

      epoch  73/100: train_loss=0.000153

      epoch  74/100: train_loss=0.000153

      epoch  75/100: train_loss=0.000153, val_loss=0.000123, IC=-0.0038

      epoch  76/100: train_loss=0.000152

      epoch  77/100: train_loss=0.000152

      epoch  78/100: train_loss=0.000152

      epoch  79/100: train_loss=0.000151

      epoch  80/100: train_loss=0.000151, val_loss=0.000123, IC=-0.0002

      epoch  81/100: train_loss=0.000151

      epoch  82/100: train_loss=0.000150

      epoch  83/100: train_loss=0.000150

      epoch  84/100: train_loss=0.000150

      epoch  85/100: train_loss=0.000150, val_loss=0.000123, IC=-0.0033

      epoch  86/100: train_loss=0.000151

      epoch  87/100: train_loss=0.000151

      epoch  88/100: train_loss=0.000149

      epoch  89/100: train_loss=0.000150

      epoch  90/100: train_loss=0.000149, val_loss=0.000123, IC=-0.0088

      epoch  91/100: train_loss=0.000150

      epoch  92/100: train_loss=0.000150

      epoch  93/100: train_loss=0.000149

      epoch  94/100: train_loss=0.000149

      epoch  95/100: train_loss=0.000150, val_loss=0.000123, IC=-0.0088

      epoch  96/100: train_loss=0.000150

      epoch  97/100: train_loss=0.000149

      epoch  98/100: train_loss=0.000149

      epoch  99/100: train_loss=0.000149

      epoch 100/100: train_loss=0.000149, val_loss=0.000123, IC=-0.0089

      best_ep=5, IC=+0.0472 (92.7s, 20 checkpoints)

  nlinear: best_epoch=5, IC=-0.0026 (755.2s)

  Best: nlinear @ epoch 5 (IC=-0.0026)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/3dd0db7c7ac4/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=16,660 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.671051

      epoch   2/100: train_loss=0.401407

      epoch   3/100: train_loss=0.225416

      epoch   4/100: train_loss=0.118809

      epoch   5/100: train_loss=0.063206, val_loss=0.060745, IC=-0.1094

      epoch   6/100: train_loss=0.042999

      epoch   7/100: train_loss=0.033582

      epoch   8/100: train_loss=0.026512

      epoch   9/100: train_loss=0.021809

      epoch  10/100: train_loss=0.019810, val_loss=0.016632, IC=-0.0943

      epoch  11/100: train_loss=0.017565

      epoch  12/100: train_loss=0.015915

      epoch  13/100: train_loss=0.014893

      epoch  14/100: train_loss=0.014175

      epoch  15/100: train_loss=0.012554, val_loss=0.006827, IC=-0.0374

      epoch  16/100: train_loss=0.012029

      epoch  17/100: train_loss=0.011387

      epoch  18/100: train_loss=0.010568

      epoch  19/100: train_loss=0.009965

      epoch  20/100: train_loss=0.009474, val_loss=0.003832, IC=-0.0197

      epoch  21/100: train_loss=0.008730

      epoch  22/100: train_loss=0.008442

      epoch  23/100: train_loss=0.008107

      epoch  24/100: train_loss=0.007729

      epoch  25/100: train_loss=0.007079, val_loss=0.002568, IC=-0.0129

      epoch  26/100: train_loss=0.006751

      epoch  27/100: train_loss=0.006608

      epoch  28/100: train_loss=0.006250

      epoch  29/100: train_loss=0.006075

      epoch  30/100: train_loss=0.005788, val_loss=0.001962, IC=+0.0139

      epoch  31/100: train_loss=0.005448

      epoch  32/100: train_loss=0.005218

      epoch  33/100: train_loss=0.004808

      epoch  34/100: train_loss=0.004553

      epoch  35/100: train_loss=0.004317, val_loss=0.001748, IC=+0.0130

      epoch  36/100: train_loss=0.004262

      epoch  37/100: train_loss=0.004071

      epoch  38/100: train_loss=0.003931

      epoch  39/100: train_loss=0.003689

      epoch  40/100: train_loss=0.003435, val_loss=0.001561, IC=+0.0175

      epoch  41/100: train_loss=0.003513

      epoch  42/100: train_loss=0.003246

      epoch  43/100: train_loss=0.003155

      epoch  44/100: train_loss=0.003109

      epoch  45/100: train_loss=0.003053, val_loss=0.001481, IC=+0.0205

      epoch  46/100: train_loss=0.002878

      epoch  47/100: train_loss=0.002791

      epoch  48/100: train_loss=0.002700

      epoch  49/100: train_loss=0.002681

      epoch  50/100: train_loss=0.002447, val_loss=0.001436, IC=+0.0239

      epoch  51/100: train_loss=0.002512

      epoch  52/100: train_loss=0.002488

      epoch  53/100: train_loss=0.002298

      epoch  54/100: train_loss=0.002247

      epoch  55/100: train_loss=0.002231, val_loss=0.001412, IC=+0.0130

      epoch  56/100: train_loss=0.002120

      epoch  57/100: train_loss=0.002170

      epoch  58/100: train_loss=0.002091

      epoch  59/100: train_loss=0.002110

      epoch  60/100: train_loss=0.001998, val_loss=0.001369, IC=+0.0224

      epoch  61/100: train_loss=0.001919

      epoch  62/100: train_loss=0.001904

      epoch  63/100: train_loss=0.001912

      epoch  64/100: train_loss=0.001886

      epoch  65/100: train_loss=0.001890, val_loss=0.001339, IC=+0.0203

      epoch  66/100: train_loss=0.001781

      epoch  67/100: train_loss=0.001761

      epoch  68/100: train_loss=0.001756

      epoch  69/100: train_loss=0.001742

      epoch  70/100: train_loss=0.001738, val_loss=0.001327, IC=+0.0209

      epoch  71/100: train_loss=0.001661

      epoch  72/100: train_loss=0.001657

      epoch  73/100: train_loss=0.001627

      epoch  74/100: train_loss=0.001665

      epoch  75/100: train_loss=0.001610, val_loss=0.001319, IC=+0.0262

      epoch  76/100: train_loss=0.001623

      epoch  77/100: train_loss=0.001572

      epoch  78/100: train_loss=0.001604

      epoch  79/100: train_loss=0.001575

      epoch  80/100: train_loss=0.001565, val_loss=0.001326, IC=+0.0206

      epoch  81/100: train_loss=0.001533

      epoch  82/100: train_loss=0.001589

      epoch  83/100: train_loss=0.001527

      epoch  84/100: train_loss=0.001493

      epoch  85/100: train_loss=0.001514, val_loss=0.001320, IC=+0.0190

      epoch  86/100: train_loss=0.001566

      epoch  87/100: train_loss=0.001564

      epoch  88/100: train_loss=0.001513

      epoch  89/100: train_loss=0.001512

      epoch  90/100: train_loss=0.001530, val_loss=0.001312, IC=+0.0205

      epoch  91/100: train_loss=0.001523

      epoch  92/100: train_loss=0.001532

      epoch  93/100: train_loss=0.001474

      epoch  94/100: train_loss=0.001530

      epoch  95/100: train_loss=0.001471, val_loss=0.001311, IC=+0.0198

      epoch  96/100: train_loss=0.001537

      epoch  97/100: train_loss=0.001486

      epoch  98/100: train_loss=0.001531

      epoch  99/100: train_loss=0.001506

      epoch 100/100: train_loss=0.001530, val_loss=0.001310, IC=+0.0201

      best_ep=75, IC=+0.0262 (77.9s, 20 checkpoints)

  Fold 1: creating sequences...
    train=21,820 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.266300

      epoch   2/100: train_loss=0.136370

      epoch   3/100: train_loss=0.088410

      epoch   4/100: train_loss=0.058962

      epoch   5/100: train_loss=0.040979, val_loss=0.016530, IC=+0.0778

      epoch   6/100: train_loss=0.030546

      epoch   7/100: train_loss=0.024007

      epoch   8/100: train_loss=0.019754

      epoch   9/100: train_loss=0.016911

      epoch  10/100: train_loss=0.014339, val_loss=0.004845, IC=-0.0144

      epoch  11/100: train_loss=0.012818

      epoch  12/100: train_loss=0.011157

      epoch  13/100: train_loss=0.010019

      epoch  14/100: train_loss=0.008844

      epoch  15/100: train_loss=0.008075, val_loss=0.002614, IC=-0.0590

      epoch  16/100: train_loss=0.007403

      epoch  17/100: train_loss=0.006638

      epoch  18/100: train_loss=0.006052

      epoch  19/100: train_loss=0.005521

      epoch  20/100: train_loss=0.005051, val_loss=0.001605, IC=-0.0444

      epoch  21/100: train_loss=0.004593

      epoch  22/100: train_loss=0.004247

      epoch  23/100: train_loss=0.003871

      epoch  24/100: train_loss=0.003627

      epoch  25/100: train_loss=0.003329, val_loss=0.001177, IC=-0.0932

      epoch  26/100: train_loss=0.003022

      epoch  27/100: train_loss=0.002915

      epoch  28/100: train_loss=0.002659

      epoch  29/100: train_loss=0.002513

      epoch  30/100: train_loss=0.002349, val_loss=0.000878, IC=-0.0513

      epoch  31/100: train_loss=0.002187

      epoch  32/100: train_loss=0.002054

      epoch  33/100: train_loss=0.001927

      epoch  34/100: train_loss=0.001879

      epoch  35/100: train_loss=0.001725, val_loss=0.000781, IC=-0.1082

      epoch  36/100: train_loss=0.001664

      epoch  37/100: train_loss=0.001599

      epoch  38/100: train_loss=0.001558

      epoch  39/100: train_loss=0.001498

      epoch  40/100: train_loss=0.001448, val_loss=0.000678, IC=-0.0806

      epoch  41/100: train_loss=0.001392

      epoch  42/100: train_loss=0.001347

      epoch  43/100: train_loss=0.001310

      epoch  44/100: train_loss=0.001260

      epoch  45/100: train_loss=0.001219, val_loss=0.000637, IC=-0.0794

      epoch  46/100: train_loss=0.001212

      epoch  47/100: train_loss=0.001166

      epoch  48/100: train_loss=0.001150

      epoch  49/100: train_loss=0.001147

      epoch  50/100: train_loss=0.001124, val_loss=0.000628, IC=-0.1205

      epoch  51/100: train_loss=0.001100

      epoch  52/100: train_loss=0.001087

      epoch  53/100: train_loss=0.001078

      epoch  54/100: train_loss=0.001060

      epoch  55/100: train_loss=0.001031, val_loss=0.000598, IC=-0.0753

      epoch  56/100: train_loss=0.001035

      epoch  57/100: train_loss=0.001020

      epoch  58/100: train_loss=0.001009

      epoch  59/100: train_loss=0.000998

      epoch  60/100: train_loss=0.000999, val_loss=0.000602, IC=-0.1054

      epoch  61/100: train_loss=0.000980

      epoch  62/100: train_loss=0.000983

      epoch  63/100: train_loss=0.000970

      epoch  64/100: train_loss=0.000963

      epoch  65/100: train_loss=0.000969, val_loss=0.000587, IC=-0.0905

      epoch  66/100: train_loss=0.000963

      epoch  67/100: train_loss=0.000954

      epoch  68/100: train_loss=0.000946

      epoch  69/100: train_loss=0.000939

      epoch  70/100: train_loss=0.000947, val_loss=0.000580, IC=-0.0764

      epoch  71/100: train_loss=0.000940

      epoch  72/100: train_loss=0.000932

      epoch  73/100: train_loss=0.000936

      epoch  74/100: train_loss=0.000931

      epoch  75/100: train_loss=0.000934, val_loss=0.000583, IC=-0.0981

      epoch  76/100: train_loss=0.000926

      epoch  77/100: train_loss=0.000924

      epoch  78/100: train_loss=0.000917

      epoch  79/100: train_loss=0.000923

      epoch  80/100: train_loss=0.000918, val_loss=0.000582, IC=-0.0967

      epoch  81/100: train_loss=0.000910

      epoch  82/100: train_loss=0.000921

      epoch  83/100: train_loss=0.000913

      epoch  84/100: train_loss=0.000911

      epoch  85/100: train_loss=0.000912, val_loss=0.000582, IC=-0.0990

      epoch  86/100: train_loss=0.000919

      epoch  87/100: train_loss=0.000909

      epoch  88/100: train_loss=0.000911

      epoch  89/100: train_loss=0.000909

      epoch  90/100: train_loss=0.000909, val_loss=0.000582, IC=-0.0988

      epoch  91/100: train_loss=0.000910

      epoch  92/100: train_loss=0.000913

      epoch  93/100: train_loss=0.000901

      epoch  94/100: train_loss=0.000917

      epoch  95/100: train_loss=0.000904, val_loss=0.000580, IC=-0.0960

      epoch  96/100: train_loss=0.000903

      epoch  97/100: train_loss=0.000913

      epoch  98/100: train_loss=0.000910

      epoch  99/100: train_loss=0.000917

      epoch 100/100: train_loss=0.000915, val_loss=0.000580, IC=-0.0946

      best_ep=5, IC=+0.0778 (88.9s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.185784

      epoch   2/100: train_loss=0.074249

      epoch   3/100: train_loss=0.046080

      epoch   4/100: train_loss=0.033251

      epoch   5/100: train_loss=0.025603, val_loss=0.006195, IC=-0.0594

      epoch   6/100: train_loss=0.021798

      epoch   7/100: train_loss=0.018952

      epoch   8/100: train_loss=0.016595

      epoch   9/100: train_loss=0.014670

      epoch  10/100: train_loss=0.012969, val_loss=0.003131, IC=-0.0991

      epoch  11/100: train_loss=0.011795

      epoch  12/100: train_loss=0.010601

      epoch  13/100: train_loss=0.009652

      epoch  14/100: train_loss=0.008784

      epoch  15/100: train_loss=0.007814, val_loss=0.001814, IC=-0.1171

      epoch  16/100: train_loss=0.007343

      epoch  17/100: train_loss=0.006615

      epoch  18/100: train_loss=0.006078

      epoch  19/100: train_loss=0.005533

      epoch  20/100: train_loss=0.005162, val_loss=0.001221, IC=-0.1230

      epoch  21/100: train_loss=0.004708

      epoch  22/100: train_loss=0.004336

      epoch  23/100: train_loss=0.004008

      epoch  24/100: train_loss=0.003753

      epoch  25/100: train_loss=0.003491, val_loss=0.000891, IC=-0.1085

      epoch  26/100: train_loss=0.003335

      epoch  27/100: train_loss=0.003021

      epoch  28/100: train_loss=0.002842

      epoch  29/100: train_loss=0.002688

      epoch  30/100: train_loss=0.002535, val_loss=0.000725, IC=-0.1193

      epoch  31/100: train_loss=0.002381

      epoch  32/100: train_loss=0.002277

      epoch  33/100: train_loss=0.002131

      epoch  34/100: train_loss=0.002043

      epoch  35/100: train_loss=0.001992, val_loss=0.000636, IC=-0.0839

      epoch  36/100: train_loss=0.001886

      epoch  37/100: train_loss=0.001790

      epoch  38/100: train_loss=0.001706

      epoch  39/100: train_loss=0.001616

      epoch  40/100: train_loss=0.001554, val_loss=0.000569, IC=-0.0760

      epoch  41/100: train_loss=0.001523

      epoch  42/100: train_loss=0.001449

      epoch  43/100: train_loss=0.001413

      epoch  44/100: train_loss=0.001349

      epoch  45/100: train_loss=0.001324, val_loss=0.000527, IC=-0.0623

      epoch  46/100: train_loss=0.001293

      epoch  47/100: train_loss=0.001264

      epoch  48/100: train_loss=0.001225

      epoch  49/100: train_loss=0.001204

      epoch  50/100: train_loss=0.001186, val_loss=0.000504, IC=-0.0514

      epoch  51/100: train_loss=0.001149

      epoch  52/100: train_loss=0.001137

      epoch  53/100: train_loss=0.001116

      epoch  54/100: train_loss=0.001105

      epoch  55/100: train_loss=0.001076, val_loss=0.000493, IC=-0.0469

      epoch  56/100: train_loss=0.001051

      epoch  57/100: train_loss=0.001039

      epoch  58/100: train_loss=0.001039

      epoch  59/100: train_loss=0.001008

      epoch  60/100: train_loss=0.001013, val_loss=0.000481, IC=-0.0304

      epoch  61/100: train_loss=0.000994

      epoch  62/100: train_loss=0.001003

      epoch  63/100: train_loss=0.000980

      epoch  64/100: train_loss=0.000965

      epoch  65/100: train_loss=0.000962, val_loss=0.000474, IC=-0.0130

      epoch  66/100: train_loss=0.000951

      epoch  67/100: train_loss=0.000953

      epoch  68/100: train_loss=0.000940

      epoch  69/100: train_loss=0.000940

      epoch  70/100: train_loss=0.000940, val_loss=0.000470, IC=+0.0016

      epoch  71/100: train_loss=0.000926

      epoch  72/100: train_loss=0.000913

      epoch  73/100: train_loss=0.000925

      epoch  74/100: train_loss=0.000905

      epoch  75/100: train_loss=0.000919, val_loss=0.000467, IC=-0.0093

      epoch  76/100: train_loss=0.000910

      epoch  77/100: train_loss=0.000912

      epoch  78/100: train_loss=0.000904

      epoch  79/100: train_loss=0.000903

      epoch  80/100: train_loss=0.000894, val_loss=0.000467, IC=-0.0077

      epoch  81/100: train_loss=0.000897

      epoch  82/100: train_loss=0.000898

      epoch  83/100: train_loss=0.000895

      epoch  84/100: train_loss=0.000898

      epoch  85/100: train_loss=0.000888, val_loss=0.000465, IC=-0.0001

      epoch  86/100: train_loss=0.000886

      epoch  87/100: train_loss=0.000885

      epoch  88/100: train_loss=0.000887

      epoch  89/100: train_loss=0.000888

      epoch  90/100: train_loss=0.000881, val_loss=0.000464, IC=-0.0025

      epoch  91/100: train_loss=0.000883

      epoch  92/100: train_loss=0.000876

      epoch  93/100: train_loss=0.000880

      epoch  94/100: train_loss=0.000881

      epoch  95/100: train_loss=0.000888, val_loss=0.000464, IC=-0.0017

      epoch  96/100: train_loss=0.000891

      epoch  97/100: train_loss=0.000888

      epoch  98/100: train_loss=0.000878

      epoch  99/100: train_loss=0.000885

      epoch 100/100: train_loss=0.000878, val_loss=0.000464, IC=-0.0015

      best_ep=70, IC=+0.0016 (64.1s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.386412

      epoch   2/100: train_loss=0.092252

      epoch   3/100: train_loss=0.061381

      epoch   4/100: train_loss=0.040963

      epoch   5/100: train_loss=0.030150, val_loss=0.012283, IC=-0.0247

      epoch   6/100: train_loss=0.023299

      epoch   7/100: train_loss=0.018572

      epoch   8/100: train_loss=0.015430

      epoch   9/100: train_loss=0.013024

      epoch  10/100: train_loss=0.011431, val_loss=0.003592, IC=+0.0009

      epoch  11/100: train_loss=0.010240

      epoch  12/100: train_loss=0.008902

      epoch  13/100: train_loss=0.008035

      epoch  14/100: train_loss=0.007296

      epoch  15/100: train_loss=0.006415, val_loss=0.001699, IC=+0.0049

      epoch  16/100: train_loss=0.005972

      epoch  17/100: train_loss=0.005429

      epoch  18/100: train_loss=0.004969

      epoch  19/100: train_loss=0.004634

      epoch  20/100: train_loss=0.004174, val_loss=0.001043, IC=-0.0063

      epoch  21/100: train_loss=0.003882

      epoch  22/100: train_loss=0.003636

      epoch  23/100: train_loss=0.003362

      epoch  24/100: train_loss=0.003148

      epoch  25/100: train_loss=0.002924, val_loss=0.000739, IC=-0.0180

      epoch  26/100: train_loss=0.002738

      epoch  27/100: train_loss=0.002583

      epoch  28/100: train_loss=0.002444

      epoch  29/100: train_loss=0.002318

      epoch  30/100: train_loss=0.002172, val_loss=0.000585, IC=-0.0370

      epoch  31/100: train_loss=0.002104

      epoch  32/100: train_loss=0.001995

      epoch  33/100: train_loss=0.001898

      epoch  34/100: train_loss=0.001805

      epoch  35/100: train_loss=0.001723, val_loss=0.000500, IC=-0.0428

      epoch  36/100: train_loss=0.001682

      epoch  37/100: train_loss=0.001607

      epoch  38/100: train_loss=0.001561

      epoch  39/100: train_loss=0.001510

      epoch  40/100: train_loss=0.001455, val_loss=0.000449, IC=-0.0463

      epoch  41/100: train_loss=0.001427

      epoch  42/100: train_loss=0.001360

      epoch  43/100: train_loss=0.001346

      epoch  44/100: train_loss=0.001316

      epoch  45/100: train_loss=0.001278, val_loss=0.000423, IC=-0.0719

      epoch  46/100: train_loss=0.001248

      epoch  47/100: train_loss=0.001208

      epoch  48/100: train_loss=0.001183

      epoch  49/100: train_loss=0.001162

      epoch  50/100: train_loss=0.001146, val_loss=0.000401, IC=-0.0674

      epoch  51/100: train_loss=0.001123

      epoch  52/100: train_loss=0.001098

      epoch  53/100: train_loss=0.001104

      epoch  54/100: train_loss=0.001078

      epoch  55/100: train_loss=0.001068, val_loss=0.000386, IC=-0.0615

      epoch  56/100: train_loss=0.001055

      epoch  57/100: train_loss=0.001045

      epoch  58/100: train_loss=0.001020

      epoch  59/100: train_loss=0.001009

      epoch  60/100: train_loss=0.001003, val_loss=0.000376, IC=-0.0531

      epoch  61/100: train_loss=0.001002

      epoch  62/100: train_loss=0.000996

      epoch  63/100: train_loss=0.000989

      epoch  64/100: train_loss=0.000980

      epoch  65/100: train_loss=0.000971, val_loss=0.000368, IC=-0.0521

      epoch  66/100: train_loss=0.000956

      epoch  67/100: train_loss=0.000946

      epoch  68/100: train_loss=0.000940

      epoch  69/100: train_loss=0.000947

      epoch  70/100: train_loss=0.000933, val_loss=0.000368, IC=-0.0644

      epoch  71/100: train_loss=0.000928

      epoch  72/100: train_loss=0.000924

      epoch  73/100: train_loss=0.000921

      epoch  74/100: train_loss=0.000919

      epoch  75/100: train_loss=0.000912, val_loss=0.000363, IC=-0.0537

      epoch  76/100: train_loss=0.000915

      epoch  77/100: train_loss=0.000913

      epoch  78/100: train_loss=0.000904

      epoch  79/100: train_loss=0.000899

      epoch  80/100: train_loss=0.000901, val_loss=0.000361, IC=-0.0541

      epoch  81/100: train_loss=0.000903

      epoch  82/100: train_loss=0.000900

      epoch  83/100: train_loss=0.000901

      epoch  84/100: train_loss=0.000906

      epoch  85/100: train_loss=0.000894, val_loss=0.000360, IC=-0.0529

      epoch  86/100: train_loss=0.000904

      epoch  87/100: train_loss=0.000885

      epoch  88/100: train_loss=0.000902

      epoch  89/100: train_loss=0.000888

      epoch  90/100: train_loss=0.000893, val_loss=0.000359, IC=-0.0544

      epoch  91/100: train_loss=0.000897

      epoch  92/100: train_loss=0.000887

      epoch  93/100: train_loss=0.000894

      epoch  94/100: train_loss=0.000886

      epoch  95/100: train_loss=0.000885, val_loss=0.000359, IC=-0.0552

      epoch  96/100: train_loss=0.000888

      epoch  97/100: train_loss=0.000891

      epoch  98/100: train_loss=0.000885

      epoch  99/100: train_loss=0.000887

      epoch 100/100: train_loss=0.000888, val_loss=0.000359, IC=-0.0555

      best_ep=15, IC=+0.0049 (62.2s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.270465

      epoch   2/100: train_loss=0.132019

      epoch   3/100: train_loss=0.073660

      epoch   4/100: train_loss=0.051268

      epoch   5/100: train_loss=0.038861, val_loss=0.021041, IC=-0.0469

      epoch   6/100: train_loss=0.031364

      epoch   7/100: train_loss=0.026485

      epoch   8/100: train_loss=0.021540

      epoch   9/100: train_loss=0.018141

      epoch  10/100: train_loss=0.015947, val_loss=0.008349, IC=+0.0163

      epoch  11/100: train_loss=0.014014

      epoch  12/100: train_loss=0.012045

      epoch  13/100: train_loss=0.010675

      epoch  14/100: train_loss=0.009411

      epoch  15/100: train_loss=0.008492, val_loss=0.003732, IC=+0.0082

      epoch  16/100: train_loss=0.007458

      epoch  17/100: train_loss=0.006569

      epoch  18/100: train_loss=0.005825

      epoch  19/100: train_loss=0.005361

      epoch  20/100: train_loss=0.004761, val_loss=0.001970, IC=+0.0090

      epoch  21/100: train_loss=0.004347

      epoch  22/100: train_loss=0.003948

      epoch  23/100: train_loss=0.003573

      epoch  24/100: train_loss=0.003313

      epoch  25/100: train_loss=0.002997, val_loss=0.001359, IC=-0.0047

      epoch  26/100: train_loss=0.002763

      epoch  27/100: train_loss=0.002545

      epoch  28/100: train_loss=0.002377

      epoch  29/100: train_loss=0.002215

      epoch  30/100: train_loss=0.002054, val_loss=0.001085, IC=-0.0151

      epoch  31/100: train_loss=0.001887

      epoch  32/100: train_loss=0.001771

      epoch  33/100: train_loss=0.001666

      epoch  34/100: train_loss=0.001560

      epoch  35/100: train_loss=0.001488, val_loss=0.000961, IC=-0.0088

      epoch  36/100: train_loss=0.001418

      epoch  37/100: train_loss=0.001350

      epoch  38/100: train_loss=0.001258

      epoch  39/100: train_loss=0.001216

      epoch  40/100: train_loss=0.001172, val_loss=0.000872, IC=-0.0136

      epoch  41/100: train_loss=0.001103

      epoch  42/100: train_loss=0.001066

      epoch  43/100: train_loss=0.001029

      epoch  44/100: train_loss=0.001008

      epoch  45/100: train_loss=0.000961, val_loss=0.000832, IC=-0.0125

      epoch  46/100: train_loss=0.000955

      epoch  47/100: train_loss=0.000916

      epoch  48/100: train_loss=0.000899

      epoch  49/100: train_loss=0.000883

      epoch  50/100: train_loss=0.000860, val_loss=0.000803, IC=-0.0192

      epoch  51/100: train_loss=0.000839

      epoch  52/100: train_loss=0.000829

      epoch  53/100: train_loss=0.000813

      epoch  54/100: train_loss=0.000812

      epoch  55/100: train_loss=0.000791, val_loss=0.000789, IC=-0.0194

      epoch  56/100: train_loss=0.000783

      epoch  57/100: train_loss=0.000780

      epoch  58/100: train_loss=0.000759

      epoch  59/100: train_loss=0.000753

      epoch  60/100: train_loss=0.000747, val_loss=0.000778, IC=-0.0187

      epoch  61/100: train_loss=0.000738

      epoch  62/100: train_loss=0.000733

      epoch  63/100: train_loss=0.000721

      epoch  64/100: train_loss=0.000722

      epoch  65/100: train_loss=0.000713, val_loss=0.000769, IC=-0.0203

      epoch  66/100: train_loss=0.000712

      epoch  67/100: train_loss=0.000707

      epoch  68/100: train_loss=0.000710

      epoch  69/100: train_loss=0.000705

      epoch  70/100: train_loss=0.000698, val_loss=0.000769, IC=-0.0167

      epoch  71/100: train_loss=0.000698

      epoch  72/100: train_loss=0.000693

      epoch  73/100: train_loss=0.000691

      epoch  74/100: train_loss=0.000688

      epoch  75/100: train_loss=0.000693, val_loss=0.000763, IC=-0.0207

      epoch  76/100: train_loss=0.000689

      epoch  77/100: train_loss=0.000683

      epoch  78/100: train_loss=0.000684

      epoch  79/100: train_loss=0.000674

      epoch  80/100: train_loss=0.000676, val_loss=0.000762, IC=-0.0203

      epoch  81/100: train_loss=0.000675

      epoch  82/100: train_loss=0.000676

      epoch  83/100: train_loss=0.000680

      epoch  84/100: train_loss=0.000677

      epoch  85/100: train_loss=0.000671, val_loss=0.000759, IC=-0.0241

      epoch  86/100: train_loss=0.000667

      epoch  87/100: train_loss=0.000678

      epoch  88/100: train_loss=0.000670

      epoch  89/100: train_loss=0.000676

      epoch  90/100: train_loss=0.000667, val_loss=0.000760, IC=-0.0220

      epoch  91/100: train_loss=0.000668

      epoch  92/100: train_loss=0.000671

      epoch  93/100: train_loss=0.000664

      epoch  94/100: train_loss=0.000674

      epoch  95/100: train_loss=0.000672, val_loss=0.000759, IC=-0.0214

      epoch  96/100: train_loss=0.000666

      epoch  97/100: train_loss=0.000673

      epoch  98/100: train_loss=0.000670

      epoch  99/100: train_loss=0.000670

      epoch 100/100: train_loss=0.000675, val_loss=0.000759, IC=-0.0218

      best_ep=10, IC=+0.0163 (77.8s, 20 checkpoints)

  Fold 5: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.317631

      epoch   2/100: train_loss=0.326477

      epoch   3/100: train_loss=0.097445

      epoch   4/100: train_loss=0.048272

      epoch   5/100: train_loss=0.035502, val_loss=0.014377, IC=+0.0022

      epoch   6/100: train_loss=0.026825

      epoch   7/100: train_loss=0.022186

      epoch   8/100: train_loss=0.018462

      epoch   9/100: train_loss=0.016314

      epoch  10/100: train_loss=0.014077, val_loss=0.003883, IC=-0.0489

      epoch  11/100: train_loss=0.012377

      epoch  12/100: train_loss=0.011166

      epoch  13/100: train_loss=0.010146

      epoch  14/100: train_loss=0.009111

      epoch  15/100: train_loss=0.008198, val_loss=0.002138, IC=-0.0520

      epoch  16/100: train_loss=0.007390

      epoch  17/100: train_loss=0.006558

      epoch  18/100: train_loss=0.006044

      epoch  19/100: train_loss=0.005459

      epoch  20/100: train_loss=0.005007, val_loss=0.001270, IC=-0.0490

      epoch  21/100: train_loss=0.004602

      epoch  22/100: train_loss=0.004262

      epoch  23/100: train_loss=0.003887

      epoch  24/100: train_loss=0.003521

      epoch  25/100: train_loss=0.003364, val_loss=0.000815, IC=-0.0469

      epoch  26/100: train_loss=0.003027

      epoch  27/100: train_loss=0.002806

      epoch  28/100: train_loss=0.002644

      epoch  29/100: train_loss=0.002466

      epoch  30/100: train_loss=0.002277, val_loss=0.000597, IC=-0.0392

      epoch  31/100: train_loss=0.002179

      epoch  32/100: train_loss=0.002023

      epoch  33/100: train_loss=0.001916

      epoch  34/100: train_loss=0.001786

      epoch  35/100: train_loss=0.001709, val_loss=0.000506, IC=-0.0351

      epoch  36/100: train_loss=0.001588

      epoch  37/100: train_loss=0.001534

      epoch  38/100: train_loss=0.001476

      epoch  39/100: train_loss=0.001393

      epoch  40/100: train_loss=0.001338, val_loss=0.000449, IC=-0.0405

      epoch  41/100: train_loss=0.001276

      epoch  42/100: train_loss=0.001231

      epoch  43/100: train_loss=0.001168

      epoch  44/100: train_loss=0.001127

      epoch  45/100: train_loss=0.001091, val_loss=0.000414, IC=-0.0295

      epoch  46/100: train_loss=0.001077

      epoch  47/100: train_loss=0.001005

      epoch  48/100: train_loss=0.000999

      epoch  49/100: train_loss=0.000957

      epoch  50/100: train_loss=0.000938, val_loss=0.000398, IC=-0.0261

      epoch  51/100: train_loss=0.000918

      epoch  52/100: train_loss=0.000907

      epoch  53/100: train_loss=0.000890

      epoch  54/100: train_loss=0.000870

      epoch  55/100: train_loss=0.000851, val_loss=0.000390, IC=-0.0317

      epoch  56/100: train_loss=0.000836

      epoch  57/100: train_loss=0.000819

      epoch  58/100: train_loss=0.000805

      epoch  59/100: train_loss=0.000794

      epoch  60/100: train_loss=0.000796, val_loss=0.000384, IC=-0.0329

      epoch  61/100: train_loss=0.000779

      epoch  62/100: train_loss=0.000770

      epoch  63/100: train_loss=0.000775

      epoch  64/100: train_loss=0.000762

      epoch  65/100: train_loss=0.000758, val_loss=0.000380, IC=-0.0378

      epoch  66/100: train_loss=0.000738

      epoch  67/100: train_loss=0.000739

      epoch  68/100: train_loss=0.000740

      epoch  69/100: train_loss=0.000733

      epoch  70/100: train_loss=0.000721, val_loss=0.000379, IC=-0.0444

      epoch  71/100: train_loss=0.000729

      epoch  72/100: train_loss=0.000712

      epoch  73/100: train_loss=0.000719

      epoch  74/100: train_loss=0.000701

      epoch  75/100: train_loss=0.000711, val_loss=0.000377, IC=-0.0393

      epoch  76/100: train_loss=0.000704

      epoch  77/100: train_loss=0.000704

      epoch  78/100: train_loss=0.000699

      epoch  79/100: train_loss=0.000696

      epoch  80/100: train_loss=0.000688, val_loss=0.000377, IC=-0.0419

      epoch  81/100: train_loss=0.000696

      epoch  82/100: train_loss=0.000690

      epoch  83/100: train_loss=0.000695

      epoch  84/100: train_loss=0.000696

      epoch  85/100: train_loss=0.000687, val_loss=0.000377, IC=-0.0438

      epoch  86/100: train_loss=0.000685

      epoch  87/100: train_loss=0.000684

      epoch  88/100: train_loss=0.000684

      epoch  89/100: train_loss=0.000689

      epoch  90/100: train_loss=0.000683, val_loss=0.000376, IC=-0.0441

      epoch  91/100: train_loss=0.000683

      epoch  92/100: train_loss=0.000687

      epoch  93/100: train_loss=0.000685

      epoch  94/100: train_loss=0.000685

      epoch  95/100: train_loss=0.000678, val_loss=0.000376, IC=-0.0442

      epoch  96/100: train_loss=0.000687

      epoch  97/100: train_loss=0.000678

      epoch  98/100: train_loss=0.000673

      epoch  99/100: train_loss=0.000683

      epoch 100/100: train_loss=0.000687, val_loss=0.000376, IC=-0.0438

      best_ep=5, IC=+0.0022 (115.0s, 20 checkpoints)

  Fold 6: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.151746

      epoch   2/100: train_loss=0.087275

      epoch   3/100: train_loss=0.060028

      epoch   4/100: train_loss=0.042581

      epoch   5/100: train_loss=0.031003, val_loss=0.013787, IC=+0.0263

      epoch   6/100: train_loss=0.023442

      epoch   7/100: train_loss=0.018502

      epoch   8/100: train_loss=0.014910

      epoch   9/100: train_loss=0.012365

      epoch  10/100: train_loss=0.010158, val_loss=0.004835, IC=+0.0068

      epoch  11/100: train_loss=0.008703

      epoch  12/100: train_loss=0.007342

      epoch  13/100: train_loss=0.006424

      epoch  14/100: train_loss=0.005350

      epoch  15/100: train_loss=0.004629, val_loss=0.002510, IC=-0.0281

      epoch  16/100: train_loss=0.004120

      epoch  17/100: train_loss=0.003537

      epoch  18/100: train_loss=0.003177

      epoch  19/100: train_loss=0.002760

      epoch  20/100: train_loss=0.002453, val_loss=0.001765, IC=-0.0543

      epoch  21/100: train_loss=0.002224

      epoch  22/100: train_loss=0.002020

      epoch  23/100: train_loss=0.001775

      epoch  24/100: train_loss=0.001587

      epoch  25/100: train_loss=0.001482, val_loss=0.001427, IC=-0.0857

      epoch  26/100: train_loss=0.001346

      epoch  27/100: train_loss=0.001234

      epoch  28/100: train_loss=0.001117

      epoch  29/100: train_loss=0.001052

      epoch  30/100: train_loss=0.000976, val_loss=0.001264, IC=-0.1104

      epoch  31/100: train_loss=0.000924

      epoch  32/100: train_loss=0.000858

      epoch  33/100: train_loss=0.000815

      epoch  34/100: train_loss=0.000779

      epoch  35/100: train_loss=0.000742, val_loss=0.001172, IC=-0.1089

      epoch  36/100: train_loss=0.000701

      epoch  37/100: train_loss=0.000666

      epoch  38/100: train_loss=0.000656

      epoch  39/100: train_loss=0.000633

      epoch  40/100: train_loss=0.000615, val_loss=0.001142, IC=-0.0787

      epoch  41/100: train_loss=0.000593

      epoch  42/100: train_loss=0.000583

      epoch  43/100: train_loss=0.000567

      epoch  44/100: train_loss=0.000556

      epoch  45/100: train_loss=0.000548, val_loss=0.001105, IC=-0.0615

      epoch  46/100: train_loss=0.000538

      epoch  47/100: train_loss=0.000532

      epoch  48/100: train_loss=0.000523

      epoch  49/100: train_loss=0.000514

      epoch  50/100: train_loss=0.000509, val_loss=0.001097, IC=-0.0377

      epoch  51/100: train_loss=0.000502

      epoch  52/100: train_loss=0.000498

      epoch  53/100: train_loss=0.000499

      epoch  54/100: train_loss=0.000493

      epoch  55/100: train_loss=0.000489, val_loss=0.001091, IC=-0.0343

      epoch  56/100: train_loss=0.000484

      epoch  57/100: train_loss=0.000479

      epoch  58/100: train_loss=0.000481

      epoch  59/100: train_loss=0.000479

      epoch  60/100: train_loss=0.000474, val_loss=0.001090, IC=-0.0325

      epoch  61/100: train_loss=0.000475

      epoch  62/100: train_loss=0.000473

      epoch  63/100: train_loss=0.000475

      epoch  64/100: train_loss=0.000469

      epoch  65/100: train_loss=0.000471, val_loss=0.001081, IC=-0.0342

      epoch  66/100: train_loss=0.000468

      epoch  67/100: train_loss=0.000468

      epoch  68/100: train_loss=0.000464

      epoch  69/100: train_loss=0.000465

      epoch  70/100: train_loss=0.000462, val_loss=0.001078, IC=-0.0355

      epoch  71/100: train_loss=0.000463

      epoch  72/100: train_loss=0.000462

      epoch  73/100: train_loss=0.000462

      epoch  74/100: train_loss=0.000463

      epoch  75/100: train_loss=0.000460, val_loss=0.001071, IC=-0.0342

      epoch  76/100: train_loss=0.000460

      epoch  77/100: train_loss=0.000461

      epoch  78/100: train_loss=0.000459

      epoch  79/100: train_loss=0.000458

      epoch  80/100: train_loss=0.000460, val_loss=0.001078, IC=-0.0361

      epoch  81/100: train_loss=0.000460

      epoch  82/100: train_loss=0.000459

      epoch  83/100: train_loss=0.000460

      epoch  84/100: train_loss=0.000458

      epoch  85/100: train_loss=0.000459, val_loss=0.001076, IC=-0.0357

      epoch  86/100: train_loss=0.000456

      epoch  87/100: train_loss=0.000458

      epoch  88/100: train_loss=0.000458

      epoch  89/100: train_loss=0.000455

      epoch  90/100: train_loss=0.000458, val_loss=0.001076, IC=-0.0346

      epoch  91/100: train_loss=0.000457

      epoch  92/100: train_loss=0.000459

      epoch  93/100: train_loss=0.000457

      epoch  94/100: train_loss=0.000458

      epoch  95/100: train_loss=0.000457, val_loss=0.001077, IC=-0.0345

      epoch  96/100: train_loss=0.000458

      epoch  97/100: train_loss=0.000457

      epoch  98/100: train_loss=0.000456

      epoch  99/100: train_loss=0.000456

      epoch 100/100: train_loss=0.000456, val_loss=0.001077, IC=-0.0344

      best_ep=5, IC=+0.0263 (119.7s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,180 seq across 20 symbols
    val=4,740 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.245096

      epoch   2/100: train_loss=0.079407

      epoch   3/100: train_loss=0.045825

      epoch   4/100: train_loss=0.031841

      epoch   5/100: train_loss=0.022955, val_loss=0.006850, IC=+0.1295

      epoch   6/100: train_loss=0.018077

      epoch   7/100: train_loss=0.015228

      epoch   8/100: train_loss=0.013010

      epoch   9/100: train_loss=0.011153

      epoch  10/100: train_loss=0.009531, val_loss=0.002293, IC=+0.0692

      epoch  11/100: train_loss=0.007876

      epoch  12/100: train_loss=0.006787

      epoch  13/100: train_loss=0.005878

      epoch  14/100: train_loss=0.005188

      epoch  15/100: train_loss=0.004690, val_loss=0.001149, IC=+0.0565

      epoch  16/100: train_loss=0.004000

      epoch  17/100: train_loss=0.003483

      epoch  18/100: train_loss=0.003173

      epoch  19/100: train_loss=0.002812

      epoch  20/100: train_loss=0.002487, val_loss=0.000707, IC=+0.0589

      epoch  21/100: train_loss=0.002248

      epoch  22/100: train_loss=0.002061

      epoch  23/100: train_loss=0.001816

      epoch  24/100: train_loss=0.001659

      epoch  25/100: train_loss=0.001515, val_loss=0.000543, IC=+0.0603

      epoch  26/100: train_loss=0.001414

      epoch  27/100: train_loss=0.001283

      epoch  28/100: train_loss=0.001211

      epoch  29/100: train_loss=0.001117

      epoch  30/100: train_loss=0.001047, val_loss=0.000479, IC=+0.0813

      epoch  31/100: train_loss=0.000983

      epoch  32/100: train_loss=0.000935

      epoch  33/100: train_loss=0.000894

      epoch  34/100: train_loss=0.000840

      epoch  35/100: train_loss=0.000811, val_loss=0.000454, IC=+0.0894

      epoch  36/100: train_loss=0.000788

      epoch  37/100: train_loss=0.000753

      epoch  38/100: train_loss=0.000728

      epoch  39/100: train_loss=0.000709

      epoch  40/100: train_loss=0.000697, val_loss=0.000445, IC=+0.0935

      epoch  41/100: train_loss=0.000677

      epoch  42/100: train_loss=0.000659

      epoch  43/100: train_loss=0.000651

      epoch  44/100: train_loss=0.000638

      epoch  45/100: train_loss=0.000628, val_loss=0.000443, IC=+0.0941

      epoch  46/100: train_loss=0.000627

      epoch  47/100: train_loss=0.000610

      epoch  48/100: train_loss=0.000602

      epoch  49/100: train_loss=0.000603

      epoch  50/100: train_loss=0.000594, val_loss=0.000441, IC=+0.1199

      epoch  51/100: train_loss=0.000592

      epoch  52/100: train_loss=0.000582

      epoch  53/100: train_loss=0.000582

      epoch  54/100: train_loss=0.000579

      epoch  55/100: train_loss=0.000574, val_loss=0.000442, IC=+0.1100

      epoch  56/100: train_loss=0.000571

      epoch  57/100: train_loss=0.000570

      epoch  58/100: train_loss=0.000565

      epoch  59/100: train_loss=0.000565

      epoch  60/100: train_loss=0.000566, val_loss=0.000441, IC=+0.0993

      epoch  61/100: train_loss=0.000560

      epoch  62/100: train_loss=0.000563

      epoch  63/100: train_loss=0.000560

      epoch  64/100: train_loss=0.000560

      epoch  65/100: train_loss=0.000557, val_loss=0.000444, IC=+0.0936

      epoch  66/100: train_loss=0.000555

      epoch  67/100: train_loss=0.000556

      epoch  68/100: train_loss=0.000551

      epoch  69/100: train_loss=0.000556

      epoch  70/100: train_loss=0.000553, val_loss=0.000442, IC=+0.0971

      epoch  71/100: train_loss=0.000554

      epoch  72/100: train_loss=0.000553

      epoch  73/100: train_loss=0.000550

      epoch  74/100: train_loss=0.000550

      epoch  75/100: train_loss=0.000549, val_loss=0.000443, IC=+0.0861

      epoch  76/100: train_loss=0.000550

      epoch  77/100: train_loss=0.000548

      epoch  78/100: train_loss=0.000551

      epoch  79/100: train_loss=0.000550

      epoch  80/100: train_loss=0.000550, val_loss=0.000444, IC=+0.0877

      epoch  81/100: train_loss=0.000547

      epoch  82/100: train_loss=0.000546

      epoch  83/100: train_loss=0.000549

      epoch  84/100: train_loss=0.000546

      epoch  85/100: train_loss=0.000548, val_loss=0.000443, IC=+0.0926

      epoch  86/100: train_loss=0.000545

      epoch  87/100: train_loss=0.000548

      epoch  88/100: train_loss=0.000550

      epoch  89/100: train_loss=0.000547

      epoch  90/100: train_loss=0.000547, val_loss=0.000443, IC=+0.0952

      epoch  91/100: train_loss=0.000546

      epoch  92/100: train_loss=0.000548

      epoch  93/100: train_loss=0.000546

      epoch  94/100: train_loss=0.000549

      epoch  95/100: train_loss=0.000547, val_loss=0.000443, IC=+0.0934

      epoch  96/100: train_loss=0.000547

      epoch  97/100: train_loss=0.000547

      epoch  98/100: train_loss=0.000546

      epoch  99/100: train_loss=0.000546

      epoch 100/100: train_loss=0.000546, val_loss=0.000443, IC=+0.0943

      best_ep=5, IC=+0.1295 (114.0s, 20 checkpoints)

  nlinear: best_epoch=5, IC=-0.0019 (719.7s)

  Best: nlinear @ epoch 5 (IC=-0.0019)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/acb22e8ad2b9/diagnostics

shape: (60, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean   ┆ ic_t      ┆ training_ ┆ predicti │
│ ---       ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---       ┆ ---       ┆ hash      ┆ on_hash  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ i64       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 5         ┆ … ┆ -0.00532  ┆ -0.62251  ┆ e81915391 ┆ 2d40c8d0 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4a7       ┆ 07d5     │
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 10        ┆ … ┆ -0.009135 ┆ -1.129905 ┆ e81915391 ┆ 8ef3bde9 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4a7       ┆ 0395     │
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 15        ┆ … ┆ -0.013354 ┆ -2.057821 ┆ e81915391 ┆ 0a255def │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4a7       ┆ e5e9     │
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 20        ┆ … ┆ -0.010913 ┆ -1.878373 ┆ e81915391 ┆ 0016f5ca │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4a7       ┆ d4b6     │
│ fwd_ret_1 ┆ nlinear   ┆ epoch     ┆ 25        ┆ … ┆ -0.009541 ┆ -1.25812  ┆ e81915391 ┆ bdad9d8a │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 4a7       ┆ c4eb     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 80        ┆ … ┆ -0.020849 ┆ -1.387619 ┆ 3dd0db7c7 ┆ 3c28fb5b │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ ac4       ┆ 1b04     │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 85        ┆ … ┆ -0.022006 ┆ -1.478283 ┆ 3dd0db7c7 ┆ 3c6edc67 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ ac4       ┆ f912     │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 90        ┆ … ┆ -0.021652 ┆ -1.501848 ┆ 3dd0db7c7 ┆ 4304ac6a │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ ac4       ┆ 53f8     │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 95        ┆ … ┆ -0.022085 ┆ -1.506117 ┆ 3dd0db7c7 ┆ cba3109e │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ ac4       ┆ 01b8     │
│ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ 100       ┆ … ┆ -0.022106 ┆ -1.501849 ┆ 3dd0db7c7 ┆ 38e5b890 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ ac4       ┆ 50aa     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Verify checkpoint reload

Repeating the request validates the fitted-state digests and returns the same prediction
identities. The notebook never reconstructs another family from an empty cache path.

In [6]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("NLinear checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview sequence checkpoints remain outside official comparisons.")

Official prediction population: ea2d3f2ce99d

## Key takeaways

- NLinear and TCN use the same sequence eligibility contract but keep separate model identities.
- Gaps remove affected windows instead of being hidden by positional indexing.
- Stored weights reproduce every declared checkpoint without retraining.