# NLinear - FX Pairs

NLinear forecasts from a fixed consecutive history after subtracting the last observed level. The
transformation focuses the model on changes over the lookback window. This notebook constructs
only the NLinear request; comparisons with TCN, TabM, trees, and linear models are deferred to
`12_model_analysis`, where the complete registered population is available.

**Learning objectives**

- Resolve NLinear's lookback, normalization, and checkpoint schedule before fitting.
- Use the shared gap-safe sequence eligibility instead of positional row windows.
- Prove weight reload and catalog handoff for every declared epoch.

**Book reference**: Chapter 13, Section 13.4

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published NLinear FX configuration."""

import json

import polars as pl
import yaml

from case_studies.research import ExecutionTier, Study, plan_models
from utils.modeling import load_configs
from utils.paths import get_case_study_dir
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
LOOKBACK = 0
BATCH_SIZE = 0
DEVICE = "cuda"
SEED = 42

## Resolve one forecasting request

The shared runner derives fold boundaries from the finalized label timeline. A missing daily
observation invalidates every lookback window that crosses it, so validation coverage can be
smaller than the raw validation panel while still being exact.

In [3]:
set_global_seeds(SEED)
case_dir = get_case_study_dir(CASE_STUDY_ID)
setup = yaml.safe_load((case_dir / "config" / "setup.yaml").read_text())
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [setup["labels"]["primary"], *setup["labels"].get("variants", [])]
)

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

reductions = {
    **({"folds": list(range(MAX_FOLDS))} if MAX_FOLDS else {}),
    **({"max_symbols": MAX_SYMBOLS} if MAX_SYMBOLS else {}),
}
tier = ExecutionTier.PREVIEW if reductions else ExecutionTier.CANONICAL
overrides = {
    "device": DEVICE,
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
    **({"lookback": LOOKBACK} if LOOKBACK else {}),
}
study = Study.regenerate(CASE_STUDY_ID)
ARCHITECTURE = "nlinear"
menu = {
    label: [
        config["config_name"]
        for config in load_configs(CASE_STUDY_ID, label, family="deep_learning")
    ]
    for label in labels
}
uncovered = {label: sorted(set(names) - {ARCHITECTURE}) for label, names in menu.items()}
for label, names in menu.items():
    if ARCHITECTURE not in names:
        raise RuntimeError(
            f"{ARCHITECTURE} is not in the configured deep_learning menu for {label}: {names}"
        )

requests = [
    study.model(
        family="deep_learning",
        label=label,
        config_name=ARCHITECTURE,
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label in labels
]
plan = plan_models(study, requests=requests)

# This notebook owes one architecture on every configured label. The rest of the family menu is
# named here rather than left implicit, because a population that is short a configured model is
# otherwise indistinguishable from a complete one.
configured = {(label, ARCHITECTURE) for label in labels}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        f"the plan does not match this notebook's declared coverage; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )
specs = {member.label: json.loads(member.spec_json) for member in plan.members}
computations = {label: spec.get("computation", spec) for label, spec in specs.items()}
computation = computations[labels[0]]

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {computation['numerics']['device']}")
print(f"Lookback: {computation['preprocessing']['lookback']} consecutive daily observations")
for horizon, values in computations.items():
    print(f"Eligible validation rows, {horizon}: {values['expected_prediction_keys']['n_rows']:,}")
for horizon, names in uncovered.items():
    print(
        f"Configured deep_learning models this notebook does not run, {horizon}: {names or 'none'}"
    )

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda
Lookback: 60 consecutive daily observations
Eligible validation rows, fwd_ret_1d: 41,260
Eligible validation rows, fwd_ret_5d: 41,180
Eligible validation rows, fwd_ret_21d: 40,860
Configured deep_learning models this notebook does not run, fwd_ret_1d: ['lstm_h64', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_5d: ['lstm_h64', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_21d: ['lstm_h64', 'tcn']

## Inspect identity-bearing settings

The model request records its architecture parameters, exact folds, expected prediction-key
digest, and every epoch that must remain reproducible from stored weights.

In [4]:
checkpoint_schedule = pl.DataFrame(computation["checkpoint_schedule"])
pl.DataFrame(
    {
        "label": list(computations),
        "architecture": [c["model"]["class"] for c in computations.values()],
        "gap_policy": [c["preprocessing"]["gap_policy"] for c in computations.values()],
        "validation_folds": [
            c["expected_prediction_keys"]["n_folds"] for c in computations.values()
        ],
        "key_digest": [c["expected_prediction_keys"]["digest"] for c in computations.values()],
    }
)
checkpoint_schedule

shape: (20, 2)
┌───────┬───────┐
│ kind  ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ epoch ┆ 5     │
│ epoch ┆ 10    │
│ epoch ┆ 15    │
│ epoch ┆ 20    │
│ epoch ┆ 25    │
│ …     ┆ …     │
│ epoch ┆ 80    │
│ epoch ┆ 85    │
│ epoch ┆ 90    │
│ epoch ┆ 95    │
│ epoch ┆ 100   │
└───────┴───────┘

## Record the official population, then fit or reload NLinear

The runner validates every fold separately before any checkpoint becomes downstream-selectable.
Checkpoint rank correlation is retained as a diagnostic and does not remove other epochs.

In [5]:
if len(plan.expected_prediction_hashes) != checkpoint_schedule.height * len(labels):
    raise RuntimeError("the plan does not cover every declared epoch checkpoint on every label")
population = (
    plan.create_population(name=f"{CASE_STUDY_ID}:{'+'.join(labels)}:nlinear")
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
catalog = execution.catalog_rows.sort("label", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial NLinear checkpoints cannot pass to backtesting")
for label in labels:
    published = catalog.filter(pl.col("label") == label).get_column("checkpoint_value").to_list()
    if published != checkpoint_schedule["value"].to_list():
        raise RuntimeError(f"catalog checkpoints for {label} differ from the resolved request")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,140 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.499876

      epoch   2/100: train_loss=0.240427

      epoch   3/100: train_loss=0.109742

      epoch   4/100: train_loss=0.052260

      epoch   5/100: train_loss=0.031561, val_loss=0.020755, IC=+0.0420

      epoch   6/100: train_loss=0.025360

      epoch   7/100: train_loss=0.018752

      epoch   8/100: train_loss=0.016823

      epoch   9/100: train_loss=0.015441

      epoch  10/100: train_loss=0.013791, val_loss=0.003809, IC=+0.0412

      epoch  11/100: train_loss=0.012336

      epoch  12/100: train_loss=0.010843

      epoch  13/100: train_loss=0.009841

      epoch  14/100: train_loss=0.009016

      epoch  15/100: train_loss=0.008516, val_loss=0.002344, IC=+0.0367

      epoch  16/100: train_loss=0.007577

      epoch  17/100: train_loss=0.007662

      epoch  18/100: train_loss=0.007007

      epoch  19/100: train_loss=0.006026

      epoch  20/100: train_loss=0.005551, val_loss=0.001185, IC=+0.0332

      epoch  21/100: train_loss=0.005804

      epoch  22/100: train_loss=0.004531

      epoch  23/100: train_loss=0.004161

      epoch  24/100: train_loss=0.003978

      epoch  25/100: train_loss=0.003545, val_loss=0.000582, IC=+0.0375

      epoch  26/100: train_loss=0.003461

      epoch  27/100: train_loss=0.003088

      epoch  28/100: train_loss=0.003070

      epoch  29/100: train_loss=0.002698

      epoch  30/100: train_loss=0.002407, val_loss=0.000530, IC=+0.0245

      epoch  31/100: train_loss=0.002481

      epoch  32/100: train_loss=0.002214

      epoch  33/100: train_loss=0.001829

      epoch  34/100: train_loss=0.001999

      epoch  35/100: train_loss=0.001618, val_loss=0.000306, IC=+0.0198

      epoch  36/100: train_loss=0.001555

      epoch  37/100: train_loss=0.001320

      epoch  38/100: train_loss=0.001267

      epoch  39/100: train_loss=0.001218

      epoch  40/100: train_loss=0.001194, val_loss=0.000170, IC=+0.0294

      epoch  41/100: train_loss=0.001085

      epoch  42/100: train_loss=0.000972

      epoch  43/100: train_loss=0.000977

      epoch  44/100: train_loss=0.001254

      epoch  45/100: train_loss=0.000854, val_loss=0.000167, IC=+0.0161

      epoch  46/100: train_loss=0.000871

      epoch  47/100: train_loss=0.000705

      epoch  48/100: train_loss=0.000655

      epoch  49/100: train_loss=0.000815

      epoch  50/100: train_loss=0.000632, val_loss=0.000097, IC=+0.0190

      epoch  51/100: train_loss=0.000542

      epoch  52/100: train_loss=0.000537

      epoch  53/100: train_loss=0.000533

      epoch  54/100: train_loss=0.000570

      epoch  55/100: train_loss=0.000468, val_loss=0.000089, IC=+0.0291

      epoch  56/100: train_loss=0.000517

      epoch  57/100: train_loss=0.000422

      epoch  58/100: train_loss=0.000417

      epoch  59/100: train_loss=0.000389

      epoch  60/100: train_loss=0.000425, val_loss=0.000064, IC=+0.0304

      epoch  61/100: train_loss=0.000438

      epoch  62/100: train_loss=0.000352

      epoch  63/100: train_loss=0.000331

      epoch  64/100: train_loss=0.000365

      epoch  65/100: train_loss=0.000346, val_loss=0.000055, IC=+0.0368

      epoch  66/100: train_loss=0.000312

      epoch  67/100: train_loss=0.000336

      epoch  68/100: train_loss=0.000285

      epoch  69/100: train_loss=0.000272

      epoch  70/100: train_loss=0.000271, val_loss=0.000051, IC=+0.0323

      epoch  71/100: train_loss=0.000346

      epoch  72/100: train_loss=0.000288

      epoch  73/100: train_loss=0.000335

      epoch  74/100: train_loss=0.000250

      epoch  75/100: train_loss=0.000256, val_loss=0.000046, IC=+0.0445

      epoch  76/100: train_loss=0.000231

      epoch  77/100: train_loss=0.000264

      epoch  78/100: train_loss=0.000226

      epoch  79/100: train_loss=0.000224

      epoch  80/100: train_loss=0.000219, val_loss=0.000046, IC=+0.0255

      epoch  81/100: train_loss=0.000240

      epoch  82/100: train_loss=0.000214

      epoch  83/100: train_loss=0.000224

      epoch  84/100: train_loss=0.000213

      epoch  85/100: train_loss=0.000233, val_loss=0.000045, IC=+0.0316

      epoch  86/100: train_loss=0.000205

      epoch  87/100: train_loss=0.000211

      epoch  88/100: train_loss=0.000207

      epoch  89/100: train_loss=0.000200

      epoch  90/100: train_loss=0.000200, val_loss=0.000044, IC=+0.0337

      epoch  91/100: train_loss=0.000228

      epoch  92/100: train_loss=0.000203

      epoch  93/100: train_loss=0.000194

      epoch  94/100: train_loss=0.000211

      epoch  95/100: train_loss=0.000219, val_loss=0.000042, IC=+0.0381

      epoch  96/100: train_loss=0.000243

      epoch  97/100: train_loss=0.000217

      epoch  98/100: train_loss=0.000192

      epoch  99/100: train_loss=0.000208

      epoch 100/100: train_loss=0.000216, val_loss=0.000043, IC=+0.0359

      best_ep=75, IC=+0.0445 (42.6s, 20 checkpoints)

  Fold 1: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.245961

      epoch   2/100: train_loss=0.111254

      epoch   3/100: train_loss=0.061864

      epoch   4/100: train_loss=0.042455

      epoch   5/100: train_loss=0.027085, val_loss=0.108402, IC=+0.0122

      epoch   6/100: train_loss=0.022755

      epoch   7/100: train_loss=0.020227

      epoch   8/100: train_loss=0.015521

      epoch   9/100: train_loss=0.013320

      epoch  10/100: train_loss=0.015730, val_loss=0.027461, IC=+0.0057

      epoch  11/100: train_loss=0.010964

      epoch  12/100: train_loss=0.009226

      epoch  13/100: train_loss=0.007902

      epoch  14/100: train_loss=0.006707

      epoch  15/100: train_loss=0.006137, val_loss=0.009827, IC=+0.0021

      epoch  16/100: train_loss=0.005865

      epoch  17/100: train_loss=0.005052

      epoch  18/100: train_loss=0.004731

      epoch  19/100: train_loss=0.004094

      epoch  20/100: train_loss=0.003795, val_loss=0.004530, IC=-0.0034

      epoch  21/100: train_loss=0.003304

      epoch  22/100: train_loss=0.003007

      epoch  23/100: train_loss=0.002964

      epoch  24/100: train_loss=0.002672

      epoch  25/100: train_loss=0.002483, val_loss=0.002928, IC=+0.0023

      epoch  26/100: train_loss=0.002113

      epoch  27/100: train_loss=0.001959

      epoch  28/100: train_loss=0.001784

      epoch  29/100: train_loss=0.001814

      epoch  30/100: train_loss=0.001829, val_loss=0.001278, IC=+0.0103

      epoch  31/100: train_loss=0.001612

      epoch  32/100: train_loss=0.001476

      epoch  33/100: train_loss=0.001258

      epoch  34/100: train_loss=0.001172

      epoch  35/100: train_loss=0.000991, val_loss=0.000669, IC=+0.0047

      epoch  36/100: train_loss=0.000963

      epoch  37/100: train_loss=0.000906

      epoch  38/100: train_loss=0.000816

      epoch  39/100: train_loss=0.000793

      epoch  40/100: train_loss=0.000733, val_loss=0.000474, IC=+0.0020

      epoch  41/100: train_loss=0.000657

      epoch  42/100: train_loss=0.000635

      epoch  43/100: train_loss=0.000556

      epoch  44/100: train_loss=0.000517

      epoch  45/100: train_loss=0.000509, val_loss=0.000287, IC=+0.0160

      epoch  46/100: train_loss=0.000481

      epoch  47/100: train_loss=0.000453

      epoch  48/100: train_loss=0.000576

      epoch  49/100: train_loss=0.000460

      epoch  50/100: train_loss=0.000388, val_loss=0.000174, IC=+0.0142

      epoch  51/100: train_loss=0.000344

      epoch  52/100: train_loss=0.000320

      epoch  53/100: train_loss=0.000308

      epoch  54/100: train_loss=0.000276

      epoch  55/100: train_loss=0.000383, val_loss=0.000138, IC=+0.0169

      epoch  56/100: train_loss=0.000260

      epoch  57/100: train_loss=0.000249

      epoch  58/100: train_loss=0.000252

      epoch  59/100: train_loss=0.000223

      epoch  60/100: train_loss=0.000219, val_loss=0.000099, IC=+0.0211

      epoch  61/100: train_loss=0.000202

      epoch  62/100: train_loss=0.000198

      epoch  63/100: train_loss=0.000191

      epoch  64/100: train_loss=0.000189

      epoch  65/100: train_loss=0.000172, val_loss=0.000099, IC=+0.0097

      epoch  66/100: train_loss=0.000176

      epoch  67/100: train_loss=0.000166

      epoch  68/100: train_loss=0.000183

      epoch  69/100: train_loss=0.000154

      epoch  70/100: train_loss=0.000149, val_loss=0.000108, IC=+0.0204

      epoch  71/100: train_loss=0.000153

      epoch  72/100: train_loss=0.000142

      epoch  73/100: train_loss=0.000174

      epoch  74/100: train_loss=0.000168

      epoch  75/100: train_loss=0.000143, val_loss=0.000083, IC=+0.0193

      epoch  76/100: train_loss=0.000133

      epoch  77/100: train_loss=0.000145

      epoch  78/100: train_loss=0.000130

      epoch  79/100: train_loss=0.000129

      epoch  80/100: train_loss=0.000117, val_loss=0.000078, IC=+0.0054

      epoch  81/100: train_loss=0.000125

      epoch  82/100: train_loss=0.000117

      epoch  83/100: train_loss=0.000122

      epoch  84/100: train_loss=0.000122

      epoch  85/100: train_loss=0.000119, val_loss=0.000077, IC=+0.0048

      epoch  86/100: train_loss=0.000124

      epoch  87/100: train_loss=0.000116

      epoch  88/100: train_loss=0.000115

      epoch  89/100: train_loss=0.000116

      epoch  90/100: train_loss=0.000112, val_loss=0.000077, IC=+0.0107

      epoch  91/100: train_loss=0.000116

      epoch  92/100: train_loss=0.000115

      epoch  93/100: train_loss=0.000117

      epoch  94/100: train_loss=0.000110

      epoch  95/100: train_loss=0.000157, val_loss=0.000077, IC=+0.0148

      epoch  96/100: train_loss=0.000118

      epoch  97/100: train_loss=0.000117

      epoch  98/100: train_loss=0.000115

      epoch  99/100: train_loss=0.000121

      epoch 100/100: train_loss=0.000109, val_loss=0.000076, IC=+0.0144

      best_ep=60, IC=+0.0211 (44.6s, 20 checkpoints)

  Fold 2: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.170913

      epoch   2/100: train_loss=0.064719

      epoch   3/100: train_loss=0.041366

      epoch   4/100: train_loss=0.028206

      epoch   5/100: train_loss=0.024255, val_loss=0.007895, IC=+0.0523

      epoch   6/100: train_loss=0.019527

      epoch   7/100: train_loss=0.017315

      epoch   8/100: train_loss=0.016749

      epoch   9/100: train_loss=0.013656

      epoch  10/100: train_loss=0.012295, val_loss=0.003728, IC=+0.0399

      epoch  11/100: train_loss=0.019836

      epoch  12/100: train_loss=0.010657

      epoch  13/100: train_loss=0.012121

      epoch  14/100: train_loss=0.009401

      epoch  15/100: train_loss=0.007808, val_loss=0.002319, IC=+0.0362

      epoch  16/100: train_loss=0.010741

      epoch  17/100: train_loss=0.006663

      epoch  18/100: train_loss=0.006069

      epoch  19/100: train_loss=0.005056

      epoch  20/100: train_loss=0.004740, val_loss=0.001270, IC=+0.0306

      epoch  21/100: train_loss=0.004353

      epoch  22/100: train_loss=0.004133

      epoch  23/100: train_loss=0.004300

      epoch  24/100: train_loss=0.003835

      epoch  25/100: train_loss=0.003240, val_loss=0.000740, IC=+0.0329

      epoch  26/100: train_loss=0.002759

      epoch  27/100: train_loss=0.002715

      epoch  28/100: train_loss=0.002486

      epoch  29/100: train_loss=0.002180

      epoch  30/100: train_loss=0.002179, val_loss=0.000465, IC=+0.0223

      epoch  31/100: train_loss=0.001989

      epoch  32/100: train_loss=0.001742

      epoch  33/100: train_loss=0.001637

      epoch  34/100: train_loss=0.001538

      epoch  35/100: train_loss=0.001402, val_loss=0.000245, IC=+0.0247

      epoch  36/100: train_loss=0.001264

      epoch  37/100: train_loss=0.001166

      epoch  38/100: train_loss=0.001110

      epoch  39/100: train_loss=0.001072

      epoch  40/100: train_loss=0.000963, val_loss=0.000224, IC=+0.0189

      epoch  41/100: train_loss=0.000868

      epoch  42/100: train_loss=0.000917

      epoch  43/100: train_loss=0.000884

      epoch  44/100: train_loss=0.000851

      epoch  45/100: train_loss=0.000860, val_loss=0.000142, IC=+0.0134

      epoch  46/100: train_loss=0.000705

      epoch  47/100: train_loss=0.000645

      epoch  48/100: train_loss=0.000597

      epoch  49/100: train_loss=0.000580

      epoch  50/100: train_loss=0.000549, val_loss=0.000086, IC=+0.0263

      epoch  51/100: train_loss=0.000590

      epoch  52/100: train_loss=0.000553

      epoch  53/100: train_loss=0.000471

      epoch  54/100: train_loss=0.000463

      epoch  55/100: train_loss=0.000446, val_loss=0.000063, IC=+0.0310

      epoch  56/100: train_loss=0.000469

      epoch  57/100: train_loss=0.000365

      epoch  58/100: train_loss=0.000340

      epoch  59/100: train_loss=0.000322

      epoch  60/100: train_loss=0.000325, val_loss=0.000054, IC=+0.0282

      epoch  61/100: train_loss=0.000310

      epoch  62/100: train_loss=0.000299

      epoch  63/100: train_loss=0.000349

      epoch  64/100: train_loss=0.000299

      epoch  65/100: train_loss=0.000288, val_loss=0.000057, IC=+0.0197

      epoch  66/100: train_loss=0.000259

      epoch  67/100: train_loss=0.000271

      epoch  68/100: train_loss=0.000243

      epoch  69/100: train_loss=0.000233

      epoch  70/100: train_loss=0.000271, val_loss=0.000043, IC=+0.0206

      epoch  71/100: train_loss=0.000266

      epoch  72/100: train_loss=0.000226

      epoch  73/100: train_loss=0.000298

      epoch  74/100: train_loss=0.000226

      epoch  75/100: train_loss=0.000233, val_loss=0.000037, IC=+0.0209

      epoch  76/100: train_loss=0.000211

      epoch  77/100: train_loss=0.000226

      epoch  78/100: train_loss=0.000212

      epoch  79/100: train_loss=0.000206

      epoch  80/100: train_loss=0.000185, val_loss=0.000036, IC=+0.0225

      epoch  81/100: train_loss=0.000183

      epoch  82/100: train_loss=0.000185

      epoch  83/100: train_loss=0.000183

      epoch  84/100: train_loss=0.000180

      epoch  85/100: train_loss=0.000202, val_loss=0.000035, IC=+0.0202

      epoch  86/100: train_loss=0.000179

      epoch  87/100: train_loss=0.000175

      epoch  88/100: train_loss=0.000180

      epoch  89/100: train_loss=0.000174

      epoch  90/100: train_loss=0.000183, val_loss=0.000035, IC=+0.0194

      epoch  91/100: train_loss=0.000182

      epoch  92/100: train_loss=0.000222

      epoch  93/100: train_loss=0.000198

      epoch  94/100: train_loss=0.000176

      epoch  95/100: train_loss=0.000181, val_loss=0.000034, IC=+0.0197

      epoch  96/100: train_loss=0.000194

      epoch  97/100: train_loss=0.000173

      epoch  98/100: train_loss=0.000217

      epoch  99/100: train_loss=0.000179

      epoch 100/100: train_loss=0.000173, val_loss=0.000034, IC=+0.0176

      best_ep=5, IC=+0.0523 (44.8s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.337393

      epoch   2/100: train_loss=0.071772

      epoch   3/100: train_loss=0.048383

      epoch   4/100: train_loss=0.035189

      epoch   5/100: train_loss=0.024183, val_loss=0.018189, IC=+0.0156

      epoch   6/100: train_loss=0.021801

      epoch   7/100: train_loss=0.015320

      epoch   8/100: train_loss=0.012913

      epoch   9/100: train_loss=0.010931

      epoch  10/100: train_loss=0.009275, val_loss=0.003554, IC=+0.0214

      epoch  11/100: train_loss=0.008242

      epoch  12/100: train_loss=0.007976

      epoch  13/100: train_loss=0.007020

      epoch  14/100: train_loss=0.006049

      epoch  15/100: train_loss=0.005661, val_loss=0.001622, IC=+0.0075

      epoch  16/100: train_loss=0.005334

      epoch  17/100: train_loss=0.004605

      epoch  18/100: train_loss=0.004083

      epoch  19/100: train_loss=0.003875

      epoch  20/100: train_loss=0.003331, val_loss=0.000928, IC=-0.0082

      epoch  21/100: train_loss=0.003107

      epoch  22/100: train_loss=0.002853

      epoch  23/100: train_loss=0.002512

      epoch  24/100: train_loss=0.002337

      epoch  25/100: train_loss=0.002111, val_loss=0.000576, IC=-0.0115

      epoch  26/100: train_loss=0.001956

      epoch  27/100: train_loss=0.001991

      epoch  28/100: train_loss=0.001744

      epoch  29/100: train_loss=0.001561

      epoch  30/100: train_loss=0.001524, val_loss=0.000383, IC=-0.0098

      epoch  31/100: train_loss=0.001390

      epoch  32/100: train_loss=0.001345

      epoch  33/100: train_loss=0.001169

      epoch  34/100: train_loss=0.001115

      epoch  35/100: train_loss=0.001039, val_loss=0.000314, IC=-0.0206

      epoch  36/100: train_loss=0.000971

      epoch  37/100: train_loss=0.000932

      epoch  38/100: train_loss=0.000894

      epoch  39/100: train_loss=0.000854

      epoch  40/100: train_loss=0.000745, val_loss=0.000245, IC=-0.0163

      epoch  41/100: train_loss=0.000724

      epoch  42/100: train_loss=0.000790

      epoch  43/100: train_loss=0.000664

      epoch  44/100: train_loss=0.000618

      epoch  45/100: train_loss=0.000575, val_loss=0.000193, IC=-0.0279

      epoch  46/100: train_loss=0.000563

      epoch  47/100: train_loss=0.000563

      epoch  48/100: train_loss=0.000502

      epoch  49/100: train_loss=0.000473

      epoch  50/100: train_loss=0.000535, val_loss=0.000167, IC=-0.0257

      epoch  51/100: train_loss=0.000442

      epoch  52/100: train_loss=0.000453

      epoch  53/100: train_loss=0.000470

      epoch  54/100: train_loss=0.000416

      epoch  55/100: train_loss=0.000405, val_loss=0.000139, IC=-0.0188

      epoch  56/100: train_loss=0.000402

      epoch  57/100: train_loss=0.000416

      epoch  58/100: train_loss=0.000370

      epoch  59/100: train_loss=0.000325

      epoch  60/100: train_loss=0.000329, val_loss=0.000121, IC=-0.0244

      epoch  61/100: train_loss=0.000318

      epoch  62/100: train_loss=0.000300

      epoch  63/100: train_loss=0.000291

      epoch  64/100: train_loss=0.000285

      epoch  65/100: train_loss=0.000261, val_loss=0.000106, IC=-0.0245

      epoch  66/100: train_loss=0.000351

      epoch  67/100: train_loss=0.000312

      epoch  68/100: train_loss=0.000295

      epoch  69/100: train_loss=0.000266

      epoch  70/100: train_loss=0.000264, val_loss=0.000102, IC=-0.0248

      epoch  71/100: train_loss=0.000264

      epoch  72/100: train_loss=0.000295

      epoch  73/100: train_loss=0.000228

      epoch  74/100: train_loss=0.000222

      epoch  75/100: train_loss=0.000228, val_loss=0.000092, IC=-0.0264

      epoch  76/100: train_loss=0.000274

      epoch  77/100: train_loss=0.000222

      epoch  78/100: train_loss=0.000230

      epoch  79/100: train_loss=0.000209

      epoch  80/100: train_loss=0.000222, val_loss=0.000094, IC=-0.0291

      epoch  81/100: train_loss=0.000205

      epoch  82/100: train_loss=0.000207

      epoch  83/100: train_loss=0.000231

      epoch  84/100: train_loss=0.000322

      epoch  85/100: train_loss=0.000232, val_loss=0.000088, IC=-0.0201

      epoch  86/100: train_loss=0.000206

      epoch  87/100: train_loss=0.000205

      epoch  88/100: train_loss=0.000210

      epoch  89/100: train_loss=0.000208

      epoch  90/100: train_loss=0.000231, val_loss=0.000088, IC=-0.0247

      epoch  91/100: train_loss=0.000197

      epoch  92/100: train_loss=0.000196

      epoch  93/100: train_loss=0.000198

      epoch  94/100: train_loss=0.000199

      epoch  95/100: train_loss=0.000212, val_loss=0.000088, IC=-0.0225

      epoch  96/100: train_loss=0.000209

      epoch  97/100: train_loss=0.000209

      epoch  98/100: train_loss=0.000202

      epoch  99/100: train_loss=0.000201

      epoch 100/100: train_loss=0.000200, val_loss=0.000088, IC=-0.0219

      best_ep=10, IC=+0.0214 (44.6s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.303968

      epoch   2/100: train_loss=0.125722

      epoch   3/100: train_loss=0.065084

      epoch   4/100: train_loss=0.048837

      epoch   5/100: train_loss=0.035778, val_loss=0.015795, IC=-0.0011

      epoch   6/100: train_loss=0.029921

      epoch   7/100: train_loss=0.025042

      epoch   8/100: train_loss=0.020942

      epoch   9/100: train_loss=0.020500

      epoch  10/100: train_loss=0.015882, val_loss=0.005424, IC=+0.0002

      epoch  11/100: train_loss=0.014953

      epoch  12/100: train_loss=0.012663

      epoch  13/100: train_loss=0.011310

      epoch  14/100: train_loss=0.009932

      epoch  15/100: train_loss=0.008872, val_loss=0.001908, IC=+0.0046

      epoch  16/100: train_loss=0.007658

      epoch  17/100: train_loss=0.007161

      epoch  18/100: train_loss=0.006343

      epoch  19/100: train_loss=0.005997

      epoch  20/100: train_loss=0.004961, val_loss=0.000995, IC=+0.0047

      epoch  21/100: train_loss=0.004556

      epoch  22/100: train_loss=0.005416

      epoch  23/100: train_loss=0.003722

      epoch  24/100: train_loss=0.003467

      epoch  25/100: train_loss=0.003184, val_loss=0.000422, IC=+0.0043

      epoch  26/100: train_loss=0.003094

      epoch  27/100: train_loss=0.002723

      epoch  28/100: train_loss=0.002445

      epoch  29/100: train_loss=0.002187

      epoch  30/100: train_loss=0.001916, val_loss=0.000273, IC=+0.0145

      epoch  31/100: train_loss=0.001856

      epoch  32/100: train_loss=0.001675

      epoch  33/100: train_loss=0.001589

      epoch  34/100: train_loss=0.001437

      epoch  35/100: train_loss=0.001463, val_loss=0.000170, IC=+0.0023

      epoch  36/100: train_loss=0.001269

      epoch  37/100: train_loss=0.001196

      epoch  38/100: train_loss=0.001154

      epoch  39/100: train_loss=0.000924

      epoch  40/100: train_loss=0.000850, val_loss=0.000102, IC=+0.0140

      epoch  41/100: train_loss=0.000830

      epoch  42/100: train_loss=0.000791

      epoch  43/100: train_loss=0.000751

      epoch  44/100: train_loss=0.000627

      epoch  45/100: train_loss=0.000623, val_loss=0.000072, IC=+0.0070

      epoch  46/100: train_loss=0.000618

      epoch  47/100: train_loss=0.000558

      epoch  48/100: train_loss=0.000489

      epoch  49/100: train_loss=0.000514

      epoch  50/100: train_loss=0.000473, val_loss=0.000060, IC=+0.0202

      epoch  51/100: train_loss=0.000417

      epoch  52/100: train_loss=0.000435

      epoch  53/100: train_loss=0.000379

      epoch  54/100: train_loss=0.000647

      epoch  55/100: train_loss=0.000357, val_loss=0.000056, IC=+0.0116

      epoch  56/100: train_loss=0.000339

      epoch  57/100: train_loss=0.000340

      epoch  58/100: train_loss=0.000312

      epoch  59/100: train_loss=0.000277

      epoch  60/100: train_loss=0.000287, val_loss=0.000038, IC=+0.0164

      epoch  61/100: train_loss=0.000252

      epoch  62/100: train_loss=0.000245

      epoch  63/100: train_loss=0.000235

      epoch  64/100: train_loss=0.000240

      epoch  65/100: train_loss=0.000227, val_loss=0.000033, IC=+0.0176

      epoch  66/100: train_loss=0.000260

      epoch  67/100: train_loss=0.000208

      epoch  68/100: train_loss=0.000212

      epoch  69/100: train_loss=0.000214

      epoch  70/100: train_loss=0.000184, val_loss=0.000030, IC=+0.0060

      epoch  71/100: train_loss=0.000179

      epoch  72/100: train_loss=0.000180

      epoch  73/100: train_loss=0.000175

      epoch  74/100: train_loss=0.000182

      epoch  75/100: train_loss=0.000197, val_loss=0.000028, IC=+0.0162

      epoch  76/100: train_loss=0.000163

      epoch  77/100: train_loss=0.000162

      epoch  78/100: train_loss=0.000159

      epoch  79/100: train_loss=0.000157

      epoch  80/100: train_loss=0.000160, val_loss=0.000027, IC=+0.0215

      epoch  81/100: train_loss=0.000181

      epoch  82/100: train_loss=0.000173

      epoch  83/100: train_loss=0.000150

      epoch  84/100: train_loss=0.000149

      epoch  85/100: train_loss=0.000142, val_loss=0.000026, IC=+0.0141

      epoch  86/100: train_loss=0.000140

      epoch  87/100: train_loss=0.000157

      epoch  88/100: train_loss=0.000148

      epoch  89/100: train_loss=0.000675

      epoch  90/100: train_loss=0.000141, val_loss=0.000030, IC=+0.0057

      epoch  91/100: train_loss=0.000150

      epoch  92/100: train_loss=0.000142

      epoch  93/100: train_loss=0.000141

      epoch  94/100: train_loss=0.000168

      epoch  95/100: train_loss=0.000154, val_loss=0.000028, IC=+0.0100

      epoch  96/100: train_loss=0.000141

      epoch  97/100: train_loss=0.000143

      epoch  98/100: train_loss=0.000150

      epoch  99/100: train_loss=0.000293

      epoch 100/100: train_loss=0.000150, val_loss=0.000028, IC=+0.0108

      best_ep=80, IC=+0.0215 (44.6s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.419994

      epoch   2/100: train_loss=0.296011

      epoch   3/100: train_loss=0.095464

      epoch   4/100: train_loss=0.045942

      epoch   5/100: train_loss=0.034511, val_loss=0.011205, IC=-0.0022

      epoch   6/100: train_loss=0.026735

      epoch   7/100: train_loss=0.023748

      epoch   8/100: train_loss=0.018663

      epoch   9/100: train_loss=0.015669

      epoch  10/100: train_loss=0.014802, val_loss=0.003734, IC=+0.0138

      epoch  11/100: train_loss=0.012609

      epoch  12/100: train_loss=0.011146

      epoch  13/100: train_loss=0.009893

      epoch  14/100: train_loss=0.008490

      epoch  15/100: train_loss=0.007576, val_loss=0.002355, IC=+0.0299

      epoch  16/100: train_loss=0.006984

      epoch  17/100: train_loss=0.006533

      epoch  18/100: train_loss=0.006134

      epoch  19/100: train_loss=0.005093

      epoch  20/100: train_loss=0.004857, val_loss=0.001083, IC=+0.0342

      epoch  21/100: train_loss=0.004393

      epoch  22/100: train_loss=0.003915

      epoch  23/100: train_loss=0.003502

      epoch  24/100: train_loss=0.003146

      epoch  25/100: train_loss=0.002920, val_loss=0.000624, IC=+0.0326

      epoch  26/100: train_loss=0.002865

      epoch  27/100: train_loss=0.002467

      epoch  28/100: train_loss=0.002463

      epoch  29/100: train_loss=0.002018

      epoch  30/100: train_loss=0.002172, val_loss=0.000313, IC=+0.0469

      epoch  31/100: train_loss=0.002093

      epoch  32/100: train_loss=0.001848

      epoch  33/100: train_loss=0.001896

      epoch  34/100: train_loss=0.001610

      epoch  35/100: train_loss=0.001344, val_loss=0.000279, IC=+0.0369

      epoch  36/100: train_loss=0.001386

      epoch  37/100: train_loss=0.001188

      epoch  38/100: train_loss=0.001099

      epoch  39/100: train_loss=0.000887

      epoch  40/100: train_loss=0.000990, val_loss=0.000151, IC=+0.0437

      epoch  41/100: train_loss=0.000737

      epoch  42/100: train_loss=0.000690

      epoch  43/100: train_loss=0.000626

      epoch  44/100: train_loss=0.000677

      epoch  45/100: train_loss=0.000590, val_loss=0.000096, IC=+0.0482

      epoch  46/100: train_loss=0.000533

      epoch  47/100: train_loss=0.000577

      epoch  48/100: train_loss=0.000583

      epoch  49/100: train_loss=0.000515

      epoch  50/100: train_loss=0.000489, val_loss=0.000072, IC=+0.0413

      epoch  51/100: train_loss=0.000446

      epoch  52/100: train_loss=0.000385

      epoch  53/100: train_loss=0.000366

      epoch  54/100: train_loss=0.001120

      epoch  55/100: train_loss=0.000364, val_loss=0.000058, IC=+0.0205

      epoch  56/100: train_loss=0.000331

      epoch  57/100: train_loss=0.000319

      epoch  58/100: train_loss=0.000309

      epoch  59/100: train_loss=0.000277

      epoch  60/100: train_loss=0.000293, val_loss=0.000046, IC=+0.0379

      epoch  61/100: train_loss=0.000265

      epoch  62/100: train_loss=0.000291

      epoch  63/100: train_loss=0.000243

      epoch  64/100: train_loss=0.000251

      epoch  65/100: train_loss=0.000255, val_loss=0.000044, IC=+0.0284

      epoch  66/100: train_loss=0.000251

      epoch  67/100: train_loss=0.000223

      epoch  68/100: train_loss=0.000228

      epoch  69/100: train_loss=0.000256

      epoch  70/100: train_loss=0.000229, val_loss=0.000044, IC=+0.0362

      epoch  71/100: train_loss=0.000195

      epoch  72/100: train_loss=0.000188

      epoch  73/100: train_loss=0.000183

      epoch  74/100: train_loss=0.000192

      epoch  75/100: train_loss=0.000183, val_loss=0.000037, IC=+0.0353

      epoch  76/100: train_loss=0.000182

      epoch  77/100: train_loss=0.000173

      epoch  78/100: train_loss=0.000169

      epoch  79/100: train_loss=0.000184

      epoch  80/100: train_loss=0.000165, val_loss=0.000037, IC=+0.0314

      epoch  81/100: train_loss=0.000177

      epoch  82/100: train_loss=0.000184

      epoch  83/100: train_loss=0.000165

      epoch  84/100: train_loss=0.000158

      epoch  85/100: train_loss=0.000161, val_loss=0.000036, IC=+0.0336

      epoch  86/100: train_loss=0.000172

      epoch  87/100: train_loss=0.000161

      epoch  88/100: train_loss=0.000152

      epoch  89/100: train_loss=0.000171

      epoch  90/100: train_loss=0.000160, val_loss=0.000036, IC=+0.0285

      epoch  91/100: train_loss=0.000155

      epoch  92/100: train_loss=0.000155

      epoch  93/100: train_loss=0.000156

      epoch  94/100: train_loss=0.000152

      epoch  95/100: train_loss=0.000155, val_loss=0.000035, IC=+0.0301

      epoch  96/100: train_loss=0.000154

      epoch  97/100: train_loss=0.000151

      epoch  98/100: train_loss=0.000198

      epoch  99/100: train_loss=0.000154

      epoch 100/100: train_loss=0.000178, val_loss=0.000035, IC=+0.0301

      best_ep=45, IC=+0.0482 (45.0s, 20 checkpoints)

  Fold 6: creating sequences...
    train=22,220 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.147192

      epoch   2/100: train_loss=0.075360

      epoch   3/100: train_loss=0.050636

      epoch   4/100: train_loss=0.040497

      epoch   5/100: train_loss=0.033306, val_loss=0.019261, IC=-0.0175

      epoch   6/100: train_loss=0.027497

      epoch   7/100: train_loss=0.022513

      epoch   8/100: train_loss=0.018670

      epoch   9/100: train_loss=0.016204

      epoch  10/100: train_loss=0.013673, val_loss=0.005551, IC=-0.0203

      epoch  11/100: train_loss=0.011796

      epoch  12/100: train_loss=0.010071

      epoch  13/100: train_loss=0.008751

      epoch  14/100: train_loss=0.007443

      epoch  15/100: train_loss=0.006502, val_loss=0.001979, IC=-0.0218

      epoch  16/100: train_loss=0.005631

      epoch  17/100: train_loss=0.004946

      epoch  18/100: train_loss=0.004385

      epoch  19/100: train_loss=0.003888

      epoch  20/100: train_loss=0.003461, val_loss=0.000875, IC=-0.0153

      epoch  21/100: train_loss=0.003113

      epoch  22/100: train_loss=0.002803

      epoch  23/100: train_loss=0.002459

      epoch  24/100: train_loss=0.002226

      epoch  25/100: train_loss=0.001962, val_loss=0.000450, IC=-0.0144

      epoch  26/100: train_loss=0.001773

      epoch  27/100: train_loss=0.001595

      epoch  28/100: train_loss=0.001475

      epoch  29/100: train_loss=0.001318

      epoch  30/100: train_loss=0.001172, val_loss=0.000252, IC=-0.0170

      epoch  31/100: train_loss=0.001054

      epoch  32/100: train_loss=0.000982

      epoch  33/100: train_loss=0.000891

      epoch  34/100: train_loss=0.000808

      epoch  35/100: train_loss=0.000760, val_loss=0.000151, IC=-0.0156

      epoch  36/100: train_loss=0.000651

      epoch  37/100: train_loss=0.000611

      epoch  38/100: train_loss=0.000563

      epoch  39/100: train_loss=0.000500

      epoch  40/100: train_loss=0.000482, val_loss=0.000097, IC=-0.0182

      epoch  41/100: train_loss=0.000429

      epoch  42/100: train_loss=0.000397

      epoch  43/100: train_loss=0.000369

      epoch  44/100: train_loss=0.000339

      epoch  45/100: train_loss=0.000318, val_loss=0.000067, IC=-0.0147

      epoch  46/100: train_loss=0.000296

      epoch  47/100: train_loss=0.000277

      epoch  48/100: train_loss=0.000257

      epoch  49/100: train_loss=0.000238

      epoch  50/100: train_loss=0.000226, val_loss=0.000055, IC=-0.0295

      epoch  51/100: train_loss=0.000216

      epoch  52/100: train_loss=0.000200

      epoch  53/100: train_loss=0.000193

      epoch  54/100: train_loss=0.000182

      epoch  55/100: train_loss=0.000174, val_loss=0.000044, IC=-0.0176

      epoch  56/100: train_loss=0.000163

      epoch  57/100: train_loss=0.000159

      epoch  58/100: train_loss=0.000151

      epoch  59/100: train_loss=0.000142

      epoch  60/100: train_loss=0.000139, val_loss=0.000039, IC=-0.0228

      epoch  61/100: train_loss=0.000133

      epoch  62/100: train_loss=0.000129

      epoch  63/100: train_loss=0.000125

      epoch  64/100: train_loss=0.000119

      epoch  65/100: train_loss=0.000117, val_loss=0.000036, IC=-0.0204

      epoch  66/100: train_loss=0.000111

      epoch  67/100: train_loss=0.000110

      epoch  68/100: train_loss=0.000108

      epoch  69/100: train_loss=0.000104

      epoch  70/100: train_loss=0.000105, val_loss=0.000034, IC=-0.0233

      epoch  71/100: train_loss=0.000101

      epoch  72/100: train_loss=0.000098

      epoch  73/100: train_loss=0.000097

      epoch  74/100: train_loss=0.000095

      epoch  75/100: train_loss=0.000093, val_loss=0.000032, IC=-0.0252

      epoch  76/100: train_loss=0.000093

      epoch  77/100: train_loss=0.000092

      epoch  78/100: train_loss=0.000091

      epoch  79/100: train_loss=0.000088

      epoch  80/100: train_loss=0.000089, val_loss=0.000031, IC=-0.0231

      epoch  81/100: train_loss=0.000087

      epoch  82/100: train_loss=0.000088

      epoch  83/100: train_loss=0.000087

      epoch  84/100: train_loss=0.000086

      epoch  85/100: train_loss=0.000085, val_loss=0.000031, IC=-0.0254

      epoch  86/100: train_loss=0.000084

      epoch  87/100: train_loss=0.000084

      epoch  88/100: train_loss=0.000085

      epoch  89/100: train_loss=0.000084

      epoch  90/100: train_loss=0.000084, val_loss=0.000031, IC=-0.0262

      epoch  91/100: train_loss=0.000083

      epoch  92/100: train_loss=0.000084

      epoch  93/100: train_loss=0.000082

      epoch  94/100: train_loss=0.000083

      epoch  95/100: train_loss=0.000084, val_loss=0.000031, IC=-0.0265

      epoch  96/100: train_loss=0.000083

      epoch  97/100: train_loss=0.000083

      epoch  98/100: train_loss=0.000083

      epoch  99/100: train_loss=0.000082

      epoch 100/100: train_loss=0.000083, val_loss=0.000031, IC=-0.0270

      best_ep=25, IC=-0.0144 (40.5s, 20 checkpoints)

  Fold 7: creating sequences...
    train=17,060 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.291165

      epoch   2/100: train_loss=0.112977

      epoch   3/100: train_loss=0.061108

      epoch   4/100: train_loss=0.045120

      epoch   5/100: train_loss=0.035072, val_loss=0.022486, IC=+0.0051

      epoch   6/100: train_loss=0.028737

      epoch   7/100: train_loss=0.023297

      epoch   8/100: train_loss=0.019912

      epoch   9/100: train_loss=0.016543

      epoch  10/100: train_loss=0.014885, val_loss=0.006780, IC=+0.0142

      epoch  11/100: train_loss=0.012934

      epoch  12/100: train_loss=0.011555

      epoch  13/100: train_loss=0.010287

      epoch  14/100: train_loss=0.009136

      epoch  15/100: train_loss=0.007837, val_loss=0.003122, IC=+0.0142

      epoch  16/100: train_loss=0.006888

      epoch  17/100: train_loss=0.006107

      epoch  18/100: train_loss=0.005370

      epoch  19/100: train_loss=0.004911

      epoch  20/100: train_loss=0.004316, val_loss=0.001585, IC=+0.0179

      epoch  21/100: train_loss=0.003870

      epoch  22/100: train_loss=0.003482

      epoch  23/100: train_loss=0.003182

      epoch  24/100: train_loss=0.002861

      epoch  25/100: train_loss=0.002527, val_loss=0.000787, IC=+0.0167

      epoch  26/100: train_loss=0.002287

      epoch  27/100: train_loss=0.002080

      epoch  28/100: train_loss=0.001858

      epoch  29/100: train_loss=0.001705

      epoch  30/100: train_loss=0.001493, val_loss=0.000493, IC=+0.0219

      epoch  31/100: train_loss=0.001440

      epoch  32/100: train_loss=0.001264

      epoch  33/100: train_loss=0.001191

      epoch  34/100: train_loss=0.001103

      epoch  35/100: train_loss=0.001002, val_loss=0.000329, IC=+0.0229

      epoch  36/100: train_loss=0.000880

      epoch  37/100: train_loss=0.000827

      epoch  38/100: train_loss=0.000762

      epoch  39/100: train_loss=0.000698

      epoch  40/100: train_loss=0.000666, val_loss=0.000269, IC=+0.0225

      epoch  41/100: train_loss=0.000575

      epoch  42/100: train_loss=0.000556

      epoch  43/100: train_loss=0.000522

      epoch  44/100: train_loss=0.000488

      epoch  45/100: train_loss=0.000456, val_loss=0.000199, IC=+0.0146

      epoch  46/100: train_loss=0.000426

      epoch  47/100: train_loss=0.000395

      epoch  48/100: train_loss=0.000377

      epoch  49/100: train_loss=0.000338

      epoch  50/100: train_loss=0.000331, val_loss=0.000177, IC=+0.0201

      epoch  51/100: train_loss=0.000302

      epoch  52/100: train_loss=0.000296

      epoch  53/100: train_loss=0.000279

      epoch  54/100: train_loss=0.000261

      epoch  55/100: train_loss=0.000254, val_loss=0.000150, IC=+0.0180

      epoch  56/100: train_loss=0.000245

      epoch  57/100: train_loss=0.000226

      epoch  58/100: train_loss=0.000214

      epoch  59/100: train_loss=0.000212

      epoch  60/100: train_loss=0.000195, val_loss=0.000134, IC=+0.0184

      epoch  61/100: train_loss=0.000194

      epoch  62/100: train_loss=0.000187

      epoch  63/100: train_loss=0.000177

      epoch  64/100: train_loss=0.000167

      epoch  65/100: train_loss=0.000168, val_loss=0.000124, IC=+0.0209

      epoch  66/100: train_loss=0.000164

      epoch  67/100: train_loss=0.000160

      epoch  68/100: train_loss=0.000154

      epoch  69/100: train_loss=0.000151

      epoch  70/100: train_loss=0.000150, val_loss=0.000112, IC=+0.0198

      epoch  71/100: train_loss=0.000140

      epoch  72/100: train_loss=0.000139

      epoch  73/100: train_loss=0.000137

      epoch  74/100: train_loss=0.000136

      epoch  75/100: train_loss=0.000131, val_loss=0.000106, IC=+0.0198

      epoch  76/100: train_loss=0.000130

      epoch  77/100: train_loss=0.000131

      epoch  78/100: train_loss=0.000126

      epoch  79/100: train_loss=0.000125

      epoch  80/100: train_loss=0.000126, val_loss=0.000103, IC=+0.0221

      epoch  81/100: train_loss=0.000121

      epoch  82/100: train_loss=0.000120

      epoch  83/100: train_loss=0.000120

      epoch  84/100: train_loss=0.000122

      epoch  85/100: train_loss=0.000120, val_loss=0.000101, IC=+0.0206

      epoch  86/100: train_loss=0.000116

      epoch  87/100: train_loss=0.000117

      epoch  88/100: train_loss=0.000122

      epoch  89/100: train_loss=0.000116

      epoch  90/100: train_loss=0.000116, val_loss=0.000100, IC=+0.0217

      epoch  91/100: train_loss=0.000114

      epoch  92/100: train_loss=0.000117

      epoch  93/100: train_loss=0.000115

      epoch  94/100: train_loss=0.000115

      epoch  95/100: train_loss=0.000115, val_loss=0.000100, IC=+0.0221

      epoch  96/100: train_loss=0.000117

      epoch  97/100: train_loss=0.000114

      epoch  98/100: train_loss=0.000114

      epoch  99/100: train_loss=0.000114

      epoch 100/100: train_loss=0.000115, val_loss=0.000099, IC=+0.0205

      best_ep=35, IC=+0.0229 (31.1s, 20 checkpoints)

  nlinear: best_epoch=10, IC=+0.0145 (337.8s)

  Best: nlinear @ epoch 10 (IC=+0.0145)
  Saved to ~/ml4t/public-s6-fx_pairs/case_studies/fx_pairs/run_log/training/e9348cbe2199/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,060 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.511855

      epoch   2/100: train_loss=0.258564

      epoch   3/100: train_loss=0.118185

      epoch   4/100: train_loss=0.058400

      epoch   5/100: train_loss=0.035459, val_loss=0.023402, IC=+0.1015

      epoch   6/100: train_loss=0.026070

      epoch   7/100: train_loss=0.019862

      epoch   8/100: train_loss=0.017265

      epoch   9/100: train_loss=0.015301

      epoch  10/100: train_loss=0.013939, val_loss=0.003861, IC=+0.0797

      epoch  11/100: train_loss=0.012523

      epoch  12/100: train_loss=0.011420

      epoch  13/100: train_loss=0.010666

      epoch  14/100: train_loss=0.010028

      epoch  15/100: train_loss=0.009107, val_loss=0.002163, IC=+0.0577

      epoch  16/100: train_loss=0.008380

      epoch  17/100: train_loss=0.007704

      epoch  18/100: train_loss=0.007187

      epoch  19/100: train_loss=0.006408

      epoch  20/100: train_loss=0.005954, val_loss=0.001265, IC=+0.0465

      epoch  21/100: train_loss=0.005395

      epoch  22/100: train_loss=0.005007

      epoch  23/100: train_loss=0.004752

      epoch  24/100: train_loss=0.004391

      epoch  25/100: train_loss=0.004018, val_loss=0.000773, IC=+0.0447

      epoch  26/100: train_loss=0.003693

      epoch  27/100: train_loss=0.003308

      epoch  28/100: train_loss=0.003025

      epoch  29/100: train_loss=0.002845

      epoch  30/100: train_loss=0.002675, val_loss=0.000503, IC=+0.0383

      epoch  31/100: train_loss=0.002479

      epoch  32/100: train_loss=0.002325

      epoch  33/100: train_loss=0.002111

      epoch  34/100: train_loss=0.001973

      epoch  35/100: train_loss=0.001859, val_loss=0.000348, IC=+0.0370

      epoch  36/100: train_loss=0.001737

      epoch  37/100: train_loss=0.001586

      epoch  38/100: train_loss=0.001545

      epoch  39/100: train_loss=0.001427

      epoch  40/100: train_loss=0.001321, val_loss=0.000265, IC=+0.0319

      epoch  41/100: train_loss=0.001278

      epoch  42/100: train_loss=0.001164

      epoch  43/100: train_loss=0.001110

      epoch  44/100: train_loss=0.001042

      epoch  45/100: train_loss=0.001015, val_loss=0.000204, IC=+0.0377

      epoch  46/100: train_loss=0.000973

      epoch  47/100: train_loss=0.000908

      epoch  48/100: train_loss=0.000897

      epoch  49/100: train_loss=0.000822

      epoch  50/100: train_loss=0.000786, val_loss=0.000175, IC=+0.0363

      epoch  51/100: train_loss=0.000735

      epoch  52/100: train_loss=0.000714

      epoch  53/100: train_loss=0.000691

      epoch  54/100: train_loss=0.000674

      epoch  55/100: train_loss=0.000634, val_loss=0.000157, IC=+0.0418

      epoch  56/100: train_loss=0.000626

      epoch  57/100: train_loss=0.000594

      epoch  58/100: train_loss=0.000564

      epoch  59/100: train_loss=0.000550

      epoch  60/100: train_loss=0.000539, val_loss=0.000146, IC=+0.0439

      epoch  61/100: train_loss=0.000509

      epoch  62/100: train_loss=0.000503

      epoch  63/100: train_loss=0.000486

      epoch  64/100: train_loss=0.000477

      epoch  65/100: train_loss=0.000486, val_loss=0.000143, IC=+0.0400

      epoch  66/100: train_loss=0.000461

      epoch  67/100: train_loss=0.000439

      epoch  68/100: train_loss=0.000433

      epoch  69/100: train_loss=0.000421

      epoch  70/100: train_loss=0.000412, val_loss=0.000137, IC=+0.0454

      epoch  71/100: train_loss=0.000406

      epoch  72/100: train_loss=0.000407

      epoch  73/100: train_loss=0.000394

      epoch  74/100: train_loss=0.000400

      epoch  75/100: train_loss=0.000385, val_loss=0.000134, IC=+0.0428

      epoch  76/100: train_loss=0.000381

      epoch  77/100: train_loss=0.000392

      epoch  78/100: train_loss=0.000372

      epoch  79/100: train_loss=0.000372

      epoch  80/100: train_loss=0.000370, val_loss=0.000133, IC=+0.0479

      epoch  81/100: train_loss=0.000368

      epoch  82/100: train_loss=0.000362

      epoch  83/100: train_loss=0.000363

      epoch  84/100: train_loss=0.000358

      epoch  85/100: train_loss=0.000354, val_loss=0.000132, IC=+0.0477

      epoch  86/100: train_loss=0.000354

      epoch  87/100: train_loss=0.000352

      epoch  88/100: train_loss=0.000350

      epoch  89/100: train_loss=0.000349

      epoch  90/100: train_loss=0.000349, val_loss=0.000131, IC=+0.0472

      epoch  91/100: train_loss=0.000351

      epoch  92/100: train_loss=0.000345

      epoch  93/100: train_loss=0.000344

      epoch  94/100: train_loss=0.000341

      epoch  95/100: train_loss=0.000346, val_loss=0.000131, IC=+0.0461

      epoch  96/100: train_loss=0.000343

      epoch  97/100: train_loss=0.000341

      epoch  98/100: train_loss=0.000342

      epoch  99/100: train_loss=0.000350

      epoch 100/100: train_loss=0.000347, val_loss=0.000131, IC=+0.0458

      best_ep=5, IC=+0.1015 (43.7s, 20 checkpoints)

  Fold 1: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.261839

      epoch   2/100: train_loss=0.119386

      epoch   3/100: train_loss=0.068383

      epoch   4/100: train_loss=0.042897

      epoch   5/100: train_loss=0.030062, val_loss=0.116526, IC=-0.0148

      epoch   6/100: train_loss=0.022669

      epoch   7/100: train_loss=0.018549

      epoch   8/100: train_loss=0.015680

      epoch   9/100: train_loss=0.013327

      epoch  10/100: train_loss=0.011474, val_loss=0.028242, IC=-0.0399

      epoch  11/100: train_loss=0.010042

      epoch  12/100: train_loss=0.008531

      epoch  13/100: train_loss=0.007713

      epoch  14/100: train_loss=0.006780

      epoch  15/100: train_loss=0.006101, val_loss=0.011245, IC=-0.0461

      epoch  16/100: train_loss=0.005480

      epoch  17/100: train_loss=0.004810

      epoch  18/100: train_loss=0.004308

      epoch  19/100: train_loss=0.003902

      epoch  20/100: train_loss=0.003517, val_loss=0.005271, IC=-0.0382

      epoch  21/100: train_loss=0.003011

      epoch  22/100: train_loss=0.002827

      epoch  23/100: train_loss=0.002571

      epoch  24/100: train_loss=0.002272

      epoch  25/100: train_loss=0.002078, val_loss=0.002910, IC=-0.0256

      epoch  26/100: train_loss=0.001911

      epoch  27/100: train_loss=0.001689

      epoch  28/100: train_loss=0.001579

      epoch  29/100: train_loss=0.001463

      epoch  30/100: train_loss=0.001315, val_loss=0.001628, IC=-0.0212

      epoch  31/100: train_loss=0.001176

      epoch  32/100: train_loss=0.001138

      epoch  33/100: train_loss=0.000989

      epoch  34/100: train_loss=0.000928

      epoch  35/100: train_loss=0.000863, val_loss=0.001002, IC=-0.0084

      epoch  36/100: train_loss=0.000811

      epoch  37/100: train_loss=0.000753

      epoch  38/100: train_loss=0.000705

      epoch  39/100: train_loss=0.000619

      epoch  40/100: train_loss=0.000579, val_loss=0.000646, IC=-0.0242

      epoch  41/100: train_loss=0.000538

      epoch  42/100: train_loss=0.000523

      epoch  43/100: train_loss=0.000493

      epoch  44/100: train_loss=0.000472

      epoch  45/100: train_loss=0.000442, val_loss=0.000450, IC=-0.0278

      epoch  46/100: train_loss=0.000415

      epoch  47/100: train_loss=0.000386

      epoch  48/100: train_loss=0.000369

      epoch  49/100: train_loss=0.000352

      epoch  50/100: train_loss=0.000332, val_loss=0.000359, IC=-0.0222

      epoch  51/100: train_loss=0.000314

      epoch  52/100: train_loss=0.000306

      epoch  53/100: train_loss=0.000292

      epoch  54/100: train_loss=0.000282

      epoch  55/100: train_loss=0.000275, val_loss=0.000314, IC=-0.0158

      epoch  56/100: train_loss=0.000266

      epoch  57/100: train_loss=0.000251

      epoch  58/100: train_loss=0.000248

      epoch  59/100: train_loss=0.000241

      epoch  60/100: train_loss=0.000235, val_loss=0.000285, IC=-0.0228

      epoch  61/100: train_loss=0.000228

      epoch  62/100: train_loss=0.000220

      epoch  63/100: train_loss=0.000213

      epoch  64/100: train_loss=0.000221

      epoch  65/100: train_loss=0.000208, val_loss=0.000265, IC=-0.0129

      epoch  66/100: train_loss=0.000207

      epoch  67/100: train_loss=0.000201

      epoch  68/100: train_loss=0.000195

      epoch  69/100: train_loss=0.000199

      epoch  70/100: train_loss=0.000192, val_loss=0.000258, IC=-0.0243

      epoch  71/100: train_loss=0.000194

      epoch  72/100: train_loss=0.000190

      epoch  73/100: train_loss=0.000188

      epoch  74/100: train_loss=0.000184

      epoch  75/100: train_loss=0.000185, val_loss=0.000249, IC=-0.0232

      epoch  76/100: train_loss=0.000177

      epoch  77/100: train_loss=0.000178

      epoch  78/100: train_loss=0.000179

      epoch  79/100: train_loss=0.000182

      epoch  80/100: train_loss=0.000177, val_loss=0.000246, IC=-0.0225

      epoch  81/100: train_loss=0.000176

      epoch  82/100: train_loss=0.000175

      epoch  83/100: train_loss=0.000175

      epoch  84/100: train_loss=0.000171

      epoch  85/100: train_loss=0.000174, val_loss=0.000244, IC=-0.0235

      epoch  86/100: train_loss=0.000171

      epoch  87/100: train_loss=0.000170

      epoch  88/100: train_loss=0.000171

      epoch  89/100: train_loss=0.000172

      epoch  90/100: train_loss=0.000171, val_loss=0.000242, IC=-0.0211

      epoch  91/100: train_loss=0.000172

      epoch  92/100: train_loss=0.000171

      epoch  93/100: train_loss=0.000171

      epoch  94/100: train_loss=0.000169

      epoch  95/100: train_loss=0.000170, val_loss=0.000242, IC=-0.0232

      epoch  96/100: train_loss=0.000168

      epoch  97/100: train_loss=0.000169

      epoch  98/100: train_loss=0.000166

      epoch  99/100: train_loss=0.000171

      epoch 100/100: train_loss=0.000170, val_loss=0.000242, IC=-0.0244

      best_ep=35, IC=-0.0084 (40.7s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.179072

      epoch   2/100: train_loss=0.069323

      epoch   3/100: train_loss=0.042552

      epoch   4/100: train_loss=0.029922

      epoch   5/100: train_loss=0.023580, val_loss=0.007726, IC=+0.1332

      epoch   6/100: train_loss=0.020251

      epoch   7/100: train_loss=0.017527

      epoch   8/100: train_loss=0.015618

      epoch   9/100: train_loss=0.014048

      epoch  10/100: train_loss=0.012881, val_loss=0.003415, IC=+0.1097

      epoch  11/100: train_loss=0.011145

      epoch  12/100: train_loss=0.010298

      epoch  13/100: train_loss=0.009651

      epoch  14/100: train_loss=0.008405

      epoch  15/100: train_loss=0.007613, val_loss=0.001961, IC=+0.0979

      epoch  16/100: train_loss=0.007002

      epoch  17/100: train_loss=0.006359

      epoch  18/100: train_loss=0.005717

      epoch  19/100: train_loss=0.005228

      epoch  20/100: train_loss=0.004730, val_loss=0.001085, IC=+0.0992

      epoch  21/100: train_loss=0.004294

      epoch  22/100: train_loss=0.003901

      epoch  23/100: train_loss=0.003504

      epoch  24/100: train_loss=0.003297

      epoch  25/100: train_loss=0.003081, val_loss=0.000637, IC=+0.0947

      epoch  26/100: train_loss=0.002786

      epoch  27/100: train_loss=0.002584

      epoch  28/100: train_loss=0.002377

      epoch  29/100: train_loss=0.002157

      epoch  30/100: train_loss=0.001991, val_loss=0.000383, IC=+0.0948

      epoch  31/100: train_loss=0.001852

      epoch  32/100: train_loss=0.001743

      epoch  33/100: train_loss=0.001578

      epoch  34/100: train_loss=0.001451

      epoch  35/100: train_loss=0.001347, val_loss=0.000249, IC=+0.0910

      epoch  36/100: train_loss=0.001272

      epoch  37/100: train_loss=0.001191

      epoch  38/100: train_loss=0.001142

      epoch  39/100: train_loss=0.001063

      epoch  40/100: train_loss=0.001004, val_loss=0.000191, IC=+0.0850

      epoch  41/100: train_loss=0.000913

      epoch  42/100: train_loss=0.000884

      epoch  43/100: train_loss=0.000826

      epoch  44/100: train_loss=0.000763

      epoch  45/100: train_loss=0.000751, val_loss=0.000149, IC=+0.0907

      epoch  46/100: train_loss=0.000707

      epoch  47/100: train_loss=0.000668

      epoch  48/100: train_loss=0.000627

      epoch  49/100: train_loss=0.000595

      epoch  50/100: train_loss=0.000579, val_loss=0.000128, IC=+0.0835

      epoch  51/100: train_loss=0.000558

      epoch  52/100: train_loss=0.000528

      epoch  53/100: train_loss=0.000515

      epoch  54/100: train_loss=0.000497

      epoch  55/100: train_loss=0.000475, val_loss=0.000116, IC=+0.0756

      epoch  56/100: train_loss=0.000460

      epoch  57/100: train_loss=0.000442

      epoch  58/100: train_loss=0.000434

      epoch  59/100: train_loss=0.000427

      epoch  60/100: train_loss=0.000410, val_loss=0.000107, IC=+0.0794

      epoch  61/100: train_loss=0.000399

      epoch  62/100: train_loss=0.000385

      epoch  63/100: train_loss=0.000369

      epoch  64/100: train_loss=0.000375

      epoch  65/100: train_loss=0.000365, val_loss=0.000103, IC=+0.0710

      epoch  66/100: train_loss=0.000358

      epoch  67/100: train_loss=0.000356

      epoch  68/100: train_loss=0.000343

      epoch  69/100: train_loss=0.000344

      epoch  70/100: train_loss=0.000332, val_loss=0.000101, IC=+0.0680

      epoch  71/100: train_loss=0.000337

      epoch  72/100: train_loss=0.000326

      epoch  73/100: train_loss=0.000324

      epoch  74/100: train_loss=0.000319

      epoch  75/100: train_loss=0.000315, val_loss=0.000099, IC=+0.0681

      epoch  76/100: train_loss=0.000309

      epoch  77/100: train_loss=0.000313

      epoch  78/100: train_loss=0.000302

      epoch  79/100: train_loss=0.000300

      epoch  80/100: train_loss=0.000300, val_loss=0.000098, IC=+0.0619

      epoch  81/100: train_loss=0.000303

      epoch  82/100: train_loss=0.000294

      epoch  83/100: train_loss=0.000296

      epoch  84/100: train_loss=0.000290

      epoch  85/100: train_loss=0.000297, val_loss=0.000098, IC=+0.0588

      epoch  86/100: train_loss=0.000295

      epoch  87/100: train_loss=0.000292

      epoch  88/100: train_loss=0.000294

      epoch  89/100: train_loss=0.000293

      epoch  90/100: train_loss=0.000291, val_loss=0.000097, IC=+0.0581

      epoch  91/100: train_loss=0.000290

      epoch  92/100: train_loss=0.000289

      epoch  93/100: train_loss=0.000286

      epoch  94/100: train_loss=0.000282

      epoch  95/100: train_loss=0.000292, val_loss=0.000097, IC=+0.0587

      epoch  96/100: train_loss=0.000283

      epoch  97/100: train_loss=0.000286

      epoch  98/100: train_loss=0.000288

      epoch  99/100: train_loss=0.000290

      epoch 100/100: train_loss=0.000288, val_loss=0.000097, IC=+0.0582

      best_ep=5, IC=+0.1332 (40.3s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.336103

      epoch   2/100: train_loss=0.079461

      epoch   3/100: train_loss=0.053211

      epoch   4/100: train_loss=0.036343

      epoch   5/100: train_loss=0.027072, val_loss=0.020263, IC=+0.0793

      epoch   6/100: train_loss=0.021055

      epoch   7/100: train_loss=0.016629

      epoch   8/100: train_loss=0.013703

      epoch   9/100: train_loss=0.011635

      epoch  10/100: train_loss=0.010063, val_loss=0.003683, IC=+0.0498

      epoch  11/100: train_loss=0.008795

      epoch  12/100: train_loss=0.007762

      epoch  13/100: train_loss=0.006959

      epoch  14/100: train_loss=0.006249

      epoch  15/100: train_loss=0.005413, val_loss=0.001644, IC=+0.0180

      epoch  16/100: train_loss=0.005029

      epoch  17/100: train_loss=0.004589

      epoch  18/100: train_loss=0.004090

      epoch  19/100: train_loss=0.003787

      epoch  20/100: train_loss=0.003446, val_loss=0.001056, IC=+0.0048

      epoch  21/100: train_loss=0.003108

      epoch  22/100: train_loss=0.002906

      epoch  23/100: train_loss=0.002675

      epoch  24/100: train_loss=0.002396

      epoch  25/100: train_loss=0.002286, val_loss=0.000763, IC=-0.0028

      epoch  26/100: train_loss=0.002090

      epoch  27/100: train_loss=0.001926

      epoch  28/100: train_loss=0.001804

      epoch  29/100: train_loss=0.001616

      epoch  30/100: train_loss=0.001591, val_loss=0.000591, IC=-0.0171

      epoch  31/100: train_loss=0.001449

      epoch  32/100: train_loss=0.001372

      epoch  33/100: train_loss=0.001284

      epoch  34/100: train_loss=0.001193

      epoch  35/100: train_loss=0.001163, val_loss=0.000487, IC=-0.0272

      epoch  36/100: train_loss=0.001107

      epoch  37/100: train_loss=0.001030

      epoch  38/100: train_loss=0.000992

      epoch  39/100: train_loss=0.000944

      epoch  40/100: train_loss=0.000899, val_loss=0.000416, IC=-0.0203

      epoch  41/100: train_loss=0.000857

      epoch  42/100: train_loss=0.000832

      epoch  43/100: train_loss=0.000785

      epoch  44/100: train_loss=0.000758

      epoch  45/100: train_loss=0.000719, val_loss=0.000371, IC=-0.0365

      epoch  46/100: train_loss=0.000693

      epoch  47/100: train_loss=0.000678

      epoch  48/100: train_loss=0.000653

      epoch  49/100: train_loss=0.000635

      epoch  50/100: train_loss=0.000604, val_loss=0.000343, IC=-0.0381

      epoch  51/100: train_loss=0.000582

      epoch  52/100: train_loss=0.000572

      epoch  53/100: train_loss=0.000558

      epoch  54/100: train_loss=0.000538

      epoch  55/100: train_loss=0.000528, val_loss=0.000320, IC=-0.0424

      epoch  56/100: train_loss=0.000519

      epoch  57/100: train_loss=0.000503

      epoch  58/100: train_loss=0.000501

      epoch  59/100: train_loss=0.000478

      epoch  60/100: train_loss=0.000472, val_loss=0.000304, IC=-0.0416

      epoch  61/100: train_loss=0.000461

      epoch  62/100: train_loss=0.000450

      epoch  63/100: train_loss=0.000447

      epoch  64/100: train_loss=0.000450

      epoch  65/100: train_loss=0.000424, val_loss=0.000293, IC=-0.0445

      epoch  66/100: train_loss=0.000427

      epoch  67/100: train_loss=0.000410

      epoch  68/100: train_loss=0.000417

      epoch  69/100: train_loss=0.000401

      epoch  70/100: train_loss=0.000401, val_loss=0.000285, IC=-0.0463

      epoch  71/100: train_loss=0.000396

      epoch  72/100: train_loss=0.000384

      epoch  73/100: train_loss=0.000385

      epoch  74/100: train_loss=0.000379

      epoch  75/100: train_loss=0.000383, val_loss=0.000282, IC=-0.0486

      epoch  76/100: train_loss=0.000382

      epoch  77/100: train_loss=0.000371

      epoch  78/100: train_loss=0.000378

      epoch  79/100: train_loss=0.000362

      epoch  80/100: train_loss=0.000363, val_loss=0.000275, IC=-0.0474

      epoch  81/100: train_loss=0.000366

      epoch  82/100: train_loss=0.000363

      epoch  83/100: train_loss=0.000362

      epoch  84/100: train_loss=0.000351

      epoch  85/100: train_loss=0.000361, val_loss=0.000274, IC=-0.0483

      epoch  86/100: train_loss=0.000353

      epoch  87/100: train_loss=0.000351

      epoch  88/100: train_loss=0.000353

      epoch  89/100: train_loss=0.000354

      epoch  90/100: train_loss=0.000360, val_loss=0.000272, IC=-0.0475

      epoch  91/100: train_loss=0.000357

      epoch  92/100: train_loss=0.000353

      epoch  93/100: train_loss=0.000350

      epoch  94/100: train_loss=0.000353

      epoch  95/100: train_loss=0.000352, val_loss=0.000271, IC=-0.0476

      epoch  96/100: train_loss=0.000356

      epoch  97/100: train_loss=0.000352

      epoch  98/100: train_loss=0.000349

      epoch  99/100: train_loss=0.000347

      epoch 100/100: train_loss=0.000351, val_loss=0.000271, IC=-0.0478

      best_ep=5, IC=+0.0793 (40.2s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.288878

      epoch   2/100: train_loss=0.135722

      epoch   3/100: train_loss=0.071517

      epoch   4/100: train_loss=0.049604

      epoch   5/100: train_loss=0.039170, val_loss=0.016965, IC=-0.0024

      epoch   6/100: train_loss=0.031816

      epoch   7/100: train_loss=0.026674

      epoch   8/100: train_loss=0.023034

      epoch   9/100: train_loss=0.019642

      epoch  10/100: train_loss=0.017301, val_loss=0.005795, IC=+0.0061

      epoch  11/100: train_loss=0.014872

      epoch  12/100: train_loss=0.013098

      epoch  13/100: train_loss=0.011575

      epoch  14/100: train_loss=0.009893

      epoch  15/100: train_loss=0.008854, val_loss=0.002082, IC=+0.0104

      epoch  16/100: train_loss=0.007996

      epoch  17/100: train_loss=0.007012

      epoch  18/100: train_loss=0.006308

      epoch  19/100: train_loss=0.005550

      epoch  20/100: train_loss=0.004939, val_loss=0.000883, IC=+0.0154

      epoch  21/100: train_loss=0.004655

      epoch  22/100: train_loss=0.004156

      epoch  23/100: train_loss=0.003653

      epoch  24/100: train_loss=0.003392

      epoch  25/100: train_loss=0.003068, val_loss=0.000445, IC=+0.0163

      epoch  26/100: train_loss=0.002751

      epoch  27/100: train_loss=0.002528

      epoch  28/100: train_loss=0.002333

      epoch  29/100: train_loss=0.002146

      epoch  30/100: train_loss=0.001937, val_loss=0.000267, IC=+0.0193

      epoch  31/100: train_loss=0.001775

      epoch  32/100: train_loss=0.001630

      epoch  33/100: train_loss=0.001471

      epoch  34/100: train_loss=0.001392

      epoch  35/100: train_loss=0.001293, val_loss=0.000189, IC=+0.0311

      epoch  36/100: train_loss=0.001182

      epoch  37/100: train_loss=0.001105

      epoch  38/100: train_loss=0.001030

      epoch  39/100: train_loss=0.000965

      epoch  40/100: train_loss=0.000915, val_loss=0.000152, IC=+0.0194

      epoch  41/100: train_loss=0.000845

      epoch  42/100: train_loss=0.000807

      epoch  43/100: train_loss=0.000754

      epoch  44/100: train_loss=0.000715

      epoch  45/100: train_loss=0.000656, val_loss=0.000127, IC=+0.0392

      epoch  46/100: train_loss=0.000633

      epoch  47/100: train_loss=0.000600

      epoch  48/100: train_loss=0.000592

      epoch  49/100: train_loss=0.000549

      epoch  50/100: train_loss=0.000542, val_loss=0.000116, IC=+0.0254

      epoch  51/100: train_loss=0.000505

      epoch  52/100: train_loss=0.000496

      epoch  53/100: train_loss=0.000471

      epoch  54/100: train_loss=0.000457

      epoch  55/100: train_loss=0.000433, val_loss=0.000107, IC=+0.0296

      epoch  56/100: train_loss=0.000431

      epoch  57/100: train_loss=0.000411

      epoch  58/100: train_loss=0.000405

      epoch  59/100: train_loss=0.000389

      epoch  60/100: train_loss=0.000391, val_loss=0.000102, IC=+0.0323

      epoch  61/100: train_loss=0.000378

      epoch  62/100: train_loss=0.000363

      epoch  63/100: train_loss=0.000362

      epoch  64/100: train_loss=0.000355

      epoch  65/100: train_loss=0.000349, val_loss=0.000100, IC=+0.0285

      epoch  66/100: train_loss=0.000343

      epoch  67/100: train_loss=0.000333

      epoch  68/100: train_loss=0.000329

      epoch  69/100: train_loss=0.000329

      epoch  70/100: train_loss=0.000318, val_loss=0.000098, IC=+0.0282

      epoch  71/100: train_loss=0.000314

      epoch  72/100: train_loss=0.000313

      epoch  73/100: train_loss=0.000315

      epoch  74/100: train_loss=0.000312

      epoch  75/100: train_loss=0.000307, val_loss=0.000096, IC=+0.0344

      epoch  76/100: train_loss=0.000307

      epoch  77/100: train_loss=0.000300

      epoch  78/100: train_loss=0.000303

      epoch  79/100: train_loss=0.000298

      epoch  80/100: train_loss=0.000293, val_loss=0.000095, IC=+0.0376

      epoch  81/100: train_loss=0.000297

      epoch  82/100: train_loss=0.000297

      epoch  83/100: train_loss=0.000290

      epoch  84/100: train_loss=0.000292

      epoch  85/100: train_loss=0.000290, val_loss=0.000095, IC=+0.0316

      epoch  86/100: train_loss=0.000293

      epoch  87/100: train_loss=0.000293

      epoch  88/100: train_loss=0.000287

      epoch  89/100: train_loss=0.000289

      epoch  90/100: train_loss=0.000287, val_loss=0.000094, IC=+0.0340

      epoch  91/100: train_loss=0.000283

      epoch  92/100: train_loss=0.000284

      epoch  93/100: train_loss=0.000283

      epoch  94/100: train_loss=0.000285

      epoch  95/100: train_loss=0.000287, val_loss=0.000094, IC=+0.0337

      epoch  96/100: train_loss=0.000283

      epoch  97/100: train_loss=0.000283

      epoch  98/100: train_loss=0.000286

      epoch  99/100: train_loss=0.000285

      epoch 100/100: train_loss=0.000285, val_loss=0.000094, IC=+0.0338

      best_ep=45, IC=+0.0392 (42.9s, 20 checkpoints)

  Fold 5: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.320099

      epoch   2/100: train_loss=0.341489

      epoch   3/100: train_loss=0.114103

      epoch   4/100: train_loss=0.051973

      epoch   5/100: train_loss=0.036486, val_loss=0.010859, IC=-0.0318

      epoch   6/100: train_loss=0.028575

      epoch   7/100: train_loss=0.023322

      epoch   8/100: train_loss=0.019794

      epoch   9/100: train_loss=0.016767

      epoch  10/100: train_loss=0.014517, val_loss=0.003414, IC=+0.0094

      epoch  11/100: train_loss=0.012741

      epoch  12/100: train_loss=0.011250

      epoch  13/100: train_loss=0.010033

      epoch  14/100: train_loss=0.009054

      epoch  15/100: train_loss=0.008206, val_loss=0.001864, IC=+0.0325

      epoch  16/100: train_loss=0.007487

      epoch  17/100: train_loss=0.006683

      epoch  18/100: train_loss=0.006046

      epoch  19/100: train_loss=0.005446

      epoch  20/100: train_loss=0.004948, val_loss=0.001012, IC=+0.0444

      epoch  21/100: train_loss=0.004470

      epoch  22/100: train_loss=0.004065

      epoch  23/100: train_loss=0.003699

      epoch  24/100: train_loss=0.003392

      epoch  25/100: train_loss=0.003012, val_loss=0.000569, IC=+0.0473

      epoch  26/100: train_loss=0.002849

      epoch  27/100: train_loss=0.002569

      epoch  28/100: train_loss=0.002349

      epoch  29/100: train_loss=0.002218

      epoch  30/100: train_loss=0.001996, val_loss=0.000361, IC=+0.0562

      epoch  31/100: train_loss=0.001839

      epoch  32/100: train_loss=0.001705

      epoch  33/100: train_loss=0.001593

      epoch  34/100: train_loss=0.001474

      epoch  35/100: train_loss=0.001371, val_loss=0.000262, IC=+0.0542

      epoch  36/100: train_loss=0.001281

      epoch  37/100: train_loss=0.001192

      epoch  38/100: train_loss=0.001124

      epoch  39/100: train_loss=0.001055

      epoch  40/100: train_loss=0.000995, val_loss=0.000203, IC=+0.0542

      epoch  41/100: train_loss=0.000931

      epoch  42/100: train_loss=0.000896

      epoch  43/100: train_loss=0.000866

      epoch  44/100: train_loss=0.000818

      epoch  45/100: train_loss=0.000764, val_loss=0.000173, IC=+0.0512

      epoch  46/100: train_loss=0.000730

      epoch  47/100: train_loss=0.000680

      epoch  48/100: train_loss=0.000659

      epoch  49/100: train_loss=0.000629

      epoch  50/100: train_loss=0.000596, val_loss=0.000153, IC=+0.0491

      epoch  51/100: train_loss=0.000578

      epoch  52/100: train_loss=0.000562

      epoch  53/100: train_loss=0.000544

      epoch  54/100: train_loss=0.000523

      epoch  55/100: train_loss=0.000513, val_loss=0.000142, IC=+0.0517

      epoch  56/100: train_loss=0.000500

      epoch  57/100: train_loss=0.000479

      epoch  58/100: train_loss=0.000464

      epoch  59/100: train_loss=0.000447

      epoch  60/100: train_loss=0.000438, val_loss=0.000136, IC=+0.0524

      epoch  61/100: train_loss=0.000425

      epoch  62/100: train_loss=0.000423

      epoch  63/100: train_loss=0.000412

      epoch  64/100: train_loss=0.000402

      epoch  65/100: train_loss=0.000397, val_loss=0.000131, IC=+0.0549

      epoch  66/100: train_loss=0.000394

      epoch  67/100: train_loss=0.000381

      epoch  68/100: train_loss=0.000381

      epoch  69/100: train_loss=0.000373

      epoch  70/100: train_loss=0.000372, val_loss=0.000128, IC=+0.0611

      epoch  71/100: train_loss=0.000363

      epoch  72/100: train_loss=0.000364

      epoch  73/100: train_loss=0.000360

      epoch  74/100: train_loss=0.000354

      epoch  75/100: train_loss=0.000354, val_loss=0.000127, IC=+0.0536

      epoch  76/100: train_loss=0.000344

      epoch  77/100: train_loss=0.000343

      epoch  78/100: train_loss=0.000341

      epoch  79/100: train_loss=0.000341

      epoch  80/100: train_loss=0.000337, val_loss=0.000125, IC=+0.0601

      epoch  81/100: train_loss=0.000339

      epoch  82/100: train_loss=0.000330

      epoch  83/100: train_loss=0.000333

      epoch  84/100: train_loss=0.000335

      epoch  85/100: train_loss=0.000331, val_loss=0.000125, IC=+0.0528

      epoch  86/100: train_loss=0.000325

      epoch  87/100: train_loss=0.000331

      epoch  88/100: train_loss=0.000327

      epoch  89/100: train_loss=0.000333

      epoch  90/100: train_loss=0.000328, val_loss=0.000124, IC=+0.0545

      epoch  91/100: train_loss=0.000328

      epoch  92/100: train_loss=0.000327

      epoch  93/100: train_loss=0.000324

      epoch  94/100: train_loss=0.000320

      epoch  95/100: train_loss=0.000323, val_loss=0.000124, IC=+0.0564

      epoch  96/100: train_loss=0.000329

      epoch  97/100: train_loss=0.000321

      epoch  98/100: train_loss=0.000328

      epoch  99/100: train_loss=0.000325

      epoch 100/100: train_loss=0.000321, val_loss=0.000124, IC=+0.0565

      best_ep=70, IC=+0.0611 (45.3s, 20 checkpoints)

  Fold 6: creating sequences...
    train=22,140 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.150043

      epoch   2/100: train_loss=0.075537

      epoch   3/100: train_loss=0.051569

      epoch   4/100: train_loss=0.041605

      epoch   5/100: train_loss=0.033186, val_loss=0.019850, IC=-0.0560

      epoch   6/100: train_loss=0.027407

      epoch   7/100: train_loss=0.022802

      epoch   8/100: train_loss=0.019266

      epoch   9/100: train_loss=0.016057

      epoch  10/100: train_loss=0.013909, val_loss=0.005896, IC=-0.0693

      epoch  11/100: train_loss=0.011812

      epoch  12/100: train_loss=0.010350

      epoch  13/100: train_loss=0.008913

      epoch  14/100: train_loss=0.007584

      epoch  15/100: train_loss=0.006745, val_loss=0.002199, IC=-0.0769

      epoch  16/100: train_loss=0.005896

      epoch  17/100: train_loss=0.005187

      epoch  18/100: train_loss=0.004545

      epoch  19/100: train_loss=0.004000

      epoch  20/100: train_loss=0.003678, val_loss=0.001030, IC=-0.0774

      epoch  21/100: train_loss=0.003248

      epoch  22/100: train_loss=0.002874

      epoch  23/100: train_loss=0.002600

      epoch  24/100: train_loss=0.002341

      epoch  25/100: train_loss=0.002075, val_loss=0.000579, IC=-0.0748

      epoch  26/100: train_loss=0.001905

      epoch  27/100: train_loss=0.001761

      epoch  28/100: train_loss=0.001592

      epoch  29/100: train_loss=0.001487

      epoch  30/100: train_loss=0.001297, val_loss=0.000391, IC=-0.0786

      epoch  31/100: train_loss=0.001227

      epoch  32/100: train_loss=0.001127

      epoch  33/100: train_loss=0.001000

      epoch  34/100: train_loss=0.000972

      epoch  35/100: train_loss=0.000898, val_loss=0.000268, IC=-0.0826

      epoch  36/100: train_loss=0.000821

      epoch  37/100: train_loss=0.000780

      epoch  38/100: train_loss=0.000716

      epoch  39/100: train_loss=0.000668

      epoch  40/100: train_loss=0.000639, val_loss=0.000202, IC=-0.0514

      epoch  41/100: train_loss=0.000599

      epoch  42/100: train_loss=0.000560

      epoch  43/100: train_loss=0.000540

      epoch  44/100: train_loss=0.000509

      epoch  45/100: train_loss=0.000492, val_loss=0.000174, IC=-0.0622

      epoch  46/100: train_loss=0.000460

      epoch  47/100: train_loss=0.000451

      epoch  48/100: train_loss=0.000427

      epoch  49/100: train_loss=0.000407

      epoch  50/100: train_loss=0.000391, val_loss=0.000161, IC=-0.0825

      epoch  51/100: train_loss=0.000381

      epoch  52/100: train_loss=0.000376

      epoch  53/100: train_loss=0.000363

      epoch  54/100: train_loss=0.000352

      epoch  55/100: train_loss=0.000347, val_loss=0.000150, IC=-0.0775

      epoch  56/100: train_loss=0.000330

      epoch  57/100: train_loss=0.000323

      epoch  58/100: train_loss=0.000324

      epoch  59/100: train_loss=0.000318

      epoch  60/100: train_loss=0.000311, val_loss=0.000141, IC=-0.0587

      epoch  61/100: train_loss=0.000306

      epoch  62/100: train_loss=0.000295

      epoch  63/100: train_loss=0.000301

      epoch  64/100: train_loss=0.000290

      epoch  65/100: train_loss=0.000285, val_loss=0.000139, IC=-0.0687

      epoch  66/100: train_loss=0.000286

      epoch  67/100: train_loss=0.000285

      epoch  68/100: train_loss=0.000279

      epoch  69/100: train_loss=0.000283

      epoch  70/100: train_loss=0.000276, val_loss=0.000136, IC=-0.0721

      epoch  71/100: train_loss=0.000273

      epoch  72/100: train_loss=0.000271

      epoch  73/100: train_loss=0.000271

      epoch  74/100: train_loss=0.000268

      epoch  75/100: train_loss=0.000265, val_loss=0.000134, IC=-0.0716

      epoch  76/100: train_loss=0.000263

      epoch  77/100: train_loss=0.000264

      epoch  78/100: train_loss=0.000265

      epoch  79/100: train_loss=0.000261

      epoch  80/100: train_loss=0.000264, val_loss=0.000133, IC=-0.0705

      epoch  81/100: train_loss=0.000263

      epoch  82/100: train_loss=0.000260

      epoch  83/100: train_loss=0.000259

      epoch  84/100: train_loss=0.000259

      epoch  85/100: train_loss=0.000260, val_loss=0.000133, IC=-0.0696

      epoch  86/100: train_loss=0.000258

      epoch  87/100: train_loss=0.000256

      epoch  88/100: train_loss=0.000258

      epoch  89/100: train_loss=0.000259

      epoch  90/100: train_loss=0.000257, val_loss=0.000132, IC=-0.0665

      epoch  91/100: train_loss=0.000255

      epoch  92/100: train_loss=0.000259

      epoch  93/100: train_loss=0.000257

      epoch  94/100: train_loss=0.000257

      epoch  95/100: train_loss=0.000257, val_loss=0.000132, IC=-0.0678

      epoch  96/100: train_loss=0.000257

      epoch  97/100: train_loss=0.000254

      epoch  98/100: train_loss=0.000254

      epoch  99/100: train_loss=0.000253

      epoch 100/100: train_loss=0.000255, val_loss=0.000132, IC=-0.0679

      best_ep=40, IC=-0.0514 (42.1s, 20 checkpoints)

  Fold 7: creating sequences...
    train=16,980 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.288923

      epoch   2/100: train_loss=0.114853

      epoch   3/100: train_loss=0.060479

      epoch   4/100: train_loss=0.046132

      epoch   5/100: train_loss=0.035421, val_loss=0.022412, IC=+0.0205

      epoch   6/100: train_loss=0.028670

      epoch   7/100: train_loss=0.024302

      epoch   8/100: train_loss=0.020061

      epoch   9/100: train_loss=0.017139

      epoch  10/100: train_loss=0.015790, val_loss=0.007045, IC=+0.0346

      epoch  11/100: train_loss=0.013743

      epoch  12/100: train_loss=0.011833

      epoch  13/100: train_loss=0.010492

      epoch  14/100: train_loss=0.009661

      epoch  15/100: train_loss=0.008159, val_loss=0.003348, IC=+0.0319

      epoch  16/100: train_loss=0.007445

      epoch  17/100: train_loss=0.006458

      epoch  18/100: train_loss=0.005878

      epoch  19/100: train_loss=0.005187

      epoch  20/100: train_loss=0.004708, val_loss=0.001617, IC=+0.0337

      epoch  21/100: train_loss=0.004156

      epoch  22/100: train_loss=0.003661

      epoch  23/100: train_loss=0.003433

      epoch  24/100: train_loss=0.003044

      epoch  25/100: train_loss=0.002698, val_loss=0.001093, IC=+0.0359

      epoch  26/100: train_loss=0.002493

      epoch  27/100: train_loss=0.002284

      epoch  28/100: train_loss=0.002034

      epoch  29/100: train_loss=0.001901

      epoch  30/100: train_loss=0.001736, val_loss=0.000749, IC=+0.0389

      epoch  31/100: train_loss=0.001566

      epoch  32/100: train_loss=0.001457

      epoch  33/100: train_loss=0.001310

      epoch  34/100: train_loss=0.001219

      epoch  35/100: train_loss=0.001153, val_loss=0.000571, IC=+0.0342

      epoch  36/100: train_loss=0.001068

      epoch  37/100: train_loss=0.000984

      epoch  38/100: train_loss=0.000956

      epoch  39/100: train_loss=0.000883

      epoch  40/100: train_loss=0.000798, val_loss=0.000527, IC=+0.0322

      epoch  41/100: train_loss=0.000762

      epoch  42/100: train_loss=0.000702

      epoch  43/100: train_loss=0.000669

      epoch  44/100: train_loss=0.000646

      epoch  45/100: train_loss=0.000600, val_loss=0.000458, IC=+0.0297

      epoch  46/100: train_loss=0.000574

      epoch  47/100: train_loss=0.000545

      epoch  48/100: train_loss=0.000522

      epoch  49/100: train_loss=0.000511

      epoch  50/100: train_loss=0.000482, val_loss=0.000419, IC=+0.0404

      epoch  51/100: train_loss=0.000458

      epoch  52/100: train_loss=0.000451

      epoch  53/100: train_loss=0.000424

      epoch  54/100: train_loss=0.000414

      epoch  55/100: train_loss=0.000409, val_loss=0.000399, IC=+0.0379

      epoch  56/100: train_loss=0.000394

      epoch  57/100: train_loss=0.000378

      epoch  58/100: train_loss=0.000377

      epoch  59/100: train_loss=0.000363

      epoch  60/100: train_loss=0.000356, val_loss=0.000381, IC=+0.0355

      epoch  61/100: train_loss=0.000350

      epoch  62/100: train_loss=0.000342

      epoch  63/100: train_loss=0.000329

      epoch  64/100: train_loss=0.000320

      epoch  65/100: train_loss=0.000327, val_loss=0.000366, IC=+0.0375

      epoch  66/100: train_loss=0.000313

      epoch  67/100: train_loss=0.000308

      epoch  68/100: train_loss=0.000301

      epoch  69/100: train_loss=0.000300

      epoch  70/100: train_loss=0.000309, val_loss=0.000355, IC=+0.0390

      epoch  71/100: train_loss=0.000294

      epoch  72/100: train_loss=0.000292

      epoch  73/100: train_loss=0.000299

      epoch  74/100: train_loss=0.000289

      epoch  75/100: train_loss=0.000291, val_loss=0.000350, IC=+0.0325

      epoch  76/100: train_loss=0.000280

      epoch  77/100: train_loss=0.000282

      epoch  78/100: train_loss=0.000285

      epoch  79/100: train_loss=0.000283

      epoch  80/100: train_loss=0.000277, val_loss=0.000348, IC=+0.0370

      epoch  81/100: train_loss=0.000274

      epoch  82/100: train_loss=0.000277

      epoch  83/100: train_loss=0.000276

      epoch  84/100: train_loss=0.000276

      epoch  85/100: train_loss=0.000280, val_loss=0.000343, IC=+0.0354

      epoch  86/100: train_loss=0.000266

      epoch  87/100: train_loss=0.000277

      epoch  88/100: train_loss=0.000271

      epoch  89/100: train_loss=0.000271

      epoch  90/100: train_loss=0.000266, val_loss=0.000342, IC=+0.0353

      epoch  91/100: train_loss=0.000271

      epoch  92/100: train_loss=0.000274

      epoch  93/100: train_loss=0.000270

      epoch  94/100: train_loss=0.000269

      epoch  95/100: train_loss=0.000275, val_loss=0.000341, IC=+0.0348

      epoch  96/100: train_loss=0.000267

      epoch  97/100: train_loss=0.000268

      epoch  98/100: train_loss=0.000270

      epoch  99/100: train_loss=0.000275

      epoch 100/100: train_loss=0.000273, val_loss=0.000341, IC=+0.0356

      best_ep=50, IC=+0.0404 (32.0s, 20 checkpoints)

  nlinear: best_epoch=5, IC=+0.0285 (327.1s)

  Best: nlinear @ epoch 5 (IC=+0.0285)
  Saved to ~/ml4t/public-s6-fx_pairs/case_studies/fx_pairs/run_log/training/c845bed56399/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=24,180 seq across 20 symbols
    val=4,740 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.513220

      epoch   2/100: train_loss=0.256562

      epoch   3/100: train_loss=0.118302

      epoch   4/100: train_loss=0.060296

      epoch   5/100: train_loss=0.036316, val_loss=0.024275, IC=+0.1890

      epoch   6/100: train_loss=0.026477

      epoch   7/100: train_loss=0.020678

      epoch   8/100: train_loss=0.018138

      epoch   9/100: train_loss=0.016218

      epoch  10/100: train_loss=0.014326, val_loss=0.003926, IC=+0.1392

      epoch  11/100: train_loss=0.013181

      epoch  12/100: train_loss=0.012004

      epoch  13/100: train_loss=0.010963

      epoch  14/100: train_loss=0.010311

      epoch  15/100: train_loss=0.009586, val_loss=0.002299, IC=+0.1090

      epoch  16/100: train_loss=0.008666

      epoch  17/100: train_loss=0.008225

      epoch  18/100: train_loss=0.007515

      epoch  19/100: train_loss=0.006884

      epoch  20/100: train_loss=0.006402, val_loss=0.001475, IC=+0.1000

      epoch  21/100: train_loss=0.005922

      epoch  22/100: train_loss=0.005448

      epoch  23/100: train_loss=0.005119

      epoch  24/100: train_loss=0.004718

      epoch  25/100: train_loss=0.004472, val_loss=0.001070, IC=+0.1050

      epoch  26/100: train_loss=0.004164

      epoch  27/100: train_loss=0.003753

      epoch  28/100: train_loss=0.003547

      epoch  29/100: train_loss=0.003322

      epoch  30/100: train_loss=0.003105, val_loss=0.000791, IC=+0.1108

      epoch  31/100: train_loss=0.002931

      epoch  32/100: train_loss=0.002813

      epoch  33/100: train_loss=0.002553

      epoch  34/100: train_loss=0.002443

      epoch  35/100: train_loss=0.002309, val_loss=0.000652, IC=+0.1215

      epoch  36/100: train_loss=0.002119

      epoch  37/100: train_loss=0.002065

      epoch  38/100: train_loss=0.001933

      epoch  39/100: train_loss=0.001881

      epoch  40/100: train_loss=0.001768, val_loss=0.000573, IC=+0.1279

      epoch  41/100: train_loss=0.001752

      epoch  42/100: train_loss=0.001592

      epoch  43/100: train_loss=0.001541

      epoch  44/100: train_loss=0.001460

      epoch  45/100: train_loss=0.001452, val_loss=0.000532, IC=+0.1268

      epoch  46/100: train_loss=0.001364

      epoch  47/100: train_loss=0.001343

      epoch  48/100: train_loss=0.001288

      epoch  49/100: train_loss=0.001250

      epoch  50/100: train_loss=0.001213, val_loss=0.000501, IC=+0.1350

      epoch  51/100: train_loss=0.001184

      epoch  52/100: train_loss=0.001123

      epoch  53/100: train_loss=0.001109

      epoch  54/100: train_loss=0.001087

      epoch  55/100: train_loss=0.001043, val_loss=0.000486, IC=+0.1334

      epoch  56/100: train_loss=0.001036

      epoch  57/100: train_loss=0.001021

      epoch  58/100: train_loss=0.000979

      epoch  59/100: train_loss=0.000976

      epoch  60/100: train_loss=0.000943, val_loss=0.000472, IC=+0.1477

      epoch  61/100: train_loss=0.000919

      epoch  62/100: train_loss=0.000916

      epoch  63/100: train_loss=0.000890

      epoch  64/100: train_loss=0.000878

      epoch  65/100: train_loss=0.000876, val_loss=0.000467, IC=+0.1435

      epoch  66/100: train_loss=0.000861

      epoch  67/100: train_loss=0.000853

      epoch  68/100: train_loss=0.000847

      epoch  69/100: train_loss=0.000831

      epoch  70/100: train_loss=0.000827, val_loss=0.000467, IC=+0.1334

      epoch  71/100: train_loss=0.000799

      epoch  72/100: train_loss=0.000813

      epoch  73/100: train_loss=0.000799

      epoch  74/100: train_loss=0.000792

      epoch  75/100: train_loss=0.000771, val_loss=0.000466, IC=+0.1278

      epoch  76/100: train_loss=0.000783

      epoch  77/100: train_loss=0.000799

      epoch  78/100: train_loss=0.000783

      epoch  79/100: train_loss=0.000772

      epoch  80/100: train_loss=0.000778, val_loss=0.000463, IC=+0.1331

      epoch  81/100: train_loss=0.000763

      epoch  82/100: train_loss=0.000762

      epoch  83/100: train_loss=0.000759

      epoch  84/100: train_loss=0.000762

      epoch  85/100: train_loss=0.000750, val_loss=0.000462, IC=+0.1330

      epoch  86/100: train_loss=0.000760

      epoch  87/100: train_loss=0.000745

      epoch  88/100: train_loss=0.000761

      epoch  89/100: train_loss=0.000755

      epoch  90/100: train_loss=0.000754, val_loss=0.000461, IC=+0.1319

      epoch  91/100: train_loss=0.000746

      epoch  92/100: train_loss=0.000751

      epoch  93/100: train_loss=0.000748

      epoch  94/100: train_loss=0.000752

      epoch  95/100: train_loss=0.000746, val_loss=0.000461, IC=+0.1319

      epoch  96/100: train_loss=0.000745

      epoch  97/100: train_loss=0.000748

      epoch  98/100: train_loss=0.000753

      epoch  99/100: train_loss=0.000753

      epoch 100/100: train_loss=0.000745, val_loss=0.000461, IC=+0.1315

      best_ep=5, IC=+0.1890 (41.7s, 20 checkpoints)

  Fold 1: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.261958

      epoch   2/100: train_loss=0.116983

      epoch   3/100: train_loss=0.068166

      epoch   4/100: train_loss=0.042827

      epoch   5/100: train_loss=0.030519, val_loss=0.114758, IC=-0.0578

      epoch   6/100: train_loss=0.023198

      epoch   7/100: train_loss=0.019020

      epoch   8/100: train_loss=0.016003

      epoch   9/100: train_loss=0.013730

      epoch  10/100: train_loss=0.011974, val_loss=0.028380, IC=-0.0995

      epoch  11/100: train_loss=0.010439

      epoch  12/100: train_loss=0.009285

      epoch  13/100: train_loss=0.008001

      epoch  14/100: train_loss=0.007247

      epoch  15/100: train_loss=0.006483, val_loss=0.012385, IC=-0.1181

      epoch  16/100: train_loss=0.005816

      epoch  17/100: train_loss=0.005362

      epoch  18/100: train_loss=0.004551

      epoch  19/100: train_loss=0.004050

      epoch  20/100: train_loss=0.003697, val_loss=0.006265, IC=-0.1400

      epoch  21/100: train_loss=0.003483

      epoch  22/100: train_loss=0.003177

      epoch  23/100: train_loss=0.002921

      epoch  24/100: train_loss=0.002611

      epoch  25/100: train_loss=0.002431, val_loss=0.003711, IC=-0.1665

      epoch  26/100: train_loss=0.002229

      epoch  27/100: train_loss=0.002071

      epoch  28/100: train_loss=0.001920

      epoch  29/100: train_loss=0.001726

      epoch  30/100: train_loss=0.001660, val_loss=0.002543, IC=-0.1783

      epoch  31/100: train_loss=0.001525

      epoch  32/100: train_loss=0.001383

      epoch  33/100: train_loss=0.001371

      epoch  34/100: train_loss=0.001285

      epoch  35/100: train_loss=0.001181, val_loss=0.001893, IC=-0.1767

      epoch  36/100: train_loss=0.001102

      epoch  37/100: train_loss=0.001083

      epoch  38/100: train_loss=0.001009

      epoch  39/100: train_loss=0.000962

      epoch  40/100: train_loss=0.000904, val_loss=0.001518, IC=-0.1652

      epoch  41/100: train_loss=0.000858

      epoch  42/100: train_loss=0.000852

      epoch  43/100: train_loss=0.000808

      epoch  44/100: train_loss=0.000778

      epoch  45/100: train_loss=0.000760, val_loss=0.001330, IC=-0.1587

      epoch  46/100: train_loss=0.000738

      epoch  47/100: train_loss=0.000720

      epoch  48/100: train_loss=0.000687

      epoch  49/100: train_loss=0.000687

      epoch  50/100: train_loss=0.000663, val_loss=0.001235, IC=-0.1313

      epoch  51/100: train_loss=0.000652

      epoch  52/100: train_loss=0.000626

      epoch  53/100: train_loss=0.000615

      epoch  54/100: train_loss=0.000604

      epoch  55/100: train_loss=0.000593, val_loss=0.001173, IC=-0.1186

      epoch  56/100: train_loss=0.000587

      epoch  57/100: train_loss=0.000582

      epoch  58/100: train_loss=0.000568

      epoch  59/100: train_loss=0.000567

      epoch  60/100: train_loss=0.000557, val_loss=0.001142, IC=-0.1103

      epoch  61/100: train_loss=0.000543

      epoch  62/100: train_loss=0.000548

      epoch  63/100: train_loss=0.000542

      epoch  64/100: train_loss=0.000536

      epoch  65/100: train_loss=0.000534, val_loss=0.001117, IC=-0.1016

      epoch  66/100: train_loss=0.000528

      epoch  67/100: train_loss=0.000527

      epoch  68/100: train_loss=0.000524

      epoch  69/100: train_loss=0.000520

      epoch  70/100: train_loss=0.000515, val_loss=0.001105, IC=-0.0947

      epoch  71/100: train_loss=0.000513

      epoch  72/100: train_loss=0.000507

      epoch  73/100: train_loss=0.000510

      epoch  74/100: train_loss=0.000509

      epoch  75/100: train_loss=0.000504, val_loss=0.001099, IC=-0.0903

      epoch  76/100: train_loss=0.000505

      epoch  77/100: train_loss=0.000506

      epoch  78/100: train_loss=0.000504

      epoch  79/100: train_loss=0.000502

      epoch  80/100: train_loss=0.000497, val_loss=0.001092, IC=-0.0893

      epoch  81/100: train_loss=0.000497

      epoch  82/100: train_loss=0.000494

      epoch  83/100: train_loss=0.000494

      epoch  84/100: train_loss=0.000501

      epoch  85/100: train_loss=0.000499, val_loss=0.001090, IC=-0.0882

      epoch  86/100: train_loss=0.000500

      epoch  87/100: train_loss=0.000493

      epoch  88/100: train_loss=0.000492

      epoch  89/100: train_loss=0.000492

      epoch  90/100: train_loss=0.000492, val_loss=0.001091, IC=-0.0871

      epoch  91/100: train_loss=0.000497

      epoch  92/100: train_loss=0.000493

      epoch  93/100: train_loss=0.000491

      epoch  94/100: train_loss=0.000493

      epoch  95/100: train_loss=0.000490, val_loss=0.001091, IC=-0.0854

      epoch  96/100: train_loss=0.000492

      epoch  97/100: train_loss=0.000494

      epoch  98/100: train_loss=0.000490

      epoch  99/100: train_loss=0.000493

      epoch 100/100: train_loss=0.000490, val_loss=0.001090, IC=-0.0855

      best_ep=5, IC=-0.0578 (46.0s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.178346

      epoch   2/100: train_loss=0.071077

      epoch   3/100: train_loss=0.043154

      epoch   4/100: train_loss=0.030743

      epoch   5/100: train_loss=0.024432, val_loss=0.007607, IC=+0.2248

      epoch   6/100: train_loss=0.020966

      epoch   7/100: train_loss=0.018031

      epoch   8/100: train_loss=0.016088

      epoch   9/100: train_loss=0.014775

      epoch  10/100: train_loss=0.013030, val_loss=0.003414, IC=+0.1863

      epoch  11/100: train_loss=0.011847

      epoch  12/100: train_loss=0.010509

      epoch  13/100: train_loss=0.009718

      epoch  14/100: train_loss=0.009128

      epoch  15/100: train_loss=0.008043, val_loss=0.002064, IC=+0.1670

      epoch  16/100: train_loss=0.007379

      epoch  17/100: train_loss=0.006764

      epoch  18/100: train_loss=0.006181

      epoch  19/100: train_loss=0.005803

      epoch  20/100: train_loss=0.005187, val_loss=0.001195, IC=+0.1647

      epoch  21/100: train_loss=0.004681

      epoch  22/100: train_loss=0.004399

      epoch  23/100: train_loss=0.003951

      epoch  24/100: train_loss=0.003709

      epoch  25/100: train_loss=0.003486, val_loss=0.000799, IC=+0.1718

      epoch  26/100: train_loss=0.003236

      epoch  27/100: train_loss=0.003040

      epoch  28/100: train_loss=0.002805

      epoch  29/100: train_loss=0.002542

      epoch  30/100: train_loss=0.002440, val_loss=0.000575, IC=+0.1637

      epoch  31/100: train_loss=0.002218

      epoch  32/100: train_loss=0.002145

      epoch  33/100: train_loss=0.002041

      epoch  34/100: train_loss=0.001914

      epoch  35/100: train_loss=0.001805, val_loss=0.000458, IC=+0.1620

      epoch  36/100: train_loss=0.001717

      epoch  37/100: train_loss=0.001619

      epoch  38/100: train_loss=0.001570

      epoch  39/100: train_loss=0.001489

      epoch  40/100: train_loss=0.001426, val_loss=0.000420, IC=+0.1401

      epoch  41/100: train_loss=0.001356

      epoch  42/100: train_loss=0.001265

      epoch  43/100: train_loss=0.001231

      epoch  44/100: train_loss=0.001193

      epoch  45/100: train_loss=0.001157, val_loss=0.000391, IC=+0.1342

      epoch  46/100: train_loss=0.001134

      epoch  47/100: train_loss=0.001087

      epoch  48/100: train_loss=0.001066

      epoch  49/100: train_loss=0.001018

      epoch  50/100: train_loss=0.001009, val_loss=0.000379, IC=+0.1197

      epoch  51/100: train_loss=0.000987

      epoch  52/100: train_loss=0.000978

      epoch  53/100: train_loss=0.000919

      epoch  54/100: train_loss=0.000898

      epoch  55/100: train_loss=0.000888, val_loss=0.000375, IC=+0.0910

      epoch  56/100: train_loss=0.000890

      epoch  57/100: train_loss=0.000869

      epoch  58/100: train_loss=0.000855

      epoch  59/100: train_loss=0.000844

      epoch  60/100: train_loss=0.000827, val_loss=0.000372, IC=+0.0837

      epoch  61/100: train_loss=0.000823

      epoch  62/100: train_loss=0.000811

      epoch  63/100: train_loss=0.000793

      epoch  64/100: train_loss=0.000785

      epoch  65/100: train_loss=0.000777, val_loss=0.000374, IC=+0.0662

      epoch  66/100: train_loss=0.000773

      epoch  67/100: train_loss=0.000763

      epoch  68/100: train_loss=0.000752

      epoch  69/100: train_loss=0.000765

      epoch  70/100: train_loss=0.000753, val_loss=0.000372, IC=+0.0520

      epoch  71/100: train_loss=0.000743

      epoch  72/100: train_loss=0.000743

      epoch  73/100: train_loss=0.000740

      epoch  74/100: train_loss=0.000724

      epoch  75/100: train_loss=0.000734, val_loss=0.000376, IC=+0.0453

      epoch  76/100: train_loss=0.000726

      epoch  77/100: train_loss=0.000715

      epoch  78/100: train_loss=0.000715

      epoch  79/100: train_loss=0.000719

      epoch  80/100: train_loss=0.000713, val_loss=0.000374, IC=+0.0382

      epoch  81/100: train_loss=0.000707

      epoch  82/100: train_loss=0.000716

      epoch  83/100: train_loss=0.000711

      epoch  84/100: train_loss=0.000704

      epoch  85/100: train_loss=0.000704, val_loss=0.000376, IC=+0.0432

      epoch  86/100: train_loss=0.000703

      epoch  87/100: train_loss=0.000705

      epoch  88/100: train_loss=0.000704

      epoch  89/100: train_loss=0.000697

      epoch  90/100: train_loss=0.000712, val_loss=0.000373, IC=+0.0360

      epoch  91/100: train_loss=0.000699

      epoch  92/100: train_loss=0.000705

      epoch  93/100: train_loss=0.000699

      epoch  94/100: train_loss=0.000705

      epoch  95/100: train_loss=0.000705, val_loss=0.000373, IC=+0.0351

      epoch  96/100: train_loss=0.000697

      epoch  97/100: train_loss=0.000698

      epoch  98/100: train_loss=0.000700

      epoch  99/100: train_loss=0.000703

      epoch 100/100: train_loss=0.000691, val_loss=0.000374, IC=+0.0353

      best_ep=5, IC=+0.2248 (46.4s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.334468

      epoch   2/100: train_loss=0.080149

      epoch   3/100: train_loss=0.053848

      epoch   4/100: train_loss=0.036689

      epoch   5/100: train_loss=0.027071, val_loss=0.019142, IC=+0.1516

      epoch   6/100: train_loss=0.021082

      epoch   7/100: train_loss=0.017018

      epoch   8/100: train_loss=0.013889

      epoch   9/100: train_loss=0.011689

      epoch  10/100: train_loss=0.010226, val_loss=0.003805, IC=+0.1045

      epoch  11/100: train_loss=0.008990

      epoch  12/100: train_loss=0.008270

      epoch  13/100: train_loss=0.007307

      epoch  14/100: train_loss=0.006483

      epoch  15/100: train_loss=0.005829, val_loss=0.002177, IC=+0.0459

      epoch  16/100: train_loss=0.005311

      epoch  17/100: train_loss=0.004920

      epoch  18/100: train_loss=0.004427

      epoch  19/100: train_loss=0.004085

      epoch  20/100: train_loss=0.003730, val_loss=0.001695, IC=+0.0065

      epoch  21/100: train_loss=0.003432

      epoch  22/100: train_loss=0.003189

      epoch  23/100: train_loss=0.003005

      epoch  24/100: train_loss=0.002785

      epoch  25/100: train_loss=0.002610, val_loss=0.001425, IC=-0.0230

      epoch  26/100: train_loss=0.002432

      epoch  27/100: train_loss=0.002313

      epoch  28/100: train_loss=0.002205

      epoch  29/100: train_loss=0.002067

      epoch  30/100: train_loss=0.001958, val_loss=0.001230, IC=-0.0441

      epoch  31/100: train_loss=0.001831

      epoch  32/100: train_loss=0.001779

      epoch  33/100: train_loss=0.001713

      epoch  34/100: train_loss=0.001613

      epoch  35/100: train_loss=0.001552, val_loss=0.001123, IC=-0.0566

      epoch  36/100: train_loss=0.001516

      epoch  37/100: train_loss=0.001441

      epoch  38/100: train_loss=0.001402

      epoch  39/100: train_loss=0.001342

      epoch  40/100: train_loss=0.001323, val_loss=0.001066, IC=-0.0673

      epoch  41/100: train_loss=0.001281

      epoch  42/100: train_loss=0.001234

      epoch  43/100: train_loss=0.001211

      epoch  44/100: train_loss=0.001164

      epoch  45/100: train_loss=0.001134, val_loss=0.001012, IC=-0.0758

      epoch  46/100: train_loss=0.001100

      epoch  47/100: train_loss=0.001109

      epoch  48/100: train_loss=0.001090

      epoch  49/100: train_loss=0.001052

      epoch  50/100: train_loss=0.001032, val_loss=0.000981, IC=-0.0872

      epoch  51/100: train_loss=0.001027

      epoch  52/100: train_loss=0.001006

      epoch  53/100: train_loss=0.000981

      epoch  54/100: train_loss=0.000963

      epoch  55/100: train_loss=0.000953, val_loss=0.000969, IC=-0.0905

      epoch  56/100: train_loss=0.000957

      epoch  57/100: train_loss=0.000931

      epoch  58/100: train_loss=0.000935

      epoch  59/100: train_loss=0.000911

      epoch  60/100: train_loss=0.000906, val_loss=0.000923, IC=-0.0831

      epoch  61/100: train_loss=0.000885

      epoch  62/100: train_loss=0.000883

      epoch  63/100: train_loss=0.000886

      epoch  64/100: train_loss=0.000870

      epoch  65/100: train_loss=0.000867, val_loss=0.000949, IC=-0.1101

      epoch  66/100: train_loss=0.000853

      epoch  67/100: train_loss=0.000854

      epoch  68/100: train_loss=0.000842

      epoch  69/100: train_loss=0.000831

      epoch  70/100: train_loss=0.000832, val_loss=0.000925, IC=-0.1043

      epoch  71/100: train_loss=0.000828

      epoch  72/100: train_loss=0.000821

      epoch  73/100: train_loss=0.000815

      epoch  74/100: train_loss=0.000821

      epoch  75/100: train_loss=0.000818, val_loss=0.000912, IC=-0.1030

      epoch  76/100: train_loss=0.000801

      epoch  77/100: train_loss=0.000808

      epoch  78/100: train_loss=0.000804

      epoch  79/100: train_loss=0.000800

      epoch  80/100: train_loss=0.000802, val_loss=0.000900, IC=-0.0980

      epoch  81/100: train_loss=0.000793

      epoch  82/100: train_loss=0.000794

      epoch  83/100: train_loss=0.000785

      epoch  84/100: train_loss=0.000794

      epoch  85/100: train_loss=0.000795, val_loss=0.000901, IC=-0.1027

      epoch  86/100: train_loss=0.000790

      epoch  87/100: train_loss=0.000790

      epoch  88/100: train_loss=0.000791

      epoch  89/100: train_loss=0.000786

      epoch  90/100: train_loss=0.000792, val_loss=0.000897, IC=-0.1013

      epoch  91/100: train_loss=0.000795

      epoch  92/100: train_loss=0.000784

      epoch  93/100: train_loss=0.000775

      epoch  94/100: train_loss=0.000789

      epoch  95/100: train_loss=0.000786, val_loss=0.000897, IC=-0.1012

      epoch  96/100: train_loss=0.000791

      epoch  97/100: train_loss=0.000783

      epoch  98/100: train_loss=0.000785

      epoch  99/100: train_loss=0.000779

      epoch 100/100: train_loss=0.000775, val_loss=0.000896, IC=-0.1003

      best_ep=5, IC=+0.1516 (46.0s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.294922

      epoch   2/100: train_loss=0.136353

      epoch   3/100: train_loss=0.071907

      epoch   4/100: train_loss=0.049916

      epoch   5/100: train_loss=0.039946, val_loss=0.016454, IC=-0.0057

      epoch   6/100: train_loss=0.032287

      epoch   7/100: train_loss=0.027313

      epoch   8/100: train_loss=0.023503

      epoch   9/100: train_loss=0.020320

      epoch  10/100: train_loss=0.017573, val_loss=0.005719, IC=+0.0047

      epoch  11/100: train_loss=0.015557

      epoch  12/100: train_loss=0.013376

      epoch  13/100: train_loss=0.012205

      epoch  14/100: train_loss=0.010705

      epoch  15/100: train_loss=0.009619, val_loss=0.002192, IC=+0.0019

      epoch  16/100: train_loss=0.008528

      epoch  17/100: train_loss=0.007511

      epoch  18/100: train_loss=0.006860

      epoch  19/100: train_loss=0.006106

      epoch  20/100: train_loss=0.005566, val_loss=0.001039, IC=+0.0070

      epoch  21/100: train_loss=0.004945

      epoch  22/100: train_loss=0.004608

      epoch  23/100: train_loss=0.004183

      epoch  24/100: train_loss=0.003850

      epoch  25/100: train_loss=0.003574, val_loss=0.000671, IC=-0.0044

      epoch  26/100: train_loss=0.003263

      epoch  27/100: train_loss=0.003018

      epoch  28/100: train_loss=0.002840

      epoch  29/100: train_loss=0.002644

      epoch  30/100: train_loss=0.002406, val_loss=0.000503, IC=+0.0181

      epoch  31/100: train_loss=0.002273

      epoch  32/100: train_loss=0.002127

      epoch  33/100: train_loss=0.001999

      epoch  34/100: train_loss=0.001904

      epoch  35/100: train_loss=0.001830, val_loss=0.000443, IC=+0.0168

      epoch  36/100: train_loss=0.001699

      epoch  37/100: train_loss=0.001636

      epoch  38/100: train_loss=0.001537

      epoch  39/100: train_loss=0.001469

      epoch  40/100: train_loss=0.001431, val_loss=0.000404, IC=+0.0175

      epoch  41/100: train_loss=0.001342

      epoch  42/100: train_loss=0.001298

      epoch  43/100: train_loss=0.001272

      epoch  44/100: train_loss=0.001237

      epoch  45/100: train_loss=0.001179, val_loss=0.000383, IC=+0.0146

      epoch  46/100: train_loss=0.001159

      epoch  47/100: train_loss=0.001121

      epoch  48/100: train_loss=0.001086

      epoch  49/100: train_loss=0.001057

      epoch  50/100: train_loss=0.001032, val_loss=0.000369, IC=+0.0261

      epoch  51/100: train_loss=0.001034

      epoch  52/100: train_loss=0.001004

      epoch  53/100: train_loss=0.000987

      epoch  54/100: train_loss=0.000984

      epoch  55/100: train_loss=0.000963, val_loss=0.000362, IC=+0.0237

      epoch  56/100: train_loss=0.000951

      epoch  57/100: train_loss=0.000935

      epoch  58/100: train_loss=0.000921

      epoch  59/100: train_loss=0.000908

      epoch  60/100: train_loss=0.000894, val_loss=0.000356, IC=+0.0204

      epoch  61/100: train_loss=0.000903

      epoch  62/100: train_loss=0.000882

      epoch  63/100: train_loss=0.000869

      epoch  64/100: train_loss=0.000873

      epoch  65/100: train_loss=0.000870, val_loss=0.000353, IC=+0.0274

      epoch  66/100: train_loss=0.000863

      epoch  67/100: train_loss=0.000853

      epoch  68/100: train_loss=0.000844

      epoch  69/100: train_loss=0.000838

      epoch  70/100: train_loss=0.000845, val_loss=0.000347, IC=+0.0322

      epoch  71/100: train_loss=0.000837

      epoch  72/100: train_loss=0.000830

      epoch  73/100: train_loss=0.000833

      epoch  74/100: train_loss=0.000834

      epoch  75/100: train_loss=0.000829, val_loss=0.000348, IC=+0.0240

      epoch  76/100: train_loss=0.000831

      epoch  77/100: train_loss=0.000828

      epoch  78/100: train_loss=0.000821

      epoch  79/100: train_loss=0.000825

      epoch  80/100: train_loss=0.000812, val_loss=0.000347, IC=+0.0202

      epoch  81/100: train_loss=0.000813

      epoch  82/100: train_loss=0.000811

      epoch  83/100: train_loss=0.000813

      epoch  84/100: train_loss=0.000813

      epoch  85/100: train_loss=0.000812, val_loss=0.000346, IC=+0.0256

      epoch  86/100: train_loss=0.000811

      epoch  87/100: train_loss=0.000810

      epoch  88/100: train_loss=0.000805

      epoch  89/100: train_loss=0.000803

      epoch  90/100: train_loss=0.000802, val_loss=0.000346, IC=+0.0213

      epoch  91/100: train_loss=0.000814

      epoch  92/100: train_loss=0.000807

      epoch  93/100: train_loss=0.000808

      epoch  94/100: train_loss=0.000801

      epoch  95/100: train_loss=0.000810, val_loss=0.000346, IC=+0.0207

      epoch  96/100: train_loss=0.000803

      epoch  97/100: train_loss=0.000806

      epoch  98/100: train_loss=0.000801

      epoch  99/100: train_loss=0.000809

      epoch 100/100: train_loss=0.000806, val_loss=0.000346, IC=+0.0204

      best_ep=70, IC=+0.0322 (46.2s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=1.300624

      epoch   2/100: train_loss=0.333447

      epoch   3/100: train_loss=0.112863

      epoch   4/100: train_loss=0.052040

      epoch   5/100: train_loss=0.037148, val_loss=0.011236, IC=-0.1031

      epoch   6/100: train_loss=0.028826

      epoch   7/100: train_loss=0.023374

      epoch   8/100: train_loss=0.020533

      epoch   9/100: train_loss=0.017268

      epoch  10/100: train_loss=0.015216, val_loss=0.003720, IC=-0.0208

      epoch  11/100: train_loss=0.013324

      epoch  12/100: train_loss=0.011753

      epoch  13/100: train_loss=0.010600

      epoch  14/100: train_loss=0.009485

      epoch  15/100: train_loss=0.008570, val_loss=0.002125, IC=+0.0461

      epoch  16/100: train_loss=0.007866

      epoch  17/100: train_loss=0.007100

      epoch  18/100: train_loss=0.006586

      epoch  19/100: train_loss=0.005835

      epoch  20/100: train_loss=0.005462, val_loss=0.001251, IC=+0.0816

      epoch  21/100: train_loss=0.004995

      epoch  22/100: train_loss=0.004604

      epoch  23/100: train_loss=0.004253

      epoch  24/100: train_loss=0.003928

      epoch  25/100: train_loss=0.003678, val_loss=0.000851, IC=+0.1047

      epoch  26/100: train_loss=0.003441

      epoch  27/100: train_loss=0.003186

      epoch  28/100: train_loss=0.002980

      epoch  29/100: train_loss=0.002786

      epoch  30/100: train_loss=0.002579, val_loss=0.000655, IC=+0.0986

      epoch  31/100: train_loss=0.002434

      epoch  32/100: train_loss=0.002280

      epoch  33/100: train_loss=0.002162

      epoch  34/100: train_loss=0.002063

      epoch  35/100: train_loss=0.001941, val_loss=0.000558, IC=+0.1085

      epoch  36/100: train_loss=0.001862

      epoch  37/100: train_loss=0.001743

      epoch  38/100: train_loss=0.001688

      epoch  39/100: train_loss=0.001618

      epoch  40/100: train_loss=0.001554, val_loss=0.000508, IC=+0.1158

      epoch  41/100: train_loss=0.001494

      epoch  42/100: train_loss=0.001438

      epoch  43/100: train_loss=0.001417

      epoch  44/100: train_loss=0.001342

      epoch  45/100: train_loss=0.001307, val_loss=0.000476, IC=+0.1341

      epoch  46/100: train_loss=0.001288

      epoch  47/100: train_loss=0.001230

      epoch  48/100: train_loss=0.001229

      epoch  49/100: train_loss=0.001187

      epoch  50/100: train_loss=0.001158, val_loss=0.000468, IC=+0.1352

      epoch  51/100: train_loss=0.001145

      epoch  52/100: train_loss=0.001106

      epoch  53/100: train_loss=0.001097

      epoch  54/100: train_loss=0.001064

      epoch  55/100: train_loss=0.001073, val_loss=0.000461, IC=+0.1373

      epoch  56/100: train_loss=0.001044

      epoch  57/100: train_loss=0.001043

      epoch  58/100: train_loss=0.001012

      epoch  59/100: train_loss=0.001011

      epoch  60/100: train_loss=0.000992, val_loss=0.000458, IC=+0.1388

      epoch  61/100: train_loss=0.000986

      epoch  62/100: train_loss=0.000976

      epoch  63/100: train_loss=0.000959

      epoch  64/100: train_loss=0.000946

      epoch  65/100: train_loss=0.000941, val_loss=0.000455, IC=+0.1398

      epoch  66/100: train_loss=0.000941

      epoch  67/100: train_loss=0.000942

      epoch  68/100: train_loss=0.000934

      epoch  69/100: train_loss=0.000936

      epoch  70/100: train_loss=0.000915, val_loss=0.000452, IC=+0.1429

      epoch  71/100: train_loss=0.000918

      epoch  72/100: train_loss=0.000920

      epoch  73/100: train_loss=0.000905

      epoch  74/100: train_loss=0.000899

      epoch  75/100: train_loss=0.000909, val_loss=0.000452, IC=+0.1408

      epoch  76/100: train_loss=0.000897

      epoch  77/100: train_loss=0.000910

      epoch  78/100: train_loss=0.000897

      epoch  79/100: train_loss=0.000892

      epoch  80/100: train_loss=0.000893, val_loss=0.000452, IC=+0.1398

      epoch  81/100: train_loss=0.000889

      epoch  82/100: train_loss=0.000887

      epoch  83/100: train_loss=0.000890

      epoch  84/100: train_loss=0.000883

      epoch  85/100: train_loss=0.000879, val_loss=0.000452, IC=+0.1380

      epoch  86/100: train_loss=0.000888

      epoch  87/100: train_loss=0.000883

      epoch  88/100: train_loss=0.000887

      epoch  89/100: train_loss=0.000887

      epoch  90/100: train_loss=0.000878, val_loss=0.000450, IC=+0.1415

      epoch  91/100: train_loss=0.000877

      epoch  92/100: train_loss=0.000877

      epoch  93/100: train_loss=0.000872

      epoch  94/100: train_loss=0.000883

      epoch  95/100: train_loss=0.000874, val_loss=0.000451, IC=+0.1391

      epoch  96/100: train_loss=0.000878

      epoch  97/100: train_loss=0.000880

      epoch  98/100: train_loss=0.000877

      epoch  99/100: train_loss=0.000880

      epoch 100/100: train_loss=0.000874, val_loss=0.000450, IC=+0.1399

      best_ep=70, IC=+0.1429 (39.7s, 20 checkpoints)

  Fold 6: creating sequences...
    train=21,820 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.149181

      epoch   2/100: train_loss=0.076193

      epoch   3/100: train_loss=0.052160

      epoch   4/100: train_loss=0.041381

      epoch   5/100: train_loss=0.033801, val_loss=0.021651, IC=-0.0754

      epoch   6/100: train_loss=0.027704

      epoch   7/100: train_loss=0.023723

      epoch   8/100: train_loss=0.019954

      epoch   9/100: train_loss=0.016719

      epoch  10/100: train_loss=0.014222, val_loss=0.006980, IC=-0.0801

      epoch  11/100: train_loss=0.012483

      epoch  12/100: train_loss=0.010679

      epoch  13/100: train_loss=0.009357

      epoch  14/100: train_loss=0.008270

      epoch  15/100: train_loss=0.007101, val_loss=0.003025, IC=-0.0989

      epoch  16/100: train_loss=0.006507

      epoch  17/100: train_loss=0.005643

      epoch  18/100: train_loss=0.005056

      epoch  19/100: train_loss=0.004586

      epoch  20/100: train_loss=0.004286, val_loss=0.001770, IC=-0.1155

      epoch  21/100: train_loss=0.003862

      epoch  22/100: train_loss=0.003462

      epoch  23/100: train_loss=0.003192

      epoch  24/100: train_loss=0.002925

      epoch  25/100: train_loss=0.002687, val_loss=0.001189, IC=-0.1008

      epoch  26/100: train_loss=0.002508

      epoch  27/100: train_loss=0.002413

      epoch  28/100: train_loss=0.002228

      epoch  29/100: train_loss=0.002049

      epoch  30/100: train_loss=0.001897, val_loss=0.000955, IC=-0.1151

      epoch  31/100: train_loss=0.001821

      epoch  32/100: train_loss=0.001743

      epoch  33/100: train_loss=0.001600

      epoch  34/100: train_loss=0.001529

      epoch  35/100: train_loss=0.001479, val_loss=0.000791, IC=-0.0873

      epoch  36/100: train_loss=0.001413

      epoch  37/100: train_loss=0.001372

      epoch  38/100: train_loss=0.001292

      epoch  39/100: train_loss=0.001259

      epoch  40/100: train_loss=0.001224, val_loss=0.000731, IC=-0.0870

      epoch  41/100: train_loss=0.001193

      epoch  42/100: train_loss=0.001149

      epoch  43/100: train_loss=0.001132

      epoch  44/100: train_loss=0.001101

      epoch  45/100: train_loss=0.001085, val_loss=0.000707, IC=-0.1147

      epoch  46/100: train_loss=0.001037

      epoch  47/100: train_loss=0.001030

      epoch  48/100: train_loss=0.001008

      epoch  49/100: train_loss=0.001002

      epoch  50/100: train_loss=0.000999, val_loss=0.000662, IC=-0.0901

      epoch  51/100: train_loss=0.000974

      epoch  52/100: train_loss=0.000962

      epoch  53/100: train_loss=0.000947

      epoch  54/100: train_loss=0.000954

      epoch  55/100: train_loss=0.000935, val_loss=0.000657, IC=-0.1123

      epoch  56/100: train_loss=0.000926

      epoch  57/100: train_loss=0.000922

      epoch  58/100: train_loss=0.000919

      epoch  59/100: train_loss=0.000914

      epoch  60/100: train_loss=0.000903, val_loss=0.000646, IC=-0.1076

      epoch  61/100: train_loss=0.000900

      epoch  62/100: train_loss=0.000886

      epoch  63/100: train_loss=0.000884

      epoch  64/100: train_loss=0.000883

      epoch  65/100: train_loss=0.000879, val_loss=0.000640, IC=-0.1115

      epoch  66/100: train_loss=0.000875

      epoch  67/100: train_loss=0.000871

      epoch  68/100: train_loss=0.000873

      epoch  69/100: train_loss=0.000877

      epoch  70/100: train_loss=0.000871, val_loss=0.000628, IC=-0.0986

      epoch  71/100: train_loss=0.000867

      epoch  72/100: train_loss=0.000868

      epoch  73/100: train_loss=0.000867

      epoch  74/100: train_loss=0.000867

      epoch  75/100: train_loss=0.000860, val_loss=0.000631, IC=-0.1060

      epoch  76/100: train_loss=0.000858

      epoch  77/100: train_loss=0.000855

      epoch  78/100: train_loss=0.000861

      epoch  79/100: train_loss=0.000861

      epoch  80/100: train_loss=0.000856, val_loss=0.000625, IC=-0.0973

      epoch  81/100: train_loss=0.000851

      epoch  82/100: train_loss=0.000857

      epoch  83/100: train_loss=0.000856

      epoch  84/100: train_loss=0.000857

      epoch  85/100: train_loss=0.000854, val_loss=0.000628, IC=-0.1065

      epoch  86/100: train_loss=0.000853

      epoch  87/100: train_loss=0.000846

      epoch  88/100: train_loss=0.000847

      epoch  89/100: train_loss=0.000852

      epoch  90/100: train_loss=0.000859, val_loss=0.000627, IC=-0.1057

      epoch  91/100: train_loss=0.000854

      epoch  92/100: train_loss=0.000850

      epoch  93/100: train_loss=0.000848

      epoch  94/100: train_loss=0.000847

      epoch  95/100: train_loss=0.000852, val_loss=0.000627, IC=-0.1042

      epoch  96/100: train_loss=0.000850

      epoch  97/100: train_loss=0.000844

      epoch  98/100: train_loss=0.000855

      epoch  99/100: train_loss=0.000848

      epoch 100/100: train_loss=0.000850, val_loss=0.000627, IC=-0.1047

      best_ep=5, IC=-0.0754 (36.2s, 20 checkpoints)

  Fold 7: creating sequences...
    train=16,660 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.288743

      epoch   2/100: train_loss=0.114331

      epoch   3/100: train_loss=0.062045

      epoch   4/100: train_loss=0.046279

      epoch   5/100: train_loss=0.036666, val_loss=0.023415, IC=-0.0354

      epoch   6/100: train_loss=0.028366

      epoch   7/100: train_loss=0.024140

      epoch   8/100: train_loss=0.020123

      epoch   9/100: train_loss=0.017773

      epoch  10/100: train_loss=0.015352, val_loss=0.007703, IC=-0.0186

      epoch  11/100: train_loss=0.014071

      epoch  12/100: train_loss=0.012065

      epoch  13/100: train_loss=0.011111

      epoch  14/100: train_loss=0.010007

      epoch  15/100: train_loss=0.008935, val_loss=0.004012, IC=-0.0008

      epoch  16/100: train_loss=0.008003

      epoch  17/100: train_loss=0.007094

      epoch  18/100: train_loss=0.006219

      epoch  19/100: train_loss=0.005759

      epoch  20/100: train_loss=0.005082, val_loss=0.002598, IC=+0.0031

      epoch  21/100: train_loss=0.004657

      epoch  22/100: train_loss=0.004326

      epoch  23/100: train_loss=0.003905

      epoch  24/100: train_loss=0.003668

      epoch  25/100: train_loss=0.003151, val_loss=0.001942, IC=+0.0249

      epoch  26/100: train_loss=0.003004

      epoch  27/100: train_loss=0.002758

      epoch  28/100: train_loss=0.002583

      epoch  29/100: train_loss=0.002484

      epoch  30/100: train_loss=0.002207, val_loss=0.001837, IC=+0.0142

      epoch  31/100: train_loss=0.002068

      epoch  32/100: train_loss=0.001933

      epoch  33/100: train_loss=0.001911

      epoch  34/100: train_loss=0.001774

      epoch  35/100: train_loss=0.001690, val_loss=0.001514, IC=+0.0289

      epoch  36/100: train_loss=0.001633

      epoch  37/100: train_loss=0.001524

      epoch  38/100: train_loss=0.001434

      epoch  39/100: train_loss=0.001344

      epoch  40/100: train_loss=0.001332, val_loss=0.001461, IC=+0.0225

      epoch  41/100: train_loss=0.001282

      epoch  42/100: train_loss=0.001245

      epoch  43/100: train_loss=0.001220

      epoch  44/100: train_loss=0.001151

      epoch  45/100: train_loss=0.001138, val_loss=0.001398, IC=+0.0263

      epoch  46/100: train_loss=0.001094

      epoch  47/100: train_loss=0.001083

      epoch  48/100: train_loss=0.001047

      epoch  49/100: train_loss=0.001031

      epoch  50/100: train_loss=0.001009, val_loss=0.001318, IC=+0.0256

      epoch  51/100: train_loss=0.000988

      epoch  52/100: train_loss=0.001002

      epoch  53/100: train_loss=0.000940

      epoch  54/100: train_loss=0.000921

      epoch  55/100: train_loss=0.000925, val_loss=0.001332, IC=+0.0291

      epoch  56/100: train_loss=0.000937

      epoch  57/100: train_loss=0.000913

      epoch  58/100: train_loss=0.000896

      epoch  59/100: train_loss=0.000901

      epoch  60/100: train_loss=0.000877, val_loss=0.001298, IC=+0.0125

      epoch  61/100: train_loss=0.000879

      epoch  62/100: train_loss=0.000855

      epoch  63/100: train_loss=0.000851

      epoch  64/100: train_loss=0.000856

      epoch  65/100: train_loss=0.000842, val_loss=0.001294, IC=+0.0119

      epoch  66/100: train_loss=0.000840

      epoch  67/100: train_loss=0.000831

      epoch  68/100: train_loss=0.000832

      epoch  69/100: train_loss=0.000831

      epoch  70/100: train_loss=0.000816, val_loss=0.001239, IC=+0.0221

      epoch  71/100: train_loss=0.000839

      epoch  72/100: train_loss=0.000830

      epoch  73/100: train_loss=0.000803

      epoch  74/100: train_loss=0.000841

      epoch  75/100: train_loss=0.000808, val_loss=0.001262, IC=+0.0187

      epoch  76/100: train_loss=0.000810

      epoch  77/100: train_loss=0.000811

      epoch  78/100: train_loss=0.000805

      epoch  79/100: train_loss=0.000801

      epoch  80/100: train_loss=0.000810, val_loss=0.001244, IC=+0.0176

      epoch  81/100: train_loss=0.000810

      epoch  82/100: train_loss=0.000799

      epoch  83/100: train_loss=0.000784

      epoch  84/100: train_loss=0.000781

      epoch  85/100: train_loss=0.000791, val_loss=0.001229, IC=+0.0136

      epoch  86/100: train_loss=0.000794

      epoch  87/100: train_loss=0.000798

      epoch  88/100: train_loss=0.000792

      epoch  89/100: train_loss=0.000799

      epoch  90/100: train_loss=0.000789, val_loss=0.001231, IC=+0.0155

      epoch  91/100: train_loss=0.000788

      epoch  92/100: train_loss=0.000790

      epoch  93/100: train_loss=0.000789

      epoch  94/100: train_loss=0.000790

      epoch  95/100: train_loss=0.000789, val_loss=0.001229, IC=+0.0131

      epoch  96/100: train_loss=0.000789

      epoch  97/100: train_loss=0.000791

      epoch  98/100: train_loss=0.000799

      epoch  99/100: train_loss=0.000813

      epoch 100/100: train_loss=0.000798, val_loss=0.001228, IC=+0.0145

      best_ep=55, IC=+0.0291 (28.2s, 20 checkpoints)

  nlinear: best_epoch=5, IC=+0.0344 (330.5s)

  Best: nlinear @ epoch 5 (IC=+0.0344)
  Saved to ~/ml4t/public-s6-fx_pairs/case_studies/fx_pairs/run_log/training/1d65a7393f44/diagnostics

shape: (60, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ label      ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean  ┆ ic_t     ┆ training_ ┆ predictio │
│ ---        ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---      ┆ ---      ┆ hash      ┆ n_hash    │
│ str        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64      ┆ f64      ┆ ---       ┆ ---       │
│            ┆ str       ┆ str       ┆ i64       ┆   ┆          ┆          ┆ str       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ fwd_ret_1d ┆ nlinear   ┆ epoch     ┆ 5         ┆ … ┆ 0.013303 ┆ 1.723168 ┆ e9348cbe2 ┆ 9eb5dd857 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 199       ┆ 7d1       │
│ fwd_ret_1d ┆ nlinear   ┆ epoch     ┆ 10        ┆ … ┆ 0.014516 ┆ 2.158379 ┆ e9348cbe2 ┆ 26150ab0d │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 199       ┆ 3db       │
│ fwd_ret_1d ┆ nlinear   ┆ epoch     ┆ 15        ┆ … ┆ 0.013679 ┆ 2.06296  ┆ e9348cbe2 ┆ 70cc489e4 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 199       ┆ 0cd       │
│ fwd_ret_1d ┆ nlinear   ┆ epoch     ┆ 20        ┆ … ┆ 0.01171  ┆ 1.781676 ┆ e9348cbe2 ┆ 9eae73b86 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 199       ┆ 751       │
│ fwd_ret_1d ┆ nlinear   ┆ epoch     ┆ 25        ┆ … ┆ 0.012545 ┆ 1.851869 ┆ e9348cbe2 ┆ 1df5922d7 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 199       ┆ 1dc       │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ fwd_ret_5d ┆ nlinear   ┆ epoch     ┆ 80        ┆ … ┆ 0.013017 ┆ 0.757352 ┆ c845bed56 ┆ 0c5ecb57c │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 399       ┆ b04       │
│ fwd_ret_5d ┆ nlinear   ┆ epoch     ┆ 85        ┆ … ┆ 0.010603 ┆ 0.639332 ┆ c845bed56 ┆ 099830b92 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 399       ┆ 20a       │
│ fwd_ret_5d ┆ nlinear   ┆ epoch     ┆ 90        ┆ … ┆ 0.011746 ┆ 0.720837 ┆ c845bed56 ┆ cba7f1e37 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 399       ┆ e22       │
│ fwd_ret_5d ┆ nlinear   ┆ epoch     ┆ 95        ┆ … ┆ 0.011388 ┆ 0.689337 ┆ c845bed56 ┆ 6ec12c495 │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 399       ┆ c30       │
│ fwd_ret_5d ┆ nlinear   ┆ epoch     ┆ 100       ┆ … ┆ 0.011209 ┆ 0.676444 ┆ c845bed56 ┆ b6bd7b1dc │
│            ┆           ┆           ┆           ┆   ┆          ┆          ┆ 399       ┆ d28       │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

## Verify checkpoint reload

Repeating the request validates the fitted-state digests and returns the same prediction
identities. The notebook never reconstructs another family from an empty cache path.

In [6]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("NLinear checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview sequence checkpoints remain outside official comparisons.")

Official prediction population: 7cf7405afc08

## Key takeaways

- NLinear and TCN use the same sequence eligibility contract but keep separate model identities.
- Gaps remove affected windows instead of being hidden by positional indexing.
- Stored weights reproduce every declared checkpoint without retraining.