# LSTM - FX Pairs

An LSTM carries a hidden state forward across the lookback window and updates it at each
observation, so what it can use from the history is not fixed in advance the way NLinear's
subtraction of the last level is, nor bounded by a receptive field the way TCN's dilated stack
is. It is the recurrent member of the three architectures this case study's `deep_learning` menu
declares. This notebook constructs only the LSTM request; comparisons with NLinear, TCN, TabM,
trees, and linear models are deferred to `12_model_analysis`, where the complete registered
population is available.

**Learning objectives**

- Resolve the LSTM's lookback, hidden size, depth, and checkpoint schedule before fitting.
- Use the shared gap-safe sequence eligibility instead of positional row windows.
- Prove weight reload and catalog handoff for every declared epoch.

**Book reference**: Chapter 13, Section 13.4

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published LSTM FX configuration."""

import json

import polars as pl
import torch

from case_studies.research import (
    ExecutionTier,
    declared_labels,
    open_study,
    plan_models,
    population_supersedes,
    sweep_labels,
)
from utils.modeling import load_configs
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
LOOKBACK = 0
BATCH_SIZE = 0
DEVICE = ""
SEED = 42
POPULATION_NAME = ""
SUPERSEDES_POPULATION: str = "2f5810edd6cd"
# The tier is a parameter, not something inferred from whether a reduction happens to be set.
# Inferring it meant a run could be reduced and still open the case study's own artifacts in
# place, which is the production path; a reader under test then wrote where the published run
# writes. WORKSPACE is the other half: a preview has nowhere else to put its results.
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None

## Resolve one forecasting request

The shared runner derives fold boundaries from the finalized label timeline. A missing daily
observation invalidates every lookback window that crosses it, so validation coverage can be
smaller than the raw validation panel while still being exact.

In [3]:
set_global_seeds(SEED)
# The reductions are read before the study is opened, because which study to open is decided by
# the tier and the two have to agree: a preview that reduces nothing is a canonical run wearing
# the wrong tier, and a canonical run carrying reductions would publish a narrowed population
# under the canonical name.
REDUCTION_PARAMETERS = {
    "folds": list(range(MAX_FOLDS)) if MAX_FOLDS else None,
    "max_symbols": MAX_SYMBOLS or None,
}
reductions = {key: value for key, value in REDUCTION_PARAMETERS.items() if value is not None}
tier = ExecutionTier(EXECUTION_TIER)
if tier is ExecutionTier.PREVIEW and not reductions:
    raise ValueError("preview execution must declare at least one reduction")
if tier is ExecutionTier.CANONICAL and reductions:
    raise ValueError(f"canonical execution cannot carry reductions: {sorted(reductions)}")
study = open_study(CASE_STUDY_ID, execution_tier=tier, workspace=WORKSPACE or None)

# Which labels this notebook fits is a question for the training menus, not for the sweep list:
# `setup.yaml` says which labels the case study carries, a menu says what to fit for one of them,
# and a sweep label whose menu declares no `deep_learning:` section owes nothing here. The two
# agree in this case study today, so restating the sweep list produced the right answer by
# coincidence and would have kept producing it silently after a menu changed. The order stays
# `setup.yaml`'s rather than `declared_labels`' menu-file order because the population is named
# after its labels and hashed over its members as an ordered list, so re-ordering would give the
# published population a new identity and demand a supersedes for a run that fits the same models.
declared = declared_labels(study, "deep_learning")
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [label for label in sweep_labels(study) if label in set(declared)]
)

# A run that fits fewer labels than the menus declare is not the canonical population, and the
# architecture is fixed below, so the label set is the only knob that narrows it. Such a run must
# publish under its own name rather than register a partial snapshot under the canonical one.
if set(labels) != set(declared) and not POPULATION_NAME:
    raise ValueError(
        f"this run fits {len(labels)} of the {len(declared)} declared labels, so it cannot "
        "publish the canonical population; pass POPULATION_NAME to give it its own"
    )

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

# An empty DEVICE resolves to what the machine has. The runners refuse "cuda" on a host without
# it rather than falling back silently - which is the right contract for a run whose results get
# registered - so a hardcoded "cuda" default made the notebook unrunnable for any reader without
# an NVIDIA card, and unrunnable on a CPU CI runner. Resolving here keeps the refusal for anyone
# who asks for "cuda" explicitly; the resolved value is printed with the rest of the numerics
# below, so a run never leaves it implicit.
device = DEVICE or ("cuda" if torch.cuda.is_available() else "cpu")
overrides = {
    "device": device,
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
    **({"lookback": LOOKBACK} if LOOKBACK else {}),
}
ARCHITECTURE = "lstm_h64"
menu = {
    label: [
        config["config_name"]
        for config in load_configs(CASE_STUDY_ID, label, family="deep_learning")
    ]
    for label in labels
}
uncovered = {label: sorted(set(names) - {ARCHITECTURE}) for label, names in menu.items()}
for label, names in menu.items():
    if ARCHITECTURE not in names:
        raise RuntimeError(
            f"{ARCHITECTURE} is not in the configured deep_learning menu for {label}: {names}"
        )

requests = [
    study.model(
        family="deep_learning",
        label=label,
        config_name=ARCHITECTURE,
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label in labels
]
plan = plan_models(study, requests=requests)

# This notebook owes one architecture on every configured label. The rest of the family menu is
# named here rather than left implicit, because a population that is short a configured model is
# otherwise indistinguishable from a complete one.
configured = {(label, ARCHITECTURE) for label in labels}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        f"the plan does not match this notebook's declared coverage; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )
specs = {member.label: json.loads(member.spec_json) for member in plan.members}
computations = {label: spec.get("computation", spec) for label, spec in specs.items()}
computation = computations[labels[0]]

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {computation['numerics']['device']}")
print(f"Lookback: {computation['preprocessing']['lookback']} consecutive daily observations")
for horizon, values in computations.items():
    print(f"Eligible validation rows, {horizon}: {values['expected_prediction_keys']['n_rows']:,}")
for horizon, names in uncovered.items():
    print(
        f"Configured deep_learning models this notebook does not run, {horizon}: {names or 'none'}"
    )

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda
Lookback: 60 consecutive daily observations
Eligible validation rows, fwd_ret_1d: 41,260
Eligible validation rows, fwd_ret_5d: 41,180
Eligible validation rows, fwd_ret_21d: 40,860
Configured deep_learning models this notebook does not run, fwd_ret_1d: ['nlinear', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_5d: ['nlinear', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_21d: ['nlinear', 'tcn']

## Inspect identity-bearing settings

The model request records its architecture parameters, exact folds, expected prediction-key
digest, and every epoch that must remain reproducible from stored weights.

In [4]:
checkpoint_schedule = pl.DataFrame(computation["checkpoint_schedule"])
pl.DataFrame(
    {
        "label": list(computations),
        "architecture": [c["model"]["class"] for c in computations.values()],
        "gap_policy": [c["preprocessing"]["gap_policy"] for c in computations.values()],
        "validation_folds": [
            c["expected_prediction_keys"]["n_folds"] for c in computations.values()
        ],
        "key_digest": [c["expected_prediction_keys"]["digest"] for c in computations.values()],
    }
)
checkpoint_schedule

shape: (20, 2)
┌───────┬───────┐
│ kind  ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ epoch ┆ 5     │
│ epoch ┆ 10    │
│ epoch ┆ 15    │
│ epoch ┆ 20    │
│ epoch ┆ 25    │
│ …     ┆ …     │
│ epoch ┆ 80    │
│ epoch ┆ 85    │
│ epoch ┆ 90    │
│ epoch ┆ 95    │
│ epoch ┆ 100   │
└───────┴───────┘

## Record the official population, then fit or reload the LSTM

The runner validates every fold separately before any checkpoint becomes downstream-selectable.
Checkpoint rank correlation is retained as a diagnostic and does not remove other epochs.

`SUPERSEDES_POPULATION` names the population hash this run replaces. A population is the set of
prediction identities it publishes, so anything that moves a training identity produces a
different population under the same name, and the registry refuses to write it without being
told which snapshot it supersedes. That lineage is the only record of which generation is which,
and what moved the identities here was a change to the family's own source file rather than to
anything the notebook declares.

`population_supersedes` decides whether the declared hash may be offered. It is offered when the
name already carries the generation this declaration produced, so a re-run resolves to the
population it published, and when the declaration names the generation in force, so a refit
publishes the next one. It is withheld everywhere else - on a reader's clean clone, where
`run_log/` is gitignored and the registry has no generation at all; under a caller's own
`POPULATION_NAME`; and in a preview, whose isolated registry holds nothing under this name.

In [5]:
if len(plan.expected_prediction_hashes) != checkpoint_schedule.height * len(labels):
    raise RuntimeError("the plan does not cover every declared epoch checkpoint on every label")
population_name = POPULATION_NAME or f"{CASE_STUDY_ID}:{'+'.join(labels)}:lstm_h64"
population = (
    plan.create_population(
        name=population_name,
        supersedes=population_supersedes(
            study, name=population_name, declared=SUPERSEDES_POPULATION
        ),
    )
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
catalog = execution.catalog_rows.sort("label", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial LSTM checkpoints cannot pass to backtesting")
for label in labels:
    published = catalog.filter(pl.col("label") == label).get_column("checkpoint_value").to_list()
    if published != checkpoint_schedule["value"].to_list():
        raise RuntimeError(f"catalog checkpoints for {label} differ from the resolved request")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=17,060 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002026

      epoch   2/100: train_loss=0.000358

      epoch   3/100: train_loss=0.000156

      epoch   4/100: train_loss=0.000105

      epoch   5/100: train_loss=0.000080, val_loss=0.000092, IC=+0.0122

      epoch   6/100: train_loss=0.000070

      epoch   7/100: train_loss=0.000063

      epoch   8/100: train_loss=0.000058

      epoch   9/100: train_loss=0.000056

      epoch  10/100: train_loss=0.000055, val_loss=0.000072, IC=+0.0078

      epoch  11/100: train_loss=0.000053

      epoch  12/100: train_loss=0.000052

      epoch  13/100: train_loss=0.000051

      epoch  14/100: train_loss=0.000049

      epoch  15/100: train_loss=0.000049, val_loss=0.000068, IC=-0.0050

      epoch  16/100: train_loss=0.000048

      epoch  17/100: train_loss=0.000048

      epoch  18/100: train_loss=0.000047

      epoch  19/100: train_loss=0.000047

      epoch  20/100: train_loss=0.000046, val_loss=0.000066, IC=-0.0071

      epoch  21/100: train_loss=0.000046

      epoch  22/100: train_loss=0.000051

      epoch  23/100: train_loss=0.000045

      epoch  24/100: train_loss=0.000045

      epoch  25/100: train_loss=0.000045, val_loss=0.000064, IC=-0.0151

      epoch  26/100: train_loss=0.000045

      epoch  27/100: train_loss=0.000044

      epoch  28/100: train_loss=0.000044

      epoch  29/100: train_loss=0.000044

      epoch  30/100: train_loss=0.000049, val_loss=0.000063, IC=-0.0133

      epoch  31/100: train_loss=0.000044

      epoch  32/100: train_loss=0.000043

      epoch  33/100: train_loss=0.000043

      epoch  34/100: train_loss=0.000043

      epoch  35/100: train_loss=0.000044, val_loss=0.000063, IC=-0.0142

      epoch  36/100: train_loss=0.000043

      epoch  37/100: train_loss=0.000043

      epoch  38/100: train_loss=0.000043

      epoch  39/100: train_loss=0.000046

      epoch  40/100: train_loss=0.000043, val_loss=0.000062, IC=-0.0182

      epoch  41/100: train_loss=0.000042

      epoch  42/100: train_loss=0.000042

      epoch  43/100: train_loss=0.000042

      epoch  44/100: train_loss=0.000042

      epoch  45/100: train_loss=0.000042, val_loss=0.000063, IC=-0.0167

      epoch  46/100: train_loss=0.000042

      epoch  47/100: train_loss=0.000042

      epoch  48/100: train_loss=0.000045

      epoch  49/100: train_loss=0.000042

      epoch  50/100: train_loss=0.000042, val_loss=0.000063, IC=-0.0166

      epoch  51/100: train_loss=0.000042

      epoch  52/100: train_loss=0.000042

      epoch  53/100: train_loss=0.000043

      epoch  54/100: train_loss=0.000042

      epoch  55/100: train_loss=0.000045, val_loss=0.000062, IC=-0.0100

      epoch  56/100: train_loss=0.000041

      epoch  57/100: train_loss=0.000045

      epoch  58/100: train_loss=0.000045

      epoch  59/100: train_loss=0.000042

      epoch  60/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0101

      epoch  61/100: train_loss=0.000041

      epoch  62/100: train_loss=0.000042

      epoch  63/100: train_loss=0.000042

      epoch  64/100: train_loss=0.000041

      epoch  65/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0096

      epoch  66/100: train_loss=0.000041

      epoch  67/100: train_loss=0.000048

      epoch  68/100: train_loss=0.000042

      epoch  69/100: train_loss=0.000045

      epoch  70/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0118

      epoch  71/100: train_loss=0.000045

      epoch  72/100: train_loss=0.000041

      epoch  73/100: train_loss=0.000045

      epoch  74/100: train_loss=0.000041

      epoch  75/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0124

      epoch  76/100: train_loss=0.000041

      epoch  77/100: train_loss=0.000041

      epoch  78/100: train_loss=0.000041

      epoch  79/100: train_loss=0.000041

      epoch  80/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0121

      epoch  81/100: train_loss=0.000041

      epoch  82/100: train_loss=0.000041

      epoch  83/100: train_loss=0.000041

      epoch  84/100: train_loss=0.000041

      epoch  85/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0100

      epoch  86/100: train_loss=0.000041

      epoch  87/100: train_loss=0.000041

      epoch  88/100: train_loss=0.000041

      epoch  89/100: train_loss=0.000041

      epoch  90/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0113

      epoch  91/100: train_loss=0.000041

      epoch  92/100: train_loss=0.000041

      epoch  93/100: train_loss=0.000041

      epoch  94/100: train_loss=0.000041

      epoch  95/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0106

      epoch  96/100: train_loss=0.000041

      epoch  97/100: train_loss=0.000041

      epoch  98/100: train_loss=0.000041

      epoch  99/100: train_loss=0.000041

      epoch 100/100: train_loss=0.000041, val_loss=0.000062, IC=-0.0103

      best_ep=5, IC=+0.0122 (39.6s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,220 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002073

      epoch   2/100: train_loss=0.000283

      epoch   3/100: train_loss=0.000129

      epoch   4/100: train_loss=0.000084

      epoch   5/100: train_loss=0.000070, val_loss=0.000035, IC=-0.0085

      epoch   6/100: train_loss=0.000064

      epoch   7/100: train_loss=0.000061

      epoch   8/100: train_loss=0.000058

      epoch   9/100: train_loss=0.000056

      epoch  10/100: train_loss=0.000055, val_loss=0.000031, IC=-0.0021

      epoch  11/100: train_loss=0.000054

      epoch  12/100: train_loss=0.000053

      epoch  13/100: train_loss=0.000052

      epoch  14/100: train_loss=0.000051

      epoch  15/100: train_loss=0.000051, val_loss=0.000029, IC=-0.0095

      epoch  16/100: train_loss=0.000051

      epoch  17/100: train_loss=0.000050

      epoch  18/100: train_loss=0.000050

      epoch  19/100: train_loss=0.000050

      epoch  20/100: train_loss=0.000049, val_loss=0.000028, IC=-0.0063

      epoch  21/100: train_loss=0.000049

      epoch  22/100: train_loss=0.000048

      epoch  23/100: train_loss=0.000048

      epoch  24/100: train_loss=0.000048

      epoch  25/100: train_loss=0.000048, val_loss=0.000027, IC=-0.0095

      epoch  26/100: train_loss=0.000048

      epoch  27/100: train_loss=0.000048

      epoch  28/100: train_loss=0.000048

      epoch  29/100: train_loss=0.000047

      epoch  30/100: train_loss=0.000047, val_loss=0.000027, IC=+0.0040

      epoch  31/100: train_loss=0.000047

      epoch  32/100: train_loss=0.000047

      epoch  33/100: train_loss=0.000047

      epoch  34/100: train_loss=0.000047

      epoch  35/100: train_loss=0.000047, val_loss=0.000027, IC=-0.0036

      epoch  36/100: train_loss=0.000046

      epoch  37/100: train_loss=0.000047

      epoch  38/100: train_loss=0.000046

      epoch  39/100: train_loss=0.000046

      epoch  40/100: train_loss=0.000046, val_loss=0.000027, IC=-0.0110

      epoch  41/100: train_loss=0.000046

      epoch  42/100: train_loss=0.000046

      epoch  43/100: train_loss=0.000046

      epoch  44/100: train_loss=0.000046

      epoch  45/100: train_loss=0.000046, val_loss=0.000027, IC=-0.0179

      epoch  46/100: train_loss=0.000046

      epoch  47/100: train_loss=0.000046

      epoch  48/100: train_loss=0.000046

      epoch  49/100: train_loss=0.000046

      epoch  50/100: train_loss=0.000046, val_loss=0.000027, IC=-0.0089

      epoch  51/100: train_loss=0.000046

      epoch  52/100: train_loss=0.000046

      epoch  53/100: train_loss=0.000046

      epoch  54/100: train_loss=0.000045

      epoch  55/100: train_loss=0.000046, val_loss=0.000027, IC=-0.0099

      epoch  56/100: train_loss=0.000045

      epoch  57/100: train_loss=0.000046

      epoch  58/100: train_loss=0.000045

      epoch  59/100: train_loss=0.000045

      epoch  60/100: train_loss=0.000046, val_loss=0.000027, IC=-0.0081

      epoch  61/100: train_loss=0.000045

      epoch  62/100: train_loss=0.000045

      epoch  63/100: train_loss=0.000046

      epoch  64/100: train_loss=0.000045

      epoch  65/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0101

      epoch  66/100: train_loss=0.000045

      epoch  67/100: train_loss=0.000045

      epoch  68/100: train_loss=0.000045

      epoch  69/100: train_loss=0.000045

      epoch  70/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0080

      epoch  71/100: train_loss=0.000045

      epoch  72/100: train_loss=0.000045

      epoch  73/100: train_loss=0.000045

      epoch  74/100: train_loss=0.000045

      epoch  75/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0105

      epoch  76/100: train_loss=0.000045

      epoch  77/100: train_loss=0.000045

      epoch  78/100: train_loss=0.000045

      epoch  79/100: train_loss=0.000045

      epoch  80/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0141

      epoch  81/100: train_loss=0.000045

      epoch  82/100: train_loss=0.000045

      epoch  83/100: train_loss=0.000045

      epoch  84/100: train_loss=0.000045

      epoch  85/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0107

      epoch  86/100: train_loss=0.000045

      epoch  87/100: train_loss=0.000045

      epoch  88/100: train_loss=0.000045

      epoch  89/100: train_loss=0.000045

      epoch  90/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0100

      epoch  91/100: train_loss=0.000045

      epoch  92/100: train_loss=0.000045

      epoch  93/100: train_loss=0.000045

      epoch  94/100: train_loss=0.000045

      epoch  95/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0103

      epoch  96/100: train_loss=0.000046

      epoch  97/100: train_loss=0.000045

      epoch  98/100: train_loss=0.000045

      epoch  99/100: train_loss=0.000045

      epoch 100/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0108

      best_ep=30, IC=+0.0040 (55.3s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000484

      epoch   2/100: train_loss=0.000118

      epoch   3/100: train_loss=0.000080

      epoch   4/100: train_loss=0.000070

      epoch   5/100: train_loss=0.000057, val_loss=0.000029, IC=-0.0095

      epoch   6/100: train_loss=0.000053

      epoch   7/100: train_loss=0.000050

      epoch   8/100: train_loss=0.000048

      epoch   9/100: train_loss=0.000051

      epoch  10/100: train_loss=0.000052, val_loss=0.000028, IC=+0.0107

      epoch  11/100: train_loss=0.000048

      epoch  12/100: train_loss=0.000048

      epoch  13/100: train_loss=0.000046

      epoch  14/100: train_loss=0.000050

      epoch  15/100: train_loss=0.000055, val_loss=0.000027, IC=-0.0126

      epoch  16/100: train_loss=0.000048

      epoch  17/100: train_loss=0.000046

      epoch  18/100: train_loss=0.000045

      epoch  19/100: train_loss=0.000046

      epoch  20/100: train_loss=0.000044, val_loss=0.000025, IC=+0.0174

      epoch  21/100: train_loss=0.000044

      epoch  22/100: train_loss=0.000042

      epoch  23/100: train_loss=0.000043

      epoch  24/100: train_loss=0.000043

      epoch  25/100: train_loss=0.000045, val_loss=0.000025, IC=+0.0476

      epoch  26/100: train_loss=0.000044

      epoch  27/100: train_loss=0.000044

      epoch  28/100: train_loss=0.000043

      epoch  29/100: train_loss=0.000045

      epoch  30/100: train_loss=0.000046, val_loss=0.000028, IC=+0.0104

      epoch  31/100: train_loss=0.000044

      epoch  32/100: train_loss=0.000043

      epoch  33/100: train_loss=0.000067

      epoch  34/100: train_loss=0.000069

      epoch  35/100: train_loss=0.000050, val_loss=0.000027, IC=+0.0094

      epoch  36/100: train_loss=0.000049

      epoch  37/100: train_loss=0.000047

      epoch  38/100: train_loss=0.000043

      epoch  39/100: train_loss=0.000042

      epoch  40/100: train_loss=0.000044, val_loss=0.000025, IC=+0.0038

      epoch  41/100: train_loss=0.000047

      epoch  42/100: train_loss=0.000045

      epoch  43/100: train_loss=0.000043

      epoch  44/100: train_loss=0.000043

      epoch  45/100: train_loss=0.000042, val_loss=0.000024, IC=+0.0267

      epoch  46/100: train_loss=0.000044

      epoch  47/100: train_loss=0.000045

      epoch  48/100: train_loss=0.000045

      epoch  49/100: train_loss=0.000052

      epoch  50/100: train_loss=0.000051, val_loss=0.000030, IC=+0.0374

      epoch  51/100: train_loss=0.000051

      epoch  52/100: train_loss=0.000046

      epoch  53/100: train_loss=0.000047

      epoch  54/100: train_loss=0.000047

      epoch  55/100: train_loss=0.000048, val_loss=0.000026, IC=+0.0140

      epoch  56/100: train_loss=0.000042

      epoch  57/100: train_loss=0.000042

      epoch  58/100: train_loss=0.000044

      epoch  59/100: train_loss=0.000043

      epoch  60/100: train_loss=0.000041, val_loss=0.000024, IC=-0.0085

      epoch  61/100: train_loss=0.000053

      epoch  62/100: train_loss=0.000048

      epoch  63/100: train_loss=0.000044

      epoch  64/100: train_loss=0.000045

      epoch  65/100: train_loss=0.000043, val_loss=0.000024, IC=+0.0115

      epoch  66/100: train_loss=0.000046

      epoch  67/100: train_loss=0.000044

      epoch  68/100: train_loss=0.000045

      epoch  69/100: train_loss=0.000045

      epoch  70/100: train_loss=0.000044, val_loss=0.000027, IC=+0.0145

      epoch  71/100: train_loss=0.000041

      epoch  72/100: train_loss=0.000043

      epoch  73/100: train_loss=0.000043

      epoch  74/100: train_loss=0.000042

      epoch  75/100: train_loss=0.000045, val_loss=0.000025, IC=+0.0195

      epoch  76/100: train_loss=0.000041

      epoch  77/100: train_loss=0.000047

      epoch  78/100: train_loss=0.000041

      epoch  79/100: train_loss=0.000043

      epoch  80/100: train_loss=0.000042, val_loss=0.000024, IC=+0.0166

      epoch  81/100: train_loss=0.000042

      epoch  82/100: train_loss=0.000040

      epoch  83/100: train_loss=0.000046

      epoch  84/100: train_loss=0.000044

      epoch  85/100: train_loss=0.000042, val_loss=0.000024, IC=+0.0213

      epoch  86/100: train_loss=0.000041

      epoch  87/100: train_loss=0.000044

      epoch  88/100: train_loss=0.000044

      epoch  89/100: train_loss=0.000041

      epoch  90/100: train_loss=0.000047, val_loss=0.000024, IC=+0.0179

      epoch  91/100: train_loss=0.000045

      epoch  92/100: train_loss=0.000045

      epoch  93/100: train_loss=0.000043

      epoch  94/100: train_loss=0.000042

      epoch  95/100: train_loss=0.000041, val_loss=0.000024, IC=+0.0173

      epoch  96/100: train_loss=0.000041

      epoch  97/100: train_loss=0.000041

      epoch  98/100: train_loss=0.000041

      epoch  99/100: train_loss=0.000043

      epoch 100/100: train_loss=0.000043, val_loss=0.000024, IC=+0.0199

      best_ep=25, IC=+0.0476 (60.6s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000708

      epoch   2/100: train_loss=0.000169

      epoch   3/100: train_loss=0.000116

      epoch   4/100: train_loss=0.000072

      epoch   5/100: train_loss=0.000058, val_loss=0.000024, IC=-0.0077

      epoch   6/100: train_loss=0.000049

      epoch   7/100: train_loss=0.000053

      epoch   8/100: train_loss=0.000052

      epoch   9/100: train_loss=0.000049

      epoch  10/100: train_loss=0.000049, val_loss=0.000022, IC=-0.0254

      epoch  11/100: train_loss=0.000050

      epoch  12/100: train_loss=0.000045

      epoch  13/100: train_loss=0.000043

      epoch  14/100: train_loss=0.000041

      epoch  15/100: train_loss=0.000043, val_loss=0.000019, IC=-0.0122

      epoch  16/100: train_loss=0.000044

      epoch  17/100: train_loss=0.000046

      epoch  18/100: train_loss=0.000043

      epoch  19/100: train_loss=0.000045

      epoch  20/100: train_loss=0.000045, val_loss=0.000021, IC=-0.0376

      epoch  21/100: train_loss=0.000043

      epoch  22/100: train_loss=0.000043

      epoch  23/100: train_loss=0.000043

      epoch  24/100: train_loss=0.000043

      epoch  25/100: train_loss=0.000043, val_loss=0.000022, IC=-0.0228

      epoch  26/100: train_loss=0.000043

      epoch  27/100: train_loss=0.000042

      epoch  28/100: train_loss=0.000041

      epoch  29/100: train_loss=0.000040

      epoch  30/100: train_loss=0.000041, val_loss=0.000018, IC=-0.0146

      epoch  31/100: train_loss=0.000041

      epoch  32/100: train_loss=0.000051

      epoch  33/100: train_loss=0.000056

      epoch  34/100: train_loss=0.000051

      epoch  35/100: train_loss=0.000048, val_loss=0.000020, IC=-0.0294

      epoch  36/100: train_loss=0.000047

      epoch  37/100: train_loss=0.000044

      epoch  38/100: train_loss=0.000046

      epoch  39/100: train_loss=0.000048

      epoch  40/100: train_loss=0.000050, val_loss=0.000026, IC=+0.0001

      epoch  41/100: train_loss=0.000049

      epoch  42/100: train_loss=0.000041

      epoch  43/100: train_loss=0.000040

      epoch  44/100: train_loss=0.000042

      epoch  45/100: train_loss=0.000047, val_loss=0.000020, IC=-0.0117

      epoch  46/100: train_loss=0.000044

      epoch  47/100: train_loss=0.000043

      epoch  48/100: train_loss=0.000042

      epoch  49/100: train_loss=0.000040

      epoch  50/100: train_loss=0.000041, val_loss=0.000019, IC=-0.0201

      epoch  51/100: train_loss=0.000045

      epoch  52/100: train_loss=0.000055

      epoch  53/100: train_loss=0.000045

      epoch  54/100: train_loss=0.000041

      epoch  55/100: train_loss=0.000049, val_loss=0.000019, IC=-0.0362

      epoch  56/100: train_loss=0.000043

      epoch  57/100: train_loss=0.000040

      epoch  58/100: train_loss=0.000040

      epoch  59/100: train_loss=0.000039

      epoch  60/100: train_loss=0.000043, val_loss=0.000018, IC=+0.0013

      epoch  61/100: train_loss=0.000044

      epoch  62/100: train_loss=0.000041

      epoch  63/100: train_loss=0.000045

      epoch  64/100: train_loss=0.000044

      epoch  65/100: train_loss=0.000040, val_loss=0.000020, IC=-0.0041

      epoch  66/100: train_loss=0.000043

      epoch  67/100: train_loss=0.000040

      epoch  68/100: train_loss=0.000040

      epoch  69/100: train_loss=0.000040

      epoch  70/100: train_loss=0.000042, val_loss=0.000018, IC=-0.0221

      epoch  71/100: train_loss=0.000044

      epoch  72/100: train_loss=0.000041

      epoch  73/100: train_loss=0.000043

      epoch  74/100: train_loss=0.000041

      epoch  75/100: train_loss=0.000050, val_loss=0.000018, IC=-0.0327

      epoch  76/100: train_loss=0.000042

      epoch  77/100: train_loss=0.000045

      epoch  78/100: train_loss=0.000039

      epoch  79/100: train_loss=0.000039

      epoch  80/100: train_loss=0.000042, val_loss=0.000017, IC=-0.0091

      epoch  81/100: train_loss=0.000042

      epoch  82/100: train_loss=0.000039

      epoch  83/100: train_loss=0.000041

      epoch  84/100: train_loss=0.000040

      epoch  85/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0243

      epoch  86/100: train_loss=0.000039

      epoch  87/100: train_loss=0.000042

      epoch  88/100: train_loss=0.000038

      epoch  89/100: train_loss=0.000040

      epoch  90/100: train_loss=0.000040, val_loss=0.000018, IC=-0.0244

      epoch  91/100: train_loss=0.000041

      epoch  92/100: train_loss=0.000039

      epoch  93/100: train_loss=0.000038

      epoch  94/100: train_loss=0.000040

      epoch  95/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0182

      epoch  96/100: train_loss=0.000040

      epoch  97/100: train_loss=0.000039

      epoch  98/100: train_loss=0.000039

      epoch  99/100: train_loss=0.000039

      epoch 100/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0176

      best_ep=60, IC=+0.0013 (60.3s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000467

      epoch   2/100: train_loss=0.000134

      epoch   3/100: train_loss=0.000071

      epoch   4/100: train_loss=0.000054

      epoch   5/100: train_loss=0.000048, val_loss=0.000047, IC=-0.0203

      epoch   6/100: train_loss=0.000044

      epoch   7/100: train_loss=0.000040

      epoch   8/100: train_loss=0.000040

      epoch   9/100: train_loss=0.000040

      epoch  10/100: train_loss=0.000040, val_loss=0.000043, IC=-0.0223

      epoch  11/100: train_loss=0.000045

      epoch  12/100: train_loss=0.000039

      epoch  13/100: train_loss=0.000036

      epoch  14/100: train_loss=0.000038

      epoch  15/100: train_loss=0.000037, val_loss=0.000046, IC=-0.0138

      epoch  16/100: train_loss=0.000037

      epoch  17/100: train_loss=0.000035

      epoch  18/100: train_loss=0.000038

      epoch  19/100: train_loss=0.000037

      epoch  20/100: train_loss=0.000034, val_loss=0.000042, IC=-0.0104

      epoch  21/100: train_loss=0.000037

      epoch  22/100: train_loss=0.000035

      epoch  23/100: train_loss=0.000034

      epoch  24/100: train_loss=0.000037

      epoch  25/100: train_loss=0.000040, val_loss=0.000042, IC=-0.0058

      epoch  26/100: train_loss=0.000034

      epoch  27/100: train_loss=0.000035

      epoch  28/100: train_loss=0.000034

      epoch  29/100: train_loss=0.000036

      epoch  30/100: train_loss=0.000037, val_loss=0.000042, IC=-0.0192

      epoch  31/100: train_loss=0.000040

      epoch  32/100: train_loss=0.000047

      epoch  33/100: train_loss=0.000044

      epoch  34/100: train_loss=0.000040

      epoch  35/100: train_loss=0.000041, val_loss=0.000042, IC=-0.0126

      epoch  36/100: train_loss=0.000035

      epoch  37/100: train_loss=0.000041

      epoch  38/100: train_loss=0.000041

      epoch  39/100: train_loss=0.000038

      epoch  40/100: train_loss=0.000040, val_loss=0.000043, IC=-0.0224

      epoch  41/100: train_loss=0.000044

      epoch  42/100: train_loss=0.000040

      epoch  43/100: train_loss=0.000036

      epoch  44/100: train_loss=0.000034

      epoch  45/100: train_loss=0.000035, val_loss=0.000041, IC=-0.0144

      epoch  46/100: train_loss=0.000033

      epoch  47/100: train_loss=0.000038

      epoch  48/100: train_loss=0.000033

      epoch  49/100: train_loss=0.000034

      epoch  50/100: train_loss=0.000038, val_loss=0.000039, IC=-0.0070

      epoch  51/100: train_loss=0.000034

      epoch  52/100: train_loss=0.000033

      epoch  53/100: train_loss=0.000032

      epoch  54/100: train_loss=0.000032

      epoch  55/100: train_loss=0.000032, val_loss=0.000039, IC=-0.0336

      epoch  56/100: train_loss=0.000034

      epoch  57/100: train_loss=0.000041

      epoch  58/100: train_loss=0.000035

      epoch  59/100: train_loss=0.000039

      epoch  60/100: train_loss=0.000036, val_loss=0.000041, IC=-0.0325

      epoch  61/100: train_loss=0.000033

      epoch  62/100: train_loss=0.000034

      epoch  63/100: train_loss=0.000033

      epoch  64/100: train_loss=0.000033

      epoch  65/100: train_loss=0.000033, val_loss=0.000039, IC=-0.0245

      epoch  66/100: train_loss=0.000037

      epoch  67/100: train_loss=0.000037

      epoch  68/100: train_loss=0.000034

      epoch  69/100: train_loss=0.000036

      epoch  70/100: train_loss=0.000032, val_loss=0.000040, IC=-0.0247

      epoch  71/100: train_loss=0.000034

      epoch  72/100: train_loss=0.000038

      epoch  73/100: train_loss=0.000036

      epoch  74/100: train_loss=0.000038

      epoch  75/100: train_loss=0.000037, val_loss=0.000040, IC=-0.0288

      epoch  76/100: train_loss=0.000033

      epoch  77/100: train_loss=0.000034

      epoch  78/100: train_loss=0.000031

      epoch  79/100: train_loss=0.000033

      epoch  80/100: train_loss=0.000033, val_loss=0.000038, IC=-0.0250

      epoch  81/100: train_loss=0.000032

      epoch  82/100: train_loss=0.000031

      epoch  83/100: train_loss=0.000032

      epoch  84/100: train_loss=0.000033

      epoch  85/100: train_loss=0.000030, val_loss=0.000039, IC=-0.0331

      epoch  86/100: train_loss=0.000038

      epoch  87/100: train_loss=0.000033

      epoch  88/100: train_loss=0.000032

      epoch  89/100: train_loss=0.000081

      epoch  90/100: train_loss=0.000035, val_loss=0.000040, IC=-0.0387

      epoch  91/100: train_loss=0.000032

      epoch  92/100: train_loss=0.000031

      epoch  93/100: train_loss=0.000032

      epoch  94/100: train_loss=0.000031

      epoch  95/100: train_loss=0.000033, val_loss=0.000038, IC=-0.0342

      epoch  96/100: train_loss=0.000031

      epoch  97/100: train_loss=0.000031

      epoch  98/100: train_loss=0.000033

      epoch  99/100: train_loss=0.000031

      epoch 100/100: train_loss=0.000031, val_loss=0.000039, IC=-0.0320

      best_ep=25, IC=-0.0058 (62.7s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002443

      epoch   2/100: train_loss=0.000340

      epoch   3/100: train_loss=0.000139

      epoch   4/100: train_loss=0.000083

      epoch   5/100: train_loss=0.000066, val_loss=0.000035, IC=+0.0088

      epoch   6/100: train_loss=0.000050

      epoch   7/100: train_loss=0.000046

      epoch   8/100: train_loss=0.000045

      epoch   9/100: train_loss=0.000043

      epoch  10/100: train_loss=0.000043, val_loss=0.000025, IC=+0.0155

      epoch  11/100: train_loss=0.000046

      epoch  12/100: train_loss=0.000043

      epoch  13/100: train_loss=0.000048

      epoch  14/100: train_loss=0.000041

      epoch  15/100: train_loss=0.000039, val_loss=0.000024, IC=+0.0291

      epoch  16/100: train_loss=0.000037

      epoch  17/100: train_loss=0.000035

      epoch  18/100: train_loss=0.000036

      epoch  19/100: train_loss=0.000035

      epoch  20/100: train_loss=0.000037, val_loss=0.000024, IC=+0.0265

      epoch  21/100: train_loss=0.000037

      epoch  22/100: train_loss=0.000034

      epoch  23/100: train_loss=0.000038

      epoch  24/100: train_loss=0.000039

      epoch  25/100: train_loss=0.000037, val_loss=0.000025, IC=+0.0184

      epoch  26/100: train_loss=0.000037

      epoch  27/100: train_loss=0.000037

      epoch  28/100: train_loss=0.000035

      epoch  29/100: train_loss=0.000035

      epoch  30/100: train_loss=0.000038, val_loss=0.000022, IC=+0.0130

      epoch  31/100: train_loss=0.000039

      epoch  32/100: train_loss=0.000036

      epoch  33/100: train_loss=0.000034

      epoch  34/100: train_loss=0.000032

      epoch  35/100: train_loss=0.000031, val_loss=0.000021, IC=+0.0210

      epoch  36/100: train_loss=0.000036

      epoch  37/100: train_loss=0.000037

      epoch  38/100: train_loss=0.000034

      epoch  39/100: train_loss=0.000036

      epoch  40/100: train_loss=0.000032, val_loss=0.000021, IC=+0.0220

      epoch  41/100: train_loss=0.000032

      epoch  42/100: train_loss=0.000031

      epoch  43/100: train_loss=0.000031

      epoch  44/100: train_loss=0.000031

      epoch  45/100: train_loss=0.000032, val_loss=0.000021, IC=+0.0073

      epoch  46/100: train_loss=0.000031

      epoch  47/100: train_loss=0.000032

      epoch  48/100: train_loss=0.000030

      epoch  49/100: train_loss=0.000029

      epoch  50/100: train_loss=0.000030, val_loss=0.000020, IC=+0.0221

      epoch  51/100: train_loss=0.000030

      epoch  52/100: train_loss=0.000030

      epoch  53/100: train_loss=0.000031

      epoch  54/100: train_loss=0.000031

      epoch  55/100: train_loss=0.000033, val_loss=0.000021, IC=+0.0167

      epoch  56/100: train_loss=0.000031

      epoch  57/100: train_loss=0.000030

      epoch  58/100: train_loss=0.000030

      epoch  59/100: train_loss=0.000029

      epoch  60/100: train_loss=0.000031, val_loss=0.000020, IC=+0.0120

      epoch  61/100: train_loss=0.000030

      epoch  62/100: train_loss=0.000031

      epoch  63/100: train_loss=0.000036

      epoch  64/100: train_loss=0.000032

      epoch  65/100: train_loss=0.000031, val_loss=0.000021, IC=+0.0047

      epoch  66/100: train_loss=0.000031

      epoch  67/100: train_loss=0.000034

      epoch  68/100: train_loss=0.000030

      epoch  69/100: train_loss=0.000030

      epoch  70/100: train_loss=0.000029, val_loss=0.000020, IC=+0.0202

      epoch  71/100: train_loss=0.000031

      epoch  72/100: train_loss=0.000033

      epoch  73/100: train_loss=0.000034

      epoch  74/100: train_loss=0.000035

      epoch  75/100: train_loss=0.000031, val_loss=0.000021, IC=+0.0141

      epoch  76/100: train_loss=0.000031

      epoch  77/100: train_loss=0.000030

      epoch  78/100: train_loss=0.000031

      epoch  79/100: train_loss=0.000032

      epoch  80/100: train_loss=0.000030, val_loss=0.000020, IC=+0.0268

      epoch  81/100: train_loss=0.000029

      epoch  82/100: train_loss=0.000031

      epoch  83/100: train_loss=0.000040

      epoch  84/100: train_loss=0.000029

      epoch  85/100: train_loss=0.000029, val_loss=0.000020, IC=+0.0225

      epoch  86/100: train_loss=0.000028

      epoch  87/100: train_loss=0.000029

      epoch  88/100: train_loss=0.000034

      epoch  89/100: train_loss=0.000031

      epoch  90/100: train_loss=0.000031, val_loss=0.000020, IC=+0.0291

      epoch  91/100: train_loss=0.000029

      epoch  92/100: train_loss=0.000031

      epoch  93/100: train_loss=0.000030

      epoch  94/100: train_loss=0.000030

      epoch  95/100: train_loss=0.000029, val_loss=0.000020, IC=+0.0279

      epoch  96/100: train_loss=0.000029

      epoch  97/100: train_loss=0.000029

      epoch  98/100: train_loss=0.000029

      epoch  99/100: train_loss=0.000029

      epoch 100/100: train_loss=0.000029, val_loss=0.000020, IC=+0.0287

      best_ep=90, IC=+0.0291 (64.7s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000534

      epoch   2/100: train_loss=0.000109

      epoch   3/100: train_loss=0.000062

      epoch   4/100: train_loss=0.000048

      epoch   5/100: train_loss=0.000046, val_loss=0.000058, IC=-0.0033

      epoch   6/100: train_loss=0.000037

      epoch   7/100: train_loss=0.000033

      epoch   8/100: train_loss=0.000030

      epoch   9/100: train_loss=0.000032

      epoch  10/100: train_loss=0.000031, val_loss=0.000053, IC=-0.0077

      epoch  11/100: train_loss=0.000028

      epoch  12/100: train_loss=0.000026

      epoch  13/100: train_loss=0.000026

      epoch  14/100: train_loss=0.000026

      epoch  15/100: train_loss=0.000031, val_loss=0.000050, IC=-0.0121

      epoch  16/100: train_loss=0.000033

      epoch  17/100: train_loss=0.000030

      epoch  18/100: train_loss=0.000033

      epoch  19/100: train_loss=0.000027

      epoch  20/100: train_loss=0.000026, val_loss=0.000051, IC=-0.0299

      epoch  21/100: train_loss=0.000025

      epoch  22/100: train_loss=0.000024

      epoch  23/100: train_loss=0.000025

      epoch  24/100: train_loss=0.000027

      epoch  25/100: train_loss=0.000025, val_loss=0.000049, IC=+0.0067

      epoch  26/100: train_loss=0.000026

      epoch  27/100: train_loss=0.000029

      epoch  28/100: train_loss=0.000029

      epoch  29/100: train_loss=0.000026

      epoch  30/100: train_loss=0.000026, val_loss=0.000051, IC=-0.0304

      epoch  31/100: train_loss=0.000029

      epoch  32/100: train_loss=0.000029

      epoch  33/100: train_loss=0.000030

      epoch  34/100: train_loss=0.000039

      epoch  35/100: train_loss=0.000029, val_loss=0.000054, IC=-0.0365

      epoch  36/100: train_loss=0.000027

      epoch  37/100: train_loss=0.000025

      epoch  38/100: train_loss=0.000029

      epoch  39/100: train_loss=0.000031

      epoch  40/100: train_loss=0.000028, val_loss=0.000054, IC=-0.0292

      epoch  41/100: train_loss=0.000027

      epoch  42/100: train_loss=0.000025

      epoch  43/100: train_loss=0.000024

      epoch  44/100: train_loss=0.000026

      epoch  45/100: train_loss=0.000031, val_loss=0.000054, IC=-0.0079

      epoch  46/100: train_loss=0.000031

      epoch  47/100: train_loss=0.000028

      epoch  48/100: train_loss=0.000025

      epoch  49/100: train_loss=0.000023

      epoch  50/100: train_loss=0.000023, val_loss=0.000048, IC=-0.0229

      epoch  51/100: train_loss=0.000023

      epoch  52/100: train_loss=0.000024

      epoch  53/100: train_loss=0.000023

      epoch  54/100: train_loss=0.000024

      epoch  55/100: train_loss=0.000024, val_loss=0.000047, IC=-0.0243

      epoch  56/100: train_loss=0.000026

      epoch  57/100: train_loss=0.000025

      epoch  58/100: train_loss=0.000024

      epoch  59/100: train_loss=0.000029

      epoch  60/100: train_loss=0.000027, val_loss=0.000048, IC=-0.0120

      epoch  61/100: train_loss=0.000025

      epoch  62/100: train_loss=0.000024

      epoch  63/100: train_loss=0.000023

      epoch  64/100: train_loss=0.000023

      epoch  65/100: train_loss=0.000023, val_loss=0.000047, IC=-0.0132

      epoch  66/100: train_loss=0.000022

      epoch  67/100: train_loss=0.000031

      epoch  68/100: train_loss=0.000027

      epoch  69/100: train_loss=0.000026

      epoch  70/100: train_loss=0.000023, val_loss=0.000049, IC=-0.0139

      epoch  71/100: train_loss=0.000023

      epoch  72/100: train_loss=0.000024

      epoch  73/100: train_loss=0.000023

      epoch  74/100: train_loss=0.000023

      epoch  75/100: train_loss=0.000025, val_loss=0.000048, IC=-0.0209

      epoch  76/100: train_loss=0.000025

      epoch  77/100: train_loss=0.000024

      epoch  78/100: train_loss=0.000023

      epoch  79/100: train_loss=0.000023

      epoch  80/100: train_loss=0.000024, val_loss=0.000047, IC=-0.0113

      epoch  81/100: train_loss=0.000023

      epoch  82/100: train_loss=0.000024

      epoch  83/100: train_loss=0.000023

      epoch  84/100: train_loss=0.000025

      epoch  85/100: train_loss=0.000025, val_loss=0.000048, IC=-0.0164

      epoch  86/100: train_loss=0.000022

      epoch  87/100: train_loss=0.000023

      epoch  88/100: train_loss=0.000022

      epoch  89/100: train_loss=0.000022

      epoch  90/100: train_loss=0.000022, val_loss=0.000048, IC=-0.0274

      epoch  91/100: train_loss=0.000023

      epoch  92/100: train_loss=0.000022

      epoch  93/100: train_loss=0.000022

      epoch  94/100: train_loss=0.000026

      epoch  95/100: train_loss=0.000027, val_loss=0.000047, IC=-0.0201

      epoch  96/100: train_loss=0.000022

      epoch  97/100: train_loss=0.000023

      epoch  98/100: train_loss=0.000022

      epoch  99/100: train_loss=0.000022

      epoch 100/100: train_loss=0.000022, val_loss=0.000047, IC=-0.0174

      best_ep=25, IC=+0.0067 (63.4s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,140 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002783

      epoch   2/100: train_loss=0.000363

      epoch   3/100: train_loss=0.000142

      epoch   4/100: train_loss=0.000084

      epoch   5/100: train_loss=0.000059, val_loss=0.000055, IC=-0.0029

      epoch   6/100: train_loss=0.000052

      epoch   7/100: train_loss=0.000049

      epoch   8/100: train_loss=0.000049

      epoch   9/100: train_loss=0.000043

      epoch  10/100: train_loss=0.000041, val_loss=0.000042, IC=+0.0019

      epoch  11/100: train_loss=0.000038

      epoch  12/100: train_loss=0.000037

      epoch  13/100: train_loss=0.000038

      epoch  14/100: train_loss=0.000038

      epoch  15/100: train_loss=0.000038, val_loss=0.000036, IC=+0.0141

      epoch  16/100: train_loss=0.000037

      epoch  17/100: train_loss=0.000039

      epoch  18/100: train_loss=0.000041

      epoch  19/100: train_loss=0.000036

      epoch  20/100: train_loss=0.000035, val_loss=0.000034, IC=+0.0118

      epoch  21/100: train_loss=0.000034

      epoch  22/100: train_loss=0.000034

      epoch  23/100: train_loss=0.000034

      epoch  24/100: train_loss=0.000032

      epoch  25/100: train_loss=0.000031, val_loss=0.000033, IC=+0.0275

      epoch  26/100: train_loss=0.000034

      epoch  27/100: train_loss=0.000034

      epoch  28/100: train_loss=0.000032

      epoch  29/100: train_loss=0.000031

      epoch  30/100: train_loss=0.000034, val_loss=0.000034, IC=-0.0177

      epoch  31/100: train_loss=0.000036

      epoch  32/100: train_loss=0.000033

      epoch  33/100: train_loss=0.000030

      epoch  34/100: train_loss=0.000029

      epoch  35/100: train_loss=0.000031, val_loss=0.000032, IC=+0.0137

      epoch  36/100: train_loss=0.000029

      epoch  37/100: train_loss=0.000028

      epoch  38/100: train_loss=0.000031

      epoch  39/100: train_loss=0.000031

      epoch  40/100: train_loss=0.000035, val_loss=0.000032, IC=+0.0265

      epoch  41/100: train_loss=0.000034

      epoch  42/100: train_loss=0.000031

      epoch  43/100: train_loss=0.000034

      epoch  44/100: train_loss=0.000032

      epoch  45/100: train_loss=0.000031, val_loss=0.000033, IC=+0.0180

      epoch  46/100: train_loss=0.000031

      epoch  47/100: train_loss=0.000029

      epoch  48/100: train_loss=0.000030

      epoch  49/100: train_loss=0.000032

      epoch  50/100: train_loss=0.000030, val_loss=0.000034, IC=-0.0095

      epoch  51/100: train_loss=0.000029

      epoch  52/100: train_loss=0.000030

      epoch  53/100: train_loss=0.000029

      epoch  54/100: train_loss=0.000029

      epoch  55/100: train_loss=0.000028, val_loss=0.000033, IC=-0.0173

      epoch  56/100: train_loss=0.000030

      epoch  57/100: train_loss=0.000028

      epoch  58/100: train_loss=0.000028

      epoch  59/100: train_loss=0.000028

      epoch  60/100: train_loss=0.000027, val_loss=0.000031, IC=+0.0084

      epoch  61/100: train_loss=0.000027

      epoch  62/100: train_loss=0.000027

      epoch  63/100: train_loss=0.000027

      epoch  64/100: train_loss=0.000029

      epoch  65/100: train_loss=0.000029, val_loss=0.000031, IC=+0.0030

      epoch  66/100: train_loss=0.000028

      epoch  67/100: train_loss=0.000028

      epoch  68/100: train_loss=0.000036

      epoch  69/100: train_loss=0.000032

      epoch  70/100: train_loss=0.000028, val_loss=0.000032, IC=+0.0090

      epoch  71/100: train_loss=0.000028

      epoch  72/100: train_loss=0.000031

      epoch  73/100: train_loss=0.000034

      epoch  74/100: train_loss=0.000028

      epoch  75/100: train_loss=0.000028, val_loss=0.000031, IC=+0.0166

      epoch  76/100: train_loss=0.000028

      epoch  77/100: train_loss=0.000028

      epoch  78/100: train_loss=0.000027

      epoch  79/100: train_loss=0.000027

      epoch  80/100: train_loss=0.000027, val_loss=0.000031, IC=+0.0047

      epoch  81/100: train_loss=0.000027

      epoch  82/100: train_loss=0.000027

      epoch  83/100: train_loss=0.000026

      epoch  84/100: train_loss=0.000029

      epoch  85/100: train_loss=0.000026, val_loss=0.000031, IC=-0.0022

      epoch  86/100: train_loss=0.000028

      epoch  87/100: train_loss=0.000028

      epoch  88/100: train_loss=0.000029

      epoch  89/100: train_loss=0.000027

      epoch  90/100: train_loss=0.000026, val_loss=0.000031, IC=+0.0085

      epoch  91/100: train_loss=0.000027

      epoch  92/100: train_loss=0.000026

      epoch  93/100: train_loss=0.000034

      epoch  94/100: train_loss=0.000029

      epoch  95/100: train_loss=0.000028, val_loss=0.000030, IC=+0.0122

      epoch  96/100: train_loss=0.000027

      epoch  97/100: train_loss=0.000027

      epoch  98/100: train_loss=0.000028

      epoch  99/100: train_loss=0.000026

      epoch 100/100: train_loss=0.000029, val_loss=0.000031, IC=+0.0082

      best_ep=25, IC=+0.0275 (60.4s, 20 checkpoints)

  lstm_h64: best_epoch=25, IC=+0.0059 (467.0s)

  Best: lstm_h64 @ epoch 25 (IC=+0.0059)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/225e9d237512/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=16,980 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002202

      epoch   2/100: train_loss=0.000508

      epoch   3/100: train_loss=0.000303

      epoch   4/100: train_loss=0.000246

      epoch   5/100: train_loss=0.000230, val_loss=0.000318, IC=+0.0481

      epoch   6/100: train_loss=0.000212

      epoch   7/100: train_loss=0.000208

      epoch   8/100: train_loss=0.000204

      epoch   9/100: train_loss=0.000201

      epoch  10/100: train_loss=0.000193, val_loss=0.000296, IC=+0.0521

      epoch  11/100: train_loss=0.000198

      epoch  12/100: train_loss=0.000191

      epoch  13/100: train_loss=0.000188

      epoch  14/100: train_loss=0.000192

      epoch  15/100: train_loss=0.000184, val_loss=0.000296, IC=+0.0446

      epoch  16/100: train_loss=0.000185

      epoch  17/100: train_loss=0.000183

      epoch  18/100: train_loss=0.000178

      epoch  19/100: train_loss=0.000178

      epoch  20/100: train_loss=0.000182, val_loss=0.000319, IC=+0.0423

      epoch  21/100: train_loss=0.000179

      epoch  22/100: train_loss=0.000174

      epoch  23/100: train_loss=0.000174

      epoch  24/100: train_loss=0.000170

      epoch  25/100: train_loss=0.000168, val_loss=0.000333, IC=+0.0332

      epoch  26/100: train_loss=0.000167

      epoch  27/100: train_loss=0.000166

      epoch  28/100: train_loss=0.000165

      epoch  29/100: train_loss=0.000160

      epoch  30/100: train_loss=0.000159, val_loss=0.000339, IC=+0.0312

      epoch  31/100: train_loss=0.000158

      epoch  32/100: train_loss=0.000157

      epoch  33/100: train_loss=0.000157

      epoch  34/100: train_loss=0.000152

      epoch  35/100: train_loss=0.000160, val_loss=0.000353, IC=+0.0325

      epoch  36/100: train_loss=0.000152

      epoch  37/100: train_loss=0.000148

      epoch  38/100: train_loss=0.000151

      epoch  39/100: train_loss=0.000154

      epoch  40/100: train_loss=0.000144, val_loss=0.000367, IC=+0.0355

      epoch  41/100: train_loss=0.000146

      epoch  42/100: train_loss=0.000141

      epoch  43/100: train_loss=0.000152

      epoch  44/100: train_loss=0.000145

      epoch  45/100: train_loss=0.000138, val_loss=0.000371, IC=+0.0378

      epoch  46/100: train_loss=0.000146

      epoch  47/100: train_loss=0.000136

      epoch  48/100: train_loss=0.000137

      epoch  49/100: train_loss=0.000135

      epoch  50/100: train_loss=0.000136, val_loss=0.000375, IC=+0.0521

      epoch  51/100: train_loss=0.000136

      epoch  52/100: train_loss=0.000134

      epoch  53/100: train_loss=0.000131

      epoch  54/100: train_loss=0.000132

      epoch  55/100: train_loss=0.000135, val_loss=0.000380, IC=+0.0484

      epoch  56/100: train_loss=0.000133

      epoch  57/100: train_loss=0.000127

      epoch  58/100: train_loss=0.000130

      epoch  59/100: train_loss=0.000129

      epoch  60/100: train_loss=0.000130, val_loss=0.000389, IC=+0.0504

      epoch  61/100: train_loss=0.000125

      epoch  62/100: train_loss=0.000126

      epoch  63/100: train_loss=0.000126

      epoch  64/100: train_loss=0.000124

      epoch  65/100: train_loss=0.000124, val_loss=0.000390, IC=+0.0543

      epoch  66/100: train_loss=0.000122

      epoch  67/100: train_loss=0.000123

      epoch  68/100: train_loss=0.000121

      epoch  69/100: train_loss=0.000124

      epoch  70/100: train_loss=0.000122, val_loss=0.000396, IC=+0.0511

      epoch  71/100: train_loss=0.000123

      epoch  72/100: train_loss=0.000125

      epoch  73/100: train_loss=0.000122

      epoch  74/100: train_loss=0.000124

      epoch  75/100: train_loss=0.000121, val_loss=0.000390, IC=+0.0494

      epoch  76/100: train_loss=0.000119

      epoch  77/100: train_loss=0.000121

      epoch  78/100: train_loss=0.000118

      epoch  79/100: train_loss=0.000123

      epoch  80/100: train_loss=0.000116, val_loss=0.000392, IC=+0.0544

      epoch  81/100: train_loss=0.000118

      epoch  82/100: train_loss=0.000118

      epoch  83/100: train_loss=0.000118

      epoch  84/100: train_loss=0.000120

      epoch  85/100: train_loss=0.000118, val_loss=0.000391, IC=+0.0533

      epoch  86/100: train_loss=0.000121

      epoch  87/100: train_loss=0.000123

      epoch  88/100: train_loss=0.000116

      epoch  89/100: train_loss=0.000116

      epoch  90/100: train_loss=0.000116, val_loss=0.000393, IC=+0.0554

      epoch  91/100: train_loss=0.000116

      epoch  92/100: train_loss=0.000118

      epoch  93/100: train_loss=0.000116

      epoch  94/100: train_loss=0.000119

      epoch  95/100: train_loss=0.000117, val_loss=0.000392, IC=+0.0553

      epoch  96/100: train_loss=0.000116

      epoch  97/100: train_loss=0.000119

      epoch  98/100: train_loss=0.000120

      epoch  99/100: train_loss=0.000117

      epoch 100/100: train_loss=0.000120, val_loss=0.000392, IC=+0.0555

      best_ep=100, IC=+0.0555 (43.0s, 20 checkpoints)

  Fold 1: creating sequences...
    train=22,140 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002248

      epoch   2/100: train_loss=0.000465

      epoch   3/100: train_loss=0.000300

      epoch   4/100: train_loss=0.000251

      epoch   5/100: train_loss=0.000236, val_loss=0.000132, IC=-0.0019

      epoch   6/100: train_loss=0.000226

      epoch   7/100: train_loss=0.000222

      epoch   8/100: train_loss=0.000220

      epoch   9/100: train_loss=0.000216

      epoch  10/100: train_loss=0.000214, val_loss=0.000131, IC=-0.0151

      epoch  11/100: train_loss=0.000209

      epoch  12/100: train_loss=0.000208

      epoch  13/100: train_loss=0.000206

      epoch  14/100: train_loss=0.000204

      epoch  15/100: train_loss=0.000202, val_loss=0.000133, IC=-0.0165

      epoch  16/100: train_loss=0.000200

      epoch  17/100: train_loss=0.000199

      epoch  18/100: train_loss=0.000196

      epoch  19/100: train_loss=0.000194

      epoch  20/100: train_loss=0.000193, val_loss=0.000140, IC=-0.0367

      epoch  21/100: train_loss=0.000191

      epoch  22/100: train_loss=0.000190

      epoch  23/100: train_loss=0.000187

      epoch  24/100: train_loss=0.000185

      epoch  25/100: train_loss=0.000184, val_loss=0.000143, IC=+0.0113

      epoch  26/100: train_loss=0.000181

      epoch  27/100: train_loss=0.000179

      epoch  28/100: train_loss=0.000177

      epoch  29/100: train_loss=0.000177

      epoch  30/100: train_loss=0.000174, val_loss=0.000153, IC=+0.0081

      epoch  31/100: train_loss=0.000173

      epoch  32/100: train_loss=0.000171

      epoch  33/100: train_loss=0.000169

      epoch  34/100: train_loss=0.000168

      epoch  35/100: train_loss=0.000166, val_loss=0.000159, IC=+0.0076

      epoch  36/100: train_loss=0.000164

      epoch  37/100: train_loss=0.000163

      epoch  38/100: train_loss=0.000162

      epoch  39/100: train_loss=0.000160

      epoch  40/100: train_loss=0.000159, val_loss=0.000166, IC=-0.0041

      epoch  41/100: train_loss=0.000158

      epoch  42/100: train_loss=0.000156

      epoch  43/100: train_loss=0.000155

      epoch  44/100: train_loss=0.000154

      epoch  45/100: train_loss=0.000152, val_loss=0.000170, IC=+0.0078

      epoch  46/100: train_loss=0.000152

      epoch  47/100: train_loss=0.000151

      epoch  48/100: train_loss=0.000149

      epoch  49/100: train_loss=0.000148

      epoch  50/100: train_loss=0.000147, val_loss=0.000181, IC=+0.0097

      epoch  51/100: train_loss=0.000146

      epoch  52/100: train_loss=0.000145

      epoch  53/100: train_loss=0.000144

      epoch  54/100: train_loss=0.000143

      epoch  55/100: train_loss=0.000142, val_loss=0.000181, IC=-0.0021

      epoch  56/100: train_loss=0.000142

      epoch  57/100: train_loss=0.000141

      epoch  58/100: train_loss=0.000141

      epoch  59/100: train_loss=0.000140

      epoch  60/100: train_loss=0.000137, val_loss=0.000190, IC=-0.0037

      epoch  61/100: train_loss=0.000137

      epoch  62/100: train_loss=0.000137

      epoch  63/100: train_loss=0.000136

      epoch  64/100: train_loss=0.000137

      epoch  65/100: train_loss=0.000135, val_loss=0.000195, IC=+0.0040

      epoch  66/100: train_loss=0.000135

      epoch  67/100: train_loss=0.000135

      epoch  68/100: train_loss=0.000133

      epoch  69/100: train_loss=0.000132

      epoch  70/100: train_loss=0.000132, val_loss=0.000199, IC=+0.0017

      epoch  71/100: train_loss=0.000131

      epoch  72/100: train_loss=0.000131

      epoch  73/100: train_loss=0.000131

      epoch  74/100: train_loss=0.000131

      epoch  75/100: train_loss=0.000130, val_loss=0.000201, IC=-0.0040

      epoch  76/100: train_loss=0.000130

      epoch  77/100: train_loss=0.000130

      epoch  78/100: train_loss=0.000130

      epoch  79/100: train_loss=0.000129

      epoch  80/100: train_loss=0.000129, val_loss=0.000203, IC=+0.0044

      epoch  81/100: train_loss=0.000130

      epoch  82/100: train_loss=0.000129

      epoch  83/100: train_loss=0.000128

      epoch  84/100: train_loss=0.000129

      epoch  85/100: train_loss=0.000128, val_loss=0.000204, IC=-0.0013

      epoch  86/100: train_loss=0.000127

      epoch  87/100: train_loss=0.000128

      epoch  88/100: train_loss=0.000128

      epoch  89/100: train_loss=0.000127

      epoch  90/100: train_loss=0.000128, val_loss=0.000205, IC=+0.0009

      epoch  91/100: train_loss=0.000127

      epoch  92/100: train_loss=0.000128

      epoch  93/100: train_loss=0.000127

      epoch  94/100: train_loss=0.000127

      epoch  95/100: train_loss=0.000127, val_loss=0.000205, IC=+0.0014

      epoch  96/100: train_loss=0.000127

      epoch  97/100: train_loss=0.000128

      epoch  98/100: train_loss=0.000127

      epoch  99/100: train_loss=0.000129

      epoch 100/100: train_loss=0.000128, val_loss=0.000205, IC=+0.0014

      best_ep=25, IC=+0.0113 (57.4s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000690

      epoch   2/100: train_loss=0.000274

      epoch   3/100: train_loss=0.000229

      epoch   4/100: train_loss=0.000213

      epoch   5/100: train_loss=0.000206, val_loss=0.000124, IC=-0.0224

      epoch   6/100: train_loss=0.000202

      epoch   7/100: train_loss=0.000197

      epoch   8/100: train_loss=0.000196

      epoch   9/100: train_loss=0.000192

      epoch  10/100: train_loss=0.000190, val_loss=0.000122, IC=+0.0237

      epoch  11/100: train_loss=0.000187

      epoch  12/100: train_loss=0.000182

      epoch  13/100: train_loss=0.000180

      epoch  14/100: train_loss=0.000177

      epoch  15/100: train_loss=0.000175, val_loss=0.000132, IC=+0.0194

      epoch  16/100: train_loss=0.000171

      epoch  17/100: train_loss=0.000168

      epoch  18/100: train_loss=0.000166

      epoch  19/100: train_loss=0.000162

      epoch  20/100: train_loss=0.000161, val_loss=0.000133, IC=+0.0384

      epoch  21/100: train_loss=0.000157

      epoch  22/100: train_loss=0.000154

      epoch  23/100: train_loss=0.000152

      epoch  24/100: train_loss=0.000150

      epoch  25/100: train_loss=0.000148, val_loss=0.000142, IC=+0.0537

      epoch  26/100: train_loss=0.000145

      epoch  27/100: train_loss=0.000142

      epoch  28/100: train_loss=0.000140

      epoch  29/100: train_loss=0.000137

      epoch  30/100: train_loss=0.000136, val_loss=0.000150, IC=+0.0235

      epoch  31/100: train_loss=0.000134

      epoch  32/100: train_loss=0.000132

      epoch  33/100: train_loss=0.000129

      epoch  34/100: train_loss=0.000126

      epoch  35/100: train_loss=0.000126, val_loss=0.000162, IC=+0.0162

      epoch  36/100: train_loss=0.000124

      epoch  37/100: train_loss=0.000124

      epoch  38/100: train_loss=0.000122

      epoch  39/100: train_loss=0.000119

      epoch  40/100: train_loss=0.000118, val_loss=0.000172, IC=+0.0308

      epoch  41/100: train_loss=0.000116

      epoch  42/100: train_loss=0.000116

      epoch  43/100: train_loss=0.000114

      epoch  44/100: train_loss=0.000113

      epoch  45/100: train_loss=0.000112, val_loss=0.000179, IC=+0.0298

      epoch  46/100: train_loss=0.000111

      epoch  47/100: train_loss=0.000110

      epoch  48/100: train_loss=0.000109

      epoch  49/100: train_loss=0.000108

      epoch  50/100: train_loss=0.000106, val_loss=0.000189, IC=+0.0288

      epoch  51/100: train_loss=0.000106

      epoch  52/100: train_loss=0.000106

      epoch  53/100: train_loss=0.000104

      epoch  54/100: train_loss=0.000104

      epoch  55/100: train_loss=0.000103, val_loss=0.000188, IC=+0.0377

      epoch  56/100: train_loss=0.000102

      epoch  57/100: train_loss=0.000101

      epoch  58/100: train_loss=0.000100

      epoch  59/100: train_loss=0.000098

      epoch  60/100: train_loss=0.000099, val_loss=0.000193, IC=+0.0421

      epoch  61/100: train_loss=0.000097

      epoch  62/100: train_loss=0.000098

      epoch  63/100: train_loss=0.000097

      epoch  64/100: train_loss=0.000098

      epoch  65/100: train_loss=0.000096, val_loss=0.000201, IC=+0.0393

      epoch  66/100: train_loss=0.000096

      epoch  67/100: train_loss=0.000096

      epoch  68/100: train_loss=0.000095

      epoch  69/100: train_loss=0.000096

      epoch  70/100: train_loss=0.000095, val_loss=0.000204, IC=+0.0366

      epoch  71/100: train_loss=0.000094

      epoch  72/100: train_loss=0.000094

      epoch  73/100: train_loss=0.000095

      epoch  74/100: train_loss=0.000094

      epoch  75/100: train_loss=0.000093, val_loss=0.000212, IC=+0.0424

      epoch  76/100: train_loss=0.000092

      epoch  77/100: train_loss=0.000092

      epoch  78/100: train_loss=0.000092

      epoch  79/100: train_loss=0.000092

      epoch  80/100: train_loss=0.000092, val_loss=0.000207, IC=+0.0382

      epoch  81/100: train_loss=0.000092

      epoch  82/100: train_loss=0.000092

      epoch  83/100: train_loss=0.000092

      epoch  84/100: train_loss=0.000091

      epoch  85/100: train_loss=0.000092, val_loss=0.000210, IC=+0.0390

      epoch  86/100: train_loss=0.000091

      epoch  87/100: train_loss=0.000091

      epoch  88/100: train_loss=0.000091

      epoch  89/100: train_loss=0.000091

      epoch  90/100: train_loss=0.000091, val_loss=0.000211, IC=+0.0391

      epoch  91/100: train_loss=0.000090

      epoch  92/100: train_loss=0.000090

      epoch  93/100: train_loss=0.000090

      epoch  94/100: train_loss=0.000091

      epoch  95/100: train_loss=0.000090, val_loss=0.000213, IC=+0.0415

      epoch  96/100: train_loss=0.000090

      epoch  97/100: train_loss=0.000090

      epoch  98/100: train_loss=0.000091

      epoch  99/100: train_loss=0.000090

      epoch 100/100: train_loss=0.000091, val_loss=0.000212, IC=+0.0407

      best_ep=25, IC=+0.0537 (69.0s, 20 checkpoints)

  Fold 3: creating sequences...

    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000842

      epoch   2/100: train_loss=0.000284

      epoch   3/100: train_loss=0.000230

      epoch   4/100: train_loss=0.000206

      epoch   5/100: train_loss=0.000197, val_loss=0.000092, IC=-0.0091

      epoch   6/100: train_loss=0.000193

      epoch   7/100: train_loss=0.000190

      epoch   8/100: train_loss=0.000188

      epoch   9/100: train_loss=0.000185

      epoch  10/100: train_loss=0.000182, val_loss=0.000091, IC=-0.0138

      epoch  11/100: train_loss=0.000180

      epoch  12/100: train_loss=0.000178

      epoch  13/100: train_loss=0.000176

      epoch  14/100: train_loss=0.000173

      epoch  15/100: train_loss=0.000171, val_loss=0.000093, IC=-0.0291

      epoch  16/100: train_loss=0.000169

      epoch  17/100: train_loss=0.000168

      epoch  18/100: train_loss=0.000166

      epoch  19/100: train_loss=0.000163

      epoch  20/100: train_loss=0.000162, val_loss=0.000097, IC=-0.0035

      epoch  21/100: train_loss=0.000160

      epoch  22/100: train_loss=0.000158

      epoch  23/100: train_loss=0.000155

      epoch  24/100: train_loss=0.000154

      epoch  25/100: train_loss=0.000151, val_loss=0.000101, IC=-0.0018

      epoch  26/100: train_loss=0.000150

      epoch  27/100: train_loss=0.000147

      epoch  28/100: train_loss=0.000146

      epoch  29/100: train_loss=0.000144

      epoch  30/100: train_loss=0.000142, val_loss=0.000106, IC=+0.0029

      epoch  31/100: train_loss=0.000140

      epoch  32/100: train_loss=0.000139

      epoch  33/100: train_loss=0.000137

      epoch  34/100: train_loss=0.000136

      epoch  35/100: train_loss=0.000135, val_loss=0.000111, IC=+0.0015

      epoch  36/100: train_loss=0.000132

      epoch  37/100: train_loss=0.000131

      epoch  38/100: train_loss=0.000129

      epoch  39/100: train_loss=0.000127

      epoch  40/100: train_loss=0.000127, val_loss=0.000117, IC=+0.0021

      epoch  41/100: train_loss=0.000124

      epoch  42/100: train_loss=0.000124

      epoch  43/100: train_loss=0.000121

      epoch  44/100: train_loss=0.000121

      epoch  45/100: train_loss=0.000120, val_loss=0.000122, IC=+0.0026

      epoch  46/100: train_loss=0.000117

      epoch  47/100: train_loss=0.000117

      epoch  48/100: train_loss=0.000116

      epoch  49/100: train_loss=0.000114

      epoch  50/100: train_loss=0.000114, val_loss=0.000126, IC=+0.0029

      epoch  51/100: train_loss=0.000113

      epoch  52/100: train_loss=0.000113

      epoch  53/100: train_loss=0.000112

      epoch  54/100: train_loss=0.000110

      epoch  55/100: train_loss=0.000110, val_loss=0.000128, IC=+0.0028

      epoch  56/100: train_loss=0.000108

      epoch  57/100: train_loss=0.000109

      epoch  58/100: train_loss=0.000107

      epoch  59/100: train_loss=0.000106

      epoch  60/100: train_loss=0.000106, val_loss=0.000132, IC=+0.0017

      epoch  61/100: train_loss=0.000105

      epoch  62/100: train_loss=0.000106

      epoch  63/100: train_loss=0.000104

      epoch  64/100: train_loss=0.000104

      epoch  65/100: train_loss=0.000102, val_loss=0.000132, IC=-0.0041

      epoch  66/100: train_loss=0.000102

      epoch  67/100: train_loss=0.000100

      epoch  68/100: train_loss=0.000102

      epoch  69/100: train_loss=0.000100

      epoch  70/100: train_loss=0.000100, val_loss=0.000137, IC=-0.0003

      epoch  71/100: train_loss=0.000099

      epoch  72/100: train_loss=0.000099

      epoch  73/100: train_loss=0.000100

      epoch  74/100: train_loss=0.000099

      epoch  75/100: train_loss=0.000099, val_loss=0.000137, IC=+0.0028

      epoch  76/100: train_loss=0.000098

      epoch  77/100: train_loss=0.000098

      epoch  78/100: train_loss=0.000099

      epoch  79/100: train_loss=0.000098

      epoch  80/100: train_loss=0.000097, val_loss=0.000137, IC=+0.0023

      epoch  81/100: train_loss=0.000097

      epoch  82/100: train_loss=0.000097

      epoch  83/100: train_loss=0.000096

      epoch  84/100: train_loss=0.000097

      epoch  85/100: train_loss=0.000097, val_loss=0.000137, IC=+0.0044

      epoch  86/100: train_loss=0.000096

      epoch  87/100: train_loss=0.000096

      epoch  88/100: train_loss=0.000097

      epoch  89/100: train_loss=0.000097

      epoch  90/100: train_loss=0.000096, val_loss=0.000138, IC=+0.0031

      epoch  91/100: train_loss=0.000095

      epoch  92/100: train_loss=0.000096

      epoch  93/100: train_loss=0.000096

      epoch  94/100: train_loss=0.000095

      epoch  95/100: train_loss=0.000096, val_loss=0.000138, IC=+0.0025

      epoch  96/100: train_loss=0.000096

      epoch  97/100: train_loss=0.000095

      epoch  98/100: train_loss=0.000096

      epoch  99/100: train_loss=0.000095

      epoch 100/100: train_loss=0.000096, val_loss=0.000137, IC=+0.0031

      best_ep=85, IC=+0.0044 (66.4s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000600

      epoch   2/100: train_loss=0.000225

      epoch   3/100: train_loss=0.000185

      epoch   4/100: train_loss=0.000168

      epoch   5/100: train_loss=0.000162, val_loss=0.000236, IC=-0.1068

      epoch   6/100: train_loss=0.000158

      epoch   7/100: train_loss=0.000155

      epoch   8/100: train_loss=0.000152

      epoch   9/100: train_loss=0.000149

      epoch  10/100: train_loss=0.000147, val_loss=0.000248, IC=-0.1345

      epoch  11/100: train_loss=0.000145

      epoch  12/100: train_loss=0.000142

      epoch  13/100: train_loss=0.000140

      epoch  14/100: train_loss=0.000138

      epoch  15/100: train_loss=0.000136, val_loss=0.000263, IC=-0.1363

      epoch  16/100: train_loss=0.000134

      epoch  17/100: train_loss=0.000132

      epoch  18/100: train_loss=0.000129

      epoch  19/100: train_loss=0.000127

      epoch  20/100: train_loss=0.000125, val_loss=0.000287, IC=-0.1237

      epoch  21/100: train_loss=0.000123

      epoch  22/100: train_loss=0.000121

      epoch  23/100: train_loss=0.000121

      epoch  24/100: train_loss=0.000118

      epoch  25/100: train_loss=0.000117, val_loss=0.000305, IC=-0.1069

      epoch  26/100: train_loss=0.000114

      epoch  27/100: train_loss=0.000112

      epoch  28/100: train_loss=0.000111

      epoch  29/100: train_loss=0.000110

      epoch  30/100: train_loss=0.000108, val_loss=0.000309, IC=-0.1098

      epoch  31/100: train_loss=0.000106

      epoch  32/100: train_loss=0.000105

      epoch  33/100: train_loss=0.000104

      epoch  34/100: train_loss=0.000103

      epoch  35/100: train_loss=0.000102, val_loss=0.000319, IC=-0.1001

      epoch  36/100: train_loss=0.000101

      epoch  37/100: train_loss=0.000100

      epoch  38/100: train_loss=0.000099

      epoch  39/100: train_loss=0.000097

      epoch  40/100: train_loss=0.000096, val_loss=0.000353, IC=-0.0940

      epoch  41/100: train_loss=0.000095

      epoch  42/100: train_loss=0.000095

      epoch  43/100: train_loss=0.000094

      epoch  44/100: train_loss=0.000093

      epoch  45/100: train_loss=0.000093, val_loss=0.000357, IC=-0.0915

      epoch  46/100: train_loss=0.000091

      epoch  47/100: train_loss=0.000091

      epoch  48/100: train_loss=0.000090

      epoch  49/100: train_loss=0.000089

      epoch  50/100: train_loss=0.000088, val_loss=0.000366, IC=-0.0877

      epoch  51/100: train_loss=0.000087

      epoch  52/100: train_loss=0.000087

      epoch  53/100: train_loss=0.000086

      epoch  54/100: train_loss=0.000085

      epoch  55/100: train_loss=0.000085, val_loss=0.000385, IC=-0.0854

      epoch  56/100: train_loss=0.000084

      epoch  57/100: train_loss=0.000083

      epoch  58/100: train_loss=0.000083

      epoch  59/100: train_loss=0.000082

      epoch  60/100: train_loss=0.000081, val_loss=0.000395, IC=-0.0827

      epoch  61/100: train_loss=0.000081

      epoch  62/100: train_loss=0.000081

      epoch  63/100: train_loss=0.000080

      epoch  64/100: train_loss=0.000080

      epoch  65/100: train_loss=0.000079, val_loss=0.000395, IC=-0.0824

      epoch  66/100: train_loss=0.000079

      epoch  67/100: train_loss=0.000079

      epoch  68/100: train_loss=0.000079

      epoch  69/100: train_loss=0.000078

      epoch  70/100: train_loss=0.000078, val_loss=0.000412, IC=-0.0833

      epoch  71/100: train_loss=0.000078

      epoch  72/100: train_loss=0.000077

      epoch  73/100: train_loss=0.000077

      epoch  74/100: train_loss=0.000076

      epoch  75/100: train_loss=0.000077, val_loss=0.000415, IC=-0.0850

      epoch  76/100: train_loss=0.000076

      epoch  77/100: train_loss=0.000076

      epoch  78/100: train_loss=0.000076

      epoch  79/100: train_loss=0.000076

      epoch  80/100: train_loss=0.000075, val_loss=0.000422, IC=-0.0835

      epoch  81/100: train_loss=0.000075

      epoch  82/100: train_loss=0.000075

      epoch  83/100: train_loss=0.000075

      epoch  84/100: train_loss=0.000075

      epoch  85/100: train_loss=0.000075, val_loss=0.000427, IC=-0.0813

      epoch  86/100: train_loss=0.000074

      epoch  87/100: train_loss=0.000075

      epoch  88/100: train_loss=0.000074

      epoch  89/100: train_loss=0.000074

      epoch  90/100: train_loss=0.000075, val_loss=0.000421, IC=-0.0819

      epoch  91/100: train_loss=0.000075

      epoch  92/100: train_loss=0.000074

      epoch  93/100: train_loss=0.000074

      epoch  94/100: train_loss=0.000074

      epoch  95/100: train_loss=0.000074, val_loss=0.000423, IC=-0.0830

      epoch  96/100: train_loss=0.000074

      epoch  97/100: train_loss=0.000074

      epoch  98/100: train_loss=0.000074

      epoch  99/100: train_loss=0.000074

      epoch 100/100: train_loss=0.000074, val_loss=0.000422, IC=-0.0829

      best_ep=85, IC=-0.0813 (84.3s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002793

      epoch   2/100: train_loss=0.000420

      epoch   3/100: train_loss=0.000247

      epoch   4/100: train_loss=0.000191

      epoch   5/100: train_loss=0.000171, val_loss=0.000098, IC=+0.0064

      epoch   6/100: train_loss=0.000163

      epoch   7/100: train_loss=0.000159

      epoch   8/100: train_loss=0.000155

      epoch   9/100: train_loss=0.000152

      epoch  10/100: train_loss=0.000149, val_loss=0.000093, IC=+0.0194

      epoch  11/100: train_loss=0.000148

      epoch  12/100: train_loss=0.000145

      epoch  13/100: train_loss=0.000143

      epoch  14/100: train_loss=0.000141

      epoch  15/100: train_loss=0.000141, val_loss=0.000092, IC=+0.0356

      epoch  16/100: train_loss=0.000139

      epoch  17/100: train_loss=0.000137

      epoch  18/100: train_loss=0.000134

      epoch  19/100: train_loss=0.000134

      epoch  20/100: train_loss=0.000132, val_loss=0.000092, IC=+0.0438

      epoch  21/100: train_loss=0.000131

      epoch  22/100: train_loss=0.000129

      epoch  23/100: train_loss=0.000128

      epoch  24/100: train_loss=0.000127

      epoch  25/100: train_loss=0.000125, val_loss=0.000092, IC=+0.0576

      epoch  26/100: train_loss=0.000124

      epoch  27/100: train_loss=0.000123

      epoch  28/100: train_loss=0.000122

      epoch  29/100: train_loss=0.000120

      epoch  30/100: train_loss=0.000120, val_loss=0.000092, IC=+0.0658

      epoch  31/100: train_loss=0.000118

      epoch  32/100: train_loss=0.000117

      epoch  33/100: train_loss=0.000116

      epoch  34/100: train_loss=0.000115

      epoch  35/100: train_loss=0.000114, val_loss=0.000094, IC=+0.0705

      epoch  36/100: train_loss=0.000114

      epoch  37/100: train_loss=0.000112

      epoch  38/100: train_loss=0.000112

      epoch  39/100: train_loss=0.000111

      epoch  40/100: train_loss=0.000110, val_loss=0.000095, IC=+0.0702

      epoch  41/100: train_loss=0.000109

      epoch  42/100: train_loss=0.000108

      epoch  43/100: train_loss=0.000108

      epoch  44/100: train_loss=0.000108

      epoch  45/100: train_loss=0.000107, val_loss=0.000097, IC=+0.0725

      epoch  46/100: train_loss=0.000105

      epoch  47/100: train_loss=0.000106

      epoch  48/100: train_loss=0.000105

      epoch  49/100: train_loss=0.000104

      epoch  50/100: train_loss=0.000103, val_loss=0.000100, IC=+0.0733

      epoch  51/100: train_loss=0.000102

      epoch  52/100: train_loss=0.000102

      epoch  53/100: train_loss=0.000102

      epoch  54/100: train_loss=0.000101

      epoch  55/100: train_loss=0.000101, val_loss=0.000101, IC=+0.0706

      epoch  56/100: train_loss=0.000100

      epoch  57/100: train_loss=0.000099

      epoch  58/100: train_loss=0.000099

      epoch  59/100: train_loss=0.000098

      epoch  60/100: train_loss=0.000099, val_loss=0.000102, IC=+0.0649

      epoch  61/100: train_loss=0.000098

      epoch  62/100: train_loss=0.000097

      epoch  63/100: train_loss=0.000097

      epoch  64/100: train_loss=0.000096

      epoch  65/100: train_loss=0.000097, val_loss=0.000105, IC=+0.0633

      epoch  66/100: train_loss=0.000096

      epoch  67/100: train_loss=0.000096

      epoch  68/100: train_loss=0.000096

      epoch  69/100: train_loss=0.000095

      epoch  70/100: train_loss=0.000095, val_loss=0.000105, IC=+0.0610

      epoch  71/100: train_loss=0.000095

      epoch  72/100: train_loss=0.000095

      epoch  73/100: train_loss=0.000094

      epoch  74/100: train_loss=0.000094

      epoch  75/100: train_loss=0.000094, val_loss=0.000105, IC=+0.0587

      epoch  76/100: train_loss=0.000093

      epoch  77/100: train_loss=0.000093

      epoch  78/100: train_loss=0.000093

      epoch  79/100: train_loss=0.000093

      epoch  80/100: train_loss=0.000093, val_loss=0.000106, IC=+0.0580

      epoch  81/100: train_loss=0.000093

      epoch  82/100: train_loss=0.000093

      epoch  83/100: train_loss=0.000093

      epoch  84/100: train_loss=0.000093

      epoch  85/100: train_loss=0.000092, val_loss=0.000107, IC=+0.0561

      epoch  86/100: train_loss=0.000092

      epoch  87/100: train_loss=0.000092

      epoch  88/100: train_loss=0.000092

      epoch  89/100: train_loss=0.000092

      epoch  90/100: train_loss=0.000092, val_loss=0.000107, IC=+0.0566

      epoch  91/100: train_loss=0.000092

      epoch  92/100: train_loss=0.000092

      epoch  93/100: train_loss=0.000092

      epoch  94/100: train_loss=0.000092

      epoch  95/100: train_loss=0.000093, val_loss=0.000107, IC=+0.0571

      epoch  96/100: train_loss=0.000092

      epoch  97/100: train_loss=0.000092

      epoch  98/100: train_loss=0.000092

      epoch  99/100: train_loss=0.000092

      epoch 100/100: train_loss=0.000092, val_loss=0.000107, IC=+0.0567

      best_ep=50, IC=+0.0733 (97.2s, 20 checkpoints)

  Fold 6: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000636

      epoch   2/100: train_loss=0.000199

      epoch   3/100: train_loss=0.000144

      epoch   4/100: train_loss=0.000127

      epoch   5/100: train_loss=0.000120, val_loss=0.000239, IC=-0.0333

      epoch   6/100: train_loss=0.000116

      epoch   7/100: train_loss=0.000113

      epoch   8/100: train_loss=0.000111

      epoch   9/100: train_loss=0.000108

      epoch  10/100: train_loss=0.000107, val_loss=0.000261, IC=-0.0170

      epoch  11/100: train_loss=0.000106

      epoch  12/100: train_loss=0.000104

      epoch  13/100: train_loss=0.000102

      epoch  14/100: train_loss=0.000101

      epoch  15/100: train_loss=0.000099, val_loss=0.000268, IC=-0.0130

      epoch  16/100: train_loss=0.000098

      epoch  17/100: train_loss=0.000098

      epoch  18/100: train_loss=0.000095

      epoch  19/100: train_loss=0.000094

      epoch  20/100: train_loss=0.000092, val_loss=0.000283, IC=-0.0012

      epoch  21/100: train_loss=0.000091

      epoch  22/100: train_loss=0.000090

      epoch  23/100: train_loss=0.000089

      epoch  24/100: train_loss=0.000087

      epoch  25/100: train_loss=0.000087, val_loss=0.000296, IC=-0.0056

      epoch  26/100: train_loss=0.000086

      epoch  27/100: train_loss=0.000084

      epoch  28/100: train_loss=0.000083

      epoch  29/100: train_loss=0.000082

      epoch  30/100: train_loss=0.000081, val_loss=0.000328, IC=-0.0038

      epoch  31/100: train_loss=0.000081

      epoch  32/100: train_loss=0.000079

      epoch  33/100: train_loss=0.000079

      epoch  34/100: train_loss=0.000078

      epoch  35/100: train_loss=0.000077, val_loss=0.000347, IC=-0.0215

      epoch  36/100: train_loss=0.000076

      epoch  37/100: train_loss=0.000076

      epoch  38/100: train_loss=0.000074

      epoch  39/100: train_loss=0.000073

      epoch  40/100: train_loss=0.000072, val_loss=0.000361, IC=-0.0226

      epoch  41/100: train_loss=0.000072

      epoch  42/100: train_loss=0.000072

      epoch  43/100: train_loss=0.000071

      epoch  44/100: train_loss=0.000070

      epoch  45/100: train_loss=0.000070, val_loss=0.000355, IC=-0.0116

      epoch  46/100: train_loss=0.000069

      epoch  47/100: train_loss=0.000069

      epoch  48/100: train_loss=0.000067

      epoch  49/100: train_loss=0.000067

      epoch  50/100: train_loss=0.000066, val_loss=0.000360, IC=+0.0037

      epoch  51/100: train_loss=0.000066

      epoch  52/100: train_loss=0.000065

      epoch  53/100: train_loss=0.000065

      epoch  54/100: train_loss=0.000064

      epoch  55/100: train_loss=0.000064, val_loss=0.000358, IC=+0.0073

      epoch  56/100: train_loss=0.000064

      epoch  57/100: train_loss=0.000064

      epoch  58/100: train_loss=0.000063

      epoch  59/100: train_loss=0.000062

      epoch  60/100: train_loss=0.000062, val_loss=0.000384, IC=-0.0092

      epoch  61/100: train_loss=0.000062

      epoch  62/100: train_loss=0.000061

      epoch  63/100: train_loss=0.000061

      epoch  64/100: train_loss=0.000061

      epoch  65/100: train_loss=0.000060, val_loss=0.000373, IC=-0.0016

      epoch  66/100: train_loss=0.000060

      epoch  67/100: train_loss=0.000060

      epoch  68/100: train_loss=0.000060

      epoch  69/100: train_loss=0.000060

      epoch  70/100: train_loss=0.000059, val_loss=0.000374, IC=+0.0002

      epoch  71/100: train_loss=0.000059

      epoch  72/100: train_loss=0.000059

      epoch  73/100: train_loss=0.000059

      epoch  74/100: train_loss=0.000059

      epoch  75/100: train_loss=0.000058, val_loss=0.000374, IC=+0.0020

      epoch  76/100: train_loss=0.000058

      epoch  77/100: train_loss=0.000058

      epoch  78/100: train_loss=0.000058

      epoch  79/100: train_loss=0.000058

      epoch  80/100: train_loss=0.000057, val_loss=0.000371, IC=+0.0043

      epoch  81/100: train_loss=0.000058

      epoch  82/100: train_loss=0.000058

      epoch  83/100: train_loss=0.000057

      epoch  84/100: train_loss=0.000057

      epoch  85/100: train_loss=0.000057, val_loss=0.000372, IC=+0.0032

      epoch  86/100: train_loss=0.000057

      epoch  87/100: train_loss=0.000057

      epoch  88/100: train_loss=0.000057

      epoch  89/100: train_loss=0.000057

      epoch  90/100: train_loss=0.000057, val_loss=0.000375, IC=+0.0030

      epoch  91/100: train_loss=0.000057

      epoch  92/100: train_loss=0.000057

      epoch  93/100: train_loss=0.000057

      epoch  94/100: train_loss=0.000057

      epoch  95/100: train_loss=0.000057, val_loss=0.000374, IC=+0.0040

      epoch  96/100: train_loss=0.000057

      epoch  97/100: train_loss=0.000057

      epoch  98/100: train_loss=0.000057

      epoch  99/100: train_loss=0.000057

      epoch 100/100: train_loss=0.000057, val_loss=0.000374, IC=+0.0041

      best_ep=55, IC=+0.0073 (112.2s, 20 checkpoints)

  Fold 7: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,060 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.003162

      epoch   2/100: train_loss=0.000506

      epoch   3/100: train_loss=0.000259

      epoch   4/100: train_loss=0.000190

      epoch   5/100: train_loss=0.000165, val_loss=0.000156, IC=+0.0124

      epoch   6/100: train_loss=0.000155

      epoch   7/100: train_loss=0.000150

      epoch   8/100: train_loss=0.000146

      epoch   9/100: train_loss=0.000143

      epoch  10/100: train_loss=0.000140, val_loss=0.000138, IC=+0.0073

      epoch  11/100: train_loss=0.000139

      epoch  12/100: train_loss=0.000136

      epoch  13/100: train_loss=0.000134

      epoch  14/100: train_loss=0.000132

      epoch  15/100: train_loss=0.000131, val_loss=0.000137, IC=-0.0143

      epoch  16/100: train_loss=0.000130

      epoch  17/100: train_loss=0.000128

      epoch  18/100: train_loss=0.000127

      epoch  19/100: train_loss=0.000125

      epoch  20/100: train_loss=0.000125, val_loss=0.000138, IC=-0.0242

      epoch  21/100: train_loss=0.000124

      epoch  22/100: train_loss=0.000122

      epoch  23/100: train_loss=0.000121

      epoch  24/100: train_loss=0.000119

      epoch  25/100: train_loss=0.000119, val_loss=0.000143, IC=-0.0330

      epoch  26/100: train_loss=0.000118

      epoch  27/100: train_loss=0.000117

      epoch  28/100: train_loss=0.000116

      epoch  29/100: train_loss=0.000115

      epoch  30/100: train_loss=0.000114, val_loss=0.000148, IC=-0.0418

      epoch  31/100: train_loss=0.000113

      epoch  32/100: train_loss=0.000112

      epoch  33/100: train_loss=0.000112

      epoch  34/100: train_loss=0.000111

      epoch  35/100: train_loss=0.000110, val_loss=0.000155, IC=-0.0494

      epoch  36/100: train_loss=0.000109

      epoch  37/100: train_loss=0.000109

      epoch  38/100: train_loss=0.000108

      epoch  39/100: train_loss=0.000108

      epoch  40/100: train_loss=0.000106, val_loss=0.000160, IC=-0.0504

      epoch  41/100: train_loss=0.000106

      epoch  42/100: train_loss=0.000105

      epoch  43/100: train_loss=0.000105

      epoch  44/100: train_loss=0.000104

      epoch  45/100: train_loss=0.000104, val_loss=0.000167, IC=-0.0629

      epoch  46/100: train_loss=0.000104

      epoch  47/100: train_loss=0.000103

      epoch  48/100: train_loss=0.000102

      epoch  49/100: train_loss=0.000102

      epoch  50/100: train_loss=0.000102, val_loss=0.000170, IC=-0.0703

      epoch  51/100: train_loss=0.000101

      epoch  52/100: train_loss=0.000100

      epoch  53/100: train_loss=0.000100

      epoch  54/100: train_loss=0.000099

      epoch  55/100: train_loss=0.000099, val_loss=0.000174, IC=-0.0663

      epoch  56/100: train_loss=0.000098

      epoch  57/100: train_loss=0.000099

      epoch  58/100: train_loss=0.000098

      epoch  59/100: train_loss=0.000097

      epoch  60/100: train_loss=0.000097, val_loss=0.000176, IC=-0.0699

      epoch  61/100: train_loss=0.000097

      epoch  62/100: train_loss=0.000097

      epoch  63/100: train_loss=0.000096

      epoch  64/100: train_loss=0.000096

      epoch  65/100: train_loss=0.000096, val_loss=0.000176, IC=-0.0751

      epoch  66/100: train_loss=0.000095

      epoch  67/100: train_loss=0.000095

      epoch  68/100: train_loss=0.000095

      epoch  69/100: train_loss=0.000094

      epoch  70/100: train_loss=0.000095, val_loss=0.000181, IC=-0.0798

      epoch  71/100: train_loss=0.000094

      epoch  72/100: train_loss=0.000093

      epoch  73/100: train_loss=0.000094

      epoch  74/100: train_loss=0.000093

      epoch  75/100: train_loss=0.000094, val_loss=0.000183, IC=-0.0808

      epoch  76/100: train_loss=0.000093

      epoch  77/100: train_loss=0.000093

      epoch  78/100: train_loss=0.000093

      epoch  79/100: train_loss=0.000093

      epoch  80/100: train_loss=0.000093, val_loss=0.000184, IC=-0.0801

      epoch  81/100: train_loss=0.000093

      epoch  82/100: train_loss=0.000092

      epoch  83/100: train_loss=0.000092

      epoch  84/100: train_loss=0.000092

      epoch  85/100: train_loss=0.000091, val_loss=0.000183, IC=-0.0823

      epoch  86/100: train_loss=0.000092

      epoch  87/100: train_loss=0.000092

      epoch  88/100: train_loss=0.000091

      epoch  89/100: train_loss=0.000092

      epoch  90/100: train_loss=0.000091, val_loss=0.000184, IC=-0.0809

      epoch  91/100: train_loss=0.000092

      epoch  92/100: train_loss=0.000092

      epoch  93/100: train_loss=0.000092

      epoch  94/100: train_loss=0.000092

      epoch  95/100: train_loss=0.000092, val_loss=0.000184, IC=-0.0815

      epoch  96/100: train_loss=0.000092

      epoch  97/100: train_loss=0.000092

      epoch  98/100: train_loss=0.000092

      epoch  99/100: train_loss=0.000092

      epoch 100/100: train_loss=0.000092, val_loss=0.000184, IC=-0.0812

      best_ep=5, IC=+0.0124 (113.1s, 20 checkpoints)

  lstm_h64: best_epoch=55, IC=+0.0018 (642.6s)

  Best: lstm_h64 @ epoch 55 (IC=+0.0018)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/ef01d12ba279/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=16,660 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002886

      epoch   2/100: train_loss=0.001023

      epoch   3/100: train_loss=0.000796

      epoch   4/100: train_loss=0.000725

      epoch   5/100: train_loss=0.000702, val_loss=0.001260, IC=+0.0660

      epoch   6/100: train_loss=0.000658

      epoch   7/100: train_loss=0.000633

      epoch   8/100: train_loss=0.000583

      epoch   9/100: train_loss=0.000567

      epoch  10/100: train_loss=0.000545, val_loss=0.001469, IC=+0.0554

      epoch  11/100: train_loss=0.000513

      epoch  12/100: train_loss=0.000478

      epoch  13/100: train_loss=0.000461

      epoch  14/100: train_loss=0.000432

      epoch  15/100: train_loss=0.000414, val_loss=0.001519, IC=+0.0508

      epoch  16/100: train_loss=0.000400

      epoch  17/100: train_loss=0.000378

      epoch  18/100: train_loss=0.000360

      epoch  19/100: train_loss=0.000344

      epoch  20/100: train_loss=0.000340, val_loss=0.001448, IC=+0.0732

      epoch  21/100: train_loss=0.000326

      epoch  22/100: train_loss=0.000315

      epoch  23/100: train_loss=0.000299

      epoch  24/100: train_loss=0.000292

      epoch  25/100: train_loss=0.000271, val_loss=0.001458, IC=+0.0792

      epoch  26/100: train_loss=0.000258

      epoch  27/100: train_loss=0.000251

      epoch  28/100: train_loss=0.000242

      epoch  29/100: train_loss=0.000234

      epoch  30/100: train_loss=0.000226, val_loss=0.001481, IC=+0.0789

      epoch  31/100: train_loss=0.000218

      epoch  32/100: train_loss=0.000214

      epoch  33/100: train_loss=0.000204

      epoch  34/100: train_loss=0.000203

      epoch  35/100: train_loss=0.000191, val_loss=0.001487, IC=+0.0754

      epoch  36/100: train_loss=0.000191

      epoch  37/100: train_loss=0.000181

      epoch  38/100: train_loss=0.000181

      epoch  39/100: train_loss=0.000176

      epoch  40/100: train_loss=0.000166, val_loss=0.001530, IC=+0.0700

      epoch  41/100: train_loss=0.000169

      epoch  42/100: train_loss=0.000172

      epoch  43/100: train_loss=0.000166

      epoch  44/100: train_loss=0.000156

      epoch  45/100: train_loss=0.000155, val_loss=0.001561, IC=+0.0649

      epoch  46/100: train_loss=0.000153

      epoch  47/100: train_loss=0.000147

      epoch  48/100: train_loss=0.000145

      epoch  49/100: train_loss=0.000140

      epoch  50/100: train_loss=0.000140, val_loss=0.001564, IC=+0.0585

      epoch  51/100: train_loss=0.000137

      epoch  52/100: train_loss=0.000134

      epoch  53/100: train_loss=0.000132

      epoch  54/100: train_loss=0.000128

      epoch  55/100: train_loss=0.000137, val_loss=0.001522, IC=+0.0604

      epoch  56/100: train_loss=0.000128

      epoch  57/100: train_loss=0.000127

      epoch  58/100: train_loss=0.000130

      epoch  59/100: train_loss=0.000123

      epoch  60/100: train_loss=0.000125, val_loss=0.001598, IC=+0.0676

      epoch  61/100: train_loss=0.000122

      epoch  62/100: train_loss=0.000123

      epoch  63/100: train_loss=0.000123

      epoch  64/100: train_loss=0.000119

      epoch  65/100: train_loss=0.000123, val_loss=0.001550, IC=+0.0709

      epoch  66/100: train_loss=0.000117

      epoch  67/100: train_loss=0.000118

      epoch  68/100: train_loss=0.000119

      epoch  69/100: train_loss=0.000129

      epoch  70/100: train_loss=0.000117, val_loss=0.001534, IC=+0.0682

      epoch  71/100: train_loss=0.000113

      epoch  72/100: train_loss=0.000115

      epoch  73/100: train_loss=0.000113

      epoch  74/100: train_loss=0.000113

      epoch  75/100: train_loss=0.000112, val_loss=0.001527, IC=+0.0763

      epoch  76/100: train_loss=0.000113

      epoch  77/100: train_loss=0.000109

      epoch  78/100: train_loss=0.000110

      epoch  79/100: train_loss=0.000112

      epoch  80/100: train_loss=0.000120, val_loss=0.001519, IC=+0.0778

      epoch  81/100: train_loss=0.000111

      epoch  82/100: train_loss=0.000111

      epoch  83/100: train_loss=0.000111

      epoch  84/100: train_loss=0.000108

      epoch  85/100: train_loss=0.000109, val_loss=0.001512, IC=+0.0760

      epoch  86/100: train_loss=0.000110

      epoch  87/100: train_loss=0.000109

      epoch  88/100: train_loss=0.000106

      epoch  89/100: train_loss=0.000108

      epoch  90/100: train_loss=0.000108, val_loss=0.001531, IC=+0.0773

      epoch  91/100: train_loss=0.000106

      epoch  92/100: train_loss=0.000106

      epoch  93/100: train_loss=0.000108

      epoch  94/100: train_loss=0.000107

      epoch  95/100: train_loss=0.000106, val_loss=0.001524, IC=+0.0766

      epoch  96/100: train_loss=0.000107

      epoch  97/100: train_loss=0.000109

      epoch  98/100: train_loss=0.000109

      epoch  99/100: train_loss=0.000105

      epoch 100/100: train_loss=0.000108, val_loss=0.001524, IC=+0.0752

      best_ep=25, IC=+0.0792 (89.6s, 20 checkpoints)

  Fold 1: creating sequences...
    train=21,820 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002807

      epoch   2/100: train_loss=0.001033

      epoch   3/100: train_loss=0.000848

      epoch   4/100: train_loss=0.000781

      epoch   5/100: train_loss=0.000730, val_loss=0.000607, IC=-0.0292

      epoch   6/100: train_loss=0.000701

      epoch   7/100: train_loss=0.000661

      epoch   8/100: train_loss=0.000623

      epoch   9/100: train_loss=0.000591

      epoch  10/100: train_loss=0.000559, val_loss=0.000706, IC=-0.0477

      epoch  11/100: train_loss=0.000526

      epoch  12/100: train_loss=0.000501

      epoch  13/100: train_loss=0.000471

      epoch  14/100: train_loss=0.000449

      epoch  15/100: train_loss=0.000420, val_loss=0.000848, IC=-0.1146

      epoch  16/100: train_loss=0.000398

      epoch  17/100: train_loss=0.000377

      epoch  18/100: train_loss=0.000351

      epoch  19/100: train_loss=0.000333

      epoch  20/100: train_loss=0.000316, val_loss=0.000982, IC=-0.0776

      epoch  21/100: train_loss=0.000300

      epoch  22/100: train_loss=0.000284

      epoch  23/100: train_loss=0.000270

      epoch  24/100: train_loss=0.000255

      epoch  25/100: train_loss=0.000245, val_loss=0.001103, IC=-0.0805

      epoch  26/100: train_loss=0.000236

      epoch  27/100: train_loss=0.000222

      epoch  28/100: train_loss=0.000214

      epoch  29/100: train_loss=0.000213

      epoch  30/100: train_loss=0.000202, val_loss=0.001166, IC=-0.0608

      epoch  31/100: train_loss=0.000193

      epoch  32/100: train_loss=0.000186

      epoch  33/100: train_loss=0.000182

      epoch  34/100: train_loss=0.000176

      epoch  35/100: train_loss=0.000171, val_loss=0.001270, IC=-0.0451

      epoch  36/100: train_loss=0.000166

      epoch  37/100: train_loss=0.000163

      epoch  38/100: train_loss=0.000160

      epoch  39/100: train_loss=0.000156

      epoch  40/100: train_loss=0.000153, val_loss=0.001251, IC=-0.0249

      epoch  41/100: train_loss=0.000150

      epoch  42/100: train_loss=0.000150

      epoch  43/100: train_loss=0.000144

      epoch  44/100: train_loss=0.000143

      epoch  45/100: train_loss=0.000142, val_loss=0.001231, IC=-0.0099

      epoch  46/100: train_loss=0.000139

      epoch  47/100: train_loss=0.000138

      epoch  48/100: train_loss=0.000136

      epoch  49/100: train_loss=0.000136

      epoch  50/100: train_loss=0.000135, val_loss=0.001187, IC=+0.0195

      epoch  51/100: train_loss=0.000132

      epoch  52/100: train_loss=0.000130

      epoch  53/100: train_loss=0.000128

      epoch  54/100: train_loss=0.000127

      epoch  55/100: train_loss=0.000125, val_loss=0.001204, IC=+0.0124

      epoch  56/100: train_loss=0.000124

      epoch  57/100: train_loss=0.000124

      epoch  58/100: train_loss=0.000123

      epoch  59/100: train_loss=0.000123

      epoch  60/100: train_loss=0.000122, val_loss=0.001238, IC=+0.0099

      epoch  61/100: train_loss=0.000122

      epoch  62/100: train_loss=0.000119

      epoch  63/100: train_loss=0.000119

      epoch  64/100: train_loss=0.000117

      epoch  65/100: train_loss=0.000117, val_loss=0.001211, IC=+0.0218

      epoch  66/100: train_loss=0.000117

      epoch  67/100: train_loss=0.000115

      epoch  68/100: train_loss=0.000114

      epoch  69/100: train_loss=0.000116

      epoch  70/100: train_loss=0.000116, val_loss=0.001218, IC=+0.0078

      epoch  71/100: train_loss=0.000115

      epoch  72/100: train_loss=0.000114

      epoch  73/100: train_loss=0.000113

      epoch  74/100: train_loss=0.000112

      epoch  75/100: train_loss=0.000112, val_loss=0.001204, IC=+0.0255

      epoch  76/100: train_loss=0.000111

      epoch  77/100: train_loss=0.000112

      epoch  78/100: train_loss=0.000111

      epoch  79/100: train_loss=0.000112

      epoch  80/100: train_loss=0.000111, val_loss=0.001209, IC=+0.0248

      epoch  81/100: train_loss=0.000110

      epoch  82/100: train_loss=0.000110

      epoch  83/100: train_loss=0.000110

      epoch  84/100: train_loss=0.000110

      epoch  85/100: train_loss=0.000110, val_loss=0.001217, IC=+0.0198

      epoch  86/100: train_loss=0.000110

      epoch  87/100: train_loss=0.000109

      epoch  88/100: train_loss=0.000109

      epoch  89/100: train_loss=0.000108

      epoch  90/100: train_loss=0.000108, val_loss=0.001207, IC=+0.0251

      epoch  91/100: train_loss=0.000108

      epoch  92/100: train_loss=0.000109

      epoch  93/100: train_loss=0.000109

      epoch  94/100: train_loss=0.000109

      epoch  95/100: train_loss=0.000108, val_loss=0.001209, IC=+0.0251

      epoch  96/100: train_loss=0.000108

      epoch  97/100: train_loss=0.000108

      epoch  98/100: train_loss=0.000110

      epoch  99/100: train_loss=0.000108

      epoch 100/100: train_loss=0.000109, val_loss=0.001207, IC=+0.0259

      best_ep=100, IC=+0.0259 (94.6s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001209

      epoch   2/100: train_loss=0.000756

      epoch   3/100: train_loss=0.000680

      epoch   4/100: train_loss=0.000634

      epoch   5/100: train_loss=0.000590, val_loss=0.000528, IC=+0.0073

      epoch   6/100: train_loss=0.000547

      epoch   7/100: train_loss=0.000507

      epoch   8/100: train_loss=0.000471

      epoch   9/100: train_loss=0.000433

      epoch  10/100: train_loss=0.000400, val_loss=0.000651, IC=-0.0127

      epoch  11/100: train_loss=0.000372

      epoch  12/100: train_loss=0.000345

      epoch  13/100: train_loss=0.000319

      epoch  14/100: train_loss=0.000298

      epoch  15/100: train_loss=0.000276, val_loss=0.000692, IC=+0.0108

      epoch  16/100: train_loss=0.000262

      epoch  17/100: train_loss=0.000246

      epoch  18/100: train_loss=0.000233

      epoch  19/100: train_loss=0.000224

      epoch  20/100: train_loss=0.000209, val_loss=0.000700, IC=+0.0416

      epoch  21/100: train_loss=0.000199

      epoch  22/100: train_loss=0.000189

      epoch  23/100: train_loss=0.000180

      epoch  24/100: train_loss=0.000174

      epoch  25/100: train_loss=0.000169, val_loss=0.000721, IC=+0.0502

      epoch  26/100: train_loss=0.000164

      epoch  27/100: train_loss=0.000162

      epoch  28/100: train_loss=0.000152

      epoch  29/100: train_loss=0.000148

      epoch  30/100: train_loss=0.000143, val_loss=0.000784, IC=+0.0522

      epoch  31/100: train_loss=0.000140

      epoch  32/100: train_loss=0.000138

      epoch  33/100: train_loss=0.000134

      epoch  34/100: train_loss=0.000130

      epoch  35/100: train_loss=0.000126, val_loss=0.000812, IC=+0.0427

      epoch  36/100: train_loss=0.000126

      epoch  37/100: train_loss=0.000122

      epoch  38/100: train_loss=0.000121

      epoch  39/100: train_loss=0.000118

      epoch  40/100: train_loss=0.000115, val_loss=0.000860, IC=+0.0236

      epoch  41/100: train_loss=0.000118

      epoch  42/100: train_loss=0.000116

      epoch  43/100: train_loss=0.000113

      epoch  44/100: train_loss=0.000110

      epoch  45/100: train_loss=0.000109, val_loss=0.000866, IC=+0.0015

      epoch  46/100: train_loss=0.000106

      epoch  47/100: train_loss=0.000106

      epoch  48/100: train_loss=0.000104

      epoch  49/100: train_loss=0.000103

      epoch  50/100: train_loss=0.000103, val_loss=0.000886, IC=+0.0129

      epoch  51/100: train_loss=0.000103

      epoch  52/100: train_loss=0.000102

      epoch  53/100: train_loss=0.000101

      epoch  54/100: train_loss=0.000100

      epoch  55/100: train_loss=0.000098, val_loss=0.000892, IC=+0.0091

      epoch  56/100: train_loss=0.000097

      epoch  57/100: train_loss=0.000097

      epoch  58/100: train_loss=0.000097

      epoch  59/100: train_loss=0.000096

      epoch  60/100: train_loss=0.000095, val_loss=0.000898, IC=+0.0104

      epoch  61/100: train_loss=0.000094

      epoch  62/100: train_loss=0.000094

      epoch  63/100: train_loss=0.000093

      epoch  64/100: train_loss=0.000092

      epoch  65/100: train_loss=0.000092, val_loss=0.000909, IC=-0.0013

      epoch  66/100: train_loss=0.000091

      epoch  67/100: train_loss=0.000092

      epoch  68/100: train_loss=0.000090

      epoch  69/100: train_loss=0.000090

      epoch  70/100: train_loss=0.000090, val_loss=0.000910, IC=+0.0051

      epoch  71/100: train_loss=0.000088

      epoch  72/100: train_loss=0.000089

      epoch  73/100: train_loss=0.000089

      epoch  74/100: train_loss=0.000089

      epoch  75/100: train_loss=0.000088, val_loss=0.000908, IC=+0.0121

      epoch  76/100: train_loss=0.000088

      epoch  77/100: train_loss=0.000088

      epoch  78/100: train_loss=0.000088

      epoch  79/100: train_loss=0.000087

      epoch  80/100: train_loss=0.000087, val_loss=0.000924, IC=+0.0052

      epoch  81/100: train_loss=0.000087

      epoch  82/100: train_loss=0.000086

      epoch  83/100: train_loss=0.000086

      epoch  84/100: train_loss=0.000086

      epoch  85/100: train_loss=0.000086, val_loss=0.000912, IC=+0.0083

      epoch  86/100: train_loss=0.000087

      epoch  87/100: train_loss=0.000085

      epoch  88/100: train_loss=0.000086

      epoch  89/100: train_loss=0.000085

      epoch  90/100: train_loss=0.000084, val_loss=0.000919, IC=+0.0030

      epoch  91/100: train_loss=0.000085

      epoch  92/100: train_loss=0.000085

      epoch  93/100: train_loss=0.000085

      epoch  94/100: train_loss=0.000085

      epoch  95/100: train_loss=0.000086, val_loss=0.000921, IC=+0.0031

      epoch  96/100: train_loss=0.000085

      epoch  97/100: train_loss=0.000085

      epoch  98/100: train_loss=0.000084

      epoch  99/100: train_loss=0.000085

      epoch 100/100: train_loss=0.000085, val_loss=0.000920, IC=+0.0031

      best_ep=30, IC=+0.0522 (110.6s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001364

      epoch   2/100: train_loss=0.000770

      epoch   3/100: train_loss=0.000692

      epoch   4/100: train_loss=0.000643

      epoch   5/100: train_loss=0.000610, val_loss=0.000379, IC=+0.0250

      epoch   6/100: train_loss=0.000572

      epoch   7/100: train_loss=0.000540

      epoch   8/100: train_loss=0.000506

      epoch   9/100: train_loss=0.000476

      epoch  10/100: train_loss=0.000441, val_loss=0.000469, IC=-0.0023

      epoch  11/100: train_loss=0.000409

      epoch  12/100: train_loss=0.000386

      epoch  13/100: train_loss=0.000356

      epoch  14/100: train_loss=0.000330

      epoch  15/100: train_loss=0.000307, val_loss=0.000570, IC=+0.0302

      epoch  16/100: train_loss=0.000281

      epoch  17/100: train_loss=0.000267

      epoch  18/100: train_loss=0.000250

      epoch  19/100: train_loss=0.000233

      epoch  20/100: train_loss=0.000217, val_loss=0.000601, IC=+0.0852

      epoch  21/100: train_loss=0.000211

      epoch  22/100: train_loss=0.000209

      epoch  23/100: train_loss=0.000188

      epoch  24/100: train_loss=0.000179

      epoch  25/100: train_loss=0.000171, val_loss=0.000684, IC=+0.0885

      epoch  26/100: train_loss=0.000165

      epoch  27/100: train_loss=0.000159

      epoch  28/100: train_loss=0.000154

      epoch  29/100: train_loss=0.000146

      epoch  30/100: train_loss=0.000144, val_loss=0.000745, IC=+0.0881

      epoch  31/100: train_loss=0.000140

      epoch  32/100: train_loss=0.000134

      epoch  33/100: train_loss=0.000131

      epoch  34/100: train_loss=0.000128

      epoch  35/100: train_loss=0.000125, val_loss=0.000807, IC=+0.0681

      epoch  36/100: train_loss=0.000122

      epoch  37/100: train_loss=0.000121

      epoch  38/100: train_loss=0.000122

      epoch  39/100: train_loss=0.000120

      epoch  40/100: train_loss=0.000115, val_loss=0.000833, IC=+0.0643

      epoch  41/100: train_loss=0.000114

      epoch  42/100: train_loss=0.000112

      epoch  43/100: train_loss=0.000108

      epoch  44/100: train_loss=0.000108

      epoch  45/100: train_loss=0.000107, val_loss=0.000877, IC=+0.0585

      epoch  46/100: train_loss=0.000105

      epoch  47/100: train_loss=0.000103

      epoch  48/100: train_loss=0.000104

      epoch  49/100: train_loss=0.000103

      epoch  50/100: train_loss=0.000101, val_loss=0.000882, IC=+0.0632

      epoch  51/100: train_loss=0.000100

      epoch  52/100: train_loss=0.000099

      epoch  53/100: train_loss=0.000097

      epoch  54/100: train_loss=0.000097

      epoch  55/100: train_loss=0.000095, val_loss=0.000907, IC=+0.0548

      epoch  56/100: train_loss=0.000096

      epoch  57/100: train_loss=0.000095

      epoch  58/100: train_loss=0.000095

      epoch  59/100: train_loss=0.000094

      epoch  60/100: train_loss=0.000092, val_loss=0.000920, IC=+0.0516

      epoch  61/100: train_loss=0.000092

      epoch  62/100: train_loss=0.000092

      epoch  63/100: train_loss=0.000090

      epoch  64/100: train_loss=0.000090

      epoch  65/100: train_loss=0.000090, val_loss=0.000933, IC=+0.0445

      epoch  66/100: train_loss=0.000090

      epoch  67/100: train_loss=0.000089

      epoch  68/100: train_loss=0.000088

      epoch  69/100: train_loss=0.000088

      epoch  70/100: train_loss=0.000086, val_loss=0.000932, IC=+0.0452

      epoch  71/100: train_loss=0.000088

      epoch  72/100: train_loss=0.000087

      epoch  73/100: train_loss=0.000086

      epoch  74/100: train_loss=0.000087

      epoch  75/100: train_loss=0.000086, val_loss=0.000946, IC=+0.0437

      epoch  76/100: train_loss=0.000086

      epoch  77/100: train_loss=0.000085

      epoch  78/100: train_loss=0.000086

      epoch  79/100: train_loss=0.000086

      epoch  80/100: train_loss=0.000084, val_loss=0.000942, IC=+0.0476

      epoch  81/100: train_loss=0.000085

      epoch  82/100: train_loss=0.000083

      epoch  83/100: train_loss=0.000084

      epoch  84/100: train_loss=0.000085

      epoch  85/100: train_loss=0.000084, val_loss=0.000952, IC=+0.0437

      epoch  86/100: train_loss=0.000084

      epoch  87/100: train_loss=0.000084

      epoch  88/100: train_loss=0.000084

      epoch  89/100: train_loss=0.000083

      epoch  90/100: train_loss=0.000084, val_loss=0.000959, IC=+0.0432

      epoch  91/100: train_loss=0.000083

      epoch  92/100: train_loss=0.000083

      epoch  93/100: train_loss=0.000082

      epoch  94/100: train_loss=0.000083

      epoch  95/100: train_loss=0.000082, val_loss=0.000954, IC=+0.0441

      epoch  96/100: train_loss=0.000083

      epoch  97/100: train_loss=0.000083

      epoch  98/100: train_loss=0.000083

      epoch  99/100: train_loss=0.000082

      epoch 100/100: train_loss=0.000083, val_loss=0.000953, IC=+0.0442

      best_ep=25, IC=+0.0885 (119.1s, 20 checkpoints)

  Fold 4: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001009

      epoch   2/100: train_loss=0.000615

      epoch   3/100: train_loss=0.000551

      epoch   4/100: train_loss=0.000506

      epoch   5/100: train_loss=0.000472, val_loss=0.001115, IC=-0.2052

      epoch   6/100: train_loss=0.000436

      epoch   7/100: train_loss=0.000400

      epoch   8/100: train_loss=0.000364

      epoch   9/100: train_loss=0.000332

      epoch  10/100: train_loss=0.000305, val_loss=0.001361, IC=-0.1459

      epoch  11/100: train_loss=0.000280

      epoch  12/100: train_loss=0.000259

      epoch  13/100: train_loss=0.000240

      epoch  14/100: train_loss=0.000220

      epoch  15/100: train_loss=0.000207, val_loss=0.001479, IC=-0.1340

      epoch  16/100: train_loss=0.000193

      epoch  17/100: train_loss=0.000180

      epoch  18/100: train_loss=0.000170

      epoch  19/100: train_loss=0.000160

      epoch  20/100: train_loss=0.000152, val_loss=0.001388, IC=-0.1001

      epoch  21/100: train_loss=0.000145

      epoch  22/100: train_loss=0.000141

      epoch  23/100: train_loss=0.000132

      epoch  24/100: train_loss=0.000129

      epoch  25/100: train_loss=0.000121, val_loss=0.001382, IC=-0.0801

      epoch  26/100: train_loss=0.000116

      epoch  27/100: train_loss=0.000112

      epoch  28/100: train_loss=0.000108

      epoch  29/100: train_loss=0.000105

      epoch  30/100: train_loss=0.000102, val_loss=0.001405, IC=-0.0639

      epoch  31/100: train_loss=0.000100

      epoch  32/100: train_loss=0.000098

      epoch  33/100: train_loss=0.000095

      epoch  34/100: train_loss=0.000093

      epoch  35/100: train_loss=0.000091, val_loss=0.001448, IC=-0.0690

      epoch  36/100: train_loss=0.000090

      epoch  37/100: train_loss=0.000088

      epoch  38/100: train_loss=0.000085

      epoch  39/100: train_loss=0.000084

      epoch  40/100: train_loss=0.000085, val_loss=0.001422, IC=-0.0648

      epoch  41/100: train_loss=0.000083

      epoch  42/100: train_loss=0.000081

      epoch  43/100: train_loss=0.000081

      epoch  44/100: train_loss=0.000079

      epoch  45/100: train_loss=0.000078, val_loss=0.001400, IC=-0.0504

      epoch  46/100: train_loss=0.000078

      epoch  47/100: train_loss=0.000077

      epoch  48/100: train_loss=0.000076

      epoch  49/100: train_loss=0.000076

      epoch  50/100: train_loss=0.000075, val_loss=0.001420, IC=-0.0465

      epoch  51/100: train_loss=0.000074

      epoch  52/100: train_loss=0.000074

      epoch  53/100: train_loss=0.000073

      epoch  54/100: train_loss=0.000072

      epoch  55/100: train_loss=0.000072, val_loss=0.001433, IC=-0.0570

      epoch  56/100: train_loss=0.000071

      epoch  57/100: train_loss=0.000071

      epoch  58/100: train_loss=0.000070

      epoch  59/100: train_loss=0.000070

      epoch  60/100: train_loss=0.000070, val_loss=0.001410, IC=-0.0437

      epoch  61/100: train_loss=0.000069

      epoch  62/100: train_loss=0.000068

      epoch  63/100: train_loss=0.000069

      epoch  64/100: train_loss=0.000067

      epoch  65/100: train_loss=0.000067, val_loss=0.001407, IC=-0.0503

      epoch  66/100: train_loss=0.000067

      epoch  67/100: train_loss=0.000067

      epoch  68/100: train_loss=0.000067

      epoch  69/100: train_loss=0.000067

      epoch  70/100: train_loss=0.000066, val_loss=0.001428, IC=-0.0589

      epoch  71/100: train_loss=0.000066

      epoch  72/100: train_loss=0.000065

      epoch  73/100: train_loss=0.000066

      epoch  74/100: train_loss=0.000065

      epoch  75/100: train_loss=0.000065, val_loss=0.001414, IC=-0.0551

      epoch  76/100: train_loss=0.000065

      epoch  77/100: train_loss=0.000065

      epoch  78/100: train_loss=0.000065

      epoch  79/100: train_loss=0.000064

      epoch  80/100: train_loss=0.000064, val_loss=0.001417, IC=-0.0552

      epoch  81/100: train_loss=0.000064

      epoch  82/100: train_loss=0.000064

      epoch  83/100: train_loss=0.000064

      epoch  84/100: train_loss=0.000064

      epoch  85/100: train_loss=0.000064, val_loss=0.001419, IC=-0.0542

      epoch  86/100: train_loss=0.000064

      epoch  87/100: train_loss=0.000063

      epoch  88/100: train_loss=0.000064

      epoch  89/100: train_loss=0.000064

      epoch  90/100: train_loss=0.000063, val_loss=0.001415, IC=-0.0538

      epoch  91/100: train_loss=0.000064

      epoch  92/100: train_loss=0.000063

      epoch  93/100: train_loss=0.000063

      epoch  94/100: train_loss=0.000063

      epoch  95/100: train_loss=0.000063, val_loss=0.001421, IC=-0.0535

      epoch  96/100: train_loss=0.000062

      epoch  97/100: train_loss=0.000063

      epoch  98/100: train_loss=0.000063

      epoch  99/100: train_loss=0.000064

      epoch 100/100: train_loss=0.000063, val_loss=0.001421, IC=-0.0536

      best_ep=60, IC=-0.0437 (136.2s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.003277

      epoch   2/100: train_loss=0.000830

      epoch   3/100: train_loss=0.000625

      epoch   4/100: train_loss=0.000557

      epoch   5/100: train_loss=0.000520, val_loss=0.000367, IC=+0.0535

      epoch   6/100: train_loss=0.000497

      epoch   7/100: train_loss=0.000478

      epoch   8/100: train_loss=0.000456

      epoch   9/100: train_loss=0.000440

      epoch  10/100: train_loss=0.000423, val_loss=0.000375, IC=+0.0869

      epoch  11/100: train_loss=0.000407

      epoch  12/100: train_loss=0.000392

      epoch  13/100: train_loss=0.000378

      epoch  14/100: train_loss=0.000359

      epoch  15/100: train_loss=0.000346, val_loss=0.000409, IC=+0.0886

      epoch  16/100: train_loss=0.000331

      epoch  17/100: train_loss=0.000319

      epoch  18/100: train_loss=0.000304

      epoch  19/100: train_loss=0.000291

      epoch  20/100: train_loss=0.000279, val_loss=0.000447, IC=+0.1154

      epoch  21/100: train_loss=0.000270

      epoch  22/100: train_loss=0.000258

      epoch  23/100: train_loss=0.000249

      epoch  24/100: train_loss=0.000238

      epoch  25/100: train_loss=0.000231, val_loss=0.000469, IC=+0.1288

      epoch  26/100: train_loss=0.000222

      epoch  27/100: train_loss=0.000217

      epoch  28/100: train_loss=0.000208

      epoch  29/100: train_loss=0.000200

      epoch  30/100: train_loss=0.000195, val_loss=0.000508, IC=+0.1396

      epoch  31/100: train_loss=0.000189

      epoch  32/100: train_loss=0.000182

      epoch  33/100: train_loss=0.000178

      epoch  34/100: train_loss=0.000172

      epoch  35/100: train_loss=0.000170, val_loss=0.000572, IC=+0.1260

      epoch  36/100: train_loss=0.000164

      epoch  37/100: train_loss=0.000161

      epoch  38/100: train_loss=0.000158

      epoch  39/100: train_loss=0.000153

      epoch  40/100: train_loss=0.000149, val_loss=0.000617, IC=+0.1110

      epoch  41/100: train_loss=0.000144

      epoch  42/100: train_loss=0.000143

      epoch  43/100: train_loss=0.000140

      epoch  44/100: train_loss=0.000135

      epoch  45/100: train_loss=0.000133, val_loss=0.000680, IC=+0.1021

      epoch  46/100: train_loss=0.000132

      epoch  47/100: train_loss=0.000128

      epoch  48/100: train_loss=0.000125

      epoch  49/100: train_loss=0.000122

      epoch  50/100: train_loss=0.000120, val_loss=0.000720, IC=+0.0947

      epoch  51/100: train_loss=0.000119

      epoch  52/100: train_loss=0.000117

      epoch  53/100: train_loss=0.000115

      epoch  54/100: train_loss=0.000113

      epoch  55/100: train_loss=0.000111, val_loss=0.000771, IC=+0.0845

      epoch  56/100: train_loss=0.000110

      epoch  57/100: train_loss=0.000108

      epoch  58/100: train_loss=0.000106

      epoch  59/100: train_loss=0.000104

      epoch  60/100: train_loss=0.000104, val_loss=0.000802, IC=+0.0805

      epoch  61/100: train_loss=0.000104

      epoch  62/100: train_loss=0.000102

      epoch  63/100: train_loss=0.000100

      epoch  64/100: train_loss=0.000100

      epoch  65/100: train_loss=0.000099, val_loss=0.000816, IC=+0.0785

      epoch  66/100: train_loss=0.000098

      epoch  67/100: train_loss=0.000097

      epoch  68/100: train_loss=0.000095

      epoch  69/100: train_loss=0.000095

      epoch  70/100: train_loss=0.000095, val_loss=0.000856, IC=+0.0727

      epoch  71/100: train_loss=0.000094

      epoch  72/100: train_loss=0.000094

      epoch  73/100: train_loss=0.000093

      epoch  74/100: train_loss=0.000092

      epoch  75/100: train_loss=0.000092, val_loss=0.000855, IC=+0.0731

      epoch  76/100: train_loss=0.000092

      epoch  77/100: train_loss=0.000091

      epoch  78/100: train_loss=0.000090

      epoch  79/100: train_loss=0.000090

      epoch  80/100: train_loss=0.000090, val_loss=0.000862, IC=+0.0739

      epoch  81/100: train_loss=0.000089

      epoch  82/100: train_loss=0.000089

      epoch  83/100: train_loss=0.000089

      epoch  84/100: train_loss=0.000089

      epoch  85/100: train_loss=0.000089, val_loss=0.000875, IC=+0.0714

      epoch  86/100: train_loss=0.000088

      epoch  87/100: train_loss=0.000088

      epoch  88/100: train_loss=0.000087

      epoch  89/100: train_loss=0.000088

      epoch  90/100: train_loss=0.000088, val_loss=0.000872, IC=+0.0713

      epoch  91/100: train_loss=0.000088

      epoch  92/100: train_loss=0.000087

      epoch  93/100: train_loss=0.000088

      epoch  94/100: train_loss=0.000087

      epoch  95/100: train_loss=0.000088, val_loss=0.000875, IC=+0.0704

      epoch  96/100: train_loss=0.000087

      epoch  97/100: train_loss=0.000088

      epoch  98/100: train_loss=0.000088

      epoch  99/100: train_loss=0.000087

      epoch 100/100: train_loss=0.000087, val_loss=0.000875, IC=+0.0699

      best_ep=30, IC=+0.1396 (135.4s, 20 checkpoints)

  Fold 6: creating sequences...

    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000970

      epoch   2/100: train_loss=0.000493

      epoch   3/100: train_loss=0.000419

      epoch   4/100: train_loss=0.000386

      epoch   5/100: train_loss=0.000362, val_loss=0.001148, IC=+0.0008

      epoch   6/100: train_loss=0.000343

      epoch   7/100: train_loss=0.000323

      epoch   8/100: train_loss=0.000307

      epoch   9/100: train_loss=0.000289

      epoch  10/100: train_loss=0.000271, val_loss=0.001239, IC=+0.0081

      epoch  11/100: train_loss=0.000254

      epoch  12/100: train_loss=0.000237

      epoch  13/100: train_loss=0.000222

      epoch  14/100: train_loss=0.000209

      epoch  15/100: train_loss=0.000194, val_loss=0.001303, IC=+0.0173

      epoch  16/100: train_loss=0.000180

      epoch  17/100: train_loss=0.000171

      epoch  18/100: train_loss=0.000162

      epoch  19/100: train_loss=0.000150

      epoch  20/100: train_loss=0.000142, val_loss=0.001395, IC=+0.0028

      epoch  21/100: train_loss=0.000133

      epoch  22/100: train_loss=0.000128

      epoch  23/100: train_loss=0.000118

      epoch  24/100: train_loss=0.000113

      epoch  25/100: train_loss=0.000108, val_loss=0.001413, IC=+0.0126

      epoch  26/100: train_loss=0.000104

      epoch  27/100: train_loss=0.000098

      epoch  28/100: train_loss=0.000094

      epoch  29/100: train_loss=0.000091

      epoch  30/100: train_loss=0.000089, val_loss=0.001399, IC=+0.0397

      epoch  31/100: train_loss=0.000087

      epoch  32/100: train_loss=0.000082

      epoch  33/100: train_loss=0.000081

      epoch  34/100: train_loss=0.000079

      epoch  35/100: train_loss=0.000079, val_loss=0.001411, IC=+0.0414

      epoch  36/100: train_loss=0.000079

      epoch  37/100: train_loss=0.000076

      epoch  38/100: train_loss=0.000073

      epoch  39/100: train_loss=0.000071

      epoch  40/100: train_loss=0.000069, val_loss=0.001420, IC=+0.0366

      epoch  41/100: train_loss=0.000069

      epoch  42/100: train_loss=0.000068

      epoch  43/100: train_loss=0.000065

      epoch  44/100: train_loss=0.000064

      epoch  45/100: train_loss=0.000064, val_loss=0.001397, IC=+0.0405

      epoch  46/100: train_loss=0.000063

      epoch  47/100: train_loss=0.000062

      epoch  48/100: train_loss=0.000062

      epoch  49/100: train_loss=0.000061

      epoch  50/100: train_loss=0.000060, val_loss=0.001432, IC=+0.0328

      epoch  51/100: train_loss=0.000060

      epoch  52/100: train_loss=0.000059

      epoch  53/100: train_loss=0.000059

      epoch  54/100: train_loss=0.000058

      epoch  55/100: train_loss=0.000058, val_loss=0.001401, IC=+0.0374

      epoch  56/100: train_loss=0.000057

      epoch  57/100: train_loss=0.000057

      epoch  58/100: train_loss=0.000056

      epoch  59/100: train_loss=0.000056

      epoch  60/100: train_loss=0.000056, val_loss=0.001418, IC=+0.0355

      epoch  61/100: train_loss=0.000055

      epoch  62/100: train_loss=0.000055

      epoch  63/100: train_loss=0.000054

      epoch  64/100: train_loss=0.000054

      epoch  65/100: train_loss=0.000054, val_loss=0.001424, IC=+0.0293

      epoch  66/100: train_loss=0.000054

      epoch  67/100: train_loss=0.000053

      epoch  68/100: train_loss=0.000054

      epoch  69/100: train_loss=0.000053

      epoch  70/100: train_loss=0.000053, val_loss=0.001422, IC=+0.0295

      epoch  71/100: train_loss=0.000052

      epoch  72/100: train_loss=0.000053

      epoch  73/100: train_loss=0.000052

      epoch  74/100: train_loss=0.000052

      epoch  75/100: train_loss=0.000052, val_loss=0.001407, IC=+0.0325

      epoch  76/100: train_loss=0.000052

      epoch  77/100: train_loss=0.000052

      epoch  78/100: train_loss=0.000051

      epoch  79/100: train_loss=0.000052

      epoch  80/100: train_loss=0.000051, val_loss=0.001402, IC=+0.0335

      epoch  81/100: train_loss=0.000051

      epoch  82/100: train_loss=0.000051

      epoch  83/100: train_loss=0.000051

      epoch  84/100: train_loss=0.000051

      epoch  85/100: train_loss=0.000051, val_loss=0.001402, IC=+0.0358

      epoch  86/100: train_loss=0.000051

      epoch  87/100: train_loss=0.000050

      epoch  88/100: train_loss=0.000051

      epoch  89/100: train_loss=0.000050

      epoch  90/100: train_loss=0.000051, val_loss=0.001401, IC=+0.0354

      epoch  91/100: train_loss=0.000050

      epoch  92/100: train_loss=0.000051

      epoch  93/100: train_loss=0.000051

      epoch  94/100: train_loss=0.000051

      epoch  95/100: train_loss=0.000050, val_loss=0.001399, IC=+0.0351

      epoch  96/100: train_loss=0.000050

      epoch  97/100: train_loss=0.000050

      epoch  98/100: train_loss=0.000050

      epoch  99/100: train_loss=0.000050

      epoch 100/100: train_loss=0.000050, val_loss=0.001399, IC=+0.0352

      best_ep=35, IC=+0.0414 (131.7s, 20 checkpoints)

  Fold 7: creating sequences...

    train=24,180 seq across 20 symbols
    val=4,740 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.003562

      epoch   2/100: train_loss=0.000876

      epoch   3/100: train_loss=0.000625

      epoch   4/100: train_loss=0.000541

      epoch   5/100: train_loss=0.000505, val_loss=0.000514, IC=-0.0166

      epoch   6/100: train_loss=0.000484

      epoch   7/100: train_loss=0.000465

      epoch   8/100: train_loss=0.000451

      epoch   9/100: train_loss=0.000433

      epoch  10/100: train_loss=0.000416, val_loss=0.000551, IC=-0.0193

      epoch  11/100: train_loss=0.000402

      epoch  12/100: train_loss=0.000390

      epoch  13/100: train_loss=0.000375

      epoch  14/100: train_loss=0.000360

      epoch  15/100: train_loss=0.000350, val_loss=0.000687, IC=-0.0947

      epoch  16/100: train_loss=0.000339

      epoch  17/100: train_loss=0.000326

      epoch  18/100: train_loss=0.000316

      epoch  19/100: train_loss=0.000306

      epoch  20/100: train_loss=0.000293, val_loss=0.000875, IC=-0.1258

      epoch  21/100: train_loss=0.000285

      epoch  22/100: train_loss=0.000274

      epoch  23/100: train_loss=0.000263

      epoch  24/100: train_loss=0.000256

      epoch  25/100: train_loss=0.000246, val_loss=0.000972, IC=-0.1351

      epoch  26/100: train_loss=0.000237

      epoch  27/100: train_loss=0.000228

      epoch  28/100: train_loss=0.000222

      epoch  29/100: train_loss=0.000213

      epoch  30/100: train_loss=0.000206, val_loss=0.000955, IC=-0.1264

      epoch  31/100: train_loss=0.000200

      epoch  32/100: train_loss=0.000194

      epoch  33/100: train_loss=0.000189

      epoch  34/100: train_loss=0.000182

      epoch  35/100: train_loss=0.000175, val_loss=0.000994, IC=-0.1284

      epoch  36/100: train_loss=0.000171

      epoch  37/100: train_loss=0.000163

      epoch  38/100: train_loss=0.000161

      epoch  39/100: train_loss=0.000156

      epoch  40/100: train_loss=0.000153, val_loss=0.001008, IC=-0.1466

      epoch  41/100: train_loss=0.000149

      epoch  42/100: train_loss=0.000144

      epoch  43/100: train_loss=0.000139

      epoch  44/100: train_loss=0.000138

      epoch  45/100: train_loss=0.000133, val_loss=0.001023, IC=-0.1411

      epoch  46/100: train_loss=0.000130

      epoch  47/100: train_loss=0.000127

      epoch  48/100: train_loss=0.000125

      epoch  49/100: train_loss=0.000123

      epoch  50/100: train_loss=0.000119, val_loss=0.001047, IC=-0.1553

      epoch  51/100: train_loss=0.000117

      epoch  52/100: train_loss=0.000117

      epoch  53/100: train_loss=0.000114

      epoch  54/100: train_loss=0.000111

      epoch  55/100: train_loss=0.000110, val_loss=0.001030, IC=-0.1532

      epoch  56/100: train_loss=0.000109

      epoch  57/100: train_loss=0.000107

      epoch  58/100: train_loss=0.000105

      epoch  59/100: train_loss=0.000104

      epoch  60/100: train_loss=0.000103, val_loss=0.001044, IC=-0.1544

      epoch  61/100: train_loss=0.000102

      epoch  62/100: train_loss=0.000101

      epoch  63/100: train_loss=0.000100

      epoch  64/100: train_loss=0.000099

      epoch  65/100: train_loss=0.000097, val_loss=0.001056, IC=-0.1675

      epoch  66/100: train_loss=0.000098

      epoch  67/100: train_loss=0.000096

      epoch  68/100: train_loss=0.000095

      epoch  69/100: train_loss=0.000095

      epoch  70/100: train_loss=0.000094, val_loss=0.001055, IC=-0.1697

      epoch  71/100: train_loss=0.000094

      epoch  72/100: train_loss=0.000094

      epoch  73/100: train_loss=0.000093

      epoch  74/100: train_loss=0.000092

      epoch  75/100: train_loss=0.000091, val_loss=0.001064, IC=-0.1720

      epoch  76/100: train_loss=0.000091

      epoch  77/100: train_loss=0.000090

      epoch  78/100: train_loss=0.000091

      epoch  79/100: train_loss=0.000090

      epoch  80/100: train_loss=0.000090, val_loss=0.001058, IC=-0.1703

      epoch  81/100: train_loss=0.000089

      epoch  82/100: train_loss=0.000089

      epoch  83/100: train_loss=0.000088

      epoch  84/100: train_loss=0.000088

      epoch  85/100: train_loss=0.000089, val_loss=0.001059, IC=-0.1738

      epoch  86/100: train_loss=0.000088

      epoch  87/100: train_loss=0.000088

      epoch  88/100: train_loss=0.000088

      epoch  89/100: train_loss=0.000088

      epoch  90/100: train_loss=0.000088, val_loss=0.001062, IC=-0.1731

      epoch  91/100: train_loss=0.000088

      epoch  92/100: train_loss=0.000087

      epoch  93/100: train_loss=0.000087

      epoch  94/100: train_loss=0.000088

      epoch  95/100: train_loss=0.000088, val_loss=0.001062, IC=-0.1731

      epoch  96/100: train_loss=0.000088

      epoch  97/100: train_loss=0.000087

      epoch  98/100: train_loss=0.000088

      epoch  99/100: train_loss=0.000087

      epoch 100/100: train_loss=0.000088, val_loss=0.001062, IC=-0.1726

      best_ep=5, IC=-0.0166 (137.7s, 20 checkpoints)

  lstm_h64: best_epoch=30, IC=+0.0199 (955.1s)

  Best: lstm_h64 @ epoch 30 (IC=+0.0199)
  Saved to ~/ml4t/public-dl-rerun/case_studies/fx_pairs/run_log/training/a802656900ee/diagnostics

shape: (60, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean   ┆ ic_t      ┆ training_ ┆ predicti │
│ ---       ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---       ┆ ---       ┆ hash      ┆ on_hash  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ i64       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 5         ┆ … ┆ -0.00389  ┆ -1.129863 ┆ 225e9d237 ┆ ea8b69c8 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 512       ┆ 6459     │
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 10        ┆ … ┆ -0.002709 ┆ -0.547034 ┆ 225e9d237 ┆ 486d60df │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 512       ┆ 8cd3     │
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 15        ┆ … ┆ -0.00273  ┆ -0.522709 ┆ 225e9d237 ┆ 62d3fed3 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 512       ┆ 3dbf     │
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 20        ┆ … ┆ -0.004447 ┆ -0.601744 ┆ 225e9d237 ┆ 2cdd3be1 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 512       ┆ dab2     │
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 25        ┆ … ┆ 0.005879  ┆ 0.743689  ┆ 225e9d237 ┆ 413eae56 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 512       ┆ da50     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 80        ┆ … ┆ -0.000241 ┆ -0.013254 ┆ ef01d12ba ┆ 61e54b1d │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 279       ┆ 4d01     │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 85        ┆ … ┆ -0.001118 ┆ -0.061855 ┆ ef01d12ba ┆ 8a8082ec │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 279       ┆ 58b4     │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 90        ┆ … ┆ -0.000601 ┆ -0.033122 ┆ ef01d12ba ┆ 95bbe7f9 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 279       ┆ 91c7     │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 95        ┆ … ┆ -0.000339 ┆ -0.018447 ┆ ef01d12ba ┆ 97c93a4e │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 279       ┆ 64a5     │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 100       ┆ … ┆ -0.000321 ┆ -0.017555 ┆ ef01d12ba ┆ 328dc612 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 279       ┆ 233c     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Verify checkpoint reload

Repeating the request validates the fitted-state digests and returns the same prediction
identities. The notebook never reconstructs another family from an empty cache path.

In [6]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("LSTM checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview sequence checkpoints remain outside official comparisons.")

Official prediction population: f39229f6bc28

## Key takeaways

- The LSTM, NLinear and TCN use the same sequence eligibility contract but keep separate model
  identities, so each is scored on the rows its own lookback leaves eligible.
- Gaps remove affected windows instead of being hidden by positional indexing.
- Stored weights reproduce every declared checkpoint without retraining.