# LSTM - FX Pairs

An LSTM carries a hidden state forward across the lookback window and updates it at each
observation, so what it can use from the history is not fixed in advance the way NLinear's
subtraction of the last level is, nor bounded by a receptive field the way TCN's dilated stack
is. It is the recurrent member of the three architectures this case study's `deep_learning` menu
declares. This notebook constructs only the LSTM request; comparisons with NLinear, TCN, TabM,
trees, and linear models are deferred to `12_model_analysis`, where the complete registered
population is available.

**Learning objectives**

- Resolve the LSTM's lookback, hidden size, depth, and checkpoint schedule before fitting.
- Use the shared gap-safe sequence eligibility instead of positional row windows.
- Prove weight reload and catalog handoff for every declared epoch.

**Book reference**: Chapter 13, Section 13.4

**Prerequisites**: `02_labels`, `03_financial_features`, and `04_model_based_features`.

In [1]:
"""Fit and catalog the published LSTM FX configuration."""

import json

import polars as pl
import torch

from case_studies.research import (
    ExecutionTier,
    declared_labels,
    open_study,
    plan_models,
    population_supersedes,
    sweep_labels,
)
from utils.modeling import load_configs
from utils.reproducibility import set_global_seeds

In [2]:
CASE_STUDY_ID = "fx_pairs"
PRIMARY_LABEL = ""
MAX_SYMBOLS = 0
MAX_FOLDS = 0
FORCE_RETRAIN = False
PREDICTION_SPLIT = "validation"
N_EPOCHS = 0
LOOKBACK = 0
BATCH_SIZE = 0
DEVICE = ""
SEED = 42
POPULATION_NAME = ""
SUPERSEDES_POPULATION: str = ""
# The tier is a parameter, not something inferred from whether a reduction happens to be set.
# Inferring it meant a run could be reduced and still open the case study's own artifacts in
# place, which is the production path; a reader under test then wrote where the published run
# writes. WORKSPACE is the other half: a preview has nowhere else to put its results.
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None

## Resolve one forecasting request

The shared runner derives fold boundaries from the finalized label timeline. A missing daily
observation invalidates every lookback window that crosses it, so validation coverage can be
smaller than the raw validation panel while still being exact.

In [3]:
set_global_seeds(SEED)
# The reductions are read before the study is opened, because which study to open is decided by
# the tier and the two have to agree: a preview that reduces nothing is a canonical run wearing
# the wrong tier, and a canonical run carrying reductions would publish a narrowed population
# under the canonical name.
REDUCTION_PARAMETERS = {
    "folds": list(range(MAX_FOLDS)) if MAX_FOLDS else None,
    "max_symbols": MAX_SYMBOLS or None,
}
reductions = {key: value for key, value in REDUCTION_PARAMETERS.items() if value is not None}
tier = ExecutionTier(EXECUTION_TIER)
if tier is ExecutionTier.PREVIEW and not reductions:
    raise ValueError("preview execution must declare at least one reduction")
if tier is ExecutionTier.CANONICAL and reductions:
    raise ValueError(f"canonical execution cannot carry reductions: {sorted(reductions)}")
study = open_study(CASE_STUDY_ID, execution_tier=tier, workspace=WORKSPACE or None)

# Which labels this notebook fits is a question for the training menus, not for the sweep list:
# `setup.yaml` says which labels the case study carries, a menu says what to fit for one of them,
# and a sweep label whose menu declares no `deep_learning:` section owes nothing here. The two
# agree in this case study today, so restating the sweep list produced the right answer by
# coincidence and would have kept producing it silently after a menu changed. The order stays
# `setup.yaml`'s rather than `declared_labels`' menu-file order because the population is named
# after its labels and hashed over its members as an ordered list, so re-ordering would give the
# published population a new identity and demand a supersedes for a run that fits the same models.
declared = declared_labels(study, "deep_learning")
labels = (
    [PRIMARY_LABEL]
    if PRIMARY_LABEL
    else [label for label in sweep_labels(study) if label in set(declared)]
)

# A run that fits fewer labels than the menus declare is not the canonical population, and the
# architecture is fixed below, so the label set is the only knob that narrows it. Such a run must
# publish under its own name rather than register a partial snapshot under the canonical one.
if set(labels) != set(declared) and not POPULATION_NAME:
    raise ValueError(
        f"this run fits {len(labels)} of the {len(declared)} declared labels, so it cannot "
        "publish the canonical population; pass POPULATION_NAME to give it its own"
    )

if PREDICTION_SPLIT != "validation":
    raise ValueError("model selection uses validation predictions; holdout runs start from a lock")
if FORCE_RETRAIN:
    raise ValueError("valid checkpoints are reloaded by identity; change the request to refit")

# An empty DEVICE resolves to what the machine has. The runners refuse "cuda" on a host without
# it rather than falling back silently - which is the right contract for a run whose results get
# registered - so a hardcoded "cuda" default made the notebook unrunnable for any reader without
# an NVIDIA card, and unrunnable on a CPU CI runner. Resolving here keeps the refusal for anyone
# who asks for "cuda" explicitly; the resolved value is printed with the rest of the numerics
# below, so a run never leaves it implicit.
device = DEVICE or ("cuda" if torch.cuda.is_available() else "cpu")
overrides = {
    "device": device,
    **({"n_epochs": N_EPOCHS} if N_EPOCHS else {}),
    **({"batch_size": BATCH_SIZE} if BATCH_SIZE else {}),
    **({"lookback": LOOKBACK} if LOOKBACK else {}),
}
ARCHITECTURE = "lstm_h64"
menu = {
    label: [
        config["config_name"]
        for config in load_configs(CASE_STUDY_ID, label, family="deep_learning")
    ]
    for label in labels
}
uncovered = {label: sorted(set(names) - {ARCHITECTURE}) for label, names in menu.items()}
for label, names in menu.items():
    if ARCHITECTURE not in names:
        raise RuntimeError(
            f"{ARCHITECTURE} is not in the configured deep_learning menu for {label}: {names}"
        )

requests = [
    study.model(
        family="deep_learning",
        label=label,
        config_name=ARCHITECTURE,
        execution_tier=tier,
        preview_reductions=reductions,
        overrides=overrides,
    )
    for label in labels
]
plan = plan_models(study, requests=requests)

# This notebook owes one architecture on every configured label. The rest of the family menu is
# named here rather than left implicit, because a population that is short a configured model is
# otherwise indistinguishable from a complete one.
configured = {(label, ARCHITECTURE) for label in labels}
planned = {(member.label, member.config_name) for member in plan.members}
if planned != configured:
    raise RuntimeError(
        f"the plan does not match this notebook's declared coverage; "
        f"missing {sorted(configured - planned)}, unexpected {sorted(planned - configured)}"
    )
specs = {member.label: json.loads(member.spec_json) for member in plan.members}
computations = {label: spec.get("computation", spec) for label, spec in specs.items()}
computation = computations[labels[0]]

print(f"Labels: {', '.join(labels)}")
print(f"Execution tier: {tier.value}")
print(f"Device: {computation['numerics']['device']}")
print(f"Lookback: {computation['preprocessing']['lookback']} consecutive daily observations")
for horizon, values in computations.items():
    print(f"Eligible validation rows, {horizon}: {values['expected_prediction_keys']['n_rows']:,}")
for horizon, names in uncovered.items():
    print(
        f"Configured deep_learning models this notebook does not run, {horizon}: {names or 'none'}"
    )

Labels: fwd_ret_1d, fwd_ret_5d, fwd_ret_21d
Execution tier: canonical
Device: cuda
Lookback: 60 consecutive daily observations
Eligible validation rows, fwd_ret_1d: 41,260
Eligible validation rows, fwd_ret_5d: 41,180
Eligible validation rows, fwd_ret_21d: 40,860
Configured deep_learning models this notebook does not run, fwd_ret_1d: ['nlinear', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_5d: ['nlinear', 'tcn']
Configured deep_learning models this notebook does not run, fwd_ret_21d: ['nlinear', 'tcn']

## Inspect identity-bearing settings

The model request records its architecture parameters, exact folds, expected prediction-key
digest, and every epoch that must remain reproducible from stored weights.

In [4]:
checkpoint_schedule = pl.DataFrame(computation["checkpoint_schedule"])
pl.DataFrame(
    {
        "label": list(computations),
        "architecture": [c["model"]["class"] for c in computations.values()],
        "gap_policy": [c["preprocessing"]["gap_policy"] for c in computations.values()],
        "validation_folds": [
            c["expected_prediction_keys"]["n_folds"] for c in computations.values()
        ],
        "key_digest": [c["expected_prediction_keys"]["digest"] for c in computations.values()],
    }
)
checkpoint_schedule

shape: (20, 2)
┌───────┬───────┐
│ kind  ┆ value │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ epoch ┆ 5     │
│ epoch ┆ 10    │
│ epoch ┆ 15    │
│ epoch ┆ 20    │
│ epoch ┆ 25    │
│ …     ┆ …     │
│ epoch ┆ 80    │
│ epoch ┆ 85    │
│ epoch ┆ 90    │
│ epoch ┆ 95    │
│ epoch ┆ 100   │
└───────┴───────┘

## Record the official population, then fit or reload the LSTM

The runner validates every fold separately before any checkpoint becomes downstream-selectable.
Checkpoint rank correlation is retained as a diagnostic and does not remove other epochs.

`SUPERSEDES_POPULATION` names the population hash this run replaces. A population is the set of
prediction identities it publishes, so anything that moves a training identity produces a
different population under the same name, and the registry refuses to write it without being
told which snapshot it supersedes. That lineage is the only record of which generation is which,
and what moved the identities here was a change to the family's own source file rather than to
anything the notebook declares.

`population_supersedes` decides whether the declared hash may be offered. It is offered when the
name already carries the generation this declaration produced, so a re-run resolves to the
population it published, and when the declaration names the generation in force, so a refit
publishes the next one. It is withheld everywhere else - on a reader's clean clone, where
`run_log/` is gitignored and the registry has no generation at all; under a caller's own
`POPULATION_NAME`; and in a preview, whose isolated registry holds nothing under this name.

In [5]:
if len(plan.expected_prediction_hashes) != checkpoint_schedule.height * len(labels):
    raise RuntimeError("the plan does not cover every declared epoch checkpoint on every label")
population_name = POPULATION_NAME or f"{CASE_STUDY_ID}:{'+'.join(labels)}:lstm_h64"
population = (
    plan.create_population(
        name=population_name,
        supersedes=population_supersedes(
            study, name=population_name, declared=SUPERSEDES_POPULATION
        ),
    )
    if tier is ExecutionTier.CANONICAL
    else None
)

execution = plan.run()
catalog = execution.catalog_rows.sort("label", "checkpoint_value")
if set(catalog.get_column("prediction_hash")) != set(plan.expected_prediction_hashes):
    raise RuntimeError("the published catalog differs from the population planned before fitting")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("partial LSTM checkpoints cannot pass to backtesting")
for label in labels:
    published = catalog.filter(pl.col("label") == label).get_column("checkpoint_value").to_list()
    if published != checkpoint_schedule["value"].to_list():
        raise RuntimeError(f"catalog checkpoints for {label} differ from the resolved request")

catalog.select(
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "complete",
    "ic_mean",
    "ic_t",
    "training_hash",
    "prediction_hash",
)

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=24,580 seq across 20 symbols
    val=5,140 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001511

      epoch   2/100: train_loss=0.000240

      epoch   3/100: train_loss=0.000098

      epoch   4/100: train_loss=0.000056

      epoch   5/100: train_loss=0.000049, val_loss=0.000046, IC=-0.0326

      epoch   6/100: train_loss=0.000041

      epoch   7/100: train_loss=0.000038

      epoch   8/100: train_loss=0.000039

      epoch   9/100: train_loss=0.000035

      epoch  10/100: train_loss=0.000034, val_loss=0.000034, IC=-0.0008

      epoch  11/100: train_loss=0.000035

      epoch  12/100: train_loss=0.000036

      epoch  13/100: train_loss=0.000031

      epoch  14/100: train_loss=0.000035

      epoch  15/100: train_loss=0.000035, val_loss=0.000034, IC=-0.0002

      epoch  16/100: train_loss=0.000031

      epoch  17/100: train_loss=0.000031

      epoch  18/100: train_loss=0.000031

      epoch  19/100: train_loss=0.000033

      epoch  20/100: train_loss=0.000034, val_loss=0.000033, IC=-0.0066

      epoch  21/100: train_loss=0.000032

      epoch  22/100: train_loss=0.000033

      epoch  23/100: train_loss=0.000033

      epoch  24/100: train_loss=0.000030

      epoch  25/100: train_loss=0.000030, val_loss=0.000031, IC=+0.0124

      epoch  26/100: train_loss=0.000030

      epoch  27/100: train_loss=0.000030

      epoch  28/100: train_loss=0.000031

      epoch  29/100: train_loss=0.000030

      epoch  30/100: train_loss=0.000029, val_loss=0.000030, IC=+0.0448

      epoch  31/100: train_loss=0.000028

      epoch  32/100: train_loss=0.000027

      epoch  33/100: train_loss=0.000027

      epoch  34/100: train_loss=0.000028

      epoch  35/100: train_loss=0.000035, val_loss=0.000033, IC=+0.0444

      epoch  36/100: train_loss=0.000034

      epoch  37/100: train_loss=0.000032

      epoch  38/100: train_loss=0.000031

      epoch  39/100: train_loss=0.000028

      epoch  40/100: train_loss=0.000032, val_loss=0.000031, IC=+0.0056

      epoch  41/100: train_loss=0.000032

      epoch  42/100: train_loss=0.000029

      epoch  43/100: train_loss=0.000030

      epoch  44/100: train_loss=0.000029

      epoch  45/100: train_loss=0.000029, val_loss=0.000031, IC=+0.0137

      epoch  46/100: train_loss=0.000032

      epoch  47/100: train_loss=0.000029

      epoch  48/100: train_loss=0.000031

      epoch  49/100: train_loss=0.000031

      epoch  50/100: train_loss=0.000033, val_loss=0.000031, IC=+0.0467

      epoch  51/100: train_loss=0.000030

      epoch  52/100: train_loss=0.000032

      epoch  53/100: train_loss=0.000030

      epoch  54/100: train_loss=0.000031

      epoch  55/100: train_loss=0.000031, val_loss=0.000031, IC=+0.0173

      epoch  56/100: train_loss=0.000028

      epoch  57/100: train_loss=0.000028

      epoch  58/100: train_loss=0.000028

      epoch  59/100: train_loss=0.000030

      epoch  60/100: train_loss=0.000034, val_loss=0.000031, IC=+0.0083

      epoch  61/100: train_loss=0.000040

      epoch  62/100: train_loss=0.000037

      epoch  63/100: train_loss=0.000032

      epoch  64/100: train_loss=0.000030

      epoch  65/100: train_loss=0.000033, val_loss=0.000030, IC=+0.0335

      epoch  66/100: train_loss=0.000031

      epoch  67/100: train_loss=0.000031

      epoch  68/100: train_loss=0.000038

      epoch  69/100: train_loss=0.000032

      epoch  70/100: train_loss=0.000029, val_loss=0.000031, IC=+0.0327

      epoch  71/100: train_loss=0.000029

      epoch  72/100: train_loss=0.000030

      epoch  73/100: train_loss=0.000038

      epoch  74/100: train_loss=0.000031

      epoch  75/100: train_loss=0.000029, val_loss=0.000030, IC=+0.0389

      epoch  76/100: train_loss=0.000027

      epoch  77/100: train_loss=0.000036

      epoch  78/100: train_loss=0.000029

      epoch  79/100: train_loss=0.000032

      epoch  80/100: train_loss=0.000027, val_loss=0.000031, IC=-0.0080

      epoch  81/100: train_loss=0.000027

      epoch  82/100: train_loss=0.000026

      epoch  83/100: train_loss=0.000027

      epoch  84/100: train_loss=0.000029

      epoch  85/100: train_loss=0.000031, val_loss=0.000030, IC=+0.0036

      epoch  86/100: train_loss=0.000026

      epoch  87/100: train_loss=0.000027

      epoch  88/100: train_loss=0.000027

      epoch  89/100: train_loss=0.000026

      epoch  90/100: train_loss=0.000028, val_loss=0.000030, IC=+0.0034

      epoch  91/100: train_loss=0.000027

      epoch  92/100: train_loss=0.000026

      epoch  93/100: train_loss=0.000027

      epoch  94/100: train_loss=0.000027

      epoch  95/100: train_loss=0.000026, val_loss=0.000030, IC=+0.0023

      epoch  96/100: train_loss=0.000034

      epoch  97/100: train_loss=0.000027

      epoch  98/100: train_loss=0.000027

      epoch  99/100: train_loss=0.000026

      epoch 100/100: train_loss=0.000026, val_loss=0.000030, IC=+0.0006

      best_ep=50, IC=+0.0467 (45.2s, 20 checkpoints)

  Fold 1: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.004857

      epoch   2/100: train_loss=0.000352

      epoch   3/100: train_loss=0.000127

      epoch   4/100: train_loss=0.000082

      epoch   5/100: train_loss=0.000059, val_loss=0.000079, IC=+0.0095

      epoch   6/100: train_loss=0.000053

      epoch   7/100: train_loss=0.000049

      epoch   8/100: train_loss=0.000049

      epoch   9/100: train_loss=0.000044

      epoch  10/100: train_loss=0.000040, val_loss=0.000071, IC=-0.0060

      epoch  11/100: train_loss=0.000039

      epoch  12/100: train_loss=0.000040

      epoch  13/100: train_loss=0.000044

      epoch  14/100: train_loss=0.000037

      epoch  15/100: train_loss=0.000034, val_loss=0.000065, IC=-0.0122

      epoch  16/100: train_loss=0.000033

      epoch  17/100: train_loss=0.000032

      epoch  18/100: train_loss=0.000031

      epoch  19/100: train_loss=0.000032

      epoch  20/100: train_loss=0.000033, val_loss=0.000063, IC=-0.0231

      epoch  21/100: train_loss=0.000031

      epoch  22/100: train_loss=0.000035

      epoch  23/100: train_loss=0.000032

      epoch  24/100: train_loss=0.000034

      epoch  25/100: train_loss=0.000033, val_loss=0.000065, IC=-0.0378

      epoch  26/100: train_loss=0.000029

      epoch  27/100: train_loss=0.000031

      epoch  28/100: train_loss=0.000029

      epoch  29/100: train_loss=0.000028

      epoch  30/100: train_loss=0.000027, val_loss=0.000056, IC=-0.0167

      epoch  31/100: train_loss=0.000026

      epoch  32/100: train_loss=0.000031

      epoch  33/100: train_loss=0.000029

      epoch  34/100: train_loss=0.000030

      epoch  35/100: train_loss=0.000030, val_loss=0.000054, IC=+0.0073

      epoch  36/100: train_loss=0.000028

      epoch  37/100: train_loss=0.000026

      epoch  38/100: train_loss=0.000026

      epoch  39/100: train_loss=0.000026

      epoch  40/100: train_loss=0.000032, val_loss=0.000052, IC=+0.0103

      epoch  41/100: train_loss=0.000031

      epoch  42/100: train_loss=0.000029

      epoch  43/100: train_loss=0.000027

      epoch  44/100: train_loss=0.000025

      epoch  45/100: train_loss=0.000025, val_loss=0.000052, IC=+0.0097

      epoch  46/100: train_loss=0.000027

      epoch  47/100: train_loss=0.000028

      epoch  48/100: train_loss=0.000027

      epoch  49/100: train_loss=0.000030

      epoch  50/100: train_loss=0.000031, val_loss=0.000053, IC=-0.0318

      epoch  51/100: train_loss=0.000027

      epoch  52/100: train_loss=0.000025

      epoch  53/100: train_loss=0.000025

      epoch  54/100: train_loss=0.000024

      epoch  55/100: train_loss=0.000028, val_loss=0.000051, IC=-0.0096

      epoch  56/100: train_loss=0.000028

      epoch  57/100: train_loss=0.000026

      epoch  58/100: train_loss=0.000024

      epoch  59/100: train_loss=0.000024

      epoch  60/100: train_loss=0.000024, val_loss=0.000051, IC=-0.0087

      epoch  61/100: train_loss=0.000026

      epoch  62/100: train_loss=0.000025

      epoch  63/100: train_loss=0.000026

      epoch  64/100: train_loss=0.000025

      epoch  65/100: train_loss=0.000024, val_loss=0.000050, IC=-0.0082

      epoch  66/100: train_loss=0.000025

      epoch  67/100: train_loss=0.000026

      epoch  68/100: train_loss=0.000026

      epoch  69/100: train_loss=0.000025

      epoch  70/100: train_loss=0.000024, val_loss=0.000051, IC=-0.0004

      epoch  71/100: train_loss=0.000026

      epoch  72/100: train_loss=0.000025

      epoch  73/100: train_loss=0.000032

      epoch  74/100: train_loss=0.000025

      epoch  75/100: train_loss=0.000028, val_loss=0.000057, IC=-0.0324

      epoch  76/100: train_loss=0.000024

      epoch  77/100: train_loss=0.000024

      epoch  78/100: train_loss=0.000025

      epoch  79/100: train_loss=0.000025

      epoch  80/100: train_loss=0.000024, val_loss=0.000052, IC=-0.0127

      epoch  81/100: train_loss=0.000024

      epoch  82/100: train_loss=0.000023

      epoch  83/100: train_loss=0.000023

      epoch  84/100: train_loss=0.000024

      epoch  85/100: train_loss=0.000023, val_loss=0.000053, IC=-0.0220

      epoch  86/100: train_loss=0.000024

      epoch  87/100: train_loss=0.000023

      epoch  88/100: train_loss=0.000023

      epoch  89/100: train_loss=0.000023

      epoch  90/100: train_loss=0.000023, val_loss=0.000051, IC=-0.0144

      epoch  91/100: train_loss=0.000024

      epoch  92/100: train_loss=0.000023

      epoch  93/100: train_loss=0.000023

      epoch  94/100: train_loss=0.000023

      epoch  95/100: train_loss=0.000023, val_loss=0.000051, IC=-0.0164

      epoch  96/100: train_loss=0.000024

      epoch  97/100: train_loss=0.000024

      epoch  98/100: train_loss=0.000023

      epoch  99/100: train_loss=0.000023

      epoch 100/100: train_loss=0.000023, val_loss=0.000051, IC=-0.0144

      best_ep=40, IC=+0.0103 (41.6s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000413

      epoch   2/100: train_loss=0.000101

      epoch   3/100: train_loss=0.000057

      epoch   4/100: train_loss=0.000047

      epoch   5/100: train_loss=0.000040, val_loss=0.000024, IC=-0.0128

      epoch   6/100: train_loss=0.000040

      epoch   7/100: train_loss=0.000041

      epoch   8/100: train_loss=0.000037

      epoch   9/100: train_loss=0.000035

      epoch  10/100: train_loss=0.000059, val_loss=0.000029, IC=+0.0064

      epoch  11/100: train_loss=0.000055

      epoch  12/100: train_loss=0.000044

      epoch  13/100: train_loss=0.000040

      epoch  14/100: train_loss=0.000035

      epoch  15/100: train_loss=0.000033, val_loss=0.000022, IC=+0.0026

      epoch  16/100: train_loss=0.000033

      epoch  17/100: train_loss=0.000032

      epoch  18/100: train_loss=0.000033

      epoch  19/100: train_loss=0.000034

      epoch  20/100: train_loss=0.000033, val_loss=0.000021, IC=-0.0178

      epoch  21/100: train_loss=0.000032

      epoch  22/100: train_loss=0.000036

      epoch  23/100: train_loss=0.000037

      epoch  24/100: train_loss=0.000039

      epoch  25/100: train_loss=0.000035, val_loss=0.000021, IC=-0.0093

      epoch  26/100: train_loss=0.000031

      epoch  27/100: train_loss=0.000032

      epoch  28/100: train_loss=0.000030

      epoch  29/100: train_loss=0.000030

      epoch  30/100: train_loss=0.000036, val_loss=0.000023, IC=+0.0010

      epoch  31/100: train_loss=0.000035

      epoch  32/100: train_loss=0.000039

      epoch  33/100: train_loss=0.000033

      epoch  34/100: train_loss=0.000031

      epoch  35/100: train_loss=0.000033, val_loss=0.000021, IC=+0.0073

      epoch  36/100: train_loss=0.000033

      epoch  37/100: train_loss=0.000033

      epoch  38/100: train_loss=0.000031

      epoch  39/100: train_loss=0.000032

      epoch  40/100: train_loss=0.000030, val_loss=0.000021, IC=-0.0162

      epoch  41/100: train_loss=0.000037

      epoch  42/100: train_loss=0.000033

      epoch  43/100: train_loss=0.000033

      epoch  44/100: train_loss=0.000042

      epoch  45/100: train_loss=0.000038, val_loss=0.000029, IC=+0.0137

      epoch  46/100: train_loss=0.000037

      epoch  47/100: train_loss=0.000039

      epoch  48/100: train_loss=0.000035

      epoch  49/100: train_loss=0.000037

      epoch  50/100: train_loss=0.000032, val_loss=0.000024, IC=+0.0148

      epoch  51/100: train_loss=0.000030

      epoch  52/100: train_loss=0.000031

      epoch  53/100: train_loss=0.000032

      epoch  54/100: train_loss=0.000032

      epoch  55/100: train_loss=0.000034, val_loss=0.000021, IC=+0.0110

      epoch  56/100: train_loss=0.000032

      epoch  57/100: train_loss=0.000033

      epoch  58/100: train_loss=0.000030

      epoch  59/100: train_loss=0.000038

      epoch  60/100: train_loss=0.000035, val_loss=0.000021, IC=+0.0328

      epoch  61/100: train_loss=0.000032

      epoch  62/100: train_loss=0.000031

      epoch  63/100: train_loss=0.000030

      epoch  64/100: train_loss=0.000032

      epoch  65/100: train_loss=0.000031, val_loss=0.000022, IC=-0.0040

      epoch  66/100: train_loss=0.000031

      epoch  67/100: train_loss=0.000030

      epoch  68/100: train_loss=0.000029

      epoch  69/100: train_loss=0.000030

      epoch  70/100: train_loss=0.000029, val_loss=0.000021, IC=+0.0063

      epoch  71/100: train_loss=0.000028

      epoch  72/100: train_loss=0.000029

      epoch  73/100: train_loss=0.000029

      epoch  74/100: train_loss=0.000029

      epoch  75/100: train_loss=0.000032, val_loss=0.000020, IC=-0.0001

      epoch  76/100: train_loss=0.000030

      epoch  77/100: train_loss=0.000030

      epoch  78/100: train_loss=0.000032

      epoch  79/100: train_loss=0.000032

      epoch  80/100: train_loss=0.000031, val_loss=0.000020, IC=-0.0075

      epoch  81/100: train_loss=0.000032

      epoch  82/100: train_loss=0.000031

      epoch  83/100: train_loss=0.000030

      epoch  84/100: train_loss=0.000029

      epoch  85/100: train_loss=0.000029, val_loss=0.000020, IC=-0.0033

      epoch  86/100: train_loss=0.000034

      epoch  87/100: train_loss=0.000029

      epoch  88/100: train_loss=0.000029

      epoch  89/100: train_loss=0.000028

      epoch  90/100: train_loss=0.000028, val_loss=0.000020, IC=-0.0038

      epoch  91/100: train_loss=0.000029

      epoch  92/100: train_loss=0.000028

      epoch  93/100: train_loss=0.000028

      epoch  94/100: train_loss=0.000031

      epoch  95/100: train_loss=0.000028, val_loss=0.000020, IC=+0.0029

      epoch  96/100: train_loss=0.000028

      epoch  97/100: train_loss=0.000029

      epoch  98/100: train_loss=0.000028

      epoch  99/100: train_loss=0.000030

      epoch 100/100: train_loss=0.000028, val_loss=0.000020, IC=+0.0024

      best_ep=60, IC=+0.0328 (43.2s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001392

      epoch   2/100: train_loss=0.000288

      epoch   3/100: train_loss=0.000105

      epoch   4/100: train_loss=0.000072

      epoch   5/100: train_loss=0.000056, val_loss=0.000061, IC=-0.0191

      epoch   6/100: train_loss=0.000049

      epoch   7/100: train_loss=0.000049

      epoch   8/100: train_loss=0.000045

      epoch   9/100: train_loss=0.000041

      epoch  10/100: train_loss=0.000041, val_loss=0.000051, IC=-0.0155

      epoch  11/100: train_loss=0.000046

      epoch  12/100: train_loss=0.000046

      epoch  13/100: train_loss=0.000044

      epoch  14/100: train_loss=0.000039

      epoch  15/100: train_loss=0.000040, val_loss=0.000047, IC=-0.0111

      epoch  16/100: train_loss=0.000044

      epoch  17/100: train_loss=0.000045

      epoch  18/100: train_loss=0.000047

      epoch  19/100: train_loss=0.000044

      epoch  20/100: train_loss=0.000042, val_loss=0.000056, IC=-0.0040

      epoch  21/100: train_loss=0.000043

      epoch  22/100: train_loss=0.000040

      epoch  23/100: train_loss=0.000038

      epoch  24/100: train_loss=0.000035

      epoch  25/100: train_loss=0.000033, val_loss=0.000041, IC=-0.0157

      epoch  26/100: train_loss=0.000035

      epoch  27/100: train_loss=0.000035

      epoch  28/100: train_loss=0.000034

      epoch  29/100: train_loss=0.000035

      epoch  30/100: train_loss=0.000035, val_loss=0.000043, IC=-0.0293

      epoch  31/100: train_loss=0.000034

      epoch  32/100: train_loss=0.000034

      epoch  33/100: train_loss=0.000033

      epoch  34/100: train_loss=0.000033

      epoch  35/100: train_loss=0.000040, val_loss=0.000046, IC=+0.0044

      epoch  36/100: train_loss=0.000039

      epoch  37/100: train_loss=0.000039

      epoch  38/100: train_loss=0.000036

      epoch  39/100: train_loss=0.000035

      epoch  40/100: train_loss=0.000034, val_loss=0.000044, IC=-0.0363

      epoch  41/100: train_loss=0.000035

      epoch  42/100: train_loss=0.000035

      epoch  43/100: train_loss=0.000035

      epoch  44/100: train_loss=0.000038

      epoch  45/100: train_loss=0.000038, val_loss=0.000041, IC=-0.0357

      epoch  46/100: train_loss=0.000037

      epoch  47/100: train_loss=0.000035

      epoch  48/100: train_loss=0.000034

      epoch  49/100: train_loss=0.000032

      epoch  50/100: train_loss=0.000034, val_loss=0.000041, IC=-0.0171

      epoch  51/100: train_loss=0.000033

      epoch  52/100: train_loss=0.000033

      epoch  53/100: train_loss=0.000036

      epoch  54/100: train_loss=0.000036

      epoch  55/100: train_loss=0.000035, val_loss=0.000045, IC=-0.0208

      epoch  56/100: train_loss=0.000034

      epoch  57/100: train_loss=0.000035

      epoch  58/100: train_loss=0.000039

      epoch  59/100: train_loss=0.000035

      epoch  60/100: train_loss=0.000033, val_loss=0.000040, IC=-0.0225

      epoch  61/100: train_loss=0.000032

      epoch  62/100: train_loss=0.000032

      epoch  63/100: train_loss=0.000036

      epoch  64/100: train_loss=0.000037

      epoch  65/100: train_loss=0.000038, val_loss=0.000041, IC=-0.0349

      epoch  66/100: train_loss=0.000036

      epoch  67/100: train_loss=0.000033

      epoch  68/100: train_loss=0.000033

      epoch  69/100: train_loss=0.000031

      epoch  70/100: train_loss=0.000041, val_loss=0.000040, IC=-0.0225

      epoch  71/100: train_loss=0.000035

      epoch  72/100: train_loss=0.000033

      epoch  73/100: train_loss=0.000034

      epoch  74/100: train_loss=0.000032

      epoch  75/100: train_loss=0.000031, val_loss=0.000041, IC=-0.0146

      epoch  76/100: train_loss=0.000034

      epoch  77/100: train_loss=0.000032

      epoch  78/100: train_loss=0.000035

      epoch  79/100: train_loss=0.000033

      epoch  80/100: train_loss=0.000031, val_loss=0.000040, IC=-0.0115

      epoch  81/100: train_loss=0.000031

      epoch  82/100: train_loss=0.000031

      epoch  83/100: train_loss=0.000031

      epoch  84/100: train_loss=0.000037

      epoch  85/100: train_loss=0.000031, val_loss=0.000041, IC=-0.0051

      epoch  86/100: train_loss=0.000031

      epoch  87/100: train_loss=0.000031

      epoch  88/100: train_loss=0.000032

      epoch  89/100: train_loss=0.000031

      epoch  90/100: train_loss=0.000034, val_loss=0.000040, IC=-0.0174

      epoch  91/100: train_loss=0.000031

      epoch  92/100: train_loss=0.000037

      epoch  93/100: train_loss=0.000042

      epoch  94/100: train_loss=0.000032

      epoch  95/100: train_loss=0.000032, val_loss=0.000040, IC=-0.0158

      epoch  96/100: train_loss=0.000031

      epoch  97/100: train_loss=0.000031

      epoch  98/100: train_loss=0.000034

      epoch  99/100: train_loss=0.000036

      epoch 100/100: train_loss=0.000033, val_loss=0.000040, IC=-0.0165

      best_ep=35, IC=+0.0044 (44.2s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000909

      epoch   2/100: train_loss=0.000175

      epoch   3/100: train_loss=0.000080

      epoch   4/100: train_loss=0.000061

      epoch   5/100: train_loss=0.000058, val_loss=0.000025, IC=-0.0073

      epoch   6/100: train_loss=0.000055

      epoch   7/100: train_loss=0.000052

      epoch   8/100: train_loss=0.000049

      epoch   9/100: train_loss=0.000053

      epoch  10/100: train_loss=0.000050, val_loss=0.000021, IC=+0.0044

      epoch  11/100: train_loss=0.000051

      epoch  12/100: train_loss=0.000047

      epoch  13/100: train_loss=0.000046

      epoch  14/100: train_loss=0.000046

      epoch  15/100: train_loss=0.000047, val_loss=0.000023, IC=-0.0087

      epoch  16/100: train_loss=0.000048

      epoch  17/100: train_loss=0.000046

      epoch  18/100: train_loss=0.000052

      epoch  19/100: train_loss=0.000048

      epoch  20/100: train_loss=0.000049, val_loss=0.000020, IC=-0.0373

      epoch  21/100: train_loss=0.000047

      epoch  22/100: train_loss=0.000047

      epoch  23/100: train_loss=0.000050

      epoch  24/100: train_loss=0.000048

      epoch  25/100: train_loss=0.000049, val_loss=0.000021, IC=+0.0193

      epoch  26/100: train_loss=0.000052

      epoch  27/100: train_loss=0.000045

      epoch  28/100: train_loss=0.000042

      epoch  29/100: train_loss=0.000042

      epoch  30/100: train_loss=0.000043, val_loss=0.000019, IC=-0.0022

      epoch  31/100: train_loss=0.000042

      epoch  32/100: train_loss=0.000042

      epoch  33/100: train_loss=0.000043

      epoch  34/100: train_loss=0.000046

      epoch  35/100: train_loss=0.000051, val_loss=0.000036, IC=-0.0114

      epoch  36/100: train_loss=0.000050

      epoch  37/100: train_loss=0.000055

      epoch  38/100: train_loss=0.000050

      epoch  39/100: train_loss=0.000052

      epoch  40/100: train_loss=0.000051, val_loss=0.000022, IC=-0.0189

      epoch  41/100: train_loss=0.000044

      epoch  42/100: train_loss=0.000043

      epoch  43/100: train_loss=0.000044

      epoch  44/100: train_loss=0.000043

      epoch  45/100: train_loss=0.000043, val_loss=0.000019, IC=+0.0015

      epoch  46/100: train_loss=0.000043

      epoch  47/100: train_loss=0.000041

      epoch  48/100: train_loss=0.000040

      epoch  49/100: train_loss=0.000045

      epoch  50/100: train_loss=0.000051, val_loss=0.000020, IC=-0.0211

      epoch  51/100: train_loss=0.000045

      epoch  52/100: train_loss=0.000041

      epoch  53/100: train_loss=0.000044

      epoch  54/100: train_loss=0.000042

      epoch  55/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0351

      epoch  56/100: train_loss=0.000041

      epoch  57/100: train_loss=0.000041

      epoch  58/100: train_loss=0.000040

      epoch  59/100: train_loss=0.000039

      epoch  60/100: train_loss=0.000041, val_loss=0.000018, IC=+0.0163

      epoch  61/100: train_loss=0.000039

      epoch  62/100: train_loss=0.000039

      epoch  63/100: train_loss=0.000038

      epoch  64/100: train_loss=0.000039

      epoch  65/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0185

      epoch  66/100: train_loss=0.000040

      epoch  67/100: train_loss=0.000038

      epoch  68/100: train_loss=0.000038

      epoch  69/100: train_loss=0.000043

      epoch  70/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0145

      epoch  71/100: train_loss=0.000040

      epoch  72/100: train_loss=0.000038

      epoch  73/100: train_loss=0.000040

      epoch  74/100: train_loss=0.000038

      epoch  75/100: train_loss=0.000040, val_loss=0.000018, IC=-0.0005

      epoch  76/100: train_loss=0.000040

      epoch  77/100: train_loss=0.000043

      epoch  78/100: train_loss=0.000042

      epoch  79/100: train_loss=0.000039

      epoch  80/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0191

      epoch  81/100: train_loss=0.000039

      epoch  82/100: train_loss=0.000038

      epoch  83/100: train_loss=0.000039

      epoch  84/100: train_loss=0.000040

      epoch  85/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0131

      epoch  86/100: train_loss=0.000039

      epoch  87/100: train_loss=0.000044

      epoch  88/100: train_loss=0.000039

      epoch  89/100: train_loss=0.000038

      epoch  90/100: train_loss=0.000039, val_loss=0.000018, IC=-0.0223

      epoch  91/100: train_loss=0.000039

      epoch  92/100: train_loss=0.000043

      epoch  93/100: train_loss=0.000039

      epoch  94/100: train_loss=0.000039

      epoch  95/100: train_loss=0.000040, val_loss=0.000018, IC=-0.0218

      epoch  96/100: train_loss=0.000038

      epoch  97/100: train_loss=0.000039

      epoch  98/100: train_loss=0.000038

      epoch  99/100: train_loss=0.000038

      epoch 100/100: train_loss=0.000038, val_loss=0.000018, IC=-0.0212

      best_ep=25, IC=+0.0193 (53.9s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,580 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000530

      epoch   2/100: train_loss=0.000151

      epoch   3/100: train_loss=0.000098

      epoch   4/100: train_loss=0.000074

      epoch   5/100: train_loss=0.000063, val_loss=0.000039, IC=+0.0150

      epoch   6/100: train_loss=0.000059

      epoch   7/100: train_loss=0.000055

      epoch   8/100: train_loss=0.000054

      epoch   9/100: train_loss=0.000053

      epoch  10/100: train_loss=0.000051, val_loss=0.000033, IC=+0.0116

      epoch  11/100: train_loss=0.000051

      epoch  12/100: train_loss=0.000048

      epoch  13/100: train_loss=0.000051

      epoch  14/100: train_loss=0.000047

      epoch  15/100: train_loss=0.000045, val_loss=0.000028, IC=+0.0078

      epoch  16/100: train_loss=0.000044

      epoch  17/100: train_loss=0.000044

      epoch  18/100: train_loss=0.000045

      epoch  19/100: train_loss=0.000044

      epoch  20/100: train_loss=0.000048, val_loss=0.000030, IC=+0.0159

      epoch  21/100: train_loss=0.000051

      epoch  22/100: train_loss=0.000055

      epoch  23/100: train_loss=0.000050

      epoch  24/100: train_loss=0.000051

      epoch  25/100: train_loss=0.000051, val_loss=0.000029, IC=+0.0416

      epoch  26/100: train_loss=0.000049

      epoch  27/100: train_loss=0.000047

      epoch  28/100: train_loss=0.000047

      epoch  29/100: train_loss=0.000048

      epoch  30/100: train_loss=0.000049, val_loss=0.000025, IC=+0.0510

      epoch  31/100: train_loss=0.000050

      epoch  32/100: train_loss=0.000057

      epoch  33/100: train_loss=0.000062

      epoch  34/100: train_loss=0.000062

      epoch  35/100: train_loss=0.000055, val_loss=0.000032, IC=+0.0027

      epoch  36/100: train_loss=0.000058

      epoch  37/100: train_loss=0.000057

      epoch  38/100: train_loss=0.000049

      epoch  39/100: train_loss=0.000045

      epoch  40/100: train_loss=0.000043, val_loss=0.000024, IC=+0.0233

      epoch  41/100: train_loss=0.000042

      epoch  42/100: train_loss=0.000047

      epoch  43/100: train_loss=0.000051

      epoch  44/100: train_loss=0.000049

      epoch  45/100: train_loss=0.000043, val_loss=0.000025, IC=+0.0044

      epoch  46/100: train_loss=0.000046

      epoch  47/100: train_loss=0.000045

      epoch  48/100: train_loss=0.000046

      epoch  49/100: train_loss=0.000044

      epoch  50/100: train_loss=0.000043, val_loss=0.000026, IC=+0.0103

      epoch  51/100: train_loss=0.000044

      epoch  52/100: train_loss=0.000045

      epoch  53/100: train_loss=0.000045

      epoch  54/100: train_loss=0.000043

      epoch  55/100: train_loss=0.000042, val_loss=0.000024, IC=+0.0190

      epoch  56/100: train_loss=0.000042

      epoch  57/100: train_loss=0.000046

      epoch  58/100: train_loss=0.000050

      epoch  59/100: train_loss=0.000050

      epoch  60/100: train_loss=0.000042, val_loss=0.000026, IC=+0.0335

      epoch  61/100: train_loss=0.000046

      epoch  62/100: train_loss=0.000044

      epoch  63/100: train_loss=0.000043

      epoch  64/100: train_loss=0.000051

      epoch  65/100: train_loss=0.000048, val_loss=0.000029, IC=+0.0138

      epoch  66/100: train_loss=0.000045

      epoch  67/100: train_loss=0.000044

      epoch  68/100: train_loss=0.000043

      epoch  69/100: train_loss=0.000635

      epoch  70/100: train_loss=0.000106, val_loss=0.000083, IC=-0.0146

      epoch  71/100: train_loss=0.000071

      epoch  72/100: train_loss=0.000050

      epoch  73/100: train_loss=0.000045

      epoch  74/100: train_loss=0.000047

      epoch  75/100: train_loss=0.000042, val_loss=0.000027, IC=+0.0015

      epoch  76/100: train_loss=0.000044

      epoch  77/100: train_loss=0.000051

      epoch  78/100: train_loss=0.000043

      epoch  79/100: train_loss=0.000044

      epoch  80/100: train_loss=0.000054, val_loss=0.000025, IC=-0.0033

      epoch  81/100: train_loss=0.000041

      epoch  82/100: train_loss=0.000043

      epoch  83/100: train_loss=0.000044

      epoch  84/100: train_loss=0.000043

      epoch  85/100: train_loss=0.000042, val_loss=0.000025, IC=-0.0029

      epoch  86/100: train_loss=0.000041

      epoch  87/100: train_loss=0.000043

      epoch  88/100: train_loss=0.000041

      epoch  89/100: train_loss=0.000055

      epoch  90/100: train_loss=0.000041, val_loss=0.000025, IC=+0.0096

      epoch  91/100: train_loss=0.000042

      epoch  92/100: train_loss=0.000042

      epoch  93/100: train_loss=0.000044

      epoch  94/100: train_loss=0.000049

      epoch  95/100: train_loss=0.000043, val_loss=0.000025, IC=+0.0079

      epoch  96/100: train_loss=0.000041

      epoch  97/100: train_loss=0.000041

      epoch  98/100: train_loss=0.000044

      epoch  99/100: train_loss=0.000044

      epoch 100/100: train_loss=0.000041, val_loss=0.000024, IC=+0.0098

      best_ep=30, IC=+0.0510 (58.8s, 20 checkpoints)

  Fold 6: creating sequences...
    train=22,220 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000412

      epoch   2/100: train_loss=0.000109

      epoch   3/100: train_loss=0.000069

      epoch   4/100: train_loss=0.000058

      epoch   5/100: train_loss=0.000054, val_loss=0.000032, IC=-0.0301

      epoch   6/100: train_loss=0.000052

      epoch   7/100: train_loss=0.000050

      epoch   8/100: train_loss=0.000049

      epoch   9/100: train_loss=0.000049

      epoch  10/100: train_loss=0.000048, val_loss=0.000028, IC=-0.0068

      epoch  11/100: train_loss=0.000048

      epoch  12/100: train_loss=0.000047

      epoch  13/100: train_loss=0.000047

      epoch  14/100: train_loss=0.000047

      epoch  15/100: train_loss=0.000046, val_loss=0.000028, IC=-0.0153

      epoch  16/100: train_loss=0.000047

      epoch  17/100: train_loss=0.000047

      epoch  18/100: train_loss=0.000047

      epoch  19/100: train_loss=0.000046

      epoch  20/100: train_loss=0.000046, val_loss=0.000027, IC=+0.0034

      epoch  21/100: train_loss=0.000046

      epoch  22/100: train_loss=0.000046

      epoch  23/100: train_loss=0.000046

      epoch  24/100: train_loss=0.000045

      epoch  25/100: train_loss=0.000046, val_loss=0.000027, IC=-0.0089

      epoch  26/100: train_loss=0.000045

      epoch  27/100: train_loss=0.000045

      epoch  28/100: train_loss=0.000045

      epoch  29/100: train_loss=0.000045

      epoch  30/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0020

      epoch  31/100: train_loss=0.000045

      epoch  32/100: train_loss=0.000045

      epoch  33/100: train_loss=0.000045

      epoch  34/100: train_loss=0.000045

      epoch  35/100: train_loss=0.000045, val_loss=0.000027, IC=-0.0030

      epoch  36/100: train_loss=0.000045

      epoch  37/100: train_loss=0.000045

      epoch  38/100: train_loss=0.000045

      epoch  39/100: train_loss=0.000045

      epoch  40/100: train_loss=0.000045, val_loss=0.000028, IC=+0.0026

      epoch  41/100: train_loss=0.000044

      epoch  42/100: train_loss=0.000044

      epoch  43/100: train_loss=0.000044

      epoch  44/100: train_loss=0.000044

      epoch  45/100: train_loss=0.000044, val_loss=0.000027, IC=-0.0147

      epoch  46/100: train_loss=0.000044

      epoch  47/100: train_loss=0.000044

      epoch  48/100: train_loss=0.000044

      epoch  49/100: train_loss=0.000044

      epoch  50/100: train_loss=0.000044, val_loss=0.000027, IC=+0.0001

      epoch  51/100: train_loss=0.000044

      epoch  52/100: train_loss=0.000043

      epoch  53/100: train_loss=0.000044

      epoch  54/100: train_loss=0.000043

      epoch  55/100: train_loss=0.000043, val_loss=0.000028, IC=-0.0095

      epoch  56/100: train_loss=0.000043

      epoch  57/100: train_loss=0.000043

      epoch  58/100: train_loss=0.000043

      epoch  59/100: train_loss=0.000043

      epoch  60/100: train_loss=0.000043, val_loss=0.000028, IC=-0.0096

      epoch  61/100: train_loss=0.000043

      epoch  62/100: train_loss=0.000043

      epoch  63/100: train_loss=0.000043

      epoch  64/100: train_loss=0.000043

      epoch  65/100: train_loss=0.000043, val_loss=0.000027, IC=-0.0139

      epoch  66/100: train_loss=0.000043

      epoch  67/100: train_loss=0.000043

      epoch  68/100: train_loss=0.000043

      epoch  69/100: train_loss=0.000043

      epoch  70/100: train_loss=0.000043, val_loss=0.000027, IC=-0.0084

      epoch  71/100: train_loss=0.000043

      epoch  72/100: train_loss=0.000042

      epoch  73/100: train_loss=0.000042

      epoch  74/100: train_loss=0.000043

      epoch  75/100: train_loss=0.000043, val_loss=0.000028, IC=-0.0078

      epoch  76/100: train_loss=0.000042

      epoch  77/100: train_loss=0.000043

      epoch  78/100: train_loss=0.000043

      epoch  79/100: train_loss=0.000043

      epoch  80/100: train_loss=0.000043, val_loss=0.000028, IC=-0.0089

      epoch  81/100: train_loss=0.000043

      epoch  82/100: train_loss=0.000042

      epoch  83/100: train_loss=0.000042

      epoch  84/100: train_loss=0.000042

      epoch  85/100: train_loss=0.000042, val_loss=0.000028, IC=-0.0114

      epoch  86/100: train_loss=0.000042

      epoch  87/100: train_loss=0.000042

      epoch  88/100: train_loss=0.000042

      epoch  89/100: train_loss=0.000043

      epoch  90/100: train_loss=0.000042, val_loss=0.000028, IC=-0.0101

      epoch  91/100: train_loss=0.000043

      epoch  92/100: train_loss=0.000042

      epoch  93/100: train_loss=0.000042

      epoch  94/100: train_loss=0.000042

      epoch  95/100: train_loss=0.000042, val_loss=0.000028, IC=-0.0082

      epoch  96/100: train_loss=0.000042

      epoch  97/100: train_loss=0.000042

      epoch  98/100: train_loss=0.000042

      epoch  99/100: train_loss=0.000042

      epoch 100/100: train_loss=0.000042, val_loss=0.000028, IC=-0.0085

      best_ep=20, IC=+0.0034 (51.7s, 20 checkpoints)

  Fold 7: creating sequences...
    train=17,060 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000453

      epoch   2/100: train_loss=0.000137

      epoch   3/100: train_loss=0.000082

      epoch   4/100: train_loss=0.000061

      epoch   5/100: train_loss=0.000054, val_loss=0.000067, IC=+0.0395

      epoch   6/100: train_loss=0.000053

      epoch   7/100: train_loss=0.000048

      epoch   8/100: train_loss=0.000047

      epoch   9/100: train_loss=0.000046

      epoch  10/100: train_loss=0.000045, val_loss=0.000061, IC=+0.0434

      epoch  11/100: train_loss=0.000044

      epoch  12/100: train_loss=0.000044

      epoch  13/100: train_loss=0.000043

      epoch  14/100: train_loss=0.000051

      epoch  15/100: train_loss=0.000047, val_loss=0.000060, IC=+0.0395

      epoch  16/100: train_loss=0.000043

      epoch  17/100: train_loss=0.000043

      epoch  18/100: train_loss=0.000042

      epoch  19/100: train_loss=0.000042

      epoch  20/100: train_loss=0.000042, val_loss=0.000060, IC=+0.0416

      epoch  21/100: train_loss=0.000042

      epoch  22/100: train_loss=0.000042

      epoch  23/100: train_loss=0.000042

      epoch  24/100: train_loss=0.000042

      epoch  25/100: train_loss=0.000041, val_loss=0.000060, IC=+0.0457

      epoch  26/100: train_loss=0.000042

      epoch  27/100: train_loss=0.000045

      epoch  28/100: train_loss=0.000041

      epoch  29/100: train_loss=0.000044

      epoch  30/100: train_loss=0.000041, val_loss=0.000060, IC=+0.0398

      epoch  31/100: train_loss=0.000041

      epoch  32/100: train_loss=0.000041

      epoch  33/100: train_loss=0.000041

      epoch  34/100: train_loss=0.000040

      epoch  35/100: train_loss=0.000041, val_loss=0.000060, IC=+0.0445

      epoch  36/100: train_loss=0.000041

      epoch  37/100: train_loss=0.000041

      epoch  38/100: train_loss=0.000040

      epoch  39/100: train_loss=0.000044

      epoch  40/100: train_loss=0.000041, val_loss=0.000061, IC=+0.0436

      epoch  41/100: train_loss=0.000040

      epoch  42/100: train_loss=0.000045

      epoch  43/100: train_loss=0.000040

      epoch  44/100: train_loss=0.000040

      epoch  45/100: train_loss=0.000040, val_loss=0.000060, IC=+0.0341

      epoch  46/100: train_loss=0.000044

      epoch  47/100: train_loss=0.000040

      epoch  48/100: train_loss=0.000040

      epoch  49/100: train_loss=0.000040

      epoch  50/100: train_loss=0.000040, val_loss=0.000060, IC=+0.0335

      epoch  51/100: train_loss=0.000040

      epoch  52/100: train_loss=0.000040

      epoch  53/100: train_loss=0.000040

      epoch  54/100: train_loss=0.000043

      epoch  55/100: train_loss=0.000040, val_loss=0.000060, IC=+0.0378

      epoch  56/100: train_loss=0.000040

      epoch  57/100: train_loss=0.000039

      epoch  58/100: train_loss=0.000043

      epoch  59/100: train_loss=0.000040

      epoch  60/100: train_loss=0.000040, val_loss=0.000060, IC=+0.0355

      epoch  61/100: train_loss=0.000040

      epoch  62/100: train_loss=0.000039

      epoch  63/100: train_loss=0.000042

      epoch  64/100: train_loss=0.000039

      epoch  65/100: train_loss=0.000039, val_loss=0.000060, IC=+0.0325

      epoch  66/100: train_loss=0.000039

      epoch  67/100: train_loss=0.000039

      epoch  68/100: train_loss=0.000039

      epoch  69/100: train_loss=0.000039

      epoch  70/100: train_loss=0.000040, val_loss=0.000060, IC=+0.0317

      epoch  71/100: train_loss=0.000039

      epoch  72/100: train_loss=0.000040

      epoch  73/100: train_loss=0.000039

      epoch  74/100: train_loss=0.000039

      epoch  75/100: train_loss=0.000039, val_loss=0.000060, IC=+0.0372

      epoch  76/100: train_loss=0.000043

      epoch  77/100: train_loss=0.000039

      epoch  78/100: train_loss=0.000039

      epoch  79/100: train_loss=0.000042

      epoch  80/100: train_loss=0.000039, val_loss=0.000060, IC=+0.0339

      epoch  81/100: train_loss=0.000042

      epoch  82/100: train_loss=0.000039

      epoch  83/100: train_loss=0.000039

      epoch  84/100: train_loss=0.000043

      epoch  85/100: train_loss=0.000039, val_loss=0.000061, IC=+0.0316

      epoch  86/100: train_loss=0.000044

      epoch  87/100: train_loss=0.000042

      epoch  88/100: train_loss=0.000039

      epoch  89/100: train_loss=0.000039

      epoch  90/100: train_loss=0.000039, val_loss=0.000061, IC=+0.0327

      epoch  91/100: train_loss=0.000039

      epoch  92/100: train_loss=0.000039

      epoch  93/100: train_loss=0.000039

      epoch  94/100: train_loss=0.000039

      epoch  95/100: train_loss=0.000039, val_loss=0.000061, IC=+0.0310

      epoch  96/100: train_loss=0.000043

      epoch  97/100: train_loss=0.000039

      epoch  98/100: train_loss=0.000039

      epoch  99/100: train_loss=0.000039

      epoch 100/100: train_loss=0.000039, val_loss=0.000061, IC=+0.0321

      best_ep=25, IC=+0.0457 (39.1s, 20 checkpoints)

  lstm_h64: best_epoch=35, IC=+0.0120 (377.9s)

  Best: lstm_h64 @ epoch 35 (IC=+0.0120)
  Saved to ~/ml4t/public-fx-lstm/case_studies/fx_pairs/run_log/training/1426ea6ecd07/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,060 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001769

      epoch   2/100: train_loss=0.000336

      epoch   3/100: train_loss=0.000198

      epoch   4/100: train_loss=0.000160

      epoch   5/100: train_loss=0.000146, val_loss=0.000140, IC=-0.0280

      epoch   6/100: train_loss=0.000140

      epoch   7/100: train_loss=0.000137

      epoch   8/100: train_loss=0.000134

      epoch   9/100: train_loss=0.000132

      epoch  10/100: train_loss=0.000130, val_loss=0.000136, IC=-0.0084

      epoch  11/100: train_loss=0.000128

      epoch  12/100: train_loss=0.000126

      epoch  13/100: train_loss=0.000125

      epoch  14/100: train_loss=0.000123

      epoch  15/100: train_loss=0.000122, val_loss=0.000139, IC=+0.0084

      epoch  16/100: train_loss=0.000121

      epoch  17/100: train_loss=0.000119

      epoch  18/100: train_loss=0.000118

      epoch  19/100: train_loss=0.000117

      epoch  20/100: train_loss=0.000116, val_loss=0.000143, IC=+0.0192

      epoch  21/100: train_loss=0.000115

      epoch  22/100: train_loss=0.000113

      epoch  23/100: train_loss=0.000113

      epoch  24/100: train_loss=0.000112

      epoch  25/100: train_loss=0.000110, val_loss=0.000150, IC=+0.0061

      epoch  26/100: train_loss=0.000110

      epoch  27/100: train_loss=0.000108

      epoch  28/100: train_loss=0.000108

      epoch  29/100: train_loss=0.000107

      epoch  30/100: train_loss=0.000106, val_loss=0.000152, IC=+0.0081

      epoch  31/100: train_loss=0.000106

      epoch  32/100: train_loss=0.000105

      epoch  33/100: train_loss=0.000104

      epoch  34/100: train_loss=0.000103

      epoch  35/100: train_loss=0.000102, val_loss=0.000155, IC=+0.0030

      epoch  36/100: train_loss=0.000103

      epoch  37/100: train_loss=0.000101

      epoch  38/100: train_loss=0.000101

      epoch  39/100: train_loss=0.000099

      epoch  40/100: train_loss=0.000099, val_loss=0.000159, IC=-0.0030

      epoch  41/100: train_loss=0.000098

      epoch  42/100: train_loss=0.000098

      epoch  43/100: train_loss=0.000096

      epoch  44/100: train_loss=0.000096

      epoch  45/100: train_loss=0.000096, val_loss=0.000166, IC=-0.0172

      epoch  46/100: train_loss=0.000095

      epoch  47/100: train_loss=0.000095

      epoch  48/100: train_loss=0.000094

      epoch  49/100: train_loss=0.000094

      epoch  50/100: train_loss=0.000093, val_loss=0.000168, IC=-0.0213

      epoch  51/100: train_loss=0.000092

      epoch  52/100: train_loss=0.000092

      epoch  53/100: train_loss=0.000091

      epoch  54/100: train_loss=0.000090

      epoch  55/100: train_loss=0.000090, val_loss=0.000173, IC=-0.0229

      epoch  56/100: train_loss=0.000090

      epoch  57/100: train_loss=0.000090

      epoch  58/100: train_loss=0.000089

      epoch  59/100: train_loss=0.000089

      epoch  60/100: train_loss=0.000088, val_loss=0.000176, IC=-0.0249

      epoch  61/100: train_loss=0.000088

      epoch  62/100: train_loss=0.000088

      epoch  63/100: train_loss=0.000087

      epoch  64/100: train_loss=0.000088

      epoch  65/100: train_loss=0.000087, val_loss=0.000179, IC=-0.0347

      epoch  66/100: train_loss=0.000086

      epoch  67/100: train_loss=0.000086

      epoch  68/100: train_loss=0.000086

      epoch  69/100: train_loss=0.000086

      epoch  70/100: train_loss=0.000086, val_loss=0.000181, IC=-0.0340

      epoch  71/100: train_loss=0.000085

      epoch  72/100: train_loss=0.000085

      epoch  73/100: train_loss=0.000085

      epoch  74/100: train_loss=0.000084

      epoch  75/100: train_loss=0.000084, val_loss=0.000185, IC=-0.0335

      epoch  76/100: train_loss=0.000084

      epoch  77/100: train_loss=0.000084

      epoch  78/100: train_loss=0.000084

      epoch  79/100: train_loss=0.000083

      epoch  80/100: train_loss=0.000084, val_loss=0.000186, IC=-0.0392

      epoch  81/100: train_loss=0.000084

      epoch  82/100: train_loss=0.000083

      epoch  83/100: train_loss=0.000083

      epoch  84/100: train_loss=0.000083

      epoch  85/100: train_loss=0.000083, val_loss=0.000186, IC=-0.0374

      epoch  86/100: train_loss=0.000083

      epoch  87/100: train_loss=0.000083

      epoch  88/100: train_loss=0.000083

      epoch  89/100: train_loss=0.000083

      epoch  90/100: train_loss=0.000083, val_loss=0.000186, IC=-0.0357

      epoch  91/100: train_loss=0.000082

      epoch  92/100: train_loss=0.000083

      epoch  93/100: train_loss=0.000083

      epoch  94/100: train_loss=0.000083

      epoch  95/100: train_loss=0.000082, val_loss=0.000186, IC=-0.0370

      epoch  96/100: train_loss=0.000083

      epoch  97/100: train_loss=0.000083

      epoch  98/100: train_loss=0.000082

      epoch  99/100: train_loss=0.000082

      epoch 100/100: train_loss=0.000083, val_loss=0.000187, IC=-0.0358

      best_ep=20, IC=+0.0192 (61.5s, 20 checkpoints)

  Fold 1: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.005363

      epoch   2/100: train_loss=0.000532

      epoch   3/100: train_loss=0.000257

      epoch   4/100: train_loss=0.000179

      epoch   5/100: train_loss=0.000155, val_loss=0.000263, IC=+0.0302

      epoch   6/100: train_loss=0.000143

      epoch   7/100: train_loss=0.000137

      epoch   8/100: train_loss=0.000134

      epoch   9/100: train_loss=0.000130

      epoch  10/100: train_loss=0.000127, val_loss=0.000257, IC=+0.0094

      epoch  11/100: train_loss=0.000125

      epoch  12/100: train_loss=0.000123

      epoch  13/100: train_loss=0.000121

      epoch  14/100: train_loss=0.000120

      epoch  15/100: train_loss=0.000118, val_loss=0.000257, IC=+0.0043

      epoch  16/100: train_loss=0.000117

      epoch  17/100: train_loss=0.000115

      epoch  18/100: train_loss=0.000113

      epoch  19/100: train_loss=0.000113

      epoch  20/100: train_loss=0.000112, val_loss=0.000261, IC=-0.0051

      epoch  21/100: train_loss=0.000110

      epoch  22/100: train_loss=0.000110

      epoch  23/100: train_loss=0.000109

      epoch  24/100: train_loss=0.000107

      epoch  25/100: train_loss=0.000107, val_loss=0.000270, IC=-0.0156

      epoch  26/100: train_loss=0.000106

      epoch  27/100: train_loss=0.000105

      epoch  28/100: train_loss=0.000105

      epoch  29/100: train_loss=0.000104

      epoch  30/100: train_loss=0.000103, val_loss=0.000277, IC=-0.0176

      epoch  31/100: train_loss=0.000103

      epoch  32/100: train_loss=0.000102

      epoch  33/100: train_loss=0.000101

      epoch  34/100: train_loss=0.000101

      epoch  35/100: train_loss=0.000101, val_loss=0.000282, IC=-0.0214

      epoch  36/100: train_loss=0.000100

      epoch  37/100: train_loss=0.000099

      epoch  38/100: train_loss=0.000100

      epoch  39/100: train_loss=0.000099

      epoch  40/100: train_loss=0.000099, val_loss=0.000281, IC=-0.0148

      epoch  41/100: train_loss=0.000097

      epoch  42/100: train_loss=0.000097

      epoch  43/100: train_loss=0.000097

      epoch  44/100: train_loss=0.000096

      epoch  45/100: train_loss=0.000096, val_loss=0.000281, IC=-0.0120

      epoch  46/100: train_loss=0.000095

      epoch  47/100: train_loss=0.000095

      epoch  48/100: train_loss=0.000095

      epoch  49/100: train_loss=0.000094

      epoch  50/100: train_loss=0.000094, val_loss=0.000294, IC=-0.0229

      epoch  51/100: train_loss=0.000094

      epoch  52/100: train_loss=0.000094

      epoch  53/100: train_loss=0.000093

      epoch  54/100: train_loss=0.000093

      epoch  55/100: train_loss=0.000092, val_loss=0.000286, IC=-0.0125

      epoch  56/100: train_loss=0.000092

      epoch  57/100: train_loss=0.000091

      epoch  58/100: train_loss=0.000092

      epoch  59/100: train_loss=0.000091

      epoch  60/100: train_loss=0.000091, val_loss=0.000285, IC=-0.0067

      epoch  61/100: train_loss=0.000091

      epoch  62/100: train_loss=0.000091

      epoch  63/100: train_loss=0.000090

      epoch  64/100: train_loss=0.000089

      epoch  65/100: train_loss=0.000090, val_loss=0.000292, IC=-0.0104

      epoch  66/100: train_loss=0.000089

      epoch  67/100: train_loss=0.000090

      epoch  68/100: train_loss=0.000089

      epoch  69/100: train_loss=0.000089

      epoch  70/100: train_loss=0.000089, val_loss=0.000289, IC=-0.0075

      epoch  71/100: train_loss=0.000089

      epoch  72/100: train_loss=0.000089

      epoch  73/100: train_loss=0.000089

      epoch  74/100: train_loss=0.000088

      epoch  75/100: train_loss=0.000088, val_loss=0.000293, IC=-0.0082

      epoch  76/100: train_loss=0.000088

      epoch  77/100: train_loss=0.000088

      epoch  78/100: train_loss=0.000088

      epoch  79/100: train_loss=0.000088

      epoch  80/100: train_loss=0.000088, val_loss=0.000295, IC=-0.0084

      epoch  81/100: train_loss=0.000088

      epoch  82/100: train_loss=0.000087

      epoch  83/100: train_loss=0.000087

      epoch  84/100: train_loss=0.000087

      epoch  85/100: train_loss=0.000088, val_loss=0.000293, IC=-0.0067

      epoch  86/100: train_loss=0.000088

      epoch  87/100: train_loss=0.000087

      epoch  88/100: train_loss=0.000087

      epoch  89/100: train_loss=0.000087

      epoch  90/100: train_loss=0.000088, val_loss=0.000294, IC=-0.0070

      epoch  91/100: train_loss=0.000087

      epoch  92/100: train_loss=0.000087

      epoch  93/100: train_loss=0.000087

      epoch  94/100: train_loss=0.000087

      epoch  95/100: train_loss=0.000087, val_loss=0.000294, IC=-0.0066

      epoch  96/100: train_loss=0.000087

      epoch  97/100: train_loss=0.000087

      epoch  98/100: train_loss=0.000087

      epoch  99/100: train_loss=0.000087

      epoch 100/100: train_loss=0.000087, val_loss=0.000294, IC=-0.0064

      best_ep=5, IC=+0.0302 (58.8s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000569

      epoch   2/100: train_loss=0.000212

      epoch   3/100: train_loss=0.000170

      epoch   4/100: train_loss=0.000158

      epoch   5/100: train_loss=0.000152, val_loss=0.000092, IC=-0.0196

      epoch   6/100: train_loss=0.000149

      epoch   7/100: train_loss=0.000146

      epoch   8/100: train_loss=0.000143

      epoch   9/100: train_loss=0.000141

      epoch  10/100: train_loss=0.000138, val_loss=0.000091, IC=+0.0094

      epoch  11/100: train_loss=0.000136

      epoch  12/100: train_loss=0.000134

      epoch  13/100: train_loss=0.000132

      epoch  14/100: train_loss=0.000130

      epoch  15/100: train_loss=0.000126, val_loss=0.000093, IC=-0.0049

      epoch  16/100: train_loss=0.000124

      epoch  17/100: train_loss=0.000123

      epoch  18/100: train_loss=0.000121

      epoch  19/100: train_loss=0.000118

      epoch  20/100: train_loss=0.000117, val_loss=0.000095, IC=-0.0024

      epoch  21/100: train_loss=0.000115

      epoch  22/100: train_loss=0.000114

      epoch  23/100: train_loss=0.000112

      epoch  24/100: train_loss=0.000110

      epoch  25/100: train_loss=0.000108, val_loss=0.000097, IC=+0.0040

      epoch  26/100: train_loss=0.000107

      epoch  27/100: train_loss=0.000105

      epoch  28/100: train_loss=0.000104

      epoch  29/100: train_loss=0.000102

      epoch  30/100: train_loss=0.000101, val_loss=0.000101, IC=+0.0137

      epoch  31/100: train_loss=0.000101

      epoch  32/100: train_loss=0.000099

      epoch  33/100: train_loss=0.000098

      epoch  34/100: train_loss=0.000096

      epoch  35/100: train_loss=0.000095, val_loss=0.000105, IC=+0.0380

      epoch  36/100: train_loss=0.000095

      epoch  37/100: train_loss=0.000094

      epoch  38/100: train_loss=0.000091

      epoch  39/100: train_loss=0.000090

      epoch  40/100: train_loss=0.000090, val_loss=0.000106, IC=+0.0464

      epoch  41/100: train_loss=0.000089

      epoch  42/100: train_loss=0.000088

      epoch  43/100: train_loss=0.000086

      epoch  44/100: train_loss=0.000085

      epoch  45/100: train_loss=0.000085, val_loss=0.000110, IC=+0.0583

      epoch  46/100: train_loss=0.000084

      epoch  47/100: train_loss=0.000084

      epoch  48/100: train_loss=0.000083

      epoch  49/100: train_loss=0.000082

      epoch  50/100: train_loss=0.000081, val_loss=0.000113, IC=+0.0707

      epoch  51/100: train_loss=0.000081

      epoch  52/100: train_loss=0.000080

      epoch  53/100: train_loss=0.000080

      epoch  54/100: train_loss=0.000078

      epoch  55/100: train_loss=0.000078, val_loss=0.000118, IC=+0.0703

      epoch  56/100: train_loss=0.000077

      epoch  57/100: train_loss=0.000077

      epoch  58/100: train_loss=0.000077

      epoch  59/100: train_loss=0.000076

      epoch  60/100: train_loss=0.000076, val_loss=0.000119, IC=+0.0749

      epoch  61/100: train_loss=0.000075

      epoch  62/100: train_loss=0.000074

      epoch  63/100: train_loss=0.000074

      epoch  64/100: train_loss=0.000074

      epoch  65/100: train_loss=0.000074, val_loss=0.000124, IC=+0.0749

      epoch  66/100: train_loss=0.000073

      epoch  67/100: train_loss=0.000072

      epoch  68/100: train_loss=0.000073

      epoch  69/100: train_loss=0.000072

      epoch  70/100: train_loss=0.000072, val_loss=0.000126, IC=+0.0706

      epoch  71/100: train_loss=0.000072

      epoch  72/100: train_loss=0.000071

      epoch  73/100: train_loss=0.000071

      epoch  74/100: train_loss=0.000071

      epoch  75/100: train_loss=0.000071, val_loss=0.000127, IC=+0.0757

      epoch  76/100: train_loss=0.000070

      epoch  77/100: train_loss=0.000070

      epoch  78/100: train_loss=0.000069

      epoch  79/100: train_loss=0.000070

      epoch  80/100: train_loss=0.000070, val_loss=0.000129, IC=+0.0760

      epoch  81/100: train_loss=0.000069

      epoch  82/100: train_loss=0.000069

      epoch  83/100: train_loss=0.000070

      epoch  84/100: train_loss=0.000069

      epoch  85/100: train_loss=0.000068, val_loss=0.000129, IC=+0.0782

      epoch  86/100: train_loss=0.000069

      epoch  87/100: train_loss=0.000069

      epoch  88/100: train_loss=0.000069

      epoch  89/100: train_loss=0.000069

      epoch  90/100: train_loss=0.000068, val_loss=0.000130, IC=+0.0774

      epoch  91/100: train_loss=0.000069

      epoch  92/100: train_loss=0.000068

      epoch  93/100: train_loss=0.000068

      epoch  94/100: train_loss=0.000069

      epoch  95/100: train_loss=0.000069, val_loss=0.000131, IC=+0.0774

      epoch  96/100: train_loss=0.000068

      epoch  97/100: train_loss=0.000069

      epoch  98/100: train_loss=0.000069

      epoch  99/100: train_loss=0.000068

      epoch 100/100: train_loss=0.000068, val_loss=0.000131, IC=+0.0759

      best_ep=85, IC=+0.0782 (56.6s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001596

      epoch   2/100: train_loss=0.000364

      epoch   3/100: train_loss=0.000225

      epoch   4/100: train_loss=0.000186

      epoch   5/100: train_loss=0.000172, val_loss=0.000245, IC=-0.0806

      epoch   6/100: train_loss=0.000165

      epoch   7/100: train_loss=0.000162

      epoch   8/100: train_loss=0.000158

      epoch   9/100: train_loss=0.000156

      epoch  10/100: train_loss=0.000153, val_loss=0.000257, IC=-0.0963

      epoch  11/100: train_loss=0.000151

      epoch  12/100: train_loss=0.000148

      epoch  13/100: train_loss=0.000147

      epoch  14/100: train_loss=0.000145

      epoch  15/100: train_loss=0.000144, val_loss=0.000271, IC=-0.0781

      epoch  16/100: train_loss=0.000142

      epoch  17/100: train_loss=0.000140

      epoch  18/100: train_loss=0.000138

      epoch  19/100: train_loss=0.000137

      epoch  20/100: train_loss=0.000136, val_loss=0.000293, IC=-0.0739

      epoch  21/100: train_loss=0.000134

      epoch  22/100: train_loss=0.000133

      epoch  23/100: train_loss=0.000131

      epoch  24/100: train_loss=0.000130

      epoch  25/100: train_loss=0.000128, val_loss=0.000284, IC=-0.0444

      epoch  26/100: train_loss=0.000127

      epoch  27/100: train_loss=0.000127

      epoch  28/100: train_loss=0.000125

      epoch  29/100: train_loss=0.000124

      epoch  30/100: train_loss=0.000123, val_loss=0.000301, IC=-0.0422

      epoch  31/100: train_loss=0.000121

      epoch  32/100: train_loss=0.000119

      epoch  33/100: train_loss=0.000119

      epoch  34/100: train_loss=0.000118

      epoch  35/100: train_loss=0.000117, val_loss=0.000304, IC=-0.0383

      epoch  36/100: train_loss=0.000116

      epoch  37/100: train_loss=0.000115

      epoch  38/100: train_loss=0.000115

      epoch  39/100: train_loss=0.000113

      epoch  40/100: train_loss=0.000112, val_loss=0.000330, IC=-0.0367

      epoch  41/100: train_loss=0.000111

      epoch  42/100: train_loss=0.000110

      epoch  43/100: train_loss=0.000109

      epoch  44/100: train_loss=0.000108

      epoch  45/100: train_loss=0.000108, val_loss=0.000322, IC=-0.0376

      epoch  46/100: train_loss=0.000106

      epoch  47/100: train_loss=0.000106

      epoch  48/100: train_loss=0.000105

      epoch  49/100: train_loss=0.000105

      epoch  50/100: train_loss=0.000104, val_loss=0.000329, IC=-0.0369

      epoch  51/100: train_loss=0.000103

      epoch  52/100: train_loss=0.000103

      epoch  53/100: train_loss=0.000101

      epoch  54/100: train_loss=0.000101

      epoch  55/100: train_loss=0.000100, val_loss=0.000327, IC=-0.0278

      epoch  56/100: train_loss=0.000101

      epoch  57/100: train_loss=0.000100

      epoch  58/100: train_loss=0.000099

      epoch  59/100: train_loss=0.000098

      epoch  60/100: train_loss=0.000098, val_loss=0.000333, IC=-0.0302

      epoch  61/100: train_loss=0.000098

      epoch  62/100: train_loss=0.000097

      epoch  63/100: train_loss=0.000097

      epoch  64/100: train_loss=0.000097

      epoch  65/100: train_loss=0.000096, val_loss=0.000339, IC=-0.0325

      epoch  66/100: train_loss=0.000096

      epoch  67/100: train_loss=0.000095

      epoch  68/100: train_loss=0.000095

      epoch  69/100: train_loss=0.000095

      epoch  70/100: train_loss=0.000094, val_loss=0.000346, IC=-0.0346

      epoch  71/100: train_loss=0.000094

      epoch  72/100: train_loss=0.000094

      epoch  73/100: train_loss=0.000093

      epoch  74/100: train_loss=0.000093

      epoch  75/100: train_loss=0.000093, val_loss=0.000350, IC=-0.0403

      epoch  76/100: train_loss=0.000093

      epoch  77/100: train_loss=0.000093

      epoch  78/100: train_loss=0.000093

      epoch  79/100: train_loss=0.000092

      epoch  80/100: train_loss=0.000092, val_loss=0.000354, IC=-0.0420

      epoch  81/100: train_loss=0.000092

      epoch  82/100: train_loss=0.000092

      epoch  83/100: train_loss=0.000091

      epoch  84/100: train_loss=0.000091

      epoch  85/100: train_loss=0.000091, val_loss=0.000355, IC=-0.0432

      epoch  86/100: train_loss=0.000091

      epoch  87/100: train_loss=0.000092

      epoch  88/100: train_loss=0.000092

      epoch  89/100: train_loss=0.000092

      epoch  90/100: train_loss=0.000091, val_loss=0.000358, IC=-0.0441

      epoch  91/100: train_loss=0.000091

      epoch  92/100: train_loss=0.000091

      epoch  93/100: train_loss=0.000091

      epoch  94/100: train_loss=0.000091

      epoch  95/100: train_loss=0.000091, val_loss=0.000358, IC=-0.0437

      epoch  96/100: train_loss=0.000091

      epoch  97/100: train_loss=0.000091

      epoch  98/100: train_loss=0.000092

      epoch  99/100: train_loss=0.000091

      epoch 100/100: train_loss=0.000091, val_loss=0.000357, IC=-0.0440

      best_ep=55, IC=-0.0278 (56.1s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001117

      epoch   2/100: train_loss=0.000329

      epoch   3/100: train_loss=0.000236

      epoch   4/100: train_loss=0.000209

      epoch   5/100: train_loss=0.000198, val_loss=0.000096, IC=-0.0506

      epoch   6/100: train_loss=0.000192

      epoch   7/100: train_loss=0.000190

      epoch   8/100: train_loss=0.000186

      epoch   9/100: train_loss=0.000184

      epoch  10/100: train_loss=0.000181, val_loss=0.000094, IC=-0.0370

      epoch  11/100: train_loss=0.000178

      epoch  12/100: train_loss=0.000177

      epoch  13/100: train_loss=0.000175

      epoch  14/100: train_loss=0.000173

      epoch  15/100: train_loss=0.000171, val_loss=0.000094, IC=-0.0285

      epoch  16/100: train_loss=0.000170

      epoch  17/100: train_loss=0.000167

      epoch  18/100: train_loss=0.000166

      epoch  19/100: train_loss=0.000163

      epoch  20/100: train_loss=0.000162, val_loss=0.000096, IC=-0.0128

      epoch  21/100: train_loss=0.000160

      epoch  22/100: train_loss=0.000158

      epoch  23/100: train_loss=0.000156

      epoch  24/100: train_loss=0.000154

      epoch  25/100: train_loss=0.000153, val_loss=0.000103, IC=-0.0399

      epoch  26/100: train_loss=0.000151

      epoch  27/100: train_loss=0.000149

      epoch  28/100: train_loss=0.000147

      epoch  29/100: train_loss=0.000145

      epoch  30/100: train_loss=0.000144, val_loss=0.000107, IC=-0.0461

      epoch  31/100: train_loss=0.000141

      epoch  32/100: train_loss=0.000140

      epoch  33/100: train_loss=0.000139

      epoch  34/100: train_loss=0.000137

      epoch  35/100: train_loss=0.000135, val_loss=0.000112, IC=-0.0297

      epoch  36/100: train_loss=0.000134

      epoch  37/100: train_loss=0.000133

      epoch  38/100: train_loss=0.000131

      epoch  39/100: train_loss=0.000129

      epoch  40/100: train_loss=0.000127, val_loss=0.000118, IC=-0.0368

      epoch  41/100: train_loss=0.000126

      epoch  42/100: train_loss=0.000125

      epoch  43/100: train_loss=0.000124

      epoch  44/100: train_loss=0.000122

      epoch  45/100: train_loss=0.000120, val_loss=0.000122, IC=-0.0360

      epoch  46/100: train_loss=0.000120

      epoch  47/100: train_loss=0.000119

      epoch  48/100: train_loss=0.000119

      epoch  49/100: train_loss=0.000117

      epoch  50/100: train_loss=0.000117, val_loss=0.000120, IC=-0.0425

      epoch  51/100: train_loss=0.000115

      epoch  52/100: train_loss=0.000114

      epoch  53/100: train_loss=0.000113

      epoch  54/100: train_loss=0.000112

      epoch  55/100: train_loss=0.000112, val_loss=0.000124, IC=-0.0364

      epoch  56/100: train_loss=0.000111

      epoch  57/100: train_loss=0.000111

      epoch  58/100: train_loss=0.000110

      epoch  59/100: train_loss=0.000110

      epoch  60/100: train_loss=0.000109, val_loss=0.000126, IC=-0.0300

      epoch  61/100: train_loss=0.000107

      epoch  62/100: train_loss=0.000107

      epoch  63/100: train_loss=0.000107

      epoch  64/100: train_loss=0.000106

      epoch  65/100: train_loss=0.000106, val_loss=0.000127, IC=-0.0392

      epoch  66/100: train_loss=0.000106

      epoch  67/100: train_loss=0.000104

      epoch  68/100: train_loss=0.000105

      epoch  69/100: train_loss=0.000104

      epoch  70/100: train_loss=0.000103, val_loss=0.000129, IC=-0.0456

      epoch  71/100: train_loss=0.000103

      epoch  72/100: train_loss=0.000103

      epoch  73/100: train_loss=0.000102

      epoch  74/100: train_loss=0.000102

      epoch  75/100: train_loss=0.000101, val_loss=0.000132, IC=-0.0337

      epoch  76/100: train_loss=0.000102

      epoch  77/100: train_loss=0.000102

      epoch  78/100: train_loss=0.000101

      epoch  79/100: train_loss=0.000101

      epoch  80/100: train_loss=0.000101, val_loss=0.000134, IC=-0.0425

      epoch  81/100: train_loss=0.000100

      epoch  82/100: train_loss=0.000100

      epoch  83/100: train_loss=0.000100

      epoch  84/100: train_loss=0.000101

      epoch  85/100: train_loss=0.000100, val_loss=0.000135, IC=-0.0396

      epoch  86/100: train_loss=0.000100

      epoch  87/100: train_loss=0.000100

      epoch  88/100: train_loss=0.000100

      epoch  89/100: train_loss=0.000099

      epoch  90/100: train_loss=0.000099, val_loss=0.000136, IC=-0.0398

      epoch  91/100: train_loss=0.000099

      epoch  92/100: train_loss=0.000099

      epoch  93/100: train_loss=0.000100

      epoch  94/100: train_loss=0.000100

      epoch  95/100: train_loss=0.000100, val_loss=0.000136, IC=-0.0386

      epoch  96/100: train_loss=0.000099

      epoch  97/100: train_loss=0.000099

      epoch  98/100: train_loss=0.000100

      epoch  99/100: train_loss=0.000099

      epoch 100/100: train_loss=0.000099, val_loss=0.000136, IC=-0.0385

      best_ep=20, IC=-0.0128 (59.1s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,500 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000748

      epoch   2/100: train_loss=0.000302

      epoch   3/100: train_loss=0.000242

      epoch   4/100: train_loss=0.000219

      epoch   5/100: train_loss=0.000209, val_loss=0.000122, IC=+0.0853

      epoch   6/100: train_loss=0.000201

      epoch   7/100: train_loss=0.000197

      epoch   8/100: train_loss=0.000193

      epoch   9/100: train_loss=0.000190

      epoch  10/100: train_loss=0.000186, val_loss=0.000124, IC=+0.0482

      epoch  11/100: train_loss=0.000183

      epoch  12/100: train_loss=0.000180

      epoch  13/100: train_loss=0.000174

      epoch  14/100: train_loss=0.000172

      epoch  15/100: train_loss=0.000169, val_loss=0.000126, IC=+0.0362

      epoch  16/100: train_loss=0.000165

      epoch  17/100: train_loss=0.000162

      epoch  18/100: train_loss=0.000159

      epoch  19/100: train_loss=0.000158

      epoch  20/100: train_loss=0.000155, val_loss=0.000132, IC=+0.0440

      epoch  21/100: train_loss=0.000151

      epoch  22/100: train_loss=0.000150

      epoch  23/100: train_loss=0.000147

      epoch  24/100: train_loss=0.000145

      epoch  25/100: train_loss=0.000143, val_loss=0.000136, IC=+0.0374

      epoch  26/100: train_loss=0.000140

      epoch  27/100: train_loss=0.000139

      epoch  28/100: train_loss=0.000136

      epoch  29/100: train_loss=0.000134

      epoch  30/100: train_loss=0.000134, val_loss=0.000148, IC=+0.0393

      epoch  31/100: train_loss=0.000132

      epoch  32/100: train_loss=0.000129

      epoch  33/100: train_loss=0.000127

      epoch  34/100: train_loss=0.000127

      epoch  35/100: train_loss=0.000125, val_loss=0.000154, IC=+0.0260

      epoch  36/100: train_loss=0.000124

      epoch  37/100: train_loss=0.000122

      epoch  38/100: train_loss=0.000121

      epoch  39/100: train_loss=0.000120

      epoch  40/100: train_loss=0.000119, val_loss=0.000158, IC=+0.0180

      epoch  41/100: train_loss=0.000117

      epoch  42/100: train_loss=0.000116

      epoch  43/100: train_loss=0.000115

      epoch  44/100: train_loss=0.000113

      epoch  45/100: train_loss=0.000113, val_loss=0.000177, IC=+0.0190

      epoch  46/100: train_loss=0.000113

      epoch  47/100: train_loss=0.000111

      epoch  48/100: train_loss=0.000109

      epoch  49/100: train_loss=0.000108

      epoch  50/100: train_loss=0.000109, val_loss=0.000172, IC=+0.0138

      epoch  51/100: train_loss=0.000108

      epoch  52/100: train_loss=0.000105

      epoch  53/100: train_loss=0.000106

      epoch  54/100: train_loss=0.000105

      epoch  55/100: train_loss=0.000103, val_loss=0.000178, IC=+0.0086

      epoch  56/100: train_loss=0.000103

      epoch  57/100: train_loss=0.000104

      epoch  58/100: train_loss=0.000102

      epoch  59/100: train_loss=0.000101

      epoch  60/100: train_loss=0.000101, val_loss=0.000186, IC=+0.0118

      epoch  61/100: train_loss=0.000100

      epoch  62/100: train_loss=0.000100

      epoch  63/100: train_loss=0.000099

      epoch  64/100: train_loss=0.000100

      epoch  65/100: train_loss=0.000097, val_loss=0.000183, IC=+0.0083

      epoch  66/100: train_loss=0.000098

      epoch  67/100: train_loss=0.000097

      epoch  68/100: train_loss=0.000097

      epoch  69/100: train_loss=0.000096

      epoch  70/100: train_loss=0.000096, val_loss=0.000191, IC=+0.0047

      epoch  71/100: train_loss=0.000095

      epoch  72/100: train_loss=0.000096

      epoch  73/100: train_loss=0.000095

      epoch  74/100: train_loss=0.000095

      epoch  75/100: train_loss=0.000095, val_loss=0.000194, IC=+0.0015

      epoch  76/100: train_loss=0.000094

      epoch  77/100: train_loss=0.000093

      epoch  78/100: train_loss=0.000093

      epoch  79/100: train_loss=0.000093

      epoch  80/100: train_loss=0.000093, val_loss=0.000194, IC=+0.0049

      epoch  81/100: train_loss=0.000093

      epoch  82/100: train_loss=0.000093

      epoch  83/100: train_loss=0.000093

      epoch  84/100: train_loss=0.000092

      epoch  85/100: train_loss=0.000093, val_loss=0.000195, IC=+0.0055

      epoch  86/100: train_loss=0.000091

      epoch  87/100: train_loss=0.000092

      epoch  88/100: train_loss=0.000092

      epoch  89/100: train_loss=0.000092

      epoch  90/100: train_loss=0.000093, val_loss=0.000195, IC=+0.0053

      epoch  91/100: train_loss=0.000092

      epoch  92/100: train_loss=0.000091

      epoch  93/100: train_loss=0.000091

      epoch  94/100: train_loss=0.000092

      epoch  95/100: train_loss=0.000092, val_loss=0.000196, IC=+0.0045

      epoch  96/100: train_loss=0.000092

      epoch  97/100: train_loss=0.000092

      epoch  98/100: train_loss=0.000092

      epoch  99/100: train_loss=0.000092

      epoch 100/100: train_loss=0.000091, val_loss=0.000196, IC=+0.0042

      best_ep=5, IC=+0.0853 (56.6s, 20 checkpoints)

  Fold 6: creating sequences...
    train=22,140 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000559

      epoch   2/100: train_loss=0.000270

      epoch   3/100: train_loss=0.000230

      epoch   4/100: train_loss=0.000216

      epoch   5/100: train_loss=0.000208, val_loss=0.000139, IC=-0.0127

      epoch   6/100: train_loss=0.000203

      epoch   7/100: train_loss=0.000198

      epoch   8/100: train_loss=0.000197

      epoch   9/100: train_loss=0.000192

      epoch  10/100: train_loss=0.000189, val_loss=0.000148, IC=-0.0314

      epoch  11/100: train_loss=0.000184

      epoch  12/100: train_loss=0.000180

      epoch  13/100: train_loss=0.000177

      epoch  14/100: train_loss=0.000173

      epoch  15/100: train_loss=0.000169, val_loss=0.000152, IC=-0.0133

      epoch  16/100: train_loss=0.000165

      epoch  17/100: train_loss=0.000163

      epoch  18/100: train_loss=0.000159

      epoch  19/100: train_loss=0.000157

      epoch  20/100: train_loss=0.000153, val_loss=0.000162, IC=-0.0226

      epoch  21/100: train_loss=0.000150

      epoch  22/100: train_loss=0.000148

      epoch  23/100: train_loss=0.000144

      epoch  24/100: train_loss=0.000141

      epoch  25/100: train_loss=0.000140, val_loss=0.000165, IC=+0.0048

      epoch  26/100: train_loss=0.000137

      epoch  27/100: train_loss=0.000135

      epoch  28/100: train_loss=0.000135

      epoch  29/100: train_loss=0.000131

      epoch  30/100: train_loss=0.000130, val_loss=0.000176, IC=-0.0057

      epoch  31/100: train_loss=0.000127

      epoch  32/100: train_loss=0.000124

      epoch  33/100: train_loss=0.000123

      epoch  34/100: train_loss=0.000123

      epoch  35/100: train_loss=0.000122, val_loss=0.000183, IC=+0.0070

      epoch  36/100: train_loss=0.000119

      epoch  37/100: train_loss=0.000116

      epoch  38/100: train_loss=0.000114

      epoch  39/100: train_loss=0.000113

      epoch  40/100: train_loss=0.000111, val_loss=0.000197, IC=+0.0087

      epoch  41/100: train_loss=0.000110

      epoch  42/100: train_loss=0.000109

      epoch  43/100: train_loss=0.000108

      epoch  44/100: train_loss=0.000106

      epoch  45/100: train_loss=0.000105, val_loss=0.000197, IC=+0.0161

      epoch  46/100: train_loss=0.000104

      epoch  47/100: train_loss=0.000103

      epoch  48/100: train_loss=0.000102

      epoch  49/100: train_loss=0.000101

      epoch  50/100: train_loss=0.000100, val_loss=0.000207, IC=+0.0064

      epoch  51/100: train_loss=0.000099

      epoch  52/100: train_loss=0.000098

      epoch  53/100: train_loss=0.000099

      epoch  54/100: train_loss=0.000098

      epoch  55/100: train_loss=0.000097, val_loss=0.000205, IC=+0.0197

      epoch  56/100: train_loss=0.000096

      epoch  57/100: train_loss=0.000095

      epoch  58/100: train_loss=0.000096

      epoch  59/100: train_loss=0.000094

      epoch  60/100: train_loss=0.000094, val_loss=0.000208, IC=+0.0107

      epoch  61/100: train_loss=0.000093

      epoch  62/100: train_loss=0.000092

      epoch  63/100: train_loss=0.000090

      epoch  64/100: train_loss=0.000092

      epoch  65/100: train_loss=0.000091, val_loss=0.000213, IC=+0.0177

      epoch  66/100: train_loss=0.000091

      epoch  67/100: train_loss=0.000090

      epoch  68/100: train_loss=0.000089

      epoch  69/100: train_loss=0.000090

      epoch  70/100: train_loss=0.000089, val_loss=0.000213, IC=+0.0186

      epoch  71/100: train_loss=0.000089

      epoch  72/100: train_loss=0.000089

      epoch  73/100: train_loss=0.000088

      epoch  74/100: train_loss=0.000086

      epoch  75/100: train_loss=0.000087, val_loss=0.000216, IC=+0.0147

      epoch  76/100: train_loss=0.000087

      epoch  77/100: train_loss=0.000087

      epoch  78/100: train_loss=0.000087

      epoch  79/100: train_loss=0.000087

      epoch  80/100: train_loss=0.000086, val_loss=0.000217, IC=+0.0183

      epoch  81/100: train_loss=0.000086

      epoch  82/100: train_loss=0.000086

      epoch  83/100: train_loss=0.000085

      epoch  84/100: train_loss=0.000086

      epoch  85/100: train_loss=0.000085, val_loss=0.000219, IC=+0.0174

      epoch  86/100: train_loss=0.000085

      epoch  87/100: train_loss=0.000084

      epoch  88/100: train_loss=0.000085

      epoch  89/100: train_loss=0.000084

      epoch  90/100: train_loss=0.000085, val_loss=0.000219, IC=+0.0184

      epoch  91/100: train_loss=0.000086

      epoch  92/100: train_loss=0.000084

      epoch  93/100: train_loss=0.000085

      epoch  94/100: train_loss=0.000086

      epoch  95/100: train_loss=0.000085, val_loss=0.000220, IC=+0.0176

      epoch  96/100: train_loss=0.000085

      epoch  97/100: train_loss=0.000084

      epoch  98/100: train_loss=0.000086

      epoch  99/100: train_loss=0.000084

      epoch 100/100: train_loss=0.000085, val_loss=0.000220, IC=+0.0173

      best_ep=55, IC=+0.0197 (52.0s, 20 checkpoints)

  Fold 7: creating sequences...
    train=16,980 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000619

      epoch   2/100: train_loss=0.000287

      epoch   3/100: train_loss=0.000226

      epoch   4/100: train_loss=0.000204

      epoch   5/100: train_loss=0.000195, val_loss=0.000289, IC=+0.0719

      epoch   6/100: train_loss=0.000191

      epoch   7/100: train_loss=0.000187

      epoch   8/100: train_loss=0.000184

      epoch   9/100: train_loss=0.000176

      epoch  10/100: train_loss=0.000180, val_loss=0.000289, IC=+0.0738

      epoch  11/100: train_loss=0.000172

      epoch  12/100: train_loss=0.000169

      epoch  13/100: train_loss=0.000167

      epoch  14/100: train_loss=0.000166

      epoch  15/100: train_loss=0.000161, val_loss=0.000307, IC=+0.0814

      epoch  16/100: train_loss=0.000160

      epoch  17/100: train_loss=0.000155

      epoch  18/100: train_loss=0.000156

      epoch  19/100: train_loss=0.000152

      epoch  20/100: train_loss=0.000147, val_loss=0.000320, IC=+0.0722

      epoch  21/100: train_loss=0.000144

      epoch  22/100: train_loss=0.000143

      epoch  23/100: train_loss=0.000142

      epoch  24/100: train_loss=0.000148

      epoch  25/100: train_loss=0.000135, val_loss=0.000328, IC=+0.0812

      epoch  26/100: train_loss=0.000136

      epoch  27/100: train_loss=0.000134

      epoch  28/100: train_loss=0.000129

      epoch  29/100: train_loss=0.000132

      epoch  30/100: train_loss=0.000130, val_loss=0.000327, IC=+0.0838

      epoch  31/100: train_loss=0.000130

      epoch  32/100: train_loss=0.000123

      epoch  33/100: train_loss=0.000121

      epoch  34/100: train_loss=0.000119

      epoch  35/100: train_loss=0.000118, val_loss=0.000352, IC=+0.0626

      epoch  36/100: train_loss=0.000115

      epoch  37/100: train_loss=0.000115

      epoch  38/100: train_loss=0.000112

      epoch  39/100: train_loss=0.000112

      epoch  40/100: train_loss=0.000109, val_loss=0.000353, IC=+0.0561

      epoch  41/100: train_loss=0.000107

      epoch  42/100: train_loss=0.000108

      epoch  43/100: train_loss=0.000105

      epoch  44/100: train_loss=0.000106

      epoch  45/100: train_loss=0.000105, val_loss=0.000357, IC=+0.0633

      epoch  46/100: train_loss=0.000103

      epoch  47/100: train_loss=0.000103

      epoch  48/100: train_loss=0.000102

      epoch  49/100: train_loss=0.000103

      epoch  50/100: train_loss=0.000100, val_loss=0.000374, IC=+0.0467

      epoch  51/100: train_loss=0.000100

      epoch  52/100: train_loss=0.000098

      epoch  53/100: train_loss=0.000100

      epoch  54/100: train_loss=0.000099

      epoch  55/100: train_loss=0.000097, val_loss=0.000380, IC=+0.0497

      epoch  56/100: train_loss=0.000096

      epoch  57/100: train_loss=0.000094

      epoch  58/100: train_loss=0.000093

      epoch  59/100: train_loss=0.000092

      epoch  60/100: train_loss=0.000094, val_loss=0.000382, IC=+0.0498

      epoch  61/100: train_loss=0.000092

      epoch  62/100: train_loss=0.000092

      epoch  63/100: train_loss=0.000095

      epoch  64/100: train_loss=0.000094

      epoch  65/100: train_loss=0.000093, val_loss=0.000375, IC=+0.0544

      epoch  66/100: train_loss=0.000093

      epoch  67/100: train_loss=0.000089

      epoch  68/100: train_loss=0.000089

      epoch  69/100: train_loss=0.000088

      epoch  70/100: train_loss=0.000088, val_loss=0.000390, IC=+0.0523

      epoch  71/100: train_loss=0.000088

      epoch  72/100: train_loss=0.000087

      epoch  73/100: train_loss=0.000089

      epoch  74/100: train_loss=0.000087

      epoch  75/100: train_loss=0.000091, val_loss=0.000393, IC=+0.0455

      epoch  76/100: train_loss=0.000088

      epoch  77/100: train_loss=0.000088

      epoch  78/100: train_loss=0.000086

      epoch  79/100: train_loss=0.000088

      epoch  80/100: train_loss=0.000086, val_loss=0.000395, IC=+0.0486

      epoch  81/100: train_loss=0.000086

      epoch  82/100: train_loss=0.000087

      epoch  83/100: train_loss=0.000086

      epoch  84/100: train_loss=0.000086

      epoch  85/100: train_loss=0.000087, val_loss=0.000396, IC=+0.0474

      epoch  86/100: train_loss=0.000085

      epoch  87/100: train_loss=0.000085

      epoch  88/100: train_loss=0.000085

      epoch  89/100: train_loss=0.000084

      epoch  90/100: train_loss=0.000084, val_loss=0.000397, IC=+0.0459

      epoch  91/100: train_loss=0.000085

      epoch  92/100: train_loss=0.000085

      epoch  93/100: train_loss=0.000085

      epoch  94/100: train_loss=0.000084

      epoch  95/100: train_loss=0.000083, val_loss=0.000396, IC=+0.0462

      epoch  96/100: train_loss=0.000086

      epoch  97/100: train_loss=0.000084

      epoch  98/100: train_loss=0.000085

      epoch  99/100: train_loss=0.000084

      epoch 100/100: train_loss=0.000085, val_loss=0.000396, IC=+0.0456

      best_ep=30, IC=+0.0838 (40.4s, 20 checkpoints)

  lstm_h64: best_epoch=60, IC=+0.0070 (441.1s)

  Best: lstm_h64 @ epoch 60 (IC=+0.0070)
  Saved to ~/ml4t/public-fx-lstm/case_studies/fx_pairs/run_log/training/0161c35e6591/diagnostics

Fold-major CV: 8 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=24,180 seq across 20 symbols
    val=4,740 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002163

      epoch   2/100: train_loss=0.000702

      epoch   3/100: train_loss=0.000548

      epoch   4/100: train_loss=0.000493

      epoch   5/100: train_loss=0.000469, val_loss=0.000596, IC=-0.1642

      epoch   6/100: train_loss=0.000446

      epoch   7/100: train_loss=0.000427

      epoch   8/100: train_loss=0.000408

      epoch   9/100: train_loss=0.000389

      epoch  10/100: train_loss=0.000370, val_loss=0.000737, IC=-0.1182

      epoch  11/100: train_loss=0.000355

      epoch  12/100: train_loss=0.000337

      epoch  13/100: train_loss=0.000318

      epoch  14/100: train_loss=0.000302

      epoch  15/100: train_loss=0.000287, val_loss=0.000924, IC=-0.1298

      epoch  16/100: train_loss=0.000273

      epoch  17/100: train_loss=0.000262

      epoch  18/100: train_loss=0.000247

      epoch  19/100: train_loss=0.000239

      epoch  20/100: train_loss=0.000229, val_loss=0.000937, IC=-0.1206

      epoch  21/100: train_loss=0.000221

      epoch  22/100: train_loss=0.000212

      epoch  23/100: train_loss=0.000204

      epoch  24/100: train_loss=0.000196

      epoch  25/100: train_loss=0.000188, val_loss=0.000972, IC=-0.1176

      epoch  26/100: train_loss=0.000180

      epoch  27/100: train_loss=0.000176

      epoch  28/100: train_loss=0.000169

      epoch  29/100: train_loss=0.000164

      epoch  30/100: train_loss=0.000157, val_loss=0.001053, IC=-0.1046

      epoch  31/100: train_loss=0.000154

      epoch  32/100: train_loss=0.000147

      epoch  33/100: train_loss=0.000143

      epoch  34/100: train_loss=0.000138

      epoch  35/100: train_loss=0.000135, val_loss=0.001115, IC=-0.1080

      epoch  36/100: train_loss=0.000132

      epoch  37/100: train_loss=0.000130

      epoch  38/100: train_loss=0.000124

      epoch  39/100: train_loss=0.000119

      epoch  40/100: train_loss=0.000117, val_loss=0.001140, IC=-0.1133

      epoch  41/100: train_loss=0.000113

      epoch  42/100: train_loss=0.000110

      epoch  43/100: train_loss=0.000107

      epoch  44/100: train_loss=0.000104

      epoch  45/100: train_loss=0.000103, val_loss=0.001146, IC=-0.1057

      epoch  46/100: train_loss=0.000101

      epoch  47/100: train_loss=0.000099

      epoch  48/100: train_loss=0.000097

      epoch  49/100: train_loss=0.000095

      epoch  50/100: train_loss=0.000094, val_loss=0.001201, IC=-0.1022

      epoch  51/100: train_loss=0.000093

      epoch  52/100: train_loss=0.000092

      epoch  53/100: train_loss=0.000090

      epoch  54/100: train_loss=0.000090

      epoch  55/100: train_loss=0.000088, val_loss=0.001218, IC=-0.1112

      epoch  56/100: train_loss=0.000086

      epoch  57/100: train_loss=0.000085

      epoch  58/100: train_loss=0.000085

      epoch  59/100: train_loss=0.000084

      epoch  60/100: train_loss=0.000084, val_loss=0.001222, IC=-0.1068

      epoch  61/100: train_loss=0.000083

      epoch  62/100: train_loss=0.000082

      epoch  63/100: train_loss=0.000082

      epoch  64/100: train_loss=0.000081

      epoch  65/100: train_loss=0.000080, val_loss=0.001247, IC=-0.1094

      epoch  66/100: train_loss=0.000080

      epoch  67/100: train_loss=0.000079

      epoch  68/100: train_loss=0.000079

      epoch  69/100: train_loss=0.000078

      epoch  70/100: train_loss=0.000078, val_loss=0.001250, IC=-0.1124

      epoch  71/100: train_loss=0.000078

      epoch  72/100: train_loss=0.000077

      epoch  73/100: train_loss=0.000077

      epoch  74/100: train_loss=0.000077

      epoch  75/100: train_loss=0.000077, val_loss=0.001268, IC=-0.1107

      epoch  76/100: train_loss=0.000076

      epoch  77/100: train_loss=0.000075

      epoch  78/100: train_loss=0.000076

      epoch  79/100: train_loss=0.000075

      epoch  80/100: train_loss=0.000075, val_loss=0.001266, IC=-0.1095

      epoch  81/100: train_loss=0.000075

      epoch  82/100: train_loss=0.000074

      epoch  83/100: train_loss=0.000075

      epoch  84/100: train_loss=0.000075

      epoch  85/100: train_loss=0.000075, val_loss=0.001274, IC=-0.1100

      epoch  86/100: train_loss=0.000074

      epoch  87/100: train_loss=0.000074

      epoch  88/100: train_loss=0.000073

      epoch  89/100: train_loss=0.000074

      epoch  90/100: train_loss=0.000074, val_loss=0.001274, IC=-0.1103

      epoch  91/100: train_loss=0.000074

      epoch  92/100: train_loss=0.000074

      epoch  93/100: train_loss=0.000073

      epoch  94/100: train_loss=0.000073

      epoch  95/100: train_loss=0.000074, val_loss=0.001274, IC=-0.1106

      epoch  96/100: train_loss=0.000074

      epoch  97/100: train_loss=0.000073

      epoch  98/100: train_loss=0.000073

      epoch  99/100: train_loss=0.000074

      epoch 100/100: train_loss=0.000073, val_loss=0.001274, IC=-0.1104

      best_ep=50, IC=-0.1022 (57.7s, 20 checkpoints)

  Fold 1: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.005581

      epoch   2/100: train_loss=0.000853

      epoch   3/100: train_loss=0.000564

      epoch   4/100: train_loss=0.000483

      epoch   5/100: train_loss=0.000447, val_loss=0.001101, IC=+0.0113

      epoch   6/100: train_loss=0.000428

      epoch   7/100: train_loss=0.000415

      epoch   8/100: train_loss=0.000401

      epoch   9/100: train_loss=0.000392

      epoch  10/100: train_loss=0.000379, val_loss=0.001176, IC=+0.0260

      epoch  11/100: train_loss=0.000371

      epoch  12/100: train_loss=0.000362

      epoch  13/100: train_loss=0.000351

      epoch  14/100: train_loss=0.000341

      epoch  15/100: train_loss=0.000332, val_loss=0.001274, IC=+0.0074

      epoch  16/100: train_loss=0.000323

      epoch  17/100: train_loss=0.000313

      epoch  18/100: train_loss=0.000304

      epoch  19/100: train_loss=0.000297

      epoch  20/100: train_loss=0.000288, val_loss=0.001313, IC=+0.0023

      epoch  21/100: train_loss=0.000281

      epoch  22/100: train_loss=0.000274

      epoch  23/100: train_loss=0.000264

      epoch  24/100: train_loss=0.000257

      epoch  25/100: train_loss=0.000250, val_loss=0.001323, IC=-0.0079

      epoch  26/100: train_loss=0.000243

      epoch  27/100: train_loss=0.000237

      epoch  28/100: train_loss=0.000229

      epoch  29/100: train_loss=0.000224

      epoch  30/100: train_loss=0.000218, val_loss=0.001367, IC=-0.0154

      epoch  31/100: train_loss=0.000213

      epoch  32/100: train_loss=0.000206

      epoch  33/100: train_loss=0.000200

      epoch  34/100: train_loss=0.000196

      epoch  35/100: train_loss=0.000190, val_loss=0.001409, IC=-0.0067

      epoch  36/100: train_loss=0.000184

      epoch  37/100: train_loss=0.000178

      epoch  38/100: train_loss=0.000175

      epoch  39/100: train_loss=0.000171

      epoch  40/100: train_loss=0.000167, val_loss=0.001478, IC=-0.0192

      epoch  41/100: train_loss=0.000162

      epoch  42/100: train_loss=0.000156

      epoch  43/100: train_loss=0.000153

      epoch  44/100: train_loss=0.000148

      epoch  45/100: train_loss=0.000146, val_loss=0.001494, IC=-0.0123

      epoch  46/100: train_loss=0.000142

      epoch  47/100: train_loss=0.000139

      epoch  48/100: train_loss=0.000135

      epoch  49/100: train_loss=0.000132

      epoch  50/100: train_loss=0.000129, val_loss=0.001483, IC=-0.0083

      epoch  51/100: train_loss=0.000126

      epoch  52/100: train_loss=0.000123

      epoch  53/100: train_loss=0.000120

      epoch  54/100: train_loss=0.000119

      epoch  55/100: train_loss=0.000115, val_loss=0.001459, IC=-0.0028

      epoch  56/100: train_loss=0.000112

      epoch  57/100: train_loss=0.000110

      epoch  58/100: train_loss=0.000110

      epoch  59/100: train_loss=0.000108

      epoch  60/100: train_loss=0.000107, val_loss=0.001526, IC=+0.0009

      epoch  61/100: train_loss=0.000106

      epoch  62/100: train_loss=0.000103

      epoch  63/100: train_loss=0.000101

      epoch  64/100: train_loss=0.000099

      epoch  65/100: train_loss=0.000100, val_loss=0.001486, IC=+0.0028

      epoch  66/100: train_loss=0.000098

      epoch  67/100: train_loss=0.000097

      epoch  68/100: train_loss=0.000096

      epoch  69/100: train_loss=0.000095

      epoch  70/100: train_loss=0.000094, val_loss=0.001502, IC=+0.0048

      epoch  71/100: train_loss=0.000094

      epoch  72/100: train_loss=0.000092

      epoch  73/100: train_loss=0.000092

      epoch  74/100: train_loss=0.000092

      epoch  75/100: train_loss=0.000092, val_loss=0.001510, IC=+0.0035

      epoch  76/100: train_loss=0.000090

      epoch  77/100: train_loss=0.000091

      epoch  78/100: train_loss=0.000089

      epoch  79/100: train_loss=0.000089

      epoch  80/100: train_loss=0.000089, val_loss=0.001507, IC=+0.0056

      epoch  81/100: train_loss=0.000088

      epoch  82/100: train_loss=0.000088

      epoch  83/100: train_loss=0.000088

      epoch  84/100: train_loss=0.000088

      epoch  85/100: train_loss=0.000087, val_loss=0.001498, IC=+0.0078

      epoch  86/100: train_loss=0.000087

      epoch  87/100: train_loss=0.000087

      epoch  88/100: train_loss=0.000087

      epoch  89/100: train_loss=0.000088

      epoch  90/100: train_loss=0.000086, val_loss=0.001504, IC=+0.0071

      epoch  91/100: train_loss=0.000087

      epoch  92/100: train_loss=0.000086

      epoch  93/100: train_loss=0.000087

      epoch  94/100: train_loss=0.000086

      epoch  95/100: train_loss=0.000086, val_loss=0.001502, IC=+0.0073

      epoch  96/100: train_loss=0.000086

      epoch  97/100: train_loss=0.000087

      epoch  98/100: train_loss=0.000086

      epoch  99/100: train_loss=0.000086

      epoch 100/100: train_loss=0.000086, val_loss=0.001503, IC=+0.0074

      best_ep=10, IC=+0.0260 (55.2s, 20 checkpoints)

  Fold 2: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000971

      epoch   2/100: train_loss=0.000585

      epoch   3/100: train_loss=0.000522

      epoch   4/100: train_loss=0.000479

      epoch   5/100: train_loss=0.000440, val_loss=0.000417, IC=-0.0450

      epoch   6/100: train_loss=0.000409

      epoch   7/100: train_loss=0.000383

      epoch   8/100: train_loss=0.000357

      epoch   9/100: train_loss=0.000336

      epoch  10/100: train_loss=0.000320, val_loss=0.000461, IC=-0.0078

      epoch  11/100: train_loss=0.000302

      epoch  12/100: train_loss=0.000282

      epoch  13/100: train_loss=0.000263

      epoch  14/100: train_loss=0.000248

      epoch  15/100: train_loss=0.000233, val_loss=0.000541, IC=+0.0197

      epoch  16/100: train_loss=0.000216

      epoch  17/100: train_loss=0.000204

      epoch  18/100: train_loss=0.000189

      epoch  19/100: train_loss=0.000179

      epoch  20/100: train_loss=0.000170, val_loss=0.000652, IC=+0.0012

      epoch  21/100: train_loss=0.000160

      epoch  22/100: train_loss=0.000148

      epoch  23/100: train_loss=0.000141

      epoch  24/100: train_loss=0.000132

      epoch  25/100: train_loss=0.000126, val_loss=0.000739, IC=+0.0134

      epoch  26/100: train_loss=0.000119

      epoch  27/100: train_loss=0.000115

      epoch  28/100: train_loss=0.000113

      epoch  29/100: train_loss=0.000108

      epoch  30/100: train_loss=0.000105, val_loss=0.000800, IC=-0.0080

      epoch  31/100: train_loss=0.000100

      epoch  32/100: train_loss=0.000097

      epoch  33/100: train_loss=0.000096

      epoch  34/100: train_loss=0.000093

      epoch  35/100: train_loss=0.000092, val_loss=0.000861, IC=-0.0409

      epoch  36/100: train_loss=0.000089

      epoch  37/100: train_loss=0.000087

      epoch  38/100: train_loss=0.000087

      epoch  39/100: train_loss=0.000084

      epoch  40/100: train_loss=0.000082, val_loss=0.000887, IC=-0.0582

      epoch  41/100: train_loss=0.000081

      epoch  42/100: train_loss=0.000080

      epoch  43/100: train_loss=0.000077

      epoch  44/100: train_loss=0.000078

      epoch  45/100: train_loss=0.000076, val_loss=0.000895, IC=-0.0573

      epoch  46/100: train_loss=0.000076

      epoch  47/100: train_loss=0.000075

      epoch  48/100: train_loss=0.000074

      epoch  49/100: train_loss=0.000074

      epoch  50/100: train_loss=0.000073, val_loss=0.000933, IC=-0.0646

      epoch  51/100: train_loss=0.000073

      epoch  52/100: train_loss=0.000072

      epoch  53/100: train_loss=0.000070

      epoch  54/100: train_loss=0.000070

      epoch  55/100: train_loss=0.000070, val_loss=0.000934, IC=-0.0690

      epoch  56/100: train_loss=0.000069

      epoch  57/100: train_loss=0.000068

      epoch  58/100: train_loss=0.000068

      epoch  59/100: train_loss=0.000067

      epoch  60/100: train_loss=0.000066, val_loss=0.000974, IC=-0.0740

      epoch  61/100: train_loss=0.000065

      epoch  62/100: train_loss=0.000066

      epoch  63/100: train_loss=0.000066

      epoch  64/100: train_loss=0.000065

      epoch  65/100: train_loss=0.000065, val_loss=0.000989, IC=-0.0712

      epoch  66/100: train_loss=0.000065

      epoch  67/100: train_loss=0.000064

      epoch  68/100: train_loss=0.000064

      epoch  69/100: train_loss=0.000063

      epoch  70/100: train_loss=0.000063, val_loss=0.000981, IC=-0.0727

      epoch  71/100: train_loss=0.000063

      epoch  72/100: train_loss=0.000063

      epoch  73/100: train_loss=0.000062

      epoch  74/100: train_loss=0.000062

      epoch  75/100: train_loss=0.000062, val_loss=0.000985, IC=-0.0729

      epoch  76/100: train_loss=0.000062

      epoch  77/100: train_loss=0.000061

      epoch  78/100: train_loss=0.000062

      epoch  79/100: train_loss=0.000062

      epoch  80/100: train_loss=0.000062, val_loss=0.000995, IC=-0.0770

      epoch  81/100: train_loss=0.000061

      epoch  82/100: train_loss=0.000061

      epoch  83/100: train_loss=0.000061

      epoch  84/100: train_loss=0.000061

      epoch  85/100: train_loss=0.000061, val_loss=0.000992, IC=-0.0742

      epoch  86/100: train_loss=0.000061

      epoch  87/100: train_loss=0.000061

      epoch  88/100: train_loss=0.000061

      epoch  89/100: train_loss=0.000061

      epoch  90/100: train_loss=0.000061, val_loss=0.000993, IC=-0.0757

      epoch  91/100: train_loss=0.000060

      epoch  92/100: train_loss=0.000060

      epoch  93/100: train_loss=0.000061

      epoch  94/100: train_loss=0.000060

      epoch  95/100: train_loss=0.000060, val_loss=0.000997, IC=-0.0750

      epoch  96/100: train_loss=0.000061

      epoch  97/100: train_loss=0.000060

      epoch  98/100: train_loss=0.000060

      epoch  99/100: train_loss=0.000060

      epoch 100/100: train_loss=0.000060, val_loss=0.000995, IC=-0.0752

      best_ep=15, IC=+0.0197 (65.7s, 20 checkpoints)

  Fold 3: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002053

      epoch   2/100: train_loss=0.000773

      epoch   3/100: train_loss=0.000622

      epoch   4/100: train_loss=0.000563

      epoch   5/100: train_loss=0.000529, val_loss=0.001051, IC=-0.1908

      epoch   6/100: train_loss=0.000503

      epoch   7/100: train_loss=0.000478

      epoch   8/100: train_loss=0.000453

      epoch   9/100: train_loss=0.000426

      epoch  10/100: train_loss=0.000399, val_loss=0.001248, IC=-0.1421

      epoch  11/100: train_loss=0.000374

      epoch  12/100: train_loss=0.000348

      epoch  13/100: train_loss=0.000330

      epoch  14/100: train_loss=0.000309

      epoch  15/100: train_loss=0.000287, val_loss=0.001251, IC=-0.1024

      epoch  16/100: train_loss=0.000274

      epoch  17/100: train_loss=0.000256

      epoch  18/100: train_loss=0.000242

      epoch  19/100: train_loss=0.000230

      epoch  20/100: train_loss=0.000217, val_loss=0.001424, IC=-0.0697

      epoch  21/100: train_loss=0.000208

      epoch  22/100: train_loss=0.000199

      epoch  23/100: train_loss=0.000190

      epoch  24/100: train_loss=0.000182

      epoch  25/100: train_loss=0.000174, val_loss=0.001442, IC=-0.0305

      epoch  26/100: train_loss=0.000169

      epoch  27/100: train_loss=0.000163

      epoch  28/100: train_loss=0.000155

      epoch  29/100: train_loss=0.000152

      epoch  30/100: train_loss=0.000147, val_loss=0.001545, IC=-0.0424

      epoch  31/100: train_loss=0.000142

      epoch  32/100: train_loss=0.000138

      epoch  33/100: train_loss=0.000135

      epoch  34/100: train_loss=0.000132

      epoch  35/100: train_loss=0.000126, val_loss=0.001579, IC=-0.0499

      epoch  36/100: train_loss=0.000124

      epoch  37/100: train_loss=0.000125

      epoch  38/100: train_loss=0.000119

      epoch  39/100: train_loss=0.000115

      epoch  40/100: train_loss=0.000113, val_loss=0.001597, IC=-0.0434

      epoch  41/100: train_loss=0.000111

      epoch  42/100: train_loss=0.000110

      epoch  43/100: train_loss=0.000107

      epoch  44/100: train_loss=0.000104

      epoch  45/100: train_loss=0.000103, val_loss=0.001538, IC=-0.0478

      epoch  46/100: train_loss=0.000102

      epoch  47/100: train_loss=0.000101

      epoch  48/100: train_loss=0.000098

      epoch  49/100: train_loss=0.000097

      epoch  50/100: train_loss=0.000094, val_loss=0.001587, IC=-0.0465

      epoch  51/100: train_loss=0.000093

      epoch  52/100: train_loss=0.000094

      epoch  53/100: train_loss=0.000091

      epoch  54/100: train_loss=0.000091

      epoch  55/100: train_loss=0.000090, val_loss=0.001637, IC=-0.0539

      epoch  56/100: train_loss=0.000089

      epoch  57/100: train_loss=0.000087

      epoch  58/100: train_loss=0.000086

      epoch  59/100: train_loss=0.000087

      epoch  60/100: train_loss=0.000086, val_loss=0.001613, IC=-0.0504

      epoch  61/100: train_loss=0.000084

      epoch  62/100: train_loss=0.000083

      epoch  63/100: train_loss=0.000083

      epoch  64/100: train_loss=0.000083

      epoch  65/100: train_loss=0.000083, val_loss=0.001597, IC=-0.0516

      epoch  66/100: train_loss=0.000082

      epoch  67/100: train_loss=0.000081

      epoch  68/100: train_loss=0.000081

      epoch  69/100: train_loss=0.000081

      epoch  70/100: train_loss=0.000081, val_loss=0.001585, IC=-0.0526

      epoch  71/100: train_loss=0.000079

      epoch  72/100: train_loss=0.000079

      epoch  73/100: train_loss=0.000080

      epoch  74/100: train_loss=0.000079

      epoch  75/100: train_loss=0.000079, val_loss=0.001593, IC=-0.0428

      epoch  76/100: train_loss=0.000078

      epoch  77/100: train_loss=0.000078

      epoch  78/100: train_loss=0.000077

      epoch  79/100: train_loss=0.000077

      epoch  80/100: train_loss=0.000078, val_loss=0.001605, IC=-0.0469

      epoch  81/100: train_loss=0.000077

      epoch  82/100: train_loss=0.000076

      epoch  83/100: train_loss=0.000077

      epoch  84/100: train_loss=0.000077

      epoch  85/100: train_loss=0.000076, val_loss=0.001599, IC=-0.0465

      epoch  86/100: train_loss=0.000076

      epoch  87/100: train_loss=0.000076

      epoch  88/100: train_loss=0.000076

      epoch  89/100: train_loss=0.000076

      epoch  90/100: train_loss=0.000077, val_loss=0.001588, IC=-0.0439

      epoch  91/100: train_loss=0.000076

      epoch  92/100: train_loss=0.000075

      epoch  93/100: train_loss=0.000075

      epoch  94/100: train_loss=0.000075

      epoch  95/100: train_loss=0.000075, val_loss=0.001598, IC=-0.0448

      epoch  96/100: train_loss=0.000075

      epoch  97/100: train_loss=0.000075

      epoch  98/100: train_loss=0.000076

      epoch  99/100: train_loss=0.000076

      epoch 100/100: train_loss=0.000075, val_loss=0.001594, IC=-0.0442

      best_ep=25, IC=-0.0305 (66.4s, 20 checkpoints)

  Fold 4: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001601

      epoch   2/100: train_loss=0.000797

      epoch   3/100: train_loss=0.000695

      epoch   4/100: train_loss=0.000649

      epoch   5/100: train_loss=0.000610, val_loss=0.000376, IC=-0.0659

      epoch   6/100: train_loss=0.000573

      epoch   7/100: train_loss=0.000539

      epoch   8/100: train_loss=0.000506

      epoch   9/100: train_loss=0.000470

      epoch  10/100: train_loss=0.000439, val_loss=0.000447, IC=-0.0712

      epoch  11/100: train_loss=0.000407

      epoch  12/100: train_loss=0.000380

      epoch  13/100: train_loss=0.000354

      epoch  14/100: train_loss=0.000332

      epoch  15/100: train_loss=0.000314, val_loss=0.000556, IC=-0.0669

      epoch  16/100: train_loss=0.000298

      epoch  17/100: train_loss=0.000283

      epoch  18/100: train_loss=0.000266

      epoch  19/100: train_loss=0.000249

      epoch  20/100: train_loss=0.000238, val_loss=0.000722, IC=-0.0418

      epoch  21/100: train_loss=0.000229

      epoch  22/100: train_loss=0.000213

      epoch  23/100: train_loss=0.000206

      epoch  24/100: train_loss=0.000194

      epoch  25/100: train_loss=0.000187, val_loss=0.000750, IC=-0.0241

      epoch  26/100: train_loss=0.000182

      epoch  27/100: train_loss=0.000172

      epoch  28/100: train_loss=0.000166

      epoch  29/100: train_loss=0.000162

      epoch  30/100: train_loss=0.000159, val_loss=0.000786, IC=-0.0111

      epoch  31/100: train_loss=0.000153

      epoch  32/100: train_loss=0.000147

      epoch  33/100: train_loss=0.000142

      epoch  34/100: train_loss=0.000141

      epoch  35/100: train_loss=0.000134, val_loss=0.000854, IC=-0.0297

      epoch  36/100: train_loss=0.000133

      epoch  37/100: train_loss=0.000134

      epoch  38/100: train_loss=0.000128

      epoch  39/100: train_loss=0.000125

      epoch  40/100: train_loss=0.000124, val_loss=0.000903, IC=-0.0386

      epoch  41/100: train_loss=0.000120

      epoch  42/100: train_loss=0.000118

      epoch  43/100: train_loss=0.000117

      epoch  44/100: train_loss=0.000115

      epoch  45/100: train_loss=0.000116, val_loss=0.000883, IC=-0.0497

      epoch  46/100: train_loss=0.000111

      epoch  47/100: train_loss=0.000109

      epoch  48/100: train_loss=0.000107

      epoch  49/100: train_loss=0.000106

      epoch  50/100: train_loss=0.000107, val_loss=0.000949, IC=-0.0561

      epoch  51/100: train_loss=0.000105

      epoch  52/100: train_loss=0.000103

      epoch  53/100: train_loss=0.000102

      epoch  54/100: train_loss=0.000100

      epoch  55/100: train_loss=0.000101, val_loss=0.000959, IC=-0.0380

      epoch  56/100: train_loss=0.000100

      epoch  57/100: train_loss=0.000099

      epoch  58/100: train_loss=0.000099

      epoch  59/100: train_loss=0.000097

      epoch  60/100: train_loss=0.000098, val_loss=0.000944, IC=-0.0432

      epoch  61/100: train_loss=0.000096

      epoch  62/100: train_loss=0.000095

      epoch  63/100: train_loss=0.000094

      epoch  64/100: train_loss=0.000094

      epoch  65/100: train_loss=0.000094, val_loss=0.000952, IC=-0.0322

      epoch  66/100: train_loss=0.000093

      epoch  67/100: train_loss=0.000093

      epoch  68/100: train_loss=0.000093

      epoch  69/100: train_loss=0.000093

      epoch  70/100: train_loss=0.000092, val_loss=0.000958, IC=-0.0240

      epoch  71/100: train_loss=0.000091

      epoch  72/100: train_loss=0.000090

      epoch  73/100: train_loss=0.000089

      epoch  74/100: train_loss=0.000090

      epoch  75/100: train_loss=0.000090, val_loss=0.000982, IC=-0.0274

      epoch  76/100: train_loss=0.000089

      epoch  77/100: train_loss=0.000089

      epoch  78/100: train_loss=0.000090

      epoch  79/100: train_loss=0.000089

      epoch  80/100: train_loss=0.000088, val_loss=0.000966, IC=-0.0268

      epoch  81/100: train_loss=0.000088

      epoch  82/100: train_loss=0.000089

      epoch  83/100: train_loss=0.000087

      epoch  84/100: train_loss=0.000087

      epoch  85/100: train_loss=0.000088, val_loss=0.000964, IC=-0.0251

      epoch  86/100: train_loss=0.000088

      epoch  87/100: train_loss=0.000087

      epoch  88/100: train_loss=0.000087

      epoch  89/100: train_loss=0.000086

      epoch  90/100: train_loss=0.000087, val_loss=0.000966, IC=-0.0231

      epoch  91/100: train_loss=0.000087

      epoch  92/100: train_loss=0.000087

      epoch  93/100: train_loss=0.000087

      epoch  94/100: train_loss=0.000087

      epoch  95/100: train_loss=0.000087, val_loss=0.000970, IC=-0.0233

      epoch  96/100: train_loss=0.000087

      epoch  97/100: train_loss=0.000086

      epoch  98/100: train_loss=0.000087

      epoch  99/100: train_loss=0.000086

      epoch 100/100: train_loss=0.000087, val_loss=0.000970, IC=-0.0231

      best_ep=30, IC=-0.0111 (65.3s, 20 checkpoints)

  Fold 5: creating sequences...
    train=24,180 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001228

      epoch   2/100: train_loss=0.000782

      epoch   3/100: train_loss=0.000693

      epoch   4/100: train_loss=0.000644

      epoch   5/100: train_loss=0.000596, val_loss=0.000550, IC=+0.1077

      epoch   6/100: train_loss=0.000552

      epoch   7/100: train_loss=0.000514

      epoch   8/100: train_loss=0.000471

      epoch   9/100: train_loss=0.000437

      epoch  10/100: train_loss=0.000401, val_loss=0.000585, IC=+0.1214

      epoch  11/100: train_loss=0.000368

      epoch  12/100: train_loss=0.000341

      epoch  13/100: train_loss=0.000319

      epoch  14/100: train_loss=0.000289

      epoch  15/100: train_loss=0.000274, val_loss=0.000666, IC=+0.1152

      epoch  16/100: train_loss=0.000251

      epoch  17/100: train_loss=0.000236

      epoch  18/100: train_loss=0.000220

      epoch  19/100: train_loss=0.000207

      epoch  20/100: train_loss=0.000196, val_loss=0.000743, IC=+0.1220

      epoch  21/100: train_loss=0.000189

      epoch  22/100: train_loss=0.000183

      epoch  23/100: train_loss=0.000175

      epoch  24/100: train_loss=0.000164

      epoch  25/100: train_loss=0.000157, val_loss=0.000814, IC=+0.0887

      epoch  26/100: train_loss=0.000153

      epoch  27/100: train_loss=0.000148

      epoch  28/100: train_loss=0.000142

      epoch  29/100: train_loss=0.000140

      epoch  30/100: train_loss=0.000140, val_loss=0.000874, IC=+0.0647

      epoch  31/100: train_loss=0.000138

      epoch  32/100: train_loss=0.000131

      epoch  33/100: train_loss=0.000129

      epoch  34/100: train_loss=0.000127

      epoch  35/100: train_loss=0.000123, val_loss=0.000890, IC=+0.0721

      epoch  36/100: train_loss=0.000121

      epoch  37/100: train_loss=0.000117

      epoch  38/100: train_loss=0.000117

      epoch  39/100: train_loss=0.000117

      epoch  40/100: train_loss=0.000116, val_loss=0.000923, IC=+0.0629

      epoch  41/100: train_loss=0.000114

      epoch  42/100: train_loss=0.000110

      epoch  43/100: train_loss=0.000110

      epoch  44/100: train_loss=0.000109

      epoch  45/100: train_loss=0.000107, val_loss=0.000949, IC=+0.0555

      epoch  46/100: train_loss=0.000106

      epoch  47/100: train_loss=0.000104

      epoch  48/100: train_loss=0.000104

      epoch  49/100: train_loss=0.000103

      epoch  50/100: train_loss=0.000101, val_loss=0.000962, IC=+0.0588

      epoch  51/100: train_loss=0.000100

      epoch  52/100: train_loss=0.000100

      epoch  53/100: train_loss=0.000099

      epoch  54/100: train_loss=0.000097

      epoch  55/100: train_loss=0.000097, val_loss=0.000967, IC=+0.0550

      epoch  56/100: train_loss=0.000097

      epoch  57/100: train_loss=0.000097

      epoch  58/100: train_loss=0.000095

      epoch  59/100: train_loss=0.000096

      epoch  60/100: train_loss=0.000094, val_loss=0.001007, IC=+0.0572

      epoch  61/100: train_loss=0.000094

      epoch  62/100: train_loss=0.000094

      epoch  63/100: train_loss=0.000094

      epoch  64/100: train_loss=0.000092

      epoch  65/100: train_loss=0.000092, val_loss=0.000995, IC=+0.0557

      epoch  66/100: train_loss=0.000091

      epoch  67/100: train_loss=0.000092

      epoch  68/100: train_loss=0.000091

      epoch  69/100: train_loss=0.000090

      epoch  70/100: train_loss=0.000090, val_loss=0.001015, IC=+0.0520

      epoch  71/100: train_loss=0.000089

      epoch  72/100: train_loss=0.000090

      epoch  73/100: train_loss=0.000090

      epoch  74/100: train_loss=0.000089

      epoch  75/100: train_loss=0.000088, val_loss=0.001019, IC=+0.0561

      epoch  76/100: train_loss=0.000089

      epoch  77/100: train_loss=0.000089

      epoch  78/100: train_loss=0.000088

      epoch  79/100: train_loss=0.000089

      epoch  80/100: train_loss=0.000087, val_loss=0.001028, IC=+0.0501

      epoch  81/100: train_loss=0.000087

      epoch  82/100: train_loss=0.000087

      epoch  83/100: train_loss=0.000087

      epoch  84/100: train_loss=0.000087

      epoch  85/100: train_loss=0.000086, val_loss=0.001025, IC=+0.0555

      epoch  86/100: train_loss=0.000086

      epoch  87/100: train_loss=0.000085

      epoch  88/100: train_loss=0.000087

      epoch  89/100: train_loss=0.000087

      epoch  90/100: train_loss=0.000086, val_loss=0.001030, IC=+0.0546

      epoch  91/100: train_loss=0.000086

      epoch  92/100: train_loss=0.000087

      epoch  93/100: train_loss=0.000086

      epoch  94/100: train_loss=0.000086

      epoch  95/100: train_loss=0.000086, val_loss=0.001033, IC=+0.0546

      epoch  96/100: train_loss=0.000085

      epoch  97/100: train_loss=0.000086

      epoch  98/100: train_loss=0.000086

      epoch  99/100: train_loss=0.000086

      epoch 100/100: train_loss=0.000086, val_loss=0.001032, IC=+0.0547

      best_ep=20, IC=+0.1220 (68.6s, 20 checkpoints)

  Fold 6: creating sequences...

    train=21,820 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001163

      epoch   2/100: train_loss=0.000809

      epoch   3/100: train_loss=0.000714

      epoch   4/100: train_loss=0.000653

      epoch   5/100: train_loss=0.000597, val_loss=0.000720, IC=-0.0901

      epoch   6/100: train_loss=0.000551

      epoch   7/100: train_loss=0.000500

      epoch   8/100: train_loss=0.000452

      epoch   9/100: train_loss=0.000408

      epoch  10/100: train_loss=0.000372, val_loss=0.000913, IC=-0.0936

      epoch  11/100: train_loss=0.000340

      epoch  12/100: train_loss=0.000312

      epoch  13/100: train_loss=0.000283

      epoch  14/100: train_loss=0.000261

      epoch  15/100: train_loss=0.000244, val_loss=0.001007, IC=-0.0782

      epoch  16/100: train_loss=0.000230

      epoch  17/100: train_loss=0.000216

      epoch  18/100: train_loss=0.000208

      epoch  19/100: train_loss=0.000199

      epoch  20/100: train_loss=0.000188, val_loss=0.001000, IC=-0.0433

      epoch  21/100: train_loss=0.000178

      epoch  22/100: train_loss=0.000176

      epoch  23/100: train_loss=0.000166

      epoch  24/100: train_loss=0.000164

      epoch  25/100: train_loss=0.000159, val_loss=0.001011, IC=-0.0093

      epoch  26/100: train_loss=0.000153

      epoch  27/100: train_loss=0.000151

      epoch  28/100: train_loss=0.000145

      epoch  29/100: train_loss=0.000143

      epoch  30/100: train_loss=0.000144, val_loss=0.000985, IC=+0.0015

      epoch  31/100: train_loss=0.000135

      epoch  32/100: train_loss=0.000133

      epoch  33/100: train_loss=0.000128

      epoch  34/100: train_loss=0.000129

      epoch  35/100: train_loss=0.000127, val_loss=0.000975, IC=+0.0087

      epoch  36/100: train_loss=0.000125

      epoch  37/100: train_loss=0.000121

      epoch  38/100: train_loss=0.000117

      epoch  39/100: train_loss=0.000117

      epoch  40/100: train_loss=0.000116, val_loss=0.000983, IC=+0.0077

      epoch  41/100: train_loss=0.000114

      epoch  42/100: train_loss=0.000114

      epoch  43/100: train_loss=0.000111

      epoch  44/100: train_loss=0.000109

      epoch  45/100: train_loss=0.000109, val_loss=0.000965, IC=+0.0266

      epoch  46/100: train_loss=0.000107

      epoch  47/100: train_loss=0.000107

      epoch  48/100: train_loss=0.000105

      epoch  49/100: train_loss=0.000104

      epoch  50/100: train_loss=0.000104, val_loss=0.000971, IC=+0.0221

      epoch  51/100: train_loss=0.000101

      epoch  52/100: train_loss=0.000102

      epoch  53/100: train_loss=0.000102

      epoch  54/100: train_loss=0.000100

      epoch  55/100: train_loss=0.000098, val_loss=0.000980, IC=+0.0247

      epoch  56/100: train_loss=0.000098

      epoch  57/100: train_loss=0.000098

      epoch  58/100: train_loss=0.000096

      epoch  59/100: train_loss=0.000097

      epoch  60/100: train_loss=0.000096, val_loss=0.000975, IC=+0.0155

      epoch  61/100: train_loss=0.000096

      epoch  62/100: train_loss=0.000096

      epoch  63/100: train_loss=0.000095

      epoch  64/100: train_loss=0.000094

      epoch  65/100: train_loss=0.000094, val_loss=0.000974, IC=+0.0282

      epoch  66/100: train_loss=0.000093

      epoch  67/100: train_loss=0.000093

      epoch  68/100: train_loss=0.000092

      epoch  69/100: train_loss=0.000091

      epoch  70/100: train_loss=0.000092, val_loss=0.000955, IC=+0.0340

      epoch  71/100: train_loss=0.000091

      epoch  72/100: train_loss=0.000091

      epoch  73/100: train_loss=0.000090

      epoch  74/100: train_loss=0.000091

      epoch  75/100: train_loss=0.000090, val_loss=0.000972, IC=+0.0284

      epoch  76/100: train_loss=0.000089

      epoch  77/100: train_loss=0.000090

      epoch  78/100: train_loss=0.000089

      epoch  79/100: train_loss=0.000088

      epoch  80/100: train_loss=0.000089, val_loss=0.000961, IC=+0.0343

      epoch  81/100: train_loss=0.000088

      epoch  82/100: train_loss=0.000088

      epoch  83/100: train_loss=0.000087

      epoch  84/100: train_loss=0.000088

      epoch  85/100: train_loss=0.000088, val_loss=0.000965, IC=+0.0352

      epoch  86/100: train_loss=0.000087

      epoch  87/100: train_loss=0.000088

      epoch  88/100: train_loss=0.000087

      epoch  89/100: train_loss=0.000087

      epoch  90/100: train_loss=0.000087, val_loss=0.000967, IC=+0.0336

      epoch  91/100: train_loss=0.000087

      epoch  92/100: train_loss=0.000087

      epoch  93/100: train_loss=0.000087

      epoch  94/100: train_loss=0.000087

      epoch  95/100: train_loss=0.000087, val_loss=0.000964, IC=+0.0342

      epoch  96/100: train_loss=0.000087

      epoch  97/100: train_loss=0.000086

      epoch  98/100: train_loss=0.000087

      epoch  99/100: train_loss=0.000087

      epoch 100/100: train_loss=0.000087, val_loss=0.000964, IC=+0.0337

      best_ep=85, IC=+0.0352 (62.8s, 20 checkpoints)

  Fold 7: creating sequences...
    train=16,660 seq across 20 symbols
    val=5,160 seq across 20 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001119

      epoch   2/100: train_loss=0.000730

      epoch   3/100: train_loss=0.000664

      epoch   4/100: train_loss=0.000608

      epoch   5/100: train_loss=0.000579, val_loss=0.001249, IC=+0.0692

      epoch   6/100: train_loss=0.000544

      epoch   7/100: train_loss=0.000517

      epoch   8/100: train_loss=0.000461

      epoch   9/100: train_loss=0.000445

      epoch  10/100: train_loss=0.000404, val_loss=0.001365, IC=+0.0818

      epoch  11/100: train_loss=0.000392

      epoch  12/100: train_loss=0.000353

      epoch  13/100: train_loss=0.000343

      epoch  14/100: train_loss=0.000319

      epoch  15/100: train_loss=0.000295, val_loss=0.001392, IC=+0.0599

      epoch  16/100: train_loss=0.000282

      epoch  17/100: train_loss=0.000262

      epoch  18/100: train_loss=0.000247

      epoch  19/100: train_loss=0.000229

      epoch  20/100: train_loss=0.000213, val_loss=0.001428, IC=+0.0498

      epoch  21/100: train_loss=0.000206

      epoch  22/100: train_loss=0.000192

      epoch  23/100: train_loss=0.000184

      epoch  24/100: train_loss=0.000173

      epoch  25/100: train_loss=0.000172, val_loss=0.001477, IC=+0.0263

      epoch  26/100: train_loss=0.000163

      epoch  27/100: train_loss=0.000152

      epoch  28/100: train_loss=0.000150

      epoch  29/100: train_loss=0.000153

      epoch  30/100: train_loss=0.000144, val_loss=0.001529, IC=+0.0179

      epoch  31/100: train_loss=0.000139

      epoch  32/100: train_loss=0.000132

      epoch  33/100: train_loss=0.000130

      epoch  34/100: train_loss=0.000135

      epoch  35/100: train_loss=0.000127, val_loss=0.001552, IC=+0.0350

      epoch  36/100: train_loss=0.000123

      epoch  37/100: train_loss=0.000120

      epoch  38/100: train_loss=0.000120

      epoch  39/100: train_loss=0.000111

      epoch  40/100: train_loss=0.000111, val_loss=0.001547, IC=+0.0338

      epoch  41/100: train_loss=0.000108

      epoch  42/100: train_loss=0.000112

      epoch  43/100: train_loss=0.000107

      epoch  44/100: train_loss=0.000107

      epoch  45/100: train_loss=0.000104, val_loss=0.001512, IC=+0.0448

      epoch  46/100: train_loss=0.000107

      epoch  47/100: train_loss=0.000104

      epoch  48/100: train_loss=0.000102

      epoch  49/100: train_loss=0.000101

      epoch  50/100: train_loss=0.000103, val_loss=0.001558, IC=+0.0368

      epoch  51/100: train_loss=0.000109

      epoch  52/100: train_loss=0.000103

      epoch  53/100: train_loss=0.000100

      epoch  54/100: train_loss=0.000096

      epoch  55/100: train_loss=0.000096, val_loss=0.001536, IC=+0.0376

      epoch  56/100: train_loss=0.000093

      epoch  57/100: train_loss=0.000100

      epoch  58/100: train_loss=0.000099

      epoch  59/100: train_loss=0.000093

      epoch  60/100: train_loss=0.000093, val_loss=0.001532, IC=+0.0369

      epoch  61/100: train_loss=0.000091

      epoch  62/100: train_loss=0.000089

      epoch  63/100: train_loss=0.000089

      epoch  64/100: train_loss=0.000090

      epoch  65/100: train_loss=0.000087, val_loss=0.001560, IC=+0.0355

      epoch  66/100: train_loss=0.000086

      epoch  67/100: train_loss=0.000085

      epoch  68/100: train_loss=0.000090

      epoch  69/100: train_loss=0.000085

      epoch  70/100: train_loss=0.000092, val_loss=0.001528, IC=+0.0366

      epoch  71/100: train_loss=0.000090

      epoch  72/100: train_loss=0.000088

      epoch  73/100: train_loss=0.000086

      epoch  74/100: train_loss=0.000089

      epoch  75/100: train_loss=0.000084, val_loss=0.001550, IC=+0.0395

      epoch  76/100: train_loss=0.000085

      epoch  77/100: train_loss=0.000083

      epoch  78/100: train_loss=0.000084

      epoch  79/100: train_loss=0.000084

      epoch  80/100: train_loss=0.000087, val_loss=0.001552, IC=+0.0405

      epoch  81/100: train_loss=0.000082

      epoch  82/100: train_loss=0.000085

      epoch  83/100: train_loss=0.000083

      epoch  84/100: train_loss=0.000087

      epoch  85/100: train_loss=0.000083, val_loss=0.001567, IC=+0.0406

      epoch  86/100: train_loss=0.000082

      epoch  87/100: train_loss=0.000081

      epoch  88/100: train_loss=0.000080

      epoch  89/100: train_loss=0.000081

      epoch  90/100: train_loss=0.000084, val_loss=0.001542, IC=+0.0430

      epoch  91/100: train_loss=0.000081

      epoch  92/100: train_loss=0.000080

      epoch  93/100: train_loss=0.000084

      epoch  94/100: train_loss=0.000081

      epoch  95/100: train_loss=0.000084, val_loss=0.001549, IC=+0.0403

      epoch  96/100: train_loss=0.000079

      epoch  97/100: train_loss=0.000080

      epoch  98/100: train_loss=0.000081

      epoch  99/100: train_loss=0.000081

      epoch 100/100: train_loss=0.000086, val_loss=0.001550, IC=+0.0410

      best_ep=10, IC=+0.0818 (44.7s, 20 checkpoints)

  lstm_h64: best_epoch=25, IC=-0.0065 (486.6s)

  Best: lstm_h64 @ epoch 25 (IC=-0.0065)
  Saved to ~/ml4t/public-fx-lstm/case_studies/fx_pairs/run_log/training/a27f7ab39115/diagnostics

shape: (60, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ label     ┆ config_na ┆ checkpoin ┆ checkpoin ┆ … ┆ ic_mean   ┆ ic_t      ┆ training_ ┆ predicti │
│ ---       ┆ me        ┆ t_kind    ┆ t_value   ┆   ┆ ---       ┆ ---       ┆ hash      ┆ on_hash  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ i64       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 5         ┆ … ┆ -0.004742 ┆ -0.582133 ┆ 1426ea6ec ┆ fab919fd │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ d07       ┆ dca5     │
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 10        ┆ … ┆ 0.004597  ┆ 0.777677  ┆ 1426ea6ec ┆ 310cbfcb │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ d07       ┆ 9890     │
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 15        ┆ … ┆ 0.000301  ┆ 0.051189  ┆ 1426ea6ec ┆ 6a756255 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ d07       ┆ 4670     │
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 20        ┆ … ┆ -0.003489 ┆ -0.430869 ┆ 1426ea6ec ┆ 9425dbf6 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ d07       ┆ 9de4     │
│ fwd_ret_1 ┆ lstm_h64  ┆ epoch     ┆ 25        ┆ … ┆ 0.005915  ┆ 0.615787  ┆ 1426ea6ec ┆ 9cc6d7f6 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ d07       ┆ 6d60     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 80        ┆ … ┆ 0.001946  ┆ 0.133262  ┆ 0161c35e6 ┆ 55fdbad3 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 591       ┆ 4355     │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 85        ┆ … ┆ 0.002701  ┆ 0.18578   ┆ 0161c35e6 ┆ db2b3cf3 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 591       ┆ 2508     │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 90        ┆ … ┆ 0.002542  ┆ 0.176492  ┆ 0161c35e6 ┆ ecf85c94 │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 591       ┆ b9e1     │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 95        ┆ … ┆ 0.002479  ┆ 0.172349  ┆ 0161c35e6 ┆ 749ea1ee │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 591       ┆ 9db6     │
│ fwd_ret_5 ┆ lstm_h64  ┆ epoch     ┆ 100       ┆ … ┆ 0.002283  ┆ 0.161031  ┆ 0161c35e6 ┆ eaea8faf │
│ d         ┆           ┆           ┆           ┆   ┆           ┆           ┆ 591       ┆ 4d86     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Verify checkpoint reload

Repeating the request validates the fitted-state digests and returns the same prediction
identities. The notebook never reconstructs another family from an empty cache path.

In [6]:
replayed = plan.run()
if set(replayed.catalog_rows.get_column("prediction_hash")) != set(
    catalog.get_column("prediction_hash")
):
    raise RuntimeError("LSTM checkpoint reload changed the prediction population")

if population is not None:
    population.require_complete()
    print(f"Official prediction population: {population.hash}")
else:
    print("Preview sequence checkpoints remain outside official comparisons.")

Official prediction population: e75cfb9b3998

## Key takeaways

- The LSTM, NLinear and TCN use the same sequence eligibility contract but keep separate model
  identities, so each is scored on the rows its own lookback leaves eligible.
- Gaps remove affected windows instead of being hidden by positional indexing.
- Stored weights reproduce every declared checkpoint without retraining.