# Holdout Predictions - FX Pairs

This notebook refits the one configuration validation selected, on the holdout interval, and
registers its predictions. It writes predictions and nothing else: the backtest is
`18_holdout_backtest`, and what any of it is worth is `19_strategy_analysis`.

Selection is not a parameter and is not made here. `resolve_solvent_carrier` reads the
highest-Sharpe registered validation backtest across the baseline, allocation and risk-overlay
stages, restricted to runs that stayed solvent, so this notebook cannot select a configuration
the validation stages did not already rank first.

The holdout is not a one-shot transaction and nothing here pre-registers it. There is no lock,
no seal and no gate: the whole rule is retrain the selected configuration on everything up to
the holdout window, predict, and backtest that same configuration on the result. Re-running is
therefore ordinary. A reader who runs it five hundred times and quotes the best number has
produced something uninterpretable, and that is a property of what they did rather than
something the software can prevent - the earlier design tried to, and bought
unfixability: a holdout found to be wrong after a bug fix could not be corrected, because the
lock was by construction the one artifact that could not be revised.

**Learning objectives**

- Derive a holdout interval from the panel's observation grid rather than the calendar.
- Reconstruct one training identity from an immutable validation specification.
- Register holdout predictions without giving them any influence over selection.

**Book reference**: Chapters 16-20

**Prerequisite**: `16_costs`. The selected configuration is resolved from the registered
validation backtests, so every stage that registers one must have run.

In [1]:
"""Refit the validation-selected FX configuration on the holdout interval."""

import polars as pl

from case_studies.research import open_study
from case_studies.research.comparison import CandidateSet
from case_studies.research.holdout import build_holdout_training_spec
from case_studies.research.models import (
    reconstruct_locked_model_request,
    validate_locked_model_run,
)
from case_studies.utils.strategy_analysis import resolve_solvent_carrier

In [2]:
CASE_STUDY_ID = "fx_pairs"
EXECUTION_TIER = "canonical"
WORKSPACE: str = ""
CANDIDATE_SET_NAME = "fx_pairs:holdout-candidates"

## Resolve the selection and the holdout interval it determines

The label the selection was made on decides which observation grid the holdout interval is
stepped back along, so it is read from the selected lineage rather than assumed. FX carries
three labels on one daily grid, which is exactly the coincidence that would let an assumption
here survive untested.

The training window ends a whole label buffer, counted in observations, before the holdout
opens, so the last training label's outcome cannot resolve inside the holdout. The buffer is
the widest this case study configures rather than the primary label's: a 21-day forward return
resolves three weeks after the session it is stamped on, and a 1-day buffer would leave three
weeks of holdout outcomes reachable from the training window.

In [3]:
study = open_study(CASE_STUDY_ID, execution_tier=EXECUTION_TIER, workspace=WORKSPACE or None)

# The selected configuration is the highest-Sharpe registered VALIDATION backtest across the
# baseline, allocation and risk-overlay stages, restricted to runs that stayed solvent. It is
# resolved from the registry rather than named here, so this notebook cannot select a configuration
# that the validation stages did not rank first. `15_risk_management` froze the set the holdout is
# allowed to choose from, and that set is passed into the resolution rather than checked against its
# answer. The two are different tests: when a conformal candidate is in the field the resolver
# re-ranks every candidate on the timestamps they all share, so a row that was never admitted still
# decides how far that intersection reaches and therefore which admitted row wins. fx has 194
# conformal backtests, so this is a live path here rather than a hypothetical one. Checking
# membership afterwards would pass while the answer had already been changed by an ineligible row.
holdout_candidates = CandidateSet.one(study, name=CANDIDATE_SET_NAME)
carrier = resolve_solvent_carrier(CASE_STUDY_ID, admitted=frozenset(holdout_candidates.members))
print(
    f"Frozen candidate set {holdout_candidates.hash}: "
    f"{len(holdout_candidates.members)} members, "
    f"raw-Sharpe pick {holdout_candidates.best_validation_sharpe().hash}"
)

validation_prediction = study.results.open(carrier["val_prediction_hash"])
prediction_record = validation_prediction.registry_record()
CHECKPOINT_KIND = prediction_record["checkpoint_kind"]
CHECKPOINT_VALUE = prediction_record["checkpoint_value"]

# The label the selected configuration was fitted on decides which observation grid the holdout
# interval is stepped back along, so it is read from the selected configuration rather than assumed.
# FX carries three labels on one daily grid, which is exactly the coincidence that would let an
# assumption here survive untested.
observation_timeline = (
    pl.read_parquet(study.root / "labels" / f"{carrier['label']}.parquet")
    .get_column("timestamp")
    .unique()
    .sort()
    .to_list()
)
validation_spec = study.results.open(carrier["training_hash"]).spec()
holdout_spec = build_holdout_training_spec(
    study,
    validation_spec,
    timeline=observation_timeline,
    case_study=CASE_STUDY_ID,
)
holdout_fold = holdout_spec["computation"]["cv"]["folds"][0]

pl.DataFrame(
    {
        "field": [
            "selected backtest",
            "selected stage",
            "validation Sharpe",
            "family",
            "configuration",
            "label",
            "checkpoint",
            "validation training",
            "validation prediction",
            "holdout train window",
            "holdout evaluation window",
        ],
        "value": [
            carrier["val_backtest_hash"],
            str(carrier["val_stage"]),
            f"{carrier['val_sharpe']:.4f}",
            str(carrier["family"]),
            str(carrier["config_name"]),
            str(carrier["label"]),
            f"{CHECKPOINT_KIND}={CHECKPOINT_VALUE}",
            str(carrier["training_hash"]),
            validation_prediction.hash,
            f"{holdout_fold['train_start']} to {holdout_fold['train_end']}",
            f"{holdout_fold['val_start']} to {holdout_fold['val_end']}",
        ],
    }
)

Frozen candidate set 07d118635d4d: 1794 members, raw-Sharpe pick 0c8d095371b6

shape: (11, 2)
┌───────────────────────────┬──────────────────────────┐
│ field                     ┆ value                    │
│ ---                       ┆ ---                      │
│ str                       ┆ str                      │
╞═══════════════════════════╪══════════════════════════╡
│ selected backtest         ┆ 0c8d095371b6             │
│ selected stage            ┆ allocation               │
│ validation Sharpe         ┆ 0.3091                   │
│ family                    ┆ deep_learning            │
│ configuration             ┆ lstm_h64                 │
│ …                         ┆ …                        │
│ checkpoint                ┆ epoch=35                 │
│ validation training       ┆ a802656900ee             │
│ validation prediction     ┆ b839846c1759             │
│ holdout train window      ┆ 2011-01-04 to 2023-11-29 │
│ holdout evaluation window ┆ 2024-01-01 to 2025-12-31 │
└───────────────────────────┴──────────────────────────┘

## Refit the selected configuration on the holdout fold

The request is reconstructed from the immutable validation specification with only the fold
geometry re-keyed, so the holdout model differs from the validation model in what it was
fitted on and in nothing else. It publishes the selected checkpoint alone: a holdout refit
that published its whole checkpoint schedule would hand the next notebook a choice, and
choosing among holdout checkpoints is selection on the holdout under another name.

The one thing checked afterwards that a specification cannot state about itself is that this
is a refit at all. A holdout training identity equal to the validation one means the fold
re-keying changed nothing, and the model is a validation fit predicting forward over a later
window rather than a model trained up to it.

In [4]:
request = reconstruct_locked_model_request(
    study,
    holdout_spec,
    checkpoint_kind=CHECKPOINT_KIND,
    checkpoint_value=CHECKPOINT_VALUE,
)
model_run = request.run()
if model_run.training.hash == carrier["training_hash"]:
    raise RuntimeError(
        f"the holdout refit produced the validation training identity "
        f"{carrier['training_hash']}, so it did not refit"
    )
if len(model_run.predictions) != 1:
    raise RuntimeError(
        f"the holdout refit published {len(model_run.predictions)} prediction sets; "
        "only the selected checkpoint may be published"
    )
prediction = model_run.predictions[0]

record = prediction.registry_record()
if record["split"] != "holdout":
    raise RuntimeError(f"the holdout refit published a {record['split']!r} prediction")
if record["checkpoint_kind"] != CHECKPOINT_KIND or record["checkpoint_value"] != CHECKPOINT_VALUE:
    raise RuntimeError(
        f"the holdout prediction is at checkpoint {record['checkpoint_kind']}="
        f"{record['checkpoint_value']}, not the carrier's {CHECKPOINT_KIND}={CHECKPOINT_VALUE}"
    )
if not prediction.complete:
    raise RuntimeError("the holdout prediction is incomplete")

# Completeness verifies the published prediction artifact, not that the persisted fitted state
# reproduces it. A cached run whose model state is missing or inconsistent passes the check
# above and fails only where someone tries to use the model again. The family's own validator
# reads that state and returns its digest, which is the one thing about this run that the
# specification cannot state about itself.
fitted_state_digest = validate_locked_model_run(request, model_run)

print(f"Holdout training run:   {model_run.training.hash}")
print(f"Fitted-state digest:    {fitted_state_digest}")
print(f"Holdout prediction set: {prediction.hash}")

Fold-major CV: 1 folds × 1 configs × 60 lookback

  Fold 8: creating sequences...

    train=57,940 seq across 20 symbols
    val=9,960 seq across 20 symbols
    creating datasets...

    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002410

      epoch   2/100: train_loss=0.000689

      epoch   3/100: train_loss=0.000634

      epoch   4/100: train_loss=0.000608

      epoch   5/100: train_loss=0.000587, val_loss=0.000462, IC=+0.0315

      epoch   6/100: train_loss=0.000562

      epoch   7/100: train_loss=0.000543

      epoch   8/100: train_loss=0.000517

      epoch   9/100: train_loss=0.000492

      epoch  10/100: train_loss=0.000468, val_loss=0.000507, IC=+0.0855

      epoch  11/100: train_loss=0.000444

      epoch  12/100: train_loss=0.000422

      epoch  13/100: train_loss=0.000398

      epoch  14/100: train_loss=0.000380

      epoch  15/100: train_loss=0.000357, val_loss=0.000588, IC=+0.0672

      epoch  16/100: train_loss=0.000336

      epoch  17/100: train_loss=0.000318

      epoch  18/100: train_loss=0.000304

      epoch  19/100: train_loss=0.000289

      epoch  20/100: train_loss=0.000273, val_loss=0.000670, IC=+0.0628

      epoch  21/100: train_loss=0.000259

      epoch  22/100: train_loss=0.000248

      epoch  23/100: train_loss=0.000238

      epoch  24/100: train_loss=0.000229

      epoch  25/100: train_loss=0.000219, val_loss=0.000747, IC=+0.0496

      epoch  26/100: train_loss=0.000208

      epoch  27/100: train_loss=0.000203

      epoch  28/100: train_loss=0.000197

      epoch  29/100: train_loss=0.000192

      epoch  30/100: train_loss=0.000184, val_loss=0.000796, IC=+0.0577

      epoch  31/100: train_loss=0.000180

      epoch  32/100: train_loss=0.000179

      epoch  33/100: train_loss=0.000168

      epoch  34/100: train_loss=0.000165

      epoch  35/100: train_loss=0.000163, val_loss=0.000840, IC=+0.0608

      epoch  36/100: train_loss=0.000154

      epoch  37/100: train_loss=0.000154

      epoch  38/100: train_loss=0.000150

      epoch  39/100: train_loss=0.000146

      epoch  40/100: train_loss=0.000144, val_loss=0.000898, IC=+0.0600

      epoch  41/100: train_loss=0.000141

      epoch  42/100: train_loss=0.000138

      epoch  43/100: train_loss=0.000135

      epoch  44/100: train_loss=0.000134

      epoch  45/100: train_loss=0.000131, val_loss=0.000879, IC=+0.0585

      epoch  46/100: train_loss=0.000131

      epoch  47/100: train_loss=0.000126

      epoch  48/100: train_loss=0.000125

      epoch  49/100: train_loss=0.000125

      epoch  50/100: train_loss=0.000122, val_loss=0.000954, IC=+0.0520

      epoch  51/100: train_loss=0.000120

      epoch  52/100: train_loss=0.000119

      epoch  53/100: train_loss=0.000117

      epoch  54/100: train_loss=0.000115

      epoch  55/100: train_loss=0.000114, val_loss=0.000960, IC=+0.0488

      epoch  56/100: train_loss=0.000114

      epoch  57/100: train_loss=0.000111

      epoch  58/100: train_loss=0.000111

      epoch  59/100: train_loss=0.000110

      epoch  60/100: train_loss=0.000110, val_loss=0.000981, IC=+0.0450

      epoch  61/100: train_loss=0.000108

      epoch  62/100: train_loss=0.000109

      epoch  63/100: train_loss=0.000107

      epoch  64/100: train_loss=0.000106

      epoch  65/100: train_loss=0.000104, val_loss=0.001022, IC=+0.0385

      epoch  66/100: train_loss=0.000104

      epoch  67/100: train_loss=0.000104

      epoch  68/100: train_loss=0.000103

      epoch  69/100: train_loss=0.000103

      epoch  70/100: train_loss=0.000102, val_loss=0.001032, IC=+0.0361

      epoch  71/100: train_loss=0.000101

      epoch  72/100: train_loss=0.000101

      epoch  73/100: train_loss=0.000100

      epoch  74/100: train_loss=0.000100

      epoch  75/100: train_loss=0.000099, val_loss=0.001045, IC=+0.0359

      epoch  76/100: train_loss=0.000098

      epoch  77/100: train_loss=0.000098

      epoch  78/100: train_loss=0.000098

      epoch  79/100: train_loss=0.000097

      epoch  80/100: train_loss=0.000097, val_loss=0.001057, IC=+0.0346

      epoch  81/100: train_loss=0.000096

      epoch  82/100: train_loss=0.000097

      epoch  83/100: train_loss=0.000096

      epoch  84/100: train_loss=0.000096

      epoch  85/100: train_loss=0.000096, val_loss=0.001049, IC=+0.0340

      epoch  86/100: train_loss=0.000096

      epoch  87/100: train_loss=0.000096

      epoch  88/100: train_loss=0.000095

      epoch  89/100: train_loss=0.000095

      epoch  90/100: train_loss=0.000095, val_loss=0.001061, IC=+0.0337

      epoch  91/100: train_loss=0.000095

      epoch  92/100: train_loss=0.000095

      epoch  93/100: train_loss=0.000095

      epoch  94/100: train_loss=0.000094

      epoch  95/100: train_loss=0.000094, val_loss=0.001069, IC=+0.0334

      epoch  96/100: train_loss=0.000094

      epoch  97/100: train_loss=0.000094

      epoch  98/100: train_loss=0.000094

      epoch  99/100: train_loss=0.000095

      epoch 100/100: train_loss=0.000095, val_loss=0.001064, IC=+0.0334

      best_ep=10, IC=+0.0855 (52.1s, 20 checkpoints)

  lstm_h64: best_epoch=10, IC=+0.0855 (52.1s)

  Best: lstm_h64 @ epoch 10 (IC=+0.0855)
  Saved to case_studies/fx_pairs/run_log/training/619480dade83/diagnostics

Holdout training run:   619480dade83
Fitted-state digest:    09d4c072ac77e81e3e8a590b5edefe6b37009f96d82570b825db753284b47d20
Holdout prediction set: f99025b8a76b

## What the holdout refit covers

The coverage is printed rather than assumed: a holdout prediction set that silently covers a
shorter window than the fold declares would make every number downstream a measurement of a
different interval than the one this notebook says it measured.

In [5]:
frame = prediction.load()
coverage = pl.DataFrame(
    {
        "field": ["prediction", "rows", "symbols", "sessions", "first session", "last session"],
        "value": [
            prediction.hash,
            str(frame.height),
            str(frame.get_column("symbol").n_unique()),
            str(frame.get_column("timestamp").n_unique()),
            str(frame.get_column("timestamp").min()),
            str(frame.get_column("timestamp").max()),
        ],
    }
)
coverage

shape: (6, 2)
┌───────────────┬───────────────────────────┐
│ field         ┆ value                     │
│ ---           ┆ ---                       │
│ str           ┆ str                       │
╞═══════════════╪═══════════════════════════╡
│ prediction    ┆ f99025b8a76b              │
│ rows          ┆ 9960                      │
│ symbols       ┆ 20                        │
│ sessions      ┆ 498                       │
│ first session ┆ 2024-01-02 00:00:00+00:00 │
│ last session  ┆ 2025-12-01 00:00:00+00:00 │
└───────────────┴───────────────────────────┘

## Key takeaways

- The configuration refitted here was selected on validation, from an immutable set, upstream.
- The holdout training window stops a full label buffer short of the holdout, counted in
  observations rather than calendar days.
- Only the selected checkpoint is published, so no choice among holdout results remains to be
  made downstream.