# CME Futures: Linear Models

This notebook fits the declared linear-model population for both return horizons. Each model
configuration uses the same walk-forward folds and eligibility rules established by
`05_evaluation`. Ridge, Lasso, and ElasticNet differ only in their regularization parameters.

The notebook executes models and publishes complete validation predictions. `13_backtest`
evaluates every configuration and checkpoint with the equal-weight signal baseline. Validation
backtest Sharpe performs selection.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit the declared CME futures linear-model population."""

import polars as pl

from case_studies.cme_futures.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    product_universe_table,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_catalog,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None
PREVIEW_REDUCTIONS: dict = {}
# The population hash this run replaces, read from the registry and set by a person. A
# first population takes None; a re-run whose membership has changed is refused without
# the hash it supersedes, and the refusal names the value required.
SUPERSEDES_POPULATION: str | None = None

## Declared requests

The request table is the model population. A canonical run snapshots every expected prediction
identity before fitting, including every declared checkpoint. A preview must name its reductions
and writes to a separate workspace.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE)
requests = model_request_catalog("linear", labels=ALL_LABELS)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    preview_reductions=PREVIEW_REDUCTIONS,
)
universe = product_universe_table()
universe

shape: (30, 4)
┌─────────────┬─────────┬──────────────────────────┬─────────────────┐
│ sector      ┆ product ┆ expiry_rule              ┆ contract_months │
│ ---         ┆ ---     ┆ ---                      ┆ ---             │
│ str         ┆ str     ┆ str                      ┆ str             │
╞═════════════╪═════════╪══════════════════════════╪═════════════════╡
│ agriculture ┆ ZC      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ agriculture ┆ ZL      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZM      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZS      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,X   │
│ agriculture ┆ ZW      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ …           ┆ …       ┆ …                        ┆ …               │
│ metals      ┆ SI      ┆ 3rd_last_business_day    ┆ H,K,N,U,Z       │
│ treasuries  ┆ ZB      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZF      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZN      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZT      ┆ last_business_day        ┆ H,M,U,Z         │
└─────────────┴─────────┴──────────────────────────┴─────────────────┘

In [4]:
resolved_model_plan(resolved)

shape: (56, 13)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ family ┆ label      ┆ config_nam ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training_ │
│ ---    ┆ ---        ┆ e          ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ hash      │
│ str    ┆ str        ┆ ---        ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│        ┆            ┆ str        ┆           ┆   ┆ date      ┆ i64       ┆ str       ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ linear ┆ fwd_ret_21 ┆ enet_f0.01 ┆ regressio ┆ … ┆ 2023-11-2 ┆ 1         ┆ canonical ┆ f2c5ff96d │
│        ┆ d          ┆ 5          ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 40a       │
│ linear ┆ fwd_ret_21 ┆ enet_f0.03 ┆ regressio ┆ … ┆ 2023-11-2 ┆ 1         ┆ canonical ┆ 0416a1995 │
│        ┆ d          ┆            ┆ n         ┆   ┆ 9         ┆           ┆           ┆ dff       │
│ linear ┆ fwd_ret_21 ┆ enet_f0.08 ┆ regressio ┆ … ┆ 2023-11-2 ┆ 1         ┆ canonical ┆ 1c878f0c9 │
│        ┆ d          ┆            ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 9fb       │
│ linear ┆ fwd_ret_21 ┆ enet_f0.2  ┆ regressio ┆ … ┆ 2023-11-2 ┆ 1         ┆ canonical ┆ a524753d5 │
│        ┆ d          ┆            ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 248       │
│ linear ┆ fwd_ret_21 ┆ enet_f0.35 ┆ regressio ┆ … ┆ 2023-11-2 ┆ 1         ┆ canonical ┆ 9b9c139b4 │
│        ┆ d          ┆            ┆ n         ┆   ┆ 9         ┆           ┆           ┆ dad       │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ regressio ┆ … ┆ 2023-12-2 ┆ 1         ┆ canonical ┆ 0898b6bee │
│        ┆            ┆ 0.0        ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 178       │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ regressio ┆ … ┆ 2023-12-2 ┆ 1         ┆ canonical ┆ 6cbd76f17 │
│        ┆            ┆ 00.0       ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 3ef       │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ regressio ┆ … ┆ 2023-12-2 ┆ 1         ┆ canonical ┆ cef0fb04a │
│        ┆            ┆ 000.0      ┆ n         ┆   ┆ 1         ┆           ┆           ┆ c50       │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ regressio ┆ … ┆ 2023-12-2 ┆ 1         ┆ canonical ┆ 703407354 │
│        ┆            ┆ 0000.0     ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 73b       │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ regressio ┆ … ┆ 2023-12-2 ┆ 1         ┆ canonical ┆ b5d26e47a │
│        ┆            ┆ 00000.0    ┆ n         ┆   ┆ 1         ┆           ┆           ┆ ec0       │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Execute and validate

The shared linear runner owns preprocessing, fold fitting, fitted-state digests, restart, metric
computation, and exact eligible-key checks. Any missing or partial member fails the cell.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_catalog(
        study,
        requests,
        population_name="cme-linear-validation-v1",
        resolved_requests=resolved,
        supersedes=SUPERSEDES_POPULATION,
    )
else:
    if WORKSPACE is None or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("label", "config_name", "checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("linear execution returned a partial prediction")
catalog

shape: (56, 9)
┌────────┬────────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family ┆ label      ┆ config_nam ┆ checkpoint ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---    ┆ ---        ┆ e          ┆ _kind      ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str    ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│        ┆            ┆ str        ┆ str        ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞════════╪════════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ linear ┆ fwd_ret_21 ┆ enet_f0.01 ┆ final      ┆ … ┆ canonical ┆ true     ┆ f2c5ff96d ┆ 133106340 │
│        ┆ d          ┆ 5          ┆            ┆   ┆           ┆          ┆ 40a       ┆ e01       │
│ linear ┆ fwd_ret_21 ┆ enet_f0.03 ┆ final      ┆ … ┆ canonical ┆ true     ┆ 0416a1995 ┆ e593217bf │
│        ┆ d          ┆            ┆            ┆   ┆           ┆          ┆ dff       ┆ 8ab       │
│ linear ┆ fwd_ret_21 ┆ enet_f0.08 ┆ final      ┆ … ┆ canonical ┆ true     ┆ 1c878f0c9 ┆ a066c4f80 │
│        ┆ d          ┆            ┆            ┆   ┆           ┆          ┆ 9fb       ┆ cd4       │
│ linear ┆ fwd_ret_21 ┆ enet_f0.2  ┆ final      ┆ … ┆ canonical ┆ true     ┆ a524753d5 ┆ 9498307c8 │
│        ┆ d          ┆            ┆            ┆   ┆           ┆          ┆ 248       ┆ 690       │
│ linear ┆ fwd_ret_21 ┆ enet_f0.35 ┆ final      ┆ … ┆ canonical ┆ true     ┆ 9b9c139b4 ┆ 637fcfd62 │
│        ┆ d          ┆            ┆            ┆   ┆           ┆          ┆ dad       ┆ 45b       │
│ …      ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ final      ┆ … ┆ canonical ┆ true     ┆ 0898b6bee ┆ 0ec3a8658 │
│        ┆            ┆ 0.0        ┆            ┆   ┆           ┆          ┆ 178       ┆ 52d       │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ final      ┆ … ┆ canonical ┆ true     ┆ 6cbd76f17 ┆ 0dec31d85 │
│        ┆            ┆ 00.0       ┆            ┆   ┆           ┆          ┆ 3ef       ┆ 309       │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ final      ┆ … ┆ canonical ┆ true     ┆ cef0fb04a ┆ ad5bc475c │
│        ┆            ┆ 000.0      ┆            ┆   ┆           ┆          ┆ c50       ┆ 886       │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ final      ┆ … ┆ canonical ┆ true     ┆ 703407354 ┆ 2d0f57867 │
│        ┆            ┆ 0000.0     ┆            ┆   ┆           ┆          ┆ 73b       ┆ dc2       │
│ linear ┆ fwd_ret_5d ┆ ridge_a100 ┆ final      ┆ … ┆ canonical ┆ true     ┆ b5d26e47a ┆ 43a0684af │
│        ┆            ┆ 00000.0    ┆            ┆   ┆           ┆          ┆ ec0       ┆ e27       │
└────────┴────────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘