# CME Futures: Tabular Deep Learning

TabM applies a parameter-efficient neural ensemble to the same point-in-time feature rows used by
the linear and gradient-boosting families. The declared configurations vary model capacity while
retaining the walk-forward fold and label contracts from `05_evaluation`.

The shared runner publishes every declared epoch checkpoint with its fitted weights and exact
validation coverage. The equal-weight validation backtest in `13_backtest` evaluates all
checkpoints and selects by Sharpe.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit the declared CME futures TabM population."""

import polars as pl

from case_studies.cme_futures.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    product_universe_table,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_catalog,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None
PREVIEW_REDUCTIONS: dict = {}
# The population hash this run replaces, read from the registry and set by a person. A
# first population takes None; a re-run whose membership has changed is refused without
# the hash it supersedes, and the refusal names the value required.
SUPERSEDES_POPULATION: str | None = None

## Declared requests

Both configured return horizons enter the same visible request table. Preview epoch or fold limits
must be passed through `PREVIEW_REDUCTIONS`, which changes identity and excludes the output from
the canonical catalog.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE)
requests = model_request_catalog("tabular_dl", labels=ALL_LABELS)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    preview_reductions=PREVIEW_REDUCTIONS,
)
universe = product_universe_table()
universe

shape: (30, 4)
┌─────────────┬─────────┬──────────────────────────┬─────────────────┐
│ sector      ┆ product ┆ expiry_rule              ┆ contract_months │
│ ---         ┆ ---     ┆ ---                      ┆ ---             │
│ str         ┆ str     ┆ str                      ┆ str             │
╞═════════════╪═════════╪══════════════════════════╪═════════════════╡
│ agriculture ┆ ZC      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ agriculture ┆ ZL      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZM      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZS      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,X   │
│ agriculture ┆ ZW      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ …           ┆ …       ┆ …                        ┆ …               │
│ metals      ┆ SI      ┆ 3rd_last_business_day    ┆ H,K,N,U,Z       │
│ treasuries  ┆ ZB      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZF      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZN      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZT      ┆ last_business_day        ┆ H,M,U,Z         │
└─────────────┴─────────┴──────────────────────────┴─────────────────┘

In [4]:
resolved_model_plan(resolved)

shape: (6, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ date      ┆ i64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ f824d83a │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 2e1a     │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_m    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ 5b840983 │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ aaef     │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_s    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ d461f9ac │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ ebf6     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_l    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ 45b5549a │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 1aab     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_m    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ 92405002 │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ a0cd     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ c9f822b2 │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 57fe     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

Fold-scoped preprocessing, seeded training, fitted-state persistence, checkpoint membership, and
prediction eligibility are enforced by the shared TabM adapter.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_catalog(
        study,
        requests,
        population_name="cme-tabular-dl-validation-v1",
        resolved_requests=resolved,
        supersedes=SUPERSEDES_POPULATION,
    )
else:
    if WORKSPACE is None or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Preparing and releasing folds...

  Fold 0: train=60,680  val=7,518

      epoch  25/200: loss=0.000955, IC=-0.0549

      epoch  50/200: loss=0.000796, IC=-0.0502

      epoch  75/200: loss=0.000714, IC=-0.0393

      epoch 100/200: loss=0.000676, IC=-0.0348

      epoch 125/200: loss=0.000657, IC=-0.0360

      epoch 150/200: loss=0.000645, IC=-0.0326

      epoch 175/200: loss=0.000636, IC=-0.0346

      epoch 200/200: loss=0.000642, IC=-0.0347

    Fold 0: best_ep=150, IC=-0.0326 (11.6s)

  Fold 1: train=60,337  val=7,684

      epoch  25/200: loss=0.000817, IC=+0.0384

      epoch  50/200: loss=0.000674, IC=+0.0600

      epoch  75/200: loss=0.000621, IC=+0.0663

      epoch 100/200: loss=0.000582, IC=+0.0632

      epoch 125/200: loss=0.000563, IC=+0.0643

      epoch 150/200: loss=0.000555, IC=+0.0580

      epoch 175/200: loss=0.000547, IC=+0.0553

      epoch 200/200: loss=0.000551, IC=+0.0563

    Fold 1: best_ep=75, IC=+0.0663 (10.6s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000758, IC=-0.0421

      epoch  50/200: loss=0.000634, IC=-0.0273

      epoch  75/200: loss=0.000585, IC=-0.0246

      epoch 100/200: loss=0.000554, IC=-0.0328

      epoch 125/200: loss=0.000534, IC=-0.0252

      epoch 150/200: loss=0.000525, IC=-0.0233

      epoch 175/200: loss=0.000514, IC=-0.0200

      epoch 200/200: loss=0.000517, IC=-0.0208

    Fold 2: best_ep=175, IC=-0.0200 (10.0s)

  Fold 3: train=59,738  val=7,692

      epoch  25/200: loss=0.000616, IC=-0.0118

      epoch  50/200: loss=0.000528, IC=-0.0364

      epoch  75/200: loss=0.000490, IC=-0.0599

      epoch 100/200: loss=0.000464, IC=-0.0707

      epoch 125/200: loss=0.000452, IC=-0.0671

      epoch 150/200: loss=0.000444, IC=-0.0684

      epoch 175/200: loss=0.000436, IC=-0.0689

      epoch 200/200: loss=0.000438, IC=-0.0687

    Fold 3: best_ep=25, IC=-0.0118 (10.1s)

  Fold 4: train=58,879  val=7,692

      epoch  25/200: loss=0.000690, IC=+0.0105

      epoch  50/200: loss=0.000573, IC=+0.0015

      epoch  75/200: loss=0.000519, IC=-0.0014

      epoch 100/200: loss=0.000493, IC=-0.0110

      epoch 125/200: loss=0.000479, IC=-0.0148

      epoch 150/200: loss=0.000465, IC=-0.0119

      epoch 175/200: loss=0.000463, IC=-0.0206

      epoch 200/200: loss=0.000460, IC=-0.0220

    Fold 4: best_ep=25, IC=+0.0105 (9.8s)

    → best_epoch=50, IC=-0.0103 (52.1s)

  Best: c9f822b257fe @ epoch 50 (IC=-0.0103)

Preparing and releasing folds...

  Fold 0: train=60,680  val=7,518

      epoch  25/200: loss=0.000715, IC=-0.0325

      epoch  50/200: loss=0.000551, IC=-0.0078

      epoch  75/200: loss=0.000497, IC=+0.0032

      epoch 100/200: loss=0.000456, IC=+0.0167

      epoch 125/200: loss=0.000432, IC=+0.0021

      epoch 150/200: loss=0.000422, IC=-0.0018

      epoch 175/200: loss=0.000419, IC=-0.0004

      epoch 200/200: loss=0.000416, IC=-0.0003

    Fold 0: best_ep=100, IC=+0.0167 (12.6s)

  Fold 1: train=60,337  val=7,684

      epoch  25/200: loss=0.000603, IC=+0.0284

      epoch  50/200: loss=0.000494, IC=+0.0413

      epoch  75/200: loss=0.000430, IC=+0.0331

      epoch 100/200: loss=0.000399, IC=+0.0388

      epoch 125/200: loss=0.000386, IC=+0.0415

      epoch 150/200: loss=0.000372, IC=+0.0442

      epoch 175/200: loss=0.000366, IC=+0.0431

      epoch 200/200: loss=0.000360, IC=+0.0449

    Fold 1: best_ep=200, IC=+0.0449 (12.9s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000590, IC=-0.0413

      epoch  50/200: loss=0.000472, IC=-0.0241

      epoch  75/200: loss=0.000417, IC=-0.0236

      epoch 100/200: loss=0.000390, IC=-0.0219

      epoch 125/200: loss=0.000370, IC=-0.0253

      epoch 150/200: loss=0.000358, IC=-0.0256

      epoch 175/200: loss=0.000351, IC=-0.0267

      epoch 200/200: loss=0.000353, IC=-0.0262

    Fold 2: best_ep=100, IC=-0.0219 (12.8s)

  Fold 3: train=59,738  val=7,692

      epoch  25/200: loss=0.000506, IC=-0.0399

      epoch  50/200: loss=0.000389, IC=-0.0375

      epoch  75/200: loss=0.000345, IC=-0.0427

      epoch 100/200: loss=0.000317, IC=-0.0510

      epoch 125/200: loss=0.000300, IC=-0.0509

      epoch 150/200: loss=0.000295, IC=-0.0483

      epoch 175/200: loss=0.000292, IC=-0.0506

      epoch 200/200: loss=0.000290, IC=-0.0501

    Fold 3: best_ep=50, IC=-0.0375 (12.6s)

  Fold 4: train=58,879  val=7,692

      epoch  25/200: loss=0.000503, IC=-0.0309

      epoch  50/200: loss=0.000396, IC=-0.0307

      epoch  75/200: loss=0.000352, IC=-0.0359

      epoch 100/200: loss=0.000323, IC=-0.0267

      epoch 125/200: loss=0.000307, IC=-0.0190

      epoch 150/200: loss=0.000300, IC=-0.0113

      epoch 175/200: loss=0.000299, IC=-0.0050

      epoch 200/200: loss=0.000295, IC=-0.0067

    Fold 4: best_ep=175, IC=-0.0050 (13.4s)

    → best_epoch=200, IC=-0.0077 (64.5s)

  Best: 92405002a0cd @ epoch 200 (IC=-0.0077)

Preparing and releasing folds...

  Fold 0: train=60,680  val=7,518

      epoch  25/200: loss=0.000610, IC=+0.0457

      epoch  50/200: loss=0.000412, IC=+0.0411

      epoch  75/200: loss=0.000334, IC=+0.0425

      epoch 100/200: loss=0.000295, IC=+0.0373

      epoch 125/200: loss=0.000276, IC=+0.0272

      epoch 150/200: loss=0.000265, IC=+0.0250

      epoch 175/200: loss=0.000255, IC=+0.0261

      epoch 200/200: loss=0.000256, IC=+0.0248

    Fold 0: best_ep=25, IC=+0.0457 (17.7s)

  Fold 1: train=60,337  val=7,684

      epoch  25/200: loss=0.000457, IC=+0.0615

      epoch  50/200: loss=0.000327, IC=+0.0469

      epoch  75/200: loss=0.000275, IC=+0.0360

      epoch 100/200: loss=0.000249, IC=+0.0353

      epoch 125/200: loss=0.000231, IC=+0.0346

      epoch 150/200: loss=0.000223, IC=+0.0278

      epoch 175/200: loss=0.000214, IC=+0.0285

      epoch 200/200: loss=0.000217, IC=+0.0293

    Fold 1: best_ep=25, IC=+0.0615 (19.1s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000463, IC=-0.0083

      epoch  50/200: loss=0.000321, IC=-0.0167

      epoch  75/200: loss=0.000264, IC=-0.0084

      epoch 100/200: loss=0.000236, IC=-0.0142

      epoch 125/200: loss=0.000219, IC=-0.0036

      epoch 150/200: loss=0.000209, IC=-0.0055

      epoch 175/200: loss=0.000207, IC=-0.0078

      epoch 200/200: loss=0.000204, IC=-0.0074

    Fold 2: best_ep=125, IC=-0.0036 (19.4s)

  Fold 3: train=59,738  val=7,692

      epoch  25/200: loss=0.000368, IC=-0.0437

      epoch  50/200: loss=0.000261, IC=-0.0367

      epoch  75/200: loss=0.000222, IC=-0.0344

      epoch 100/200: loss=0.000192, IC=-0.0211

      epoch 125/200: loss=0.000181, IC=-0.0202

      epoch 150/200: loss=0.000176, IC=-0.0197

      epoch 175/200: loss=0.000169, IC=-0.0222

      epoch 200/200: loss=0.000169, IC=-0.0213

    Fold 3: best_ep=150, IC=-0.0197 (18.2s)

  Fold 4: train=58,879  val=7,692

      epoch  25/200: loss=0.000374, IC=+0.0067

      epoch  50/200: loss=0.000271, IC=-0.0091

      epoch  75/200: loss=0.000227, IC=-0.0083

      epoch 100/200: loss=0.000206, IC=-0.0086

      epoch 125/200: loss=0.000192, IC=-0.0089

      epoch 150/200: loss=0.000182, IC=-0.0070

      epoch 175/200: loss=0.000180, IC=-0.0102

      epoch 200/200: loss=0.000180, IC=-0.0105

    Fold 4: best_ep=25, IC=+0.0067 (18.7s)

    → best_epoch=25, IC=+0.0122 (93.2s)

  Best: 45b5549a1aab @ epoch 25 (IC=+0.0122)

Preparing and releasing folds...

  Fold 0: train=60,200  val=7,038

      epoch  25/200: loss=0.002457, IC=-0.0091

      epoch  50/200: loss=0.001898, IC=-0.0054

      epoch  75/200: loss=0.001676, IC=-0.0034

      epoch 100/200: loss=0.001546, IC=-0.0007

      epoch 125/200: loss=0.001489, IC=-0.0050

      epoch 150/200: loss=0.001451, IC=+0.0006

      epoch 175/200: loss=0.001398, IC=+0.0039

      epoch 200/200: loss=0.001431, IC=+0.0024

    Fold 0: best_ep=175, IC=+0.0039 (11.5s)

  Fold 1: train=59,857  val=7,684

      epoch  25/200: loss=0.002227, IC=+0.0371

      epoch  50/200: loss=0.001684, IC=+0.0375

      epoch  75/200: loss=0.001466, IC=+0.0367

      epoch 100/200: loss=0.001341, IC=+0.0271

      epoch 125/200: loss=0.001281, IC=+0.0299

      epoch 150/200: loss=0.001264, IC=+0.0276

      epoch 175/200: loss=0.001255, IC=+0.0251

      epoch 200/200: loss=0.001245, IC=+0.0257

    Fold 1: best_ep=50, IC=+0.0375 (11.3s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.002116, IC=-0.0962

      epoch  50/200: loss=0.001568, IC=-0.0842

      epoch  75/200: loss=0.001389, IC=-0.0934

      epoch 100/200: loss=0.001293, IC=-0.0914

      epoch 125/200: loss=0.001219, IC=-0.0863

      epoch 150/200: loss=0.001197, IC=-0.0901

      epoch 175/200: loss=0.001188, IC=-0.0846

      epoch 200/200: loss=0.001167, IC=-0.0852

    Fold 2: best_ep=50, IC=-0.0842 (11.5s)

  Fold 3: train=59,210  val=7,692

      epoch  25/200: loss=0.001698, IC=-0.0357

      epoch  50/200: loss=0.001299, IC=-0.1173

      epoch  75/200: loss=0.001140, IC=-0.1213

      epoch 100/200: loss=0.001062, IC=-0.1247

      epoch 125/200: loss=0.001024, IC=-0.1296

      epoch 150/200: loss=0.000992, IC=-0.1225

      epoch 175/200: loss=0.000981, IC=-0.1283

      epoch 200/200: loss=0.000981, IC=-0.1268

    Fold 3: best_ep=25, IC=-0.0357 (10.5s)

  Fold 4: train=58,325  val=7,692

      epoch  25/200: loss=0.001890, IC=+0.0322

      epoch  50/200: loss=0.001426, IC=+0.0488

      epoch  75/200: loss=0.001238, IC=+0.0366

      epoch 100/200: loss=0.001149, IC=+0.0333

      epoch 125/200: loss=0.001092, IC=+0.0374

      epoch 150/200: loss=0.001079, IC=+0.0275

      epoch 175/200: loss=0.001059, IC=+0.0256

      epoch 200/200: loss=0.001048, IC=+0.0246

    Fold 4: best_ep=50, IC=+0.0488 (11.0s)

    → best_epoch=25, IC=-0.0144 (55.8s)

  Best: d461f9acebf6 @ epoch 25 (IC=-0.0144)

Preparing and releasing folds...

  Fold 0: train=60,200  val=7,038

      epoch  25/200: loss=0.001699, IC=-0.0158

      epoch  50/200: loss=0.001192, IC=+0.0026

      epoch  75/200: loss=0.001002, IC=+0.0078

      epoch 100/200: loss=0.000920, IC=+0.0207

      epoch 125/200: loss=0.000861, IC=+0.0195

      epoch 150/200: loss=0.000830, IC=+0.0195

      epoch 175/200: loss=0.000812, IC=+0.0185

      epoch 200/200: loss=0.000807, IC=+0.0185

    Fold 0: best_ep=100, IC=+0.0207 (14.2s)

  Fold 1: train=59,857  val=7,684

      epoch  25/200: loss=0.001557, IC=+0.0102

      epoch  50/200: loss=0.001106, IC=+0.0002

      epoch  75/200: loss=0.000938, IC=+0.0034

      epoch 100/200: loss=0.000830, IC=-0.0037

      epoch 125/200: loss=0.000773, IC=+0.0009

      epoch 150/200: loss=0.000748, IC=+0.0012

      epoch 175/200: loss=0.000736, IC=+0.0032

      epoch 200/200: loss=0.000731, IC=+0.0012

    Fold 1: best_ep=25, IC=+0.0102 (14.4s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.001486, IC=-0.0880

      epoch  50/200: loss=0.001055, IC=-0.0877

      epoch  75/200: loss=0.000892, IC=-0.0940

      epoch 100/200: loss=0.000785, IC=-0.0842

      epoch 125/200: loss=0.000735, IC=-0.0780

      epoch 150/200: loss=0.000718, IC=-0.0720

      epoch 175/200: loss=0.000710, IC=-0.0714

      epoch 200/200: loss=0.000697, IC=-0.0712

    Fold 2: best_ep=200, IC=-0.0712 (14.0s)

  Fold 3: train=59,210  val=7,692

      epoch  25/200: loss=0.001166, IC=-0.0483

      epoch  50/200: loss=0.000818, IC=-0.0587

      epoch  75/200: loss=0.000686, IC=-0.0581

      epoch 100/200: loss=0.000627, IC=-0.0656

      epoch 125/200: loss=0.000587, IC=-0.0673

      epoch 150/200: loss=0.000569, IC=-0.0661

      epoch 175/200: loss=0.000550, IC=-0.0675

      epoch 200/200: loss=0.000558, IC=-0.0679

    Fold 3: best_ep=25, IC=-0.0483 (14.0s)

  Fold 4: train=58,325  val=7,692

      epoch  25/200: loss=0.001240, IC=+0.0066

      epoch  50/200: loss=0.000891, IC=+0.0113

      epoch  75/200: loss=0.000756, IC=-0.0068

      epoch 100/200: loss=0.000687, IC=-0.0609

      epoch 125/200: loss=0.000647, IC=-0.0279

      epoch 150/200: loss=0.000625, IC=-0.0480

      epoch 175/200: loss=0.000615, IC=-0.0390

      epoch 200/200: loss=0.000611, IC=-0.0403

    Fold 4: best_ep=50, IC=+0.0113 (13.7s)

    → best_epoch=50, IC=-0.0270 (70.4s)

  Best: 5b840983aaef @ epoch 50 (IC=-0.0270)

Preparing and releasing folds...

  Fold 0: train=60,200  val=7,038

      epoch  25/200: loss=0.001143, IC=+0.0375

      epoch  50/200: loss=0.000730, IC=+0.0598

      epoch  75/200: loss=0.000600, IC=+0.0656

      epoch 100/200: loss=0.000532, IC=+0.0809

      epoch 125/200: loss=0.000485, IC=+0.0741

      epoch 150/200: loss=0.000462, IC=+0.0751

      epoch 175/200: loss=0.000456, IC=+0.0792

      epoch 200/200: loss=0.000447, IC=+0.0765

    Fold 0: best_ep=100, IC=+0.0809 (17.2s)

  Fold 1: train=59,857  val=7,684

      epoch  25/200: loss=0.001005, IC=-0.0303

      epoch  50/200: loss=0.000658, IC=-0.0365

      epoch  75/200: loss=0.000534, IC=-0.0422

      epoch 100/200: loss=0.000471, IC=-0.0319

      epoch 125/200: loss=0.000438, IC=-0.0273

      epoch 150/200: loss=0.000413, IC=-0.0210

      epoch 175/200: loss=0.000404, IC=-0.0216

      epoch 200/200: loss=0.000402, IC=-0.0221

    Fold 1: best_ep=150, IC=-0.0210 (19.4s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.000936, IC=-0.0650

      epoch  50/200: loss=0.000608, IC=-0.0567

      epoch  75/200: loss=0.000505, IC=-0.0559

      epoch 100/200: loss=0.000453, IC=-0.0594

      epoch 125/200: loss=0.000413, IC=-0.0570

      epoch 150/200: loss=0.000390, IC=-0.0539

      epoch 175/200: loss=0.000379, IC=-0.0554

      epoch 200/200: loss=0.000377, IC=-0.0542

    Fold 2: best_ep=150, IC=-0.0539 (18.8s)

  Fold 3: train=59,210  val=7,692

      epoch  25/200: loss=0.000765, IC=-0.0697

      epoch  50/200: loss=0.000502, IC=-0.0935

      epoch  75/200: loss=0.000411, IC=-0.1058

      epoch 100/200: loss=0.000365, IC=-0.1158

      epoch 125/200: loss=0.000338, IC=-0.1086

      epoch 150/200: loss=0.000318, IC=-0.1044

      epoch 175/200: loss=0.000316, IC=-0.1073

      epoch 200/200: loss=0.000314, IC=-0.1063

    Fold 3: best_ep=25, IC=-0.0697 (17.8s)

  Fold 4: train=58,325  val=7,692

      epoch  25/200: loss=0.000841, IC=+0.0767

      epoch  50/200: loss=0.000561, IC=+0.0155

      epoch  75/200: loss=0.000459, IC=-0.0039

      epoch 100/200: loss=0.000407, IC=-0.0005

      epoch 125/200: loss=0.000375, IC=-0.0010

      epoch 150/200: loss=0.000354, IC=+0.0002

      epoch 175/200: loss=0.000346, IC=+0.0029

      epoch 200/200: loss=0.000347, IC=+0.0032

    Fold 4: best_ep=25, IC=+0.0767 (16.9s)

    → best_epoch=25, IC=-0.0109 (90.2s)

  Best: f824d83a2e1a @ epoch 25 (IC=-0.0109)

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("label", "config_name", "checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("TabM execution returned a partial prediction")
catalog

shape: (48, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f824d83a2 ┆ 25f47db03 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ e1a       ┆ b7c       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f824d83a2 ┆ 591b4daf8 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ e1a       ┆ ec0       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f824d83a2 ┆ 72af89777 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ e1a       ┆ 5ca       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f824d83a2 ┆ 97d642b87 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ e1a       ┆ 356       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ f824d83a2 ┆ b6f732b56 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ e1a       ┆ 25a       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c9f822b25 ┆ a647df582 │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 7fe       ┆ 347       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c9f822b25 ┆ 461e33cb7 │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 7fe       ┆ 489       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c9f822b25 ┆ a4d467f15 │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 7fe       ┆ 2e0       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c9f822b25 ┆ e6b5b4ebc │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 7fe       ┆ 49b       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c9f822b25 ┆ ead8bd454 │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 7fe       ┆ 2fd       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘