# CME Futures: Tabular Deep Learning

TabM applies a parameter-efficient neural ensemble to the same point-in-time feature rows used by
the linear and gradient-boosting families. The declared configurations vary model capacity while
retaining the walk-forward fold and label contracts from `05_evaluation`.

The shared runner publishes every declared epoch checkpoint with its fitted weights and exact
validation coverage. The equal-weight validation backtest in `13_backtest` evaluates all
checkpoints and selects by Sharpe.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

## Why a neural network on a feature table at all

Deep learning earned its reputation on images, audio and text, where the input has structure a
network can exploit: neighbouring pixels are related, words have order, and the architecture is
built to reflect that. A table of engineered features has none of it. Columns can be permuted
with no loss of meaning, and there is no locality for a convolution to use or a sequence for a
recurrence to traverse.

On that kind of input, gradient-boosted trees remain the standard to beat, and they beat neural
networks often enough that "tabular deep learning" is a live research area rather than a
settled one. Trees handle mixed scales without preprocessing, ignore irrelevant columns almost
for free, and split on thresholds - which is exactly the shape of many real relationships in a
feature table, where an effect appears above some level of a variable and not below it.

So this stage runs with a specific question rather than an assumption: on this panel, with
these features, does a network find anything the trees in `07_gbm` do not? It reads the same
point-in-time feature rows under the same fold and label contracts, so the comparison isolates
the model family.

### What TabM is doing differently

The obvious way to improve a neural network's reliability is to train several and average
them, which reduces the variance that comes from initialization and from the optimizer's path.
The obvious cost is that k models take k times the compute and k times the memory.

TabM is a parameter-efficient ensemble: it trains what behaves like several models while
sharing most of the weights between them, so the averaging is available at close to the cost of
one. That matters here more than it would on a large dataset, because the thing most likely to
go wrong on a panel this size is not bias but variance - a single network on a small, noisy
feature table can land in a very different place depending on where it started, and the spread
between those places can exceed whatever edge is being measured.

`varies model capacity` in the declared configurations is the other half of the same concern.
Capacity is the dial that trades fitting the training rows against generalizing off them, and
on a noisy panel the best setting is usually much smaller than intuition suggests. Declaring
several and letting the backtest choose is what keeps that from being a guess.

One consequence worth stating for the comparison with `07_gbm`: a network needs its features
standardized and trees do not. So the two families do not read quite the same inputs even
though they read the same columns, and a difference in their results is partly a difference in
preprocessing rather than purely in model family. That is unavoidable - an unstandardized
network on mixed-scale features does not train - but it is worth knowing before the gap
between the two is attributed entirely to what the models can represent.

### Why every checkpoint is published

A neural fit is a trajectory rather than a model: it passes through a sequence of states, and
which one is kept is a choice with the same standing as the architecture. The runner publishes
every declared epoch checkpoint with its own fitted weights and validation coverage, and
`13_backtest` selects among them on Sharpe like any other configuration.

Publishing them rather than picking one is the honest arrangement. Choosing the best epoch by
looking at validation performance and then reporting that model's validation performance is
selection inside the number being reported, and it does not stop being that because the choice
was made by hand rather than by a search. Declaring the checkpoints puts the choice into the
same funnel and the same trial count as everything else - which the deflated Sharpe downstream
then has to divide by, and which is why the count is not free.

In [1]:
"""Fit the declared CME futures TabM population."""

import polars as pl

from case_studies.cme_futures.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    product_universe_table,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_catalog,
    run_resolved_model_requests,
)
from case_studies.research import SUPERSEDES_LIVE, supersedes_for_run

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None
PREVIEW_REDUCTIONS: dict = {}
# That this run intends to extend the lineage published under this population's name.
# `SUPERSEDES_LIVE` says so without quoting a hash: a re-run whose membership has changed is
# refused without the generation it supersedes, and a quoted hash has to equal a value the
# registry moves on every publish. `supersedes_for_run` resolves it against the registry and
# withholds it where offering it would be refused - a reader's clean clone, a caller's own
# `POPULATION_NAME`, a preview.
SUPERSEDES_POPULATION: str | None = SUPERSEDES_LIVE
# The device to fit on. Empty means the device this population was published on.
DEVICE: str = ""
# The population this run publishes into. Empty publishes the canonical one, which a run
# on another device may not do.
POPULATION_NAME: str = ""

## Declared requests

Both configured return horizons enter the same visible request table. Preview epoch or fold limits
must be passed through `PREVIEW_REDUCTIONS`, which changes identity and excludes the output from
the canonical catalog.

Routing reductions through identity rather than through a flag is what keeps a reduced run
from being mistaken for a real one later. A preview that trained for two epochs instead of the
declared schedule produces a genuine prediction set with genuine metrics, and nothing about
the numbers announces that they came from a fraction of the work. Because the reduction enters
the hash, the reduced rows cannot resolve to the same identity as canonical ones, cannot be
served back in place of them, and are excluded from the catalog the backtest reads.

The alternative - a boolean that says "this was a preview" - fails the moment anyone queries
the registry without checking it, which is the failure mode that makes a leaderboard quietly
wrong rather than visibly broken.

**TabM runs on the GPU, and the request says so rather than inheriting it.** With no override the
shared adapter falls back to a literal `"cuda"` written in `case_studies/utils/tabular_dl.py`, and
`resolve_torch_device` raises `CUDA was requested but is unavailable` rather than quietly moving
the fit to the CPU. Naming it in the request puts that requirement where a reader meets it. The
resolved specification hash is the same with the override as without, so this states what the
published run already did.

A network trained on a GPU and the same network trained on a CPU accumulate their sums in
different orders and reach different weights, so the device is part of what the fitted model is
and enters the computation's identity rather than sitting beside it. `PUBLISHED_DEVICE` is the
device this population was fitted on, and the canonical population accepts no other: a reader
without an NVIDIA card sets `DEVICE="cpu"` and passes a `POPULATION_NAME` to fit the same grid
into a population of its own, whose rows are excluded from the catalog the backtest reads.

In [3]:
PUBLISHED_DEVICE = "cuda"
device = DEVICE or PUBLISHED_DEVICE
if device != PUBLISHED_DEVICE and not POPULATION_NAME:
    raise ValueError(
        f"this run fits on device {device!r}, which is not the {PUBLISHED_DEVICE!r} this "
        f"population was published on, so it cannot publish the canonical population; pass "
        f"POPULATION_NAME to give it its own"
    )

population_name = POPULATION_NAME or "cme_futures-tabular_dl-validation-v1"

study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE)
requests = model_request_catalog("tabular_dl", labels=ALL_LABELS)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": device},
    preview_reductions=PREVIEW_REDUCTIONS,
)
universe = product_universe_table()
universe

shape: (30, 4)
┌─────────────┬─────────┬──────────────────────────┬─────────────────┐
│ sector      ┆ product ┆ expiry_rule              ┆ contract_months │
│ ---         ┆ ---     ┆ ---                      ┆ ---             │
│ str         ┆ str     ┆ str                      ┆ str             │
╞═════════════╪═════════╪══════════════════════════╪═════════════════╡
│ agriculture ┆ ZC      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ agriculture ┆ ZL      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZM      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZS      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,X   │
│ agriculture ┆ ZW      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ …           ┆ …       ┆ …                        ┆ …               │
│ metals      ┆ SI      ┆ 3rd_last_business_day    ┆ H,K,N,U,Z       │
│ treasuries  ┆ ZB      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZF      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZN      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZT      ┆ last_business_day        ┆ H,M,U,Z         │
└─────────────┴─────────┴──────────────────────────┴─────────────────┘

In [4]:
resolved_model_plan(resolved)

shape: (6, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ date      ┆ i64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ 2d3b9b93 │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 1085     │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_m    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ acaada56 │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 96bc     │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_s    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ c077267e │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 4946     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_l    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ 2600527d │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ a927     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_m    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ 1cffb566 │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ d84e     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ 7253951b │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 0052     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

Fold-scoped preprocessing, seeded training, fitted-state persistence, checkpoint membership, and
prediction eligibility are enforced by the shared TabM adapter.

**Fold-scoped preprocessing is the item on that list most easily got wrong.** A network needs
its inputs standardized, and standardizing means subtracting a mean and dividing by a scale -
both of which are estimated quantities. Estimating them over the whole panel and then applying
them inside each fold leaks: the training rows are centred using a mean that already reflects
the validation period, and the resulting predictions are built from a summary of data the model
was not supposed to have. It is a small leak and an invisible one - no assertion over the
prediction frame can see it, because the leaked quantity is two numbers that never appear in
the output. The adapter refits the scaler inside each training fold for that reason.

**Seeded training is what makes a result a result rather than a draw.** Two runs of the same
configuration with different seeds land in different places, and on a panel this size the gap
between them can be comparable to the differences the backtest is trying to measure. Fixing the
seed does not make the model better; it makes the number attributable to the configuration
rather than to the draw, which is the precondition for comparing configurations at all.

That is also why the seed lives in the resolved specification rather than in a notebook
constant. A seed that only reached the training call would be a dial that turned without
moving the identity - change it, and the registry serves back the result fitted under the old
one while the notebook claims the new.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_catalog(
        study,
        requests,
        population_name=population_name,
        resolved_requests=resolved,
        supersedes=supersedes_for_run(
            study,
            population_name=population_name,
            declared=SUPERSEDES_POPULATION,
            execution_tier=EXECUTION_TIER,
        ),
    )
else:
    if WORKSPACE is None or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Preparing and releasing folds...

  Fold 0: train=58,879  val=7,692

      epoch  25/200: loss=0.000777, IC=-0.0115

      epoch  50/200: loss=0.000720, IC=-0.0191

      epoch  75/200: loss=0.000700, IC=-0.0113

      epoch 100/200: loss=0.000688, IC=-0.0057

      epoch 125/200: loss=0.000680, IC=-0.0080

      epoch 150/200: loss=0.000675, IC=-0.0047

      epoch 175/200: loss=0.000673, IC=-0.0044

      epoch 200/200: loss=0.000672, IC=-0.0047

    Fold 0: best_ep=175, IC=-0.0044 (29.1s)

  Fold 1: train=59,738  val=7,692

      epoch  25/200: loss=0.000689, IC=-0.0643

      epoch  50/200: loss=0.000657, IC=-0.0658

      epoch  75/200: loss=0.000642, IC=-0.0437

      epoch 100/200: loss=0.000628, IC=-0.0323

      epoch 125/200: loss=0.000619, IC=-0.0299

      epoch 150/200: loss=0.000613, IC=-0.0294

      epoch 175/200: loss=0.000610, IC=-0.0316

      epoch 200/200: loss=0.000609, IC=-0.0311

    Fold 1: best_ep=150, IC=-0.0294 (21.4s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000919, IC=-0.0416

      epoch  50/200: loss=0.000861, IC=-0.0556

      epoch  75/200: loss=0.000830, IC=-0.0533

      epoch 100/200: loss=0.000803, IC=-0.0399

      epoch 125/200: loss=0.000783, IC=-0.0351

      epoch 150/200: loss=0.000773, IC=-0.0312

      epoch 175/200: loss=0.000767, IC=-0.0287

      epoch 200/200: loss=0.000767, IC=-0.0288

    Fold 2: best_ep=175, IC=-0.0287 (20.3s)

  Fold 3: train=60,337  val=7,684

      epoch  25/200: loss=0.000943, IC=+0.0353

      epoch  50/200: loss=0.000888, IC=+0.0316

      epoch  75/200: loss=0.000852, IC=+0.0264

      epoch 100/200: loss=0.000818, IC=+0.0276

      epoch 125/200: loss=0.000796, IC=+0.0376

      epoch 150/200: loss=0.000791, IC=+0.0363

      epoch 175/200: loss=0.000782, IC=+0.0335

      epoch 200/200: loss=0.000785, IC=+0.0342

    Fold 3: best_ep=125, IC=+0.0376 (25.2s)

  Fold 4: train=60,680  val=7,518

      epoch  25/200: loss=0.001160, IC=-0.0536

      epoch  50/200: loss=0.001067, IC=-0.0598

      epoch  75/200: loss=0.001028, IC=-0.0487

      epoch 100/200: loss=0.001000, IC=-0.0447

      epoch 125/200: loss=0.000981, IC=-0.0418

      epoch 150/200: loss=0.000966, IC=-0.0379

      epoch 175/200: loss=0.000965, IC=-0.0375

      epoch 200/200: loss=0.000962, IC=-0.0375

    Fold 4: best_ep=175, IC=-0.0375 (20.6s)

    → best_epoch=150, IC=-0.0133 (116.8s)

  Best: 7253951b0052 @ epoch 150 (IC=-0.0133)

Preparing and releasing folds...

  Fold 0: train=58,879  val=7,692

      epoch  25/200: loss=0.000746, IC=-0.0052

      epoch  50/200: loss=0.000709, IC=-0.0048

      epoch  75/200: loss=0.000693, IC=+0.0052

      epoch 100/200: loss=0.000681, IC=+0.0097

      epoch 125/200: loss=0.000672, IC=+0.0057

      epoch 150/200: loss=0.000663, IC=+0.0031

      epoch 175/200: loss=0.000663, IC=+0.0028

      epoch 200/200: loss=0.000662, IC=+0.0021

    Fold 0: best_ep=100, IC=+0.0097 (21.8s)

  Fold 1: train=59,738  val=7,692

      epoch  25/200: loss=0.000692, IC=-0.0267

      epoch  50/200: loss=0.000660, IC=-0.0474

      epoch  75/200: loss=0.000646, IC=-0.0431

      epoch 100/200: loss=0.000633, IC=-0.0382

      epoch 125/200: loss=0.000623, IC=-0.0393

      epoch 150/200: loss=0.000616, IC=-0.0382

      epoch 175/200: loss=0.000614, IC=-0.0387

      epoch 200/200: loss=0.000614, IC=-0.0389

    Fold 1: best_ep=25, IC=-0.0267 (15.9s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000899, IC=-0.0372

      epoch  50/200: loss=0.000849, IC=-0.0357

      epoch  75/200: loss=0.000813, IC=-0.0293

      epoch 100/200: loss=0.000783, IC=-0.0253

      epoch 125/200: loss=0.000761, IC=-0.0282

      epoch 150/200: loss=0.000752, IC=-0.0296

      epoch 175/200: loss=0.000745, IC=-0.0313

      epoch 200/200: loss=0.000744, IC=-0.0310

    Fold 2: best_ep=100, IC=-0.0253 (16.4s)

  Fold 3: train=60,337  val=7,684

      epoch  25/200: loss=0.000952, IC=-0.0096

      epoch  50/200: loss=0.000891, IC=+0.0046

      epoch  75/200: loss=0.000853, IC=+0.0184

      epoch 100/200: loss=0.000827, IC=+0.0151

      epoch 125/200: loss=0.000801, IC=+0.0158

      epoch 150/200: loss=0.000791, IC=+0.0152

      epoch 175/200: loss=0.000786, IC=+0.0146

      epoch 200/200: loss=0.000784, IC=+0.0145

    Fold 3: best_ep=75, IC=+0.0184 (21.3s)

  Fold 4: train=60,680  val=7,518

      epoch  25/200: loss=0.001080, IC=-0.0449

      epoch  50/200: loss=0.001018, IC=-0.0415

      epoch  75/200: loss=0.000962, IC=-0.0205

      epoch 100/200: loss=0.000921, IC=-0.0276

      epoch 125/200: loss=0.000895, IC=-0.0347

      epoch 150/200: loss=0.000882, IC=-0.0369

      epoch 175/200: loss=0.000875, IC=-0.0334

      epoch 200/200: loss=0.000874, IC=-0.0349

    Fold 4: best_ep=75, IC=-0.0205 (16.1s)

    → best_epoch=100, IC=-0.0132 (91.7s)

  Best: 1cffb566d84e @ epoch 100 (IC=-0.0132)

Preparing and releasing folds...

  Fold 0: train=58,879  val=7,692

      epoch  25/200: loss=0.000717, IC=-0.0032

      epoch  50/200: loss=0.000691, IC=-0.0033

      epoch  75/200: loss=0.000665, IC=-0.0068

      epoch 100/200: loss=0.000644, IC=-0.0047

      epoch 125/200: loss=0.000628, IC=-0.0040

      epoch 150/200: loss=0.000617, IC=-0.0040

      epoch 175/200: loss=0.000614, IC=-0.0021

      epoch 200/200: loss=0.000614, IC=-0.0020

    Fold 0: best_ep=200, IC=-0.0020 (33.7s)

  Fold 1: train=59,738  val=7,692

      epoch  25/200: loss=0.000675, IC=-0.0564

      epoch  50/200: loss=0.000650, IC=-0.0491

      epoch  75/200: loss=0.000631, IC=-0.0480

      epoch 100/200: loss=0.000611, IC=-0.0467

      epoch 125/200: loss=0.000598, IC=-0.0502

      epoch 150/200: loss=0.000588, IC=-0.0501

      epoch 175/200: loss=0.000585, IC=-0.0513

      epoch 200/200: loss=0.000585, IC=-0.0509

    Fold 1: best_ep=100, IC=-0.0467 (36.0s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000872, IC=-0.0865

      epoch  50/200: loss=0.000818, IC=-0.0598

      epoch  75/200: loss=0.000769, IC=-0.0603

      epoch 100/200: loss=0.000736, IC=-0.0514

      epoch 125/200: loss=0.000712, IC=-0.0471

      epoch 150/200: loss=0.000699, IC=-0.0453

      epoch 175/200: loss=0.000692, IC=-0.0432

      epoch 200/200: loss=0.000690, IC=-0.0435

    Fold 2: best_ep=175, IC=-0.0432 (35.4s)

  Fold 3: train=60,337  val=7,684

      epoch  25/200: loss=0.000916, IC=+0.0147

      epoch  50/200: loss=0.000858, IC=+0.0236

      epoch  75/200: loss=0.000805, IC=+0.0282

      epoch 100/200: loss=0.000772, IC=+0.0324

      epoch 125/200: loss=0.000746, IC=+0.0344

      epoch 150/200: loss=0.000733, IC=+0.0358

      epoch 175/200: loss=0.000726, IC=+0.0334

      epoch 200/200: loss=0.000725, IC=+0.0335

    Fold 3: best_ep=150, IC=+0.0358 (33.5s)

  Fold 4: train=60,680  val=7,518

      epoch  25/200: loss=0.001068, IC=-0.0331

      epoch  50/200: loss=0.001000, IC=-0.0349

      epoch  75/200: loss=0.000940, IC=-0.0238

      epoch 100/200: loss=0.000898, IC=-0.0242

      epoch 125/200: loss=0.000866, IC=-0.0186

      epoch 150/200: loss=0.000855, IC=-0.0203

      epoch 175/200: loss=0.000845, IC=-0.0226

      epoch 200/200: loss=0.000843, IC=-0.0222

    Fold 4: best_ep=125, IC=-0.0186 (34.0s)

    → best_epoch=150, IC=-0.0168 (172.7s)

  Best: 2600527da927 @ epoch 150 (IC=-0.0168)

Preparing and releasing folds...

  Fold 0: train=58,325  val=7,692

      epoch  25/200: loss=0.002708, IC=+0.0059

      epoch  50/200: loss=0.002362, IC=+0.0355

      epoch  75/200: loss=0.002136, IC=+0.0308

      epoch 100/200: loss=0.002014, IC=+0.0397

      epoch 125/200: loss=0.001944, IC=+0.0473

      epoch 150/200: loss=0.001902, IC=+0.0499

      epoch 175/200: loss=0.001872, IC=+0.0495

      epoch 200/200: loss=0.001872, IC=+0.0514

    Fold 0: best_ep=200, IC=+0.0514 (16.0s)

  Fold 1: train=59,210  val=7,692

      epoch  25/200: loss=0.002481, IC=-0.1064

      epoch  50/200: loss=0.002125, IC=-0.1156

      epoch  75/200: loss=0.001913, IC=-0.1404

      epoch 100/200: loss=0.001780, IC=-0.1368

      epoch 125/200: loss=0.001716, IC=-0.1364

      epoch 150/200: loss=0.001693, IC=-0.1376

      epoch 175/200: loss=0.001678, IC=-0.1351

      epoch 200/200: loss=0.001676, IC=-0.1375

    Fold 1: best_ep=25, IC=-0.1064 (29.5s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.003247, IC=-0.0923

      epoch  50/200: loss=0.002741, IC=-0.0761

      epoch  75/200: loss=0.002462, IC=-0.0610

      epoch 100/200: loss=0.002327, IC=-0.0614

      epoch 125/200: loss=0.002212, IC=-0.0596

      epoch 150/200: loss=0.002166, IC=-0.0690

      epoch 175/200: loss=0.002147, IC=-0.0689

      epoch 200/200: loss=0.002134, IC=-0.0680

    Fold 2: best_ep=125, IC=-0.0596 (45.9s)

  Fold 3: train=59,857  val=7,684

      epoch  25/200: loss=0.003238, IC=+0.0569

      epoch  50/200: loss=0.002691, IC=+0.0618

      epoch  75/200: loss=0.002432, IC=+0.0826

      epoch 100/200: loss=0.002288, IC=+0.0901

      epoch 125/200: loss=0.002214, IC=+0.0884

      epoch 150/200: loss=0.002178, IC=+0.0882

      epoch 175/200: loss=0.002151, IC=+0.0848

      epoch 200/200: loss=0.002144, IC=+0.0841

    Fold 3: best_ep=100, IC=+0.0901 (24.9s)

  Fold 4: train=60,200  val=7,038

      epoch  25/200: loss=0.003880, IC=-0.0687

      epoch  50/200: loss=0.003345, IC=-0.0763

      epoch  75/200: loss=0.003026, IC=-0.0643

      epoch 100/200: loss=0.002822, IC=-0.0536

      epoch 125/200: loss=0.002709, IC=-0.0503

      epoch 150/200: loss=0.002640, IC=-0.0461

      epoch 175/200: loss=0.002628, IC=-0.0459

      epoch 200/200: loss=0.002613, IC=-0.0457

    Fold 4: best_ep=200, IC=-0.0457 (16.6s)

    → best_epoch=125, IC=-0.0216 (133.4s)

  Best: c077267e4946 @ epoch 125 (IC=-0.0216)

Preparing and releasing folds...

  Fold 0: train=58,325  val=7,692

      epoch  25/200: loss=0.002619, IC=+0.0611

      epoch  50/200: loss=0.002227, IC=+0.0576

      epoch  75/200: loss=0.001976, IC=+0.0500

      epoch 100/200: loss=0.001845, IC=+0.0414

      epoch 125/200: loss=0.001760, IC=+0.0463

      epoch 150/200: loss=0.001710, IC=+0.0437

      epoch 175/200: loss=0.001691, IC=+0.0430

      epoch 200/200: loss=0.001691, IC=+0.0431

    Fold 0: best_ep=25, IC=+0.0611 (21.3s)

  Fold 1: train=59,210  val=7,692

      epoch  25/200: loss=0.002467, IC=-0.1009

      epoch  50/200: loss=0.002082, IC=-0.1372

      epoch  75/200: loss=0.001847, IC=-0.1644

      epoch 100/200: loss=0.001704, IC=-0.1664

      epoch 125/200: loss=0.001623, IC=-0.1631

      epoch 150/200: loss=0.001586, IC=-0.1618

      epoch 175/200: loss=0.001574, IC=-0.1603

      epoch 200/200: loss=0.001568, IC=-0.1600

    Fold 1: best_ep=25, IC=-0.1009 (13.4s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.003090, IC=-0.1273

      epoch  50/200: loss=0.002546, IC=-0.0969

      epoch  75/200: loss=0.002258, IC=-0.0782

      epoch 100/200: loss=0.002076, IC=-0.0770

      epoch 125/200: loss=0.001984, IC=-0.0789

      epoch 150/200: loss=0.001943, IC=-0.0796

      epoch 175/200: loss=0.001918, IC=-0.0799

      epoch 200/200: loss=0.001912, IC=-0.0793

    Fold 2: best_ep=100, IC=-0.0770 (16.5s)

  Fold 3: train=59,857  val=7,684

      epoch  25/200: loss=0.003225, IC=+0.0113

      epoch  50/200: loss=0.002643, IC=+0.0094

      epoch  75/200: loss=0.002337, IC=+0.0205

      epoch 100/200: loss=0.002166, IC=+0.0381

      epoch 125/200: loss=0.002062, IC=+0.0396

      epoch 150/200: loss=0.002014, IC=+0.0439

      epoch 175/200: loss=0.001983, IC=+0.0453

      epoch 200/200: loss=0.001971, IC=+0.0446

    Fold 3: best_ep=175, IC=+0.0453 (18.3s)

  Fold 4: train=60,200  val=7,038

      epoch  25/200: loss=0.003420, IC=-0.0987

      epoch  50/200: loss=0.002754, IC=-0.0859

      epoch  75/200: loss=0.002457, IC=-0.0650

      epoch 100/200: loss=0.002279, IC=-0.0593

      epoch 125/200: loss=0.002175, IC=-0.0512

      epoch 150/200: loss=0.002135, IC=-0.0470

      epoch 175/200: loss=0.002107, IC=-0.0469

      epoch 200/200: loss=0.002103, IC=-0.0465

    Fold 4: best_ep=200, IC=-0.0465 (13.3s)

    → best_epoch=200, IC=-0.0395 (82.9s)

  Best: acaada5696bc @ epoch 200 (IC=-0.0395)

Preparing and releasing folds...

  Fold 0: train=58,325  val=7,692

      epoch  25/200: loss=0.002339, IC=+0.0420

      epoch  50/200: loss=0.001857, IC=+0.0366

      epoch  75/200: loss=0.001626, IC=+0.0274

      epoch 100/200: loss=0.001512, IC=+0.0310

      epoch 125/200: loss=0.001437, IC=+0.0352

      epoch 150/200: loss=0.001395, IC=+0.0331

      epoch 175/200: loss=0.001375, IC=+0.0351

      epoch 200/200: loss=0.001375, IC=+0.0354

    Fold 0: best_ep=25, IC=+0.0420 (29.5s)

  Fold 1: train=59,210  val=7,692

      epoch  25/200: loss=0.002304, IC=-0.1106

      epoch  50/200: loss=0.001830, IC=-0.1258

      epoch  75/200: loss=0.001586, IC=-0.1233

      epoch 100/200: loss=0.001447, IC=-0.1347

      epoch 125/200: loss=0.001376, IC=-0.1293

      epoch 150/200: loss=0.001338, IC=-0.1315

      epoch 175/200: loss=0.001324, IC=-0.1334

      epoch 200/200: loss=0.001322, IC=-0.1339

    Fold 1: best_ep=25, IC=-0.1106 (30.0s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.002772, IC=-0.1044

      epoch  50/200: loss=0.002170, IC=-0.0808

      epoch  75/200: loss=0.001891, IC=-0.0577

      epoch 100/200: loss=0.001739, IC=-0.0555

      epoch 125/200: loss=0.001642, IC=-0.0563

      epoch 150/200: loss=0.001603, IC=-0.0615

      epoch 175/200: loss=0.001591, IC=-0.0617

      epoch 200/200: loss=0.001572, IC=-0.0614

    Fold 2: best_ep=100, IC=-0.0555 (31.9s)

  Fold 3: train=59,857  val=7,684

      epoch  25/200: loss=0.002881, IC=+0.0316

      epoch  50/200: loss=0.002263, IC=+0.0194

      epoch  75/200: loss=0.001972, IC=+0.0064

      epoch 100/200: loss=0.001809, IC=+0.0084

      epoch 125/200: loss=0.001718, IC=+0.0097

      epoch 150/200: loss=0.001673, IC=+0.0091

      epoch 175/200: loss=0.001648, IC=+0.0094

      epoch 200/200: loss=0.001644, IC=+0.0100

    Fold 3: best_ep=25, IC=+0.0316 (30.9s)

  Fold 4: train=60,200  val=7,038

      epoch  25/200: loss=0.003245, IC=-0.0720

      epoch  50/200: loss=0.002532, IC=-0.0630

      epoch  75/200: loss=0.002213, IC=-0.0611

      epoch 100/200: loss=0.002045, IC=-0.0571

      epoch 125/200: loss=0.001939, IC=-0.0534

      epoch 150/200: loss=0.001884, IC=-0.0519

      epoch 175/200: loss=0.001853, IC=-0.0516

      epoch 200/200: loss=0.001852, IC=-0.0514

    Fold 4: best_ep=200, IC=-0.0514 (32.7s)

    → best_epoch=125, IC=-0.0386 (155.0s)

  Best: 2d3b9b931085 @ epoch 125 (IC=-0.0386)

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("label", "config_name", "checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("TabM execution returned a partial prediction")
catalog

shape: (48, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 2d3b9b931 ┆ f966569f8 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 085       ┆ 440       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 2d3b9b931 ┆ 992a706c8 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 085       ┆ b0c       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 2d3b9b931 ┆ 48f5879ea │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 085       ┆ d23       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 2d3b9b931 ┆ d065f04ed │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 085       ┆ abc       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 2d3b9b931 ┆ cb1a5014f │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 085       ┆ 321       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 7253951b0 ┆ 8ea0e204e │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 052       ┆ 0b9       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 7253951b0 ┆ 46095094a │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 052       ┆ 4dd       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 7253951b0 ┆ 5ea38eeba │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 052       ┆ 536       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 7253951b0 ┆ e5f78542c │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 052       ┆ 285       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 7253951b0 ┆ 1f493730a │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 052       ┆ ddc       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘