# CME Futures: Tabular Deep Learning

TabM applies a parameter-efficient neural ensemble to the same point-in-time feature rows used by
the linear and gradient-boosting families. The declared configurations vary model capacity while
retaining the walk-forward fold and label contracts from `05_evaluation`.

The shared runner publishes every declared epoch checkpoint with its fitted weights and exact
validation coverage. The equal-weight validation backtest in `13_backtest` evaluates all
checkpoints and selects by Sharpe.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit the declared CME futures TabM population."""

import polars as pl

from case_studies.cme_futures.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    product_universe_table,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_catalog,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None
PREVIEW_REDUCTIONS: dict = {}
# The population hash this run replaces, read from the registry and set by a person. A
# first population takes None; a re-run whose membership has changed is refused without
# the hash it supersedes, and the refusal names the value required.
SUPERSEDES_POPULATION: str | None = None

## Declared requests

Both configured return horizons enter the same visible request table. Preview epoch or fold limits
must be passed through `PREVIEW_REDUCTIONS`, which changes identity and excludes the output from
the canonical catalog.

**TabM runs on the GPU, and the request says so rather than inheriting it.** With no override the
shared adapter falls back to a literal `"cuda"` written in `case_studies/utils/tabular_dl.py`, and
`resolve_torch_device` raises `CUDA was requested but is unavailable` rather than quietly moving
the fit to the CPU. A CUDA device is therefore a hard requirement of this population, declared two
layers below the notebook: without one these configurations cannot be reproduced at all. Naming it
in the request puts that requirement where a reader meets it. The resolved specification hash is
the same with the override as without, so this states what the published run already did.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE)
requests = model_request_catalog("tabular_dl", labels=ALL_LABELS)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": "cuda"},
    preview_reductions=PREVIEW_REDUCTIONS,
)
universe = product_universe_table()
universe

shape: (30, 4)
┌─────────────┬─────────┬──────────────────────────┬─────────────────┐
│ sector      ┆ product ┆ expiry_rule              ┆ contract_months │
│ ---         ┆ ---     ┆ ---                      ┆ ---             │
│ str         ┆ str     ┆ str                      ┆ str             │
╞═════════════╪═════════╪══════════════════════════╪═════════════════╡
│ agriculture ┆ ZC      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ agriculture ┆ ZL      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZM      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZS      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,X   │
│ agriculture ┆ ZW      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ …           ┆ …       ┆ …                        ┆ …               │
│ metals      ┆ SI      ┆ 3rd_last_business_day    ┆ H,K,N,U,Z       │
│ treasuries  ┆ ZB      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZF      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZN      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZT      ┆ last_business_day        ┆ H,M,U,Z         │
└─────────────┴─────────┴──────────────────────────┴─────────────────┘

In [4]:
resolved_model_plan(resolved)

shape: (6, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ date      ┆ i64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ c626cf46 │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 688a     │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_m    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ 5ccff0bd │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 685d     │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_s    ┆ regressio ┆ … ┆ 2023-11-2 ┆ 8         ┆ canonical ┆ d575ade2 │
│ l         ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 3232     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_l    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ f1ba0c34 │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ a929     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_m    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ b8688e1e │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ e906     │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ regressio ┆ … ┆ 2023-12-2 ┆ 8         ┆ canonical ┆ 0f5b1db3 │
│ l         ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 0a12     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

Fold-scoped preprocessing, seeded training, fitted-state persistence, checkpoint membership, and
prediction eligibility are enforced by the shared TabM adapter.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_catalog(
        study,
        requests,
        population_name="cme_futures-tabular_dl-validation-v1",
        resolved_requests=resolved,
        supersedes=SUPERSEDES_POPULATION,
    )
else:
    if WORKSPACE is None or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Preparing and releasing folds...

  Fold 0: train=60,680  val=7,518

      epoch  25/200: loss=0.000956, IC=-0.0483

      epoch  50/200: loss=0.000800, IC=-0.0523

      epoch  75/200: loss=0.000714, IC=-0.0404

      epoch 100/200: loss=0.000682, IC=-0.0459

      epoch 125/200: loss=0.000659, IC=-0.0484

      epoch 150/200: loss=0.000642, IC=-0.0417

      epoch 175/200: loss=0.000635, IC=-0.0426

      epoch 200/200: loss=0.000635, IC=-0.0436

    Fold 0: best_ep=75, IC=-0.0404 (19.3s)

  Fold 1: train=60,337  val=7,684

      epoch  25/200: loss=0.000822, IC=+0.0271

      epoch  50/200: loss=0.000681, IC=+0.0504

      epoch  75/200: loss=0.000633, IC=+0.0247

      epoch 100/200: loss=0.000589, IC=+0.0232

      epoch 125/200: loss=0.000576, IC=+0.0173

      epoch 150/200: loss=0.000561, IC=+0.0195

      epoch 175/200: loss=0.000556, IC=+0.0176

      epoch 200/200: loss=0.000556, IC=+0.0178

    Fold 1: best_ep=50, IC=+0.0504 (25.2s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000766, IC=-0.0695

      epoch  50/200: loss=0.000634, IC=-0.0498

      epoch  75/200: loss=0.000581, IC=-0.0527

      epoch 100/200: loss=0.000550, IC=-0.0477

      epoch 125/200: loss=0.000530, IC=-0.0488

      epoch 150/200: loss=0.000523, IC=-0.0481

      epoch 175/200: loss=0.000517, IC=-0.0443

      epoch 200/200: loss=0.000518, IC=-0.0433

    Fold 2: best_ep=200, IC=-0.0433 (14.9s)

  Fold 3: train=59,738  val=7,692

      epoch  25/200: loss=0.000618, IC=-0.0190

      epoch  50/200: loss=0.000528, IC=-0.0316

      epoch  75/200: loss=0.000492, IC=-0.0527

      epoch 100/200: loss=0.000465, IC=-0.0699

      epoch 125/200: loss=0.000452, IC=-0.0772

      epoch 150/200: loss=0.000440, IC=-0.0792

      epoch 175/200: loss=0.000442, IC=-0.0800

      epoch 200/200: loss=0.000436, IC=-0.0805

    Fold 3: best_ep=25, IC=-0.0190 (13.4s)

  Fold 4: train=58,879  val=7,692

      epoch  25/200: loss=0.000689, IC=-0.0070

      epoch  50/200: loss=0.000577, IC=-0.0158

      epoch  75/200: loss=0.000521, IC=-0.0133

      epoch 100/200: loss=0.000495, IC=-0.0177

      epoch 125/200: loss=0.000475, IC=-0.0195

      epoch 150/200: loss=0.000465, IC=-0.0200

      epoch 175/200: loss=0.000461, IC=-0.0228

      epoch 200/200: loss=0.000462, IC=-0.0214

    Fold 4: best_ep=25, IC=-0.0070 (14.6s)

    → best_epoch=50, IC=-0.0197 (87.6s)

  Best: 0f5b1db30a12 @ epoch 50 (IC=-0.0197)

Preparing and releasing folds...

  Fold 0: train=60,680  val=7,518

      epoch  25/200: loss=0.000717, IC=-0.0131

      epoch  50/200: loss=0.000556, IC=+0.0029

      epoch  75/200: loss=0.000495, IC=-0.0106

      epoch 100/200: loss=0.000454, IC=+0.0060

      epoch 125/200: loss=0.000434, IC=-0.0041

      epoch 150/200: loss=0.000418, IC=+0.0006

      epoch 175/200: loss=0.000416, IC=+0.0000

      epoch 200/200: loss=0.000412, IC=+0.0016

    Fold 0: best_ep=100, IC=+0.0060 (15.1s)

  Fold 1: train=60,337  val=7,684

      epoch  25/200: loss=0.000610, IC=+0.0231

      epoch  50/200: loss=0.000488, IC=+0.0372

      epoch  75/200: loss=0.000430, IC=+0.0286

      epoch 100/200: loss=0.000403, IC=+0.0275

      epoch 125/200: loss=0.000379, IC=+0.0245

      epoch 150/200: loss=0.000370, IC=+0.0301

      epoch 175/200: loss=0.000363, IC=+0.0265

      epoch 200/200: loss=0.000361, IC=+0.0257

    Fold 1: best_ep=50, IC=+0.0372 (17.2s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000592, IC=-0.0392

      epoch  50/200: loss=0.000469, IC=-0.0409

      epoch  75/200: loss=0.000414, IC=-0.0241

      epoch 100/200: loss=0.000388, IC=-0.0117

      epoch 125/200: loss=0.000367, IC=-0.0114

      epoch 150/200: loss=0.000353, IC=-0.0115

      epoch 175/200: loss=0.000352, IC=-0.0093

      epoch 200/200: loss=0.000355, IC=-0.0093

    Fold 2: best_ep=175, IC=-0.0093 (15.5s)

  Fold 3: train=59,738  val=7,692

      epoch  25/200: loss=0.000506, IC=-0.0469

      epoch  50/200: loss=0.000393, IC=-0.0861

      epoch  75/200: loss=0.000344, IC=-0.0776

      epoch 100/200: loss=0.000320, IC=-0.0836

      epoch 125/200: loss=0.000302, IC=-0.0833

      epoch 150/200: loss=0.000296, IC=-0.0850

      epoch 175/200: loss=0.000291, IC=-0.0871

      epoch 200/200: loss=0.000292, IC=-0.0866

    Fold 3: best_ep=25, IC=-0.0469 (17.4s)

  Fold 4: train=58,879  val=7,692

      epoch  25/200: loss=0.000506, IC=-0.0039

      epoch  50/200: loss=0.000397, IC=-0.0346

      epoch  75/200: loss=0.000353, IC=-0.0301

      epoch 100/200: loss=0.000323, IC=-0.0422

      epoch 125/200: loss=0.000309, IC=-0.0301

      epoch 150/200: loss=0.000303, IC=-0.0285

      epoch 175/200: loss=0.000299, IC=-0.0290

      epoch 200/200: loss=0.000300, IC=-0.0293

    Fold 4: best_ep=25, IC=-0.0039 (16.4s)

    → best_epoch=25, IC=-0.0160 (81.7s)

  Best: b8688e1ee906 @ epoch 25 (IC=-0.0160)

Preparing and releasing folds...

  Fold 0: train=60,680  val=7,518

      epoch  25/200: loss=0.000611, IC=+0.0139

      epoch  50/200: loss=0.000418, IC=+0.0302

      epoch  75/200: loss=0.000335, IC=+0.0404

      epoch 100/200: loss=0.000300, IC=+0.0468

      epoch 125/200: loss=0.000278, IC=+0.0263

      epoch 150/200: loss=0.000269, IC=+0.0279

      epoch 175/200: loss=0.000259, IC=+0.0234

      epoch 200/200: loss=0.000259, IC=+0.0238

    Fold 0: best_ep=100, IC=+0.0468 (21.3s)

  Fold 1: train=60,337  val=7,684

      epoch  25/200: loss=0.000468, IC=+0.0510

      epoch  50/200: loss=0.000331, IC=+0.0473

      epoch  75/200: loss=0.000274, IC=+0.0438

      epoch 100/200: loss=0.000250, IC=+0.0418

      epoch 125/200: loss=0.000230, IC=+0.0407

      epoch 150/200: loss=0.000219, IC=+0.0393

      epoch 175/200: loss=0.000215, IC=+0.0391

      epoch 200/200: loss=0.000214, IC=+0.0403

    Fold 1: best_ep=25, IC=+0.0510 (20.8s)

  Fold 2: train=60,044  val=7,676

      epoch  25/200: loss=0.000473, IC=+0.0064

      epoch  50/200: loss=0.000327, IC=-0.0229

      epoch  75/200: loss=0.000271, IC=-0.0075

      epoch 100/200: loss=0.000239, IC=+0.0008

      epoch 125/200: loss=0.000223, IC=-0.0027

      epoch 150/200: loss=0.000213, IC=-0.0071

      epoch 175/200: loss=0.000209, IC=-0.0101

      epoch 200/200: loss=0.000208, IC=-0.0101

    Fold 2: best_ep=25, IC=+0.0064 (23.1s)

  Fold 3: train=59,738  val=7,692

      epoch  25/200: loss=0.000371, IC=-0.0702

      epoch  50/200: loss=0.000260, IC=-0.0733

      epoch  75/200: loss=0.000221, IC=-0.0654

      epoch 100/200: loss=0.000194, IC=-0.0520

      epoch 125/200: loss=0.000182, IC=-0.0503

      epoch 150/200: loss=0.000174, IC=-0.0487

      epoch 175/200: loss=0.000169, IC=-0.0502

      epoch 200/200: loss=0.000167, IC=-0.0497

    Fold 3: best_ep=150, IC=-0.0487 (22.7s)

  Fold 4: train=58,879  val=7,692

      epoch  25/200: loss=0.000376, IC=+0.0177

      epoch  50/200: loss=0.000273, IC=+0.0244

      epoch  75/200: loss=0.000229, IC=-0.0048

      epoch 100/200: loss=0.000204, IC=+0.0057

      epoch 125/200: loss=0.000195, IC=+0.0071

      epoch 150/200: loss=0.000183, IC=+0.0132

      epoch 175/200: loss=0.000179, IC=+0.0113

      epoch 200/200: loss=0.000181, IC=+0.0123

    Fold 4: best_ep=50, IC=+0.0244 (28.2s)

    → best_epoch=100, IC=+0.0085 (116.1s)

  Best: f1ba0c34a929 @ epoch 100 (IC=+0.0085)

Preparing and releasing folds...

  Fold 0: train=60,200  val=7,038

      epoch  25/200: loss=0.002517, IC=+0.0367

      epoch  50/200: loss=0.001938, IC=+0.0504

      epoch  75/200: loss=0.001720, IC=+0.0581

      epoch 100/200: loss=0.001575, IC=+0.0536

      epoch 125/200: loss=0.001487, IC=+0.0482

      epoch 150/200: loss=0.001449, IC=+0.0507

      epoch 175/200: loss=0.001422, IC=+0.0504

      epoch 200/200: loss=0.001452, IC=+0.0505

    Fold 0: best_ep=75, IC=+0.0581 (16.9s)

  Fold 1: train=59,857  val=7,684

      epoch  25/200: loss=0.002276, IC=+0.0446

      epoch  50/200: loss=0.001735, IC=+0.0348

      epoch  75/200: loss=0.001509, IC=+0.0485

      epoch 100/200: loss=0.001389, IC=+0.0427

      epoch 125/200: loss=0.001333, IC=+0.0484

      epoch 150/200: loss=0.001287, IC=+0.0526

      epoch 175/200: loss=0.001300, IC=+0.0504

      epoch 200/200: loss=0.001279, IC=+0.0505

    Fold 1: best_ep=150, IC=+0.0526 (20.3s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.002173, IC=-0.0694

      epoch  50/200: loss=0.001601, IC=-0.1010

      epoch  75/200: loss=0.001398, IC=-0.0997

      epoch 100/200: loss=0.001294, IC=-0.1006

      epoch 125/200: loss=0.001235, IC=-0.1023

      epoch 150/200: loss=0.001203, IC=-0.0966

      epoch 175/200: loss=0.001205, IC=-0.0944

      epoch 200/200: loss=0.001181, IC=-0.0951

    Fold 2: best_ep=25, IC=-0.0694 (13.9s)

  Fold 3: train=59,210  val=7,692

      epoch  25/200: loss=0.001711, IC=-0.0658

      epoch  50/200: loss=0.001314, IC=-0.0772

      epoch  75/200: loss=0.001166, IC=-0.0813

      epoch 100/200: loss=0.001084, IC=-0.1124

      epoch 125/200: loss=0.001039, IC=-0.1086

      epoch 150/200: loss=0.001006, IC=-0.1037

      epoch 175/200: loss=0.000998, IC=-0.1081

      epoch 200/200: loss=0.001002, IC=-0.1097

    Fold 3: best_ep=25, IC=-0.0658 (13.1s)

  Fold 4: train=58,325  val=7,692

      epoch  25/200: loss=0.001912, IC=+0.0240

      epoch  50/200: loss=0.001454, IC=+0.0749

      epoch  75/200: loss=0.001253, IC=+0.0658

      epoch 100/200: loss=0.001159, IC=+0.0640

      epoch 125/200: loss=0.001089, IC=+0.0665

      epoch 150/200: loss=0.001071, IC=+0.0708

      epoch 175/200: loss=0.001053, IC=+0.0689

      epoch 200/200: loss=0.001035, IC=+0.0682

    Fold 4: best_ep=50, IC=+0.0749 (12.1s)

    → best_epoch=75, IC=-0.0027 (76.5s)

  Best: d575ade23232 @ epoch 75 (IC=-0.0027)

Preparing and releasing folds...

  Fold 0: train=60,200  val=7,038

      epoch  25/200: loss=0.001724, IC=-0.0138

      epoch  50/200: loss=0.001206, IC=-0.0073

      epoch  75/200: loss=0.001025, IC=+0.0054

      epoch 100/200: loss=0.000931, IC=+0.0150

      epoch 125/200: loss=0.000869, IC=+0.0133

      epoch 150/200: loss=0.000837, IC=+0.0162

      epoch 175/200: loss=0.000826, IC=+0.0134

      epoch 200/200: loss=0.000818, IC=+0.0133

    Fold 0: best_ep=150, IC=+0.0162 (15.9s)

  Fold 1: train=59,857  val=7,684

      epoch  25/200: loss=0.001580, IC=+0.0410

      epoch  50/200: loss=0.001090, IC=+0.0118

      epoch  75/200: loss=0.000947, IC=+0.0135

      epoch 100/200: loss=0.000842, IC=+0.0130

      epoch 125/200: loss=0.000788, IC=+0.0064

      epoch 150/200: loss=0.000754, IC=+0.0091

      epoch 175/200: loss=0.000739, IC=+0.0109

      epoch 200/200: loss=0.000734, IC=+0.0117

    Fold 1: best_ep=25, IC=+0.0410 (15.6s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.001574, IC=-0.0858

      epoch  50/200: loss=0.001090, IC=-0.0909

      epoch  75/200: loss=0.000918, IC=-0.0725

      epoch 100/200: loss=0.000817, IC=-0.0702

      epoch 125/200: loss=0.000765, IC=-0.0717

      epoch 150/200: loss=0.000742, IC=-0.0646

      epoch 175/200: loss=0.000731, IC=-0.0697

      epoch 200/200: loss=0.000729, IC=-0.0696

    Fold 2: best_ep=150, IC=-0.0646 (15.3s)

  Fold 3: train=59,210  val=7,692

      epoch  25/200: loss=0.001178, IC=-0.0762

      epoch  50/200: loss=0.000831, IC=-0.1126

      epoch  75/200: loss=0.000689, IC=-0.1043

      epoch 100/200: loss=0.000625, IC=-0.1088

      epoch 125/200: loss=0.000587, IC=-0.1233

      epoch 150/200: loss=0.000564, IC=-0.1257

      epoch 175/200: loss=0.000549, IC=-0.1268

      epoch 200/200: loss=0.000559, IC=-0.1266

    Fold 3: best_ep=25, IC=-0.0762 (15.1s)

  Fold 4: train=58,325  val=7,692

      epoch  25/200: loss=0.001229, IC=+0.0529

      epoch  50/200: loss=0.000881, IC=+0.0634

      epoch  75/200: loss=0.000756, IC=+0.0670

      epoch 100/200: loss=0.000681, IC=+0.0598

      epoch 125/200: loss=0.000638, IC=+0.0563

      epoch 150/200: loss=0.000623, IC=+0.0567

      epoch 175/200: loss=0.000606, IC=+0.0596

      epoch 200/200: loss=0.000604, IC=+0.0593

    Fold 4: best_ep=75, IC=+0.0670 (15.6s)

    → best_epoch=25, IC=-0.0164 (77.8s)

  Best: 5ccff0bd685d @ epoch 25 (IC=-0.0164)

Preparing and releasing folds...

  Fold 0: train=60,200  val=7,038

      epoch  25/200: loss=0.001178, IC=+0.0303

      epoch  50/200: loss=0.000758, IC=+0.0163

      epoch  75/200: loss=0.000615, IC=+0.0227

      epoch 100/200: loss=0.000539, IC=+0.0254

      epoch 125/200: loss=0.000493, IC=+0.0239

      epoch 150/200: loss=0.000480, IC=+0.0239

      epoch 175/200: loss=0.000460, IC=+0.0234

      epoch 200/200: loss=0.000454, IC=+0.0230

    Fold 0: best_ep=25, IC=+0.0303 (18.7s)

  Fold 1: train=59,857  val=7,684

      epoch  25/200: loss=0.001052, IC=-0.0236

      epoch  50/200: loss=0.000677, IC=-0.0420

      epoch  75/200: loss=0.000550, IC=-0.0375

      epoch 100/200: loss=0.000485, IC=-0.0364

      epoch 125/200: loss=0.000447, IC=-0.0409

      epoch 150/200: loss=0.000427, IC=-0.0431

      epoch 175/200: loss=0.000416, IC=-0.0407

      epoch 200/200: loss=0.000406, IC=-0.0399

    Fold 1: best_ep=25, IC=-0.0236 (19.5s)

  Fold 2: train=59,564  val=7,676

      epoch  25/200: loss=0.000972, IC=-0.0782

      epoch  50/200: loss=0.000634, IC=-0.0708

      epoch  75/200: loss=0.000530, IC=-0.0676

      epoch 100/200: loss=0.000464, IC=-0.0755

      epoch 125/200: loss=0.000429, IC=-0.0797

      epoch 150/200: loss=0.000405, IC=-0.0774

      epoch 175/200: loss=0.000395, IC=-0.0815

      epoch 200/200: loss=0.000387, IC=-0.0818

    Fold 2: best_ep=75, IC=-0.0676 (19.3s)

  Fold 3: train=59,210  val=7,692

      epoch  25/200: loss=0.000773, IC=-0.1050

      epoch  50/200: loss=0.000503, IC=-0.1359

      epoch  75/200: loss=0.000407, IC=-0.1310

      epoch 100/200: loss=0.000365, IC=-0.1433

      epoch 125/200: loss=0.000340, IC=-0.1301

      epoch 150/200: loss=0.000316, IC=-0.1384

      epoch 175/200: loss=0.000316, IC=-0.1359

      epoch 200/200: loss=0.000315, IC=-0.1344

    Fold 3: best_ep=25, IC=-0.1050 (20.9s)

  Fold 4: train=58,325  val=7,692

      epoch  25/200: loss=0.000847, IC=+0.0490

      epoch  50/200: loss=0.000558, IC=+0.0404

      epoch  75/200: loss=0.000455, IC=+0.0476

      epoch 100/200: loss=0.000402, IC=+0.0441

      epoch 125/200: loss=0.000371, IC=+0.0451

      epoch 150/200: loss=0.000352, IC=+0.0490

      epoch 175/200: loss=0.000343, IC=+0.0467

      epoch 200/200: loss=0.000342, IC=+0.0465

    Fold 4: best_ep=25, IC=+0.0490 (20.9s)

    → best_epoch=25, IC=-0.0264 (99.5s)

  Best: c626cf46688a @ epoch 25 (IC=-0.0264)

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("label", "config_name", "checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("TabM execution returned a partial prediction")
catalog

shape: (48, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c626cf466 ┆ 418039bbf │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 88a       ┆ 729       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c626cf466 ┆ 801d69d13 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 88a       ┆ dff       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c626cf466 ┆ 1f62cf8d0 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 88a       ┆ 2e4       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c626cf466 ┆ f07808693 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 88a       ┆ cc8       │
│ tabular_d ┆ fwd_ret_2 ┆ tabm_l    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ c626cf466 ┆ 1678f2cc1 │
│ l         ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 88a       ┆ d0c       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 0f5b1db30 ┆ 329899b68 │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ a12       ┆ 0cc       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 0f5b1db30 ┆ 53aa5ef6c │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ a12       ┆ 84c       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 0f5b1db30 ┆ 484c6fae9 │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ a12       ┆ 092       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 0f5b1db30 ┆ 6a1d426c5 │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ a12       ┆ 43c       │
│ tabular_d ┆ fwd_ret_5 ┆ tabm_s    ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 0f5b1db30 ┆ ddfd6617c │
│ l         ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ a12       ┆ 76f       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘