# CME Futures: Sequence Models

This notebook evaluates the declared NLinear and LSTM sequence configurations. Each input window
contains observations from one product and ends before its prediction timestamp. Purge gaps and
fold boundaries prevent a sequence from crossing into another validation interval, and hidden
state does not pass between products or folds.

Every declared epoch checkpoint is published with fitted weights and exact chronological
eligibility. MC dropout is not an undeclared side experiment. Configuration selection remains the
validation backtest decision in `13_backtest`.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

## What a sequence model reads that the other families do not

Every family up to this point saw one row per product per decision: a vector of features
describing that product at that moment. Anything about how it got there had to be engineered
into a column - a 21-session volatility, a momentum composite, a carry z-score against a
rolling window. The model saw the summary, never the path.

A sequence model reads the path. Its input is a window of consecutive observations for one
product, and the architecture is built to make use of their order. The claim being tested is
that the shape of recent history carries information that no fixed set of summary statistics
captured - that a product whose carry rose steadily to its current level differs from one that
spiked and fell back, even where both end at the same value with the same 21-session
volatility.

For thirty futures products the windows are also the scarcest data in the case study. A
feature-row model gets one training example per product per session; a sequence model needs a
whole window per example, so the same history yields fewer independent examples and they
overlap heavily with each other. That is the structural reason to expect these models to
struggle here relative to a benchmark with millions of series, and it is worth holding
alongside whatever the backtest reports.

### Two architectures, and why both

**LSTM** processes the window one step at a time, carrying a hidden state forward and learning
what to keep and what to forget. It is the general answer, and its generality is the cost: it
has many parameters, it trains slowly, and on a short noisy series it has ample capacity to
memorize.

**NLinear** is close to the opposite. It is a linear map from the window to the forecast, with
a normalization step that subtracts the window's last value before the map and adds it back
afterwards. That subtraction is the whole idea: it makes the model predict the *change* from
where the series currently sits rather than the level, which removes the drift that otherwise
dominates a naive fit.

It is here because a body of recent work found that simple linear baselines matched or beat
elaborate sequence architectures on many forecasting benchmarks once evaluated carefully - a
finding that survived enough scrutiny to be worth designing around. Running both is what turns
"the sophisticated model should win" into something this case study measures rather than
assumes.

## Where a sequence model can leak, and what stops it

A window is a span of time rather than a point, which gives leakage more places to enter than
the other families have.

- **Each window ends before its prediction timestamp.** The last observation a window contains
  is strictly earlier than the moment being predicted, so a forecast never reads the bar it is
  forecasting.
- **Purge gaps and fold boundaries stop a window crossing into another interval.** Without them
  a window ending just after a fold boundary would extend back across it, and validation rows
  would be predicted from a window overlapping the training period. The failure would be
  invisible in the output: the prediction is dated correctly and the returns are real.
- **Hidden state does not pass between products or folds.** An LSTM's state accumulates
  whatever it has seen, so carrying it across a boundary carries information across that
  boundary too - and unlike a feature column, the state never appears in any frame, so nothing
  downstream could detect it.

The three are separate mechanisms rather than one guarantee stated three times, which is why
they are enforced separately rather than by a single check on the output.

In [1]:
"""Fit the declared CME futures sequence-model population."""

import polars as pl

from case_studies.cme_futures.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    product_universe_table,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_catalog,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None
PREVIEW_REDUCTIONS: dict = {}
# The population hash this run replaces, read from the registry and set by a person. A
# first population takes None; a re-run whose membership has changed is refused without
# the hash it supersedes, and the refusal names the value required.
SUPERSEDES_POPULATION: str | None = None

## Declared requests

The request rows identify architecture, label, and published configuration. Sequence length,
checkpoint schedule, seed, gap policy, and device enter the resolved computation identity.

**The device is declared here rather than inherited.** With no override the shared sequence
adapter falls back to a literal `"cuda"` written in `case_studies/utils/deep_learning.py`, and
resolving the request raises `CUDA was requested for sequence training, but CUDA is unavailable`
rather than quietly moving the fit to the CPU. That refusal comes from resolving the request, so
it arrives before any fitting starts. A CUDA device is therefore a hard requirement of this
population, and stating it in the request puts that requirement where a reader meets it instead
of two layers below. The resolved specification hash is the same with the override as without,
so this names what the published run already did.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE)
requests = model_request_catalog("deep_learning", labels=ALL_LABELS)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    overrides={"device": "cuda"},
    preview_reductions=PREVIEW_REDUCTIONS,
)
universe = product_universe_table()
universe

shape: (30, 4)
┌─────────────┬─────────┬──────────────────────────┬─────────────────┐
│ sector      ┆ product ┆ expiry_rule              ┆ contract_months │
│ ---         ┆ ---     ┆ ---                      ┆ ---             │
│ str         ┆ str     ┆ str                      ┆ str             │
╞═════════════╪═════════╪══════════════════════════╪═════════════════╡
│ agriculture ┆ ZC      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ agriculture ┆ ZL      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZM      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZS      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,X   │
│ agriculture ┆ ZW      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ …           ┆ …       ┆ …                        ┆ …               │
│ metals      ┆ SI      ┆ 3rd_last_business_day    ┆ H,K,N,U,Z       │
│ treasuries  ┆ ZB      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZF      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZN      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZT      ┆ last_business_day        ┆ H,M,U,Z         │
└─────────────┴─────────┴──────────────────────────┴─────────────────┘

In [4]:
resolved_model_plan(resolved)

shape: (4, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ regressio ┆ … ┆ 2023-11-2 ┆ 20        ┆ canonical ┆ 8ee34cb7 │
│ ning      ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 81c1     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ fwd_ret_2 ┆ nlinear   ┆ regressio ┆ … ┆ 2023-11-2 ┆ 20        ┆ canonical ┆ d92b5fb2 │
│ ning      ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ c8a4     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ fwd_ret_5 ┆ lstm_h64  ┆ regressio ┆ … ┆ 2023-12-2 ┆ 20        ┆ canonical ┆ 38dd7a2d │
│ ning      ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ cbdd     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ regressio ┆ … ┆ 2023-12-2 ┆ 20        ┆ canonical ┆ a8a3dc31 │
│ ning      ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 16fd     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

The shared sequence adapter owns window construction, checkpoint reload, prediction coverage, and
restart. A failed configuration cannot remove itself from the population snapshot.

**"Cannot remove itself" is the load-bearing clause.** The natural way to write a sweep is to
catch a failure, log it, and carry on with what worked - which produces a population defined
by what happened to train rather than by what was declared. The leaderboard still looks
sensible, and the configuration that failed is indistinguishable from one that was never
requested. Sequence models make this more likely than the other families do, because they are
the ones that run out of memory or fail to converge on a thin product.

### What MC dropout is, and why it is declared rather than switched on

Dropout during training randomly disables units so the network cannot rely on any one path.
**MC dropout** leaves it enabled at prediction time and runs the forward pass several times, so
each pass gives a slightly different answer and their spread estimates the model's uncertainty
about that prediction.

That is a useful quantity - it is what an allocator sizing inversely to uncertainty would want
- but it changes what the model outputs. A prediction averaged over stochastic passes is not
the same number as the deterministic one, and a run that quietly enabled it would publish
different values under the same configuration name. So it is part of the declared
configuration and enters the identity, which is what the header means by "not an undeclared
side experiment": either the population says these predictions are MC-dropout predictions, or
they are not, and no run gets to decide that on its own.

### Why checkpoints are published rather than chosen

As in `08_tabular_dl`: a neural fit is a trajectory, and choosing the best epoch by validation
performance before reporting that model's validation performance is selection inside the
number being reported. Every declared checkpoint becomes a candidate row and `13_backtest`
selects among them on Sharpe, so the choice sits in the same funnel and the same trial count
as everything else.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_catalog(
        study,
        requests,
        population_name="cme_futures-deep_learning-validation-v1",
        resolved_requests=resolved,
        supersedes=SUPERSEDES_POPULATION,
    )
else:
    if WORKSPACE is None or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Fold-major CV: 5 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=35,301 seq across 30 symbols
    val=5,588 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.211482

      epoch   2/100: train_loss=0.091371

      epoch   3/100: train_loss=0.051564

      epoch   4/100: train_loss=0.031783

      epoch   5/100: train_loss=0.020841, val_loss=0.006030, IC=-0.0066

      epoch   6/100: train_loss=0.014805

      epoch   7/100: train_loss=0.010932

      epoch   8/100: train_loss=0.008759

      epoch   9/100: train_loss=0.006917

      epoch  10/100: train_loss=0.005751, val_loss=0.001684, IC=+0.0521

      epoch  11/100: train_loss=0.004737

      epoch  12/100: train_loss=0.004034

      epoch  13/100: train_loss=0.003449

      epoch  14/100: train_loss=0.002950

      epoch  15/100: train_loss=0.002580, val_loss=0.000845, IC=+0.0507

      epoch  16/100: train_loss=0.002276

      epoch  17/100: train_loss=0.002026

      epoch  18/100: train_loss=0.001775

      epoch  19/100: train_loss=0.001636

      epoch  20/100: train_loss=0.001483, val_loss=0.000620, IC=+0.0416

      epoch  21/100: train_loss=0.001360

      epoch  22/100: train_loss=0.001251

      epoch  23/100: train_loss=0.001172

      epoch  24/100: train_loss=0.001121

      epoch  25/100: train_loss=0.001045, val_loss=0.000544, IC=+0.0465

      epoch  26/100: train_loss=0.001001

      epoch  27/100: train_loss=0.000955

      epoch  28/100: train_loss=0.000932

      epoch  29/100: train_loss=0.000897

      epoch  30/100: train_loss=0.000881, val_loss=0.000524, IC=+0.0378

      epoch  31/100: train_loss=0.000856

      epoch  32/100: train_loss=0.000848

      epoch  33/100: train_loss=0.000813

      epoch  34/100: train_loss=0.000810

      epoch  35/100: train_loss=0.000804, val_loss=0.000515, IC=+0.0471

      epoch  36/100: train_loss=0.000783

      epoch  37/100: train_loss=0.000785

      epoch  38/100: train_loss=0.000767

      epoch  39/100: train_loss=0.000763

      epoch  40/100: train_loss=0.000769, val_loss=0.000511, IC=+0.0455

      epoch  41/100: train_loss=0.000752

      epoch  42/100: train_loss=0.000754

      epoch  43/100: train_loss=0.000750

      epoch  44/100: train_loss=0.000746

      epoch  45/100: train_loss=0.000745, val_loss=0.000510, IC=+0.0600

      epoch  46/100: train_loss=0.000737

      epoch  47/100: train_loss=0.000737

      epoch  48/100: train_loss=0.000735

      epoch  49/100: train_loss=0.000737

      epoch  50/100: train_loss=0.000735, val_loss=0.000509, IC=+0.0458

      epoch  51/100: train_loss=0.000732

      epoch  52/100: train_loss=0.000737

      epoch  53/100: train_loss=0.000730

      epoch  54/100: train_loss=0.000729

      epoch  55/100: train_loss=0.000732, val_loss=0.000508, IC=+0.0603

      epoch  56/100: train_loss=0.000731

      epoch  57/100: train_loss=0.000728

      epoch  58/100: train_loss=0.000721

      epoch  59/100: train_loss=0.000732

      epoch  60/100: train_loss=0.000732, val_loss=0.000511, IC=+0.0562

      epoch  61/100: train_loss=0.000727

      epoch  62/100: train_loss=0.000735

      epoch  63/100: train_loss=0.000729

      epoch  64/100: train_loss=0.000726

      epoch  65/100: train_loss=0.000730, val_loss=0.000510, IC=+0.0630

      epoch  66/100: train_loss=0.000732

      epoch  67/100: train_loss=0.000735

      epoch  68/100: train_loss=0.000726

      epoch  69/100: train_loss=0.000724

      epoch  70/100: train_loss=0.000723, val_loss=0.000510, IC=+0.0614

      epoch  71/100: train_loss=0.000725

      epoch  72/100: train_loss=0.000730

      epoch  73/100: train_loss=0.000721

      epoch  74/100: train_loss=0.000729

      epoch  75/100: train_loss=0.000730, val_loss=0.000510, IC=+0.0524

      epoch  76/100: train_loss=0.000731

      epoch  77/100: train_loss=0.000731

      epoch  78/100: train_loss=0.000731

      epoch  79/100: train_loss=0.000724

      epoch  80/100: train_loss=0.000728, val_loss=0.000510, IC=+0.0574

      epoch  81/100: train_loss=0.000728

      epoch  82/100: train_loss=0.000725

      epoch  83/100: train_loss=0.000725

      epoch  84/100: train_loss=0.000724

      epoch  85/100: train_loss=0.000724, val_loss=0.000510, IC=+0.0606

      epoch  86/100: train_loss=0.000721

      epoch  87/100: train_loss=0.000718

      epoch  88/100: train_loss=0.000721

      epoch  89/100: train_loss=0.000724

      epoch  90/100: train_loss=0.000725, val_loss=0.000510, IC=+0.0582

      epoch  91/100: train_loss=0.000733

      epoch  92/100: train_loss=0.000743

      epoch  93/100: train_loss=0.000727

      epoch  94/100: train_loss=0.000725

      epoch  95/100: train_loss=0.000732, val_loss=0.000510, IC=+0.0587

      epoch  96/100: train_loss=0.000729

      epoch  97/100: train_loss=0.000717

      epoch  98/100: train_loss=0.000727

      epoch  99/100: train_loss=0.000727

      epoch 100/100: train_loss=0.000724, val_loss=0.000510, IC=+0.0574

      best_ep=65, IC=+0.0630 (84.7s, 20 checkpoints)

  Fold 1: creating sequences...

    train=36,638 seq across 30 symbols
    val=5,732 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.173262

      epoch   2/100: train_loss=0.065050

      epoch   3/100: train_loss=0.035023

      epoch   4/100: train_loss=0.022451

      epoch   5/100: train_loss=0.016501, val_loss=0.023087, IC=+0.0264

      epoch   6/100: train_loss=0.012747

      epoch   7/100: train_loss=0.010147

      epoch   8/100: train_loss=0.008401

      epoch   9/100: train_loss=0.007070

      epoch  10/100: train_loss=0.005799, val_loss=0.005543, IC=-0.0012

      epoch  11/100: train_loss=0.004723

      epoch  12/100: train_loss=0.003924

      epoch  13/100: train_loss=0.003305

      epoch  14/100: train_loss=0.002819

      epoch  15/100: train_loss=0.002472, val_loss=0.003305, IC=-0.0055

      epoch  16/100: train_loss=0.002134

      epoch  17/100: train_loss=0.001829

      epoch  18/100: train_loss=0.001589

      epoch  19/100: train_loss=0.001417

      epoch  20/100: train_loss=0.001294, val_loss=0.002851, IC=-0.0136

      epoch  21/100: train_loss=0.001164

      epoch  22/100: train_loss=0.001071

      epoch  23/100: train_loss=0.000994

      epoch  24/100: train_loss=0.000936

      epoch  25/100: train_loss=0.000866, val_loss=0.002744, IC=-0.0274

      epoch  26/100: train_loss=0.000833

      epoch  27/100: train_loss=0.000804

      epoch  28/100: train_loss=0.000776

      epoch  29/100: train_loss=0.000756

      epoch  30/100: train_loss=0.000737, val_loss=0.002692, IC=-0.0239

      epoch  31/100: train_loss=0.000723

      epoch  32/100: train_loss=0.000710

      epoch  33/100: train_loss=0.000702

      epoch  34/100: train_loss=0.000693

      epoch  35/100: train_loss=0.000686, val_loss=0.002662, IC=-0.0362

      epoch  36/100: train_loss=0.000681

      epoch  37/100: train_loss=0.000676

      epoch  38/100: train_loss=0.000672

      epoch  39/100: train_loss=0.000672

      epoch  40/100: train_loss=0.000673, val_loss=0.002689, IC=-0.0441

      epoch  41/100: train_loss=0.000666

      epoch  42/100: train_loss=0.000666

      epoch  43/100: train_loss=0.000665

      epoch  44/100: train_loss=0.000665

      epoch  45/100: train_loss=0.000664, val_loss=0.002659, IC=-0.0362

      epoch  46/100: train_loss=0.000664

      epoch  47/100: train_loss=0.000663

      epoch  48/100: train_loss=0.000662

      epoch  49/100: train_loss=0.000662

      epoch  50/100: train_loss=0.000660, val_loss=0.002658, IC=-0.0385

      epoch  51/100: train_loss=0.000660

      epoch  52/100: train_loss=0.000661

      epoch  53/100: train_loss=0.000661

      epoch  54/100: train_loss=0.000661

      epoch  55/100: train_loss=0.000661, val_loss=0.002666, IC=-0.0402

      epoch  56/100: train_loss=0.000660

      epoch  57/100: train_loss=0.000659

      epoch  58/100: train_loss=0.000660

      epoch  59/100: train_loss=0.000662

      epoch  60/100: train_loss=0.000661, val_loss=0.002654, IC=-0.0143

      epoch  61/100: train_loss=0.000662

      epoch  62/100: train_loss=0.000659

      epoch  63/100: train_loss=0.000660

      epoch  64/100: train_loss=0.000660

      epoch  65/100: train_loss=0.000660, val_loss=0.002664, IC=-0.0224

      epoch  66/100: train_loss=0.000660

      epoch  67/100: train_loss=0.000659

      epoch  68/100: train_loss=0.000661

      epoch  69/100: train_loss=0.000659

      epoch  70/100: train_loss=0.000659, val_loss=0.002669, IC=-0.0422

      epoch  71/100: train_loss=0.000661

      epoch  72/100: train_loss=0.000659

      epoch  73/100: train_loss=0.000660

      epoch  74/100: train_loss=0.000659

      epoch  75/100: train_loss=0.000660, val_loss=0.002664, IC=-0.0395

      epoch  76/100: train_loss=0.000659

      epoch  77/100: train_loss=0.000659

      epoch  78/100: train_loss=0.000659

      epoch  79/100: train_loss=0.000659

      epoch  80/100: train_loss=0.000659, val_loss=0.002663, IC=-0.0322

      epoch  81/100: train_loss=0.000659

      epoch  82/100: train_loss=0.000660

      epoch  83/100: train_loss=0.000660

      epoch  84/100: train_loss=0.000658

      epoch  85/100: train_loss=0.000659, val_loss=0.002666, IC=-0.0414

      epoch  86/100: train_loss=0.000659

      epoch  87/100: train_loss=0.000659

      epoch  88/100: train_loss=0.000660

      epoch  89/100: train_loss=0.000658

      epoch  90/100: train_loss=0.000659, val_loss=0.002667, IC=-0.0436

      epoch  91/100: train_loss=0.000658

      epoch  92/100: train_loss=0.000659

      epoch  93/100: train_loss=0.000659

      epoch  94/100: train_loss=0.000659

      epoch  95/100: train_loss=0.000660, val_loss=0.002668, IC=-0.0427

      epoch  96/100: train_loss=0.000660

      epoch  97/100: train_loss=0.000659

      epoch  98/100: train_loss=0.000658

      epoch  99/100: train_loss=0.000660

      epoch 100/100: train_loss=0.000658, val_loss=0.002668, IC=-0.0421

      best_ep=5, IC=+0.0264 (88.4s, 20 checkpoints)

  Fold 2: creating sequences...

    train=37,989 seq across 30 symbols
    val=5,188 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.127833

      epoch   2/100: train_loss=0.054578

      epoch   3/100: train_loss=0.036365

      epoch   4/100: train_loss=0.025515

      epoch   5/100: train_loss=0.019094, val_loss=0.006952, IC=+0.0663

      epoch   6/100: train_loss=0.014658

      epoch   7/100: train_loss=0.011549

      epoch   8/100: train_loss=0.009632

      epoch   9/100: train_loss=0.007731

      epoch  10/100: train_loss=0.006639, val_loss=0.001995, IC=+0.0878

      epoch  11/100: train_loss=0.005496

      epoch  12/100: train_loss=0.004526

      epoch  13/100: train_loss=0.003853

      epoch  14/100: train_loss=0.003398

      epoch  15/100: train_loss=0.002959, val_loss=0.000895, IC=+0.0796

      epoch  16/100: train_loss=0.002513

      epoch  17/100: train_loss=0.002205

      epoch  18/100: train_loss=0.001960

      epoch  19/100: train_loss=0.001731

      epoch  20/100: train_loss=0.001615, val_loss=0.000681, IC=+0.0790

      epoch  21/100: train_loss=0.001492

      epoch  22/100: train_loss=0.001429

      epoch  23/100: train_loss=0.001334

      epoch  24/100: train_loss=0.001275

      epoch  25/100: train_loss=0.001194, val_loss=0.000645, IC=+0.0556

      epoch  26/100: train_loss=0.001150

      epoch  27/100: train_loss=0.001128

      epoch  28/100: train_loss=0.001088

      epoch  29/100: train_loss=0.001072

      epoch  30/100: train_loss=0.001052, val_loss=0.000647, IC=-0.0212

      epoch  31/100: train_loss=0.001037

      epoch  32/100: train_loss=0.001022

      epoch  33/100: train_loss=0.001019

      epoch  34/100: train_loss=0.001011

      epoch  35/100: train_loss=0.000995, val_loss=0.000637, IC=+0.0384

      epoch  36/100: train_loss=0.001001

      epoch  37/100: train_loss=0.000994

      epoch  38/100: train_loss=0.000991

      epoch  39/100: train_loss=0.000987

      epoch  40/100: train_loss=0.000983, val_loss=0.000650, IC=-0.0391

      epoch  41/100: train_loss=0.000983

      epoch  42/100: train_loss=0.000980

      epoch  43/100: train_loss=0.000975

      epoch  44/100: train_loss=0.000976

      epoch  45/100: train_loss=0.000986, val_loss=0.000654, IC=-0.0733

      epoch  46/100: train_loss=0.000979

      epoch  47/100: train_loss=0.000976

      epoch  48/100: train_loss=0.000994

      epoch  49/100: train_loss=0.000971

      epoch  50/100: train_loss=0.000976, val_loss=0.000650, IC=-0.0580

      epoch  51/100: train_loss=0.000980

      epoch  52/100: train_loss=0.000976

      epoch  53/100: train_loss=0.000973

      epoch  54/100: train_loss=0.000975

      epoch  55/100: train_loss=0.000974, val_loss=0.000650, IC=+0.0104

      epoch  56/100: train_loss=0.000988

      epoch  57/100: train_loss=0.000972

      epoch  58/100: train_loss=0.000980

      epoch  59/100: train_loss=0.000976

      epoch  60/100: train_loss=0.000982, val_loss=0.000652, IC=-0.0638

      epoch  61/100: train_loss=0.000979

      epoch  62/100: train_loss=0.000975

      epoch  63/100: train_loss=0.000974

      epoch  64/100: train_loss=0.000975

      epoch  65/100: train_loss=0.000972, val_loss=0.000650, IC=-0.0616

      epoch  66/100: train_loss=0.000974

      epoch  67/100: train_loss=0.000978

      epoch  68/100: train_loss=0.000976

      epoch  69/100: train_loss=0.000977

      epoch  70/100: train_loss=0.000987, val_loss=0.000658, IC=-0.0936

      epoch  71/100: train_loss=0.000972

      epoch  72/100: train_loss=0.000977

      epoch  73/100: train_loss=0.000968

      epoch  74/100: train_loss=0.000973

      epoch  75/100: train_loss=0.000980, val_loss=0.000651, IC=-0.0601

      epoch  76/100: train_loss=0.000971

      epoch  77/100: train_loss=0.000974

      epoch  78/100: train_loss=0.000990

      epoch  79/100: train_loss=0.000974

      epoch  80/100: train_loss=0.000973, val_loss=0.000651, IC=-0.0613

      epoch  81/100: train_loss=0.000972

      epoch  82/100: train_loss=0.000969

      epoch  83/100: train_loss=0.000970

      epoch  84/100: train_loss=0.000971

      epoch  85/100: train_loss=0.000972, val_loss=0.000652, IC=-0.0753

      epoch  86/100: train_loss=0.000979

      epoch  87/100: train_loss=0.000967

      epoch  88/100: train_loss=0.000982

      epoch  89/100: train_loss=0.000970

      epoch  90/100: train_loss=0.000975, val_loss=0.000652, IC=-0.0694

      epoch  91/100: train_loss=0.000984

      epoch  92/100: train_loss=0.000977

      epoch  93/100: train_loss=0.000970

      epoch  94/100: train_loss=0.000971

      epoch  95/100: train_loss=0.000968, val_loss=0.000652, IC=-0.0722

      epoch  96/100: train_loss=0.000980

      epoch  97/100: train_loss=0.000971

      epoch  98/100: train_loss=0.000976

      epoch  99/100: train_loss=0.000976

      epoch 100/100: train_loss=0.000975, val_loss=0.000651, IC=-0.0683

      best_ep=10, IC=+0.0878 (91.5s, 20 checkpoints)

  Fold 3: creating sequences...

    train=39,811 seq across 30 symbols
    val=5,740 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.495827

      epoch   2/100: train_loss=0.078379

      epoch   3/100: train_loss=0.036777

      epoch   4/100: train_loss=0.023833

      epoch   5/100: train_loss=0.016875, val_loss=0.009191, IC=+0.0353

      epoch   6/100: train_loss=0.012963

      epoch   7/100: train_loss=0.010079

      epoch   8/100: train_loss=0.008115

      epoch   9/100: train_loss=0.006727

      epoch  10/100: train_loss=0.005750, val_loss=0.003266, IC=+0.0271

      epoch  11/100: train_loss=0.005116

      epoch  12/100: train_loss=0.004445

      epoch  13/100: train_loss=0.003811

      epoch  14/100: train_loss=0.003487

      epoch  15/100: train_loss=0.003139, val_loss=0.002299, IC=+0.0045

      epoch  16/100: train_loss=0.002794

      epoch  17/100: train_loss=0.002543

      epoch  18/100: train_loss=0.002298

      epoch  19/100: train_loss=0.002123

      epoch  20/100: train_loss=0.001951, val_loss=0.002030, IC=-0.0092

      epoch  21/100: train_loss=0.001846

      epoch  22/100: train_loss=0.001731

      epoch  23/100: train_loss=0.001625

      epoch  24/100: train_loss=0.001566

      epoch  25/100: train_loss=0.001458, val_loss=0.001954, IC=-0.0082

      epoch  26/100: train_loss=0.001393

      epoch  27/100: train_loss=0.001340

      epoch  28/100: train_loss=0.001279

      epoch  29/100: train_loss=0.001249

      epoch  30/100: train_loss=0.001193, val_loss=0.001921, IC=-0.0186

      epoch  31/100: train_loss=0.001172

      epoch  32/100: train_loss=0.001144

      epoch  33/100: train_loss=0.001119

      epoch  34/100: train_loss=0.001108

      epoch  35/100: train_loss=0.001096, val_loss=0.001909, IC=-0.0214

      epoch  36/100: train_loss=0.001091

      epoch  37/100: train_loss=0.001083

      epoch  38/100: train_loss=0.001050

      epoch  39/100: train_loss=0.001042

      epoch  40/100: train_loss=0.001028, val_loss=0.001886, IC=+0.0006

      epoch  41/100: train_loss=0.001012

      epoch  42/100: train_loss=0.001011

      epoch  43/100: train_loss=0.001006

      epoch  44/100: train_loss=0.001009

      epoch  45/100: train_loss=0.000994, val_loss=0.001880, IC=-0.0031

      epoch  46/100: train_loss=0.000992

      epoch  47/100: train_loss=0.000982

      epoch  48/100: train_loss=0.000993

      epoch  49/100: train_loss=0.000983

      epoch  50/100: train_loss=0.000993, val_loss=0.001888, IC=+0.0015

      epoch  51/100: train_loss=0.000980

      epoch  52/100: train_loss=0.000974

      epoch  53/100: train_loss=0.000973

      epoch  54/100: train_loss=0.000974

      epoch  55/100: train_loss=0.000969, val_loss=0.001879, IC=+0.0017

      epoch  56/100: train_loss=0.000967

      epoch  57/100: train_loss=0.000976

      epoch  58/100: train_loss=0.000977

      epoch  59/100: train_loss=0.000971

      epoch  60/100: train_loss=0.000972, val_loss=0.001876, IC=-0.0035

      epoch  61/100: train_loss=0.000961

      epoch  62/100: train_loss=0.000975

      epoch  63/100: train_loss=0.000962

      epoch  64/100: train_loss=0.000977

      epoch  65/100: train_loss=0.000957, val_loss=0.001876, IC=-0.0090

      epoch  66/100: train_loss=0.000968

      epoch  67/100: train_loss=0.000968

      epoch  68/100: train_loss=0.000976

      epoch  69/100: train_loss=0.000962

      epoch  70/100: train_loss=0.000962, val_loss=0.001876, IC=+0.0022

      epoch  71/100: train_loss=0.000958

      epoch  72/100: train_loss=0.000960

      epoch  73/100: train_loss=0.000963

      epoch  74/100: train_loss=0.000960

      epoch  75/100: train_loss=0.000970, val_loss=0.001877, IC=-0.0063

      epoch  76/100: train_loss=0.000959

      epoch  77/100: train_loss=0.000962

      epoch  78/100: train_loss=0.000959

      epoch  79/100: train_loss=0.000960

      epoch  80/100: train_loss=0.000955, val_loss=0.001874, IC=-0.0085

      epoch  81/100: train_loss=0.000956

      epoch  82/100: train_loss=0.000965

      epoch  83/100: train_loss=0.000953

      epoch  84/100: train_loss=0.000962

      epoch  85/100: train_loss=0.000959, val_loss=0.001875, IC=-0.0081

      epoch  86/100: train_loss=0.000980

      epoch  87/100: train_loss=0.000958

      epoch  88/100: train_loss=0.000978

      epoch  89/100: train_loss=0.000950

      epoch  90/100: train_loss=0.000958, val_loss=0.001874, IC=-0.0095

      epoch  91/100: train_loss=0.000955

      epoch  92/100: train_loss=0.000958

      epoch  93/100: train_loss=0.000962

      epoch  94/100: train_loss=0.000956

      epoch  95/100: train_loss=0.000964, val_loss=0.001874, IC=-0.0103

      epoch  96/100: train_loss=0.000960

      epoch  97/100: train_loss=0.000955

      epoch  98/100: train_loss=0.000956

      epoch  99/100: train_loss=0.000961

      epoch 100/100: train_loss=0.000959, val_loss=0.001874, IC=-0.0095

      best_ep=5, IC=+0.0353 (94.8s, 20 checkpoints)

  Fold 4: creating sequences...

    train=43,008 seq across 30 symbols
    val=5,078 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.147037

      epoch   2/100: train_loss=0.059767

      epoch   3/100: train_loss=0.037657

      epoch   4/100: train_loss=0.027132

      epoch   5/100: train_loss=0.019752, val_loss=0.007449, IC=+0.0482

      epoch   6/100: train_loss=0.015090

      epoch   7/100: train_loss=0.011904

      epoch   8/100: train_loss=0.008991

      epoch   9/100: train_loss=0.007206

      epoch  10/100: train_loss=0.005551, val_loss=0.001828, IC=+0.0558

      epoch  11/100: train_loss=0.004533

      epoch  12/100: train_loss=0.003598

      epoch  13/100: train_loss=0.003026

      epoch  14/100: train_loss=0.002539

      epoch  15/100: train_loss=0.002229, val_loss=0.000847, IC=+0.0341

      epoch  16/100: train_loss=0.001980

      epoch  17/100: train_loss=0.001779

      epoch  18/100: train_loss=0.001617

      epoch  19/100: train_loss=0.001486

      epoch  20/100: train_loss=0.001398, val_loss=0.000730, IC=-0.0091

      epoch  21/100: train_loss=0.001325

      epoch  22/100: train_loss=0.001281

      epoch  23/100: train_loss=0.001240

      epoch  24/100: train_loss=0.001222

      epoch  25/100: train_loss=0.001186, val_loss=0.000723, IC=-0.0466

      epoch  26/100: train_loss=0.001162

      epoch  27/100: train_loss=0.001157

      epoch  28/100: train_loss=0.001142

      epoch  29/100: train_loss=0.001132

      epoch  30/100: train_loss=0.001128, val_loss=0.000740, IC=-0.0688

      epoch  31/100: train_loss=0.001116

      epoch  32/100: train_loss=0.001116

      epoch  33/100: train_loss=0.001115

      epoch  34/100: train_loss=0.001111

      epoch  35/100: train_loss=0.001111, val_loss=0.000737, IC=-0.0963

      epoch  36/100: train_loss=0.001106

      epoch  37/100: train_loss=0.001106

      epoch  38/100: train_loss=0.001106

      epoch  39/100: train_loss=0.001103

      epoch  40/100: train_loss=0.001101, val_loss=0.000748, IC=-0.0938

      epoch  41/100: train_loss=0.001103

      epoch  42/100: train_loss=0.001105

      epoch  43/100: train_loss=0.001105

      epoch  44/100: train_loss=0.001103

      epoch  45/100: train_loss=0.001100, val_loss=0.000743, IC=-0.0975

      epoch  46/100: train_loss=0.001103

      epoch  47/100: train_loss=0.001105

      epoch  48/100: train_loss=0.001105

      epoch  49/100: train_loss=0.001101

      epoch  50/100: train_loss=0.001104, val_loss=0.000743, IC=-0.1065

      epoch  51/100: train_loss=0.001101

      epoch  52/100: train_loss=0.001100

      epoch  53/100: train_loss=0.001103

      epoch  54/100: train_loss=0.001101

      epoch  55/100: train_loss=0.001100, val_loss=0.000740, IC=-0.1053

      epoch  56/100: train_loss=0.001104

      epoch  57/100: train_loss=0.001101

      epoch  58/100: train_loss=0.001103

      epoch  59/100: train_loss=0.001103

      epoch  60/100: train_loss=0.001100, val_loss=0.000742, IC=-0.1024

      epoch  61/100: train_loss=0.001104

      epoch  62/100: train_loss=0.001103

      epoch  63/100: train_loss=0.001102

      epoch  64/100: train_loss=0.001103

      epoch  65/100: train_loss=0.001101, val_loss=0.000742, IC=-0.1047

      epoch  66/100: train_loss=0.001105

      epoch  67/100: train_loss=0.001099

      epoch  68/100: train_loss=0.001102

      epoch  69/100: train_loss=0.001102

      epoch  70/100: train_loss=0.001101, val_loss=0.000744, IC=-0.1022

      epoch  71/100: train_loss=0.001099

      epoch  72/100: train_loss=0.001100

      epoch  73/100: train_loss=0.001098

      epoch  74/100: train_loss=0.001099

      epoch  75/100: train_loss=0.001099, val_loss=0.000748, IC=-0.0957

      epoch  76/100: train_loss=0.001104

      epoch  77/100: train_loss=0.001101

      epoch  78/100: train_loss=0.001099

      epoch  79/100: train_loss=0.001100

      epoch  80/100: train_loss=0.001101, val_loss=0.000747, IC=-0.1040

      epoch  81/100: train_loss=0.001100

      epoch  82/100: train_loss=0.001101

      epoch  83/100: train_loss=0.001097

      epoch  84/100: train_loss=0.001100

      epoch  85/100: train_loss=0.001098, val_loss=0.000747, IC=-0.0990

      epoch  86/100: train_loss=0.001100

      epoch  87/100: train_loss=0.001100

      epoch  88/100: train_loss=0.001100

      epoch  89/100: train_loss=0.001098

      epoch  90/100: train_loss=0.001099, val_loss=0.000746, IC=-0.1001

      epoch  91/100: train_loss=0.001100

      epoch  92/100: train_loss=0.001102

      epoch  93/100: train_loss=0.001103

      epoch  94/100: train_loss=0.001101

      epoch  95/100: train_loss=0.001099, val_loss=0.000745, IC=-0.1007

      epoch  96/100: train_loss=0.001099

      epoch  97/100: train_loss=0.001099

      epoch  98/100: train_loss=0.001097

      epoch  99/100: train_loss=0.001095

      epoch 100/100: train_loss=0.001101, val_loss=0.000745, IC=-0.0998

      best_ep=10, IC=+0.0558 (114.0s, 20 checkpoints)

  nlinear: best_epoch=10, IC=+0.0443 (473.4s)

  Best: nlinear @ epoch 10 (IC=+0.0443)
  Saved to ~/ml4t/public/case_studies/cme_futures/run_log/training/a8a3dc3116fd/diagnostics

Fold-major CV: 5 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=35,301 seq across 30 symbols
    val=5,588 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001022

      epoch   2/100: train_loss=0.000735

      epoch   3/100: train_loss=0.000696

      epoch   4/100: train_loss=0.000673

      epoch   5/100: train_loss=0.000649, val_loss=0.000552, IC=+0.0069

      epoch   6/100: train_loss=0.000620

      epoch   7/100: train_loss=0.000592

      epoch   8/100: train_loss=0.000573

      epoch   9/100: train_loss=0.000553

      epoch  10/100: train_loss=0.000515, val_loss=0.000644, IC=+0.0022

      epoch  11/100: train_loss=0.000499

      epoch  12/100: train_loss=0.000483

      epoch  13/100: train_loss=0.000470

      epoch  14/100: train_loss=0.000461

      epoch  15/100: train_loss=0.000443, val_loss=0.000717, IC=+0.0078

      epoch  16/100: train_loss=0.000435

      epoch  17/100: train_loss=0.000421

      epoch  18/100: train_loss=0.000410

      epoch  19/100: train_loss=0.000398

      epoch  20/100: train_loss=0.000386, val_loss=0.000704, IC=+0.0094

      epoch  21/100: train_loss=0.000382

      epoch  22/100: train_loss=0.000380

      epoch  23/100: train_loss=0.000366

      epoch  24/100: train_loss=0.000358

      epoch  25/100: train_loss=0.000360, val_loss=0.000735, IC=+0.0169

      epoch  26/100: train_loss=0.000343

      epoch  27/100: train_loss=0.000335

      epoch  28/100: train_loss=0.000335

      epoch  29/100: train_loss=0.000333

      epoch  30/100: train_loss=0.000326, val_loss=0.000760, IC=+0.0086

      epoch  31/100: train_loss=0.000323

      epoch  32/100: train_loss=0.000317

      epoch  33/100: train_loss=0.000305

      epoch  34/100: train_loss=0.000303

      epoch  35/100: train_loss=0.000305, val_loss=0.000731, IC=+0.0426

      epoch  36/100: train_loss=0.000300

      epoch  37/100: train_loss=0.000290

      epoch  38/100: train_loss=0.000287

      epoch  39/100: train_loss=0.000288

      epoch  40/100: train_loss=0.000286, val_loss=0.000753, IC=+0.0244

      epoch  41/100: train_loss=0.000284

      epoch  42/100: train_loss=0.000278

      epoch  43/100: train_loss=0.000274

      epoch  44/100: train_loss=0.000274

      epoch  45/100: train_loss=0.000269, val_loss=0.000759, IC=+0.0448

      epoch  46/100: train_loss=0.000269

      epoch  47/100: train_loss=0.000260

      epoch  48/100: train_loss=0.000260

      epoch  49/100: train_loss=0.000256

      epoch  50/100: train_loss=0.000258, val_loss=0.000770, IC=+0.0311

      epoch  51/100: train_loss=0.000252

      epoch  52/100: train_loss=0.000252

      epoch  53/100: train_loss=0.000250

      epoch  54/100: train_loss=0.000250

      epoch  55/100: train_loss=0.000246, val_loss=0.000764, IC=+0.0317

      epoch  56/100: train_loss=0.000244

      epoch  57/100: train_loss=0.000241

      epoch  58/100: train_loss=0.000241

      epoch  59/100: train_loss=0.000238

      epoch  60/100: train_loss=0.000239, val_loss=0.000765, IC=+0.0300

      epoch  61/100: train_loss=0.000235

      epoch  62/100: train_loss=0.000232

      epoch  63/100: train_loss=0.000234

      epoch  64/100: train_loss=0.000233

      epoch  65/100: train_loss=0.000232, val_loss=0.000769, IC=+0.0373

      epoch  66/100: train_loss=0.000230

      epoch  67/100: train_loss=0.000229

      epoch  68/100: train_loss=0.000226

      epoch  69/100: train_loss=0.000224

      epoch  70/100: train_loss=0.000226, val_loss=0.000767, IC=+0.0426

      epoch  71/100: train_loss=0.000222

      epoch  72/100: train_loss=0.000224

      epoch  73/100: train_loss=0.000222

      epoch  74/100: train_loss=0.000224

      epoch  75/100: train_loss=0.000221, val_loss=0.000779, IC=+0.0337

      epoch  76/100: train_loss=0.000220

      epoch  77/100: train_loss=0.000221

      epoch  78/100: train_loss=0.000220

      epoch  79/100: train_loss=0.000218

      epoch  80/100: train_loss=0.000218, val_loss=0.000782, IC=+0.0335

      epoch  81/100: train_loss=0.000216

      epoch  82/100: train_loss=0.000217

      epoch  83/100: train_loss=0.000216

      epoch  84/100: train_loss=0.000216

      epoch  85/100: train_loss=0.000213, val_loss=0.000779, IC=+0.0399

      epoch  86/100: train_loss=0.000216

      epoch  87/100: train_loss=0.000214

      epoch  88/100: train_loss=0.000213

      epoch  89/100: train_loss=0.000216

      epoch  90/100: train_loss=0.000211, val_loss=0.000782, IC=+0.0364

      epoch  91/100: train_loss=0.000214

      epoch  92/100: train_loss=0.000213

      epoch  93/100: train_loss=0.000212

      epoch  94/100: train_loss=0.000213

      epoch  95/100: train_loss=0.000213, val_loss=0.000783, IC=+0.0364

      epoch  96/100: train_loss=0.000212

      epoch  97/100: train_loss=0.000215

      epoch  98/100: train_loss=0.000212

      epoch  99/100: train_loss=0.000211

      epoch 100/100: train_loss=0.000214, val_loss=0.000783, IC=+0.0371

      best_ep=45, IC=+0.0448 (126.6s, 20 checkpoints)

  Fold 1: creating sequences...

    train=36,638 seq across 30 symbols
    val=5,732 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001132

      epoch   2/100: train_loss=0.000692

      epoch   3/100: train_loss=0.000648

      epoch   4/100: train_loss=0.000629

      epoch   5/100: train_loss=0.000607, val_loss=0.002903, IC=-0.0261

      epoch   6/100: train_loss=0.000584

      epoch   7/100: train_loss=0.000556

      epoch   8/100: train_loss=0.000530

      epoch   9/100: train_loss=0.000506

      epoch  10/100: train_loss=0.000488, val_loss=0.003364, IC=-0.0316

      epoch  11/100: train_loss=0.000468

      epoch  12/100: train_loss=0.000451

      epoch  13/100: train_loss=0.000432

      epoch  14/100: train_loss=0.000428

      epoch  15/100: train_loss=0.000407, val_loss=0.003775, IC=-0.0349

      epoch  16/100: train_loss=0.000397

      epoch  17/100: train_loss=0.000389

      epoch  18/100: train_loss=0.000381

      epoch  19/100: train_loss=0.000370

      epoch  20/100: train_loss=0.000356, val_loss=0.003754, IC=-0.0046

      epoch  21/100: train_loss=0.000352

      epoch  22/100: train_loss=0.000350

      epoch  23/100: train_loss=0.000344

      epoch  24/100: train_loss=0.000334

      epoch  25/100: train_loss=0.000327, val_loss=0.003668, IC=-0.0168

      epoch  26/100: train_loss=0.000322

      epoch  27/100: train_loss=0.000316

      epoch  28/100: train_loss=0.000311

      epoch  29/100: train_loss=0.000302

      epoch  30/100: train_loss=0.000295, val_loss=0.003752, IC=-0.0303

      epoch  31/100: train_loss=0.000293

      epoch  32/100: train_loss=0.000289

      epoch  33/100: train_loss=0.000282

      epoch  34/100: train_loss=0.000279

      epoch  35/100: train_loss=0.000276, val_loss=0.003669, IC=-0.0231

      epoch  36/100: train_loss=0.000270

      epoch  37/100: train_loss=0.000270

      epoch  38/100: train_loss=0.000266

      epoch  39/100: train_loss=0.000261

      epoch  40/100: train_loss=0.000258, val_loss=0.003671, IC=-0.0357

      epoch  41/100: train_loss=0.000257

      epoch  42/100: train_loss=0.000253

      epoch  43/100: train_loss=0.000248

      epoch  44/100: train_loss=0.000245

      epoch  45/100: train_loss=0.000244, val_loss=0.003641, IC=-0.0389

      epoch  46/100: train_loss=0.000241

      epoch  47/100: train_loss=0.000240

      epoch  48/100: train_loss=0.000236

      epoch  49/100: train_loss=0.000234

      epoch  50/100: train_loss=0.000231, val_loss=0.003606, IC=-0.0282

      epoch  51/100: train_loss=0.000230

      epoch  52/100: train_loss=0.000226

      epoch  53/100: train_loss=0.000226

      epoch  54/100: train_loss=0.000226

      epoch  55/100: train_loss=0.000222, val_loss=0.003633, IC=-0.0262

      epoch  56/100: train_loss=0.000221

      epoch  57/100: train_loss=0.000221

      epoch  58/100: train_loss=0.000217

      epoch  59/100: train_loss=0.000214

      epoch  60/100: train_loss=0.000213, val_loss=0.003594, IC=-0.0245

      epoch  61/100: train_loss=0.000213

      epoch  62/100: train_loss=0.000208

      epoch  63/100: train_loss=0.000210

      epoch  64/100: train_loss=0.000209

      epoch  65/100: train_loss=0.000208, val_loss=0.003632, IC=-0.0301

      epoch  66/100: train_loss=0.000207

      epoch  67/100: train_loss=0.000207

      epoch  68/100: train_loss=0.000205

      epoch  69/100: train_loss=0.000203

      epoch  70/100: train_loss=0.000203, val_loss=0.003590, IC=-0.0285

      epoch  71/100: train_loss=0.000202

      epoch  72/100: train_loss=0.000203

      epoch  73/100: train_loss=0.000200

      epoch  74/100: train_loss=0.000200

      epoch  75/100: train_loss=0.000197, val_loss=0.003588, IC=-0.0261

      epoch  76/100: train_loss=0.000199

      epoch  77/100: train_loss=0.000198

      epoch  78/100: train_loss=0.000197

      epoch  79/100: train_loss=0.000195

      epoch  80/100: train_loss=0.000197, val_loss=0.003589, IC=-0.0261

      epoch  81/100: train_loss=0.000195

      epoch  82/100: train_loss=0.000195

      epoch  83/100: train_loss=0.000195

      epoch  84/100: train_loss=0.000194

      epoch  85/100: train_loss=0.000194, val_loss=0.003601, IC=-0.0258

      epoch  86/100: train_loss=0.000193

      epoch  87/100: train_loss=0.000194

      epoch  88/100: train_loss=0.000194

      epoch  89/100: train_loss=0.000190

      epoch  90/100: train_loss=0.000191, val_loss=0.003607, IC=-0.0272

      epoch  91/100: train_loss=0.000193

      epoch  92/100: train_loss=0.000193

      epoch  93/100: train_loss=0.000192

      epoch  94/100: train_loss=0.000190

      epoch  95/100: train_loss=0.000192, val_loss=0.003592, IC=-0.0245

      epoch  96/100: train_loss=0.000192

      epoch  97/100: train_loss=0.000193

      epoch  98/100: train_loss=0.000191

      epoch  99/100: train_loss=0.000193

      epoch 100/100: train_loss=0.000192, val_loss=0.003594, IC=-0.0247

      best_ep=20, IC=-0.0046 (115.6s, 20 checkpoints)

  Fold 2: creating sequences...

    train=37,989 seq across 30 symbols
    val=5,188 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.003892

      epoch   2/100: train_loss=0.001157

      epoch   3/100: train_loss=0.001010

      epoch   4/100: train_loss=0.000965

      epoch   5/100: train_loss=0.000930, val_loss=0.000706, IC=+0.0141

      epoch   6/100: train_loss=0.000910

      epoch   7/100: train_loss=0.000881

      epoch   8/100: train_loss=0.000843

      epoch   9/100: train_loss=0.000812

      epoch  10/100: train_loss=0.000775, val_loss=0.000723, IC=-0.0161

      epoch  11/100: train_loss=0.000735

      epoch  12/100: train_loss=0.000711

      epoch  13/100: train_loss=0.000674

      epoch  14/100: train_loss=0.000640

      epoch  15/100: train_loss=0.000638, val_loss=0.000848, IC=-0.0183

      epoch  16/100: train_loss=0.000617

      epoch  17/100: train_loss=0.000597

      epoch  18/100: train_loss=0.000579

      epoch  19/100: train_loss=0.000562

      epoch  20/100: train_loss=0.000543, val_loss=0.000911, IC=-0.0318

      epoch  21/100: train_loss=0.000533

      epoch  22/100: train_loss=0.000516

      epoch  23/100: train_loss=0.000515

      epoch  24/100: train_loss=0.000501

      epoch  25/100: train_loss=0.000486, val_loss=0.001078, IC=-0.0348

      epoch  26/100: train_loss=0.000476

      epoch  27/100: train_loss=0.000460

      epoch  28/100: train_loss=0.000466

      epoch  29/100: train_loss=0.000459

      epoch  30/100: train_loss=0.000443, val_loss=0.001142, IC=-0.0543

      epoch  31/100: train_loss=0.000444

      epoch  32/100: train_loss=0.000435

      epoch  33/100: train_loss=0.000425

      epoch  34/100: train_loss=0.000419

      epoch  35/100: train_loss=0.000412, val_loss=0.001212, IC=-0.0369

      epoch  36/100: train_loss=0.000408

      epoch  37/100: train_loss=0.000400

      epoch  38/100: train_loss=0.000401

      epoch  39/100: train_loss=0.000392

      epoch  40/100: train_loss=0.000387, val_loss=0.001403, IC=-0.0643

      epoch  41/100: train_loss=0.000384

      epoch  42/100: train_loss=0.000378

      epoch  43/100: train_loss=0.000376

      epoch  44/100: train_loss=0.000371

      epoch  45/100: train_loss=0.000371, val_loss=0.001463, IC=-0.0516

      epoch  46/100: train_loss=0.000368

      epoch  47/100: train_loss=0.000357

      epoch  48/100: train_loss=0.000355

      epoch  49/100: train_loss=0.000352

      epoch  50/100: train_loss=0.000347, val_loss=0.001608, IC=-0.0647

      epoch  51/100: train_loss=0.000347

      epoch  52/100: train_loss=0.000342

      epoch  53/100: train_loss=0.000342

      epoch  54/100: train_loss=0.000341

      epoch  55/100: train_loss=0.000339, val_loss=0.001560, IC=-0.0674

      epoch  56/100: train_loss=0.000335

      epoch  57/100: train_loss=0.000331

      epoch  58/100: train_loss=0.000330

      epoch  59/100: train_loss=0.000329

      epoch  60/100: train_loss=0.000322, val_loss=0.001705, IC=-0.0712

      epoch  61/100: train_loss=0.000321

      epoch  62/100: train_loss=0.000323

      epoch  63/100: train_loss=0.000319

      epoch  64/100: train_loss=0.000317

      epoch  65/100: train_loss=0.000312, val_loss=0.001816, IC=-0.0748

      epoch  66/100: train_loss=0.000311

      epoch  67/100: train_loss=0.000310

      epoch  68/100: train_loss=0.000310

      epoch  69/100: train_loss=0.000306

      epoch  70/100: train_loss=0.000309, val_loss=0.001810, IC=-0.0704

      epoch  71/100: train_loss=0.000302

      epoch  72/100: train_loss=0.000306

      epoch  73/100: train_loss=0.000302

      epoch  74/100: train_loss=0.000300

      epoch  75/100: train_loss=0.000299, val_loss=0.001855, IC=-0.0724

      epoch  76/100: train_loss=0.000299

      epoch  77/100: train_loss=0.000299

      epoch  78/100: train_loss=0.000295

      epoch  79/100: train_loss=0.000295

      epoch  80/100: train_loss=0.000298, val_loss=0.001986, IC=-0.0799

      epoch  81/100: train_loss=0.000297

      epoch  82/100: train_loss=0.000294

      epoch  83/100: train_loss=0.000291

      epoch  84/100: train_loss=0.000289

      epoch  85/100: train_loss=0.000290, val_loss=0.001933, IC=-0.0760

      epoch  86/100: train_loss=0.000295

      epoch  87/100: train_loss=0.000291

      epoch  88/100: train_loss=0.000290

      epoch  89/100: train_loss=0.000289

      epoch  90/100: train_loss=0.000290, val_loss=0.001942, IC=-0.0772

      epoch  91/100: train_loss=0.000288

      epoch  92/100: train_loss=0.000288

      epoch  93/100: train_loss=0.000288

      epoch  94/100: train_loss=0.000288

      epoch  95/100: train_loss=0.000288, val_loss=0.001948, IC=-0.0767

      epoch  96/100: train_loss=0.000287

      epoch  97/100: train_loss=0.000289

      epoch  98/100: train_loss=0.000287

      epoch  99/100: train_loss=0.000288

      epoch 100/100: train_loss=0.000288, val_loss=0.001947, IC=-0.0772

      best_ep=5, IC=+0.0141 (141.2s, 20 checkpoints)

  Fold 3: creating sequences...

    train=39,811 seq across 30 symbols
    val=5,740 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001790

      epoch   2/100: train_loss=0.000996

      epoch   3/100: train_loss=0.000933

      epoch   4/100: train_loss=0.000879

      epoch   5/100: train_loss=0.000844, val_loss=0.001902, IC=+0.0258

      epoch   6/100: train_loss=0.000803

      epoch   7/100: train_loss=0.000763

      epoch   8/100: train_loss=0.000723

      epoch   9/100: train_loss=0.000689

      epoch  10/100: train_loss=0.000665, val_loss=0.002064, IC=+0.0055

      epoch  11/100: train_loss=0.000626

      epoch  12/100: train_loss=0.000603

      epoch  13/100: train_loss=0.000596

      epoch  14/100: train_loss=0.000564

      epoch  15/100: train_loss=0.000550, val_loss=0.002169, IC=+0.0373

      epoch  16/100: train_loss=0.000524

      epoch  17/100: train_loss=0.000510

      epoch  18/100: train_loss=0.000501

      epoch  19/100: train_loss=0.000483

      epoch  20/100: train_loss=0.000472, val_loss=0.002183, IC=+0.0254

      epoch  21/100: train_loss=0.000464

      epoch  22/100: train_loss=0.000454

      epoch  23/100: train_loss=0.000437

      epoch  24/100: train_loss=0.000438

      epoch  25/100: train_loss=0.000422, val_loss=0.002143, IC=+0.0416

      epoch  26/100: train_loss=0.000414

      epoch  27/100: train_loss=0.000407

      epoch  28/100: train_loss=0.000400

      epoch  29/100: train_loss=0.000398

      epoch  30/100: train_loss=0.000382, val_loss=0.002386, IC=+0.0289

      epoch  31/100: train_loss=0.000381

      epoch  32/100: train_loss=0.000368

      epoch  33/100: train_loss=0.000372

      epoch  34/100: train_loss=0.000360

      epoch  35/100: train_loss=0.000356, val_loss=0.002220, IC=+0.0596

      epoch  36/100: train_loss=0.000352

      epoch  37/100: train_loss=0.000347

      epoch  38/100: train_loss=0.000337

      epoch  39/100: train_loss=0.000333

      epoch  40/100: train_loss=0.000326, val_loss=0.002216, IC=+0.0549

      epoch  41/100: train_loss=0.000325

      epoch  42/100: train_loss=0.000325

      epoch  43/100: train_loss=0.000318

      epoch  44/100: train_loss=0.000317

      epoch  45/100: train_loss=0.000312, val_loss=0.002179, IC=+0.0672

      epoch  46/100: train_loss=0.000311

      epoch  47/100: train_loss=0.000304

      epoch  48/100: train_loss=0.000302

      epoch  49/100: train_loss=0.000298

      epoch  50/100: train_loss=0.000292, val_loss=0.002320, IC=+0.0491

      epoch  51/100: train_loss=0.000290

      epoch  52/100: train_loss=0.000292

      epoch  53/100: train_loss=0.000289

      epoch  54/100: train_loss=0.000284

      epoch  55/100: train_loss=0.000280, val_loss=0.002195, IC=+0.0623

      epoch  56/100: train_loss=0.000278

      epoch  57/100: train_loss=0.000277

      epoch  58/100: train_loss=0.000273

      epoch  59/100: train_loss=0.000275

      epoch  60/100: train_loss=0.000270, val_loss=0.002243, IC=+0.0513

      epoch  61/100: train_loss=0.000269

      epoch  62/100: train_loss=0.000266

      epoch  63/100: train_loss=0.000265

      epoch  64/100: train_loss=0.000264

      epoch  65/100: train_loss=0.000263, val_loss=0.002233, IC=+0.0610

      epoch  66/100: train_loss=0.000260

      epoch  67/100: train_loss=0.000260

      epoch  68/100: train_loss=0.000255

      epoch  69/100: train_loss=0.000254

      epoch  70/100: train_loss=0.000252, val_loss=0.002257, IC=+0.0573

      epoch  71/100: train_loss=0.000254

      epoch  72/100: train_loss=0.000255

      epoch  73/100: train_loss=0.000252

      epoch  74/100: train_loss=0.000249

      epoch  75/100: train_loss=0.000249, val_loss=0.002273, IC=+0.0582

      epoch  76/100: train_loss=0.000249

      epoch  77/100: train_loss=0.000247

      epoch  78/100: train_loss=0.000247

      epoch  79/100: train_loss=0.000245

      epoch  80/100: train_loss=0.000246, val_loss=0.002283, IC=+0.0563

      epoch  81/100: train_loss=0.000245

      epoch  82/100: train_loss=0.000242

      epoch  83/100: train_loss=0.000245

      epoch  84/100: train_loss=0.000240

      epoch  85/100: train_loss=0.000237, val_loss=0.002280, IC=+0.0591

      epoch  86/100: train_loss=0.000241

      epoch  87/100: train_loss=0.000240

      epoch  88/100: train_loss=0.000240

      epoch  89/100: train_loss=0.000240

      epoch  90/100: train_loss=0.000238, val_loss=0.002276, IC=+0.0610

      epoch  91/100: train_loss=0.000239

      epoch  92/100: train_loss=0.000237

      epoch  93/100: train_loss=0.000240

      epoch  94/100: train_loss=0.000240

      epoch  95/100: train_loss=0.000240, val_loss=0.002281, IC=+0.0609

      epoch  96/100: train_loss=0.000240

      epoch  97/100: train_loss=0.000240

      epoch  98/100: train_loss=0.000238

      epoch  99/100: train_loss=0.000237

      epoch 100/100: train_loss=0.000238, val_loss=0.002279, IC=+0.0609

      best_ep=45, IC=+0.0672 (150.1s, 20 checkpoints)

  Fold 4: creating sequences...

    train=43,008 seq across 30 symbols
    val=5,078 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001292

      epoch   2/100: train_loss=0.001062

      epoch   3/100: train_loss=0.000995

      epoch   4/100: train_loss=0.000935

      epoch   5/100: train_loss=0.000859, val_loss=0.001084, IC=+0.0219

      epoch   6/100: train_loss=0.000805

      epoch   7/100: train_loss=0.000762

      epoch   8/100: train_loss=0.000720

      epoch   9/100: train_loss=0.000677

      epoch  10/100: train_loss=0.000658, val_loss=0.001079, IC=+0.0212

      epoch  11/100: train_loss=0.000624

      epoch  12/100: train_loss=0.000605

      epoch  13/100: train_loss=0.000597

      epoch  14/100: train_loss=0.000575

      epoch  15/100: train_loss=0.000560, val_loss=0.001109, IC=-0.0227

      epoch  16/100: train_loss=0.000542

      epoch  17/100: train_loss=0.000530

      epoch  18/100: train_loss=0.000517

      epoch  19/100: train_loss=0.000510

      epoch  20/100: train_loss=0.000484, val_loss=0.001199, IC=-0.0312

      epoch  21/100: train_loss=0.000476

      epoch  22/100: train_loss=0.000470

      epoch  23/100: train_loss=0.000466

      epoch  24/100: train_loss=0.000448

      epoch  25/100: train_loss=0.000440, val_loss=0.001129, IC=-0.0307

      epoch  26/100: train_loss=0.000431

      epoch  27/100: train_loss=0.000426

      epoch  28/100: train_loss=0.000415

      epoch  29/100: train_loss=0.000411

      epoch  30/100: train_loss=0.000405, val_loss=0.001109, IC=-0.0557

      epoch  31/100: train_loss=0.000398

      epoch  32/100: train_loss=0.000390

      epoch  33/100: train_loss=0.000385

      epoch  34/100: train_loss=0.000383

      epoch  35/100: train_loss=0.000376, val_loss=0.001113, IC=-0.0775

      epoch  36/100: train_loss=0.000369

      epoch  37/100: train_loss=0.000363

      epoch  38/100: train_loss=0.000359

      epoch  39/100: train_loss=0.000352

      epoch  40/100: train_loss=0.000356, val_loss=0.001126, IC=-0.0645

      epoch  41/100: train_loss=0.000345

      epoch  42/100: train_loss=0.000348

      epoch  43/100: train_loss=0.000345

      epoch  44/100: train_loss=0.000334

      epoch  45/100: train_loss=0.000330, val_loss=0.001108, IC=-0.0678

      epoch  46/100: train_loss=0.000322

      epoch  47/100: train_loss=0.000324

      epoch  48/100: train_loss=0.000316

      epoch  49/100: train_loss=0.000312

      epoch  50/100: train_loss=0.000312, val_loss=0.001148, IC=-0.0740

      epoch  51/100: train_loss=0.000308

      epoch  52/100: train_loss=0.000306

      epoch  53/100: train_loss=0.000304

      epoch  54/100: train_loss=0.000301

      epoch  55/100: train_loss=0.000298, val_loss=0.001108, IC=-0.0647

      epoch  56/100: train_loss=0.000299

      epoch  57/100: train_loss=0.000291

      epoch  58/100: train_loss=0.000293

      epoch  59/100: train_loss=0.000288

      epoch  60/100: train_loss=0.000284, val_loss=0.001106, IC=-0.0663

      epoch  61/100: train_loss=0.000284

      epoch  62/100: train_loss=0.000283

      epoch  63/100: train_loss=0.000281

      epoch  64/100: train_loss=0.000277

      epoch  65/100: train_loss=0.000279, val_loss=0.001115, IC=-0.0741

      epoch  66/100: train_loss=0.000275

      epoch  67/100: train_loss=0.000271

      epoch  68/100: train_loss=0.000274

      epoch  69/100: train_loss=0.000273

      epoch  70/100: train_loss=0.000272, val_loss=0.001134, IC=-0.0685

      epoch  71/100: train_loss=0.000267

      epoch  72/100: train_loss=0.000269

      epoch  73/100: train_loss=0.000266

      epoch  74/100: train_loss=0.000267

      epoch  75/100: train_loss=0.000266, val_loss=0.001132, IC=-0.0674

      epoch  76/100: train_loss=0.000263

      epoch  77/100: train_loss=0.000261

      epoch  78/100: train_loss=0.000260

      epoch  79/100: train_loss=0.000263

      epoch  80/100: train_loss=0.000260, val_loss=0.001143, IC=-0.0652

      epoch  81/100: train_loss=0.000259

      epoch  82/100: train_loss=0.000257

      epoch  83/100: train_loss=0.000260

      epoch  84/100: train_loss=0.000258

      epoch  85/100: train_loss=0.000259, val_loss=0.001136, IC=-0.0653

      epoch  86/100: train_loss=0.000256

      epoch  87/100: train_loss=0.000259

      epoch  88/100: train_loss=0.000255

      epoch  89/100: train_loss=0.000255

      epoch  90/100: train_loss=0.000255, val_loss=0.001139, IC=-0.0655

      epoch  91/100: train_loss=0.000255

      epoch  92/100: train_loss=0.000257

      epoch  93/100: train_loss=0.000254

      epoch  94/100: train_loss=0.000255

      epoch  95/100: train_loss=0.000254, val_loss=0.001138, IC=-0.0656

      epoch  96/100: train_loss=0.000253

      epoch  97/100: train_loss=0.000256

      epoch  98/100: train_loss=0.000253

      epoch  99/100: train_loss=0.000252

      epoch 100/100: train_loss=0.000254, val_loss=0.001139, IC=-0.0653

      best_ep=5, IC=+0.0219 (158.5s, 20 checkpoints)

  lstm_h64: best_epoch=5, IC=+0.0085 (692.0s)

  Best: lstm_h64 @ epoch 5 (IC=+0.0085)
  Saved to ~/ml4t/public/case_studies/cme_futures/run_log/training/38dd7a2dcbdd/diagnostics

Fold-major CV: 5 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=34,983 seq across 30 symbols
    val=5,588 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.216428

      epoch   2/100: train_loss=0.095786

      epoch   3/100: train_loss=0.053806

      epoch   4/100: train_loss=0.033138

      epoch   5/100: train_loss=0.022789, val_loss=0.007514, IC=+0.0111

      epoch   6/100: train_loss=0.017225

      epoch   7/100: train_loss=0.013124

      epoch   8/100: train_loss=0.010824

      epoch   9/100: train_loss=0.008984

      epoch  10/100: train_loss=0.008022, val_loss=0.003212, IC=+0.0407

      epoch  11/100: train_loss=0.006921

      epoch  12/100: train_loss=0.006193

      epoch  13/100: train_loss=0.005599

      epoch  14/100: train_loss=0.005034

      epoch  15/100: train_loss=0.004711, val_loss=0.002377, IC=+0.0673

      epoch  16/100: train_loss=0.004430

      epoch  17/100: train_loss=0.004133

      epoch  18/100: train_loss=0.003965

      epoch  19/100: train_loss=0.003690

      epoch  20/100: train_loss=0.003598, val_loss=0.002110, IC=+0.1071

      epoch  21/100: train_loss=0.003454

      epoch  22/100: train_loss=0.003415

      epoch  23/100: train_loss=0.003267

      epoch  24/100: train_loss=0.003227

      epoch  25/100: train_loss=0.003209, val_loss=0.002050, IC=+0.1462

      epoch  26/100: train_loss=0.003113

      epoch  27/100: train_loss=0.003077

      epoch  28/100: train_loss=0.003049

      epoch  29/100: train_loss=0.003018

      epoch  30/100: train_loss=0.003001, val_loss=0.002010, IC=+0.1673

      epoch  31/100: train_loss=0.002888

      epoch  32/100: train_loss=0.002948

      epoch  33/100: train_loss=0.002929

      epoch  34/100: train_loss=0.002905

      epoch  35/100: train_loss=0.002914, val_loss=0.002015, IC=+0.1541

      epoch  36/100: train_loss=0.002904

      epoch  37/100: train_loss=0.002844

      epoch  38/100: train_loss=0.002855

      epoch  39/100: train_loss=0.002905

      epoch  40/100: train_loss=0.002870, val_loss=0.001996, IC=+0.1861

      epoch  41/100: train_loss=0.002903

      epoch  42/100: train_loss=0.002853

      epoch  43/100: train_loss=0.002907

      epoch  44/100: train_loss=0.002858

      epoch  45/100: train_loss=0.002851, val_loss=0.002003, IC=+0.1782

      epoch  46/100: train_loss=0.002850

      epoch  47/100: train_loss=0.002827

      epoch  48/100: train_loss=0.002823

      epoch  49/100: train_loss=0.002845

      epoch  50/100: train_loss=0.002849, val_loss=0.001983, IC=+0.1937

      epoch  51/100: train_loss=0.002860

      epoch  52/100: train_loss=0.002807

      epoch  53/100: train_loss=0.002860

      epoch  54/100: train_loss=0.002830

      epoch  55/100: train_loss=0.002799, val_loss=0.001988, IC=+0.1936

      epoch  56/100: train_loss=0.002822

      epoch  57/100: train_loss=0.002819

      epoch  58/100: train_loss=0.002807

      epoch  59/100: train_loss=0.002897

      epoch  60/100: train_loss=0.002799, val_loss=0.001985, IC=+0.1993

      epoch  61/100: train_loss=0.002835

      epoch  62/100: train_loss=0.002801

      epoch  63/100: train_loss=0.002820

      epoch  64/100: train_loss=0.002830

      epoch  65/100: train_loss=0.002843, val_loss=0.001982, IC=+0.1821

      epoch  66/100: train_loss=0.002783

      epoch  67/100: train_loss=0.002833

      epoch  68/100: train_loss=0.002783

      epoch  69/100: train_loss=0.002836

      epoch  70/100: train_loss=0.002846, val_loss=0.001989, IC=+0.1778

      epoch  71/100: train_loss=0.002828

      epoch  72/100: train_loss=0.002841

      epoch  73/100: train_loss=0.002826

      epoch  74/100: train_loss=0.002818

      epoch  75/100: train_loss=0.002807, val_loss=0.001988, IC=+0.1808

      epoch  76/100: train_loss=0.002787

      epoch  77/100: train_loss=0.002841

      epoch  78/100: train_loss=0.002840

      epoch  79/100: train_loss=0.002804

      epoch  80/100: train_loss=0.002870, val_loss=0.001993, IC=+0.1835

      epoch  81/100: train_loss=0.002816

      epoch  82/100: train_loss=0.002798

      epoch  83/100: train_loss=0.002812

      epoch  84/100: train_loss=0.002816

      epoch  85/100: train_loss=0.002795, val_loss=0.001988, IC=+0.1916

      epoch  86/100: train_loss=0.002811

      epoch  87/100: train_loss=0.002843

      epoch  88/100: train_loss=0.002842

      epoch  89/100: train_loss=0.002802

      epoch  90/100: train_loss=0.002800, val_loss=0.001986, IC=+0.1814

      epoch  91/100: train_loss=0.002824

      epoch  92/100: train_loss=0.002771

      epoch  93/100: train_loss=0.002826

      epoch  94/100: train_loss=0.002776

      epoch  95/100: train_loss=0.002797, val_loss=0.001987, IC=+0.1836

      epoch  96/100: train_loss=0.002793

      epoch  97/100: train_loss=0.002780

      epoch  98/100: train_loss=0.002793

      epoch  99/100: train_loss=0.002799

      epoch 100/100: train_loss=0.002799, val_loss=0.001987, IC=+0.1830

      best_ep=60, IC=+0.1993 (111.2s, 20 checkpoints)

  Fold 1: creating sequences...

    train=36,286 seq across 30 symbols
    val=5,732 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.175728

      epoch   2/100: train_loss=0.068006

      epoch   3/100: train_loss=0.037558

      epoch   4/100: train_loss=0.024897

      epoch   5/100: train_loss=0.018248, val_loss=0.027257, IC=+0.1215

      epoch   6/100: train_loss=0.014786

      epoch   7/100: train_loss=0.012284

      epoch   8/100: train_loss=0.010374

      epoch   9/100: train_loss=0.008783

      epoch  10/100: train_loss=0.007842, val_loss=0.012752, IC=+0.0507

      epoch  11/100: train_loss=0.006561

      epoch  12/100: train_loss=0.005832

      epoch  13/100: train_loss=0.005311

      epoch  14/100: train_loss=0.004745

      epoch  15/100: train_loss=0.004330, val_loss=0.011532, IC=+0.0125

      epoch  16/100: train_loss=0.004023

      epoch  17/100: train_loss=0.003750

      epoch  18/100: train_loss=0.003511

      epoch  19/100: train_loss=0.003348

      epoch  20/100: train_loss=0.003218, val_loss=0.011340, IC=+0.0171

      epoch  21/100: train_loss=0.003080

      epoch  22/100: train_loss=0.002997

      epoch  23/100: train_loss=0.002925

      epoch  24/100: train_loss=0.002865

      epoch  25/100: train_loss=0.002819, val_loss=0.011414, IC=-0.0273

      epoch  26/100: train_loss=0.002765

      epoch  27/100: train_loss=0.002735

      epoch  28/100: train_loss=0.002702

      epoch  29/100: train_loss=0.002685

      epoch  30/100: train_loss=0.002669, val_loss=0.011520, IC=-0.0381

      epoch  31/100: train_loss=0.002663

      epoch  32/100: train_loss=0.002637

      epoch  33/100: train_loss=0.002620

      epoch  34/100: train_loss=0.002629

      epoch  35/100: train_loss=0.002623, val_loss=0.011476, IC=-0.0446

      epoch  36/100: train_loss=0.002610

      epoch  37/100: train_loss=0.002611

      epoch  38/100: train_loss=0.002599

      epoch  39/100: train_loss=0.002596

      epoch  40/100: train_loss=0.002609, val_loss=0.011605, IC=-0.0461

      epoch  41/100: train_loss=0.002594

      epoch  42/100: train_loss=0.002596

      epoch  43/100: train_loss=0.002586

      epoch  44/100: train_loss=0.002591

      epoch  45/100: train_loss=0.002594, val_loss=0.011575, IC=-0.0506

      epoch  46/100: train_loss=0.002593

      epoch  47/100: train_loss=0.002601

      epoch  48/100: train_loss=0.002601

      epoch  49/100: train_loss=0.002583

      epoch  50/100: train_loss=0.002596, val_loss=0.011579, IC=-0.0459

      epoch  51/100: train_loss=0.002585

      epoch  52/100: train_loss=0.002584

      epoch  53/100: train_loss=0.002588

      epoch  54/100: train_loss=0.002593

      epoch  55/100: train_loss=0.002584, val_loss=0.011587, IC=-0.0424

      epoch  56/100: train_loss=0.002586

      epoch  57/100: train_loss=0.002582

      epoch  58/100: train_loss=0.002593

      epoch  59/100: train_loss=0.002594

      epoch  60/100: train_loss=0.002587, val_loss=0.011428, IC=-0.0102

      epoch  61/100: train_loss=0.002578

      epoch  62/100: train_loss=0.002589

      epoch  63/100: train_loss=0.002589

      epoch  64/100: train_loss=0.002578

      epoch  65/100: train_loss=0.002592, val_loss=0.011611, IC=-0.0472

      epoch  66/100: train_loss=0.002584

      epoch  67/100: train_loss=0.002578

      epoch  68/100: train_loss=0.002589

      epoch  69/100: train_loss=0.002581

      epoch  70/100: train_loss=0.002586, val_loss=0.011534, IC=-0.0304

      epoch  71/100: train_loss=0.002596

      epoch  72/100: train_loss=0.002586

      epoch  73/100: train_loss=0.002591

      epoch  74/100: train_loss=0.002584

      epoch  75/100: train_loss=0.002582, val_loss=0.011583, IC=-0.0442

      epoch  76/100: train_loss=0.002577

      epoch  77/100: train_loss=0.002584

      epoch  78/100: train_loss=0.002576

      epoch  79/100: train_loss=0.002583

      epoch  80/100: train_loss=0.002583, val_loss=0.011567, IC=-0.0398

      epoch  81/100: train_loss=0.002583

      epoch  82/100: train_loss=0.002591

      epoch  83/100: train_loss=0.002589

      epoch  84/100: train_loss=0.002583

      epoch  85/100: train_loss=0.002576, val_loss=0.011589, IC=-0.0387

      epoch  86/100: train_loss=0.002583

      epoch  87/100: train_loss=0.002591

      epoch  88/100: train_loss=0.002579

      epoch  89/100: train_loss=0.002575

      epoch  90/100: train_loss=0.002579, val_loss=0.011583, IC=-0.0413

      epoch  91/100: train_loss=0.002592

      epoch  92/100: train_loss=0.002588

      epoch  93/100: train_loss=0.002589

      epoch  94/100: train_loss=0.002588

      epoch  95/100: train_loss=0.002585, val_loss=0.011575, IC=-0.0401

      epoch  96/100: train_loss=0.002580

      epoch  97/100: train_loss=0.002586

      epoch  98/100: train_loss=0.002581

      epoch  99/100: train_loss=0.002580

      epoch 100/100: train_loss=0.002568, val_loss=0.011576, IC=-0.0403

      best_ep=5, IC=+0.1215 (96.1s, 20 checkpoints)

  Fold 2: creating sequences...

    train=37,637 seq across 30 symbols
    val=5,188 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.134110

      epoch   2/100: train_loss=0.057820

      epoch   3/100: train_loss=0.039616

      epoch   4/100: train_loss=0.028129

      epoch   5/100: train_loss=0.021756, val_loss=0.009303, IC=+0.1014

      epoch   6/100: train_loss=0.017910

      epoch   7/100: train_loss=0.014802

      epoch   8/100: train_loss=0.012275

      epoch   9/100: train_loss=0.010979

      epoch  10/100: train_loss=0.009305, val_loss=0.003836, IC=+0.1162

      epoch  11/100: train_loss=0.008372

      epoch  12/100: train_loss=0.007696

      epoch  13/100: train_loss=0.006859

      epoch  14/100: train_loss=0.006245

      epoch  15/100: train_loss=0.005730, val_loss=0.002991, IC=+0.0888

      epoch  16/100: train_loss=0.005483

      epoch  17/100: train_loss=0.005142

      epoch  18/100: train_loss=0.004998

      epoch  19/100: train_loss=0.004770

      epoch  20/100: train_loss=0.004640, val_loss=0.002878, IC=+0.0676

      epoch  21/100: train_loss=0.004426

      epoch  22/100: train_loss=0.004349

      epoch  23/100: train_loss=0.004282

      epoch  24/100: train_loss=0.004204

      epoch  25/100: train_loss=0.004106, val_loss=0.002928, IC=-0.0123

      epoch  26/100: train_loss=0.004105

      epoch  27/100: train_loss=0.004039

      epoch  28/100: train_loss=0.004021

      epoch  29/100: train_loss=0.004102

      epoch  30/100: train_loss=0.003951, val_loss=0.002935, IC=-0.0241

      epoch  31/100: train_loss=0.004031

      epoch  32/100: train_loss=0.003905

      epoch  33/100: train_loss=0.003898

      epoch  34/100: train_loss=0.003949

      epoch  35/100: train_loss=0.003897, val_loss=0.003022, IC=-0.0898

      epoch  36/100: train_loss=0.003912

      epoch  37/100: train_loss=0.003938

      epoch  38/100: train_loss=0.003919

      epoch  39/100: train_loss=0.003891

      epoch  40/100: train_loss=0.003891, val_loss=0.002933, IC=-0.0045

      epoch  41/100: train_loss=0.003939

      epoch  42/100: train_loss=0.003905

      epoch  43/100: train_loss=0.003862

      epoch  44/100: train_loss=0.003909

      epoch  45/100: train_loss=0.003865, val_loss=0.003008, IC=-0.0776

      epoch  46/100: train_loss=0.003875

      epoch  47/100: train_loss=0.003877

      epoch  48/100: train_loss=0.003860

      epoch  49/100: train_loss=0.003874

      epoch  50/100: train_loss=0.003858, val_loss=0.002954, IC=-0.0264

      epoch  51/100: train_loss=0.003845

      epoch  52/100: train_loss=0.003858

      epoch  53/100: train_loss=0.003848

      epoch  54/100: train_loss=0.003845

      epoch  55/100: train_loss=0.003866, val_loss=0.002989, IC=-0.0805

      epoch  56/100: train_loss=0.003876

      epoch  57/100: train_loss=0.003812

      epoch  58/100: train_loss=0.003834

      epoch  59/100: train_loss=0.003838

      epoch  60/100: train_loss=0.003835, val_loss=0.003005, IC=-0.0800

      epoch  61/100: train_loss=0.003840

      epoch  62/100: train_loss=0.003842

      epoch  63/100: train_loss=0.003810

      epoch  64/100: train_loss=0.003839

      epoch  65/100: train_loss=0.003820, val_loss=0.003025, IC=-0.0934

      epoch  66/100: train_loss=0.003832

      epoch  67/100: train_loss=0.003838

      epoch  68/100: train_loss=0.003801

      epoch  69/100: train_loss=0.003869

      epoch  70/100: train_loss=0.003818, val_loss=0.002989, IC=-0.0699

      epoch  71/100: train_loss=0.003820

      epoch  72/100: train_loss=0.003839

      epoch  73/100: train_loss=0.003832

      epoch  74/100: train_loss=0.003825

      epoch  75/100: train_loss=0.003841, val_loss=0.003018, IC=-0.0876

      epoch  76/100: train_loss=0.003834

      epoch  77/100: train_loss=0.003844

      epoch  78/100: train_loss=0.003837

      epoch  79/100: train_loss=0.003824

      epoch  80/100: train_loss=0.003925, val_loss=0.003032, IC=-0.0903

      epoch  81/100: train_loss=0.003845

      epoch  82/100: train_loss=0.003834

      epoch  83/100: train_loss=0.003836

      epoch  84/100: train_loss=0.003822

      epoch  85/100: train_loss=0.003837, val_loss=0.002988, IC=-0.0659

      epoch  86/100: train_loss=0.003857

      epoch  87/100: train_loss=0.003839

      epoch  88/100: train_loss=0.003826

      epoch  89/100: train_loss=0.003857

      epoch  90/100: train_loss=0.003850, val_loss=0.003000, IC=-0.0744

      epoch  91/100: train_loss=0.003839

      epoch  92/100: train_loss=0.003820

      epoch  93/100: train_loss=0.003824

      epoch  94/100: train_loss=0.003842

      epoch  95/100: train_loss=0.003896, val_loss=0.002997, IC=-0.0731

      epoch  96/100: train_loss=0.003810

      epoch  97/100: train_loss=0.003829

      epoch  98/100: train_loss=0.003808

      epoch  99/100: train_loss=0.003844

      epoch 100/100: train_loss=0.003852, val_loss=0.002997, IC=-0.0737

      best_ep=10, IC=+0.1162 (99.9s, 20 checkpoints)

  Fold 3: creating sequences...

    train=39,459 seq across 30 symbols
    val=5,740 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.498933

      epoch   2/100: train_loss=0.080393

      epoch   3/100: train_loss=0.038388

      epoch   4/100: train_loss=0.025958

      epoch   5/100: train_loss=0.019152, val_loss=0.013714, IC=+0.0062

      epoch   6/100: train_loss=0.015490

      epoch   7/100: train_loss=0.012751

      epoch   8/100: train_loss=0.010833

      epoch   9/100: train_loss=0.009603

      epoch  10/100: train_loss=0.008547, val_loss=0.008017, IC=-0.0079

      epoch  11/100: train_loss=0.007965

      epoch  12/100: train_loss=0.007108

      epoch  13/100: train_loss=0.006787

      epoch  14/100: train_loss=0.006156

      epoch  15/100: train_loss=0.005842, val_loss=0.007589, IC=-0.0408

      epoch  16/100: train_loss=0.005629

      epoch  17/100: train_loss=0.005358

      epoch  18/100: train_loss=0.005132

      epoch  19/100: train_loss=0.004943

      epoch  20/100: train_loss=0.004787, val_loss=0.007682, IC=-0.0684

      epoch  21/100: train_loss=0.004647

      epoch  22/100: train_loss=0.004587

      epoch  23/100: train_loss=0.004490

      epoch  24/100: train_loss=0.004354

      epoch  25/100: train_loss=0.004334, val_loss=0.007676, IC=-0.0730

      epoch  26/100: train_loss=0.004260

      epoch  27/100: train_loss=0.004221

      epoch  28/100: train_loss=0.004114

      epoch  29/100: train_loss=0.004032

      epoch  30/100: train_loss=0.004064, val_loss=0.007671, IC=-0.0621

      epoch  31/100: train_loss=0.003940

      epoch  32/100: train_loss=0.004014

      epoch  33/100: train_loss=0.003976

      epoch  34/100: train_loss=0.003921

      epoch  35/100: train_loss=0.003904, val_loss=0.007687, IC=-0.0545

      epoch  36/100: train_loss=0.003926

      epoch  37/100: train_loss=0.003883

      epoch  38/100: train_loss=0.003855

      epoch  39/100: train_loss=0.003874

      epoch  40/100: train_loss=0.003868, val_loss=0.007705, IC=-0.0621

      epoch  41/100: train_loss=0.003865

      epoch  42/100: train_loss=0.003828

      epoch  43/100: train_loss=0.003852

      epoch  44/100: train_loss=0.003809

      epoch  45/100: train_loss=0.003842, val_loss=0.007603, IC=-0.0399

      epoch  46/100: train_loss=0.003838

      epoch  47/100: train_loss=0.003890

      epoch  48/100: train_loss=0.003827

      epoch  49/100: train_loss=0.003820

      epoch  50/100: train_loss=0.003816, val_loss=0.007621, IC=-0.0275

      epoch  51/100: train_loss=0.003834

      epoch  52/100: train_loss=0.003823

      epoch  53/100: train_loss=0.003791

      epoch  54/100: train_loss=0.003909

      epoch  55/100: train_loss=0.003796, val_loss=0.007529, IC=-0.0362

      epoch  56/100: train_loss=0.003813

      epoch  57/100: train_loss=0.003798

      epoch  58/100: train_loss=0.003817

      epoch  59/100: train_loss=0.003874

      epoch  60/100: train_loss=0.003889, val_loss=0.007503, IC=-0.0258

      epoch  61/100: train_loss=0.003834

      epoch  62/100: train_loss=0.003809

      epoch  63/100: train_loss=0.003789

      epoch  64/100: train_loss=0.003807

      epoch  65/100: train_loss=0.003779, val_loss=0.007467, IC=-0.0256

      epoch  66/100: train_loss=0.003762

      epoch  67/100: train_loss=0.003836

      epoch  68/100: train_loss=0.003766

      epoch  69/100: train_loss=0.003773

      epoch  70/100: train_loss=0.003765, val_loss=0.007475, IC=-0.0181

      epoch  71/100: train_loss=0.003818

      epoch  72/100: train_loss=0.003763

      epoch  73/100: train_loss=0.003767

      epoch  74/100: train_loss=0.003772

      epoch  75/100: train_loss=0.003821, val_loss=0.007483, IC=-0.0167

      epoch  76/100: train_loss=0.003782

      epoch  77/100: train_loss=0.003825

      epoch  78/100: train_loss=0.003863

      epoch  79/100: train_loss=0.003775

      epoch  80/100: train_loss=0.003773, val_loss=0.007476, IC=-0.0184

      epoch  81/100: train_loss=0.003765

      epoch  82/100: train_loss=0.003807

      epoch  83/100: train_loss=0.003831

      epoch  84/100: train_loss=0.003756

      epoch  85/100: train_loss=0.003799, val_loss=0.007476, IC=-0.0146

      epoch  86/100: train_loss=0.003768

      epoch  87/100: train_loss=0.003748

      epoch  88/100: train_loss=0.003812

      epoch  89/100: train_loss=0.003835

      epoch  90/100: train_loss=0.003824, val_loss=0.007471, IC=-0.0137

      epoch  91/100: train_loss=0.003810

      epoch  92/100: train_loss=0.003816

      epoch  93/100: train_loss=0.003727

      epoch  94/100: train_loss=0.003817

      epoch  95/100: train_loss=0.003782, val_loss=0.007474, IC=-0.0148

      epoch  96/100: train_loss=0.003764

      epoch  97/100: train_loss=0.003843

      epoch  98/100: train_loss=0.003818

      epoch  99/100: train_loss=0.003776

      epoch 100/100: train_loss=0.003869, val_loss=0.007473, IC=-0.0148

      best_ep=5, IC=+0.0062 (116.4s, 20 checkpoints)

  Fold 4: creating sequences...

    train=42,656 seq across 30 symbols
    val=4,726 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.149549

      epoch   2/100: train_loss=0.062440

      epoch   3/100: train_loss=0.041133

      epoch   4/100: train_loss=0.030743

      epoch   5/100: train_loss=0.023528, val_loss=0.008327, IC=+0.0426

      epoch   6/100: train_loss=0.018750

      epoch   7/100: train_loss=0.015045

      epoch   8/100: train_loss=0.012583

      epoch   9/100: train_loss=0.010430

      epoch  10/100: train_loss=0.008979, val_loss=0.003219, IC=+0.0533

      epoch  11/100: train_loss=0.007850

      epoch  12/100: train_loss=0.007035

      epoch  13/100: train_loss=0.006249

      epoch  14/100: train_loss=0.005820

      epoch  15/100: train_loss=0.005444, val_loss=0.002773, IC=-0.0397

      epoch  16/100: train_loss=0.005155

      epoch  17/100: train_loss=0.004994

      epoch  18/100: train_loss=0.004836

      epoch  19/100: train_loss=0.004666

      epoch  20/100: train_loss=0.004625, val_loss=0.002964, IC=-0.1204

      epoch  21/100: train_loss=0.004553

      epoch  22/100: train_loss=0.004478

      epoch  23/100: train_loss=0.004423

      epoch  24/100: train_loss=0.004404

      epoch  25/100: train_loss=0.004375, val_loss=0.003105, IC=-0.1436

      epoch  26/100: train_loss=0.004360

      epoch  27/100: train_loss=0.004332

      epoch  28/100: train_loss=0.004343

      epoch  29/100: train_loss=0.004313

      epoch  30/100: train_loss=0.004305, val_loss=0.003275, IC=-0.1391

      epoch  31/100: train_loss=0.004306

      epoch  32/100: train_loss=0.004316

      epoch  33/100: train_loss=0.004294

      epoch  34/100: train_loss=0.004317

      epoch  35/100: train_loss=0.004300, val_loss=0.003252, IC=-0.1400

      epoch  36/100: train_loss=0.004283

      epoch  37/100: train_loss=0.004287

      epoch  38/100: train_loss=0.004282

      epoch  39/100: train_loss=0.004280

      epoch  40/100: train_loss=0.004274, val_loss=0.003353, IC=-0.1496

      epoch  41/100: train_loss=0.004297

      epoch  42/100: train_loss=0.004276

      epoch  43/100: train_loss=0.004278

      epoch  44/100: train_loss=0.004282

      epoch  45/100: train_loss=0.004273, val_loss=0.003254, IC=-0.1547

      epoch  46/100: train_loss=0.004276

      epoch  47/100: train_loss=0.004257

      epoch  48/100: train_loss=0.004288

      epoch  49/100: train_loss=0.004273

      epoch  50/100: train_loss=0.004282, val_loss=0.003270, IC=-0.1493

      epoch  51/100: train_loss=0.004264

      epoch  52/100: train_loss=0.004293

      epoch  53/100: train_loss=0.004276

      epoch  54/100: train_loss=0.004283

      epoch  55/100: train_loss=0.004268, val_loss=0.003302, IC=-0.1568

      epoch  56/100: train_loss=0.004256

      epoch  57/100: train_loss=0.004278

      epoch  58/100: train_loss=0.004278

      epoch  59/100: train_loss=0.004285

      epoch  60/100: train_loss=0.004278, val_loss=0.003248, IC=-0.1614

      epoch  61/100: train_loss=0.004280

      epoch  62/100: train_loss=0.004267

      epoch  63/100: train_loss=0.004253

      epoch  64/100: train_loss=0.004262

      epoch  65/100: train_loss=0.004272, val_loss=0.003256, IC=-0.1605

      epoch  66/100: train_loss=0.004281

      epoch  67/100: train_loss=0.004282

      epoch  68/100: train_loss=0.004278

      epoch  69/100: train_loss=0.004278

      epoch  70/100: train_loss=0.004282, val_loss=0.003205, IC=-0.1579

      epoch  71/100: train_loss=0.004271

      epoch  72/100: train_loss=0.004278

      epoch  73/100: train_loss=0.004264

      epoch  74/100: train_loss=0.004289

      epoch  75/100: train_loss=0.004291, val_loss=0.003224, IC=-0.1529

      epoch  76/100: train_loss=0.004268

      epoch  77/100: train_loss=0.004275

      epoch  78/100: train_loss=0.004272

      epoch  79/100: train_loss=0.004244

      epoch  80/100: train_loss=0.004265, val_loss=0.003214, IC=-0.1551

      epoch  81/100: train_loss=0.004262

      epoch  82/100: train_loss=0.004277

      epoch  83/100: train_loss=0.004248

      epoch  84/100: train_loss=0.004259

      epoch  85/100: train_loss=0.004251, val_loss=0.003216, IC=-0.1516

      epoch  86/100: train_loss=0.004249

      epoch  87/100: train_loss=0.004267

      epoch  88/100: train_loss=0.004268

      epoch  89/100: train_loss=0.004236

      epoch  90/100: train_loss=0.004257, val_loss=0.003262, IC=-0.1495

      epoch  91/100: train_loss=0.004257

      epoch  92/100: train_loss=0.004247

      epoch  93/100: train_loss=0.004277

      epoch  94/100: train_loss=0.004284

      epoch  95/100: train_loss=0.004271, val_loss=0.003243, IC=-0.1493

      epoch  96/100: train_loss=0.004278

      epoch  97/100: train_loss=0.004252

      epoch  98/100: train_loss=0.004259

      epoch  99/100: train_loss=0.004250

      epoch 100/100: train_loss=0.004263, val_loss=0.003245, IC=-0.1494

      best_ep=10, IC=+0.0533 (118.7s, 20 checkpoints)

  nlinear: best_epoch=5, IC=+0.0568 (542.3s)

  Best: nlinear @ epoch 5 (IC=+0.0568)
  Saved to ~/ml4t/public/case_studies/cme_futures/run_log/training/d92b5fb2c8a4/diagnostics

Fold-major CV: 5 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=34,983 seq across 30 symbols
    val=5,588 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.003042

      epoch   2/100: train_loss=0.002515

      epoch   3/100: train_loss=0.002174

      epoch   4/100: train_loss=0.001775

      epoch   5/100: train_loss=0.001539, val_loss=0.002527, IC=+0.0544

      epoch   6/100: train_loss=0.001259

      epoch   7/100: train_loss=0.001064

      epoch   8/100: train_loss=0.000965

      epoch   9/100: train_loss=0.000892

      epoch  10/100: train_loss=0.000801, val_loss=0.003042, IC=+0.0247

      epoch  11/100: train_loss=0.000748

      epoch  12/100: train_loss=0.000712

      epoch  13/100: train_loss=0.000677

      epoch  14/100: train_loss=0.000625

      epoch  15/100: train_loss=0.000607, val_loss=0.003166, IC=+0.0480

      epoch  16/100: train_loss=0.000586

      epoch  17/100: train_loss=0.000575

      epoch  18/100: train_loss=0.000541

      epoch  19/100: train_loss=0.000526

      epoch  20/100: train_loss=0.000496, val_loss=0.003250, IC=+0.0539

      epoch  21/100: train_loss=0.000486

      epoch  22/100: train_loss=0.000472

      epoch  23/100: train_loss=0.000460

      epoch  24/100: train_loss=0.000454

      epoch  25/100: train_loss=0.000446, val_loss=0.003226, IC=+0.0433

      epoch  26/100: train_loss=0.000443

      epoch  27/100: train_loss=0.000438

      epoch  28/100: train_loss=0.000419

      epoch  29/100: train_loss=0.000407

      epoch  30/100: train_loss=0.000397, val_loss=0.003502, IC=+0.0205

      epoch  31/100: train_loss=0.000385

      epoch  32/100: train_loss=0.000376

      epoch  33/100: train_loss=0.000368

      epoch  34/100: train_loss=0.000364

      epoch  35/100: train_loss=0.000357, val_loss=0.003441, IC=+0.0118

      epoch  36/100: train_loss=0.000359

      epoch  37/100: train_loss=0.000355

      epoch  38/100: train_loss=0.000349

      epoch  39/100: train_loss=0.000340

      epoch  40/100: train_loss=0.000344, val_loss=0.003406, IC=+0.0131

      epoch  41/100: train_loss=0.000340

      epoch  42/100: train_loss=0.000333

      epoch  43/100: train_loss=0.000333

      epoch  44/100: train_loss=0.000327

      epoch  45/100: train_loss=0.000320, val_loss=0.003484, IC=+0.0164

      epoch  46/100: train_loss=0.000322

      epoch  47/100: train_loss=0.000309

      epoch  48/100: train_loss=0.000310

      epoch  49/100: train_loss=0.000308

      epoch  50/100: train_loss=0.000310, val_loss=0.003455, IC=+0.0095

      epoch  51/100: train_loss=0.000316

      epoch  52/100: train_loss=0.000316

      epoch  53/100: train_loss=0.000297

      epoch  54/100: train_loss=0.000294

      epoch  55/100: train_loss=0.000296, val_loss=0.003453, IC=+0.0211

      epoch  56/100: train_loss=0.000292

      epoch  57/100: train_loss=0.000296

      epoch  58/100: train_loss=0.000296

      epoch  59/100: train_loss=0.000292

      epoch  60/100: train_loss=0.000287, val_loss=0.003434, IC=+0.0049

      epoch  61/100: train_loss=0.000285

      epoch  62/100: train_loss=0.000281

      epoch  63/100: train_loss=0.000275

      epoch  64/100: train_loss=0.000280

      epoch  65/100: train_loss=0.000274, val_loss=0.003457, IC=+0.0081

      epoch  66/100: train_loss=0.000279

      epoch  67/100: train_loss=0.000280

      epoch  68/100: train_loss=0.000275

      epoch  69/100: train_loss=0.000273

      epoch  70/100: train_loss=0.000267, val_loss=0.003476, IC=+0.0020

      epoch  71/100: train_loss=0.000266

      epoch  72/100: train_loss=0.000264

      epoch  73/100: train_loss=0.000266

      epoch  74/100: train_loss=0.000266

      epoch  75/100: train_loss=0.000272, val_loss=0.003473, IC=+0.0005

      epoch  76/100: train_loss=0.000269

      epoch  77/100: train_loss=0.000269

      epoch  78/100: train_loss=0.000262

      epoch  79/100: train_loss=0.000261

      epoch  80/100: train_loss=0.000266, val_loss=0.003432, IC=+0.0078

      epoch  81/100: train_loss=0.000258

      epoch  82/100: train_loss=0.000262

      epoch  83/100: train_loss=0.000257

      epoch  84/100: train_loss=0.000259

      epoch  85/100: train_loss=0.000267, val_loss=0.003462, IC=+0.0018

      epoch  86/100: train_loss=0.000257

      epoch  87/100: train_loss=0.000259

      epoch  88/100: train_loss=0.000261

      epoch  89/100: train_loss=0.000255

      epoch  90/100: train_loss=0.000259, val_loss=0.003465, IC=+0.0030

      epoch  91/100: train_loss=0.000255

      epoch  92/100: train_loss=0.000253

      epoch  93/100: train_loss=0.000256

      epoch  94/100: train_loss=0.000254

      epoch  95/100: train_loss=0.000258, val_loss=0.003460, IC=+0.0040

      epoch  96/100: train_loss=0.000256

      epoch  97/100: train_loss=0.000255

      epoch  98/100: train_loss=0.000257

      epoch  99/100: train_loss=0.000255

      epoch 100/100: train_loss=0.000256, val_loss=0.003460, IC=+0.0037

      best_ep=5, IC=+0.0544 (128.1s, 20 checkpoints)

  Fold 1: creating sequences...

    train=36,286 seq across 30 symbols
    val=5,732 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002976

      epoch   2/100: train_loss=0.002339

      epoch   3/100: train_loss=0.001966

      epoch   4/100: train_loss=0.001590

      epoch   5/100: train_loss=0.001293, val_loss=0.016315, IC=-0.1499

      epoch   6/100: train_loss=0.001095

      epoch   7/100: train_loss=0.000930

      epoch   8/100: train_loss=0.000828

      epoch   9/100: train_loss=0.000746

      epoch  10/100: train_loss=0.000675, val_loss=0.015671, IC=-0.1097

      epoch  11/100: train_loss=0.000630

      epoch  12/100: train_loss=0.000574

      epoch  13/100: train_loss=0.000535

      epoch  14/100: train_loss=0.000522

      epoch  15/100: train_loss=0.000488, val_loss=0.016123, IC=-0.1194

      epoch  16/100: train_loss=0.000461

      epoch  17/100: train_loss=0.000454

      epoch  18/100: train_loss=0.000426

      epoch  19/100: train_loss=0.000414

      epoch  20/100: train_loss=0.000397, val_loss=0.015697, IC=-0.0942

      epoch  21/100: train_loss=0.000390

      epoch  22/100: train_loss=0.000375

      epoch  23/100: train_loss=0.000372

      epoch  24/100: train_loss=0.000360

      epoch  25/100: train_loss=0.000351, val_loss=0.015756, IC=-0.0956

      epoch  26/100: train_loss=0.000357

      epoch  27/100: train_loss=0.000341

      epoch  28/100: train_loss=0.000328

      epoch  29/100: train_loss=0.000323

      epoch  30/100: train_loss=0.000324, val_loss=0.015432, IC=-0.0878

      epoch  31/100: train_loss=0.000319

      epoch  32/100: train_loss=0.000314

      epoch  33/100: train_loss=0.000312

      epoch  34/100: train_loss=0.000312

      epoch  35/100: train_loss=0.000307, val_loss=0.015280, IC=-0.0844

      epoch  36/100: train_loss=0.000295

      epoch  37/100: train_loss=0.000290

      epoch  38/100: train_loss=0.000292

      epoch  39/100: train_loss=0.000286

      epoch  40/100: train_loss=0.000279, val_loss=0.015329, IC=-0.0868

      epoch  41/100: train_loss=0.000278

      epoch  42/100: train_loss=0.000276

      epoch  43/100: train_loss=0.000272

      epoch  44/100: train_loss=0.000275

      epoch  45/100: train_loss=0.000272, val_loss=0.015050, IC=-0.0796

      epoch  46/100: train_loss=0.000269

      epoch  47/100: train_loss=0.000266

      epoch  48/100: train_loss=0.000262

      epoch  49/100: train_loss=0.000264

      epoch  50/100: train_loss=0.000261, val_loss=0.015096, IC=-0.0828

      epoch  51/100: train_loss=0.000258

      epoch  52/100: train_loss=0.000261

      epoch  53/100: train_loss=0.000252

      epoch  54/100: train_loss=0.000251

      epoch  55/100: train_loss=0.000251, val_loss=0.015104, IC=-0.0843

      epoch  56/100: train_loss=0.000246

      epoch  57/100: train_loss=0.000246

      epoch  58/100: train_loss=0.000242

      epoch  59/100: train_loss=0.000242

      epoch  60/100: train_loss=0.000242, val_loss=0.015071, IC=-0.0840

      epoch  61/100: train_loss=0.000243

      epoch  62/100: train_loss=0.000241

      epoch  63/100: train_loss=0.000240

      epoch  64/100: train_loss=0.000236

      epoch  65/100: train_loss=0.000239, val_loss=0.015184, IC=-0.0914

      epoch  66/100: train_loss=0.000236

      epoch  67/100: train_loss=0.000236

      epoch  68/100: train_loss=0.000233

      epoch  69/100: train_loss=0.000234

      epoch  70/100: train_loss=0.000231, val_loss=0.015129, IC=-0.0905

      epoch  71/100: train_loss=0.000231

      epoch  72/100: train_loss=0.000230

      epoch  73/100: train_loss=0.000229

      epoch  74/100: train_loss=0.000229

      epoch  75/100: train_loss=0.000227, val_loss=0.015127, IC=-0.0894

      epoch  76/100: train_loss=0.000226

      epoch  77/100: train_loss=0.000227

      epoch  78/100: train_loss=0.000225

      epoch  79/100: train_loss=0.000224

      epoch  80/100: train_loss=0.000224, val_loss=0.015159, IC=-0.0897

      epoch  81/100: train_loss=0.000225

      epoch  82/100: train_loss=0.000224

      epoch  83/100: train_loss=0.000223

      epoch  84/100: train_loss=0.000222

      epoch  85/100: train_loss=0.000221, val_loss=0.015075, IC=-0.0855

      epoch  86/100: train_loss=0.000219

      epoch  87/100: train_loss=0.000220

      epoch  88/100: train_loss=0.000220

      epoch  89/100: train_loss=0.000223

      epoch  90/100: train_loss=0.000220, val_loss=0.015130, IC=-0.0888

      epoch  91/100: train_loss=0.000220

      epoch  92/100: train_loss=0.000220

      epoch  93/100: train_loss=0.000222

      epoch  94/100: train_loss=0.000221

      epoch  95/100: train_loss=0.000220, val_loss=0.015130, IC=-0.0893

      epoch  96/100: train_loss=0.000219

      epoch  97/100: train_loss=0.000217

      epoch  98/100: train_loss=0.000219

      epoch  99/100: train_loss=0.000219

      epoch 100/100: train_loss=0.000222, val_loss=0.015133, IC=-0.0893

      best_ep=45, IC=-0.0796 (130.5s, 20 checkpoints)

  Fold 2: creating sequences...

    train=37,637 seq across 30 symbols
    val=5,188 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.007034

      epoch   2/100: train_loss=0.003873

      epoch   3/100: train_loss=0.003322

      epoch   4/100: train_loss=0.002822

      epoch   5/100: train_loss=0.002306, val_loss=0.003519, IC=+0.0487

      epoch   6/100: train_loss=0.001879

      epoch   7/100: train_loss=0.001603

      epoch   8/100: train_loss=0.001380

      epoch   9/100: train_loss=0.001246

      epoch  10/100: train_loss=0.001126, val_loss=0.004899, IC=+0.0657

      epoch  11/100: train_loss=0.001068

      epoch  12/100: train_loss=0.001009

      epoch  13/100: train_loss=0.000960

      epoch  14/100: train_loss=0.000895

      epoch  15/100: train_loss=0.000840, val_loss=0.004942, IC=+0.0499

      epoch  16/100: train_loss=0.000807

      epoch  17/100: train_loss=0.000792

      epoch  18/100: train_loss=0.000764

      epoch  19/100: train_loss=0.000705

      epoch  20/100: train_loss=0.000688, val_loss=0.004809, IC=+0.0149

      epoch  21/100: train_loss=0.000678

      epoch  22/100: train_loss=0.000649

      epoch  23/100: train_loss=0.000632

      epoch  24/100: train_loss=0.000616

      epoch  25/100: train_loss=0.000613, val_loss=0.004589, IC=+0.0105

      epoch  26/100: train_loss=0.000586

      epoch  27/100: train_loss=0.000567

      epoch  28/100: train_loss=0.000551

      epoch  29/100: train_loss=0.000540

      epoch  30/100: train_loss=0.000538, val_loss=0.004610, IC=+0.0224

      epoch  31/100: train_loss=0.000557

      epoch  32/100: train_loss=0.000560

      epoch  33/100: train_loss=0.000528

      epoch  34/100: train_loss=0.000514

      epoch  35/100: train_loss=0.000494, val_loss=0.004474, IC=+0.0323

      epoch  36/100: train_loss=0.000485

      epoch  37/100: train_loss=0.000478

      epoch  38/100: train_loss=0.000476

      epoch  39/100: train_loss=0.000460

      epoch  40/100: train_loss=0.000452, val_loss=0.004577, IC=+0.0141

      epoch  41/100: train_loss=0.000449

      epoch  42/100: train_loss=0.000445

      epoch  43/100: train_loss=0.000445

      epoch  44/100: train_loss=0.000427

      epoch  45/100: train_loss=0.000434, val_loss=0.004518, IC=+0.0229

      epoch  46/100: train_loss=0.000430

      epoch  47/100: train_loss=0.000419

      epoch  48/100: train_loss=0.000412

      epoch  49/100: train_loss=0.000422

      epoch  50/100: train_loss=0.000409, val_loss=0.004302, IC=+0.0307

      epoch  51/100: train_loss=0.000399

      epoch  52/100: train_loss=0.000400

      epoch  53/100: train_loss=0.000396

      epoch  54/100: train_loss=0.000392

      epoch  55/100: train_loss=0.000397, val_loss=0.004356, IC=+0.0292

      epoch  56/100: train_loss=0.000388

      epoch  57/100: train_loss=0.000384

      epoch  58/100: train_loss=0.000377

      epoch  59/100: train_loss=0.000381

      epoch  60/100: train_loss=0.000379, val_loss=0.004442, IC=+0.0262

      epoch  61/100: train_loss=0.000375

      epoch  62/100: train_loss=0.000372

      epoch  63/100: train_loss=0.000374

      epoch  64/100: train_loss=0.000365

      epoch  65/100: train_loss=0.000369, val_loss=0.004355, IC=+0.0339

      epoch  66/100: train_loss=0.000366

      epoch  67/100: train_loss=0.000358

      epoch  68/100: train_loss=0.000367

      epoch  69/100: train_loss=0.000355

      epoch  70/100: train_loss=0.000357, val_loss=0.004315, IC=+0.0375

      epoch  71/100: train_loss=0.000352

      epoch  72/100: train_loss=0.000359

      epoch  73/100: train_loss=0.000354

      epoch  74/100: train_loss=0.000351

      epoch  75/100: train_loss=0.000351, val_loss=0.004263, IC=+0.0362

      epoch  76/100: train_loss=0.000351

      epoch  77/100: train_loss=0.000346

      epoch  78/100: train_loss=0.000347

      epoch  79/100: train_loss=0.000350

      epoch  80/100: train_loss=0.000342, val_loss=0.004330, IC=+0.0314

      epoch  81/100: train_loss=0.000344

      epoch  82/100: train_loss=0.000341

      epoch  83/100: train_loss=0.000342

      epoch  84/100: train_loss=0.000336

      epoch  85/100: train_loss=0.000337, val_loss=0.004331, IC=+0.0368

      epoch  86/100: train_loss=0.000338

      epoch  87/100: train_loss=0.000338

      epoch  88/100: train_loss=0.000330

      epoch  89/100: train_loss=0.000335

      epoch  90/100: train_loss=0.000334, val_loss=0.004334, IC=+0.0344

      epoch  91/100: train_loss=0.000340

      epoch  92/100: train_loss=0.000335

      epoch  93/100: train_loss=0.000334

      epoch  94/100: train_loss=0.000334

      epoch  95/100: train_loss=0.000349, val_loss=0.004326, IC=+0.0370

      epoch  96/100: train_loss=0.000332

      epoch  97/100: train_loss=0.000336

      epoch  98/100: train_loss=0.000338

      epoch  99/100: train_loss=0.000335

      epoch 100/100: train_loss=0.000336, val_loss=0.004321, IC=+0.0376

      best_ep=10, IC=+0.0657 (141.6s, 20 checkpoints)

  Fold 3: creating sequences...

    train=39,459 seq across 30 symbols
    val=5,740 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.004558

      epoch   2/100: train_loss=0.003341

      epoch   3/100: train_loss=0.002611

      epoch   4/100: train_loss=0.002015

      epoch   5/100: train_loss=0.001606, val_loss=0.008897, IC=+0.1028

      epoch   6/100: train_loss=0.001352

      epoch   7/100: train_loss=0.001152

      epoch   8/100: train_loss=0.001050

      epoch   9/100: train_loss=0.000992

      epoch  10/100: train_loss=0.000918, val_loss=0.008537, IC=+0.0867

      epoch  11/100: train_loss=0.000868

      epoch  12/100: train_loss=0.000822

      epoch  13/100: train_loss=0.000768

      epoch  14/100: train_loss=0.000743

      epoch  15/100: train_loss=0.000694, val_loss=0.008540, IC=+0.0789

      epoch  16/100: train_loss=0.000678

      epoch  17/100: train_loss=0.000659

      epoch  18/100: train_loss=0.000650

      epoch  19/100: train_loss=0.000663

      epoch  20/100: train_loss=0.000606, val_loss=0.008640, IC=+0.0827

      epoch  21/100: train_loss=0.000568

      epoch  22/100: train_loss=0.000556

      epoch  23/100: train_loss=0.000541

      epoch  24/100: train_loss=0.000535

      epoch  25/100: train_loss=0.000523, val_loss=0.008859, IC=+0.0947

      epoch  26/100: train_loss=0.000502

      epoch  27/100: train_loss=0.000496

      epoch  28/100: train_loss=0.000519

      epoch  29/100: train_loss=0.000479

      epoch  30/100: train_loss=0.000475, val_loss=0.008772, IC=+0.0848

      epoch  31/100: train_loss=0.000477

      epoch  32/100: train_loss=0.000461

      epoch  33/100: train_loss=0.000451

      epoch  34/100: train_loss=0.000444

      epoch  35/100: train_loss=0.000429, val_loss=0.008713, IC=+0.0806

      epoch  36/100: train_loss=0.000423

      epoch  37/100: train_loss=0.000413

      epoch  38/100: train_loss=0.000419

      epoch  39/100: train_loss=0.000416

      epoch  40/100: train_loss=0.000412, val_loss=0.008773, IC=+0.0632

      epoch  41/100: train_loss=0.000413

      epoch  42/100: train_loss=0.000404

      epoch  43/100: train_loss=0.000392

      epoch  44/100: train_loss=0.000393

      epoch  45/100: train_loss=0.000382, val_loss=0.008885, IC=+0.0600

      epoch  46/100: train_loss=0.000376

      epoch  47/100: train_loss=0.000382

      epoch  48/100: train_loss=0.000375

      epoch  49/100: train_loss=0.000375

      epoch  50/100: train_loss=0.000368, val_loss=0.009002, IC=+0.0637

      epoch  51/100: train_loss=0.000373

      epoch  52/100: train_loss=0.000366

      epoch  53/100: train_loss=0.000357

      epoch  54/100: train_loss=0.000354

      epoch  55/100: train_loss=0.000359, val_loss=0.008955, IC=+0.0602

      epoch  56/100: train_loss=0.000366

      epoch  57/100: train_loss=0.000362

      epoch  58/100: train_loss=0.000351

      epoch  59/100: train_loss=0.000341

      epoch  60/100: train_loss=0.000339, val_loss=0.008981, IC=+0.0679

      epoch  61/100: train_loss=0.000345

      epoch  62/100: train_loss=0.000340

      epoch  63/100: train_loss=0.000335

      epoch  64/100: train_loss=0.000337

      epoch  65/100: train_loss=0.000330, val_loss=0.009045, IC=+0.0666

      epoch  66/100: train_loss=0.000328

      epoch  67/100: train_loss=0.000327

      epoch  68/100: train_loss=0.000324

      epoch  69/100: train_loss=0.000324

      epoch  70/100: train_loss=0.000326, val_loss=0.009016, IC=+0.0686

      epoch  71/100: train_loss=0.000318

      epoch  72/100: train_loss=0.000322

      epoch  73/100: train_loss=0.000324

      epoch  74/100: train_loss=0.000315

      epoch  75/100: train_loss=0.000314, val_loss=0.008999, IC=+0.0633

      epoch  76/100: train_loss=0.000314

      epoch  77/100: train_loss=0.000310

      epoch  78/100: train_loss=0.000316

      epoch  79/100: train_loss=0.000312

      epoch  80/100: train_loss=0.000312, val_loss=0.008927, IC=+0.0699

      epoch  81/100: train_loss=0.000312

      epoch  82/100: train_loss=0.000311

      epoch  83/100: train_loss=0.000310

      epoch  84/100: train_loss=0.000309

      epoch  85/100: train_loss=0.000312, val_loss=0.009016, IC=+0.0673

      epoch  86/100: train_loss=0.000304

      epoch  87/100: train_loss=0.000311

      epoch  88/100: train_loss=0.000303

      epoch  89/100: train_loss=0.000301

      epoch  90/100: train_loss=0.000310, val_loss=0.009010, IC=+0.0680

      epoch  91/100: train_loss=0.000304

      epoch  92/100: train_loss=0.000303

      epoch  93/100: train_loss=0.000303

      epoch  94/100: train_loss=0.000300

      epoch  95/100: train_loss=0.000304, val_loss=0.009002, IC=+0.0688

      epoch  96/100: train_loss=0.000298

      epoch  97/100: train_loss=0.000302

      epoch  98/100: train_loss=0.000301

      epoch  99/100: train_loss=0.000303

      epoch 100/100: train_loss=0.000300, val_loss=0.009000, IC=+0.0685

      best_ep=5, IC=+0.1028 (157.9s, 20 checkpoints)

  Fold 4: creating sequences...

    train=42,656 seq across 30 symbols
    val=4,726 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.004390

      epoch   2/100: train_loss=0.003334

      epoch   3/100: train_loss=0.002560

      epoch   4/100: train_loss=0.001937

      epoch   5/100: train_loss=0.001636, val_loss=0.005581, IC=-0.1384

      epoch   6/100: train_loss=0.001397

      epoch   7/100: train_loss=0.001234

      epoch   8/100: train_loss=0.001153

      epoch   9/100: train_loss=0.001023

      epoch  10/100: train_loss=0.000966, val_loss=0.005633, IC=-0.1921

      epoch  11/100: train_loss=0.000908

      epoch  12/100: train_loss=0.000848

      epoch  13/100: train_loss=0.000819

      epoch  14/100: train_loss=0.000795

      epoch  15/100: train_loss=0.000753, val_loss=0.005514, IC=-0.1727

      epoch  16/100: train_loss=0.000729

      epoch  17/100: train_loss=0.000710

      epoch  18/100: train_loss=0.000704

      epoch  19/100: train_loss=0.000661

      epoch  20/100: train_loss=0.000645, val_loss=0.005189, IC=-0.1102

      epoch  21/100: train_loss=0.000624

      epoch  22/100: train_loss=0.000625

      epoch  23/100: train_loss=0.000602

      epoch  24/100: train_loss=0.000574

      epoch  25/100: train_loss=0.000576, val_loss=0.004771, IC=-0.1148

      epoch  26/100: train_loss=0.000563

      epoch  27/100: train_loss=0.000564

      epoch  28/100: train_loss=0.000546

      epoch  29/100: train_loss=0.000527

      epoch  30/100: train_loss=0.000519, val_loss=0.005309, IC=-0.1117

      epoch  31/100: train_loss=0.000523

      epoch  32/100: train_loss=0.000509

      epoch  33/100: train_loss=0.000499

      epoch  34/100: train_loss=0.000494

      epoch  35/100: train_loss=0.000493, val_loss=0.005254, IC=-0.1248

      epoch  36/100: train_loss=0.000483

      epoch  37/100: train_loss=0.000480

      epoch  38/100: train_loss=0.000473

      epoch  39/100: train_loss=0.000471

      epoch  40/100: train_loss=0.000464, val_loss=0.005489, IC=-0.1229

      epoch  41/100: train_loss=0.000454

      epoch  42/100: train_loss=0.000450

      epoch  43/100: train_loss=0.000441

      epoch  44/100: train_loss=0.000434

      epoch  45/100: train_loss=0.000444, val_loss=0.005126, IC=-0.1346

      epoch  46/100: train_loss=0.000432

      epoch  47/100: train_loss=0.000421

      epoch  48/100: train_loss=0.000428

      epoch  49/100: train_loss=0.000426

      epoch  50/100: train_loss=0.000419, val_loss=0.005146, IC=-0.1132

      epoch  51/100: train_loss=0.000413

      epoch  52/100: train_loss=0.000415

      epoch  53/100: train_loss=0.000416

      epoch  54/100: train_loss=0.000414

      epoch  55/100: train_loss=0.000402, val_loss=0.005309, IC=-0.1370

      epoch  56/100: train_loss=0.000402

      epoch  57/100: train_loss=0.000394

      epoch  58/100: train_loss=0.000389

      epoch  59/100: train_loss=0.000394

      epoch  60/100: train_loss=0.000392, val_loss=0.005274, IC=-0.1277

      epoch  61/100: train_loss=0.000386

      epoch  62/100: train_loss=0.000388

      epoch  63/100: train_loss=0.000379

      epoch  64/100: train_loss=0.000377

      epoch  65/100: train_loss=0.000373, val_loss=0.005366, IC=-0.1325

      epoch  66/100: train_loss=0.000378

      epoch  67/100: train_loss=0.000370

      epoch  68/100: train_loss=0.000372

      epoch  69/100: train_loss=0.000366

      epoch  70/100: train_loss=0.000367, val_loss=0.005414, IC=-0.1314

      epoch  71/100: train_loss=0.000367

      epoch  72/100: train_loss=0.000366

      epoch  73/100: train_loss=0.000359

      epoch  74/100: train_loss=0.000363

      epoch  75/100: train_loss=0.000362, val_loss=0.005482, IC=-0.1442

      epoch  76/100: train_loss=0.000360

      epoch  77/100: train_loss=0.000362

      epoch  78/100: train_loss=0.000356

      epoch  79/100: train_loss=0.000356

      epoch  80/100: train_loss=0.000351, val_loss=0.005432, IC=-0.1390

      epoch  81/100: train_loss=0.000358

      epoch  82/100: train_loss=0.000354

      epoch  83/100: train_loss=0.000350

      epoch  84/100: train_loss=0.000352

      epoch  85/100: train_loss=0.000356, val_loss=0.005446, IC=-0.1384

      epoch  86/100: train_loss=0.000347

      epoch  87/100: train_loss=0.000344

      epoch  88/100: train_loss=0.000348

      epoch  89/100: train_loss=0.000344

      epoch  90/100: train_loss=0.000348, val_loss=0.005427, IC=-0.1368

      epoch  91/100: train_loss=0.000343

      epoch  92/100: train_loss=0.000342

      epoch  93/100: train_loss=0.000342

      epoch  94/100: train_loss=0.000343

      epoch  95/100: train_loss=0.000336, val_loss=0.005443, IC=-0.1382

      epoch  96/100: train_loss=0.000344

      epoch  97/100: train_loss=0.000343

      epoch  98/100: train_loss=0.000344

      epoch  99/100: train_loss=0.000347

      epoch 100/100: train_loss=0.000347, val_loss=0.005447, IC=-0.1388

      best_ep=20, IC=-0.1102 (158.3s, 20 checkpoints)

  lstm_h64: best_epoch=20, IC=-0.0089 (716.4s)

  Best: lstm_h64 @ epoch 20 (IC=-0.0089)
  Saved to ~/ml4t/public/case_studies/cme_futures/run_log/training/8ee34cb781c1/diagnostics

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("label", "config_name", "checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("sequence execution returned a partial prediction")
catalog

shape: (80, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8ee34cb78 ┆ 3f17045a7 │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 1c1       ┆ e0b       │
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8ee34cb78 ┆ 1d1ccc345 │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 1c1       ┆ 3a6       │
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8ee34cb78 ┆ 57cf60e14 │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 1c1       ┆ 4ea       │
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8ee34cb78 ┆ 9d906fa51 │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 1c1       ┆ 5d0       │
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 8ee34cb78 ┆ 64cee17c7 │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 1c1       ┆ 439       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a8a3dc311 ┆ e8e371a14 │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 6fd       ┆ 26b       │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a8a3dc311 ┆ 131c4cc9b │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 6fd       ┆ 0be       │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a8a3dc311 ┆ daa3f5c1a │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 6fd       ┆ 33f       │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a8a3dc311 ┆ 977553e36 │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 6fd       ┆ 039       │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ a8a3dc311 ┆ cd11fe3da │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 6fd       ┆ 5b5       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘