# CME Futures: Sequence Models

This notebook evaluates the declared NLinear and LSTM sequence configurations. Each input window
contains observations from one product and ends before its prediction timestamp. Purge gaps and
fold boundaries prevent a sequence from crossing into another validation interval, and hidden
state does not pass between products or folds.

Every declared epoch checkpoint is published with fitted weights and exact chronological
eligibility. MC dropout is not an undeclared side experiment. Configuration selection remains the
validation backtest decision in `13_backtest`.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit the declared CME futures sequence-model population."""

import polars as pl

from case_studies.cme_futures.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    product_universe_table,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_catalog,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None
PREVIEW_REDUCTIONS: dict = {}
# The population hash this run replaces, read from the registry and set by a person. A
# first population takes None; a re-run whose membership has changed is refused without
# the hash it supersedes, and the refusal names the value required.
SUPERSEDES_POPULATION: str | None = None

## Declared requests

The request rows identify architecture, label, and published configuration. Sequence length,
checkpoint schedule, seed, gap policy, and device enter the resolved computation identity.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE)
requests = model_request_catalog("deep_learning", labels=ALL_LABELS)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    preview_reductions=PREVIEW_REDUCTIONS,
)
universe = product_universe_table()
universe

shape: (30, 4)
┌─────────────┬─────────┬──────────────────────────┬─────────────────┐
│ sector      ┆ product ┆ expiry_rule              ┆ contract_months │
│ ---         ┆ ---     ┆ ---                      ┆ ---             │
│ str         ┆ str     ┆ str                      ┆ str             │
╞═════════════╪═════════╪══════════════════════════╪═════════════════╡
│ agriculture ┆ ZC      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ agriculture ┆ ZL      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZM      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZS      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,X   │
│ agriculture ┆ ZW      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ …           ┆ …       ┆ …                        ┆ …               │
│ metals      ┆ SI      ┆ 3rd_last_business_day    ┆ H,K,N,U,Z       │
│ treasuries  ┆ ZB      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZF      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZN      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZT      ┆ last_business_day        ┆ H,M,U,Z         │
└─────────────┴─────────┴──────────────────────────┴─────────────────┘

In [4]:
resolved_model_plan(resolved)

shape: (4, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ regressio ┆ … ┆ 2023-11-2 ┆ 20        ┆ canonical ┆ d6443432 │
│ ning      ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ aeea     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ fwd_ret_2 ┆ nlinear   ┆ regressio ┆ … ┆ 2023-11-2 ┆ 20        ┆ canonical ┆ 84b92874 │
│ ning      ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ b08c     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ fwd_ret_5 ┆ lstm_h64  ┆ regressio ┆ … ┆ 2023-12-2 ┆ 20        ┆ canonical ┆ 132bb3f3 │
│ ning      ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 7379     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ regressio ┆ … ┆ 2023-12-2 ┆ 20        ┆ canonical ┆ 84a4e0f3 │
│ ning      ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 6909     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

The shared sequence adapter owns window construction, checkpoint reload, prediction coverage, and
restart. A failed configuration cannot remove itself from the population snapshot.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_catalog(
        study,
        requests,
        population_name="cme-sequence-validation-v1",
        resolved_requests=resolved,
        supersedes=SUPERSEDES_POPULATION,
    )
else:
    if WORKSPACE is None or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Fold-major CV: 5 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=43,008 seq across 30 symbols
    val=5,078 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.269393

      epoch   2/100: train_loss=0.094486

      epoch   3/100: train_loss=0.048709

      epoch   4/100: train_loss=0.028004

      epoch   5/100: train_loss=0.018455, val_loss=0.005218, IC=-0.0529

      epoch   6/100: train_loss=0.013150

      epoch   7/100: train_loss=0.009978

      epoch   8/100: train_loss=0.007931

      epoch   9/100: train_loss=0.006395

      epoch  10/100: train_loss=0.005386, val_loss=0.001541, IC=-0.0365

      epoch  11/100: train_loss=0.004526

      epoch  12/100: train_loss=0.003809

      epoch  13/100: train_loss=0.003254

      epoch  14/100: train_loss=0.002870

      epoch  15/100: train_loss=0.002560, val_loss=0.000965, IC=-0.0700

      epoch  16/100: train_loss=0.002234

      epoch  17/100: train_loss=0.001995

      epoch  18/100: train_loss=0.001821

      epoch  19/100: train_loss=0.001720

      epoch  20/100: train_loss=0.001578, val_loss=0.000839, IC=-0.0715

      epoch  21/100: train_loss=0.001507

      epoch  22/100: train_loss=0.001432

      epoch  23/100: train_loss=0.001356

      epoch  24/100: train_loss=0.001310

      epoch  25/100: train_loss=0.001274, val_loss=0.000778, IC=-0.0667

      epoch  26/100: train_loss=0.001250

      epoch  27/100: train_loss=0.001216

      epoch  28/100: train_loss=0.001194

      epoch  29/100: train_loss=0.001182

      epoch  30/100: train_loss=0.001171, val_loss=0.000765, IC=-0.0818

      epoch  31/100: train_loss=0.001151

      epoch  32/100: train_loss=0.001145

      epoch  33/100: train_loss=0.001139

      epoch  34/100: train_loss=0.001128

      epoch  35/100: train_loss=0.001129, val_loss=0.000769, IC=-0.0485

      epoch  36/100: train_loss=0.001123

      epoch  37/100: train_loss=0.001123

      epoch  38/100: train_loss=0.001117

      epoch  39/100: train_loss=0.001114

      epoch  40/100: train_loss=0.001114, val_loss=0.000755, IC=-0.0767

      epoch  41/100: train_loss=0.001112

      epoch  42/100: train_loss=0.001110

      epoch  43/100: train_loss=0.001109

      epoch  44/100: train_loss=0.001106

      epoch  45/100: train_loss=0.001106, val_loss=0.000759, IC=-0.0779

      epoch  46/100: train_loss=0.001105

      epoch  47/100: train_loss=0.001102

      epoch  48/100: train_loss=0.001102

      epoch  49/100: train_loss=0.001104

      epoch  50/100: train_loss=0.001108, val_loss=0.000750, IC=-0.0689

      epoch  51/100: train_loss=0.001100

      epoch  52/100: train_loss=0.001103

      epoch  53/100: train_loss=0.001103

      epoch  54/100: train_loss=0.001103

      epoch  55/100: train_loss=0.001100, val_loss=0.000752, IC=-0.0725

      epoch  56/100: train_loss=0.001100

      epoch  57/100: train_loss=0.001100

      epoch  58/100: train_loss=0.001098

      epoch  59/100: train_loss=0.001099

      epoch  60/100: train_loss=0.001101, val_loss=0.000758, IC=-0.0635

      epoch  61/100: train_loss=0.001101

      epoch  62/100: train_loss=0.001098

      epoch  63/100: train_loss=0.001098

      epoch  64/100: train_loss=0.001098

      epoch  65/100: train_loss=0.001097, val_loss=0.000761, IC=-0.0670

      epoch  66/100: train_loss=0.001098

      epoch  67/100: train_loss=0.001101

      epoch  68/100: train_loss=0.001100

      epoch  69/100: train_loss=0.001101

      epoch  70/100: train_loss=0.001103, val_loss=0.000757, IC=-0.0815

      epoch  71/100: train_loss=0.001099

      epoch  72/100: train_loss=0.001097

      epoch  73/100: train_loss=0.001098

      epoch  74/100: train_loss=0.001100

      epoch  75/100: train_loss=0.001098, val_loss=0.000757, IC=-0.0736

      epoch  76/100: train_loss=0.001098

      epoch  77/100: train_loss=0.001099

      epoch  78/100: train_loss=0.001098

      epoch  79/100: train_loss=0.001099

      epoch  80/100: train_loss=0.001100, val_loss=0.000755, IC=-0.0750

      epoch  81/100: train_loss=0.001096

      epoch  82/100: train_loss=0.001098

      epoch  83/100: train_loss=0.001096

      epoch  84/100: train_loss=0.001098

      epoch  85/100: train_loss=0.001096, val_loss=0.000753, IC=-0.0776

      epoch  86/100: train_loss=0.001094

      epoch  87/100: train_loss=0.001097

      epoch  88/100: train_loss=0.001097

      epoch  89/100: train_loss=0.001098

      epoch  90/100: train_loss=0.001095, val_loss=0.000756, IC=-0.0700

      epoch  91/100: train_loss=0.001094

      epoch  92/100: train_loss=0.001094

      epoch  93/100: train_loss=0.001096

      epoch  94/100: train_loss=0.001096

      epoch  95/100: train_loss=0.001098, val_loss=0.000756, IC=-0.0723

      epoch  96/100: train_loss=0.001096

      epoch  97/100: train_loss=0.001100

      epoch  98/100: train_loss=0.001097

      epoch  99/100: train_loss=0.001098

      epoch 100/100: train_loss=0.001097, val_loss=0.000756, IC=-0.0725

      best_ep=10, IC=-0.0365 (91.3s, 20 checkpoints)

  Fold 1: creating sequences...

    train=39,811 seq across 30 symbols
    val=5,740 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.178920

      epoch   2/100: train_loss=0.068168

      epoch   3/100: train_loss=0.034027

      epoch   4/100: train_loss=0.021019

      epoch   5/100: train_loss=0.014823, val_loss=0.006233, IC=-0.0320

      epoch   6/100: train_loss=0.011532

      epoch   7/100: train_loss=0.009145

      epoch   8/100: train_loss=0.007447

      epoch   9/100: train_loss=0.006069

      epoch  10/100: train_loss=0.004929, val_loss=0.002922, IC=-0.0687

      epoch  11/100: train_loss=0.004164

      epoch  12/100: train_loss=0.003574

      epoch  13/100: train_loss=0.003016

      epoch  14/100: train_loss=0.002619

      epoch  15/100: train_loss=0.002266, val_loss=0.002153, IC=-0.0713

      epoch  16/100: train_loss=0.002041

      epoch  17/100: train_loss=0.001814

      epoch  18/100: train_loss=0.001659

      epoch  19/100: train_loss=0.001526

      epoch  20/100: train_loss=0.001395, val_loss=0.001972, IC=-0.0631

      epoch  21/100: train_loss=0.001312

      epoch  22/100: train_loss=0.001270

      epoch  23/100: train_loss=0.001203

      epoch  24/100: train_loss=0.001145

      epoch  25/100: train_loss=0.001118, val_loss=0.001884, IC=-0.0371

      epoch  26/100: train_loss=0.001074

      epoch  27/100: train_loss=0.001074

      epoch  28/100: train_loss=0.001042

      epoch  29/100: train_loss=0.001021

      epoch  30/100: train_loss=0.001011, val_loss=0.001867, IC=-0.0274

      epoch  31/100: train_loss=0.001002

      epoch  32/100: train_loss=0.000991

      epoch  33/100: train_loss=0.000979

      epoch  34/100: train_loss=0.000978

      epoch  35/100: train_loss=0.000980, val_loss=0.001848, IC=+0.0093

      epoch  36/100: train_loss=0.000974

      epoch  37/100: train_loss=0.000974

      epoch  38/100: train_loss=0.000964

      epoch  39/100: train_loss=0.000960

      epoch  40/100: train_loss=0.000971, val_loss=0.001851, IC=+0.0028

      epoch  41/100: train_loss=0.000966

      epoch  42/100: train_loss=0.000963

      epoch  43/100: train_loss=0.000967

      epoch  44/100: train_loss=0.000976

      epoch  45/100: train_loss=0.000967, val_loss=0.001848, IC=+0.0044

      epoch  46/100: train_loss=0.000960

      epoch  47/100: train_loss=0.000972

      epoch  48/100: train_loss=0.000978

      epoch  49/100: train_loss=0.000959

      epoch  50/100: train_loss=0.000969, val_loss=0.001846, IC=+0.0271

      epoch  51/100: train_loss=0.000967

      epoch  52/100: train_loss=0.000955

      epoch  53/100: train_loss=0.000960

      epoch  54/100: train_loss=0.000959

      epoch  55/100: train_loss=0.000962, val_loss=0.001849, IC=+0.0160

      epoch  56/100: train_loss=0.000965

      epoch  57/100: train_loss=0.000963

      epoch  58/100: train_loss=0.000965

      epoch  59/100: train_loss=0.000955

      epoch  60/100: train_loss=0.000959, val_loss=0.001853, IC=+0.0103

      epoch  61/100: train_loss=0.000964

      epoch  62/100: train_loss=0.000961

      epoch  63/100: train_loss=0.000958

      epoch  64/100: train_loss=0.000961

      epoch  65/100: train_loss=0.000959, val_loss=0.001852, IC=+0.0103

      epoch  66/100: train_loss=0.000956

      epoch  67/100: train_loss=0.000958

      epoch  68/100: train_loss=0.000963

      epoch  69/100: train_loss=0.000958

      epoch  70/100: train_loss=0.000962, val_loss=0.001846, IC=+0.0059

      epoch  71/100: train_loss=0.000958

      epoch  72/100: train_loss=0.000958

      epoch  73/100: train_loss=0.000956

      epoch  74/100: train_loss=0.000967

      epoch  75/100: train_loss=0.000959, val_loss=0.001850, IC=+0.0119

      epoch  76/100: train_loss=0.000958

      epoch  77/100: train_loss=0.000959

      epoch  78/100: train_loss=0.000959

      epoch  79/100: train_loss=0.000964

      epoch  80/100: train_loss=0.000956, val_loss=0.001849, IC=+0.0146

      epoch  81/100: train_loss=0.000968

      epoch  82/100: train_loss=0.000969

      epoch  83/100: train_loss=0.000958

      epoch  84/100: train_loss=0.000956

      epoch  85/100: train_loss=0.000954, val_loss=0.001850, IC=+0.0112

      epoch  86/100: train_loss=0.000958

      epoch  87/100: train_loss=0.000958

      epoch  88/100: train_loss=0.000955

      epoch  89/100: train_loss=0.000953

      epoch  90/100: train_loss=0.000960, val_loss=0.001848, IC=+0.0148

      epoch  91/100: train_loss=0.000951

      epoch  92/100: train_loss=0.000956

      epoch  93/100: train_loss=0.000956

      epoch  94/100: train_loss=0.000958

      epoch  95/100: train_loss=0.000958, val_loss=0.001848, IC=+0.0125

      epoch  96/100: train_loss=0.000956

      epoch  97/100: train_loss=0.000966

      epoch  98/100: train_loss=0.000959

      epoch  99/100: train_loss=0.000965

      epoch 100/100: train_loss=0.000963, val_loss=0.001848, IC=+0.0126

      best_ep=50, IC=+0.0271 (72.5s, 20 checkpoints)

  Fold 2: creating sequences...

    train=37,989 seq across 30 symbols
    val=5,188 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.131575

      epoch   2/100: train_loss=0.056055

      epoch   3/100: train_loss=0.037335

      epoch   4/100: train_loss=0.026097

      epoch   5/100: train_loss=0.019562, val_loss=0.008853, IC=+0.0625

      epoch   6/100: train_loss=0.015102

      epoch   7/100: train_loss=0.011895

      epoch   8/100: train_loss=0.009892

      epoch   9/100: train_loss=0.007851

      epoch  10/100: train_loss=0.006730, val_loss=0.002114, IC=+0.0761

      epoch  11/100: train_loss=0.005507

      epoch  12/100: train_loss=0.004546

      epoch  13/100: train_loss=0.003837

      epoch  14/100: train_loss=0.003388

      epoch  15/100: train_loss=0.002957, val_loss=0.000948, IC=+0.0696

      epoch  16/100: train_loss=0.002504

      epoch  17/100: train_loss=0.002193

      epoch  18/100: train_loss=0.001941

      epoch  19/100: train_loss=0.001718

      epoch  20/100: train_loss=0.001606, val_loss=0.000712, IC=+0.0760

      epoch  21/100: train_loss=0.001474

      epoch  22/100: train_loss=0.001410

      epoch  23/100: train_loss=0.001320

      epoch  24/100: train_loss=0.001262

      epoch  25/100: train_loss=0.001186, val_loss=0.000656, IC=+0.0634

      epoch  26/100: train_loss=0.001145

      epoch  27/100: train_loss=0.001122

      epoch  28/100: train_loss=0.001081

      epoch  29/100: train_loss=0.001069

      epoch  30/100: train_loss=0.001049, val_loss=0.000647, IC=+0.0071

      epoch  31/100: train_loss=0.001035

      epoch  32/100: train_loss=0.001021

      epoch  33/100: train_loss=0.001017

      epoch  34/100: train_loss=0.001009

      epoch  35/100: train_loss=0.000995, val_loss=0.000640, IC=+0.0684

      epoch  36/100: train_loss=0.001002

      epoch  37/100: train_loss=0.000994

      epoch  38/100: train_loss=0.000991

      epoch  39/100: train_loss=0.000989

      epoch  40/100: train_loss=0.000983, val_loss=0.000650, IC=+0.0074

      epoch  41/100: train_loss=0.000984

      epoch  42/100: train_loss=0.000980

      epoch  43/100: train_loss=0.000975

      epoch  44/100: train_loss=0.000976

      epoch  45/100: train_loss=0.000987, val_loss=0.000655, IC=-0.0575

      epoch  46/100: train_loss=0.000980

      epoch  47/100: train_loss=0.000977

      epoch  48/100: train_loss=0.000994

      epoch  49/100: train_loss=0.000971

      epoch  50/100: train_loss=0.000976, val_loss=0.000651, IC=-0.0066

      epoch  51/100: train_loss=0.000981

      epoch  52/100: train_loss=0.000975

      epoch  53/100: train_loss=0.000974

      epoch  54/100: train_loss=0.000975

      epoch  55/100: train_loss=0.000974, val_loss=0.000652, IC=+0.0416

      epoch  56/100: train_loss=0.000988

      epoch  57/100: train_loss=0.000973

      epoch  58/100: train_loss=0.000980

      epoch  59/100: train_loss=0.000977

      epoch  60/100: train_loss=0.000983, val_loss=0.000652, IC=-0.0227

      epoch  61/100: train_loss=0.000980

      epoch  62/100: train_loss=0.000976

      epoch  63/100: train_loss=0.000975

      epoch  64/100: train_loss=0.000975

      epoch  65/100: train_loss=0.000972, val_loss=0.000651, IC=-0.0163

      epoch  66/100: train_loss=0.000975

      epoch  67/100: train_loss=0.000979

      epoch  68/100: train_loss=0.000978

      epoch  69/100: train_loss=0.000977

      epoch  70/100: train_loss=0.000987, val_loss=0.000656, IC=-0.0665

      epoch  71/100: train_loss=0.000973

      epoch  72/100: train_loss=0.000977

      epoch  73/100: train_loss=0.000968

      epoch  74/100: train_loss=0.000974

      epoch  75/100: train_loss=0.000981, val_loss=0.000652, IC=-0.0164

      epoch  76/100: train_loss=0.000971

      epoch  77/100: train_loss=0.000974

      epoch  78/100: train_loss=0.000992

      epoch  79/100: train_loss=0.000975

      epoch  80/100: train_loss=0.000974, val_loss=0.000651, IC=-0.0127

      epoch  81/100: train_loss=0.000972

      epoch  82/100: train_loss=0.000969

      epoch  83/100: train_loss=0.000970

      epoch  84/100: train_loss=0.000972

      epoch  85/100: train_loss=0.000973, val_loss=0.000651, IC=-0.0307

      epoch  86/100: train_loss=0.000979

      epoch  87/100: train_loss=0.000967

      epoch  88/100: train_loss=0.000983

      epoch  89/100: train_loss=0.000971

      epoch  90/100: train_loss=0.000976, val_loss=0.000652, IC=-0.0259

      epoch  91/100: train_loss=0.000985

      epoch  92/100: train_loss=0.000977

      epoch  93/100: train_loss=0.000970

      epoch  94/100: train_loss=0.000971

      epoch  95/100: train_loss=0.000969, val_loss=0.000651, IC=-0.0280

      epoch  96/100: train_loss=0.000981

      epoch  97/100: train_loss=0.000973

      epoch  98/100: train_loss=0.000976

      epoch  99/100: train_loss=0.000976

      epoch 100/100: train_loss=0.000976, val_loss=0.000651, IC=-0.0267

      best_ep=10, IC=+0.0761 (69.4s, 20 checkpoints)

  Fold 3: creating sequences...

    train=36,638 seq across 30 symbols
    val=5,732 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.540043

      epoch   2/100: train_loss=0.098255

      epoch   3/100: train_loss=0.040316

      epoch   4/100: train_loss=0.026787

      epoch   5/100: train_loss=0.020055, val_loss=0.074333, IC=+0.0329

      epoch   6/100: train_loss=0.015410

      epoch   7/100: train_loss=0.012552

      epoch   8/100: train_loss=0.010236

      epoch   9/100: train_loss=0.008677

      epoch  10/100: train_loss=0.007251, val_loss=0.016493, IC=+0.0523

      epoch  11/100: train_loss=0.006108

      epoch  12/100: train_loss=0.005223

      epoch  13/100: train_loss=0.004535

      epoch  14/100: train_loss=0.003987

      epoch  15/100: train_loss=0.003545, val_loss=0.005581, IC=+0.0248

      epoch  16/100: train_loss=0.003097

      epoch  17/100: train_loss=0.002788

      epoch  18/100: train_loss=0.002480

      epoch  19/100: train_loss=0.002219

      epoch  20/100: train_loss=0.002060, val_loss=0.003508, IC=-0.0062

      epoch  21/100: train_loss=0.001857

      epoch  22/100: train_loss=0.001721

      epoch  23/100: train_loss=0.001589

      epoch  24/100: train_loss=0.001514

      epoch  25/100: train_loss=0.001370, val_loss=0.002998, IC=-0.0238

      epoch  26/100: train_loss=0.001294

      epoch  27/100: train_loss=0.001228

      epoch  28/100: train_loss=0.001164

      epoch  29/100: train_loss=0.001095

      epoch  30/100: train_loss=0.001042, val_loss=0.002853, IC=-0.0332

      epoch  31/100: train_loss=0.001018

      epoch  32/100: train_loss=0.000962

      epoch  33/100: train_loss=0.000939

      epoch  34/100: train_loss=0.000904

      epoch  35/100: train_loss=0.000880, val_loss=0.002784, IC=-0.0430

      epoch  36/100: train_loss=0.000861

      epoch  37/100: train_loss=0.000835

      epoch  38/100: train_loss=0.000813

      epoch  39/100: train_loss=0.000808

      epoch  40/100: train_loss=0.000788, val_loss=0.002753, IC=-0.0418

      epoch  41/100: train_loss=0.000779

      epoch  42/100: train_loss=0.000765

      epoch  43/100: train_loss=0.000753

      epoch  44/100: train_loss=0.000744

      epoch  45/100: train_loss=0.000734, val_loss=0.002711, IC=-0.0365

      epoch  46/100: train_loss=0.000736

      epoch  47/100: train_loss=0.000721

      epoch  48/100: train_loss=0.000720

      epoch  49/100: train_loss=0.000715

      epoch  50/100: train_loss=0.000714, val_loss=0.002685, IC=-0.0228

      epoch  51/100: train_loss=0.000709

      epoch  52/100: train_loss=0.000703

      epoch  53/100: train_loss=0.000696

      epoch  54/100: train_loss=0.000698

      epoch  55/100: train_loss=0.000697, val_loss=0.002682, IC=-0.0325

      epoch  56/100: train_loss=0.000693

      epoch  57/100: train_loss=0.000688

      epoch  58/100: train_loss=0.000689

      epoch  59/100: train_loss=0.000683

      epoch  60/100: train_loss=0.000686, val_loss=0.002672, IC=-0.0274

      epoch  61/100: train_loss=0.000682

      epoch  62/100: train_loss=0.000680

      epoch  63/100: train_loss=0.000681

      epoch  64/100: train_loss=0.000678

      epoch  65/100: train_loss=0.000677, val_loss=0.002690, IC=-0.0465

      epoch  66/100: train_loss=0.000678

      epoch  67/100: train_loss=0.000678

      epoch  68/100: train_loss=0.000674

      epoch  69/100: train_loss=0.000676

      epoch  70/100: train_loss=0.000674, val_loss=0.002678, IC=-0.0420

      epoch  71/100: train_loss=0.000673

      epoch  72/100: train_loss=0.000671

      epoch  73/100: train_loss=0.000672

      epoch  74/100: train_loss=0.000670

      epoch  75/100: train_loss=0.000670, val_loss=0.002678, IC=-0.0384

      epoch  76/100: train_loss=0.000669

      epoch  77/100: train_loss=0.000669

      epoch  78/100: train_loss=0.000670

      epoch  79/100: train_loss=0.000670

      epoch  80/100: train_loss=0.000669, val_loss=0.002677, IC=-0.0375

      epoch  81/100: train_loss=0.000667

      epoch  82/100: train_loss=0.000669

      epoch  83/100: train_loss=0.000668

      epoch  84/100: train_loss=0.000667

      epoch  85/100: train_loss=0.000666, val_loss=0.002678, IC=-0.0369

      epoch  86/100: train_loss=0.000668

      epoch  87/100: train_loss=0.000667

      epoch  88/100: train_loss=0.000665

      epoch  89/100: train_loss=0.000667

      epoch  90/100: train_loss=0.000671, val_loss=0.002679, IC=-0.0402

      epoch  91/100: train_loss=0.000667

      epoch  92/100: train_loss=0.000668

      epoch  93/100: train_loss=0.000666

      epoch  94/100: train_loss=0.000666

      epoch  95/100: train_loss=0.000669, val_loss=0.002680, IC=-0.0400

      epoch  96/100: train_loss=0.000667

      epoch  97/100: train_loss=0.000667

      epoch  98/100: train_loss=0.000668

      epoch  99/100: train_loss=0.000667

      epoch 100/100: train_loss=0.000667, val_loss=0.002680, IC=-0.0407

      best_ep=10, IC=+0.0523 (67.0s, 20 checkpoints)

  Fold 4: creating sequences...

    train=35,301 seq across 30 symbols
    val=5,588 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.150616

      epoch   2/100: train_loss=0.066420

      epoch   3/100: train_loss=0.039453

      epoch   4/100: train_loss=0.027526

      epoch   5/100: train_loss=0.020479, val_loss=0.356951, IC=-0.0176

      epoch   6/100: train_loss=0.015903

      epoch   7/100: train_loss=0.012474

      epoch   8/100: train_loss=0.009782

      epoch   9/100: train_loss=0.007719

      epoch  10/100: train_loss=0.006265, val_loss=0.045611, IC=-0.0130

      epoch  11/100: train_loss=0.005011

      epoch  12/100: train_loss=0.003950

      epoch  13/100: train_loss=0.003279

      epoch  14/100: train_loss=0.002683

      epoch  15/100: train_loss=0.002232, val_loss=0.005580, IC=-0.0065

      epoch  16/100: train_loss=0.001939

      epoch  17/100: train_loss=0.001676

      epoch  18/100: train_loss=0.001471

      epoch  19/100: train_loss=0.001309

      epoch  20/100: train_loss=0.001188, val_loss=0.000960, IC=-0.0037

      epoch  21/100: train_loss=0.001077

      epoch  22/100: train_loss=0.001001

      epoch  23/100: train_loss=0.000945

      epoch  24/100: train_loss=0.000908

      epoch  25/100: train_loss=0.000869, val_loss=0.000579, IC=+0.0124

      epoch  26/100: train_loss=0.000846

      epoch  27/100: train_loss=0.000815

      epoch  28/100: train_loss=0.000792

      epoch  29/100: train_loss=0.000799

      epoch  30/100: train_loss=0.000770, val_loss=0.000531, IC=+0.0022

      epoch  31/100: train_loss=0.000767

      epoch  32/100: train_loss=0.000770

      epoch  33/100: train_loss=0.000752

      epoch  34/100: train_loss=0.000755

      epoch  35/100: train_loss=0.000739, val_loss=0.000517, IC=+0.0115

      epoch  36/100: train_loss=0.000736

      epoch  37/100: train_loss=0.000738

      epoch  38/100: train_loss=0.000740

      epoch  39/100: train_loss=0.000736

      epoch  40/100: train_loss=0.000728, val_loss=0.000510, IC=-0.0045

      epoch  41/100: train_loss=0.000730

      epoch  42/100: train_loss=0.000724

      epoch  43/100: train_loss=0.000729

      epoch  44/100: train_loss=0.000725

      epoch  45/100: train_loss=0.000730, val_loss=0.000510, IC=+0.0271

      epoch  46/100: train_loss=0.000725

      epoch  47/100: train_loss=0.000735

      epoch  48/100: train_loss=0.000719

      epoch  49/100: train_loss=0.000727

      epoch  50/100: train_loss=0.000723, val_loss=0.000508, IC=+0.0183

      epoch  51/100: train_loss=0.000723

      epoch  52/100: train_loss=0.000725

      epoch  53/100: train_loss=0.000724

      epoch  54/100: train_loss=0.000728

      epoch  55/100: train_loss=0.000730, val_loss=0.000508, IC=+0.0242

      epoch  56/100: train_loss=0.000719

      epoch  57/100: train_loss=0.000729

      epoch  58/100: train_loss=0.000725

      epoch  59/100: train_loss=0.000720

      epoch  60/100: train_loss=0.000732, val_loss=0.000510, IC=+0.0242

      epoch  61/100: train_loss=0.000727

      epoch  62/100: train_loss=0.000726

      epoch  63/100: train_loss=0.000724

      epoch  64/100: train_loss=0.000729

      epoch  65/100: train_loss=0.000723, val_loss=0.000509, IC=+0.0159

      epoch  66/100: train_loss=0.000719

      epoch  67/100: train_loss=0.000727

      epoch  68/100: train_loss=0.000726

      epoch  69/100: train_loss=0.000719

      epoch  70/100: train_loss=0.000721, val_loss=0.000509, IC=+0.0167

      epoch  71/100: train_loss=0.000716

      epoch  72/100: train_loss=0.000719

      epoch  73/100: train_loss=0.000723

      epoch  74/100: train_loss=0.000731

      epoch  75/100: train_loss=0.000730, val_loss=0.000508, IC=+0.0230

      epoch  76/100: train_loss=0.000719

      epoch  77/100: train_loss=0.000724

      epoch  78/100: train_loss=0.000718

      epoch  79/100: train_loss=0.000728

      epoch  80/100: train_loss=0.000723, val_loss=0.000507, IC=+0.0197

      epoch  81/100: train_loss=0.000728

      epoch  82/100: train_loss=0.000726

      epoch  83/100: train_loss=0.000721

      epoch  84/100: train_loss=0.000723

      epoch  85/100: train_loss=0.000729, val_loss=0.000508, IC=+0.0183

      epoch  86/100: train_loss=0.000721

      epoch  87/100: train_loss=0.000727

      epoch  88/100: train_loss=0.000724

      epoch  89/100: train_loss=0.000724

      epoch  90/100: train_loss=0.000727, val_loss=0.000508, IC=+0.0188

      epoch  91/100: train_loss=0.000726

      epoch  92/100: train_loss=0.000739

      epoch  93/100: train_loss=0.000726

      epoch  94/100: train_loss=0.000719

      epoch  95/100: train_loss=0.000718, val_loss=0.000508, IC=+0.0167

      epoch  96/100: train_loss=0.000723

      epoch  97/100: train_loss=0.000723

      epoch  98/100: train_loss=0.000722

      epoch  99/100: train_loss=0.000725

      epoch 100/100: train_loss=0.000728, val_loss=0.000508, IC=+0.0157

      best_ep=45, IC=+0.0271 (64.6s, 20 checkpoints)

  nlinear: best_epoch=10, IC=+0.0022 (364.8s)

  Best: nlinear @ epoch 10 (IC=+0.0022)
  Saved to ~/ml4t/public-s6-cme_futures/case_studies/cme_futures/run_log/training/84a4e0f36909/diagnostics

Fold-major CV: 5 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=43,008 seq across 30 symbols
    val=5,078 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001412

      epoch   2/100: train_loss=0.001081

      epoch   3/100: train_loss=0.001016

      epoch   4/100: train_loss=0.000948

      epoch   5/100: train_loss=0.000875, val_loss=0.000923, IC=-0.0925

      epoch   6/100: train_loss=0.000818

      epoch   7/100: train_loss=0.000782

      epoch   8/100: train_loss=0.000727

      epoch   9/100: train_loss=0.000700

      epoch  10/100: train_loss=0.000675, val_loss=0.001103, IC=-0.0636

      epoch  11/100: train_loss=0.000660

      epoch  12/100: train_loss=0.000630

      epoch  13/100: train_loss=0.000608

      epoch  14/100: train_loss=0.000606

      epoch  15/100: train_loss=0.000574, val_loss=0.001252, IC=-0.0499

      epoch  16/100: train_loss=0.000555

      epoch  17/100: train_loss=0.000541

      epoch  18/100: train_loss=0.000533

      epoch  19/100: train_loss=0.000526

      epoch  20/100: train_loss=0.000511, val_loss=0.001288, IC=-0.0509

      epoch  21/100: train_loss=0.000494

      epoch  22/100: train_loss=0.000492

      epoch  23/100: train_loss=0.000483

      epoch  24/100: train_loss=0.000471

      epoch  25/100: train_loss=0.000461, val_loss=0.001371, IC=-0.0454

      epoch  26/100: train_loss=0.000451

      epoch  27/100: train_loss=0.000446

      epoch  28/100: train_loss=0.000432

      epoch  29/100: train_loss=0.000425

      epoch  30/100: train_loss=0.000418, val_loss=0.001353, IC=-0.0429

      epoch  31/100: train_loss=0.000414

      epoch  32/100: train_loss=0.000408

      epoch  33/100: train_loss=0.000405

      epoch  34/100: train_loss=0.000398

      epoch  35/100: train_loss=0.000392, val_loss=0.001390, IC=-0.0493

      epoch  36/100: train_loss=0.000385

      epoch  37/100: train_loss=0.000382

      epoch  38/100: train_loss=0.000374

      epoch  39/100: train_loss=0.000372

      epoch  40/100: train_loss=0.000371, val_loss=0.001368, IC=-0.0332

      epoch  41/100: train_loss=0.000363

      epoch  42/100: train_loss=0.000362

      epoch  43/100: train_loss=0.000357

      epoch  44/100: train_loss=0.000352

      epoch  45/100: train_loss=0.000350, val_loss=0.001364, IC=-0.0360

      epoch  46/100: train_loss=0.000341

      epoch  47/100: train_loss=0.000339

      epoch  48/100: train_loss=0.000341

      epoch  49/100: train_loss=0.000335

      epoch  50/100: train_loss=0.000330, val_loss=0.001341, IC=-0.0422

      epoch  51/100: train_loss=0.000329

      epoch  52/100: train_loss=0.000323

      epoch  53/100: train_loss=0.000322

      epoch  54/100: train_loss=0.000317

      epoch  55/100: train_loss=0.000318, val_loss=0.001332, IC=-0.0577

      epoch  56/100: train_loss=0.000316

      epoch  57/100: train_loss=0.000312

      epoch  58/100: train_loss=0.000312

      epoch  59/100: train_loss=0.000306

      epoch  60/100: train_loss=0.000307, val_loss=0.001334, IC=-0.0483

      epoch  61/100: train_loss=0.000303

      epoch  62/100: train_loss=0.000306

      epoch  63/100: train_loss=0.000301

      epoch  64/100: train_loss=0.000301

      epoch  65/100: train_loss=0.000297, val_loss=0.001325, IC=-0.0450

      epoch  66/100: train_loss=0.000293

      epoch  67/100: train_loss=0.000291

      epoch  68/100: train_loss=0.000292

      epoch  69/100: train_loss=0.000289

      epoch  70/100: train_loss=0.000289, val_loss=0.001352, IC=-0.0494

      epoch  71/100: train_loss=0.000288

      epoch  72/100: train_loss=0.000287

      epoch  73/100: train_loss=0.000281

      epoch  74/100: train_loss=0.000285

      epoch  75/100: train_loss=0.000282, val_loss=0.001354, IC=-0.0442

      epoch  76/100: train_loss=0.000283

      epoch  77/100: train_loss=0.000283

      epoch  78/100: train_loss=0.000279

      epoch  79/100: train_loss=0.000280

      epoch  80/100: train_loss=0.000280, val_loss=0.001352, IC=-0.0479

      epoch  81/100: train_loss=0.000274

      epoch  82/100: train_loss=0.000276

      epoch  83/100: train_loss=0.000279

      epoch  84/100: train_loss=0.000274

      epoch  85/100: train_loss=0.000277, val_loss=0.001351, IC=-0.0510

      epoch  86/100: train_loss=0.000277

      epoch  87/100: train_loss=0.000275

      epoch  88/100: train_loss=0.000275

      epoch  89/100: train_loss=0.000269

      epoch  90/100: train_loss=0.000274, val_loss=0.001350, IC=-0.0507

      epoch  91/100: train_loss=0.000273

      epoch  92/100: train_loss=0.000275

      epoch  93/100: train_loss=0.000272

      epoch  94/100: train_loss=0.000272

      epoch  95/100: train_loss=0.000272, val_loss=0.001349, IC=-0.0502

      epoch  96/100: train_loss=0.000273

      epoch  97/100: train_loss=0.000272

      epoch  98/100: train_loss=0.000271

      epoch  99/100: train_loss=0.000272

      epoch 100/100: train_loss=0.000273, val_loss=0.001348, IC=-0.0512

      best_ep=40, IC=-0.0332 (127.3s, 20 checkpoints)

  Fold 1: creating sequences...

    train=39,811 seq across 30 symbols
    val=5,740 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001384

      epoch   2/100: train_loss=0.000964

      epoch   3/100: train_loss=0.000909

      epoch   4/100: train_loss=0.000871

      epoch   5/100: train_loss=0.000829, val_loss=0.001958, IC=+0.0277

      epoch   6/100: train_loss=0.000755

      epoch   7/100: train_loss=0.000695

      epoch   8/100: train_loss=0.000661

      epoch   9/100: train_loss=0.000631

      epoch  10/100: train_loss=0.000599, val_loss=0.002179, IC=+0.0426

      epoch  11/100: train_loss=0.000576

      epoch  12/100: train_loss=0.000557

      epoch  13/100: train_loss=0.000542

      epoch  14/100: train_loss=0.000525

      epoch  15/100: train_loss=0.000514, val_loss=0.002318, IC=+0.0475

      epoch  16/100: train_loss=0.000498

      epoch  17/100: train_loss=0.000493

      epoch  18/100: train_loss=0.000465

      epoch  19/100: train_loss=0.000458

      epoch  20/100: train_loss=0.000443, val_loss=0.002531, IC=+0.0329

      epoch  21/100: train_loss=0.000430

      epoch  22/100: train_loss=0.000425

      epoch  23/100: train_loss=0.000409

      epoch  24/100: train_loss=0.000415

      epoch  25/100: train_loss=0.000406, val_loss=0.002544, IC=+0.0141

      epoch  26/100: train_loss=0.000394

      epoch  27/100: train_loss=0.000384

      epoch  28/100: train_loss=0.000378

      epoch  29/100: train_loss=0.000362

      epoch  30/100: train_loss=0.000372, val_loss=0.002545, IC=+0.0226

      epoch  31/100: train_loss=0.000362

      epoch  32/100: train_loss=0.000350

      epoch  33/100: train_loss=0.000350

      epoch  34/100: train_loss=0.000350

      epoch  35/100: train_loss=0.000334, val_loss=0.002598, IC=+0.0017

      epoch  36/100: train_loss=0.000334

      epoch  37/100: train_loss=0.000329

      epoch  38/100: train_loss=0.000324

      epoch  39/100: train_loss=0.000318

      epoch  40/100: train_loss=0.000319, val_loss=0.002558, IC=+0.0102

      epoch  41/100: train_loss=0.000314

      epoch  42/100: train_loss=0.000308

      epoch  43/100: train_loss=0.000303

      epoch  44/100: train_loss=0.000299

      epoch  45/100: train_loss=0.000294, val_loss=0.002584, IC=+0.0090

      epoch  46/100: train_loss=0.000288

      epoch  47/100: train_loss=0.000288

      epoch  48/100: train_loss=0.000289

      epoch  49/100: train_loss=0.000293

      epoch  50/100: train_loss=0.000283, val_loss=0.002583, IC=+0.0076

      epoch  51/100: train_loss=0.000277

      epoch  52/100: train_loss=0.000277

      epoch  53/100: train_loss=0.000277

      epoch  54/100: train_loss=0.000276

      epoch  55/100: train_loss=0.000273, val_loss=0.002586, IC=+0.0101

      epoch  56/100: train_loss=0.000267

      epoch  57/100: train_loss=0.000267

      epoch  58/100: train_loss=0.000265

      epoch  59/100: train_loss=0.000266

      epoch  60/100: train_loss=0.000264, val_loss=0.002540, IC=+0.0119

      epoch  61/100: train_loss=0.000258

      epoch  62/100: train_loss=0.000256

      epoch  63/100: train_loss=0.000256

      epoch  64/100: train_loss=0.000252

      epoch  65/100: train_loss=0.000251, val_loss=0.002549, IC=+0.0075

      epoch  66/100: train_loss=0.000251

      epoch  67/100: train_loss=0.000247

      epoch  68/100: train_loss=0.000245

      epoch  69/100: train_loss=0.000244

      epoch  70/100: train_loss=0.000244, val_loss=0.002569, IC=+0.0037

      epoch  71/100: train_loss=0.000247

      epoch  72/100: train_loss=0.000246

      epoch  73/100: train_loss=0.000243

      epoch  74/100: train_loss=0.000241

      epoch  75/100: train_loss=0.000242, val_loss=0.002594, IC=+0.0074

      epoch  76/100: train_loss=0.000238

      epoch  77/100: train_loss=0.000241

      epoch  78/100: train_loss=0.000237

      epoch  79/100: train_loss=0.000237

      epoch  80/100: train_loss=0.000239, val_loss=0.002576, IC=+0.0078

      epoch  81/100: train_loss=0.000236

      epoch  82/100: train_loss=0.000238

      epoch  83/100: train_loss=0.000235

      epoch  84/100: train_loss=0.000233

      epoch  85/100: train_loss=0.000234, val_loss=0.002562, IC=+0.0108

      epoch  86/100: train_loss=0.000236

      epoch  87/100: train_loss=0.000233

      epoch  88/100: train_loss=0.000234

      epoch  89/100: train_loss=0.000233

      epoch  90/100: train_loss=0.000231, val_loss=0.002573, IC=+0.0079

      epoch  91/100: train_loss=0.000232

      epoch  92/100: train_loss=0.000231

      epoch  93/100: train_loss=0.000233

      epoch  94/100: train_loss=0.000233

      epoch  95/100: train_loss=0.000233, val_loss=0.002571, IC=+0.0080

      epoch  96/100: train_loss=0.000233

      epoch  97/100: train_loss=0.000231

      epoch  98/100: train_loss=0.000232

      epoch  99/100: train_loss=0.000230

      epoch 100/100: train_loss=0.000231, val_loss=0.002569, IC=+0.0083

      best_ep=15, IC=+0.0475 (100.5s, 20 checkpoints)

  Fold 2: creating sequences...

    train=37,989 seq across 30 symbols
    val=5,188 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.003954

      epoch   2/100: train_loss=0.001160

      epoch   3/100: train_loss=0.001003

      epoch   4/100: train_loss=0.000959

      epoch   5/100: train_loss=0.000925, val_loss=0.000686, IC=+0.0333

      epoch   6/100: train_loss=0.000904

      epoch   7/100: train_loss=0.000879

      epoch   8/100: train_loss=0.000843

      epoch   9/100: train_loss=0.000810

      epoch  10/100: train_loss=0.000770, val_loss=0.000703, IC=+0.0273

      epoch  11/100: train_loss=0.000730

      epoch  12/100: train_loss=0.000708

      epoch  13/100: train_loss=0.000681

      epoch  14/100: train_loss=0.000647

      epoch  15/100: train_loss=0.000638, val_loss=0.000798, IC=+0.0022

      epoch  16/100: train_loss=0.000615

      epoch  17/100: train_loss=0.000592

      epoch  18/100: train_loss=0.000572

      epoch  19/100: train_loss=0.000563

      epoch  20/100: train_loss=0.000540, val_loss=0.000812, IC=+0.0074

      epoch  21/100: train_loss=0.000528

      epoch  22/100: train_loss=0.000518

      epoch  23/100: train_loss=0.000515

      epoch  24/100: train_loss=0.000499

      epoch  25/100: train_loss=0.000483, val_loss=0.000959, IC=-0.0089

      epoch  26/100: train_loss=0.000470

      epoch  27/100: train_loss=0.000463

      epoch  28/100: train_loss=0.000464

      epoch  29/100: train_loss=0.000458

      epoch  30/100: train_loss=0.000443, val_loss=0.000952, IC=+0.0110

      epoch  31/100: train_loss=0.000439

      epoch  32/100: train_loss=0.000435

      epoch  33/100: train_loss=0.000426

      epoch  34/100: train_loss=0.000418

      epoch  35/100: train_loss=0.000415, val_loss=0.001065, IC=-0.0116

      epoch  36/100: train_loss=0.000409

      epoch  37/100: train_loss=0.000402

      epoch  38/100: train_loss=0.000398

      epoch  39/100: train_loss=0.000390

      epoch  40/100: train_loss=0.000382, val_loss=0.001172, IC=-0.0104

      epoch  41/100: train_loss=0.000390

      epoch  42/100: train_loss=0.000383

      epoch  43/100: train_loss=0.000374

      epoch  44/100: train_loss=0.000376

      epoch  45/100: train_loss=0.000372, val_loss=0.001181, IC=-0.0169

      epoch  46/100: train_loss=0.000365

      epoch  47/100: train_loss=0.000360

      epoch  48/100: train_loss=0.000353

      epoch  49/100: train_loss=0.000352

      epoch  50/100: train_loss=0.000350, val_loss=0.001308, IC=-0.0338

      epoch  51/100: train_loss=0.000351

      epoch  52/100: train_loss=0.000345

      epoch  53/100: train_loss=0.000339

      epoch  54/100: train_loss=0.000340

      epoch  55/100: train_loss=0.000339, val_loss=0.001241, IC=-0.0269

      epoch  56/100: train_loss=0.000334

      epoch  57/100: train_loss=0.000331

      epoch  58/100: train_loss=0.000327

      epoch  59/100: train_loss=0.000330

      epoch  60/100: train_loss=0.000326, val_loss=0.001286, IC=-0.0318

      epoch  61/100: train_loss=0.000323

      epoch  62/100: train_loss=0.000318

      epoch  63/100: train_loss=0.000318

      epoch  64/100: train_loss=0.000317

      epoch  65/100: train_loss=0.000312, val_loss=0.001336, IC=-0.0366

      epoch  66/100: train_loss=0.000311

      epoch  67/100: train_loss=0.000310

      epoch  68/100: train_loss=0.000310

      epoch  69/100: train_loss=0.000307

      epoch  70/100: train_loss=0.000308, val_loss=0.001313, IC=-0.0269

      epoch  71/100: train_loss=0.000303

      epoch  72/100: train_loss=0.000307

      epoch  73/100: train_loss=0.000305

      epoch  74/100: train_loss=0.000305

      epoch  75/100: train_loss=0.000300, val_loss=0.001301, IC=-0.0255

      epoch  76/100: train_loss=0.000296

      epoch  77/100: train_loss=0.000297

      epoch  78/100: train_loss=0.000297

      epoch  79/100: train_loss=0.000298

      epoch  80/100: train_loss=0.000298, val_loss=0.001357, IC=-0.0348

      epoch  81/100: train_loss=0.000296

      epoch  82/100: train_loss=0.000293

      epoch  83/100: train_loss=0.000292

      epoch  84/100: train_loss=0.000293

      epoch  85/100: train_loss=0.000294, val_loss=0.001348, IC=-0.0324

      epoch  86/100: train_loss=0.000296

      epoch  87/100: train_loss=0.000294

      epoch  88/100: train_loss=0.000292

      epoch  89/100: train_loss=0.000291

      epoch  90/100: train_loss=0.000292, val_loss=0.001353, IC=-0.0334

      epoch  91/100: train_loss=0.000293

      epoch  92/100: train_loss=0.000289

      epoch  93/100: train_loss=0.000293

      epoch  94/100: train_loss=0.000290

      epoch  95/100: train_loss=0.000291, val_loss=0.001350, IC=-0.0341

      epoch  96/100: train_loss=0.000291

      epoch  97/100: train_loss=0.000290

      epoch  98/100: train_loss=0.000287

      epoch  99/100: train_loss=0.000289

      epoch 100/100: train_loss=0.000291, val_loss=0.001348, IC=-0.0344

      best_ep=5, IC=+0.0333 (96.0s, 20 checkpoints)

  Fold 3: creating sequences...

    train=36,638 seq across 30 symbols
    val=5,732 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.001571

      epoch   2/100: train_loss=0.000709

      epoch   3/100: train_loss=0.000656

      epoch   4/100: train_loss=0.000638

      epoch   5/100: train_loss=0.000622, val_loss=0.002787, IC=-0.0280

      epoch   6/100: train_loss=0.000605

      epoch   7/100: train_loss=0.000587

      epoch   8/100: train_loss=0.000567

      epoch   9/100: train_loss=0.000546

      epoch  10/100: train_loss=0.000529, val_loss=0.003125, IC=-0.0219

      epoch  11/100: train_loss=0.000508

      epoch  12/100: train_loss=0.000489

      epoch  13/100: train_loss=0.000469

      epoch  14/100: train_loss=0.000449

      epoch  15/100: train_loss=0.000438, val_loss=0.003360, IC=-0.0236

      epoch  16/100: train_loss=0.000421

      epoch  17/100: train_loss=0.000412

      epoch  18/100: train_loss=0.000403

      epoch  19/100: train_loss=0.000392

      epoch  20/100: train_loss=0.000380, val_loss=0.003496, IC=-0.0000

      epoch  21/100: train_loss=0.000370

      epoch  22/100: train_loss=0.000362

      epoch  23/100: train_loss=0.000357

      epoch  24/100: train_loss=0.000347

      epoch  25/100: train_loss=0.000343, val_loss=0.003393, IC=+0.0173

      epoch  26/100: train_loss=0.000334

      epoch  27/100: train_loss=0.000326

      epoch  28/100: train_loss=0.000323

      epoch  29/100: train_loss=0.000319

      epoch  30/100: train_loss=0.000317, val_loss=0.003424, IC=+0.0158

      epoch  31/100: train_loss=0.000307

      epoch  32/100: train_loss=0.000303

      epoch  33/100: train_loss=0.000299

      epoch  34/100: train_loss=0.000299

      epoch  35/100: train_loss=0.000288, val_loss=0.003458, IC=+0.0101

      epoch  36/100: train_loss=0.000284

      epoch  37/100: train_loss=0.000281

      epoch  38/100: train_loss=0.000276

      epoch  39/100: train_loss=0.000271

      epoch  40/100: train_loss=0.000270, val_loss=0.003445, IC=+0.0122

      epoch  41/100: train_loss=0.000271

      epoch  42/100: train_loss=0.000265

      epoch  43/100: train_loss=0.000260

      epoch  44/100: train_loss=0.000256

      epoch  45/100: train_loss=0.000256, val_loss=0.003360, IC=+0.0299

      epoch  46/100: train_loss=0.000253

      epoch  47/100: train_loss=0.000248

      epoch  48/100: train_loss=0.000250

      epoch  49/100: train_loss=0.000246

      epoch  50/100: train_loss=0.000243, val_loss=0.003432, IC=+0.0216

      epoch  51/100: train_loss=0.000242

      epoch  52/100: train_loss=0.000240

      epoch  53/100: train_loss=0.000237

      epoch  54/100: train_loss=0.000236

      epoch  55/100: train_loss=0.000234, val_loss=0.003420, IC=+0.0267

      epoch  56/100: train_loss=0.000229

      epoch  57/100: train_loss=0.000230

      epoch  58/100: train_loss=0.000229

      epoch  59/100: train_loss=0.000226

      epoch  60/100: train_loss=0.000225, val_loss=0.003347, IC=+0.0377

      epoch  61/100: train_loss=0.000225

      epoch  62/100: train_loss=0.000220

      epoch  63/100: train_loss=0.000220

      epoch  64/100: train_loss=0.000216

      epoch  65/100: train_loss=0.000217, val_loss=0.003364, IC=+0.0328

      epoch  66/100: train_loss=0.000217

      epoch  67/100: train_loss=0.000215

      epoch  68/100: train_loss=0.000213

      epoch  69/100: train_loss=0.000213

      epoch  70/100: train_loss=0.000210, val_loss=0.003363, IC=+0.0366

      epoch  71/100: train_loss=0.000215

      epoch  72/100: train_loss=0.000210

      epoch  73/100: train_loss=0.000210

      epoch  74/100: train_loss=0.000206

      epoch  75/100: train_loss=0.000208, val_loss=0.003366, IC=+0.0404

      epoch  76/100: train_loss=0.000208

      epoch  77/100: train_loss=0.000207

      epoch  78/100: train_loss=0.000203

      epoch  79/100: train_loss=0.000206

      epoch  80/100: train_loss=0.000204, val_loss=0.003374, IC=+0.0359

      epoch  81/100: train_loss=0.000204

      epoch  82/100: train_loss=0.000205

      epoch  83/100: train_loss=0.000203

      epoch  84/100: train_loss=0.000204

      epoch  85/100: train_loss=0.000203, val_loss=0.003367, IC=+0.0369

      epoch  86/100: train_loss=0.000204

      epoch  87/100: train_loss=0.000202

      epoch  88/100: train_loss=0.000200

      epoch  89/100: train_loss=0.000203

      epoch  90/100: train_loss=0.000200, val_loss=0.003361, IC=+0.0360

      epoch  91/100: train_loss=0.000201

      epoch  92/100: train_loss=0.000200

      epoch  93/100: train_loss=0.000203

      epoch  94/100: train_loss=0.000202

      epoch  95/100: train_loss=0.000201, val_loss=0.003367, IC=+0.0361

      epoch  96/100: train_loss=0.000201

      epoch  97/100: train_loss=0.000200

      epoch  98/100: train_loss=0.000201

      epoch  99/100: train_loss=0.000200

      epoch 100/100: train_loss=0.000200, val_loss=0.003365, IC=+0.0361

      best_ep=75, IC=+0.0404 (93.5s, 20 checkpoints)

  Fold 4: creating sequences...

    train=35,301 seq across 30 symbols
    val=5,588 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.000922

      epoch   2/100: train_loss=0.000722

      epoch   3/100: train_loss=0.000674

      epoch   4/100: train_loss=0.000643

      epoch   5/100: train_loss=0.000612, val_loss=0.003581, IC=-0.0358

      epoch   6/100: train_loss=0.000586

      epoch   7/100: train_loss=0.000557

      epoch   8/100: train_loss=0.000542

      epoch   9/100: train_loss=0.000514

      epoch  10/100: train_loss=0.000486, val_loss=0.005152, IC=-0.0467

      epoch  11/100: train_loss=0.000471

      epoch  12/100: train_loss=0.000456

      epoch  13/100: train_loss=0.000444

      epoch  14/100: train_loss=0.000433

      epoch  15/100: train_loss=0.000421, val_loss=0.004626, IC=-0.0514

      epoch  16/100: train_loss=0.000404

      epoch  17/100: train_loss=0.000402

      epoch  18/100: train_loss=0.000392

      epoch  19/100: train_loss=0.000382

      epoch  20/100: train_loss=0.000370, val_loss=0.004422, IC=-0.0501

      epoch  21/100: train_loss=0.000365

      epoch  22/100: train_loss=0.000358

      epoch  23/100: train_loss=0.000350

      epoch  24/100: train_loss=0.000342

      epoch  25/100: train_loss=0.000344, val_loss=0.004613, IC=-0.0538

      epoch  26/100: train_loss=0.000329

      epoch  27/100: train_loss=0.000328

      epoch  28/100: train_loss=0.000323

      epoch  29/100: train_loss=0.000314

      epoch  30/100: train_loss=0.000307, val_loss=0.004213, IC=-0.0446

      epoch  31/100: train_loss=0.000305

      epoch  32/100: train_loss=0.000303

      epoch  33/100: train_loss=0.000299

      epoch  34/100: train_loss=0.000294

      epoch  35/100: train_loss=0.000287, val_loss=0.004126, IC=-0.0470

      epoch  36/100: train_loss=0.000288

      epoch  37/100: train_loss=0.000282

      epoch  38/100: train_loss=0.000280

      epoch  39/100: train_loss=0.000276

      epoch  40/100: train_loss=0.000273, val_loss=0.003850, IC=-0.0423

      epoch  41/100: train_loss=0.000264

      epoch  42/100: train_loss=0.000262

      epoch  43/100: train_loss=0.000261

      epoch  44/100: train_loss=0.000259

      epoch  45/100: train_loss=0.000257, val_loss=0.003462, IC=-0.0438

      epoch  46/100: train_loss=0.000254

      epoch  47/100: train_loss=0.000252

      epoch  48/100: train_loss=0.000248

      epoch  49/100: train_loss=0.000243

      epoch  50/100: train_loss=0.000245, val_loss=0.003579, IC=-0.0409

      epoch  51/100: train_loss=0.000244

      epoch  52/100: train_loss=0.000239

      epoch  53/100: train_loss=0.000239

      epoch  54/100: train_loss=0.000238

      epoch  55/100: train_loss=0.000236, val_loss=0.003738, IC=-0.0431

      epoch  56/100: train_loss=0.000233

      epoch  57/100: train_loss=0.000231

      epoch  58/100: train_loss=0.000227

      epoch  59/100: train_loss=0.000227

      epoch  60/100: train_loss=0.000227, val_loss=0.003541, IC=-0.0406

      epoch  61/100: train_loss=0.000225

      epoch  62/100: train_loss=0.000222

      epoch  63/100: train_loss=0.000224

      epoch  64/100: train_loss=0.000218

      epoch  65/100: train_loss=0.000220, val_loss=0.003532, IC=-0.0399

      epoch  66/100: train_loss=0.000219

      epoch  67/100: train_loss=0.000215

      epoch  68/100: train_loss=0.000215

      epoch  69/100: train_loss=0.000218

      epoch  70/100: train_loss=0.000212, val_loss=0.003628, IC=-0.0421

      epoch  71/100: train_loss=0.000214

      epoch  72/100: train_loss=0.000212

      epoch  73/100: train_loss=0.000208

      epoch  74/100: train_loss=0.000210

      epoch  75/100: train_loss=0.000210, val_loss=0.003611, IC=-0.0406

      epoch  76/100: train_loss=0.000210

      epoch  77/100: train_loss=0.000210

      epoch  78/100: train_loss=0.000207

      epoch  79/100: train_loss=0.000208

      epoch  80/100: train_loss=0.000205, val_loss=0.003558, IC=-0.0402

      epoch  81/100: train_loss=0.000203

      epoch  82/100: train_loss=0.000207

      epoch  83/100: train_loss=0.000205

      epoch  84/100: train_loss=0.000205

      epoch  85/100: train_loss=0.000203, val_loss=0.003623, IC=-0.0396

      epoch  86/100: train_loss=0.000203

      epoch  87/100: train_loss=0.000205

      epoch  88/100: train_loss=0.000201

      epoch  89/100: train_loss=0.000204

      epoch  90/100: train_loss=0.000203, val_loss=0.003603, IC=-0.0400

      epoch  91/100: train_loss=0.000204

      epoch  92/100: train_loss=0.000202

      epoch  93/100: train_loss=0.000203

      epoch  94/100: train_loss=0.000205

      epoch  95/100: train_loss=0.000200, val_loss=0.003587, IC=-0.0406

      epoch  96/100: train_loss=0.000201

      epoch  97/100: train_loss=0.000202

      epoch  98/100: train_loss=0.000200

      epoch  99/100: train_loss=0.000199

      epoch 100/100: train_loss=0.000202, val_loss=0.003587, IC=-0.0404

      best_ep=5, IC=-0.0358 (105.1s, 20 checkpoints)

  lstm_h64: best_epoch=30, IC=-0.0075 (522.4s)

  Best: lstm_h64 @ epoch 30 (IC=-0.0075)
  Saved to ~/ml4t/public-s6-cme_futures/case_studies/cme_futures/run_log/training/132bb3f37379/diagnostics

Fold-major CV: 5 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=42,656 seq across 30 symbols
    val=4,726 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.275852

      epoch   2/100: train_loss=0.098893

      epoch   3/100: train_loss=0.050991

      epoch   4/100: train_loss=0.031493

      epoch   5/100: train_loss=0.021666, val_loss=0.007391, IC=-0.0563

      epoch   6/100: train_loss=0.016654

      epoch   7/100: train_loss=0.013450

      epoch   8/100: train_loss=0.011307

      epoch   9/100: train_loss=0.009758

      epoch  10/100: train_loss=0.008787, val_loss=0.003645, IC=-0.1087

      epoch  11/100: train_loss=0.007777

      epoch  12/100: train_loss=0.007007

      epoch  13/100: train_loss=0.006445

      epoch  14/100: train_loss=0.006080

      epoch  15/100: train_loss=0.005745, val_loss=0.003446, IC=-0.1676

      epoch  16/100: train_loss=0.005402

      epoch  17/100: train_loss=0.005209

      epoch  18/100: train_loss=0.005042

      epoch  19/100: train_loss=0.004894

      epoch  20/100: train_loss=0.004796, val_loss=0.003387, IC=-0.1536

      epoch  21/100: train_loss=0.004695

      epoch  22/100: train_loss=0.004661

      epoch  23/100: train_loss=0.004579

      epoch  24/100: train_loss=0.004512

      epoch  25/100: train_loss=0.004455, val_loss=0.003371, IC=-0.1414

      epoch  26/100: train_loss=0.004447

      epoch  27/100: train_loss=0.004439

      epoch  28/100: train_loss=0.004392

      epoch  29/100: train_loss=0.004392

      epoch  30/100: train_loss=0.004361, val_loss=0.003410, IC=-0.1395

      epoch  31/100: train_loss=0.004335

      epoch  32/100: train_loss=0.004310

      epoch  33/100: train_loss=0.004307

      epoch  34/100: train_loss=0.004315

      epoch  35/100: train_loss=0.004286, val_loss=0.003340, IC=-0.1580

      epoch  36/100: train_loss=0.004290

      epoch  37/100: train_loss=0.004306

      epoch  38/100: train_loss=0.004303

      epoch  39/100: train_loss=0.004281

      epoch  40/100: train_loss=0.004292, val_loss=0.003372, IC=-0.1323

      epoch  41/100: train_loss=0.004277

      epoch  42/100: train_loss=0.004286

      epoch  43/100: train_loss=0.004265

      epoch  44/100: train_loss=0.004274

      epoch  45/100: train_loss=0.004267, val_loss=0.003422, IC=-0.1432

      epoch  46/100: train_loss=0.004245

      epoch  47/100: train_loss=0.004257

      epoch  48/100: train_loss=0.004297

      epoch  49/100: train_loss=0.004280

      epoch  50/100: train_loss=0.004272, val_loss=0.003395, IC=-0.1403

      epoch  51/100: train_loss=0.004269

      epoch  52/100: train_loss=0.004245

      epoch  53/100: train_loss=0.004259

      epoch  54/100: train_loss=0.004278

      epoch  55/100: train_loss=0.004263, val_loss=0.003346, IC=-0.1435

      epoch  56/100: train_loss=0.004264

      epoch  57/100: train_loss=0.004258

      epoch  58/100: train_loss=0.004276

      epoch  59/100: train_loss=0.004276

      epoch  60/100: train_loss=0.004273, val_loss=0.003397, IC=-0.1465

      epoch  61/100: train_loss=0.004273

      epoch  62/100: train_loss=0.004271

      epoch  63/100: train_loss=0.004272

      epoch  64/100: train_loss=0.004291

      epoch  65/100: train_loss=0.004266, val_loss=0.003354, IC=-0.1459

      epoch  66/100: train_loss=0.004245

      epoch  67/100: train_loss=0.004273

      epoch  68/100: train_loss=0.004257

      epoch  69/100: train_loss=0.004268

      epoch  70/100: train_loss=0.004271, val_loss=0.003356, IC=-0.1417

      epoch  71/100: train_loss=0.004255

      epoch  72/100: train_loss=0.004264

      epoch  73/100: train_loss=0.004249

      epoch  74/100: train_loss=0.004258

      epoch  75/100: train_loss=0.004278, val_loss=0.003365, IC=-0.1464

      epoch  76/100: train_loss=0.004262

      epoch  77/100: train_loss=0.004260

      epoch  78/100: train_loss=0.004250

      epoch  79/100: train_loss=0.004251

      epoch  80/100: train_loss=0.004277, val_loss=0.003342, IC=-0.1396

      epoch  81/100: train_loss=0.004253

      epoch  82/100: train_loss=0.004253

      epoch  83/100: train_loss=0.004253

      epoch  84/100: train_loss=0.004290

      epoch  85/100: train_loss=0.004254, val_loss=0.003362, IC=-0.1413

      epoch  86/100: train_loss=0.004260

      epoch  87/100: train_loss=0.004258

      epoch  88/100: train_loss=0.004273

      epoch  89/100: train_loss=0.004251

      epoch  90/100: train_loss=0.004266, val_loss=0.003351, IC=-0.1432

      epoch  91/100: train_loss=0.004256

      epoch  92/100: train_loss=0.004246

      epoch  93/100: train_loss=0.004257

      epoch  94/100: train_loss=0.004258

      epoch  95/100: train_loss=0.004262, val_loss=0.003352, IC=-0.1424

      epoch  96/100: train_loss=0.004258

      epoch  97/100: train_loss=0.004243

      epoch  98/100: train_loss=0.004242

      epoch  99/100: train_loss=0.004269

      epoch 100/100: train_loss=0.004269, val_loss=0.003352, IC=-0.1434

      best_ep=5, IC=-0.0563 (61.5s, 20 checkpoints)

  Fold 1: creating sequences...

    train=39,459 seq across 30 symbols
    val=5,740 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.183368

      epoch   2/100: train_loss=0.072087

      epoch   3/100: train_loss=0.037294

      epoch   4/100: train_loss=0.023596

      epoch   5/100: train_loss=0.018029, val_loss=0.011695, IC=-0.0223

      epoch   6/100: train_loss=0.014822

      epoch   7/100: train_loss=0.012344

      epoch   8/100: train_loss=0.010543

      epoch   9/100: train_loss=0.009223

      epoch  10/100: train_loss=0.008124, val_loss=0.008849, IC=-0.1030

      epoch  11/100: train_loss=0.007260

      epoch  12/100: train_loss=0.006531

      epoch  13/100: train_loss=0.005988

      epoch  14/100: train_loss=0.005618

      epoch  15/100: train_loss=0.005168, val_loss=0.008030, IC=-0.0882

      epoch  16/100: train_loss=0.004951

      epoch  17/100: train_loss=0.004744

      epoch  18/100: train_loss=0.004645

      epoch  19/100: train_loss=0.004460

      epoch  20/100: train_loss=0.004309, val_loss=0.007598, IC=-0.0664

      epoch  21/100: train_loss=0.004204

      epoch  22/100: train_loss=0.004147

      epoch  23/100: train_loss=0.004109

      epoch  24/100: train_loss=0.004059

      epoch  25/100: train_loss=0.004015, val_loss=0.007472, IC=-0.0328

      epoch  26/100: train_loss=0.003966

      epoch  27/100: train_loss=0.003934

      epoch  28/100: train_loss=0.003871

      epoch  29/100: train_loss=0.003884

      epoch  30/100: train_loss=0.003918, val_loss=0.007406, IC=-0.0419

      epoch  31/100: train_loss=0.003892

      epoch  32/100: train_loss=0.003877

      epoch  33/100: train_loss=0.003821

      epoch  34/100: train_loss=0.003828

      epoch  35/100: train_loss=0.003859, val_loss=0.007394, IC=-0.0186

      epoch  36/100: train_loss=0.003837

      epoch  37/100: train_loss=0.003846

      epoch  38/100: train_loss=0.003864

      epoch  39/100: train_loss=0.003830

      epoch  40/100: train_loss=0.003784, val_loss=0.007354, IC=-0.0324

      epoch  41/100: train_loss=0.003853

      epoch  42/100: train_loss=0.003814

      epoch  43/100: train_loss=0.003815

      epoch  44/100: train_loss=0.003846

      epoch  45/100: train_loss=0.003822, val_loss=0.007440, IC=-0.0254

      epoch  46/100: train_loss=0.003821

      epoch  47/100: train_loss=0.003824

      epoch  48/100: train_loss=0.003836

      epoch  49/100: train_loss=0.003810

      epoch  50/100: train_loss=0.003808, val_loss=0.007344, IC=+0.0010

      epoch  51/100: train_loss=0.003823

      epoch  52/100: train_loss=0.003789

      epoch  53/100: train_loss=0.003809

      epoch  54/100: train_loss=0.003798

      epoch  55/100: train_loss=0.003818, val_loss=0.007313, IC=-0.0177

      epoch  56/100: train_loss=0.003778

      epoch  57/100: train_loss=0.003952

      epoch  58/100: train_loss=0.003774

      epoch  59/100: train_loss=0.003806

      epoch  60/100: train_loss=0.003836, val_loss=0.007301, IC=-0.0024

      epoch  61/100: train_loss=0.003809

      epoch  62/100: train_loss=0.003826

      epoch  63/100: train_loss=0.003804

      epoch  64/100: train_loss=0.003823

      epoch  65/100: train_loss=0.003829, val_loss=0.007300, IC=-0.0163

      epoch  66/100: train_loss=0.003802

      epoch  67/100: train_loss=0.003778

      epoch  68/100: train_loss=0.003800

      epoch  69/100: train_loss=0.003805

      epoch  70/100: train_loss=0.003774, val_loss=0.007314, IC=-0.0013

      epoch  71/100: train_loss=0.003781

      epoch  72/100: train_loss=0.003830

      epoch  73/100: train_loss=0.003801

      epoch  74/100: train_loss=0.003781

      epoch  75/100: train_loss=0.003843, val_loss=0.007301, IC=+0.0016

      epoch  76/100: train_loss=0.003799

      epoch  77/100: train_loss=0.003767

      epoch  78/100: train_loss=0.003810

      epoch  79/100: train_loss=0.003777

      epoch  80/100: train_loss=0.003784, val_loss=0.007280, IC=-0.0089

      epoch  81/100: train_loss=0.003819

      epoch  82/100: train_loss=0.003804

      epoch  83/100: train_loss=0.003829

      epoch  84/100: train_loss=0.003903

      epoch  85/100: train_loss=0.003847, val_loss=0.007291, IC=-0.0095

      epoch  86/100: train_loss=0.003796

      epoch  87/100: train_loss=0.003806

      epoch  88/100: train_loss=0.003828

      epoch  89/100: train_loss=0.003770

      epoch  90/100: train_loss=0.003784, val_loss=0.007277, IC=-0.0091

      epoch  91/100: train_loss=0.003791

      epoch  92/100: train_loss=0.003863

      epoch  93/100: train_loss=0.003813

      epoch  94/100: train_loss=0.003814

      epoch  95/100: train_loss=0.003841, val_loss=0.007270, IC=-0.0081

      epoch  96/100: train_loss=0.003841

      epoch  97/100: train_loss=0.003900

      epoch  98/100: train_loss=0.003855

      epoch  99/100: train_loss=0.003796

      epoch 100/100: train_loss=0.003765, val_loss=0.007273, IC=-0.0077

      best_ep=75, IC=+0.0016 (54.9s, 20 checkpoints)

  Fold 2: creating sequences...

    train=37,637 seq across 30 symbols
    val=5,188 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.138140

      epoch   2/100: train_loss=0.059276

      epoch   3/100: train_loss=0.040649

      epoch   4/100: train_loss=0.028980

      epoch   5/100: train_loss=0.022287, val_loss=0.011953, IC=+0.0700

      epoch   6/100: train_loss=0.018189

      epoch   7/100: train_loss=0.015046

      epoch   8/100: train_loss=0.012427

      epoch   9/100: train_loss=0.011011

      epoch  10/100: train_loss=0.009381, val_loss=0.004203, IC=+0.1009

      epoch  11/100: train_loss=0.008381

      epoch  12/100: train_loss=0.007670

      epoch  13/100: train_loss=0.006809

      epoch  14/100: train_loss=0.006235

      epoch  15/100: train_loss=0.005696, val_loss=0.003144, IC=+0.0669

      epoch  16/100: train_loss=0.005469

      epoch  17/100: train_loss=0.005129

      epoch  18/100: train_loss=0.004998

      epoch  19/100: train_loss=0.004768

      epoch  20/100: train_loss=0.004625, val_loss=0.002915, IC=+0.0771

      epoch  21/100: train_loss=0.004434

      epoch  22/100: train_loss=0.004356

      epoch  23/100: train_loss=0.004288

      epoch  24/100: train_loss=0.004202

      epoch  25/100: train_loss=0.004104, val_loss=0.002896, IC=+0.0311

      epoch  26/100: train_loss=0.004114

      epoch  27/100: train_loss=0.004056

      epoch  28/100: train_loss=0.004039

      epoch  29/100: train_loss=0.004114

      epoch  30/100: train_loss=0.003965, val_loss=0.002894, IC=+0.0369

      epoch  31/100: train_loss=0.004052

      epoch  32/100: train_loss=0.003931

      epoch  33/100: train_loss=0.003921

      epoch  34/100: train_loss=0.003971

      epoch  35/100: train_loss=0.003913, val_loss=0.002949, IC=-0.0304

      epoch  36/100: train_loss=0.003935

      epoch  37/100: train_loss=0.003963

      epoch  38/100: train_loss=0.003940

      epoch  39/100: train_loss=0.003919

      epoch  40/100: train_loss=0.003916, val_loss=0.002882, IC=+0.0511

      epoch  41/100: train_loss=0.003963

      epoch  42/100: train_loss=0.003932

      epoch  43/100: train_loss=0.003877

      epoch  44/100: train_loss=0.003931

      epoch  45/100: train_loss=0.003887, val_loss=0.002938, IC=-0.0229

      epoch  46/100: train_loss=0.003894

      epoch  47/100: train_loss=0.003896

      epoch  48/100: train_loss=0.003887

      epoch  49/100: train_loss=0.003896

      epoch  50/100: train_loss=0.003881, val_loss=0.002904, IC=+0.0384

      epoch  51/100: train_loss=0.003871

      epoch  52/100: train_loss=0.003877

      epoch  53/100: train_loss=0.003871

      epoch  54/100: train_loss=0.003866

      epoch  55/100: train_loss=0.003892, val_loss=0.002931, IC=-0.0256

      epoch  56/100: train_loss=0.003903

      epoch  57/100: train_loss=0.003835

      epoch  58/100: train_loss=0.003853

      epoch  59/100: train_loss=0.003864

      epoch  60/100: train_loss=0.003858, val_loss=0.002945, IC=-0.0318

      epoch  61/100: train_loss=0.003862

      epoch  62/100: train_loss=0.003867

      epoch  63/100: train_loss=0.003833

      epoch  64/100: train_loss=0.003866

      epoch  65/100: train_loss=0.003841, val_loss=0.002975, IC=-0.0524

      epoch  66/100: train_loss=0.003849

      epoch  67/100: train_loss=0.003860

      epoch  68/100: train_loss=0.003827

      epoch  69/100: train_loss=0.003892

      epoch  70/100: train_loss=0.003843, val_loss=0.002943, IC=-0.0229

      epoch  71/100: train_loss=0.003845

      epoch  72/100: train_loss=0.003863

      epoch  73/100: train_loss=0.003850

      epoch  74/100: train_loss=0.003850

      epoch  75/100: train_loss=0.003861, val_loss=0.002973, IC=-0.0489

      epoch  76/100: train_loss=0.003854

      epoch  77/100: train_loss=0.003869

      epoch  78/100: train_loss=0.003858

      epoch  79/100: train_loss=0.003848

      epoch  80/100: train_loss=0.003947, val_loss=0.002982, IC=-0.0442

      epoch  81/100: train_loss=0.003868

      epoch  82/100: train_loss=0.003858

      epoch  83/100: train_loss=0.003856

      epoch  84/100: train_loss=0.003848

      epoch  85/100: train_loss=0.003858, val_loss=0.002950, IC=-0.0172

      epoch  86/100: train_loss=0.003876

      epoch  87/100: train_loss=0.003859

      epoch  88/100: train_loss=0.003847

      epoch  89/100: train_loss=0.003877

      epoch  90/100: train_loss=0.003873, val_loss=0.002959, IC=-0.0313

      epoch  91/100: train_loss=0.003867

      epoch  92/100: train_loss=0.003843

      epoch  93/100: train_loss=0.003848

      epoch  94/100: train_loss=0.003861

      epoch  95/100: train_loss=0.003920, val_loss=0.002955, IC=-0.0294

      epoch  96/100: train_loss=0.003827

      epoch  97/100: train_loss=0.003852

      epoch  98/100: train_loss=0.003828

      epoch  99/100: train_loss=0.003867

      epoch 100/100: train_loss=0.003876, val_loss=0.002956, IC=-0.0293

      best_ep=10, IC=+0.1009 (52.9s, 20 checkpoints)

  Fold 3: creating sequences...

    train=36,286 seq across 30 symbols
    val=5,732 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.541634

      epoch   2/100: train_loss=0.097042

      epoch   3/100: train_loss=0.041895

      epoch   4/100: train_loss=0.028375

      epoch   5/100: train_loss=0.021534, val_loss=0.074492, IC=+0.0591

      epoch   6/100: train_loss=0.017183

      epoch   7/100: train_loss=0.014254

      epoch   8/100: train_loss=0.012166

      epoch   9/100: train_loss=0.010560

      epoch  10/100: train_loss=0.009124, val_loss=0.022285, IC=+0.0660

      epoch  11/100: train_loss=0.008094

      epoch  12/100: train_loss=0.007165

      epoch  13/100: train_loss=0.006519

      epoch  14/100: train_loss=0.005907

      epoch  15/100: train_loss=0.005404, val_loss=0.013367, IC=+0.0587

      epoch  16/100: train_loss=0.004997

      epoch  17/100: train_loss=0.004693

      epoch  18/100: train_loss=0.004398

      epoch  19/100: train_loss=0.004149

      epoch  20/100: train_loss=0.003971, val_loss=0.012187, IC=+0.0205

      epoch  21/100: train_loss=0.003761

      epoch  22/100: train_loss=0.003642

      epoch  23/100: train_loss=0.003491

      epoch  24/100: train_loss=0.003441

      epoch  25/100: train_loss=0.003309, val_loss=0.012119, IC=-0.0135

      epoch  26/100: train_loss=0.003224

      epoch  27/100: train_loss=0.003122

      epoch  28/100: train_loss=0.003089

      epoch  29/100: train_loss=0.003032

      epoch  30/100: train_loss=0.002996, val_loss=0.012023, IC=-0.0168

      epoch  31/100: train_loss=0.002931

      epoch  32/100: train_loss=0.002897

      epoch  33/100: train_loss=0.002860

      epoch  34/100: train_loss=0.002842

      epoch  35/100: train_loss=0.002803, val_loss=0.012056, IC=-0.0425

      epoch  36/100: train_loss=0.002796

      epoch  37/100: train_loss=0.002763

      epoch  38/100: train_loss=0.002747

      epoch  39/100: train_loss=0.002728

      epoch  40/100: train_loss=0.002724, val_loss=0.011893, IC=-0.0222

      epoch  41/100: train_loss=0.002702

      epoch  42/100: train_loss=0.002699

      epoch  43/100: train_loss=0.002704

      epoch  44/100: train_loss=0.002675

      epoch  45/100: train_loss=0.002665, val_loss=0.011851, IC=-0.0255

      epoch  46/100: train_loss=0.002658

      epoch  47/100: train_loss=0.002670

      epoch  48/100: train_loss=0.002658

      epoch  49/100: train_loss=0.002648

      epoch  50/100: train_loss=0.002634, val_loss=0.011810, IC=-0.0196

      epoch  51/100: train_loss=0.002646

      epoch  52/100: train_loss=0.002643

      epoch  53/100: train_loss=0.002632

      epoch  54/100: train_loss=0.002627

      epoch  55/100: train_loss=0.002620, val_loss=0.011824, IC=-0.0295

      epoch  56/100: train_loss=0.002619

      epoch  57/100: train_loss=0.002626

      epoch  58/100: train_loss=0.002625

      epoch  59/100: train_loss=0.002613

      epoch  60/100: train_loss=0.002616, val_loss=0.011793, IC=-0.0249

      epoch  61/100: train_loss=0.002617

      epoch  62/100: train_loss=0.002618

      epoch  63/100: train_loss=0.002613

      epoch  64/100: train_loss=0.002610

      epoch  65/100: train_loss=0.002609, val_loss=0.011737, IC=-0.0185

      epoch  66/100: train_loss=0.002610

      epoch  67/100: train_loss=0.002609

      epoch  68/100: train_loss=0.002614

      epoch  69/100: train_loss=0.002611

      epoch  70/100: train_loss=0.002613, val_loss=0.011778, IC=-0.0282

      epoch  71/100: train_loss=0.002607

      epoch  72/100: train_loss=0.002609

      epoch  73/100: train_loss=0.002612

      epoch  74/100: train_loss=0.002611

      epoch  75/100: train_loss=0.002592, val_loss=0.011783, IC=-0.0281

      epoch  76/100: train_loss=0.002601

      epoch  77/100: train_loss=0.002609

      epoch  78/100: train_loss=0.002606

      epoch  79/100: train_loss=0.002606

      epoch  80/100: train_loss=0.002600, val_loss=0.011760, IC=-0.0232

      epoch  81/100: train_loss=0.002601

      epoch  82/100: train_loss=0.002592

      epoch  83/100: train_loss=0.002596

      epoch  84/100: train_loss=0.002599

      epoch  85/100: train_loss=0.002601, val_loss=0.011757, IC=-0.0238

      epoch  86/100: train_loss=0.002603

      epoch  87/100: train_loss=0.002596

      epoch  88/100: train_loss=0.002595

      epoch  89/100: train_loss=0.002598

      epoch  90/100: train_loss=0.002599, val_loss=0.011733, IC=-0.0206

      epoch  91/100: train_loss=0.002595

      epoch  92/100: train_loss=0.002598

      epoch  93/100: train_loss=0.002600

      epoch  94/100: train_loss=0.002599

      epoch  95/100: train_loss=0.002601, val_loss=0.011751, IC=-0.0244

      epoch  96/100: train_loss=0.002594

      epoch  97/100: train_loss=0.002597

      epoch  98/100: train_loss=0.002604

      epoch  99/100: train_loss=0.002598

      epoch 100/100: train_loss=0.002591, val_loss=0.011754, IC=-0.0242

      best_ep=10, IC=+0.0660 (50.4s, 20 checkpoints)

  Fold 4: creating sequences...

    train=34,983 seq across 30 symbols
    val=5,588 seq across 30 symbols
    creating datasets...
    datasets ready
    nlinear:

      epoch   1/100: train_loss=0.152478

      epoch   2/100: train_loss=0.068150

      epoch   3/100: train_loss=0.041689

      epoch   4/100: train_loss=0.029497

      epoch   5/100: train_loss=0.022858, val_loss=0.796981, IC=-0.0456

      epoch   6/100: train_loss=0.018584

      epoch   7/100: train_loss=0.015044

      epoch   8/100: train_loss=0.012090

      epoch   9/100: train_loss=0.009930

      epoch  10/100: train_loss=0.008497, val_loss=0.148975, IC=-0.0306

      epoch  11/100: train_loss=0.007322

      epoch  12/100: train_loss=0.006290

      epoch  13/100: train_loss=0.005439

      epoch  14/100: train_loss=0.004927

      epoch  15/100: train_loss=0.004422, val_loss=0.021126, IC=-0.0098

      epoch  16/100: train_loss=0.004134

      epoch  17/100: train_loss=0.003766

      epoch  18/100: train_loss=0.003615

      epoch  19/100: train_loss=0.003528

      epoch  20/100: train_loss=0.003321, val_loss=0.004626, IC=+0.0168

      epoch  21/100: train_loss=0.003231

      epoch  22/100: train_loss=0.003130

      epoch  23/100: train_loss=0.003055

      epoch  24/100: train_loss=0.003027

      epoch  25/100: train_loss=0.003016, val_loss=0.002300, IC=+0.0693

      epoch  26/100: train_loss=0.002983

      epoch  27/100: train_loss=0.002960

      epoch  28/100: train_loss=0.002932

      epoch  29/100: train_loss=0.002872

      epoch  30/100: train_loss=0.002901, val_loss=0.002139, IC=+0.1046

      epoch  31/100: train_loss=0.002859

      epoch  32/100: train_loss=0.002829

      epoch  33/100: train_loss=0.002827

      epoch  34/100: train_loss=0.002839

      epoch  35/100: train_loss=0.002826, val_loss=0.002153, IC=+0.1052

      epoch  36/100: train_loss=0.002854

      epoch  37/100: train_loss=0.002861

      epoch  38/100: train_loss=0.002812

      epoch  39/100: train_loss=0.002810

      epoch  40/100: train_loss=0.002906, val_loss=0.002176, IC=+0.0816

      epoch  41/100: train_loss=0.002838

      epoch  42/100: train_loss=0.002869

      epoch  43/100: train_loss=0.002794

      epoch  44/100: train_loss=0.002811

      epoch  45/100: train_loss=0.002809, val_loss=0.002225, IC=+0.0933

      epoch  46/100: train_loss=0.002821

      epoch  47/100: train_loss=0.002842

      epoch  48/100: train_loss=0.002931

      epoch  49/100: train_loss=0.002836

      epoch  50/100: train_loss=0.002848, val_loss=0.002186, IC=+0.0841

      epoch  51/100: train_loss=0.002871

      epoch  52/100: train_loss=0.002839

      epoch  53/100: train_loss=0.002794

      epoch  54/100: train_loss=0.002861

      epoch  55/100: train_loss=0.002804, val_loss=0.002132, IC=+0.0991

      epoch  56/100: train_loss=0.002828

      epoch  57/100: train_loss=0.002857

      epoch  58/100: train_loss=0.002817

      epoch  59/100: train_loss=0.002850

      epoch  60/100: train_loss=0.002841, val_loss=0.002208, IC=+0.0836

      epoch  61/100: train_loss=0.002862

      epoch  62/100: train_loss=0.002794

      epoch  63/100: train_loss=0.002821

      epoch  64/100: train_loss=0.002806

      epoch  65/100: train_loss=0.002880, val_loss=0.002271, IC=+0.0974

      epoch  66/100: train_loss=0.002844

      epoch  67/100: train_loss=0.002765

      epoch  68/100: train_loss=0.002923

      epoch  69/100: train_loss=0.002830

      epoch  70/100: train_loss=0.002851, val_loss=0.002211, IC=+0.0923

      epoch  71/100: train_loss=0.002787

      epoch  72/100: train_loss=0.002816

      epoch  73/100: train_loss=0.002800

      epoch  74/100: train_loss=0.002865

      epoch  75/100: train_loss=0.002784, val_loss=0.002225, IC=+0.0957

      epoch  76/100: train_loss=0.002825

      epoch  77/100: train_loss=0.002826

      epoch  78/100: train_loss=0.002866

      epoch  79/100: train_loss=0.002867

      epoch  80/100: train_loss=0.002828, val_loss=0.002235, IC=+0.0964

      epoch  81/100: train_loss=0.002836

      epoch  82/100: train_loss=0.002789

      epoch  83/100: train_loss=0.002851

      epoch  84/100: train_loss=0.002823

      epoch  85/100: train_loss=0.002841, val_loss=0.002236, IC=+0.0966

      epoch  86/100: train_loss=0.002861

      epoch  87/100: train_loss=0.002813

      epoch  88/100: train_loss=0.002835

      epoch  89/100: train_loss=0.002871

      epoch  90/100: train_loss=0.002842, val_loss=0.002228, IC=+0.0974

      epoch  91/100: train_loss=0.002793

      epoch  92/100: train_loss=0.002793

      epoch  93/100: train_loss=0.002808

      epoch  94/100: train_loss=0.002840

      epoch  95/100: train_loss=0.002865, val_loss=0.002228, IC=+0.0967

      epoch  96/100: train_loss=0.002803

      epoch  97/100: train_loss=0.002896

      epoch  98/100: train_loss=0.002825

      epoch  99/100: train_loss=0.002845

      epoch 100/100: train_loss=0.002822, val_loss=0.002228, IC=+0.0965

      best_ep=35, IC=+0.1052 (48.8s, 20 checkpoints)

  nlinear: best_epoch=5, IC=+0.0019 (268.5s)

  Best: nlinear @ epoch 5 (IC=+0.0019)
  Saved to ~/ml4t/public-s6-cme_futures/case_studies/cme_futures/run_log/training/84b92874b08c/diagnostics

Fold-major CV: 5 folds × 1 configs × 60 lookback

  Fold 0: creating sequences...

    train=42,656 seq across 30 symbols
    val=4,726 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.004573

      epoch   2/100: train_loss=0.003453

      epoch   3/100: train_loss=0.002550

      epoch   4/100: train_loss=0.001933

      epoch   5/100: train_loss=0.001566, val_loss=0.004886, IC=-0.1912

      epoch   6/100: train_loss=0.001334

      epoch   7/100: train_loss=0.001200

      epoch   8/100: train_loss=0.001109

      epoch   9/100: train_loss=0.001022

      epoch  10/100: train_loss=0.000967, val_loss=0.005567, IC=-0.2041

      epoch  11/100: train_loss=0.000911

      epoch  12/100: train_loss=0.000872

      epoch  13/100: train_loss=0.000835

      epoch  14/100: train_loss=0.000794

      epoch  15/100: train_loss=0.000773, val_loss=0.005730, IC=-0.2057

      epoch  16/100: train_loss=0.000749

      epoch  17/100: train_loss=0.000729

      epoch  18/100: train_loss=0.000679

      epoch  19/100: train_loss=0.000668

      epoch  20/100: train_loss=0.000640, val_loss=0.005708, IC=-0.1994

      epoch  21/100: train_loss=0.000633

      epoch  22/100: train_loss=0.000616

      epoch  23/100: train_loss=0.000600

      epoch  24/100: train_loss=0.000580

      epoch  25/100: train_loss=0.000579, val_loss=0.005964, IC=-0.2130

      epoch  26/100: train_loss=0.000591

      epoch  27/100: train_loss=0.000555

      epoch  28/100: train_loss=0.000541

      epoch  29/100: train_loss=0.000533

      epoch  30/100: train_loss=0.000518, val_loss=0.005820, IC=-0.2173

      epoch  31/100: train_loss=0.000513

      epoch  32/100: train_loss=0.000511

      epoch  33/100: train_loss=0.000499

      epoch  34/100: train_loss=0.000496

      epoch  35/100: train_loss=0.000488, val_loss=0.005895, IC=-0.2149

      epoch  36/100: train_loss=0.000482

      epoch  37/100: train_loss=0.000475

      epoch  38/100: train_loss=0.000481

      epoch  39/100: train_loss=0.000503

      epoch  40/100: train_loss=0.000470, val_loss=0.005689, IC=-0.1992

      epoch  41/100: train_loss=0.000460

      epoch  42/100: train_loss=0.000449

      epoch  43/100: train_loss=0.000454

      epoch  44/100: train_loss=0.000439

      epoch  45/100: train_loss=0.000440, val_loss=0.005627, IC=-0.1958

      epoch  46/100: train_loss=0.000433

      epoch  47/100: train_loss=0.000437

      epoch  48/100: train_loss=0.000425

      epoch  49/100: train_loss=0.000419

      epoch  50/100: train_loss=0.000419, val_loss=0.005779, IC=-0.1963

      epoch  51/100: train_loss=0.000416

      epoch  52/100: train_loss=0.000412

      epoch  53/100: train_loss=0.000410

      epoch  54/100: train_loss=0.000412

      epoch  55/100: train_loss=0.000409, val_loss=0.005640, IC=-0.1974

      epoch  56/100: train_loss=0.000404

      epoch  57/100: train_loss=0.000392

      epoch  58/100: train_loss=0.000393

      epoch  59/100: train_loss=0.000394

      epoch  60/100: train_loss=0.000389, val_loss=0.005732, IC=-0.1952

      epoch  61/100: train_loss=0.000384

      epoch  62/100: train_loss=0.000385

      epoch  63/100: train_loss=0.000390

      epoch  64/100: train_loss=0.000382

      epoch  65/100: train_loss=0.000379, val_loss=0.006003, IC=-0.1979

      epoch  66/100: train_loss=0.000374

      epoch  67/100: train_loss=0.000376

      epoch  68/100: train_loss=0.000370

      epoch  69/100: train_loss=0.000370

      epoch  70/100: train_loss=0.000364, val_loss=0.005956, IC=-0.1971

      epoch  71/100: train_loss=0.000365

      epoch  72/100: train_loss=0.000367

      epoch  73/100: train_loss=0.000361

      epoch  74/100: train_loss=0.000359

      epoch  75/100: train_loss=0.000361, val_loss=0.005979, IC=-0.1979

      epoch  76/100: train_loss=0.000360

      epoch  77/100: train_loss=0.000358

      epoch  78/100: train_loss=0.000357

      epoch  79/100: train_loss=0.000355

      epoch  80/100: train_loss=0.000357, val_loss=0.005980, IC=-0.1970

      epoch  81/100: train_loss=0.000355

      epoch  82/100: train_loss=0.000355

      epoch  83/100: train_loss=0.000354

      epoch  84/100: train_loss=0.000350

      epoch  85/100: train_loss=0.000352, val_loss=0.005945, IC=-0.1977

      epoch  86/100: train_loss=0.000347

      epoch  87/100: train_loss=0.000349

      epoch  88/100: train_loss=0.000351

      epoch  89/100: train_loss=0.000350

      epoch  90/100: train_loss=0.000352, val_loss=0.005981, IC=-0.1967

      epoch  91/100: train_loss=0.000349

      epoch  92/100: train_loss=0.000352

      epoch  93/100: train_loss=0.000347

      epoch  94/100: train_loss=0.000347

      epoch  95/100: train_loss=0.000351, val_loss=0.005993, IC=-0.1961

      epoch  96/100: train_loss=0.000343

      epoch  97/100: train_loss=0.000343

      epoch  98/100: train_loss=0.000346

      epoch  99/100: train_loss=0.000343

      epoch 100/100: train_loss=0.000347, val_loss=0.005987, IC=-0.1960

      best_ep=5, IC=-0.1912 (86.8s, 20 checkpoints)

  Fold 1: creating sequences...

    train=39,459 seq across 30 symbols
    val=5,740 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.004053

      epoch   2/100: train_loss=0.003093

      epoch   3/100: train_loss=0.002395

      epoch   4/100: train_loss=0.001861

      epoch   5/100: train_loss=0.001511, val_loss=0.008216, IC=+0.0630

      epoch   6/100: train_loss=0.001267

      epoch   7/100: train_loss=0.001105

      epoch   8/100: train_loss=0.001034

      epoch   9/100: train_loss=0.000926

      epoch  10/100: train_loss=0.000861, val_loss=0.008522, IC=+0.0508

      epoch  11/100: train_loss=0.000821

      epoch  12/100: train_loss=0.000754

      epoch  13/100: train_loss=0.000733

      epoch  14/100: train_loss=0.000704

      epoch  15/100: train_loss=0.000701, val_loss=0.008632, IC=+0.0461

      epoch  16/100: train_loss=0.000681

      epoch  17/100: train_loss=0.000624

      epoch  18/100: train_loss=0.000609

      epoch  19/100: train_loss=0.000587

      epoch  20/100: train_loss=0.000560, val_loss=0.008489, IC=+0.0661

      epoch  21/100: train_loss=0.000558

      epoch  22/100: train_loss=0.000551

      epoch  23/100: train_loss=0.000539

      epoch  24/100: train_loss=0.000505

      epoch  25/100: train_loss=0.000504, val_loss=0.008805, IC=+0.0462

      epoch  26/100: train_loss=0.000492

      epoch  27/100: train_loss=0.000476

      epoch  28/100: train_loss=0.000470

      epoch  29/100: train_loss=0.000459

      epoch  30/100: train_loss=0.000447, val_loss=0.008583, IC=+0.0425

      epoch  31/100: train_loss=0.000438

      epoch  32/100: train_loss=0.000442

      epoch  33/100: train_loss=0.000434

      epoch  34/100: train_loss=0.000433

      epoch  35/100: train_loss=0.000445, val_loss=0.008676, IC=+0.0455

      epoch  36/100: train_loss=0.000435

      epoch  37/100: train_loss=0.000422

      epoch  38/100: train_loss=0.000409

      epoch  39/100: train_loss=0.000397

      epoch  40/100: train_loss=0.000403, val_loss=0.008552, IC=+0.0442

      epoch  41/100: train_loss=0.000419

      epoch  42/100: train_loss=0.000397

      epoch  43/100: train_loss=0.000394

      epoch  44/100: train_loss=0.000378

      epoch  45/100: train_loss=0.000374, val_loss=0.008658, IC=+0.0402

      epoch  46/100: train_loss=0.000378

      epoch  47/100: train_loss=0.000363

      epoch  48/100: train_loss=0.000361

      epoch  49/100: train_loss=0.000356

      epoch  50/100: train_loss=0.000372, val_loss=0.008640, IC=+0.0357

      epoch  51/100: train_loss=0.000362

      epoch  52/100: train_loss=0.000349

      epoch  53/100: train_loss=0.000347

      epoch  54/100: train_loss=0.000349

      epoch  55/100: train_loss=0.000346, val_loss=0.008693, IC=+0.0340

      epoch  56/100: train_loss=0.000338

      epoch  57/100: train_loss=0.000339

      epoch  58/100: train_loss=0.000349

      epoch  59/100: train_loss=0.000338

      epoch  60/100: train_loss=0.000335, val_loss=0.008744, IC=+0.0347

      epoch  61/100: train_loss=0.000335

      epoch  62/100: train_loss=0.000326

      epoch  63/100: train_loss=0.000319

      epoch  64/100: train_loss=0.000325

      epoch  65/100: train_loss=0.000324, val_loss=0.008750, IC=+0.0257

      epoch  66/100: train_loss=0.000321

      epoch  67/100: train_loss=0.000321

      epoch  68/100: train_loss=0.000317

      epoch  69/100: train_loss=0.000326

      epoch  70/100: train_loss=0.000326, val_loss=0.008736, IC=+0.0301

      epoch  71/100: train_loss=0.000314

      epoch  72/100: train_loss=0.000312

      epoch  73/100: train_loss=0.000309

      epoch  74/100: train_loss=0.000309

      epoch  75/100: train_loss=0.000312, val_loss=0.008774, IC=+0.0281

      epoch  76/100: train_loss=0.000309

      epoch  77/100: train_loss=0.000304

      epoch  78/100: train_loss=0.000309

      epoch  79/100: train_loss=0.000301

      epoch  80/100: train_loss=0.000305, val_loss=0.008776, IC=+0.0224

      epoch  81/100: train_loss=0.000300

      epoch  82/100: train_loss=0.000306

      epoch  83/100: train_loss=0.000299

      epoch  84/100: train_loss=0.000299

      epoch  85/100: train_loss=0.000297, val_loss=0.008791, IC=+0.0233

      epoch  86/100: train_loss=0.000299

      epoch  87/100: train_loss=0.000299

      epoch  88/100: train_loss=0.000302

      epoch  89/100: train_loss=0.000299

      epoch  90/100: train_loss=0.000301, val_loss=0.008823, IC=+0.0223

      epoch  91/100: train_loss=0.000297

      epoch  92/100: train_loss=0.000298

      epoch  93/100: train_loss=0.000300

      epoch  94/100: train_loss=0.000295

      epoch  95/100: train_loss=0.000296, val_loss=0.008825, IC=+0.0216

      epoch  96/100: train_loss=0.000296

      epoch  97/100: train_loss=0.000297

      epoch  98/100: train_loss=0.000294

      epoch  99/100: train_loss=0.000296

      epoch 100/100: train_loss=0.000295, val_loss=0.008820, IC=+0.0213

      best_ep=20, IC=+0.0661 (81.1s, 20 checkpoints)

  Fold 2: creating sequences...

    train=37,637 seq across 30 symbols
    val=5,188 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.007112

      epoch   2/100: train_loss=0.003878

      epoch   3/100: train_loss=0.003346

      epoch   4/100: train_loss=0.002841

      epoch   5/100: train_loss=0.002303, val_loss=0.003767, IC=-0.0596

      epoch   6/100: train_loss=0.001876

      epoch   7/100: train_loss=0.001580

      epoch   8/100: train_loss=0.001413

      epoch   9/100: train_loss=0.001257

      epoch  10/100: train_loss=0.001118, val_loss=0.004461, IC=-0.0235

      epoch  11/100: train_loss=0.001050

      epoch  12/100: train_loss=0.000985

      epoch  13/100: train_loss=0.000928

      epoch  14/100: train_loss=0.000878

      epoch  15/100: train_loss=0.000847, val_loss=0.004643, IC=-0.0426

      epoch  16/100: train_loss=0.000790

      epoch  17/100: train_loss=0.000780

      epoch  18/100: train_loss=0.000742

      epoch  19/100: train_loss=0.000700

      epoch  20/100: train_loss=0.000682, val_loss=0.005070, IC=-0.0515

      epoch  21/100: train_loss=0.000655

      epoch  22/100: train_loss=0.000629

      epoch  23/100: train_loss=0.000622

      epoch  24/100: train_loss=0.000612

      epoch  25/100: train_loss=0.000596, val_loss=0.005211, IC=-0.0587

      epoch  26/100: train_loss=0.000578

      epoch  27/100: train_loss=0.000551

      epoch  28/100: train_loss=0.000545

      epoch  29/100: train_loss=0.000538

      epoch  30/100: train_loss=0.000526, val_loss=0.005152, IC=-0.0533

      epoch  31/100: train_loss=0.000555

      epoch  32/100: train_loss=0.000593

      epoch  33/100: train_loss=0.000535

      epoch  34/100: train_loss=0.000515

      epoch  35/100: train_loss=0.000504, val_loss=0.005098, IC=-0.0340

      epoch  36/100: train_loss=0.000486

      epoch  37/100: train_loss=0.000489

      epoch  38/100: train_loss=0.000472

      epoch  39/100: train_loss=0.000460

      epoch  40/100: train_loss=0.000452, val_loss=0.005165, IC=-0.0407

      epoch  41/100: train_loss=0.000449

      epoch  42/100: train_loss=0.000448

      epoch  43/100: train_loss=0.000445

      epoch  44/100: train_loss=0.000424

      epoch  45/100: train_loss=0.000437, val_loss=0.005293, IC=-0.0422

      epoch  46/100: train_loss=0.000426

      epoch  47/100: train_loss=0.000423

      epoch  48/100: train_loss=0.000415

      epoch  49/100: train_loss=0.000424

      epoch  50/100: train_loss=0.000402, val_loss=0.005143, IC=-0.0332

      epoch  51/100: train_loss=0.000403

      epoch  52/100: train_loss=0.000401

      epoch  53/100: train_loss=0.000397

      epoch  54/100: train_loss=0.000392

      epoch  55/100: train_loss=0.000394, val_loss=0.005246, IC=-0.0363

      epoch  56/100: train_loss=0.000389

      epoch  57/100: train_loss=0.000390

      epoch  58/100: train_loss=0.000374

      epoch  59/100: train_loss=0.000381

      epoch  60/100: train_loss=0.000381, val_loss=0.005300, IC=-0.0325

      epoch  61/100: train_loss=0.000374

      epoch  62/100: train_loss=0.000378

      epoch  63/100: train_loss=0.000376

      epoch  64/100: train_loss=0.000366

      epoch  65/100: train_loss=0.000372, val_loss=0.005344, IC=-0.0348

      epoch  66/100: train_loss=0.000369

      epoch  67/100: train_loss=0.000363

      epoch  68/100: train_loss=0.000368

      epoch  69/100: train_loss=0.000351

      epoch  70/100: train_loss=0.000359, val_loss=0.005277, IC=-0.0304

      epoch  71/100: train_loss=0.000353

      epoch  72/100: train_loss=0.000361

      epoch  73/100: train_loss=0.000353

      epoch  74/100: train_loss=0.000352

      epoch  75/100: train_loss=0.000353, val_loss=0.005304, IC=-0.0281

      epoch  76/100: train_loss=0.000350

      epoch  77/100: train_loss=0.000344

      epoch  78/100: train_loss=0.000346

      epoch  79/100: train_loss=0.000346

      epoch  80/100: train_loss=0.000344, val_loss=0.005321, IC=-0.0286

      epoch  81/100: train_loss=0.000346

      epoch  82/100: train_loss=0.000344

      epoch  83/100: train_loss=0.000345

      epoch  84/100: train_loss=0.000339

      epoch  85/100: train_loss=0.000340, val_loss=0.005319, IC=-0.0307

      epoch  86/100: train_loss=0.000342

      epoch  87/100: train_loss=0.000339

      epoch  88/100: train_loss=0.000331

      epoch  89/100: train_loss=0.000338

      epoch  90/100: train_loss=0.000334, val_loss=0.005348, IC=-0.0308

      epoch  91/100: train_loss=0.000343

      epoch  92/100: train_loss=0.000338

      epoch  93/100: train_loss=0.000336

      epoch  94/100: train_loss=0.000335

      epoch  95/100: train_loss=0.000351, val_loss=0.005338, IC=-0.0291

      epoch  96/100: train_loss=0.000334

      epoch  97/100: train_loss=0.000336

      epoch  98/100: train_loss=0.000341

      epoch  99/100: train_loss=0.000338

      epoch 100/100: train_loss=0.000334, val_loss=0.005338, IC=-0.0296

      best_ep=10, IC=-0.0235 (77.2s, 20 checkpoints)

  Fold 3: creating sequences...

    train=36,286 seq across 30 symbols
    val=5,732 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.003448

      epoch   2/100: train_loss=0.002455

      epoch   3/100: train_loss=0.002180

      epoch   4/100: train_loss=0.001828

      epoch   5/100: train_loss=0.001519, val_loss=0.015469, IC=-0.0926

      epoch   6/100: train_loss=0.001249

      epoch   7/100: train_loss=0.001042

      epoch   8/100: train_loss=0.000914

      epoch   9/100: train_loss=0.000814

      epoch  10/100: train_loss=0.000735, val_loss=0.016099, IC=-0.0534

      epoch  11/100: train_loss=0.000675

      epoch  12/100: train_loss=0.000631

      epoch  13/100: train_loss=0.000593

      epoch  14/100: train_loss=0.000554

      epoch  15/100: train_loss=0.000523, val_loss=0.015616, IC=-0.0750

      epoch  16/100: train_loss=0.000494

      epoch  17/100: train_loss=0.000474

      epoch  18/100: train_loss=0.000444

      epoch  19/100: train_loss=0.000429

      epoch  20/100: train_loss=0.000420, val_loss=0.015523, IC=-0.0802

      epoch  21/100: train_loss=0.000410

      epoch  22/100: train_loss=0.000398

      epoch  23/100: train_loss=0.000383

      epoch  24/100: train_loss=0.000367

      epoch  25/100: train_loss=0.000357, val_loss=0.014946, IC=-0.0572

      epoch  26/100: train_loss=0.000349

      epoch  27/100: train_loss=0.000350

      epoch  28/100: train_loss=0.000340

      epoch  29/100: train_loss=0.000331

      epoch  30/100: train_loss=0.000318, val_loss=0.014966, IC=-0.0699

      epoch  31/100: train_loss=0.000316

      epoch  32/100: train_loss=0.000307

      epoch  33/100: train_loss=0.000305

      epoch  34/100: train_loss=0.000303

      epoch  35/100: train_loss=0.000298, val_loss=0.014862, IC=-0.0602

      epoch  36/100: train_loss=0.000294

      epoch  37/100: train_loss=0.000289

      epoch  38/100: train_loss=0.000286

      epoch  39/100: train_loss=0.000283

      epoch  40/100: train_loss=0.000282, val_loss=0.014850, IC=-0.0623

      epoch  41/100: train_loss=0.000275

      epoch  42/100: train_loss=0.000272

      epoch  43/100: train_loss=0.000270

      epoch  44/100: train_loss=0.000269

      epoch  45/100: train_loss=0.000268, val_loss=0.014791, IC=-0.0591

      epoch  46/100: train_loss=0.000262

      epoch  47/100: train_loss=0.000256

      epoch  48/100: train_loss=0.000254

      epoch  49/100: train_loss=0.000251

      epoch  50/100: train_loss=0.000252, val_loss=0.015078, IC=-0.0686

      epoch  51/100: train_loss=0.000248

      epoch  52/100: train_loss=0.000250

      epoch  53/100: train_loss=0.000248

      epoch  54/100: train_loss=0.000244

      epoch  55/100: train_loss=0.000242, val_loss=0.015153, IC=-0.0890

      epoch  56/100: train_loss=0.000240

      epoch  57/100: train_loss=0.000239

      epoch  58/100: train_loss=0.000238

      epoch  59/100: train_loss=0.000236

      epoch  60/100: train_loss=0.000234, val_loss=0.014956, IC=-0.0778

      epoch  61/100: train_loss=0.000233

      epoch  62/100: train_loss=0.000232

      epoch  63/100: train_loss=0.000228

      epoch  64/100: train_loss=0.000229

      epoch  65/100: train_loss=0.000228, val_loss=0.015091, IC=-0.0903

      epoch  66/100: train_loss=0.000230

      epoch  67/100: train_loss=0.000229

      epoch  68/100: train_loss=0.000226

      epoch  69/100: train_loss=0.000227

      epoch  70/100: train_loss=0.000223, val_loss=0.014905, IC=-0.0774

      epoch  71/100: train_loss=0.000223

      epoch  72/100: train_loss=0.000223

      epoch  73/100: train_loss=0.000222

      epoch  74/100: train_loss=0.000219

      epoch  75/100: train_loss=0.000218, val_loss=0.015032, IC=-0.0794

      epoch  76/100: train_loss=0.000219

      epoch  77/100: train_loss=0.000218

      epoch  78/100: train_loss=0.000216

      epoch  79/100: train_loss=0.000216

      epoch  80/100: train_loss=0.000216, val_loss=0.015061, IC=-0.0830

      epoch  81/100: train_loss=0.000215

      epoch  82/100: train_loss=0.000214

      epoch  83/100: train_loss=0.000217

      epoch  84/100: train_loss=0.000212

      epoch  85/100: train_loss=0.000214, val_loss=0.015024, IC=-0.0808

      epoch  86/100: train_loss=0.000213

      epoch  87/100: train_loss=0.000215

      epoch  88/100: train_loss=0.000215

      epoch  89/100: train_loss=0.000211

      epoch  90/100: train_loss=0.000213, val_loss=0.015088, IC=-0.0833

      epoch  91/100: train_loss=0.000213

      epoch  92/100: train_loss=0.000213

      epoch  93/100: train_loss=0.000211

      epoch  94/100: train_loss=0.000210

      epoch  95/100: train_loss=0.000212, val_loss=0.015096, IC=-0.0830

      epoch  96/100: train_loss=0.000210

      epoch  97/100: train_loss=0.000212

      epoch  98/100: train_loss=0.000211

      epoch  99/100: train_loss=0.000212

      epoch 100/100: train_loss=0.000214, val_loss=0.015098, IC=-0.0834

      best_ep=10, IC=-0.0534 (74.3s, 20 checkpoints)

  Fold 4: creating sequences...

    train=34,983 seq across 30 symbols
    val=5,588 seq across 30 symbols
    creating datasets...
    datasets ready
    lstm_h64:

      epoch   1/100: train_loss=0.002973

      epoch   2/100: train_loss=0.002421

      epoch   3/100: train_loss=0.001982

      epoch   4/100: train_loss=0.001627

      epoch   5/100: train_loss=0.001339, val_loss=0.017780, IC=-0.0608

      epoch   6/100: train_loss=0.001114

      epoch   7/100: train_loss=0.001003

      epoch   8/100: train_loss=0.000927

      epoch   9/100: train_loss=0.000831

      epoch  10/100: train_loss=0.000753, val_loss=0.021370, IC=-0.0765

      epoch  11/100: train_loss=0.000714

      epoch  12/100: train_loss=0.000690

      epoch  13/100: train_loss=0.000651

      epoch  14/100: train_loss=0.000615

      epoch  15/100: train_loss=0.000588, val_loss=0.019571, IC=-0.0724

      epoch  16/100: train_loss=0.000558

      epoch  17/100: train_loss=0.000529

      epoch  18/100: train_loss=0.000509

      epoch  19/100: train_loss=0.000492

      epoch  20/100: train_loss=0.000474, val_loss=0.017595, IC=-0.0691

      epoch  21/100: train_loss=0.000464

      epoch  22/100: train_loss=0.000454

      epoch  23/100: train_loss=0.000442

      epoch  24/100: train_loss=0.000438

      epoch  25/100: train_loss=0.000431, val_loss=0.017138, IC=-0.0650

      epoch  26/100: train_loss=0.000405

      epoch  27/100: train_loss=0.000398

      epoch  28/100: train_loss=0.000385

      epoch  29/100: train_loss=0.000381

      epoch  30/100: train_loss=0.000371, val_loss=0.015671, IC=-0.0678

      epoch  31/100: train_loss=0.000360

      epoch  32/100: train_loss=0.000363

      epoch  33/100: train_loss=0.000364

      epoch  34/100: train_loss=0.000365

      epoch  35/100: train_loss=0.000349, val_loss=0.014825, IC=-0.0641

      epoch  36/100: train_loss=0.000335

      epoch  37/100: train_loss=0.000344

      epoch  38/100: train_loss=0.000335

      epoch  39/100: train_loss=0.000338

      epoch  40/100: train_loss=0.000333, val_loss=0.014346, IC=-0.0694

      epoch  41/100: train_loss=0.000330

      epoch  42/100: train_loss=0.000319

      epoch  43/100: train_loss=0.000313

      epoch  44/100: train_loss=0.000317

      epoch  45/100: train_loss=0.000322, val_loss=0.013669, IC=-0.0716

      epoch  46/100: train_loss=0.000310

      epoch  47/100: train_loss=0.000303

      epoch  48/100: train_loss=0.000309

      epoch  49/100: train_loss=0.000296

      epoch  50/100: train_loss=0.000296, val_loss=0.013383, IC=-0.0735

      epoch  51/100: train_loss=0.000290

      epoch  52/100: train_loss=0.000290

      epoch  53/100: train_loss=0.000290

      epoch  54/100: train_loss=0.000284

      epoch  55/100: train_loss=0.000281, val_loss=0.012100, IC=-0.0692

      epoch  56/100: train_loss=0.000281

      epoch  57/100: train_loss=0.000278

      epoch  58/100: train_loss=0.000276

      epoch  59/100: train_loss=0.000271

      epoch  60/100: train_loss=0.000278, val_loss=0.012722, IC=-0.0729

      epoch  61/100: train_loss=0.000273

      epoch  62/100: train_loss=0.000271

      epoch  63/100: train_loss=0.000267

      epoch  64/100: train_loss=0.000268

      epoch  65/100: train_loss=0.000273, val_loss=0.012376, IC=-0.0730

      epoch  66/100: train_loss=0.000264

      epoch  67/100: train_loss=0.000262

      epoch  68/100: train_loss=0.000264

      epoch  69/100: train_loss=0.000255

      epoch  70/100: train_loss=0.000258, val_loss=0.012421, IC=-0.0695

      epoch  71/100: train_loss=0.000262

      epoch  72/100: train_loss=0.000259

      epoch  73/100: train_loss=0.000258

      epoch  74/100: train_loss=0.000255

      epoch  75/100: train_loss=0.000253, val_loss=0.011953, IC=-0.0694

      epoch  76/100: train_loss=0.000251

      epoch  77/100: train_loss=0.000252

      epoch  78/100: train_loss=0.000258

      epoch  79/100: train_loss=0.000249

      epoch  80/100: train_loss=0.000249, val_loss=0.012264, IC=-0.0692

      epoch  81/100: train_loss=0.000249

      epoch  82/100: train_loss=0.000246

      epoch  83/100: train_loss=0.000247

      epoch  84/100: train_loss=0.000248

      epoch  85/100: train_loss=0.000246, val_loss=0.012127, IC=-0.0691

      epoch  86/100: train_loss=0.000245

      epoch  87/100: train_loss=0.000243

      epoch  88/100: train_loss=0.000246

      epoch  89/100: train_loss=0.000244

      epoch  90/100: train_loss=0.000246, val_loss=0.012158, IC=-0.0700

      epoch  91/100: train_loss=0.000240

      epoch  92/100: train_loss=0.000245

      epoch  93/100: train_loss=0.000250

      epoch  94/100: train_loss=0.000245

      epoch  95/100: train_loss=0.000242, val_loss=0.012211, IC=-0.0696

      epoch  96/100: train_loss=0.000241

      epoch  97/100: train_loss=0.000251

      epoch  98/100: train_loss=0.000243

      epoch  99/100: train_loss=0.000243

      epoch 100/100: train_loss=0.000246, val_loss=0.012204, IC=-0.0695

      best_ep=5, IC=-0.0608 (87.6s, 20 checkpoints)

  lstm_h64: best_epoch=10, IC=-0.0590 (407.1s)

  Best: lstm_h64 @ epoch 10 (IC=-0.0590)
  Saved to ~/ml4t/public-s6-cme_futures/case_studies/cme_futures/run_log/training/d6443432aeea/diagnostics

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("label", "config_name", "checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("sequence execution returned a partial prediction")
catalog

shape: (80, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ d6443432a ┆ 3f30b41f6 │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ eea       ┆ 846       │
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ d6443432a ┆ 549e87d85 │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ eea       ┆ afc       │
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ d6443432a ┆ eb80870cf │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ eea       ┆ 954       │
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ d6443432a ┆ 546b7b03a │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ eea       ┆ 0ea       │
│ deep_lear ┆ fwd_ret_2 ┆ lstm_h64  ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ d6443432a ┆ 75482b8d1 │
│ ning      ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ eea       ┆ 946       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 84a4e0f36 ┆ b09b78938 │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 909       ┆ bca       │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 84a4e0f36 ┆ b530eb7c1 │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 909       ┆ 3a7       │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 84a4e0f36 ┆ 1ae720566 │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 909       ┆ 828       │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 84a4e0f36 ┆ 917d79469 │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 909       ┆ 077       │
│ deep_lear ┆ fwd_ret_5 ┆ nlinear   ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 84a4e0f36 ┆ 20949c0aa │
│ ning      ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 909       ┆ c47       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘