# CME Futures: Principal-Component Factors

PCA compresses the point-in-time feature panel into fold-scoped components. The transformer fits
on training rows only, and the saved fitted state is reused to transform that fold's validation
rows. Both return horizons are declared explicitly.

This notebook publishes predictions and fitted-state lineage. `13_backtest` applies the common
validation-Sharpe selection rule.

Prerequisites: `03_financial_features`, `04_model_based_features`, and `05_evaluation`.

In [1]:
"""Fit the declared CME futures PCA factor population."""

import polars as pl

from case_studies.cme_futures.research_workflow import (
    ALL_LABELS,
    model_request_catalog,
    open_study,
    product_universe_table,
    resolve_model_requests,
    resolved_model_plan,
    run_official_model_catalog,
    run_resolved_model_requests,
)

In [2]:
EXECUTION_TIER = "canonical"
WORKSPACE: str | None = None
PREVIEW_REDUCTIONS: dict = {}

## Declared requests

Both return horizons use the named PCA configuration. The resolved plan shows the eligible rows,
folds, feature count, checkpoint schedule, and identity before fitting begins.

In [3]:
study = open_study(execution_tier=EXECUTION_TIER, workspace=WORKSPACE)
requests = model_request_catalog(
    "latent_factors",
    labels=ALL_LABELS,
    config_names=("pca",),
)
resolved = resolve_model_requests(
    study,
    requests,
    execution_tier=EXECUTION_TIER,
    preview_reductions=PREVIEW_REDUCTIONS,
)
universe = product_universe_table()
universe

shape: (30, 4)
┌─────────────┬─────────┬──────────────────────────┬─────────────────┐
│ sector      ┆ product ┆ expiry_rule              ┆ contract_months │
│ ---         ┆ ---     ┆ ---                      ┆ ---             │
│ str         ┆ str     ┆ str                      ┆ str             │
╞═════════════╪═════════╪══════════════════════════╪═════════════════╡
│ agriculture ┆ ZC      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ agriculture ┆ ZL      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZM      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,V,Z │
│ agriculture ┆ ZS      ┆ business_day_before_15th ┆ F,H,K,N,Q,U,X   │
│ agriculture ┆ ZW      ┆ business_day_before_15th ┆ H,K,N,U,Z       │
│ …           ┆ …       ┆ …                        ┆ …               │
│ metals      ┆ SI      ┆ 3rd_last_business_day    ┆ H,K,N,U,Z       │
│ treasuries  ┆ ZB      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZF      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZN      ┆ last_business_day        ┆ H,M,U,Z         │
│ treasuries  ┆ ZT      ┆ last_business_day        ┆ H,M,U,Z         │
└─────────────┴─────────┴──────────────────────────┴─────────────────┘

In [4]:
resolved_model_plan(resolved)

shape: (2, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ family    ┆ label     ┆ config_na ┆ task      ┆ … ┆ validatio ┆ checkpoin ┆ execution ┆ training │
│ ---       ┆ ---       ┆ me        ┆ ---       ┆   ┆ n_end     ┆ ts        ┆ _tier     ┆ _hash    │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ latent_fa ┆ fwd_ret_2 ┆ pca       ┆ regressio ┆ … ┆ 2023-11-2 ┆ 1         ┆ canonical ┆ 164ce7df │
│ ctors     ┆ 1d        ┆           ┆ n         ┆   ┆ 9         ┆           ┆           ┆ 51e5     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
│ latent_fa ┆ fwd_ret_5 ┆ pca       ┆ regressio ┆ … ┆ 2023-12-2 ┆ 1         ┆ canonical ┆ 4a8088d4 │
│ ctors     ┆ d         ┆           ┆ n         ┆   ┆ 1         ┆           ┆           ┆ 7213     │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Execute and validate

The shared latent-factor runner fits PCA inside each training fold, persists the transformer, and
requires the complete validation key set before publication.

In [5]:
if EXECUTION_TIER == "canonical":
    execution, population = run_official_model_catalog(
        study,
        requests,
        population_name="cme-pca-validation-v1",
        resolved_requests=resolved,
    )
else:
    if WORKSPACE is None or not PREVIEW_REDUCTIONS:
        raise ValueError("preview execution requires WORKSPACE and PREVIEW_REDUCTIONS")
    execution = run_resolved_model_requests(study, resolved)
    population = None

Latent factor CV: 1 models × 5 folds
Log file: case_studies/cme_futures/run_log/training/4a8088d47213/.models.05e4de49528745c0ab4f2b34c62080e7.tmp/latent_factors.log
Scoring: dates=all cadence=- step=1 checkpoint_selection=fixed reporting_epoch=0
  pca (K=5):
    Fold 0: persistent train=2059, val=253, max_N=30

      fold 0: reported_epoch=0, IC=-0.0894, 0.1s
    Fold 1: persistent train=2059, val=258, max_N=30

      fold 1: reported_epoch=0, IC=-0.0370, 0.0s
    Fold 2: persistent train=2059, val=258, max_N=29

      fold 2: reported_epoch=0, IC=-0.0066, 0.0s
    Fold 3: persistent train=2059, val=258, max_N=29

      fold 3: reported_epoch=0, IC=-0.0356, 0.0s
    Fold 4: persistent train=2039, val=258, max_N=29

      fold 4: reported_epoch=0, IC=+0.0526, 0.1s
    -> best epoch=0, IC=-0.0232 (1.2s)

  Best: pca (IC=-0.0232)

Latent factor CV: 1 models × 5 folds
Log file: case_studies/cme_futures/run_log/training/164ce7df51e5/.models.3bcd3424ba9c40eba31ff489ddb90a04.tmp/latent_factors.log
Scoring: dates=all cadence=- step=1 checkpoint_selection=fixed reporting_epoch=0
  pca (K=5):
    Fold 0: persistent train=2043, val=237, max_N=30

      fold 0: reported_epoch=0, IC=+0.1517, 0.0s
    Fold 1: persistent train=2043, val=258, max_N=30

      fold 1: reported_epoch=0, IC=-0.0926, 0.0s
    Fold 2: persistent train=2043, val=258, max_N=29

      fold 2: reported_epoch=0, IC=-0.1139, 0.0s
    Fold 3: persistent train=2043, val=258, max_N=29

      fold 3: reported_epoch=0, IC=-0.1118, 0.0s
    Fold 4: persistent train=2022, val=258, max_N=29

      fold 4: reported_epoch=0, IC=+0.1590, 0.0s
    -> best epoch=0, IC=-0.0015 (1.2s)

  Best: pca (IC=-0.0015)

In [6]:
catalog = execution.catalog_rows.select(
    "family",
    "label",
    "config_name",
    "checkpoint_kind",
    "checkpoint_value",
    "execution_tier",
    "complete",
    "training_hash",
    "prediction_hash",
).sort("label", "checkpoint_value")
if catalog.filter(~pl.col("complete")).height:
    raise RuntimeError("PCA execution returned a partial prediction")
catalog

shape: (2, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ family    ┆ label     ┆ config_na ┆ checkpoin ┆ … ┆ execution ┆ complete ┆ training_ ┆ predictio │
│ ---       ┆ ---       ┆ me        ┆ t_kind    ┆   ┆ _tier     ┆ ---      ┆ hash      ┆ n_hash    │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ bool     ┆ ---       ┆ ---       │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ latent_fa ┆ fwd_ret_2 ┆ pca       ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 164ce7df5 ┆ 863984af3 │
│ ctors     ┆ 1d        ┆           ┆           ┆   ┆           ┆          ┆ 1e5       ┆ db2       │
│ latent_fa ┆ fwd_ret_5 ┆ pca       ┆ epoch     ┆ … ┆ canonical ┆ true     ┆ 4a8088d47 ┆ 187857c9b │
│ ctors     ┆ d         ┆           ┆           ┆   ┆           ┆          ┆ 213       ┆ 69d       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘